### ISSUE TITLE
_p9k_cache_get: bad math expression on startup

### ISSUE THREAD

**Issue by gregf** [romkatv/powerlevel10k#1]
After enabling your version of the prompt I get the following error on startup of my shell. It never returns a prompt after.

```
 _p9k_cache_get:1: bad math expression: operator expected atprompt_use...'
_p9k_cache_get:1: bad math expression: operator expected at 1 0 0' 
```

**Comment by gregf** [comment]
I'm loading it using zplug like so.

```
zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme
```

**Comment by romkatv** [comment]
Interesting. Please give me a bit more info about your environment.

- ZSH version.
- OS.
- Does the original Powerlevel9k work for you?

You aren't sourcing Powerlevel9k together with Powerlevel10k?

**Comment by romkatv** [comment]
Also, could check if it works if you manually source powerlevel10k/powerlevel10k.zsh-theme ?

**Comment by robobenklein** [comment]
Got a similar issue running in docker image `robobenklein/home`:
![image](https://user-images.githubusercontent.com/5423266/53688033-5fa38f80-3d0b-11e9-82df-66ae6597cb86.png)

**Comment by romkatv** [comment]
@robobenklein Could check if it works if you manually source powerlevel10k/powerlevel10k.zsh-theme ? It would help me to know whether it's something specific to zplug, which I don't use but can install if necessary to debug this.

**Comment by robobenklein** [comment]
I'm using zplugin ( https://github.com/zdharma/zplugin ) actually, zplg is just an alias, sorry.

Cloning the repo and doing source ./.zsh works.

Reason I put my configs in a docker container is exactly for reproduction issues like this...

Tested with:
```
docker run --rm --env ZSH_THEME=p9k -it robobenklein/home:latest zsh -i
```

**Comment by romkatv** [comment]
@robobenklein Thanks! I'll dig into it.

**Comment by romkatv** [comment]
@robobenklein This should be fixed now. I have also verified that gitstatus work with your setup.

```zsh
zplg load romkatv/gitstatus
zplg load romkatv/powerlevel10k
```

Enjoy fast prompt!

**Comment by romkatv** [comment]
@gregf Please try again and let me know if it works.

**Comment by robobenklein** [comment]
Fix confirmed! Thanks

**Comment by romkatv** [comment]
My pleasure.
