### ISSUE TITLE
Typing 'terraform' displays Azure context

### ISSUE THREAD

**Issue by argamanza** [romkatv/powerlevel10k#1000]
I just noticed that when typing "`terraform`" on the terminal, the prompt segment of the Azure context shows.

I love this functionality of prompt segment showing only when relevant, like when the Google Cloud context shows when I type "gcloud" etc., but as someone who works with multiple contexts in multiple clouds, the Azure context segment isn't relevant all the time I use `terraform`.

Here's a demonstration of this bug:
1. Desired functionality - show Google Cloud and Azure contexts when starting a command with the relevant CLI tool:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9576019/92489600-9f98dc00-f1f8-11ea-8d83-1fa30670a35c.gif)

2. Bug - shows Azure context when starting a `terraform` command:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/9576019/92489671-b3444280-f1f8-11ea-820b-5bd24eed2236.gif)

3. Even worse - when in a Terraform directory, I already have a terraform workspace prompt, and it still shows the Azure context:
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/9576019/92489882-f43c5700-f1f8-11ea-8ec2-afcfcdb02b82.gif)

**Comment by romkatv** [comment]
Default settings are not ideal for everyone. Apparently they aren’t ideal for you, so you’ll need to change them. See https://github.com/romkatv/powerlevel10k#why-some-prompt-segments-appear-and-disappear-as-im-typing.

**Comment by argamanza** [comment]
@romkatv I'm sorry but after another look at the documentation, and I did read it several times, I still have no clue how it's supposed to behave like that, the `terraform` command should only show prompts relevant to Terraform, and while I would love to see the Azure context information displayed while I'm working on Terraform scripts that will interact with infrastructure on Azure, in the examples I gave and the GIFs the Azure context segment shows while I'm in a terraform directory that interacts with Google Cloud...

Again, as I said -
>  I love this functionality of prompt segment showing only when relevant...

It looked to me like a bug you can only solve by changing the code itself, not by just additional configuration.

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and search for `POWERLEVEL9K_AZURE_SHOW_ON_COMMAND`. Remove `terraform` from the value of this parameter. Now `azure` prompt segment won't be shown when you are typing `terraform` on the command line.

Is that what you want? If not, please explain what you want.

**Comment by argamanza** [comment]
@romkatv Simply display the relevant context, when the terraform script has an Azure provider - show Azure context, when it's a GCP provider - Google Cloud context etc.

**Comment by romkatv** [comment]
How can I figure out which provider does the terraform script have?

**Comment by argamanza** [comment]
@romkatv I have forked the project to find a way myself, the most obvious way is to search the terraform scripts for mentioned provider and show the appropriate cloud context, but that's just over-complicating things.

Anyway I'm trying to figure a way to at least prevent the mentioned bug (showing Azure context unnecessarily).

**Comment by romkatv** [comment]
In case this wasn’t clear, what you described is not a bug. You want an extra feature and you mistakenly believe that it has been implemented. It has not been.

**Comment by argamanza** [comment]
You're right, calling it a bug is technically wrong.
As I said I'm trying to figure out a way to achieve the functionality I'm looking for.
Thanks!
