### ISSUE TITLE
Show gitlab segment in a different color when in dirty state

### ISSUE THREAD

**Issue by shikhanshu** [romkatv/powerlevel10k#1003]
![image](https://user-images.githubusercontent.com/31578/92543559-a4618e00-f200-11ea-8fa1-4fc56ae757d8.png)
Can the git segment be shown in a non-green color when there are untracked files, or the local repo is diverged from remote?

**Comment by romkatv** [comment]
> Can the git segment be shown in a non-green color when there are untracked files

Yes. Open `~/.p10k.zsh` and find this line: https://github.com/romkatv/powerlevel10k/blob/12cef820770a5067b16bb31dfe2f5078e1f88266/config/p10k-rainbow.zsh#L338

Uncomment it and set the value of `POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND` to whatever you like.

> ... or the local repo is diverged from remote?

There is no parameter for this.

**Comment by maojj** [comment]
BTW, you can change the foreground by add one line in `~/.p10k.zsh`:   (change to red for example) 
`  typeset -g POWERLEVEL9K_VCS_{MODIFIED,STAGED,UNSTAGED,UNTRACKED}_FOREGROUND=$red`

result(dirty and  clean):
![image](https://user-images.githubusercontent.com/1456741/148877583-383d9f73-855c-430c-8d53-e2911257dc69.png)
