### ISSUE TITLE
How to display ^C on keyboard interrupt in the prompt?

### ISSUE THREAD

**Issue by vivienm** [romkatv/powerlevel10k#1004]
I often use ctrl-C to "abort" a command being typed and I'd like to display `^C` as Bash does. That way, I can easily see an instruction was not executed when browsing through the terminal history:

```shell
$ rm -rf /^C  # phew!
$ sudo rm -rf /tmp/cache/whatever
```

I used to mimic this behavior in Zsh with a trap:

```shell
TRAPINT() {
  print -n "^C"
  return $(( 128 + $1 ))
}
```

But this does not seem to work anymore when using Powerlevel10k (maybe because of [this](https://github.com/romkatv/powerlevel10k/blob/54d40b924c491a6510c44391dccac05fe78a7310/internal/p10k.zsh#L6654-L6667)?). Is there a way to retrieve this behavior?

PS: Thanks for your work on Powerline10k, it's a very nice project!

**Comment by romkatv** [comment]
How did you configure your terminal/zsh/tty to *not* output `^C` on <kbd>Ctrl+C</kbd>? If I run `sleep 10` and hit <kbd>Ctrl+C</kbd>, I get `^C` printed out. If I add a trap similar to the one you've posted, I get `^C` printed twice.

**Comment by romkatv** [comment]
Oh, do you mean you hit <kbd>Ctrl+C</kbd> in order to clear the command line? In this case I would recommend not doing it. It's generally a bad idea to send `SIGINT` to the shell as it can arrive in the middle of non-atomic computation and hose your session. Use something like this instead:

```zsh
bindkey '^U' kill-buffer
```

Then use <kbd>Ctrl+U</kbd> to clear the command line.

**Comment by vivienm** [comment]
> Oh, do you mean you hit Ctrl+C in order to clear the command line?

Yes, exactly. Sorry if I was not clear before.

> In this case I would recommend not doing it. It's generally a bad idea to send `SIGINT` to the shell as it can arrive in the middle of a non-atomic computation and hose your session. Use something like this instead:
> 
> ```shell
> bindkey '^U' kill-buffer
> ```
> 
> Then use Ctrl+U to clear the command line.

Good to know. Thanks!
