### ISSUE TITLE
Change Text font

### ISSUE THREAD

**Issue by mhasadi78** [romkatv/powerlevel10k#1006]
Hi
I installed the recommended (Meslo LGS NF) fonts, everything is really fine. One minor problem though, I want to all texts including commands and outputs shown in Fira Code Font. But when you change the font of your terminal emulator (Konsole in my case), it force everything to use that font. Is there a way to make prompt uses Meslo fonts but not affect other texts?

**Comment by romkatv** [comment]
Konsole can use only one font.
