### ISSUE TITLE
kube ps1 + p10k

### ISSUE THREAD

**Issue by gAmUssA** [romkatv/powerlevel10k#1008]
hi team

Could you suggest how to properly integrate [kube ps1](https://github.com/jonmosco/kube-ps1) and p10k?
Appending to the prompt doesn't seem to work.
Thank you

**Comment by romkatv** [comment]
You don’t need to use kube ps1 when using powerlevel10k. Search for `kubecontext` in `~/.p10k.zsh` to find relevant parameters and set them to your liking.

**Comment by gAmUssA** [comment]
Thanks for your response. I would like to turn this on and off (the same way I did `kube on` and `kube off`).
Could you recommend the way to translate that experience here?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#why-some-prompt-segments-appear-and-disappear-as-im-typing

**Comment by romkatv** [comment]
Closing because the reporter has disappeared.

**Comment by gAmUssA** [comment]
I didn't 😂
Yeah, your suggestion worked for me.
Thank you

**Comment by romkatv** [comment]
Thanks for the confirmation.

**Comment by jsarkar** [comment]
@romkatv I am having same issue. Could you please point me to a doc, how to configure ps1 like experience while using powerlevel10k?

**Comment by jsarkar** [comment]
I figured. Just for future reference, here is the [doc](https://www.reddit.com/r/zsh/comments/ep6987/new_powerlevel10k_feature_show_on_command/?rdt=47012)

**Comment by romkatv** [comment]
There is no doc. Please see my first comment on this issue.

**Comment by parisni** [comment]
In case you wan't the kube-ps1 colors:
```
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='%F{red}${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}%f:%F{cyan}${P9K_KUBECONTEXT_NAMESPACE}%f'
```
