### ISSUE TITLE
Font installation from the command line (for automated font installations)

### ISSUE THREAD

**Issue by fourstepper** [romkatv/powerlevel10k#1011]
Hi!

How would I proceed with installing the fonts mentioned here manually from the command line? https://github.com/romkatv/powerlevel10k#manual-font-installation

I am asking because I would like to include them as part of my automatic workstation installation

Thank you!

**Comment by romkatv** [comment]
This depends on your OS. This question is not specific to powerlevel10k.

**Comment by fourstepper** [comment]
Hi, the OS is Linux, Fedora. The one thing I've noticed is that the manually downloaded files create more files when installed via the GUI, which is why I am asking.

**Comment by romkatv** [comment]
> Hi, the OS is Linux, Fedora.

In this case you need to figure out how to install fonts on Fedora. This question is not specific to Powerlevel10k.

**Comment by fourstepper** [comment]
You are right. Thanks, I will figure it out.
