### ISSUE TITLE
prompt bug on maximizing and minimizing

### ISSUE THREAD

**Issue by molereddy** [romkatv/powerlevel10k#1012]
Upon maximizing and minimizing the terminal window more and more prompts are produced each time resulting in strange stuff like this
![Screenshot from 2020-09-14 21-34-40](https://user-images.githubusercontent.com/49127549/93109794-1d198c00-f6d2-11ea-9581-eabece5288ee.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
