### ISSUE TITLE
Git Status only shows up for certain repos

### ISSUE THREAD

**Issue by robbins** [romkatv/powerlevel10k#1014]
I can't exactly figure out what repos it shows and doesn't show for (or even if what they are matters), but I have 2 examples:

![image](https://user-images.githubusercontent.com/31457698/93271698-e602b380-f781-11ea-97b3-7ebac8ae1bb6.png)

The one on the left is a Git repo from the ArchLinux User Repository, and the one on the right is a Git repo from the Android Open Source Project. I can't figure out why the one on the right doesn't show git information. 

Creating an empty folder and running `git init` (even inside the previous repo) makes the Git information show up. But it doesn't want to show up for these repos.

Please let me know if there's anything I can do to provide you with further information to troubleshoot this, as I guess it's not a lot to go on right now.

Thanks.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/926#issuecomment-667591112.

**Comment by robbins** [comment]
Thanks for the reply. Checked the log: https://pastebin.com/NBGEQVwH and it looks like the issue is from using Git partial clone.

`[2020-09-16 09:01:15 00007f6919b6cc78 ERROR src/repo_cache.cc:66] git_repository_open_ext: "/home/nate/android/aosp_11/packages/apps/Settings/.git/": unsupported extension name extensions.partialclone`

Is there an option or workaround that would fix this extension? Thanks.

**Comment by romkatv** [comment]
All options and workarounds are listed in the link I’ve posted.
