### ISSUE TITLE
current time

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#1017]
How do i change the color of at
#2DCC70
![IMG_20200919_123414](https://user-images.githubusercontent.com/61009000/93659131-b3540600-fa74-11ea-9282-9366d77c2918.jpg)

typeset -g POWERLEVEL9K_TIME_PREFIX='%fat '

**Comment by romkatv** [comment]
Replace `%f` with `%F{1}`. See http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html.
