### ISSUE TITLE
Fix arch installation instructions

### ISSUE THREAD

**Issue by patatahooligan** [romkatv/powerlevel10k#1018]
Using `pacman -Sy` (which `yay -Sy` will do internally) can break the user's system and should *never* be mentioned in instructions unless doing something very specific that requires it. See [here](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).

It should be changed either to
* `yay -S` will simply install the package
* `yay -Syu` will perform a full upgrade, then install. In my opinion, we shouldn't decide to upgrade on behalf of the user, but at least it's safe.

Also, note that there is an official package that theoretically follows the stable releases, though it seems to have currently fallen behind. Maybe it should be mentioned or even be the recommended installation method.

    pacman -S zsh-theme-powerlevel10k

**Comment by romkatv** [comment]
> It should be changed either to
> 
> * `yay -S` will simply install the package

Done.

> Also, note that there is an official package [...]

See https://github.com/romkatv/powerlevel10k/pull/786.

**Comment by patatahooligan** [comment]
Thanks for the quick response.

Consider adding a short note on why the aur package is preferred. To me it looked like the readme was simply outdated and I installed the official package, which I wouldn't have done if I knew.

**Comment by romkatv** [comment]
> Consider adding a short note on why the aur package is preferred.

I added a note that the community package is to be avoided and linked to https://github.com/romkatv/powerlevel10k/pull/786 where some of its past issues are documented.
