### ISSUE TITLE
Implementing n1kk's minor aesthetic changes?

### ISSUE THREAD

**Issue by Hebgbs** [romkatv/powerlevel10k#102]
I gave this a look in the config showcase, and some people may want to emulate this in p10k. The code for this in p9k next is as follows;

```
P9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL="\ue0b2"
P9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL="\ue0b0"
```

The resulting effect of these attributes in p9k next per the above:
https://github.com/n1kk/p9k-config/raw/master/screens/style-bullet.png

There isn't a need to completely ape his setup since it's mostly vanilla stuff with his changes implemented. _Again_ they're p9k next attributes (on a Mac no less) I understand p10k uses p9k master as base no need to wax on about differences here. I tried his code on Linux, _it works..._ on p9k next.

**Comment by romkatv** [comment]
Done. The parameters are called `POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL` and 
`POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL`.
