### ISSUE TITLE
amibiwidth=double causes corrupted prompt in a terminal in Vim

### ISSUE THREAD

**Issue by ichihara-3** [romkatv/powerlevel10k#1022]
I don't know whether it is a problem of p10k or vim's bug...

When `set ambiwidth=double` option is set in vim and start terminal mode in vim, the prompt lines are corrupted or doubled.

### How to reproduce

environments　　
vim 8.2  
macOS  Catalina
iTerm2
powerlevel10k installed with prezto  
 
1. launch vim with the command `vim -u none --noplugin` so that vim loads no settings.
2. type `:set ambiwidth=double`
3. type `:terminal` to launch a terminal in vim
4. the lines are corrupted
![image](https://user-images.githubusercontent.com/23014016/93759676-99b5e880-fc45-11ea-92bb-cf970ff7fedb.png)
5. type `exit` to close the terminal
6. if `:set ambiwidth=single` (and it is the default of vim), the prompt looks good.

the option `ambiwidth=double` is frequently set in Japan and some countries using doubled width font.

### my workaround

These settings in .vimrc worked good for me.

```
augroup TermSettings
  autocmd!
  autocmd TerminalOpen * set ambiwidth=single
  autocmd BufEnter * if &buftype=="terminal" | set ambiwidth=single | endif
  autocmd BufLeave * if &buftype=="terminal" | set ambiwidth=double | endif
augroup END
```

**Comment by romkatv** [comment]
> amibiwidth=double causes corrupted prompt in a terminal

This is expected. Zsh requires that the terminal renders ambiguous-width characters as narrow (taking one column).
