### ISSUE TITLE
Console output during zsh initialization detected

### ISSUE THREAD

**Issue by RKOsvk** [romkatv/powerlevel10k#1023]
this is my error mesage 
`[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --
`

i try follow this issue https://github.com/romkatv/powerlevel10k/issues/315 but i havent solve my problem.

**Comment by romkatv** [comment]
Have you tried doing what the warning suggests?

**Comment by RKOsvk** [comment]
Yes i add typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet to my p10k configure file.

**Comment by romkatv** [comment]
And? Did it help?

**Comment by RKOsvk** [comment]
It didnt help

**Comment by romkatv** [comment]
Too bad

**Comment by woss** [comment]
haha what an answer. 

i'm having the same situation and yes mister @romkatv i did follow what it says, `   typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet` and it keeps repeating once in a while

I'm using the [keychain](https://www.funtoo.org/Keychain) to manage my ssh keys which has the output. any idea how to include this in the zshrc without getting the warnings?

**Comment by romkatv** [comment]
Type `echo $POWERLEVEL9K_INSTANT_PROMPT`. What do you see?

**Comment by woss** [comment]
verbose

**Comment by romkatv** [comment]
> verbose

Oh well.

**Comment by woss** [comment]
and that means what, exactly. what should be the most common option

**Comment by romkatv** [comment]
Please read the warning and try what it says.

**Comment by woss** [comment]
i chose the `typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet` it doesn't show now but once in a while it shows. maybe installing v3 will help. i'll let you know if this occurs again. 

thanks :)

**Comment by romkatv** [comment]
> i chose the `typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet`

Your previous comment contradicts this.

**Comment by LukasKnuth** [comment]
This will probably happen when you have chosen the "Recommendet" option for instant prompt during the wizard. In this case, your `.p10k.zsh` file will contain a `typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose`.

If you added the typeset command (as suggested by the warning message) _before_ the `.p10k.zsh` file is sourced (which by default should be the last thing in your `.zshrc` file) it will be overridden again and you'll still see the warning.

So either add the suggested `typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet` _after_ `source .p10k.zsh`, OR edit the `.p10k.zsh` file directly and make the change there.

**Comment by BFalls158** [comment]
Thanks @LukasKnuth. Makes sense now and is fixed. Great explination, Much better than the terse, 1 word, holier than thou answers of the owner.

**Comment by eddyg** [comment]
@BFalls158 The `INSTANT_PROMPT` functionality and configuration options are fully documented and explained _very_ clearly [in the README](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-enable-instant-prompt) in the **How do I enable instant prompt?** section. There's absolutely no need for snide comments about the author, who provides this tool for _free_, and has dealt with hundreds and hundreds of questions here that are opened as "issues"... many of which have been _already answered_ in the extensive README that nobody takes the time to read.
