### ISSUE TITLE
Cursor overflows to next line

### ISSUE THREAD

**Issue by ShreyBana** [romkatv/powerlevel10k#1024]
For some reason my cursor is overflowing to the next line. This is not by choice.
![Screenshot from 2020-09-23 20-12-58](https://user-images.githubusercontent.com/51321651/94028152-3d83cd80-fdd9-11ea-8281-8f545d5fad5f.png)

**Comment by romkatv** [comment]
Have you seen this? https://github.com/romkatv/powerlevel10k#prompt-wrapping-around-in-a-weird-way

**Comment by ShreyBana** [comment]
> Have you seen this? https://github.com/romkatv/powerlevel10k#prompt-wrapping-around-in-a-weird-way
Yep tried everything didnt work. Even changing the font to the recommended one did not work.

**Comment by romkatv** [comment]
I’m afraid there is nothing else you can try.
