### ISSUE TITLE
Powerlevel10k configuration wizard keeps appearing

### ISSUE THREAD

**Issue by jcctr** [romkatv/powerlevel10k#1025]
Hi all, I know it has been already solved for someone but I keep having the wizard appearing when I open a new terminal session/window/tab.

Any idea how to fix that ? Fyi I already have POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=True in my ~/.zshrc

Cheers

**Comment by jcctr** [comment]
I've moved POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=True much higher in the ~/.zshrc file and it works

**Comment by romkatv** [comment]
For a proper fix, see https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by jcctr** [comment]
Mind if I send you the zshrc and p10k.zsh ? Now I always get [this issue too ](https://github.com/romkatv/powerlevel10k/issues/315)

Cheers

**Comment by romkatv** [comment]
You aren’t getting an issue, you are seeing a warning. Simply read what it says and do what it suggests.

**Comment by jcctr** [comment]
That's what I did, even when I set it to "off" it appears. And I have quit and relaunched the terminal...

**Comment by jcctr** [comment]
Also, for some reason, after I run a new config it would not be saved, I lose it all the time... very frustrating
<img width="1283" alt="Screenshot 2020-09-25 at 22 34 41" src="https://user-images.githubusercontent.com/20440775/94313611-4f9f7080-ff7f-11ea-8c01-c7f0eff290fe.png">

**Comment by romkatv** [comment]
See this: https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

Read the whole thing.

**Comment by muriloacs** [comment]
Thanks @romkatv . It happened to me due to a syntax error on the `~/.zshrc` file.
