### ISSUE TITLE
How to add a new git icon?

### ISSUE THREAD

**Issue by ShaneTian** [romkatv/powerlevel10k#1027]
For a new code hosting website (eg. [gitee.com](https://gitee.com/)), how do I add a corresponding git icon?
![image](https://user-images.githubusercontent.com/42370681/94522597-77822300-0262-11eb-86c8-205b9dc841e3.png)
![image](https://user-images.githubusercontent.com/42370681/94522639-879a0280-0262-11eb-9c19-99ccbab3d4f0.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/1009#issuecomment-692552972
