### ISSUE TITLE
root directory display with DIR_PATH_SEPARATOR

### ISSUE THREAD

**Issue by deathtrip** [romkatv/powerlevel10k#1028]
This is a sort of continuation of a [bug](https://github.com/Powerlevel9k/powerlevel9k/issues/1041) in the original powerlevel9k repo, that never got fixed.
I have set `POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{250} $(print_icon 'LEFT_SUBSEGMENT_SEPARATOR') "`
and now i get no root directory slash anymore.
![p10k](https://user-images.githubusercontent.com/8403455/94547833-1e10f880-0250-11eb-8802-a0b52ff63461.jpg)
I tried setting `POWERLEVEL9K_FOLDER_ICON='/'` and changing few other options but haven't been able to fix it.
It only happens with the root directory, home works just fine.
![p10k1](https://user-images.githubusercontent.com/8403455/94550524-2703c900-0254-11eb-8820-d7045066e3cb.jpg)

**Comment by romkatv** [comment]
Try the following:

1. Update powerlevel10k to the latest version.
2. Set these parameters:
    ```zsh
    typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR=' \uE0B1 '
    typeset -g POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
    typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR_FOREGROUND=250
    ```

The last parameter is optional. Everything might look fine without it.

Does this do what you want?

**Comment by deathtrip** [comment]
I already use the git package from the AUR.

When i set `typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR=' \uE0B1 '` i get this:
![p10k3](https://user-images.githubusercontent.com/8403455/94572825-bbc8ef80-0271-11eb-9d91-b2c81dad55b2.jpg)
It just prints the characters instead of the actual glyph.

And setting `POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true` just gets rid of the first separator (like in the image above), or the first slash when used without DIR_PATH_SEPARATOR.

The look i'm looking for is something like this:
![p105](https://user-images.githubusercontent.com/8403455/47622586-03cfbc80-db07-11e8-8bd4-10e3a39a686d.jpeg)

**Comment by romkatv** [comment]
> I already use the git package from the AUR.

This only works in the latest version of powerlevel10k. You need to update to the latest version.

**Comment by deathtrip** [comment]
It is the latest version, recommended in this repos readme as the official arch package. And it looks like it's even maintained by you.

**Comment by romkatv** [comment]
It is maintained by me, yes. You still need to update to the latest version for these parameters to work. There is no way around it.

**Comment by deathtrip** [comment]
So i updated to the latest commit r3726.
Setting `DIR_OMIT_FIRST_CHARACTER` fixes the issue of the extra segment when being in the root directory, and `/` slash is being displayed correctly. 
![p10k11](https://user-images.githubusercontent.com/8403455/94596405-60f0c180-028c-11eb-9083-8ddf7d87d07d.jpg)

However once you go into another directory the slash and it's segment are also gone. So it got fixed but only for one path.
![p10k4](https://user-images.githubusercontent.com/8403455/94596670-b9c05a00-028c-11eb-80e8-014871e91532.jpg)


Another thing i noticed is when i specify dir_writable as a seperate segment, the lock icon gets displayed twice.
![p10k6](https://user-images.githubusercontent.com/8403455/94597699-2be56e80-028e-11eb-96e4-a0aae7233c46.jpg)
Tried various icon options, but couldn't get it to appear only once.

**Comment by romkatv** [comment]
This is all working as expected. To hide the lock within `dir` segment, remove `POWERLEVEL9K_DIR_SHOW_WRITABLE`. Read comments around it to understand how it works.
