### ISSUE TITLE
Ruby 2.7.0 DOESNOT shows ruby version icon but 2.6.1 does

### ISSUE THREAD

**Issue by ziraqyoung** [romkatv/powerlevel10k#1030]
Hi

I manage Ruby versions with rbenv. I updated my global ruby version to 2.7.0 from 2.6.1.
The ruby version icon on the right status bar ( as per .ruby-version file ) shows correctly in 2.6.1 version but on 2.7.0 the icon doesn't show.

Ruby 2.6.1 - ruby version icon on the right showing (with .ruby-version as 2.6.1)
![Ruby 2 6 1](https://user-images.githubusercontent.com/41262193/94596998-aa91da00-0295-11eb-8b58-ceb584e60975.png)

Ruby 2.7- ruby version icon on the right  NOT showing (with .ruby-version as 2.7.0)
![Ruby 2 7](https://user-images.githubusercontent.com/41262193/94597008-aebdf780-0295-11eb-98f8-629bed0cdaf8.png)

When not in ruby project folder,  `$ ruby -v ` shows `$ 2.7.0` (global)

Any help will be appreciated.

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `rbenv` and read comments.

Does this answer your question?

**Comment by ziraqyoung** [comment]
Thanks so much.
changing   `typeset -g POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=true` did it

**Comment by ziraqyoung** [comment]
Thank got it. And thanks for the great project
