### ISSUE TITLE
Improve configure

### ISSUE THREAD

**Issue by rsalmei** [romkatv/powerlevel10k#1031]
Hello!

Please, could you improve `configure` to accept ENTER, meaning to maintain the current state of that option?
Several times I want to change just one aspect, say Prompt Spacing. And I always need to re-configure everything to the very same as it already were, which needs much more attention than needed.
It would be awesome to just press ENTER until I got to the one I do want to change. The screen could even include an `*` to display the currently selected options.
Would it be possible?

Thank you!!

**Comment by romkatv** [comment]
`p10k configure` is a one-way generator. It doesn’t and cannot know what the current values of different options are. Think what happens when you manually edit your config after generating it.

**Comment by rsalmei** [comment]
I understand, thank you anyway.
