### ISSUE TITLE
Trying to set up powerlevel10k on offline device

### ISSUE THREAD

**Issue by cmunk** [romkatv/powerlevel10k#1033]
Hi -- We have our coding enviroment at work cut off from the internet and I'm trying to set up powerlevel10k.

I have copied over the repo but I get stuck on the:
`[powerlevel10k] fetching gitstatusd .. -`

I have tried to see if I can set it up offline / manually but I have not succeeded -- can you advice me if this is an option and how I might achieve it?

Thank you!

**Comment by romkatv** [comment]
I added offline installation instructions to the doc: https://github.com/romkatv/powerlevel10k#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access

Please let me know whether they work for you.

**Comment by romkatv** [comment]
Closing because the reporter has vanished.

**Comment by Mat-R** [comment]
I have the same use case as the OP.

> I added offline installation instructions to the doc: https://github.com/romkatv/powerlevel10k#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access
> 
> Please let me know whether they work for you.

It works for me.

**Comment by romkatv** [comment]
Thanks for verifying!
