### ISSUE TITLE
`transient_prompt=off` But still transient

### ISSUE THREAD

**Issue by jctaillandier** [romkatv/powerlevel10k#1034]
With the config wizard I ask for it to be turned on, and it works perfectly.

I can't find how to turn it off; everything in the config folder is set to `transient_prompt=off`

When should I look?

**Comment by romkatv** [comment]
Run `p10k configure` and select "Off" when asked about Transient Prompt.

**Comment by jctaillandier** [comment]
I overwrote the variable in my .zshrc instead, but thanks! 

Why couldn't I find where it's set though?

**Comment by romkatv** [comment]
> I overwrote the variable in my .zshrc instead, but thanks!

If that works, it works. Having prompt-related options spread over multiple files is not a good idea. Also, if in the future you decide to change some other parameter, you'll likely be confused.

> Why couldn't I find where it's set though?

¯\_(ツ)_/¯
