### ISSUE TITLE
Some Segments Are Colored Black Altough They Are Set Different Colors

### ISSUE THREAD

**Issue by hmtekin** [romkatv/powerlevel10k#1036]
First time using Powerlevel10K. I installed it with ZSH and oh-my-zsh on a new Arch Linux install (which also i am new into).

I installed Powerlevel10K by git clone-ing this git, following this tutorial: https://www.youtube.com/watch?v=dg1tK50UVGI I used "p10k configure" to configure it. I chose rainbow at first, which did not look right to me, left segments blur was missing and colors didn't seem consistent. Then i played a bit with .p10k.zsh. I uncommented some segments, change the order and placement of some and i run "source .zshrc" (which later i saw i shouldnt). Then i run "p10k configure" again, choose "lean" this time. And result was worse.

![Screenshot_20201003_225607](https://user-images.githubusercontent.com/10072697/95000745-12189400-05cc-11eb-9ba9-40f86c28fc5f.png)

(This is not the immediate screenshot after p10k configure)

Problem is time segment and home icon is wrongly colored as a kind of dark grayish black. Other segments are just fine. At first i thought whole segments are missing. But i noticed there is an empty space after completion time segment. After changing terminal background to a lighter one, i saw that the empty space is indeed time segment which is not missing but colored as black.  

I opened .p10k.zsh and find this line:

`typeset -g POWERLEVEL9K_TIME_FOREGROUND=66
`

I tried changing this value (which obviously is not black already) and have no results whatsoever. It's like it is commented out (it is not btw). I can add segments, and change their colors. I can change time format to hh:mm and it shows. But i cant assign a color to time segment and home icon.

If the problem has not occured because i sourced .zshrc, what can it be? May be something else is interfering with p10k. What can that be? If it is because of "source .zshrc" how can i fix that? I have browsed through old issues but couldn't find a solution there.

**Comment by romkatv** [comment]
Please do the following.

1. Run `p10k configure` and select lean style with time.
2. Once you are through the configuration wizard, take a screenshot and post it here.
3. Run the following command. Take a screenshot and post it here.
   ```zsh
   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
   ```
4. Run the following command. Take a screenshot and post it here.
   ```zsh
   POWERLEVEL9K_TIME_FOREGROUND=1; p10k reload
   ```

**Comment by hmtekin** [comment]
**1)** SS after p10k configure:

![Screenshot_20201004_083622](https://user-images.githubusercontent.com/10072697/95007836-d22dcd00-061c-11eb-809b-1dabb54d8736.png)

**2)** SS after color printing cmd:

![Screenshot_20201004_084146](https://user-images.githubusercontent.com/10072697/95007924-bb3baa80-061d-11eb-8764-024a00ef5ee9.png)


**3)** SS after changing time fg:

![Screenshot_20201004_084445](https://user-images.githubusercontent.com/10072697/95007955-08b81780-061e-11eb-8c29-1c50218f412e.png)


Additionally:



1.1) First ss with light terminal bg:
![Screenshot_20201004_083313](https://user-images.githubusercontent.com/10072697/95007990-6482a080-061e-11eb-8412-e80d58a86514.png)

1.2) First ss when i select two lines with mouse

![Screenshot_20201004_083810](https://user-images.githubusercontent.com/10072697/95008021-a3b0f180-061e-11eb-8ee9-9cf052b3ebd8.png)

**Comment by hmtekin** [comment]
I've managed to change the mentioned colors, not through .p10k.zsh file but through terminal settings:

![Screenshot_20201004_183836](https://user-images.githubusercontent.com/10072697/95019951-ff0bcf80-0670-11eb-9e19-305f036c6668.png)

In settings i have changed this color (Renk 1 : Color 1)  to a light blue one:

![Screenshot_20201004_183115](https://user-images.githubusercontent.com/10072697/95019978-2c587d80-0671-11eb-888e-f133bc610c45.png)

Does this means some segments colors are overriden by terminal settings? I'm using Yakuake as terminal but it shares settings with Konsole, may be it is about how KDE manages things. 

I hope this helps.

**Comment by romkatv** [comment]
1. What is the output of `echo $TERM`?
2. Please run the following command and post a screenshot:
   ```zsh
   ( 
     emulate -L zsh -o err_return
     local tmp
     tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
     {
       git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k
       >$tmp/.zshrc <<\END
   POWERLEVEL9K_MODE=nerdfont-complete
   POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
   POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
   POWERLEVEL9K_BACKGROUND=
   POWERLEVEL9K_ICON_PADDING=none
   POWERLEVEL9K_DIR_FOREGROUND=31
   POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
   POWERLEVEL9K_SHORTEN_DELIMITER=
   POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
   POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
   POWERLEVEL9K_DIR_ANCHOR_BOLD=true
   POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
   source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
   END
       ZDOTDIR=$tmp zsh -is <<<exit
       print
       print -P '%31FNORMAL%f %B%39FBOLD%f%b'
       PS1='%31FNORMAL%f %B%39FBOLD%f%b' zsh -fis <<<exit
       print
     } always {
       builtin cd -q /
       command rm -rf -- $tmp
     }
   )
   ```

**Comment by hmtekin** [comment]
**1)** $TERM value:

![Screenshot_20201004_191358](https://user-images.githubusercontent.com/10072697/95020799-01bcf380-0676-11eb-86e9-ae8a3de0b5cd.png)


**2)** Command result:

![Screenshot_20201004_191750](https://user-images.githubusercontent.com/10072697/95020876-74c66a00-0676-11eb-9317-c0afa8196d72.png)

**Comment by romkatv** [comment]
Wow, this is so weird. The home icon and `~` use the style attributes as `NORMAL` and `BOLD` respectively, yet they are rendered differently by the terminal. I've never seen anything like this.

Please run the following command, post a screenshot and attach (drag-and-drop) `/tmp/p10k.txt`:

```zsh
( 
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k
    >$tmp/.zshrc <<\END
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_BACKGROUND=
POWERLEVEL9K_ICON_PADDING=none
POWERLEVEL9K_DIR_FOREGROUND=31
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DELIMITER=
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    {
      ZDOTDIR=$tmp zsh -dis <<<exit
      print
      print -P '%31FNORMAL%f %B%39FBOLD%f%b'
      print '\e[0m\e[49m\e[39m\e[0m\e[49m\e[38;5;31mNORMAL \e[1m\e[38;5;31m\e[38;5;39mBOLD\e[0m'
    } 2>&1 | tee /tmp/p10k.txt
    cat /tmp/p10k.txt
    cat -v /tmp/p10k.txt
  } always {
    builtin cd -q /
    command rm -rf -- $tmp
  }
)
```

**Comment by hmtekin** [comment]
SS:

![Screenshot_20201005_103225](https://user-images.githubusercontent.com/10072697/95055429-eb597b00-06fb-11eb-9d53-0d1a06769fe6.png)

File:

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/5326083/p10k.txt)

**Comment by romkatv** [comment]
The mystery deepens. Please run this and post a screenshot:

```zsh
(
print '\e[0m\e[49m\e[39m\e[0m\e[49m\e[38;5;31m \uF015 \e[1m\e[38;5;31m\e[38;5;39m~\e[0m\e[38;5;39m\e[49m\e[38;5;31m\e[0m\e[38;5;31m\e[49m\e[38;5;31m \e[0m\e[38;5;31m\e[49m\e[30m\uE0B0\e[0m\e[30m\e[49m\e[39m \e[0m\e[49m\e[39m'
print '\e[0m\e[49m\e[39m\e[0m\e[49m\e[38;5;31m X \e[1m\e[38;5;31m\e[38;5;39mY\e[0m\e[38;5;39m\e[49m\e[38;5;31m\e[0m\e[38;5;31m\e[49m\e[38;5;31m \e[0m\e[38;5;31m\e[49m\e[30m\uE0B0\e[0m\e[30m\e[49m\e[39m \e[0m\e[49m\e[39m'
print '\e[0m\e[49m\e[39m\e[0m\e[49m\e[38;5;31m X \e[1m\e[38;5;31m\e[38;5;39mY\e[0m\e[38;5;39m\e[49m\e[38;5;31m\e[0m\e[38;5;31m\e[49m\e[38;5;31m \e[0m\e[38;5;31m\e[49m\e[30m\uE0B0\e[0m'
print '\e[0m\e[49m\e[39m\e[0m\e[49m\e[38;5;31m X \e[1m\e[38;5;31m\e[38;5;39mY\e[0m\e[38;5;39m\e[49m\e[38;5;31m\e[0m'
print '\e[0m\e[49m\e[39m\e[0m\e[49m\e[38;5;31m X \e[1m\e[38;5;31m\e[38;5;39mY\e[0m'
print '\e[0m\e[49m\e[39m\e[0m\e[49m\e[38;5;31m X \e[0m'
print '\e[0m\e[49m\e[38;5;31m X \e[0m'
print '\e[49m\e[38;5;31m X \e[0m'
)
```

**Comment by romkatv** [comment]
Sorry, the previous command is not necessary to run. Please run the one and post a screenshot:

```zsh
( 
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k
    >$tmp/.zshrc <<\END
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_BACKGROUND=
POWERLEVEL9K_ICON_PADDING=none
POWERLEVEL9K_DIR_FOREGROUND=31
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DELIMITER=
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
  ZDOTDIR=$tmp zsh -dis <<<'( x=${(e)PS1}; y=${(%)x}; z=$(cat -v <<<$y); print -lr -- x $x y $y z $z ); exit'
  } always {
    builtin cd -q /
    command rm -rf -- $tmp
  }
)
```

**Comment by hmtekin** [comment]
![Screenshot_20201005_122439](https://user-images.githubusercontent.com/10072697/95062874-3a0c1280-0706-11eb-9eb4-d1aaad332871.png)

**Comment by romkatv** [comment]
OK, I think we are getting close to solving this. Please run the following command and attach `/tmp/p10k.txt`. Screenshot is not necessary this time.

```zsh
( 
  emulate -L zsh -o err_return -o extended_glob
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k
    >$tmp/.zshrc <<\END
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_BACKGROUND=
POWERLEVEL9K_ICON_PADDING=none
POWERLEVEL9K_DIR_FOREGROUND=31
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DELIMITER=
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
  rm -rf -- ~/.cache/p10k-${(%):-%n} ~/.cache/p10k-dump-${(%):-%n}.zsh
  ZDOTDIR=$tmp zsh -xdis <<<'locale; [[ 31 == <-> ]] && echo number || echo not-a-number; _p9k_translate_color 31; typeset -pm "_p9k__ret|ZSH_VERSION|*POWERLEVEL9K_DIR_FOREGROUND"; exit'
  } always {
    builtin cd -q /
    command rm -rf -- $tmp
  }
) &>/tmp/p10k.txt
```

**Comment by hmtekin** [comment]
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/5326947/p10k.txt)

**Comment by romkatv** [comment]
Thanks for helping to debug this. TIL that the results uppercasing an ascii character are locale-dependent. E.g., with `tr_TR` locale (Turkish) uppercasing "i" (lowercase Latin character) produces "İ". I've pushed a fix to Powerlevel10k.

Please revert the terminal setting changes that you've described in https://github.com/romkatv/powerlevel10k/issues/1036#issuecomment-703274019 and update powerlevel10k to the latest version. Let me know if this fixes the problem for you.

**Comment by hmtekin** [comment]
Youre welcome, i should thank you too. I updated and it works just nicely now. Great job! 

![Screenshot_20201005_162036](https://user-images.githubusercontent.com/10072697/95085063-61270c00-0727-11eb-841d-381fe9dac171.png)

Turkish locale huh? I have never guessed that. So it was "time" becoming "TİME" somewhere instead of "TIME"?

**Comment by romkatv** [comment]
> Turkish locale huh? I have never guessed that. So it was "time" becoming "TİME" somewhere instead of "TIME"?

Yep, exactly.
