### ISSUE TITLE
Git status and checkout very slow on some repository

### ISSUE THREAD

**Issue by Chelayel** [romkatv/powerlevel10k#1039]
Hello,

I am facing some very slow performances using git commands. I am using WSL2 on Windows 10.
Below is the results of `time git status`  on two repositories, one small repo and one very large repo 

Small Repo
`nothing to commit, working tree clean
git status  0.07s user 0.91s system 19% cpu 4.922 total`

Large Repo
`It took 5.03 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
no changes added to commit (use "git add" and/or "git commit -a")
git status  6.91s user 34.01s system 19% cpu 3:28.93 total`

Using Bash, the same command displays the following for the large repo and is almost instant
`no changes added to commit (use "git add" and/or "git commit -a")
real    0m0.363s
user    0m0.047s
sys     0m0.125s
`
Did anything change recently? Can you please help me with that regard? Thank you

**Comment by romkatv** [comment]
Powerlevel10k has no effect on commands such as `git status`. The only thing Powerlevel10k does is display prompt.

It's also extremely unlikely that `git status` behaves differently when you invoke it from Bash and Zsh. It's the same command after all.

FWIW, WSL2 is known to have abysmal filesystem performance on NTFS mounted filesystems. In my own tests, `git status` on NTFS is about 50x slower in WSL2 than in WSL1. However, if you put your Git repository on rootfs (e.g., in `$HOME`), `git status` becomes very fast in WSL2. You can find some details in https://github.com/microsoft/WSL/issues/4197.

**Comment by Chelayel** [comment]
Noted, thank you. Closing this issue as this is related to WSL2 and not powerlevel10k.

**Comment by bebound** [comment]
On WSL2, we can use `git.exe "$@"` to speed up git query. Can powerlevel10k get benefits from this?
```
function git() {
  if $(pwd -P | grep -q "^\/mnt\/c\/*"); then
    git.exe "$@"
  else
    command git "$@"
  fi
}
```

Ref: https://markentier.tech/posts/2020/10/faster-git-under-wsl2/

**Comment by romkatv** [comment]
> Can powerlevel10k get benefits from this?

Powerlevel10k is already a lot faster than this.

**Comment by bebound** [comment]
Actually, it's a WSL problem.
In large Windows mounted repo, it takes 4seconds to display git status. But the git.exe is much faster.
I wonder if we can override the git command which p10k uses.

**Comment by romkatv** [comment]
If something in powerlevel10k is slow, open an issue. You are commenting on an issue that has nothing to do with powerlevl10k performance.
