### ISSUE TITLE
Empty remote url for branch different to master

### ISSUE THREAD

**Issue by cdalvaro** [romkatv/powerlevel10k#104]
The remote url is not properly recovered when the current branch is not `master`.

This also affects to the repository icon:

![RemoteURL](https://user-images.githubusercontent.com/16347742/60701120-dd1a1f00-9efa-11e9-9333-1f2d1a610e7f.png)

**Comment by romkatv** [comment]
Different branches of the same repository can have different tracking remotes. I'm guessing that `empty_remote_url_when_switching_to_branch` doesn't have a tracking remote. You can see remotes with `git branch -vv`. The one marked with `*` is the tracking remote.

You can notice that while you are on a branch without a tracking remote, you don't see ahead/behind arrows. E.g., if you make a commit, normally a vertical arrow appears in the Git prompt but on it won't appear on `empty_remote_url_when_switching_to_branch`. This is in alignment with `git status` command. Ahead/behind is relative to the tracking remote.

P.S.

You can use the following command to print Git status without having to modify the code of `gitstatus.plugin.zsh`:

```zsh
typeset -m 'VCS_*'
```

It'll show everything in a user-friendly format.

**Comment by cdalvaro** [comment]
Thank you very much! I've learned a lot from this!
