### ISSUE TITLE
Cannot disable gitstatus for managed machine

### ISSUE THREAD

**Issue by mahatma-andy** [romkatv/powerlevel10k#1040]
Hi there,

Though I understand gitstatus provides much better performance than the traditional way of gathering info for the prompt, I use a managed machine on which I don't have permission to run it.

As such, every time I open a new shell, I have to wait for this to fail:

```
[powerlevel10k] fetching gitstatusd .. -
```

How can I disable this feature?

**Comment by romkatv** [comment]
There are several ways. If you don’t use Git on that machine, remove `vcs` from the list of enabled prompt segments in `~/.p10k.zsh`. If you do use Git on that machine and you are OK with having a slow prompt, add `POWERLEVEL9K_DISABLE_GITSTATUS=true` to `~/.p10k.zsh`.

**Comment by romkatv** [comment]
By the way, what do you mean by not being allowed to run gitstatusd? What exactly is disallowed?

Fetching gitstatusd requires internet access. If you don’t have internet access on that machine, see https://github.com/romkatv/powerlevel10k#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access.

**Comment by mahatma-andy** [comment]
Aha, that's exactly what I needed.

Regarding not being able to run gitstatusd, it's not an internet connectivity issue, but that only whitelisted executables are allowed to run. Perhaps one day the admins will see fit to add gitstatusd to that list, but in the meantime, many thanks. :)
