### ISSUE TITLE
Powerlevel10K conf wizard run each tab

### ISSUE THREAD

**Issue by BorgesGabo** [romkatv/powerlevel10k#1041]
Hi,
I completed  the wizard and I got this (see below). It seems something is not working. Once I complete the wizard In the actual tab everything is ok, but when I try to open a new tab or window the wizard runs again.  

I also disable the wizard with
echo 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true' >>! ~/.zshrc

the I source the zshrc. but nothing. Also I restart the terminal unsuccessfully

I appreciate your help.

Thanks

Last login: Mon Oct  5 14:46:47 on ttys004
/Users/myname/.zshrc:117: bad assignment

New config: ~/.p10k.zsh.
Backup of the old config: $TMPDIR/.p10k.zsh.2yx85UcMu6.

File feature requests and bug reports at https://github.com/romkatv/powerlevel10k/issues

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by romkatv** [comment]
> /Users/myname/.zshrc:117: bad assignment

This is the culprit.

**Comment by BorgesGabo** [comment]
thank you romkatv solved!
