### ISSUE TITLE
POWERLEVEL9K_TIME_FORMAT %k adds extra space during single digit hours

### ISSUE THREAD

**Issue by FrazerClews** [romkatv/powerlevel10k#1043]
When `POWERLEVEL9K_TIME_FORMAT` uses `%k` as part of the time format, and the hour is a single digit, it prints an extra space where a 0 would normally be when using `%H` instead

e.g. `typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%k:%M}'`
Expected: `0:12`
Got: ` 0:12` (`<space>0:12`)

**Comment by romkatv** [comment]
This is working as expected. See `man strftime`:

> %k     The hour (24-hour clock) as a decimal number (range 0 to 23); single digits are preceded  by  a  blank.
