### ISSUE TITLE
Colorize where part of VCS

### ISSUE THREAD

**Issue by flohw** [romkatv/powerlevel10k#1044]
Hi,

I wanted to add tag name in addition of branch name when tag is present. If find [this comment](https://github.com/romkatv/powerlevel10k/issues/391#issuecomment-612702692) and it works perfectly. The icon is colorized in white I wanted to also colorize the tag name (test . In addition would it be possible to make it look like a different segment ?

![2020-10-07-103631_408x38_scrot](https://user-images.githubusercontent.com/457663/95307485-fa216880-0888-11eb-925d-78c469b3a572.png)

Having green bgcolor for branch name and maybe orange for tag name with the desired separators.

I tried first to add `${meta}` to the where variable but it writes the characeters `%7F` in the prompt.
```zsh
      if [[ -n $VCS_STATUS_TAG ]]; then
          (( $#where > 32 )) && where[13,-13]="…"
          res+="${clean}${where//\%/%%}"  # escape %
          res+=" ${meta}#"
          where=${meta}${(V)VCS_STATUS_TAG}
      fi
```
![2020-10-07-103732_438x41_scrot](https://user-images.githubusercontent.com/457663/95307592-1e7d4500-0889-11eb-958b-fe5d03b47dc7.png)

I may miss something in the documentation? How can I achieve this?

Thank you

**Comment by romkatv** [comment]
> The icon is colorized in white I wanted to also colorize the tag name

You can find these definitions at the top of `my_git_formatter`:

```zsh
# Styling for different parts of Git status.
local       meta='%7F' # white foreground
local      clean='%0F' # black foreground
local   modified='%0F' # black foreground
local  untracked='%0F' # black foreground
local conflicted='%1F' # red foreground
```

So, `${meta}` makes the following text white, while `${clean}` makes it black. You can see it here:

```zsh
print -P '%0F this is black %7F this is white %f'
```

(Black text may be invisible if it's the same color as background.)

> In addition would it be possible to make it look like a different segment

Sure. Try placing `$\uE0B1` before the tag.

> I tried first to add `${meta}` to the where variable but it writes the characeters `%7F` in the prompt.

This is expected. You've prepended `%7F` to the name of the tag, so you see `%7F` in front of the tag.

> I may miss something in the documentation? How can I achieve this?

`my_git_formatter` is written in plain Zsh. It's not using anything specific to Powerlevel10k. To understand and to modify its code you need to understand Zsh. The most relevant documentation is here:

- Basic shell grammar (if-else, `&&`, etc.): http://zsh.sourceforge.net/Doc/Release/Shell-Grammar.html
- Percent escapes such as `%7F`: http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
- Parameter expansions such as `${where//\%/%%}`: http://zsh.sourceforge.net/Doc/Release/Expansion.html

You can print all `VCS_STATUS_*` parameters with this command:

```zsh
typeset -pm 'VCS_STATUS_*'
```

**Comment by flohw** [comment]
I use the same technique with variable res and where so why is there a difference between both outputs?

`res+=${meta} #` produces a white `#` while `where+=${meta} ${(V)VCS_STATUS_TAG}` produces `%7F test`. From my point of view there is no difference.

While adding `$\uE0B1` before the tag writes literally `$\uE0B1`.

If you can give me more advice and maybe more explicit, it would be helpful for everyone.

Thank you

**Comment by romkatv** [comment]
> I use the same technique with variable res and where so why is there a difference between both outputs?

`%7F` makes the following text red, while `%%7F` will produce text `%7F`. This is documented in http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html. It's not specific to Powerlevel10k.

```zsh
print -P '%1Fthis is red%f'
print -P '%%1Fthis is uncolored%f'
```

> `res+=${meta} #` produces a white `#` while `where+=${meta} ${(V)VCS_STATUS_TAG}` produces `%7F test`. From my point of view there is no difference.

The difference is that the first of these modifies `res`, the second modifies `where`.

> While adding `$\uE0B1` before the tag writes literally `$\uE0B1`.

Sorry about that. I meant `$'\uE0B1'` rather than `'$\uE0B1'`. These are different things (this is not specific to Powerlevel10k; it's just how Zsh works).

```zsh
print -rl --$'\uE0B1' '$\uE0B1'
```

> If you can give me more advice and maybe more explicit, it would be helpful for everyone.

If you want to customize how Git status is shown in prompt, edit `my_git_formatter`. Doing so requires some (not advanced) knowledge of Zsh.

**Comment by flohw** [comment]
Didn't notice `res+="${clean}${where//\%/%%}"` some lines after. That's why `where` is not colored.

That's what I was referring to about explanations. I can understand what p10k requires to be customized but some parts are not obvious to every one.

Sorry to not be as smart as you are.

**Comment by romkatv** [comment]
> Sorry to not be as smart as you are.

You are welcome to ask questions and I'll do my best to provide answers but please refrain from posting snark remarks.

**Comment by romkatv** [comment]
> I wanted to add tag name in addition of branch name when tag is present.

I've updated the templates for `~/.p10k.zsh` so that it's easier to make this change: https://github.com/romkatv/powerlevel10k/commit/a5d0525c6a34b614a885ec6f1c3d8ff8ddfc9e45. If you update powerlevel10k and run `p10k configure`, you'll have the following piece of code in `~/.p10k.zsh`: https://github.com/romkatv/powerlevel10k/blob/a5d0525c6a34b614a885ec6f1c3d8ff8ddfc9e45/config/p10k-lean.zsh#L387-L389
