### ISSUE TITLE
Problem with root-indicator icon

### ISSUE THREAD

**Issue by regenpfeifer** [romkatv/powerlevel10k#1045]
Hello, 

i have a problem with the root-indicator icon instead of a rhomb (#) it shows as a superscript "e".

Oh-My-Zsh and Powerlevel 10k are running on a machine with Ubuntu 20.04 LTS. I have installed the font-awesome package and the Powerline font. I can also see other font awesome icons (home, picture, music etc.) without any problems.

Furthermore I have here the same config files (.zshrc and .p10k) which I am using on several other machines, where I can see the root-indicator icon without any problems.

Does anyone have a hint, what the reason for this problem may be?

**Comment by romkatv** [comment]
Have you tried following this troubleshooting recommendation? https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by regenpfeifer** [comment]
Thank you romkatv,

indeed it was the Meslo font, which was missing.
Yours, regenpfeifer

**Comment by romkatv** [comment]
Thanks for the confirmation.
