### ISSUE TITLE
Make prompt multiline

### ISSUE THREAD

**Issue by regenpfeifer** [romkatv/powerlevel10k#1046]
I have configured my p10k prompt to my desires and are therefore hesitating to run the configuration assistant once again.
But i would like to change the prompt manually to multiline / two lines. Where can I find the configuration option for this?
Thank you very much, regenpfeifer

**Comment by romkatv** [comment]
Multi-line prompt has several additional options in the wizard:

- Whether to display frame (left, right, both or none).
- Whether to display `prompt_char`.
- Whether to display prompt connection (solid, dotted or none).
- If displaying frame or connection, what color should it be.

Without knowing the actual content of your `~/.p10k.zsh` and how you want your multi-line prompt to look like I cannot say how you should modify your config.

**Comment by romkatv** [comment]
Closing because the reporter has disappeared.

**Comment by pre** [comment]
How I did it: 

Add the `.p10k.zsh` to git and re-run `p10k configure`. After the wizard has done its magic, inspect the changes and keep only the changes you want. 

(I have under git a ~/dotfiles folder from where I symlink to ~/.zshrc, ~/.p10k.zsh etc)

**Comment by regenpfeifer** [comment]
> How I did it:
> 
> Add the `.p10k.zsh` to git and re-run `p10k configure`. After the wizard has done its magic, inspect the changes and keep only the changes you want.
> 
> (I have under git a ~/dotfiles folder from where I symlink to ~/.zshrc, ~/.p10k.zsh etc)

Thank you @pre, this is also working for me!
