### ISSUE TITLE
Icon cannot be displayed

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#1047]
The Termux terminal cannot display some icons. Why?
![Screenshot_20201008_130536_com huawei android launcher](https://user-images.githubusercontent.com/61009000/95417338-68d4f380-0967-11eb-99c4-4a479db0d27b.jpg)

**Comment by romkatv** [comment]
You are looking at a file that lists custom symbols from bad fonts. Those symbols will display properly only when using the specific bad fonts. Apparently you are using a good font, so you don't see these symbols.

**Comment by 26chk** [comment]
> 您正在查看的文件列出了不良字体中的自定义符号。这些符号仅在使用特定的不良字体时才能正确显示。显然，您使用的字体很好，因此看不到这些符号。

Thanks so much！👍
