### ISSUE TITLE
How to use hex color code ?

### ISSUE THREAD

**Issue by glepnir** [romkatv/powerlevel10k#1049]
Hey thanks for your work. I found that the clean is ` local      clean='%76F'  `,  But I want use `#08c2c2` so how to use this code for clean?

**Comment by romkatv** [comment]
Like this:

```zsh
local clean='%F{#08c2c2}'
```

This isn't specific to Powerlevel10k. This is plain zsh. You can test it like this:

```zsh
print -P '%F{#08c2c2}this is teal%f %Uthis is underlined%u'
```

Percent escape sequences are documented here: http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html.

**Comment by glepnir** [comment]
@romkatv  Works fine. other question is  like `    typeset -g my_git_format=[$res]` , the color is different,How to fix it ? both use same color.
![image](https://user-images.githubusercontent.com/41671631/95651175-06245900-0b1b-11eb-8aec-9d3ddee752c1.png)

**Comment by romkatv** [comment]
Again, is is not specific to Powerlevel10k. It's plain zsh.

```zsh
typeset -g my_git_format="%F{red}[$res%F{red}]"
```

Please read http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html.

**Comment by glepnir** [comment]
Thanks.Sorry for bother you.

**Comment by glepnir** [comment]
Hmm  So how to add bold for current directory?

**Comment by romkatv** [comment]
There is no option for it.
