### ISSUE TITLE
segment seperators

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/powerlevel10k#105]
So I am having a hard time trying to accomplish something and I dont know if I am not understanding things correctly, or what but. I am trying to replicate my bash theme into powerlevel10k and having a hard time:
┌─[13:27:07][boris][aristotle][default][master ↓1 {4} ?:2 ✗][~/Sources/charts]
└─▪

I have managed to get almost there:
┌─ 12:36:58  boris@aristotle  solutions1:admin:default  master ? ⇣1 *4  ~/Sources/charts
└─▪
The biggest thing I am having a hard time figuring out how to get done is the [ ] around my segments. no amount of setting left/right segment seperator variables is able to get me what I want :(

**Comment by romkatv** [comment]
I'm going to add additional parameters for segment prefix/suffix. This should give you square brackets.

Is `boris@aristotle` produced by `context` segment? If so, you can transform `boris@aristotle` to `boris][aristotle` by defining `POWERLEVEL9K_CONTEXT_TEMPLATE='%n][%m'`.

What is `solutions1:admin:default`? Do you need to find a way to shorten it to just `default`?

Could you post your current Powerlevel10k config?

**Comment by kurktchiev** [comment]
It’s by context tho I might switch it to user and host. The solutions1 is the kubernetes namespace and you have a PR opened that fixes that issue :) the prefix and suffix would be amazing

**Comment by romkatv** [comment]
You can shorten `kubecontext` to the part after the last colon with `POWERLEVEL9K_KUBECONTEXT_CONTENT_TRANSFORMER='${P9K_CONTENT##*:}'.

> It’s by context tho I might switch it to user and host.

So you are good with this part? I'm just trying to infer from your two prompt images what you need help with. If you could enumerate the issues you are still having, it would save time.

**Comment by romkatv** [comment]
> I'm going to add additional parameters for segment prefix/suffix. This should give you square brackets.

This is done. Example:

```zsh
typeset POWERLEVEL9K_VCS_{LOADING,CLEAN,UNTRACKED,MODIFIED}_PREFIX='['
typeset POWERLEVEL9K_VCS_{LOADING,CLEAN,UNTRACKED,MODIFIED}_SUFFIX=']'

typeset POWERLEVEL9K_CONTEXT_{DEFAULT,ROOT,REMOTE_SUDO,REMOTE,SUDO}_PREFIX='['
typeset POWERLEVEL9K_CONTEXT_{DEFAULT,ROOT,REMOTE_SUDO,REMOTE,SUDO}_SUFFIX=']'
```

Specifying this for every segment and state is verbose but flexible.

**Comment by romkatv** [comment]
Since this issue was primarily about square brackets, I'm going to close it. If this feature doesn't work, please reopen. If some other customization options seems missing, open another.

**Comment by romkatv** [comment]
It works just like it used to.

If something doesn't work for you, open an issue. Attach your config, a screenshot of your prompt and an explanation why the prompt is not what you expect.
