### ISSUE TITLE
windows 10 in VS Code by cygwin64 close terminal with zsh.exe leakage

### ISSUE THREAD

**Issue by wszgrcy** [romkatv/powerlevel10k#1052]
when I stop terminal ,I find `Task Manager`have one `zsh.exe` process and when I commit
`[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh` this line and stop terminal have no `zsh.exe` process in `Manager`.
Open terminal has 4 `zsh.exe` process and stop terminal remain 1 process
```sh

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.zinit/bin/zinit.zsh
zinit ice depth=1; zinit light romkatv/powerlevel10k

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# autoload -Uz compinit; compinit

zinit snippet OMZ::lib/completion.zsh
ZLE_RPROMPT_INDENT=0
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '

 if [ -x /usr/bin/dircolors ]; then
     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
        alias ls='ls --color=auto'
        alias dir='dir --color=auto'
        alias vdir='vdir --color=auto'
        alias grep='grep --color=auto'
        alias fgrep='fgrep --color=auto'
        alias egrep='egrep --color=auto'
 fi
```

**Comment by romkatv** [comment]
Could you describe how to reproduce this problem step by step?

**Comment by wszgrcy** [comment]
> Could you describe how to reproduce this problem step by step?

open vscode(config "terminal.integrated.shell.windows": "E:\\cygwin64\\bin\\zsh.exe",)
`Ctrl ~`open terminal
input some word(or Enter) in terminal
click `Trash` icon
open `Task Manager` find a `zsh.exe`

**Comment by romkatv** [comment]
It's possible that you are being affected by a bug in Zsh (not in Powerlevel10k) -- https://www.zsh.org/mla/workers/2020/msg00207.html. To work around this bug, close VS Code terminal by pressing <kbd>Ctrl+D</kbd> or by typing `exit`. Do not use the trash icon to close VS Code terminal.

Could you confirm that this workaround work for you?

**Comment by wszgrcy** [comment]
> It's possible that you are being affected by a bug in Zsh (not in Powerlevel10k) -- https://www.zsh.org/mla/workers/2020/msg00207.html. To work around this bug, close VS Code terminal by pressing Ctrl+D or by typing `exit`. Do not use the trash icon to close VS Code terminal.
> 
> Could you confirm that this workaround work for you?

Thanks.It's ok
