### ISSUE TITLE
p9k_widget_hook - bad math expression

### ISSUE THREAD

**Issue by leachim** [romkatv/powerlevel10k#1053]
I am experiencing the following error when listing directories with autocomplete (with both v1.12.0 and v1.13.0). I am using https://github.com/zdharma/zinit for zsh management.

`_p9k_widget_hook:3: bad math expression: operator expected at 'p9k_show_o...'`
`_p9k_widget_hook:5: parse error: condition expected: $langinfo[CODESET]`

Any idea what might cause this? I am happy to provide any debugging information, etc.

**Comment by romkatv** [comment]
Please provide the minimal instructions how to reproduce. Start by removing all other plugins you are using, then removing zinit, etc.

**Comment by romkatv** [comment]
Have you figured out what was wrong? Could you post an update for the benefit of future users who might bump into the same issue?

**Comment by leachim** [comment]
Apologies, I could not find a solution and decided to ignore the problem for the time being. I am busy with other things right now.
