### ISSUE TITLE
No transient option on Ubuntu+prezto

### ISSUE THREAD

**Issue by nWacher** [romkatv/powerlevel10k#1054]
I use powerlevel p10k on both Ubuntu and Mac, however the configuration wizard on Ubuntu doesn't show the option to turn on transient terminal. The p10k.zsh file on mac is also twice as big as the one on Ubuntu (700 vs 1500 lines). I tried copying my config file from mac to ubuntu but it didn't work, I got a message suggesting to run the configuration wizard. Both systems have the latest version of prezto, Mac is running Catalina and iterm2, Ubuntu is vanilla 20.04 running stock terminal, and zsh 5.8 on both.

**Comment by romkatv** [comment]
Please run `p10k configure` on Ubuntu and post a screenshot (or a title) of every screen with an indication of which options you are choosing.

**Comment by nWacher** [comment]
![1](https://user-images.githubusercontent.com/10953535/95776253-941e5200-0c89-11eb-9e7e-8e0ab3220770.png)
y
![2](https://user-images.githubusercontent.com/10953535/95776280-a3050480-0c89-11eb-8630-7b75bdc533e4.png)
y
![3](https://user-images.githubusercontent.com/10953535/95776287-a7312200-0c89-11eb-914a-8666f9d00be9.png)
y
![4](https://user-images.githubusercontent.com/10953535/95776306-b3b57a80-0c89-11eb-9556-dc065e6d4e00.png)
y
![5](https://user-images.githubusercontent.com/10953535/95776313-b7490180-0c89-11eb-8469-ab6245f11e74.png)
1
![6](https://user-images.githubusercontent.com/10953535/95776320-b912c500-0c89-11eb-9330-39203873d49e.png)
y
![7](https://user-images.githubusercontent.com/10953535/95776325-badc8880-0c89-11eb-9d6b-0d7775245611.png)
2
![8](https://user-images.githubusercontent.com/10953535/95776332-bca64c00-0c89-11eb-913b-3a57aea2f3ba.png)
1
![9](https://user-images.githubusercontent.com/10953535/95776338-be700f80-0c89-11eb-9133-e2c26f416d83.png)
2
![10](https://user-images.githubusercontent.com/10953535/95776352-c16b0000-0c89-11eb-97f0-6ce8b88bfad6.png)
2
![11](https://user-images.githubusercontent.com/10953535/95776355-c334c380-0c89-11eb-90ca-e11411dd31b4.png)
1
![12](https://user-images.githubusercontent.com/10953535/95776774-97fea400-0c8a-11eb-9dd2-72953fdbb936.png)
y
![13](https://user-images.githubusercontent.com/10953535/95776777-99c86780-0c8a-11eb-810b-97b5b8519748.png)
y
In the end I get these two, the second one is after starting closing and opening a new terminal session:
![14](https://user-images.githubusercontent.com/10953535/95776780-9b922b00-0c8a-11eb-91be-84a962ef223f.png)
![last](https://user-images.githubusercontent.com/10953535/95776787-9e8d1b80-0c8a-11eb-85fe-86e5d8a27c92.png)

**Comment by romkatv** [comment]
You are using a very-very old version of Powerlevel10k on Ubuntu. Once you [update](https://github.com/romkatv/powerlevel10k#how-do-i-update-powerlevel10k) it, restart zsh (with `exec zsh`) and run `p10k configure`, you'll see more options in the wizard.

**Comment by nWacher** [comment]
Got it, it's working. For some reason Prezto was not updating Powerlevel10k while running 'prezto update' or even updating it through git (it showed as up to date). I removed it and installed again, and now it's working without any problems. Thank you.
