### ISSUE TITLE
Git status stopped showing in home directory

### ISSUE THREAD

**Issue by infokiller** [romkatv/powerlevel10k#1057]
Hi,

I recently noticed that the git status stopped showing in my home directory (which is a git repo for tracking dotfiles). My tests show that:
- It works in other repos other than my homedir (including submodules from my dotfiles repo).
- It works with the bash prompt (using `gitstatus.plugin.sh`)
- It works with the default p10k prompt you get if you don't source `p10k.zsh` and then use "quit" when the wizard starts:

![image](https://user-images.githubusercontent.com/10516814/96165646-943a7e00-0f25-11eb-860d-812d9d370458.png)

I'm able to reproduce this with a `.zshrc` that only contains the p10k lines, i.e.:

```zsh
source /tmp/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/tmp/zsh-git-prompt-fix//.p10k.zsh.
[[ ! -f ~/tmp/zsh-git-prompt-fix/.p10k.zsh ]] || source ~/tmp/zsh-git-prompt-fix//.p10k.zsh
```

Zsh version: `zsh 5.8 (x86_64-pc-linux-gnu)`
Powerlevel10k version: reproducible both on current master and `v.13.0`.

Any tips on how to debug this?

Thanks!

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#why-is-git-status-from-homegit-not-displayed-in-prompt

**Comment by infokiller** [comment]
Thanks! I actually went through the whole troubleshooting section and missed the other FAQ... sorry!

**Comment by romkatv** [comment]
No worries. Your issue description was very clear.  It took me less than a minute to link read through and to link the relevant faq. If only all issues were like that.
