### ISSUE TITLE
Instant prompt missing script

### ISSUE THREAD

**Issue by JordanMartin** [romkatv/powerlevel10k#1060]
Hello, 

I juste install p10k and want to enable the instant prompt feature. I use the WSL with Ubuntu.
I've added these lines at the top of the `.zshrc` file :
```bash
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

But it did not works beacause the file `$HOME/.cache/p10k-instant-prompt-myusername.zsh` don't exists.

Do you know why this file is missing and how I can get it ?

**Comment by romkatv** [comment]
Have you tried enabling it via `p10k configure`?

**Comment by JordanMartin** [comment]
Yes I try it but the there is no configuration about this setting for me : 

![p10k](https://user-images.githubusercontent.com/5437374/96374632-19b36d80-1174-11eb-831c-2669f38d8539.gif)

**Comment by romkatv** [comment]
Instant prompt requires Zsh >= 5.4. What is the output of the following command?

```zsh
typeset -p ZSH_VERSION; is-at-least 5.4 && echo good || echo too old
```

**Comment by JordanMartin** [comment]
My bad i'm running 5.1... I miss that in the doc.
Thanks for your fast answer :)
