### ISSUE TITLE
Kubernetes segment doesn't work if current-context contains quotes

### ISSUE THREAD

**Issue by t0ch1k** [romkatv/powerlevel10k#1061]
If there's something like `current-context: "111222"` in ~/.kube/config the Kubernetes segment stops working. The pattern on [this line](https://github.com/romkatv/powerlevel10k/blob/a124a7103236124c95128f71da632f50d426ba7c/internal/p10k.zsh#L4309) returns empty result.

**Comment by romkatv** [comment]
Thanks for the report! Fixed.
