### ISSUE TITLE
Unable to make entire dir bold

### ISSUE THREAD

**Issue by xim** [romkatv/powerlevel10k#1063]
Hi,

recently started using powerlevel10k. The only thing that's bothering me this far is that I can't style the text in dir freely. I'd like the entire thing to be bold, but currently it appears that only `POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD` and `POWERLEVEL9K_DIR_ANCHOR_BOLD` can add boldness.

I could write my own super-simple dir plugin, but I really love the shortening algorithm you're using =)

Additional comment: Rockin' work, really loving the feel of powerlevel10k ♥

**Comment by romkatv** [comment]
You can do this:

```zsh
POWERLEVEL9K_DIR_ANCHOR_BOLD=false
unset POWERLEVEL9K_DIR_ANCHOR_FOREGROUND
unset POWERLEVEL9K_DIR_SHORTENED_FOREGROUND
POWERLEVEL9K_DIR_CONTENT_EXPANSION='%B$P9K_CONTENT%b'
```

This will display the whole directory in bold with the foreground color defined by `POWERLEVEL9K_DIR_FOREGROUND`. Is that good enough?

Keep in mind that many terminals display bold simply as bright, so you can achieve the "bold" effect by using colors 8 through 15. Try it to see how your terminal handles it:

```zsh
print -P '%B%F{4}bold 4%f%b %F{12}regular 12%f'
```

**Comment by xim** [comment]
![image](https://user-images.githubusercontent.com/169057/96555473-1e813a00-12b8-11eb-92a9-08b0642f62d4.png)

I tried reading the source to figure out if there was a way to do that, but couldn't. Great that there was an option that did the trick, @romkatv is my hero ^_^

**Comment by hungngodev** [comment]
I have tried to paste that code in but it won't make the folder name bold.
