### ISSUE TITLE
How about improve git status?

### ISSUE THREAD

**Issue by Santinell** [romkatv/powerlevel10k#1064]
Hello,

Recently I migrated from powerlevel9k, and one thing
make me sad - I need to take care about new dotfile with big amount of lines.
I would prefer to generate it on new machine, and use my settings from .zshrc which will have
more priority or at least will be passed after `[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh` and rewrite default settings.

I would be able to do it, if not hard-coded icons in `my_git_formatter`.
I suggest to improve default function `my_git_formatter` with using `POWERLEVEL9K_VCS_*_ICON`
I faced with problem that not all statuses has icon in `POWERLEVEL9K_VCS_*_ICON` and I had to use workaround like this:
`${(g::)icons[VCS_STASH_ICON]}`
It would be much easier for users to change icons without rewriting whole function

**Comment by romkatv** [comment]
You can use the original config that you’ve used with powerlevel9k. Prompt will look the same as before.

**Comment by Santinell** [comment]
Yes, I can use it with old style, but I like idea to switch design if I bored of an old one.

I think it's not a big deal to replace ? ! * ~ and other symbols to use variables in `my_git_formatter`

**Comment by romkatv** [comment]
There is no simple way to resolve icons within the formatter function, unfortunately.

**Comment by Santinell** [comment]
Even with symbol values by default? Some styles could be without this variables (Pure for example)
Users could set variables with unicode values and space separation.
For example `POWERLEVEL9K_VCS_STASH_ICON='\u235F '`
Such options allow user have style-independent settings and have predictable result after changing style

**Comment by romkatv** [comment]
> Even with symbol values by default?

Yes. There is no API in powerlevel10k to retrieve icons. There is only an API to resolve and print a single icon with: `p10k segment -ri VCS_STASH_ICON`. Neither `${(g::)POWERLEVEL9K_VCS_STASH_ICON}`, nor `${(g::)POWERLEVEL9K_VCS_STASH_ICON:-"\u235F"}` do the right thing. They are approximations but aren't correct.

> Such options allow user have style-independent settings and have predictable result after changing style

I'm afraid this wouldn't work. Even defining something as simple as `POWERLEVEL9K_DIR_FOREGROUND` after sourcing `~/.p10k.zsh` is not guaranteed to work when you regenerate `~/.p10k.zsh` with different options or even with the same options after updating Powerlevel10k. Moreover, when you update Powerlevel10k, styles and options can disappear from the wizard.

Is it possible that what you are looking for is this?

```zsh
unset POWERLEVEL9K_VCS_CONTENT_EXPANSION
unset POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING
```

Once you unset these parameters, you can configure the vcs segment the same way as in p9k (plus a ton of extensions).

**Comment by Santinell** [comment]
It's too complex for simple configuration to write my own function.
I would better wait until you implement this feature.
Looking forward for it. Thanks for your work.

**Comment by romkatv** [comment]
You can configure the appearance of `vcs` either by defining/editing `my_git_formatter` or by unsetting `POWERLEVEL9K_VCS_CONTENT_EXPANSION` and `POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING` and setting a bunch of `POWERLEVEL9K_*` parameters. Choose your poison.

> I would better wait until you implement this feature.
> Looking forward for it. Thanks for your work.

Which feature do you mean? I've no immediate plans for any changes related to `vcs`.

**Comment by Santinell** [comment]
I mean feature to use several icons in one segment. You said:
```
There is no API in powerlevel10k to retrieve icons. 
```
As I understand it's main problem for using icons in VCS block.

**Comment by romkatv** [comment]
Without this API it's impossible to correctly resolve icons (such as `VCS_STASH_ICON`) in `my_git_formatter`. However, even if this API existed, I don't think it would be a good idea to use it in the default implementation of `my_git_formatter` produced by the configuration wizard because it would make the implementation more complex and thus more difficult to edit. Everything in `~/.p10k.zsh` is meant to be edited by users, and this includes `my_git_formatter`.

So if the API in question was added, you would be able to write your own `my_git_formatter` that resolves icons by name (e.g., `VCS_STASH_ICONS`) instead of specifying them directly (e.g., `'\u235F'`), but given that you don't want to write `my_git_formatter` in the first place, it wouldn't be much help.

**Comment by Santinell** [comment]
My Idea was just put variable to `my_git_formatter`
User can define symbol or icon as he wants in .zshrc after sourcing .p10k.zsh
```
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# * by default
typeset -g POWERLEVEL9K_VCS_STASH_ICON=$icons[VCS_STASH_ICONS] # or any compatible value 
```

and in `my_git_formatter` will be line like this
```
(( VCS_STATUS_STASHES        )) && res+=" ${clean}${POWERLEVEL9K_VCS_STASH_ICON}${VCS_STATUS_STASHES}"
```

**Comment by romkatv** [comment]
> My Idea was just put variables to `my_git_formatter` instead of hard-coded symbols

Do you mean variables such as `POWERLEVEL9K_VCS_STASH_ICON`? As I mentioned, there is no way to correctly resolve `VCS_STASH_ICON` into the actual icon within `my_git_formatter`. Neither `${(g::)POWERLEVEL9K_VCS_STASH_ICON}` nor `${(g::)POWERLEVEL9K_VCS_STASH_ICON:-"\u235F"}` do the right thing. They are approximations but aren't correct.

**Comment by romkatv** [comment]
Closing because this discussion seems to be going in circles.

**Comment by romkatv** [comment]
> Is it possible that what you are looking for is this?
> 
> ```shell
> unset POWERLEVEL9K_VCS_CONTENT_EXPANSION
> unset POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING
> ```
> 
> Once you unset these parameters, you can configure the vcs segment the same way as in p9k (plus a ton of extensions).

:point_up:

**Comment by Santinell** [comment]
As I said before I don't want define my own function for such simple feature as changing icons.
I thought, it should be pretty simple to make it work by default, without dancing with tambourine.

Maybe we can put switcher: icons/symbols to wizard?
If it's impossible at all and never be implemented then it's very sad.

**Comment by romkatv** [comment]
> As I said before I don't want define my own function for such simple feature as changing icons.

That's why I keep quoting the alternative method for configuring `vcs` that doesn't use `my_git_formatter`. Please do try it.

**Comment by Santinell** [comment]
Oh, I am very sorry for misunderstanding.
To make vcs segment looks as it was in powerlevel9k with any generated style I just added this lines
after sourcing ~/.p10k.zsh

```
unset POWERLEVEL9K_VCS_CONTENT_EXPANSION
unset POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING
unset POWERLEVEL9K_ICON_PADDING
```

Thanks for your help!

**Comment by romkatv** [comment]
Phew! I'm glad this has been resolved.
