### ISSUE TITLE
Pyenv-virtualenv

### ISSUE THREAD

**Issue by usmcfiredog** [romkatv/powerlevel10k#1067]
Is there a way to hide the python version number and only display the pyenv-virtualenv name that was set, when using pyenv to control virtual environments.

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_PYENV_CONTENT_EXPANSION` and change its value like this:

```zsh
typeset -g POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${P9K_CONTENT}'
```

See comments above for the explanation.

**Comment by usmcfiredog** [comment]
Thank you
