### ISSUE TITLE
on loading 

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#1069]
Hi, I don’t know what this “loading” means, and where are its options, can you tell me😅
![IMG_20201024_211409](https://user-images.githubusercontent.com/61009000/97082671-030e8a00-163e-11eb-8512-3df5d959e5a9.jpg)

**Comment by romkatv** [comment]
1. Run this: `GITSTATUS_LOG_LEVEL=DEBUG zsh`.
2. Type `echo $GITSTATUS_DAEMON_LOG_POWERLEVEL9K`. It will print the name of a log file.
3. Attach that file to this issue.

**Comment by 26chk** [comment]
> 1. 运行此：`GITSTATUS_LOG_LEVEL=DEBUG zsh`。
> 2. 输入`echo $GITSTATUS_DAEMON_LOG_POWERLEVEL9K`。它将打印日志文件的名称。
> 3. 将该文件附加到此问题。



+_gitstatus_daemon_p9k_:3> local pgid=10172
+_gitstatus_daemon_p9k_:4> [[ 10172 == <1-> ]]
+_gitstatus_daemon_p9k_:5> cd -q /
+_gitstatus_daemon_p9k_:9> trap '' PIPE
+_gitstatus_daemon_p9k_:11> local uname_sm
+_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
+_gitstatus_daemon_p9k_:93> zsystem flock -- /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10368.10122.1603546472.2.lock
+_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
+_gitstatus_daemon_p9k_:12> uname_sm='linux aarch64' 
+_gitstatus_daemon_p9k_:13> [[ 'linux aarch64' == [^\ ]##\ [^\ ]## ]]
+_gitstatus_daemon_p9k_:14> local uname_s=linux
+_gitstatus_daemon_p9k_:15> local uname_m=aarch64
+_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
+_gitstatus_daemon_p9k_:20> local cpus
+_gitstatus_daemon_p9k_:21> ((  ! 1  ))
+_gitstatus_daemon_p9k_:21> [[ linux == linux ]]
+_gitstatus_daemon_p9k_:23> ((  ! 0  ))
+_gitstatus_daemon_p9k_:24> cpus=8 
+_gitstatus_daemon_p9k_:27> args+=( -t 16 ) 
+_gitstatus_daemon_p9k_:30> mkfifo -- /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10368.10122.1603546472.2.fifo
+_gitstatus_daemon_p9k_:31> print -rnu 15 -- '               10172'
+_gitstatus_daemon_p9k_:33> zf_rm -- /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10368.10122.1603546472.2.fifo
+_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
+_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
+_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
+_gitstatus_daemon_p9k_:45> set -- -d /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s linux -m aarch64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
+_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
+_gitstatus_daemon_p9k_:48> source /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
+/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:403> [ -z '' ']'
+/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:404> _gitstatus_install_main /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -d /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s linux -m aarch64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
+_gitstatus_install_main:1> [ -n 5.8 ']'
+_gitstatus_install_main:2> emulate -L sh -o no_unset
+_gitstatus_install_main:7> local argv1=/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
+_gitstatus_install_main:8> shift
+_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status=''
+_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
+_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s linux -m aarch64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
+_gitstatus_install_main:14> case d (h)
+_gitstatus_install_main:14> case d (n)
+_gitstatus_install_main:14> case d (f)
+_gitstatus_install_main:14> case d (d)
+_gitstatus_install_main:54> [ -n '' ']'
+_gitstatus_install_main:58> [ -z /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus ']'
+_gitstatus_install_main:62> gitstatus_dir=/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus 
+_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s linux -m aarch64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
+_gitstatus_install_main:14> case s (h)
+_gitstatus_install_main:14> case s (n)
+_gitstatus_install_main:14> case s (f)
+_gitstatus_install_main:14> case s (d)
+_gitstatus_install_main:14> case s (p)
+_gitstatus_install_main:14> case s (m)
+_gitstatus_install_main:14> case s (s)
+_gitstatus_install_main:87> [ -n '' ']'
+_gitstatus_install_main:91> [ -z linux ']'
+_gitstatus_install_main:95> uname_s=linux 
+_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s linux -m aarch64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
+_gitstatus_install_main:14> case m (h)
+_gitstatus_install_main:14> case m (n)
+_gitstatus_install_main:14> case m (f)
+_gitstatus_install_main:14> case m (d)
+_gitstatus_install_main:14> case m (p)
+_gitstatus_install_main:14> case m (m)
+_gitstatus_install_main:76> [ -n '' ']'
+_gitstatus_install_main:80> [ -z aarch64 ']'
+_gitstatus_install_main:84> uname_m=aarch64 
+_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s linux -m aarch64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
+_gitstatus_install_main:14> case p (h)
+_gitstatus_install_main:14> case p (n)
+_gitstatus_install_main:14> case p (f)
+_gitstatus_install_main:14> case p (d)
+_gitstatus_install_main:14> case p (p)
+_gitstatus_install_main:65> [ -n '' ']'
+_gitstatus_install_main:69> [ -z 'printf . >&15' ']'
+_gitstatus_install_main:73> dl_status='printf . >&15' 
+_gitstatus_install_main:13> getopts :s:m:d:p:fnh opt -d /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s linux -m aarch64 -p 'printf . >&15' -- _gitstatus_set_daemon_p9k_
+_gitstatus_install_main:103> shift 9
+_gitstatus_install_main:105> : /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
+_gitstatus_install_main:107> [ -n '' -a -n '' ']'
+_gitstatus_install_main:112> [ -z linux ']'
+_gitstatus_install_main:116> [ -z aarch64 ']'
+_gitstatus_install_main:121> local daemon=''
+_gitstatus_install_main:122> local cache_dir=/data/data/com.termux/files/home/.cache/gitstatus
+_gitstatus_install_main:124> [ -z '' ']'
+_gitstatus_install_main:125> [ -n '' ']'
+_gitstatus_install_main:129> [ -z '' -a -e /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
+_gitstatus_install_main:132> [ -n '' ']'
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='' 
+_gitstatus_install_main:149> [ -n '' ']'
+_gitstatus_install_main:149> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="c96baef70b81b5a1d46adcc9e93721eaf4bdc295562bdd2baf210a6b416b9911";' 
+_gitstatus_install_main:149> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="c96baef70b81b5a1d46adcc9e93721eaf4bdc295562bdd2baf210a6b416b9911";' ']'
+_gitstatus_install_main:151> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
+_gitstatus_install_main:152> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="c96baef70b81b5a1d46adcc9e93721eaf4bdc295562bdd2baf210a6b416b9911";'
+_gitstatus_install_main:152> uname_s_glob=cygwin_nt-10.0 
+_gitstatus_install_main:152> uname_m_glob=i686 
+_gitstatus_install_main:152> file=gitstatusd-linux-aarch64 
+_gitstatus_install_main:152> version=v1.3.1 
+_gitstatus_install_main:152> sha256=c96baef70b81b5a1d46adcc9e93721eaf4bdc295562bdd2baf210a6b416b9911 
+_gitstatus_install_main:154> [ -z cygwin_nt-10.0 -o -z i686 -o -z gitstatusd-linux-aarch64 -o -z v1.3.1 -o -z c96baef70b81b5a1d46adcc9e93721eaf4bdc295562bdd2baf210a6b416b9911 ']'
+_gitstatus_install_main:163> case linux (cygwin_nt-10.0)
+_gitstatus_install_main:163> case linux (*)
+_gitstatus_install_main:165> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="18b5be49f6eb9ff1cf25e76d6f2333c7402e686e05ce5b88ca107c80504210d8";' 
+_gitstatus_install_main:149> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="18b5be49f6eb9ff1cf25e76d6f2333c7402e686e05ce5b88ca107c80504210d8";' ']'
+_gitstatus_install_main:151> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
+_gitstatus_install_main:152> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="18b5be49f6eb9ff1cf25e76d6f2333c7402e686e05ce5b88ca107c80504210d8";'
+_gitstatus_install_main:152> uname_s_glob=cygwin_nt-10.0 
+_gitstatus_install_main:152> uname_m_glob=x86_64 
+_gitstatus_install_main:152> file=gitstatusd-linux-aarch64 
+_gitstatus_install_main:152> version=v1.3.1 
+_gitstatus_install_main:152> sha256=18b5be49f6eb9ff1cf25e76d6f2333c7402e686e05ce5b88ca107c80504210d8 
+_gitstatus_install_main:154> [ -z cygwin_nt-10.0 -o -z x86_64 -o -z gitstatusd-linux-aarch64 -o -z v1.3.1 -o -z 18b5be49f6eb9ff1cf25e76d6f2333c7402e686e05ce5b88ca107c80504210d8 ']'
+_gitstatus_install_main:163> case linux (cygwin_nt-10.0)
+_gitstatus_install_main:163> case linux (*)
+_gitstatus_install_main:165> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="26d582fe9a0b2090c28e84e5e32a6d42d6988cedff51e41ec5f789512c53b0fc";' 
+_gitstatus_install_main:149> [ -n 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="26d582fe9a0b2090c28e84e5e32a6d42d6988cedff51e41ec5f789512c53b0fc";' ']'
+_gitstatus_install_main:151> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
+_gitstatus_install_main:152> eval 'uname_s_glob="darwin";         uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="26d582fe9a0b2090c28e84e5e32a6d42d6988cedff51e41ec5f789512c53b0fc";'
+_gitstatus_install_main:152> uname_s_glob=darwin 
+_gitstatus_install_main:152> uname_m_glob=x86_64 
+_gitstatus_install_main:152> file=gitstatusd-linux-aarch64 
+_gitstatus_install_main:152> version=v1.3.1 
+_gitstatus_install_main:152> sha256=26d582fe9a0b2090c28e84e5e32a6d42d6988cedff51e41ec5f789512c53b0fc 
+_gitstatus_install_main:154> [ -z darwin -o -z x86_64 -o -z gitstatusd-linux-aarch64 -o -z v1.3.1 -o -z 26d582fe9a0b2090c28e84e5e32a6d42d6988cedff51e41ec5f789512c53b0fc ']'
+_gitstatus_install_main:163> case linux (darwin)
+_gitstatus_install_main:163> case linux (*)
+_gitstatus_install_main:165> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='uname_s_glob="freebsd";        uname_m_glob="amd64";   file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="54a823373458a0908187ba8d1c5b8921015c844811916451674cc09fbdff88bb";' 
+_gitstatus_install_main:149> [ -n 'uname_s_glob="freebsd";        uname_m_glob="amd64";   file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="54a823373458a0908187ba8d1c5b8921015c844811916451674cc09fbdff88bb";' ']'
+_gitstatus_install_main:151> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
+_gitstatus_install_main:152> eval 'uname_s_glob="freebsd";        uname_m_glob="amd64";   file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="54a823373458a0908187ba8d1c5b8921015c844811916451674cc09fbdff88bb";'
+_gitstatus_install_main:152> uname_s_glob=freebsd 
+_gitstatus_install_main:152> uname_m_glob=amd64 
+_gitstatus_install_main:152> file=gitstatusd-linux-aarch64 
+_gitstatus_install_main:152> version=v1.3.1 
+_gitstatus_install_main:152> sha256=54a823373458a0908187ba8d1c5b8921015c844811916451674cc09fbdff88bb 
+_gitstatus_install_main:154> [ -z freebsd -o -z amd64 -o -z gitstatusd-linux-aarch64 -o -z v1.3.1 -o -z 54a823373458a0908187ba8d1c5b8921015c844811916451674cc09fbdff88bb ']'
+_gitstatus_install_main:163> case linux (freebsd)
+_gitstatus_install_main:163> case linux (*)
+_gitstatus_install_main:165> continue
+_gitstatus_install_main:147> IFS='' +_gitstatus_install_main:147> read -r line
+_gitstatus_install_main:148> line='uname_s_glob="linux";          uname_m_glob="aarch64"; file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="4e0a506eafb14b009cf6670f0e11399ac7e765cad17b9fcf38ef65516d248bfa";' 
+_gitstatus_install_main:149> [ -n 'uname_s_glob="linux";          uname_m_glob="aarch64"; file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="4e0a506eafb14b009cf6670f0e11399ac7e765cad17b9fcf38ef65516d248bfa";' ']'
+_gitstatus_install_main:151> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
+_gitstatus_install_main:152> eval 'uname_s_glob="linux";          uname_m_glob="aarch64"; file="gitstatusd-${uname_s}-${uname_m}";     version="v1.3.1"; sha256="4e0a506eafb14b009cf6670f0e11399ac7e765cad17b9fcf38ef65516d248bfa";'
+_gitstatus_install_main:152> uname_s_glob=linux 
+_gitstatus_install_main:152> uname_m_glob=aarch64 
+_gitstatus_install_main:152> file=gitstatusd-linux-aarch64 
+_gitstatus_install_main:152> version=v1.3.1 
+_gitstatus_install_main:152> sha256=4e0a506eafb14b009cf6670f0e11399ac7e765cad17b9fcf38ef65516d248bfa 
+_gitstatus_install_main:154> [ -z linux -o -z aarch64 -o -z gitstatusd-linux-aarch64 -o -z v1.3.1 -o -z 4e0a506eafb14b009cf6670f0e11399ac7e765cad17b9fcf38ef65516d248bfa ']'
+_gitstatus_install_main:163> case linux (linux)
+_gitstatus_install_main:167> case aarch64 (aarch64)
+_gitstatus_install_main:174> [ -z '' ']'
+_gitstatus_install_main:176> local daemon=/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-aarch64
+_gitstatus_install_main:177> [ ! -e /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-linux-aarch64 ']'
+_gitstatus_install_main:178> daemon=/data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 
+_gitstatus_install_main:179> [ -e /data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 ']'
+_gitstatus_install_main:181> [ -n /data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 ']'
+_gitstatus_install_main:182> [ 1 '=' 0 ']'
+_gitstatus_install_main:182> _gitstatus_set_daemon_p9k_ /data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 v1.3.1 0
+_gitstatus_set_daemon_p9k_:1> _gitstatus_zsh_daemon=/data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 
+_gitstatus_set_daemon_p9k_:2> _gitstatus_zsh_version=v1.3.1 
+_gitstatus_set_daemon_p9k_:3> _gitstatus_zsh_downloaded=0 
+_gitstatus_install_main:183> return
+_gitstatus_daemon_p9k_:49> [[ -n /data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 ]]
+_gitstatus_daemon_p9k_:50> [[ -n v1.3.1 ]]
+_gitstatus_daemon_p9k_:51> [[ 0 == [01] ]]
+_gitstatus_daemon_p9k_:53> ((  UID == EUID  ))
+_gitstatus_daemon_p9k_:54> local home=/data/data/com.termux/files/home
+_gitstatus_daemon_p9k_:62> [[ -x /data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 ]]
+_gitstatus_daemon_p9k_:63> HOME=/data/data/com.termux/files/home /data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64 -G v1.3.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 16
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[0]: "/data/data/com.termux/files/home/.cache/gitstatus/gitstatusd-linux-aarch64"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[1]: "-G"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[2]: "v1.3.1"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[3]: "-s"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[4]: "-1"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[5]: "-u"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[6]: "-1"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[7]: "-d"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[8]: "-1"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[9]: "-c"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[10]: "-1"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[11]: "-m"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[12]: "-1"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[13]: "-v"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[14]: "DEBUG"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[15]: "-t"
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:177] argv[16]: "16"
[2020-10-24 13:34:32 00000074e998e610 INFO src/thread_pool.cc:81] Spawning 16 thread(s)
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:192] Processing request: "hello" for ""
[2020-10-24 13:34:32 00000074e998e610 INFO src/response.cc:69] Replying without git status
+_gitstatus_daemon_p9k_:93> [[ -e /data/data/com.termux/files/usr/tmp/gitstatus.POWERLEVEL9K.10368.10122.1603546472.2.lock ]]
[2020-10-24 13:34:32 00000074e998e610 INFO src/timer.cc:67] Timing for: request: 0ms cpu, 1.64375ms wall
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:195] Successfully processed request: "hello" for ""
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:192] Processing request: "1603546472.5277655125 _p9k_vcs_resume 0" for "/data/data/com.termux/files/home" [no-diff]
[2020-10-24 13:34:32 00000074e998e610 INFO src/response.cc:69] Replying without git status
[2020-10-24 13:34:32 00000074e998e610 INFO src/timer.cc:67] Timing for: request: 0ms cpu, 0.913021ms wall
[2020-10-24 13:34:32 00000074e998e610 INFO src/gitstatus.cc:195] Successfully processed request: "1603546472.5277655125 _p9k_vcs_resume 0" for "/data/data/com.termux/files/home" [no-diff]
[2020-10-24 13:34:40 00000074e998e610 INFO src/gitstatus.cc:192] Processing request: "1603546480.5925774574 _p9k_vcs_resume 0" for "/data/data/com.termux/files/home" [no-diff]
[2020-10-24 13:34:40 00000074e998e610 INFO src/response.cc:69] Replying without git status
[2020-10-24 13:34:40 00000074e998e610 INFO src/timer.cc:67] Timing for: request: 0ms cpu, 0.184896ms wall
[2020-10-24 13:34:40 00000074e998e610 INFO src/gitstatus.cc:195] Successfully processed request: "1603546480.5925774574 _p9k_vcs_resume 0" for "/data/data/com.termux/files/home" [no-diff]

**Comment by romkatv** [comment]
There are no errors in the log file. I don't know why you see "loading". Try reinstalling powerlevel10k or something like that. If that doesn't work, please debug it yourself.
