### ISSUE TITLE
git branch drops me in to a temporary buffer

### ISSUE THREAD

**Issue by elsigh** [romkatv/powerlevel10k#1072]
This is maybe intentional, but when I run `git branch` I end up in a buffer that closes on me and it's odd if I want to git branch -D a few where I have to keep going back to that buffer experience vs just scroll up - is that configurable?

**Comment by romkatv** [comment]
Powerlevel10k does not affect the behavior of `git` command in any way. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect. You can verify this by disabling Powerlevel10k.
