### ISSUE TITLE
Missing k8s namespace 

### ISSUE THREAD

**Issue by motizzz** [romkatv/powerlevel10k#1074]
Hi, 
i am using powerlevel10k with 
POWERLEVEL9K_KUBECONTEXT_SHORTEN=(gke eks)
<img width="1436" alt="Screen Shot 2020-10-27 at 9 11 53 AM" src="https://user-images.githubusercontent.com/73519463/97268441-93aebb00-1834-11eb-916c-b70b6bfd12ab.png">

i would like to know how to show the namespace as well and how i can change the color ? 

thanks in advance

**Comment by romkatv** [comment]
Are you using a config created for Powerlevel9k (note "9k")? If so, I highly recommend running `p10k configure` to create a more modern config. Then you can open `~/.p10k.zsh`, search for "kubecontext" and edit the related parameters: https://github.com/romkatv/powerlevel10k/blob/54d40b924c491a6510c44391dccac05fe78a7310/config/p10k-rainbow.zsh#L1245-L1332

If you want to keep your own config, see the parameters referenced above together with their comments and apply them to your config as you see fit.

**Comment by romkatv** [comment]
It's likely that the config created by `p10k configure` will do what you want without having to change anything related to `kubecontext`. Give it a try. Note that by default `kubecontext` will be shown only when the current command you are typing makes use of kubernetes (e.g., `kubectl`).

**Comment by motizzz** [comment]
works! 
thanks  @romkatv
