### ISSUE TITLE
Transient prompt - modify prompt before

### ISSUE THREAD

**Issue by weilbith** [romkatv/powerlevel10k#1076]
Hey,
thanks for you great work here! :pray: 

I just tried the cool transient prompt feature. It just works, no bugs or anything, great feature.
I have customized the `prompt_char` segment. Unfortunately this does not work well when it gets "transformed" into the transient prompt. In fact I get a single gray character (from a nerd font) that is hard to see. I use a partially transparent terminal background and eventually this amplifies the issue, but I guess it is similar problematic on black backgrounds or other colors as well. After all the lines in the history which where commands and not a commands output are incredibly hard to identify. Usually just by their syntax highlighting which is not so much of a help for the common short commands.
So I was wondering if it is eventually possible to use something different as prompt for the transient prompt? So I could change it to something else that is easier to see, or maybe even some coloring while the rest of the (prompt) still "disappears"? I hope you get the direction of what I would like to be able to do. Anything you could help me with?
Thank you!!

**Comment by romkatv** [comment]
Please post your Powerlevel10k config (usually this is `~/.p10k.zsh`).

**Comment by weilbith** [comment]
It is still under construction but [here](https://github.com/weilbith/dotfiles/blob/ansible/roles/powerlevel10k/files/configuration/config.zsh) you can see the current version I use in a test environment.

**Comment by romkatv** [comment]
1. Open your config and set `typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off`.
2. Add this to the config:
   ```zsh
   function p10k-on-pre-prompt() {
     p10k display 'empty_line|1'=show
   }
   
   function p10k-on-post-prompt() {
     if [[ $PWD == ${my_last_dir-} ]]; then
       p10k display 'empty_line|1'=hide
     fi
     typeset -g my_last_dir=$PWD
   }
   ```

See `p10k help display` for help.

---

> ```zsh
> virtualenv pyenv # Which one?
> nodenv nvm nodeenv # Which one?
> ```

Do you use pyenv, nodenv, nvm, nodenv, etc? If not, you can remove them because these segments won't show anything. The original config had links to the projects to let you know what `nvm` and others are.

> ```zsh
> ranger vim_shell # What is that?
> ```

The original config had explanations. These are indicators that you are in a ranger shell and vim shell respectively. If you don't use ranger shell or vim shell, they won't show anything, so you can remove them.

> ```zsh
> typeset -gA __p9k_vcs_states=(
>   'CLEAN'         '81'
>   'MODIFIED'      '3'
>   'UNTRACKED'     '32'
>   'LOADING'       '239'
>   'CONFLICTED'    '197'
>)
> ```

It's a bad idea to refer (yet alone modify) internal, undocumented parameters. Use the public API instead.

```zsh
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=81
```

**Comment by weilbith** [comment]
> 
    Open your config and set typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off.
    Add this to the config:
    ...

Awesome! Thanks for your great and fast help. :ok_hand: 

> It's a bad idea to reference (let alone modify) internal, undocumented parameters. Use the public API instead.

Sorry I was not aware of these variables and I just found that definition in the code itself. :see_no_evil: 
Adopted it now. This is the much more favorable configuration approach. :+1:

**Comment by weilbith** [comment]
One question not strongly related to this PR, but I don't know here else to ask:
What is the `VIOWR` mode for the prompt char segment? I only know [these](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Keymaps) from the docs.

**Comment by romkatv** [comment]
Enter command mode and press `R` (that is, <kbd>Shift+R</kbd>). Now you can type over the existing text.

**Comment by weilbith** [comment]
Okay it relates to overwrite. I had that in mind (from you code) and tried it, but his simply shows the `viins` mode for me. Despite the color I checked `echo $POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_CONTENT_EXPANSION`. It gives me `VIOWR` (I set this for test purpose to see it when it appears. But instead I just see the prompt for my configured insert mode. That's why I was confused.

**Comment by romkatv** [comment]
This is because you've removed `POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true`. It was present in the original config but not in yours.

**Comment by weilbith** [comment]
Oh okay.
Thanks for your kind help! :pray:
