### ISSUE TITLE
[Feature Request] Add Mullvad VPN support

### ISSUE THREAD

**Issue by M4lik** [romkatv/powerlevel10k#1078]
I saw that there is a prompt for nordvpn, and I was wondering if it would be possible to also add one for mullvad.
I sadly have no real experience with zsh scripting, but found the part for nordvpn [here](https://github.com/romkatv/powerlevel10k/blob/aa6d40b733280f154d9a55383f5efb6cf01a7a2a/internal/p10k.zsh#L4577) but as i don't know how to use sockets either....

There is also a executable (on my machine at /bin/mullvad) that could be used.
Here are the statuses that `mullvad status` can return
```
# When using WireGuard
Tunnel status: Connecting to WireGuard <IP>:<PORT> over UDP...
Tunnel status: Connected to WireGuard <IP>:<PORT> over UDP

# When using OVPN
Tunnel status: Connecting to WireGuard <IP>:<PORT> over UDP...
Tunnel status: Connected to WireGuard <IP>:<PORT> over UDP

# Independent
Tunnel status: Disconnecting...
Tunnel status: Disconnected

# On error
Tunnel status: Blocked: <Some Error Here (e.g. "Failed to set system DNS server")>
```

I guess that the "over UDP" changes if you set it to TCP, but I have not tried that out yet.

**Comment by romkatv** [comment]
You can implement this through the extension API. Search for "example" in `~/.p10k.zsh`.
