### ISSUE TITLE
Git repo crashing plugin

### ISSUE THREAD

**Issue by Chelayel** [romkatv/powerlevel10k#1080]
Hello,

I am facing the following issue: 
Whenever I go to any git repo on my local machine while running the powerlevel10k theme, wsl2 crashes.
I tried to navigate to those git repos using a different theme and I did not face that issue. 
Can you please help me debug it? Thank you

**Comment by romkatv** [comment]
wsl2 is not supposed to crash like that. I suggest reporting this issue against wsl2.

**Comment by Chelayel** [comment]
okay thank you

**Comment by Chelayel** [comment]
I tested multiple other teams but the crash was only happening with powerlevel10k
The issue is as follows:
I go to a git repo from my command line, the repo opens, tries to show the branch and then the branch disappears from the prompt.
If I write any command on my promt when this happens I will get the following message Input/output error.
As an example I tried using robbyrussell theme and I did not face that issue

**Comment by romkatv** [comment]
So WSL doesn't crash?

**Comment by Chelayel** [comment]
Correct the command line stays open.

**Comment by romkatv** [comment]
Please do the following:

1. Add this line to `~/.zshrc`:
   ```zsh
   GITSTATUS_LOG_LEVEL=DEBUG
   ```
2. Restart zsh with `exec zsh`.
3. Trigger the error.
4. Type `echo $GITSTATUS_DAEMON_LOG_POWERLEVEL9K`. It'll print a file name.
5. Attach that file to this issue.

**Comment by Chelayel** [comment]
[Logs.txt](https://github.com/romkatv/powerlevel10k/files/5460205/Logs.txt)
Please find attached the logs

**Comment by romkatv** [comment]
Here's the error:

```text
[2020-10-29 19:23:57 00007faa719a7c78 ERROR src/repo_cache.cc:52] git_repository_open_ext: "/mnt/c/Development/catalog-service": failed to resolve path '/mnt/c/Development/catalog-service': I/O error
```

This means that `realpath(3)` has failed on this path. Do you know why that may be? What is the output of these commands?

```zsh
ls -ld /mnt/c/Development/catalog-service
realpath /mnt/c/Development/catalog-service
readlink -f /mnt/c/Development/catalog-service
```

By the way, using NTFS from WSL2 is *extremely* slow. If you need to store the repo on NTFS, then WSL1 *much* faster. By a factor of 50 or so. WSL2 is a good choice if you don't need NTFS and can store all files on the Linux partition.

**Comment by Chelayel** [comment]
Below is the ouput of each command
`ls -ld /mnt/c/Development/catalog-service
drwxrwxrwx 1 chelayel chelayel 4096 Oct 29 18:05 /mnt/c/Development/catalog-service`

`realpath /mnt/c/Development/catalog-service
/mnt/c/Development/catalog-service`

`readlink -f /mnt/c/Development/catalog-service
/mnt/c/Development/catalog-service`

I will try to use wsl1 and see if the issue occurs

**Comment by Chelayel** [comment]
Indeed the issue is not reproduceable on wsl1

**Comment by romkatv** [comment]
Thanks for the extra info. Nothing looks unusual there.

I'm going to close this issue as I don't plan to debug it any further. As a workaround, please either use WSL1 or put the Git repository in your home directory.

**Comment by Chelayel** [comment]
just some information: the issue is a WSL issue and is tracked here: https://github.com/microsoft/WSL/issues/6174
adding
`[automount] options = "metadata" `to /etc/wsl.conf seems to fix the issue for now, if anyone faces the same issue

**Comment by romkatv** [comment]
Thanks for the info!
