### ISSUE TITLE
[Question] How to get a specific prompt style with square brackets '[ ]'

### ISSUE THREAD

**Issue by rrobertobt** [romkatv/powerlevel10k#1081]
I want to make my prompt to look a bit different using square brackets for the command prompt, this is an example of what I would like my prompt to look like:
`left_side_elements [ commands go here ] right_side_elements` instead of just `❯` or `$`
Is there any way to get this? I know I can change the `prompt_char` property to the character I want, but I also want to show the opposite `]` in the right side. Is this posible?

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and scroll to the bottom. Add the following code right after the `typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true` line:

```zsh
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' %F{green}[%f'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%F{green}]%f '
unset POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL
```

**Comment by romkatv** [comment]
This assumes that you've ran `p10k configure` and selected Lean style with one line.

**Comment by rrobertobt** [comment]
That's right, and yes, that worked, thanks. Is there a way to make it bold (or set as bright color)?

**Comment by romkatv** [comment]
```zsh
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' %B%F{10}[%f%b'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%B%F{10}]%f%b '
unset POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL
```
