### ISSUE TITLE
bug in split view with iTerm

### ISSUE THREAD

**Issue by LazaroFilm** [romkatv/powerlevel10k#1083]
![Screen Shot 2020-10-30 at 11 45 14 AM](https://user-images.githubusercontent.com/18351100/97726659-d6c39500-1aa5-11eb-9f55-fcdc9c49dc2f.png)

To recreate the issue: Open an iTerm window, split it vertically then resize it by dragging a corner. The issue happens when you shrink the window

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
