### ISSUE TITLE
why hyper config fontFamily: 'MesloLGS NF', Do not show

### ISSUE THREAD

**Issue by jimmyann** [romkatv/powerlevel10k#1084]
I have installed recommended fonts 'MesloLGS NF'
hyper is do not show
<img width="528" alt="QQ20201031-093333@2x" src="https://user-images.githubusercontent.com/18024840/97768167-3c725880-1b5c-11eb-91a8-fce05984d03a.png">
<img width="427" alt="QQ20201031-093345@2x" src="https://user-images.githubusercontent.com/18024840/97768168-3da38580-1b5c-11eb-8ba4-fd3154558f68.png">
 
but item2 is show 
<img width="623" alt="QQ20201031-093645@2x" src="https://user-images.githubusercontent.com/18024840/97768226-9d9a2c00-1b5c-11eb-8fdf-3e6418fb9ad1.png">

**Comment by romkatv** [comment]
Please report this issue to Hyper.
