### ISSUE TITLE
Lengthy test for file: [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

### ISSUE THREAD

**Issue by ratijas** [romkatv/powerlevel10k#1085]
Hi,

I'm sorry if I'm asking super obvious question here, but I'm really curious about this one.

So, I've had [this line](https://github.com/ratijas/dotfiles/blob/37aae5a834100620f6eef2ee0f1ce87b30e25317/tag-zsh/zshrc#L266) in my `.zshrc` for ages, probably for a longer time than I'm using zsh itself — that is to say, the line was likely copied from `.bashrc`:

```zsh
[ -f $HOME/.pythonrc ] && export PYTHONSTARTUP="$HOME/.pythonrc"
```

And this idiom works just fine: test for existence of a certain file, and if it does exist, then source it or whatever. In fact, over the years I've collected many similar lines to provide dynamic support for different environments, where set of available programs is expected to vary, e.g. virtualenvwrapper, command-not-found handler, site-local ssh keys etc.

Now, compare it to the one used in README and by the configuration wizard of Powerlevel10k:

```zsh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

Notice the counter-intuitive double negation: boolean inverse (`!`) and else-branch (`||`); and it also uses double square brackets for condition.

My question is: was there a reason behind it (which I'm not aware of), that more complex and lengthy syntax were used instead of simpler `[ -f ... ] && source ...` ?

**Comment by romkatv** [comment]
Try adding this at the bottom of `~/.zshrc` and restarting zsh with `exec zsh`:

```zsh
[[ ! -f ~/does-not-exist ]] || source ~/does-not-exist
```

Everything looks fine, right? Now try the same but with a different line:

```zsh
[[ -f ~/does-not-exist ]] && source ~/does-not-exist
```

Restart zsh. See the difference?

**Comment by ratijas** [comment]
I assume you're referring to the exit code. Indeed, it is set to 1 when file does not exist, and that 1 appears in a flashy red segment on the right.

And the key point here is that this line must be the last one, i.e. no commands run after it. That explains why my `.zshrc` worked fine with `[ -f ... ]` somewhere in the middle.

The only reasonable alternative would be the following syntax, which is more understandable but much much longer. Interestingly, similar snippet is used for loading the instant prompt, but with `[[ -r ... ]]`.

```zsh
if [ -f ... ]; then
  source ...
fi
```

Amusingly, all kinds of these checks possess inherent race conditions (e.g. the file may be removed, or permissions changed by the time shell attempts to read it), but the whole community seem to be fine with it.

**Comment by romkatv** [comment]
> And the key point here is that this line must be the last one, i.e. no commands run after it.

Correct. And sourcing `~/.p10k.zsh` is quite often the last command.

> The only reasonable alternative would be the following syntax, which is more understandable but much much longer. Interestingly, similar snippet is used for loading the instant prompt, but with `[[ -r ... ]]`.

The instant prompt stanza uses `if` because the file name is long, so `&&` or `||` wouldn't fit on a single line and it doesn't look good when split over two lines.
