### ISSUE TITLE
Some characters stopped rendering after font update by 'p10k configure'

### ISSUE THREAD

**Issue by bdcarr** [romkatv/powerlevel10k#1086]
So I just ran `p10k configure` and it offered to update the Meslo Nerd Fonts. I accepted, it downloaded & installed them in iterm2, and now the icons won't render :(

![image](https://user-images.githubusercontent.com/1940488/97954941-f71e8700-1df8-11eb-9178-f9320402af6a.png)

I answered 'no' to all the questions in `p10k configure` so it's using (lame) alternatives which you can see in the screenshot at the bottom. The top half is the attempt at rendering the restored session from before p10k updated the fonts.

https://gist.github.com/bdcarr/ab26a94ee976626b330af58da5c5191c

https://gist.github.com/bdcarr/f1f499220c40bd9e980f0afcdcab830e

My iterm2 font prefs:
![image](https://user-images.githubusercontent.com/1940488/97955148-9c395f80-1df9-11eb-824b-e067c1c17102.png)

**Comment by romkatv** [comment]
Please close iTerm2 with <kbd>Command+Q</kbd> and start it again.

**Comment by bdcarr** [comment]
I restarted it when prompted (after the font install), that's when the issue started. 

Anyway, I uh, I fixed it by pressing `Command+0`, resetting font size / zoom level. Not sure how it got zoomed out in the first place, but I noticed the font looked different after restarting iTerm2 so I tried that and voila. Weird, thanks for your help!

**Comment by romkatv** [comment]
> I restarted it when prompted (after the font install), that's when the issue started.

Have you restarted it with <kbd>Command+Q</kbd> or by some other means?

**Comment by bdcarr** [comment]
Yep, with cmd+Q. It might not look like it in the screenshot because I have iterm2 set to restore sessions, but you can see the grey band across the screenshot where it restored the session after I restarted.

**Comment by romkatv** [comment]
Hm... Perhaps restarting iTerm2 is not enough to force it to reload settings when it's configured to restore sessions. I'll run some experiments. Thanks for reporting this!
