### ISSUE TITLE
CONEXT Formatter

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/powerlevel10k#109]
Hey so I am trying to change the Kube context to only just show me the namespace and I have this as your suggestions

typeset -g POWERLEVEL9K_KUBECONTEXT_CONTENT_TRANSFORMER='${P9K_CONTENT##*:}'

However, I still get:
┌─08:50:19[boris][aristotle][solutions1:admin:mongo-demo/mongo-demo][master ? ⇣7 *4][~/Sources/charts]                                                                                                     1.00
└─▪
or if i am in default:
┌─08:50:01[boris][aristotle][solutions1:admin:default][master ? ⇣7 *4][~/Sources/charts]                                                                                                                   1.40
└─▪

thoughts?

**Comment by romkatv** [comment]
Are you on the latest version of p10k? `git pull` to be sure.

If you are seeing `solutions1:admin:mongo-demo/mongo-demo` without setting `POWERLEVEL9K_KUBECONTEXT_CONTENT_TRANSFORMER`, then `POWERLEVEL9K_KUBECONTEXT_CONTENT_TRANSFORMER='${P9K_CONTENT##*:}'` will give you `mongo-demo/mongo-demo`. Is this what you want? If not, what is the desired output?

For `solutions1:admin:default` you'll get `default`. Is this what you want?

**Comment by romkatv** [comment]
Do you set `POWERLEVEL9K_KUBECONTEXT_CLASSES`? If so, you'll need to specify `POWERLEVEL9K_KUBECONTEXT_${class}_CONTENT_TRANSFORMER` for every `${class}`.

**Comment by kurktchiev** [comment]
Yeah I pulled the latest changes as of 30mins ago. 

The desired output is to always have: default, mongo-demo, someothername as the output rather than all the other info I don’t care about atm.

I am using pure power and modifying the look of it

**Comment by romkatv** [comment]
> The desired output is to always have: default, mongo-demo, someothername as the output rather than all the other info I don’t care about atm.

If the original string is `solutions1:admin:mongo-demo/mongo-demo`, I understand that you want to see `mongo-demo`. Is this the because there is `mongo-demo` after the slash or because of `mongo-demo` between the last colon and the slash? Basically, there are two natural transforms that will give `mongo-demo` for this string but they will give different strings for `x:y/z`. Do you want `y` or `z` here?

**Comment by kurktchiev** [comment]
I haven’t looked at your code for kubectl but I am assuming you are just doing get context and sadly it’s super noisy and obnoxiously unhelpful info format. All I want at the end of the day is just the namespace I am currently working in and that’s it

**Comment by romkatv** [comment]
Got it. Namespace is the thing after the slash.

These are the default Pure Power settings for `kubecontext`. Please read the comments to understand how context classes work.

```zsh
# Don't show trailing "/default" in kubernetes context.
typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=false
# Kubernetes context classes for the purpose of using different colors with different contexts.
#
# POWERLEVEL9K_KUBECONTEXT_CLASSES is an array with even number of elements. The first element in
# each pair defines a pattern against which the current kubernetes context (in the format it is
# displayed in the prompt) gets matched. The second element defines the context class. Patterns
# are tried in order. The first match wins.
#
# For example, if your current kubernetes context is "deathray-testing", its class is TEST because
# "deathray-testing" doesn't match the pattern '*prod*' but does match '*test*'. Hence it'll be
# shown with the color of $POWERLEVEL9K_KUBECONTEXT_TEST_FOREGROUND.
typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
    '*prod*'  PROD
    '*test*'  TEST
    '*'       DEFAULT)
typeset -g POWERLEVEL9K_KUBECONTEXT_{PROD,TEST,DEFAULT}_BACKGROUND=none
typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND=1
typeset -g POWERLEVEL9K_KUBECONTEXT_TEST_FOREGROUND=2
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=3
typeset -g POWERLEVEL9K_KUBERNETES_ICON=
```

In order to display just the namespace, do the following:

1. Change the value of `POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE` to `true`.
2. Add this:

```zsh
typeset -g POWERLEVEL9K_KUBECONTEXT_{PROD,TEST,DEFAULT}_CONTENT_TRANSFORMER='${P9K_CONTENT:t}'
```

If you don't want to use different colors with different contexts, you need to remove `POWERLEVEL9K_KUBECONTEXT_CLASSES` and change all options. Like this:

```zsh
typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=true
typeset -g POWERLEVEL9K_KUBECONTEXT_CONTENT_TRANSFORMER='${P9K_CONTENT:t}'
typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=none
typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=3
typeset -g POWERLEVEL9K_KUBERNETES_ICON=
```

**Comment by kurktchiev** [comment]
Yeah I have the context classes and like them so I have kept them. I need to double check if I defined the content transformer for all classes or if I messed something up, but I have not changed any options on it other than what you have in there as default

**Comment by romkatv** [comment]
So, did this work?

> In order to display just the namespace, do the following:
> 
> 1. Change the value of `POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE` to `true`.
> 2. Add this:
> 
> ```zsh
> typeset -g POWERLEVEL9K_KUBECONTEXT_{PROD,TEST,DEFAULT}_CONTENT_TRANSFORMER='${P9K_CONTENT:t}'
> ```

If it didn't, please post all your `POWERLEVEL9K` options and a screenshot of your prompt.

**Comment by kurktchiev** [comment]
that did it, thank you!

**Comment by romkatv** [comment]
Thanks for the confirmation!
