### ISSUE TITLE
 configuration wizard keep running. 

### ISSUE THREAD

**Issue by clownlaughinatyou** [romkatv/powerlevel10k#1090]
The configuration wizard keeps triggering every time I start zsh.
here is my .zshrc https://github.com/clownlaughinatyou/dotfiles/commit/ce7862265ca5f20696e0385efacad85f99a10228

**Comment by romkatv** [comment]
Typo here (stray single quote): https://github.com/clownlaughinatyou/dotfiles/commit/ce7862265ca5f20696e0385efacad85f99a10228#diff-4c2d312ff50ee6b26c2cb601fc96a95eceabe4b456831762e5d6caf41b900383R117

More info: https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration-wizard-runs-automatically-every-time-zsh-is-started
