### ISSUE TITLE
bold typeface for the "first" and "last" path segments in dir

### ISSUE THREAD

**Issue by kapad** [romkatv/powerlevel10k#1093]
In my dir segment of my prompt that displays on the left hand side, the first and last elements on the dir are always in bold font. How do I change this so that the entire `dir` segment is either entirely bold or entirely not bold (regular).

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and search for "bold". You'll find the right option soon enough.

**Comment by kapad** [comment]
It was actually a different color that made it look bold. I'd tried
searching bold before raising this issue. The option that finally did need
changing was anchor color.
