### ISSUE TITLE
Prompt segment displaying expanded alias as we type?

### ISSUE THREAD

**Issue by afeblot** [romkatv/powerlevel10k#1095]
Hi,

I was looking for a way to display a right prompt segment displaying the expanded value of an alias, while typing, if the command being typed on the command line would expand as an alias.
It looks like in addition to custom segments, I just miss:
* a way to have the prompt re-evaluated on each keystroke (hoping that would not kill the prompt speed)
* a way to get the command line content or rather the parsed command line containing this command in the function handling this segment.

Is this hope even realistic? I'd be grateful for any suggestion or help.

Thanks

**Comment by romkatv** [comment]
Try adding this to `~/.p10k.zsh`:

```zsh
function prompt_my_alias() {
  p10k segment -b blue -f yellow -e -t '${my_expanded_command//\%/%%}'
}

function p10k-on-post-widget() {
  emulate -L zsh
  local buf=$PREBUFFER$BUFFER
  local words=(${(Z+C+)buf})
  words[1]=$aliases[$words[1]]
  local cmd
  [[ -n $words[1] ]] && cmd="$words"
  if [[ $cmd != $my_expanded_command ]]; then
    my_expanded_command="$cmd"
    p10k display -r
  fi
}

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(my_alias)
```

This code supports only the simple case where the first word on the command is a regular alias. It doesn't support global aliases, suffix aliases, aliases with a trailing space, or complex commands. You can add these features if you like.

See `p10k help segment` and `p10k help display` for help. Everything else in this code is pure zsh, so see zsh manual for help.

**Comment by afeblot** [comment]
This is awesome!
Thank you so much :-)

**Comment by romkatv** [comment]
You are welcome.

**Comment by p1r473** [comment]
@romkatv Ive added this to my ~/.p10k.zsh and nothing seems to happen after reboot/resource
Was I supposed to change anything?

**Comment by romkatv** [comment]
Open a new issue and describe what you are trying to achieve.
