### ISSUE TITLE
Please add step for installing to oh-my-zsh

### ISSUE THREAD

**Issue by LiveSlowSkateFast** [romkatv/powerlevel10k#1096]
The installation steps for oh-my-zsh do not include updating the theme in the `~/.zshrc` file.

I am brand new to zsh and oh-my-zsh

I took a lot of searching to figure out I needed to add this exact theme definition
```ZSH_THEME="powerlevel10k/powerlevel10k"```

**Comment by romkatv** [comment]
From https://github.com/romkatv/powerlevel10k/blob/master/README.md#oh-my-zsh:

> Set `ZSH_THEME="powerlevel10k/powerlevel10k"` in `~/.zshrc`.

How can I make it clearer?

**Comment by LiveSlowSkateFast** [comment]
Oh man that is honestly embarrassing, I re-read the instructions a number of times, not sure how I managed to skip over that :(
As a potential option, giving it steps to make it more clear, but honestly I think this was more a me issue

## Oh My Zsh
1. Clone the theme
```git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k```
Users in mainland China can use the official mirror on gitee.com for faster download.
中国大陆用户可以使用 gitee.com 上的官方镜像加速下载.
```git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k```
1. Set ZSH_THEME="powerlevel10k/powerlevel10k" in ~/.zshrc.
