### ISSUE TITLE
Regression from 9k: Github not recognized 

### ISSUE THREAD

**Issue by arianf** [romkatv/powerlevel10k#1097]
I was trying out 10k with

```bash
git clone https://github.com/romkatv/powerlevel10k.git /tmp/powerlevel10k
source /tmp/powerlevel10k/powerlevel10k.zsh-theme
```

And my Github icon turned into a Git icon once I switched over.

<img width="1082" alt="Screen Shot 2020-11-08 at 11 10 17 AM" src="https://user-images.githubusercontent.com/7397857/98481975-0748b480-21b3-11eb-8160-d7df6ad65a82.png">

```bash
git remote -v                                                            
origin	git@github.foo.example.com:team/test.git (fetch)
origin	git@github.foo.example.com:team/test.git (push)
```

We have an enterprise version of GitHub

**Comment by romkatv** [comment]
When you see the plan `git` icon, type `git pull`. What do you get?

**Comment by arianf** [comment]
Yep it works now! Thanks, closing
