### ISSUE TITLE
powerlevel10k seems to conflict with ohmyzsh's tmux plugin

### ISSUE THREAD

**Issue by HideOnLie** [romkatv/powerlevel10k#1099]
Please see this issue. 
[https://github.com/ohmyzsh/ohmyzsh/issues/9289](https://github.com/ohmyzsh/ohmyzsh/issues/9289)
One guy found that this problem would not occur without this theme. I am very want to report it to you.

**Comment by romkatv** [comment]
Please update powerlevel10k to the latest version and try again.

**Comment by HideOnLie** [comment]
> Please update powerlevel10k to the latest version and try again.

I have been git pull in gitee's repo before. Today, I delete it and pull new powerlevel10k from github. it can run normoaly!!! Maybe gitee's repositories are not in sync yet. Next time I will check the problem after updating.Thank~

**Comment by romkatv** [comment]
> Maybe gitee's repositories are not in sync yet.

I've updated https://gitee.com/romkatv/powerlevel10k/. You can use **that** if it's faster.

**Comment by StayPirate** [comment]
I ma not using `ohmyzsh`, but I get the same error.
I have Powerlevel10k instant prompt enabled at the beginning of my `.zshrc`
```bash
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```
and I start tmux at the end of `.zshrc`
```bash
if [ -z "$TMUX" ]; then
  tmux new-session -A -s workspace
fi
```
If I either remove one of the two above snippets (instant prompt or tmux autostart) I don't get any issue. In case both of them are present in the `.zshrc` then I get the following message:
```
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.config/zsh/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

open terminal failed: not a terminal
``` 

Can you please help me to understand why this is happening?

Thanks in advance.

**Comment by romkatv** [comment]
Please open an issue instead of commenting on a closed issue that isn’t the same as what you experience.

**Comment by imavroukakis** [comment]
Apologies for commenting on the closed issue, but I think this is occurring again. 
What is happening is as follows: 

Start iTerm - session fails
Start new session - works fine
Start another session - session fails

The pattern here is, that every *other* session seems to fail. Not using the ohmyzsh plugin fixes the issue, but I am at a loss as to whether this is some sort of bad interaction between the ohmyzsh tmux plugin and the theme, or something else entirely.

**Comment by romkatv** [comment]
@imavroukakis Please open a new issue. Attach all your configs.

**Comment by imavroukakis** [comment]
Will do, what do you require? .zshrc and tmux.conf ?

**Comment by romkatv** [comment]
Attach what you believe is enough to reproduce it. We’ll go from there.
