### ISSUE TITLE
Icons disappearing

### ISSUE THREAD

**Issue by terencode** [romkatv/powerlevel10k#11]
## Description

When first opening a session, all looks normal but after going into the root of the home dir (or just pressing return without changing directory): 
- the left prompt `HOME_ICON` disappear but reappear on any directory other than home.
- the right prompt  `LOAD_ICON` disappear but never reappear.
- The left prompt `LAST_PROMPT_PREFIX` is replaced by a faded grey icon nonsense and reappear on any directory other than home.

## Preview
![image](https://user-images.githubusercontent.com/12665563/54148155-04bd1700-4434-11e9-8488-203c88020ff7.png)

## Powerlevel9K config
```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" \uF101 "
POWERLEVEL9K_LOAD_ICON="\uF0AE"
POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=false
POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=80
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='white'
POWERLEVEL9K_DIR_BACKGROUND='black'
POWERLEVEL9K_FAIL_ICON="\uF140"
POWERLEVEL9K_DIR_HOME_FOREGROUND='black'
POWERLEVEL9K_HOME_ICON="\uF303"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status load time disk_usage ssh background_jobs command_execution_time virtualenv vpn_ip)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_MODE='nerdfont-fontconfig'

**Comment by romkatv** [comment]
Your config works for me. There may be interference with something else you have. Maybe you sourced powerlevel10k together with powerlevel9k?

Does it work if you open a clean zsh shell with `zsh -df`, paste your config into console and then `source powerlevel10k.zsh-theme`? If no, please send me the results of `uname -a` and `zsh --version`. If it does work, try to figure out what in your config causes interference with the prompt (basically enable/disable plugins one by one).

**Comment by terencode** [comment]
I can confirm I have no problem with a clean zsh shell.
I'm using oh-my-zsh and my icons are not hardcoded bu using variables like `$i_fa_angle_double_right`from NerdFonts

**Comment by terencode** [comment]
The culprit is using variables holding the unicode charaters. What are you doing it that messes it up compared to 9k ?

**Comment by romkatv** [comment]
> The culprit is using variables holding the unicode charaters.

Can you explain how to reproduce?

**Comment by terencode** [comment]
> > The culprit is using variables holding the unicode charaters.
> 
> Can you explain how to reproduce?

1. Install https://github.com/ryanoasis/nerd-fonts
2. Make sure the following files are installed or add them manually to your font directory (e.g. ~/.local/share/fonts) : https://github.com/ryanoasis/nerd-fonts/tree/master/bin/scripts/lib
3. Source i_all.sh : (e.g. source  $HOME/.local/share/fonts/i_all.sh)
4. Use the following config file:
```
export DEFAULT_USER="$USER"  # will not display context when using the default user
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" \u"$i_fa_angle_double_right" "
POWERLEVEL9K_LOAD_ICON="\u"$i_fa_tasks
POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=false
POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=80
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='white'
POWERLEVEL9K_DIR_BACKGROUND='black'
POWERLEVEL9K_FAIL_ICON="\u"$i_fa_bullseye
POWERLEVEL9K_DIR_HOME_FOREGROUND='black'
POWERLEVEL9K_HOME_ICON="\u"$i_linux_archlinux
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status load time disk_usage ssh background_jobs command_execution_time virtualenv vpn_ip)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_MODE='nerdfont-fontconfig'

```

**Comment by romkatv** [comment]
Thank you for the clear instructions.

Variables such as `i_fa_angle_double_right` expand to the actual icons, not to the unicode code points for these icons. If you type `echo $i_fa_angle_double_right`, you'll see the icon and not hex digits. This means you shouldn't prefix them with "\u". This prefix is for turning hex-encoded unicode code points into text, such as `\uF005`.

Here's your config with all "\u" removed. Please let me know if it works:

```zsh
export DEFAULT_USER="$USER"  # will not display context when using the default user
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" $i_fa_angle_double_right "
POWERLEVEL9K_LOAD_ICON=$i_fa_tasks
POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=false
POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=80
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='red'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='white'
POWERLEVEL9K_DIR_BACKGROUND='black'
POWERLEVEL9K_FAIL_ICON=$i_fa_bullseye
POWERLEVEL9K_DIR_HOME_FOREGROUND='black'
POWERLEVEL9K_HOME_ICON=$i_linux_archlinux
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status load time disk_usage ssh background_jobs command_execution_time virtualenv vpn_ip)
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_MODE='nerdfont-fontconfig'
```

What powerlevel9k did is ignore "\u" that weren't followed by hex digits. This was likely by accident due to the way they expanded things. My code did something different, so the result was also different. I expand things differently for performance; it has the safe effect on valid inputs. I could try to maintain compatibility when it comes to invalid escape sequences but this feels rather arcane to me, and the strings were in fact invalid. So if the fixed config works for you, I'm inclined to mark this issue as WAI.

**Comment by terencode** [comment]
Thanks for the explanation,  it makes sense to be stricter on the inputs in the name of performance.
