### ISSUE TITLE
Configure the virtualenv prompt result in "command not found: _prompt_segment"

### ISSUE THREAD

**Issue by AxZxP** [romkatv/powerlevel10k#1101]
## Context

The expectation is for the `custom_pipenv` prompt to display  "**Myvenv**" when the  `VIRTUAL_ENV ` variable returns "**Myvenv-sqLYihth**"

## Error

`prompt_virtualenv:6: command not found: _prompt_segment`

## My script

```bash
ZSH_THEME="powerlevel9k/powerlevel9k"
export ZSH="/Users/me/.oh-my-zsh"

prompt_virtualenv() {
  local MYVAR="$VIRTUAL_ENV"
  local NAME=${MYVAR%-*}
  local NAME=${NAME##*/}
  # Early exit; $virtualenv_path must always be set.
  [[ -z "$NAME" ]] && return
  "$1_prompt_segment" "$0" "$2" "blue" "$DEFAULT_COLOR" "${NAME:t}" 'PYTHON_ICON'
  }

POWERLEVEL9K_CUSTOM_PIPENV="prompt_virtualenv"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
VIRTUAL_ENV_DISABLE_PROMPT=1
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(custom_pipenv)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs)

```

## Question 

Is this an issue, or my bash script is failing somewhere ? If the script is faulty could you highlight what's wrong and how to set it correctly ?

many thanks

**Comment by romkatv** [comment]
Powerlevel9k and Powerlevel10k are separate and independent. Which one are you using?

**Comment by AxZxP** [comment]
I'm using both but but this is actually when sourcing the Powerlevel9k theme. Should I open open a ticket in this project ?

Please excuse me if it's the wrong place.

**Comment by romkatv** [comment]
You shouldn't use two zsh themes at the same time. You should use just one.

If you go with Powerlevel10k, here's how you can achieve what you want:

1. Clone powerlevel10k:
   ```zsh
   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
   ```
2. Remove function `prompt_virtualenv` and all lines that start with `POWERLEVEL9K` from `~/.zshrc`.
3. Replace `ZSH_THEME="powerlevel9k/powerlevel9k"` with `ZSH_THEME="powerlevel10k/powerlevel10k"`.
4. Restart zsh with `exec zsh`. **Do not use `source ~/.zshrc`.**
5. If the configuration wizard doesn't start automatically, invoke `p10k configure`.
6. Follow the wizard.
7. Once done with the wizard, open `~/.p10k.zsh` and add the following parameter there (the natural place would be next to the existing `POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION` parameter):
   ```zsh
   typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION='${P9K_CONTENT%-*}'
   ```
8. Restart zsh with `exec zsh`.

**Comment by AxZxP** [comment]
Excellent, thank you very much !

**Comment by romkatv** [comment]
You are welcome.
