### ISSUE TITLE
Formatting options

### ISSUE THREAD

**Issue by kitingChris** [romkatv/powerlevel10k#1102]
Is there a docu on how to formatting options like boldness?

For example like:
`POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%232F$bold\uE0B1'`

**Comment by romkatv** [comment]
Yes. It's here: http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html

```zsh
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%B%232F\uE0B1'
```

**Comment by kitingChris** [comment]
seems to have no real effect in this case... 
But i guess that has more to do with the utf character used as separator. 
Unfortunately I did not figure out which type of unicode charset this is. 

While the sign looks like https://www.compart.com/de/unicode/U+276D this does not fit with \uE0B1.
Slightly confused

**Comment by romkatv** [comment]
You can test this stuff easily with `print`:

```zsh
print -P '%B\uE0B1%b'
```

U+E0B1 is from Private Use Area, which means it doesn’t have a defined meaning in the UNICODE. Every font is free to display anything at all. In practice virtually all fonts that have a glyph with this number will have a powerline symbol in there.

**Comment by romkatv** [comment]
Note that none of this stuff is specific to powerlevel10k.

**Comment by kitingChris** [comment]
Yep got it.
```
print -P '%B\uE0B1%b'
print -P '\uE0B1%b'
```
Print the same char both in the same format. Guess the glyphs in private use area are not possible to format in any way. 

Thanks for pointing me in the right direction!

**Comment by romkatv** [comment]
When you use `%B`, the following text gets rendered in the bold fontface. Some glyphs can simply be the same in the bold and the regular fontfaces. This specific glyph likely is.
