### ISSUE TITLE
Add support for POWERLEVEL9K_MULTILINE_MIDDLE_PROMPT_PREFIX

### ISSUE THREAD

**Issue by AzimMuradov** [romkatv/powerlevel10k#1103]
Screenshot of the issue:

![screenshot](https://user-images.githubusercontent.com/31899809/99145929-40d26180-2684-11eb-8d57-74e112036dc4.png)

&nbsp;

Please, add support for configuring middle prompts prefix (not only for the second, but for all except the first and last).

For example:

```zsh
 POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}╭─"
POWERLEVEL9K_MULTILINE_MIDDLE_PROMPT_PREFIX="%F{blue}├─"
  POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}╰> "
```

**Comment by romkatv** [comment]
It's `NEWLINE` rather than `MIDDLE`. Try renaming it and you see that it works as you expect.

**Comment by AzimMuradov** [comment]
That's worked! Thanks!
