### ISSUE TITLE
nvm, and NVM_AUTO_USE

### ISSUE THREAD

**Issue by CircleCode** [romkatv/powerlevel10k#1106]
I'm using nvm through lukechilds/zsh-nvm plugin.
Both zsh-nvm plugin and powerlevel10k are loaded through zinit.
zsh-nvm plugin is configured with `NVM_AUTO_USE=true` (see https://github.com/lukechilds/zsh-nvm#auto-use),
and instant-prompt is enabled.

This option adds a hook on directory enter to use the nvm version from .nvmrc.

The thing is that with this option, when first entering a directory, nvm segment does not report the node version (since it is not immediately in use).

is there a way to display node version from nvm after it has been enabled?

**Comment by romkatv** [comment]
Let's see if I understand the bug report. When you `cd` into a directory with `.nvmrc`, zsh-nvm automatically invokes uses the specified version but prompt doesn't show the new node version. Is that correct?

I was unable to reproduce this:

```zsh
docker run -e TERM -e COLORTERM -w /root -it --rm debian /bin/bash -uec '
  apt-get update
  apt-get install -y zsh git curl
  git clone --depth=1 https://github.com/lukechilds/zsh-nvm.git
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
  mkdir /tmp/foo /tmp/bar /tmp/baz
  echo v14.15.0 >/tmp/foo/.nvmrc
  echo v14.13.0 >/tmp/bar/.nvmrc
  cat >.zshrc <<\END
NVM_AUTO_USE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nvm)
source ~/zsh-nvm/zsh-nvm.plugin.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
END
  exec zsh'
```

When prompt shows up, you can `cd` into `/tmp/foo`, `/tmp/bar` and `/tmp/baz`. Prompt seems to always display the expected node version.

- `/tmp/foo` -- nothing is displayed because the version in use is the same as the default (`nvm current` and `nvm version default` print the same thing).
- `/tmp/bar` -- the current version -- v14.13.0 -- is displayed because it's not equal to the default version (v14.15.0)
- `/tmp/baz` -- nothing is displayed because there is no `.nvmrc`.

What am I missing?

**Comment by CircleCode** [comment]
Thanks for trying to reproduce it.

It seems it only occurs on first prompt, thus it must be related to zinit "turbo mode" and instant prompt

I was not able to reproduce it in a fully automated way, but here is the simplest way I've found:

```sh
docker run -e TERM -e COLORTERM -w /root -it --rm debian /bin/bash -uec '
  apt-get update
  apt-get install -y zsh git curl
  git clone --depth=1 https://github.com/zdharma/zinit.git /root/.zinit/bin
  mkdir /tmp/foo /tmp/bar /tmp/baz
  echo v14.15.0 >/tmp/foo/.nvmrc
  echo v14.13.0 >/tmp/bar/.nvmrc
  cat >.zshrc <<\END
source /root/.zinit/bin/zinit.zsh
export NVM_DIR="/root/.nvm"
export NVM_AUTO_USE=true
zinit ice wait'!' lucid
zinit light lukechilds/zsh-nvm

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nvm)
zinit ice depth=1
zinit light romkatv/powerlevel10k

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
END
  exec bash'
```

Then, in the container:

- cd into `foo`, launch zsh (which will install zinit plugins, install node v14.15.0 and mark it as default)
  ```sh
  cd /tmp/foo
  zsh
  ```
- exit zsh (to come back to bash)
  ```sh
  exit
  ```
- cd into bar, and launch zsh (which will install node v14.13.0 and use it)
  ```
  cd /tmp/bar
  zsh
  ```
Here, node version is not shown.
If you press enter to refresh the prompt, it is now displayed.

**Comment by romkatv** [comment]
Thanks for the extra details. The solution is to not use zinit turbo mode. It's unnecessary when you enable instant prompt, so you aren't getting any advantages from it. Try removing all `wait` ices from your config and you'll notice that zsh starts as quickly as before.

`~/.zshrc` would look like this:

```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /root/.zinit/bin/zinit.zsh

export NVM_DIR="/root/.nvm"
export NVM_AUTO_USE=true
zinit light lukechilds/zsh-nvm

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(nvm)
zinit ice depth=1
zinit light romkatv/powerlevel10k
```

The important part is that the instant prompt stanza is at the top and that there is no `ice wait` anywhere. The order of commands after instant prompt is not important.

**Comment by CircleCode** [comment]
thanks, I arrived at the same conclusion and was editing my answer while you were posting yours

**Comment by romkatv** [comment]
Is there anything left to do in this issue or can it be closed?

**Comment by CircleCode** [comment]
Sorry, I thought I closed it with previous comment.
Again, thanks for your time and your explanations.

**Comment by romkatv** [comment]
You are welcome.
