### ISSUE TITLE
VCS no longer updates after 8488f7c

### ISSUE THREAD

**Issue by GrzegorzKozub** [romkatv/powerlevel10k#1107]
I think https://github.com/romkatv/powerlevel10k/commit/8488f7c75c34b7cd1d0f2868dc674197b74aede3 broke VCS updates for the consecutive prompt displays. VCS now only updates when I restart my terminal. I'm using alacritty and transient prompt. As soon as I check out https://github.com/romkatv/powerlevel10k/commit/feaf120ddc25279d6efa52ef4aecb7d14504064f it's back to normal.

**Comment by romkatv** [comment]
Thanks a lot for the report! Fixed.

**Comment by GrzegorzKozub** [comment]
Works! Fastest fix ever :1st_place_medal:
