### ISSUE TITLE
Color changes in ~/.p10k.zsh not working

### ISSUE THREAD

**Issue by dstronczak** [romkatv/powerlevel10k#1108]
Hi,

Even though the `~/.p10k.zsh` gets properly sourced (for example changing `  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off` to a diffrent value has an effect) I am not able to modify the colors. I tried that with multiple color parameters. For example chaning this line:

```
  # Default current directory color.
  #typeset -g POWERLEVEL9K_DIR_FOREGROUND=31
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=245
```

has no effect. Tried with other `FOREGROUND`s and diffrent values. What might be the issue here?

**Comment by romkatv** [comment]
Please do the following:

1. Run: `exec zsh`
2. Run `typeset -pm 'POWERLEVEL9K_DIR_*`.
3. Take a screenshot and post it here (you can drag and drop images to the edit box).
4. Modify the colors of `dir` segment in `~/.p10k.zsh` as you like.
5. Repeat steps 1-3.

The short version is that there is a mistake on your side. I can help you find it but it's likely something that you can find yourself if you try.

**Comment by dstronczak** [comment]
Hi,

So I experimented a bit. 

Here are the initial values:

![1](https://user-images.githubusercontent.com/436352/99296945-d538f180-2847-11eb-82b9-19aad483d48f.png)

Here's is what happens after I changed `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=245` and `POWERLEVEL9K_DIR_FOREGROUND=245` - no effect:

![2](https://user-images.githubusercontent.com/436352/99297043-fc8fbe80-2847-11eb-84d9-af8e9531d82c.png)

Here is what happened after I modified `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=245` - it worked:

![3](https://user-images.githubusercontent.com/436352/99297146-20eb9b00-2848-11eb-93b5-6d21806f0b42.png)

Is something wrong or do I just misinterpret what each of those parameters is responsible for? 

By the way - appreciate your help.

**Comment by romkatv** [comment]
This behavior is expected. Different parts of the current directory are colored differently. There are anchors, shortened segments, and everything else. If you search for "anchor" in the config, you'll find settings what control what's considered an anchor. Anchors get their own color and they are never shortened. They are **important** parts of the current directory.

Please do search "anchor" and read comments above every parameter with the search hit. Let me know if you still have questions.

**Comment by dstronczak** [comment]
I see. Thank you for the clarification. Using the occassion I'd like to ask: how do I modify the main color of other default prompt elements?

![image](https://user-images.githubusercontent.com/436352/99300140-804baa00-284c-11eb-85ee-e1e0f2be906c.png)

I'd like to change the color of the git branch name, the execution time color, the "prompt arrow" color, etc. Is this documented somwhere? Search for `color` gives me 77 occurences and I am interested in the main ones.

By the way - is there an easy / recommended way to modify the whole prompt / it's elemets? Say I'd like to add a space and a symple betweent he dir and branch name. Or change the "prompt arrow" symbol to a dollar sign?

**Comment by romkatv** [comment]
> I'd like to add a space and a symple betweent he dir and branch name.

While you can add a "between" symbol (that would be a separator), you'll probably want to have an icon for the `vcs` segment instead. That's `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION`. If you install the recommended font and run `p10k configure`, you'll have an option to enable a ton of (rather useless in my opinion) icons, including a few for `vcs`.

> Or change the "prompt arrow" symbol to a dollar sign?

In general, when you want to change something in Powerlevel10k prompt, you need to figure out which segment you want to change. Segments are listed at the top within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. Once you've figure out the segment's name, search for it to find the block of parameters that control it. Read the parameter names and their comments, then experiment.

**Comment by dstronczak** [comment]
Thanks a lot. Last questions that came to my mind - I entered my project dir and saw some "version" displayed in my prompt (2 15). The problem is I don't know what that is. Is there a way to find our what segments are currently displayed in order to turn them off / modify them?

![image](https://user-images.githubusercontent.com/436352/99301533-66ab6200-284e-11eb-9ddb-1b70faf930d1.png)


For the given case I might want to disable this segment but I don't even know what to look for.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean

I'm going to close this issue as I believe it has been resolved.
