### ISSUE TITLE
Remove AWS profile from right bar

### ISSUE THREAD

**Issue by dsentker** [romkatv/powerlevel10k#1113]
I used the configuration wizard and choosed the clock display on the right side. 
When i enter a directory related to an AWS project, the AWS profile is shown, too. How to disable this? I couldn't find any information about this in the documentation.

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `aws` and comment out the first hit.

**Comment by romkatv** [comment]
By default AWS profile is shown only when the command you are currently typing invokes `aws`, `awless`, `terraform`, `pulumi` or `terragrunt`. Perhaps what you are seeing is AWS elastic beanstalk environment. That one is shown whenever you are in an elastic beanstalk project directory. You can disable it by commenting out `aws_eb_env`.
