### ISSUE TITLE
Add support to Apple Silicon

### ISSUE THREAD

**Issue by MarsSelfDev** [romkatv/powerlevel10k#1116]
I'm using a new M1 MacBook and tryna install p10k like I did on all my other computers but I got [ERROR]: gitstatus failed to initialize. I went to ~/.cache/gitstatus and I saw gitstatusd-darwin-x86_64 which I believe was intended for x86 not M1's arm64. I'm not sure if that's the root cause of the issue but it seems like it. Appreciate if you could add support to arm64. Thanks!

**Comment by MarsSelfDev** [comment]
saw this in the error log: _gitstatus_daemon_p9k_:82: bad CPU type in executable: /Users/captainmars/.cache/gitstatus/gitstatusd-darwin-x86_64

**Comment by romkatv** [comment]
Please install Rosetta: https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment

**Comment by leeeboo** [comment]
Could please make gitstatusd compile for darwin arm64?

**Comment by romkatv** [comment]
> Could please make gitstatusd compile for darwin arm64?

I'll likely have access to the necessary hardware in January. Please wait.

May I ask why you want this? Are there any issues that you expect to get resolved with a native arm64 binary?

**Comment by leeeboo** [comment]
> > Could please make gitstatusd compile for darwin arm64?
> 
> I'll likely have access to the necessary hardware in January. Please wait.
> 
> May I ask why you want this? Are there any issues that you expect to get resolved with a native arm64 binary?

Just obsession....

**Comment by romkatv** [comment]
> Just obsession....

Got it. Hopefully in January you'll have a relief then.

**Comment by eddyg** [comment]
I don't think GitHub has any Apple Silicon Macs yet, so not directly related to this issue, but wanted to mention [this](https://github.com/fastai/fastmac) as a way that you could test stuff (like iTerm2) on a Mac in case it's easier than via going back-and-forth in issue comments. I think a session is good for up to six hours.

**Comment by romkatv** [comment]
@eddyg I run macOS in KVM but it's x86_64. I use it to build darwin binaries and for testing stuff. There is currently no solution for running arm64 macOS in a VM on Linux. In January I should have an M1 MacBook as a replacement for one of the laptops that I primarily use to browse the web. I'll also use it for arm64 builds.

**Comment by eddyg** [comment]
Ah, it all comes clear now! Looking forward to arm64 support. (I just got a MacBook Air myself and have yet to install Rosetta 2, in an attempt to see how good ASi support is.) Thanks for the update.
