### ISSUE TITLE
gitstatus prevents USB drive from being ejected

### ISSUE THREAD

**Issue by kongslund** [romkatv/powerlevel10k#1121]
(First of all, thanks for this awesome Zsh theme. The speed is amazing compared to powerlevel9k)

This is perhaps a bit unusual but I have a USB drive that contains a git directory. After entering that directory, doing some work and changing back to my home directory, I would like to eject the USB drive. However, macOS refuses to do so because gitstatus (more precisely gitstatusd-darwin-x86_64) still has a handle to that directory.

My current approach is to kill the gitstatus process so that I can eject the drive. What would be a nicer way?

**Comment by romkatv** [comment]
A nicer way would be to restart your shell by using the following command:

```zsh
exec zsh
```

You can also wait for an hour. This is configuration in theory the knob isn't exposed though powerlevel10k parameters. Either way, I wouldn't recommend changing this default.

**Comment by kongslund** [comment]
`exec zsh` is indeed much nicer. Thanks!
