### ISSUE TITLE
How to properly use git status plugin in zshrc

### ISSUE THREAD

**Issue by viking1304** [romkatv/powerlevel10k#1122]
I am using your git status plugin for custom function inside zshrc that is not related to prompt customization. I do not want to make any conflict with p10k prompt and I do not want to have zombie processes after executing that function, so I would really aprichiate if you could help. There is no separate git status plugin issue page, so I had to ask here. If you think that this is irrelevant question, just close this issue.

I have 50+ repositories, and I need relatively quick way to check if I am behind few commits or if I forgot to commit something. 

There is probably better way to source your plug-in than this

```sh
# load gitstatus plugin for use in shell functions
source .oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh
```
This is my function:

```sh
function git-status() {
  {
    function __get-git-status() {
      gitstatus_stop 'GS' && gitstatus_start -s -1 -u -1 -c -1 -d -1 'GS'
      if gitstatus_query -d $1 GS && [[ $VCS_STATUS_RESULT == ok-sync ]]; then

        local      clean='%79F'  # green foreground
        local   modified='%75F'  # blue foreground
        local  notsynced='%75F'  # blue foreground
        local  untracked='%75F'  # blue foreground
        local conflicted='%196F'  # red foreground
        local       repo='%254F'  # white foreground

        local p

        local where  # branch name, tag or commit
        if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
          where=$VCS_STATUS_LOCAL_BRANCH
        elif [[ -n $VCS_STATUS_TAG ]]; then
          p+='%f#'
          where=$VCS_STATUS_TAG
        else
          p+='%f@'
          where=${VCS_STATUS_COMMIT[1,8]}
        fi    

        (( $#where > 32 )) && where[13,-13]="…"  # truncate long branch names and tags
        p+="${where//\%/%%}"             # escape %

        # ⇣42 if behind the remote.
        (( VCS_STATUS_COMMITS_BEHIND )) && p="${notsynced}${p} ⇣${VCS_STATUS_COMMITS_BEHIND}"
        # ⇡42 if ahead of the remote; no leading space if also behind the remote: ⇣42⇡42.
        (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && p+=" "
        (( VCS_STATUS_COMMITS_AHEAD  )) && p="${notsynced}${p}⇡${VCS_STATUS_COMMITS_AHEAD}"
        # ⇠42 if behind the push remote.
        (( VCS_STATUS_PUSH_COMMITS_BEHIND )) && p="${notsynced}${p} ⇠${VCS_STATUS_PUSH_COMMITS_BEHIND}"
        (( VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND )) && p+=" "
        # ⇢42 if ahead of the push remote; no leading space if also behind: ⇠42⇢42.
        (( VCS_STATUS_PUSH_COMMITS_AHEAD  )) && p="${notsynced}${p}⇢${VCS_STATUS_PUSH_COMMITS_AHEAD}"
        # *42 if have stashes.
        (( VCS_STATUS_STASHES        )) && p="${modified}${p} *${VCS_STATUS_STASHES}"
        # 'merge' if the repo is in an unusual state.
        [[ -n $VCS_STATUS_ACTION     ]] && p="${conflicted}${p} ${VCS_STATUS_ACTION}"
        # ~42 if have merge conflicts.
        (( VCS_STATUS_NUM_CONFLICTED )) && p="${conflicted}${p} ~${VCS_STATUS_NUM_CONFLICTED}"
        # +42 if have staged changes.
        (( VCS_STATUS_NUM_STAGED     )) && p="${modified}${p} +${VCS_STATUS_NUM_STAGED}"
        # !42 if have unstaged changes.
        (( VCS_STATUS_NUM_UNSTAGED   )) && p="${modified}${p} !${VCS_STATUS_NUM_UNSTAGED}"
        # ?42 if have untracked files. It's really a question mark, your font isn't broken.
        (( VCS_STATUS_NUM_UNTRACKED  )) && p="${untracked}${p} ?${VCS_STATUS_NUM_UNTRACKED}"
        # clean
        [[ ${p} == ${where} ]] && p="${clean}${p}"

        local gitstatus="  ${repo}$1:t ${p}%f"
        print -P "${gitstatus}"
      fi

    }

    echo ""
    echo "Statuts of Git repositories:"
    echo ""

    for dir in ~/Documents/Work/Web/Projects/*/ ; do
      __get-git-status $dir;
    done
  } always {
    unfunction __get-git-status
  }
}
```

I hope that using GS should be more than enough to avoid any potential conflict with p10k prompt. But I guess MY would also work. Right?

Is it ok to use gitstatus_stop 'GS' before start as I did (following your example) or it would be better to use it after query in this case?

I am using unfunction, just to be remove subfunction from accidental shell usage.

**Comment by romkatv** [comment]
> There is no separate git status plugin issue page

It's here: https://github.com/romkatv/gitstatus/issues

> ```shell
> # load gitstatus plugin for use in shell functions
> source .oh-my-zsh/custom/themes/powerlevel10k/gitstatus/gitstatus.plugin.zsh
> ```

A better way would be to add `~/` to the path. Otherwise it'll fail if the current directory is not `$HOME`.

> I hope that using GS should be more than enough to avoid any potential conflict with p10k prompt. But I guess MY would also work. Right?

I personally use `MY` or `my` as a namespace/prefix for my symbols because I think it unlikely that some project will grab this name. I wouldn't use `GS` because it can be used by some project (e.g., by something called Git Status). I would also be hesitant to define a function called `git-status` because it uses the naming convention of `git` commands (if you define command `git-blah`, `git blah` will invoke it).

> This is my function: [...]

If you  remove the call to `gitstatus_stop` this function will be orders of magnitude faster when called more than once in the same shell.

`print -P` is incorrect and a potential security vulnerability. You can replace it with this:

```zsh
print -r -- "${(%)gitstatus}"
```

Add `local dir` to `git-status` to avoid setting the global `dir` parameter.

Add `emulate -L zsh` at the top of `git-status` to make this function work with any shell options.
