### ISSUE TITLE
Is it possible to make two-lines prompt works better with the "less" pager?

### ISSUE THREAD

**Issue by ZekeLu** [romkatv/powerlevel10k#1126]
When the `prompt height` is set to **two lines**, after quit the `less` pager, the output of the pager is pushed one line up. See the first image below.

What I want is keep the output of the pager on the screen without being pushed up. When the `prompt height` is set to **one line**, I can get the expected behavior. See the second image below.

I like the **two lines** mode very much! Is it possible to keep the output of the pager no moving in **two lines** mode?

Thank you in advance!

![Prompt Height: two lines](https://user-images.githubusercontent.com/1063615/100261192-5a798000-2f85-11eb-9eed-3efbdeae7d09.gif)

![Prompt Height: one line](https://user-images.githubusercontent.com/1063615/100263505-8e09d980-2f88-11eb-8410-082d93ee46ea.gif)

**Comment by romkatv** [comment]
The output is moved up whenever anything is printed on the screen. There is no way around it. If your pager has an option to use only `N - 1` lines of the screen (where `N` is the total height of your terminal), then you can achieve what you want. If your pager doesn't have this option, then you cannot.

**Comment by ZekeLu** [comment]
Wow, I didn't expect to get your reply so soon! Thank you @romkatv !

I'm using the `less` pager. Its doc says that it will read from the environment variable `LINES` to set the number of lines on the screen, but it seems that this variable is controlled by the system, and I can not change it.

I have tried to customize the prompt of `less` to split it into two lines, but with no luck, I can not split it into two lines (`\n` and `\r` don't work).

I think I have to stay with the **one line** mode.

Your work is deeply, deeply appreciated. Thank you very much!
