### ISSUE TITLE
Powerlevel10k suddenly become broken in JetBrains IDE terminal

### ISSUE THREAD

**Issue by oleynikandrey** [romkatv/powerlevel10k#1128]
Powerlevel10k installed through `Oh My Zsh`.
There are was not updates of the IDE itself, but prompt line starts with `[0m`, ends with `[K` and cursor is on the next line:
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/1157958/100352769-91d84300-2ffe-11eb-8638-fc79a45d0ebd.png">

How I can find the reason?

**Comment by romkatv** [comment]
Can you reproduce it in another terminal?

**Comment by oleynikandrey** [comment]
No, It works fine in iTerm2 and MacOS native Terminal.

**Comment by romkatv** [comment]
I'm afraid I won't have the time to look into this for a few days/weeks. Perhaps reinstalling something might help?

**Comment by oleynikandrey** [comment]
Reinstalling of Powerlevel10k didn't help. So I will wait.

**Comment by sidharthyatish** [comment]
True. Temporarily switched to robbyrussell. Adding this to ```zshrc``` helps
```
if [[ $__INTELLIJ_COMMAND_HISTFILE__ ]]; then
  ZSH_THEME="robbyrussell"
else
  ZSH_THEME="powerlevel10k/powerlevel10k"
fi
```

Reference : https://stackoverflow.com/questions/43056684/oh-my-zsh-theme-not-rendering-properly-in-intellij

**Comment by CmplxStack** [comment]
This fixed the rendering for me:
Remove:
`ZSH_THEME="powerlevel10k/powerlevel10k"`
Add:
`source ~/powerlevel10k/powerlevel10k.zsh-theme`

**Comment by oleynikandrey** [comment]
> This fixed the rendering for me:
> Remove:
> `ZSH_THEME="powerlevel10k/powerlevel10k"`
> Add:
> `source ~/powerlevel10k/powerlevel10k.zsh-theme`

For me it changed nothing.

**Comment by gufertum** [comment]
Reverting to release 1.14.2 works for me as workaround.

**Comment by romkatv** [comment]
@gufertum Can you confirm that the problem reproduces for you with powerlevel10k > 1.14.2?

**Comment by gufertum** [comment]
@romkatv Yes I can confirm that it works using 1.14.2
![image](https://user-images.githubusercontent.com/550133/100613179-63b37580-3314-11eb-9d4d-398880ec4482.png)

**Comment by romkatv** [comment]
Fascinating. Here's the output of `git diff v1.14.2..v1.14.3` in powerlevel10k:

```diff
diff --git a/Makefile b/Makefile
index f78c379f..2ba7c76d 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
-ZSH ?= $(shell command -v zsh 2> /dev/null)
+ZSH := $(shell command -v zsh 2> /dev/null)
 
 all:
 
 pkg:
- cd gitstatus && $(MAKE) ZSH=$(ZSH) pkg && cd ..
+ cd gitstatus && $(MAKE) pkg && cd ..
  $(or $(ZSH),:) -fc 'for f in *.zsh-theme internal/*.zsh; do zcompile -R -- $$f.zwc $$f || exit; done'
diff --git a/gitstatus/Makefile b/gitstatus/Makefile
index a6e02a02..0141dd90 100644
--- a/gitstatus/Makefile
+++ b/gitstatus/Makefile
@@ -2,7 +2,7 @@ APPNAME ?= gitstatusd
 OBJDIR ?= obj
 
 CXX ?= g++
-ZSH ?= $(shell command -v zsh 2> /dev/null)
+ZSH := $(shell command -v zsh 2> /dev/null)
 
 VERSION ?= $(shell . ./build.info && printf "%s" "$$gitstatus_version")
```

The only files that have changed are `Makefile` and `gitstatus/Makefile`. These files aren't being used on your machine. You can verify this by deleting them, or filling them with garbage.

**Comment by gufertum** [comment]
OK, I'm sorry I tested it with the MASTER branch, not 1.14.3 and that is the one causing issues. I'm using oh-my-zsh and that seems to update to the master branch, not the latests release branch - my bad.

So this time I tested again with these 3 versions, directly from powerleve10k using git:
- 1.14.2 -> is ok
- 1.14.3 -> is ok
- master -> breaks intellij

**Comment by romkatv** [comment]
The `master` branch is currently at `2c3bcd8b5d301f469fd8095d32ab2dc18e254a8e` and the diff between v1.4.3 and that commit has effect only if you are using zsh4humans v5. If pretty sure you aren't using it, so it's a mystery why this has any effect on your setup.

Can you describe how exactly powerlevel10k is broken in Idea? I see on your screenshot that two promps are different. One has some garbage in the front, the other has some garbage at the back. Is it random? Alternating? Only the first two prompts broken? Something else?

Does it depend on some specific option? E.g., is it broken if you type `unset -m 'POWERLEVEL9K_*' && p10k reload`? Is it broken if you type `p10k configure` and select all options differently from how you normally select them?

Is it broken if you reset Idea preferences?

What OS are you using?

Do you use iTerm2? Do you use iTerm2 shell integration? What is the output of `$ITERM_SHELL_INTEGRATION_INSTALLED`?

**Comment by gufertum** [comment]
@romkatv You're right, I only use oh-my-zsh and powerlevel10k.

I use OSX. The prompt does look like that in intellij, but is perfectly fine in iterm2 and terminal.
It also works fine, but the garbage is displayed.
The garbage in front of the prompt is there when opening an new terminal or after a 'reset'.
The garbage after the prompt is always there but appears slightly later after loading and showing the git-prompt info...

It is still broken after 'unset -m 'POWERLEVEL9K_*' && p10k reload'. It looks differently, but still broken:
![image](https://user-images.githubusercontent.com/550133/100620117-57ccb100-331e-11eb-8d08-9e7ddf6234db.png)

p10k configure does not change anything - tried various settings.
Yes, I use iterm2
`echo $ITERM_SHELL_INTEGRATION_INSTALLED
Yes
`
Still broken after typing 'ZDOTDIR=$HOME exec zsh'.

I'm not into resetting my idea preferences right now... I'm heavily developing...

**Comment by romkatv** [comment]
Does this fix it?

```zsh
unset ITERM_SHELL_INTEGRATION_INSTALLED && p10k reload
```

**Comment by gufertum** [comment]
> Does this fix it?
> 
> ```shell
> unset ITERM_SHELL_INTEGRATION_INSTALLED && p10k reload
> ```

Yes, that does fix the problem.

**Comment by romkatv** [comment]
How are you enabling iTerm2 shell integration?

**Comment by gufertum** [comment]
I source it using
`
# iterm2 integration
if [ -f ~/.iterm2_shell_integration.zsh ]; then
	source ~/.iterm2_shell_integration.zsh
fi
`

Disabling it also works (of course).

**Comment by romkatv** [comment]
Please attach `~/.iterm2_shell_integration.zsh` to this issue (drag-and-drop).

Can you also attach `~/.zshrc`? If not, please describe where in `~/.zshrc` this line is located.

**Comment by gufertum** [comment]
Well OK, thats complicated. I have my own little env-loader in .zshrc which is called after the sourcing of oh-my-zsh...

`if [ -d ~/dot_zsh/envs ]; then
    for f in $(find ~/dot_zsh/envs -name '*.env' | sort); do
      source "$f"
    done
  fi`

It searches my folder structure and sources all the files. the mac.env contains the iterm integration.
Should i try to load it first/last?

**Comment by gufertum** [comment]
to get .iterm2_shell_intergration you can use:
```
curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh
```

**Comment by romkatv** [comment]
> to get .iterm2_shell_intergration you can use:
> 
> ```
> curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh
> ```

I know.

**Comment by oleynikandrey** [comment]
I have the same issue, so my script could fit.
[iterm2_shell_integration.txt](https://github.com/romkatv/powerlevel10k/files/5616903/iterm2_shell_integration.txt)

**Comment by romkatv** [comment]
> I have the same issue, so my script could fit.
> [iterm2_shell_integration.txt](https://github.com/romkatv/powerlevel10k/files/5616903/iterm2_shell_integration.txt)
> 
> I source it from ~/.zlogin

Thanks.

Can you share all your zsh rc files?

**Comment by oleynikandrey** [comment]
I've removed all comments and some custom aliases.

```
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="awesome-patched"

plugins=(rails ruby git osx pep8 git-extras pip python screen pyenv vagrant z httpie dircycle tmux docker golang dash vscode zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='vim'
fi

LESSPIPE=`which src-hilite-lesspipe.sh`
export LESSOPEN="| ${LESSPIPE} %s"
export LESS=' -R '

export LC_ALL=en_US.UTF-8

if [[ -t 0 && $- = *i* ]]
then
    stty -ixon # unmap ctrl-s
fi 

TERM=xterm-256color
alias tmux="TERM=screen-256color-bce tmux"
export TERM
alias vi="vim"

fpath=(/usr/local/share/zsh-completions $fpath)

fpath=(~/zsh_functions $fpath)
autoload transfer

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="/Users/user/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by romkatv** [comment]
Are you using tmux? Do you get the same problem without tmux?

**Comment by gufertum** [comment]
@romkatv I solved the problem for my by only loading the iterm2 integration, when running in iterm2. Is cleaner anyways. I can now source this file everywhere, but it only loads on osx in iterm2

```
# osx env for iterm2 only

# exit if not on a mac
if [[ "$OSTYPE" != "darwin"* ]]; then
	return
fi

if [[ "$LC_TERMINAL" != "iTerm2"* ]]; then
	return
fi

# - - - - - - - - - - - - - - - - - -

iterm2_help() {
    #source ~/.iterm2_shell_integration.zsh
    echo "iterm2 shortcuts :: osx layout => [ ctrl | option/alt | cmd ]"
    echo " -----------------------------------------------------------"
    echo "   Cmd-N            -> New Window"
    echo "   Cmd-T            -> New Tab (add shift for osx shortcut)"
    echo "   Ctrl-[Shift]-Tab -> Cycle Tabs"
    echo "   Cmd-Shift-B      -> Toggle Toolbelt"
    echo "   Cmd-Shift-+/-    -> Change Font Size"
    echo "   Ctrl-D           -> Logout"
    echo " ----------------------------------------------------------"
}
alias f1='iterm2_help'

# iterm2 integration
if [ -f ~/.iterm2_shell_integration.zsh ]; then
    source ~/.iterm2_shell_integration.zsh
fi
```

**Comment by romkatv** [comment]
I'm glad you have a workaround. It disables iTerm2 integration when you are working over ssh but perhaps you don't care about that.

**Comment by oleynikandrey** [comment]
> Are you using tmux? Do you get the same problem without tmux?

I usually don't use tmux locally. Sometime through iTerm integration, but it's rare case.

**Comment by gufertum** [comment]
> I'm glad you have a workaround. It disables iTerm2 integration when you are working over ssh but perhaps you don't care about that.

Yes thats OK for me. I use the intellij-shell only for builds and stuff. Otherwise I live in iterm... 👍

**Comment by romkatv** [comment]
> I usually don't use tmux locally. Sometime through iTerm integration, but it's rare case.

Does this mean the error you are reporting is happening without using tmux?

**Comment by RickCogley** [comment]
Chiming in here because for me, mine broke in a similar way, in kitty but not in the native terminal on MacOS Big Sur which was fine once I set the right font. I had iTerm2 uninstalled, but was loading its shell integration script in `.zshrc`. 

Entering the above `unset ITERM_SHELL_INTEGRATION_INSTALLED && p10k reload` fixed it temporarily, and commenting `z4h source ~/.iterm2_shell_integration.zsh` in `.zshrc` fixed it permanently. 

FYI just in case someone searches.

**Comment by romkatv** [comment]
Thanks for the info, everyone. I was finally able to reproduce this and to track down and fix the bug. Please update powerlevel10k to the latest version and verify that the issue is fixed.

**Comment by gufertum** [comment]
@romkatv Thanks Roman, it's working again! 👍

**Comment by romkatv** [comment]
Phew... I'm glad.

Thanks for verifying!

**Comment by RickCogley** [comment]
Tested and looks good on my system too. Thanks for the incredibly fast work @romkatv !

**Comment by romkatv** [comment]
Heh, took 6 days to fix. Not something I'm proud of.

**Comment by RickCogley** [comment]
shoot, sorry, wasn't trying to be sarcastic tbh by saying "fast"; it's just I didn't read the whole thread. This product is great. I just want to say I appreciate your great work.

**Comment by romkatv** [comment]
Thanks, Rick.

**Comment by oleynikandrey** [comment]
@romkatv, thank you!

**Comment by ky0n** [comment]
> True. Temporarily switched to robbyrussell. Adding this to `zshrc` helps
> 
> ```
> if [[ $__INTELLIJ_COMMAND_HISTFILE__ ]]; then
>   ZSH_THEME="robbyrussell"
> else
>   ZSH_THEME="powerlevel10k/powerlevel10k"
> fi
> ```
> 
> Reference : https://stackoverflow.com/questions/43056684/oh-my-zsh-theme-not-rendering-properly-in-intellij

this doesn't seem to work for me after the latest intelliJ update version 2023.1.3

**Comment by Tcharl** [comment]
Hi,

Happened again on last brew release & last IJ

**Comment by romkatv** [comment]
@Tcharl Can you clarify on which versions of different pieces of software you can reproduce the problem and which ones you cannot?

**Comment by Tcharl** [comment]
Sure:

Intellij: Build #IU-233.14015.106, built on January 25, 2024
Powerlevel10k brew version: 1.20.0
zsh 5.9 (arm-apple-darwin22.1.0)

Zshrc declaration: 
```
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
source /opt/homebrew/opt/powerlevel10k/share/powerlevel10k/powerlevel10k.zsh-theme
```

Works perfectly on iterm2, but waaaaaay too much spaces in the intellij terminal:
<img width="1389" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/792925/b4ae8342-c245-430e-9f6e-eee109070dd8">

Your project rocks dude, I would really enjoy it again within Intellij (I definitely continue to love it within iTerm2 ;-)).

Do you need anything else?

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with another theme?

**Comment by romkatv** [comment]
The issue is with your font configuration. Zsh configs are irrelevant here. You'll see the same thing in bash or even if you run something like `vi`.

P.S.

In the future, when you have a problem, err on the side of opening a new issue instead of commenting on a closed one, especially when the original issue was fixed. It's almost always something else.
