### ISSUE TITLE
broken chars in st.

### ISSUE THREAD

**Issue by Ohio2** [romkatv/powerlevel10k#1129]
**i use MesloLGS NF**

**Comment by romkatv** [comment]
Elaborate.

**Comment by Ohio2** [comment]
Ok so, like it does the weird characters. Like the _/ or some thing at the end.

**Comment by romkatv** [comment]
That sounds bad. Have you tried opening a bug against st?

**Comment by romkatv** [comment]
I mean, if st cannot display some glyphs from your font properly, this must be a bug in st, right? Is there any indication that the bug is not in st?

**Comment by Ohio2** [comment]
well no, there seems to be a patch that fixes it, but i have it.

**Comment by romkatv** [comment]
Closing because there is no indication that anything is broken in Powerlevel10k.
