### ISSUE TITLE
purepower - Strange ─ ( DRAWINGS LIGHT HORIZONTAL / u2500) character before each prompt

### ISSUE THREAD

**Issue by kbakk** [romkatv/powerlevel10k#113]
Each time the prompt runs, it prints an annoying line at the top.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/24817039/60846410-9f114980-a1df-11e9-9a28-54cd61b84eb9.png">

I have installed powerlevel10k (in ~/.oh-my-zsh/custom/themes/) and enabled the purepower prompt. 

I've tried to disable all oh-my-zsh plugins, as well as almost all other lines in my .zshrc config, to see if any of these could affect it. It doesn't seem to be anything in my environment. 

<details>
<summary>~/.zshrc</summary>

    export ZSH=/Users/kristofferb/.oh-my-zsh

    plugins=()
    ZSH_THEME=powerlevel10k/powerlevel10k

    source $ZSH/oh-my-zsh.sh

    export HISTSIZE=500000
    export SAVEHIST=500000
    setopt HIST_EXPIRE_DUPS_FIRST 
    setopt HIST_IGNORE_DUPS       
    setopt HIST_FIND_NO_DUPS      

    source ~/.purepower

</details>

If I remove the `source ~/.purepower` line, I get the default theme, however without the line.

**Comment by romkatv** [comment]
Run this to disable the horizontal line:

```zsh
sed -e 's/POWERLEVEL9K_SHOW_RULER=true/POWERLEVEL9K_SHOW_RULER=false/' -i ~/.purepower
```

**Comment by romkatv** [comment]
P.S.

If you want to have an empty line where the horizontal line used to go, open `~/.purepower` with your favorite text editor and add `typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true` next to the `POWERLEVEL9K_SHOW_RULER` line.

**Comment by kbakk** [comment]
Thanks, that worked! I was a bit confused about this, as the pure [example](https://github.com/romkatv/powerlevel10k#configuration) doesn't show the line. Hopefully if others should have the same problem they can find this issue now.

**Comment by romkatv** [comment]
Pure Power config is the one I use myself. I change it quite frequently but don't always update the screenshot. The screenshot has an empty line but I've eventually realized that a horizontal line is better. The purpose of an empty line and a horizontal line is to make it easier to see where commands start and end. Both take the same amount of vertical space (one line) but horizontal line is better at separating commands. It also makes it easier to visually align right and left prompt.

It's OK if you prefer a different prompt. `~/.purepower` is meant to be edited.
