### ISSUE TITLE
Configure without shell restart

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#1130]
Greetings!
Can you please tell me if there is a way to run `p10k configure` without restarting the shell?
I'm making an environment setup script via ansible and I really don't want to split the playbook into 2 parts.

**Comment by romkatv** [comment]
If you want to automate the installation of pwerlevel10k, you need to *copy* an existing `~/.p10k.zsh` over. `p10k configure` is for interactive use only.

**Comment by Mystic8b** [comment]
Is only .p10k.zsh generated during configuration? Nothing else?

**Comment by romkatv** [comment]
Correct.

**Comment by romkatv** [comment]
Well, it also can optionally modify `~/.zshrc` but I'm assuming you are already copying an existing `~/.zshrc` over.

**Comment by Mystic8b** [comment]
I only partially edit it, but I can see what changes are made there, this is not a problem.
In general, this option is also fine. Thanks!

**Comment by romkatv** [comment]
Good. Closing then.
