### ISSUE TITLE
Configuration Wizard keeps popping up, despite .p10k.zsh in ~/

### ISSUE THREAD

**Issue by atripes** [romkatv/powerlevel10k#1131]
Title says it all, how do I disable the wizard? I brought my own config file, but the wizard doesn't seem to notice. 
Many thanks!

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by atripes** [comment]
So sorry, I thought I had skimmed the FAQ properly. Thanks!

**Comment by romkatv** [comment]
No worries.
