### ISSUE TITLE
How to move some element first line

### ISSUE THREAD

**Issue by KairuiLiu** [romkatv/powerlevel10k#1132]
I want to move battery/ip/public ip tags to the first line, but don't know how to config

![image](https://user-images.githubusercontent.com/25458969/100609810-96c42c00-3349-11eb-94dc-059c6a311f34.png)

THANKS

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and edit `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. Comments above these parameters explain what they mean.
