### ISSUE TITLE
Unwanted new line in the left segment

### ISSUE THREAD

**Issue by mushi-nova** [romkatv/powerlevel10k#1134]
While customising prompt I'm facing the following bug (possibly)

![2020-11-30_22-15](https://user-images.githubusercontent.com/62972573/100638772-689b1800-335a-11eb-92fb-ab58ac765134.png)

In this whenever I add 3 level of right segments a new blank segement is added on the right side. So is there any way to remove the blank segment in the right side?

Versions:
1. zsh 5.8 (x86_64-pc-linux-gnu)
2. powerlevel10k 1.13.0-1

**Comment by romkatv** [comment]
Cursor must always be on the last line. Does this answer your question?

**Comment by mushi-nova** [comment]
Thanks a lot for your quick reply and I do understand your statement. So is there any way to change that behavior?

**Comment by romkatv** [comment]
In Zsh the cursor must be on the last prompt line. The only way to change it is to modify the source code of Zsh and recompile it. You can obtain the source code of Zsh here: http://zsh.sourceforge.net/Arc/source.html.

**Comment by mushi-nova** [comment]
Thanks a lot for the info.
