### ISSUE TITLE
Blank space under line

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#1136]
Greetings!
Perhaps a somewhat strange question, but suddenly someone can help.
I wanted to make the prompt appear right at the bottom of the terminal. Added the following to the beginning of .zshrc:
`printf '\n%.0s' {1..35}`
But even if you add more blank lines, the prompts are displayed slightly higher than expected (even if a scroll appears) and only move to the desired location after a new line.
I checked in bash and the standard zsh theme - everything is fine there and after a new line, prompt stays in place.
It makes me very sad. I would be very grateful if it is possible to solve it!
![image](https://user-images.githubusercontent.com/35394377/100737252-f885a400-33e4-11eb-80cd-fbfa8497636e.png)

**Comment by romkatv** [comment]
p10k is the only theme with [Instant Prompt](https://github.com/romkatv/powerlevel10k#instant-prompt) on these screenshots. If you disable instant prompt, you'll get p10k prompt on the last line. The downside, of course, is that it'll take longer for prompt to appear (like in all other themes).

To see the reason why instant prompt needs that extra line, add `sleep 3` at the very bottom of `~/.zshrc`, open a terminal and quickly type `ls` and hit <kbd>Enter</kbd>.

Now, add `POWERLEVEL9K_INSTANT_PROMPT_COMMAND_LINES=0` to `~/.p10k.zsh` and restart zsh with `exec zsh` **twice**. Try opening a terminal again and typing `ls` followed by <kbd>Enter</kbd>. See the issue?

If you rarely hit <kbd>Enter</kbd> while instant prompt is active, and if you don't mind the visual mess that appears when you do, keep `POWERLEVEL9K_INSTANT_PROMPT_COMMAND_LINES=0`. (But remove that `sleep` :wink: )

FWIW, I also like my prompt line to be at the bottom and in my setup I have it at the *very bottom* without having to disable instant prompt and without the negative side effects of `POWERLEVEL9K_INSTANT_PROMPT_COMMAND_LINES=0`. In addition, in my setup prompt stays at the bottom without jumping upwards when completing commands or clearing the screen. You can see how it works in this cast:

[![asciicast](https://asciinema.org/a/372068.svg)](https://asciinema.org/a/372068)

**Comment by Mystic8b** [comment]
In your example, the result looks incredible. Does it depend on the terminal, or do you have your own settings and is it a secret?)

**Comment by romkatv** [comment]
It's this: https://github.com/romkatv/zsh4humans/tree/v5. Note that it links to v5 -- the development branch with no backward compatibility guarantees. The latest stable release is v4, and it doesn't have these features (the crucial feature is the ability to display information in a kind of pop-up above prompt).

If you decide to try v5, it's a good idea to either disable auto-update or to follow https://github.com/romkatv/zsh4humans/issues/35 to get notified about breaking changes. It's not really something I would recommend unless you like using bleading-edge software that breaks often.

**Comment by Mystic8b** [comment]
I have windows, so I'm used to something not working for me: D So I'll give it a try!
Prompt at the bottom is also there, right?

**Comment by romkatv** [comment]
> Prompt at the bottom is also there, right?

Yes.

**Comment by Mystic8b** [comment]
Thank you so much!
You are doing very cool things! My regards.

**Comment by romkatv** [comment]
You are very welcome.
