### ISSUE TITLE
First character gets chopped off when exiting the completion menu

### ISSUE THREAD

**Issue by yanneg** [romkatv/powerlevel10k#1138]
Here's an asciinema that hopefully shows the problem I'm experiencing. https://asciinema.org/a/9r8rCZ2mGddOGmgkdDxF33ulx

Whenever I exit out of the completion menu, the first character gets truncated from the command. It's actually there, just not visible. It happens only in iTerm2 and it works fine in Terminal.app. My iTerm2 version is the latest beta: Build 3.4.2beta3. 

I did a git bisect and tracked the offending commit to 96646e8b9c676a9f3302d27fd96e9343826afee3

I'm also using https://github.com/laggardkernel/zsh-iterm2 - maybe that's causing an issue with p10k? Any ideas?

**Comment by romkatv** [comment]
Thanks for the report! Should be fixed now. Please verify.

**Comment by yanneg** [comment]
Verified :) Thanks @romkatv, you rock!

**Comment by romkatv** [comment]
Thanks for verifying!
