### ISSUE TITLE
[Question] Make default segment bold?

### ISSUE THREAD

**Issue by meav** [romkatv/powerlevel10k#1139]
How do I make some default segment (command_execution_time, vcs ...) display as bold format?

**Comment by romkatv** [comment]
There is no single answer that works for all segments. For `command_execution_time` you can do this:

```zsh
POWERLEVEL9K_COMMAND_EXECUTION_TIME_CONTENT_EXPANSION='%B$P9K_CONTENT%b'
```

For `vcs` you need to change the last line of `my_git_formatter`:

```zsh
typeset -g my_git_format=%B$res%b
```

**Comment by meav** [comment]
Thank you very much! It works perfect.
