### ISSUE TITLE
feature request : keep status line at the top of the terminal

### ISSUE THREAD

**Issue by Chronigan** [romkatv/powerlevel10k#1141]
I like the idea of the transient prompt/status line to cut down on screen clutter. Would it be possible tk keep the status line at the top of the terminal and just move the prompt down after a command is executed? For me that would look better and make more sense.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k-media/issues/2. It's fairly long but it explains why it's neither possible nor desirable to keep prompt at the top.
