### ISSUE TITLE
Issues with zsh 5.8

### ISSUE THREAD

**Issue by kenjc55** [romkatv/powerlevel10k#1142]
I am using osx with zsh 5.8.  zsh does not have is-at-least (is-at-least: function definition file not found).  I commented out the zsh version check in internal/p10k.zsh since I have 5.8 and 5.1 or higher is required. I discovered issues with vcs_info (vcs_info: function definition file not found).

**Comment by romkatv** [comment]
Seems like your installation of zsh is broken. I suggest filing a bug against the distributor that provided you with this package.

**Comment by kenjc55** [comment]
This turned out to be a $FPATH issue.  I had to make sure that the functions directory (/usr/local/Cellar/zsh/5.8_1/share/zsh/functions) was in my FPATH in my .zshrc before the power10k setup.
