### ISSUE TITLE
plz check, this issue.

### ISSUE THREAD

**Issue by sa96125** [romkatv/powerlevel10k#1143]
-- console output produced during zsh initialization follows --

/Users/chaplin/.oh-my-zsh/oh-my-zsh.sh:source:128: no such file or directory: /Users/chaplin/.oh-my-zsh/themes/powerlevel10k/powerlevel10k.zsh-theme

**Comment by romkatv** [comment]
On line 128 of `/Users/chaplin/.oh-my-zsh/oh-my-zsh.sh:source` you are attempting to `source` file `/Users/chaplin/.oh-my-zsh/themes/powerlevel10k/powerlevel10k.zsh-theme` but this file doesn't exist.

**Comment by romkatv** [comment]
You can fix this by following the installation instructions: https://github.com/romkatv/powerlevel10k/#oh-my-zsh

**Comment by sa96125** [comment]
Thank you:)

**Comment by kevinadhiguna** [comment]
@romkatv I ran the command but it did not fix the issue. It said : `fatal: destination path '/home/username/.oh-my-zsh/custom/themes/powerlevel10k' already exists and is not an empty directory.`

@sa96125 could you please let me know how did you overcome this problem? Thanks

**Comment by romkatv** [comment]
@kevinadhiguna What is the output of the following command?

```zsh
ls -l ~/.oh-my-zsh/custom/themes/powerlevel10k
```

**Comment by kevinadhiguna** [comment]
> @kevinadhiguna What is the output of the following command?
> 
> ```shell
> ls -l ~/.oh-my-zsh/custom/themes/powerlevel10k
> ```

here is the output :
![output](https://user-images.githubusercontent.com/43397636/102494505-5255c180-40a7-11eb-88e7-b95e2acfec57.png)

**Comment by romkatv** [comment]
Thanks. That means your issue is unrelated. Please don't comment on existing issues unless you are 100% sure you are experiencing the same problem. Open a new one instead and describe what's wrong.

**Comment by romkatv** [comment]
In you case the problem can be solved by opening `~/.zshrc` and removing line 107 from it. That line looks like this:

```zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

**Comment by kevinadhiguna** [comment]
> In your case the problem can be solved by opening `~/.zshrc` and removing line 107 from it. That line looks like this:
> 
> ```shell
> source ~/powerlevel10k/powerlevel10k.zsh-theme
> ```

Thanks for your help, it did not appear again.
