### ISSUE TITLE
No text wrapping

### ISSUE THREAD

**Issue by Donokami** [romkatv/powerlevel10k#1144]
![image](https://user-images.githubusercontent.com/5563277/101110427-3a773b80-35d9-11eb-9c64-6a2201236b8b.png)
On ZSH 5.8, with p10k the text doesn't wrap, which make powerlevel10k unusable.
Here are the config files:
https://gist.github.com/Donokami/34e35f27464195512b4e18dd491add4c

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k but otherwise leave your configs unchanged? Does it fix the issue?

**Comment by Donokami** [comment]
Yup:
![image](https://user-images.githubusercontent.com/5563277/101161890-da60b380-3631-11eb-82f6-9d4545d3fb7c.png)
I purged the installation multiple times, without success. This issue happens either on Tilix or Gnome Terminal, not tried on other terminal but probably the same!
The strange thing is the fact that other p10k users reported me that they didn't have this issue on zsh 5.8

**Comment by romkatv** [comment]
Please do the following:

1. Run `zsh -f`.
2. Copy-paste this block of command:
   ```zsh
   reset
   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /tmp/p10k
   repeat $COLUMNS print -n xx
   POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
   source /tmp/p10k/powerlevel10k.zsh-theme
   ```
3. Copy-paste this block of command:
   ```zsh
   repeat $COLUMNS print -n xx
   ```
4. Post a screenshot of your terminal.

**Comment by Donokami** [comment]
![image](https://user-images.githubusercontent.com/5563277/101163946-b2268400-3634-11eb-821c-420b77fda991.png)
btw, installing ZSH 5.4 on Ubuntu 20.04 did fix the issue (on this screen I reinstalled 5.8); the annoying thing is the fact that I can't install the amazing fix-winchange patch you made, since it does have this issue too

**Comment by romkatv** [comment]
Your screenshots show that text wrapping works fine. This means there is some interaction with your zsh config files. Try disabling *everything* except powerlevel10k. You should see that text wrapping works. Then try enabling things one by one until you find what causes text wrapping to break.

**Comment by Donokami** [comment]
Thanks alot for your help. You are right, the sed in 
```
neofetch --ascii_distro ubuntu_old | sed '$d' | sed '$d' | lolcat
```
which was at the start of my .zshrc was creating this bug.
I'll find another way to cut the 2 last lines of neofetch, but still thanks! :)
