### ISSUE TITLE
Wrong icon for node version

### ISSUE THREAD

**Issue by hrmoller** [romkatv/powerlevel10k#1145]
For node version I'm seeing the same icon as for system, isn't that wrong?

![Screenshot 2020-12-04 at 11 04 05](https://user-images.githubusercontent.com/645472/101150602-c06aa500-3620-11eb-9a97-73970acc34a9.png)

**Comment by romkatv** [comment]
The first shows version from `nodenv`, `nvm` or `nodeenv` (whichever one you are using). The second is likely `node_version` (it's disabled by default but I suppose you've enabled it).

Does this answer your question?

**Comment by hrmoller** [comment]
Yes all good thanks, my bad🙄

I was looking for an icon with same shape as the logo (blue ring), not the "N" in the name (red ring). I interpreted the N as a house repressing "Home" which confused me.

![Screenshot 2020-12-04 at 15 03 45](https://user-images.githubusercontent.com/645472/101173093-5662f780-3642-11eb-9cc4-1750f352a902.png)
