### ISSUE TITLE
How to remove the triangle on the left of the prompt

### ISSUE THREAD

**Issue by simokhwang** [romkatv/powerlevel10k#1146]
I am using Zsh on iTerm2, and I see a left triangle on the leftest side of the prompt. How can I remove that?

 
![image](https://user-images.githubusercontent.com/73351449/101187726-96f24f00-3609-11eb-9dd3-a2ca8dc9b30a.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/970
