### ISSUE TITLE
Valid commands don't turn green (right prompt works)

### ISSUE THREAD

**Issue by BitProcessor** [romkatv/powerlevel10k#1148]
Hi,

I am trying to get p10k working on Ubuntu 20.04 in WSL2
While most of it seems to work just fine, I can't seem to get the commands I type to turn green when recognized as a valid command. No special configs, simple p10k install from git, default ZSH from ubuntu (see details in screenshot). 

As you can see in the screenshot, the right prompt does show info related to the command (the kubecontext).

Am I missing a package? After searching the internet thoroughly, I just can't seem to find the reason why this isn't working. Help would be really appreciated. 

**In short:**
Expected behavior: typing a valid command on the prompt turns it green (cd, mkdir, kubectl...)
Current behavior: it stays white  

Thanks in advance.

![Screenshot 2020-12-05 230217](https://user-images.githubusercontent.com/50638541/101266346-551ef100-374e-11eb-9469-fde6a1935e2c.png)

```         
                "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
                "hidden": false,
                "name": "Ubuntu 20.04",
                "source": "Windows.Terminal.Wsl",
                "fontFace": "MesloLGS NF",
                "fontSize": 11,
                "cursorShape":"underscore"
            
```

**Comment by Anu2001dev** [comment]
install zsh-syntax-highlighting

**Comment by romkatv** [comment]
> install `zsh-syntax-highlighting` https://github.com/zsh-users/zsh-syntax-highlighting
> basically add `zsh-syntax-highlighting` to your plugins like this `plugins=(git zsh-syntax-highlighting)`

Thanks, @Anu2001dev . There is also https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by BitProcessor** [comment]
thanks @romkatv and @Anu2001dev - that was indeed it
