### ISSUE TITLE
Change The instant prompt character

### ISSUE THREAD

**Issue by Anu2001dev** [romkatv/powerlevel10k#1149]
How to change the instant prompt character? it's the same as the normal prompt char but it would be better if there was an environmental variable to change the instant prompt char.

**Comment by romkatv** [comment]
> it would be better if there was an environmental variable to change the instant prompt char.

This character serves the same purpose in the regular and instant prompt, so why use a different glyph?

**Comment by Anu2001dev** [comment]
so the thing is I am using to normal prompt chars for the prompt so it would be better if It displays 1 prompt char after executing the command. and further more emoji people can set emojis for that

**Comment by romkatv** [comment]
> so the thing is I am using to normal prompt chars for the prompt so it would be better if It displays 1 prompt char after executing the command. and further 

Sorry, I don't understand this. Can you elaborate? Perhaps you can show your current prompt looks like and explain how you want it to look like?

> more emoji people can set emojis for that

They can do so now, it just requires a few lines of configuration.

**Comment by Anu2001dev** [comment]
![prompt](https://user-images.githubusercontent.com/61502343/101285594-151e4380-380c-11eb-9a58-dee2c99e1738.png)
I said that it would be better if I could use only one arrow like char for a finished process rather than two which is the default prompt char

**Comment by romkatv** [comment]
Oh, you mean transient prompt rather than instant prompt?

Anyway, the practical suggestion is to use one character in both cases. Less space, the same amount of information. I would also recommend disabling left frame. It'll ensure that commands are always starting from the same offset.

If you really want to, you can implement your own `prompt_char` segment for instant prompt and then use `p10k-on-pre-prompt` and `p10k-on-post-prompt` hooks. Search through the issues for examples. I don't recommend it.

**Comment by Anu2001dev** [comment]
oh, sorry, my bad. and thanks for your time. but why don't you recommend it? does it affect performance

**Comment by romkatv** [comment]
> but why don't you recommend it? does it affect performance

It doesn't affect performance. I don't recommend doing it because I expect that the benefit you'll receive from this change will be lower than the costs.

**Comment by Anu2001dev** [comment]
oh, that. the cost wouldn't ever go be over knowledge I get
