### ISSUE TITLE
Last prompt not shown

### ISSUE THREAD

**Issue by MounirMesselmeni** [romkatv/powerlevel10k#1151]
The last prompt of last command is not shown, so I can't for example see when I did run the last command (One of the reason that I enable the time)

![image](https://user-images.githubusercontent.com/1055731/101490966-68ef7080-3963-11eb-9ce0-26f74e78469d.png)

After running pwd as an example
![image](https://user-images.githubusercontent.com/1055731/101491005-76a4f600-3963-11eb-9ed7-0d8ec6a11080.png)

I'm using ohmyzsh, Ubuntu 20 and zsh version 5.8. Also tried with a clean `.zshrc` file, but it did not help.
Is this by default or only happening to me?

Without powerlevel10k (Only ohmyzsh)
![image](https://user-images.githubusercontent.com/1055731/101492819-7f96c700-3965-11eb-8c92-9dd6d252b307.png)

Thanks in advance!

**Comment by romkatv** [comment]
Type `p10k configure` and when asked whether to enable Transient Prompt answer No.
