### ISSUE TITLE
custom prompt not showing

### ISSUE THREAD

**Issue by suhussai** [romkatv/powerlevel10k#1153]
I've just setup powerlevel10k and I was trying to get a custom prompt working. I noticed that whenever I set it, nothing would happen.

I assumed it was because of my prompt function, so I tried this:
``` 
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=prompt_example
```
Since I saw that `prompt_example` had already been set as follows: 
```bash
  function prompt_example() {
    p10k segment -f 208 -i '⭐' -t 'hello, %n'
  }
```
in `~/.p10k.zsh`

But I still didn't see any change in the right side prompt.

Is there something I'm missing here?

**Comment by romkatv** [comment]
Please do the following:

1. Open `~/.p10k.zsh`.
2. Search for `example` and uncomment the first hit.
3. Restart zsh with `exec zsh`.

Do you see the example prompt segment now?

**Comment by suhussai** [comment]
I do see it now. Thanks!
