### ISSUE TITLE
Weird alignment in VScode

### ISSUE THREAD

**Issue by Leuxll** [romkatv/powerlevel10k#1154]
<img width="1625" alt="Screenshot 2020-12-10 at 8 02 56 AM" src="https://user-images.githubusercontent.com/69574944/101703734-29896700-3abe-11eb-9ded-db28e8d47c27.png">
Referring to the above screenshot, the terminal prompt on the bottom has weird boxes and alignment issues.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render
