### ISSUE TITLE
Blurred prompt tails with black blackground rather than transparent.

### ISSUE THREAD

**Issue by DanielAtKrypton** [romkatv/powerlevel10k#1155]
![Imgur](https://i.imgur.com/A097SJ8.png)

If you look at the transparent prompt I have set in VS code, the blurred prompt tails are drawn with a black background when I believe it was supposed to be transparent here. To reach that setup follow [this](https://github.com/tonsky/FiraCode/issues/1161#issuecomment-734453611). Is there something that can be done to workaround that functionality?

**Comment by romkatv** [comment]
Indeed, it looks like a VSCode renders these glyphs incorrectly. If you decide to open a bug against VSCode, please post a link here. Other than that, I don't think there is anything you can do.

**Comment by DanielAtKrypton** [comment]
I think it is correctly displaying, actually. If you look closer, it is drawing the shadow of the blurred elements at the background. It is black because the Css tells the shadow to be black in this case.

**Comment by romkatv** [comment]
Zsh doesn't do css. Those tails are made of glyphs with grey foreground and no background. VSCode displays black of its own accord. Zsh doesn’t ask for anything black.

**Comment by romkatv** [comment]
I see on your screenshot that every character has black outline. That’s the culprit. Zsh doesn’t ask for it.

**Comment by DanielAtKrypton** [comment]
Everything is running perfectly!

**Comment by romkatv** [comment]
I'm glad you've managed to resolve this problem. For the sake of future users, can you leave a comment explaining how you did that?

**Comment by DanielAtKrypton** [comment]
I added outline and shadow in the CSS file so that I could use VS Code with the vibrancy effect with any background color without interfering on readability.

> I'm glad you've managed to resolve this problem. For the sake of future users, can you leave a comment explaining how you did that?

Sure!

If for example you remove some of the css lines from [here](https://github.com/tonsky/FiraCode/issues/1161#issuecomment-734453611):

![Imgur](https://i.imgur.com/n77YTBW.png)

Then restart VS code, it will not show neither outline or shadow.

**Comment by DanielAtKrypton** [comment]
Likewise one could add [glowing effect](https://www.w3schools.com/howto/howto_css_glowing_text.asp) or whichever HTML effect to it.

**Comment by romkatv** [comment]
I’m not following. I’ve a feeling you’ve opened an issue against a wrong project. Anyway, since everything is rubbing perfectly, all is well.

**Comment by DanielAtKrypton** [comment]
> 
> 
> I’m not following. I’ve a feeling you’ve opened an issue against a wrong project. Anyway, since everything is rubbing perfectly, all is well.

Indeed. I mistakenly opened here because I first thougth Powerlevel 10k was responsible for the black background in the blurred prompt tails. But instead I have found out that Powerleve10k is alright and the responsible for the apparently looking black background depicted above is actually the edited CSS file of the theme being used by the Vibrancy effect extension.

**Comment by romkatv** [comment]
Got it. Thanks for the explanation.
