### ISSUE TITLE
Right prompt is not aligned to the rightmost

### ISSUE THREAD

**Issue by yanzhang0219** [romkatv/powerlevel10k#1158]
Hello,

Probably this is a stupid question. I noticed that there is a little gap between the right prompt part and the right edge of the terminal (attached a screenshot below). Is it designed like this on purpose? Can I config to make it align to the right next to the edge?
![image](https://user-images.githubusercontent.com/11582667/101991233-27f7a480-3c60-11eb-9746-b38ed999a88a.png)

Thank you very much.

**Comment by romkatv** [comment]
It’s how zsh does it. If you have zsh 5.8, you can do this to remove the gap: `ZLE_RPROMPT_INDENT=0`

**Comment by yanzhang0219** [comment]
Great! Thanks.
