### ISSUE TITLE
prompt_char renders strangely in tmux

### ISSUE THREAD

**Issue by Keating950** [romkatv/powerlevel10k#1159]
Inside tmux:
<img width="148" alt="Screen Shot 2020-12-12 at 16 42 17" src="https://user-images.githubusercontent.com/43932454/101995595-0070fe00-3c99-11eb-9f15-ef83ad832152.png">

Outside tmux:
<img width="148" alt="Screen Shot 2020-12-12 at 16 42 35" src="https://user-images.githubusercontent.com/43932454/101995597-0a92fc80-3c99-11eb-9ab2-824dd1b7f4e7.png">

The issue is unaffected by setting `$TERM` to `screen-256color` in tmux via `set -g default-terminal "screen-256color"`.

OS: MacOS 11.0.2
Terminal: iTerm2 Build 3.4.2
Shell: zsh 5.8
Font: JetBrains Mono
tmux: tmux next-3.3

**Comment by Keating950** [comment]
<img width="139" alt="Screen Shot 2020-12-12 at 16 49 58" src="https://user-images.githubusercontent.com/43932454/101995696-13d09900-3c9a-11eb-941b-60d2ac3bf9f6.png">
It does correctly render when in visual mode, however.

**Comment by romkatv** [comment]
It seems like tmux is unable to display non-ascii characters for you. I don’t know why that may be but I do know it’s not related to powerlevel10k. If you are OK with just ascii in the terminal, run `p10k configure` from within tmux. If you want the ability to see non-ascii in tmux, you'll need to ask for help on tmux forums.

**Comment by Keating950** [comment]
Sounds good — I figured it being a tmux issue was possible. Thanks!
