### ISSUE TITLE
Multi-line prompt broken after "unify multiline prompt prefix parameters" commit

### ISSUE THREAD

**Issue by errantepiphany** [romkatv/powerlevel10k#116]
Multi-line prompts broke with this commit: https://github.com/romkatv/powerlevel10k/commit/502baefcec3a5e0f31cf322b8f67bab7457884f1 , and are still broken on master.

I use zplug to load powerlevel10k in my ~/.zshrc file, which gives me the ability to specify an exact commit-point for the plugin. When I set it to the earlier (previous) commit, everything works. I will add 4 screenshots with 4 different scenarios to this jira next, so you can see the behavior:

1) **good** - using the earlier/working commit
`zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme, at:28b9fe09`
Here everything displays properly:

![1_good_28b9fe09](https://user-images.githubusercontent.com/392133/61136482-c000c580-a491-11e9-9dd0-69d39381f6b9.png)

2) **good** - using the earlier/working commit, plus the env var to reduce space on the right prompt:
`zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme, at:28b9fe09`
`export ZLE_RPROMPT_INDENT=0`
Here everything displays properly also:

![2_good_28b9fe09](https://user-images.githubusercontent.com/392133/61136492-c55e1000-a491-11e9-945d-231b129fbcc4.png)

3) **bad** - using the later/broken commit
`zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme, at:502baefc`
Here the cursor is on the proper (left-hand) side, however the multi-line prompt white bracket is missing:

![3_bad_502baefc](https://user-images.githubusercontent.com/392133/61136514-ce4ee180-a491-11e9-8afd-34250a091e91.png)

4) **bad** - using the later/broken commit, plus the env var to reduce space on the right prompt:
`zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme, at:502baefc`
`export ZLE_RPROMPT_INDENT=0`
Here the cursor is on the wrong (right-hand) side - and the wrong color, _and_ the multi-line prompt white bracket is also missing:

![4_bad_502baefc](https://user-images.githubusercontent.com/392133/61137872-56ce8180-a494-11e9-82a3-acebbde13489.png)

Not sure what in the commit broke things, but I'm guessing it's probably broken for others as well. On the left-hand side of each screenshot, you can see my complete configuration section for powerlevel10k.

This is my environment:
`$ uname -a`
`Linux tpad 5.1.16-300.fc30.x86_64 #1 SMP Wed Jul 3 15:06:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`$ echo $ZSH_VERSION`
`5.7.1`

Thank you!

**Comment by romkatv** [comment]
Sorry about that. I've reverted the faulty commit for now. Will figure out later how to do the intended unification properly.

Thanks for the high quality bug report!

**Comment by errantepiphany** [comment]
@romkatv Much appreciated, thank you. (And yes, of course!) :)
