### ISSUE TITLE
[Request] Add a 'non_existant_dir' state (or similar) for use in dir_states

### ISSUE THREAD

**Issue by NICHOLAS85** [romkatv/powerlevel10k#1160]
I find myself in deleted directories more often than I expected and would like to be able to have p10k show me a different icon when I am in one. Currently, `*NOT_WRITABLE` is set showing me a lock icon. I'd like to know when I'm currently in a deleted directory instead of potentially being in an existing one and just not having the permission to write to it.

**Comment by romkatv** [comment]
Done. If you set `POWERLEVEL9K_DIR_SHOW_WRITABLE=v3`, you'll be able to use `_NON_EXISTENT` similarly to `_NOT_WRITABLE`.

**Comment by NICHOLAS85** [comment]
Thanks!

**Comment by NICHOLAS85** [comment]
Ahh I see what was causing my issue, I commented out `typeset -g POWERLEVEL9K_DIR_CLASSES=()` and then used `typeset -g POWERLEVEL9K_DIR_NON_EXISTENT_VISUAL_IDENTIFIER_EXPANSION=...` which didn't work. Is there a way of setting the NON_EXISTENT icon for all dir classes or would I have to specify each manually?

**Comment by romkatv** [comment]
> Is there a way of setting the NON_EXISTENT icon for all dir classes or would I have to specify each manually?

There is no built-in way to do that. You can use a loop in your own config although I would probably just copy-paste. Such config may be longer but will likely be easier to understand.

**Comment by NICHOLAS85** [comment]
Sounds good, thanks again.
