### ISSUE TITLE
Make transient prompt remain until the command you run has completed

### ISSUE THREAD

**Issue by jamesnunn** [romkatv/powerlevel10k#1165]
I find in a few scenarios that I need the info in the prompt to be available while I'm in a docker container, or some other interactive CLI. With transient prompt enabled, the prompt is removed the instant the command is run and doesn't appear until after I exit whatever interactive session I'm in or until a long running task exits. Is there a setting to make the prompt remain in place until the next one is just about to appear?

![Before I hit enter](https://user-images.githubusercontent.com/2095017/102478196-3aede880-4055-11eb-8eff-abb1a7c287ea.png)

![After I hit enter - no prompt until I exit the container](https://user-images.githubusercontent.com/2095017/102478405-74beef00-4055-11eb-8d3f-e57a5619c150.png)

**Comment by romkatv** [comment]
It's not possible to change prompt after a command starts running. The last chance to change it is right before a command starts running. See https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them.

**Comment by jamesnunn** [comment]
Thanks but I'm not really interested in the return code or changing the just-used prompt, just that it's worth keeping a prompt visible until the next one can be shown so environment info like path, branch, terraform status etc.

**Comment by romkatv** [comment]
I understand that. My comment still stands. The link I posted explains why what you are asking for is impossible.

**Comment by jamesnunn** [comment]
Understood, thanks for the quick response!
