### ISSUE TITLE
POWERLEVEL9K_LINUX_ICON won't apply when in SSH

### ISSUE THREAD

**Issue by ktheticdev** [romkatv/powerlevel10k#1166]
When SSH session is used, powerlevel10k ignores POWERLEVEL9K_LINUX_ICON varible, showing default Fedora icon instead.
Fedora icon is displayed:
![Screenshot_20201218-102428540](https://user-images.githubusercontent.com/64607352/102586448-3f7cd480-411b-11eb-9d86-63e0031a2ca4.jpg)
However config starts with:
![Screenshot_20201218-102507881](https://user-images.githubusercontent.com/64607352/102586506-54f1fe80-411b-11eb-83fa-fec39fb5777c.jpg)
Everything is fine when using URXVT on host:
![Screenshot_20201218_102541](https://user-images.githubusercontent.com/64607352/102586721-b6b26880-411b-11eb-9336-2a657a404476.png)

**Comment by romkatv** [comment]
`LINUX_ICON` is used on Linux distributions for which there is no distribution-specific icon. E.g., this is what youl get on Pop!_OS. For Fedora there is a distribution-specific icon, so you get `LINUX_FEDORA_ICON`. If you want to use a different icon on Fedora, override `POWERLEVEL9K_LINUX_FEDORA_ICON`.

If you want `os_icon` to always display a fixed icon, do this:

```zsh
POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF300'
```

Note that this defeats the purpose of `os_icon` because it no longer tells you which OS you are on.

If you are overriding `POWERLEVEL9K_*` parameters in `~/.zshrc`, make sure this is done **below** the line that sources `~/.p10k.zsh`, otherwise it will not have any effect.

**Comment by ktheticdev** [comment]
Actually I am using Arch, but the wrong icon is displayed.

**Comment by ktheticdev** [comment]
> `LINUX_ICON` is used on Linux distributions for which there is no distribution-specific icon. E.g., this is what youl get on Pop!_OS. For Fedora there is a distribution-specific icon, so you get `LINUX_FEDORA_ICON`. If you want to use a different icon on Fedora, override `POWERLEVEL9K_LINUX_FEDORA_ICON`.
> 
> If you want `os_icon` to always display a fixed icon, do this:
> 
> ```shell
> POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF300'
> ```
> 
> Note that this defeats the purpose of `os_icon` because it no longer tells you which OS you are on.
> 
> If you are overriding `POWERLEVEL9K_*` parameters in `~/.zshrc`, make sure this is done **below** the line that sources `~/.p10k.zsh`, otherwise it will not have any effect.

Actually I am using Arch, but the wrong icon is displayed.

**Comment by ktheticdev** [comment]
Exporting `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` doesn't help either:
![Screenshot_20201218-105147743](https://user-images.githubusercontent.com/64607352/102588895-35f56b80-411f-11eb-9a19-39d12164e60e.jpg)

**Comment by romkatv** [comment]
> Actually I am using Arch, but the wrong icon is displayed.

Please run the following command on the Arch host and post a screenshot here:

```zsh
cat /etc/os-release && typeset -pm '_p9k_os|_p9k_os_icon|POWERLEVEL9K_LINUX*'
```

> Exporting `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` doesn't help

Try this:

```zsh
print -r -- "POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=\$'\uF300'" >>~/.zshrc
exec zsh
```

**Comment by ktheticdev** [comment]
> > Actually I am using Arch, but the wrong icon is displayed.
> 
> Please run the following command on the Arch host and post a screenshot here:
> 
> ```shell
> cat /etc/os-release && typeset -pm '_p9k_os|_p9k_os_icon|POWERLEVEL9K_LINUX*'
> ```
> 
> > Exporting `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` doesn't help
> 
> Try this:
> 
> ```shell
> print -r -- "POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=\$'\uF300'" >>~/.zshrc
> exec zsh
> ```

Second variant worked, thanks.

**Comment by romkatv** [comment]
> > Actually I am using Arch, but the wrong icon is displayed.
> 
> Please run the following command on the Arch host and post a screenshot here:
> 
> ```shell
> cat /etc/os-release && typeset -pm '_p9k_os|_p9k_os_icon|POWERLEVEL9K_LINUX*'
> ```

I'd appreciate if you can lend your help here. You've reported a bug (Fedora icon is shown on Arch Linux) and I'd really like to fix it. If you have a free moment, please do what I've asked above.
