### ISSUE TITLE
NordVPN prompt segment is displayed even when I'm disconnected

### ISSUE THREAD

**Issue by ivan-preocanin** [romkatv/powerlevel10k#1167]
NordVPN prompt segment is displayed no matter if I'm connected or not, as shown on image below.

![2020-12-18-112806_1365x182_scrot](https://user-images.githubusercontent.com/20935129/102604236-2c223700-4124-11eb-897a-06381f8260c0.png)

Relevant settings:
```
  ##########[ nordvpn: nordvpn connection status, linux only (https://nordvpn.com/) ]###########
  # NordVPN connection indicator color.
  typeset -g POWERLEVEL9K_NORDVPN_FOREGROUND=6
  # Hide NordVPN connection indicator when not connected.
  typeset -g POWERLEVEL9K_NORDVPN_{DISCONNECTED,CONNECTING,DISCONNECTING}_CONTENT_EXPANSION=
  typeset -g POWERLEVEL9K_NORDVPN_{DISCONNECTED,CONNECTING,DISCONNECTING}_VISUAL_IDENTIFIER_EXPANSION=
  # Custom icon.
  typeset -g POWERLEVEL9K_NORDVPN_VISUAL_IDENTIFIER_EXPANSION='nord'
```

**Comment by romkatv** [comment]
Did it work before and recently broke after you've updated nordvpn?

**Comment by ivan-preocanin** [comment]
Now that you mentioned it, I did update nordvpn this morning. Yesterday it was working properly.

**Comment by romkatv** [comment]
Got it. I'll take a look later.

What's happening is that powerlevel10k is unable to retrieve status from nordvpn, so it renders the segment with the state set to `MISSING`. This is why you always see just "nord" without the country, whether you are connected or not. You can make it not show `MISSING` state by adding `MISSING` it to the list similar to how `DISCONNECTED` is handled in your config. This will not fix nordvpn for you, it'll just remove it completely.

**Comment by ariaieboy** [comment]
hi 
i am using the theme on ohmyzsh in fedora and the nordvpn segment dont work for me and wont show the connection status at all 
i didnt have any problem before but right now its broken
i am using nordvpn 3.8.8-1
with latest powerlevel10k theme pulled from github

**Comment by romkatv** [comment]
@ariaieboy See my comment above.

**Comment by romkatv** [comment]
Fixed.
