### ISSUE TITLE
[Help/Question] Block ending arrows aren't correct size

### ISSUE THREAD

**Issue by Machine-Maker** [romkatv/powerlevel10k#1168]
I downloaded the suggested font files and installed them, but the output looks a little off. Any suggestions for a fix would be greatly appreciated. 
<img width="980" alt="Screen Shot 2020-12-18 at 23 38 23" src="https://user-images.githubusercontent.com/15055071/102684066-4e4ea000-418a-11eb-9b13-1d78ede6c84b.png">

**Comment by romkatv** [comment]
Which terminal is this?

**Comment by Machine-Maker** [comment]
iTerm2 v3.4.3

**Comment by romkatv** [comment]
You need to tweak iTerm2 settings. If you didn't install the font manually, that would've been done by powerlevel10k automatically.

Here's what you can do:

1. Open iTerm2 settings and change the font to anything that is **not** MesloLGS NF.
2. Run `p10k configure`.
3. The first screen will ask whether you want MesloLGS NF to be installed. Say yes.

**Comment by Machine-Maker** [comment]
Yep, that did it. I'm planning to switch to this theme on my linux machine as well, which won't have iTerm2, so the font installation will have to be manual. What manual steps do I have to follow to make sure stuff lines up correctly?

**Comment by romkatv** [comment]
> Yep, that did it. I'm planning to switch to this theme on my linux machine as well, which won't have iTerm2, so the font installation will have to be manual. What manual steps do I have to follow to make sure stuff lines up correctly?

On most terminals it'll just work.

You can also switch from rainbow to lean style. The latter doesn't suffer from rendering issues anywhere and has much better signal-to-noise ratio.
