### ISSUE TITLE
Make Left Prompt Bold

### ISSUE THREAD

**Issue by mustaqimM** [romkatv/powerlevel10k#117]
Hi there and thanks for this awesome project and purepower!

I tried making the left prompt bold:
```zsh
local ins=$(_pp_s '>' '$bold_color$❯')
local cmd=$(_pp_s '<' '$bold_color$❮')
```
But when I try to tab autocomplete a word with zsh-autosuggestions, the first word is displayed twice.

![image](https://user-images.githubusercontent.com/24436622/61154278-37a81200-a4dd-11e9-9367-0e2e9792d1b8.png)

**Comment by romkatv** [comment]
ZSH doesn't allow raw escape codes in the prompt. You'll get the same behavior with this:

```zsh
PROMPT='$bold_color >' zsh -df
```

To make these symbols bold, do this:

```zsh
local ins=$(_pp_s '>' $'%B❯%b')
local cmd=$(_pp_s '<' $'%B❮%b')
```
