### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Machine-Maker** [romkatv/powerlevel10k#1170]
How can I prevent say longer-named git branches from being truncated? I've got a ultrawide monitor so I'd prefer if I didn't end up with `...` in the middle of the branch name when there is still tons of space left.

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `my_git_formatter` and edit it’s source code. You’ll find the line to change soon enough. There is a comment with a tip.
