### ISSUE TITLE
Native Apple Silicon (M1) build of gitstatusd

### ISSUE THREAD

**Issue by wozman** [romkatv/powerlevel10k#1172]
Although gitstatusd-darwin-x86_64 runs fine under Rosetta on Apple Silicon Macs it would be nice to have an arm64 binary working out of the box.

This is clearly possible as I've noticed that if I run `./build -w` in the gitstatus directory that I do get an arm64 binary called gitstatusd created in the gitstatus/usrbin subdirectory, and if I copy this to ~/.cache/gitstatus/gitstatusd-darwin-x86_64 it actually works fine, i.e. Powerlevel10k starts the gitstatusd-darwin-x86_64 (which is actually a native arm64 binary) in the background when the shell starts as normal.

I'm just trying to figure out what I need to do to make this work in a more elegant fashion rather than copying the manually built arm64 binary over the x86_64 binary

**Comment by romkatv** [comment]
With some luck, native arm64 support will land next week.

**Comment by wozman** [comment]
Awesome. You've clearly down the groundwork to produce the arm64 binary, so I figured this was on the way. Thanks!

**Comment by romkatv** [comment]
This is done.
