### ISSUE TITLE
git segment color change delay

### ISSUE THREAD

**Issue by arkantos493** [romkatv/powerlevel10k#1174]
Upon entering a git folder, the git segment appears. 
However, the segment's color changes with a slight delay and I don't think that's intended.

![powerlevel10k_lag](https://user-images.githubusercontent.com/38330545/102725408-cea20c00-4316-11eb-8f07-6354f32ed5ba.gif)

My p10k.zsh file looks as follows (github won't let me upload a .zsh file): [p10k.txt](https://github.com/romkatv/powerlevel10k/files/5721579/p10k.txt)

My laptop has an Intel i5-6200U CPU @ 2.30GHz (but I don't think that this is the bottleneck and the cause for the delay).
Is there any fix for this?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#why-does-git-status-sometimes-appear-grey-and-then-gets-colored-after-a-short-period-of-time

**Comment by arkantos493** [comment]
Thanks for the fast replay. Now it works.
