### ISSUE TITLE
Context (Left Prompt) in Lean mode

### ISSUE THREAD

**Issue by johnalanwoods** [romkatv/powerlevel10k#1175]
I used to use rainbow a lot and liked having "context" on the left...

"John@MacBook" type thing. I noticed in Lean that adding "context" doesn't work. Is this expected?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-add-username-andor-hostname-to-prompt

**Comment by johnalanwoods** [comment]
Thank you! Great work By the way. ❤️
