### ISSUE TITLE
zsh history same as new command 

### ISSUE THREAD

**Issue by Engazan** [romkatv/powerlevel10k#1176]
hi,
I would like to know how to change command history to looks same as new command ( with timestamp and folder )

already tried edit ```.p10k.zsh``` but can't find it :/

my zsh right now

<img width="893" alt="Snímka obrazovky 2020-12-21 o 23 30 21" src="https://user-images.githubusercontent.com/53254371/102829693-f44b1600-43e7-11eb-9cac-16d1378cbcc2.png">

**Comment by romkatv** [comment]
Type `p10k configure` and when asked whether to enable Transient Prompt answer No.
