### ISSUE TITLE
[Question] How do I remove the Git/Github icon?

### ISSUE THREAD

**Issue by naheller** [romkatv/powerlevel10k#1177]
When using a "many icons" configuration, I can see a Git branch icon as expected. How can I control the appearance of the Git/Github icon that sits next to it?

**Comment by romkatv** [comment]
This: https://github.com/romkatv/powerlevel10k/blob/38a5492b5f123acf62b7bc0aa1c06a88a9aac2d7/config/p10k-lean.zsh#L470

Set it to empty to get rid of the icon.

Pro tip: use the “few icons“ option. The extra icons enabled by “many icons” are decorative. All informative icons are shown either way.

**Comment by naheller** [comment]
Thanks for the tip - I've reconfigured to use "few icons." How do I turn the current directory folder icon on?

**Comment by romkatv** [comment]
Comment out or remove this line: https://github.com/romkatv/powerlevel10k/blob/38a5492b5f123acf62b7bc0aa1c06a88a9aac2d7/config/p10k-lean.zsh#L328

Note that this icon doesn’t add any information that wasn’t already present in the prompt.

**Comment by naheller** [comment]
Thanks for the lightning fast support! Closing ✅
