### ISSUE TITLE
glcoud indicator isn't visible

### ISSUE THREAD

**Issue by lhriley** [romkatv/powerlevel10k#1178]
Hello,

I recently installed the `google sdk` and it is setup and working for me. However, even with the `glcoud` plugin enabled, I don't see anything in the prompt. I found some related topics to this that were fixed earlier in the year, but I suspect that this problem is not quite the same (https://github.com/romkatv/powerlevel10k/issues/731).

I'm including the output of these comamnds for reference:
https://github.com/romkatv/powerlevel10k/issues/731#issuecomment-630977302

```
❯ print -r -- ${_p9k__param_pat%%$'\1'*}
v112
❯ () {
  emulate -L zsh -o xtrace
  typeset -pm 'P9K_GCLOUD_*'
  cat ~/.config/gcloud/active_config <(print)
  gcloud config configurations describe $P9K_GCLOUD_CONFIGURATION --format=$'value[separator="|"](properties.core.account,properties.core.project)'
}
+(anon):2> typeset -pm 'P9K_GCLOUD_*'
+(anon):3> print
+(anon):3> cat /home/<REDACTED>/.config/gcloud/active_config /proc/self/fd/14
default
+(anon):4> gcloud config configurations describe '--format=value[separator="|"](properties.core.account,properties.core.project)'
ERROR: (gcloud.config.configurations.describe) argument CONFIGURATION_NAME: Must be specified.
Usage: gcloud config configurations describe CONFIGURATION_NAME [optional flags]
  optional flags may be  --all | --help

For detailed information on this command and its flags, run:
  gcloud config configurations describe --help
```

Interestingly, in the terminal I get this, which doesn't seem to exist in the output of the function:
```
echo $P9K_GCLOUD_CONFIGURATION
default
```
However, it doesn't seem to appear in the debug output on line 4.

Additionally, if I run the command outside of the function I get what looks like the correct result (I've redacted the result):
```
gcloud config configurations describe $P9K_GCLOUD_CONFIGURATION --format=$'value[separator="|"](properties.core.account,properties.core.project)'
<email>|<project>
```

**Comment by romkatv** [comment]
Please describe what you do, what you observe and what you expect.

**Comment by lhriley** [comment]
When working with an active `gcloud` profile, I would expect that in my prompt I would see some text to appear similar to the form of:
```
<email>|<project>
```

This would be similar in nature to how the AWS plugin displays the active profile name in the prompt, which has worked for me as expected in the past.

(Thanks for the quick response btw!)

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k#why-some-prompt-segments-appear-and-disappear-as-im-typing

**Comment by lhriley** [comment]
Ah ha. Yes. That does seem to work. Did this behavior change recently? I recall that in the past if I had `AWS_PROFILE` set at all in my environment, the profile was always present.

I think maybe I was experiencing a bug with the initial error message, but this `SHOW_ON_COMMAND` option is definitely controlling it now.

**Comment by romkatv** [comment]
This isn’t a new feature but it’s a pretty good one. Without show-on-command I wouldn’t be able to enable many prompt segments by default because users often have kubernetes contexts, gcloud profiles, etc., that they don’t want to see all the time since they are almost never relevant.

**Comment by romkatv** [comment]
Closing as resolved.
