### ISSUE TITLE
RFE: Smart disable gitstatus in large repo

### ISSUE THREAD

**Issue by holymonson** [romkatv/powerlevel10k#1179]
Hi there, I'm working on a very large repo where `git status` may normally take ~10 seconds. Each time I hit Enter gitstatus will take ~2 seconds of full CPU time to output an unnecessary result.

May I ask if p10k could measure the cost of gitstatus, and automatedly disable it after several times of test until we leave that repo? Thanks.

**Comment by romkatv** [comment]
What is the output of the following command in the large repo?

```zsh
git ls-files | wc -l
```

**Comment by holymonson** [comment]
```
❯ git ls-files | wc -l
  323176
```

**Comment by romkatv** [comment]
Please try the following:

1. Open `~/.p10k.zsh`, find `POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY` and change its value to `100000`.
2. Restart zsh with `exec zsh`.
3. Navigate to the large repository and see if the performance is acceptable.

Here's the meaning of the parameter:

```zsh
# Don't count the number of unstaged, untracked and conflicted files in Git repositories with
# more than this many files in the index. Negative value means infinity.
#
 # If you are working in Git repositories with tens of millions of files and seeing performance
# sagging, try setting POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY to a number lower than the output
# of `git ls-files | wc -l`. Alternatively, add `bash.showDirtyState = false` to the repository's
# config: `git config bash.showDirtyState false`.
```

**Comment by holymonson** [comment]
Thanks! This save my ass.
