### ISSUE TITLE
Free RAM seems inaccurate, on M1 Mac (Apple Silicon/ARM64)

### ISSUE THREAD

**Issue by johnalanwoods** [romkatv/powerlevel10k#1181]
I'm not sure how RAM is being calculated for the RHS widget, but it seems to show a very low RAM value, the only thing I can think is that it's not showing free available RAM but instead, also treating "cached files" as used RAM.

Is there a way to tweak this?

Seems to maybe use `vm_stat` under the hood?

**Comment by romkatv** [comment]
`ram` segment shows the amount of unused physical memory:

- On macOS: pages free + pages inactive from `vm_stat`
- On FreeBSD: avail memory from `/var/run/dmesg.boot`
- On Linux: MemAvailable or MemFree from `/proc/meminfo`

There is no option to change what `ram` segment shows. It's always the amount of unused physical memory.

**Comment by johnalanwoods** [comment]
@romkatv  - thanks as always for quick reply.

I think we have a bug, because that's what I expect.

<img width="834" alt="Screenshot 2020-12-23 at 20 28 13" src="https://user-images.githubusercontent.com/5158898/103034738-79a40700-455d-11eb-87f8-03854856806d.png">


I think the calculation is incorrect. on my system P10k is showing only 1.67GB free of RAM.

`vm_stat` shows, `61996` (pages free) `377102` (pages inactive) yielding -> `439098` total pages * `16384` byte page size, gives a grand total of `7194181632` bytes, or just over 7GB.

As you can see from the screenshot, this is not being calculated right, I think you are using a page size of `4096` incorrectly.
On Big Sur the page size is `16384`

**Comment by johnalanwoods** [comment]
@romkatv oh meant to add, this is on an M1 Mac, this is specific to ARM64!

We need to check the page size, and base it on that.

**Comment by romkatv** [comment]
Thanks!

Do you happen to know how to query the page size on macOS? Or perhaps a link to the documentation that says that darwin-arm64 has 16k pages?

**Comment by johnalanwoods** [comment]
@romkatv, so on macOS (BSD) you can grab the system pagesize using the `pagesize` command.

```
DESCRIPTION
     The pagesize utility prints the size of a page of memory in bytes, as returned by getpagesize(3).
     This program is useful in constructing portable shell scripts.
```


`pagesize -- print system page size`, on my M1 it's `16384`.

I can't find documentation for this (though it's implicit with the ARM64 architecture. Though I do some low level cryptographic engineering on macOS and I can tell you, Apple's docs in this type of low level stuff is non-existent or out of date.

**Comment by romkatv** [comment]
Fixed.
