### ISSUE TITLE
Colors of the right tooltip do not change

### ISSUE THREAD

**Issue by boris-gu** [romkatv/powerlevel10k#1182]
Colors of the right prompt do not change. The left prompt is okay.
I thought I needed to change the values shown in the screenshot. I changed from black to white (0 to 254). Then I saved the file and entered "source ~/.p10k.zsh" into the terminal. But nothing has changed.
What am I doing wrong?
![image](https://user-images.githubusercontent.com/44787162/103041957-fd271d80-4588-11eb-9b8e-f95f9a0d62e1.png)

**Comment by johnalanwoods** [comment]
That line is commented out. Notice the hashtag/pound symbol at the start of the line. 

It's being ignored as expected.

**Comment by romkatv** [comment]
> That line is commented out. Notice the hashtag/pound symbol at the start of the line.
> 
> It's being ignored as expected.

Thanks, @johnalanwoods.

Closing as Working as Intended.
