### ISSUE TITLE
Custom Short Directory Path

### ISSUE THREAD

**Issue by mziminski** [romkatv/powerlevel10k#1183]
Hi,

I've looked through a lot of the other short directory path issues, but I haven't stumbled across one that fit what I was looking for.

I would like to get the prompt's directory path to behave in this way (be shortened): ~/.../anchor_files 
when in a directory with .git present, otherwise have the normal truncate_to_unique path.

How can I do this?

And how does this line work?
typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"

To be more specific, I'm wondering what's the role of the j and the |? 

And this is from my .p10k.zsh config file.

Thanks in advance.

**Comment by romkatv** [comment]
> I would like to get the prompt's directory path to behave in this way (be shortened): ~/.../anchor_files
when in a directory with .git present

Please give a more specific example.

> To be more specific, I'm wondering what's the role of the j and the |?

See `man zshexpn`. You can also add this in your `~/.zshrc` to see the effect of this code:

```zsh
typeset -p anchor_files POWERLEVEL9K_SHORTEN_FOLDER_MARKER
```

**Comment by mziminski** [comment]
Example: ~/foo/1/2/bar/git_repo/nested_git_repo/baz

I just realized that part of what I want is actually there, but I just wasn't testing it correctly. 
I added "last" to typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER="last" in the .p10k.zsh file.
And this brought me closer to what I want, but not quite.

Then using the example, I'd like this to happen in zsh powerlevel10k prompt:
when not in a git repo, I'd like the shortened directory path to be ~/.../bar or ~/../2
when in a git repo, I'd like the shortened directory path to be /../baz or /./nested_git_repo

So, would it be possible to implement this functionality, with "." representing 1 truncated directory, then ".." representing 2, and so on? Because I'm not quite sure how to further edit "(${(j:|:)anchor_files})" or the rest of this section to reflect this.

**Comment by romkatv** [comment]
> Example: ~/foo/1/2/bar/git_repo/nested_git_repo/baz

I like this example because it's specific. Can you describe what you want to see in path when you are in this directory? Don't use any dots to represent anything. Tell me the exact  content of prompt.

If this example won't be enough to understand what you want, I'll ask for more examples. If you anticipate that a single example doesn't showcase the full logic of what you want, go ahead and proactively provide several examples. Each example should be of the form "if I'm in directory X, I want to see Y in prompt".

**Comment by mziminski** [comment]
Sorry not being more clear, but I would like the dots to represent a truncated directory, and I wasn't using them to arbitrarily represent something (they have a purpose).

And I'll use the above example ~/foo/1/2/bar/git_repo/nested_git_repo/baz to describe what I would like to see.

Not in git repo.
If I'm in directory foo, I would like to see ~/foo in the prompt.
If I'm in directory bar, I'd like to see ~/.../bar in the prompt.

In git repo:
If I'm in directory git_repo, I'd like to see /git_repo in the prompt.
If I'm in directory baz, I'd like to see /../baz in the prompt.

So the dots basically represent the hidden directories between ~ and the anchor_file (when not in a git repo) or / and the anchor_file (when in a git repo). And I'd like the / to be shown when in a git repo, not like how it's hidden when using "last"

**Comment by romkatv** [comment]
I'm not sure I understand what you want but there is a very high chance I won't be adding this functionality. Your best bet is to implement this as a custom prompt segment. Search for `prompt_example` in `~/.p10k.zsh` and run `p10k help segment`. Good luck!

**Comment by mziminski** [comment]
I'm hoping these pictures help getting my point across, because I'm not sure I can explain it any better, but basically all I want is to modify the directory path that's being displayed (the blue/cyan) in the below images
![image](https://user-images.githubusercontent.com/26189380/103104421-a5220280-45ec-11eb-9ab5-d43d2c82aeb2.png)
![image](https://user-images.githubusercontent.com/26189380/103104460-f0d4ac00-45ec-11eb-90b3-316bc4e4ae83.png)

So what I would like to happen is for "\~/foo/1/2/bar" to become "\~/.../bar" and "git_repo/nested_git_repo/baz" to become "/../baz" 

Is this possible to do without using a custom prompt segment? Or how can I modify the truncate_to_unique call in 
"typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique" to do what I want?

I tried looking for were the code for truncate_to_unique resides and modifying it, but I don't know where it resides.

Anyways, thanks for the quick replies!

**Comment by romkatv** [comment]
I'm not sure I understand what you want but this custom segment will work for the two examples you've provided:

```zsh
function prompt_my_dir() {
  p10k segment -f 75 '%3(~|%-1~/../%1~|%~)'
}
```

Given this definition, you can use `my_dir` in place of `dir` within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.

If this doesn't do exactly what you want, I highly recommend changing it. It's extremely unlikely I'll be modifying the core of powerlevel10k to do what you want. Good luck!

**Comment by romkatv** [comment]
Sorry, I didn't notice that you want the current directory to be displayed as absolute when you are in a git repo. This should do it:

```zsh
function prompt_my_dir() {
  local c
  git rev-parse --is-inside-work-tree 2>/dev/null && c=/ || c='~'
  p10k segment -f 75 -t "%3($c|%-1$c/../%1$c|%$c)"
}
```

**Comment by mziminski** [comment]
Thanks, I'll take a look at these. And I wasn't expecting you to modify the core functionality, I was just looking for some help on modifying my prompt.
