### ISSUE TITLE
Refactor 9k script to 10k script (Question, _prompt_segment)

### ISSUE THREAD

**Issue by TheBabu** [romkatv/powerlevel10k#1184]
Hello,
I upgraded from 9k to 10k without really changing my settings at all that much. But recently I noticed my "background" indicator is broken, presumably because I upgraded.

I'm not going to lie, I forgot where I got this script so I'm not sure if it has been updated in that source.

```
#Background Jobs Function
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
prompt_background_jobs() {
local background_jobs_number=${$(jobs -l | wc -l)// /}
local wrong_lines=`jobs -l | awk '/pwd now/{ count++ } END {print count}'`
if [[ wrong_lines -gt 0 ]]; then
     background_jobs_number=$(( $background_jobs_number - $wrong_lines ))
  fi
  if [[ background_jobs_number -gt 0 ]]; then
    local background_jobs_number_print="1"
    if [[ "$POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE" == "true" ]] && [[ "$background_jobs_number" -gt 1 ]]; then
      background_jobs_number_print="$background_jobs_number"
    fi
    "$1_prompt_segment" "$0" "$2" "$DEFAULT_COLOR" "cyan" "$background_jobs_number_print" 'BACKGROUND_JOBS_ICON'
  fi
}
```

The error that I get when I try to get now when I try to run a command in the background is: `prompt_background_jobs:11: command not found: _prompt_segment`

So I'm guessing that parameter named got changed when I upgraded.

Thanks for any help.

**Comment by romkatv** [comment]
The code snippet you've posted overrides a function from p9k and invokes an internal function (`"$1_prompt_segment"`). This don't work in p10k (it also could break if p9k was ever updated).

Here's what you need to do:

1. Remove the whole function `prompt_background_jobs` from your config. Leave `POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true` as is.
2. Add `POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=true` to your config.
2. Restart zsh with `exec zsh`.

This should make background jobs to be displayed the same as you had it before but it'll be *much* faster.

If you have any other custom prompt segments, you'll probably want to remove/replace them. If you post their code, I can help you with the transition.

**Comment by romkatv** [comment]
One more thing. Consider running `p10k configure`. It'll generate a new config in `~/.p10k.zsh` and append a line to `~/.zshrc` to source it. If you don't like the result, either run `p10k configure` again to generate another config or delete the bottom line from `~/.zshrc` to get back to your original prompt. `p10k configure` can also enable [instant prompt](https://github.com/romkatv/powerlevel10k#instant-prompt), which greatly speeds up zsh startup. If you choose *Yes* when `p10k configure` asks whether to enable instant prompt, it'll add a few lines at the top of `~/.zshrc`.

**Comment by TheBabu** [comment]
Thank you so much for you answer! Not only you fixed my problem, you made my setup better :)

From what I read the only code that enabled instant prompt is:
```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

Closing issue.

**Comment by romkatv** [comment]
> From what I read the only code that enabled instant prompt is:
> 
> ```
> if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
>   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
> fi
> ```
> 
> Is that correct?

Instant prompt is enabled by adding the code snippet you've quoted at the top of `~/.zshrc`.

Once again: consider running `p10k configure`. If you don't like the results, simply delete `~/.p10k.zsh`.

**Comment by TheBabu** [comment]
I did do `p10k configure`, but I perfer keeping my previous configuration the way it was.
Thank you again for the help!
