### ISSUE TITLE
jupyterhub terminal does not show icon

### ISSUE THREAD

**Issue by newTypeGeek** [romkatv/powerlevel10k#1186]
When I open a terminal from JupyterHub on my local laptop, the icon fails to show up as shown below
<img width="1147" alt="jupyterhub-terminal" src="https://user-images.githubusercontent.com/38719080/103163623-469e9380-483b-11eb-9bc7-82e96ad9343c.png">

But when the terminal is opened using iTerm2, the icon is here as shown below
<img width="1435" alt="local-terminal" src="https://user-images.githubusercontent.com/38719080/103163660-d17f8e00-483b-11eb-85ad-3141c830254a.png">

### Spec
- macOS Big Sur 11.1
- jupyter core 4.7.0
- jupyter-notebook 6.1.6

**Comment by romkatv** [comment]
JupyterHub on your terminal is using a font that doesn't have glyphs for the icons used by your prompt. It's also incapable of displaying 256 colors (it can display only 8). The best solution would be to change the font and to enable 256 colors. If this isn't possible (I don't use JupyterHub myself so I don't know), run `p10k configure` from the JupyterHub terminal to generate a new prompt config that uses only 8 colors and doesn't use icons.
