### ISSUE TITLE
Prompt elements display in rectangles instead of arrow with triangle on Ubuntu18.04

### ISSUE THREAD

**Issue by jet-chien** [romkatv/powerlevel10k#1187]
My terminal output:
![image](https://user-images.githubusercontent.com/67193495/103167448-2df7a300-4866-11eb-85b3-cdf78102648d.png)

Expected outlook:
![image](https://user-images.githubusercontent.com/67193495/103167478-55e70680-4866-11eb-857e-cebfa5473f51.png)

**Comment by romkatv** [comment]
Run `p10k configure` and select the style you want. If there is no style with arrows, see https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard.

**Comment by jet-chien** [comment]
I am using Ubuntu18.04 and my zsh version is 5.4.2, can I ask how to install the version that is higher than 5.7.1?

**Comment by romkatv** [comment]
> I am using Ubuntu18.04 and my zsh version is 5.4.2, can I ask how to install the version that is higher than 5.7.1?

You can install zsh 5.8 with this: https://github.com/romkatv/zsh-bin#installation
