### ISSUE TITLE
Support for Multiline RPROMPT

### ISSUE THREAD

**Issue by vinay0410** [romkatv/powerlevel10k#119]
Currently RPROMPT elements doesn't support newline as an element.
It would be very helpful to have this support.

**Comment by romkatv** [comment]
I just merged the support for multiline right prompt into master. These are pretty big changes with lots of corner cases. Let me know if you notice anything weird.

**Comment by vinay0410** [comment]
Hi @romkatv , I have verified it, and it's working great

**Comment by romkatv** [comment]
Thanks for the verification!

By the way, if you are using powerline-style prompt, you might like these options: https://github.com/romkatv/powerlevel10k/blob/dadab0ef5fff54d71ce247e5fcce4381f3d30354/config/p10k-classic.zsh#L53-L60

The `PREFIX` options have existed before but the `SUFFIX` ones are new. Makes prompt more symmetric.
