### ISSUE TITLE
confusing display at end of line

### ISSUE THREAD

**Issue by rhysburnie** [romkatv/powerlevel10k#1191]
Hi Im new to using this but am confused by a couple of things here...
after both these commands (one bing an error) it displays `HUP` and `127` are they supposed to be icons that aren't working?

<img width="638" alt="image" src="https://user-images.githubusercontent.com/245933/103331364-283fce80-4aad-11eb-9a60-bccc477ab256.png">

<img width="642" alt="image" src="https://user-images.githubusercontent.com/245933/103331377-355cbd80-4aad-11eb-89bf-0d85fcf3855b.png">

**Comment by romkatv** [comment]
That red thing on the right display the exit code of the last process. In the second case it's 127, which is the common exit code for when a command is not found. `HUP` is another name for the exit code 129. This is normally returned when a process is killed by `HUP` signal. Some programs (like `git`) return 128 even when they aren't killed by `HUP`, so this can be a bit confusing. Most of the time it works fine though. For example, try running `sleep 10` and hit <kbd>Ctrl+C</kbd>. You should see `INT` that tells you that the job was killed by `INT` (short for "interrupt") signal, a.k.a. exit code 130.

**Comment by rhysburnie** [comment]
@romkatv cheers - I just worked that out looking at the config here 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/245933/103331630-62f63680-4aae-11eb-8b82-5ad0e20c28ef.png">

**Comment by romkatv** [comment]
That segment is very useful as it shows you whether the last command has succeeded or failed. I don't recommend disabling it. It's possible to make it less verbose if you want. For example, you can configure it to not show `HUP` or `127` but still show the red cross when a command fails.

**Comment by rhysburnie** [comment]
yeah I only disabled it to see if it was that line have left it enabled now
