### ISSUE TITLE
Question: How to add custom icon for ssh connection

### ISSUE THREAD

**Issue by blacknet76** [romkatv/powerlevel10k#1192]
Hi a short question I want to add the SSH_ICON into this 
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
e.g. '$SSH_ICON %n' but I do not know how
Can anyone explain me how to add the custom icon?

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and add the following line:

```zsh
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_VISUAL_IDENTIFIER_EXPANSION=$'\uF489'
```

Restart zsh with `exec zsh`.

Does this do what you want?

You can replace the value with any icon of your choice.

**Comment by blacknet76** [comment]
Thanks for the quick answer, yes this is what I wanted.
And it is so simple.
