### ISSUE TITLE
hook into prompt to execute custom VT sequence (without output!)

### ISSUE THREAD

**Issue by christianparpart** [romkatv/powerlevel10k#1193]
Hey,

this may seem like a little strange intent, but I want to execute a VT sequence (that is neither producing output nor changing the text cursor state) at the beginning of each prompt.

In my case and my terminal, that is `\033[<M`, a custom VT sequence to bookmark the current position, so I can cycle through each prompt top's via shortcuts later.

But I can't get p10k to not shout at me either because I am printing to stdout (via `echo -ne ...`) during zsh initialization phase, or it produces bad output during each prompt.

I tried
```sh
preprompt_setmark() {
    echo -ne "\033[>M"
}
# ...
precmd_functions=( $precmd_functions preprompt_setmark)
```

And via p10k segment:
```sh
prompt_setmark() {
    #echo -ne $"%{\033[>M%}$"
    p10k segment -t $"%{\e[>M%}$"
}
# ...
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=setmark
```

None of the above solutions did yield satisfying results, so I wonder what I could to do tame p10k.

Happy new year,
Christian.

**Comment by romkatv** [comment]
Try this:

```zsh
precmd_setmark() print -n '\e[>M' >$TTY
autoload -Uz add-zsh-hook
add-zsh-hook precmd precmd_setmark
```

**Comment by christianparpart** [comment]
@romkatv I've added your suggestion to my `~/.zshrc` at the bottom and that actually works best out of all 3 solutions now. Many thanks for that. (Maybe it's worth mentioning in a README about how to inject arbitrary VT sequences at the prompt for advanced uses?)

**Comment by romkatv** [comment]
The code snippet I've posted is not specific to powerlevel10k. It's generic zsh code that works with any theme. The documentation is already too bloated, so I wouldn't want to such a niche thing to it.

**Comment by christianparpart** [comment]
I agree with that. But many thanks for your feedback, that greatly helped me. :)
