### ISSUE TITLE
Can powerlevel10k enable or hide some secondary display elements by identifying things like DPI?

### ISSUE THREAD

**Issue by daiaji** [romkatv/powerlevel10k#1196]
I installed zinit and powerlevel10k in Ternux, but powerlevel10k does not seem to be able to enable all the elements when using Ternux on the vertical screen, but after I rotate the screen to the horizontal screen, everything is the opposite.
The same situation also happened after I connected the Ternux terminal on the phone via ssh.
Can powerlevel10k enable or hide some secondary display elements by identifying things like DPI?

**Comment by romkatv** [comment]
Powerlevel10k doesn’t know the DPI of your screen nor the orientation of your phone. Sorry.
