### ISSUE TITLE
Ram usage instead of  free ram

### ISSUE THREAD

**Issue by KonstantMan** [romkatv/powerlevel10k#1197]
It's not really an issue but i prefer to see the used ram ram instead of free , it would be something like used_ram =( system_ram - free_ram )  but i don't how to implement this in powerlevel10k

**Comment by romkatv** [comment]
Search for "prompt_example" in `~/.p10k.zsh` for an example of a custom prompt segment. With enough determination you can define a segment that shows ram usage.
