### ISSUE TITLE
p10k sets OS shell variable

### ISSUE THREAD

**Issue by yacoob** [romkatv/powerlevel10k#1198]
Not strictly a bug, more of a unexpected (?) side effect. I've bumped into this, as I use `OS` variable for my own purposes (in https://github.com/yacoob/conf) and I've noticed a discrepancy. p10k with a default config seems to be setting `OS=Linux`. This should be either avoided, or clearly documented.

How to reproduce:
https://asciinema.org/a/BCVhVNRJEThuxGnCej4WCcc09
I've used docker to launch a clean copy of zsh, check if the variable is unset, install p10k, restart zsh - and the variable appeared.

**Comment by romkatv** [comment]
I know. I don’t like it at all. Cannot change this because it’ll break existing users. I don’t think it’ll help anyone if it gets documented.

**Comment by yacoob** [comment]
Well, it'd have helped me in tracing down what fiddles with that variable. :D Hence, I've opened this bug just in case someone else bumps into this.

At least we'll have a bug entry here.
