### ISSUE TITLE
Use latest version of gitstatus for Apple Silicon support

### ISSUE THREAD

**Issue by melgu** [romkatv/powerlevel10k#1199]
The [latest release](https://github.com/romkatv/gitstatus/releases/tag/v1.4.4) of gitstatus added native support for ARM64. It'd be nice to use that instead of relying on Rosetta for translation.

**Comment by romkatv** [comment]
Powerlevel10k is always using the latest version of gitstatus. If your local copy of powerlevel10k doesn’t have a native gitstatusd binary for arm64, simply update it.

**Comment by melgu** [comment]
I'm using zprezto. Do I wait for the next zprezto update or should I update powerlevel10k individually?

**Comment by romkatv** [comment]
Up to you. Consider leaving a comment on https://github.com/sorin-ionescu/prezto/pull/1878.
