### ISSUE TITLE
nvm slows down prompt considerably

### ISSUE THREAD

**Issue by FallingSnow** [romkatv/powerlevel10k#12]
When adding `nvm` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=` the prompt slows down considerably to 100-200ms per prompt.

Not a deal breaker, just thought you should know.

**Comment by romkatv** [comment]
Thanks for letting me know. It's one of the prompts I haven't optimized yet (I don't even know what nvm is). If someone me-too's this issue or if I get bored, I might look into. Your best bet is to try to optimize it yourself and send a PR. It's best if you send it to Powerlevel9k. I upstream everything, so your patch will benefit more people this way.

P.S.

I'm assuming that nvm is also slow in Powerlevel9k. If not, it changes everything and I'll debug right away.

**Comment by FallingSnow** [comment]
> Your best bet is to try to optimize it yourself and send a PR.

All good. I'm just going to not use it for right now :)

> I'm assuming that nvm is also slow in Powerlevel9k.

Same. I assume if I open this in Powerlevel9k they are just going to tell me "yeah, we know". And I don't really care about it enough to put any effort into it haha. I'll leave this open in case more people are affected by it.

Btw nvm is the *node version manager*. Kind of like letting you switch on the fly between python2 and python3 but with node.

**Comment by romkatv** [comment]
@FallingSnow Should be fast now. Please try.

I had to reimplement about half of nvm code to achieve the speedup. Please open an issue if you notice anything weird in how nvm prompt now works.

**Comment by FallingSnow** [comment]
I'll report back if I have any issues. Thank you for your hard work!
