### ISSUE TITLE
shell prompt redisplay and text reflowing terminals

### ISSUE THREAD

**Issue by christianparpart** [romkatv/powerlevel10k#1200]
Hey,

While experimenting with text reflow algorithms and looking at probably most of the other terminals supporting text reflow, what I noticed is that the zsh shell prompt display (at least for the two-line prompts) is broken on all terminals.

AFAICT this makes sense because the reflow upon resize is wrapping/unwrapping lines. When now a prompt is also having text on the right margin, too, it's meant to break, because zsh/p10k just doesn't know about that its one/two lines shell prompt where now split up into 2/3/4 lines.

One way to work around this is using some terminal features to better integrate with the shell. What I see that could work is that the shell/p10k tells the terminal which lines must not be reflown (via sending out a VT sequence that is telling the terminal to block reflow on the text line the cursor is currently positioned in).

While such a VT sequence does not exist yet in a defacto-standardized way -(we could eye at the terminal-wg here, as there have been some attempts to improve convergense in shell integration VT sequences)- it would be nice if p10k provides a hook to allow sending VT sequences for each line the shell prompt is being rendered in. Pretty much like the `precmd` zsh hook, but for each line that the prompt is about to be rendered to, maybe a `prerender` hook?

What do you think?

**Comment by romkatv** [comment]
If such a VT sequence existed, it would need to have the following meaning:

- Text below the last printed sequence of this kind is not reflown when the terminal is resized.

This is because prompt is not the only thing that can reflow and break zle. Everything else that zle prints (the command line, completion menu, etc.) also shouldn't reflow.

If any terminal adds support for this sequence, it can be printed in `precmd`.

**Comment by christianparpart** [comment]
> Text below the last printed sequence of this kind is not reflown when the terminal is resized.

Oh I didn't think of that. You are right. The way I see that is just like `SM`/`RM` sequences for enabling/disabling that semantics.

But that would require apart from `precmd` to also have some kind of `postcmd` to disable this mode again, so the command output itself can be wrappable again. - Sorry if I'm a little dumb with regards to zsh/p10k knowledge. That's still fairly new to me. :)

**Comment by romkatv** [comment]
> But that would require apart from `precmd` to also have some kind of `postcmd` to disable this mode again

That would be `preexec`.

It appears there is nothing to do w.r.t. this issue in Powerlevel10k. Close?

**Comment by christianparpart** [comment]
Yeah, we can close this. But many thanks for your feedback. :)
