### ISSUE TITLE
P10K clutters on changing terminal size

### ISSUE THREAD

**Issue by cr-trojan23** [romkatv/powerlevel10k#1201]
Hi, I recently found this bug because of which P10K prompt's left and right elements completely displace upon maximizing and minimizing the terminal. Here is an image:
![image](https://user-images.githubusercontent.com/42072570/103601347-73cffd80-4f2f-11eb-9d03-46272f5d0d47.png)
<be>
I'm using Oh My Zsh (fully updated)<be>
Resizing a terminal does this (happens only when the terminal is already maximized or minimized) :
![image](https://user-images.githubusercontent.com/42072570/103601781-65ceac80-4f30-11eb-9840-5fed4ba8bd0c.png)
<be>
Kindly help me resolve this issue.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
