### ISSUE TITLE
Incorrect colours in *-diresct terminals (truecolor terminfo)

### ISSUE THREAD

**Issue by tecosaur** [romkatv/powerlevel10k#1202]
Hello!

This project is fantastic! I've just got a bit of an issue with the colour whenever I try to use a truecolor `TERM`.
I think this issue is pretty well illustrated by the image below, where I use the "test the colors" snippet from the readme:

![image](https://user-images.githubusercontent.com/20903656/103664544-5b9ec380-4fad-11eb-9f21-ee28600a1957.png)

If I change the `print` statement to `echo` the ANSI escape codes for 8-bit colour, then everything works as expected.

![image](https://user-images.githubusercontent.com/20903656/103665008-dcf65600-4fad-11eb-948a-aa5b0de82220.png)

I have no idea what's causing this, but it would be great if it could be resolved :slightly_smiling_face:

**Comment by tecosaur** [comment]
> direct value of TERM doesn’t do what you think it does. You probably don’t want what it actually does.

Setting `TERM` to, e.g. `kitty-direct` or `alacritty-direct` should just direct any process looking at the terminal to a terminal that advertises 24-bit color support as I understand it.

Comparing terminfo for `xterm-kitty` to `kitty-direct` contains:
```diff
- 	colors#0x100, cols#80, it#8, lines#24, pairs#0x7fff,
+	colors#0x1000000, cols#80, it#8, lines#24, pairs#0x10000,
...
- 	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
-	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,L
+	setab=\E[%?%p1%{8}%<%t4%p1%d%e48\:2\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m,
+	setaf=\E[%?%p1%{8}%<%t3%p1%d%e38\:2\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&%d\:%p1%{255}%&%d%;m,
```

Is my understanding incorrect?

> Does everything work fine if you keep TERM unchanged? If not, please describe what you want to see and what you actually see.

That's what the 1st and 3rd panels show. The `TERM` is set to the `*-direct` variants in the 2nd and 4th panel.
When I set this other TUIs that provide 24-bit color support work fine, but revert to 8-bit support with the non-`*-direct` `TERM` variables.

I'd expect Powerline10k to be like them, and not have all the 8-bit colors (outside of the 4-bit range) turn into shades of blue.

**Comment by romkatv** [comment]
> Is my understanding incorrect?

Not really. When you set `TERM=kitty-direct`, it does two things. First, you are now using Kitty in unsupported mode with a terminfo definition that is likely incorrect. The documentation for Kitty says that only `xterm-kitty` is valid value for `TERM`. Second, colors in zsh with codes above 8 look bad. You can see this in your screenshots.

The solution is to use `TERM=xterm-kitty`. It supports trucolor just fine. If some TUI cannot output 24-bit colors with this value of `TERM`, try `export COLORTERM=truecolor`. If this doesn't help, verify that your terminfo for `xterm-kitty` is correct. If this also doesn't help, report an issue against the TUI.

**Comment by tecosaur** [comment]
It surprises me to hear that `kitty-direct` is not recognised as a valid value for kitty. However, to in case, it was just one terminal emulator being funny, I used two in the screenshots. The left two are kitty, the right two are alacrity.
It does seem that `alacritty-direct` is distributed as part of the official project, see: https://github.com/alacritty/alacritty/blob/master/extra/alacritty.info

I'm guessing that the TUIs I have in mind don't check the `COLORTERM` variable, but rather `tput color`, which seems to be based on the terminfo. I get the sense that truecolor support in terminals may be a bit of a mess.

```
~$ tput colors
256
~$ TERM=alacritty-direct tput colors
16777216
```

I think I can see where the blue is coming from now at least, since it's just a number being provided as the color, `235` for example will become `0000EB`, etc.

It would be nice if Powerline10k could look the same regardless of whether the terminfo gives 8-bit or 24-bit colour. Might adding some sort of tput check + color code conversion be a possible solution?

**Comment by romkatv** [comment]
Powerlevel10k cannot make color 235 look any different. And it shouldn't even try because that would be confusing. If you tell powerlevel10k to display some prompt segment with color 235, it'll display it with color 235.

If you want, you can specify all colors in `#rrggbb` notation in your `~/.p10k.zsh`. I don't recommend doing it because you'll still be bumping into issues with `*-direct` terminfo. The real solution is to use a normal (not direct) terminfo. If there is an app that refuses to display 24 bit colors, file a bug against it. FWIW, I don't know any such apps.

**Comment by tecosaur** [comment]
For the sake of anyone else who has this annoyance, I'm using the following shell function
```sh
function truec ()
{
  if [ "$COLORTERM" = "truecolor" ]; then; echo "$2"; else; echo "$1"; fi
}
```
then replacing lines like this
```sh
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
```
with this
```sh
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$(truec 232 '#242730')
```

**Comment by romkatv** [comment]
Why not this?

```zsh
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#242730'
```

Or, better yet, why not set `TERM` to the normal value that everyone else uses? There are no advantages to `*-direct`.

**Comment by tecosaur** [comment]
What happens when `'#242730'` is used in 256-color terminals?

Re: Why use `*-direct`, because some programs seem to check the terminfo, not `COLORTERM`. For me, Emacs, also [looks like ncurses](https://github.com/weechat/weechat/issues/1364).

**Comment by romkatv** [comment]
> What happens when `'#242730'` is used in 256-color terminals?

Do you actually use a terminal that supports 256 colors but not truecolor? Which one is it?

If you really do use such a terminal, you can add this stanza to `~/.zshrc`:

```zsh
if using-a-terminal-with-256-colors-but-without-truecolor; then
    # approximate 24-bit colors with 8 bits
    zmodload zsh/nearcolor
fi
```

> Re: Why use `*-direct`, because some programs seem to check the terminfo, not `COLORTERM`. For me, Emacs, also [looks like ncurses](https://github.com/weechat/weechat/issues/1364).

Zsh uses ncurses and it can output 24-bit colors on all modern terminals with their default value of `TERM`.

I don't use emacs but perhaps it has a configuration option to tell it to use 24-bit colors?

If you are OK with a non-standard `TERM`, you could create a terminfo entry called something like `xterm-truecolor` that's based on `xterm-256color` (or `xterm-kitty` for Kitty) with extra `setb24` and `setf24`.

**Comment by tecosaur** [comment]
> Do you actually use a terminal that supports 256 colors but not truecolor? Which one is it?

I thought that `tty` might be, but it looks like that's actually 3-bit. It looks like 3-bit/24-bit is more realistic that 256-bit/24-bit.

> Zsh uses ncurses and it can output 24-bit colors on all modern terminals with their default value of TERM.

Ah, I didn't know - cool.

> I don't use emacs but perhaps it has a configuration option to tell it to use 24-bit colors?

It just seems to rely on the terminfo, but I can set an alias to `TERM=xyz emacs` and I think that should be fine.

Thanks for following up on this, you've been really helpful with something I know very little about!

**Comment by romkatv** [comment]
> It just seems to rely on the terminfo, but I can set an alias to `TERM=xyz emacs` and I think that should be fine.

This is a reasonable solution. There are likely not that many programs that can output 24-bit colors but don't do that with the default value of `TERM`. So an alias for each of them wouldn't be too many aliases.
