### ISSUE TITLE
Tmux doesn't auto-start due `open terminal failed: not a terminal`

### ISSUE THREAD

**Issue by StayPirate** [romkatv/powerlevel10k#1203]
I'm getting `open terminal failed: not a terminal` and tmux doesn't auto-start.

I have Powerlevel10k instant prompt enabled at the beginning of my `.zshrc`
```bash
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```
and I start tmux at the end of `.zshrc`
```bash
if [ -z "$TMUX" ]; then
  tmux new-session -A -s workspace
fi
```
If I either remove one of the two above snippets (instant prompt or tmux auto-start) I don't get any issue. In case both of them are present in the `.zshrc` I then get the following message:
```
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.config/zsh/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

open terminal failed: not a terminal
``` 

Can someone help me to understand why this is happening?

Even if I remove my custom `.tmux.conf` keeping only the default setting, it happens.

**Comment by romkatv** [comment]
Remove your current tmux stanza and add this at the very top of zshrc:

```zsh
if [ -z "$TMUX" ]; then
  exec tmux new-session -A -s workspace
fi
```

**Comment by StayPirate** [comment]
If I do this, when I open `gnome-terminal` it immediately close itself.

**Comment by romkatv** [comment]
Please confirm whether this worked for you.

**Comment by StayPirate** [comment]
**Moving this before the Powerlevel10k instant prompt activation works**. But I don't understand why should I move it before, as for my understanding (from the wiki) I should move at the top of `.zshrc` only programs which generate some output during startup, and tmux does not print out anything. Is that because some race-condition? Like Powerlevel10k  instant prompt delays terminal capabilities and tmux thinks to not be running within a interactive terminal?

Moreover, may I ask why did you suggest me to use `exec` to run tmux? Is this a better way to start it?

**Comment by romkatv** [comment]
> **Moving this before the Powerlevel10k instant prompt activation works**.

Thanks for the confirmation.

> I should move at the top of `.zshrc` only programs which generate some output during startup

Correct.

> and tmux does not print out anything

Everything you see in your terminal is printed by tmux.

> Moreover, may I ask why did you suggest me to use `exec` to run tmux? Is this a better way to start it?

So that you only have one shell when you open a terminal. Now, if you type `exit` or press <kbd>Ctrl+D</kbd>, you won't end up in another shell.

**Comment by StayPirate** [comment]
> > Moreover, may I ask why did you suggest me to use `exec` to run tmux? Is this a better way to start it?
> 
> So that you only have one shell when you open a terminal. Now, if you type `exit` or press Ctrl+D, you won't end up in another shell.

### Amazing 🤯! 

Thanks for your help, you are great!

**Comment by amigthea** [comment]
> Remove your current tmux stanza and add this at the very top of zshrc:
> 
> ```shell
> if [ -z "$TMUX" ]; then
>   exec tmux new-session -A -s workspace
> fi
> ```

I have a problem with a modified version of this:

```shell
if [ -z "$TMUX" ]; then
  while true; do
    read -k 1 "REPLY?Start tmux? [Yn]: "
    case $REPLY in
      "y"|"Y"|$'\n') exec tmux new-session -A -s && break ;;
      "n"|"N") echo "\ntmux not selected" && break;;
      *) clear && continue ;;
    esac
  done
fi
```

it works but it will not let omz updates itself, it will start the updates and show them only when I choose to not start tmux (n), what could be the culprit?

**Comment by romkatv** [comment]
I don't know.
