### ISSUE TITLE
Right side of prompt disappears on certain column lengths

### ISSUE THREAD

**Issue by peterroelants** [romkatv/powerlevel10k#1204]
I have a powerlevel10k prompt that looks like:

![col117_cropped](https://user-images.githubusercontent.com/951093/103741225-fc66a080-4ff8-11eb-920d-e6dab84bb44d.png)

However when I resize my terminal, the right part of the prompt (which contains the conda environment info, status, and time) dissapears depending on the terminal width.

In order of resizizing the terminal with I see the following pattern on this particular prompt:

- Width: 58 columns: No right prompt visible ![col58_cropped](https://user-images.githubusercontent.com/951093/103741479-6e3eea00-4ff9-11eb-8642-2008e9109fb9.png)
- Width: 59 - 78 columns: Right prompt visible
  - 59: ![col59_cropped](https://user-images.githubusercontent.com/951093/103741576-a2b2a600-4ff9-11eb-8f2e-a286f4e02444.png)
  - 78: ![col78_cropped](https://user-images.githubusercontent.com/951093/103741727-e1e0f700-4ff9-11eb-8592-2aac82034160.png)
- Width: 79 - 116: No right prompt visible
  - 79: ![col79_cropped](https://user-images.githubusercontent.com/951093/103741879-2a98b000-4ffa-11eb-8069-a8d16c1d9675.png)
  - 116: ![col116_cropped](https://user-images.githubusercontent.com/951093/103741940-48661500-4ffa-11eb-804e-e22ebf83a620.png)
- Width: 117 to max screen size: Right prompt visible: ![col117_cropped](https://user-images.githubusercontent.com/951093/103741225-fc66a080-4ff8-11eb-920d-e6dab84bb44d.png)

Could this be a powerlever10k issue? If not, what else could be the cause of this?

## System info

I'm using zsh with oh-my-zsh and powerlevel10k:
- [My .zshrc file](https://gist.github.com/peterroelants/35c78111d42fc1be0fc47a050ea6d239#file-zshrc)
- [My p10k.zsh file](https://gist.github.com/peterroelants/35c78111d42fc1be0fc47a050ea6d239#file-p10k-zsh)

Other system info:
- zsh version: zsh 5.8 (x86_64-ubuntu-linux-gnu)
- OS: Ubuntu 20.04.1 LTS
- Terminal: Standard Ubuntu Terminal app

## Copy of the full prompt:

(special characters don't work in GitHub)
```
 ~/w/n/sharepoint-microscopy-ingest  sharepoint_prefect_prototype +1 !4 ?1                                            ✔  prefect_sharepoint   08:20:18 
 ```

**Comment by romkatv** [comment]
That's how zsh works. It automatically hides right prompt if it doesn't fit.

With such long prompt I highly recommend running `p10k configure` and selecting the 2-line option. It's also a good idea to enable Transient Prompt (there is a separate screen for that in `p10k configure`).

**Comment by peterroelants** [comment]
Thanks for the context.

The 2-line options creates two lines, but still drops the right side of the prompt for certain terminal widths. I have `POWERLEVEL9K_TRANSIENT_PROMPT=always` for the transient prompt.

I had zsh with p10k splitting the line before with the right side of the prompt appearing on the next line, however I'm unable to replicate this.

**Comment by romkatv** [comment]
> The 2-line options creates two lines, but still drops the right side of the prompt for certain terminal widths.

It's still the same logic. If right prompt doesn't fit, it doesn't get displayed.

> I have `POWERLEVEL9K_TRANSIENT_PROMPT=always` for the transient prompt.

👍 

> I had zsh with p10k splitting the line before with the right side of the prompt appearing on the next line, however I'm unable to replicate this.

With a two-line prompt you have more space for typing commands and more space for prompt segments. If right prompt on the first line gets very crowded for you, you can move some of the segments to the second line. To do that, open `~/.p10k.zsh` and search for `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. You'll know what to do once you find it. There are plenty of comments explaining what's going on.

**Comment by peterroelants** [comment]
Thanks so much for the help :+1: 

By moving the segments after `newline` I have been able to display the information I need over two lines.

**Comment by romkatv** [comment]
Thanks for the confirmation.
