### ISSUE TITLE
"add-zle-hook-widget keymap-select $fn" + zdharma/fast-syntax-highlighting causes error in p10k

### ISSUE THREAD

**Issue by xPMo** [romkatv/powerlevel10k#1205]
I used to have my own `zle-keymap-select(){ }` function, but changed it to a custom name and added it to a hook:

```zsh
autoload -Uz add-zle-hook-widget
zle-cursor(){
 ...
}
add-zle-hook-widget keymap-select zle-cursor
```

Without zdharma/fast-syntax-highlighting, it works fine. With it, the prompt hangs for a bit before:
```
_p9k_deschedule_redraw:1: maximum nested function level reached; increase FUNCNEST?
```

Crossref: zdharma/fast-syntax-highlighting#214

**Comment by romkatv** [comment]
Thanks for filing the issue.

I'm short on time budget, so really could use your help tackling this. If you can figure out how to reproduce the problem without involving zdharma/fast-syntax-highlighting, I'll take over from there.

**Comment by xPMo** [comment]
Fixed in fsh.

**Comment by romkatv** [comment]
Wow, nice! Could you link to the fix?

**Comment by xPMo** [comment]
[PR](https://github.com/zdharma/fast-syntax-highlighting/pull/215) | 
[Commit](https://github.com/zdharma/fast-syntax-highlighting/pull/215/commits/6c1c00bba0f639c48848df7acd8ad15df484c7a6)

FSH wraps almost every widget. I removed zle-keymap-select from the list and it worked.

**Comment by romkatv** [comment]
Thanks for fixing this!

**Comment by romkatv** [comment]
I took a look at this issue and was able to reproduce it with this test case:

```zsh
autoload -Uz add-zsh-hook-widget add-zle-hook-widget

# Add `foo` hook to zle-line-finish.
function foo() {}
add-zle-hook-widget line-finish foo

# Invoke `bar` on zle-line-finish, which in turn invokes the original widget.
zle -A zle-line-finish orig-zle-line-finish
function bar() zle orig-zle-line-finish
zle -N zle-line-finish bar

# Add `baz` hook to zle-line-finish.
function baz() {}
add-zle-hook-widget line-finish baz
```

This produces `bar: job table full or recursion limit exceeded` on zle-line-finish.

Here's a similar example but with a different effect.

```zsh
autoload -Uz add-zsh-hook-widget add-zle-hook-widget

# Add `foo` hook to zle-line-finish.
function foo() print -rl '' foo
add-zle-hook-widget line-finish foo

# Invoke `bar` on zle-line-finish, which in turn invokes the original widget.
zle -A zle-line-finish orig-zle-line-finish
function bar() { zle orig-zle-line-finish; print bar; }
zle -N zle-line-finish bar

# Add `foo` hook to zle-line-finish for the second time.
add-zle-hook-widget line-finish foo
```

This results in `foo` being called on zle-line-finish but `bar` doesn't get called.

These look like bugs in add-zle-hook-widget to me. Both can be fixed. There is some choice w.r.t. the desired behavior of these test cases. I think it would be reasonable for the first to invoke `bar`, `foo`, `baz` (in this order) and for the second to invoke `bar`, `foo` (in this order). Here's one more test case to complete the picture:

```zsh
autoload -Uz add-zsh-hook-widget add-zle-hook-widget

# Add `foo` hook to zle-line-finish.
function foo() print -rl '' foo
add-zle-hook-widget line-finish foo

# Invoke `bar` on zle-line-finish, which does nothing.
function bar() {}
zle -N zle-line-finish bar

# Add `foo` hook to zle-line-finish for the second time.
add-zle-hook-widget line-finish foo
```

I think it reasonable to require that `bar` and `foo` get called here (in this order).

It's not too difficult to implement add-zle-hook-widget in a way that it conforms to these requirements and doesn't break the existing code that checks for `[[ $widgets[zle-line-finish] == user:azhw:zle-line-finish ]]`.

P.S.

I've also added a [workaround](https://github.com/romkatv/powerlevel10k/commit/b816abfed0e8785d8bc2e47987cc40f6bcd4bc29) to p10k that would've prevented the original issue. The workaround performs a check similar to the one above.
