### ISSUE TITLE
why is `≡` now in my prompt?

### ISSUE THREAD

**Issue by LucasLarson** [romkatv/powerlevel10k#1206]
I found `≡` in my prompt and am wondering how to find out which background job it’s referring to?

https://github.com/romkatv/powerlevel10k/blob/d524164020a91a04e8f1982ef5e57d434ef04dfb/internal/wizard.zsh#L1705

**Comment by romkatv** [comment]
Type `jobs` to see the list of background jobs.

**Comment by LucasLarson** [comment]
Thanks so much – and keep up the amazing work!

---
Sidebar that I was wondering about a specific Zsh syntax issue the other day and knew I should check out how you handled the problem first. Your work is kind of amazing!
