### ISSUE TITLE
When using the configuration wizard (macOS, iTerm2), I do not get an option to download fonts

### ISSUE THREAD

**Issue by mhulse** [romkatv/powerlevel10k#1207]
How do I trigger the automatic download?

Thanks!

**Comment by romkatv** [comment]
There is no way to manually trigger it. If the wizard doesn't offer it, it means it cannot do it. You'll have to install the font manually.

**Comment by mhulse** [comment]
> There is no way to manually trigger it. If the wizard doesn't offer it, it means it cannot do it. You'll have to install the font manually.

Ahhhh, thank you!

I was just confused by the [README](https://github.com/romkatv/powerlevel10k/blob/d524164020a91a04e8f1982ef5e57d434ef04dfb/README.md#automatic-font-installation):

> If you are using iTerm2 or Termux, p10k configure can install the recommended font for you. Simply answer Yes when asked whether to install Meslo Nerd Font.

I ended up doing the manual installation and it worked great.

Thank you! 👍
