### ISSUE TITLE
Agnoster theme in p10k

### ISSUE THREAD

**Issue by ericu65** [romkatv/powerlevel10k#1211]
[likely there's a better way to ask questions instead of raising issues but I couldn't find it]

Running p10k configure with rainbow base will create unexpected (to me) default colours, however the default color theme and profile is perfect (seems identical to Agnoster). I would like to create a profile based on the default (the default when not running configure) where I can add an additional prompt. Is there any way to create a ~/.p10k.zsh based on the current state, or which is the default profile (*.zsh) loaded when not running config?

**Comment by romkatv** [comment]
I’m not sure I understand the question. Does this do what you want?

```zsh
print 'POWERLEVEL9K_MODE=nerdfont-complete\nPOWERLEVEL9K_LEGACY_ICON_SPACING=true' >~/.p10k.zsh && exec zsh
```

**Comment by ericu65** [comment]
Yes. This, or an empty ```.p10k.zsh``` file, or no file and ```POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true``` set in .zshrc are the result I am looking for. But I'd still like the settings to be in my own .p10k.zsh so I can modify slightly.

**Comment by romkatv** [comment]
Are you asking for a config file with all options set to their default values? There is no file like that right now. If there were, it would be infinite in size.

**Comment by ericu65** [comment]
Right. Makes sense. In that case I'd like to create a similar base like ```p10k configure``` creates but for the default configuration. Does this make sense? If there's no quick way to dump it and modify I can of course just create the needed additions on an empty ```.p10k.zsh``` but I was unsure how much to keep from a generated file, i.e everything that's not typeset and could be support script needed to load these safely.

**Comment by romkatv** [comment]
> I'd like to create a similar base like `p10k configure` creates but for the default configuration.

Go ahead.

> I was unsure how much to keep from a generated file.

You can keep as much or as little as you want. The minimum viable config is empty. The maximum is infinite (there are literally infinite number of parameters that control powerlevel10k).

FWIW, I don't think what you are attempting to do is a good idea but it's definitely feasible. If I were in our shoes I'd instead keep the generated config and only modify a few colors. It's likely that modifying only the colors for `dir` will give you the result you are after. There is an FAQ entry for it: https://github.com/romkatv/powerlevel10k#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style

**Comment by ericu65** [comment]
Hi @Roman,

Thanks for the help. Indeed, your hunch was right.
Setting:
```
POWERLEVEL9K_DIR_FOREGROUND=0
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=0
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=0
POWERLEVEL9K_DIR_ANCHOR_BOLD=false
```
makes it very close to my agnoster.

My confusion came from the former way of working (in P9k) with themes and starting with modifying those to achieve a custom look. Thus I was looking to find the file which was the _default_ theme. Seems the default theme is not a profile/theme file but gathered from multiple scripts which the ```.p10k.zsh``` generated by configure overwrite.

Much appreciated!
(speed in P10k is incredible compared to P9k! Thank you!)

**Comment by romkatv** [comment]
> My confusion came from the former way of working (in P9k) with themes and starting with modifying those to achieve a custom look.

Powerlevel9k doesn't have themes. Powerlevel10k uses the same configuration parameters as Powerlevel9k (this is why they all start with `POWERLEVEL9K`) plus some extra. If you want, you can get any Powerlevel9k config (that is, any set of `POWERLEVEL9K` parameters that work with Powerlevel9k) and use them with Powerlevel10k. You'll get the same prompt. Not that I would recommend it.
