### ISSUE TITLE
Incompatibilities with `zsh-autocomplete` — potential bug in `_p9k_deschedule_redraw()`

### ISSUE THREAD

**Issue by tekhnee** [romkatv/powerlevel10k#1212]
As reported in [elsewhere](https://github.com/marlonrichert/zsh-autocomplete/issues/166#issue-783450289), powerlevel10k generates a `_p9k_deschedule_redraw` error when used alongside the `zsh-autocomplete` plugin.

Transient prompt also stops after the first iteration. I'm not able to assess whether the two issues are related.

**Comment by romkatv** [comment]
If you think this is a bug in p10k, please send a PR with a fix.

**Comment by romkatv** [comment]
This looks like a bug in zsh-autocomplete. See https://github.com/marlonrichert/zsh-autocomplete/issues/166#issuecomment-758437197.
