### ISSUE TITLE
iTerm2 mark misplaced in multiline prompt

### ISSUE THREAD

**Issue by rejsmont** [romkatv/powerlevel10k#1213]
Hi,

I am using p10k v1.14.5 in iTerm2, with shell integrations installed. I noticed that the position of the iTerm2 mark is hardcoded in [p10k source](https://github.com/romkatv/powerlevel10k/blob/9c3ecab81e7a8080d4f11b966d705d51f29198b0/internal/p10k.zsh#L7859). Unfortunately, with a multiline prompt preceded by a newline, the iTerm2 mark renders above the prompt.

![screenshot](https://i.imgur.com/lk1iVpn.png)

I believe that:
- the mark should be placed after pre-prompt newlines
- ideally, there should be an option to place the mark on any prompt line

What do you think? I could not find an easy fix beside modifying `_p9k_init_prompt()` and `_p9k_init_cacheable()`.

Thanks for your help!

Best,
/Radek/

**Comment by romkatv** [comment]
Once a mark is set, it cannot be moved. Look at the prompt lines on your screenshot that corresponds to the commands `cd Public` and `ls`. Is the mark in the right place? If you think it is, then it's also in the right place on the prompt at the bottom. If the mark on the last prompt was placed anywhere else, it would be misplaced once you press <kbd>Enter</kbd>.

**Comment by romkatv** [comment]
By the way, most users prefer to disable the display of those marks. They add little information and they are noisy. There is a setting in iTerm2 preferences to hide the marks. All iTerm2 features that require shell integration will still work as before.

**Comment by rejsmont** [comment]
> Once a mark is set, it cannot be moved. Look at the prompt lines on your screenshot that corresponds to the commands `cd Public` and `ls`. Is the mark in the right place? If you think it is, then it's also in the right place on the prompt at the bottom. If the mark on the last prompt was placed anywhere else, it would be misplaced once you press Enter.

I see. OK - fair enough - and acceptable compromise ;)

**Comment by romkatv** [comment]
It's not a compromise. There is really no choice given that marks in iTerm2 cannot be moved.
