### ISSUE TITLE
Cannot install with zplug on remote server

### ISSUE THREAD

**Issue by gipert** [romkatv/powerlevel10k#1219]
I've got some troubles making powerlevel10k work with zplug on one of my remote (SSH) servers. The issue is that, right after installing the plugin and in any other new shell, the `p10k` command is not found. The configuration wizard does not start and the theme is not loaded. Needless to say, I could not find anything suspicious in the zplug installation itself and in `~/.zplug/repos/romkatv/powerlevel10k`.  I'm not even sure this is a p10k issue. I'll try to document the relevant dotfiles in the following, so you can maybe help me figure out what's causing all this.

[Here are all my dotfiles](https://github.com/gipert/.dotfiles), I sync them over multiple machines and I'm having this issue only on this specific remote server.

1. Since I cannot change my default (bash) shell on this machine, [this is what I do](https://github.com/gipert/.dotfiles/blob/master/.bash_profile#L9) (zsh version is `zsh 5.0.2 (x86_64-redhat-linux-gnu)`). This could be related to the issue, I'm not sure.
2. [This is my `.zshrc`](). As you can see I install zplug, then load powerlevel10k as per instructions.

Do you see anything wrong here? How can I further debug this?

Thanks so much in advance for helping me with this.

**Comment by romkatv** [comment]
Powerlevel10k requires zsh >= 5.1. See https://github.com/romkatv/powerlevel10k#what-is-the-minimum-supported-zsh-version

**Comment by gipert** [comment]
Damn! I should have thought about that, sorry for spamming. Thank you for the fast reply. Would it make sense to implement an error message?

**Comment by romkatv** [comment]
There is an error message. Try running `zsh -f` and sourcing powerlevel10k manually. If you don’t see it when using zplug, it’s probably suppressed by zplug. I don’t use zplug myself, so it’s just a speculation.
