### ISSUE TITLE
VCS segment at root of version controlled dir (subdirectories after vcs_segment)

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#122]
Copied over from https://github.com/Powerlevel9k/powerlevel9k/issues/790 by @sbibauw. It's a cool feature and I'd like to implement it in Powerlevel10k. The original issue description follows.

---

I do not see the possibility to do this in powerlevel9k, so this is more a suggestion: make it possible to show the VCS segment in-between the path to the version controlled dir and its subdirectories. I find this presentation to be helping a lot to perceive where I am in a project, especially if there are submodules.

The prompt would look like this:

> ~/dev/project > **[master +...ꜛ1]** > src/module >

rather than current:

> ~/dev/project/src/module > **[master +...ꜛ1]** >

This would allow to distinguish immediately in which version controlled repository one is, avoiding any confusion for submodules:

> ~/dev/project/vendor/cloned_repo > **[master ✓]** >

In terms of **segments**, I would see it as:

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs subdir)
```

**Comment by Syphdias** [comment]
I wonder if this would be to confusing:
```
~/dev/project > [master +...ꜛ1] > vendor/cloned_repo > [master ✓] >
```
Just a thought, not saying I want this 😉

**Comment by romkatv** [comment]
@Syphdias I like it. I'd have to try it for a few days before I can decide if I'd stick with it but it certainly has appeal.

By the way, I've picked this feature primarily because it's technically difficult to implement. It's not as crazy difficult as multi-line right prompt or auto-shrinking dir but it's still pretty tough due to its breaking the existing model in which prompts don't intermix.

**Comment by Syphdias** [comment]
```zsh
repeat 100 { mkdir -p chromium; cd $_; git submodule add $chromium_repo chromium}
```
:see_no_evil:

**Comment by romkatv** [comment]
Ha-ha :-) Can add `POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true` to make it `O(N^2)`.

**Comment by romkatv** [comment]
Closing as I'm unlikely to ever implement this. No one else has requested this and it I also realized it's not generally possible. Basically, the current directory isn't always a subdirectory of the Git worktree. In my current workflow this happens often.

**Comment by MaienM** [comment]
I didn't respond to this because I didn't have anything to add, and didn't click the thumbs up because I forgot, but I was subscribed to this because I was interested in it. Could have made that more obvious in hindsight, whoops.

I'm curious what cases this wouldn't work in though, because I can't come up with any.

**Comment by romkatv** [comment]
> I didn't respond to this because I didn't have anything to add, and didn't click the thumbs up because I forgot, but I was subscribed to this because I was interested in it. Could have made that more obvious in hindsight, whoops.

Sorry about that. I opened the issue originally because I was short on difficult feature requests. I no longer am. If I keep this issue open, I still won't get around to implementing it given my current workload and influx of feature requests and bug reports.

If you can implement this, I'll be happy to receive a PR. Note that it's a very difficult feature to implement because `dir` and `vcs` segments are both custom, meaning that they cannot be implemented on top of the public `p10k segment` API. `dir` is tricky due to [responsive truncation](https://asciinema.org/a/258376) and `vcs` is tricky because it's multi-step sync/async hybrid.

> I'm curious what cases this wouldn't work in though, because I can't come up with any.

This :point_down: 

> Basically, the current directory isn't always a subdirectory of the Git worktree. In my current workflow this happens often.

You can specify the location of `.git` directory with `GIT_DIR` and worktree with `GIT_WORK_TREE`. Powerlevel10k respects these parameters. If `GIT_WORK_TREE` is not a parent of the current directory, how would Git status be displayed in "split" mode?

**Comment by MaienM** [comment]
Ah, I wasn't aware of `GIT_DIR` and `GIT_WORK_TREE`. That certainly complicates things. You could always fallback to the non-split behavior, I suppose, but at that point it might appear the current directory is the root.

I _might_ take a stab at this eventually, but don't hold your breath, it's not high up on my list. If anyone else feels like trying their hand at this, by all means. If not, I suppose I'll survive without this functionality.
