### ISSUE TITLE
PWD bug in truncation when directory has a space

### ISSUE THREAD

**Issue by IlanCosman** [romkatv/powerlevel10k#1220]
I discovered this while working on an issue with spaces for [Tide](https://github.com/IlanCosman/tide) 😂

pwd = `~/Documents/has space/foo/bar/baz/qux/quz/one/two/three/four/five/six/seven/`
pwd gets truncated to `~/Doc/h/foo/bar/baz/qux/quz/one/two/three/four/five/six/seven`

However, there is a `~/Documents/hat` directory as well, so `has space` should be truncated to `has` instead of `h`.

**Comment by romkatv** [comment]
Cannot reproduce.

```zsh
mkdir -p ~/Documents/has\ space/foo/bar/baz/qux/quz/one/two/three/four/five/six/seven ~/Documents/hat ~/Downloads
cd ~/Documents/has\ space/foo/bar/baz/qux/quz/one/two/three/four/five/six/seven
```

![image](https://user-images.githubusercontent.com/1282067/104552680-86d28400-5639-11eb-8c91-d6b41f08f5df.png)

Please post exact instructions how to reproduce.

**Comment by IlanCosman** [comment]
Well that's really strange, I can't seem to reproduce today. 😅Perhaps I was hallucinating it. Thanks for taking a look.
