### ISSUE TITLE
[question] show first line only when there is some content?

### ISSUE THREAD

**Issue by ftpd** [romkatv/powerlevel10k#1221]
Hi. I'm using a multiline prompt - first line shows things like git, kubernetes, aws, python venv and so on; the second one contains my working dir, username and 'prompt char'.  
Everything works, but I'm wondering: is there any way to only show this first line when there is something to show? I mean, if I'm not in a git repo, k8s not configured, aws profile not set and venv not activated, it's just an empty line, so I would like to get rid of it in this case.

**Comment by romkatv** [comment]
No, Powerlevel10k doesn’t support this.

**Comment by ftpd** [comment]
Ok, thanks for quick reply.
