### ISSUE TITLE
ZLE_RPROMP_INDENT and SHOW_ON_COMMAND has weird behavior

### ISSUE THREAD

**Issue by jansssson** [romkatv/powerlevel10k#1223]
I want to use ZLE_RPROMPT_INDENT=0, but with show-on-command I get some weird behavior.
Not sure if it's only kubernetes, which I've tried, or all contextual commands, or perhaps something with my config.

As soon as I type a command that triggers a segment to show (e.g. helm or kubectl), an extra space is added to the left prompt, moving what's already typed, without moving the cursor. If I remove the command (or just a char), hiding the segment again, the prompt is still wrong. Interesting though, it seems to be ZLE_RPROMPT_INDENT (which should control the right side), that adds the extra space on my left side. Not sure if it's my config, I'm new to both zsh and p10k.

Before I type the full command, with ZLE_RPROMPT=0
![image](https://user-images.githubusercontent.com/56471607/104707901-53692580-571d-11eb-8459-46c62d27f3ab.png)
Once I type the last char, the entire word is indented with one space, but the cursor remain. It seems to be only a display issue though, typing the full command and pressing enter works, if I don't pay attention to how it looks...
![image](https://user-images.githubusercontent.com/56471607/104708207-af33ae80-571d-11eb-9c1d-9018fa4bd05a.png)
If I remove the last char again, the segment disappears, but the text is still indented, and the cursor position doesn't reflect what is actually edited
![image](https://user-images.githubusercontent.com/56471607/104708323-d9856c00-571d-11eb-917b-c0c7d4631f1c.png)

The workaround I've determined works right now, is using ZLE_RPROMPT_INDENT=1, which give me a permanent extra space in the left prompt:
![image](https://user-images.githubusercontent.com/56471607/104708474-0fc2eb80-571e-11eb-9d60-28d0567eeff2.png)
![image](https://user-images.githubusercontent.com/56471607/104708571-2d905080-571e-11eb-9d9a-af06d57bacfe.png)

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
typeset -p ZSH_VERSION
```

**Comment by jansssson** [comment]
5.4.2, oh, might be a to old zsh??...

**Comment by romkatv** [comment]
`ZLE_RPROMPT_INDENT` has several bugs in all version of zsh prior to 5.8. If you are using zsh older than 5.8, you may or may not be hit by these bugs. Apparently, in your use case you do get hit by them. You need to either upgrade to zsh 5.8 or unset `ZLE_RPROMPT_INDENT`.

**Comment by jansssson** [comment]
Ah, I see. Unsetting it seems to give the extra permanent space, and everything seems to work, guess it's ok for now.
It's an Ubunut 18.04.5 with apt-based zsh, can't upgrade it right now.
Thanks for the help, closing.

**Comment by romkatv** [comment]
There is https://github.com/romkatv/zsh-bin if you really want to upgrade.

**Comment by jansssson** [comment]
Thanks for the tip! I'll look into it.
