### ISSUE TITLE
git status color rendering

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#1225]
The color does not work, not even git status (vcs)
What is the problem?  help
![Screenshot_20210116_124639](https://user-images.githubusercontent.com/61009000/104797441-02c6fa80-57f9-11eb-9a1b-adcf9bd6552b.jpg)
![Screenshot_20210116_124658](https://user-images.githubusercontent.com/61009000/104797443-065a8180-57f9-11eb-8ed3-5b15759a913f.jpg)
![Screenshot_20210116_124721](https://user-images.githubusercontent.com/61009000/104797445-08bcdb80-57f9-11eb-8ff4-daa34277dd8e.jpg)

**Comment by romkatv** [comment]
Do you believe there is something wrong with the color of git status on the screenshots? What is it?
