### ISSUE TITLE
Why when i type "sudo su" i see ( i use zsh with this theme and oh my zsh )

### ISSUE THREAD

**Issue by yoge67855** [romkatv/powerlevel10k#1226]
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x 1 xyz xyz  344 Jan  4 17:18 /home/xyz/.oh-my-zsh
drwxr-xr-x 1 xyz xyz 4012 Jan 16 22:28 /home/xyz/.oh-my-zsh/plugins
drwxr-xr-x 1 xyz xyz   46 Jan  4 17:18 /home/xyz/.oh-my-zsh/plugins/git

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.

how could i fix it?

**Comment by romkatv** [comment]
Have you tried doing what the warning says?

**Comment by yoge67855** [comment]
yes and nothing happened

**Comment by romkatv** [comment]
Please describe what you’ve tried doing.

**Comment by yoge67855** [comment]
i tried everything but not first option because i dont know how to do it

**Comment by romkatv** [comment]
Please describe what you've tried in detail. List the actions you've taken and the results you've observed.

**Comment by yoge67855** [comment]
first i typed sudo vim ~/.p10.zsh and added following lines:
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
Nothing happened same issue
then changed ZSH_DISABLE_COMPFIX in ~/.zshrc to:
 ZSH_DISABLE_COMPFIX true
Still same issue

**Comment by romkatv** [comment]
> first i typed sudo vim ~/.p10.zsh and added following lines:
> typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
> typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

Where in `~/.p10.zsh` have you added these lines?

**Comment by yoge67855** [comment]
does that matter?

**Comment by romkatv** [comment]
yes

**Comment by yoge67855** [comment]
below this:
# The list of segments shown on the left. Fill it with the most important segments.

**Comment by romkatv** [comment]
This won't do anything because is overridden below. Search for `POWERLEVEL9K_INSTANT_PROMPT` and change the value from `verbose` to `quiet`. Save the file and run `sudo su` **twice**.

**Comment by yoge67855** [comment]
now i see: 
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xr-x 1 xyz xyz  344 Jan  4 17:18 /home/xyz/.oh-my-zsh
drwxr-xr-x 1 xyz xyz 4012 Jan 16 22:28 /home/xyz/.oh-my-zsh/plugins
drwxr-xr-x 1 xyz xyz   46 Jan  4 17:18 /home/xyz/.oh-my-zsh/plugins/git

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.

**Comment by romkatv** [comment]
This error is not coming from powerlevel10k. If you replace powerlevel10k with another theme (e.g., the default robbyrussell), you'll see the same error.

Closing.
