### ISSUE TITLE
incorrect status of git

### ISSUE THREAD

**Issue by wang1zhen** [romkatv/powerlevel10k#1227]
![Screenshot_20210118_012526](https://user-images.githubusercontent.com/31798841/104836510-557fdf80-58e9-11eb-9881-a82682296a17.png)

Here is my screenshot, where you can see that the `master` is not displayed correctly.

I'm on Manjaro KDE, with `Cascadia Code PL`, and this could be reproduced both in yakuake and konsole.

**Comment by romkatv** [comment]
What should I do to reproduce this issue on my machine?

**Comment by wang1zhen** [comment]
Maybe would you please try my p10k config file with `Cascadia Code PL` as the terminal font?

[p10k.zip](https://github.com/romkatv/powerlevel10k/files/5825827/p10k.zip)

**Comment by romkatv** [comment]
Have you foundation solution to this problem? I’m sorry that I haven’t tried reproducing it.

**Comment by wang1zhen** [comment]
It seems to be a result of font fallback, the original font Cascadia Code has no glyphs so that it fallback to another font which might not be monospace, which causes the width of the characters becomes weird. After switching to a nerd font (CaskaydiaCove Nerd Font), the problem no longer exists.

**Comment by romkatv** [comment]
Thanks for the update! Hopefully it’ll help others facing the same problem.
