### ISSUE TITLE
Question: bring process back to foreground

### ISSUE THREAD

**Issue by marciliocn** [romkatv/powerlevel10k#1228]
Is there a way to bring back a process to foreground with a shortcut?

I try `Ctrl + z` like to send process, but nothing.....with `fg` work fine.

In [grml-zsh-confg](https://grml.org/zsh/) the shortcut is `Ctrl + z`, like toggle...(sending & bring back)

I found this project with a example for function: https://github.com/mdumitru/fancy-ctrl-z

Tks

**Comment by romkatv** [comment]
Powerlevel10k only provides prompt. It doesn’t and will not define bindings.
