### ISSUE TITLE
Transient prompt breaks if used alongside zsh-autcomplete

### ISSUE THREAD

**Issue by yrammos** [romkatv/powerlevel10k#1229]
The "transient prompt" feature of Powerlevel10k works only for the first command, and then stops, if [marlonrichert/zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete) is included in the shell configuration.

Reproduction:

```
> cd "$(mktemp -d)"
> ZDOTDIR=$PWD HOME=$PWD zsh -f 
> source absolute/path/to/zsh-autocomplete.plugin.zsh; source absolute/path/to/powerlevel10k.zsh-theme; source path/to/.p10k.zsh
```

Am not implying this is a bug on either side. Widget handling (zle) by the two plugins may be fundamentally incompatible, for instance. (This is clearly a low-level issue and diagnosis requires familiarity with both code bases.) Anyhow a warning in the p10k config script might be useful in case of incompatibility. 

Thank @romkatv you for this extraordinary piece of work.

**Comment by romkatv** [comment]
This is a bug in zsh-autocomplete. See https://github.com/marlonrichert/zsh-autocomplete/issues/173#issuecomment-762182789.

**Comment by yrammos** [comment]
Thank you, @romkatv!

**Comment by yrammos** [comment]
@romkatv just a heads up that the latest zsh-autocomplete revision, while promising, did not resolve the issue, neither does a solution seem imminent. To prevent confusion, you may want to add an incompatibility warning in your config script.

**Comment by jeyjai** [comment]
This is still a problem btw
