### ISSUE TITLE
Help in changing prompt_char color and symbol

### ISSUE THREAD

**Issue by hdaasari** [romkatv/powerlevel10k#1230]
I want to change the prompt_char to the one in this image

<img width="502" alt="Screen Shot 2021-01-18 at 6 53 10 PM" src="https://user-images.githubusercontent.com/3305401/104921603-90ecdd80-59bf-11eb-99c8-85186404743a.png">

Tried my best and got until here but unable to get the same as the top image
<img width="357" alt="Screen Shot 2021-01-18 at 6 58 54 PM" src="https://user-images.githubusercontent.com/3305401/104921614-95b19180-59bf-11eb-83c9-01fffd6a9070.png">

Could you please help me out in configuring this. 

Thanks in advance.

**Comment by romkatv** [comment]
There is no `prompt_char` segment on the first screenshot. The thing in the left bottom corner is `status`. Try the following:

1. Run `p10k configure` and select ranbow style with a single line.
2. Open `~/.p10k.zsh` and remove `status` from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. In addition, add `newline` and `status` to the end of `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.

**Comment by hdaasari** [comment]
Thanks for the reply @romkatv 

I was able to get here with the steps 

<img width="526" alt="Screen Shot 2021-01-18 at 8 04 12 PM" src="https://user-images.githubusercontent.com/3305401/104928277-7408d800-59c8-11eb-9c55-f156c6519d76.png">

Attaching the status part in ~/.p10k.zsh but unable to change the check mark to green color 

<img width="738" alt="Screen Shot 2021-01-18 at 8 03 50 PM" src="https://user-images.githubusercontent.com/3305401/104928284-7703c880-59c8-11eb-9a68-901d3cd3a116.png">

**Comment by romkatv** [comment]
See those `BACKGROUND` and `FOREGROUND` parameters in your screenshot? You can incident them and change their values. See the top of the file for a tip how to choose color codes.

**Comment by hdaasari** [comment]
The `BACKGROUND` works as expected but when I set `FOREGROUND` checkmarks turns white for any color I set

**Comment by hdaasari** [comment]
Got it fixed @romkatv. I was messing with colors in iterm2 I rest them and the `FOREGROUND` is working as expected
