### ISSUE TITLE
How can I keep rainbow theme when connecting to ssh host using anaconda?

### ISSUE THREAD

**Issue by Rubertos** [romkatv/powerlevel10k#1231]
As you can see, on my mac, my theme is rainbow.

![image](https://user-images.githubusercontent.com/46097562/105174010-3b523580-5b65-11eb-99e6-a25983c1a0c0.png)

However, when I connect to ssh server using anaconda, rainbow theme is not applied there like below picture.. How do I fix this?

![image](https://user-images.githubusercontent.com/46097562/105174112-6a68a700-5b65-11eb-8e04-f95beea3fa65.png)

I'm using Mac to connect ssh servers and I spend most of my time working on ssh servers (all servers are using anaconda). Hence, if theme is not applied when I connect to ssh servers using conda, it is useless to me.. Is there any way to fix this?

**Comment by romkatv** [comment]
Different computers can have different operating systems, different programs and different configs. Apparently, your local machine is a mac with zsh for shell, and your remote machine is a PC running Linux with bash for shell. If you want to use zsh as your shell on that server, install zsh on it. Likewise for powerlevel10k -- you need to install it where you want to use it.

**Comment by Rubertos** [comment]
@romkatv Thank you!
