### ISSUE TITLE
feature request: configure with parameters (automated installation without interactive wizard)

### ISSUE THREAD

**Issue by ww7** [romkatv/powerlevel10k#1234]
For quick setup and stay updated with latest p10k would be nice to have way to quick silent install where all answers passed as command line arguments.

**Comment by romkatv** [comment]
The only thing the wizard does is creating `~/.p10k.zsh`. Simply save this file and you won't need to run the wizard.

**Comment by romkatv** [comment]
Also just in case it's not clear: you don't need to run `p10k configure` when you upgrade Powerlevel10k.
