### ISSUE TITLE
Where can I change the transient prompt chevron ❯

### ISSUE THREAD

**Issue by Luxcium** [romkatv/powerlevel10k#1236]
![Screenshot_20210123_092201](https://user-images.githubusercontent.com/42672814/105580786-766a8980-5d5c-11eb-86a5-1070a3c27b3d.png)

I would like to change the chevron ❯ here in green or red I would like to change it in my fork but I can't find where... I did a <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>F</kbd> and was able to change the « ⑆ ». I sent a private message using Twitter saying «I don't feel like opening a ticket (issue) for a private request »

**Comment by Luxcium** [comment]
I probably have an [OCD](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder)  but to me, it feels so wrong that it is red and points to something that was working or green and pointing to something that failed I do understand that it won't be fixed but I want at least to be able to change it in my version to ⮝ something pointing to the previous code but I am unable to find where to change it

**Comment by romkatv** [comment]
Do you have `~/.p10k.Zsh`? You can find the symbol there.

**Comment by Luxcium** [comment]
I think I have it there:
![Screenshot_20210123_094342](https://user-images.githubusercontent.com/42672814/105588500-8899f700-5d5f-11eb-813a-ca8f7eab02c0.png)

**Comment by Luxcium** [comment]
![Screenshot_20210123_094549](https://user-images.githubusercontent.com/42672814/105589459-cac33880-5d5f-11eb-8866-bfa610392145.png)

I don't know if I can ask another question in the same issue... I would like to know if you think I should be able to fix the lines that are messy ???

**Comment by romkatv** [comment]
> I think I have it there:
> 
> ![Screenshot_20210123_094443](https://user-images.githubusercontent.com/42672814/105588911-a49d9880-5d5f-11eb-9b40-9f58c4972dde.png)

Change it there.

**Comment by romkatv** [comment]
> ![Screenshot_20210123_094549](https://user-images.githubusercontent.com/42672814/105589459-cac33880-5d5f-11eb-8866-bfa610392145.png)
> 
> I don't know if I can ask another question in the same issue... I would like to know if you think I should be able to fix the lines that are messy ??? it is probably my right prompt icon I guess ...
> 
> ```js
> {
> /* [VSCode settings.json] */
>   "terminal.integrated.lineHeight": 1,
>   "terminal.integrated.letterSpacing": 1,
>   "terminal.integrated.rendererType": "canvas",
>   "terminal.integrated.fontFamily": "'FuraCode Nerd Font mono','TerminessTTF Nerd Font Mono'",
> /* [...] */
> }
> ```
> 
> ```
> ❯ echo $POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR
> 
> ❯ echo $POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR
> 
> ```
> 
> ![Screenshot_20210123_095316](https://user-images.githubusercontent.com/42672814/105593263-d82cf280-5d60-11eb-88de-1f5400a60bec.png)

See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by Luxcium** [comment]
I get different results with different fonts ... Therefor for a specific font I am not sure I will be able to get better results and I think it is strange since I didn't have the same problem (I think) on my mac book (I am not 100% sure in fact) I am now on Fedora PlasmaShell

**Comment by romkatv** [comment]
Has your issue been resolved? If not, please describe what you do, what you observe and what you expect.

**Comment by jdmallen** [comment]
> I probably have an [OCD](https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder) but to me, it feels so wrong that it is red and points to something that was working or green and pointing to something that failed I do understand that it won't be fixed but I want at least to be able to change it in my version to ⮝ something pointing to the previous code but I am unable to find where to change it

@romkatv First, great work on this theme, it looks terrific and I love the features. What OP mentioned here is also my one nit, but he mentioned that it won't be fixed. I just want to understand that a bit better as I can't find it mentioned in the documentation anywhere. Is it just impossible for zsh to modify a previous line (i.e. change green to red of prompt that failed) because that would involve editing history? Doesn't the shell learn the edit code of a process before it moves that line to history and creates a new prompt? I'd love to learn more about this so maybe I can help fix it, if it's something that can be fixed, or confirm that it's impossible. Thanks!

**Comment by romkatv** [comment]
@jdmallen See https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them

**Comment by jdmallen** [comment]
> @jdmallen See https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them

Sorry I missed that. Thanks for the great explanation.

**Comment by romkatv** [comment]
> Has your issue been resolved? If not, please describe what you do, what you observe and what you expect.

Closing then.

**Comment by habahabahaba** [comment]
Firstly, big thank you, **romkatv**, for the awesome work you've done!

I would like to suggest, maybe adding another step to the config wizard, that lets you set theme-designated colors for the fluent chevrons: 001 for an error and 002 for a success (those are usually red and green in most iTerm2 themes).
