### ISSUE TITLE
Combine current directory truncate_to_unique with SHORTEN_DIR_LENGTH

### ISSUE THREAD

**Issue by protist** [romkatv/powerlevel10k#1243]
Is it possible to combine `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique` with `POWERLEVEL9K_SHORTEN_DIR_LENGTH=2`? I like `truncate_to_unique` in theory, but I'd prefer slightly more context if possible. For example, instead of truncating `gitstatus` to `g` on my system:
```
~ > cd /usr/share/zsh-theme-powerlevel10k/gitstatus/docs
/usr/sh/zsh-/gitstatus/docs >
```

Also, is there somewhere I can find documentation of the various configuration options? I migrated from powerlevel9k, so I guess I'm missing the automatically generated config. However, even [searching this repo](https://github.com/romkatv/powerlevel10k/search?q=POWERLEVEL9K_SHORTEN_STRATEGY) didn't find an exhaustive list. Thanks in advance!

**Comment by romkatv** [comment]
> Is it possible to combine `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique` with `POWERLEVEL9K_SHORTEN_DIR_LENGTH=2`?

When you set `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique`, `POWERLEVEL9K_SHORTEN_DIR_LENGTH` defines the number of trailing directory components that don't get truncated.

> Also, is there somewhere I can find documentation of the various configuration options?

No.

> I migrated from powerlevel9k, so I guess I'm missing the automatically generated config.

I highly recommend running `p10k configure` to generate a config. You can easily go back to your original config by removing the two lines from the bottom of `.zshrc` that `p10k configure` appends.

**Comment by protist** [comment]
> When you set `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique`, `POWERLEVEL9K_SHORTEN_DIR_LENGTH` defines the number of trailing directory components that don't get truncated.

Oh yes, that works very well. Sorry, that seems like an obvious thing to try in retrospect.

> I highly recommend running p10k configure to generate a config.

Done! It took me about an hour to transfer all my settings across, but it seems worth it to discover the new options!

I can see in the newly-generated config file that the first segment is always an anchor. Is it possible to disable that?

**Comment by romkatv** [comment]
> I can see in the newly-generated config file that the first segment is always an anchor. Is it possible to disable that?

No.

**Comment by protist** [comment]
Okay. Thanks for the help again. FWIW almost every directory path I use starts with `/HDD/`, so it's a bit superfluous in my case.

**Comment by romkatv** [comment]
You can do this:

```zsh
hash -d H=/HDD
```

Then you'll get `~H/blah/blah`. This is as short as `/H/blah/blah` that you would get if the first segment was shortened. The advantage is that `~H` is a real path that you can pass as an argument to commands, trigger completions on, etc.

**Comment by protist** [comment]
Good idea! Thanks again.
