### ISSUE TITLE
virtualenv can't show right virtualenv dir name

### ISSUE THREAD

**Issue by GalphaXie** [romkatv/powerlevel10k#1244]
expect the virtualenv dir name is `venv` , but got `demo`

![image](https://user-images.githubusercontent.com/39283832/106833437-7a889680-66ce-11eb-9d20-15ba0014fd2c.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/532#issuecomment-612604406.
