### ISSUE TITLE
Looking for a DIR_CLASSES pattern outside of ~

### ISSUE THREAD

**Issue by wAuner** [romkatv/powerlevel10k#1245]
I'd like to have a custom class for directories other than `~/**` but so far I couldn't come up with one. For example everything outside or above `~` should have a different coloring. Can anyone help?

**Comment by romkatv** [comment]
You are trying to apply different styling to directories under your home directory and everything that's not under your home directory? If so, open `~/.p10k.zsh`, search for `POWERLEVEL9K_DIR_CLASSES` and see the example. It does just that.

**Comment by wAuner** [comment]
thanks,  I was thinking the other way around.
But there is something I don't quite understand or maybe have messed up in my config:

![image](https://user-images.githubusercontent.com/18383180/107080280-57a2d300-67f1-11eb-91e7-82854951be6e.png)

I want to change the color such that the anchor is more intense than the preceding dir. Just like this:
![image](https://user-images.githubusercontent.com/18383180/107080419-8ae56200-67f1-11eb-8c17-ab089df63cdd.png)
 
In both cases I've set `DIR_FOREGROUND` and `DIR_ANCHOR_FOREGROUND`, but in the first case it changes the `/` instead of the preceding dir. Did I mess up?

**Comment by romkatv** [comment]
When the current directory is `/foo/bar` both `foo` and `bar` are anchors. `foo` because it's the first, `bar` because it's the last. It's the same as `~/foo` where both `~` and `foo` are anchors.

**Comment by romkatv** [comment]
> I was thinking the other way around.

I didn't understand this comment. If it's relevant. please rephrase.

**Comment by wAuner** [comment]
> When the current directory is `/foo/bar` both `foo` and `bar` are anchors. `foo` because it's the first, `bar` because it's the last. It's the same as `~/foo` where both `~` and `foo` are anchors.

ah I see. But wouldn`t `/` be the first directory and therefore the anchor? Why is foo considered an anchor when it's just a `middle dir`?



> > I was thinking the other way around.
> 
> I didn't understand this comment. If it's relevant. please rephrase.

I was approaching the problem by defining something that tried to exclude the pattern instead of defining the pattern. My approach was too complicated is what I wanted to say.

**Comment by romkatv** [comment]
> > When the current directory is `/foo/bar` both `foo` and `bar` are anchors. `foo` because it's the first, `bar` because it's the last. It's the same as `~/foo` where both `~` and `foo` are anchors.
> 
> ah I see. But wouldn't `/` be the first directory and therefore the anchor?

In powerlevel10k all slashes are styled as separators.

> Why is foo considered an anchor when it's just a "middle dir"?

Because it's more useful to myself and (I believe) to virtually all users.

> I was approaching the problem by defining something that tried to exclude the pattern instead of defining the pattern. My approach was too complicated is what I wanted to say.

Thanks for the clarification.

**Comment by wAuner** [comment]
I see, thanks! great work with the theme, thank you. I've already spent way too much integrating unicorns in my terminal ;)
