### ISSUE TITLE
Help Wanted in terminal output

### ISSUE THREAD

**Issue by cyberwr3nch** [romkatv/powerlevel10k#1247]
Hi can you help me with an issue that i have been facing
[Here](https://github.com/romkatv/powerlevel10k/blob/master/README.md#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect) This is mentioned as the color prompts of `ls` is not affected but I am facing a problem, when I type `ls` i cant find it in colors and when in auto completion i am seeing the colors can anyone help me with this ?
I also used the export command from [here](https://github.com/romkatv/powerlevel10k/issues/805#issuecomment-640159400)
![image](https://user-images.githubusercontent.com/55705969/107139614-8ed4c980-6942-11eb-9277-b8178205829e.png)

**Comment by romkatv** [comment]
Please ask elsewhere. Powerlevel10k has nothing to do with the color of `ls` or completions.
