### ISSUE TITLE
Custum icon for Gitea-Repositories

### ISSUE THREAD

**Issue by regenpfeifer** [romkatv/powerlevel10k#1248]
Hello,

powerlevel10k provides custom icons for Github- and Gitlab-Repositories, which looks very nice. I have a personal Gitea-instance, where I am hosting my git-repositories. Is it possible to set a custom icon, too, for these type of repositories?

Thank you very much,
yours, Hermann Josef

**Comment by romkatv** [comment]
Do you have a font with Gitea logo in it?

**Comment by regenpfeifer** [comment]
No, I didn't find a special Gitea icon. It's just that the "normal" git-icon looks a bit ugly for me, like a fat exclamation mark. It would be suffcient, if i could change this with a more git-like icon. It would also be possible to use the java icon "cup of tea / coffee" for Gitea, because the two are quite similar.

**Comment by romkatv** [comment]
Sorry, this is not supported.

**Comment by regenpfeifer** [comment]
O.K., thank you, @romkatv; maybe this will be supported in the future, because gitea seems to me a quite popular alternative for people or organizations who prefer a free and privacy-sensible hosting for their repositories.

**Comment by romkatv** [comment]
Sure, as soon as a logo for Gitee appears in fonts that people use, I'll modify powerlevel10k to display it.

P.S.

Personal tip: disable those icons. They are useless.
