### ISSUE TITLE
powerlevel10k icons/symbols not showing up in VScode terminal

### ISSUE THREAD

**Issue by derekowusubekoe** [romkatv/powerlevel10k#1249]
I am using iTerm2 on a MacBook Pro as my default terminal and the powerlevel10k theme works fine. However, in my integrated terminal (iTerm2.app) in VSCode I don't see the icons for folder, operating system icon, and the git icons. I also tried to reconfigure the theme in my VScode terminal but still see the same problem. The icons/symbols are not displaying in the VSCode terminal.  Is there anything I missed in the installation. Please assist.

Regards,

Derek
<img width="552" alt="Screen Shot 2021-02-07 at 9 06 12 AM" src="https://user-images.githubusercontent.com/53391732/107150012-b2d7e100-6929-11eb-9f28-e309956f394b.png">
<img width="712" alt="Screen Shot 2021-02-07 at 9 51 46 AM" src="https://user-images.githubusercontent.com/53391732/107150096-182bd200-692a-11eb-98f7-b2c4286ea00e.png">

**Comment by romkatv** [comment]
From the [FAQ](https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render):

- **Q**: Icons, glyphs or powerline symbols don't render
- **A**: Restart your terminal, install [the recommended font](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k) and run `p10k configure`.
