### ISSUE TITLE
zsh: bad substitution

### ISSUE THREAD

**Issue by Adrian-Grimm** [romkatv/powerlevel10k#125]
Everytime Antigen loads powerlevel10k theme I get this:
zsh: bad substitution
instead of every prompt

powerlevel9k is working

System WSL Ubuntu 18.04 LTS everything up to date

**Comment by romkatv** [comment]
I installed Ubuntu 18.04 LTS on WSL, launched `wsl.exe` and ran these commands:

```bash
apt update && apt install -y zsh git curl gawk
curl -fsSLO git.io/antigen
echo >~/.zshrc <<END
source ~/antigen
antigen theme romkatv/powerlevel10k
antigen apply
END
exec zsh
```

It works.

Let's try to isolate what's causing issues for you. Please run the following command:

```zsh
(
  emulate -L zsh
  setopt err_return no_unset
  local tmp && tmp=$(mktemp -d "${TMPDIR:-/tmp}"/p10k.XXXXXXXXXX)
  {
    cd $tmp
    curl -fsSLO git.io/antigen
    >>$tmp/.zshrc echo "source ${(q)tmp}/antigen"
    >>$tmp/.zshrc echo "antigen theme romkatv/powerlevel10k"
    >>$tmp/.zshrc echo "antigen apply"
    ZDOTDIR=$tmp zsh -d
  } always {
    cd || true
    rm -rf $tmp
  }
)
```

Does it work or do you get `zsh: bad substitution`? If it works, you'll need to figure out what in your `~/.zshrc` is necessary to trigger the error. If it doesn't work, try `antigen reset` and `rm -rf ~/.antigen`.

**Comment by Adrian-Grimm** [comment]
OK your command results in a working PowerLevel10k! thx
Then a other plugin update results in a broken PowerLevel10k...
I take a look on this

**Comment by Adrian-Grimm** [comment]
That is the config line which made all the Trouble:
`POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{014}╭%F{cyan}"``
But is that not allowed?

**Comment by romkatv** [comment]
Replace it with this for now:

```zsh
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%6F╭%f"
```

This will work identically in p9k and p10k. Let me know if this fixes the problem for you. Leave the issue open. I'll figure out what the best general solution is.

**Comment by romkatv** [comment]
P.S.

:+1: on tracking the culprit down.

**Comment by Adrian-Grimm** [comment]
> Replace it with this for now:
> 
> ```shell
> POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%6F╭%f"
> ```
> 
> This will work identically in p9k and p10k. Let me know if this fixes the problem for you. Leave the issue open. I'll figure out what the best general solution is.

looks a bit different but it's working 👍

**Comment by romkatv** [comment]
Can you post your p9k config? I can either fix p10k so that it looks the same with your config, or tell you how to change the config so that you get the same UI with p10k you are used to.

**Comment by benmontour-wf** [comment]
I am also having the exact same issue. 
`POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{white}"`
This line causes the issue for me. Comment out this line and no more "bad substitution"

**Comment by romkatv** [comment]
@benmontour-wf Perhaps _you_ can past your config?

**Comment by romkatv** [comment]
@benmontour-wf Blue is 4, not 6. So you need `%4F`.

**Comment by romkatv** [comment]
> looks a bit different but it's working

Sorry, it should be `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%14F╭%f". The no-effect `cyan` in your config confused me.

**Comment by benmontour-wf** [comment]
Thanks for the tip on 4 vs 6, that worked perfectly. For your reference here is my config in it's entirety.
```
POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''

POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''

POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%4F╭%f"

#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F{white}"

POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} "

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir dir_writable_joined)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time

                                    vcs background_jobs_joined)

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="clear"

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="clear"

POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="clear"

POWERLEVEL9K_VCS_CLEAN_FOREGROUND="green"

POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"

POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="red"

POWERLEVEL9K_DIR_HOME_BACKGROUND="clear"

POWERLEVEL9K_DIR_HOME_FOREGROUND="blue"

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="clear"

POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="blue"

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="clear"

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="clear"

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"

POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"

POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white"

POWERLEVEL9K_STATUS_OK_BACKGROUND="clear"

POWERLEVEL9K_STATUS_OK_FOREGROUND="green"

POWERLEVEL9K_STATUS_ERROR_BACKGROUND="clear"

POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

POWERLEVEL9K_TIME_BACKGROUND="clear"

POWERLEVEL9K_TIME_FOREGROUND="cyan"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='clear'

POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta'

POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='clear'

POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='green'
```

**Comment by romkatv** [comment]
I've submitted a fix that makes powerlevel10k work with your original configs.

Thanks to both of you for reporting this issue and helping to debug it.

**Comment by romkatv** [comment]
By the way, if you like those ornaments on the left side, you might like them on the right side as well. Powerlevel9k doesn't support this but Powerlevel10k does.

```zsh
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='─╮'
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='─┤'
POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='─╯'
```

You can add colors as you like.

**Comment by benmontour-wf** [comment]
Thanks @romkatv!

**Comment by Adrian-Grimm** [comment]
Thx =) I'll try that =)
