### ISSUE TITLE
Homebrew: remove zsh dependency 

### ISSUE THREAD

**Issue by wAuner** [romkatv/powerlevel10k#1250]
The current homebrew formula lists zsh as a dependency. However, listing this does not make sense since zsh is already the default shell on newer versions of macOS and installing another zsh is not helpful. 

https://github.com/romkatv/homebrew-powerlevel10k/blob/d2a7a4e37119bb9933c4283334475fca926d2fee/Formula/powerlevel10k.rb#L7

Even for older versions of macOS that came with bash I think it might be test to separate these two installations.

```
brew info romkatv/powerlevel10k/powerlevel10k
romkatv/powerlevel10k/powerlevel10k: stable 1.14.6
A Zsh Theme
https://github.com/romkatv/powerlevel10k
Not installed
From: https://github.com/romkatv/homebrew-powerlevel10k/blob/HEAD/Formula/powerlevel10k.rb
==> Dependencies
Required: zsh ✘
==> Caveats
To activate powerlevel10k, add the following line to .zshrc:

  source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme

If your .zshrc sets ZSH_THEME, remove that line.
```

**Comment by romkatv** [comment]
Please send a PR if this is something you care about.
