### ISSUE TITLE
Question: Is there a way to prevent custom command from slowing down prompt?

### ISSUE THREAD

**Issue by tgeng** [romkatv/powerlevel10k#1257]
I came across this project this morning and switched from Powerlevel9K immediately! The async status update is awesome! Thank you for creating this project!

However, I have a custom command that pulls Github PR status and display it in the prompt. But it slows down the prompt significantly. Is there a way to make a custom command async, just like the built-in vcs command?

**Comment by romkatv** [comment]
> I came across this project this morning and switched from Powerlevel9K immediately! The async status update is awesome! Thank you for creating this project!

Thanks 😄 

> However, I have a custom command that pulls Github PR status and display it in the prompt. But it slows down the prompt significantly. Is there a way to make a custom command async, just like the built-in vcs command?

Yes, you can implement a custom async prompt segment. Here's an example: https://www.reddit.com/r/zsh/comments/l2y976/p10k_custom_async_segment/gkb9y72/

The documentation for `p10k segment` is in `p10k help segment`. If you've run `p10k configure`, search for `prompt_example` in `~/.p10k.zsh`. (If you haven't run `p10k configure`, I highly recommend running it.)

**Comment by tgeng** [comment]
Awesome! Thank you for the pointers!
