### ISSUE TITLE
Powerlevel10k "on loading"

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#1258]
How to not show this prompt==>on loading
Could You help me?

![97082671-030e8a00-163e-11eb-8512-3df5d959e5a9](https://user-images.githubusercontent.com/61009000/107727305-efd71580-6d25-11eb-9a28-8c1ccb5346ad.jpg)

**Comment by romkatv** [comment]
Try this:

```zsh
POWERLEVEL9K_VCS_LOADING_TEXT=
POWERLEVEL9K_VCS_LOADING_PREFIX=
```

**Comment by 26chk** [comment]
> Try this:
> 
> ```shell
> POWERLEVEL9K_VCS_LOADING_TEXT=
> POWERLEVEL9K_VCS_LOADING_PREFIX=
> ```

So how do I change the color of "loading"？

**Comment by romkatv** [comment]
The same way as any other color, via `POWERLEVEL9K_VCS_LOADING_FOREGROUND`.

Closing as fixed.
