### ISSUE TITLE
p10k extensions

### ISSUE THREAD

**Issue by sadovnychyi** [romkatv/powerlevel10k#126]
(this is not an issue, feel free to close)

I took some time to configure macboook pro touchbar (just for fun, unlikely to get any use) using p10k elements, and I'm curious about better ways to hook up into p10k elements.

Source: https://github.com/sadovnychyi/dotfiles/blob/master/touchbar.zsh

Basically, you can declare something like:
```zsh
typeset -g POWERLEVEL9K_TOUCHBAR_ELEMENTS=(
  dir
  vcs
)
```

And get those elements on your touchbar, instead of left/right prompt (or in addition to).
![image](https://user-images.githubusercontent.com/193864/61634387-cbd75d80-acc3-11e9-898e-8a429da87ab9.png)
![image](https://user-images.githubusercontent.com/193864/61634402-d5f95c00-acc3-11e9-8f75-429e8279c864.png)
![image](https://user-images.githubusercontent.com/193864/61634406-d8f44c80-acc3-11e9-91d8-adddad307b1e.png)

The challenge here is that they must be in plaintext -- so all colors, links and icons must be stripped and ideally replaced with unicode equivalents. I would force plain text icons from [here](https://github.com/romkatv/powerlevel10k/blob/master/functions/icons.zsh#L442), but I'm not sure that hey are exposed unless chosen via POWERLEVEL9K_MODE (and also there's no real unicode equivalent of those icons).

And the most important question, is calling `prompt_$element custom_func` is the best way to get those p10k prompt values? I would love some documentation about each parameter to the function it's calling afterwards with results: it seems like icon can be stored in either $4 or $5, but sometimes there's a color value. Same for label, it's either in $7 or $8.

I would appreciate any guidance on ways to integrate with this, thanks a lot.

**Comment by romkatv** [comment]
This is cool!

The code is using quite a few internal APIs for which I make no promises. Here's a full list of functions from p10k that are public and can be called from user code without the risk of breakage on every update:

```zsh
prompt_powerlevel9k_setup
prompt_powerlevel9k_teardown
powerlevel9k_refresh_prompt_inplace
p9k_prompt_segment
print_icon
```

If you use anything else, you'll need to be careful when pulling updates from powerlevel10k.

I'll close the issue as you suggested. While this looks cool, it may not be useful enough to require official support form p10k.
