### ISSUE TITLE
How to edit ~/.p10k.zsh so that directory path can be shortened like this?

### ISSUE THREAD

**Issue by ChandlerHarden** [romkatv/powerlevel10k#1261]
eg: the directory would be like ~/a/b/c/d/e/f/g and I would like to shorten my directory path like this .../f/g. I have tried to set **POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_first_and_last** and **POWERLEVEL9K_SHORTEN_DIR_LENGTH=2** in ~/.p10k.zsh.

But it turns out that the new directory path is ~/a/.../.../.../.../.../f/g now.

Is there any way that I can shorten my directory path like .../f/g?

**Comment by romkatv** [comment]
Powerlevel10k cannot do this.

**Comment by ChandlerHarden** [comment]
I set:
**typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=...
 # typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_first_and_last
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2** 
and successfully meet my requirement :)
![image](https://user-images.githubusercontent.com/35600326/108101632-742cee00-70c2-11eb-81f4-f4b6bd79f413.png)

**Comment by romkatv** [comment]
Nice 👍
