### ISSUE TITLE
%{%K{black}%}%{%F{default}%} %(!.%{%F{yellow}%}.)%n@%m %{%K{blue}%F{black}%}%{%F{black}%} %~%  

### ISSUE THREAD

**Issue by iBelow** [romkatv/powerlevel10k#1262]
hi, after fresh installing on fresh OS, i'm: 
install ohmyzsh 
install from aur p10k
but after configure i have a problem ) 
in terminal i'm use MesloLGS NF Regular.ttf font

(with ohmyzsh i haven't this problem

![image](https://user-images.githubusercontent.com/8112733/107860036-51929f00-6e4e-11eb-8e5d-34aaad80ab72.png)
![image](https://user-images.githubusercontent.com/8112733/107860071-6ff89a80-6e4e-11eb-8c7a-395c82a7c77e.png)

so, how to fix it?

**Comment by romkatv** [comment]
To fix this, you need to follow installation instructions carefully.

**Comment by iBelow** [comment]
> To fix this, you need to follow installation instructions carefully.

i'm tying, but this cant fix it.


i find a solution. in .zshrc -> 
# ZSH_THEME="agnoster"

was not a commented

**Comment by nguyenvulong** [comment]
For those who are looking for the answer, this is either because you did not configure "ZSH_THEME" in `.zshrc`  OR because you use `antigen` and forgot to change this line to `powerlevel10k`:

`antigen theme romkatv/powerlevel10k`
