### ISSUE TITLE
What is .zshrc:109:bad assignment?

### ISSUE THREAD

**Issue by jms080809** [romkatv/powerlevel10k#1264]
![image](https://user-images.githubusercontent.com/75464622/107946503-77e24700-6fd4-11eb-950f-875f8fb6ce23.png)

I have finished configuring powerlevel10k and turned on the Windows Terminal again, and the powerlevel10k configuration wizard runs again. Do you have any idea why this is so? The sentences may not be natural because i was use Google translator.

**Comment by jms080809** [comment]
I solved this problem myself.

**Comment by romkatv** [comment]
> I solved this problem myself.

👍

**Comment by jms080809** [comment]
😊
