### ISSUE TITLE
Sparse-checkout repo's branch and status aren't displayed

### ISSUE THREAD

**Issue by pnuzhdin** [romkatv/powerlevel10k#1265]
See the sparse-checkout feature overview in the github blog https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/.
1. Clone any repo without checkout using `--no-checkout`.
1. Activate the sparse-checkout `git sparse-checkout init --cone`. It must be enough but I've also checkout master.
1. Powerlevel10k shows bunch of not checkout files but `git status` correctly notifies e.g. `On branch master. Your branch is up to date with 'origin/master'. You are in a sparse checkout with 1% of tracked files present.`
1. Close terminal and open it again in the same repo working directory.

Observe:
```
~/s/external-1/dev/work/exyte/ver-pvp  git status                                                         ✔ │ at 01:10:48
On branch master
Your branch is up to date with 'origin/master'.

You are in a sparse checkout with 1% of tracked files present.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   test
```

Expexted result: Powelevel10k should display the current branch and status for for such working copies/repos as usual.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/816.
