### ISSUE TITLE
VPN_IP wireguard

### ISSUE THREAD

**Issue by HaxNet** [romkatv/powerlevel10k#1266]
In the .p10k.zsh file I was able to configure to show the VPN_IP in the terminal
It seems to be only  available for OPENVPN. It doesn't show the VPN status when I am using WireGuard.

Thanks in advance

**Comment by romkatv** [comment]
Search for `vpn_ip` in `~/.p10k.zsh`. You’ll know what to do when you find the block of parameter controlling this segment.

**Comment by HaxNet** [comment]
I have it enabled and it works for openvpn, but it doesn't work for wireguard.

**Comment by romkatv** [comment]
My comment still stands.

**Comment by HaxNet** [comment]
I added the wgpia to the vpn_ip_interface

**Comment by romkatv** [comment]
> I added the wgpia to the vpn_ip_interface

👍
