### ISSUE TITLE
Upgrading from powerlevel9k added Py to the conda segment

### ISSUE THREAD

**Issue by tcpekin** [romkatv/powerlevel10k#1269]
I upgraded from powerlevel9k to 10k, and it retained everything the same way as before, except it added both the conda Python version, as well as Py to the command line prompt. My current prompt is shown below.

![image](https://user-images.githubusercontent.com/9438848/108379930-ac3d4980-7206-11eb-8168-25302ff8aded.png)

I was able to remove the Python version by setting `POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=false`, but how can I remove the Py section before the environment name? 

My full options are below:

```
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set powerlevel10k options
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(anaconda context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_ANACONDA_FOREGROUND='white'
POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=false
POWERLEVEL9K_ANACONDA_BACKGROUND='035'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
```

**Comment by romkatv** [comment]
Try this:

```zsh
POWERLEVEL9K_PYTHON_ICON=
```

**Comment by tcpekin** [comment]
Works perfectly, thank you!
