### ISSUE TITLE
Prompt shows 99 unstaged changes...but there are none

### ISSUE THREAD

**Issue by mathomp4** [romkatv/powerlevel10k#127]
I have an odd one here and this will be a long explanation. 

I work on a code that is essentially a lot of other repos constructed in a directory tree. But we don't use git submodules, but rather [manage_externals](https://github.com/ESMCI/manage_externals) (the reasons are political and sort of unique to this code).

The issue is that when I go into some of these sub-repos, I'm getting unstaged changes when there are none:

```
~/Models/GEOSgcm-from-github/GEOSgcm/src/Shared/@NCEP_Shared @aa3b651c !99                             0.01 mathomp4@gs6101-parcel-198120226232❯ git status
HEAD detached at origin/master
nothing to commit, working tree clean
```
As you see, there are no unstaged files, but it's showing 99. Now, you'll notice the odd @symbol in one of the parent directories. Again, this was a "higher than me" decision to let people know they are in one of these subrepositories. My first guess is this is causing the issue, but there are other sub-repos that it seems happy with:
```
~/Models/GEOSgcm-from-github/GEOSgcm/src/Shared/@MAPL @ae870f40#1.1.1                                  0.00 mathomp4@gs6101-parcel-198120226232❯ git status
HEAD detached at 1.1.1
nothing to commit, working tree clean
```
So...yeah. Now I did see #95 and I tried updating powerlevel10k by running `zprezto-update` and that did get a new powerlevel10k, but that didn't seem to help.

Also, per #95, I tried running `zsh -dfxic 'GITSTATUS_ENABLE_LOGGING=1 && source ~/.zprezto/modules/prompt/external/powerlevel10k/gitstatus/gitstatus.plugin.zsh && gitstatus_start MY && gitstatus_query MY && cat $GITSTATUS_DAEMON_LOG_MY'` and when I do that I see:
```
[2019-07-22 10:06:49 INFO src/repo.cc:154] Found 236 dirty candidate(s) spanning from .gitignore to README.md
[2019-07-22 10:06:49 INFO src/repo.cc:196] Found unstaged file: .gitignore
```
which is odd and suggestive. Here is this directory's listing:
```
~/Models/GEOSgcm-from-github/GEOSgcm/src/Shared/@NCEP_Shared master !99                                0.01 mathomp4@gs6101-parcel-198120226232❯ \ls -ltra
total 8
drwxr-xr-x    7 mathomp4  staff   224 Jul 22 07:34 ..
-rw-r--r--    1 mathomp4  staff   929 Jul 22 07:34 CMakeLists.txt
drwxr-xr-x   25 mathomp4  staff   800 Jul 22 07:34 NCEP_bacio
drwxr-xr-x   15 mathomp4  staff   480 Jul 22 07:34 NCEP_sfcio
drwxr-xr-x   17 mathomp4  staff   544 Jul 22 07:34 NCEP_sigio
drwxr-xr-x   72 mathomp4  staff  2304 Jul 22 07:34 NCEP_sp
drwxr-xr-x  109 mathomp4  staff  3488 Jul 22 07:34 NCEP_w3
drwxr-xr-x    9 mathomp4  staff   288 Jul 22 08:08 .
drwxr-xr-x   14 mathomp4  staff   448 Jul 22 10:06 .git
```
There is no .gitignore. But, and here's the crucial bit, there *was*! It turns out the directories that have issues are the ones where we run a [git sparse checkout](https://git-scm.com/docs/git-read-tree) to "thin" them out. Now, removing the `.gitignore` was a mistake (we also removed the `README.md`, `LICENSE.md`...oops, time for a pull request!) but there are entire directories being sparsed-out too.

So, here's a question. Do you have any experience with sparse-checkouts and this prompt? I will say my prompt configuration is essentially "copy and paste what I found on web" when I found your prompt, so I'm not an expert. Hopefully there is a simple fix, but if not, I can probably help get you to the point where you can checkout this group of code like we do and see for yourself.

**Comment by romkatv** [comment]
gitstatusd uses libgit2 to make the final assessment on the dirty candidates, and libgit2 doesn't support sparse checkout. I'm using a fork of libgit2 where I've implemented many performance improvements but I'm not up to the task of implementing sparse checkout. Sorry. Once libgit2 implements sparse checkout, gitstatusd will handle your case. Here's the issue you might want to follow: https://github.com/libgit2/libgit2/issues/2263.

**Comment by romkatv** [comment]
@mathomp4 

It's an old issue, and it's still not resolved, but there is a workaround now. Basically, you can ignore deleted unstaged files in prompt. Here's how.

1. Install powerlevel10k or update to the latest version if already installed.
2. Run `p10k configure` and select *Lean* style.
3. Open `~/.p10k.zsh` and change one line in it:
```diff
-    (( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
+    (( VCS_STATUS_NUM_UNSTAGED - VCS_STATUS_NUM_UNSTAGED_DELETED )) && res+=" ${modified}!$((VCS_STATUS_NUM_UNSTAGED - VCS_STATUS_NUM_UNSTAGED_DELETED))"
```

Basically, subtract `VCS_STATUS_NUM_UNSTAGED_DELETED` from `VCS_STATUS_NUM_UNSTAGED`.

I saw [your comment](https://github.com/starship/starship/issues/423#issuecomment-535534280) where you mentioned that you've switched to Starship. Powerlevel10k has come a long way since then. If you are open to a bit of experimentation, give it another try. It should be *much* faster than Starship, and it has several exciting new features. See the (redesigned) [homepage](https://github.com/romkatv/powerlevel10k/blob/master/README.md).

**Comment by mathomp4** [comment]
@romkatv I'm actually using p10k most places now because of the slowness. I'll have to try this out in my repos...

**Comment by jarjar2go** [comment]
@romkatv Thanks for the workaround. 

My prompt remains yellow instead of green because of the deleted unstaged filed. Do you know how to fix this as well?

**Comment by romkatv** [comment]
The easiest way to fix this is to use Lean or Classic style instead of Rainbow.
