### ISSUE TITLE
_p9k_left_prompt_segment:85: bad math expression: operand expected at end of string

### ISSUE THREAD

**Issue by Jerilok** [romkatv/powerlevel10k#1270]
Hello,

By some reason every **second tab** that I open in my iTerm falls into this error:
```
Last login: Fri Feb 19 14:33:24 on ttys001
_p9k_restore_state_impl:87: read-only variable: _p9k_sourced
_p9k_left_prompt_segment:85: bad math expression: operand expected at end of string
_p9k_left_prompt_segment:85: bad math expression: operand expected at end of string
 ~

_p9k_left_prompt_segment:85: bad math expression: operand expected at end of string
_p9k_left_prompt_segment:85: bad math expression: operand expected at end of string
```
Does anyone knows how to fix this issue?

**Comment by romkatv** [comment]
> Does anyone knows how to fix this issue?

My guess is that your `~/.zshrc` invokes internal functions from powerlevel10k. Once you remove calls to the internal functions of powerlevel10k, the errors will go away.

**Comment by Jerilok** [comment]
Thanks for the info, I was mistakenly written ```ZSH_THEME="powerlevel10k/powerlevel10k"``` in the ```~/.zshrc``` , now by removing it the problem is fixed.
