### ISSUE TITLE
How to shorten path of CWD?

### ISSUE THREAD

**Issue by qazip** [romkatv/powerlevel10k#1271]
Hello,

First, let me thank you for this amazing project. Thank you for the awesome work mate!

Is it possible to shorten the path of the working directory? If you use p10k on 1 line (as opposed to 2 lines, where the input is below the current working directory), it is handy to shorten the CWD. Say you are in a folder with a name that never ends. It would be nice to have it shorten.

Does p10k already support this?

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `dir:` and modify parameters that you see there. The following parameters are most relevant:

```zsh
# Shorten directory if it's longer than this even if there is space for it. The value can
# be either absolute (e.g., '80') or a percentage of terminal width (e.g, '50%'). If empty,
# directory will be shortened only when prompt doesn't fit or when other parameters demand it
# (see POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS and POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT below).
# If set to `0`, directory will always be shortened to its minimum length.
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
# When `dir` segment is on the last prompt line, try to shorten it enough to leave at least this
# many columns for typing commands.
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
# When `dir` segment is on the last prompt line, try to shorten it enough to leave at least
# COLUMNS * POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT * 0.01 columns for typing commands.
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
```

**Comment by qazip** [comment]
Ah.. I was using "Pure" and that is why I didn't see those options in the .p10k.zsh. Choosing "lean" and then "8 bit" fixes this.

**Comment by peeredNL** [comment]
Is there a way to shorten the pwd path when using Pure variant of Powerlevel10k?

**Comment by romkatv** [comment]
Pure style replicates [pure zsh theme](https://github.com/sindresorhus/pure). The latter doesn't shorten path, hence Pure style in powerlevel10k does not. You can customize it by editing `~/.p10k.zsh` if you like.

Note that Lean style is all around better than Pure.

**Comment by peeredNL** [comment]
Thanks for the quick reply! I'll switch back to Lean style and try things out
