### ISSUE TITLE
How to show git status in home directory

### ISSUE THREAD

**Issue by Adnios** [romkatv/powerlevel10k#1272]
My home directory is a git repository. When `cd` my home directory, p10k looks like this.
![image](https://user-images.githubusercontent.com/41060790/108625035-912b3d80-7483-11eb-88f9-d95163365559.png)
But I want it to be like this. What can I do?
![image](https://user-images.githubusercontent.com/41060790/108625058-aa33ee80-7483-11eb-8d6d-42876aaeba33.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#why-is-git-status-from-homegit-not-displayed-in-prompt

**Comment by Adnios** [comment]
> See https://github.com/romkatv/powerlevel10k#why-is-git-status-from-homegit-not-displayed-in-prompt

thank you very much
