### ISSUE TITLE
Getting a ?1 after my git branch 

### ISSUE THREAD

**Issue by jefflam** [romkatv/powerlevel10k#1275]
There seems to be a weird "?1" character in my command line despite folllowing the instructions to install and configure p10k

I'm wonderinf if this was supposed to be a symbol?

Attaching a screenshot here.. 

<img width="798" alt="Screenshot 2021-02-23 at 6 21 50 PM" src="https://user-images.githubusercontent.com/1057981/108830202-10477f80-7604-11eb-9f6d-0729caf32274.png">

Thanks!

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#question-mark-in-prompt

**Comment by jefflam** [comment]
Ah. Thanks!
