### ISSUE TITLE
Feature Request - cmd execution timestamp when `transient:true`

### ISSUE THREAD

**Issue by Drauku** [romkatv/powerlevel10k#1277]
I would like to request the ability to display the timestamp of when a command was executed after the active command line has already moved on. I am currently using the 'transient' style, and very much appreciate the minimalism that is left behind once a command is executed, but I would like a visible timeline of commands if possible, perhaps also the execution duration, or additional options to be added to the left of the `>` symbol prior to the command as well. I have modified a screenshot to show approximately what I am trying to describe. I am aware that I can achieve this by not using the 'transient' style, however I want the additional active information displayed from a full feature-set only on my _current_ command line structure.

Note the first three lines show current behavior, and the 4th line indicates my desired change in display behavior:
![image](https://user-images.githubusercontent.com/17952866/109357333-ab7c6700-7847-11eb-825d-1dba5bff3b6e.png)

Apologies if this is already a feature, I was unable to discover how to activate after reading through the `.p10k.zsh` config file nor the instructions on this GitHub page.

Thank you!

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/917#issuecomment-664791542. If it's unclear how to apply those parameters to your own config, attach your config and I'll do it for you.

**Comment by Drauku** [comment]
Apologies for the request then, as it's already possible. I'll dig more into the scripts and figure it out. No need for you to waste time on my issue! This week has been my first foray into ZSH, and your theme is amazing. Thanks for your work creating this, it's obviously the best one out there. 

After messing around for a couple more hours I figured out that modifying lines `197-203` does mostly what I want. Is there a better way to do it, maybe one that follows the formatting on `RPROMPT` `time` field? I could not figure out how to use the same call as the one used in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` so the time-text is color formatted to match the prompt foreground color.

```bash
  # Default prompt symbol.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='[%*] ❯'
  # Prompt symbol in command vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='[%*] ❮'
  # Prompt symbol in visual vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='[%*] V'
  # Prompt symbol in overwrite vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='[%*] ▶'
```

I'll close the ticket with this comment since I've technically accomplished the request myself.

Again, thanks for your work on this amazing theme.

**Comment by romkatv** [comment]
> If it's unclear how to apply those parameters to your own config, attach your config and I'll do it for you.

☝️ 

I realize you've decided to ask a question instead of posting your config in order to save my time and I appreciate that. It would be much easier if you did what I suggested. If you want help, please post your config.

**Comment by Drauku** [comment]
GitHub won't allow me to post the config file with the proper `.zsh` extension, so I change it to `.txt`

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/6056068/p10k.txt)

**Comment by romkatv** [comment]
This should do it:

```diff
@@ -37,7 +37,8 @@
     vcs                     # git status
     # =========================[ Line #2 ]=========================
     newline                 # \n
-    # prompt_char             # prompt symbol
+    time                    # current time
+    prompt_char             # prompt symbol
   )
 
   # The list of segments shown on the right. Fill it with less important segments.
@@ -135,7 +136,7 @@
   # as POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND below.
   typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%238F╭─'
   typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%238F├─'
-  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%238F╰─'
+  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%238F╰─▶'
   # Connect right prompt lines with these symbols.
   typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
   typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
@@ -178,7 +179,7 @@
   # The right end of right prompt.
   typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
   # Left prompt terminator for lines without any segments.
-  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='%238F▶'
+  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
 
   #################################[ os_icon: os identifier ]##################################
   # OS identifier color.
@@ -194,13 +195,13 @@
   # Red prompt symbol if the last command failed.
   typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196
   # Default prompt symbol.
-  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='[%*] ❯'
+  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
   # Prompt symbol in command vi mode.
-  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='[%*] ❮'
+  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
   # Prompt symbol in visual vi mode.
-  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='[%*] V'
+  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
   # Prompt symbol in overwrite vi mode.
-  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='[%*] ▶'
+  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
   typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
   # No line terminator if prompt_char is the last segment.
   typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
@@ -545,6 +546,8 @@
   # Custom prefix.
   # typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='%244Ftook '
 
+  typeset -g POWERLEVEL9K_TIME_LEFT_RIGHT_WHITESPACE=' %k%234F\uE0B4'
+
   #######################[ background_jobs: presence of background jobs ]#######################
   # Don't show the number of background jobs.
   typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
@@ -1532,6 +1535,9 @@
   # Custom prefix.
   # typeset -g POWERLEVEL9K_TIME_PREFIX='%244Fat '
 
+  function p10k-on-post-prompt() { p10k display '1|2/left_frame'=hide '2/left/*'=show }
+  function p10k-on-pre-prompt()  { p10k display '1|2/left_frame'=show '2/left/*'=hide }
+
   # Example of a user-defined prompt segment. Function prompt_example will be called on every
   # prompt if `example` prompt segment is added to POWERLEVEL9K_LEFT_PROMPT_ELEMENTS or
   # POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS. It displays an icon and orange text greeting the user.
@@ -1571,7 +1577,7 @@
   #   - always:   Trim down prompt when accepting a command line.
   #   - same-dir: Trim down prompt when accepting a command line unless this is the first command
   #               typed after changing current working directory.
-  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
+  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
 
   # Instant prompt mode.
   #
```

**Comment by Drauku** [comment]
Fantastic. It works exactly as requested, thank you!

I never would have figured it out due to the addition of those functions and additional typeset options. 

Thanks for cleaning up the LAST_PROMPT_PREFIX_END_SYMBOL as well.
