### ISSUE TITLE
Instant prompt flickers and resizes

### ISSUE THREAD

**Issue by pinpox** [romkatv/powerlevel10k#1280]
I've enabled the instant prompt by adding this to the top of my `.zshrc` as specified in the README.
```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```
The instant prompt seems to be working, the prompt is indeed way faster (actually it is indeed "instant"), but it flickers when loading real prompt later on. Also the connection between the left and right side of the prompt is incomplete and resizes, which is even more confusing than the flicker. Since it's a bit hard to describe, here is a video of starting a terminal (alacritty) with the problem:

https://user-images.githubusercontent.com/1719781/109420703-31c5b400-79d4-11eb-96bc-86f8898823a1.mp4

Is there a fix/workaround for this? I'd really like to use the instant prompt, but this flicker/resize is too confusing.

**Comment by romkatv** [comment]
Some terminals are better than others at rendering performance. Try using a different terminal and see if you like it better.

**Comment by pinpox** [comment]
@romkatv I doesn't seem to be related to the terminal emulator. I'm using [alacritty](https://github.com/alacritty/alacritty) which claims to have one of the best rendering performances. I also just tried:
- xterm
- kitty
- lxterminal
- termite

And all of them have the flicker bug and most of them the resizing thing aswell (the connecting blue dots from the video above being only about 80 chars with when starting and then resizing to the full width on flicker)

Are you *not* having the flickering? If so, what terminal are you using?

**Comment by romkatv** [comment]
> I'm using [alacritty](https://github.com/alacritty/alacritty) which claims to have one of the best rendering performances.

It's well-known that Alacritty documentation is deceptive. When it claims to be fast, it would be more accurate to say it has high throughput. No one cares about throughput though and everyone cares about latency. Alacritty is far from having the lowest latency. It's not terrible but by no means fast.

> Are you _not_ having the flickering?

No. I don't have flickering in any terminal.

> If so, what terminal are you using?

I've used all terminals you've listed above and more. My current go-to terminal on Linux is Tilix.

Can you reproduce this with a zshrc that sources nothing except powerlevel10k?

Are you using a very slow machine?

**Comment by nathanbraun** [comment]
FYI - I was experiencing this same issue -- turned out to be from prezto, got rid of some of the unnecc modules and it sped it up.
