### ISSUE TITLE
Is autoconfiguration possible upon first install?

### ISSUE THREAD

**Issue by jonassteinberg1** [romkatv/powerlevel10k#1281]
Building a docker image and have zsh, oh-my-zsh and your theme installing nicely except I'd like a way to handle autoconfiguration.  Is this possible?  Something like `zsh yyyy112nyy` to automatically configure the shell I like.  Is this already a feature or?

Love the theme, use it everyday!

- Jonas

**Comment by romkatv** [comment]
The configuration wizard generates `~/.p10k.zsh` and adds a few lines to `~/.zshrc`. You can simply copy these two files over.

**Comment by jonassteinberg1** [comment]
okay that's what I thought, thanks.
