### ISSUE TITLE
'MesloGS NF' not working normal

### ISSUE THREAD

**Issue by seuldos** [romkatv/powerlevel10k#1282]
### This is my iTerm2 preference#profiles#font conf
![image](https://user-images.githubusercontent.com/29501807/109915823-719add00-7ced-11eb-90ab-ffa29e29f0e1.png)

### This is `get_icon_names` executed result
![image](https://user-images.githubusercontent.com/29501807/109915848-80818f80-7ced-11eb-91ae-b94294c46f6f.png)

### This is sample as git repo view
![image](https://user-images.githubusercontent.com/29501807/109915890-98591380-7ced-11eb-8708-cd0528f8e805.png)

maybe what i missing?

**Comment by romkatv** [comment]
Restart your terminal, then run `p10k configure`.
