### ISSUE TITLE
Is there a way to TAB for fuzzy matching of history? 

### ISSUE THREAD

**Issue by knutole** [romkatv/powerlevel10k#1283]
Let's say I've done the following command some minutes back: 

```bash
kubectl port-forward -n default svc/unique-service 80:8080
```

In fish, I'm used to being able to write `$ uniq` [TAB] -> `kubectl port-forward -n default svc/unique-service 80:8080`, as it "fuzzy matches" strings from history. This is great for finding and repeating previous commands. (Apart from this I don't miss fish at alll, LOVE your shell! 💯 )

Is this functionality available in p10k? Or something I could easily add myself? 

Thanks!

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by knutole** [comment]
Thanks, I understand. Found what I was looking for: https://github.com/zsh-users/zsh-autosuggestions
