### ISSUE TITLE
Incorrect VCS commit symbol condition

### ISSUE THREAD

**Issue by EvanDurfee** [romkatv/powerlevel10k#1294]
In the p10k configuration files (classic and lean, at least), there's a check for whether or not to show the git commit symbol:

```
# Display the current Git commit if there is no branch and no tag.
# Tip: To always display the current Git commit, delete the next line.
[[ -z $VCS_STATUS_LOCAL_BRANCH && -z $VCS_STATUS_LOCAL_BRANCH ]] &&  # <-- this line
  res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"
```

Judging by the comment, the second condition should be `$VCS_STATUS_TAG` instead of checking branch again. Swapping out for `$VCS_STATUS_TAG` results in the documented behavior, showing only the tag instead of both tag and commit.

**Comment by romkatv** [comment]
Thanks for the bug report! Fixed.
