### ISSUE TITLE
Cross-shell p10k

### ISSUE THREAD

**Issue by anki-code** [romkatv/powerlevel10k#1296]
Hi @romkatv ! Long time no see!

Is there a way to use p10k as cross-shell prompt like [Starship](https://github.com/starship/starship)?

In the nutshell there is a `starship prompt` command that returns the prompt. Maybe there is something similar for p10k?

Thanks!

**Comment by romkatv** [comment]
> Is there a way to use p10k as cross-shell prompt like [Starship](https://github.com/starship/starship)?

No. Powerlevel10k is a zsh theme.

**Comment by romkatv** [comment]
> The full question is: can I install zsh, then setup p10k and then get the p10k prompt output and to use it in another shell?

No. Powerlevel10k only works in zsh. It's not possible to use it from another shell.
