### ISSUE TITLE
Maintaining the timestamp of past lines in transient prompt.

### ISSUE THREAD

**Issue by yrammos** [romkatv/powerlevel10k#1297]
The date-time field of the prompt provides rich information and often proves invaluable for debugging and data recovery purposes.

Would it be possible to keep it visible in previous transient-prompt lines?

Many thanks.

**Comment by romkatv** [comment]
This is supported. See https://github.com/romkatv/powerlevel10k/issues/917#issuecomment-664791542 for a config example.

**Comment by yrammos** [comment]
Much appreciated, @romkatv. Thank you for your stellar work and generous contribution to the community.

**Comment by bric3** [comment]
This is neat but hard to get right if you're not a shell expert. Also this has to be re-applied and adapted after reconfiguration.

This could be a nice feature to be able to to configure how the post exec prompt should look.
