### ISSUE TITLE
How to change color or make text item list under like zsh-autosuggestions

### ISSUE THREAD

**Issue by scila1996** [romkatv/powerlevel10k#1298]
Hi. Current when i press '[TAB]' and it will be show the list under command like this. But color of them is alternative to command 

![image](https://user-images.githubusercontent.com/17109300/110980806-d531a400-8398-11eb-940e-f03b4f3b0ddf.png)

I like all item of under list will colored like zsh-autosuggestions

![image](https://user-images.githubusercontent.com/17109300/110980934-fb574400-8398-11eb-8fd1-47751abaf194.png)

How can i do that , thank all !

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect
