### ISSUE TITLE
[Feature request] toggle options (especially transient prompt)

### ISSUE THREAD

**Issue by kescobo** [romkatv/powerlevel10k#1299]
I really like having the history of what directory I was in, time of execution etc, so I don't want transient prompt under most circumstances. But sometimes, especially (as noted in the docs), when I need to copy a bunch of commands and their output, it's nice to turn on the transient prompt, but I don't want to have to go back through the entire config wizard. 

Is there a straightforward way to transiently (ha!) turn on the transient prompt?

**Comment by romkatv** [comment]
This should do it:

```zsh
function flip-transient-prompt() {
  if [[ $POWERLEVEL9K_TRANSIENT_PROMPT != off ]]; then
    POWERLEVEL9K_TRANSIENT_PROMPT=off
  else
    POWERLEVEL9K_TRANSIENT_PROMPT=always
  fi
  p10k reload
}

zle -N flip-transient-prompt
bindkey '^T' flip-transient-prompt
```

You can flip transient prompt on and off either by typing `flip-transient-prompt` or by hitting <kbd>Ctrl+T</kbd>.

**Comment by kescobo** [comment]
Amazing! There's a slight delay (I can hit enter a few times with the initial behavior), but other than that, works like a charm!
