### ISSUE TITLE
Question: changing VCS branch colour?

### ISSUE THREAD

**Issue by krupenja** [romkatv/powerlevel10k#130]
I am using powerlevel10k with a modified lean config. I was able to change all the colours to the one desired *except* VCS branch colour, bright green "master" on the screenshot below:

![image](https://user-images.githubusercontent.com/26354715/61711201-23c1a300-ad5c-11e9-8734-8935023014bf.png)

Any idea which variable should I modify to change the branch colour?

**Comment by romkatv** [comment]
The answer depends on what you've already changed. In the unchanged `p10k-lean.zsh` you can change `76` to the desired color on this line: https://github.com/romkatv/powerlevel10k/blob/db70d1a59fade013c8e87fe88306b0e4f51d39cf/config/p10k-lean.zsh#L207

You might want to change `76` on the next line as well. It shows `@commit` if and only if there is no branch.

**Comment by romkatv** [comment]
By the way, did have you intentionally enabled `user@host` or is it showing like that by default? The unchanged config is not supposed to show `user@host` unless you are root or connected via SSH (in other cases this segment has almost no value).

**Comment by krupenja** [comment]
Thank you for the quick response! Changing `76` where you suggested indeed does the trick. And yes, I have temporarily enabled `user@host` and `time` to play around so there is no bug in the default lean config 👍

**Comment by AX-11** [comment]
This has since been moved to `vcs: git status` in the config file.
https://github.com/romkatv/powerlevel10k/blob/65599411ec83505a091f68489617316dec355510/config/p10k-lean.zsh#L363-L369
Branch colour is `clean`.

**Comment by kuntau** [comment]
@romkatv How do you use hex format in this configs? <sup>sorry for pinging</sup>

> This has since been moved to `vcs: git status` in the config file.
> 
> https://github.com/romkatv/powerlevel10k/blob/65599411ec83505a091f68489617316dec355510/config/p10k-lean.zsh#L363-L369
> 
> 
> Branch colour is `clean`.

**Comment by romkatv** [comment]
```zsh
local clean='%F{#ffffff}'
```
