### ISSUE TITLE
Get rid of branch name

### ISSUE THREAD

**Issue by virejdasani** [romkatv/powerlevel10k#1309]
Right now, my terminal looks like this

![Screenshot 2021-03-18 at 12 06 18 PM](https://user-images.githubusercontent.com/67495678/111583399-5b5b4980-87e2-11eb-945e-c87c090454ee.png)

I don't want it to show the branch name at all.
I want it to show only CodeForces.
I tried messing about in the .p10k.zsh but can't find how I can achieve this.
Please help!

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for "vcs" and comment out the first match.

**Comment by virejdasani** [comment]
Thank you so much @romkatv, it worked. I appreciate it 👍
