### ISSUE TITLE
Transparent background does not apply to accompanying separator character

### ISSUE THREAD

**Issue by Azumgi** [romkatv/powerlevel10k#131]
I try to make status segment transparent but cannot achieve this whether I put it on the left or on the right because of unaffected separator characters.
![image](https://user-images.githubusercontent.com/35058624/61746926-74a9b980-ada5-11e9-875f-fa0c5fe3b491.png)
```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

# For some reason, if I put 'dir_writable_joined' right after 'dir', it will break formatting.
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir vcs dir_writable_joined command_execution_time status)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{blue}\u256D\u2500%F"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{blue}\u2570\uf460%F{white} "

# Do not show successful execution indicator.
POWERLEVEL9K_STATUS_OK=false
# Do not show error code.
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='none'

POWERLEVEL9K_HOME_ICON="\uf015"                 # 
POWERLEVEL9K_HOME_SUB_ICON="\uf015"             # 
POWERLEVEL9K_FOLDER_ICON="\uf07c "              # 
POWERLEVEL9K_LOCK_ICON="\uf023"                 # 
POWERLEVEL9K_VCS_BRANCH_ICON="\uf418 "          # 
POWERLEVEL9K_VCS_UNSTAGED_ICON="\uf111"         # 
POWERLEVEL9K_VCS_STAGED_ICON="\uf055"           # 
POWERLEVEL9K_VCS_STASH_ICON="\uf01c "           # 
POWERLEVEL9K_VCS_UNTRACKED_ICON="\uf059"        # 
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON="\uf175" # 
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON="\uf176" # 
POWERLEVEL9K_EXECUTION_TIME_ICON="\uf017 "      # 
```

Zsh, Oh-My-Zsh, PowerLevel10k are all up to date.
System: WSL Arch

**Comment by romkatv** [comment]
There are a couple of bugs in Powerlevel9k where transparent background gets conflated with black background. Unfortunately, many users rely on this exact manifestation of the bug that you are experiencing. When I've fixed it, I received a flood of bug reports and had to roll it back. I've now constrained the effects of this bug to a narrow band where it's not too destructive, and I also implemented workarounds that you can employ to counteract the bug.

In your case the solution is to define this parameter:

```zsh
POWERLEVEL9K_STATUS_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
```

This sets the end-of-line symbol for left prompt but only when the line ends with `status`.

Powerlevel10k allows you to set most parameters with different degrees of specificity. For example, `POWERLEVEL9K_BACKGROUND` sets the default background for all segments, `POWERLEVEL9K_DIR_BACKGROUND` sets background for `dir`, and `POWERLEVEL9K_DIR_HOME_BACKGROUND` sets background for `dir` in state `HOME`. The most specific parameter wins.

Similarly, `POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL` sets the terminator for the left prompt line, `POWERLEVEL9K_STATUS_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL` sets the same but only for `status` and `POWERLEVEL9K_STATUS_ERROR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL` sets it just for `status` in state `ERROR`.

> `# For some reason, if I put 'dir_writable_joined' right after 'dir', it will break formatting.`

This works as expected. `joined` means the segment is rendered right after the previous segment without any separator in between. It looks weird when segments use different background colors. If you can tell me what you are trying to achieve, I'll likely be able to can tell you how to do it.

P.S.

The recommended config is very good: https://github.com/romkatv/powerlevel10k#for-new-users. If you are into icons, remove `POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION` parameter from it and you'll get a great prompt.

**Comment by Azumgi** [comment]
Thank you very much for your extremely thorough answer. It answers everything and even more. I've just tried to play with `p10k-lean` config and it has a lot of awesome features. But more importantly, it serves as complete documentation, and I should've examined it in the first place instead of skimming through PowerLevel9k wiki and user configs. Sorry for wasting your time and thanks again for your very descriptive answer.

**Comment by FlatZephyr** [comment]
Hello, I have the same problem with directory segment from the right side. What the variable responds for this color or how to make it (triangle to the left) transparent too??
![screen_with_triangle](https://user-images.githubusercontent.com/65401519/85899783-4e876780-b807-11ea-91da-247d36ae1a58.png)

**Comment by romkatv** [comment]
@FlatZephyr Try this:

```zsh
POWERLEVEL9K_DIR_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
```

**Comment by FlatZephyr** [comment]
Thank you, this solves my problem until the status appears. Can this triangle before status become transparent too??
![bad_triangle_with_status](https://user-images.githubusercontent.com/65401519/85901073-ad4de080-b809-11ea-9e79-1144d7fc52d9.png)

**Comment by romkatv** [comment]
@FlatZephyr That's not possible currently.

**Comment by Adrian-Benavente** [comment]
In Konsole terminal, I can confirm you can fix it by setting the same terminal theme as your global desktop theme. I don't know about other terminals.
