### ISSUE TITLE
importing .p10k.zsh vice using p10k confiugure

### ISSUE THREAD

**Issue by Vanderscycle** [romkatv/powerlevel10k#1310]
Hi,

Sorry to bother you if that question was already asked, but I couldn't find an answer.

As part of my .dofiles repo, I have saved the .p10k.zsh config that I configured previously. When setting a new server, the p10k configure boots every time I log despite the presence of the .p10k.zsh file in ~/
Is there a command that I must append to .zshrc file for oh-my-zsh to look for the file vice running p10k configure?

Thank you,

**Comment by romkatv** [comment]
You need to source `~/.p10k.zsh` from `~/.zshrc`.

**Comment by Vanderscycle** [comment]
Thank you very much it works! I still have so much to learn.
