### ISSUE TITLE
Color of arrow in non-hooked mode shifted by one

### ISSUE THREAD

**Issue by MySurmise** [romkatv/powerlevel10k#1311]
![image](https://user-images.githubusercontent.com/70728036/111759854-5cea4780-889e-11eb-810c-fc71ed83009d.png)

The first arrow should be red, while the 7th should be green. It always prints the current arrow in the color of success of the last command.

My suggestion is that the currently typed command is colored in e.g. yellow and the already typed commands are colored in their correct success status-color. (If it worked, green, if it didn't, red.)

As this may be important, I attached the config file here:
[configp10k.txt](https://github.com/romkatv/powerlevel10k/files/6170146/configp10k.txt)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them
