### ISSUE TITLE
Please add remove OS Icon option.

### ISSUE THREAD

**Issue by joezhouchenye** [romkatv/powerlevel10k#1312]
I think the OS icon is ugly and occupies unnecessary space. Although I can change the view by editing the configuration file, can you add the option in the configuration process? It would be more convenient.

**Comment by romkatv** [comment]
When you run `p10k configure`, it asks you whether you want "few" or "many" icons. The second option adds decorative (a.k.a. non-functional, or useless) icons. Choose "few".

**Comment by joezhouchenye** [comment]
I know that. The problem is that I like the other icons, except the os icon. I have to comment on the os_icon line in the POWERLEVEL9K_LEFT_PROMPT_ELEMENTS option currently. Maybe this is not a common request.

**Comment by romkatv** [comment]
This is not a common request.
