### ISSUE TITLE
[Feature] - More Colors with Prompts while Using Rainbow

### ISSUE THREAD

**Issue by Not-Qualified** [romkatv/powerlevel10k#1314]
Can You give Options with Like Selecting Color that which color we can use with prompt

Something Like at start of script color chooser:
1: red
2: green
3: custom - (Comma Separated value List)

Then You use that color with Rainbow theme

**Comment by romkatv** [comment]
I'm afraid I won't have time to implement this in the foreseeable feature. Please send a PR if you care about this feature.

**Comment by Not-Qualified** [comment]
What is PR ?

**Comment by romkatv** [comment]
Sorry, PR means Pull Request.

**Comment by Not-Qualified** [comment]
If I'll update it myself then I'll for sure, yet i don't know whether I'll be able to implement that kind of thing or not
