### ISSUE TITLE
Separate gitstatus

### ISSUE THREAD

**Issue by JuniorJPDJ** [romkatv/powerlevel10k#1316]
Hi!
I'd like to package powerlevel10k for Alpine Linux but I've a concern.

My idea is to package gitstatus as separate package, as it's architecture dependent, and powerlevel10k itself is not (could use `noarch` arch).
1. Would you support this setup? It would be cool to be listed in readme here ;)
2. How can it be safely done without any hidden problems?

**Comment by romkatv** [comment]
> Hi!
> I'd like to package powerlevel10k for Alpine Linux but I've a concern.
> 
> My idea is to package gitstatus as separate package, as it's architecture dependent, and powerlevel10k itself is not (could use `noarch` arch).
> 
> 1. Would you support this setup? It would be cool to be listed in readme here ;)

No. Powerlevel10k can be used either without gitstatus or with the one bundled with it.

> 2. How can it be safely done without any hidden problems?

Packages owned by other people cause me a lot of grief. If at all possible, please don't package powerlevel10k. If you do, please make sure people submit bugs to you and not to me if they use your package and it doesn't work.

That said, you are of course free to do whatever you want within the (very permissible) terms of the license.

**Comment by JuniorJPDJ** [comment]
I'd like to stay very close to your AUR package, that's why I asked.
I'm not here to cause trouble.
Thanks for reply anyway, closing!
