### ISSUE TITLE
How do you get multi coloured +/- symbols on Git Diff

### ISSUE THREAD

**Issue by AzySir** [romkatv/powerlevel10k#1319]
Hi there, I may have made a mistake on the installation but I can't seem to get multi coloured + and - symbols on git diff. 

AS you can see in the image, I know i'm being a little precious but they do assist me in quicker development. IS there anything I can do to address this that you recommend? 

<img width="659" alt="Screen Shot 2021-03-24 at 1 58 06 pm" src="https://user-images.githubusercontent.com/37623164/112323103-8225ee00-8cc2-11eb-892e-830b40b02b9d.png">

**Comment by romkatv** [comment]
See:

- https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect
- https://github.com/so-fancy/diff-so-fancy

**Comment by AzySir** [comment]
Thanks @romkatv
