### ISSUE TITLE
p10k configure does not offer to select config icons

### ISSUE THREAD

**Issue by vladseverin** [romkatv/powerlevel10k#1320]
I went through all the steps and I did not get the step of choosing the display of many icons?

How to resolve it or manually enable them?

**Comment by romkatv** [comment]
This option is only offered if the font used by your terminal is capable of displaying said items. Which font are you using?

**Comment by vladseverin** [comment]
@romkatv fontFamily: '"Hack Nerd Font","MesloLGS NF", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace'

**Comment by romkatv** [comment]
Please run the following command and post a screenshot:

```zsh
locale && print -r $terminfo[colors] && print '\uF306'
```

**Comment by vladseverin** [comment]
@romkatv <img width="674" alt="Screenshot 2021-03-25 at 19 55 04" src="https://user-images.githubusercontent.com/26458868/112484285-000df600-8da4-11eb-9e58-5fc48c81cc15.png">

**Comment by romkatv** [comment]
Please run `p10k configure` and post a screenshot of the first 3 screens and indicate your answers to the questions from them.

**Comment by romkatv** [comment]
Sorry, the first **5** screens.

**Comment by vladseverin** [comment]
1. Yes ![image](https://user-images.githubusercontent.com/26458868/112500575-b37de700-8db2-11eb-8abd-9454ab80f331.png)
2. Yes ![image](https://user-images.githubusercontent.com/26458868/112500618-bed11280-8db2-11eb-804d-c8f063f0a227.png)
3. Yes ![image](https://user-images.githubusercontent.com/26458868/112500664-c690b700-8db2-11eb-8702-2232cb597d08.png)
4. Yes ![image](https://user-images.githubusercontent.com/26458868/112500695-cdb7c500-8db2-11eb-9592-d7ead8eed5dc.png)
5. Yes ![image](https://user-images.githubusercontent.com/26458868/112500737-d7412d00-8db2-11eb-8199-f06d51ffcd9c.png)

**Comment by romkatv** [comment]
"Pure" style (screen 5) is a complete replication of this theme: https://github.com/sindresorhus/pure. That theme doesn't have fancy icons, hence this style doesn't.

This option exists only for people who got used to the pure theme. It's worse than "Lean" style by all measures. Lean has "many icons" among other things.

**Comment by vladseverin** [comment]
@romkatv thanks for help!!
