### ISSUE TITLE
The font MesloLGS NF Regular cannot display some characters normally .

### ISSUE THREAD

**Issue by phone-burner** [romkatv/powerlevel10k#1321]
Environment : KUbuntu 20.10
Terminal : Konsole 20.08.2
Font : MesloLGS NF Regular downloaded from this project's  `README.md`
Zsh version : 5.8
Powerlevel10k theme's version : today's latest git version
Powerlevel10k with Konsole's default font `hack` :
![Screenshot_20210325_211901](https://user-images.githubusercontent.com/51866924/112480377-ede68480-8db0-11eb-8f27-590dd04a59f1.png)
Powerlevel10k with MesloLGS NF Regular : 
![Screenshot_20210325_211930](https://user-images.githubusercontent.com/51866924/112480740-487fe080-8db1-11eb-8ff2-cd9b0030b9ec.png)
![Screenshot_20210325_213249](https://user-images.githubusercontent.com/51866924/112481231-c04e0b00-8db1-11eb-9b0b-75fab976a2a9.png)
![Screenshot_20210325_213317](https://user-images.githubusercontent.com/51866924/112481238-c3e19200-8db1-11eb-9fb8-d0afce3715d1.png)
Icons and some UTF-8 characters cannot be displayed normally when using font MesloLGS NF Regular .

**Comment by phone-burner** [comment]
But on Termux it works normally .
![IMG_20210325_214804](https://user-images.githubusercontent.com/51866924/112483511-0efca480-8db4-11eb-82ab-2796be7871fa.jpg)

**Comment by romkatv** [comment]
I'm afraid I don't have the bandwidth to debug this. If you find a reason for this, please post an update.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here.
