### ISSUE TITLE
Unstaged changes count incorrect for git sparse checkout

### ISSUE THREAD

**Issue by Mellbourn** [romkatv/powerlevel10k#1322]
I'm using https://git-scm.com/docs/git-sparse-checkout on a large monorepo. When I do, powerlevel10k shows a large number of files as unstaged (using the `!` notation), although I have none unstaged.

```
❯ git status --ignore-submodules=dirty
On branch master
Your branch is behind 'origin/master' by 39 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

You are in a sparse checkout with 51% of tracked files present.

nothing to commit, working tree clean
 ~/c/k/xxx-app ❯                                                                 ✔ < master ⇣39 *9 !42073 
```
(I've edited out some Unicode characters that did not paste well into Github)

This is a brand new pull of `powerlevel10k`, commit 58f5470. Git version is 2.31.0. macOS Big Sur 11.2.3

Thanks for making this otherwise great piece of software!

**Comment by romkatv** [comment]
See https://github.com/romkatv/gitstatus/issues/107

**Comment by Mellbourn** [comment]
Ok, that makes sense. Thank you for your quick response.

**Comment by romkatv** [comment]
Closing as Won't Fix.
