### ISSUE TITLE
Issue with instant prompt and gcloud prompt element

### ISSUE THREAD

**Issue by notrev** [romkatv/powerlevel10k#1328]
I have just recently installed p10k and haven´t made any changes to the default configurations yet. I enabled instant prompt and whenever I start a new instance of `zsh` I get a warning saying: `[WARNING]: Console output during zsh initialization detected.`. The output is the one below:

```sh
-- console output produced during zsh initialization follows --

ERROR: (gcloud.config.configurations.describe) unrecognized arguments: --filter=is_active:true (did you mean '--flatten'?)

To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
```

If I disable `gcloud` prompt element, the warning is gone. What could be a solution to keep `gcloud` prompt element and prevent it from printing this warning?

Using:
- ubuntu 20.04
- zsh: 5.8
- p10k: commit `af86b53047ea6d6866dc5dae83eb219e691b9c76`
- google-cloud-sdk: 333.0.0

**Comment by romkatv** [comment]
Seems related to #1324. CC @ramonlucas

**Comment by notrev** [comment]
There is no `--filter` option in the reference for the `gcloud config configure describe` command (https://cloud.google.com/sdk/gcloud/reference/config/configurations/describe)

**Comment by TYsewyn** [comment]
This PR broke `gcloud` prompt segment. See #1342.
