### ISSUE TITLE
Implement nordvpn prompt segment

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#133]
See https://github.com/Powerlevel9k/powerlevel9k/issues/306#issuecomment-514831640 for the idea by @zaneselvans.

`nordvpn` tool is fairly slow but there must be a way to do the same thing faster.

**Comment by romkatv** [comment]
This is done. The new 'nordvpn' segment has four states.

`MISSING`: nordvpn is not installed. By default the segment is not shown in this state. Override `POWERLEVEL9K_NORDVPN_MISSING_CONTENT_EXPANSION` and/or `POWERLEVEL9K_NORDVPN_MISSING_VISUAL_IDENTIFIER_EXPANSION` to make the segment visible.

`CONNECTED`: nordvpn is connected. By default shows `LOCK_ICON` as icon and country code as content. In addition, the following variables are set for the use by `POWERLEVEL9K_NORDVPN_CONNECTED_CONTENT_EXPANSION` and `POWERLEVEL9K_NORDVPN_CONNECTED_VISUAL_IDENTIFIER_EXPANSION`: `P9K_NORDVPN_PROTOCOL`, `P9K_NORDVPN_IP_ADDRESS`, `P9K_NORDVPN_SERVER`, `P9K_NORDVPN_COUNTRY`, `P9K_NORDVPN_CITY` and `P9K_NORDVPN_STATUS` (always "Connected"). These correspond to the output lines of `nordvpn status`.

`DISCONNECTED`: nordvpn is disconnected. By default shows `LOCK_ICON` as icon and `FAIL_ICON` as content. `P9K_NORDVPN_STATUS` is set to "Disconnected".

`OTHER`: nordvpn is in status other than "Connected" or "Disconnected". I'm not sure this is possible. By default shows `LOCK_ICON` as icon and `FAIL_ICON` as content. `P9K_NORDVPN_STATUS` is set to the actual status (neither empty, "Connected" nor "Disconnected").

Needs more testing.

**Comment by zaneselvans** [comment]
There's at least one other status called "Connecting" which it can spend a little time in, especially if the network connection is slow, or it's trying to connect when a machine wakes from sleep on a different WiFi network.

**Comment by romkatv** [comment]
@zaneselvans Thanks. I've also managed to catch "Disconnecting" state (in which NordVPN has stuck until I typed `nordvpn connect`).

I've added `CONNECTING` and `DISCONNECTING` states, removed `OTHER` and wrote documentation with customization examples: https://github.com/romkatv/powerlevel10k/blob/cef049e0de310c0ba00eed5d21f7678d105db3d2/internal/p10k.zsh#L2989-L3028.

Could you check if it works for you? If you are using Powerlevel9k, the following commands will replace your custom nordvpn segment with the builtin and load Powerlevel10k.

```zsh
git clone --depth 1 https://github.com/romkatv/powerlevel10k.git /tmp/powerlevel10k
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(${(@)POWERLEVEL9K_LEFT_PROMPT_ELEMENTS:/*nordvpn*/nordvpn})
source /tmp/powerlevel10k/powerlevel10k.zsh-theme
```

Other than the style of nordvpn segment the appearance of your prompt will stay unchanged because p10k is backward compatible with p9k configuration options. Your prompt will become much faster though. The only thing that can slow p10k down is custom prompt segments.
