### ISSUE TITLE
Working Dir not showing?

### ISSUE THREAD

**Issue by momoblydblk** [romkatv/powerlevel10k#1333]
![image](https://user-images.githubusercontent.com/21081757/113038765-74dc9800-91c9-11eb-8ba0-7c0367e70e12.png)
Like this, the dir isn't showing.
How can I add it to the prompt?

Thanks

**Comment by romkatv** [comment]
Your current dir is `~`. It is there, just hard to see with the colors you’ve chosen for your terminal. Change the terminal color scheme to something decent and it’ll be easier to see. Or run `p10k configure` and pick Lean style with 256 colors. It looks the same regardless of the terminal settings.

**Comment by momoblydblk** [comment]
> 
> 
> Your current dir is `~`. It is there, just hard to see with the colors you’ve chosen for your terminal. Change the terminal color scheme to something decent and it’ll be easier to see. Or run `p10k configure` and pick Lean style with 256 colors. It looks the same regardless of the terminal settings.

It is not letting me choose my Lean style. :  (

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
