### ISSUE TITLE
p10k Shows "~_p9k__cwd" For Command "dirs -v"

### ISSUE THREAD

**Issue by bigapple10027** [romkatv/powerlevel10k#1334]
Hi,

I'm running into issues when using the `dirs -v` command and here is a list of sample output I got:
```
0       ~_p9k__cwd
1       ~_p9k__cwd/build/test
2       ~_p9k__cwd/build
3       ~_p9k__cwd/tst
4       ~_p9k__cwd/src
```

**Environment**:  RHEL,   ZSH 5.8,   Tmux 2.8, Oh-my-zsh (Updated on the beginning of March)

It seems the variable `_p9k__cwd` is not expanded correctly? But I'm not sure what is broken and how to fix this. I like powerlevel10k a lot and use it all the time. I had no problem running it on the iTerm on my Mac, but is running into issues when running it on RHEL. Could somebody help with this issue? Thanks!

**Comment by bigapple10027** [comment]
Problem fixed! This is amazing! Do you mind explaining a bit on what's happening? I googled a bit on what is AUTO_NAME_DIRS option for ZSH, but didn't really get what it does. http://zsh.sourceforge.net/Doc/Release/Options.html

**Comment by romkatv** [comment]
It does what you observed. It’s bad option, so don’t set it.

**Comment by bigapple10027** [comment]
@romkatv Got it. Thank you!
