### ISSUE TITLE
adding push remote name and git submodule count to prompt

### ISSUE THREAD

**Issue by derrgill** [romkatv/powerlevel10k#1335]
I've just started using powerlevel10k for the first time, and I was trying to get a crude implementation of this working in my `.p10k.zsh` as follows:
```zsh
    if [[ -n $VCS_STATUS_PUSH_REMOTE_NAME
        ]]; then
      local premn=${(V)VCS_STATUS_PUSH_REMOTE_NAME}
      res+="${meta}|${clean}${premn}"
    fi

    local git_submodule_count="$(git config --file .gitmodules --get-regexp path | wc -l)"
    res+="${meta}▪${clean}${git_submodule_count}"
```

![p10k-git-prompt-in-progress](https://user-images.githubusercontent.com/7062385/113152625-4f20b480-9204-11eb-8ee0-ec7f88873ab6.png)

So far the submodule count works, but showing the remote name does not work. From reading the comments in the file, my understanding was that `VCS_STATUS_PUSH_REMOTE_NAME` is set in the gitstatus plugin, so I tried to use that. Am I doing it wrong?

**Comment by romkatv** [comment]
You can see all VCS parameters with this command:

```zsh
typeset -pm 'VCS_STATUS_*'
```

> `local git_submodule_count="$(git config --file .gitmodules --get-regexp path | wc -l)"`

Be careful. Forks can dramatically slow down your prompt.

**Comment by derrgill** [comment]
Thanks, now I found the correct remote parameter name.

Is it possible a submodule count paramater might ever be included in a future version of the plugin and theme?

**Comment by romkatv** [comment]
> Thanks, now I found the correct remote parameter name.

Good.

> Is it possible a submodule count parameter might ever be included in a future version of the plugin and theme?

Not impossible but very unlikely.

**Comment by derrgill** [comment]
Thanks again, powerlevel10k is awesome!
