### ISSUE TITLE
Glyphs not shown in URXVT

### ISSUE THREAD

**Issue by habsfanongit** [romkatv/powerlevel10k#1336]
Hi,
System:
Arch Linux 
Desktop Manager:None
Windows Manager:i3

I am not sure what am doing wrong here but regardless of what I do, I can never get the powerline glyphs to show properly in URXVT while termite is showing them without any problems.
I can see the font is applied even when I start urxvt using `urxvt -fn 'xft:MesloLG S NF:autohint=true:size=10'`
strace using `strace urxvt -fn "MesloLG S NF:autohint=true:size=10" 2>&1 | grep '/usr/share/fonts/'` and `strace urxvt -fn "MesloLG S NF:autohint=true:size=10" 2>&1 | grep '~/.local/share/fonts/'` return nothing even though I can see the font file. I ran xrdb -m ~/.Xresources after every update 
urxvt config 

`
! ******************
! urxvt config
! ******************

URxvt.utf8: true
URxvt.intensityStyles:  true
URxvt.saveLines:        8192

URxvt*scrollTtyOutput:    false
URxvt*scrollWithBuffer:   true
URxvt*scrollTtyKeypress:  true
URxvt.scrollBar:          false
URxvt.internalBorder:     25
URxvt.cursorBlink:        false
URxvt.cursorUnderline:    true
! URxvt.scrollBar: false
! URxvt.scrollBar_right: false

Xft.dpi:        128
Xft.antialias:  true
Xft.rgba:       rgb
Xft.hinting:    true
Xft.hintstyle:  hintslight

! Disable Perl extension
! If you do not use the Perl extension features, you can improve the security
! and speed by disabling Perl extensions completely. 
!URxvt.perl-ext:
!URxvt.perl-ext-common:

! -- Fonts -- !
URxvt*font: xft:MesloLG S NF:autohint=true:size=10
URxvt*letterSpace: -1

! special
*.foreground:   #d8dee9
*.background:   #1d1f21
*.cursorColor:  #d8dee9

! black
*.color0:       #2d2d2d
*.color8:       #444444

! red
*.color1:       #ed0b0b
*.color9:       #b55454

! green
*.color2:       #40a62f
*.color10:      #78a670

! yellow
*.color3:       #f2e635
*.color11:      #faf380

! blue
*.color4:       #327bd1
*.color12:      #68a7d4

! magenta
*.color5:       #b30ad0
*.color13:      #c583d0

! cyan
*.color6:       #32d0fc
*.color14:      #8adaf1

! white
*.color7:       #555555
*.color15:      #e0e3e7

! *****************
! Copy and Paste 
! *****************

! Disable ISO 14755 unicode input so we can use Ctrl-Shift bindings
URxvt.iso14755:        false
URxvt.iso14755_52:     false

! Disable Ctrl-Alt-c & Ctrl-Alt-v bindings (optional)
URxvt.keysym.C-M-c:    builtin-string:
URxvt.keysym.C-M-v:    builtin-string:

! Bind Ctrl-Shift-c & Ctrl-Shift-v to copy and paste

URxvt.keysym.C-S-0x43: eval:selection_to_clipboard
URxvt.keysym.C-S-0x56: eval:paste_clipboard

! ***********End Copy and paste*******

! ******************
! /urxvt config
! ******************
`
![urxvt](https://user-images.githubusercontent.com/21362322/113304605-3251b300-92d0-11eb-883e-6680da8247dd.png)

I would appreciate any help.
Thanks

**Comment by romkatv** [comment]
This issue is not specific to powerlevel10k or to zsh. I don’t rxvt myself, so unable to help. Sorry.
