### ISSUE TITLE
[Question] Can't get p10k-lean theme to correctly display prompt char in 'vivis' mode

### ISSUE THREAD

**Issue by Azumgi** [romkatv/powerlevel10k#134]
I tried to install https://github.com/b4b4r07/zsh-vimode-visual in several different ways. The plugin itself works as intended, but when I enter visual mode from normal mode, the prompt character changes to
```bash
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
```
instead of
```bash
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='Ⅴ'
```

![GIF example](https://user-images.githubusercontent.com/35058624/61967961-6b0b9600-afdf-11e9-8294-6f2293f6560a.gif)

Perhaps I'm doing something wrong? Or is it a bug in p10k? I'm using pure 'lean' theme without any tinkering.

**Comment by romkatv** [comment]
I've never heard of this plugin. Is it better than the standard visual mode that you access through the same shortcuts (`v` and `V` while in vi command mode)?

From the docs:

> Zsh Line Editer has two vi-like editing mode (viins, vicmd), but Vim has three or more major editing mode such as insert, command, visual and so on.

ZLE also has regular visual mode and line visual mode.

> Let's implement visual mode in Zsh Line Editer.

Hm...

My guess is that this is an old plugin that predates the addition of visual mode to ZLE. I haven't tried to verify this.

I'd suggest removing this plugin and seeing if the builtin functionality is sufficient. Either way, however, I've added support for this plugin to p10k so that it will show `Ⅴ` when you are using it.

**Comment by Azumgi** [comment]
I've got tricked by Oh-My-Zsh's vi-mode plugin that had `v` [bound](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/vi-mode/vi-mode.plugin.zsh#L29) for a different thing. When I tried to search some info about the visual mode in Zsh, `zsh-vimode-visual` plugin was the first suggestion in my search results list. After seeing it had a relatively recent commit, plenty of stars, mentioning that zsh does not support visual mode out of the box, and keyword `vivis` in Zsh context (which I could find only in the plugin itself and in p9k/p10k) I just assumed this it what everyone uses. Thanks for pointing out that zsh has the native visual mode support and for uhh.. adding support for that plugin (I'm so embarassed to be the cause of this😅). Now I'm just using `bindkey -v` and everything works perfectly.

**Comment by romkatv** [comment]
No worries at all. Thanks to your report p10k now supports that plugin.

> I've got tricked by Oh-My-Zsh's vi-mode plugin that had v bound for a different thing.

Oh-My-Zsh has a lot of harmful plugins hiding under innocuous names. For example, if you've enabled `git-prompt` or `kube-ps1`, you  need to turn them off. They do nothing except making your prompt slow.

`common-aliases` is a super dangerous plugin. If you have it enabled, try running this code:

```zsh
echo H
[[ 'H' == H ]]
```

The first command will print an empty line (normally it prints `H`), the second will print an error saying `zsh: parse error: condition expected: 'H'` (normally it does nothing).

You also need to define `DISABLE_MAGIC_FUNCTIONS=true`. It's likely already in your config but it's commented out. This will make pasting commands into your prompt fast again and you won't lose anything.

If you are using zsh-syntax-highlighting (one of the very few must have plugins), define `ZSH_AUTOSUGGEST_MANUAL_REBIND=1` to make your prompt faster. Once again, you won't lose anything.

**Comment by Azumgi** [comment]
These are very helpful tips that I'll be using in the future. Especially the one regarding zsh-syntax-highlighting. Thank you very much! I'm also examining your `.zshrc`. So many useful things in there.

**Comment by romkatv** [comment]
There is a lot of weird stuff in my dotfiles but some things are generally useful. I can highly recommend my history setup. See https://www.reddit.com/r/zsh/comments/bsa224/how_to_setup_a_better_history/eon23cl/.

**Comment by Azumgi** [comment]
Thanks! Will take a look there as well :)
