### ISSUE TITLE
Pop!_OS custom OS icon

### ISSUE THREAD

**Issue by nourkagha** [romkatv/powerlevel10k#1341]
Hello,

I'm trying to get a Pop!_OS icon added as a custom OS icon in my prompt. I found out that it's not included in the font, so I went looking for a glyph and found this: https://github.com/lukas-w/font-logos

I installed the font (by installing the .ttf file), called `font-logos`, but I'm wondering how to add the Pop icon to my zsh.

I have changed this line to the unicode value of it, `F12B`:

```
# Custom icon.
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF12B'
```
However, this is what it looks like in my prompt: 
![image](https://user-images.githubusercontent.com/50773468/113488658-1c0e4780-94c8-11eb-82bb-81a0435d455f.png)

Any help would be greatly appreciated :D

**Comment by romkatv** [comment]
What you did is correct. If this doesn’t print the right icon, fix the Unicode value or the font.

**Comment by nourkagha** [comment]
Thanks!

How would I go about doing this? I'm not very experienced in working with fonts. Should I be looking for a different unicode value somehow or should I add the font somewhere?

**Comment by nourkagha** [comment]
Here is what it shows up as:
![image](https://user-images.githubusercontent.com/50773468/113488989-24678200-94ca-11eb-982c-d449a669805d.png)

However, changing to another font like Liberation Serif, shows this for the unicode value `f12b`:

![image](https://user-images.githubusercontent.com/50773468/113489022-4e20a900-94ca-11eb-92d8-8a7dedb4f28e.png)

**Comment by romkatv** [comment]
You need to configure your terminal to use the font that has the logo.

**Comment by nourkagha** [comment]
Since this font only contains the logos alone, it seems I would have to add and patch them to an existing font like `MesloLGS NF`.

Thanks for the help!

**Comment by romkatv** [comment]
If this font only contains the logo, you either need to copy those glyphs into another font (this is usually called pasting a font) or set up a fallback for these glyphs. Neither of these are specific to powerlevel10k or to zsh.
