### ISSUE TITLE
Weird offsetting in VSCode terminal

### ISSUE THREAD

**Issue by aronchick** [romkatv/powerlevel10k#1343]
I'm getting a weird font issue on VSCode - here's what the integrated terminal looks like:

![image](https://user-images.githubusercontent.com/51317/113516766-f5382b80-9530-11eb-83ec-6be5d3123278.png)

And here's what it looks like in iTerm:

![image](https://user-images.githubusercontent.com/51317/113516772-01bc8400-9531-11eb-9251-0f7f6b26e06c.png)

It's JUST the line endings that are broken - and the font is installed (otherwise, wouldn't iTerm be broken?)

Here's my VSCode settings:
```
    "terminal.integrated.fontFamily": "MesloLGS NF",
    "terminal.integrated.fontSize": 12,
```

Anyone seen this?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by aronchick** [comment]
Thank you for everything you do! The weirdness to me is the right fonts are all installed (otherwise it wouldn't render in iTerm), but not in VSCode.

Wish there was a way to detect it during config so it wouldn't bother you with this - i reran p10k config in VSCode and everything looked right. Oh well.
