### ISSUE TITLE
MULTILINE_FIRST_PROMPT_GAP and LEFT_PROMPT_LAST_SEGMENT

### ISSUE THREAD

**Issue by migmolrod** [romkatv/powerlevel10k#1346]
I have a very small issue when I manually set `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND` to a custom color. And it's that `LEFT_PROMPT_LAST_SEGMENT`'s background is not changed and I can't find the option to do so, breaking homogeneity.

Here is a screenshot of the issue:
![screenshot](https://i.imgur.com/17Q7Lie.png)

Is there a way to change this? RIght now in my case it's taking the default background color from my terminal (eg, if I put a blue background, those little gaps are blue as well)

![screenshot](https://i.imgur.com/wFAbHc8.png)

And just in case it helps, this is my P10K configuration file:
[.p10k.zsh](https://gist.github.com/migmolrod/f6c573b460f86e1673ac571ae635fa95)

**Comment by romkatv** [comment]
This is fixable. I don't have time to fix this though. I'll keep the issue open in case anyone wants to fix this.

**Comment by migmolrod** [comment]
Ok.
I could try to dive into p10k code to see uses of that `LEFT_PROMPT_LAST_SEGMENT` and see if I can fix it myself.
It would need to wait til at least next weekend, tho. I don't have too much time either.

**Comment by romkatv** [comment]
To clarify, I didn't mean to imply it would be a good use of your time or that I consider this a useful contribution. My advice is to not waste your time on this.

**Comment by migmolrod** [comment]
Ricing is not wasting time :V

**Comment by migmolrod** [comment]
For anyone interested on this, I have good news.

Back then, I ended up not using that kind of separators.
But I recently made a bit of work in my dotfiles and after a couple hours, I was able to achieve this. In a somewhat 'hacky' way, not too clean, I must admit.
For anyone interested, I just had to set these two variables in my p10krc file:
```zsh
  # The right end of left prompt.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='%K{8}'
  # The left end of right prompt.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%K{8}'
```
Where the number between curly braces is the same color used in `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND`.

The result is this:
![Imgur](https://i.imgur.com/3voXWR1.png)

For me, this can be considered closed.
