### ISSUE TITLE
Truncate Segments (e.g. shorten pipenv name length)

### ISSUE THREAD

**Issue by jchenVT** [romkatv/powerlevel10k#1347]
Hi! Really appreciate this project!
I was wondering if there is a way to truncate a segment such as the venv. For example pipenv generates a very long name for the virtualenv and it ends up taking up a big chunk of the prompt up.  (sorry I can't upload files from the work network). Is there a method that would allow truncating a specific segment?

**Comment by romkatv** [comment]
There is no built-in support for shortening the content of `virtualenv` segment. You can either implement a custom segment with shortening (search for `prompt_example` in `~/.p10k.zsh`) or do something with `POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION`.
