### ISSUE TITLE
The configuration wizard always runs

### ISSUE THREAD

**Issue by Azumix** [romkatv/powerlevel10k#1348]
Hello!

I was using powerlevel10k on Fedora 33 then 34 for a moment and all was good, however starting yesterday it runs automatically the configuration wizard every time I launch a new terminal. I checked my `.zshrc` file, it have the line to launch powerlevel10k and I have my .p10k configuration file so I don't understand why the configuration wizard always start. 

Any idea?
Thanks!

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by Azumix** [comment]
@romkatv didn't saw this passage of the README. It was an error in my `zshrc` file indeed, thanks for your reply!
