### ISSUE TITLE
Add region to AWS prompt

### ISSUE THREAD

**Issue by tikeyike** [romkatv/powerlevel10k#1349]
### Feature Request

As a person that has multiple AWS profiles that have different default regions, it would be nice if powerlevel10k could also include the region from the currently set profile to be displayed in the prompt out of the box.

Example below:

![image](https://user-images.githubusercontent.com/37505521/114165956-7ef05a80-9970-11eb-95e3-0622499b290a.png)

**Comment by romkatv** [comment]
Do you know how this information can be retrieved?

**Comment by tikeyike** [comment]
It would be coming from the `~/.aws/config` file.

The config file contains the following by default:
`[default]` This is the profile name
`region=us-west-2` This is the region for that profile
`output=json` and this is the output option for the aws cli

For reference, here is the link to the omz aws plugin: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/aws
Also here is the link to the AWS doc for the cli configuration file: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

I assume you would need a wait to set the both the profile name and region as environment variables. I believe the aws plugin for zsh uses `asp` `$profile_name` or something similar. `asp` is short for "aws set profile".

Again, I'm not sure how easy this is to implement out of the box, but I figured it would be a "nice to have" feature.

Thanks for all the powerlevel goodness.
Cheers.

**Comment by romkatv** [comment]
Thanks for the info.

This requires more work than I can afford. I'll leave the issue open but the chances of my ever working on it are very low.

**Comment by tikeyike** [comment]
Thinking about it, its probably easier just to rename the profiles in the config file and include the region in the profile name - no coding changes required. I'm happy for you to close this issue.

Thanks 🙂

**Comment by romkatv** [comment]
Sounds like a clever and practical workaround. Closing.
