### ISSUE TITLE
Disable vcs_info for specific directories

### ISSUE THREAD

**Issue by rahuliyer95** [romkatv/powerlevel10k#135]
Hi, I am new to this plugin and would like to disable the vcs info for specific directories. I have a very large repository and the prompt slows down when in that directory. I did some searching and bumped into `zstyle ':vcs_info:*' disable-patterns "${(b)HOME}/repository(|/*)"`, but this doesn't seem to disable the info segment when I cd into that directory. Any other ways to achieve this?

Thanks! 🙂

**Comment by romkatv** [comment]
> I have a very large repository and the prompt slows down when in that directory.

This is interesting. I'll need a bit more info to understand what's going on. Please do the following.

1. Pull the latest version of Powerlevel10k.
2. `cd` into the large repo where prompt is slow.
3. Type `GITSTATUS_LOG_LEVEL=DEBUG zsh`.
4. Wait for prompt to fully load so that it displays vcs status.
5. Hit `<enter>` and again wait for prompt to fully load.
6. Make a screenshot of your prompt. You can drag-and-drop images into the comment text box on GitHub.
7. Type the following command and post its output.

```zsh
(
uname -a
typeset -pm '(POWERLEVEL9K_*|VCS_STATUS_*|ZSH_VERSION)'
cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K
)
```

If you need to censor anything from the output, please tell me what you've changed/removed.

8. Type `exit` to close the temporary `zsh` instance.

**Comment by rahuliyer95** [comment]
Here is the information you requested. I have blacked out the hostname and the actual filenames in the debug logs. The prompt takes time to update and uses a lot of CPU (I guess thrashing is happening not sure). The output is also very huge 😅
<img width="1122" alt="powerlevel10k-debug" src="https://user-images.githubusercontent.com/4255590/62012393-69a2b080-b13a-11e9-8280-6a51755a0c5f.png">
[output.txt.zip](https://github.com/romkatv/powerlevel10k/files/3439539/output.txt.zip)

**Comment by romkatv** [comment]
I appreciate the level of professionalism you've displayed in your reply by censoring all personal information and yet leaving all technical details from which I could figure out what's going on. I realize this was time consuming but this effort wasn't in vain.

It seems like `git` on your system was built with `NO_NSEC=YesPlease` flag or similar which causes gitstatus to mistakenly believe that files have changes when they really haven't. I've pushed a fix for this right now. Please `git pull` powerlevel10k and `cd` into that repository again. If everything works as planned, your prompt should become fast (it'll still be slow-ish on the first `cd` into the repo but after that it should be very fast). Let me know how it goes.

**Comment by rahuliyer95** [comment]
Yes, it's way faster now. Thanks for the quick fix 🙂

**Comment by romkatv** [comment]
> Yes, it's way faster now. Thanks for the quick fix :slightly_smiling_face: 

Thanks for the confirmation!

> On an unrelated note do you know a fast git completion plugin?

Nope.

>  The checkout completion seems to be very slow on the ones I find online.

Same for me, so I avoid using it. As far as I know, there is no good reason for this slowness. There is very little computation necessary to complete `checkout`. It's likely possible to fix this if you really want to.

P.S.

I took a peek at your dotfiles and noticed that your configuration options are compatible with p9k. p10k has many great features that p9k doesn't and some of them might be useful to you. For example, counters for staged/unstaged/untracked or [great directory truncation](https://asciinema.org/a/258376). To get a taste, run `p9k_configure`. Details at https://www.reddit.com/r/zsh/comments/ciziab/powerlevel10k_configuration_wizard/.

P.P.S.

If the experience with your large repo is still underwhelming, you can define `POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=100000`. This will disable dirty scan for repos with over 100k files in the index (your repo is 3x as large). You'll still get branch name, ahead/behind arrows, the number of staged changes and stashes, but you'll lose unstaged and untracked indicators. You can also style such repos differently (e.g., indicate with a special color or an icon that a repo is over the limit). FWIW, on Linux a 300k repository is no problem at all, with prompt latency being unnoticeable. It might be slower on macOS as I don't have a native macOS machine and hence cannot do platform-specific optimizations for it.
