### ISSUE TITLE
Symbols not displaying correctly after running `cd`

### ISSUE THREAD

**Issue by OliverFM** [romkatv/powerlevel10k#1350]
I have installed the Meslo fonts & can see all the symbols in the config, however when I run `cd` I get symbols that are incorrectly displayed. This is running on ubuntu 18.04 with the default terminal.

![Screenshot from 2021-04-09 11-41-18](https://user-images.githubusercontent.com/16237233/114168797-a58aa300-9928-11eb-8a00-e62cb862554b.png)

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k?

**Comment by OliverFM** [comment]
the problem persists -- so clearly not a p10k thing. Sorry about that.
This must be related to changes I made at the same time

**Comment by romkatv** [comment]
The problem is likely caused by incorrect value of `TERM`. If your zshrc sets `TERM`, remove that line. You should never override the value of `TERM` that is set by your terminal.

**Comment by OliverFM** [comment]
Thanks that solved the problem -- I had been doing that. However when I remove that I cannot get colours in tmux on a remote host in `p10k` -- setting `export TERM="screen-256color` had resolved that issue.
Any suggestions on fixing that?

**Comment by romkatv** [comment]
The solution for tmux is to add this to `~/.tmux.conf`:

```text
set -g default-terminal "screen-256color"
```

Do not set `TERM` manually anywhere.

**Comment by OliverFM** [comment]
Thanks so much -- this has been really helpful!
