### ISSUE TITLE
command not found: prompt_segment

### ISSUE THREAD

**Issue by NIL-zhuang** [romkatv/powerlevel10k#1351]
Hello, I'm using zinit and powerlevel10k on arch linux, I want to shorten my work dir description to 2 so I added the following code to my .zshrc
```
prompt_dir() {
   prompt_segment blue black '%2~'
}
```
But it turns out to show `command not found: prompt_segment`
I've attached my .zshrc here.
Thank you for your help.
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/6289404/zshrc.txt)

**Comment by romkatv** [comment]
Do the following:

1. Remove this line from `~/.zshrc`:
   ```zsh
   POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
   ```
2. Remove this line from `~/.zshrc`:
   ```zsh
   source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
   ```
3. I don't see `prompt_dir` function in your `~/.zshrc` but if you have it, remove it.
4. Open `~/.p10k.zsh`.
5. Search for `POWERLEVEL9K_SHORTEN_STRATEGY` and change its value to `truncate_to_last`.
6. Search for `POWERLEVEL9K_SHORTEN_DIR_LENGTH` and change its value to `2`.
7. Restart zsh with `exec zsh`.

**Comment by NIL-zhuang** [comment]
Thank you, it fits me great
