### ISSUE TITLE
kubecontext permanently shown for "show on command" when kubecontext class name contains a number

### ISSUE THREAD

**Issue by ajaegle** [romkatv/powerlevel10k#1353]
First of all, I'm super stoked about the `show on command` feature and the styling options for kubecontext based on pattern matching. So I immediately created a subclass for my playground `k3d` clusters to easily spot if I'm on dev, prod or my local playgrounds. 

The classes are applied correctly but I noticed the behaviour that for my `k3d` clusters the kubecontext is displayed independently of the active command, even with no single character typed, the context is shown. This is only true for the one class mapping my k3d clusters. I tried different things, switching order, renaming my pattern and my kubecontexts but the result was the same.

Only when I renamed the `class` that is also used for the variables defining the style, the issue was gone. So I'm guessing that the issue comes with the number used in my class name `K3D` compared to `DEV`, `TEST` or `PROD`. 

This (shortened) setup causes an issue when activating a context matching the pattern:

```
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
      '*dev*'   DEV
      '*k3d*'   K3D
      '*'       DEFAULT)
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=7
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=1

  typeset -g POWERLEVEL9K_KUBECONTEXT_DEV_FOREGROUND=0
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEV_BACKGROUND=35

  typeset -g POWERLEVEL9K_KUBECONTEXT_K3D_FOREGROUND=0
  typeset -g POWERLEVEL9K_KUBECONTEXT_K3D_BACKGROUND=33
```

This one works as expected:

```
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
      '*dev*'   DEV
      '*k3d*'   KTHREED
      '*'       DEFAULT)
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=7
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=1

  typeset -g POWERLEVEL9K_KUBECONTEXT_DEV_FOREGROUND=0
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEV_BACKGROUND=35

  typeset -g POWERLEVEL9K_KUBECONTEXT_KTHREED_FOREGROUND=0
  typeset -g POWERLEVEL9K_KUBECONTEXT_KTHREED_BACKGROUND=33
```

I cross-checked by renaming the class again to `KTHRE44ED` which resulted in the same, permanent displaying of the kubecontext. Maybe that's not a critical issue to be resolved but it might be worth finding the reason for this behaviour and adding some note to the corresponding docs in the p10k config file.

**Comment by romkatv** [comment]
Thanks for the report. Fixed.

**Comment by ajaegle** [comment]
Wow, that was fast! Thanks a lot!

**Comment by romkatv** [comment]
Have you tried it? Does it work?

**Comment by ajaegle** [comment]
Validated with b55ad16bdf747e7ff6a3c821d92ed942d4e3be7c and works as expected!

**Comment by romkatv** [comment]
Thanks for verifying!
