### ISSUE TITLE
[beginner] It seems that it has conflict with zsh-interactive-cd plugin

### ISSUE THREAD

**Issue by hhuangpen** [romkatv/powerlevel10k#1355]
I just installed this theme but when I add zsh-interactive-cd plugin to my plugin section and restart the shell, the plugin seems to not function. When I press tabs for autocompletion on semi-matched words, it keeps adding blank lines onto the terminal.  I wonder if it has anything to do with powerlevel10k.

**Comment by romkatv** [comment]
Please file a bug against zsh-interactive-cd.
