### ISSUE TITLE
arrows in the prompt

### ISSUE THREAD

**Issue by Arturo0911** [romkatv/powerlevel10k#1356]
Hi, how can i change the green arrows when i use any command in the zsh ?

Like this. 
 
![Screenshot at 2021-04-16 03-12-42](https://user-images.githubusercontent.com/47924579/114993762-bcb61d00-9e61-11eb-96c7-e93e647a425d.png)

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `❯` and replace it with something else.
