### ISSUE TITLE
How to upgrade ~/.p10k.zsh file?

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#1357]
I have used the Powerlevel10k theme a long time ago. When I updated Powerlevel10k, the new configuration has been more than the original ~/.p10.zsh file How can I upgrade it? Got the changed content? I don't want to reconfigure Power level10K, can you help?

**Comment by romkatv** [comment]
There is no need to upgrade `~/.p10k.zsh`. You can keep using your config with the newer version of powerlevel10k.

**Comment by 26chk** [comment]
> 无需升级`~/.p10k.zsh`。您可以继续将配置与powerlevel10k的较新版本一起使用。

![Uploading Screenshot_20210416_184210.jpg…]()


I compared the old ~/.p10k.zsh file with the new ~/.p10.zsh file, the new configuration cannot be added to the old ~/.p10k.zsh

left：Old ~/.p10k.zsh
right：New ~/.p10.zsh

**Comment by romkatv** [comment]
You can use the old or the new config. It's up to you.
