### ISSUE TITLE
Resizing terminal window has redraw issues

### ISSUE THREAD

**Issue by JamesYeoman** [romkatv/powerlevel10k#1358]
This is a bit of an edge case, but it's something that _could_ be an issue.

When maximising and unmaximising the terminal window a lot of times, the prompt got redrawn, but the previous prompt didn't get cleared.

![image](https://user-images.githubusercontent.com/21042602/115013495-08d88000-9ea9-11eb-9d0e-be7962d51e0f.png)

Here's a neofetch screenshot, in case the environment is useful for determining the source of the issue
![image](https://user-images.githubusercontent.com/21042602/115013641-36bdc480-9ea9-11eb-924d-e41ea8529f5c.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
