### ISSUE TITLE
kubecontext does not show emoji icons

### ISSUE THREAD

**Issue by mariusandersen** [romkatv/powerlevel10k#1361]
So my kubectl contexts have some emoji icons to make it easier for me to know what environment I am in:
![image](https://user-images.githubusercontent.com/3061094/115072538-05b8b080-9ef8-11eb-87e9-93e0621b81cc.png)

Currently these symbols show like this in the right prompt elements:
![image](https://user-images.githubusercontent.com/3061094/115073414-98594f80-9ef8-11eb-8b7f-62951920ad43.png)

I am using: 

- WSL2 Ubuntu
- Windows Terminal
- oh-my-zsh
- "fontFace": "MesloLGM NF"

Anyone know what can be wrong?

**Comment by romkatv** [comment]
Does the output of the following command contain emojis?

```zsh
kubectl config view -o=yaml
```

**Comment by mariusandersen** [comment]
no. It shows the same issue. for example
`current-context: "\U0001F9A2dev\U0001F9A2"`

I was previously using bash with kube-ps1 and there it worked fine:
![image](https://user-images.githubusercontent.com/3061094/115075589-980e8380-9efb-11eb-8048-6354b3043aad.png)

**Comment by romkatv** [comment]
> no. It shows the same issue. for example
> `current-context: "\U0001F9A2dev\U0001F9A2"`

How about the following command? Does *that one* contain emojis?

```zsh
kubectl config current-context
```

**Comment by mariusandersen** [comment]
> > no. It shows the same issue. for example
> > `current-context: "\U0001F9A2dev\U0001F9A2"`
> 
> How about the following command? Does _that one_ contain emojis?
> 
> ```shell
> kubectl config current-context
> ```

yes
![image](https://user-images.githubusercontent.com/3061094/115075956-2daa1300-9efc-11eb-8d35-635a8fc207e7.png)

**Comment by romkatv** [comment]
Please update powerlevel10k and restart zsh with `exec zsh`. Does that help?

**Comment by mariusandersen** [comment]
I updated it, verified the mentioned commit changes was in the p10k.zsh file, and restarted the terminal. Unfortunately still the same issue.

**Comment by romkatv** [comment]
Forgot to bust caches. Please update and try again.

**Comment by mariusandersen** [comment]
Amazing. It worked.

![image](https://user-images.githubusercontent.com/3061094/115078963-b88d0c80-9f00-11eb-84aa-6930e1bc2a27.png)

Thank you so much for the incredibly quick fix!

**Comment by romkatv** [comment]
Thanks for reporting the bug, providing additional info and verifying the fix!
