### ISSUE TITLE
[Feature Request] Is it possible to write the prompt several points larger than everything else

### ISSUE THREAD

**Issue by JamesYeoman** [romkatv/powerlevel10k#1363]
The purpose of this feature request is to be able to have the prompt large enough that the glyphs are comfortably visible (see the following image)
![image](https://user-images.githubusercontent.com/21042602/115225689-471eab00-a106-11eb-84ab-929d8d34e395.png)
while everything else (commands and command output) is at a more reasonable size (see the following image)
![image](https://user-images.githubusercontent.com/21042602/115225834-77664980-a106-11eb-9ba2-71ddb76d3f99.png)

Is there any ASCII codes that would enable this? Or are my dreams of an ultra-fancy-looking prompt just pipe-dreams?

EDIT:
For reference, here's a screenshot of neofetch using the first font size
![image](https://user-images.githubusercontent.com/21042602/115226451-29057a80-a107-11eb-8707-aa0a895d5050.png)

**Comment by romkatv** [comment]
I'm not sure what your screenshots are meant to show.

I'm not aware of any terminal emulator that can use more than one font (or more than one font size) at once. Everything in the terminal is comprised of glyphs from a single font.

**Comment by JamesYeoman** [comment]
The screenshots are all the same size window. They're meant to show the difference in screen realestate at the two font sizes. I was hoping there was an ascii code or something like that for font sizes.

**Comment by romkatv** [comment]
There are terminals that allow you to change the font size by writing special escapes codes to the TTY. The effect of these codes is the same as changing the font size through terminal settings. Either way, all glyphs in a terminal will always be the same size.
