### ISSUE TITLE
Can't change foreground color for directories

### ISSUE THREAD

**Issue by SylEleuth** [romkatv/powerlevel10k#1364]
In Termite and Konsole powerlevel10k takes color number 8 (from config of those terminals) and use it to color directories:
![Screenshot_20210420_152528](https://user-images.githubusercontent.com/33354262/115413073-cab2c780-a1ec-11eb-85c4-9fd3fac64b85.png)
As you can see that color is responding for cursor and hints.

Powerlevel10k config:
https://gist.github.com/SylEleuth/af5a1a6fcc4195858d372ef37c3a68e2

I'm stuck with this problem and I can't find a solution. I went trough config and changed everything I could but I think that I'm missing an option that should be there but it's not.

**Comment by romkatv** [comment]
In your screenshot "~" and "blender" at the end of the current directory are *anchors*. Anchors are rendered with the foreground color of `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND` (that's `0` in your config). In addition, if `POWERLEVEL9K_DIR_ANCHOR_BOLD` is set to `true` (it is, in your config), they are bolded. So you get this:

```zsh
print -P '%B%F{0}blender%f%b'
```

If you run this command, you should see "blender" printed in the same color as on your screenshot.

Some terminals have a setting that reads something like "use bright colors for bold". You have this setting enabled. What it means is that colors 0-7, when bolded, get printed as 8-15. What happens with other colors when they are bolded is anyone's guess. (I usually turn this option off. If I want colors 8-15, I'll use colors 8-15. I want bold to bold.)

Does this give you enough information to configure your prompt?

P.S.

Lean style might look better out of the box. Give it a try.

**Comment by SylEleuth** [comment]
Thank You kindly for explanation. That's what I was looking for.
