### ISSUE TITLE
taskwarrior: bad math expression: illegal character: ^[ 

### ISSUE THREAD

**Issue by steven-omaha** [romkatv/powerlevel10k#1365]
This is with
- zsh 5.8
- p10k 48ff2e8
- taskwarrior 2.5.3

Steps to reproduce
1. create new empty user called test, `chsh -s /usr/bin/zsh test`, `sudo su test`
2. `echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc`, then `p10k configure`
3. run `task` to create `.taskrc` and `~/.task`
4. run `echo "_forcecolor=1" >> .taskrc`  (in accordance with `man 5 taskrc`) 
5. `task add due:tomorrow something`
6. start a new zsh (which I did using `su test`)

result:
1. `_p9k_taskwarrior_init_data:29: bad math expression: illegal character: ^[` is printed after some taskwarrior commands, like `task start 1`
2. `${$((_p9k_on_expand()))+}${(e)_p9k_t[7]}` is entered in the command prompt (but not executed) when step 6 is first executed
3. on subsequent shell starts, p10k-instant-prompt sometimes complains about console output during zsh initialization

`typeset -pm 'POWERLEVEL*' > p10k.log`: [p10k.log](https://github.com/romkatv/powerlevel10k/files/6344743/p10k.log)

**Comment by romkatv** [comment]
Thanks for reporting. What's the output of the following command?

```zsh
command task +PENDING -OVERDUE list rc.verbose=nothing rc.report.list.labels= rc.report.list.columns=due.epoch | od -t x1 -An -v
```

**Comment by romkatv** [comment]
Oh, I see what's going on.

Do you know of a way to disable color for one invocation of that command? Basically, please try to find a way to invoke the following command and get uncolored output.

```zsh
# We need the output of this command but without colors.
command task +PENDING -OVERDUE list rc.verbose=nothing rc.report.list.labels= rc.report.list.columns=due.epoch
```

**Comment by steven-omaha** [comment]
This works for me:  (append `rc.color=0`)
```
command task +PENDING -OVERDUE list rc.verbose=nothing rc.report.list.labels= rc.report.list.columns=due.epoch rc.color=0
```

**Comment by romkatv** [comment]
Thanks! I don't use taskwarrior myself, so the info you've provided is super helpful.

Please update powerlevel10k and let me know if this fixes the issue for you.

**Comment by steven-omaha** [comment]
Sorry, I messed up the testing when drafting the response.  Bug is still there, but now I have it correct

When I have `_forcecolor=1` in `.taskrc`, then the command line must have *two* arguments to disable color output. So the command must end with `rc.color=0 rc._forcecolor=0`. Then output is monochrome, regardless of taskrc settings.

And thanks a lot for the super quick response! Definitely among the best report-to-fix times I have ever seen! :)

**Comment by romkatv** [comment]
Alright, added that flag too. Please update and try again.

**Comment by steven-omaha** [comment]
Yes, now fixed. Thanks!

**Comment by romkatv** [comment]
Thanks for verifying!
