### ISSUE TITLE
ls with enter does not work

### ISSUE THREAD

**Issue by mchikira** [romkatv/powerlevel10k#1366]
I have the following section in my .zshrc to excute a ls command when hitting enter without inputting any commands.

```
enter-ls () {
  if [[ $#BUFFER -eq 0 ]]; then
     echo ""
     ls
     zle redisplay
  else
     zle accept-line
  fi
}
zle -N enter-ls
bindkey '^M' enter-ls
```

It perfectly worked before installing powerlevel10k, but it doesn't after the installation. The output of the ls command is not shown.
Can you think of any reason and how to fix this?

I am using zsh 5.8 on Mac Catalina with powerlevel10k 1.14.6.

**Comment by romkatv** [comment]
Try replacing your code with this:

```zsh
function p10k-on-post-prompt() {
  typeset -g my_cmd=$PREBUFFER$BUFFER
}
function my_precmd() {
  if ! zle && [[ -z ${my_cmd-x}  ]]; then
    echo
    ls
  fi
  unset my_cmd
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd my_precmd
```

**Comment by mchikira** [comment]
Your code worked!
I learned a lot from your code. Thanks a lot!
