### ISSUE TITLE
Incorrect display in vscode

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#1368]
Greetings!
After a recent update to either vscode or p10k, there were problems in vscode terminal.
I'm not sure if it’s p10k, if not, I’ll make an issue for microsoft.
![image](https://user-images.githubusercontent.com/35394377/115845315-63358b80-a429-11eb-855f-2cb61d1d3e87.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by Mystic8b** [comment]
Changing the font size helps before restarting. Looks like vscode problem, thanks!
