### ISSUE TITLE
this happens when you split views in konsole

### ISSUE THREAD

**Issue by barfin** [romkatv/powerlevel10k#1369]
![image](https://user-images.githubusercontent.com/37030489/115930848-6703f500-a49f-11eb-880d-e709dc73304f.png)
feel free to close this issue if the bug is from zsh or kde itself because i'm not sure where to post it

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
