### ISSUE TITLE
Don't store .p10k file in $HOME by default

### ISSUE THREAD

**Issue by z0rc** [romkatv/powerlevel10k#137]
Please don't create or store dotfiles in user HOME by default. There are either [XDG Base Dir Spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) which honored by majority of applications, including the CLI only commands, or `ZDOTDIR`, which may be not set by default.

There is quite a bit community of people who work on liberating of HOME's root, making it primary a place for user files and documents, and not a place for applications to store configuration. https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by romkatv** [comment]
What should I replace `${ZDOTDIR:-$HOME}/.p10k.zsh` with?

**Comment by z0rc** [comment]
My personal preference would be `${XDG_CONFIG_HOME:-$HOME/.config}/p10k/config.zsh`. This is how `git`, `systemd`, `mc` and any other compliant application behave. You may add `ZDOTDIR` as higher priority to make it more coupled with ZSH configuration. Either approach works for me.

**Comment by romkatv** [comment]
Sure, I can do that. I don't think I've seen anyone store ZSH configuration in `$XDG_CONFIG_HOME` though. Is it a good practice?

Consider aliases:

```zsh
alias grep='grep --color`
```

Or bindings:

```zsh
bindkey '^E' edit-command-line
```

Normally people put these definitions directly in `~/.zshrc` but if there are many, it's not uncommon to factor them out to `aliases.zsh` and `bindings.zsh`.

Likewise for prompt configuration. If it's more than a few lines, it's a good idea to put it in a separate file instead of dumping everything in `~/.zshrc.

Is `$XDG_CONFIG_HOME` a good location for such files?

**Comment by romkatv** [comment]
I took a look at your config. You are defining `ZDOTDIR`, so the generated config file will end up in the right place, right? Or am I missing something?

If `ZDOTDIR`, I think this should be the place for the config file because it belongs with other zsh configuration files and is meant to be edited by humans.

If `ZDOTDIR` is not set but `XDG_CONFIG_HOME` is set, zsh config files are in `$HOME. Do you think it would better (and not confusing) if in this case p10k has placed prompt config file in '$XDG_CONFIG_HOME'?

**Comment by z0rc** [comment]
Logically I agree with your approach of following ZDOTDIR. My biggest concern isn't mine own configuration, but another dotfile in $HOME, that ends there by default for majority of users. Adoption of XDG base dir spec is rather slow and tolerating stuffing dotfiles in HOME isn't really helping with it.

Sometimes it's major PITA to make old application (like Zsh) for follow XDG Base Dir spec. But with new ones, it shouldn't be a problem.

From my point of view if Zsh plugin creates/uses own configuration files, it already graduated from being just plugin to full blown application, so you don't need to stick with ZDOTDIR anymore.

**Comment by romkatv** [comment]
> From my point of view if Zsh plugin creates/uses own configuration files, it already graduated from being just plugin to full blown application, so you don't need to stick with ZDOTDIR anymore.

p10k configuration wizard is creating a config that the user will own and edit. The wizard has several good curated configs that can be used as a base and gives the user the one they want. After that neither p10k nor the wizard attempt to read or modify the file.

I promise to start writing this config to `XDG_CONFIG_HOME` once ZSH starts reading its config files from `XDG_CONFIG_HOME`. Until then doing so would be confusing to the users. I'd rather accept the risk of annoying a few empty-home enthusiasts than confuse the masses. Given that the location of the file can be controlled with `ZDOTDIR` and that anyone is free to move the file wherever they like (p10k doesn't look for this file, it just needs configuration options to be set), I think this is a reasonable choice.

I realize this isn't what you are asking for. I'm sorry.

**Comment by mislam** [comment]
Despite of being called a "empty-home enthusiast" by the author, I would still advocate for respecting the XDG standards. A lot of modern CLI tools started using it instead of dumping on user's home directory. And I'm sure this simple compliance won't break the bank for @romkatv 😉

**Comment by ccjmne** [comment]
Just chiming in, as an empty-home enthusiast as well (aggravated by also doubling as a non-hidden file afficionado): I actually had the same train of thought as @romkatv: I feel like the Zsh business belongs in ZDOTDIR.

If anything, if you're of those that like their home barren, stumbling upon that pesky file probably can turn into a fantastic opportunity to learn about ZDOTDIR.
Well, spinning it like this is exaggerating, but still: a Zsh user who enjoys free real estate (get it? your home is free! [of junk]) probably would want to know about ZDOTDIR.

In any case, the second argument there is also pretty impeccable: this file is yours, owned by you, edited by you, read only when you specifically source it, from wherever you want... You could even inline it to your zshrc (good grief!).
The point boils down to: Powerlevel10k won't write to it, and won't even read it. You operate it 'cause it's more convenient to have these p10k entrails in their own space (read: file).

Maybe the flaw is in `p10k configure` not being too obvious about just creating some content that it means to wash its hands of, and goes the extra step of stashing it to a file and proposing to source it from your zshrc? But obviously, that's a very welcome boon to its adoption.
Well, also yeah, it's fair, maybe the default's default (after ZDOTDIR as the main default) should be `XDG_CONFIG_DIR/p10k`, before `$HOME/.config` as the last-resort default.

The colon-hyphen operator doesn't support hierarchies of defaults, though ;)

**Comment by romkatv** [comment]
> Well, also yeah, it's fair, maybe the default's default (after `ZDOTDIR` as the main default) should be `$XDG_CONFIG_HOME/p10k`, before `$HOME/.config` or `$HOME` as the last-resort default.

The most intuitive place for `.p10k.zsh`, when it is being created, is right next to `.zshrc`. If users configure their system to place `.zshrc` in their home directory, `.p10k.zsh` will go there, too.

Note that you can override the location of the generated file when invoking the wizard:

```zsh
POWERLEVEL9K_CONFIG_FILE=/path/to/p10k.zsh p10k configure
```

However, if you want to place `.p10k.zsh` outside of the home directory, you'll probably want to do the same with `.zshrc`, and thus should override `ZDOTDIR`.
