### ISSUE TITLE
Oh my zsh plugins

### ISSUE THREAD

**Issue by malde11** [romkatv/powerlevel10k#1371]
hi,
is it possible to use oh-my-zsh plugins, if i have installed powerlevel10k via homebrew?
Powerlevel10k is working, but i do not know where i can use some plugin.

thanks, malde

**Comment by romkatv** [comment]
You can use oh my zsh plugins with powerlevel10k the same way as you can use them without powerlevel10k.

**Comment by malde11** [comment]
yeah, but I have to install oh-my-zsh first right?

At the moment i have installed iterm2 and powerlevel10k with homebrew. So, i do not have oh-my-zsh.
And if I put this in the .zshrc nothing is working:

plugins=(laravel docker composer compleate git ruby)

**Comment by romkatv** [comment]
Powerlevel10k doesn’t change anything w.r.t. how you use oh my zsh plugins. The answer to the question “how to use oh my zsh plugins with powerlevel10k“ is the same as the answer to the question “how to use oh my zsh plugins”.
