### ISSUE TITLE
Truncate specific DIR

### ISSUE THREAD

**Issue by Alyetama** [romkatv/powerlevel10k#1372]
is there a way to truncate a specific directory (e.g., $WORK) if it's set as an environment variable to a shorter path?  For example, in _oh-my-bash_'s Powerline theme, this would replace `$WORK` (variable – e.g., /work/lab/member) to `WORK` (bare string) in the DIR segment:
` "$(pwd | sed "s|^${WORK}|WORK|")|${CWD_THEME_PROMPT_COLOR}"`

Before:
`/work/lab/member/my_project`

After (desired):
`WORK/my_project`

is there a way to do the same with powerlevel10k?

**Comment by romkatv** [comment]
Add this to `~/.zshrc`:

```zsh
hash -d WORK=/work/lab/member/my_project
```

This will establish a bidirectional mapping between `~WORK` and `/work/lab/member/my_project` which works just like the mapping between `~` and `$HOME`. You can type `cd ~WORK/my_project` and it'll just work. Tab completion will work, too (`cd ~WPRL/<TAB>`). Prompt will look nicer, etc.

**Comment by Alyetama** [comment]
Thank you very much!  This is exactly what I needed!
