### ISSUE TITLE
Question: Escape codes first run in emacs term-mode

### ISSUE THREAD

**Issue by torgeir** [romkatv/powerlevel10k#1373]
Forgive me if this is the wrong channel for this kind of questions, if so feel free to close this one.

I am suspecting that running powerlevel10k in emacs term-mode (on [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) on mac os big sur) is the cause of the following output of escape codes on every first invocation of the session. Besides that, things generally seem to be working fine, even the custom icons 👌 

<img src="https://p196.p4.n0.cdn.getcloudapp.com/items/X6ueQOQd/fb1dbc62-deb9-4b17-94be-0c2666728c53.jpg?source=viewer&v=2d619c04f81a10b8eff7256c3355a9c0">

Do you have any idea as to what might be causing this and how I might get rid of it?

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k but otherwise keep your zsh config unchanged?

What happens if you remove everything from your zsh configs except for powerlevel10k?

**Comment by torgeir** [comment]
Omg that's a derp if I ever saw one, I'll close this. I had a leftover pywall initialization hidden away in a nested rc-file.

**Comment by torgeir** [comment]
Thanks, I guess 😉 

<img src="https://p196.p4.n0.cdn.getcloudapp.com/items/YEuRWpv4/29f6866e-34ce-4e19-a014-c1079af78533.jpg?source=viewer&v=b29f0b9615ffb6cb94ba430ff13ff290">

**Comment by romkatv** [comment]
You are welcome.
