### ISSUE TITLE
Show kubernetes context when using make

### ISSUE THREAD

**Issue by evenme** [romkatv/powerlevel10k#1374]
We heavily use makefiles for our kubernetes structure (especially for helm charts) but when running make *, kubernetes context doesn't show on command, making me have to double check the context for every make I run. Is there a way to enable for make commands when inside specific [sub]folders for example (e.g kubernetes/helm-charts/application, every make running inside kubernetes would show the context)?

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k#why-some-prompt-segments-appear-and-disappear-as-im-typing

**Comment by evenme** [comment]
Adding make on POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND works but I only wanted if I'm inside somewhere kubernetes related (kube/kubernetes/k8s folder name for example). With terraform makefiles for example, I'd want to have the AWS profile, not kube context.

**Comment by romkatv** [comment]
> I only wanted if I'm inside somewhere kubernetes related

Please elaborate. Describe what you want such that it can be codified as an algorithm.
