### ISSUE TITLE
What might cause slow prompt update?

### ISSUE THREAD

**Issue by Asocia** [romkatv/powerlevel10k#1375]
When I press enter, I feel a slight delay. This delay is more visible when I spam enter. You can see it here:

[![asciicast](https://asciinema.org/a/Y5cHG2gqYraiqGElu0GaV3LS2.svg)](
  https://asciinema.org/a/Y5cHG2gqYraiqGElu0GaV3LS2)

In the above recording, I wasn't pressing enter while the last ~15 prompts are printing to the screen.

I don't see this delay in the recording at the [README page](https://github.com/romkatv/powerlevel10k#is-it-really-fast) so I think there is a problem with my configuration. 

I configured my prompt with `p10k configure` and didn't change too much thing at the `~/.p10k.zsh` (Just disabled some segments and added custom icons for git). So I don't understand what might be causing this. 

Here is a [link](https://github.com/Asocia/dotfiles/blob/master/.zshrc) to my  `~/.zshrc` and the below one is the same file without comments and aliases:

```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel10k/powerlevel10k"

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

plugins=(
  zsh-autosuggestions python pip last-working-dir history sudo command-not-found git extract zsh-syntax-highlighting docker docker-compose zsh-vi-mode z.lua
)


zstyle ':completion:*:*:git:*' script ~/.git-completion.bash
fpath=(~/.zsh $fpath)

ZVM_VI_INSERT_ESCAPE_BINDKEY=kj
ZVM_LAZY_KEYBINDINGS=false

source $ZSH/oh-my-zsh.sh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=32'

export LANG=en_US.UTF-8
export PATH="/snap/bin:$PATH"


[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
[[ -n $TMUX ]] || POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=(battery time)

export VISUAL=vim
export EDITOR="$VISUAL"
export PYTHONBREAKPOINT=ipdb.set_trace
export ZSH_AUTOSUGGEST_USE_ASYNC=true

function my_bindings() {
    # easy bindings instead of ctrl + arrow keys
    bindkey '^j' backward-word
    bindkey '^f' forward-word
    bindkey '^g' autosuggest-accept
    bindkey "\e\e" sudo-command-line
}


zvm_after_init_commands+=('[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh')
zvm_after_init_commands+=(my_bindings)
ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
ZVM_INSERT_MODE_CURSOR=$ZVM_CURSOR_BLOCK

export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -l -g ""'
export FZF_DEFAULT_OPTS='--bind change:top'

autoload -U compinit; compinit -y
```

**Comment by romkatv** [comment]
Try disabling all plugins.

**Comment by Asocia** [comment]
It's obviously better but the prompt still can't catch up. Last 6-7 prompts are printed after I stopped pressing enter.

**Comment by Asocia** [comment]
Here is the benchmark without plugins:
```
********************************************************************
                      Prompt Benchmark Results
********************************************************************
Warmup duration      8s
Benchmark duration   2.025s
Benchmarked prompts  29
Time per prompt      69.83ms  <-- prompt latency (lower is better)
********************************************************************
```

And with plugins:
```
********************************************************************
                      Prompt Benchmark Results
********************************************************************
Warmup duration      8s
Benchmark duration   2.110s
Benchmarked prompts  17
Time per prompt      124.09ms  <-- prompt latency (lower is better)
********************************************************************
```

**Comment by romkatv** [comment]
Try this:

1. Run: `POWERLEVEL9K_CONFIG_FILE=/tmp/p10k.zsh zsh -f`
2. Run: `source ~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme`
3. Choose any style you like.

Is it fast?

**Comment by Asocia** [comment]
Yes, this is `literally` instant.

**Comment by romkatv** [comment]
Then either you haven't disabled all plugins or you've a very different prompt config.

Try running this:

```zsh
mv ~/.p10k.zsh ~/.p10k.zsh.bak
mv ~/.zshrc ~/.zshrc.bak
mv /tmp/p10k.zsh ~/.p10k.zsh

cat >~/.zshrc <<\END
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
export ZSH=~/.oh-my-zsh
ZSH_THEME=powerlevel10k/powerlevel10k
plugins=()
source $ZSH/oh-my-zsh.sh
source ~/.p10k.zsh
END
```

Is it fast?

**Comment by romkatv** [comment]
Forgot to mention that you need to run `exec zsh` afterwards.

**Comment by Asocia** [comment]
Yes, this is also fast.

> Then either you haven't disabled all plugin
I have commented out `plugins=(...)` line.

> or you've a very different prompt config.

You can see my `~/.p10k.zsh` [here](https://github.com/Asocia/dotfiles). I didn't change too much thing as I said.

**Comment by romkatv** [comment]
> Yes, this is also fast.

That's good. Now you have two configs: `~/.zshrc` that is fast and `~/.zshrc.bak` that is slow. Try adding things from the latter to the former one by one until things get slow. This will tell you what's the culprit of this slowdown.

**Comment by Asocia** [comment]
Ok, this is great! Thanks for the help. I will try to dig this down and share the results.

**Comment by Asocia** [comment]
The line that was slowing down my terminal was this:

```zsh
eval "$(pyenv virtualenv-init -)"
```

And it is also reported  by other users:
 - https://github.com/pyenv/pyenv/issues/784
 - https://github.com/pyenv/pyenv-virtualenv/issues/259

I will close this issue when I am sure that everything works as expected.

**Comment by Asocia** [comment]
Everything is normal after deleting `eval "$(pyenv virtualenv-init -)"` from `~/.zshrc`. 

Thanks for your time!

**Comment by romkatv** [comment]
Thanks for posting the results of your findings.

**Comment by eddyg** [comment]
Thanks for pointing this out, @Asocia!

I have noticed this slowness as well (and just been living with it), and have this in my `.zshrc`:

```shell
eval "$(pyenv init - --no-rehash); $(pyenv virtualenv-init -)"
```

and `zhooks` shows that `pyenv-virtualenv` is adding a `precmd` hook:

```
❯ zhooks
...
precmd_functions:
_p9k_do_nothing
_pyenv_virtualenv_hook      <<<<<
_set-term-title-precmd
_zshz_precmd
_p9k_precmd
```

which even _looks_ like it would be slow:

```shell
❯ whence -f _pyenv_virtualenv_hook
_pyenv_virtualenv_hook () {
	local ret=$?
	if [ -n "$VIRTUAL_ENV" ]
	then
		eval "$(pyenv sh-activate --quiet || pyenv sh-deactivate --quiet || true)" || true
	else
		eval "$(pyenv sh-activate --quiet || true)" || true
	fi
	return $ret
}
```

I'm going to try adding this to my `.zshrc`, to make it a `chpwd` hook (which should be adequate for my auto-activation needs):

```shell
add-zsh-hook -D precmd _pyenv_virtualenv_hook
add-zsh-hook chpwd _pyenv_virtualenv_hook
```
