### ISSUE TITLE
Incorrect Python version in "virtualenv" prompt segment

### ISSUE THREAD

**Issue by eddyg** [romkatv/powerlevel10k#1378]
Hi Roman!

I seem to have run into a situation where the Python version shown in the **virtualenv** prompt segment doesn't match the _active_ Python version.

First, for some context, here's some relevant bits from my config:

```shell
❯ cd ~/git/qa
❯ () {
  emulate -L zsh
  typeset -pm 'ZSH_VERSION|*ELEMENTS|*PYENV*|*pyenv*|*PYTHON*|*VIRTUAL*ENV*'
  echo
  pyenv versions
  echo
  pyenv version-name
  pyenv version
  pyenv global
  echo
  python --version
}
typeset -g _POWERLEVEL9K_PYENV_BACKGROUND=243
export VIRTUAL_ENV=/Users/eddyg/.pyenv/versions/3.8.5/envs/qa
typeset -g POWERLEVEL9K_VIRTUALENV_SUFFIX=' '
typeset -g -i _POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=1
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=7
typeset -g -a POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status root_indicator command_execution_time time background_jobs virtualenv )
typeset -g -A _p9k__read_pyenv_like_version_file_cache=( )
typeset -g _POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=true
typeset -g _POWERLEVEL9K_VIRTUALENV_SUFFIX=' '
typeset -g -a _POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( ssh context dir git_dir vcs newline prompt_char )
typeset -g _POWERLEVEL9K_PYENV_PREFIX=' '
typeset -g POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${P9K_CONTENT}${${P9K_PYENV_PYTHON_VERSION:#$P9K_CONTENT}:+ %250F$P9K_PYENV_PYTHON_VERSION%f}'
typeset -g _POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${P9K_CONTENT}${${P9K_PYENV_PYTHON_VERSION:#$P9K_CONTENT}:+ %250F$P9K_PYENV_PYTHON_VERSION%f}'
export PYENV_SHELL=zsh
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=243
typeset -g ZSH_VERSION=5.8
typeset -g _POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER=''
export PIP_REQUIRE_VIRTUALENV=1
typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_VIRTUALENV_PREFIX=' '
typeset -g POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=''
typeset -g POWERLEVEL9K_PYENV_FOREGROUND=7
typeset -g POWERLEVEL9K_PYENV_SUFFIX=' '
export PYENV_VIRTUALENV_INIT=1
typeset -g _POWERLEVEL9K_VIRTUALENV_PREFIX=' '
export PYENV_VIRTUAL_ENV=/Users/eddyg/.pyenv/versions/3.8.5/envs/qa
typeset -g -a POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( ssh context dir git_dir vcs newline prompt_char )
typeset -g POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=false
typeset -g _POWERLEVEL9K_PYENV_FOREGROUND=7
typeset -g POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER=''
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
typeset -g POWERLEVEL9K_PYENV_PREFIX=' '
typeset -g -i _POWERLEVEL9K_PYENV_SHOW_SYSTEM=1
typeset -g -i _POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=0
typeset -g -a POWERLEVEL9K_PYENV_SOURCES=( shell local global )
typeset -g _POWERLEVEL9K_VIRTUALENV_FOREGROUND=7
typeset -g _POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES='virtualenv|venv|.venv|env'
typeset -g -a _POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status root_indicator command_execution_time time background_jobs virtualenv )
typeset -g POWERLEVEL9K_PYENV_BACKGROUND=243
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
typeset -g -i _POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=0
typeset -g _POWERLEVEL9K_VIRTUALENV_BACKGROUND=243
typeset -g _POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=''
typeset -g _POWERLEVEL9K_PYENV_SUFFIX=' '
typeset -g -a _POWERLEVEL9K_PYENV_SOURCES=( shell local global )

  system
  2.7.17
  2.7.17/envs/skynet
  3.8.5
  3.8.5/envs/qa
  3.8.7
  3.8.7/envs/dev
  3.8.9
  dev
* qa (set by /Users/eddyg/git/qa/.python-version)
  skynet

qa
qa (set by /Users/eddyg/git/qa/.python-version)
3.8.9

Python 3.8.5
```

But this results in a prompt that looks like this:
<img width="608" alt="ScreenShot 2021-04-29-18 12 56@2x" src="https://user-images.githubusercontent.com/3235109/116624979-dc941900-a916-11eb-8d1e-23faa1e02c5a.png">

Notice that it's showing **2.7.17** as the version, which is incorrect for this directory (but _would_ be correct for a different pyenv virtualenv). Ideally I'd like the prompt to show **3.8.5 qa** (the active Python version and the name of the pyenv virtualenv) in this case.

Finally, for reference, my checkout is up-to-date:
<img width="600" alt="ScreenShot 2021-04-29-18 16 57@2x" src="https://user-images.githubusercontent.com/3235109/116625149-2a108600-a917-11eb-9ce6-60a85ee44035.png">

Thanks (as always) for your time!

**Comment by romkatv** [comment]
Thanks for the bug report.

Could you attach `/Users/eddyg/git/qa/.python-version` and your p10k config to the issue?

**Comment by eddyg** [comment]
`my-p10k.zsh` is how I setup p10k from my `.zshrc` (to try to keep track of my customizations). `dotp10k.zsh.txt` is actually named `.p10k.zsh` (since you can't attach "hidden" files).

[my-p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/6407371/my-p10k.zsh.txt)
[dotp10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/6407388/dotp10k.zsh.txt)

I don't claim to understand any of the intricacies of P10K, but I did try to do some poking around and it seems `_p9k_cached_cmd` may be the culprit?

Some output that may be of interest (including the thing you asked for):
 
```
❯ cd ~/git/qa
❯ cat .python-version
qa
❯ 
❯ echo $VIRTUAL_ENV
/Users/eddyg/.pyenv/versions/3.8.5/envs/qa
❯ echo $PYENV_VIRTUAL_ENV
/Users/eddyg/.pyenv/versions/3.8.5/envs/qa
❯ where python
/Users/eddyg/.pyenv/shims/python
/usr/bin/python
❯ python --version
Python 3.8.5
❯ /usr/bin/python --version
Python 2.7.16
❯ _p9k_cached_cmd 1 python --version; echo $_p9k__ret
Python 2.7.17
❯ ls ~/.pyenv/versions
2.7.17/ 3.8.5/  3.8.7/  3.8.9/  dev@    qa@     skynet@
```

I also tried running `pyenv local dev` (to change the Python version to 3.8.7, for example) but the prompt behaved the same way.

Thanks for taking the time to look in to this.

**Comment by romkatv** [comment]
Your analysis is spot on. p10k has cached the output of `python --version` when it was printing "2.7.17". It thinks there is no need to invoke this command again because `python` still resolves to the same file (`/Users/eddyg/.pyenv/shims/python`) and that file hasn't changed. The output of `python --version` depends on environment that p10k is unaware of.

I don't see a generic solution but it's not hard to hack something up that would work for pyenv. Will do that once I get another chunk of free time.

**Comment by romkatv** [comment]
> I don't see a generic solution but it's not hard to hack something up that would work for pyenv. Will do that once I get another chunk of free time.

This is done. Please update powerlevel10k and let me know whether it works for you.

**Comment by romkatv** [comment]
By the way, have you tried `pyenv` segment instead of `virtualenv`? I think that's what most pyenv users do. Here are the default options for it in case you want to try it: https://github.com/romkatv/powerlevel10k/blob/69d3650958ce03d666f433792444290b7b2ffe5d/config/p10k-rainbow.zsh#L965-L990

**Comment by eddyg** [comment]
Hi Roman!

Been using the latest version for a couple days and wanted to confirm that it is working great. Thanks! 🎉 

I also switched to the `pyenv` segment... and I'm using a custom `POWERLEVEL9K_PYENV_CONTENT_EXPANSION` that adds the version information in a slightly different foreground color. Thanks again!

<img width="609" alt="ScreenShot 2021-05-25-08 15 56@2x" src="https://user-images.githubusercontent.com/3235109/119496473-8659a080-bd31-11eb-8c2c-5dfd43a04fb4.png">

**Comment by romkatv** [comment]
Thanks for the confirmation. Closing as fixed. Keep those bug reports coming, I really value them (despite taking a long time to fix).

**Comment by eddyg** [comment]
I never had any doubt I'd see an update on this issue, and to me, this was _still_ a "quick resolution", so thank you. The effort you put in to this project is astounding, and anybody who complains about anything related to P10K doesn't realize what "open source" means or how fantastic your attentiveness to this project is.  Keep up the great work!
