### ISSUE TITLE
./zshrc does NOT exist

### ISSUE THREAD

**Issue by Steve-Dusty** [romkatv/powerlevel10k#1380]
The instructions asked me to set themes in ./zshrc but ./zshrc doesn't exist.. I ran everything in zsh shell.

**Comment by JustFast** [comment]
its in ~/zshrc i think

**Comment by Steve-Dusty** [comment]
that was a typo. it's ~/.zshrc according to the dOcS.

**Comment by JustFast** [comment]
your supposed to execute it

**Comment by romkatv** [comment]
What?

**Comment by Steve-Dusty** [comment]
I fixed it. It's just that I'm not good at reading documentation.
