### ISSUE TITLE
prompt saying base in left of terminal 

### ISSUE THREAD

**Issue by oussama-aouini** [romkatv/powerlevel10k#1383]
how to hide it ?

![Screenshot from 2021-05-09 15-43-35](https://user-images.githubusercontent.com/80572095/117576388-b7a16200-b0dd-11eb-95b2-7b2ef4b13d0b.png)

**Comment by romkatv** [comment]
Your prompt is telling you that you've enabled python virtual environment with the name "base". You can either not enter the virtual environment, or open `~/.p10k.zsh`, search for `virtualenv` and remove the first matching line.

**Comment by oussama-aouini** [comment]
i commented that line and it disappeared 
#anaconda                # conda environment (https://conda.io/) 

but i want to know does it affect performance or it just has a visual effect ?

**Comment by romkatv** [comment]
Most people who use conda (or other tools) to enable virtual environments want to know when said environments are enabled. This is why powerlevel10k shows it. The display of the virtual environment's name doesn't affect performance.
