### ISSUE TITLE
the arrows position in the prompt are slightly shifted

### ISSUE THREAD

**Issue by oussama-aouini** [romkatv/powerlevel10k#1384]
i know it is no big deal but can someone help me plz it is driving me crazy 

![image](https://user-images.githubusercontent.com/80572095/117588175-b1c97200-b119-11eb-9527-2a5827d197cb.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols
