### ISSUE TITLE
help with segment updates.

### ISSUE THREAD

**Issue by getsec** [romkatv/powerlevel10k#1385]
I'm trying to write a custom prompt segment to read data from a file each time I enter a newline. Every 10seconds I have a mac plist that dumps my AWS account (used via env vars) to a file called `~/.awscurracct`.

Ive taken the example found in the p10k.zsh file, and also tried a few more, but it only updates the segment when I restart ZSH.

Segment below, 

```sh
  ACCOUNT_INFO=$(cat ~/.awscurracct)
  function prompt_example() {
    #p10k segment -f 2 -i '⭐' -t $ACCOUNT_INFO
    p10k segment -i $'\uf308' -f blue -e -c $ACCOUNT_INFO -t $ACCOUNT_INFO
  }
```

**Comment by romkatv** [comment]
This should do it:

```zsh
function prompt_my_aws_account() {
  local account
  [[ -r ~/.awscurracct ]]    || return
  account=$(<~/.awscurracct) || return
  [[ -n $account ]]          || return
  p10k segment -i $'\uF308' -f blue -t ${account//\%/%%}
}
```

The name of the segment is `my_aws_account`. It's a good idea to have `my` as a prefix in order to avoid clashes with future versions of powerlevel10k.

**Comment by getsec** [comment]
@romkatv MY MAN!!! That works flawlessly.

If you have a sec can you explain what this does? I'm honestly, not too familiar with what's going on here. Cheer

**Comment by romkatv** [comment]
All lines except the last (the one that invokes `p10k segment`) are plain zsh and aren't specific to powerlevel10k. You can use zsh documentation and forums to figure out what they do. The last line is documented at `p10k help segment`.
