### ISSUE TITLE
Enable instant prompt without `p10k configure`?

### ISSUE THREAD

**Issue by roeniss** [romkatv/powerlevel10k#1387]
tl;dr: Can I just copy and paste `p10k-instant-prompt-${(%):-%n}.zsh` on every Linux distro? (ex. Ubuntu18.04, Ubuntu20.04, macOS10.15.4, FreeBSD, ...)

I'm trying to make dotfiles including my p10k and oh-my-zsh settings.

I have my own `.p10.zsh` which is made by `p10k configure`, then I realized that if I want to enable instant prompt I have to bring `${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh` file. 

It is there but is it safe to copy that file, or should I re-configure p10k entirely each based on linux distros?

**Comment by romkatv** [comment]
Just copy `~/.p10k.zsh`. Don't copy `p10k-instant-prompt-${(%):-%n}.zsh`.

**Comment by roeniss** [comment]
@romkatv Thank you. It was actually my problem. I manually edit `.zshrc` like this:

```sh
...
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi
...
```

When I uncomment lines above, p10k automatically install instant prompt files.

**Comment by romkatv** [comment]
> @romkatv Thank you. It was actually my problem. I manually edit `.zshrc` like this:
> 
> ```shell
> ...
> #if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
>   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
> #fi
> ...
> ```

That's a bad idea. I highly recommend reverting your changes.

In order to copy your zsh config to another machine you just need to copy `~/.zshrc` and `~/.p10k.zsh`. Don't do anything else. Don't copy other files and don't modify anything.

**Comment by roeniss** [comment]
I updated my code already to use if-statement. Thanks for confirming!
