### ISSUE TITLE
Support Volta

### ISSUE THREAD

**Issue by rdsedmundo** [romkatv/powerlevel10k#1388]
[Volta](https://volta.sh/) is a JavaScript tool manager, a faster alternative from nvm written in Rust.

I'd like to be able to see the Node version coming from Volta in the `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` configuration as I can see with `nvm`.

**Comment by romkatv** [comment]
Please send a PR if you want this. It’s very unlikely to happen otherwise.

**Comment by rdsedmundo** [comment]
I'm not very proficient in Bash, but I can give it a shot. I suppose it's something along those lines, right? https://github.com/romkatv/powerlevel10k/blob/8d1daa4e6340b1689bf951730489bc64c52220c7/internal/p10k.zsh#L2425-L2435

**Comment by romkatv** [comment]
> I suppose it's something along those lines, right?
> 
> https://github.com/romkatv/powerlevel10k/blob/8d1daa4e6340b1689bf951730489bc64c52220c7/internal/p10k.zsh#L2425-L2435

That code is for nvm. Volta is very different, so the code will be very different, too.

**Comment by romkatv** [comment]
Closing as I don't intend to do anything here.

**Comment by wfpaisa** [comment]
temporal solution is use `node_version` set a cache, maybe with add at end of: `~/.p10k.zsh` 


```
# Volta
prompt_node_version() {

  if (( _POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY )); then
    _p9k_upglob package.json && return
  fi

  local v=$(node --version)
  _p9k_prompt_segment "$0" "green" "white" 'NODE_ICON' 0 '' "${v#v}"
}
```

and uncomment: `node_version`

**Comment by romkatv** [comment]
@wfpaisa This code may break without notice when you update powerlevel10k. To avoid the risk of your shell breaking, use the public documented API instead and don't override functions provided by powerlevel10k.

First, define this function in `~/.p10k.zsh`:

```zsh
function prompt_my_volta() {
  emulate -L zsh -o extended_glob
  # Don't do anything if there is no `node` command.
  (( $+commands[node] )) || return
  # Don't do anything if there is no `package.json` file.
  [[ -n ./(../)#package.json(#qN) ]] || return
  # Get version of `node` command.
  local version
  version=$(node --version) || return
  # Display it with white foreground on green background.
  p10k segment -b green -f white -ri NODE_ICON -t "${version#v}"
}
```

Then put `my_volta` in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in the same file. You can find this parameter close to the top.

Note that this segment may slow down your prompt by a lot.

**Comment by wfpaisa** [comment]
@romkatv  thank you very much :)
it was perfect:
![image](https://user-images.githubusercontent.com/1735752/121680423-27a95c00-ca7f-11eb-9616-a2c3629104ce.png)

**Comment by romkatv** [comment]
@wfpaisa I might be able to make the default `node_version` segment work for volta and it'll be much faster than the custom segment I've posted in my previous comment. Could you send me the output of the following command?

```zsh
which node
```

**Comment by wfpaisa** [comment]
oh, that would be perfect: this is 
```
/home/USER/.volta/bin/node
```

**Comment by romkatv** [comment]
Done. Please update powerlevel10k and see if `node_version` works as you would expect when using volta.

**Comment by wfpaisa** [comment]
works, thank you!

**Comment by romkatv** [comment]
Thanks for the confirmation!
