### ISSUE TITLE
Put the git branch on the right side

### ISSUE THREAD

**Issue by sevenmaxis** [romkatv/powerlevel10k#1389]
I found the git branch on the left side is annoying. 
Is there a way to put the git branch on the right side?
Picture for reference:
<img width="721" alt="Screen Shot 2021-05-13 at 13 29 10" src="https://user-images.githubusercontent.com/293438/118113725-4fa98f00-b3ef-11eb-9639-ab55d79998af.png">

**Comment by romkatv** [comment]
Move `vcs` from `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in your config (usually `~/p10k.zsh`).

**Comment by sevenmaxis** [comment]
Perfect! Thanks
