### ISSUE TITLE
Shortening kubernetes cluster name

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#139]
Great idea by @bric3. See https://github.com/Powerlevel9k/powerlevel9k/issues/1345.

**Comment by romkatv** [comment]
I've implemented this. Shortening is controlled by an optional array parameter that lists shortening strategies to be applied. Currently there are only two supported strategies: `gke` and `eks`.

```zsh
# Shorten gke and eks cluster names:
#
#   - gke_projectname_availability-zone_cluster-01         => cluster-01
#   - arn:aws:eks:us-east-1:XXXXXXXXXXXX:cluster/eks-infra => eks-infra
#
# This transformation is applied before class matching and content
# expansion.
POWERLEVEL9K_KUBECONTEXT_SHORTEN=(gke eks)
```

I've implemented the same logic as in powerline-go but I don't use kubernetes myself so cannot easily verify that it works.

@bric3 Could you check if it works for you? If you are using Powerlevel9k, the following commands should let you test the new feature without making changes to your system:

```zsh
git clone --depth 1 https://github.com/romkatv/powerlevel10k.git /tmp/powerlevel10k
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=kubecontext
POWERLEVEL9K_KUBECONTEXT_SHORTEN=(gke eks)
source /tmp/powerlevel10k/powerlevel10k.zsh-theme
```

Other than the addition of the extra `kubecontext` segment on the right, your prompt will stay unchanged because p10k is backward compatible with p9k configuration options.

**Comment by patrickdean** [comment]
Is there a way to disable this functionality? I can't seem to figure out how to go back to using the current-context name for my eks cluster. My devl and prod clusters have the same name in different AWS accounts.

**Comment by romkatv** [comment]
@patrickdean If you update p10k to the latest version, kubecontext should behave the same way as before (assuming you haven't changed any settings). If this is not the case, please open an issue. Attach you p10k configuration and describe what you context is, what you are seeing and what you used to see.

**Comment by patrickdean** [comment]
opened #142 thanks!

**Comment by bric3** [comment]
@romkatv actually it does not work, I'm not sure what wrong here, as this is quite advanced zsh scripting.

**Comment by romkatv** [comment]
@bric3 could you clarify what doesn't work?

**Comment by bric3** [comment]
@romkatv Sorry, I sent the comment to early, the shortening doesn't work at all.

I've run your command in an _clean_ zsh, using the following command `zsh -d -f`, and I still see the full string with the namespace

```
gke_my-project-94fea987_europe-west1_my-cluster-k8s-cluster-1/the-namespace ⎈
```

**Comment by romkatv** [comment]
@bric3 Thanks for trying it. I just fixed bug with an inverted check. Could you try again with the newest version?

**Comment by bric3** [comment]
@romkatv Nope this is the same issue

**Comment by bric3** [comment]
@romkatv I'm not sure this regex https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L2924 matches my cluster `gke_my-project-94fea987_europe-west1_my-cluster-k8s-cluster-1`

**Comment by romkatv** [comment]
Ok, I'll debug this in a few hours. I haven't tried the command the way you are running it. However, I believe the original command should work. If you want to use zsh -df, then simply source the theme without setting any parameters. It also should work.

**Comment by bric3** [comment]
Actually testing in the shell directly I've found that the regex prefix `(#b)` makes the test fail

```bash
[[ $cluster == gke_(?*)_(asia|australia|europe|northamerica|southamerica|us)-([a-z]##<->-[a-z])_(?*) ]] && echo ok
ok
```

```bash
[[ $cluster == (#b)gke_(?*)_(asia|australia|europe|northamerica|southamerica|us)-([a-z]##<->-[a-z])_(?*) ]] && echo ok
```

**Comment by romkatv** [comment]
You are right, the pattern is the problem. I don't use gke myself and from the docs I've got the impression that cluster names encode zones but your string encodes region. I've updated the patter to recognize both cases.

By the way, shortening is very flexible. kubecontext segment sets the following parameters:

- `P9K_CONTENT`: The content that would've been displayed if there was no content expansion defined (see below). This is what you normally see in your prompt.
- `P9K_KUBECONTEXT_NAME`: The current context's name. Corresponds to column `NAME` in the output of `kubectl config get-contexts`.
- `P9K_KUBECONTEXT_CLUSTER`: The current context's cluster. Corresponds to column `CLUSTER` in the output of `kubectl config get-contexts`.
- `P9K_KUBECONTEXT_NAMESPACE`: The current context's namespace. Corresponds to column `NAMESPACE` in the output of `kubectl config get-contexts`. If there is no namespace, the parameter is set to "default".

If the context points to GKE or EKS, the following extra parameters are set:

- `P9K_KUBECONTEXT_CLOUD_NAME`: Either "gke" or "eks".
- `P9K_KUBECONTEXT_CLOUD_ACCOUNT`: Account/project ID.
- `P9K_KUBECONTEXT_CLOUD_ZONE`: Availability zone or region.
- `P9K_KUBECONTEXT_CLOUD_CLUSTER`: Cluster.

`P9K_KUBECONTEXT_CLOUD_*` parameters are derived from `P9K_KUBECONTEXT_CLUSTER`. For example, if `P9K_KUBECONTEXT_CLUSTER` is "gke_my-account_us-east1-a_my-cluster-01":

- `P9K_KUBECONTEXT_CLOUD_NAME=gke`
- `P9K_KUBECONTEXT_CLOUD_ACCOUNT=my-account`
- `P9K_KUBECONTEXT_CLOUD_ZONE=us-east1-a`
- `P9K_KUBECONTEXT_CLOUD_CLUSTER=my-cluster-01`

If `P9K_KUBECONTEXT_CLUSTER` is "arn:aws:eks:us-east-1:123456789012:cluster/my-cluster-01":

- `P9K_KUBECONTEXT_CLOUD_NAME=eks`
- `P9K_KUBECONTEXT_CLOUD_ACCOUNT=123456789012`
- `P9K_KUBECONTEXT_CLOUD_ZONE=us-east-1`
- `P9K_KUBECONTEXT_CLOUD_CLUSTER=my-cluster-01`

`POWERLEVEL9K_KUBECONTEXT_CONTENT_EXPANSION` specifies what gets shown in your prompt. By default it's set to `${P9K_CONTENT}`. You can override it to display the info you care about. For example, the expansion below will show `P9K_KUBECONTEXT_CLOUD_CLUSTER` if it's not empty and fall back to `P9K_KUBECONTEXT_NAME`.

```zsh
POWERLEVEL9K_KUBECONTEXT_CONTENT_EXPANSION='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'
```

You can also combine this with context classes. These are also very powerful. If you've generated a config by following the guide in p10k, take a look at it for details. If the guide didn't trigger, type `p9k_configure` after loading p10k.

P.S.

Huge thanks for your help with testing and debugging this!

**Comment by bric3** [comment]
@romkatv Thanks for the implementation and quick fix.
I wasn't aware of powerline10k, I've switched :)

----

By the way, when powerline10k fork a process, does it so for each term, or is there a single daemon that can be share for all terms ?

**Comment by romkatv** [comment]
> I wasn't aware of powerline10k, I've switched :)

Enjoy fast prompt :smile: 

> By the way, when powerline10k fork a process, does it so for each term, or is there a single daemon that can be share for all terms ?

You mean for Git status? It's one per interactive shell, to avoid security hazard. Wouldn't want to accidentally leak information about your Git repositories to processes that aren't supposed to see it.

**Comment by bric3** [comment]
OK indeed, I haven't thought of that. By the way this point should be in the readme ;)
That advertises the code take into account security hazard to some level.

**Comment by romkatv** [comment]
> By the way this point should be in the readme ;)

Done in https://github.com/romkatv/powerlevel10k/commit/fa90d99636c467037ce8285bfd56c49a8eb8036d.

**Comment by bric3** [comment]
Cool :)
