### ISSUE TITLE
when running tmux and transient prompt CLEAR command moves it back to the top 

### ISSUE THREAD

**Issue by woss** [romkatv/powerlevel10k#1390]
Everything works as it should: 
![image](https://user-images.githubusercontent.com/80440/118132159-b040c800-b3ff-11eb-9da1-d515bb16d6c0.png)

Then when I enter `clear` this happens:
![image](https://user-images.githubusercontent.com/80440/118132259-c6e71f00-b3ff-11eb-802b-c9dd755ea766.png)

This is just the example usually it's much more cluttered, that's why I would like to clear the screen. 

Please advise.

**Comment by romkatv** [comment]
`clear` doesn't come from powerlevel10k. It's an external command. See `man clear`. It always does the same thing whether you are using tmux/powerleevl10k/transient prompt or not.

**Comment by woss** [comment]
how could you misunderstand me? i know `clear` has nothing to do with p10k, I am reporting the strange behaviour. 
or you are saying that these two images are the same?

**Comment by romkatv** [comment]
> i know `clear` has nothing to do with p10k, I am reporting the strange behaviour.

Maybe I'm misunderstanding. What do you mean by strange behaviour? Does `clear` behave in a way you don't expect? Does it behave differently with and without powerlevel10k?

> or you are saying that these two images are the same?

They are obviously different. If they were the same, that would be a bug in zsh ("pressing <kbd>Enter</kbd> after typing `clear` has no effect").

**Comment by woss** [comment]
so it's not a bug that the prompt goes to the top and never comes back down after the `clear` is invoked? 
This part of the zsh clearly saying that in the tmux the prompt is down.

```bash
# Automaticaly wrap TTY with a transparent tmux ('integrated'), or start a
# full-fledged tmux ('system'), or disable features that require tmux ('no').
zstyle ':z4h:' start-tmux       'system'
# Move prompt to the bottom when zsh starts up so that it's always in the
# same position. Has no effect if start-tmux is 'no'.
zstyle ':z4h:' prompt-at-bottom 'yes'
```

**Comment by romkatv** [comment]
> so it's not a bug that the prompt goes to the top and never comes back down after the `clear` is invoked?

No. That's how `clear` works. You are invoking an external command and that command does what it's mean to do. The behavior of `clear` is documented at `man clear`. It always does the same thing whether you are using bash/zsh/tmux/powerlevel10k or not using any of those things. Exactly the same behavior all the time. Always clears the screen and puts the cursor at the top.

> This part of the zsh clearly saying that in the tmux the prompt is down.

Oh, you are using zsh4humans? He quoted code and comments don't say what you are implying.

You can press <kbd>Ctrl+L</kbd> to clear screen and keep cursor at the bottom.

**Comment by woss** [comment]
> No. That's how clear works. You are invoking an external command and that command does what it's mean to do. The behavior of clear is documented at man clear. It always does the same thing whether you are using bash/zsh/tmux/powerlevel10k or not using any of those things. Exactly the same behavior all the time. Always clears the screen and puts the cursor at the top.

I'm looking at `man clear` and can't seem to find the part where it puts the cursor at the top. 
![image](https://user-images.githubusercontent.com/80440/118142576-c902ab00-b40a-11eb-8c1a-472355ffdcd0.png)

But that's not important, I choose to trust you on this since you are way more knowledgeable in this than I. 

I didn't know of the `Ctrl+l` (small case L) in the zsh4humans, does that comes from the zsh4humans or somewhere else?

**Comment by romkatv** [comment]
> I didn't know of the `Ctrl+l` (small case L)

It's `^L` either way.

> in the zsh4humans, does that comes from the zsh4humans or somewhere else?

<kbd>Ctrl+L</kbd> is a standard binding in zsh (and a few other shells). zsh4humans rebinds it to keep cursor and prompt at the bottom. You can see what it's bound to with `bindkey '^L'`.

```text
❯ bindkey '^L'
"^L" z4h-clear-screen-soft-bottom
```

`soft` means the scrollback is not deleted (there is also a `hard` version), and `bottom` means the cursor stays at the bottom (there is also a `top` version).

None of this is specific to powerlevel10k by the way.

**Comment by woss** [comment]
ok, cool! thanks for clearing this up! i learned a new thing today. thanks :)
