### ISSUE TITLE
NPM Version in right prompt elements

### ISSUE THREAD

**Issue by lgabster** [romkatv/powerlevel10k#1391]
Hi! There is any way to show npm version (as node version) in the right side?
I looked `.p10k.zsh` config file but didn't find any relevant option.

**Comment by romkatv** [comment]
Are you looking for "package" segment? It's commented out by default in `~/.p10k.zsh`, so you'll need to uncomment it. You might also uncomment and change `POWERLEVEL9K_PACKAGE_CONTENT_EXPANSION`. See comments above it.

**Comment by lgabster** [comment]
Yes, i saw the "package" segment, but that is different. I would like to see npm version (`npm -v` command output), not the package version.

**Comment by romkatv** [comment]
There is no such segment in powerlevel10k.

**Comment by romkatv** [comment]
You can implement this as a custom prompt segment in your own config. See `prompt_example` in `~/.p10k.zsh`.
