### ISSUE TITLE
[Feature Request] Bytes since last prompt

### ISSUE THREAD

**Issue by bmayen** [romkatv/powerlevel10k#1392]
In addition to send/receive rate and total bytes sent/received for a network interface, it would be nice to have bytes sent/received *since last prompt*. This would give some insight into how much bandwidth commands are using. Granted, it wouldn't be the most accurate since other background tasks could be using bandwidth between prompts, but could still be nice to have during operations like `npm i`.

**Comment by romkatv** [comment]
Done. You can now use `P9K_IP_RX_BYTES_DELTA` and `P9K_IP_TX_BYTES_DELTA` within `POWERLEVEL9K_IP_CONTENT_EXPANSION`. They give you the number of bytes received/sent since the last prompt.

**Comment by bmayen** [comment]
Wow, thanks so much for the immediate turnaround on this! A couple thoughts after trying it out.

1) Would it be possible to have the delta be between just command start and end instead of since last prompt? That would be more accurate to see how much bandwidth a given command uses. Since the last prompt can be an enormous value if you've spent an hour in a web browser before coming back to the terminal.

2) Perhaps a whitelist to only show this info when specific commands are run?

**Comment by romkatv** [comment]
Both the these are possible. They are also not too difficult to implement in user space without modifying powerlevel10k. You would need to define `p10k-on-post-prompt` to grab the command(s) from `P9K_COMMANDS`, and define a formatter for `ip` similarly to how it's done for `vcs`. Good luck!

**Comment by bmayen** [comment]
Thank you for the feedback! Will look into this solution and post back here if I come up with something :)
