### ISSUE TITLE
How I can change old prompt 

### ISSUE THREAD

**Issue by grigorii-horos** [romkatv/powerlevel10k#1393]
How you reset the prompt after press `ENTER` ?

Normal prompt looks good, but old prompt has only `❯`

![img](https://user-images.githubusercontent.com/47924579/114993762-bcb61d00-9e61-11eb-96c7-e93e647a425d.png)

**Comment by romkatv** [comment]
Run `p10k configure` and when you get asked whether you want to enable **Transient Prompt**, say No.

**Comment by grigorii-horos** [comment]
Oh... Sorry, I asked how this is realized internally. I tried to change PROMPT in function in precmd/preexec, but I think you use another algorithm

**Comment by romkatv** [comment]
Some info here: https://github.com/starship/starship/issues/888
