### ISSUE TITLE
[Question] Difference betwen forked NerdFonts and upstream one

### ISSUE THREAD

**Issue by grzesuav** [romkatv/powerlevel10k#1394]
hi @romkatv , I wanted to clarify differences between your fork and upstream one (https://github.com/ryanoasis/nerd-fonts), as I can see it is a bit behind. 

The problem I am trying to solve - I am using `MesloLGS NF` font, but I can't get some ligatures working, i.e. I have currently

![image](https://user-images.githubusercontent.com/9568421/118292548-0897c880-b4d9-11eb-9fb7-8ab0f760c2bc.png)

but I would like to have also (as in `FiraCode NerdFont`)

![image](https://user-images.githubusercontent.com/9568421/118292767-4137a200-b4d9-11eb-8c32-f0e10ee474c1.png)

not sure if the `!=` `<=` `=>` are not attached in `MesloLGS NF` or is there other reason why they do not render  ?

**Comment by romkatv** [comment]
Does this answer your question? https://github.com/romkatv/powerlevel10k#how-was-the-recommended-font-created

**Comment by romkatv** [comment]
You are correct that the recommended font doesn't have ligatures. It's a much better default.

You are welcome to use any other font of course. The recommended one exists so that I can point to something that definitely works well.

**Comment by grzesuav** [comment]
ok, I asked as I also want to have sth which will work ;) but if I understand correctly I can rebuild meslo font variant with additional glyphs, and use it. I am also bit used to existing glyphs in Meslo, just missing additional ones. Thank you for you answer, will close the issue.

P.S. have you consder enabling `discussions` feature on this repo ? Seems a bit better place for questions like mine ;)

**Comment by grzesuav** [comment]
additional question - is there sth in upstream which is worth rebasing into your fork ?

**Comment by romkatv** [comment]
> ok, I asked as I also want to have sth which will work ;) but if I understand correctly I can rebuild meslo font variant with additional glyphs, and use it.

Yes, you can do that.

> have you consder enabling `discussions` feature on this repo ? Seems a bit better place for questions like mine ;)

No, I haven't. I've never used "discussions" on GitHub. Opening an issue to ask a question is fine with me. There is also gitter although I very much prefer issues.

> additional question - is there sth in upstream which is worth rebasing into your fork ?

Dunno. I'm not following what happens in the upstream repo.
