### ISSUE TITLE
Git status does sync with upstream

### ISSUE THREAD

**Issue by rensftw** [romkatv/powerlevel10k#1395]
Just noticed today that the git status does not automatically sync with the upstream branch. 
For example, when I navigate into an outdated repo nothing is shown in the prompt status and it does not get updated even if I wait, checkout other local branches, create/modify files, etc:
![image](https://user-images.githubusercontent.com/22574186/118314574-ff205780-b4fc-11eb-88de-0fc301ac0944.png)

but if I manually `git fetch` the status is immediately updated:
![image](https://user-images.githubusercontent.com/22574186/118314721-2f67f600-b4fd-11eb-9860-1893d78a4901.png)

To fix this I tried the following setting, but it didn't help.
```sh
typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0
```

Environment details:
* macOS `11.3.1`
* iTerm2 `3.4.6`
* `zsh 5.8 (x86_64-apple-darwin20.1.0)`
* [`.p10k.zsh`](https://github.com/rensftw/.dotfiles/blob/main/zsh/.p10k.zsh) 
* I was able to reproduce this issue on both Rainbow and Lean themes

I thought that p10k should periodically do a background `git fetch` in order to sync the status with the upstream. Am I missing something?

**Comment by romkatv** [comment]
> Just noticed today that the git status does not automatically sync with the upstream branch.

This is working as intended. You can think of prompt information as being based on `git status`.

> I thought that p10k should periodically do a background `git fetch` in order to sync the status with the upstream. Am I missing something?

Powerlevel10k doesn't do that for the same reason `git status` doesn't automatically do `git fetch`.

**Comment by rensftw** [comment]
Ah, I see 😮 

I am coming from [Pure](https://github.com/sindresorhus/pure) and was expecting to see the arrow indicator for unpulled commits. Is this a feature in p10k as well?

(I don't know which command is used for this check, I was assuming it's fetch)

**Comment by romkatv** [comment]
> Ah, I see 😮
> 
> I am coming from [Pure](https://github.com/sindresorhus/pure) and was expecting to see the arrow indicator for unpulled commits.

As far as I'm aware, Pure is the only theme that does this (across all shells). It's easy to implement but the fact that no one else implements it (or that `git` doesn't automatically do `fetch` for you) has to tell you something.

> Is this a feature in p10k as well?

No.

> (I don't know which command is used for this check, I was assuming it's fetch)

Note that issuing `git fetch` isn't something your prompt should do. If you want `git fetch` to be issues all the time in the background, go ahead and do that. Powerlevel10k will reflect appropriate git status in prompt.

**Comment by rensftw** [comment]
Got it, that makes sense. Thanks!
