### ISSUE TITLE
Output of terminals overlap while using tmux.

### ISSUE THREAD

**Issue by shauryagoel0** [romkatv/powerlevel10k#1397]
Hi, I ssh into my server and began using tmux there. I compiled zsh 5.8 and installed this repository using OhMyZsh. Now, whenever I switch between windows I get overlapping text across windows like, on window 2-
![Screenshot from 2021-05-15 15-27-54](https://user-images.githubusercontent.com/6321314/118356412-c632c200-b592-11eb-82e7-96e14162312f.png)

On window 3-
![Screenshot from 2021-05-15 15-28-05](https://user-images.githubusercontent.com/6321314/118356417-c8951c00-b592-11eb-92b4-9a733c138faf.png)

This only happens after installing powerlevel10k. Before installing this issue was not present.

**Comment by romkatv** [comment]
What do you mean by overlapping text? What do you mean by switching windows?

**Comment by shauryagoel0** [comment]
Overlapping text means that in above images you can see that in both image there is output of ls -l. I typed this command only in window 3 and then switched to window 2 to take screenshot.
By switching windows I mean switching tmux windows. In above images you can see the bottom most bar listing windows 0-6. Well even this bar is overlapping as I have mentioned that first image corresponds to window number 2 and second image to window 3,

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k without changing anything else in your config?

**Comment by shauryagoel0** [comment]
As I have mentioned, this problem only occurs after installing powerlevel10k.

**Comment by romkatv** [comment]
Have you tried disabling powerlevel10k without changing anything else in your configuration? Can you post screenshots made under identical circumstances as the screenshots above (except without powerlevel10k)?

**Comment by shauryagoel0** [comment]
I removed powerlevel10k as mentioned in the README and obtain the following-
Window 2-
![Screenshot from 2021-05-15 16-00-52](https://user-images.githubusercontent.com/6321314/118357282-e6648000-b596-11eb-8775-959bb3bdf768.png)

Window 3-
![Screenshot from 2021-05-15 16-01-04](https://user-images.githubusercontent.com/6321314/118357290-f2504200-b596-11eb-81c5-7c1d8fc0fee7.png)

As you can see there are no issues after removing powerlevel10k.

**Comment by romkatv** [comment]
Thanks.

Could you describe all steps that are necessary to reproduce this problem?

**Comment by shauryagoel0** [comment]
I found out it is a tmux issue. Tmux doesn't display UTF-8 automatically, you have to start it with tmux -u.
