### ISSUE TITLE
How to set user/hostname background and color without configure.

### ISSUE THREAD

**Issue by duongkhoangiam** [romkatv/powerlevel10k#1398]
![Image of Yaktocat](https://i.ibb.co/ZX1p9b0/terminal.png)

**Comment by romkatv** [comment]
```zsh
POWERLEVEL9K_CONTEXT_BACKGROUND=3
POWERLEVEL9K_CONTEXT_FOREGROUND=7
```

**Comment by duongkhoangiam** [comment]
@romkatv 
Very thanks sir.
So another option to short the name and host
example jimmy........May Mackbook Pro
=> I need format to like "jimmy@MB"

**Comment by romkatv** [comment]
You can run the configuration wizard and read the comments in the generated config.
