### ISSUE TITLE
Double tab to autocomplete

### ISSUE THREAD

**Issue by abonforti** [romkatv/powerlevel10k#1399]
Hello,
this is most probably a misconfiguration in my config files, but in order to autocomplete i need to double press the tab key.
Is there any way to disable this and switch back to the classic functionality which makes tab autocomplete within one keypress?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by abonforti** [comment]
> See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

It might be something on oh-my-zsh level then, sorry for bothering.
