### ISSUE TITLE
Readme addition suggestions

### ISSUE THREAD

**Issue by desbma** [romkatv/powerlevel10k#14]
Hello,

First, thanks for making this project, it is indeed both much faster than the original theme and a drop in compatible replacement.

I have a few suggestions for additions or changes in the Readme, for stuff than personally confused me:

1. You wrote:
> Powerlevel10k uses the same configuration options as Powerlevel9k and produces the same results. It's simply faster. There is no catch.

however it directy contradicts the sentence at the end:

> Git prompt doesn't show tags and revisions. Open an issue if you need them.

2. Clearly mention that to be faster, this version spawns 2 subprocesses (zsh and gitstatusd), the processes are not a problem for me, but was somewhat a surprise, and looked very suspicious at first sight.

3. I see that you are devoting time and energy to upstream some of the changes, and I think you should mention it with a link to the relevant issues. Even if it fails or you don't have enough time to push though, it shows that is not a "hostile" fork, and it also puts pressure on the upstream project.

4. On Arch Linux, powerlevel10k can be installed with an [AUR package](https://aur.archlinux.org/packages/zsh-theme-powerlevel10k-git/) (I am not the packager), maybe you should add a link to it

**Comment by romkatv** [comment]
All very good points. I removed "What's the catch" section and added FAQ. Does this work for you?

**Comment by desbma** [comment]
You handled 2, 3 and 4, but for 1 there is still a contradiction IMO between the "_there is no catch_" in the header, and the FAQ answer for "_Does Powerlevel10k always render exactly the same prompt with the same config?_"

**Comment by romkatv** [comment]
Would you say the fact that Powerlevel10k doesn't show svn prompt unless you set `POWERLEVEL9K_VCS_BACKENDS` is a catch?

**Comment by desbma** [comment]
No, I rather thinking about 
> Git prompt in Powerlevel10k doesn't show tags and revisions. Open an issue if you need them.

**Comment by romkatv** [comment]
So that's the catch?

I think you are nitpicking. If you really care, send me a PR.

**Comment by desbma** [comment]
The catch is exactly what you wrote in the FAQ, it does not show git tags and revisions, therefore the result is not exactly identical to powerlevel9k.

Theses are merely minor suggestions, you can safely ignore them and close this, I won't be mad :)

**Comment by romkatv** [comment]
We read different meaning into "catch". I removed this word and added an asterisk after "produces the
same results" leading to the FAQ.

**Comment by romkatv** [comment]
FYI: Powerlevel10k now supports tags and revisions in vcs segment when using gitstatus. It also honors `POWERLEVEL9K_VCS_GIT_HOOKS` to produce the same prompt as Powerlevel9k even though it doesn't actually have hooks.

**Comment by desbma** [comment]
Good job!
