### ISSUE TITLE
Not seeing ability to change prompt style when using cygwin

### ISSUE THREAD

**Issue by d0n03rkf1tz** [romkatv/powerlevel10k#1400]
when running `p10k configure` in cygwin, the first screen it shows me is this:
![image](https://user-images.githubusercontent.com/83191295/118708958-0045d300-b7e2-11eb-817d-0f840ad431ad.png)

are there any known issues with using cygwin + oh-my-zsh that would prevent me from configuring my prompt style?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by d0n03rkf1tz** [comment]
@romkatv thanks for the link. I followed everything and it still seems to not allow me to change the prompt style. I see all the images and have it set to unicode:
![image](https://user-images.githubusercontent.com/83191295/118710132-81ea3080-b7e3-11eb-8291-97a58a1f0eaa.png)

and I never get this prompt:
![image](https://user-images.githubusercontent.com/83191295/118711767-93ccd300-b7e5-11eb-99d3-55e91672c906.png)

even when trying to configure with 2 lines.

**Comment by romkatv** [comment]
From the link I posted earlier:

> If the terminal can display fewer than 256 colors, configuration wizard preselects Lean style with 8 colors. All other styles require at least 256 colors. *Fix*: Use a terminal with 256 color support and make sure that `TERM` environment variable is set correctly. Verify with `print $terminfo[colors]`.

**Comment by d0n03rkf1tz** [comment]
d'oh!
https://media.giphy.com/media/xT5LMzIK1AdZJ4cYW4/source.gif

that was the one thing I thought I had taken care of, but hadn't.  Thanks for your help! Everything is working great!
