### ISSUE TITLE
Wrong remote repository icon

### ISSUE THREAD

**Issue by dbfin** [romkatv/powerlevel10k#1401]
Hi again,

Just wanted to pay your attention at this little issue.

When a github remote repository is configured via an ssh key (and either the option to show more icons is chosen during the configuration or POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION is unset), the prompt shows the remote repository glyph, but it shows the generic git one rather than the github one. 

To illustrate, one can configure in ~/.ssh/config a new connection named say github with user git, the path to the key (that is also added to github) etc. Then, if a repository is cloned as 
``` sh
git clone https://github.com/user/repo
```
the github icon is shown, but if it is cloned using 
``` sh
git clone github:user/repo
```
the generic git icon is shown.

It would be nice if it would recognize such cases appropriately if possible at all. 

Thanks again for the wonderful work!

Vadim.

**Comment by romkatv** [comment]
> if it is cloned using
> 
> ```shell
> git clone github:user/repo
> ```
> 
> the generic git icon is shown.

This shows the github logo for me. My guess is that your `Host` entry in `~/.ssh/config` has a different name, without "github" in it. In both cases this is working as expected.

If you want to see the github logo, either rename your host to anything with "github" in it or modify `my_git_formatter` in `~/.p10k.zsh`. You can inspect `VCS_STATUS_REMOTE_URL` for conditional icons. Something like this:

```zsh
if [[ $VCS_STATUS_REMOTE_URL == my-host:* ]]; then
  res+=${clean}$'\uF113 '
fi
```

If you do that, set `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION` to empty to disable the builtin icon.

**Comment by dbfin** [comment]
Good catch! Indeed, the way I named it here in the example you cannot reproduce the issue exactly because I named it github. My guess is that any other host name that includes github in it would work as well. 

And indeed what I meant is that if the host name in the ssh config file does not contain github but still refers to it, the icon is git. 

I am not in for changing anything inside .p10k simply because I consider this file as autogenerated, so I am strongly inclined to do all changes in .zshrc.

However, your comment regarding naming hosts works for me, and I consider it elegant enough to adopt. I have several github keys, and name them usually as gh..., gh... etc. so I guess I can change them to github..., github... Thanks for the idea! 

Please feel free to close this issue.

**Comment by romkatv** [comment]
I'm glad you've found a satisfactory workaround.
