### ISSUE TITLE
Using `. ~/.zshrc` to reload the config seems to break Transient Prompt

### ISSUE THREAD

**Issue by pm5k** [romkatv/powerlevel10k#1402]
Hello, I have encountered an interesting behaviour with p10k whereby a Transient Prompt that's set to "always" in the config gets broken upon reloading the zsh config in the same terminal window.

**Initial Behaviour:**
<img width="657" alt="Screenshot 2021-05-19 at 15 49 19" src="https://user-images.githubusercontent.com/9250112/118834380-1757f400-b8ba-11eb-8401-6ea16fade858.png">

**After `. ~/.zshrc` or `source ~/.zshrc`:**
<img width="402" alt="Screenshot 2021-05-19 at 15 49 44" src="https://user-images.githubusercontent.com/9250112/118834349-10c97c80-b8ba-11eb-88b4-01a2805219b6.png">

Not sure if any of these are relevant, but here are my specs and config below.
One quick addition is that if one was to use simply `> zsh` as a command, it seems to reload the config without causing this side-effect, which I suppose solves my problem, but should sourcing the dotconf not do the same thing? Would be great to get a confirmation if this breakage is intended or perhaps I am not using it properly..

- Terminal: Kitty
- Theme: p10k (fresh install)
 
<details>
<summary>`.zshrc` config:</summary>

```bash
#---------#
#   ENV   #
#---------#
export LANG=en_GB.UTF-8
export ZSH="/Users/$USER/.oh-my-zsh"
export DEFAULT_USER="$USER"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export GOPATH=$HOME/go
export PATH="$PATH:/usr/local/go/bin"
export PATH="$HOME/.poetry/bin:$PATH"
export PATH="/Users/$USER/.pyenv:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
# NVM
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
# Serverless
export PATH="$HOME/.serverless/bin:$PATH"
# Mysql
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

#---------------------#
#   PLUGINS / THEME   #
#---------------------#
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    git
    poetry
    zsh-autosuggestions
)

#----------#
#   INIT   #
#----------#
source $ZSH/oh-my-zsh.sh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#------------------#
#   VARS / FUNCS   #
#------------------#
VSCODE="Visual\ Studio\ Code"

# Capture function for aliasing Poetry so it does not f-up neofetch..
function capture {
    if [[ "$2" == "shell" ]]; then
        array=($(poetry env list --full-path))
        if [[ "$array" != *"RuntimeError"* ]]; then
            . $array[1]/bin/activate
        else
            echo "Cannot activate, are you in a project that uses poetry?"
        fi
    else
        ${@:1}
    fi
}


#----------------#
#   EVAL/ALIAS   #
#----------------#
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

alias cl=neofetch # clears terminal anyway..
alias pls=sudo
alias zshconf="open -a $VSCODE ~/.zshrc"
alias p10kconf="open -a $VSCODE ~/.p10k.zsh"
alias neoconf="open -a $VSCODE ~/.config/neofetch/config.conf"
alias zshrld=". ~/.zshrc"
alias ohmyzsh="open -a $VSCODE ~/.oh-my-zsh"
alias pr="poetry run"
alias vscode="open -a $VSCODE ."
alias poetry='capture poetry'

#-------------#
#   TABTABS   #
#-------------#

# tabtab source for packages uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

#---------#
#   NVM   #
#---------#
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

neofetch
```
</details>

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#weird-things-happen-after-typing-source-zshrc

**Comment by pm5k** [comment]
@romkatv so this is because sourcing doesn’t technically let the shell inherit that content per-se? In any case, ive got a workaround, just thought I’d ask. Thanks for your response.

**Comment by romkatv** [comment]
This is because `source ~/.zshrc` can do pretty much anything. The good thing is that there is never a reason to invoke this destructive and unpredictable command. `exec zsh` is even easier to type.
