### ISSUE TITLE
Sometimes `^[[52;1R` gets printed inbetween prompts seemingly randomly

### ISSUE THREAD

**Issue by h0adp0re** [romkatv/powerlevel10k#1403]
- `zsh 5.8 (x86_64-apple-darwin20.1.0)`
- p10k: 9c034101fe3cec1e2edb8e07c32a3e6dba9afaee
- no frameworks

Sometimes `^[[52;1R` gets printed after executing a command.

I believe I have also seen `^[[52;9R`, `^[[52;6R`, `^[[52;3R`, in that order, after each prompt. The numbers might have been in different places but I distinctly remember seeing `9`, then `6`, then `3`. But I can't tell you on what conditions all that happened.

I tested without sourcing p10k and the issue did not appear. Let me know what questions pop into your head, I don't know what else to provide intially.

**Comment by romkatv** [comment]
Can you reproduce it if you disable **everything** in your zsh rc files except powerlevel10k? Your `~/.zshrc` would look like this:

```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
source ~/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by romkatv** [comment]
You might need to change `~/powerlevel10k` but other than that that's the whole `~/.zshrc`.

**Comment by h0adp0re** [comment]
Wow, everything got insanely fast, what a sobering experience, I'll start pruning that file ASAP.

And no, I could not reproduce it that way. I'll find out what is causing this and report it at the correct place. Thanks for the help and for the theme.

Closing this as the issue clearly isn't related to p10k.

**Comment by h0adp0re** [comment]
The issue seems to be with [zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete). I've filed an issue there – https://github.com/marlonrichert/zsh-autocomplete/issues/261.
