### ISSUE TITLE
Newly overwrite .p10k.zsh?

### ISSUE THREAD

**Issue by GitHubNeko** [romkatv/powerlevel10k#1404]
I have updated powerlevel10k, but the new configuration options have not been added to .p10k.zsh as shown below
![Screenshot_20210521_190040_com thirtydegreesray openhub](https://user-images.githubusercontent.com/83487691/119127464-f254b400-ba66-11eb-9c62-2643bab47d3e.jpg)
![Screenshot_20210521_190108](https://user-images.githubusercontent.com/83487691/119127476-f54fa480-ba66-11eb-87fb-e2104adc97d9.jpg)
So I used p10k configure again, and this option was added to .p10k.zsh, but my configuration no longer exists! How can I add new configuration options to the old .p10k.zsh ？

**Comment by romkatv** [comment]
> I have updated powerlevel10k, but the new configuration options have not been added to .p10k.zsh

This is working as expected. Updating powerlevel10k does not modify your config.

> So I used p10k configure again, and this option was added to .p10k.zsh, but my configuration no longer exists!

This is working as expected. `p10k configure` generates a new config. It asks for confirmation before overriding your config. It also backs up the old config and prints the location of the backup.

> How can I add new configuration options to the old .p10k.zsh ？

By hand.

**Comment by GitHubNeko** [comment]
> > I have updated powerlevel10k, but the new configuration options have not been added to .p10k.zsh
> 
> This is working as expected. Updating powerlevel10k does not modify your config.
> 
> > So I used p10k configure again, and this option was added to .p10k.zsh, but my configuration no longer exists!
> 
> This is working as expected. `p10k configure` generates a new config. It asks for confirmation before overriding your config. It also backs up the old config and prints the location of the backup.
> 
> > How can I add new configuration options to the old .p10k.zsh ？
> 
> By hand.

Is there a way to add new options to .p10k.zsh without affecting the old configuration?

**Comment by romkatv** [comment]
> Is there a way to add new options to .p10k.zsh without affecting the old configuration?

You can edit `~/.p10k.zsh` by hand or you can generate a new version (ignoring all changes that you might have made) with `p10k configure`.

**Comment by GitHubNeko** [comment]
> > 有没有一种方法可以在不影响旧配置的情况下向.p10k.zsh添加新选项？
> 
> 您可以`~/.p10k.zsh`手动编辑，也可以使用生成新版本（忽略所有可能的更改）`p10k configure`。

Ok thank you :-)
