### ISSUE TITLE
Cannot assign a value to $token environment variable name

### ISSUE THREAD

**Issue by kasunt-nixdev** [romkatv/powerlevel10k#1407]
**Describe the bug**
After installing and configuring ohmyzsh and powerlevel10k `$token` cannot be assigned a value. Ive test this on vanilla zsh and its working fine. 

**To Reproduce**
Install and configure ohmyzsh and powerlevel10k.
Run command,
```
❯ export TOKEN=test
❯ echo $TOKEN
test
❯ export token=test
❯ echo $token
$token
```

**Expected behaviour**
`echo $token` must output `test` instead of `$token`.

**Comment by romkatv** [comment]
Powerlevel10k only affects your prompt.

**Comment by kasunt-nixdev** [comment]
@romkatv this is at the prompt.
So if I try to assign to `token` variable it completely fails.
Works fine with other OMZ themes

**Comment by romkatv** [comment]
I've closed this issue prematurely. You are right, this is a bug in powerlevel10k. Should be fixed now. Please update powerlevel10k and try again.
