### ISSUE TITLE
No asdf versions shown when there is a .tool-versions file in $HOME

### ISSUE THREAD

**Issue by miquecg** [romkatv/powerlevel10k#1409]
Hi,

I've noticed that [this commit](https://github.com/romkatv/powerlevel10k/commit/1ad8e5759ecd41619746a775d9bc9d2902c5c90e) introduced a regression for `asdf` users, causing runtime versions to dissapear from the prompt. This only happens when there is a top level `.tool-versions` in $HOME. If I rename/remove this file, prompt looks as usual.

**Comment by romkatv** [comment]
Thanks for reporting this. Will take a look.

**Comment by romkatv** [comment]
Fixed. Please update powerlevel10k and let me know whether it works for you.

**Comment by romkatv** [comment]
> I've also noticed one more thing happening to `asdf`. Having a runtime version placed on global `.tool-versions` causes the prompt to not show it, regardless of which folder you are. So imagine I'm on a project folder which also defines a version for this runtime, that piece of information is missing. I imagine this is not expected behaviour but wanted to ask before opening a new issue.

That's a customizable feature. See https://github.com/romkatv/powerlevel10k/blob/69d3650958ce03d666f433792444290b7b2ffe5d/config/p10k-lean.zsh#L555-L570 and https://github.com/romkatv/powerlevel10k/blob/69d3650958ce03d666f433792444290b7b2ffe5d/config/p10k-lean.zsh#L584-L589.

**Comment by LuanComputacao** [comment]
That is a customizable feature that made me lost 2 days of work. 
Seems a good idea, but worst and not desirable.
