### ISSUE TITLE
Cursor disappears while navigating shell command

### ISSUE THREAD

**Issue by arkantos493** [romkatv/powerlevel10k#1410]
First of all: this theme is amazing.

However, I've one thing that really annoys me. When I've copied a large shell command and I want to change a part of it in the middle, I've no navigate to it suing the arrow keys. The problem is: while I navigate the command, the cursor disappears. So I've to guess the current cursor position or release the arrow keys for a short moment until the cursor reappears.
Here an example of the current behavior.
![Peek 2021-05-25 10-22](https://user-images.githubusercontent.com/38330545/119488852-4dcebc80-bd5b-11eb-822b-b4a67a7a6feb.gif)

If I use bash for example (or ZSH without your theme), the behavior is as intended, i.e., I can always see the current cursor position:
![Peek 2021-05-25 10-23](https://user-images.githubusercontent.com/38330545/119489131-a736eb80-bd5b-11eb-9300-d8d798940a61.gif)

I'm using Ubuntu 20.04 with the default `gnome-terminal` and downloaded the current `prezto` master including the distributed powerlevel10k theme.

Is there a way to get the same cursor behavior for this theme as in vanilla bash or zsh?

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k without changing anything else in your config? If you are using oh-my-zsh, comment out the line in `~/.zshrc` that sets `ZSH_THEME` and run `exec zsh` to restart zsh.

**Comment by romkatv** [comment]
Just noticed you are using prezto, so please ignore the oh-my-zsh part. Change your theme to "sorin" and see what happens.

**Comment by arkantos493** [comment]
Ok when I use the "sorin" theme the cursor also disappears. So it looks like this is more a general `prezto` problem than the problem of a specific theme.

**Comment by romkatv** [comment]
Closing because this is not related to powerlevel10k.

FWIW, I would just change the cursor to solid block (no blinking). You can do this in the terminal settings.

**Comment by romkatv** [comment]
Even better -- beam cursor. It's obviously the best 😉

**Comment by arkantos493** [comment]
Thanks. It works like a charm with "I-Beam" (even with blinking enabled).
However, using solid block with blinking disabled worsen the problem (the cursor is only visible at the end of the current line).

**Comment by romkatv** [comment]
> It works like a charm with "I-Beam" (even with blinking enabled).

I-Beam -- *the best* 😼
