### ISSUE TITLE
any way to change specific settings, like prompt style, without running configure?

### ISSUE THREAD

**Issue by sebpn** [romkatv/powerlevel10k#1416]
hi, i want to just play around with prompt styles and the only way i found is to re-run the configuration wizard, which is a little annoying

i can't find where in the config file is the prompt style setting in order to change it faster, where is it?

**Comment by romkatv** [comment]
You can either overwrite the whole config by running `p10k configure` or manually edit `~/.p10k.zsh`. There are no other options for configuring Powerlevel10k. There is no "style" parameter in `~/.p10k.zsh` or anywhere else other than in the configuration wizard.

**Comment by ermissa** [comment]
Being able to skip the config you don't want to change would be great. But this is probably not that easy. I just came accross the same problem and wanted the express my opinion. Thanks for amazing theme.

**Comment by SomeoneIsWorking** [comment]
The problem is I can't figure out what to change in `~/.p10k.zsh`
For example, where is the tail style?
