### ISSUE TITLE
How to always show segments

### ISSUE THREAD

**Issue by Apollorion** [romkatv/powerlevel10k#1418]
I work with Kubernetes all the time and I like that there is a segment that shows me what current context / namespace I am connected to is.

Is it possible to make it always show, like how it always shows me what directory Im in?

I tried adding it to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` but it still only shows when I use the command.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#why-some-prompt-segments-appear-and-disappear-as-im-typing

**Comment by Apollorion** [comment]
> https://github.com/romkatv/powerlevel10k#why-some-prompt-segments-appear-and-disappear-as-im-typing

Perfect, thank you!
