### ISSUE TITLE
Issue icons name branch github

### ISSUE THREAD

**Issue by senotasanchez** [romkatv/powerlevel10k#1419]
hello, I hope you are well as per the attached image, when the repository is initialized, the branch name does not have the last characters:

![image](https://user-images.githubusercontent.com/53236007/119752582-e56b0280-be62-11eb-8e62-82e0a4d9b9e9.png)

do you have any idea how this could be solved?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean
