### ISSUE TITLE
question: weird text after git prompt

### ISSUE THREAD

**Issue by alexisvisco** [romkatv/powerlevel10k#1422]
Hi folk ! 

I have some weird text after the git prompt and I don't know the meaning of them, could someone explain me what mean the `!2 ?1` ? 

![image](https://user-images.githubusercontent.com/17145294/119944876-19464500-bf95-11eb-9d31-b2a8ef27bbcf.png)

Thank's you !

**Comment by romkatv** [comment]
See here: https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean
