### ISSUE TITLE
[Feature Request] Show if HEAD is a wip commit

### ISSUE THREAD

**Issue by lakshayg** [romkatv/powerlevel10k#1425]
In my local installation of p10k, I have edited `~/.p10k.sh` to include this:

```
[[ $(work_in_progress) ]] && res+=" ${modified}[WIP]"
# work_in_progress is defined in oh-my-zsh's git plugin
```

Whenever HEAD's commit message starts with "--wip--", my prompt shows "[WIP]". I think this could be generally useful so starting this thread to discuss if there's interest in including something like this in p10k. If there's interest, I'm happy to give it a try.

**Comment by romkatv** [comment]
I've added `VCS_STATUS_COMMIT_SUMMARY` to gitstatus: https://github.com/romkatv/gitstatus/commit/e193be52899fad2c71a6b049604b1bbdb35b0f68. Your code would look like this:

```zsh
# If HEAD's commit message starts with "--wip--", display "[WIP]" in prompt.
[[ $VCS_STATUS_COMMIT_SUMMARY == '--wip--'* ]] && res+=" ${modified}[WIP]"
```

If you try this, it won't actually work because I haven't released a new version of gitstatus yet. What is the output of `uname -sm` on your system? I can push push a new release for your architecture sooner than for others so that you can try this feature and let me know whether it works for you.

**Comment by lakshayg** [comment]
Thanks for implementing it so quickly. The output of `uname -sm` is `Linux x86_64` on my machine.

**Comment by romkatv** [comment]
> The output of `uname -sm` is `Linux x86_64` on my machine.

I've pushed a release for this architecture. Once you update powerlevel10k, you should be able to use `VCS_STATUS_COMMIT_SUMMARY` in your prompt config. Let me know whether this works for you.

**Comment by tyron** [comment]
I've been wishing for this feature for so long, and today I started actually looking and found you just added this. Perfect timing, thanks to both!
I tried with latest in my local and it's not working with the newest version. I can confirm gitstatus was updated, but echoing `$VCS_STATUS_COMMIT_SUMMARY ` in p10k.sh doesn't output anything. Is it possible that it's not getting set properly?
I'm on macOS, so `uname -sm` translates to `Darwin x86_64`  (and `Darwin arm64` in my Apple Silicon machine).

**Comment by romkatv** [comment]
@tyron I haven't released the new version of gitstatus for darwin yet. I'm waiting for @lakshayg to confirm that it works. Given that he was the one requesting the feature, I want to ensure it has at least one user who's being helped by it (miscommunication happens; sometimes I can implement something that isn't really what's being requested).

**Comment by lakshayg** [comment]
@romkatv This works great

**Comment by romkatv** [comment]
@lakshayg Thanks for the confirmation. I'll release gitstatus for all supported platforms later this week.

**Comment by lakshayg** [comment]
That's great! Will you be creating a follow-up PR for displaying "[wip]" in the shell prompt?

**Comment by romkatv** [comment]
That depends on how widespread the "--wip--" convention is. Where did you get it from?

**Comment by tyron** [comment]
This is a ohmyzsh convention: https://github.com/ohmyzsh/ohmyzsh/wiki/Cheatsheet
Running `gwip` creates a quick commit with that description, and running `gunwip` will revert it.

**Comment by lakshayg** [comment]
Yes, I got this from ohmyzsh

**Comment by romkatv** [comment]
I've released gitstatus and powerlevel10k. If after updating you run `p10k configure`, the new config will contain `my_git_formatter` that displays "wip" when the latest commit's summary contains "wip" or "WIP".

**Comment by lakshayg** [comment]
Thank you. This works great.
