### ISSUE TITLE
prompt has a "?2"

### ISSUE THREAD

**Issue by dragonBall561** [romkatv/powerlevel10k#1426]
I am on windows wsl, and installed the recommended MesloLGS NF font on Windows Terminal. Whenever I am in a git repo, it has a ?2 at the end of the prompt:

![image](https://user-images.githubusercontent.com/61358474/120075323-c8a31a80-c06e-11eb-94a0-0d79312de66f.png)

how do I fix this?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean
