### ISSUE TITLE
_p9k_worker_start:sysopen:6: can't open file /proc/self/fd/11: no such file or directory

### ISSUE THREAD

**Issue by nzkller** [romkatv/powerlevel10k#1427]
Hello,

I’m installing power10k on ISH iPad Pro and it seems that has an issue when try to run power10k. Ohmyzsh has been working correctly for me so far, but I love Power10k.

Is this something that can be fixed? I’m having the following error

_p9k_worker_start:sysopen:6: can't open file /proc/self/fd/11: no such file or directory

I enabled the debug for the gift status and the output is the following:

> [ERROR]: gitstatus failed to initialize.
  Zsh log (/tmp/gitstatus.POWERLEVEL9K.0.4.1622509813.1.xtrace.log):
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'Linux version 4.20.69-ish iSH 1.2 (149) Apr 26 2021 08:14:51' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.0.4.1622509813.1.lock
    +(anon):15> [[ 15 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ linux-musl == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /proc/self/fd/14
    (anon):sysopen:41: can't open file /proc/self/fd/14: no such file or directory
    +(anon):41> return
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
  Daemon log (/tmp/gitstatus.POWERLEVEL9K.0.4.1622509813.1.daemon.log):
    +_gitstatus_daemon_p9k_:3> local pgid=28
    +_gitstatus_daemon_p9k_:4> [[ 28 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.0.4.1622509813.1.lock
    _gitstatus_daemon_p9k_:zsystem:93: failed to open /tmp/gitstatus.POWERLEVEL9K.0.4.1622509813.1.lock for writing: no such file or directory
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
  System information:
    zsh:      5.8
    uname -a: Linux iPad 4.20.69-ish iSH 1.2 (149) Apr 26 2021 08:14:51 i686 Linux
  If you need help, open an issue and attach this whole error message to it:
    https://github.com/romkatv/gitstatus/issues/new
_p9k_worker_start:sysopen:6: can't open file /proc/self/fd/11: no such file or directory                                                                        
prompt_vcs:17: vcs_info: function definition file not found

This is the M1 iPad Pro, I’m not sure of it makes a difference.

Thank you in advance and best regards,

CD

**Comment by romkatv** [comment]
This is caused by a bug in iSH: https://github.com/ish-app/ish/issues/783

**Comment by nzkller** [comment]
Thank you! I saw your comments, but it seems they don't know how to fix it!

Great job on power10k.

Best regards,

CD

**Comment by romkatv** [comment]
> Great job on power10k.

Thanks! Great job on Ibit.

**Comment by G2Jose** [comment]
@romkatv curious if there's a way to just disable something powerlevel10k to make this error go away for users on iSH (totally understand that the root cause is a bug in iSH and not here)

**Comment by romkatv** [comment]
You can comment out `vcs` within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` in `~/.p10k.zsh`.

**Comment by G2Jose** [comment]
I already tried that but I'm still seeing: 
> _p9k_worker_start:sysopen:12: can't open file /proc/self/fd/11: no such file or directory

This is what the relevant lines look like on `~/.p10k.zsh`: 

```shell
  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon               # os identifier
    dir                     # current directory
    # vcs                     # git status
    # prompt_char           # prompt symbol
  )
```

Also this is what the last few lines in my .zshrc look like: 

```shell
ZSH_THEME="powerlevel10k/powerlevel10k"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
POWERLEVEL9K_DISABLE_GITSTATUS=true
```

**Comment by romkatv** [comment]
Oh, I see. It's from the async worker, which is launched if at least one prompt segment requires it. Neither `os_icon` nor `dir` require the async worker but something in your `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` does. Try to remove everything from it. If that helps, try enabling things you need one by one.

Also, remove `POWERLEVEL9K_DISABLE_GITSTATUS=true` from `.zshrc`. It doesn't do anything good.
