### ISSUE TITLE
Issue on Macbook using powerlevel 10k with ohmyzsh

### ISSUE THREAD

**Issue by bhattacharyyasom** [romkatv/powerlevel10k#1431]
I am facing the following errors when starting up the shell.
I am on MacOS + iTerm + ohmyZSH.

/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 14: local: can only be used in a function
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 18: builtin: setopt: not a shell builtin
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 20: ((: $+__p9k_root_dir : syntax error: operand expected (error token is "$+__p9k_root_dir ")
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 20: ${${(%):-%x}:A:h}: bad substitution
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 21: ((: $+__p9k_intro : syntax error: operand expected (error token is "$+__p9k_intro ")
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 25: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 30: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 31: ${${__p9k_intro_base/ match / match reply }/ MATCH / MATCH REPLY }: bad substitution
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 33: zmodload: command not found
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 47: syntax error near unexpected token `)'
/Users/somshankerb/powerlevel10k/powerlevel10k.zsh-theme: line 47: `() {'

**Comment by romkatv** [comment]
The errors indicate that you are trying to load Powerlevel10k in bash. Powerlevel10k can only be loaded in zsh.
