### ISSUE TITLE
Icons not in good padding and stay close to directories 

### ISSUE THREAD

**Issue by Henry-Ta** [romkatv/powerlevel10k#1433]
Please see my photo below for more details. 

The icons not stay in the middle of space but slightly close to the right. I'm using "Cascadia Code" on kitty. Please guide me how to fix this. 

![Screenshot_2021-06-02_11-10-00](https://user-images.githubusercontent.com/59848305/120531247-475fc680-c393-11eb-94fe-5502270b09b8.png)

**Comment by romkatv** [comment]
That's an issue with the font you are using. If you don't like it, file a bug against the font.

The [recommended font](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k) doesn't have this issue.

**Comment by John-Gee** [comment]
I have the same issue using the recommended font in Konsole.

Padding set to none:

![image](https://github.com/romkatv/powerlevel10k/assets/1646210/aec6be74-694d-4ba8-8b98-461a093ccacb)


Padding set to moderate:
![image](https://github.com/romkatv/powerlevel10k/assets/1646210/ca1e83c7-3561-479f-8f3d-1bf13e08f14b)

How can all spacing around the icons be removed, and maybe after the sharp ends too?
Thanks!

**Comment by romkatv** [comment]
This is not the recommended font. Try the recommended font instead.

**Comment by John-Gee** [comment]
Wow thanks for the quick reply, but that's all I see when installing the fonts from https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k .

```
fc-list |  rg -i meslo
/usr/share/fonts/TTF/MesloLGS-NF-Bold-Italic.ttf: MesloLGS NF:style=Bold Italic
/usr/share/fonts/TTF/MesloLGS-NF-Italic.ttf: MesloLGS NF:style=Italic
/usr/share/fonts/TTF/MesloLGS-NF-Regular.ttf: MesloLGS NF:style=Regular
/usr/share/fonts/TTF/MesloLGS-NF-Bold.ttf: MesloLGS NF:style=Bold
```

```
pacman -Ql ttf-meslo-nerd-font-powerlevel10k
ttf-meslo-nerd-font-powerlevel10k /usr/
ttf-meslo-nerd-font-powerlevel10k /usr/share/
ttf-meslo-nerd-font-powerlevel10k /usr/share/fonts/
ttf-meslo-nerd-font-powerlevel10k /usr/share/fonts/TTF/
ttf-meslo-nerd-font-powerlevel10k /usr/share/fonts/TTF/MesloLGS-NF-Bold-Italic.ttf
ttf-meslo-nerd-font-powerlevel10k /usr/share/fonts/TTF/MesloLGS-NF-Bold.ttf
ttf-meslo-nerd-font-powerlevel10k /usr/share/fonts/TTF/MesloLGS-NF-Italic.ttf
ttf-meslo-nerd-font-powerlevel10k /usr/share/fonts/TTF/MesloLGS-NF-Regular.ttf
```

(I used the PKGBUILD from AUR but made sure to grab the files manually, though they were a match.)
Or is Konsole not showing me the right font? Because it is not showing me any iosevka so it's clearly possible that those are missing too.

Thank you!
