### ISSUE TITLE
Confusion between conda and venv Python3 environments

### ISSUE THREAD

**Issue by malfroid** [romkatv/powerlevel10k#1434]
Screenshot:

<img width="658" alt="terminal" src="https://user-images.githubusercontent.com/3715399/120637648-73e91080-c46f-11eb-8741-fb5f7b464ec7.png">

Problem 1: it is not so clear what is conda and what is venv.
Possible solution: use the conda logo instead of the python logo next to the conda environment name in the prompt?
<img width="658" alt="terminal conda logo" src="https://user-images.githubusercontent.com/3715399/120637701-8400f000-c46f-11eb-9686-93dc35a55080.png">

Problem 2: when alternating between conda and venv Python3 environments, I don't know which python binary is currently active
Possible solution: do not show both the activated conda and venv environments in the prompt, but only the environment which is actually used when I run `python`?
<img width="658" alt="terminal only show the current active python env" src="https://user-images.githubusercontent.com/3715399/120637730-89f6d100-c46f-11eb-935d-b950172aa877.png">

**Comment by romkatv** [comment]
To change the icon of `conda` prompt segment, open `~/.p10k.zsh`, search for `POWERLEVEL9K_ANACONDA_VISUAL_IDENTIFIER_EXPANSION`, uncomment it and set the value to the icon of your choice.

To hide `virtualenv` when `python` command is from conda, add this to `~/.p10k.zsh`:

```zsh
function p10k-on-pre-prompt() {
  if [[ $commands[python] == /usr/local/Caskroom/miniconda/* ]]; then
    p10k display '1/right/virtualenv'=hide '1/right/conda'=show
  else
    p10k display '1/right/virtualenv'=show '1/right/conda'=hide
  fi
}
```

**Comment by malfroid** [comment]
Thank you for the fast response! I added the snippet to `~/.p10k.zsh` and tested, it does exactly what I wanted.

In order to define the conda icon for POWERLEVEL9K_ANACONDA_VISUAL_IDENTIFIER_EXPANSION. I assume I need to have a font installed that includes the conda icon? Do you know any such font, or do you know how I can request to add the conda icon to the font MesloLGS NF?

**Comment by romkatv** [comment]
I don't have a font wit the Conda logo and I don't know where you can request such font to be made. My practical advice would be to use plain "C" -- you'll know what it means. You can also add the glyph to a font manually with FontForge (a free tool for editing fonts).
