### ISSUE TITLE
_p9k_prompt_length:4: bad math expression: operand expected at `) '

### ISSUE THREAD

**Issue by bsander** [romkatv/powerlevel10k#1435]
Hello! I'm using p10k through zsh4humans and while I love the experience, except for this little error which shows up in every new session I start and I have no idea how to address it:

```
_p9k_prompt_length:4: bad math expression: operand expected at `) '
```

I located the function and put `set -x` there, which results in the following:

```
+_p9k_prompt_length:2> local -i COLUMNS=1024
+_p9k_prompt_length:3> local -i x y=0 m
+_p9k_prompt_length:4> ((  y  ))
+_p9k_prompt_length:14> typeset -g _p9k__ret=0
+_p9k_prompt_length:2> local -i COLUMNS=1024
+_p9k_prompt_length:3> local -i x y=19 m
+_p9k_prompt_length:4> ((  y  ))
+_p9k_prompt_length:5> ((  0  ))
+_p9k_prompt_length:9> ((  y > x + 1  ))
+_p9k_prompt_length:10> ((  m = x + (y - x) / 2  ))
+_p9k_prompt_length:11> ((  y = m  ))
+_p9k_prompt_length:9> ((  y > x + 1  ))
+_p9k_prompt_length:10> ((  m = x + (y - x) / 2  ))
+_p9k_prompt_length:11> ((  y = m  ))
+_p9k_prompt_length:9> ((  y > x + 1  ))
+_p9k_prompt_length:10> ((  m = x + (y - x) / 2  ))
+_p9k_prompt_length:11> ((  y = m  ))
+_p9k_prompt_length:9> ((  y > x + 1  ))
+_p9k_prompt_length:10> ((  m = x + (y - x) / 2  ))
+_p9k_prompt_length:11> ((  x = m  ))
+_p9k_prompt_length:9> ((  y > x + 1  ))
+_p9k_prompt_length:14> typeset -g _p9k__ret=1
```

But beyond this I have no idea how to find out what's wrong. 

Here's my p10k config: https://github.com/bsander/dotfiles/blob/a9ec08ff409cc3f9f3fc272f4e4dc6149c804b22/dotfiles/p10k.zsh

**Comment by romkatv** [comment]
Please attach your `~/.zshrc` and `~/.zshenv`.

**Comment by romkatv** [comment]
I see that you have a lot of dotfiles. Can you produce a smaller set of files that would demonstrate the issue?

Start with the default `~/.zshrc` and `~/.zshenv` from zsh4humans and put only `POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true` in `~/.p10k.zsh`. Does this still trigger the error? If not, what do you need to change to trigger it?

**Comment by bsander** [comment]
Hi! I traced the problem down to this line:

```zsh
export PROMPT_EOL_MARK='%'
```

I believe the `%` sign has a special meaning here, so it's probably a misconfiguration on my end. Changing that value to something else seems to get rid of the problem.

Thanks for the help!
