### ISSUE TITLE
kubecontext not showing

### ISSUE THREAD

**Issue by nikola-n6c** [romkatv/powerlevel10k#1436]
Hi, wanted to give kubecontext a spin. For some reason using out-of-the-box config, context is not displayed when typing kubectl. So I tried to add it to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` as in:
```typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    dir                     # current directory
    kubecontext
    vcs                     # git status

    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )
```
to make sure I didn't mess up right prompt or "show on command" somehow. But still no luck:
```
~/go/src/k8s.io/apimachinery master 
>
```
`POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION` are unchanged. 
Any ideas on how to debug this? Could it be a somewhat complex kubeconfig file I have? Any way to test the parsing separately? 
Thanks!

**Comment by romkatv** [comment]
What do you expect to see?

**Comment by nikola-n6c** [comment]
Ah my bad, I had unset the context earlier. Thanks for taking a look!
