### ISSUE TITLE
I can't run the command [p10k configuration]

### ISSUE THREAD

**Issue by ManelRosPuig** [romkatv/powerlevel10k#1437]
Hey!

I just installed this theme in my Arch Linux. I follow the installation instructions. I just run these two commands:
1. [yay -S --noconfirm zsh-theme-powerlevel10k-git]
2. [echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc]

After that, I tried to run the command [p10k configure], but it says "command not found". I don't understand, I just followed the instructions. Can someone help me? I am not very good at Linux.

**Comment by romkatv** [comment]
Run `exec zsh` and try again.

**Comment by ManelRosPuig** [comment]
Oh, thank you! :)
