### ISSUE TITLE
home directory git status not showing

### ISSUE THREAD

**Issue by TrentonAdams** [romkatv/powerlevel10k#1438]
I store common settings of things in my home directory in a git repo.  It seems powerlevel10k doesn't support that, as the git status shows anywhere except in my home directory.

![image](https://user-images.githubusercontent.com/534192/121120931-d75e9f80-c7db-11eb-86ae-5f3c2920fc15.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#why-is-git-status-from-homegit-not-displayed-in-prompt

**Comment by TrentonAdams** [comment]
Oh, sorry about that.
