### ISSUE TITLE
Configuration wizard differs significantly from what is shown in the README

### ISSUE THREAD

**Issue by respondcreate** [romkatv/powerlevel10k#1442]
Just installed today (Mac OSX + iTerm2) and, when I run `p10k configure` I get a significantly different configuration options than what is shown under the Features > Configuration Wizard. I installed the recommended font (with iTerm2).

When I run `p10k configure` I don't see any options for Lean / Classic / Rainbow / Pure instead, I get asked to see if I see a Diamond , Lock, Debian, Logo etc.

After that it I get prompted for:
1. Character set (unicode or ascii)
2. Show current time (no, 24-hour or 12-hour)
3. Prompt height (one or two lines)
4. Prompt connection (disconnected, dotted or solid)
5. Prompt frame (no frame, left, right or full)
6. Connection frame and color (black, white, green or blue)
7. Prompt spacing (compact or sparse)
8. Icons (few or many)
9. Prompt flow (concise or fluent)
10. Enable transient prompt (yes or no)
11. Instant prompt mode (verbose, quiet or off)
12. Overwrite (yes, restart or quit)

I just installed it today following the installation instructions exactly as listed in the README but never get prompted for Lean, Classic, Rainbow or Pure) Is there something obvious I'm missing that needs to be done before running `p10k configure` to get prompted for that?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by romkatv** [comment]
From the list of screens you've listed it looks as if your terminal doesn't support 256 colors. You can verify with `print $terminfo[colors]`. If this command outputs "16", that's the problem. This is usually caused by incorrect `TERM` variable. If your configs (`~/zshrc`, etc.) set `TERM`, remove that line and restart your terminal. If this doesn't help, open terminal settings, find `TERM` override in them and revert to the default.

**Comment by respondcreate** [comment]
> This is usually caused by incorrect `TERM` variable. If your configs (`~/zshrc`, etc.) set `TERM`, remove that line and restart your terminal. If this doesn't help, open terminal settings, find `TERM` override in them and revert to the default.

This was the source of the issue, thanks so much @romkatv ! Here was the offending line:

    [ $TERM != "screen" ]] && exec tmux

**Comment by respondcreate** [comment]
For anyone who comes here in the future and is wondering about how to get TMUX & powerlevel10k to play  together nicely, here's how I had to modify my dotfiles:

1. Add `set -g default-terminal "screen-256color"` to `.tmux.conf`.
2. Add these lines to `.zprofile`: 
    ```bash
    alias tmux="TERM=xterm-256color tmux"
    export TERM=screen-256color
    if [ "$TMUX" = "" ]; then tmux; fi
    ```
3.  Restart your tmux server this command: `tmux kill-server && tmux`
4. Quit your terminal app (not just close the window, run ⌘ + Q).
5. Restart your terminal and you should be good to go!

**Comment by romkatv** [comment]
Step 1 is good. Step 2 looks weird. This should work fine:

```zsh
[[ -n $TMUX ]] || exec tmux
```

None of this is specific to powerlevel10k, so it's kind of off-topic here.

Alternatively to all of this, you could use zsh4humans and answer "yes" when asked whether you want tmux.

**Comment by respondcreate** [comment]
> Step 1 is good. Step 2 looks weird. This should work fine:
> 
> ```shell
> [[ -n $TMUX ]] || exec tmux
> ```

You were right, I removed those other bits and substituted this line and it worked perfectly.

> None of this is specific to powerlevel10k, so it's kind of off-topic here.

Noted!

> Alternatively to all of this, you could use zsh4humans and answer "yes" when asked whether you want tmux.

Wasn't aware of that package (I just recently moved to zsh) so thanks for the heads up, @romkatv !
