### ISSUE TITLE
Not getting a prompt for the slanted bars.

### ISSUE THREAD

**Issue by norogoth** [romkatv/powerlevel10k#1443]
Here is what my terminal looks like:

![2021-06-09_11_19_20- an_z_frontend](https://user-images.githubusercontent.com/52639031/121608046-06585980-ca06-11eb-84e1-ef98f7b42d69.png)

Here is what I wanted it to look like

![2021-06-09_11_17_27-Make_your_WSL_or_WSL2_terminal_awesome_-_with_Windows_Terminal_zsh_oh-my-zsh_a](https://user-images.githubusercontent.com/52639031/121608063-0e17fe00-ca06-11eb-9a53-b6846cf90c24.png)

I tried to get my fonts loaded as well by following these instructions.

> Windows Terminal by Microsoft (the new thing): Open Settings (Ctrl+,), search for fontFace and set value to MesloLGS NF for every profile.

Here is what I get. I get a JSON file which does not contain the line "fontFace" and there is no option to edit the fontFace in the GUI.

![2021-06-10 16_05_43-Window](https://user-images.githubusercontent.com/52639031/121608206-546d5d00-ca06-11eb-93c6-23ed344d60ff.png)

**Comment by norogoth** [comment]
https://paste.gg/p/anonymous/7ca90cec1209487fa15211968589571b - This is what I see in the settings.JSON. Should I add "fontFace: 'MesloLGS NF' " to this file somewhere?

**Comment by romkatv** [comment]
Yes.

**Comment by norogoth** [comment]
Wonderful. This issue is resolved. Thank you for your assistance.

For future reference, I added this to a color theme area in the JSON.
