### ISSUE TITLE
can't fetch gitstatusd when starting up the shell

### ISSUE THREAD

**Issue by D0nnieD4rk0** [romkatv/powerlevel10k#1444]
[powerlevel10k] fetching gitstatusd .. -
[ERROR]: gitstatus failed to initialize.

Failed to download gitstatusd-linux-x86_64 from any mirror:

  1. https://github.com/romkatv/gitstatus/releases/download/v1.5.1/gitstatusd-linux-x86_64.tar.gz
  2. https://gitee.com/romkatv/gitstatus/raw/release-v1.5.1/release/gitstatusd-linux-x86_64.tar.gz

Check your internet connection, then restart your shell.

...this a common issue ?

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
() {
  emulate -L zsh -o xtrace
  if (( $+commands[curl] )); then
    command curl -fsSL -- https://github.com/romkatv/gitstatus/releases/download/v1.5.1/gitstatusd-linux-x86_64.tar.gz >/dev/null
  else
    command wget -O - -- https://github.com/romkatv/gitstatus/releases/download/v1.5.1/gitstatusd-linux-x86_64.tar.gz >/dev/null
  fi
  print -r -- $?
}
```

**Comment by D0nnieD4rk0** [comment]
just booted my comp back up and it works fine now, sorry for wasting time on something that got fixed by a restart
