### ISSUE TITLE
[Feature Request] Config File Or Configuration Wizard Options To Specify Segments

### ISSUE THREAD

**Issue by Rayqan** [romkatv/powerlevel10k#1446]
Would you consider adding a way (config file/wizard options/anything else) to specify which segments you want to use and therefore only add relevant config options into the powerlevel10k config file. I personally like to keep my configs as clean as possible and since I only use a select few segments I tend to have a lot of unnecessary settings in my p10k config. Generally I would just delete these manually but as the config file starts out at 1500+ lines this is quite tedious.

Regardless of your decision, thanks for making p10k this theme's feature set and performance is unparalleled.

**Comment by romkatv** [comment]
I see your point. Adding extra steps to the wizard makes it longer to go through it. The benefit does not seem worth it.

**Comment by Rayqan** [comment]
Any way you deem best would work for me. I would lean towards an optional config file which simply functions as a list of desired segments. Perhaps an environment variable functioning in a similar manner could also work?

**Comment by romkatv** [comment]
Valid feature request but not something I'm willing to spend my time on. The amount of time it would save you is likely small or even negative. My personal recommendation is to leave the config as is. If extra parameters bother you, go ahead and delete them.
