### ISSUE TITLE
nvm: ALWAYS_SHOW and SHOW_SYSTEM options

### ISSUE THREAD

**Issue by 0xallie** [romkatv/powerlevel10k#1447]
It would be nice to have more options with nvm that are available with nodenv:

* Show prompt even if it matches global version
* Hide `system` from prompt

**Comment by Machine-Maker** [comment]
Yeah, I just spent a few minutes trying to figure out why `system` was showing up for me everywhere.

**Comment by romkatv** [comment]
> * Show prompt even if it matches global version

This can now be enabled with `POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW=true`.

> * Hide `system` from prompt

This can now be enabled with `POWERLEVEL9K_NVM_SHOW_SYSTEM=false`.

Thanks to @zaidhaan for implementing these new parameters!
