### ISSUE TITLE
Duplicate lines after any command when tmux is open

### ISSUE THREAD

**Issue by ysl2** [romkatv/powerlevel10k#1448]
In this gif, you can see:

Tmux is opened first

then, I did not input any command, and opened a new tmux pane, p10k preformed normal.

after I executed `l` (alias to `ls`), and opened a new tmux pane, it generated duplicate lines.

![Peek 2021-06-15 08-41](https://user-images.githubusercontent.com/39717545/121976219-f6e66100-cdb5-11eb-8489-9aed30a0aad2.gif)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by ysl2** [comment]
> See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

Thank you :-)
