### ISSUE TITLE
Theme not working properly

### ISSUE THREAD

**Issue by sudip-mondal-2002** [romkatv/powerlevel10k#1449]
I installed zshrc and used the theme powerlevel10k but it's not showing in the terminal properly

![image](https://user-images.githubusercontent.com/74463091/122332777-a6593a00-cf54-11eb-8689-d7fa8beeffcb.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by sudip-mondal-2002** [comment]
Thank you, I got it
