### ISSUE TITLE
Long directory paths confuse prompts

### ISSUE THREAD

**Issue by mcandre** [romkatv/powerlevel10k#1450]
powerlevel10k is generally decent at handling deep current working directory paths. However, when I change directory just one level further into `jenkins_resources/`, then somehow the abbreviation logic gets confused.

The ENTIRE right prompt disappears. Normally that only happens when my live typing begins to collide with the right prompt characters. But this is happening for me even before I type anything. There is plenty of screen real estate left to show both my commands, and my left prompt dollar (`$`) and my right prompt, but alas zsh is not abbreviating the CWD correctly when rendering the right prompt.

https://github.com/mcandre/dotfiles

**Comment by romkatv** [comment]
I guessing you are using a single-line prompt? In this case powerlevel10k by default tries to reserve at least 40 columns and at least 50% of the terminal width for you to type commands. If after maximally shortening the current directory the gap between the left and the right prompt is smaller than the goal, right prompt is removed. This is configurable: https://github.com/romkatv/powerlevel10k/blob/4ba3c010f6fa66dcf7d785251c80c416454b6e90/config/p10k-lean.zsh#L260-L265

P.S.

Two-line prompt is better. The biggest downside of two-line prompt is that it wastes a lot of vertical space in scrollback, but this downside doesn't exist in powerlevel10k if you enable transient prompt. See https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard
