### ISSUE TITLE
Web Package got an extra space

### ISSUE THREAD

**Issue by tsunheang** [romkatv/powerlevel10k#1452]
Web Package icon has an extra space between the icon and the version number, compare to other segments.

If your prompt has line on the tail, the tail on the first line miss the tail on the second line (sorry haven't captured this one)

<img width="309" alt="Screen Shot 2021-06-19 at 5 51 10 pm" src="https://user-images.githubusercontent.com/44729117/122640070-93e32a00-d127-11eb-9373-4e9770535a73.png">

**Comment by romkatv** [comment]
Looks like a bug in your terminal. Please run the following command and post a screenshot:

```zsh
print -r $'\uF8D6 xyz\n   ^\nthe arrow must point at "y"'
```

**Comment by tsunheang** [comment]
You are right, something wrong on my part. Any Solution?

<img width="675" alt="Screen Shot 2021-06-19 at 7 09 22 pm" src="https://user-images.githubusercontent.com/44729117/122641834-e295c180-d131-11eb-9032-5232d12180d2.png">

**Comment by romkatv** [comment]
There are two workarounds.

1. Use a different terminal. On macOS good alternative terminals include iTerm2 and Kitty.
2. Replace the package icon with something else. To do that, open `~/.p10k.zsh`, find `POWERLEVEL9K_PACKAGE_VISUAL_IDENTIFIER_EXPANSION`, uncomment it and change its value.
   ```zsh
   typeset -g POWERLEVEL9K_PACKAGE_VISUAL_IDENTIFIER_EXPANSION='pkg'
   ```

**Comment by tsunheang** [comment]
Thanks for the solutions.

I'll think, I will go with iTerm2 option. I have used it before but haven't install one on this machine yet. The built-in terminal capability is always limited.

Anyway, Great Job on PowerLevel10K theme! It literally blew my mind. I remember tinkering with bash script to make my own terminal in the past; it was brutal.

Thanks for building such a great project! 😁
