### ISSUE TITLE
I don't get the prompt I want when I run "su"

### ISSUE THREAD

**Issue by Toadfield** [romkatv/powerlevel10k#1453]
When I run "su" cause I sometimes want to do multiple things as root without the need to type my password every time,then the prompt looks like this:
![image](https://user-images.githubusercontent.com/68649672/122666322-db5fc980-d1ac-11eb-8905-089f4bdac2ed.png)
But it normally looks like this:
![image](https://user-images.githubusercontent.com/68649672/122666332-e61a5e80-d1ac-11eb-8e1f-be2bc262edbc.png)

**Comment by romkatv** [comment]
Try `sudo zsh` instead.

**Comment by Toadfield** [comment]
thanks,that works
