### ISSUE TITLE
[Question] Is there a way to remove that Linux logo?

### ISSUE THREAD

**Issue by Toadfield** [romkatv/powerlevel10k#1454]
I mean this:
![image](https://user-images.githubusercontent.com/68649672/122666361-fdf1e280-d1ac-11eb-8a9f-aff5fee99a55.png)
I don't need it,cause I know that I use Linux anyway lol

**Comment by romkatv** [comment]
You also don't need that house icon because you can already see your current directory `~`. These icons are just for decoration, they convey little to no information. To get rid of them, run `p10k configure` and select "few icons" instead of "many icons" that you've selected previously.

**Comment by Toadfield** [comment]
thanks
