### ISSUE TITLE
Show local env var in prompt if set

### ISSUE THREAD

**Issue by patrickhener** [romkatv/powerlevel10k#1455]
I have this script called netns.sh which will let you put Ethernet devices in isolation using network namespaces in linux. So it will have $NETNS set in the env to a name. Like if you do `sudo netns.sh start -n MyName eth0` it will isolate eth0 in a network namespace called *MyName*. I would love to have my prompt say `[NS: MyName]` somewhere on the left hand side if the ENV var is set, so I can recognise when I am in that namespace and when not.

I tried to understand what is happening in .p10k.zsh but can not handle to implement this. Can you provide guidance on how to do it?

Thanks in advance.

**Comment by romkatv** [comment]
1. Open `~/.p10k.zsh`.
2. Add this:
   ```zsh
   # Prompt segment "my_ns". Displays $NETNS.
   function prompt_my_net_ns() {
     if [[ -n $NETNS ]]; then
       p10k segment -b yellow -f red -i "NS" -t "$NETNS"
     fi
   }
   ```
3. Add `my_net_ns` somewhere within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.
4. Restart zsh with `exec zsh`.

See `p10k help segment` for help.

**Comment by patrickhener** [comment]
Dude awesome, thanks!
