### ISSUE TITLE
Terminal is showing a strange path at the beggining

### ISSUE THREAD

**Issue by NicolasBonet** [romkatv/powerlevel10k#1456]
Hello everyone!

I just wanted to report the following issue showing in both VSCode and iTerm2:

![image](https://user-images.githubusercontent.com/13696500/123148528-f5581100-d425-11eb-82e1-22649a61ef29.png)

I'm not entirely sure of what ~ /Doc/R/t/0m is, in case in matters I'm using an M1 Mac Mini.

**Comment by romkatv** [comment]
Yep, that's a feature. https://github.com/romkatv/powerlevel10k#current-directory-that-just-works
