### ISSUE TITLE
Powerline font symbols will not display

### ISSUE THREAD

**Issue by ItsElectra** [romkatv/powerlevel10k#1458]
I've installed the recommended powerline font and set it to the font used in my terminal emulator (Terminator) and the symbols are missing.
![image](https://user-images.githubusercontent.com/59057998/123305104-ba211500-d4ed-11eb-9b96-56f2b19b4404.png)
This is what it looks like. ^^^
![image](https://user-images.githubusercontent.com/59057998/123305234-e341a580-d4ed-11eb-898a-f1181bc5d072.png)
This is what it SHOULD look like ^^^
Help?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard. My guess is that your don't have a UTF-8 locale. You can verify with `locale -a`.

**Comment by ItsElectra** [comment]
![image](https://user-images.githubusercontent.com/59057998/123318045-c82a6200-d4fc-11eb-8b6d-8d5393f76cf0.png)
nope. that's not it

**Comment by romkatv** [comment]
See those errors? They are the culprit. You need to install a utf-8 locale.

**Comment by ItsElectra** [comment]
oh \:I

**Comment by ItsElectra** [comment]
got it
thanks!
