### ISSUE TITLE
Change icons of Home Folders, and subfolders

### ISSUE THREAD

**Issue by mariomegu** [romkatv/powerlevel10k#1459]
Hi guys, how can I change the icons for Start (\ uF015) and Folders (\ uF07C)?

Try modifying the .oh-my-zsh / custom / themes / powerlevel10k / internal / icons.zsh file but it doesn't change

and the .p10k.zsh file I don't know how to change them
![ohmyzsh](https://user-images.githubusercontent.com/54611021/123309454-8e506000-d4ea-11eb-92d4-88e8a7c1358a.png)

**Comment by romkatv** [comment]
```zsh
POWERLEVEL9K_HOME_ICON='bla'
POWERLEVEL9K_HOME_SUB_ICON='bla'
```

**Comment by mariomegu** [comment]
Should I add those two lines to the .p10k.zsh file?

**Comment by romkatv** [comment]
Yes.

**Comment by mariomegu** [comment]
excellent, thank you very much, excellent project
![ohmyzsh_correct](https://user-images.githubusercontent.com/54611021/123310564-d459f380-d4eb-11eb-9cd4-91ff087b68f1.png)

**Comment by romkatv** [comment]
You are welcome.
