### ISSUE TITLE
ruby version not fully shown in rbenv section

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [romkatv/powerlevel10k#146]
The ruby version is not fully shown (only the first character) in the `rbenv` section.
For example `rbenv version-name` prints `jruby-9.2.5.0` but only `j` in the prompt.
When the local version is (ruby) `2.5.3` nothing is shown in the prompt.

Both versions work with https://github.com/Powerlevel9k/powerlevel9k

**Comment by romkatv** [comment]
Please post the output of the following command:

```zsh
() {
  emulate -L zsh
  setopt xtrace
  uname -a
  rbenv version
  bash -x =rbenv version
  rbenv global
  bash -x =rbenv global
  typeset -m 'ZSH_VERSION|RBENV*|POWERLEVEL9K_*'
}
```

**Comment by romkatv** [comment]
I think this could've been caused by unusual `IFS`. I've submitted a fix that sets `IFS` to its default when building prompt.

Could you update powerlevel10k and try again? If it still doesn't work, please send me the output of the command from my previous comment.

**Comment by brandonb927** [comment]
I inadvertently [reported this on Twitter](https://twitter.com/brandonb927/status/1157072673928695808) earlier today without checking the issues in the repo here first, however after @romkatv pointed me at this issue and after updating p10k I can report that it now works correctly 🎉

**Comment by romkatv** [comment]
Awesome! Thanks, @brandonb927.

@ThomasKoppensteiner, please reopen if this doesn't work for you after updating to the latest version.

**Comment by ThomasKoppensteiner** [comment]
@romkatv the latest version fixed it for me as well. Thank you!

**Comment by romkatv** [comment]
Thanks for the confirmation and for reporting the bug in the first place! 🤗
