### ISSUE TITLE
Replacement for POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX ?

### ISSUE THREAD

**Issue by skotambkar** [romkatv/powerlevel10k#1460]
Tried setting `POWERLEVEL10K_MULTILINE_FIRST_PROMPT_PREFIX= "%f"` but seems it isn't supported. This results in prompts sticking to each other and creates an awkward apperance. 

Is there a replacement for `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX`?

**Comment by romkatv** [comment]
Yes. It's called `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX`.

**Comment by skotambkar** [comment]
So it's the same?

**Comment by romkatv** [comment]
Yes.
