### ISSUE TITLE
How to show only the venv symbol under virtualenv and suppress the username

### ISSUE THREAD

**Issue by avatar-lavventura** [romkatv/powerlevel10k#1461]
`powerlevel10k` shows: venv section as `(x) alper` (`symbal <username>`) ; is it possible to show only the symbol and suppress the user name?

Normal output:

<img width="157" alt="image" src="https://user-images.githubusercontent.com/18537398/123408208-6d087600-d5b5-11eb-8274-69a1ca89a4d1.png">

Wanted output:

<img width="157" alt="Screen Shot 2021-06-25 at 13 21 30" src="https://user-images.githubusercontent.com/18537398/123410687-426bec80-d5b8-11eb-9f59-9400f6de5dfe.png">

My setting:

```
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
      virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
      ...
)

typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
```
I have advised to ask a new question  https://github.com/romkatv/powerlevel10k/issues/730#issuecomment-868251948.

**Comment by romkatv** [comment]
Try this:

```zsh
# Replace the content of virtualenv segment with an empty value.
typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION=
```
