### ISSUE TITLE
_p9k_declare:34: character not in range 

### ISSUE THREAD

**Issue by horseinthesky** [romkatv/powerlevel10k#1462]
Hi.
Trying to run my [p10k](https://github.com/horseinthesky/dotfiles/blob/master/files/zsh/p10k.zsh) config in lxc Arch container and getting:
```
(anon):299: character not in range
_p9k_declare:34: character not in range 
```
There is probably something missing inside the container but I have no clue how to find what exactly.

**Comment by romkatv** [comment]
Try installing a utf-8 locale.

**Comment by horseinthesky** [comment]
> Try installing a utf-8 locale.

Thank you.

Uncommenting
```
en-US.UTF-8 UTF-8
```
in `/etc/locale.gen`

Then running `locale-gen` after and finally `echo "LANG=en_US.UTF-8" > /etc/locale.conf` did the trick.

**Comment by romkatv** [comment]
👍
