### ISSUE TITLE
Change OS Icon to windows icon

### ISSUE THREAD

**Issue by crydotsnake** [romkatv/powerlevel10k#1463]
Hello,

i use powerlevl10k inside WSL2 with Ubuntu, and i would like to know if i could replace the OS icon with the windows icon.

Cheers!

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`, uncomment it and set the value to anything you like. For example:

```zsh
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF17A'
```

**Comment by crydotsnake** [comment]
Thanks a lot! <3

**Comment by crydotsnake** [comment]
Is there something in the docs where those values `\uF17A` are documented?

**Comment by crydotsnake** [comment]
For example which values are available

**Comment by romkatv** [comment]
This is zsh syntax for specifying symbols by their UNICODE numbers. You can use Character Map (it comes preinstalled in Windows) to inspect fonts and to find suitable symbols. You can also use https://www.nerdfonts.com/cheat-sheet. Note that none of this is specific to powerlevel10k.

**Comment by crydotsnake** [comment]
Ahh okay, thanks a lot!
