### ISSUE TITLE
Glitching while maximize.

### ISSUE THREAD

**Issue by Sudeep-Sharma0-0** [romkatv/powerlevel10k#1464]
When I maximize and restore the window it shows the glitch. This fixes after running clear or reset command but this is annoying.

![image](https://user-images.githubusercontent.com/69481000/123664664-436e7980-d857-11eb-8abb-6b9cfa8ec5c6.png)

My system: 
![image](https://user-images.githubusercontent.com/69481000/123665013-9cd6a880-d857-11eb-8075-8cdcd3e54c4f.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by Sudeep-Sharma0-0** [comment]
You can close this. Thanks <3
