### ISSUE TITLE
New Installation requires zsh version of 5.1

### ISSUE THREAD

**Issue by rlam3** [romkatv/powerlevel10k#1465]
➜  ~ source ~/.zshrc
You are using ZSH version 5.0.8. The minimum required version for Powerlevel10k is 5.1.
Type 'echo $ZSH_VERSION' to see your current zsh version.

Is it possible to lower the dependency?

**Comment by romkatv** [comment]
It’s probably possible but it’s not something I’m willing to do. You can install zsh 5.8 with this: https://github.com/romkatv/zsh-bin
