### ISSUE TITLE
Git Icon Wrong Colour

### ISSUE THREAD

**Issue by benthegeek01** [romkatv/powerlevel10k#1466]
Hi,
After installing p10k and changing colours to my liking, the github icon refuses to change to anything other than black.
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/6730080/p10k.txt)
<img width="1422" alt="Screenshot 2021-06-29 at 02 58 02" src="https://user-images.githubusercontent.com/46504256/123725359-e63dec80-d885-11eb-9108-5b3916ccff44.png">

Any help appreciated!

**Comment by romkatv** [comment]
Try this:

```zsh
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=046
```

**Comment by benthegeek01** [comment]
Amazing, that worked.
Now it's just the separator that is black rather than green...

**Comment by benthegeek01** [comment]
Done - solution was to change `POWERLEVEL9K_VCS_FOREGROUND`

**Comment by romkatv** [comment]
Glad you managed to sort it out.

By the way, you can set all backgrounds to black with just one parameter:

```zsh
typeset -g POWERLEVEL9K_BACKGROUND=000
```

After that you can still override individual background colors for specific segments.

**Comment by benthegeek01** [comment]
Thanks for your help! And speedy replies too

**Comment by blakeperdue** [comment]
yes, thank you, this was very helpful!
