### ISSUE TITLE
[Feature] Add the ability to change the AWS profile background

### ISSUE THREAD

**Issue by jwhitcraft** [romkatv/powerlevel10k#1468]
Much, like how the kube context bit works, if the AWS profile contains specific bits, it should support changing the background color.

**Comment by romkatv** [comment]
This already exists. Search for POWERLEVEL9K_AWS_CLASSES in `~/.p10k.zsh`.

**Comment by jwhitcraft** [comment]
I think i just need to update this theme then.  Thanks for the fast response!
