### ISSUE TITLE
 ~  on   master ?72

### ISSUE THREAD

**Issue by freeyland** [romkatv/powerlevel10k#147]
Hi,

I am using the Nerd font but I get ? before the 72. How do I remove
(the square are icons)

thx

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-do-i-have-a-question-mark-symbol-in-my-prompt-is-my-font-broken

**Comment by freeyland** [comment]
I saw this but where in ~/.p10k.zsh should I look?

**Comment by romkatv** [comment]
Use the search function in your text editor. Search for `?`. There is only one place in the code where it's used.

```zsh
# ?42 if have untracked files.
vcs+='${${VCS_STATUS_NUM_UNTRACKED:#0}:+ %39F?${VCS_STATUS_NUM_UNTRACKED}}'
                                             ^
                                             |
                                            here
```

**Comment by freeyland** [comment]
Thanx, it worked

**Comment by romkatv** [comment]
Thanks for the confirmation!

I've changed the config and documentation to make it easier to change the untracked files icon. If you update powerlevel10k, restart zsh and run `p10k configure` again, your new config will have a dedicated parameter (`POWERLEVEL9K_VCS_UNTRACKED_ICON`) whose value you can change.
