### ISSUE TITLE
Configuration wizard skipping prompts?

### ISSUE THREAD

**Issue by QuantumCoded** [romkatv/powerlevel10k#1470]
Trying setting up Kitty + MesloLGS NF + zsh + OMZsh + powerlevel10k. This is my third time setting up this exact stack and I was impressed with how easy it worked the last two times. :+1:

However, this time everything is working as expected EXCEPT `p10k configure`.
Kitty installs fine from `pacman`.
Default font set fine.
Zsh installs fine from `pacman`.
Oh My Zsh installs fine from the command on their [website](https://ohmyz.sh/#install).
Powerlevel10k installs with the [command for Oh My Zsh](https://github.com/romkatv/powerlevel10k#oh-my-zsh).

The past two setups the wizard went through *all* the prompts like this:
![Powerlevel10k Configuration Wizard](
  https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/configuration-wizard.gif)

Now, running `p10k configure` gives me the prompts to configure: Prompt Style, Prompt Color, Show current time?,  Prompt Height, Prompt Spacing, Prompt Flow, Enable Transient Prompt?, Instant Prompt Mode, and then exits out.

Where are the prompts to edit: Prompt Separators, Prompt Heads, Prompt Tails, and Icons?

I'm sure this is probably my mistake somehow, I just can't find any information on how to fix it. Thanks!

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
