### ISSUE TITLE
[Request] Add POWERLEVEL9K_KUBECONTEXT_NAMESPACE_CLASSES

### ISSUE THREAD

**Issue by norman-zon** [romkatv/powerlevel10k#1471]
I would love to have an additional class `POWERLEVEL9K_KUBECONTEXT_NAMESPACE_CLASSES` that allows to define different styling for only the `NAMESPACE` part of the `KUBECONTEXT`.

E.g: 

my whole context is `deathray-testing/myspace`, so I can use the existing `POWERLEVEL9K_KUBECONTEXT_CLASSES` to match against `deatray-testing`, like before.  But additionally use `POWERLEVEL9K_KUBECONTEXT_NAMESPACE_CLASSES` to match against `myspace` separately and apply color, icon etc.

This would greatly help to distinguish workspaces and thereby prevent mistakes.

**Comment by romkatv** [comment]
Is `POWERLEVEL9K_KUBECONTEXT_CLASSES` not enough for your purposes? `*/myspace` would match all contexts from "myspace" namespace.

**Comment by norman-zon** [comment]
Not quite.
I want to set a seperate style for the `NAMESPACE` part only. Not for the whole context. So e.g. `deathray-testing` is green and `myspace` pink.
I use a handful of different clusters, each with a lot of namespaces. This makes it sometimes hard to see on a glimpse where I am. Having separate colors for the cluster and the workspace would really help.

**Comment by romkatv** [comment]
Does this do what you want?

```zsh
POWERLEVEL9K_KUBECONTEXT_CLASSES=(
  '*/myspace' MY
  '*'         DEFAULT)

# myspace: green name / red namespace
POWERLEVEL9K_KUBECONTEXT_MY_CONTENT_EXPANSION='%2F$P9K_KUBECONTEXT_NAME%1F/$P9K_KUBECONTEXT_NAMESPACE%f'
# default: green name / yellow namespace
POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='%2F$P9K_KUBECONTEXT_NAME%3F/$P9K_KUBECONTEXT_NAMESPACE%f'
```

**Comment by norman-zon** [comment]
Yes, that works.
Thank you very much for the quick help. I really appreciate you keeping up with your project and being an active maintainer!

**Comment by romkatv** [comment]
> Yes, that works.

Great! Thanks for the confirmation.

> Thank you very much for the quick help. I really appreciate you keeping up with your project and being an active maintainer!

You are very welcome 🤗
