### ISSUE TITLE
Get rid of flashing gitstatusd process?

### ISSUE THREAD

**Issue by tmpm697** [romkatv/powerlevel10k#1472]
I use `ps` command to filter process and doing it in real-time, but sometime not just one but 10 or 20 `gitstatusd-linux-x86_64`  processes spawned and killed immmediately, this messup monitoring tool/script that I'm using.

Is there a way to get rid of spawning `gitstatusd`? As I use `ps`, `grep -Ev` seems to doesn't work to exclude `gitstatusd` from output.

**Comment by romkatv** [comment]
I don’t understand what you are asking for.

**Comment by tmpm697** [comment]
I think `sleep .1` does help and seems not related to this package :P
