### ISSUE TITLE
Not offering to install fonts

### ISSUE THREAD

**Issue by tr4g** [romkatv/powerlevel10k#1473]
I just intalled ohmyzsh and followed instructions to install powerlevel10, which I have done before on my macbook. 

I'm using iTerm2. However, the config wizard didn't offer me to install the fonts automatically, it just started asking me if the characters look like they should, bot no fonts.

**Comment by romkatv** [comment]
You can install the font manually. See https://github.com/romkatv/powerlevel10k#manual-font-installation

**Comment by tr4g** [comment]
@romkatv yes but i wanted the cool feature. Anyway, I reinstalled both ohmyzsh and powerlevel10k and it offered me to install the fonts, so it was something i did wrong 😃

**Comment by romkatv** [comment]
Glad you sorted it out.

**Comment by tr4g** [comment]
I just had the same problem again on another MacBook Air, fresh OS installation using iTerm2.

The way the installer detects iTerm is clearly not working well. How could I help you fix this? Where does that detection happen?

**Comment by romkatv** [comment]
The code is here: https://github.com/romkatv/powerlevel10k/blob/master/internal/wizard.zsh (search for "iterm").

**Comment by tr4g** [comment]
I checked the code and assumed the problem was the font defined in the profile (since i exported the profile when I had the Meslo font set), however I tried resetting the font to Andale Mono and deleting it from the Fonts folder, ran `p10k configure` and it still didn't offer to install the font. Then I switched to the Default profile and guess what? it offered me to install the font.

It definitely has something to do with the profile you're using. Would be great if you could give it a look.

**Comment by romkatv** [comment]
The code I linked doesn't attempt to do anything if you are using a non-default profile. So it makes sense that it didn't offer to install the font for you.

The code is written this way because very few users employ non-default profiles and supporting them is work. If you send a PR with clean code, I'll be happy to merge it. I'm unlikely to do this by myself. My personal advice is to just install the font manually.

**Comment by tr4g** [comment]
It would be a great help if you specify in the README that fonts will only be auto-installed if you use the Default profile. Other than that, I don't entirely understand the code so I couldn't fix it myself.

**Comment by romkatv** [comment]
There are many conditions — documenting them all will make it unlikely that anyone will read them. There is always an escape hatch of installing the fonts manually.

**Comment by prasannjeet** [comment]
Some more info, in case someone stumbles upon here. You need to "DELETE" all the other profiles from iTerm2, and name the only profile as "Default" for the font-install-prompt to appear!

**Comment by WHenry55** [comment]
@prasannjeet I have literally spent the last like 3-4 hours trying to get this to work and when I "DELETED" my other created profile in Iterm2, and restarted Iterm 2. It finally prompted me to install meslo. thank you!

**Comment by mjrodriguez** [comment]
No need to delete, just need to move the preferred profile to the top. That prompted p10k configure to install the fonts.

**Comment by romkatv** [comment]
iTerm2 is the only terminal for which I specifically implemented automatic font installation. The vast majority of p10k users—those on other terminals—install the font manually. It's a straightforward process, so there's no need to find a way to force the automatic installer to run.
