### ISSUE TITLE
An extra space on the right side

### ISSUE THREAD

**Issue by mortymacs** [romkatv/powerlevel10k#1474]
Hi :)

I've configured my zsh and p10k and everything works great. I just found something which I know it's not very important, but I was looking for a way to fix it, is on the right side I have an extra space:
![2021-07-06_21-43](https://user-images.githubusercontent.com/1261448/124660441-7b546d00-dea6-11eb-971e-48cce30b83d9.png)

I don't have it on the left side. I don't know what exactly it is, but I wanted to report that maybe it's something that needs to be fixed or I have this problem locally.

**Comment by romkatv** [comment]
Try this:

```zsh
ZLE_RPROMPT_INDENT=0
```

**Comment by romkatv** [comment]
This is documented at the bottom of this page: https://zsh.sourceforge.io/Doc/Release/Parameters.html#index-ZLE_005fRPROMPT_005fINDENT

**Comment by mortymacs** [comment]
Thank you so much!
