### ISSUE TITLE
Adding bottom padding to prompt

### ISSUE THREAD

**Issue by eduardoHoefel** [romkatv/powerlevel10k#1475]
Hello,

I'd like to have my prompt looking like [this](https://ibb.co/ct48JtS)

I've read some of the issues related to this one and If i got it correctly, you mentioned that it is impossible without patching the terminal itself. However, this is easily achievable with `PS1="\n\n\n\n\n\033[5A"`. Basically adding 5 newlines and returning the cursor. I tried to achieve the same with the `newline` segment but could not find a way of returning the cursor.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/1457 for a lengthy discussion of a similar request. Setting `PS1` they way you described is a partial solution that brings a multitude of issues on its own. It's worse than the partial solution outlined in the issue linked above that uses a `precmd` hook.
