### ISSUE TITLE
Reapply config from wizard?

### ISSUE THREAD

**Issue by Relequestual** [romkatv/powerlevel10k#1479]
Hey!

Firstly, thank you for P10K. I'm sure I have lots to discover as I use it more.

I used the configuration wizard to set up, and again once I had the right font installed!

I'm trying to log any system setup processes so I can easily re-install should I need to.

I've copied the resulting config file to a gist, and I noticed at the top how it details the chosen options.

What would be great is a "replay wizard choices" CLI option, so configurations could be saved as one-liners, allowing config options to be replayed to generate the config file.

Obviously, people might modify the config after the using the wizard.
It could be possible to make a smaller diff type file which contains just the changes and how to apply them, but I'd say that's a "could have" sort of bonus.

**Comment by romkatv** [comment]
You can save the whole config. I hope storage won’t be a problem.

**Comment by Relequestual** [comment]
Right, I've saved the whole config, that's not a problem.

If I'm provising a new system, I ideally want to follow a script of commands to run.

If I want to include P10K, I need to copy a file, rather than run a (hyperthetical) one line command.

Here's an example of a tool which has a CLI which does the same thing as I'm suggesting but with gitignore files: https://docs.gitignore.io/use/command-line

**Comment by romkatv** [comment]
You need to copy the file. You should also do the same with other config files such as `~/.zshrc` and whatnot.
