### ISSUE TITLE
_p9k_init:193: error in flags

### ISSUE THREAD

**Issue by mjlbach** [romkatv/powerlevel10k#148]
I just pulled the latest version and am getting this error using the p10k-lean.zsh theme on first prompt initialization (fixes after subsequent commands, for example ls)

**Comment by romkatv** [comment]
Thanks for the report. Could you post the output of `echo $ZSH_VERSION`?

I've disabled `nordvpn` segment in `p10k-lean.zsh` for now. If you update, the error will go away. (Please do send me your zsh version anyway!)

**Comment by mjlbach** [comment]
Thanks! This works now. $ZSH_VERSION is 5.1.1

**Comment by romkatv** [comment]
Turns out `(q+)` expansion flag doesn't work in zsh older than 5.3. I've disabled nordvpn for older shells and enabled for the newer.

Thanks for the bug report!
