### ISSUE TITLE
Segment customization in transient prompt

### ISSUE THREAD

**Issue by ev0rtex** [romkatv/powerlevel10k#1481]
Following some of the other examples I've seen in the other issues/comments I wanted to customize my transient prompt to show me the timestamp for when I ran the last command but I wanted to change the style of it so that it has different background/foreground colors but haven't had any luck figuring out how to do that. It _appears_ to me that you can't customize the `time` segment separately for right and left prompts. I'm curious if there actually is a way to do that but I gave up on that idea.

As I kept thinking about the issue I decided on a different approach of just creating my own custom segment which actually gives me a lot more flexibility to show whatever I might want about the last run command instead of just the timestamp. I ran into one issue with it, however. It shows the timestamp from when it had rendered the prompt but I would like it to show the timestamp for when the user actually hit enter to run the command. Is it possible to refresh/update the segment at that point before it shows the transient prompt?

Here is what my current config for the custom segment looks like in case it is useful:
```zsh
# Prompt segment
prompt_exectime() {
    local date_icon="$(_p9k_get_icon '' DATE_ICON && echo "$_p9k__ret")"
    local time_icon="$(_p9k_get_icon '' TIME_ICON && echo "$_p9k__ret")"
    p10k segment -f 252 -b 237 -t "$(date +"${date_icon}"' %m/%d '"${time_icon}"' %H:%M:%S')"
}

# Config to use the segment with customized transient prompt
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=(exectime)

function p10k-on-pre-prompt() {
    p10k display '1'=show '2/left/exectime'=hide '2/left_frame'=show
}
function p10k-on-post-prompt() {
    p10k display '1'=hide '2/left/exectime'=show '2/left_frame'=hide
}
```
It looks nice to me but it uses an old timestamp from when it presumably rendered the last prompt:

<img width="941" alt="Screen Shot 2021-07-10 at 1 21 49 AM" src="https://user-images.githubusercontent.com/1640672/125155497-9977d280-e11d-11eb-85b7-74b60d0a8145.png">

**Comment by romkatv** [comment]
You can use `time` segment for the current prompt and `date` for past prompts. You can customize `date` format through `POWERLEVEL9K_DATE_FORMAT`.

```zsh
POWERLEVEL9K_DATE_FORMAT=$'%m/%d \uF017 %H:%M:%S'
```

P.S.

Never use any symbol that starts with `_p9k` or `__p9k`. These are internal. If you use them, bad things can happen to your machine. There are no guarantees at all.

**Comment by romkatv** [comment]
Hm... There is no `POWERLEVEL9K_TIME_UPDATE_ON_COMMAND` equivalent for `date` segment, so you'll need to use `date` for current prompt and `time` for past prompts. Given that both of them are customizable (via `POWERLEVEL9K_DATE_FORMAT` and `POWERLEVEL9K_TIME_FORMAT` respectively), this shouldn't make a difference. In case you'll need to specify the calendar icon, it's `\uF073`.

**Comment by ev0rtex** [comment]
okay, I can give that a shot. I assume doing that means I will lose the ability to use `POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME` though, right?

**Comment by romkatv** [comment]
Yes. `POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME` is quite terrible though. I'm sure it's worse than the clock your OS already displays.

**Comment by ev0rtex** [comment]
okay, that looks like a functional solution and seems to do the right thing. My config now looks like this:

```zsh
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  ...
  date     # replaced `time` with `date` here
  ...
}
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
typeset -g POWERLEVEL9K_TIME_FORMAT=$' %D{%m/%d} \uF017  %D{%H:%M:%S}'
typeset -g POWERLEVEL9K_TIME_ICON=$'\uF073'
typeset -g POWERLEVEL9K_TIME_FOREGROUND=252
typeset -g POWERLEVEL9K_TIME_BACKGROUND=237
typeset -g POWERLEVEL9K_DATE_FORMAT="%D{%H:%M:%S}"
typeset -g POWERLEVEL9K_DATE_ICON=$'\uF017 '
           POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=(time)
```

I did have to do the `%D{...}` in order for the time/date formats to be parsed correctly and I had to add some extra spacing to make the icons look right but this does seem to do the trick well enough for now. Does that seem like a good config to you?

BTW, thanks for working on this project @romkatv, it's so nice!

**Comment by romkatv** [comment]
Looks good to me. One thing I would change is to replace `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS+=(time)` with a plain `time` element at the end of `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. This will make no difference other than simplifying the config a little.

**Comment by ev0rtex** [comment]
yeah, I should do that... I was really just shoving all of this at the bottom of the file together but I really ought to integrate it into the rest of the config file where things fit
