### ISSUE TITLE
Instant prompt display instantly then disappear then reappear

### ISSUE THREAD

**Issue by giom-l** [romkatv/powerlevel10k#1483]
Hi, 

I'm using p10k for a long time now and I think I might having this issue since a long time too, but I got used to it.
As I'm cleaning a little bit my confs today, I'm wanting to get rid of this.

I have enabled instant prompt and it works.
The prompt appears instantly. But then it disappears for 2/3 seconds the reappears again.
I set instant prompt to verbose hoping that would give me some clues, but there is no output.

Here is a gif of what happens
![prompt_render](https://user-images.githubusercontent.com/29728596/125267237-e79bfa00-e306-11eb-904f-c68657c2f859.gif)

Also here is my .zshrc (yes, I need to clean some stuffs in it :) )
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/6800638/zshrc.txt)

**Comment by romkatv** [comment]
Thanks for opening the issue. Could you attach `~/.p10k.zsh`? Preferably as a file rather than inlining its content in a comment. I've done the same in your original issue report w.r.t. zshrc.

Can you reproduce it after doing the following?

1. Remove `~/.zshenv`, `~/.zprofile`, `~/.zlogin`.
2. Run this command:
   ```zsh
   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
   ```
2. Replace `~/.zshrc` with the this content:
    ```zsh
   if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
     source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
   fi
   [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
   source ~/powerlevel10k/powerlevel10k.zsh-theme
   ```
3. Restart your terminal.

**Comment by giom-l** [comment]
Sure, 
Here is my [p10kzsh.txt](https://github.com/romkatv/powerlevel10k/files/6802552/p10kzsh.txt)

I'll give a shot to your tests later and will update this comment with feedbacks

**Comment by romkatv** [comment]
> I tried the steps you proposed and.... no issue.

That's good. Does it mean that prompt now also appears instantly when you open a new terminal? It should, but in your original recording it didn't.

Now you have a small config that doesn't exhibit the issue and a large one that does. This means that something in your rc files triggers the issue. You need to find what it is. You can either add things from the large config to the small config one at a time until the issue reappears, or keep removing stuff from the large config until the issue disappears.

**Comment by giom-l** [comment]
Well, I found the culprit.
The prompt reloads whenever I add `zplug load`

That seems bad to not use it as zplug is my plugin loader.
Ever experienced this issue ?

**Comment by romkatv** [comment]
I don’t think `zplug load` does this by itself, at least it didn’t use to (I don’t use zplug myself). It’s probably the thing that’s being loaded that causes issues.

**Comment by giom-l** [comment]
Seems like `zsh-async` was causing the prompt reload.
After disabling it, I have no reload anymore but the prompt is maybe a little slower to display.

![new_shell](https://user-images.githubusercontent.com/29728596/125414503-ac258188-41cb-4832-a84d-d15568a9bad8.gif)

**Comment by romkatv** [comment]
Glad you found the culprit. You definitely should not use zsh-async. It doesn’t do anything good for your setup. You get all the downsides with no benefits.
