### ISSUE TITLE
Lost line in prompt separator

### ISSUE THREAD

**Issue by FernandoGarcia** [romkatv/powerlevel10k#1484]
Hi @romkatv !

Thanks for your job!

I have updated my power level 10k right now from the master branch and I have noticed a thin line lost in the prompt separator.

![p10k](https://user-images.githubusercontent.com/2778501/125478961-f3cfdd3b-8449-41e8-af38-fc86dc4d97a9.png)

I haven't seen it before.

Best regards.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by FernandoGarcia** [comment]
Thanks for fast reply and sorry for waste your time with previously answered question.

Changing the font did the trick.
