### ISSUE TITLE
Prompt prefix or cursor change inside virtual environment

### ISSUE THREAD

**Issue by Rathan007** [romkatv/powerlevel10k#1486]
Hi,
How to make a python emoji appear (like this 🐍) in the prompt when the virtual environment is activated and does not when venv is not activated

**Comment by romkatv** [comment]
Try this:

1. Run `p10k configure`.
2. When asked to choose *Prompt Style*, select *Lean*, *Classic* or *Rainbow*. For the rest of the options choose what you like.
3. Open `~/.p10k.zsh`.
4. Search for `POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION`, uncomment it and set the value to whatever you like.
5. If you don't want the name of the virtual environment to be displayed, add this:
   ```zsh
   typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION=
   ```

**Comment by Rathan007** [comment]
I tried and it showing on the left side .
Is there a way to show only the emoji in the right side prompt and the virtualenv details on left.

Non env :
> echo "Hello"                                     <

During env, I want a prompt like this
🐍>                                                      <3.8.1 venv

only the character in prompt

**Comment by romkatv** [comment]
> I tried and it showing on the left side .

That extremely weird. Can you post a screenshot?

> Is there a way to show only the emoji in the right side prompt and the virtualenv details on left.
>
> Non env :
> .> echo "Hello" <
> 
> During env, I want a prompt like this
> 🐍> <3.8.1 venv
> 
> only the character in prompt

Oh, when you say "right" you actually mean "left" and vice versa?

If so, try this:

```zsh
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='${VIRTUAL_ENV:+🐍}❯'
```

**Comment by Rathan007** [comment]
> > I tried and it showing on the left side .
> 
> That extremely weird. Can you post a screenshot?
> 
> > Is there a way to show only the emoji in the right side prompt and the virtualenv details on left.
> > Non env :
> > .> echo "Hello" <
> > During env, I want a prompt like this
> > 🐍> <3.8.1 venv
> > only the character in prompt
> 
> Oh, when you say "right" you actually mean "left" and vice versa?
> 
> If so, try this:
> 
> ```shell
> typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='${VIRTUAL_ENV:+🐍}❯'
> ```

I have attached a screenshot and updated my earlier post

**Comment by romkatv** [comment]
> I have attached a screenshot and updated my earlier post

Thanks. Indeed, the words "right" and "left" in your comments are swapped.

My previous comment has assumed as much, so the solution I've posted should work as far as I understood your request.

**Comment by Rathan007** [comment]
> > I have attached a screenshot and updated my earlier post
> 
> Thanks. Indeed, the words "right" and "left" in your comments are swapped.
> 
> My previous comment has assumed as much, so the solution I've posted should work as far as I understood your request.

Yay, It works. 💯 
Thank you 👍
