### ISSUE TITLE
Not rendered properly in windows terminal review.

### ISSUE THREAD

**Issue by Nautilus3000** [romkatv/powerlevel10k#1488]
![Screenshot (59)](https://user-images.githubusercontent.com/84305275/125748427-1763b145-f0bd-4f84-b39b-679a4ca26f94.png)

**Comment by romkatv** [comment]
Some fonts are better than others. Give the [recommended font](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k) a try.

**Comment by Nautilus3000** [comment]
That did the trick. Thanks!
