### ISSUE TITLE
Issue on POWERLEVEL9K_DIR_CLASSES:

### ISSUE THREAD

**Issue by webhive** [romkatv/powerlevel10k#149]
If set POWERLEVEL9K_DIR_CLASSES variable (no matter how - even default example has an issue) on zsh start got the following error

```
_p9k_init:161: _POWERLEVEL9K_DIR_CLASSES: assignment to invalid subscript range
```
After enter new line pressing Enter everything became fine and working as expected

```
$ zplug list romkatv/powerlevel10k
$ zplug info 'romkatv/powerlevel10k'
- use: "powerlevel10k.zsh-theme"
- as: "plugin"
- at: "master"
- ignore: ""
- lazy: "no"
- commit: ""
- dir: "/home/roman/.zplug/repos/romkatv/powerlevel10k"
- of: ""
- rename-to: ""
- from: "github"
- do: ""
- defer: "0"
- hook-load: ""
- file: ""
- name: "romkatv/powerlevel10k"
- nice: ""
- if: ""
- depth: "0"
- frozen: "no"
- on: ""
- hook-build: ""
```

**Comment by romkatv** [comment]
There was a bug at some point that could've caused this error but it's been fixed some time ago. Please update powerlevel10k to the latest version and try again. If the error persists, attach the output of `typeset -m 'ZSH_VERSION|POWERLEVEL9K_*' from a terminal that prints errors.

**Comment by webhive** [comment]
Hmm - you are right. Just pulled latest master and got it working well. 
Sorry for being disturbing you with such a stupid issue.

**Comment by romkatv** [comment]
No worries 🤗
