### ISSUE TITLE
iTerm 2 glitch

### ISSUE THREAD

**Issue by sintezcs** [romkatv/powerlevel10k#1490]
Hey guys, I've been using powerlevel10k for about 1.5 years without updating it. Today I've updated to the latest version and now there is a glitch in iTerm, Please see the screenshot. I'm using MacOS 11.4 + iterm2 3.4.8 + zsh + ohmyzsh + Meslo Nerd patched. I've tried the steps [from the manual](https://awesomeopensource.com/project/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols) to solve it, but nothing helped. Can you please assist me what can I do? I can share my config if needed.

<img width="511" alt=" " src="https://user-images.githubusercontent.com/2989480/125964810-681e6dc0-0ae7-4cdf-b471-c89a3613b160.png">

**Comment by romkatv** [comment]
Powerlevel10k (or anything that runs in the terminal for that matter) is not capable of causing this kind of glitch. What you see can be caused by a bug in the terminal or in the font.
