### ISSUE TITLE
How to Remove Code Number of Status, Remain Only the ✘ Icon?

### ISSUE THREAD

**Issue by 1ndeed** [romkatv/powerlevel10k#1495]
I know there are people there who need this. But personally, I don't need to know exactly what the error code number is. I just need the red ✘ icon when something goes wrong. The extra code number is unnecessary to me.

#Feature Request
Option to Disable Error Code Number in `~/.p10k.zsh`.

I wanted to remove it myself. I know that the status function is at line 3201-3302 in `/usr/share/zsh-theme-powerlevel10k/internal/p10k.zsh`. But I know nothing about zsh language.

So how to remove code number of status, remain only the ✘ icon?

**Comment by romkatv** [comment]
Try this:

```zsh
typeset -g POWERLEVEL9K_STATUS_CONTENT_EXPANSION=
```

**Comment by 1ndeed** [comment]
> Try this:
> 
> ```shell
> typeset -g POWERLEVEL9K_STATUS_CONTENT_EXPANSION=
> ```

It worked!! Thanks.
