### ISSUE TITLE
Strange prompt rendering glitch

### ISSUE THREAD

**Issue by lefc** [romkatv/powerlevel10k#1496]
Hello folks, 
I apologize in advance if this has already been asked and solved, but it's bothering me a lot lately and I have already and extensively tried to Google for answers without success. Whenever I'd leave my p10k prompt open via iTerm2, and the computer would go to sleep or simply just Screen-off+Lock, I can see that the terminal displays the following behavior while I've been away:
![image](https://user-images.githubusercontent.com/9439941/126460379-f8ff4d86-a6ba-434e-8cf4-348560fa401c.png)
Needless to say, this does not happen during normal operation, whereas the prompt works normally and as intended:
![image](https://user-images.githubusercontent.com/9439941/126460650-1e191784-12d8-4b88-a63b-38e074e146b1.png)
Any ideas what may be causing said behavior and/or tips/resources regarding how to fix it?
All input is very much appreciated. 
Many thanks to all in advance.
EDIT: forgot to add that the same behavior also happens whenever I plug/unplug a monitor.

**Comment by romkatv** [comment]
It's this: https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
