### ISSUE TITLE
vi-mode prompt doesn't update

### ISSUE THREAD

**Issue by DanManN** [romkatv/powerlevel10k#15]
Using the vi-mode plugin from oh-my-zsh doesn't update the mode prompts when changing vi modes. The prompt just stays on insert mode even though the mode has actually changed. I also have the clock in my prompt and can see that it is being updated when I switch modes so I find it weird that the vi-mode prompt isn't being updated.

Link to vi-mode plugin code: https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/vi-mode/vi-mode.plugin.zsh

**Comment by romkatv** [comment]
Could you post your POWERLEVEL9K config?

**Comment by DanManN** [comment]
Sure.
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time virtualenv public_ip ssh dir_writable dir vcs background_jobs status vi_mode)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_PUBLIC_IP_METHODS=(dig)
POWERLEVEL9K_VI_INSERT_MODE_STRING=""
POWERLEVEL9K_VI_COMMAND_MODE_STRING="N"
#POWERLEVEL9K_HOME_ICON=$'\UF015 '
#POWERLEVEL9K_HOME_SUB_ICON=$'\UF07C '
#POWERLEVEL9K_FOLDER_ICON=$'\UF115 '
#POWERLEVEL9K_LOCK_ICON=$'\UF023 '
POWERLEVEL9K_VCS_BRANCH_ICON=$'\UF126 '
POWERLEVEL9K_MODE="awesome-fontconfig"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="powerlevel9k/powerlevel9k"
# source /usr/share/zsh-theme-powerlevel9k/powerlevel9k.zsh-theme
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
```
I've already tried commenting out `POWERLEVEL9K_VI_INSERT_MODE_STRING=""` and
`POWERLEVEL9K_VI_COMMAND_MODE_STRING="N"` and that didn't fix it.

Also oh-my-zsh is sourced later in the config with `vi-mode` in the plugins list

**Comment by romkatv** [comment]
I've fixed this.

I don't use vi_mode myself, so I'm not 100% sure I implemented it the way it's supposed to work. Please try it.

**Comment by DanManN** [comment]
Works great. Thanks!
