### ISSUE TITLE
p10k can't display the style normally

### ISSUE THREAD

**Issue by MKingWang** [romkatv/powerlevel10k#1500]
I cannot modify its Prompt Style. If I copy the configuration file from another computer, the style cannot be displayed correctly. what should I do
<img width="961" alt="image" src="https://user-images.githubusercontent.com/32352403/126763770-8655d33e-e0d6-440b-890d-a55bfc9632fb.png">

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by MKingWang** [comment]
Thanks !!
