### ISSUE TITLE
gitstatusd on FreeBSD on raspberrypi

### ISSUE THREAD

**Issue by georgemagnuson** [romkatv/powerlevel10k#1501]
Hi,

when running oh-my-sh in FreeBSD on a raspberrypi, the initial screen says gitstatusd isn't loaded and suggests to compile gitstatusd.

I finally got around to doing this but ran into an issue where I had to specify the cpu architecture during build:
 sudo ./build -c armv8-a -s -w
without specifying -c armv8-a, the build would stop with unrecognised -march armv8

-g

**Comment by romkatv** [comment]
Thanks for the report.

What is the output of `uname -sm` on this machine?

**Comment by georgemagnuson** [comment]
uname -sm
FreeBSD arm64

**Comment by romkatv** [comment]
Thanks for the info. Fixed.
