### ISSUE TITLE
gitstatus_cxx is hardcoded to g++

### ISSUE THREAD

**Issue by advaithm** [romkatv/powerlevel10k#1502]
When building gitstatusd it is possible to replace gcc with clang by using the `CC` env var. normally you could override the compiler for c++ using the `CXX` var but the build system doesn't respect this. Looking through it appears g++ is actually hard coded.  changing `gitstatus_cxx=-g++` too `gitstatus_cxx=${CXX:-g++}` fixes this issue.

**Comment by romkatv** [comment]
Thanks for filing the issue.

I've fixed it upstream in https://github.com/romkatv/gitstatus/commit/cf21109b9e7b2ec5dd2ed9765987e27b435a1e72 and pulled changes into powerlevel10k.
