### ISSUE TITLE
Prompt Artifacts While Resizing Window

### ISSUE THREAD

**Issue by vraimonds** [romkatv/powerlevel10k#1504]
### Issue

![2021-07-24_16:32:06](https://user-images.githubusercontent.com/10418870/126871731-f09bdb8e-7a81-432c-96ac-a496de4b173e.png)

While resizing the terminal window, a new line with prompt artifacts at the end of the line are created.

### Expected Behavior
On the creation of a new line the artifacts at the end of the previous line should be removed.

### Specifications
OS: Ubuntu 20.04
Terminal: gnome-terminal
Shell: zsh
Desktop Manager: i3wm

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
