### ISSUE TITLE
Lines between segments

### ISSUE THREAD

**Issue by tarneaux** [romkatv/powerlevel10k#1505]
Hi,
I have tried a lot of things without success.
There's the problem: in my terminal (konsole), there are lines between the segments:
![screenshot](https://i.ibb.co/DQWrYxS/Screenshot-2021-07-24-20-24-07.png "screenshot")
(You may need to zoom to see the black lines between the segments)
What is the option in .p10k.zsh that changes this?
Thanks

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by tarneaux** [comment]
I've already tried it. Still those lines.
The only thing I couldn't do is "Enable builtin powerline glyphs in terminal settings if your terminal supports it (iTerm2 does)" How do you do that in konsole?

**Comment by romkatv** [comment]
> I've already tried it. Still those lines.

I don't have anything to add to what's in that FAQ entry.

> The only thing I couldn't do is "Enable builtin powerline glyphs in terminal settings if your terminal supports it (iTerm2 does)" How do you do that in konsole?

I don't know whether Konsole supports this.
