### ISSUE TITLE
Python logo during setup not rendering despite using recommended patched font

### ISSUE THREAD

**Issue by macintacos** [romkatv/powerlevel10k#151]
I'm using the MesloLGS NF font that was recommended to be used with powerlevel10k, and it doesn't render the python logo when running `p10k configure`. Is this to be expected?

![](https://cl.ly/a048dc1e5dac/Image%202019-08-05%20at%2010.43.56.png)

**Comment by romkatv** [comment]
Yes, this is expected. If you give correct answers (answer `y` for symbols that render correctly and `n` for those that don't), you'll get all icons in your prompt.

I'll add this to FAQ.

**Comment by macintacos** [comment]
Ah okay, thanks @romkatv! Just didn't know if I was doing something wrong or not. Appreciate the insight.

**Comment by romkatv** [comment]
> I'll add this to FAQ.

Added: https://github.com/romkatv/powerlevel10k#ive-installed-the-recommended-font-but-i-still-dont-see-the-python-logo-in-the-configuration-wizard.

**Comment by xuhuizhou-vt** [comment]
> Yes, this is expected. If you give correct answers (answer `y` for symbols that render correctly and `n` for those that don't), you'll get all icons in your prompt.
> 
> I'll add this to FAQ.

Hi, can I remove the python logo? 
<img width="86" alt="image" src="https://user-images.githubusercontent.com/60275671/190036265-3f5c0880-5a02-4761-bcad-9a21ca4f3ca6.png">
