### ISSUE TITLE
No gitstatus on bare repos

### ISSUE THREAD

**Issue by mtalexan** [romkatv/powerlevel10k#1510]
While the `git status` command isn't available in a bare repo, the shell-version of the git prompt that's regularly distributed with git installations does support some basic info when in bare repos.

See https://github.com/romkatv/gitstatus/issues/252 for the details of this, but at least some basic details should still be shown for bare repos.

**Comment by romkatv** [comment]
Powerlevel10k will support bare repos once gitstatus supports them.
