### ISSUE TITLE
Question: Is there some setting or feature available in transient prompt to see elapsed time for a command while its running ?

### ISSUE THREAD

**Issue by aravinder111** [romkatv/powerlevel10k#1512]
Scenario: I use transient prompt, so my terminal commands look like below. However I need to run a command sometimes and it takes 15-30mins to finish, during this time, I cant see any clock or timer to know how long its been since the command has been running. Is there a setting or feature available to see time elapsed counter while a command is still running ?
```
❯
❯
❯ echo "Hi"
Hi
❯ echo "there"
there

  ~ ❯
```

I appreciate your time and help. Thanks in advance.

**Comment by romkatv** [comment]
It's not possible to display the elapsed time. When the command is running, it has full control over the terminal's content, so nothing else can do anything with the terminal.

There are two alternatives.

1. It's possible to display the start time of a command in the "short" prompt, either on the left or on the right. If this is what you want, please attach your `~/.p10k.zsh` and I'll show you how to modify it.
2. It's possible to display the start time of a command (perhaps along with the command itself) in the terminal window title. This is outside of scope of powerlevel10k but I can give you some pointers if this is what you want.
