### ISSUE TITLE
Enabling ruler and customizing how it works

### ISSUE THREAD

**Issue by robmonte** [romkatv/powerlevel10k#1513]
Is the `POWERLEVEL9K_SHOW_RULER` feature only properly supported in styles like lean? I really couldn't find much info at all about this feature for both p9k and p10k in my searches.

I was hoping to the ruler line with the Classic style, however when I enable the feature it gives the background color of the ruler the same gray as the prompt, making it look bad.
Example:
![image](https://user-images.githubusercontent.com/17119716/127632570-1bd1f6b1-099e-4347-8334-ff0580453827.png)
_The ruler line background color should match the terminal background color so it only appears as a thin line_

&nbsp;

In addition to this, I was hoping the ruler would work as a divider between commands in history, however with the transient prompt feature enabled the line does not stay (which _does_ make sense since the ruler is a part of the prompt itself).
Example:
![image](https://user-images.githubusercontent.com/17119716/127633691-171798c4-d72e-4882-b445-af5f50d66c7c.png)
_I was hoping that the ruler line would remain below the output "1" in the history_

&nbsp;

So the first question is simple, how do I fix that background color from the ruler character so it matches my terminal background?

My next question is more complex: Is it possible to configure the ruler in such a way that it will be "outside" of the prompt so that the transient prompt does not remove it and thus persists in the scrollback history? If not, is this a reasonable feature request? I feel like it could be something others find desirable as well. I'm curious about others' thoughts on this.

**Comment by romkatv** [comment]
> The ruler line background color should match the terminal background color so it only appears as a thin line

Add this:

```zsh
```

**Comment by romkatv** [comment]
> So the first question is simple, how do I fix that background color from the ruler character so it matches my terminal background?

Add this:

```zsh
typeset -g POWERLEVEL9K_RULER_BACKGROUND=
```

It's the same syntax as for prompt segments. You can either specify the background color or leave the value empty for transparent background. If you don't set this parameter, it defaults to `POWERLEVEL9K_BACKGROUND`. The latter is empty in Lean but it's a shade of grey in Classic.

> My next question is more complex: Is it possible to configure the ruler in such a way that it will be "outside" of the prompt so that the transient prompt does not remove it and thus persists in the scrollback history?

Yes. Transient prompt can actually be configured to display anything you like, almost independently from your normal prompt. It can have a different number of segments, different number of lines, ruler, frame, etc. The binary option for transient prompt is just a preset for something that makes sense.

Configuring transient prompt isn't easy and there are no docs. However, if you search issues for `p10k-on-preprompt`, you'll find plenty of examples.

By the way, ruler is really not as useful as you might think. In your setup it doesn't add anything. You already have more than enough separation between the last command's output and the current prompt.

**Comment by robmonte** [comment]
Thanks a ton! I got my terminal exactly as I was hoping to now! I discovered a lot by looking up p10k-on-pre-prompt. Cheers for the great theme and evolution of p9k.
