### ISSUE TITLE
Get length of path as printed by p10k

### ISSUE THREAD

**Issue by lilithium-hydride** [romkatv/powerlevel10k#1514]
Is there a way to get the length of the shortened path that gets displayed? I'm trying to make a line that extends to the end of the dir module, but there doesn't appear to be any variable for that length and I don't want to have to run some big shell script every time to generate the length.

**Comment by romkatv** [comment]
Can you expand on what you are trying to achieve?

**Comment by lilithium-hydride** [comment]
I have a Starship prompt on Fish set up as shown below, with a little bar stretching out to surround the current directory.
![image](https://user-images.githubusercontent.com/78992082/127754748-e3da5266-6375-4128-ab1e-893c95396e12.png)

However, I've Starship to be incredibly slow in comparison to p10k, so I'm attempting to recreate that prompt. 
![image](https://user-images.githubusercontent.com/78992082/127754779-b0728d26-b9d4-49c6-9352-f47c70ba207a.png)
I've made decent progress, but I can't figure out a way to replicate the bar that I have on Starship.

**Comment by romkatv** [comment]
If the current directory is not shortened, `${(m)#${(%):-%~}}` will give you its printed length. It even handles wide unicode characters correctly (e.g., if the current directory contains "❎").

```text
% mkdir /tmp/❎ && cd $_
% print -r -- ${(m)#${(%):-%~}}
7
```

If the current directory is shortened in powerlevel10k prompt, there is no way to get its length. Note that this length changes dynamically when the terminal is resized.

P.S.

Try Lean style in `p10k configure` if you haven't tried yet. It's similar to what you are trying to achieve but without non-functional cruft. Choose "few icons" in the wizard for best results.

**Comment by lilithium-hydride** [comment]
Yeah, I have a script that just does what Starship does to shorten the path. As its shortening is very primitive, this isn't too hard to do. P10k's shortened path would be near impossible to predict externally, so if there's no environment variable or something that stores this shoetene, then I guess

**Comment by romkatv** [comment]
There is no environment variable and it's impossible to create one because the length of the current directory changes dynamically when the terminal window is resized.
