### ISSUE TITLE
Original python vend prompt

### ISSUE THREAD

**Issue by Bruno21** [romkatv/powerlevel10k#1515]
Hello,

Don't see the answer in doc

I've switch Pure thème
![image](https://user-images.githubusercontent.com/4353024/127736355-9cb1ce3d-f39c-4f8f-a0a4-ed167872c0ad.png)

to Powerlevel10k
<img width="299" alt="image" src="https://user-images.githubusercontent.com/4353024/127736392-36bb7584-0a95-4bfe-b690-fa9bdbc589b8.png">

I prefer the original display for venv
bash-5.1$ source mkdocs/bin/activate
(mkdocs) bash-5.1$

Is there an option for that ?

**Comment by romkatv** [comment]
I don't understand the question.

Please describe what you do, what you prefer to happen, and what actually happens.

**Comment by Bruno21** [comment]
With Powerlevel10k, when I activate a virtual env, I don't see the prompt of the venv:

```
bruno@airbook  ~/Documents/venv  source mkdocs/bin/activate
bruno@airbook  ~/Documents/venv                         ✔  773  14:25:22
```
The venv is well activated.


As a python newbie, I prefer

$ source mkdocs/bin/activate
(mkdocs) $                                                           # <-   I want to see this line

I run in bash for the example, but it's the same with zsh and Pure theme.

**Comment by romkatv** [comment]
Please attach `~/.p10k.zsh` if you have it.

**Comment by Bruno21** [comment]
Voila
[p10k.zip](https://github.com/romkatv/powerlevel10k/files/6912916/p10k.zip)

**Comment by romkatv** [comment]
Thanks for posting the config.

This config doesn't match the description of what you see that you've posted in the previous comment (https://github.com/romkatv/powerlevel10k/issues/1515#issuecomment-890342849).

Can you confirm that you are using this config and that you don't see the name of the virtual environment in prompt when you activate it?

If you do see the name of the virtual environment in prompt when you activate it, then please specify how the prompt you see is different from the prompt you want to see.

**Comment by Bruno21** [comment]
> Thanks for posting the config.

> Can you confirm that you are using this config and that you don't see the name of the virtual environment in prompt when you activate it?
> 
 
It is on the right.

I understand my mistake:
Just un-comment virtualenv on left and comment on right.
and it is perfect

Very sorry.
Thanks for your patience...

**Comment by romkatv** [comment]
Glad you manage to solve this problem. Closing.
