### ISSUE TITLE
Octave CLI support?

### ISSUE THREAD

**Issue by saaditory** [romkatv/powerlevel10k#1517]
Hi!
Can you add support for Octave command prompt as well? 
It can also be modified using ~/.octaverc file.

I tried this custom design for myself so far and it works:
`PS1('\[\033[37m\]\[\033[30;47m\]  \[\033[37;44m\]\[\033[97m\]  \[\033[1m\]\W \[\033[0;34;42m\]\[\033[30m\]  \[\033[0;32m\]\[\033[0m\] ')`

![image](https://user-images.githubusercontent.com/38633812/127784966-9b493bf8-1646-4aeb-8f69-12092d878899.png)
[This page was helpful.](https://octave.org/doc/v6.3.0/Customizing-the-Prompt.html)

Looking for proper powerlevel10k support for Octave.

**Comment by romkatv** [comment]
I cannot.
