### ISSUE TITLE
Icons don't work in Visual Studio Code

### ISSUE THREAD

**Issue by gillescoolen** [romkatv/powerlevel10k#1520]
I tried all the fixes listed in #617.

Whenever I list directories in my normal terminal (Alacritty) I see icons.
![image](https://user-images.githubusercontent.com/31668393/127895146-26bb2e2b-dd39-4b81-b75c-c5c47f38cac6.png)

If I do the same in the integrated terminal in Visual Studio Code, I see boxes.
![image](https://user-images.githubusercontent.com/31668393/127894684-ac3c38a1-84ce-4bd9-a93c-dd33b17f541f.png)

My settings for the integrated terminal:
```json
  "terminal.integrated.cursorStyle": "line",
  "terminal.integrated.fontFamily": "Operator Mono",
  "terminal.integrated.fontSize": 15,
  "terminal.integrated.scrollback": 1000000,
```

My font related settings for Alacritty:
```yml
font:
  size: 10
  normal:
    family: 'Operator Mono'
```
I'm not sure if this repository is the right place to post this issue. If it's not, just close it and I'll open it on the Visual Studio Code repository.

**Comment by romkatv** [comment]
The output of `ls` is produced by `ls` and it’s rendered by the terminal emulator. Powerlevel10k has no say in this.

**Comment by gillescoolen** [comment]
Okay, but other icons have the same behavior. For example, when running the p10k

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by gillescoolen** [comment]
It does seem to work with that exact font. Is there no way to patch another font to have the same behavior?
