### ISSUE TITLE
OSX Prompt Has Undesired Artifact When iTerm Started

### ISSUE THREAD

**Issue by bigapple10027** [romkatv/powerlevel10k#1521]
**OS**:           Big Sur. 11.2.3
**Terminal**:  iTerm2
**Powerlevel10k version**: Not sure how to check the version. But it was installed on Aug 2, 2021 through homebrew.

**Description**:

As shown in the screenshot, when iTerm is reopened after being quit completely, it displays an extra undesired artificial line. This extra line will not disappear until the window size is adjusted through mouse. While if you create a new tab or window, the prompt in the new tab/window is as expected.

**Steps to Reproduce**:
1. Quit iTerm through "cmd + Q" on Mac.
2. Open the iTerm app.

![Screen Shot 2021-08-02 at 2 51 03 PM](https://user-images.githubusercontent.com/25491828/127929040-8a641862-4114-4c1b-b729-7a30eda8c53e.png)

**Comment by romkatv** [comment]
This is caused by a bug in iTerm. See https://github.com/romkatv/powerlevel10k/issues/1497
