### ISSUE TITLE
Unable to get "context" to work

### ISSUE THREAD

**Issue by CleanMachine1** [romkatv/powerlevel10k#1522]
Hi, just began using ZSH and been enjoying powerlevel10k.

I have found 1 error though.

I am unable to get the context "plugin" to work.

Setup:
Arch
Installed powerlevel10k with ohmyzsh

I have tried to set the name using this command from powerlevel9k, and then changed to 9 to 10 
`POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -f`"`

Do you have any suggestions for me to fix this?

Regards.

**Comment by romkatv** [comment]
Try the following:

1. Run `p10k configure` to generate a config.
2. See this FAQ entry: https://github.com/romkatv/powerlevel10k#how-do-i-add-username-andor-hostname-to-prompt

**Comment by CleanMachine1** [comment]
Thanks a lot!

The solution was to remove the following line

`typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=`
