### ISSUE TITLE
oh-my-zsh installation instructions do not work: zsh: command not found: p10k

### ISSUE THREAD

**Issue by johnpitchko** [romkatv/powerlevel10k#1523]
Clean install of 10.13 (on an 2011 MacBook Air).

Installed oh-my-zsh following instructions in that repo. Verified that it was installed successfully.

Followed instructions in this repo to install p10k via oh-my-zsh. Ran `git clone...` command successfully. Added `ZSH_THEME="powerlevel10k/powerlevel10k"` as instructed.

Restarted zsh (multiple times, quitting and re-launching terminal, doing full system restart).

Ran command `$ p10k configure` and received error `zsh: command not found: p10k`.

**Comment by romkatv** [comment]
Have you added `ZSH_THEME` or changed the value of it? You need to do the later.

**Comment by kodersky** [comment]
Add one more line to your `~/.zshrc` file:

`source ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
`

Then run `$ exec zsh`. You should be able to see the configuration wizard.

**Comment by romkatv** [comment]
@kodersky Don't do that. You'll end up with two zsh themes. Powerlevel10k will eventually win but there may be side effects. At the very least it'll be slower.

Instead, follow the installation instructions. Clone the repo and set `ZSH_THEME="powerlevel10k/powerlevel10k"` in `~/.zshrc`. Your `~/.zshrc` should already have `ZSH_THEME` in it, you just need to change the value.

**Comment by kodersky** [comment]
@romkatv Oh. Thanks for pointing this out. I was fallowing install instructions. 

1. install recommended fonts 
2. install Powerlevel10k for my Oh My Zsh

`git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k`

3. add `ZSH_THEME="powerlevel10k/powerlevel10k"` to .zshrc

After restarting ZSH the configuration wizard was not triggered. And I couldn't trigger it by command `p10k configure` - command not found :/

There wasn't any `ZSH_THEME` variable before in .zshrc. So to what I should change it? To the `ZSH_THEME=~/.oh-my-zsh/custom/themes/powerlevel10k/`?

**Comment by romkatv** [comment]
> 1. add `ZSH_THEME="powerlevel10k/powerlevel10k"` to .zshrc

The instructions say **set**, not **add**. You shouldn't be adding `ZSH_THEME` to `~/.zshrc`.

> There wasn't any `ZSH_THEME` variable before in .zshrc.

This means you aren't using Oh My Zsh. You should follow Powerlevel10k installation instructions for Oh My Zsh only if you are using Oh My Zsh. If you aren't using Oh My Zsh, follow different installation instructions that depend on your plugin manager. If you aren't using any plugin manager, follow the manual installation instructions.

**Comment by ahillio** [comment]
I'm glad to find this issue now.... I was wondering how to make the `p10k configure` command available.  I didn't realize `ZSH_THEME="powerlevel10k/powerlevel10k"` is required in `~/.zshrc` (I thought the wizard would do that) because I missed that in the instructions due to the "Users in mainland China..." part.  I didn't quickly see how to create a merge request (not sure you'd want it anyway) but https://github.com/ahillio/powerlevel10k/blob/master/README.md#oh-my-zsh shows how those two steps for `oh-my-zsh` installation can be made more explicit... if you'd like.  Thank you @romkatv !

**Comment by romkatv** [comment]
@ahillio Your change LGTM 👍 Please go ahead and send a PR.
