### ISSUE TITLE
representing vi-mode in prompt

### ISSUE THREAD

**Issue by ahillio** [romkatv/powerlevel10k#1527]
I was using powerlevel9k until this morning and am now trying to get the vi-mode indicator to work with powerlevel10k the way it used to.

Currently, the `vi_mode` plugin works, but the prompt does not change to represent which mode I'm in; it always says "INSERT" and never switches to "VI-Mode".

I wanted to "start from scratch" when installing powerlevel10k, so I deleted the old pl9k variables from my `~/.zshrc` and used the configuration wizard.  After the wizard I added the following to `~/.p10k.zsh`:

```
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode status history battery time)
POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="VI-Mode"
```

Any tips/suggestions on what I might do?  I've been stuck on this for a while now.

**Comment by romkatv** [comment]
Your config has incorrect names of some parameters. Try copying this block: https://github.com/romkatv/powerlevel10k/blob/2c135dd631019a251e073a0f4e86267cf12c50c0/config/p10k-rainbow.zsh#L791-L805

Alternatively, run `p10k configure`. It should work without any changes. Note that if you select a prompt style with `prompt_char` in it, `vi_mode` will be disabled by default because it's useless in this case.

**Comment by romkatv** [comment]
I take that back, your config is fine. No types in there. It works fine for me. Can you try it with nothing else in your `~/.zshrc` other than these parameters and a line that sources powerlevel10k? If that doesn't work, attach your `~/.zshrc`.

**Comment by ahillio** [comment]
Starting with an alltogether fresh `~/.zshrc` like so....

```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
export ZSH=$HOME/.oh-my-zsh
plugins=(git vi-mode history-substring-search)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode status history battery time)
POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="VI-Mode"
```

...I'm just getting a broken prompt (some shell default thing with no color or segments or anything).

**Comment by romkatv** [comment]
This config isn't sourcing powerlevel10k. Try this (this is the full `~/.zshrc`):

```zsh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode status history battery time)
POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="VI-Mode"
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

You might need to change the file path on the last line if you've cloned powerlevel10k to a different directory.

**Comment by ahillio** [comment]
Wouldn't I need the line:
```
plugins=(git vi-mode history-substring-search)
```
(which relies on oh-my-zsh)
in order for this to work?

**Comment by romkatv** [comment]
No. Please create `~/.zshrc` with the content I posted above and run `exec zsh`.

**Comment by romkatv** [comment]
If you want to enable vi keymaps by default, add `bindkey -v` to the config.

**Comment by ahillio** [comment]
I created new `~/.zshrc` config with contents:

```
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vi_mode status history battery time)
POWERLEVEL9K_VI_INSERT_MODE_STRING="INSERT"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="VI-Mode"
source ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
```

and I get a working prompt.

**Comment by ahillio** [comment]
I'm websearching for `bindkey -v` to learn how to use it for this...

**Comment by romkatv** [comment]
Great. Now you can try to figure out which part of your original config breaks your prompt.

**Comment by romkatv** [comment]
> I'm websearching for `bindkey -v` to learn how to use it for this...

You just run it. It enables vi mode in zsh.

**Comment by ahillio** [comment]
Adding `bindkey -v` to my full `.zshrc` results in the `POWERLEVEL9K_VI_COMMAND_MODE_STRING="VI-Mode"` successfully toggling the RIGHT_PROMPT element when I hit escape.

But it doesn't change the cursor between `|` for insert and a wide bar (kinda like `|||` but an actual single block/bar and not three pipe characters).... any ideas about that?

**Comment by ahillio** [comment]
at one point I had used the method described here https://archive.emily.st/2013/05/03/zsh-vi-cursor/ but haven't used it in a while because it just behaved that way without the extra code.... but now it's not.

**Comment by romkatv** [comment]
The cursor is not supposed to change. If you want it to be changed, you need to write code for that. This is outside of the scope of powerlevel10k. Powerlevel10k only provides prompt.

**Comment by ahillio** [comment]
...oh maybe it wasn't actually working with powerlevel9k, as it doesn't now when I switch back to it.  I guess that's something I can do without.

Thank you for the help finding `bindkey -v`!!!
