### ISSUE TITLE
Some Persian characters render incorrectly in gnome-terminal with Meslo Nerd font

### ISSUE THREAD

**Issue by pajuhesh80** [romkatv/powerlevel10k#1531]
The title describes the problem. For example, `ژ` renders as as skull icon.
Windows terminal and Termux render these characters well with this font.

**Comment by romkatv** [comment]
This sounds like an issue with gnome-terminal. Do you think it's an issue with the powerlevel10k? Or perhaps with the font?

**Comment by pajuhesh80** [comment]
I don't know exactly but I guess font and gnome-terminal together cause this problem. This font is OK in other terminals; also gnome-terminal is OK with other fonts.

**Comment by romkatv** [comment]
If you find out that something needs to be fixed in the font, please post a comment.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here.
