### ISSUE TITLE
Transient prompt breaks after re-sourcing .zshrc

### ISSUE THREAD

**Issue by Forst** [romkatv/powerlevel10k#1533]
I often use `source ~/.zshrc` to reload my Zsh config without restarting the shell itself. This breaks the transient prompt:

![Screenshot from 2021-08-11 10-16-59](https://user-images.githubusercontent.com/369699/128995062-2551bd4b-eb8c-4430-bfe7-e1e672b99f78.png)

Sample configuration I'm using: [zshrc.txt](https://github.com/romkatv/powerlevel10k/files/6966867/zshrc.txt), [p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/6966904/p10k.zsh.txt).

Test environment:

* Ubuntu 20.04 Docker image
* zsh 5.8
* oh-my-zsh latest `master` (ohmyzsh/ohmyzsh@7eeb1e193d4a55ab706931fb80ef556a939be8fd)
* powerlevel10k latest `master` (romkatv/powerlevel10k@32e76e772173f1d2856ee4002f21607523221ce7)

---

On a side note, thanks a lot for this feature! Very useful for copying console snippets into chats or documentation :+1:

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#weird-things-happen-after-typing-source-zshrc

**Comment by Forst** [comment]
And of course it's already documented, my bad 😊 Thank you!
