### ISSUE TITLE
show bindkey / set -o mode

### ISSUE THREAD

**Issue by xenoterracide** [romkatv/powerlevel10k#1537]
so I tried to get powerline itself to work due to #748, and I did, but I never figured out how to customize it. One of the nice things it had in addition to your existing symbols, was a differentiator between vi and emacs mode. It would be cool to have that in p10k.

**Comment by romkatv** [comment]
Could you describe what you want to see and when?

**Comment by xenoterracide** [comment]
well, that's a bit hard to say... but in powerline when you're using the >|||||> block style it's kind of like

>EMACS>...>...>

or for vi

>INSERT>...>...> etc

I think that's probably far more verbose than needed. In powerlevel10k it treats emacs as perpetual insert. So there's no indication that your keystrokes are different. 

I'm currently just using `>` for the prompt, not the >||||> . Maybe just a different  symbol, though. A $ or a % is pretty standard... or you could use any number of unicode characters. if that's not good, maybe something else. I'm not fussy, I just realized I liked that the prompt was giving me some indicator on whether I was in emacs or vi mode.

**Comment by romkatv** [comment]
I'm intrigued. I've never heard of anyone dynamically switching between emacs and viins keymaps. Can you describe your use case? What's your main keymap? How do you switch to the other keymap and why?

**Comment by xenoterracide** [comment]
Hah, I thought I responded to this, oops. I don't actually switch “dynamically” per se. I have switched. I use emacs primarily, and primarily because that is the default on most systems which have bash. I'm debating on getting away from that. This is really the primary use case, I may not be sure when I enter a system which shell the system is configured for, and what mode that shell is in. So it's kind of nice to be able to see it somehow. To bad, I couldn't find single unicode symbols in a font for vi or emacs ;)

**Comment by romkatv** [comment]
If you are able to install powerlevel10k on a system, you should also be able to invoke `bindkey -e`. Add it to `~/.zshrc` and you won't need to know whether the main keymap is emacs of viins.

**Comment by xenoterracide** [comment]
doesn't that kind of assume there is only one user account on the system? and that any given user account will have the same access out of the box? and that you'll remember which is which?

**Comment by romkatv** [comment]
> doesn't that kind of assume there is only one user account on the system?

Do you think it does? Why?

Can you modify prompt? Then you can also modify keymap. Under which circumstances you can modify one but not the other?

Is it perchance possible that we have a miscommunication w.r.t. modifying the keymap? You do that with `bindkey -e` in `~/.zshrc`. It's as local as modifying `PS1` in `~/.zshrc`. If you can do the latter, you can do the former.

**Comment by xenoterracide** [comment]
The problem is not that you can modify, it's that they may look similar, you may not realize which one you're currently in. I've worked in environments that while they weren't modifying the admin's remote prompt, you could have, but it also doesn't mean it's the same as your local, or that the remote prompt is something you have significant control over.

**Comment by romkatv** [comment]
I don't follow. You've filed this feature request to add a new option to powerlevel10k. Would you be able to use this new option? If yes, then instead of using this option you can invoke `bindkey -e`. What am I missing?

**Comment by xenoterracide** [comment]
tell me something, what mode am I in? ignoring all of the errors of course... also, none of these errors occur if I don't `sudo -E`

```
❯ bindkey -v
❯ sudo -E /bin/zsh
default-ice: stored the ices: lucid ''.
This Zshell's ID: <2> (no name assigned)


When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

** Message: 14:13:29.516: couldn't access control socket: /run/user/1000/keyring/control: Permission denied
** Message: 14:13:29.517: couldn't connect to dbus session bus: Could not connect: Permission denied
** Message: 14:13:29.517: The gnome-keyring control directory cannot be accessed: /run/user/1000/keyring: Permission denied

** (gnome-keyring-daemon:6578): WARNING **: 14:13:29.517: couldn't create socket directory: /run/user/1000/keyring-2OC870: Permission denied

** (gnome-keyring-daemon:6578): WARNING **: 14:13:29.517: couldn't bind to control socket: /run/user/1000/keyring-2OC870/control: Permission denied

 ~ ────────────────────────────────────────────────────────────────────────────────── root@manjaro
❯ zsh compinit: insecure directories and files, run compaudit for list.


 ~ ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── root@manjaro
❯ 
```

**Comment by romkatv** [comment]
```text
❯ bindkey -v
❯ sudo -E /bin/zsh
```

The first line has no effect on the second line.

You need to invoke `bindkey -e` at the same place (the same file) where you were planning on using the new powerlevel10k option. So instead of this:

```zsh
POWERLEVEL9K_SOME_NEW_OPTION=blah
```

Do this (on the same line):

```zsh
bindkey -e
```

**Comment by xenoterracide** [comment]
Yeah, I know that, but the prompt could indicate it, that's the request, to have the prompt show that I'm in that mode somehow.

**Comment by romkatv** [comment]
If you invoke `bindkey -e`, there won't be a need for this.

It's not a good idea to add features that have no use cases. As far as I can tell, this feature doesn't have a use case. `bindkey -e` is simply better than not invoking it and using the new hypothetical feature.

**Comment by xenoterracide** [comment]
I mean, do I need to copy over a shell script then to copy all of my settings?  I think, can do a similar thing with ssh, and I've worked in an environment where we would all just log in to the same root account directly (we could debate how stupid that is, but lets not, welcome to web hosts, common). Also, there's not really any kind of a guarantee that you remember that until you try to do something. You're assuming single user systems where you aren't logging into a lot of different systems in a day. I can't make you do it, but I think it'd be a nice thing to support. I feel like I've defined the use case and the problems involved in not having it well enough.

**Comment by romkatv** [comment]
Does your last comment apply equally to using a new powerlevel10k option as well as to invoking `bindkey -e`? It looks that way. This means this argument doesn't favor one solution over the other.

**Comment by xenoterracide** [comment]
Honestly, I'm just arguing for a visual indicator, or the ability to have one.

**Comment by xenoterracide** [comment]
I guess I would also say, that if you *don't* somehow end up changing modes, it wouldn't impact you.

**Comment by romkatv** [comment]
How about this in `~/.zshrc`?

```zsh
print -ru2 'Your main keymap is EMACS'
bindkey -e
```

There is an indicator and also consistent bindings.

**Comment by xenoterracide** [comment]
I ran that in my shell and then ran `sudo -E` and it didn't seem to propagate. The foreign prompt or immediate prompt, that I might not be able to modify the `rc` of, is more of what I'm worried about.

**Comment by xenoterracide** [comment]
Oh, and that doesn't print when you exit whatever subshell, user, etc. So it's less helpful to know the *current* mode.

**Comment by romkatv** [comment]
If you are unable to modify a shell so that it prints something on startup, then you wouldn't be able to define `POWERLEVEL9K_SOME_NEW_OPTION` in that shell. There is no situation where the new option would help you. Either you would be able to use it, in which case you would be better off just calling `bindkey -e`; or you wouldn't be able to use it, in which case the option is moot.

**Comment by romkatv** [comment]
> Oh, and that doesn't print when you exit whatever subshell, user, etc. So it's less helpful to know the _current_ mode.

You can add whatever text or icon to prompt to indicate that this is *your* prompt and not some random stuff.

The thing is, you cannot modify all prompts in the world, you can only modify your own prompt. And if you can modify your own prompt, you can also enforce emacs keymap. If the prompt is that you cannot distinguish your own prompt from random prompts, then make your prompt more distinguishable. Either way there is no need to add a keymap indicator to your own prompt because your own prompt will always have emacs keymap.

**Comment by xenoterracide** [comment]
Yeah, unless it's the default that it's a different symbol, or you can talk to whomever would be able to. Also, and I am not sure about this at all, but wouldn't/couldn't that symbol change on the PS1 carry over? Or does it require some re-invocation that couldn't? all I'm really thinking is another option for emacs mode here

```
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  # Prompt symbol in command vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  # Prompt symbol in visual vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  # Prompt symbol in overwrite vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
```

**Comment by xenoterracide** [comment]
> The thing is, you cannot modify all prompts in the world, you can only modify your own prompt.

yeah but I've proven you can carry your prompt with you.

**Comment by romkatv** [comment]
> Yeah, unless it's the default that it's a different symbol, or you can talk to whomever would be able to.

I don't understand this sentence.

> Also, and I am not sure about this at all, but wouldn't/couldn't that symbol change on the PS1 carry over?

Nor this.

> Or does it require some re-invocation that couldn't?

Or this.

I suggest we stop this discussion. There is serious miscommunication and we are wasting our time.

**Comment by xenoterracide** [comment]
You have these, all I'm saying is for emacs mode, you'd have a symbol that isn't `❯`, or you could add a modal symbol that's different, but that seems necessary. The variable names even already seem to explicitly say `vi` so they shouldn't be relevant to an emacs mode.

```
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  # Prompt symbol in command vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  # Prompt symbol in visual vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  # Prompt symbol in overwrite vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
```

I'm saying, I don't even know if it's possible for this change to carry over to a shell via `sudo -E` in a way that it would actually change.

> I suggest we stop this discussion. There is serious miscommunication and we are wasting our time.

Up to you, I guess, seems like you're not actually trying to understand what a visual indicator of current mode is, and why that would be useful anywhere.

**Comment by romkatv** [comment]
Either you didn’t understand my comments or I don’t understand yours. Let’s drop this.
