### ISSUE TITLE
Configuration Powerlevel10k

### ISSUE THREAD

**Issue by viet-hung-it** [romkatv/powerlevel10k#1538]
![image](https://user-images.githubusercontent.com/33823245/129132120-d40adc11-9a7e-43ae-a226-b99ba44194a5.png)
i need to configure zsh like this, can anyone help me?

**Comment by romkatv** [comment]
What have you already tried? What does your current prompt look like?

**Comment by viet-hung-it** [comment]
![image](https://user-images.githubusercontent.com/33823245/129154207-79d87ab7-e6c4-4d5d-ae9f-32f791407428.png)

I can't figure out how to make things like batteries or set the time down to the 2nd line

I'm looking forward to getting the .zshrc file content for the first image, i just installed powerlevel10k on elementary os (ubuntu 18.04)

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and read comments above and within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` (it's close to the top). Does that help?
