### ISSUE TITLE
[feature request] new prompt line for "post-command output" / "error indicator"

### ISSUE THREAD

**Issue by ahillio** [romkatv/powerlevel10k#1539]
Regarding: https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them I would love to see the error indication improved.

I do not want this info, indication of error, to be presented in my prompt's most active character `>`.  I don't believe these two things, "this command" and "last command" should be conflated; they are separate things and should be separated visually.

This can be solved!  Rather than trying to re-write the previous `>` indicator to change its color, and rather than indicate the former command's error in this command's prompt... how about adding an additional line for error information?

So instead of:\
![pl10k-prompt-current-error-indication](https://user-images.githubusercontent.com/5461756/129418109-0926d805-66a2-4c45-8d9d-3bb8b7edc244.png)

We could have something like:\
![pl10k-prompt-improved-error-indication](https://user-images.githubusercontent.com/5461756/129418165-eb31328b-c380-4c04-bdd8-9a2306e216fb.png)

What do you think?

**Comment by romkatv** [comment]
Does this mean that the color on the current prompt won't mean anything?

**Comment by ahillio** [comment]
Correct.  Or at least that the color of the current prompt would have nothing to do with the previous command.  (Possibly current prompt color might change to indicate something like vi-mode or another condition of the current command, but that's a different topic.)

**Comment by romkatv** [comment]
Interesting.

What would happen if you press <kbd>Ctrl-L</kbd>?

**Comment by ahillio** [comment]
`Ctrl-L`???? I have no idea.  I use tmux+vim using a vim-tmux-navigator plugin and `Ctrl` + `h`/`j`/`k`/`l` are used for navigating between panes.

**Comment by ahillio** [comment]
What does `Ctrl-L` do for you?

**Comment by romkatv** [comment]
<kbd>Ctrl-L</kbd> is a standard binding in zsh (and in bash). Tmux does not override it. You can try it by starting zsh or bash.

**Comment by ahillio** [comment]
I'm using this plugin https://github.com/christoomey/vim-tmux-navigator so `Ctrl-L` moves me to a tmux pane one place to the right of the current pane.

But I see that when launching a terminal with no tmux that `Ctrl-L` erases the terminal screen.  I'm not sure what that has to do with this feature idea.  Is there a particular interference or something you're wondering about?

**Comment by romkatv** [comment]
I’m just wondering what it should do. Can you draw/print the expected result?

**Comment by ahillio** [comment]
You would normally expect it to clear the terminal screen and put the prompt at the top?  I think that behavior would stay the same.

**Comment by romkatv** [comment]
Would you mind creating a mock image or a mock ascii?

**Comment by ahillio** [comment]
![pl10k-prompt-improved-error-indication_after-ctrl-l](https://user-images.githubusercontent.com/5461756/129424388-a68e6def-e4ba-468a-977f-af2cb497f2e8.png)

I guess that would be at the top of the screen.  With all the history being visually lost.

**Comment by romkatv** [comment]
Thanks for the clarification! You can achieve this by adding the following snippet to `~/.zshrc`:

```zsh
function print-command-status() {
  local -i err=$?
  (( err )) && ! zle && [[ -t 2 ]] || return
  emulate -L zsh -o prompt_percent -o no_prompt_subst
  local sig
  (( err > 128 )) && sig=${signals[err-127]-}
  print -Pu2 -- "%F{196}\\u21B5%f Error. Exit status $err${sig:+ (SIG$sig)}."
}

add-zsh-hook precmd print-command-status
```

My questions above were meant to ascertain whether you want this information in prompt or not. The answer is No -- otherwise you would see it on the screen after pressing <kbd>Ctrl-L</kbd>. Since this information is not a part of prompt, it doesn't need to be and shouldn't be implemented in powerlevel10k. The snippet I posted above works with any prompt, so it's an independent "plugin".

If you use this code, you might want to make `❯` in your prompt always green. For that, open `~/.p10k.zsh` and find this block: https://github.com/romkatv/powerlevel10k/blob/2c135dd631019a251e073a0f4e86267cf12c50c0/config/p10k-lean.zsh#L183-L186

Adjust colors as you like.

You'll might also want to remove `status` from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

Let me know if this works for you and whether it does what you want.

**Comment by ahillio** [comment]
Oh yes!  For my purposes it doesn't need to be part of the prompt at all.  I just don't know much at all about scripting the shell so it never occurred to me that this could be achieved without the prompt.  Following you suggestion exactly gave me precisely what I was hoping for...
![Screenshot_20210814_180425](https://user-images.githubusercontent.com/5461756/129461277-49fd6d1e-d57a-416f-a9a5-7e44bd9f9ab9.png)

Thanks a bunch!

**Comment by romkatv** [comment]
Cool! I'm glad it's working for you.
