### ISSUE TITLE
How to disable bg color of directories

### ISSUE THREAD

**Issue by jiggleexe** [romkatv/powerlevel10k#1542]
![image](https://user-images.githubusercontent.com/66196611/129746530-f4af15b7-0499-4430-b567-841784ab8da0.png)

**Comment by romkatv** [comment]
Type `p10k configure` and select Lean style.

**Comment by jiggleexe** [comment]
and also i would like to remove git master thing too how can I do it

**Comment by jiggleexe** [comment]
> Type `p10k configure` and select Lean style.

but I like rainbow one more is there no workaround to disable it within rainbow style

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and remove the first line with “vcs“ in it.

**Comment by romkatv** [comment]
> > Type `p10k configure` and select Lean style.
> 
> but I like rainbow one more is there no workaround to disable it within rainbow style

There is but you must do it manually. If you cannot figure out how, use Lean style.
