### ISSUE TITLE
MacOS Terminal not saving p10k.zsh config

### ISSUE THREAD

**Issue by abhyusandy** [romkatv/powerlevel10k#1546]
I have installed powerlevel10k theme for terminal via Homebrew. I created ~/.zshrc and followed instructions from the installation guide. The p10k.zsh config is not being saved by terminal. Upon quitting the configuration wizard, pasted the disable config wizard in ~/.zshrc and got the theme working.

Can you tell me why it is happening like this?

I checked following things:
~/.zshrc has read and write permissions for my account.
terminal has full disk access in security&privacy --> full disk access

Tried to login to su account but it has no access to home folder.

I have attached following pics for your reference.

![p10k config fail to save](https://user-images.githubusercontent.com/89185408/130031639-66287e36-0cc6-4c2c-ad63-d620d44f1371.jpg)
![p10k config](https://user-images.githubusercontent.com/89185408/130031690-70709e29-659d-49b7-861d-c97653eca099.jpg)
![terminal](https://user-images.githubusercontent.com/89185408/130031722-e5ce0b33-6e70-41a2-8154-91efa5551026.jpg)
![zshrc](https://user-images.githubusercontent.com/89185408/130031745-186a5657-e67e-4e60-8d5c-ad3b29b584ba.jpg)

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
whoami && ls -ld ~ ~/.zshrc
```

**Comment by abhyusandy** [comment]
![who am i](https://user-images.githubusercontent.com/89185408/130033020-26d3f2e8-72f5-4148-ae3a-1a66ff5bee05.jpg)

**Comment by romkatv** [comment]
The permissions on `~/.zshrc` are incorrect. You can fix them by executing the following command:

```zsh
sudo chown sandeepsagar ~/.zshrc
```

In the future, never modify or create files in your home directory as root.

**Comment by abhyusandy** [comment]
thank you very much

**Comment by romkatv** [comment]
You are welcome.
