### ISSUE TITLE
P10K installed through oh my zsh in wsl2. terminal gets broken in IntelliJ IDEA

### ISSUE THREAD

**Issue by inust33** [romkatv/powerlevel10k#1549]
I have P10k installed through oh-my-zsh in WSL2. It works without problem in Windows Terminal or VScode.
when i load terminal in my IntelliJ IDEA, some garbage and glitches are blocking line.
![화면 캡처 2021-08-21 094245](https://user-images.githubusercontent.com/84079237/130305191-ae233af7-f376-4146-8b50-fdb365942161.png)
![화면 캡처 2021-08-21 094234](https://user-images.githubusercontent.com/84079237/130305243-84e4f24b-661f-4589-992c-1e686a6af2b3.png)
when i searched here, a similar issue #1128 came up,  but it was for Iterm2 and none of the solutions really worked for me .
here is my zshrc files.
I've removed all comments and some custom aliases.

would really appreciate your help.

```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
export ZSH="/home/inu/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"


plugins=(git)

source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
LS_COLORS="ow=01;36;40" && export LS_COLORS
```

**Comment by inust33** [comment]
my IntelliJ shell path is wsl.exe

**Comment by romkatv** [comment]
This is a bug in IntelliJ IDEA. You might be able to work around this problem by running `p10k configure` and trying a more conservative style (I would start with **Lean** and **Few Icons**).
