### ISSUE TITLE
Issue with decrypting gpg encrypted files using hardware key

### ISSUE THREAD

**Issue by preimmortal** [romkatv/powerlevel10k#1550]
Hi,

I have an  GPG encrypted file which can be decrypted using the GPG key stored on a Yubikey.
When using the P10K theme, the decryption fails:

``` 
$ gpg --decrypt --armor encrypted.txt
gpg: anonymous recipient; trying secret key 0xXXXXXXXXXXXXXX ...
gpg: encrypted with RSA key, ID 0x0000000000000000
gpg: decryption failed: No secret key
```
Using another zsh theme, the decryption passes:
```
$ gpg --decrypt --armor encrypted.txt
gpg: anonymous recipient; trying secret key 0xXXXXXXXXXXXXXX  ...
gpg: okay, we are the anonymous recipient.
gpg: encrypted with RSA key, ID 0x0000000000000000
test message string
```

After decryption using another shell or zsh theme, P10K is able to decrypt the file again.

I believe this issue is caused due to an issue with P10K and the pinentry program which makes a PIN request to the Yubikey, since that is the only part that is failing.

Thanks,
-D

**Comment by romkatv** [comment]
Please attach two version of `~/.zshrc`. One that doesn't work and the other that does.

**Comment by preimmortal** [comment]
Sure, here is the zshrc:
[Failing](https://pastebin.com/fTX0Cf7B)
[Passing](https://pastebin.com/wQ6PC4JX)

The only difference are these two lines:
ZSH_THEME="powerlevel10k/powerlevel10k" (fails)
ZSH_THEME="robbyrussell (passes)

**Comment by romkatv** [comment]
Try replacing this:

```zsh
export GPG_TTY="$(tty)"
```

With this:

```zsh
export GPG_TTY=$TTY
```

Then run `exec zsh`. Does this help?

**Comment by preimmortal** [comment]
Yeah that worked!
Thank you very much for the quick replies!

**Comment by romkatv** [comment]
Were you getting an error message when starting shell? Something like "not a tty"?

**Comment by preimmortal** [comment]
I didn't get an error message when starting the shell, but when I `echo $GPG_TTY`, it did say "not a tty".

**Comment by romkatv** [comment]
Interesting. This is a bug in your implementation of `tty`. It's supposed to print error messages to stderr and not to stdout.

Closing as resolved.
