### ISSUE TITLE
Question: how do I add brackets only arround git status signs?

### ISSUE THREAD

**Issue by AtifChy** [romkatv/powerlevel10k#1551]
my current prompt 
![image](https://user-images.githubusercontent.com/42291930/130313716-cd590c45-02ee-4888-94ae-c151d2a74bb4.png)

how do i bold the branch name and add square brackets ``[]`` around git status signs? 
![image](https://user-images.githubusercontent.com/42291930/130313765-de9c6c6f-e579-4187-a321-c4d54dfe9a14.png)

my [p10k config](https://github.com/AtifChy/dotfiles/blob/main/.config/zsh/.p10k.zsh) and my [zshrc](https://github.com/AtifChy/dotfiles/blob/main/.config/zsh/.zshrc)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-change-the-format-of-git-status. You can make text bold by enclosing it in `%B...%b`. See https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html.

**Comment by romkatv** [comment]
Were you getting an error message when starting shell? Something like "not a tty"?

**Comment by AtifChy** [comment]
> See https://github.com/romkatv/powerlevel10k#how-do-i-change-the-format-of-git-status. You can make text bold by enclosing it in `%B...%b`. See https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html.

no

**Comment by AtifChy** [comment]
```(( VCS_STATUS_COMMITS_AHEAD || VCS_STATUS_COMMITS_BEHIND || VCS_STATUS_PUSH_COMMITS_AHEAD || VCS_STATUS_PUSH_COMMITS_BEHIND || VCS_STATUS_STASHES || VCS_STATUS_ACTION || VCS_STATUS_NUM_CONFLICTED || VCS_STATUS_NUM_STAGED || VCS_STATUS_NUM_UN || VCS_STATUS_NUM_UNTRACKED )) && res+=" %1F%B[%b%f"``` should i use this to add opening brackcat before git signs?

**Comment by romkatv** [comment]
If this produces the prompt you desire, then yes.

**Comment by AtifChy** [comment]
> If this produces the prompt you desire, then yes.

yes it does. thanks for your help.

**Comment by romkatv** [comment]
You are welcome.
