### ISSUE TITLE
Theme breaks intellij smart command execution

### ISSUE THREAD

**Issue by NyCodeGHG** [romkatv/powerlevel10k#1558]
There is [this feature](https://www.jetbrains.com/help/idea/terminal-emulator.html#smart-command-execution) in jetbrains IDEs which allows executing some commands using the IDE. But it doesn't work when I'm using this theme. It works with the standard theme from oh-my-zsh.

![with theme](https://user-images.githubusercontent.com/37078297/131159923-3cbf5b69-6219-426b-aa92-ae60ef0991f5.gif)
![Peek 2021-08-27 18-33](https://user-images.githubusercontent.com/37078297/131159928-232705ca-29d9-4acd-972e-310bdc68c72a.gif)

**Comment by romkatv** [comment]
Closing because there is no indication that it’s a Powerlevel10k issue. Please reopen or open a new issue if something needs to be changed or fixed in Powerlevel10k.

**Comment by NyCodeGHG** [comment]
Should be fixed in the next EAP Release of IntelliJ according to a JetBrains Dev:
https://youtrack.jetbrains.com/issue/IDEA-276990#focus=Comments-27-5225264.0-0

**Comment by romkatv** [comment]
Cool! Thanks for the update.
