### ISSUE TITLE
'delete', 'ctrl+left', 'ctrl+right' keys are not working

### ISSUE THREAD

**Issue by gadefox** [romkatv/powerlevel10k#1559]
Is this a bug? When I want to delete character, it shows '~' instead. Also fast moving using 'ctrl + {left | right }' writes {;5D | ;5C} respectively. The same with 'shift' (;2D | ;2C }. Could this be a unicode problem on my 32 bit?

**Comment by romkatv** [comment]
Powerlevel10k doesn’t do anything w.r.t. key bindings. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by gadefox** [comment]
Okay, I'll google.. One more thing (and _I don't want to spam you with issues, but I'm happy to create new one_): I'd like to remove seconds from the time format. Could you specify places in the code please, so I don't need to review whole source code? It'd be helpful..

**Comment by romkatv** [comment]
> I'd like to remove seconds from the time format.

Open `~/.p10k.zsh` and search for " time: ". This works for all other segment, too. If you want to configure segment `$X`, search for " $X: ".

**Comment by gadefox** [comment]
Thanks.. I'd like to have very useful feature implemented and please let me know what you think. Sometimes the execution takes hours and it would be nice to get a notification when it is completed (alsa, send-notify etc) or there is an error.

**Comment by romkatv** [comment]
Powerlevel10k only does prompt.

**Comment by gadefox** [comment]
Sure, but how do you know how long does the execution take? And where is the best place in your code to call alsa and or send-notify?

**Comment by romkatv** [comment]
I’m sorry, this is off topic. You’ll need to ask these questions elsewhere.

**Comment by gadefox** [comment]
> Open ~/.p10k.zsh and search for " time: ". This works for all other segment, too. If you want to configure segment $X, search for " $X: ".

Thanks for the advice. I also changed source files in `config` folder, so the configuration doesn't overwrite the time format.

**Comment by gadefox** [comment]
> When I want to delete character, it shows '~' instead. Also fast moving using 'ctrl + {left | right }' writes {;5D | ;5C} respectively. The same with 'shift' (;2D | ;2C }

For those w/ the same issue: you have to add keybindings for home, end keys (etc.) with appropriate escape sequences to zshrc.
