### ISSUE TITLE
Podman/Toolbox Contenxt prompts

### ISSUE THREAD

**Issue by Lunarequest** [romkatv/powerlevel10k#1560]
Toolbox is a tool for Linux operating systems, which allows the use of containerized command line environments. It is built on top of Podman and other standard container technologies from OCI. On hosts like Fedora Silverblue  where the file system is immutable installing packages is time  consuming  hence a very container centeric workflow is used.

entering the a toolbox is fairly simple with the command `toolbox enter`.  however it is very hard to distinguish a toolbox from the host system. For example here.
![image](https://user-images.githubusercontent.com/30698906/131325915-83c27463-1aa9-4d45-9098-73dbbbacb796.png)
i am proposing something similar to how python virtual envs are shown but with for example `in toolbox` or another phrase indicative of if the user is inside a toolbox container 
![image](https://user-images.githubusercontent.com/30698906/131326148-c3fdf423-f71f-4b95-b0cd-d817dac64e01.png)

**Comment by romkatv** [comment]
Try the following.

1. Open `~/.p10k.zsh`.
2. Search for `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`.
3. Replace that line with this:
   ```zsh
   # Display "toolbox" next to the OS icon when inside a toolbox container.
   if [[ -f /run/.containerenv && -f /run/.toolboxenv ]]; then
     typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='$P9K_CONTENT toolbox'
   fi
   ```

**Comment by advaithm** [comment]
this is exactly what i was looking for. Could this be made default behavior? 
![image](https://user-images.githubusercontent.com/30698906/131327574-258820ee-76f4-4c65-adad-0ea40e127b94.png)

**Comment by romkatv** [comment]
> this is exactly what i was looking for.

That's good 👍 

> Could this be made default behavior?

Not this change, no. Adding a separate segment would be nice though. I'll keep this issue open for a while even though it's unlikely I'll be doing anything about it.

By the way, that weirdness on the right hand side of your prompt is caused by your terminal's background color being identical to color 0 (black). You can fix it either by changing one of these colors in the terminal config or by replacing all instances of "BACKGROUND=0" in `~/.p10k.zsh` with something else. My advice is to change color 0 (black) in your terminal so that it's not identical to the background color. Since the background is grey, try pitch black as color 0, or something that's in between pit black and the current value that you have.

**Comment by advaithm** [comment]
> > this is exactly what i was looking for.
> 
> That's good +1
> 
> > Could this be made default behavior?
> 
> Not this change, no. Adding a separate segment would be nice though. I'll keep this issue open for a while even though it's unlikely I'll be doing anything about it.

I there any where that explains how one could add segments? I'd like to try and implement this
> 
> By the way, that weirdness on the right hand side of your prompt is caused by your terminal's background color being identical to color 0 (black). You can fix it either by changing one of these colors in the terminal config or by replacing all instances of "BACKGROUND=0" in `~/.p10k.zsh` with something else. My advice is to change color 0 (black) in your terminal so that it's not identical to the background color. Since the background is grey, try pitch black as color 0, or something that's in between pitch black and the current value that you have.
That is an unfortunate side effect of konsole blue on top of a github page with the dark theme.

**Comment by advaithm** [comment]
> > That is an unfortunate side effect of konsole blue on top of a github page with the dark theme.
> 
> What does blue or github have to do with it? Perhaps you didn't understand what I meant?
> 
> The issue I'm alluding to is that on your terminal the output of `print -P '%K{0} %k'` is invisible or almost invisible. You can fix this by opening your terminal preferences and manually changing color 0 (black). I suggest making it darker.

I meant blur.

**Comment by romkatv** [comment]
I'm confused.

Are you saying you've fixed the issue? Or perhaps that you don't know how to fix it? Or maybe that it cannot be fixed? Or that it's not an issue for you?

**Comment by advaithm** [comment]
> I'm confused.
> 
> Are you saying you've fixed the issue? Or perhaps that you don't know how to fix it? Or maybe that it cannot be fixed? Or that it's not an issue for you?

It's not an issue.

**Comment by romkatv** [comment]
Good 👍 Thanks for clearing that out.

**Comment by Funky185540** [comment]
Hey, a bit "late", but here's my approach to the "issue":

You add this to the prompt configuration:

```
    my_toolbox              # toolbox identifier
```

And somewhere below you add this block:

```zsh
  ################################[ my_toolbox: toolbox identifier ]###########################
  typeset -g POWERLEVEL9K_MY_TOOLBOX_ENABLED_FOREGROUND=black
  typeset -g POWERLEVEL9K_MY_TOOLBOX_ENABLED_BACKGROUND=yellow
  typeset -g POWERLEVEL9K_MY_TOOLBOX_ENABLED_VISUAL_IDENTIFIER_EXPANSION=''
#  typeset -g POWERLEVEL9K_MY_TOOLBOX_ENABLED_CONTENT_EXPANSION=

  typeset -g POWERLEVEL9K_MY_TOOLBOX_DISABLED_FOREGROUND=
  typeset -g POWERLEVEL9K_MY_TOOLBOX_DISABLED_BACKGROUND=
  typeset -g POWERLEVEL9K_MY_TOOLBOX_DISABLED_VISUAL_IDENTIFIER_EXPANSION=''
  typeset -g POWERLEVEL9K_MY_TOOLBOX_DISABLED_CONTENT_EXPANSION=''

  function prompt_my_toolbox {
    if [ -f "/run/.toolboxenv" ]; then
      local state=ENABLED
      local name=$(grep -oP '(?<=\bname=")[^";]+' /run/.containerenv)
    else
      local state=DISABLED
      local name="N/A"
    fi
    p10k segment -s $state -i '' -f blue -t "$name"
  }
```

(caution: Github mangled the toolbox icon behind the `-i`!)

And now my default shell looks like this:

![shell_default](https://user-images.githubusercontent.com/13232838/132103737-a0262135-1c0b-4019-a888-4a32ed64c0f8.png)

and when I'm in toolbox it shows an Icon and the current toolboxes name:

![toolbox_segment](https://user-images.githubusercontent.com/13232838/132103749-8355cefc-d2e6-4fce-a63f-0708ccc38b9e.png)

It's probably not very elegant and loading the segment takes a while (i.e. it appears a short while, fractions of a second or so, after entering the toolbox), but once that's done the prompt is a fluent as ever!

**Comment by Funky185540** [comment]
Oh and I searched here for the pretty icons: https://www.nerdfonts.com/cheat-sheet

Not sure if that's the right place, but I believe that's what Meslo LGS was patched with, and it works!

The tools symbol has code `e20f`, but for me escaping it as `-i '\ue20f'` didn't work, so I copied the icon from the nerfonts page directly.

**Comment by romkatv** [comment]
Try `$'\ue20f'`

**Comment by Funky185540** [comment]
Yeah, that does the trick. Thank you!

**Comment by romkatv** [comment]
Here's a more efficient implementation of `my_toolbox` prompt segment:

```zsh
if [[ -e /run/.toolboxenv && -r /run/.containerenv ]]; then
  typeset -g my_toolbox_name=${(Q)${${(@M)${(f)"$(</run/.containerenv)"}:#name=*}#name=}}
  function prompt_my_toolbox {
    p10k segment -i $'\uE20F' -b yellow -f black -t "$my_toolbox_name"
  }
fi
```

If you switch to it, you can remove all `POWERLEVEL9K_MY_TOOLBOX_*` parameters.

The advantage of this implementation is that it doesn't have to run `grep` before every command (basically, every time you press ENTER in zsh). External commands are extremely slow. Just a handful of them will introduce noticeable prompt lag.

**Comment by Funky185540** [comment]
Is there a chance it could become an official tile? If so: What would still need to be done for that?

**Comment by romkatv** [comment]
I've added the official `toolbox` prompt segment. It's better than the custom prompt segment I posted in my previous comment (https://github.com/romkatv/powerlevel10k/issues/1560#issuecomment-913101184), so I recommend changing your configs.

You'll need to update powerlevel10k, run `exec zsh`, and then either run `p10k configure` or manually add `toolbox` to your existing `~/.p10k.zsh`.

**Comment by Lunarequest** [comment]
I've tried it out, its pretty good. I'm closing this  issue

**Comment by romkatv** [comment]
Thanks for verifying.

**Comment by debarshiray** [comment]
> I've added the official `toolbox` prompt segment.

That's really cool!  Thanks.
