### ISSUE TITLE
Please move all "your" files from ~/.cache to ~/.cache/p10k folder

### ISSUE THREAD

**Issue by gadefox** [romkatv/powerlevel10k#1561]
Thanks.

**Comment by romkatv** [comment]
I don't think I will.

**Comment by gadefox** [comment]
Why are you polluting standard folders (.cache/.config) in this case??

**Comment by romkatv** [comment]
Why are you saying I'm polluting standard folders?

**Comment by gadefox** [comment]
I think it's self-explanatory. You should create one single folder and put everything there otherwise you're causing a mess.

**Comment by romkatv** [comment]
> I think it's self-explanatory.

It isn't.

> You should create one single folder and put everything there 

Why?

> you're causing a mess.

Why do you think so?

**Comment by gadefox** [comment]
Let's say I want to "uninstall" your app. You know I have to do it manually, right? How do I know what belongs to your app? The easiest way is to search one single folder in ~/.config and delete it. The same with cache, share, etc. etc. And let's say everyone follows your standards. Then I have 1000 files in the cache root.. Does it make sense now?

**Comment by romkatv** [comment]
> Let's say I want to "uninstall" your app. You know I have to do it manually, right? How do I know what belongs to your app?

You would need to look at the docs: https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k

> ### How do I uninstall Powerlevel10k?
> 
> 1. Remove all references to "p10k" from `~/.zshrc`. You might have this snippet at the top:
>    ```zsh
>    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
>      source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
>    fi
>    ```
>    And this at the bottom:
>    ```zsh
>    [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
>    ```
>    These are added by the [configuration wizard](#configuration-wizard). Remove them.
> 2. Remove all references to "powerlevel10k" from `~/.zshrc`, `~/.zpreztorc` and `~/.zimrc` (some
>    of these files may be missing -- this is normal). These references have been added manually by
>    yourself when installing Powerlevel10k. Refer to the [installation instructions](#installation)
>    if you need a reminder.
> 3. Verify that all references to "p10k" and "powerlevel10k" are gone from `~/.zshrc`, `~/.zpreztorc`
>    and `~/.zimrc`.
>    ```zsh
>    grep -E 'p10k|powerlevel10k' ~/.zshrc ~/.zpreztorc ~/.zimrc 2>/dev/null
>    ```
>    If this command produces output, there are still references to "p10k" or "powerlevel10k". You
>    need to remove them.
> 4. Delete Powerlevel10k configuration file. This file is created by the
>    [configuration wizard](#configuration-wizard) and may contain manual edits by yourself.
>    ```zsh
>    rm -f ~/.p10k.zsh
>    ```
> 5. Delete Powerlevel10k source files. These files have been downloaded when you've installed
>    Powerlevel10k. The command to delete them depends on which installation method you'd chosen.
>    Refer to the [installation instructions](#installation) if you need a reminder.
> 
>    | Installation              | Uninstall command                                                |
>    |---------------------------|------------------------------------------------------------------|
>    | [Manual](#manual)         | `rm -rf ~/powerlevel10k`                                         |
>    | [Oh My Zsh](#oh-my-zsh)   | `rm -rf -- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k` |
>    | [Prezto](#prezto)         | n/a                                                              |
>    | [Zim](#zim)               | `zimfw uninstall`                                                |
>    | [Antigen](#antigen)       | `antigen purge romkatv/powerlevel10k`                            |
>    | [Zplug](#zplug)           | `zplug clean`                                                    |
>    | [Zgen](#zgen)             | `zgen reset`                                                     |
>    | [Zplugin](#zplugin)       | `zplugin delete romkatv/powerlevel10k`                           |
>    | [Zinit](#zinit)           | `zinit delete romkatv/powerlevel10k`                             |
>    | [Homebrew](#homebrew)     | `brew uninstall powerlevel10k; brew untap romkatv/powerlevel10k` |
>    | [Arch Linux](#arch-linux) | `yay -R --noconfirm zsh-theme-powerlevel10k-git`                 |
> 6. Restart Zsh. [Do not use `source ~/.zshrc`](#weird-things-happen-after-typing-source-zshrc).

This list doesn't mention cache files. That's an oversight. Thanks for brining it to my attention. I've fixed it by adding this:

> 7. Delete Powerlevel10k cache files.
>    ```zsh
>    rm -rf -- "${XDG_CACHE_HOME:-$HOME/.cache}"/p10k-*(N) "${XDG_CACHE_HOME:-$HOME/.cache}"/gitstatus
>    ```

Does this resolve your concerns?

**Comment by gadefox** [comment]
Why do you do this? I'm pretty sure you know exactly what the point is.. But let me clarify it again: You create folder* in the ~/.cache and then you don't use it?! What's the reason?

* You create one folder for each user so technically it's not one.. but I hope you understand what I mean..

**Comment by romkatv** [comment]
It’s pointless to tell me to make specific changes. I don’t do those things. If you can describe the issue you are having, I’ll figure out how to solve it. Here’s an example of an issue: After uninstalling Powerlevel10k cache files are left over. Here’s an example of a request for specific changes: Move files from A to B. The former is useful to me, the latter isn’t.

**Comment by romkatv** [comment]
Closing as invalid. In the future please describe the issue, not what you believe is a solution.

**Comment by gadefox** [comment]
> not what you believe is a solution

Well, this is exactly the reason why you act like you don't understand and play games with me. 

> Closing as invalid.

I don't think so, therefore I changed the code by myself. Thanks for your time..

**Comment by romkatv** [comment]
I’m not playing games and not pretending to misunderstand. What I need is the description of an issue. The symptoms of a problem. “When I do *this* it hurts.” I’m not misunderstanding when you reply “do X”. I simply ignore it because it’s not describing anything.
