### ISSUE TITLE
Why can't I edit "[ ! -f ~/.config/zsh/.p10k.zsh ] || source ~/.config/zsh/.p10k.zsh" at all?

### ISSUE THREAD

**Issue by gadefox** [romkatv/powerlevel10k#1562]
I'd like to move this line of code to /etc/zshrc, but I can't, because the app thinks it's not configured. Can't you check anything else e.g. comment "# please don't delete this line" instead? Ta

**Comment by romkatv** [comment]
If you want to move this line, go ahead and move it. If you decide to run `p10k configure` afterwards and it asks you whether you want your `~/.zshrc` to be modified, say No.

**Comment by gadefox** [comment]
> but I can't, because the app thinks it's not configured

Mea culpa, it's not true what I wrote. It was my (wrong) assumption based on the behavior on my PC..

**Comment by romkatv** [comment]
No worries. I'm glad you've solved this problem.
