### ISSUE TITLE
Suggestions have wrong color in tmux

### ISSUE THREAD

**Issue by gadefox** [romkatv/powerlevel10k#1564]
Please let me know if this is your issue or it belongs to tmux. Suggestions have different color on xterm, gnome-terminal, st. But when I use tmux, all selections are displayed with the same text color - which is pretty annoying. Thanks

**Comment by romkatv** [comment]
Powerlevel10k only does prompt: https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by gadefox** [comment]
**Solution**: 256 color terminal instead of 16..
