### ISSUE TITLE
BUG: there is a problem with my terminal

### ISSUE THREAD

**Issue by tanzi1997** [romkatv/powerlevel10k#1566]
environment：
  OS：MACOS Big sur 11.5.2
  APP：iTerm2

Hello, there is a problem with my terminal

<img width="730" alt="CleanShot 2021-09-07 at 10 30 27@2x" src="https://user-images.githubusercontent.com/23359102/132275121-7a69c53b-e9ad-4357-9426-b3f76a4f7bb1.png">

font：
MesloLGS NF

<img width="612" alt="CleanShot 2021-09-07 at 10 38 54@2x" src="https://user-images.githubusercontent.com/23359102/132275806-921b9603-cdb5-4b10-8a55-db5fdd9c000f.png">

**Comment by romkatv** [comment]
What is the problem?

**Comment by romkatv** [comment]
Perhaps this will help: https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by tanzi1997** [comment]
thanks  Is this problem
some prompt styles are missing from the configuration wizard

But i can't solve

```zsh
> print $terminfo[colors]
256
```

<img width="594" alt="CleanShot 2021-09-07 at 16 27 21@2x" src="https://user-images.githubusercontent.com/23359102/132311516-c4d96db4-8f17-4e00-9443-1a4443326363.png">

**Comment by tanzi1997** [comment]
sorry

The reason is that I chose No in the first step
