### ISSUE TITLE
can't add node and os icon

### ISSUE THREAD

**Issue by nudelx** [romkatv/powerlevel10k#1567]
<img width="1047" alt="Screen Shot 2021-09-07 at 13 01 04" src="https://user-images.githubusercontent.com/2046035/132326151-0b35968f-2512-4e80-aa52-a319ced3669b.png">

**Comment by romkatv** [comment]
To see the icons you need to install a capable font, configure your terminal to use it, run `p10k configure` and select *Lean*, *Classic* or *Rainbow* style.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/font.md and https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by nudelx** [comment]
thank you for the super-fast response !!
so I am using the font installed by the configuration. and the second annoying issue is there is no padding between branch icons, do I have some way to change it?
<img width="280" alt="Screen Shot 2021-09-07 at 13 32 53" src="https://user-images.githubusercontent.com/2046035/132330634-18d184ff-c0e5-4ada-b343-0cc8c823dfea.png">

<img width="583" alt="Screen Shot 2021-09-07 at 13 31 29" src="https://user-images.githubusercontent.com/2046035/132330326-ef86581a-0cb2-4f49-9ad1-2729306b65da.png">

**Comment by romkatv** [comment]
> so I am using the font

Good. Proceed to the next step from my previous comment.

**Comment by nudelx** [comment]
ok, I found the problem, it wasn't related to the p10k :) now it's ok  
<img width="498" alt="Screen Shot 2021-09-07 at 14 09 53" src="https://user-images.githubusercontent.com/2046035/132335149-e1498a04-48a9-438a-9763-8bafca277e8b.png">
can I change or disable only one icon, for example, the folder icon?
thank you !!!

**Comment by romkatv** [comment]
You can change or disable icons by editing `~/.p10k.zsh`.

**Comment by nudelx** [comment]
yes, I see, 
where can I find the doc about variable names and how to replace it 
I am looking into the src internal/icons.zsh but it feels kinda not a legit way to reverse it :)

**Comment by romkatv** [comment]
The only documentation is the comments in `~/.p10k.zsh`.

**Comment by nudelx** [comment]
ok, thank you !
