### ISSUE TITLE
Instant prompt not working

### ISSUE THREAD

**Issue by SilverLiningSL** [romkatv/powerlevel10k#1569]
Hi,
Just installed p10k, but instant prompt doesn't work as expected.
![image](https://user-images.githubusercontent.com/44988999/132698728-48a92311-0d81-4871-a514-4274489881ff.png)
![image](https://user-images.githubusercontent.com/44988999/132699363-2638a82b-35e7-4d4a-aa01-6f1c5d8f65e9.png)

```shell
❯ typeset -pm 'POWERLEVEL9K_INSTANT_PROMPT|ZSH_VERSION'
typeset ZSH_VERSION=5.8
typeset POWERLEVEL9K_INSTANT_PROMPT=verbose
```
Could you please tell me where I went wrong and what can I do?

**Comment by romkatv** [comment]
Why do you think that instant prompt isn’t working as expected?

**Comment by SilverLiningSL** [comment]
> Why do you think that instant prompt isn’t working as expected?

because if I'm not making it wrong, enabled instant prompt will be able to highlight syntax like mkdir or ls?

**Comment by romkatv** [comment]
No, Powerlevel10k doesn’t do that. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by SilverLiningSL** [comment]
> No, Powerlevel10k doesn’t do that. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

Oh, seems I made a mistake. Thanks and sorry to disturb
