### ISSUE TITLE
Question mark before each line

### ISSUE THREAD

**Issue by francoism90** [romkatv/powerlevel10k#157]
![image](https://user-images.githubusercontent.com/5028905/62682963-acc41580-b9bd-11e9-9b46-d86cbda47fc3.png)

This is on Arch Linux with Konsole, oh-my-zsh-git and zsh-theme-powerlevel10k-git or steps in README.

In gnome-terminal a desktop is shown before each line (hostname `desktop1`) - is this correct? Anyway to disable this?

Thanks.

**Comment by romkatv** [comment]
It tries to show the Arch Linux icon but your font cannot render it. I'll need a bit more info to figure out the reason.

If you run `p10k configure`, does this icon render in the wizard? It's on the screen close to the very end when you are asked whether you want few or many icons.

How do you answer the yes/no questions in the first several screens of the wizard? These are the questions in the form "Does this look like a XXX?"

What font are you using and how did you install it?

P.S.

You can disable that icon by commenting out `os_icon` in `~/.p10k.zsh`. It's around here: https://github.com/romkatv/powerlevel10k/blob/93230ae6ec92add5f86bf6131c970a3c04f232cd/config/p10k-lean.zsh#L28.

I would really appreciate if you can answer the questions above anyway. This way I can fix this issue for everyone.

**Comment by francoism90** [comment]
@romkatv Some icons render correctly, only this is one in the wizard doesn't work and I respond with `n` :
![image](https://user-images.githubusercontent.com/5028905/62683595-214b8400-b9bf-11e9-857e-5859103d1d71.png)

Konsole font: `otf-fira-code 1.207-1`

Thanks for looking into the issue.

**Comment by romkatv** [comment]
Just to clarify, you answered the first 3 questions with `y`, `y`, `n`?

What's the output of `echo $POWERLEVEL9K_MODE`?

Which of the following render correctly?

1. `print '\uE26E'` -- Apple.
1. `print '\uF179'` -- Apple.
1. `print '\uF16B'` -- Dropbox.
1. `print '\uE1AD'` -- Wireless.
1. `print '\uF1EB'` -- Wireless.
1. `print '\uF09E'` -- Wireless.

> If you run `p10k configure`, does this icon render in the wizard? It's on the screen close to the very end when you are asked whether you want few or many icons.

Would appreciate if you can answer this.

**Comment by francoism90** [comment]
> Just to clarify, you answered the first 3 questions with y, y, n?

Yes, same order.

Output:
![image](https://user-images.githubusercontent.com/5028905/62689445-18f94600-b9cb-11e9-86c2-3d7936191d9a.png)

![image](https://user-images.githubusercontent.com/5028905/62689492-33cbba80-b9cb-11e9-9476-cf93431b843e.png)

**Comment by romkatv** [comment]
Thanks, that was useful.

> If you run `p10k configure`, does this icon render in the wizard? It's on the screen close to the very end when you are asked whether you want few or many icons.

It would help if you could answer this question. Basically, when you get to this screen:

![few-or-many-icons](https://user-images.githubusercontent.com/1282067/62689767-b8b6d400-b9cb-11e9-8d84-2c67c32d5852.png)

I believe you are choosing (2) here. **Does the icon on the left side of the prompt render or is it a question mark**? On my screenshot it shows Ubuntu logo (I'm using Ubuntu).

**Comment by francoism90** [comment]
> I believe you are choosing (2) here.

True

Output and I indeed would like to use (2):

![image](https://user-images.githubusercontent.com/5028905/62690852-c8cfb300-b9cd-11e9-9b11-d83736c94b66.png)

**Comment by romkatv** [comment]
Thanks for your help in debugging this.

I've committed a fix. Please update powerlevel10k and run `p10k configure`. You are now supposed to see a Linux logo where you previously saw that broken question mark. Let me know whether it works.

**Comment by francoism90** [comment]
@romkatv Thanks for pushing a fix. The icon does overlap thought:
![image](https://user-images.githubusercontent.com/5028905/62693140-3251c080-b9d2-11e9-8a6e-311122a96bbc.png)

When running the wizard the python logo isn't rendered correctly - should I simple ignore that one? :)
Also would be it be possible to show an Arch icon instead of a generic Linux one?

**Comment by romkatv** [comment]
> The icon does overlap thought.

Your screenshot doesn't show any overlap -- there is plenty of space between linux logo and home icon. Linux logo is truncated because Konsole is buggy. It's the only terminal with this particular bug. I've committed a workaround that should help. Please update and run `p10k configure` again.

> When running the wizard the python logo isn't rendered correctly - should I simple ignore that one?

Make sure to answer `n` when you are presented with an icon that doesn't render. The wizard will switch that icon for another. Type `VIRTUAL_ENV=foo/bar` to see the replacement Python icon in your prompt.

> Also would be it be possible to show an Arch icon instead of a generic Linux one?

Sure. Just use a [good font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-my-icons-andor-powerline-symbols-look-bad). You'll also get more styling options.

**Comment by francoism90** [comment]
Thanks for the fixes and details. :)

Is it correct that the linked font doesn't include the symbols? Any other terminal you recommend on KDE?

**Comment by romkatv** [comment]
> Is it correct that the linked font doesn't include the symbols?

Could you clarify? You've installed that font and some symbols don't render? Or something else?

> Any other terminal you recommend on KDE?

If you switch to a monospace font (e.g., the recommended one), your prompt will fine in Konsole.

**Comment by francoism90** [comment]
> Could you clarify? You've installed that font and some symbols don't render? Or something else?

I would like more symbols and if I understand correctly using the correct (symbol) font includes this icon?

> Any other terminal you recommend on KDE?

Thanks, will try another monospace font.

**Comment by romkatv** [comment]
> I would like more symbols and if I understand correctly using the correct (symbol) font includes this icon?

[The recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k) has all symbols, including the Arch logo.

> Thanks, will try another monospace font.

Your Fira isn't monospace, hence massive icons and truncated glyphs. The recommended font is monospace.

**Comment by romkatv** [comment]
> [The recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k) has all symbols, including the Arch logo.

To clarify, that font is self-contained. Once you configure your terminal to use `MesloLGS NF`, all symbols will come from `MesloLGS NF`, including regular letters, numbers and fancy icons. You don't need to have any other fonts on your system for your prompt to look good.

**Comment by francoism90** [comment]
Would it be possible to distribute these fonts (optional) with this theme? It would make it easier to integrate it into the current AUR package and allow global install.

**Comment by romkatv** [comment]
It's possible, but I don't want to increase the size of this repo by 5MB. Plus, unlike zsh files that have to be installed on all machines that you access, you only need to install fonts on your dev machines. Most people have just one or two dev machines.

> Maybe adding the details to the README (includes symbols, etc.) would be helpful, I wasn't aware of this.. but maybe it's only me. :)

To be honest, I still don't understand the question about symbols.

Here's what the readme says:

> Powerlevel10k doesn't require custom fonts but can take advantage of them if they are available. The full choice of style options is available only when using Nerd Fonts.

And then on the next line, in bold:

> Recommended: Meslo Nerd Font patched for Powerlevel10k

The first item in the FAQ:

> Q: Why my icons and/or powerline symbols look bad?
> Q: It's likely your font's fault. Install **the recommended font** and run `p10k configure`.

What should be changed to make it clear that the recommended font is recommended?

**Comment by francoism90** [comment]
@rawkode Sorry for the noise, I must learn how to read. :)
