### ISSUE TITLE
The configuration screen show each time

### ISSUE THREAD

**Issue by Satheez** [romkatv/powerlevel10k#1570]
Hi, 
I've installed 'powerlevel10k' on my mac with zsh ( https://ohmyz.sh/ ).
I've setup the configuration the first time but whenever I open a new window the same configuration option is show and I'm unable to turn it off (Suggested option "echo 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true' >>! ~/.zshrc" is not working.

Is there anything that I've missed.
May thanks in advance.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by Satheez** [comment]
I had a syntax error on '~/.zshrc' file.
Thank you @romkatv.
