### ISSUE TITLE
How can I set up the output of the npm version (not the local version of the package that is available out of the p10k box, but the general global version) in the right-hand segment?

### ISSUE THREAD

**Issue by haosmos** [romkatv/powerlevel10k#1571]
First of all, thank you very much for your awesome tool! 

I should note that I don't understand .bash language at all and I came up with my solution by studying other people's code 😂

In the .p10k.zsh file, I have tried these options: 

```
function promt_my_npm_version() {
    if which npm 2>/dev/null 1>/dev/null && [ -f "./package.json" ]; then
      NPM_VERSION='npm -v'
      p10k segment -b yellow -f red -i '📦' -t "${NPM_VERSION}"
    fi
}
```
and: 

```
function promt_my_npm_version() {
    if [ -f "./package.json" ]; then
      NPM_VERSION='npm -v'
      p10k segment -b yellow -f red -i '📦' -t "${NPM_VERSION}"
    fi
}
```

I also specified my custom function in the right segment output settings: 

![Code_v1KaiabjY3](https://user-images.githubusercontent.com/30666874/133002921-4bbac487-4b80-49b2-8849-d7b0d7f0b9c9.png)

But nothing works: 
![F91UywGyKd](https://user-images.githubusercontent.com/30666874/133002998-79b3d58f-a10a-4775-8b16-f1360c6bf35b.png)

I ran the command:

`source ~/.p10k.zsh`

And restarted wsl - doesn't help either. 

I would like to place the npm icon and its version number after the node.js version output.

My environment: 

zsh 5.8 (x86_64-ubuntu-linux-gnu)
ohmyzsh
p10k: 1.15.0
os: wsl 2 (ubuntu 20.04)

**Comment by romkatv** [comment]
This should work:

```zsh
function prompt_my_npm_version() {
  emulate -L zsh -o extended_glob
  (( ${+commands[npm]} )) && [[ -n ./(../)#package.json(#qN) ]] || return
  local v
  v=$(npm -v) && [[ -n $v ]] || return
  p10k segment -b yellow -f red -i $'\U1F4E6' -t $v
}
```

Note that I've changed the body **and** the name of the function (your function had a typo in its name).

This should display the output of `npm -v` in your prompt whenever you are in a directory with `package.json` in it or in a subdirectory thereof. It'll also make your prompt **really slow** because it'll invoke `npm -v` whenever you press <kbd>Enter</kbd>.

**Comment by haosmos** [comment]
> The icon you've originally chosen is a _wide character_ according to UNICODE 9. Many terminals have bugs in their handling of wide characters, which results in broken prompt. This is why Powerlevel10k doesn't use any wide characters in its default configuration. The character you've chosen as a substitute is _narrow_, so it should work well in all terminals. It also looks better because it respects the chosen foreground color.

— It seems that the problem is with the webstorm terminal: in windows terminal and in vs code everything is displayed correctly - icons and fonts. The lines are also without gaps. I have installed custom icons for successful and unsuccessful commands in p10.k:

![WindowsTerminal_eQpsHbjAPf](https://user-images.githubusercontent.com/30666874/133266620-44735495-264f-41c6-8898-b18ca5e0ca04.png)

I use fira code: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode

Again, everything displays correctly in windows terminal and vs code, but not in webstorm: 

![webstorm64_D9W1S133n6](https://user-images.githubusercontent.com/30666874/133267271-75792265-f3ff-4d9a-847a-9ef1919afb7b.png)

I tried many fonts like Meslo, Jetbrains Mono, Cascadia Code, and many others. I even patched myself with font-pathcer.

I have looked into this issue — how to set up the display of icons in webstorm terminal and as far as I understand there is no good solution yet. 

Someone advised to put such settings in webstorm64.exe.vmoptions file: 

```
-Dfile.encoding=UTF-8
-Dconsole.encoding=UTF-8
```

I did that, but it didn't help 😢.

**Comment by romkatv** [comment]
> — It seems that the problem is with the webstorm terminal

Yep, webstorm terminal has many rendering issues. It's not something you can fix. As a workaround I would suggest disabling prompt frame. It doesn't have any useful purpose anyway. Also, avoid wide characters.

> I tried many fonts like Meslo, Jetbrains Mono, Cascadia Code, and many others. I even patched myself with font-pathcer.

Changing fonts cannot help. It's not a font issue. It's a buggy terminal issue.

> Someone advised to put such settings in webstorm64.exe.vmoptions file:
> 
> ```
> -Dfile.encoding=UTF-8
> -Dconsole.encoding=UTF-8
> ```

This cannot possibly help.
