### ISSUE TITLE
How to use icons from internal/icons.zsh for git?

### ISSUE THREAD

**Issue by Rizhiy** [romkatv/powerlevel10k#1573]
Hi, I migrated from p9k to p10k, and while most of the stuff works, git icons do not.

Docs say that I need to modify `my_git_formatter` to update it. I would like to use icons from `internals/icons.zsh` in my config, but their definitions don't seem to be available (at least if I just type them normally).

How can use those icons in my config?

P.S. Shouldn't they also be automatically picked up when theme is selected?

**Comment by romkatv** [comment]
> Hi, I migrated from p9k to p10k, and while most of the stuff works, git icons do not.

You can use your old p9k config with p10k. In order to get literally the same prompt you need to define these two parameters in addition to the ones you already have:

```zsh
```
It'll give you literally the same prompt.

**Comment by Rizhiy** [comment]
> The same way as any other icon: either specify them literally ('⎈') or via their UNICODE number ($'\u2388')

That is kind of ugly, I want them to follow if I change the theme. Is there a way to them as variables?

**Comment by romkatv** [comment]
> Is there a way to them as variables?

Sure.

```zsh
foo='⎈'
bar=$'\u2388'
```

**Comment by Rizhiy** [comment]
That's not what I meant. Anyway the answer is set:
```
typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=false
```

**Comment by romkatv** [comment]
> ```zsh
> typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=false
> ```

If you want to do this, it's also a good idea to remove `POWERLEVEL9K_VCS_CONTENT_EXPANSION` and `POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION`. It won't make a visible difference but it'll speed things up. You can also delete `my_git_formatter` as it's not used by anything with your settings.

If you want your prompt to look exactly the same way it looked in Powerlevel9k, see the first paragraph in https://github.com/romkatv/powerlevel10k/issues/1573#issuecomment-919840722.

**Comment by Rizhiy** [comment]
The thing is, I don't want the whole prompt to look exactly the same.
I still want to use `p10k configure`, but I would like my git bar to remain the same.

**Comment by Rizhiy** [comment]
Thanks, I just commented it out for now.

**Comment by romkatv** [comment]
> The thing is, I don't want the whole prompt to look exactly the same.
> I still want to use `p10k configure`, but I would like my git bar to remain the same.

Alright. Then what you've done is not the worst way to go about it.

**Comment by PatTheMav** [comment]
Sorry for semi-necro-ing this (closed) issue, but I found the question raised in the OP interesting:

Given that `icons.zsh` already defines glyphs for specific purposes for different font setups (e.g. `VCS_UNTRACKED_ICON`), I'd assume that using that identifier in a config instead of the unicode value (or raw glyph) would help with portability of this config.

Say I run this config on a machine with a Nerd-Font enhanced font, but then take it with me to a machine which doesn't, it would allow the prompt theme to gracefully use the alternatives specified in `icons.zsh` instead of requiring me to change all the unicode code points in the config.

From what I could take the file is used for generation of the config but not intended to setup "global" font identifiers in configs.

**Comment by romkatv** [comment]
> Say I run this config on a machine with a Nerd-Font enhanced font, but then take it with me to a machine which doesn't, it would allow the prompt theme to gracefully use the alternatives specified in `icons.zsh` instead of requiring me to change all the unicode code points in the config.

Do you have this use case?

**Comment by PatTheMav** [comment]
A had it a few times e.g. when using a web console to VPS servers. But upon further inspection it occurred to me that such a functionality would require detecting whether the used font has the glyphs, which - as far as I know - you cannot do within a shell script.

As such an end user would have to manually adjust their config anyway (or switch to another config) which makes the whole thing a bit moot.. 🤷🏻‍♂️
