### ISSUE TITLE
Question: Why is zcompile always called with -R flag?

### ISSUE THREAD

**Issue by trallnag** [romkatv/powerlevel10k#1574]
Hello, thanks for this great project.

I'm interested in `zcompile` and I noticed that this project only uses `zcompile -R`. Never `zcompile -M` or the "auto" mode where zcompile itself decides if R or M should be used.

Is there a specific reason for this?

>        -R     When the compiled file is read, its contents are copied into
>               the  shell's  memory,  rather  than  memory-mapped (see -M).
>               This happens automatically on systems that  do  not  support
>               memory mapping.
> 
>               When compiling scripts instead of autoloadable functions, it
>               is often desirable to use this option; otherwise  the  whole
>               file,  including  the  code  to  define functions which have
>               already been defined, will remain mapped, consequently wast‐
>               ing memory.
> 
>        -M     The  compiled  file  is  mapped into the shell's memory when
>               read. This is done in such a way that multiple instances  of
>               the  shell  running  on the same host will share this mapped
>               file.  If neither -R nor -M is given, the  zcompile  builtin
>               decides what to do based on the size of the compiled file.
>
> - https://github.com/antonio/zsh-config/blob/master/help/zcompile

**Comment by romkatv** [comment]
This is done to avoid errors if the zwc files are deleted while zsh is still running. This happens when you update Powerlevel10k in one terminal but still have another terminal running.

**Comment by trallnag** [comment]
okay thanks for the answer
