### ISSUE TITLE
OS X Terminal "marks" are defeated by Transient Prompt.

### ISSUE THREAD

**Issue by barkofdelight** [romkatv/powerlevel10k#1575]
Hello.

The Terminal program on OS X has a mark feature, and can automatically put marks at each prompt.

When using Transient Prompt, somehow these marks get erased.

Is this intentional behavior or a side-effect?

Thanks!

**Comment by romkatv** [comment]
This is not intentional. Last time I checked it, it looked like a bug in the terminal. Maybe there is a workaround but I could not find it. FWIW, the marks work correctly in iTerm.
