### ISSUE TITLE
Terminal becomes disordered when resize it in GNOME Terminal 3.38.1

### ISSUE THREAD

**Issue by AnthonyFararoni** [romkatv/powerlevel10k#1576]
Hi, thanks for this project! This is the result when I resize the default terminal in Gnome 3.38.5:

![Screenshot from 2021-09-16 12-37-29](https://user-images.githubusercontent.com/82466844/133660398-ec9ec117-00c1-4340-942d-8db621807579.png)

Processor: AMD® Ryzen 3 3250u with radeon graphics × 4 
Graphics: AMD® Radeon vega 3 graphics
OS: Pop!_OS 21.04
Windowing System: X11
Kernel: 5.13.0-7614-generic

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
