### ISSUE TITLE
How to apply those colorful prompt themes to the SSH connected remote server?

### ISSUE THREAD

**Issue by yan-hao-tian** [romkatv/powerlevel10k#1579]
I install zsh, oh my zsh, poerlevel10k and the nerd font on my remote server. My remote server is a centOS one. I can use the powerlevel now but i can not switch the themes because only the lean theme is available in the configuration.  Could anyone tell me how to set other themes correctly?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
