### ISSUE TITLE
Oh My Zsh instructions

### ISSUE THREAD

**Issue by MikeJohnPage** [romkatv/powerlevel10k#158]
Should the instructions for the Oh My Zsh installation not read:

Set `ZSH_THEME="powerlevel10k/powerlevel10k"` in . . .

Rather than:

Set `ZSH_THEME=powerlevel10k/powerlevel10k` in . . .

Notice the additional `" "`?

Thanks for powerlevel10k, it looks amazing!

**Comment by romkatv** [comment]
It's ZSH, so standard rules apply. If you like `ZSH_THEME="powerlevel10k/powerlevel10k"` better, use that. If you rather prefer single quotes, `ZSH_THEME='powerlevel10k/powerlevel10k'` is fine too. Really like double quotes? Then use `ZSH_THEME="""powerlevel10k/powerlevel10k"""`.

**Comment by MikeJohnPage** [comment]
Understood, thanks. I should have read the docs before filing an issue, apologies! Thanks again for the great theme.
