### ISSUE TITLE
git icon is displayed instead of github

### ISSUE THREAD

**Issue by iamart** [romkatv/powerlevel10k#1584]
After latest oh my Zsh update github icon is not being displayed. Not quite sure where the problem arises, so just leaving it here.
<img width="417" alt="Screen Shot 2021-09-23 at 11 53 57 AM" src="https://user-images.githubusercontent.com/1152959/134558876-30893a29-4554-4488-8d85-a5c734bbcb3e.png">

**Comment by romkatv** [comment]
What do you get if you run `git pull` in that repository?

**Comment by iamart** [comment]
I was checked out on a commit after which I've done a rebase, so that commit was no longer in a branch. thanks for the help!
