### ISSUE TITLE
Unable to unset VCS_GIT_*_ICONS

### ISSUE THREAD

**Issue by trallnag** [romkatv/powerlevel10k#1585]
Hello, I have configured p10k with rainbow and many icons. Now I am trying to remove a few icons while keeping most of them.

I already succeeded removing the directory icons.

![image](https://user-images.githubusercontent.com/24834206/134647082-41a26269-993b-4947-8472-7118155b3d18.png)

But I'm failing to remove the GitHub icon. Executing the following does not work:

```zsh
typeset -g VCS_GIT_ICON=
typeset -g VCS_GIT_GITHUB_ICON=
typeset -g VCS_GIT_BITBUCKET_ICON=
typeset -g VCS_GIT_GITLAB_ICON=
```

**Comment by romkatv** [comment]
You can run `p10k configure` and select Few Icons.

**Comment by trallnag** [comment]
But selecting "Few icons" removes both the GitHub icon and the branch icon. But okay I guess icons that are defined in [icons.zsh](https://github.com/romkatv/powerlevel10k/blob/master/internal/icons.zsh) cannot be overridden

**Comment by romkatv** [comment]
> But selecting "Few icons" removes both the GitHub icon and the branch icon.

Do you want to have the branch icon? After choosing Few Icons you can open `~/.p10k.zsh`, search for "POWERLEVEL9K_VCS_BRANCH_ICON" and read the comment above it. Here it is:

```zsh
# Branch icon. Set this parameter to '\uF126 ' for the popular Powerline branch icon.
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
```

If you head the tip and set `POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '` (note the trailing space), you'll have the branch icon in prompt.

**Comment by trallnag** [comment]
Yes, but that also removes all other icons. When I activate "Few icons", other icons disappear. For example the command execution icon

**Comment by romkatv** [comment]
You can generate two configs—one with many icons and another with few—and look at the diff. Pick the changes you like.

**Comment by trallnag** [comment]
Okay I got it to work!

![image](https://user-images.githubusercontent.com/24834206/134654323-4e6bdf7f-63cf-43dc-af20-f3b21e82822b.png)

I had to edit the expansion variable even though I don't understand exactly what this variable is doing.

**Comment by trallnag** [comment]
But I wonder why I can unset certain icons like `POWERLEVEL9K_HOME_ICON` directly, but for other icons I have to use the expansion variable

**Comment by romkatv** [comment]
> But I wonder why I can unset certain icons like `POWERLEVEL9K_HOME_ICON` directly, but for other icons I have to use the expansion variable

Both of these work. You just need to ensure you are spelling the variable names correctly.

**Comment by trallnag** [comment]
@romkatv, ah indeed. I forgot to add the prefix. So this works as well:

```zsh
typeset -g POWERLEVEL9K_VCS_GIT_ICON=
typeset -g POWERLEVEL9K_VCS_GIT_GITHUB_ICON=
typeset -g POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=
typeset -g POWERLEVEL9K_VCS_GIT_GITLAB_ICON=
```
