### ISSUE TITLE
kubectx is showing the cluster name rather than the context name for EKS clusters

### ISSUE THREAD

**Issue by nea1** [romkatv/powerlevel10k#1586]
### Observed Behaviour
Steps to recreate:
1. Create EKS cluster e.g. cluster name "foo"
2. Login to cluster:
```
aws eks update-kubeconfig \
--profile my-prod-acct \
--region us-west-2 \
--name foo \
--alias my-prod-acct-us-west-2-foo
```
3. p10k's kubectx displays "foo" (the cluster name in eks), rather than "my-prod-acct-us-west-2-foo" (the k8s context name)

When managing a number of EKS clusters across accounts this is undesirable. For example you may have a cluster called "foo" in my-prod-acct/us-west-2, my-prod-acct/us-east-1, my-test-acct/us-west-2 etc. - all would appear with the same value "foo" in the terminal.  

### Desired Behaviour
p10k should display the name of the cluster's *context* as per ~/.kube/config i.e. the value seen when you use the `kubectx` command directly. This will always be unique and is user defined.

Note: SAML federation is being used with AWS if that has any bearing on this

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION`, read comments above it and adjust the value as you like.

**Comment by nea1** [comment]
Excellent, all working now - thanks. Not sure how I missed that 😄
