### ISSUE TITLE
[Feature Request] Ability for custom icon color to be set automatically like the the fill colors

### ISSUE THREAD

**Issue by BaronKrause** [romkatv/powerlevel10k#1587]
Is it possible to let custom icons color be set automatically like the rest of the theme colors? Like some color code that says use the systems terminal fill color?

right now to achieve something like this:
https://pop-planet.info/forums/attachments/screenshot-from-2021-07-04-14-45-04-png.1066/
you need to manually set the icon color to the same as your terminals current color. And if its on a machine that you ssh into it will always be off if the connecting machines have different themes.

Not a huge deal at all but was wondering if instead of something like this:
```
  # Custom icon.
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'%F{#48B9C7}\uf31D'
```

to set the color, if there could be a color code to automatically use the terminal like in the picture.

Thanks!

**Comment by romkatv** [comment]
I don't understand what you screenshot demonstrates.

What do you mean by "systems terminal fill color"? On your screenshot, is it grey, white or teal? Which part of your prompt you want to have that color?

**Comment by BaronKrause** [comment]
Sorry for explaining it s poorly, using the picture as reference The Gray and teal background colors are set automatically by the terminals theme, whereas the OS glyph is by default black, and can be set manually to a specific color like here (where I set it to the same color that the terminal uses fr the second part of the background fill).

I was wondering f there was a way, or if it could be added to be able to set that OS icon to always use the same terminal color that the second portion of the background fill uses, so it can automatically change like those other portions of the interface.

**Comment by romkatv** [comment]
Do you want `os_icon` to have the same foreground color as the background of `dir`? If so, you can see that the background of `dir` is 4 (usually it looks like some shade of blue):

```zsh
typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
```

So you can try this:

```zsh
POWERLEVEL9K_OS_ICON_FOREGROUND=4
```

You'll need to remove `%F` from `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` for this to have effect. 

```zsh
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF31D'
```

Does this do what you want?

**Comment by BaronKrause** [comment]
That did Exactly what I wanted, thank you!

**Comment by romkatv** [comment]
Great! Closing.
