### ISSUE TITLE
Feature Request: Time with timezone different from PC's timezone

### ISSUE THREAD

**Issue by aryanc403** [romkatv/powerlevel10k#1588]
Right now one can enable Right_Prompt_Element `time` to print the current time.

These days due to WFH people often work with multiple timezones. An option to add time in some other timezone from PC's timezone would be nice. This way one can also add time in multiple timezones as well.

Also, some pointers on how to do it would be really nice. I would pick it up as https://hacktoberfest.digitalocean.com/ PR if the PR owner agrees to merge it otherwise I would try to implement it for my own fork so that I can use it.

**Comment by JonathanDCohen** [comment]
How does this work? couldn't find docs on it

**Comment by Syphdias** [comment]
Afaict this was not implemented since the PR was closed 4 years ago. Your best bet is to write your own segment and use `TZ='America/Los_Angeles' date +%H:%M:%S` with:
https://github.com/romkatv/powerlevel10k/blob/8ed1f58e082e1cce85e1d69235d1a906cf3c643e/config/p10k-lean.zsh#L1645-L1652
