### ISSUE TITLE
Feature request: allow execution outside of prompt

### ISSUE THREAD

**Issue by hoshsadiq** [romkatv/powerlevel10k#159]
My use case being that I would like to add specific segments to tmux status line for example. For example, I've manually coded up what's in the screenshot. One thing I've had to do is manually comment out the `[[ -o 'interactive' ]] || 'return'` in gitstatusd. Additionally, much prefer the p9k/p10k logic that goes into showing the current dir and there are other segments I'd like to show in tmux that come with p9k/p10k.

Idea being that I can keep the prompt much emptier.

It would be nice to have this working for tmux's `pane-border-format`, `status-left`, `status-right`, `window-status-format` and `window-status-current-format`

![image](https://user-images.githubusercontent.com/600045/62705936-60410000-b9e6-11e9-9f4c-e98d1f79a651.png)

**Comment by romkatv** [comment]
What exactly are you asking for? To remove `[[ -o 'interactive' ]]` from gitstatus? If that's the issue, can you pass `-i` when calling zsh? Or `setopt interactive`?

If you are asking for something else, please explain.

**Comment by hoshsadiq** [comment]
Sorry, so I'd like to be able to run powerlevel10k within tmux to add specific segments to the status bar and pane-border-format. Something along the lines of:

```
# tmux.conf

set -g pane-border-format '#(p10k segment dir) - #(p10k segment vcs)'
# or perhaps
set -g pane-border-format '#(POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs) p10k tmux)'
```

**Comment by romkatv** [comment]
I don't know anything about tmux status bar or pane-border-format. If I understand your request correctly, you want to display something similar to p10k prompt somewhere that isn't a ZSH prompt. Is that correct? If yes, there is no easy way to do this. p10k does many things that are specific to ZSH prompt. E.g., directory shortening is of this kind. Some logic could be factored out but it would complicate code. I'd rather not do it unless there is significant demand (at least 100k potential users).

If I misunderstood your request and you believe there is a way to provide what you need without large and complex changes in p10k code, please let me know. Otherwise I'm inclined to close this feature request as out of scope.

**Comment by hoshsadiq** [comment]
Totally understand. I think the only thing that is necessary to make changes through non-tty and in a new subshell, as that is essentially what tmux does (so shebang sets the interpreter). So it's just a matter of adjusting it so p10k can be directly invoked from another script.  That way, someone like me for example could simply write a wrapper script, set the p10k configuration env vars, and simply runs p10k command (or something).

**Comment by romkatv** [comment]
> Totally understand. I think the only thing that is necessary to make changes through non-tty and in a new subshell, as that is essentially what tmux does (so shebang sets the interpreter). So it's just a matter of adjusting it so p10k can be directly invoked from another script. That way, someone like me for example could simply write a wrapper script, set the p10k configuration env vars, and simply runs p10k command (or something).

How about this. I close this feature request as I'm not going to work on it. If you know what needs to be done and believe it's not difficult, send a PR. Sounds fair?

**Comment by hoshsadiq** [comment]
No problem. Thanks anyway

**Comment by ytian81** [comment]
> What exactly are you asking for? To remove `[[ -o 'interactive' ]]` from gitstatus? If that's the issue, can you pass `-i` when calling zsh? Or `setopt interactive`?
> 
> If you are asking for something else, please explain.

I am trying to use `setopt interactive` in a zsh script but it doesn't seem to work.
```
 can't change option: interactive
```

**Comment by romkatv** [comment]
> I am trying to use `setopt interactive` in a zsh script but it doesn't seem to work.
> 
> ```
>  can't change option: interactive
> ```

Yep, apparently it doesn't work.

**Comment by ytian81** [comment]
So is there anyway to use gitstatus.plugin.zsh in a non-interactive shell?

**Comment by hoshsadiq** [comment]
I think @romkatv original suggestion was to run `zsh -i` rather than using `setopt interactive`

**Comment by romkatv** [comment]
> So is there anyway to use gitstatus.plugin.zsh in a non-interactive shell?

No. I'm pretty sure it cannot be done. It also makes no sense to even attempt this.

**Comment by romkatv** [comment]
@ytang What are you trying to do?

**Comment by ytian81** [comment]
I would like to have a git prompt in tmux status line. There are some plugins for this purpose but they are purely using `git status` which is slow and blocking normal git command (by creating an index.lock in .git directory). Since I already use p10k and take advantage of gitstatusd, I am thinking of if I can directly use gitstatusd in tmux status line. After some quick prototype, I am able to achieve my goal but I have to comment out  `[[ -o 'interactive' ]]` from the gitstatus.plugin.zsh because the shell launched by tmux is non-interactive.

**Comment by romkatv** [comment]
`gitstatus.plugin.zsh` uses zle. The check for `interactive` can be replaced with a check for `zle`. Does it work for you if you make this change?

**Comment by romkatv** [comment]
I'm confused. You mentioned earlier that you've written something that can use `gitstatus.plugin.zsh` as long as the check for `interactive` is removed from it. `gitstatus.plugin.zsh` cannot work without zle.

**Comment by ytian81** [comment]
```
#!/usr/bin/env zsh

set -euo pipefail

# set -x
# echo "start at: $(date)" >&2
# exec 2> /tmp/tmux-git-status.log

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]:-$0}" )" && pwd )"

typeset -A settings
settings[icon]=''
settings[prefix]=' '
settings[suffix]=' '
# settings[statusd-directory]='~/.gitstatusd'
settings[statusd-directory]="$HOME/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus"

settings[icon-staged]='+'
settings[icon-unstaged]='!'
settings[icon-untracked]='?'
settings[icon-stashes]='*'
settings[icon-ahead]='↑'
settings[icon-behind]='↓'

settings[staged-count]='true'
settings[unstaged-count]='true'
settings[untracked-count]='true'
settings[stashes-count]='true'
settings[ahead-count]='true'
settings[behind-count]='true'

cat "${settings[statusd-directory]}/gitstatus.plugin.zsh" | grep -v "interactive" > "${settings[statusd-directory]}/gitstatus.non_interactive.plugin.zsh"

function get_git_status {
  local dir
  local tmux_git_status

  dir="$(tmux display -p "#{pane_current_path}")"

  # Have to comment out early return of non interactive shell
  source "${settings[statusd-directory]}/gitstatus.non_interactive.plugin.zsh"
  # source "${settings[statusd-directory]}/gitstatus.plugin.zsh"

  gitstatus_stop tmux && gitstatus_start -s -1 -u -1 -c -1 -d -1 tmux
  if gitstatus_query -d "$dir" tmux && [[ $VCS_STATUS_RESULT == ok-sync ]]; then
    tmux_git_status="${settings[prefix]}"

    if [[ -n "${settings[icon]}" ]]; then
      tmux_git_status+="${settings[icon]} "
    fi
    tmux_git_status+="${${VCS_STATUS_LOCAL_BRANCH:-@${VCS_STATUS_COMMIT}}//\%/%%}"

    if [[ $VCS_STATUS_COMMITS_AHEAD != "0" ]]; then
       tmux_git_status+=" ${settings[icon-ahead]}"
       [[ "${settings[ahead-count]}" == 'true' ]] && tmux_git_status+="$VCS_STATUS_COMMITS_AHEAD"
    fi

    if [[ $VCS_STATUS_COMMITS_BEHIND != "0" ]]; then
       tmux_git_status+=" ${settings[icon-behind]}"
       [[ "${settings[behind-count]}" == 'true' ]] && tmux_git_status+="$VCS_STATUS_COMMITS_BEHIND"
    fi

    if [[ $VCS_STATUS_HAS_STAGED == 1 ]]; then
       tmux_git_status+=" ${settings[icon-staged]}"
       [[ "${settings[staged-count]}" == 'true' ]] && tmux_git_status+="$VCS_STATUS_NUM_STAGED"
    fi

    if [[ $VCS_STATUS_HAS_UNSTAGED == 1 ]]; then
      tmux_git_status+=" ${settings[icon-unstaged]}"
      [[ "${settings[unstaged-count]}" == 'true' ]] && tmux_git_status+="$VCS_STATUS_NUM_UNSTAGED"
    fi

    if [[ $VCS_STATUS_HAS_UNTRACKED == 1 ]]; then
      tmux_git_status+=" ${settings[icon-untracked]}"
      [[ "${settings[untracked-count]}" == 'true' ]] && tmux_git_status+="$VCS_STATUS_NUM_UNTRACKED"
    fi

    if [[ $VCS_STATUS_STASHES != "0" ]]; then
      tmux_git_status+=" ${settings[icon-stashes]}"
      [[ "${settings[stashes-count]}" == 'true' ]] && tmux_git_status+="$VCS_STATUS_STASHES"
    fi
    tmux_git_status+="${settings[suffix]}"

    printf "%s" "${tmux_git_status}"
  fi
}

main() {
	get_git_status
}

main

```

**Comment by ytian81** [comment]
This is a script I copied from @hoshsadiq. You could save it as `git-status.sh`. Also need to change `settings[statusd-directory]="$HOME/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus"` to your gitstatus directory. and then run this script with zsh. It would return the prompt if the current dir is a git repo.

**Comment by ytang** [comment]
> @ytang What are you trying to do?

Wrong chat?

**Comment by romkatv** [comment]
> > @ytang What are you trying to do?
> 
> Wrong chat?

No.

> This is a script I copied from @hoshsadiq.

Thanks for providing the context.

The way this script uses `gitstatus.plugin.zsh` is counterproductive. `gitstatus.plugin.zsh` is fairly complex because it manages a daemon and provides async access to it. However, the script you've posted launches the daemon, makes a single request, waits for the result and shuts the daemon down. If this is what you want, just use `gitstatusd` directly. It'll be less than 10 lines of code. See `gitstatusd --help` for an example. It'll also be faster (but still about 10x slower than whan you get in zsh when using powerlevel10k).

**Comment by ytian81** [comment]
Thanks for your explanation!

**Comment by ytang** [comment]
> > > @ytang What are you trying to do?
> > 
> > 
> > Wrong chat?
> 
> No.
Sorry, but I'm not following you. What do you mean by asking me what I'm trying to do?

**Comment by romkatv** [comment]
@ytang Oh dear, I've tagged the wrong person. I typed `@tang` and chose the first auto-completion suggestion. In the past GitHub would always offer participants from the current thread first (that would be `@ytian81` here) but this time it didn't. Sorry!

**Comment by ytang** [comment]
> @ytang Oh dear, I've tagged the wrong person. I typed `@tang` and chose the first auto-completion suggestion. In the past GitHub would always offer participants from the current thread first (that would be `@ytian81` here) but this time it didn't. Sorry!

Oh I see...Don't worry about it! 😀

**Comment by ytian81** [comment]
> gitstatus.plugin.zsh is fairly complex because it manages a daemon and provides async access to it. However, the script you've posted launches the daemon, makes a single request, waits for the response, and shuts the daemon down.

I am wondering why my script shared above works because it is run under a non-interactive shell but `gitstatus.plugin.zsh` requires `zle` which is only available in interactive shell.

**Comment by romkatv** [comment]
@ytian81 Your script queries gitstatus in sync mode, which doesn't require zle. Sync mode is implemented to make examples simpler but other than that it's not a useful feature. I should repeat that starting gitstatusd in background, querying it synchronously and then shutting it down is counterproductive. If you want to issue a single query, just use gitstatusd. It'll be faster and will require a small fraction of code. (It'll still be very slow though, on part with invoking `git`.)
