### ISSUE TITLE
OSC 133 support

### ISSUE THREAD

**Issue by jack1142** [romkatv/powerlevel10k#1591]
It would be great if powerlevel10k sent OSC 133 escape codes out of the box without the need to do any custom configuration.
See:
https://github.com/kovidgoyal/kitty/blob/master/docs/shell-integration.rst#notes-for-shell-developers
https://iterm2.com/documentation-escape-codes.html#:~:text=FTCS_PROMPT-,OSC%20133%20%3B,-A%20ST

**Comment by romkatv** [comment]
I think this should work if you set `ITERM_SHELL_INTEGRATION_INSTALLED=Yes` in your zshrc. Could you try it?

**Comment by jack1142** [comment]
It appears to be working correctly on kitty, awesome!
This doesn't seem to be documented anywhere and the generated `.p10k.zsh` file also doesn't include it so I thought there simply isn't support for it in powerlevel10k.

A small side note, I got a bit confused by this option requiring `Yes` rather than `true`. Not a problem at all, just different from the other options 😄 

Anyways, thanks for the quick help! I'll leave this open in case you want to document this feature.

**Comment by romkatv** [comment]
`ITERM_SHELL_INTEGRATION_INSTALLED=Yes` isn't a Powerlevel10k option per se. This parameter is set when users source the iTerm2 shell integration script. Powerlevel10k detects this, undoes what the iTerm2 script did, and then properly enables shell integration.

Kitty has recently implemented the same protocol. I probably should do something specific in Powerlevel10k to support this. FWIW, in zsh4humans this is handled properly.

**Comment by jack1142** [comment]
> This parameter is set when users source the iTerm2 shell integration script.

Ah, that makes sense! kitty doesn't seem to be setting any environment variable in its shell integration but if it would help, I'm guessing the author would be open to it.

**Comment by kovidgoyal** [comment]
kitty sets the KITTY_SHELL_INTEGRATION env var, however this is unset by the shell integration scripts themselves so as to not pollute the users environment. So if you want to detect/intercept it, the place to do so is before the shell integration scripts are sourced.

**Comment by romkatv** [comment]
> I probably should do something specific in Powerlevel10k to support this.

Done. I've added a dedicated parameter to powerlevel10k that you can use to enable OSC 133 marks:

```zsh
typeset -g POWERLEVEL9K_TERM_SHELL_INTEGRATION=true
```

If you are using powerlevel10k via zsh4humans, you can enable shell integration like this:

```zsh
zstyle ':z4h:' term-shell-integration 'yes'
```

Shell integration in zsh4humans is more complete.
