### ISSUE TITLE
Rainbow prompt - context background is slighly thinner than other backgrounds

### ISSUE THREAD

**Issue by keremenci** [romkatv/powerlevel10k#1592]
After moving the context to left of the prompt, There is an apparent misalignment.

![image](https://user-images.githubusercontent.com/57116822/135864279-2a67a78c-3d05-4d67-aa4d-0cef2e0ed134.png)

**Comment by romkatv** [comment]
Where is the misalignment?

**Comment by keremenci** [comment]
Here. About 1 pixel
![image](https://user-images.githubusercontent.com/57116822/135869000-f55b1f28-a3d9-47c0-8cd5-ceaff559795f.png)

**Comment by romkatv** [comment]
I don't see it with 500% zoom on a 43 inch display.

Anyway, it's not something that powerlevel10k has control over. Powerlevel10k asks the terminal to display certain characters with certain foreground and background colors. The terminal is responsible for rendering them. If you believe that your terminal is rendering something incorrectly, open a bug against the terminal. You can print the same thing without powerlevel10k. Like this:

```zsh
zsh -fc 'print -P "%K{4}%F{3} \uE0BA%K{3} "'
```

I don't know which colors you are using for the directory and context on the screenshot, so I've used `4` and `3` respectively. You can adjust these to match your prompt exactly.
