### ISSUE TITLE
right prompt disappears with long folderpath 

### ISSUE THREAD

**Issue by ixzh** [romkatv/powerlevel10k#1593]
this is normal prompt showing im at level 1 of nnn invocation:
![normal prompt](https://user-images.githubusercontent.com/14981695/135907274-9eb6e361-f2a9-4e42-a265-e6396b65590c.png)

the right prompt disappears and the nnn level info is missing: 
![right prompt info missing](https://user-images.githubusercontent.com/14981695/135907596-da416345-8ef5-490c-829f-5d644750ba72.png)

if disappearance is inevitable can i have the nnn info on the leftmost of the prompt?🙏

**Comment by romkatv** [comment]
Right prompt disappears when it would have overlapped left prompt. This is how zsh works. You can see this by doing the following:

1. Run this: `PS1='%/ ' RPS1='%*' zsh -f`
2. `cd` into a directory with a very long path.
3. Note how right prompt disappears.

> can i have the nnn info on the leftmost of the prompt?

Of course. Open `~/.p10k.zsh` and move `nnn` from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`. Read the comments around that place to understand what's going on.

**Comment by romkatv** [comment]
By the way, you might want to also do the following:

1. Open `~/.p10k.zsh`.
2. Search "POWERLEVEL9K_SHORTEN_DIR_LENGTH".
3. Set the value of this parameter to `0`.
4. Restart zsh with `exec zsh`.

This will tell Powerlevel10k that it's OK to shorten the last segment of the current directory if it doesn't fit. On your screenshot your can see in bold blue directory segments that powerlevel10k is not allowed to shorten.

**Comment by ixzh** [comment]
Thank you very much!!

>     2\. Search "POWERLEVEL9K_SHORTEN_DIR_LENGTH".

Thank you for the detailed explanation!! works perfectly.

BTW, I can't not find this variable, the only length related is this row:
`typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80`

so I just create it below the above line:
`typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=0`

**Comment by ixzh** [comment]
on a second thought, I will have to bear with the disappearance of right prompt, as I find the full name of current folder is useful, whereas even if I allow shortening of the last segment, the right part will still disappear as I often deal with deep folders (so the shortening is outmatched by folder levels). :) So to have all the info and long name at the same time, it is best to put all modules on the left prompt? ✋🏻

**Comment by romkatv** [comment]
> So to have all the info and long name at the same time, it is best to put all modules on the left prompt?

Left prompt never disappears. Right prompt does. So if you want something in prompt to never disappear, it has to be on the left.

Given that your screen is so narrow, it might be a good idea to remove decorations from it. You can do that by running `p10k configure` and selecting "No Frame" and "Few Icons". You also probably don't need the current time in prompt.
