### ISSUE TITLE
venv name with dot on NTFS partition

### ISSUE THREAD

**Issue by brccabral** [romkatv/powerlevel10k#1594]
My /media/brccabral/Data drive is a NTFS partition (I use dual boot Ubuntu/Windows).
On Ubuntu drive, specifically my home dir ~, everything works fine

```
cd ~
mkdir -p MyPythonProjects/AwesomeProject
python3 -m venv venv1
source venv1/bin/activate # p10k shows venv1 OK
deactivate
python3 -m venv venv1.2
source venv1.2/bin/activate # p10k shows venv1.2 OK
deactivate
```

But then, if I switch to my NTFS drive, venv names are shown, except if I use a dot in its name

```
cd /media/brccabral/Data/PythonProjects/ImageAndVideo
python3 -m venv venv1.2
source venv1.2/bin/activate # p10k shows blank!
deactivate
python3 -m venv venv12
source venv12/bin/activate # p10k shows venv12 correctly, but it doesn't have the dot
deactivate
```

Is there anything you can do to support dot on NTFS?

**Comment by romkatv** [comment]
> `source venv1.2/bin/activate # p10k shows blank!`

What is the output of `typeset -p VIRTUAL_ENV` here?

> `source venv12/bin/activate # p10k shows venv12 correctly, but it doesn't have the dot`

Also here.

**Comment by morallys** [comment]
Hello,
Based on the problem that colleague brcabral raised above, that the terminal must have a minimum width, how to move the 'venv' denomination or the path to the second line?

Trying to make several different configurations, I saw that p10k already supports this, not in rainbow or classic, but in the 'pure' configuration this venv denomination is already moved to the second line.

How to make this configuration?

**Comment by romkatv** [comment]
Open `~/.10k.zsh` and edit it. Search for `newline`.

**Comment by morallys** [comment]
Hello,
thanks for the quick response, but in case I would add the constant like newline?

`typeset -g POWERLEVEL9K_VIRTUALENV_MULTILINE_NEWLINE_PROMPT_PREFIX=true`

Thus? I would like to just add the id of 'venv' to the second line as I show in the following print

![image](https://user-images.githubusercontent.com/44041037/183157367-88b07d4d-b7ff-4df1-92a8-490ba0411851.png)

**Comment by romkatv** [comment]
Have you tried opening `~/.p10k.zsh` and searching for `newline` in it?

**Comment by romkatv** [comment]
This is the block that you need to edit: https://github.com/romkatv/powerlevel10k/blob/f9fd384d8d64022e24c83bb03ba69e415c7fa90e/config/p10k-classic.zsh#L25-L107

**Comment by brccabral** [comment]
Hi @morallys 
On my ~/.p10k.zsh I added a new line and put all venv/version/apps in it. Check image:
![image](https://user-images.githubusercontent.com/130455/183327474-f76be43f-ec21-4473-90e2-12b7373e9aef.png)

**Comment by morallys** [comment]
Hello, I got what I wanted. I added in LEFT_PROMPT_ELEMENTS on the second line the virtualenv I needed. It was what I really wanted.

![image](https://user-images.githubusercontent.com/44041037/183719326-340bcb0d-5d19-4b49-a771-1217be34a7ba.png)
![image](https://user-images.githubusercontent.com/44041037/183719640-3165218b-cf87-49fe-b01a-f4209c2a25a5.png)
