### ISSUE TITLE
Rainbow style is not listed while configuring powerlevel10k theme

### ISSUE THREAD

**Issue by karthick87** [romkatv/powerlevel10k#1595]
I am trying to configure powerlevel10k theme and I see Rainbow style is not getting listed. Here is how my current terminal looks like. Any inputs would be very helpful.

![image](https://user-images.githubusercontent.com/12709834/136380576-cdb98692-a127-4231-a2cd-c4839edcbace.png)

**Comment by romkatv** [comment]
see https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by romkatv** [comment]
you've chosen prompt without the arrow mark. you can run `p10k configure` again and choose differently.

**Comment by 5inf** [comment]
Another reason for the rainbow styles not being available is the terminal not supporting colours.
E.g. Putty in its default configuration registers $TERM as "xterm" causing the exact behaviour that @romkatv mentioned here.
Changing the terminal configuration to e.g. xterm-256color enables the rainbow styles in the wizard.
Maybe a hint in the configuration wizard could point out the missing terminal capabilities.

**Comment by romkatv** [comment]
> Another reason for the rainbow styles not being available is the terminal not supporting colours.

From the docs:

> If the terminal can display fewer than 256 colors, configuration wizard preselects Lean style with 8 colors. All other styles require at least 256 colors. *Fix*: Use a terminal with 256 color support and make sure that `TERM` environment variable is set correctly. Verify with `print $terminfo[colors]`.

> Maybe a hint in the configuration wizard could point out the missing terminal capabilities.

Maybe.
