### ISSUE TITLE
WiFi, IP and Battery data not displayed

### ISSUE THREAD

**Issue by im-coder-lg** [romkatv/powerlevel10k#1596]
Hi,

First off, thanks for this. I could now find a valid replacement to my (rather stupidly looking) Git Bash(I hacked it and installed Zsh) and got this theme when I first started it. I set up MesloLGS NF on my Hyper Terminal and tried using Vim to add some more data for my ease, and added WiFi, IP and Battery lines in the specific section but it doesn't work. Can you tell me what is the problem since I am hopelessly addicted to an Oh My ZSH theme with this level of configuration, can you help me here?

PS: Video clip coming soon on how this doesn't work as expected.

**Comment by im-coder-lg** [comment]
https://user-images.githubusercontent.com/76845820/136645368-3e504c14-56e0-490c-a7d1-6aba3d49ba95.mp4

Video clip above

**Comment by romkatv** [comment]
`wifi` works on macOS and on Linux if you have `iw` installed. It may not work on WSL, I haven't tried it.

`battery` may not work on WSL. I haven't tried it.

`ip` should work. Make sure you've set `POWERLEVEL9K_IP_INTERFACE` to the right value.

**Comment by romkatv** [comment]
> @romkatv this isn't WSL or MSYS2, this is Git Bash.

Git Bash is based on MSYS2. Lots of Linux things don't work on MSYS2.
