### ISSUE TITLE
Shell exits on successful script source when using zsh + powerlevel10k

### ISSUE THREAD

**Issue by JBKahn** [romkatv/powerlevel10k#1599]
I have no configuration for powerlevel10k but when sourcing a script it always exits the shell even though the script itself is successful. Have you encountered this before? The problem goes away when I comment out `source ~/powerlevel10k/powerlevel10k.zsh-theme` on current master.

`zsh --version`: `zsh 5.8 (x86_64-apple-darwin19.6.0)`. Happy to provide any more information. I removed everything from my `zshrc` except `source ~/powerlevel10k/powerlevel10k.zsh-theme` and it causes the behaviour so all I know is that it is related.

**Comment by romkatv** [comment]
powerlevel10k ran commands to show you prompt. There is no point in trying to make powerlevel10k work with `-e` in effect because it's not an environment anyone uses intentionally. Any sneeze will bring the shell down.

**Comment by romkatv** [comment]
It's neither expected nor unexpected. You just did something no one does (I suppose by mistake). You need to execute that script instead of sourcing it.
