### ISSUE TITLE
Customize POWERLEVEL9K_VCS_GIT_HOOKS with gitstatus

### ISSUE THREAD

**Issue by sozercan** [romkatv/powerlevel10k#16]
With `gitstatus` enabled, I can't customize `POWERLEVEL9K_VCS_GIT_HOOKS`. If I turn off `gitstatus` then it works fine. Is there a way to customize the features (stashes, branch, etc)?

**Comment by romkatv** [comment]
> Is there a way to customize the features (stashes, branch, etc)?

Not at the moment but it can be implemented. What's your `POWERLEVEL9K_VCS_GIT_HOOKS`? Perhaps I can quickly add support for your use-case without having to implement full backward compatibility with all hook permutations.

**Comment by romkatv** [comment]
This is done. Please verify that it works as you expect. You should get the same prompt in Powerlevel10k as in Powerlevel9k with the same hooks.

**Comment by sozercan** [comment]
Thanks so much for the fast response and fix! Just tested and custom hooks are working great now, closing the issue.
