### ISSUE TITLE
Skip p10k Configure on First Run

### ISSUE THREAD

**Issue by corycollier** [romkatv/powerlevel10k#160]
I'm using this theme in docker containers for cli connection to apps in development environments. I'm copying over a standard .p10k.zsh file, and I'd like to avoid the p10k configure step everytime someone connects to the running container. Is there a way to avoid this step?

**Comment by corycollier** [comment]
Dammit. Figured it out. My apologies

**Comment by romkatv** [comment]
That was fast :grin:
