### ISSUE TITLE
Configuration wizard differs significantly from what is shown in the README

### ISSUE THREAD

**Issue by patrykdabrowskii** [romkatv/powerlevel10k#1602]
After typing **p10k configure**  it I get prompted for:

Character set (unicode or ascii)
Show current time (no, 24-hour or 12-hour)
Prompt height (one or two lines)
Prompt connection (disconnected, dotted or solid)
Prompt frame (no frame, left, right or full)
Connection frame and color (black, white, green or blue)
Prompt spacing (compact or sparse)
Icons (few or many)
Prompt flow (concise or fluent)
Enable transient prompt (yes or no)
Instant prompt mode (verbose, quiet or off)
Overwrite (yes, restart or quit)

I don't see any options for Lean / Classic / Rainbow / Pure instead, I get asked to see if I see a Diamond , Lock, Debian, Logo etc.

My terminal supports 256 color.
Recommends fonts are also installed.
I am using iTerm2

**Comment by patrykdabrowskii** [comment]
> > The first one is
> > > 
> > 
> > 
> > ```
> >             Does this look like a diamond (rotated square)?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > >
> 
> Does it?

yes, for the next ones also

**Comment by romkatv** [comment]
What are the first 5 questions and what are your answers?

**Comment by romkatv** [comment]
What's the issue again?
