### ISSUE TITLE
[request] Transient prompt: same-branch, like same-dir for repos

### ISSUE THREAD

**Issue by bdcarr** [romkatv/powerlevel10k#1603]
I do a fair bit of swapping between branches in git repos and it would be really sweet if I could make the transient prompt react to branch changes in the same way as directory changes. Is that within scope for p10k?

**Comment by bdcarr** [comment]
Here it is: https://gist.github.com/bdcarr/753847cac5baeb3a9d8bf733f9c5ec7e

**Comment by franciscosili** [comment]
Hi! So I tried to use this as well. I tried changing what @romkatv posted but does not work: the transient prompt does not work when inside the same directory, and does not work when on the same branch. Perhaps something have changed in the meantime?

Here's my `.p10kzsh` file (without the mentioned changes shown above): https://github.com/franciscosili/configuration/blob/master/zsh/.p10k.zsh

I also tried combining with https://github.com/romkatv/powerlevel10k/issues/2116, but without succeed.
