### ISSUE TITLE
Non interactive or unattended powerlevel10k configuration

### ISSUE THREAD

**Issue by ravikiranj** [romkatv/powerlevel10k#1609]
Hi there,
    Is there a non-interactive or unattended way to configure powerlevel10k (p10k configure) when running within a script? If there is no automated way, would you recommend generating the configuration manually and copy the "$HOME/.p10k.zsh" within the automated script?

**Comment by romkatv** [comment]
> If there is no automated way, would you recommend generating the configuration manually and copy the "$HOME/.p10k.zsh" within the automated script?

This *is* the unattended way to create a configuration file. `p10k configure` is the interactive way to do the same.
