### ISSUE TITLE
Support for custom git and working directories

### ISSUE THREAD

**Issue by brickstool** [romkatv/powerlevel10k#161]
To manage my dotfiles on Linux, I am using the method detailed in [this link](https://www.atlassian.com/git/tutorials/dotfiles). Setting up a repository following this method means that the default `.git` folder is changed to something like `.cfg`. 

Can powerlevel10k be configured to display git status information within a directory with these differences? 

Thanks for the effort you have put in to creating powerlevel10k.

**Comment by romkatv** [comment]
How do you expect this to work from the user's point of view?

When using a bare Git repository to store dotfiles, the repository is overlayed on top of your home directory. Any directory under `$HOME` can have files tracked by the dotfiles repo.

For example, my [dotfiles-public](https://github.com/romkatv/dotfiles-public) repo has files in `$HOME`, `$HOME/bin`, `$HOME/.local/share/fonts`, etc. My `dotfiles-private` repository also has files under `$HOME` and `$HOME/bin`.

When my current directory is `$HOME` or `$HOME/bin`, should prompt display Git status from `dotfiles-public` repo, from `dotfiles-private`, none, or both?

What if my current working directory is `$HOME/stuff`, which doesn't have any files tracked by `dotfiles-public` and `dotfiles-private` but could have them? In other words, this directory is under the work tree of both `dotfiles-public` and `dotfiles-private`.

What if I'm in `$HOME/powerlevel10k`? This is a regular Git repository (not bare) but it can also have files tracked by `dotfiles-public` and/or `dotfiles-private`. How should prompt look like?

**Comment by mathieucivel** [comment]
Can it be acceptable to just support this edge case in $HOME, as it is where most of the dotfile-git operations will take place ?

**Comment by romkatv** [comment]
> Can it be acceptable to just support this edge case in $HOME (or one configurable dir), as it is where most of the dotfile-git operations will take place ?

I wouldn't like hardcoding special behavior when the current directory is `$HOME` and it's unclear how it could be made configurable. Moreover, for me personally it wouldn't be convenient. When I work on my dotfiles I'm often in `~/bin` or `~/dotfiles` and not in `$HOME`.

> For multiple bare repos it make sense to also only support one for now, for simplicity.

Which one? How would you specify it?

I'm inclined to close this feature request as underspecified and/or infeasible. If you figure out what p10k should do, feel free to reopen. Sounds reasonable?

**Comment by mathieucivel** [comment]
Sure it would create a weird configuration couple and likely introduce issues

```
..._CUSTOM_GIT_WORKDIR_FOR_DIR = $HOME
..._CUSTOM_GIT_WORKDIR_TARGET = $HOME/.dotfiles
```

Seems wise to close this issue..

Its
