### ISSUE TITLE
Is it possible to show the FQDN and not the hostname?

### ISSUE THREAD

**Issue by EugenMayer** [romkatv/powerlevel10k#1620]
Is it possible to let powerlevel show the FQDN and not just the hostname? I guess/assume that one downside of this is, it needs to be resolved, right?

**Comment by romkatv** [comment]
Powerlevel10k cannot display FQDN out of the box but you can create a custom segment that does it if you know how to obtain FQDN. Search for "example" in `~/.p10k.zsh` to see how to define a custom segment.

**Comment by EugenMayer** [comment]
@romkatv thank you!. AFAIU this would allow me to add an additional segment, but not change the current one, right?

**Comment by romkatv** [comment]
Correct. Define a new segment and use it instead of the existing segment that doesn't do what you want.

**Comment by EugenMayer** [comment]
So the current segment i'am interested in is `context` on the right`. I see that `%m` is used for the hostname - bit I cannot see where `%m` is populated.

Defining a new segment seems at lest not trivial, since the current context segment does a lot already, I would have to replicate it.

But I understood you. It is not working out of the box, and if needed, replacing the `context` segment with and own implementation would be the way to go. Thank you for the help!

**Comment by romkatv** [comment]
`%m` is documented at https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html.

You can start with this:

```zsh
# TODO: set this to a real value by calling some command.
typeset -g my_fqdn='foo.bar.baz'

function my_context() {
  p10k segment -b yellow -f red "%u@${my_fqdn//\%/%%}"
}
```

**Comment by EugenMayer** [comment]
Thank you a lot @romkatv - sorry for the late reply!
