### ISSUE TITLE
Prompt is a bunch of `:` inside Intellij

### ISSUE THREAD

**Issue by rdohms** [romkatv/powerlevel10k#1621]
Not sure if this is a IntelliJ or a p10k issue or a combination of both, so starting here for ideas to move it to the right project.

I have my Intellij using the right font and confirmed that inside `p10k configure` where the symbols all relate correctly. However my prompt (even in the style choice part of configure) just looks like a lot of `:` characters with the occasional bit that makes sense.

Here are some screens:
![Screenshot 2021-11-01 at 14 44 37](https://user-images.githubusercontent.com/94331/139681866-7abe81ed-7f8e-4efc-bfd6-ba0f5972575e.png)
![Screenshot 2021-11-01 at 14 29 19](https://user-images.githubusercontent.com/94331/139681901-207549db-1c52-49bf-abbc-311f018865c5.png)

Any ideas?

**Comment by romkatv** [comment]
The terminal looks broken. Please file a bug against IntelliJ.

**Comment by rdohms** [comment]
Thanks, trying it: https://youtrack.jetbrains.com/issue/WI-63748
Any clue as to what could be broken? color coding?

**Comment by romkatv** [comment]
I don't know. It looks very broken.
