### ISSUE TITLE
Creating a tfenv module like pyenv to display in the prompt the current terraform version.

### ISSUE THREAD

**Issue by ginolegigot** [romkatv/powerlevel10k#1622]
Hello!
[Tfenv](https://github.com/tfutils/tfenv) est a tool like pyenv to ease the multiple terraform versions one could use for his projects.
The idea is creating a tfenv p10k module in a more optimized way.
Currently i created this module in .p10k.zsh:

```bash  
function prompt_tfenv_version() {
    if [[ -f .terraform-version ]] || [[ -f ../.terraform-version ]]; then
      terraform_version=`tfenv version-name 2>&1`
      if [[ "$terraform_version" =~ "No installed versions of terraform" ]]
      then
        p10k segment -f 205 -t "no tfenv"
      else
        p10k segment -f 205 -t "${terraform_version}"
      fi
    fi
  }
```
And i was wondering if it could be possible to write it in a more optimized way. It slows down quite a bit my prompt execution when i use this module.

**Comment by romkatv** [comment]
There is infinite number of those env projects and I cannot add support for all of them. Have you considered using asdf instead of tfenv?

**Comment by ginolegigot** [comment]
Thanks for asdf suggestion i did not know at all.
Regarding our first subject and for those who might be interested in having the terraform version in the prompt through tfenv, i wrote this in my .p10k.zsh:
```bash
  function prompt_tfenv_version() {
    if [[ -z $TFENV_VERSION ]]; then
      p10k segment -f 205 -t "no tfenv"
    else
      p10k segment -f 205 -t "${TFENV_VERSION}"
    fi
  }
```
And i set this in my .zshrc:
```bash
function tfu {
  tfenv use $1 && export TFENV_VERSION=$(tfenv version-name)
}
```
Creating an environment variable at each tfenv use, allows to gain a lot of performance for my prompt because this part of my former p10k module "tfenv version-name 2>&1" was very poor in terms of performance.

**Comment by romkatv** [comment]
Thanks for the update.

**Comment by TrueLecter** [comment]
As an addition, if you do not want to use alias for tfenv you can use wrapper:
```bash
function prompt_tfenv() {
  if [[ -z $TFENV_VERSION ]]; then
    TFENV_VERSION=$(tfenv version-name)
  fi

  p10k segment -f 038 -t "tf ${TFENV_VERSION}"
}

function tfenv() {
  command tfenv "$@"

  if [[ "$1" == "use" ]]; then
    TFENV_VERSION=$(tfenv version-name)
  fi
}
```

**Comment by ginolegigot** [comment]
Hello @TrueLecter ,
I tried to avoid using wrapper cuz it impacts a lot my prompt performances.
