### ISSUE TITLE
Visual Studio for Mac - Freaking out. Icons Missing etc.

### ISSUE THREAD

**Issue by iChaosren** [romkatv/powerlevel10k#1625]
![image](https://user-images.githubusercontent.com/783885/140302007-6aadf22a-fc76-41d9-8334-c7083aca97b1.png)

I was attempting to run the terminal on Visual Studio for Mac.
I found this [https://devblogs.microsoft.com/visualstudio/meet-visual-studio-for-macs-new-integrated-terminal/](https://devblogs.microsoft.com/visualstudio/meet-visual-studio-for-macs-new-integrated-terminal/)
Which is a good example of the terminal working in Visual Studio for Mac back in April 2020.

The cursor is also in completely the wrong location...
Icons are missing...
Whether I use the recommended font or the font specified in the screenshot from the above article, "Cascadia Code PL", it doesn't matter.

I can confirm it works perfectly in the terminal and in Visual Studio Code, just not in Visual Studio for Mac's integrated terminal...

**Comment by romkatv** [comment]
I suggest that you file a bug against Visual Studio for Mac.

**Comment by iChaosren** [comment]
For anyone else who want to know the status of the issue:

[My Bug Report](https://developercommunity.visualstudio.com/t/Terminal---Custom-FontIcons-Not-Display/1572131?space=41&entry=myfeedback)
[Existing Bug Report from 2020](https://developercommunity2.visualstudio.com/t/Terminal-Fonts-not-being-applied/1231235?space=41&entry=problem)
