### ISSUE TITLE
Git branch segment isn't being displayed

### ISSUE THREAD

**Issue by diegolonio** [romkatv/powerlevel10k#1626]
**I'm using p10k in an Ubuntu terminal running in WSL. It happens that the Git branch segment isn't being displayed. I tried the `p10k configure` command but it's still not being displayed even in the configuration wizard.**

![issue](https://user-images.githubusercontent.com/39118059/140438234-29bd9b7f-1def-476a-86f1-fca139dbedbb.gif)

![image](https://user-images.githubusercontent.com/39118059/140435419-0531bbd6-c030-4e0a-b602-b544fe964636.png)

![image](https://user-images.githubusercontent.com/39118059/140436062-34058e23-a102-4fdc-b47f-801a5b7698e1.png)

**When I execute a command the segment is displayed for less than one second and then it disappears. This is an example in a Git repo.**

![image](https://user-images.githubusercontent.com/39118059/140436154-64aa337b-66b5-41f4-b53b-8da7b87713d3.png)

**Also characters' names aren't being displayed in the configuration wizard.**

![image](https://user-images.githubusercontent.com/39118059/140435923-dd212775-67aa-4330-8fcf-c86753dda344.png)

![image](https://user-images.githubusercontent.com/39118059/140435981-2d4b30be-dd43-4494-be37-16cf24c26f4c.png)

**Neither choosing ASCII nor Unicode has helped me. ¿Does anyone know what can I do?**

**Comment by romkatv** [comment]
Your terminal is configured to display green as black. You need to fix that in the terminal settings.
