### ISSUE TITLE
Option to display exit status at end of command

### ISSUE THREAD

**Issue by leighmcculloch** [romkatv/powerlevel10k#1627]
I'd like to make powerlevel10k print the exit code of the last command at the end of the command on its own line, above the prompt line, essentially separate to the prompt line.

With my previous zsh prompt script I did this by outputting that printing at the beginning of the prompt line, but I'm not sure how to replicate that with powerlevel10k.

How it looked in my previous script was:
<img width="292" alt="Screen Shot 2021-11-04 at 11 17 45 PM" src="https://user-images.githubusercontent.com/351529/140467001-2ce5aa53-8fc8-44d4-84e2-b0a8399af6d4.png">

I achieved this with a simple:
```zsh
exit_code() {
  code=$?
  if [ $code -eq 0 ]; then return; fi
  # A zero-width space is added to the end to ensure the new line is not trimmed
  echo "❌ %{$fg[red]%}exit code $code\n\n​"
}
```

Where would be the right place to insert something like this?

**Comment by leighmcculloch** [comment]
Also, I realize that powerlevel10k has the builtin option to display the exit status code inside the prompt line. I'm looking specifically how to display it above the prompt line, separate to the prompt line, so that it stays there in the output even when the prompt line disappears when transient prompt is enabled.

**Comment by romkatv** [comment]
Try adding this to `~/.zshrc`:

```zsh
function print-exit-code() {
  local -i code=$?
  if (( code )); then
    print -rC1 -- '' ${(%):-"❌ %F{red}exit code $code"} ''
  fi
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd print-exit-code
```

This is not specific to powerlevel10k.

**Comment by leighmcculloch** [comment]
Ah, thanks @romkatv ! That's really helpful. And alologies, I hadn't considered of using the hooks to implement this independent of of the prompt line. Great idea!!!

**Comment by bizrad** [comment]
Sharing a bit of my config I ended up using here in case anyone else is interested in this.

I don't like having my current prompt changed based on the last command and I don't want an error to repeat if I'm just hitting enter to add spacing between long outputs .

I set all my prompts green in the config
```
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=76
```

Then only print exit code if there was a command
```
# Print non-zero exit codes
function store-command-run() { cmd=$1; }
function print-exit-code() {
  local -i code=$?
  if [ "$cmd" ]; then
    lcmd=$cmd
    cmd=
    if (( code )); then
      print -rC1 -- ''${(%):-"❌ %F{red}exit code $code%f"}''
    fi
  fi
}

autoload -Uz add-zsh-hook
add-zsh-hook preexec store-command-run
add-zsh-hook precmd print-exit-code
```

**Comment by romkatv** [comment]
@bizrad Note that your code malfunctions if you attempt to execute something like `fi`.

**Comment by bizrad** [comment]
Yeah, thanks for pointing that out. While it won't print on shell logic errors like you say, I still think this is very usable. This is still a more feedback than I'm used to 🙂 

```
❯ cat foo
cat: foo: No such file or directory
❌ exit code 1
❯ fi
zsh: parse error near `fi'
❯ echo $?
1
❯
```

**Comment by romkatv** [comment]
Alternatively, you could avoid holding ENTER to separate commands and instead define a separate keybinding that would draw a horizontal line and print a bunch of empty lines. Then you wouldn't need the preexec hook and would avoid this bug.
