### ISSUE TITLE
no such file or directory: ~/.antigen/bin/internal/p10k.zsh

### ISSUE THREAD

**Issue by andreiz** [romkatv/powerlevel10k#1629]
Trying to install powerlevel10k via antigen I get this output:

> antigen init ~/.antigenrc
Installing romkatv/powerlevel10k@master... Done. Took 1s.
(anon):source:27: no such file or directory: /home/andrei/.antigen/bin/internal/p10k.zsh

and then the ssh session hangs, Ctrl-Z doesn't work, have to kill the session

**Comment by romkatv** [comment]
If you installed powerlevel10k differently from the [instructions](https://github.com/romkatv/powerlevel10k#antigen), try reinstalling by following the instructions. You can also try `antigen reset` or even `rm -rf ~/.antigen`. If nothing helps, open an issue against antigen. Give them more information than you've given here.
