### ISSUE TITLE
gitstatusd not reporting correctly

### ISSUE THREAD

**Issue by shaunhp** [romkatv/powerlevel10k#163]
Hi, I cannot seem to see when my local is out of date anymore.  Not sure when this started happening but it _was_ working.  Using *zsh* with *oh-my-zsh* on MacOS *Mojave*.

e.g. I run `git remote show origin` and can see this output:

```
* remote origin
  Fetch URL: git@gitlab.com:<removed>.git
  Push  URL: git@gitlab.com:<removed>.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date)
```

I _know_ the origin has changes I haven't pulled, but in my prompt I don't see this.  I used to be able to.  There used to be little arrow that pointed down.  Now I just see `>master>` and that's it.   If I run `set | egrep '^VCS_STATUS'` in the same folder, I see this:

```
VCS_STATUS_ACTION=''
VCS_STATUS_COMMIT=909d5c7fcb3c6abaf20f37c826aeec7b4366c6b2
VCS_STATUS_COMMITS_AHEAD=0
*VCS_STATUS_COMMITS_BEHIND=0*
VCS_STATUS_HAS_CONFLICTED=0
VCS_STATUS_HAS_STAGED=0
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_HAS_UNTRACKED=0
VCS_STATUS_INDEX_SIZE=6
VCS_STATUS_LOCAL_BRANCH=master
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_NUM_STAGED=0
VCS_STATUS_NUM_UNSTAGED=0
VCS_STATUS_NUM_UNTRACKED=0
VCS_STATUS_REMOTE_BRANCH=master
VCS_STATUS_REMOTE_NAME=origin
VCS_STATUS_REMOTE_URL=git@gitlab.com:<removed>.git
VCS_STATUS_RESULT=ok-sync
VCS_STATUS_STASHES=0
VCS_STATUS_TAG=''
VCS_STATUS_WORKDIR=/Users/<removed>
```

Looks like something is broken.  Also, I used to notice in iTerm2 if I looked at `jobs` I would see gitstatusd running all the time.  I don't see it anymore.  Any help would be much appreciated!  Thank you.

**Comment by romkatv** [comment]
What's the output of `git status` in this repository?

**Comment by shaunhp** [comment]
```On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean```

**Comment by romkatv** [comment]
It's working as intended then. Your prompt shows the same thing as `git status`.

If there are changes on the remote, run `git fetch` to pick them up.

**Comment by shaunhp** [comment]
I was sure that used to happen automatically, in other words I didn't have to run `git fetch` to see the local was out of date.  I must have been mistaken...

**Comment by shaunhp** [comment]
p.s. Thanks very much for responding so quickly. :)

**Comment by romkatv** [comment]
Git doesn't run `git fetch` in the background, neither does p10k. You may have used a plugin that calls `git fetch` periodically on all your Git repos or something.

**Comment by luisdavim** [comment]
is there a way to embed `git fetch` in `powerlevel10k`?

**Comment by romkatv** [comment]
> is there a way to embed `git fetch` in `powerlevel10k`?

There isn't.

If you want your git repos to be fetched periodically, it's better to do it outside of a zsh theme. You can decide which repos to fetch and when, and p10k will keep doing its job -- showing you information.
