### ISSUE TITLE
P10K configure wizard on every terminal startup; ZSH command doesn't refresh terminal, launches the wizard again

### ISSUE THREAD

**Issue by yonasuriv** [romkatv/powerlevel10k#1630]
As said in the title.. everytime I close my terminal and start again, the configuration wizard launches again, like it's my first time
Also, when updating some stuff inside .zsrc, I try to update the terminal using 'zsh' command (like I always used) but now instead of updating it, it launches the wizard again

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by yonasuriv** [comment]
> https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started

  ~ ❯ POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true zsh                                                                                  22:35:24

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

/home/yonasuriv/.zshrc:134: sudo apt install not found

**Comment by romkatv** [comment]
👇 

> ```text
> /home/yonasuriv/.zshrc:134: sudo apt install not found
> ```

☝️

**Comment by yonasuriv** [comment]
> point_down
> 
> > ```
> > /home/yonasuriv/.zshrc:134: sudo apt install not found
> > ```
> 
> point_up

But it's installed

`sudo apt install `                                                   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by romkatv** [comment]
If you remove powerlevel10k from your config, you'll still get the same error. It's not specific to powerlevel10k. Your zshrc is just broken and you need to fix it. It's broken on line 134.

**Comment by yonasuriv** [comment]
> If you remove powerlevel10k from your config, you'll still get the same error. It's not specific to powerlevel10k. Your zshrc is broken and you need to fix it. It's broken on line 134.

Thanks you so much, problem solved

**Comment by romkatv** [comment]
👍
