### ISSUE TITLE
[Feature Request] Only show git prompt in home root when it's dirty

### ISSUE THREAD

**Issue by ElSamhaa** [romkatv/powerlevel10k#1632]
The title pretty much sums it up. I want to detect any changes to my dotfiles that aren't in sync with remote.

**Comment by romkatv** [comment]
You can do that by editing `my_git_prompt` in `~/.p10k.zsh`. It's fairly straightforward.

**Comment by ElSamhaa** [comment]
@romkatv you mean `my_git_format`?

**Comment by romkatv** [comment]
It's `my_git_formatter`. A function.

**Comment by ElSamhaa** [comment]
@romkatv I'm not sure how would you do that!

I want to satisfy this criterion:
* Hide git prompt in all subdirectories under HOME
* Hide git prompt when in HOME in case the `HEAD` is on `main` and in sync with the `remote`

I'm having a look at `my_git_formatter` rn, but are you suggesting that I should remove `~` from `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN` and check the directory under the `my_git_formatter`?

**Comment by romkatv** [comment]
> are you suggesting that I should remove `~` from `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN` and check the directory under the `my_git_formatter`?

yes

**Comment by ElSamhaa** [comment]
@romkatv I looked at the `p10k.zsh` file, and sadly I don't think that this requirement can be applied from there.

**Comment by romkatv** [comment]
Have you tried https://github.com/romkatv/powerlevel10k/issues/1632#issuecomment-965683251? What was the problem with this approach?

**Comment by romkatv** [comment]
CWD is `$PWD`. Status of the git repo is available through these: https://github.com/romkatv/powerlevel10k/blob/f217e4a39a284f6db7be7a4cfde8647085f97865/gitstatus/gitstatus.plugin.zsh#L90

**Comment by romkatv** [comment]
Closing because I believe I've answered all questions here. As per FAQ, customizing git prompt requires editing `my_git_formatter`.
