### ISSUE TITLE
When I use 'screen' window manager, the fonts don't look right.

### ISSUE THREAD

**Issue by bassamanator** [romkatv/powerlevel10k#1634]
Here is what my terminal looks like:
![image](https://user-images.githubusercontent.com/61985779/141507255-f96e1a44-4e72-42b5-8ec7-2386f45caa63.png)

Here is what my terminal looks like when I use [screen window manager](http://www.gnu.org/software/screen/manual/screen.html):
![image](https://user-images.githubusercontent.com/61985779/141507478-eeb7f121-fe00-427d-8110-f91b96320463.png)

Here is what my terminal looks like with the command `/snap/bin/serve -s todo` typed in the terminal:
![image](https://user-images.githubusercontent.com/61985779/141507787-51607831-9980-44f7-86c0-b0e11cd0983f.png)

Can this be fixed?

Thanks!

PS Love powerlevel10k. It's the first thing I install after installing omz.

**Comment by romkatv** [comment]
On broken screenshots all non-ascii characters are displayed as question marks. You need to figure out how to configure your terminal/screen/whatever to display non-ascii UNICODE characters properly. You can use this command as a test:

```zsh
print '\u2591'
```

Note that this is not specific to powerlevel10k. If this command prints a question mark, you need to fix your terminal.

Alternatively, you can run `p10k configure` while in a "broken" terminal and configure it to use only ascii characters. Your prompt won't be as pretty but it'll look the same way everywhere.

**Comment by bassamanator** [comment]
So, `print '\u2591'` prints a question mark. How do I fix my terminal, and what terminal exactly? On my local computer, I use terminator/konsole/guake. The computer with the 'garbled' text is a remote cloud computer running debian. Is there a guide that I can follow? Thanks!

>Operating System: Manjaro Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.2
Kernel Version: 5.11.4-1-rt11-MANJARO (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series

**Comment by romkatv** [comment]
> So, `print '\u2591'` prints a question mark. How do I fix my terminal, and what terminal exactly?

I don't know. This is not specific to powerlevel10k. If there was no electricity in your city, powerlevel10k wouldn't work and I wouldn't know how to help you. It's the same when your terminal cannot display U+2591.

**Comment by bassamanator** [comment]
Alright. I ended up running the p10k config in the broken terminal. For my remote computer, I can live without an extremely prettified terminal. 

Thanks for your help!
