### ISSUE TITLE
Prompt tail is on the next line. 

### ISSUE THREAD

**Issue by aruiplex** [romkatv/powerlevel10k#1636]
![image](https://user-images.githubusercontent.com/40193711/141683831-9c83a98e-021d-4aea-a72c-2c9b7eab6ba7.png)

![image](https://user-images.githubusercontent.com/40193711/141683851-838995b3-fc07-402e-bfe8-3a694b922344.png)

As the figure shown, the tail is on the next line.

I set the `.p10k.zsh` follow the [answer](https://stackoverflow.com/questions/61176257/customizing-powerleve10k-prompt) 

```
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last

typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=1
```

However, it is stil not working. 

My OS is `Ubuntu 21.10`. And the `.zshrc` is:

```bash
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export LANG='en_US.UTF-8'
export LANGUAGE='en_US:en'
export LC_ALL='en_US.UTF-8'
export TERM=xterm-256color

##### Zsh/Oh-my-Zsh Configuration
export ZSH="/home/aruix/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=()


source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

```

Thanks in advance.

**Comment by romkatv** [comment]
Please do the following:

1. Comment out `ZSH_THEME`:
  ```zsh
  # ZSH_THEME="powerlevel10k/powerlevel10k"
  ```
2. Add these two lines:
  ```zsh
  PS1=$'%F{2}━\uE0B0%f '
  RPS1=$'%F{3}\uE0B2━%f'
  ```
3. Restart zsh with `exec zsh`.
4. Post a screenshot of your terminal.

**Comment by aruiplex** [comment]
This is the screenshot:

![image](https://user-images.githubusercontent.com/40193711/141685824-4980e079-8198-4c3b-ad19-c7f848489d46.png)

And one thing more, in terminal the "tab" key to autocomplete sometimes will cause the screen to tear.

**Comment by romkatv** [comment]
As you can see on the second screenshot, your terminal is broken even when not using powerlevel10k. This issue is not specific to powerleve10k, so I'm closing it. You need to fix your terminal. One thing I would suggest is to remove these lines:

```zsh
export LANG='en_US.UTF-8'
export LANGUAGE='en_US:en'
export LC_ALL='en_US.UTF-8'
export TERM=xterm-256color
```

These variables should never be exported from zshrc. Once you remove these lines, restart your terminal. Restarting zsh is not enough.

If this doesn't help, ask for help elsewhere. This is not an issue with powerlevel10k.

**Comment by aruiplex** [comment]
Oh yes, very thank you.

**Comment by aruiplex** [comment]
I find my solution, the answer is in the ubuntu terminal. Change the **Wide** to **Narrow** in the **Compatibility**. The apparence of shell will be ok.

![image](https://user-images.githubusercontent.com/40193711/141686703-0e05ac0a-82e8-4d23-95ab-aaf0bf9fb6ad.png)

Very thanks this beautiful theme.

**Comment by romkatv** [comment]
Thanks for the update.
