### ISSUE TITLE
Multiple prompt lines when it should only be one

### ISSUE THREAD

**Issue by kevinrobayna** [romkatv/powerlevel10k#1637]
I have configured (see config https://github.com/kevinrobayna/dotfiles/blob/master/.p10k.zsh) to have a prompt on the next line but now it shows two (see picture)

![image](https://user-images.githubusercontent.com/5471469/141802440-6c85bfb5-8e19-47a9-97fc-7558d905f9a6.png)

after i change directory 

![image](https://user-images.githubusercontent.com/5471469/141802482-b73a4201-7041-45d1-8de8-a69f9c2f204a.png)

**Comment by romkatv** [comment]
Seems like you have two themes activated at the same time. You need to disable the other theme.

**Comment by kevinrobayna** [comment]
I configured p10k with `p10k configure` is the multiple themes something that would be in the `.zshrc` file instead?

**Comment by kevinrobayna** [comment]
these all the config i have in `.zshrc`

```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/dev/dotfiles/.p10k.zsh.
[[ ! -f ~/dev/dotfiles/.p10k.zsh ]] || source ~/dev/dotfiles/.p10k.zsh
```

**Comment by romkatv** [comment]
What happens if you run `exec zsh`?

**Comment by kevinrobayna** [comment]
![image](https://user-images.githubusercontent.com/5471469/141812023-370dac9a-9983-498b-8db2-bd1fa50b939a.png)

**Comment by kevinrobayna** [comment]
![image](https://user-images.githubusercontent.com/5471469/141823469-bd7aecdb-0c38-442b-a384-f38714b1d370.png)

**Comment by romkatv** [comment]
Hash of .zshrc doesn't match the content you've posted and the screenshot doesn't capture the prompt below.

Can you post the full content of your zshrc, run the command again and post a screenshot that includes the output of the command and the new prompt under it?

**Comment by romkatv** [comment]
Better yet, use what you've posted here as your .zshrc. You'll find that it resolves the issue.

**Comment by kevinrobayna** [comment]
oh! this is the `.zshrc` https://github.com/kevinrobayna/dotfiles/blob/master/.zshrc

**Comment by romkatv** [comment]
So something in that config prints the current directory. I'm guessing znap.

Unrelated, but you need to replace `export GPG_TTY=$(tty)` with `export GPG_TTY=$TTY`. The latter is about 1000 times faster and always works. The former doesn't work with instant prompt.

By the way, how did [this comment](https://github.com/romkatv/powerlevel10k/issues/1637#issuecomment-968995658) happen?

> these all the config i have in `.zshrc`
> 
> ```
> # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
> # Initialization code that may require console input (password prompts, [y/n]
> # confirmations, etc.) must go above this block; everything else may go below.
> if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
>   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
> fi
> 
> source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme
> 
> # To customize prompt, run `p10k configure` or edit ~/dev/dotfiles/.p10k.zsh.
> [[ ! -f ~/dev/dotfiles/.p10k.zsh ]] || source ~/dev/dotfiles/.p10k.zsh
> ```

**Comment by romkatv** [comment]
> TBH it was just to put everything that i thought related to `p10k` 😅

Don't do that. When someone is trying to diagnose a problem with your configs (for free, no less), lying to them is counterproductive.

Closing because it's not an issue with powerlevel10k.

**Comment by kevinrobayna** [comment]
thank you very much for the help!

This was my issue https://github.com/kevinrobayna/dotfiles/commit/826b3c26e98f45939e34c561864bf1c7b6ff0450

**Comment by romkatv** [comment]
Great! Note my first comment on this issue.
