### ISSUE TITLE
Can't set bold to "unicode"

### ISSUE THREAD

**Issue by emanuelep57** [romkatv/powerlevel10k#1638]
Hello, I am a user of p10k since almost a year, and I never had problems. Yesterday I installed it on my laptop and everything worked fine. Today I installed it on my desktop after a reset but "_unicode mode_" can't be set to bold.  I tried to set the bold in the config file, but sadly I have no idea how. Any idea why this issue is happening and how to solve it? Thanks in advance. I'll link a [picture of the issue](https://imgur.com/a/nneZ4Bn).

**Comment by romkatv** [comment]
> "unicode mode" can't be set to bold.

What does it mean?

> I'll link a [picture of the issue](https://imgur.com/a/nneZ4Bn).

Is this a picture from a non-working machine (desktop)? If so, what do you think is wrong with it?

**Comment by emanuelep57** [comment]
> What does it mean?
If you look at [this picture](https://imgur.com/a/EMJieiX) you'll notice how colors of the prompt in unicode character set are bold. While in the [picture of the issue](https://imgur.com/a/nneZ4Bn) are not.

> Is this a picture from a non-working machine (desktop)? If so, what do you think is wrong with it?
Well, on this desktop until was worked fine until yesterday. Now I don't know why unicode character set looks the same as ascii, just slightly different

**Comment by romkatv** [comment]
Most terminals have a setting whether to use bold fonts or not. In this case I think both terminals on your screenshots support bold fonts. Compare "Restart from the beginning" (not bold) with "Choice" under it (bold). The two terminals use different fonts though. Compare 'g' at the end of "nothing" for example. Font size is also different.

By the way, you can drag-and-drop your screenshots to the edit box on github.

**Comment by romkatv** [comment]
> I don't know why unicode character set looks the same as ascii, just slightly different.

The only different character between the two choices on this screen is `❯` vs `>`. However, the choice will affect the next screens in the wizard to a much greater degree.

**Comment by emanuelep57** [comment]
> By the way, you can drag-and-drop your screenshots to the edit box on github.

I am not using a graphical file manager 

> The two terminals use different fonts though. Compare 'g' at the end of "nothing" for example. Font size is also different.

They use the exact same configuration, I copied and pasted it, I suppose the problem is on my side, something missing. thanks for your time!

**Comment by romkatv** [comment]
> I am not using a graphical file manager

Cool I guess. I cannot say anything about other maintainers but *I* very much prefer when people asking for help post screenshots directly on github rather than on imgur.com. It would takes less of my time to help you and the history of my project's issues would be self-contained.

> They use the exact same configuration, I copied and pasted it, I suppose the problem is on my side

You see that 'g' is different on the two screenshots, right? These two terminals use different fonts. You can run this command to see it without powerlevel10k:

```zsh
echo 'g ❯'
```

**Comment by emanuelep57** [comment]
> You see that 'g' is different on the two screenshots, right? These two terminals use different fonts.

Yes, I do see it. But  I am **theorically** using the same font and the same configuration.. Anyway thanks a lot for your help :)
