### ISSUE TITLE
Your OhMyZsh instructions are bad.

### ISSUE THREAD

**Issue by kingram6865** [romkatv/powerlevel10k#1639]
`/home/kingram/.oh-my-zsh/oh-my-zsh.sh:source:177: no such file or directory: /home/kingram/.oh-my-zsh/themes/powerlevel10k/powerlevel0k.zsh-theme`

Actual directory: `/home/kingram/.oh-my-zsh/custom/themes/powerlevel10k`

My .zshrc

```
export TERM="xterm-256color"
export ZSH="/home/kingram/.oh-my-zsh"

#ZSH_THEME="powerlevel9k/powerlevel9k"
#POWERLEVEL9K_COLOR_SCHEME='light'

ZSH_THEME="powerlevel10k/powerlevel0k"
plugins=(git)
source $ZSH/oh-my-zsh.sh
```

**Comment by romkatv** [comment]
Your config is bad.

```text
> ZSH_THEME="powerlevel10k/powerlevel0k"
```

This line ☝️ has a typo. Copy-paste it from the instructions to avoid mistakes of this kind.

**Comment by kingram6865** [comment]
> Your config is bad.
> 
> > ```
> > ZSH_THEME="powerlevel10k/powerlevel0k"
> > ```
> 
> This line ☝️ has a typo. Copy-paste it from the instructions to avoid mistakes of this kind.

Ah. I am embarassed. Forgive me the mistake.

**Comment by romkatv** [comment]
> Forgive me the mistake.

Naaaah 😛
