### ISSUE TITLE
Dynamically change transient prompt

### ISSUE THREAD

**Issue by piotrekfus91** [romkatv/powerlevel10k#1640]
Hi! First of all - you do a great job, I love p10k.
I have a question - is it possible to change prompt transience dynamically (using some keyboard shortcut)? I'm afraid it's not possible, but let me explain my reasoning.
Full prompt (i.e. two liner) looks great and I would really appreciate to work with that. But, on the other hand, when copying and pasting terminal, it looks terrible, so for commands results it is better to keep it simple. So for now i can't use full prompt, but it would be awesome if I can switch view dynamically (shrink just to copy and then return to full version).
Thanks in advance :)

**Comment by romkatv** [comment]
Add this to `~/.zshrc`:

```zsh
function toggle-transient-prompt() {
  (( ${+functions[p10k]} )) || return
  if [[ ${POWERLEVEL9K_TRANSIENT_PROMPT-} == off ]]; then
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  else
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
  fi
  p10k reload
  if zle; then
    zle push-input
    zle accept-line
  fi
}
```

Invoke this function by typing `toggle-transient-prompt`. You can also bind it to a key by adding two more lines to `~/.zshrc`:

```zsh
# Bind Ctrl-T to toggle powerlevel10k transient prompt.
zle -N toggle-transient-prompt
bindkey '^T' toggle-transient-prompt
```

**Comment by piotrekfus91** [comment]
That is nice, helpful indeed, but not exactly solving my problem. I would like to change previous lines (results of previous commands), to be able to copy past results. Is it possible?
Your solution is also great, obviously, but need to know that you would want to copy before typing command :)

**Comment by romkatv** [comment]
> Is it possible?

Nope. Terminals don't work that way.

**Comment by piotrekfus91** [comment]
Ok, anyway - many thanks for your answers and extremely short response time!

**Comment by romkatv** [comment]
You are welcome.

**Comment by yittg** [comment]
@romkatv Can [these feature](https://github.com/romkatv/powerlevel10k/issues/1640#issuecomment-970066345) be builtin? That would be great.

**Comment by romkatv** [comment]
@yittg The code I've posted uses only public APIs of powerlevel10k, so it's safe to use as is. It won't break when powerlevel10k is updated. I don't think I'll be including this widget or a binding in powerlevel10k but that shouldn't stop you from using this code.
