### ISSUE TITLE
Prompt being replaced after hiting enter

### ISSUE THREAD

**Issue by betogrun** [romkatv/powerlevel10k#1643]
I just installed powerline10k on ohmyzsh and I noticed the prompt is being replaced by `>` after a command is entered.

It starts with the expected prompt:
<img width="238" alt="image" src="https://user-images.githubusercontent.com/14967395/142679273-ca9f2e84-7291-4130-ae1b-d5bc65acfc08.png">

After I hit enter, the previous prompt is replaced:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/14967395/142679496-bb1bf469-3531-49b1-a655-34cb65e7a621.png">

Is it expected?

**Comment by romkatv** [comment]
It's expected if that's what you choose when you run `p10k configure`. If you don't like it, run `p10k configure` and choose differently. The relevant screen is called "Transient Prompt".

**Comment by betogrun** [comment]
Got it! 
Thanks!

**Comment by romkatv** [comment]
Transient Prompt is a popular feature and one my favorite. You can see it in action here with a different prompt style:

![transient prompt](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/performance.gif)

Several prompt features interact in a way that makes overall result better than the sum of its parts. See [this FAQ entry](https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard).

**Comment by betogrun** [comment]
This is really cool! I'm giving transient prompt another try!
I noticed the prompt starts from the bottom, and I try to follow the instructions [here](https://github.com/romkatv/powerlevel10k/issues/563#issuecomment-656547713) without success. Is there another approach?

**Comment by betogrun** [comment]
Nevermind! I got used to the transient prompt regardless of its position. Thanks for sharing this!

**Comment by romkatv** [comment]
If you want prompt to start at the bottom, add this at the very top of zshrc (above even the instant prompt preamble):

    repeat $LINES print

If you want prompt to start at the bottom *and stay there*, you'll need to install zsh4humans.

[![asciicast](https://asciinema.org/a/372068.svg)](https://asciinema.org/a/372068)

**Comment by betogrun** [comment]
Love it! 
I'm using z4h!
