### ISSUE TITLE
Loading is Slow and causes Freezing / Process Interruption on OSX Big Sur

### ISSUE THREAD

**Issue by bgenchel** [romkatv/powerlevel10k#1644]
Hi,

I just upgraded my 2019 13" MacBook Pro to Big Sur, and found that trying to open and load my terminal in iterm2 was significantly delayed. It also caused freezing of programs like Alfred and Cisco AnyConnect. I use .oh-my-zsh with stock macbook zsh installation. 

Once I was able to change my theme to something default in oh-my-zsh, the problem went away. So, this issue is certainly stemming from something in powerlevel10k. 

When I open the terminal window when using the theme I see the following in the window top bar (mine shows commands being run):

- login
- uname
- python
- zsh
- git
- who

it gets stuck on who, but I also noticed between window openings the presence of several other commands.

Not sure what to do or where this problem is coming from.

**Comment by romkatv** [comment]
> It also caused freezing of programs like Alfred and Cisco AnyConnect. Once I was able to change my theme to something default in oh-my-zsh, the problem went away. So, this issue is certainly stemming from something in powerlevel10k.

It's very unlikely that powerlevel10k could cause freezing of programs like Alfred and Cisco AnyConnect. It doesn't operate on the level where such effects could possibly be achieved.

Can you switch back to powerlevel10k and verify that Alfred and Cisco AnyConnect freeze and then disable powerlevel10k and verify that these programs don't freeze? My guess is that your machine is very slow when running *any* program for the first time. Or maybe everything was very slow for a while after upgrade. You happened to be using powerlevel10k at the time and a different theme after, so it may have looked like a zsh theme makes a difference.

> it gets stuck on who

Can you clarify? Does "stuck" mean it freezes forever or just takes a long time? If the latter, how long does it stay on `who`?

Can you post the output of `repeat 2 time who -m`?

**Comment by bgenchel** [comment]
Thanks for getting back to me. I tried switching the theme to 'nanotech' and back, and can verify that the theme is the cause of the slowness.
 
My computer doesn't appear to be slow otherwise. Everything is responsive, except when I open my terminal with powerlevel10k as the theme. 

Stuck means that the terminal isn't acting, my vpn disconnects and reconnects, I see the mac waiting colorwheel, and Alfred freezes.

**Comment by bgenchel** [comment]
Seems like the issue had to do with git status updates, and potentially was due to my using an outdated version of powershell10k. Things are working fine after reinstalling.
