### ISSUE TITLE
Current directory truncate not working.

### ISSUE THREAD

**Issue by pedrogcamposb** [romkatv/powerlevel10k#1645]
Hello! First of all, congrats on the theme, it is great! However, the current directory truncate feature doesn't seem to be working, whenever I get to a very long path, it does not shorten and eats up the prompt elements on the right... am I missing something or is it really a bug? I've gone over the .p10k.zsh file many times and I don't seem to find nothing wrong there. I've tested both on iTerm2 and the mac Terminal and both terminals report this problem. I am attaching pictures so you can better understand my problem.

Before truncate flaw
<img width="886" alt="Screen Shot 2021-11-20 at 00 27 53" src="https://user-images.githubusercontent.com/71517464/142713426-2d744acb-3250-4bbe-8473-8facbc949bae.png">

Truncate flaw
<img width="883" alt="Screen Shot 2021-11-20 at 00 28 18" src="https://user-images.githubusercontent.com/71517464/142713427-c187b3ec-4c08-4b87-b145-a09b6883471c.png">

**Comment by romkatv** [comment]
Please attach your `~/.p10k.zsh`.

Does this happen only in `~/onedrive`?

**Comment by pedrogcamposb** [comment]
No, it happens wherever.

Before flaw
<img width="883" alt="Screen Shot 2021-11-20 at 15 57 41" src="https://user-images.githubusercontent.com/71517464/142738072-05cf082b-f85f-41a2-8502-3d57aafc5e40.png">

Truncate flaw
<img width="884" alt="Screen Shot 2021-11-20 at 15 58 01" src="https://user-images.githubusercontent.com/71517464/142738073-62c87609-01ee-4206-b0a1-21ed747bc900.png">

P10K ZSH file copy
[p10k.zsh.zip](https://github.com/romkatv/powerlevel10k/files/7575078/p10k.zsh.zip)

I found a work around the flaw by only using prompt elements in line 2.

**Comment by romkatv** [comment]
I cannot reproduce this with your `.p10k.zsh` and the following `.zshrc`:

```zsh
[[ -e ~/powerlevel10k ]] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
source ~/powerlevel10k/powerlevel10k.zsh-theme
source ~/.p10k.zsh
```

Can you?

**Comment by pedrogcamposb** [comment]
I can... but I don't have the first two lines in my .zshrc file, only the last one ```source ~/.p10k.zsh```. I am attaching my .zshrc file so you can better take a look.

[zshrc.zip](https://github.com/romkatv/powerlevel10k/files/7576466/zshrc.zip)

**Comment by romkatv** [comment]
Please do the following:

1. Replace your `~/.zshrc` with this:
  ```zsh
  [[ -e ~/powerlevel10k ]] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  source ~/powerlevel10k/powerlevel10k.zsh-theme
  source ~/.p10k.zsh
   ```
2. Reboot your machine.
3. Check whether the problem is still there.

**Comment by pedrogcamposb** [comment]
Yes, it still persists... but I think we can let this go, the work around I found is fine by me.

**Comment by romkatv** [comment]
Let's try a few more things. Please run the following command and post a screenshot when it shows prompt:

```zsh
() (
  emulate -L zsh -o err_return
  local tmp
  {
    tmp="$(command mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
    builtin cd -q -- $tmp
    command curl -fsSLO https://github.com/romkatv/powerlevel10k/files/7575078/p10k.zsh.zip
    command unzip p10k.zsh.zip
    command mv p10k.zsh .p10k.zsh
    >.zshrc <<\END
[[ -e ~/powerlevel10k ]] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
source ~/powerlevel10k/powerlevel10k.zsh-theme
source ~/.p10k.zsh
END
    command mkdir -p documents/code/downloads/css-hover-package/hover-master
    builtin cd -q documents/code/downloads/css-hover-package/hover-master
    ZDOTDIR=$tmp HOME=$tmp command zsh --no-global-rcs
  } always {
    builtin cd -q /
    command rm -rf -- "$tmp"
  }
)
```

**Comment by romkatv** [comment]
> Please run the following command and post a screenshot when it shows prompt

I'd appreciate if you could do this.

**Comment by romkatv** [comment]
Oh well.
