### ISSUE TITLE
Prompt heads not correctly aligned

### ISSUE THREAD

**Issue by hblanko** [romkatv/powerlevel10k#1646]
Hello everyone,

I'm doing a fresh install of Zsh and the powerlevel10k in Ubuntu and I'm encountering that the prompt heads when choosing Unicode character set are not properly aligned with the prompt itself, actually kind of shifted down a pixel.

This picture shows the issue:
![image](https://user-images.githubusercontent.com/6222166/142761237-9394aead-0b27-4ce5-b279-9e43c67b4a9e.png)

I did install the MesloLGS font.

Any clue on what is happening?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by hblanko** [comment]
Hi @romkatv, indeed that explains a lot. Didn't see this info in the README before. Font resizing mostly helped, but I ended up going to the "Lean" style, which is great too :wink:.

Congrats for the nice work!
