### ISSUE TITLE
weird bug? when resizing terminal

### ISSUE THREAD

**Issue by damdam-kr** [romkatv/powerlevel10k#1648]
Forgive me if this is already asked. But i noticed that when I resize my terminal, it does show some of this weird looking prompts until i clear terminal again
![Screenshot_20211125_111206](https://user-images.githubusercontent.com/85185940/143365841-141a5559-618d-409d-a077-78309cb4582f.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
