### ISSUE TITLE
Directory substitutions

### ISSUE THREAD

**Issue by martylouis** [romkatv/powerlevel10k#1652]
Is there a way to to define arbitrary replacements for literal strings that occur in the path, for example long network prefixes or development directories (i.e. github)

Ex: `~/github/example/path` to `github.com/example/path`

<img width="502" alt="CleanShot--102732@2x" src="https://user-images.githubusercontent.com/169188/144090549-48a1f5e0-d6fe-48b7-8c40-ee2233121424.png">

I would like to remove `~/github/` and prefix with `github.com` so that we can just cmd+click on the path to open in a browser.

Similar to how [starship.rs](https://starship.rs/config/#options-13) handles directory substitutions (see "▶" dropdown for advanced configuration).

If there's a simpler solution just using a function, please let me know.

Thanks!

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/1518#issuecomment-890808101

**Comment by martylouis** [comment]
Okay, yeah that is a solution is something I explored as well, was just curious if there was anything like the starship.rs solution out of the box.

Thanks for the response and appreciate the plugin!!

**Comment by romkatv** [comment]
I don't think the solution in starship is very good. To be honest, I think it's actually quite bad. You get the ability to see (and copy) the github URL but at the same time lose the ability to see (and copy) the current directory. Besides, the current directory get automatically shortened if it's too long. The shortening is unambiguous, so you can copy-paste the shortened directory and expand it to the original with TAB. However, if a github URL gets shortened it'll be broken. So it only appears that starship has a solution to your problem while in reality it does not.
