### ISSUE TITLE
The goenv segment shows the whole content of the go.mod file

### ISSUE THREAD

**Issue by zxeoc** [romkatv/powerlevel10k#1653]
The goenv segment shows the whole content of the go.mod file in the path of a golang project, which takes a lot of space.
![image](https://user-images.githubusercontent.com/4046320/144289406-278ef099-ec29-4345-8ec3-819bef8953ba.png)

**Comment by romkatv** [comment]
What's the output of the following command?

```zsh
() {
  emulate -L zsh -o extended_glob
  local f
  for f in ./(../)#.go-version(#qN:a); do
    command ls -ld -- $f
    if [[ -f $f && -r $f ]]; then
      command cat -- $f
    fi
    print -r -- -------------------
  done
}
```

**Comment by zxeoc** [comment]
How do I run this command?

**Comment by romkatv** [comment]
The easiest would be to copy-paste it into your terminal. You can also type it by hand.

**Comment by zxeoc** [comment]
It doesn't give any output.
![image](https://user-images.githubusercontent.com/4046320/145164353-02fb5f9c-ad9e-4a69-bc72-043e8536e145.png)

**Comment by romkatv** [comment]
Why do you think it's goenv that shows "module gitUpdater..." in prompt?

**Comment by zxeoc** [comment]
Sorry, my mistake. I thought it's for detecting the environment of golang projects. And I found a "go.mod" for "anchor_files", but it doesn't seem to be the config for showing the info. Any idea how I can config this?

**Comment by romkatv** [comment]
It's a bug in some prompt segment. Before I can fix it you'll need to figure out which segment that is. You can do that by disabling prompt segments in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` one by one until the problematic segment disappears.

1. Open `~/.p10k.zsh`.
2. Find `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.
3. Comment out one of the segments.
4. Save the file.
5. Restart zsh with `exec zsh`.
6. If the problematic segment disappears from prompt, tell me which segment you've removed commented out last. Otherwise got to step 1.

**Comment by zxeoc** [comment]
Found it. It's the asdf segment. But I didn't install golang through asdf( yes, I installed asdf and golang plugin of it, but for now, my golang installation is from pamac ).
`asdf current golang`
shows "golang          ______          No version is set..."

**Comment by zxeoc** [comment]
I found a "typeset -g POWERLEVEL9K_ASDF_SHOW_ON_UPGLOB=" line in the `~/.p10k.zsh` without value set. Should that be the case?

**Comment by romkatv** [comment]
I've made a change that might (although not very likely) to fix the issue. Please update powerlevel10k, restart zsh with `exec zsh`, and let me know if it helps.

**Comment by zxeoc** [comment]
Problem solved! Thank you!

**Comment by romkatv** [comment]
Thanks for verifying.
