### ISSUE TITLE
A color by virtualenv ?

### ISSUE THREAD

**Issue by agaillar** [romkatv/powerlevel10k#1654]
Hello, 

thank you very much for this project. It is really top!

I have a question regarding the management of virtualenvs.
I have one virtualenv per environment (dev, stagging, prod ...).
I will want to change the color (POWERLEVEL9K_VIRTUALENV_BACKGROUND) according to the enabled virtualenv.
I tried to reload the .p10k.zsh in the postactivate script but it didn't work.
Thanks for your help.

**Comment by romkatv** [comment]
Try this:

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=1
p10k reload
```

**Comment by agaillar** [comment]
top, the p10k reload in the postactivate file !
Thanks

**Comment by romkatv** [comment]
?

**Comment by agaillar** [comment]
Hello, 

in postactivate file of my virtualenv, i have added the next lines : 

```
typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=46
p10k reload
```

The color of  virtualenv change. it's OK.

But, in the git folder, i have this error : 

![image](https://user-images.githubusercontent.com/17762091/145694124-ffb1d919-d67c-4208-97d1-1f76c2c43b0f.png)

It's a good idea to reload p10k from this file ?

Thanks for your help.

**Comment by romkatv** [comment]
I don't know why that happens but it's possible that you can fix it by adding this line at the very bottom of `~/.zshrc`:

```zsh
unset ZSH_AUTOSUGGEST_USE_ASYNC
```

**Comment by agaillar** [comment]
If's OK.
Thanks @romkatv !! 💪

**Comment by romkatv** [comment]
Did my suggestion help? Is the error gone?

**Comment by agaillar** [comment]
yes, it 's OK. I no longer have errors.
Thanks

**Comment by romkatv** [comment]
Thanks for the confirmation.
