### ISSUE TITLE
Can't use it in tmux

### ISSUE THREAD

**Issue by rzksobhy78** [romkatv/powerlevel10k#1656]
![Sun Dec  5 03:40:52 EET 2021](https://user-images.githubusercontent.com/94202082/144730145-c918319b-dafe-46ee-ac21-f7c1af3a0bcb.png)

how to make tmux use it

**Comment by romkatv** [comment]
Your tmux has two issues.

1. It cannot display 256 colors. To fix this, create `~/.tmux` with `set -g default-terminal screen-256color` in it and reboot your machine.
2. It cannot display non-ascii characters. To fix this, install and enable a UTF-8 locale in your OS and reboot your machine.

You can verify that you've fixed tmux by running the following command:

```zsh
print -P -- '--> %F{70}\u276E\u276F%f <--'
```

The output must look like this:

![image](https://user-images.githubusercontent.com/1282067/144739612-5bdcd187-00a8-4ce1-9f62-a2e02ba8af6c.png)

**Comment by murchu27** [comment]
Thanks, the first fix did the trick for me. The test command was a very helpful test, thanks for that test also.

This should probably be put in the docs somewhere. Maybe in the FAQ section of the README?

**Comment by romkatv** [comment]
@murchu27  The FAQ is already so big that few read it. I don't think it's a good idea to start adding entries to it that aren't specific to powerlevel10k (e.g. how to configure tmux so that it can display UNICODE and 256 colors).

**Comment by Kha1r0** [comment]
for anyone coming coming across this issue in the future: 
i had to put the `set -g default-terminal screen-256color` line in `~/.tmux.conf`, NOT `~/.tmux`. Thanks for the help!

**Comment by natereprogle** [comment]
> for anyone coming coming across this issue in the future: i had to put the `set -g default-terminal screen-256color` line in `~/.tmux.conf`, NOT `~/.tmux`. Thanks for the help!

The world needs more people like you lol, thanks! I had to have my absolutely unnecessary colors in tmux, this worked perfectly 🤣

**Comment by sauravexodus** [comment]
Thanks @Kha1r0!
