### ISSUE TITLE
Icon cut off in theme powerlevel10k

### ISSUE THREAD

**Issue by redhat72** [romkatv/powerlevel10k#1657]
What I try but can't fix:
"Manually add an extra space after the icon that gets cut off. For example, if the content of os_icon prompt segment gets cut off, open ~/.p10k.zsh, search for POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION and change it as follows:
```typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='ﮈ ' ```     "
I'm using Ubuntu  on WSL2 - Windows Terminal.
![image](https://user-images.githubusercontent.com/95615284/144820417-565bd631-e9ca-404c-aa05-395e75047fd9.png)
![iG6kR](https://user-images.githubusercontent.com/95615284/144820527-cabdbcaf-38c1-4ead-8499-b8d67a30295e.png)
Thank!

**Comment by romkatv** [comment]
It's a bug in Windows Terminal. I think Konsole has a similar bug but most terminals don't have it.

It's possible that this bug doesn't trigger if you switch to Lean style. Worth giving it a try.
