### ISSUE TITLE
Prompt does not resize properly causing garbage all over terminal

### ISSUE THREAD

**Issue by markcarroll** [romkatv/powerlevel10k#1658]
MacOS 12.0.1
Using `Terminal`
<img width="996" alt="Screen Shot 2021-12-06 at 10 23 42 AM" src="https://user-images.githubusercontent.com/599566/144901390-5de35766-d16a-4add-bd8a-faedc70f95cb.png">

Video here: https://imgur.com/a/PjL9XBo

Here is my config
[p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/7662758/p10k.zsh.txt)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
