### ISSUE TITLE
nvm prompt uses `commands[nvm]`

### ISSUE THREAD

**Issue by frescoraja** [romkatv/powerlevel10k#166]
i noticed my nvm prompt does not show, even when i set my node version to a version other than the default... when i look at source of `prompt_nvm` i see that you are using `$+commands[nvm]` .. but in my system that returns 0.. `$+functions[nvm]` however returns 1.

i installed nvm using the installation script from their readme.

just wondering if this is a bug or something due to my own environment? thanks!

**Comment by romkatv** [comment]
Thanks for the bug report! Fixed.
