### ISSUE TITLE
[FEATURE?] Is it possible to set DIR_CLASSES colour for each folder

### ISSUE THREAD

**Issue by quiltedstars** [romkatv/powerlevel10k#1661]
Hi, I'm working on trying to colour each directory path a different (or at least recursively-patterned) way. I really appreciate that PL10K already has colour differences for the inner folders against the current and home folder, along with the options of POWERLEVEL9K_DIR_CLASSES. 
However, when I am trying to change the DIR CLASSES based on a previous issue here:
```
typeset -g POWERLEVEL9K_DIR_CLASSES=(
    '~'                     HOME              ''
    '~/*'                   HOME_SUBFOLDER    ''
    '/private/etc(|/*)'     ETC               ''
    '*'                     DEFAULT           ''
  )

  typeset -g POWERLEVEL9K_DIR_FOREGROUND='#d0d0d0'

  # typeset -g POWERLEVEL9K_DIR_HOME{,_NOT_WRITABLE}_FOREGROUND='#d0d0d0'
  typeset -g POWERLEVEL9K_DIR_HOME{,_NOT_WRITABLE}_BACKGROUND='#005faf'
  typeset -g POWERLEVEL9K_DIR_HOME{,_NOT_WRITABLE}_VISUAL_IDENTIFIER_EXPANSION='h '

  # typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER{,_NOT_WRITABLE}_FOREGROUND='#d0d0d0'
  typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER{,_NOT_WRITABLE}_BACKGROUND='#005fd7'
  typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER{,_NOT_WRITABLE}_VISUAL_IDENTIFIER_EXPANSION='hs '

  # typeset -g POWERLEVEL9K_DIR_ETC{,_NOT_WRITABLE}_FOREGROUND='#d0d0d0'
  typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND='#005fff'
  typeset -g POWERLEVEL9K_DIR_ETC_NOT_WRITABLE_BACKGROUND='#5f00af'
  typeset -g POWERLEVEL9K_DIR_ETC_{,NOT_WRITABLE_}VISUAL_IDENTIFIER_EXPANSION='etc '

  # typeset -g POWERLEVEL9K_DIR_DEFAULT{,_NOT_WRITABLE}_FOREGROUND='#d0d0d0'
  typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='#005fff'
  typeset -g POWERLEVEL9K_DIR_DEFAULT_VISUAL_IDENTIFIER_EXPANSION='def '

  typeset -g POWERLEVEL9K_DIR_DEFAULT_NOT_WRITABLE_BACKGROUND='#870000'
  typeset -g POWERLEVEL9K_DIR_DEFAULT_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='nw '
```

It hasn't changed the way I expected it to--obviously I didn't expect it to do exactly what I want, but I'm a bit stuck on what to do next. 
Essentially, I would be trying to figure out a way that I could have POWERLEVEL9K_DIR_CLASSES include:
```
~, ~/(+1 subfolder), ~/(1)/(+2), ~/(1)/(2)/(3), ...~/.../(n)
```
where the backgrounds of, say, the odd and even folders/directories are different colours, but without being restricted by having to put in a specific folder? Again, I think the code I used has this at a primary level  (~/*), but I am new to all of this.

Any help, or if someone could say if this is even possible, would be much appreciated.

**Comment by romkatv** [comment]
Describe what you are trying to achieve.

**Comment by quiltedstars** [comment]
![term](https://user-images.githubusercontent.com/87580563/145463063-8dccdcba-2a0d-4735-a10d-7fdb15518626.png)
I'm hoping to change the background color, or text color, of each directory. So the home directory ~ would be one colour, the second (in this case, Orchis-theme) would be another, and so on. Honestly, though, I would be fine with two alternating colors. If it isn't possible, though, this is already miles better than what I previously had!

**Comment by romkatv** [comment]
> So the home directory ~ would be one colour, the second (in this case, Orchis-theme) would be another, and so on.

Do you mean that when your current directory is `~/foo/bar/baz`, you want to see `~`, `foo`, `bar` and `baz` all in different colors?

**Comment by quiltedstars** [comment]
> > So the home directory ~ would be one colour, the second (in this case, Orchis-theme) would be another, and so on.
> 
> Do you mean that when your current directory is `~/foo/bar/baz`, you want to see `~`, `foo`, `bar` and `baz` all in different colors?

Yes!

**Comment by romkatv** [comment]
Powerlevel10k doesn't support this.

**Comment by quiltedstars** [comment]
Oh okay, thanks for letting me know
