### ISSUE TITLE
Rainbow, 8 colors unavailable

### ISSUE THREAD

**Issue by LLBlumire** [romkatv/powerlevel10k#1662]
When setting up a prompt, and selecting rainbow, no option to use only 8 colors is ever presented. This is desirable as it would mean better matching with my terminal theme.

The readme notes in this section: https://github.com/romkatv/powerlevel10k#change-the-color-palette-used-by-your-terminal

> Rainbow, Lean → 8 colors or Pure → Original

Which would imply that an 8 color mode for rainbow exists. But the only color options I am offered are lightest, light, dark, and darkest for the middle bar, never options for the overall color range

**Comment by romkatv** [comment]
Rainbow mostly uses the base colors but not exclusively. If you need prompt that works on terminals that can display only 8 colors, use Lean style.
