### ISSUE TITLE
Possible to hide Anaconda environment if it's base?

### ISSUE THREAD

**Issue by Lunchb0ne** [romkatv/powerlevel10k#1667]
Hi, so I use anaconda with its base as the python interpreter, so it's activated all the time. Is it possible to edit the config so that I can hide the segment if the environment is set to base?

**Comment by romkatv** [comment]
Try adding this to `~/.p10k.zsh`:

```zsh
function p10k-on-pre-prompt() {
  # If the active conda environment is "base", hide `anaconda` prompt segment.
  # Otherwise show.
  if [[ $CONDA_DEFAULT_ENV == base ]]; then
    p10k display '*/anaconda'=hide
  else
    p10k display '*/anaconda'=show
  fi
}
```

Then restart zsh with `exec zsh`.

**Comment by Lunchb0ne** [comment]
> Try adding this to `~/.p10k.zsh`:
> 
> ```shell
> function p10k-on-pre-prompt() {
>   # If the active conda environment is "base", hide `anaconda` prompt segment.
>   # Otherwise show.
>   if [[ $CONDA_DEFAULT_ENV == base ]]; then
>     p10k display '*/anaconda'=hide
>   else
>     p10k display '*/anaconda'=show
>   fi
> }
> ```
> 
> Then restart zsh with `exec zsh`.

Ahh I see, it works perfectly. Thanks a lot for this!

**Comment by romkatv** [comment]
You are welcome.
