### ISSUE TITLE
How to show Kubernetes namespace using P9K_KUBECONTEXT_NAMESPACE

### ISSUE THREAD

**Issue by JCzz** [romkatv/powerlevel10k#1668]
New to powerlevel - how do make it show the namespace?

`vi ~/.oh-my-zsh/oh-my-zsh.sh`

Tried using `typeset -g P9K_KUBECONTEXT_NAMESPACE`

Copied from:
`  # - P9K_KUBECONTEXT_NAMESPACE  The current context's namespace. Corresponds to column NAMESPACE`

**Comment by romkatv** [comment]
1. Read these comments: https://github.com/romkatv/powerlevel10k/blob/4f3d2ffe7251a17aa10e00ed30d55f6fd9d65002/config/p10k-classic.zsh#L1253-L1297
2. Modify `POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION` in `~/.p10k.zsh` accordingly to your preference.
3. Restart zsh with `exec zsh`.

**Comment by JCzz** [comment]
Thanks @romkatv
