### ISSUE TITLE
~/.oh-my-zsh/oh-my-zsh.sh:source:177: the file or directory does not exist 

### ISSUE THREAD

**Issue by moshpirit** [romkatv/powerlevel10k#1669]
I'm getting this error (in Spanish) after trying install it :

`~/.oh-my-zsh/oh-my-zsh.sh:source:177: the file or directory does not exist: ~/.oh-my-zsh/themes/powerlevel10k.zsh-theme`

I installed the AUR package and also manually but I'm still getting the error.

**Comment by romkatv** [comment]
If you want to install powerlevel10k from AUR, do this:

```zsh
yay -S --noconfirm zsh-theme-powerlevel10k-git
echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
```

This will enable powerlevel10k.

If you are using ohmyzsh, make sure that ohmyzsh does not load another theme at the same time. To do this, remove `ZSH_THEME` from `.zshrc`.

**Comment by moshpirit** [comment]
> If you are using ohmyzsh, make sure that ohmyzsh does not load another theme at the same time. To do this, remove `ZSH_THEME` from `.zshrc.`

That solved the issue, thanks! :)
