### ISSUE TITLE
broken os_icon

### ISSUE THREAD

**Issue by Privth** [romkatv/powerlevel10k#167]
icon of archlinux have dot on the right side
![2019-08-13_13-52](https://user-images.githubusercontent.com/45431891/62939467-ab398980-bdd1-11e9-838a-561be1ee7a49.png)

**Comment by romkatv** [comment]
Please submit this issue to your font provider.

**Comment by Privth** [comment]
@romkatv on powerlevel9k works fine

**Comment by romkatv** [comment]
Please post all your `POWERLEVEL9K` parameters.
