### ISSUE TITLE
How can I make my prompt input bold?

### ISSUE THREAD

**Issue by embeddedpenguin** [romkatv/powerlevel10k#1671]
I've ctrl+f "FOREGROUND" through 1k lines and I can't seem to find an option to change the foreground of input. I've probably just missed it somewhere.

![image](https://user-images.githubusercontent.com/33668314/146447145-cec0a208-23f4-4f4f-b5d0-1e36a32ecf89.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

tl;dr: powerlevel10k doesn't affect the styling of the command line. If you want that to become bold, you can achieve it by the same means with powerlevel10k as without. This might do it (I haven't tried):

```zsh
zle_highlight=(default:bold)
```

If this doesn't work, you'll have to ask for help elsewhere. This isn't related to powerlevel10k.

**Comment by embeddedpenguin** [comment]
My mistake. Big fan of p10k. Thanks for the help!
