### ISSUE TITLE
Wrong OS Icon

### ISSUE THREAD

**Issue by ShabirK21** [romkatv/powerlevel10k#1679]
I'm using endeavour os and am getting the Linux penguin icon, how can i change it to the Endeavour OS icon?

**Comment by romkatv** [comment]
Endeavour OS is Linux, so the icon isn't wrong, just not as specific as for some other operating systems.

Your terminal can display only those glyphs that exist in the font used by the terminal. Does the font used by your terminal have a glyph for Endeavour OS?

**Comment by ShabirK21** [comment]
How can I check? I'm using the recommended MesloLGS NF font

**Comment by romkatv** [comment]
The recommended MesloLGS NF font does not have a glyph for Endeavour OS logo.

You can search for glyphs supported by MesloLGS NF here: https://www.nerdfonts.com/cheat-sheet. For example, try searching for "ubuntu", "vim" or "java".

If you find or create a font with a glyph for Endeavour OS logo, you can configure powerlevel10k to display it. Search for `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` in `~/.p10k.zsh`.

**Comment by ShabirK21** [comment]
Alright, will look into that. Thank you

**Comment by romkatv** [comment]
You are welcome.
