### ISSUE TITLE
[ERROR]: gitstatus failed to initialize. (Cygwin/Windows 10)

### ISSUE THREAD

**Issue by ic3guy** [romkatv/powerlevel10k#1681]
I've had a look at previous issues, but can't immediately see what the problem is. 

All of a sudden I'm starting to get "gitstatus failed to initialize". Only thing that changed was oh-my-zsh auto-updated. Could that be the issue? I don't see any errors immediately in the logs below.

I've tried reinstalling gitstatus manually, but that didn't help.

 Zsh log (/tmp/gitstatus.POWERLEVEL9K.1057388.1949.1640029419.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version && 'CYGWIN_NT-10.0-19042 version 3.2.0-340.x86_64 (corinna@calimero) (gcc version 9.3.0 20200312 (Fedora Cygwin 9.3.0-1) (GCC) ) 2021-03-29 08:42 UTC' == *Microsoft* ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /tmp/gitstatus.POWERLEVEL9K.1057388.1949.1640029419.1.lock
    +(anon):15> [[ 15 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ cygwin == cygwin* && -d /proc/self/fd ]]
    +(anon):32> local -i fd
    +(anon):35> [[ -r /proc/self/fd/16 ]]
    +(anon):36> sysopen -r -o cloexec -u resp_fd /proc/self/fd/16
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=2415'
    +(anon):46> [[ 17 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 17 ]]
    +(anon):57> sysread -s 20 -t 5.0000000000 -i 17 'pgid[$#pgid+1]'
    +(anon):55> ((  20 < 20  ))
    +(anon):59> [[ '                2415' == \ #<1-> ]]
    +(anon):60> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):62> sysopen -w -o cloexec -u req_fd -- /tmp/gitstatus.POWERLEVEL9K.1057388.1949.1640029419.1.fifo
    +(anon):63> [[ 16 == <1-> ]]
    +(anon):64> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):66> print -nru 16 -- $'}hello\C-_\C-^'
    +(anon):67> local expected=$'}hello\C-_0\C-^' actual
    +(anon):68> ((  1  ))
    +(anon):68> [[ ! -t 1 ]]
    +(anon):71> local -F deadline=1
    +(anon):73> true
    +(anon):74> [[ -t 17 ]]
    +(anon):75> sysread -s 1 -t 5.0000000000 -i 17 actual
    +(anon):75> return

  Daemon log (/tmp/gitstatus.POWERLEVEL9K.1057388.1949.1640029419.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=2415
    +_gitstatus_daemon_p9k_:4> [[ 2415 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /tmp/gitstatus.POWERLEVEL9K.1057388.1949.1640029419.1.lock
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:12> uname_sm='cygwin_nt-10.0 x86_64'
    +_gitstatus_daemon_p9k_:13> [[ 'cygwin_nt-10.0 x86_64' == [^\ ]##\ [^\ ]## ]]
    +_gitstatus_daemon_p9k_:14> local uname_s=cygwin_nt-10.0
    +_gitstatus_daemon_p9k_:15> local uname_m=x86_64
    +_gitstatus_daemon_p9k_:17> [[ '' == <1-> ]]
    +_gitstatus_daemon_p9k_:20> local cpus
    +_gitstatus_daemon_p9k_:21> ((  ! 0  ))
    +_gitstatus_daemon_p9k_:23> ((  ! 1  ))
    +_gitstatus_daemon_p9k_:23> cpus=+_gitstatus_daemon_p9k_:23> getconf _NPROCESSORS_ONLN
    +_gitstatus_daemon_p9k_:23> cpus=12
    +_gitstatus_daemon_p9k_:27> args+=( -t 24 )
    +_gitstatus_daemon_p9k_:30> mkfifo -- /tmp/gitstatus.POWERLEVEL9K.1057388.1949.1640029419.1.fifo
    +_gitstatus_daemon_p9k_:31> print -rnu 12 -- '                2415'
    +_gitstatus_daemon_p9k_:33> zf_rm -- /tmp/gitstatus.POWERLEVEL9K.1057388.1949.1640029419.1.fifo
    +_gitstatus_daemon_p9k_:35> local _gitstatus_zsh_daemon _gitstatus_zsh_version _gitstatus_zsh_downloaded
    +_gitstatus_daemon_p9k_:43> local gitstatus_plugin_dir_var=_gitstatus_plugin_dir_p9k_
    +_gitstatus_daemon_p9k_:44> local gitstatus_plugin_dir=/cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_daemon_p9k_:45> set -- -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_daemon_p9k_:47> [[ 1 == (|-|+)<1-> ]]
    +_gitstatus_daemon_p9k_:48> source /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install
    +/cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:469> [ -z '' ']'
    +/cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install:470> _gitstatus_install_main /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:1> [ -n 5.8 ']'
    +_gitstatus_install_main:2> emulate -L sh -o no_unset
    +_gitstatus_install_main:7> local argv1=/cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:8> shift
    +_gitstatus_install_main:10> local no_check='' no_install='' uname_s='' uname_m='' gitstatus_dir='' dl_status='' e=''
    +_gitstatus_install_main:11> local opt='' OPTARG='' OPTIND=1
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case d (h)
    +_gitstatus_install_main:14> case d (n)
    +_gitstatus_install_main:14> case d (f)
    +_gitstatus_install_main:14> case d (d)
    +_gitstatus_install_main:55> [ -n '' ']'
    +_gitstatus_install_main:59> [ -z /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus ']'
    +_gitstatus_install_main:63> gitstatus_dir=/cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case s (h)
    +_gitstatus_install_main:14> case s (n)
    +_gitstatus_install_main:14> case s (f)
    +_gitstatus_install_main:14> case s (d)
    +_gitstatus_install_main:14> case s (p)
    +_gitstatus_install_main:14> case s (e)
    +_gitstatus_install_main:14> case s (m)
    +_gitstatus_install_main:14> case s (s)
    +_gitstatus_install_main:99> [ -n '' ']'
    +_gitstatus_install_main:103> [ -z cygwin_nt-10.0 ']'
    +_gitstatus_install_main:107> uname_s=cygwin_nt-10.0
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case m (h)
    +_gitstatus_install_main:14> case m (n)
    +_gitstatus_install_main:14> case m (f)
    +_gitstatus_install_main:14> case m (d)
    +_gitstatus_install_main:14> case m (p)
    +_gitstatus_install_main:14> case m (e)
    +_gitstatus_install_main:14> case m (m)
    +_gitstatus_install_main:88> [ -n '' ']'
    +_gitstatus_install_main:92> [ -z x86_64 ']'
    +_gitstatus_install_main:96> uname_m=x86_64
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case p (h)
    +_gitstatus_install_main:14> case p (n)
    +_gitstatus_install_main:14> case p (f)
    +_gitstatus_install_main:14> case p (d)
    +_gitstatus_install_main:14> case p (p)
    +_gitstatus_install_main:66> [ -n '' ']'
    +_gitstatus_install_main:70> [ -z 'printf '\''\001'\'' >&12' ']'
    +_gitstatus_install_main:74> dl_status='printf '\''\001'\'' >&12'
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:14> case e (h)
    +_gitstatus_install_main:14> case e (n)
    +_gitstatus_install_main:14> case e (f)
    +_gitstatus_install_main:14> case e (d)
    +_gitstatus_install_main:14> case e (p)
    +_gitstatus_install_main:14> case e (e)
    +_gitstatus_install_main:77> [ -n '' ']'
    +_gitstatus_install_main:81> [ -z 12 ']'
    +_gitstatus_install_main:85> e=12
    +_gitstatus_install_main:13> getopts :s:m:d:p:e:fnh opt -d /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus -s cygwin_nt-10.0 -m x86_64 -p 'printf '\''\001'\'' >&12' -e 12 -- _gitstatus_set_daemon_p9k_
    +_gitstatus_install_main:115> shift 11
    +_gitstatus_install_main:117> : 12
    +_gitstatus_install_main:118> : /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus
    +_gitstatus_install_main:120> [ -n '' -a -n '' ']'
    +_gitstatus_install_main:125> [ -z cygwin_nt-10.0 ']'
    +_gitstatus_install_main:129> [ -z x86_64 ']'
    +_gitstatus_install_main:134> local daemon=''
    +_gitstatus_install_main:135> local cache_dir=/cygdrive/d/cygwin/.cache/gitstatus
    +_gitstatus_install_main:137> [ -z '' ']'
    +_gitstatus_install_main:138> [ -n '' ']'
    +_gitstatus_install_main:142> [ -z '' -a -e /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:145> [ -n '' ']'
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line=''
    +_gitstatus_install_main:163> [ -n '' ']'
    +_gitstatus_install_main:163> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.5.1"; sha256="fe132c412c460c2889d731012d280207fe2b4a3c94d077fb4f1c06ed5d319a42";'
    +_gitstatus_install_main:163> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.5.1"; sha256="fe132c412c460c2889d731012d280207fe2b4a3c94d077fb4f1c06ed5d319a42";' ']'
    +_gitstatus_install_main:165> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:166> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="i686";    file="gitstatusd-${uname_s}-${uname_m}";     version="v1.5.1"; sha256="fe132c412c460c2889d731012d280207fe2b4a3c94d077fb4f1c06ed5d319a42";'
    +_gitstatus_install_main:166> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:166> uname_m_glob=i686
    +_gitstatus_install_main:166> file=gitstatusd-cygwin_nt-10.0-x86_64
    +_gitstatus_install_main:166> version=v1.5.1
    +_gitstatus_install_main:166> sha256=fe132c412c460c2889d731012d280207fe2b4a3c94d077fb4f1c06ed5d319a42
    +_gitstatus_install_main:168> [ -z cygwin_nt-10.0 -o -z i686 -o -z gitstatusd-cygwin_nt-10.0-x86_64 -o -z v1.5.1 -o -z fe132c412c460c2889d731012d280207fe2b4a3c94d077fb4f1c06ed5d319a42 ']'
    +_gitstatus_install_main:177> case cygwin_nt-10.0 (cygwin_nt-10.0)
    +_gitstatus_install_main:181> case x86_64 (i686)
    +_gitstatus_install_main:181> case x86_64 (*)
    +_gitstatus_install_main:183> continue
    +_gitstatus_install_main:161> IFS='' +_gitstatus_install_main:161> read -r line
    +_gitstatus_install_main:162> line='uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.5.1"; sha256="c84cade0d6b86e04c27a6055f45851f6b46d6b88ba58772f7ca8ef4d295c800f";'
    +_gitstatus_install_main:163> [ -n 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.5.1"; sha256="c84cade0d6b86e04c27a6055f45851f6b46d6b88ba58772f7ca8ef4d295c800f";' ']'
    +_gitstatus_install_main:165> local uname_s_glob='' uname_m_glob='' file='' version='' sha256=''
    +_gitstatus_install_main:166> eval 'uname_s_glob="cygwin_nt-10.0"; uname_m_glob="x86_64";  file="gitstatusd-${uname_s}-${uname_m}";     version="v1.5.1"; sha256="c84cade0d6b86e04c27a6055f45851f6b46d6b88ba58772f7ca8ef4d295c800f";'
    +_gitstatus_install_main:166> uname_s_glob=cygwin_nt-10.0
    +_gitstatus_install_main:166> uname_m_glob=x86_64
    +_gitstatus_install_main:166> file=gitstatusd-cygwin_nt-10.0-x86_64
    +_gitstatus_install_main:166> version=v1.5.1
    +_gitstatus_install_main:166> sha256=c84cade0d6b86e04c27a6055f45851f6b46d6b88ba58772f7ca8ef4d295c800f
    +_gitstatus_install_main:168> [ -z cygwin_nt-10.0 -o -z x86_64 -o -z gitstatusd-cygwin_nt-10.0-x86_64 -o -z v1.5.1 -o -z c84cade0d6b86e04c27a6055f45851f6b46d6b88ba58772f7ca8ef4d295c800f ']'
    +_gitstatus_install_main:177> case cygwin_nt-10.0 (cygwin_nt-10.0)
    +_gitstatus_install_main:181> case x86_64 (x86_64)
    +_gitstatus_install_main:188> [ -z '' ']'
    +_gitstatus_install_main:190> local daemon=/cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-cygwin_nt-10.0-x86_64
    +_gitstatus_install_main:191> [ ! -e /cygdrive/d/cygwin/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-cygwin_nt-10.0-x86_64 ']'
    +_gitstatus_install_main:192> daemon=/cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64
    +_gitstatus_install_main:193> [ -e /cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64 ']'
    +_gitstatus_install_main:195> [ -n /cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64 ']'
    +_gitstatus_install_main:196> _gitstatus_install_daemon_found 0 _gitstatus_set_daemon_p9k_
    +_gitstatus_install_daemon_found:1> local installed=0
    +_gitstatus_install_daemon_found:2> shift
    +_gitstatus_install_daemon_found:3> [ 1 '=' 0 ']'
    +_gitstatus_install_daemon_found:3> _gitstatus_set_daemon_p9k_ /cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64 v1.5.1 0
    +_gitstatus_set_daemon_p9k_:1> _gitstatus_zsh_daemon=/cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64
    +_gitstatus_set_daemon_p9k_:2> _gitstatus_zsh_version=v1.5.1
    +_gitstatus_set_daemon_p9k_:3> _gitstatus_zsh_downloaded=0
    +_gitstatus_install_main:197> return
    +_gitstatus_daemon_p9k_:49> [[ -n /cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64 ]]
    +_gitstatus_daemon_p9k_:50> [[ -n v1.5.1 ]]
    +_gitstatus_daemon_p9k_:51> [[ 0 == [01] ]]
    +_gitstatus_daemon_p9k_:53> ((  UID == EUID  ))
    +_gitstatus_daemon_p9k_:54> local home=/cygdrive/d/cygwin
    +_gitstatus_daemon_p9k_:62> [[ -x /cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64 ]]
    +_gitstatus_daemon_p9k_:63> HOME=/cygdrive/d/cygwin /cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64 -G v1.5.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 24

  System information:

    zsh:      5.8
    uname -a: CYGWIN_NT-10.0 CA1-LAP106 3.2.0(0.340/5/3) 2021-03-29 08:42 x86_64 Cygwin

**Comment by romkatv** [comment]
No usual suspects in the log. Time to switch to WSL I guess. It's only a matter of time until I'll drop cygwin support anyway.

**Comment by ic3guy** [comment]
Thanks for taking a look. I'll try and fiddle with a few things. This is on a corp laptop, so I can only surmise that it might be permission issues or connection related. The same setup and versions of Cygwin+OhMyZsh+Powerlevel10k on my home Windows 10 machine works just fine.

**Comment by romkatv** [comment]
Try running the last command and see what happens:

```zsh
HOME=/cygdrive/d/cygwin /cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64 -G v1.5.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG
```

**Comment by ic3guy** [comment]
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[0]: "/cygdrive/d/cygwin/.cache/gitstatus/gitstatusd-cygwin_nt-10.0-x86_64"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[1]: "-G"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[2]: "v1.5.1"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[3]: "-s"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[4]: "-1"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[5]: "-u"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[6]: "-1"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[7]: "-d"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[8]: "-1"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[9]: "-c"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[10]: "-1"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[11]: "-m"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[12]: "-1"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[13]: "-v"
[2021-12-20 13:34:18 0000000800000010 INFO src/gitstatus.cc:186] argv[14]: "DEBUG"
[2021-12-20 13:34:18 0000000800000010 INFO src/thread_pool.cc:81] Spawning 1 thread(s)

**Comment by ic3guy** [comment]
out of nowhere, it starts working again. perhaps after I ran the above command manually? so weird.

**Comment by ic3guy** [comment]
I'd also add, that I hope you continue to support Cygwin. WSL is not a good option for me because I use Cygwin for the shell/ZSH. I develop in windows and my services/code run on windows machines.

**Comment by romkatv** [comment]
WSL1 is just a better (*much better*) Cygwin. It's meant for the use-cases you've described and it handles them well. Instead of `/cygdrive/d` you'll have `/mnt/d`, and when invoking a windows binary you'll need to supply its extension (that is, `notepad.exe` rather than just `notepad`). Other than that your whole workflow can stay unchanged.

**Comment by ic3guy** [comment]
Thanks for your input. I think my Cygwin install was broken. 

I wasn't aware that you could invoke from WSL using the .exe extension. I had tried a workflow using WSL2, but I didn't want to be compiling/building in Linux as my build servers are Windows.

I'm going to try out WSL1

**Comment by ic3guy** [comment]
I started getting these same issues with Cygwin, but I finally figured out the problem. It was my corporate antivirus McAfee. I had cygwin and cygdrive in a folder that was being scanned. Moving the install folder and cygdrive to a whitelisted (source code) folder that isn't monitored by McAfee fixed everything up. Made the shell/code completetion etc snappier too.

**Comment by romkatv** [comment]
Obligatory: https://www.youtube.com/watch?v=bKgf5PaBzyg
