### ISSUE TITLE
White Space before new line starts

### ISSUE THREAD

**Issue by Showvro** [romkatv/powerlevel10k#1684]
![Screenshot 2021-12-24 at 11 13 34 AM](https://user-images.githubusercontent.com/86624254/147319541-f90f4001-a72f-4790-8e27-6199f572dde3.JPG)
![Screenshot 2021-12-24 at 11 14 55 AM](https://user-images.githubusercontent.com/86624254/147319548-8a9669a0-1497-49ee-8805-57d5311b0427.JPG)

When I go on a new line, It shows a white space before the line start. How can I solve this?

**Comment by romkatv** [comment]
Please attach all relevant config files.

**Comment by Showvro** [comment]
I'm feeling proud to say that I solve the issue by adding 1 more white space.

But sir, can you give me the solution of the issue that why the color is being changed after sometimes later. Just like the image I attached. 


![147319548-8a9669a0-1497-49ee-8805-57d5311b0427](https://user-images.githubusercontent.com/86624254/147325640-21f2a70c-edb6-4d77-8811-12877f2bff81.jpg)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them
