### ISSUE TITLE
Remove OS_ICON from instant prompt

### ISSUE THREAD

**Issue by twang817** [romkatv/powerlevel10k#1685]
Similar to #1312

Except I don't mind a hack.  I comment out os_icon from my p10k.zsh after running the wizard.  Works great.

Except now with instant prompt, it's back.  Is there a similar hack/edit that I can make to the instant prompt (or regenerate the instant prompt with my current config after the wizard has been run) so that it's not there during the instant prompt?

Interestingly, I notice that it doesn't go away even after my prompt should have fully loaded.  This leads me to believe that the list of segments is actually controlled in the instant prompt, and only updated later as the full prompt loads.  The full prompt doesn't reload the list of segments.  Is that expected behavior?

**Comment by romkatv** [comment]
Please run the following command and post a screenshot. The screenshot should contain the command, its output and prompt.

```zsh
typeset -pm 'POWERLEVEL9K_(LEFT|RIGHT)_PROMPT_ELEMENTS'
```

**Comment by twang817** [comment]
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/766820/147392678-d55e5712-8d08-4bda-ac82-2cfd01295ddf.png">

```
❯ typeset -pm 'POWERLEVEL9K_(LEFT|RIGHT)_PROMPT_ELEMENTS'
typeset -a POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status command_execution_time background_jobs direnv asdf virtualenv anaconda pyenv goenv nodenv nvm nodeenv rbenv rvm fvm luaenv jenv plenv phpenv scalaenv haskell_stack kubecontext terraform aws aws_eb_env azure gcloud google_app_cred toolbox context nordvpn ranger nnn xplr vim_shell midnight_commander nix_shell todo timewarrior taskwarrior time newline )
typeset -a POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon dir vcs newline prompt_char )
```

**Comment by romkatv** [comment]
If you want to remove the apple logo from left prompt you need to:

1. Open `~/.p10k.zsh`.
2. Search for `os_icon`.
3. Remove or comment out the first hit.
4. Restart zsh with `exec zsh`.

**Comment by twang817** [comment]
I have done that already. If I remove the instant prompt, the os_icon is correctly hidden, but with the instant prompt, it comes back - presumably because I chose many icons during initial configuration in the wizard. 

I've stepped away from my desk. Let me fiddle with it more when I get home. Perhaps I've simply goofed something up.

**Comment by twang817** [comment]
Ok, after fiddling around with it, it looks like there's some refresh mechanism that detects changes and will recache the instant prompt.  All good!

**Comment by romkatv** [comment]
> I have done that already.

If you've done that already, you must have reverted your changes since then. The output you've posted earlier says that `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` still contains `os_icon`.

> All good!

👍
