### ISSUE TITLE
Certain directories display incorrectly

### ISSUE THREAD

**Issue by Logicer16** [romkatv/powerlevel10k#1687]
When setting `POWERLEVEL9K_DIR_HYPERLINK` to true, some directories display incorrectly.

Examples:
<img width="562" alt="Screen Shot 2021-12-27 at 11 32 32 am" src="https://user-images.githubusercontent.com/81077770/147425769-16d887a1-b162-4b04-95d5-e3a8ee1db8e4.png">
<img width="562" alt="Screen Shot 2021-12-27 at 11 30 04 am" src="https://user-images.githubusercontent.com/81077770/147425782-6e403a49-cdd8-489d-92b4-d1b41435ab8f.png">
<img width="562" alt="Screen Shot 2021-12-27 at 11 31 40 am" src="https://user-images.githubusercontent.com/81077770/147425797-5e34d528-707b-4690-baa7-3cccfaadca08.png">
<img width="562" alt="Screen Shot 2021-12-27 at 11 37 17 am" src="https://user-images.githubusercontent.com/81077770/147425802-9a3595ac-09ff-4f15-a9be-7baefe10bcd5.png">

**Comment by romkatv** [comment]
Thanks for reporting this issue. Fixed.
