### ISSUE TITLE
Git status indicators are not correct

### ISSUE THREAD

**Issue by aihaddad** [romkatv/powerlevel10k#1689]
Hi,

In one of my repos I have the following status indicators:
![image](https://user-images.githubusercontent.com/5328478/147451102-1b919375-23e3-4c4d-87dd-40ffdc9998f2.png)

Which I would understand as 1 stash, 1 staged file and 2 untracked. Problem is, only the stash number is correct; `git status` turns this up:
![image](https://user-images.githubusercontent.com/5328478/147451474-3c5de907-5b08-4057-9b3f-40257bfa912e.png)

It's just this one repo, and I've tried re-installing to no avail. It might be something with my repo itself, but I don't really know where to look and what to do

[gitstatus.txt](https://github.com/romkatv/powerlevel10k/files/7779449/gitstatus.txt)

**Comment by romkatv** [comment]
Please run the following command and then attach `~/gitstatus.txt` to this issue (you can drag-and-drop files into the edit box on github):

```zsh
(
  emulate -L zsh -o xtrace -o err_return
  typeset -m 'ZSH_VERSION|ZSH_PATCHLEVEL'
  zsh --version
  git --version
  git config -l
  git status --ignore-submodules=dirty
  git status --ignored
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    zsh -feic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
      gitstatus_query MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    rm -rf $tmp
  }
) &>~/gitstatus.txt
```

**Comment by aihaddad** [comment]
Edited the original issue, and to highlight, there are these values:
```bash
VCS_STATUS_NUM_UNSTAGED=1
VCS_STATUS_NUM_STAGED=0
...
VCS_STATUS_HAS_UNTRACKED=1
VCS_STATUS_COMMITS_AHEAD=0
VCS_STATUS_COMMITS_BEHIND=0
...
VCS_STATUS_NUM_STAGED_NEW=0
VCS_STATUS_NUM_UNTRACKED=2
VCS_STATUS_RESULT=ok-sync
VCS_STATUS_STASHES=1
VCS_STATUS_INDEX_SIZE=2488
VCS_STATUS_HAS_CONFLICTED=0
VCS_STATUS_PUSH_REMOTE_URL=''
VCS_STATUS_HAS_UNSTAGED=1
```

**Comment by romkatv** [comment]
`ConfigUtils.test.js` is spelled like that (with an upper case) on your local filesystem but it's `configUtils.js` in the git index. If you delete your local clone and run `git clone` again, this should fix it.

Ideally I should fix this bug in gitstatus but it's unlikely to happen soon.

**Comment by desires19** [comment]
![image](https://user-images.githubusercontent.com/45759525/147473203-0c59df6d-92ec-4793-aa95-b68322eaedbd.png)
I have met the same question, I hope it can be solve early!!!
Thanks

**Comment by romkatv** [comment]
@desires19 Please open a separate issue and describe what the problem is.

**Comment by romkatv** [comment]
> If you delete your local clone and run `git clone` again, this should fix it.

You can also rewrite all files in worktree without re-cloning. This should do it (needs to be run when the current directory is the root of the repo):

```zsh
git ls-files | xargs rm && git reset --hard dev-int
```

You might need to `exec zsh` after this.

Let me know if this fixes the issue.

**Comment by aihaddad** [comment]
> > If you delete your local clone and run `git clone` again, this should fix it.
> 
> You can also rewrite all files in worktree without re-cloning. This should do it (needs to be run when the current directory is the root of the repo):
> 
> ```shell
> git ls-files | xargs rm && git reset --hard dev-int
> ```
> 
> You might need to `exec zsh` after this.
> 
> Let me know if this fixes the issue.

This one didn't work, and I can't really delet my local copy. I have lots of local branches I'm keeping as backups and remote doesn't need them

**Comment by romkatv** [comment]
Got it. I guess pick your poison. As I mentioned earlier, it's very unlikely I'll fix this issue any time soon. Very few people use case-insensitive filesystems (it's awful btw; try to switch to a decent filesystem if you can) and rename files by only changing their case.
