### ISSUE TITLE
How to Adding a new prompt element

### ISSUE THREAD

**Issue by securisec** [romkatv/powerlevel10k#169]
Typically I like to add a prompt element for my powerlevel9k theme to show if i am in a directory that has a `.envrc` file in it. I am trying to replicate the same behavior in powerlevel10k, but am not getting the same output. The code i am using is:

- `p10k.zsh`
```
prompt_direnv(){
  if [ ! -z "$DIRENV_DIR" ]; then
    _p9k_prompt_segment "$0" "$2" "black" "green" "" 'DIRENV_ICON'
  fi
}
```

- `icons.zsh`
```
DIRENV_ICON '\uFA98'
``` 
under all the icon configuration

- `~/.p10k.zsh`
```
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(direnv)
```

A silimar configuration to this works for me in powerlevel9k, but cant seem to get any output in p10k... any suggestions on how to show an icon in p10k when a `.envrc` file is present?

**Comment by romkatv** [comment]
`_p9k_prompt_segment` is an internal API. Don't use it.

Open `~/.p10k.zsh` and search for "prompt_example". Does it help?

**Comment by securisec** [comment]
Ah yes, that was perfect! 

```
function prompt_direnv(){
    if [ ! -z "$DIRENV_DIR" ]; then
      p10k segment -f 208 -i '🔥' -t ''
    fi
  }
```

Thanks!

**Comment by romkatv** [comment]
👍

**Comment by romkatv** [comment]
(You can remote `-t ''` argument. Empty text is the default.)

**Comment by securisec** [comment]
even better!

**Comment by securisec** [comment]
There is one slight odd behavior though.. When i am in a dir with either virtualenv or something like that, it doesnt show the indicator sometimes until i press enter. is this as designed?

**Comment by romkatv** [comment]
If `DIRENV_DIR` is set in a `precmd` hook that was registered after p10k, you'll can get this behavior. Try changing your `prompt_direnv` as follows:

```zsh
function prompt_direnv() {
  p10k segment -f 208 -i '🔥' -c '$DIRENV_DIR'
}
```

(By the way, I don't think this icon can be rendered in different colors, so you can remove `-f 208`.)

From `p10k help segment`:

```
  -c        condition; if empty after parameter expansion and process substitution, the
            segment is hidden;
```

So we instruct `p10k` to show 🔥 only when `$DIRENV_DIR` is non-empty.

**Comment by securisec** [comment]
This is perfect! Thanks for the tips!

**Comment by doronbehar** [comment]
Hey! Just came around this issue when searching for a way to define my own segment and the explanations and examples here were very useful. Perhaps we should add these to the WiKi? I would have added it my self already but I think it's disabled.

**Comment by doronbehar** [comment]
Thanks for replying so quickly! I read the comments in my `~/.p10k.zsh` and understood most of them. I also use direnv and I added the exact same prompt element as @securisec did. I intend to write a bit more complex prompt element that will indicate how many new emails I've got in my maildirs and I wanted to share it somehow.

Somewhat related to documentation, it wasn't completely obvious right from the start that `~/.p10k` has so many useful comments that will help me configure it. If I hadn't encountered this issue, I wouldn't have searched for `prompt_example`. Besides that, I had to find other issues related to `vi_mode` that led me into adding it to my config. This wasn't trivial as well to figure out - even the issues themselves haven't indicated I should just add the string `vi_mode` in e.g `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` - I mean, you know what I mean, it could be `vi_mode` / `vimode` etc. how am I supposed to guess without `git grep vi | grep mode` in the repo?

p10k is great but it's a shame it's only configuration documentation is available with `git grep` inside the repo and old issues...

**Comment by doronbehar** [comment]
Note that I'm not a migrator from p9k and I don't even know what that is so if it has documentation, it might be useful to link to it somewhere.

Here are issues that helped me configure vi-mode indication:

- https://github.com/romkatv/powerlevel10k/issues/15
- https://github.com/romkatv/powerlevel10k/issues/64
- https://github.com/romkatv/powerlevel10k/issues/232

**Comment by romkatv** [comment]
@securisec @doronbehar 

Heads up: I've implemented `direnv` prompt segment in Powerlevel10k. Since it has the same name as your user-defined segment, it may or may not override it. I recommend that you do the following:

1. Update powerlevel10k.
2. Remove `prompt_direnv` function that you had earlier.
3. Restart zsh and verify that you still see `direnv` segment but now it has a different icon (▼) and perhaps color (it's now yellow).
4. Optional: Define necessary style-related parameters to get the look you want:
```zsh
typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=4
typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=7
typeset -g POWERLEVEL9K_DIRENV_VISUAL_IDENTIFIER_EXPANSION='🔥'
```

Note: `p10k configure` includes `direnv` in the list of enabled segments by default.

**Comment by securisec** [comment]
Great! This is awesome! Thanks for building this in!

**Comment by Ameausoone** [comment]
👌 https://github.com/romkatv/powerlevel10k/blob/cf67cad46557d57d5d2399e6d893c317126e037c/config/p10k-classic.zsh#L1577
