### ISSUE TITLE
Why do I see size information when I resize the terminal window?

### ISSUE THREAD

**Issue by s-aleck** [romkatv/powerlevel10k#1690]
Is there a way to disable that notification?

I customized my terminal using the command `p10k configure` and set font manually.

**Comment by romkatv** [comment]
What is "size information"?

**Comment by s-aleck** [comment]
![image](https://user-images.githubusercontent.com/91084202/147463872-d7aa6275-3ab4-46a0-8fa2-08ec5dc1da90.png)

It appears in the middle of the terminal window and disappears after one or two seconds.

**Comment by romkatv** [comment]
Your terminal does that. I'm guessing it's Konsole. [Powerlevel10k only sets prompt](https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect).
