### ISSUE TITLE
Checkmark not green 

### ISSUE THREAD

**Issue by nickvanwegen** [romkatv/powerlevel10k#1691]
Hi there!

I have been using p10k for a while now really happy with it. 

Tho i had reinstall my os and now I cant get the status checkmark to become green. 
![image](https://user-images.githubusercontent.com/47427309/147495101-a1bb3c16-5958-45b5-999e-61e99ab9b1c4.png)

Can you maybe help me figure it out why? 

Thanks!

**Comment by romkatv** [comment]
Do you mean the checkmark on the right? Can you run two commands back -- `true` and `false` and post a screenshot?

**Comment by nickvanwegen** [comment]
Yes thats the one i mean. It used to be green before :/

![image](https://user-images.githubusercontent.com/47427309/147495973-46ab431f-4de2-4320-9d94-fe301967e381.png)

**Comment by romkatv** [comment]
How that checkmark looks depends on your font. You've changed your font, so it looks differently now. Try the recommended font: https://github.com/romkatv/powerlevel10k/blob/master/font.md

**Comment by nickvanwegen** [comment]
this indeed fixed it thanks alot for the quick reply!
