### ISSUE TITLE
Terminal is not showing directory path properly

### ISSUE THREAD

**Issue by mrhrifat** [romkatv/powerlevel10k#1692]
After install & configure `powerlevel10k` theme. Whenever I open a directory with terminal. The terminal not showing my `directory` path properly, like
```diff
+/media/username/Software/Coding & Project/Git Hub/my-repository
-/media/u/S/C/Git Hub/my-repository
```
- Here 1st line I am working on
- 2nd line the terminal is showing

**Note**: I am using 
- Ubuntu 20.04
- ZSH
- Rainbow style

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#current-directory-that-just-works

You can configure this by editing `~/.p10k.zsh`. Look for this line and below: https://github.com/romkatv/powerlevel10k/blob/4f3d2ffe7251a17aa10e00ed30d55f6fd9d65002/config/p10k-lean.zsh#L256

Also see https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard

**Comment by mrhrifat** [comment]
I try to fix by following your all suggestions
- I make changes [Line 256](https://github.com/romkatv/powerlevel10k/blob/4f3d2ffe7251a17aa10e00ed30d55f6fd9d65002/config/p10k-lean.zsh#L256) option's
```
 typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
```
`80` value to `200/500/50%` but it's not working
- I change the `Terminal Color Palette` to `Tango Dark/Solarized Dark/blue` .  Not it's on `Tango Dark`

#### But I can't solve this.
**Note:**  Whenever for first time I open the same path of directory on VS Code it show me correctly. But after do any commit it react like default terminal.

**Comment by romkatv** [comment]
If you want as little shortening as possible, you need to set these parameters:

```zsh
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0
```

> * I change the `Terminal Color Palette` to `Tango Dark/Solarized Dark/blue` .  Not it's on `Tango Dark`

Why is this relevant?

> Whenever for first time I open the same path of directory on VS Code it show me correctly. But after do any commit it react like default terminal.

I don't understand this. If it's relevant, please rephrase.

**Comment by mrhrifat** [comment]
I am sorry for I unable to make my problem clear to you. But thanks for your nice response to me. After


> ```shell
> typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=
> typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0
> typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0
> ```
do this changes now I get rid from my problem about to 99%. I glad to have full path of directory 
```diff
+/media/username/Google/Chrome Web Browser/Git Hub/A
+/media/username/Google/Chrome Web Browser/Git Hub/A
```
But if I make `A` normal directory to `git directory` by `git init`. Then I am having a problem of the above path like
```diff
- +/media/u/G/C/Git Hub/A master
```
But if I revert it to normal by `rm -rf .git`. The path also revert to
```diff
+/media/username/Google/Chrome Web Browser/Git Hub/A
```

- How to fix it

**Comment by romkatv** [comment]
If your current directory is so long that it doesn't fit on the prompt line, it gets shortened. You can disable it but you really shouldn't. In fact you shouldn't have made previous changes either. Instead, please read https://github.com/romkatv/powerlevel10k#current-directory-that-just-works. Also read https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard. The gist of the latter is that it's a really good idea for you to run `p10k configure` and to choose a two-line prompt (preferably with transient prompt).

**Comment by mrhrifat** [comment]
I got it. Thanks. I won't do any changes now. But please let me know for the last time, with the changes of this. 

> ```shell
> typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=
> typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0
> typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0
> ```
Will it make any major trouble for my system or not.

**Comment by romkatv** [comment]
These parameters do exactly what the comments say.

**Comment by mrhrifat** [comment]
Ok. thank you so much.

**Comment by romkatv** [comment]
You are welcome.
