### ISSUE TITLE
Layout will be destroyed when zooming the screen

### ISSUE THREAD

**Issue by huangcs427** [romkatv/powerlevel10k#1693]
**As shown in the figure below：**
![image](https://user-images.githubusercontent.com/31842636/147621182-146c3a6f-5d5d-409c-8f25-26f61ecfb815.png)
![image](https://user-images.githubusercontent.com/31842636/147621491-49795a5d-5a04-4957-990d-a082010cc682.png)

**System version:** 
Windows subsystem For Linux

**Terminal:** 
Tabby, Windows Terminal

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by huangcs427** [comment]
> https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

Sorry, I didn't really look at readme.md.
