### ISSUE TITLE
wrong OS icon on 64-bit raspbian

### ISSUE THREAD

**Issue by darkBuddha** [romkatv/powerlevel10k#1695]
On standard 32-bit raspbian (arm7l) it shows the correct berry icon. On aarch64 raspbian (same version) it shows a debian icon instead.

**Comment by romkatv** [comment]
What is the output of `cat /etc/os-release` on aarch64 raspbian?

**Comment by darkBuddha** [comment]
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

It could be detected by `uname -a`, which yields:
`Linux raspberrypi 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux
`

**Comment by romkatv** [comment]
Either your OS is in fact Debian, or Raspbian incorrectly reports itself being Debian. In the latter case you might want to report this to Raspbian.

**Comment by darkBuddha** [comment]
On 32bit raspbian, it reports:
`PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

I will forward to Raspbian.
