### ISSUE TITLE
distrobox container type/name in prompt by default?

### ISSUE THREAD

**Issue by erwin** [romkatv/powerlevel10k#1696]
If you haven't had a chance to experiment with [distrobox](https://github.com/89luca89/distrobox), I would recommend taking it for a spin...

> Distrobox is a wrapper around podman/docker that conveniently shares your `/home`, `/proc`, and such, making the other distro completely blend in with your main environment, while you spin up any distro you want.
>
> I think the combination of [quickemu](https://github.com/quickemu-project/quickemu) for VMs and [distrobox](https://github.com/89luca89/distrobox) for containers make Linux in 2022 the best environment that's ever existed for running target development environments....

Anyway, you've had enough of my rant... If you want to put Distrobox into your RPROMPT, it's easy enough thanks to [this previous issue](https://github.com/romkatv/powerlevel10k/issues/1560) about [toolbox](https://github.com/containers/toolbox).

For example, after the "battery:" section of your `~/.p10k.zsh` add:

```zsh
  ################################[ my_distrobox: distrobox identifier ]###########################
  typeset -g POWERLEVEL9K_MY_DISTROBOX_ENABLED_FOREGROUND=black
  typeset -g POWERLEVEL9K_MY_DISTROBOX_ENABLED_BACKGROUND=yellow
  typeset -g POWERLEVEL9K_MY_DISTROBOX_ENABLED_VISUAL_IDENTIFIER_EXPANSION=''
#  typeset -g POWERLEVEL9K_MY_DISTROBOX_ENABLED_CONTENT_EXPANSION=

  typeset -g POWERLEVEL9K_MY_DISTROBOX_DISABLED_FOREGROUND=
  typeset -g POWERLEVEL9K_MY_DISTROBOX_DISABLED_BACKGROUND=
  typeset -g POWERLEVEL9K_MY_DISTROBOX_DISABLED_VISUAL_IDENTIFIER_EXPANSION=''
  typeset -g POWERLEVEL9K_MY_DISTROBOX_DISABLED_CONTENT_EXPANSION=''

  function prompt_my_distrobox {
    if [ -f "/run/.containerenv" ]; then
      local state=ENABLED
      local name=$(grep -oP '(?<=\bname=")[^";]+' /run/.containerenv)
    else
      local state=DISABLED
      local name="N/A"
    fi
    p10k segment -s $state -i $'\ue20f' -f blue -t "$name "
  }
```

Last, add this to your `typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(` array:

```
my_distrobox # Local support for Distrobox
```

Last, you might also uncomment the `os_icon` in LEFT_PROMPT_ELEMENTS` so that the distrobox distro shows up as your OS icon...

```
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    prompt_char             # prompt symbol
  )
```

Enjoy.

**Comment by romkatv** [comment]
Thanks!

I've updated `toolbox` prompt segment to recognize distrobox containers (unlike your implementation it also works when using distrobox with docker; it's also much faster).

**Comment by erwin** [comment]
The update is perfect! Thank you!!!

**Comment by romkatv** [comment]
Thanks for verifying.
