### ISSUE TITLE
Local mac setup causes gitstatus plugin issues

### ISSUE THREAD

**Issue by piyat** [romkatv/powerlevel10k#1697]
Hey - first off, thanks for this awesome project! I'm raising this on the off chance that there's some configuration I can change. It's not an issue with P10K, but if I'm right about the cause, it's not something I can change either.

I've been asked by IT dept at work to use a new Mac. I installed p10k from scratch and annoyingly gitstatus doesn't work in a certain context.

I found this old issue and followed the instructions in [this comment](https://github.com/romkatv/powerlevel10k/issues/1428#issuecomment-851904085) to look for errors. I didn't find errors but have a suspicion that the plugin doesn't work correctly because my username has a backslash in it 😞.

Username is in the format: `<domain>\<username>`
e.g. `foo\bar`
So the path to a git repository would be: `/Users/foo\bar/repo1`.

In the example below, I can see that the backslash is missing and in the first log line - in the path - the next folder (the git repo) is missing.. I assume this causes the issue.

When I clone a repository in my home dir, gitstatus doesn't display:

<img width="612" alt=" 2022-01-02 at 12 49 17" src="https://user-images.githubusercontent.com/33325022/147876340-931a5324-19cf-46bc-818c-dba705517b6e.png">

and log shows:

> [2022-01-02 12:46:39 000000011647d600 INFO src/gitstatus.cc:204] Successfully processed request: "1641127599.3070659637 _p9k_vcs_resume 0" for "/Users/MYDOMAINmyusername" [no-diff]
> [2022-01-02 12:49:06 000000011647d600 INFO src/gitstatus.cc:201] Processing request: "1641127746.5165300369 _p9k_vcs_resume 0" for "/Users/MYDOMAINmyusername/powerlevel10k" [no-diff]
> [2022-01-02 12:49:06 000000011647d600 INFO src/response.cc:69] Replying without git status

When I clone a repository outside of my home dir, gitstatus displays:

<img width="622" alt=" 2022-01-02 at 12 49 46" src="https://user-images.githubusercontent.com/33325022/147876350-07bf4dc7-30b0-4f5b-a0ba-6c6578fc9be1.png">

and log shows:

> [2022-01-02 12:49:42 000000011647d600 INFO src/gitstatus.cc:204] Successfully processed request: "1641127782.7479538918 _p9k_vcs_resume 0" for "/private/tmp/powerlevel10k" [no-diff]
> [2022-01-02 12:49:54 000000011647d600 INFO src/gitstatus.cc:201] Processing request: "1641127794.4639019966 _p9k_vcs_resume 1" for "/private/tmp/powerlevel10k"
> [2022-01-02 12:49:54 000000011647d600 INFO src/repo.cc:387] Splitting 86 object(s) into 1 shard(s)
> [2022-01-02 12:49:54 000000011647d600 INFO src/repo.cc:183] Index and HEAD unchanged; staged = 0, conflicted = 0

If I'm right about the cause, is there anything I can do to fix it? If you need more info, or what I've described wouldn't cause this issue then I'd appreciate some troubleshooting advice.

Thanks!

**Comment by romkatv** [comment]
Thanks for the bug report. Fixed.

**Comment by piyat** [comment]
Thank you @romkatv. That was seriously fast 👍 

Fix confirmed!

![ 2022-01-02 at 22 12 00](https://user-images.githubusercontent.com/33325022/147890725-30e28255-2474-47a0-98cd-257165895083.png)

**Comment by romkatv** [comment]
Thanks for verifying.
