### ISSUE TITLE
"dir" on right is truncated more aggressively than when it's on the left

### ISSUE THREAD

**Issue by ddribin** [romkatv/powerlevel10k#1698]
Hello,

When I put `dir` on the right (in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`) it gets truncated more aggressively than when it's on the left (in `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`). This is on macOS Big Sur (11.6.1) running `zsh` version `5.8` in iTerm2 version `3.4.12`. Is there any way to make `dir` truncate less aggressively on the right like it does on the left?

Here's a screenshot of what it looks like when typing with `dir` on the left:

    > cd ~/alpha/beta/gamma/delta/epsilon

<img width="762" alt="dir_in_left" src="https://user-images.githubusercontent.com/20428/147884729-1c74d8b3-8307-4d40-aeee-bfa9ac555934.png">

And with `dir` on the right:

<img width="762" alt="dir_in_right" src="https://user-images.githubusercontent.com/20428/147884739-6e9616f7-c232-42bc-9c85-cc4845b28069.png">

**Comment by romkatv** [comment]
Correct, it's always fully truncated on the right. Also, if you put more than one `dir` on the left on the same line, all but the first will be fully truncated. In theory it's possible to fix this but in practice it's quite difficult. I don't plan on doing that.

One option you have is to disable truncation altogether. My advice is to keep `dir` on the left and use a two-line prompt. Since you've enabled transient prompt, a two-line prompt is a no-brainer. It gives you massive advantages and no disadvantages. I mean this:

```zsh
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir newline prompt_char)
```

**Comment by ddribin** [comment]
Thanks for the response! I briefly tried a two-line prompt, but wasn't a fan, as it felt like the previous commands "jumped" up as I typed them. I'll give it another shot, though.

I am curious why it's difficult to fix. Before I tried P10K, I had a right prompt with a truncated path setup manually:

<img width="682" alt="Screen Shot 2022-01-03 at 9 31 40 AM" src="https://user-images.githubusercontent.com/20428/147949139-fc4ba433-5f3e-4428-bc2e-81433790816d.png">

Granted, my truncation was not as sophisticated as P10K, which is part of the appeal. ;-)

**Comment by romkatv** [comment]
Currently your commands jump left, which sends worse.  Closing as I don't intend to do anything here.

**Comment by ddribin** [comment]
Not sure what you mean by "jump left". I've put all the variable width stuff on the right, so the left prompt width is constant and does not move around.

Would you be willing to point me where in the code this truncation occurs? I'm motivated to try and fix it myself and submit a PR. I've had the current directory on the right for many (15?) years now and old habits are hard to break.

**Comment by romkatv** [comment]
> Not sure what you mean by "jump left". I've put all the variable width stuff on the right, so the left prompt width is constant and does not move around.

You are right, I forgot that you put everything on the right.

I just realized that by default there is indeed more command line jumping than necessary. I set this parameter in my own zshrc:

```zsh
POSTEDIT=$'\n\n\e[2A'
```

This is for a 3-line prompt: 2 proper lines and 1 empty line before prompt. Without an empty line it would be `POSTEDIT=$'\n\e[A'`.

You can try running `sleep 1` with and without this parameter to see the difference. Make sure your prompt is at the bottom of the screen.

> Would you be willing to point me where in the code this truncation occurs? I'm motivated to try and fix it myself and submit a PR. I've had the current directory on the right for many (15?) years now and old habits are hard to break.

The source code for `dir` is in `prompt_dir` function in https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh. There is extra code related to `dir` in `_p9k_set_prompt` (search for `_p9k__dir`).

I don't recommend trying to fix this. It's difficult.

**Comment by ddribin** [comment]
Thanks again for the reply. I will give that `POSTEDIT` setting a shot. What does the `\e[A` escape sequence do?

**Comment by romkatv** [comment]
It moves the cursor up. Once you try it with `sleep 1`, you'll immediately see how that works.
