### ISSUE TITLE
Prompt hangs upon exit of virtualenv

### ISSUE THREAD

**Issue by iboyperson** [romkatv/powerlevel10k#17]
My specific case is with Pipenv but whenever I exit the virtualenv it hangs and I have to press enter an aditional time to get the prompt to display once more.

**Comment by romkatv** [comment]
Thanks for the report. I'll need a bit more info to debug this.

1. What do you mean when you say prompt hangs? What expected thing it doesn't do when you exit virtualenv?
2. Does it work with Powerlevel9k with the same config?
3. Please post all POWERLEVEL9K settings you set in your config.

**Comment by iboyperson** [comment]
1. When I say the prompt hangs I mean that upon typing `exit` in the virtual environment the shell appears to hang requiring me to press enter and additional time (after pressing to run exit) to get the prompt to display. Hopefully the below image better explains the issue:
![image](https://user-images.githubusercontent.com/10000914/54421633-10c20680-46ca-11e9-82e1-0f47621a95e3.png)

2. The issue does not persist on powerlevel9k with the same config.

3. Below are my settings. They are loaded by being put into a function called before the plugin is loaded as seen here: `zplugin ice lucid atinit"_config_powerline"; zplugin light romkatv/powerlevel10k`

Settings:
```
    POWERLEVEL9K_MODE=nerdfont-complete
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs virtualenv)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)

    POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
    POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
    POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=''
    POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
    POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
    POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS=''

    # user
    POWERLEVEL9K_USER_DEFAULT_BACKGROUND='none'
    POWERLEVEL9K_USER_SUDO_BACKGROUND='none'
    POWERLEVEL9K_USER_ROOT_BACKGROUND='none'

    # dir
    POWERLEVEL9K_SHORTEN_DELIMITER=''
    POWERLEVEL9K_SHORTEN_DIR_LENGTH=7
    # POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_first_and_last'

    POWERLEVEL9K_ETC_ICON=''
    POWERLEVEL9K_FOLDER_ICON=''
    POWERLEVEL9K_HOME_ICON=''
    POWERLEVEL9K_HOME_SUB_ICON=''

    POWERLEVEL9K_DIR_ETC_BACKGROUND='none'
    POWERLEVEL9K_DIR_ETC_FOREGROUND='005'
    POWERLEVEL9K_DIR_HOME_BACKGROUND='none'
    POWERLEVEL9K_DIR_HOME_FOREGROUND='004'
    POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='none'
    POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='005'
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='none'
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='004'

    # vcs
    POWERLEVEL9K_VCS_GIT_ICON=''
    POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
    POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=''
    POWERLEVEL9K_VCS_GIT_GITLAB_ICON=''
    POWERLEVEL9K_VCS_BRANCH_ICON=''
    POWERLEVEL9K_VCS_UNTRACKED_ICON='%F{009}%B?%b%f'
    POWERLEVEL9K_VCS_UNSTAGED_ICON='%F{011}%B!%b%f'
    POWERLEVEL9K_VCS_STAGED_ICON='%F{010}%B+%b%f'
    POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='%F{011}%B>%b%f'
    POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='%F{011}%B<%b%f'
    POWERLEVEL9K_VCS_STASH_ICON='%F{011}%B*%b%f'

    POWERLEVEL9K_SHOW_CHANGESET=true
    POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

    POWERLEVEL9K_VCS_CLEAN_BACKGROUND='none'
    POWERLEVEL9K_VCS_CLEAN_FOREGROUND='076'
    POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='none'
    POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='005'
    POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='none'
    POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='003'

    # virtualenv
    POWERLEVEL9K_PYTHON_ICON=''
    POWERLEVEL9K_VIRTUALENV_BACKGROUND='none'
    POWERLEVEL9K_VIRTUALENV_FOREGROUND='green'

    # status
    POWERLEVEL9K_CARRIAGE_RETURN_ICON=''
    POWERLEVEL9K_STATUS_OK=false
    POWERLEVEL9K_STATUS_OK_BACKGROUND='none'
    POWERLEVEL9K_STATUS_ERROR_BACKGROUND='none'
    POWERLEVEL9K_STATUS_OK_FOREGROUND='green'
    POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'

    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?.%F{012}❯%f.%F{009}❯%f) "
    PS2='$POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX'
    PS3='$POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX'
```

**Comment by romkatv** [comment]
Thank you for the detailed answer and the config. That's a beautiful theme you've got.

I tried to reproduce the hanging after exiting virtualenv but couldn't. I've never used virtualenv and I couldn't deduce from the screenshot all the relevant context. Here's what I did:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  apt update && apt install -y zsh git python3 python3-pip python3-venv
  git clone https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  cat >~/.zshrc <<END
    POWERLEVEL9K_MODE=nerdfont-complete
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs virtualenv)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)
    POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
    POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=" "
    POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=""
    POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
    POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=" "
    POWERLEVEL9K_WHITESPACE_BETWEEN_RIGHT_SEGMENTS=""
    POWERLEVEL9K_USER_DEFAULT_BACKGROUND=none
    POWERLEVEL9K_USER_SUDO_BACKGROUND=none
    POWERLEVEL9K_USER_ROOT_BACKGROUND=none
    # POWERLEVEL9K_SHORTEN_DELIMITER=?  # I don't know what icon you use here
    POWERLEVEL9K_SHORTEN_DIR_LENGTH=7
    POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_first_and_last
    POWERLEVEL9K_ETC_ICON=""
    POWERLEVEL9K_FOLDER_ICON=""
    POWERLEVEL9K_HOME_ICON=""
    POWERLEVEL9K_HOME_SUB_ICON=""
    POWERLEVEL9K_DIR_ETC_BACKGROUND=none
    POWERLEVEL9K_DIR_ETC_FOREGROUND=005
    POWERLEVEL9K_DIR_HOME_BACKGROUND=none
    POWERLEVEL9K_DIR_HOME_FOREGROUND=004
    POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=none
    POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=005
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=none
    POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=004
    POWERLEVEL9K_VCS_GIT_ICON=""
    POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
    POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=""
    POWERLEVEL9K_VCS_GIT_GITLAB_ICON=""
    POWERLEVEL9K_VCS_BRANCH_ICON=""
    POWERLEVEL9K_VCS_UNTRACKED_ICON="%F{009}%B?%b%f"
    POWERLEVEL9K_VCS_UNSTAGED_ICON="%F{011}%B!%b%f"
    POWERLEVEL9K_VCS_STAGED_ICON="%F{010}%B+%b%f"
    POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON="%F{011}%B>%b%f"
    POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON="%F{011}%B<%b%f"
    POWERLEVEL9K_VCS_STASH_ICON="%F{011}%B*%b%f"
    POWERLEVEL9K_SHOW_CHANGESET=true
    POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
    POWERLEVEL9K_VCS_CLEAN_BACKGROUND=none
    POWERLEVEL9K_VCS_CLEAN_FOREGROUND=076
    POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=none
    POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=005
    POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=none
    POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=003
    POWERLEVEL9K_PYTHON_ICON=""
    POWERLEVEL9K_VIRTUALENV_BACKGROUND=none
    POWERLEVEL9K_VIRTUALENV_FOREGROUND=green
    POWERLEVEL9K_CARRIAGE_RETURN_ICON=""
    POWERLEVEL9K_STATUS_OK=false
    POWERLEVEL9K_STATUS_OK_BACKGROUND=none
    POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none
    POWERLEVEL9K_STATUS_OK_FOREGROUND=green
    POWERLEVEL9K_STATUS_ERROR_FOREGROUND=red
    POWERLEVEL9K_PROMPT_ON_NEWLINE=true
    POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
    POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?.%F{012}❯%f.%F{009}❯%f) "
    PS2=\$POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX
    PS3=\$POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX
    source ~/powerlevel10k/powerlevel10k.zsh-theme
END
  mkdir ~/environments
  cd ~/environments
  python3 -m venv project_env
  zsh -i'
```

This command installs virtualenv and powerlevel10k with your config on a fresh Ubuntu. I followed [this guide](https://linoxide.com/linux-how-to/setup-python-virtual-environment-ubuntu/) for installing virtualenv.

Once the prompt appeared, I typed `source project_env/bin/activate` and hit `[ENTER]`. Segment `project_env` appeared in the prompt. I then typed `deactivate` and hit `[ENTER]`. A new prompt appeared right away without my having to hit `[ENTER]` again, but this time without `project_env` in it. I suppose this is the expected behavior? Here's a screenshot:

![virtualenv](https://user-images.githubusercontent.com/1282067/54424534-61aa1d00-4713-11e9-824c-c18b5b9401f9.png)

Note that I used `deactivate` instead of `exit`. This is because `exit` exits from zsh. I suspect I'm missing something here.

I also see in your screenshot that you had some commands running automatically after you typed `cd projects/mkproj`. Maybe that's something I need to reproduce this?

P.S.

Please pull the latest version of Powerlevel10k to be sure we are using the same code in our tests.

**Comment by iboyperson** [comment]
For clarification when I enter that directory the command `pipenv shell` is being run to activate the virtualenv.

Interestingly enough this looks like it might actually be an issue with `pipenv shell`. It seems `pipenv shell` might do more then just activating the virtualenv as it appears it might fork the shell (not entirely sure) through [Python's os.execvp](https://docs.python.org/2/library/os.html#os.execvp). 

For additional information when I run `deactivate` the expected result of the prompt showing up happens.
![image](https://user-images.githubusercontent.com/10000914/54448418-ef343f80-4708-11e9-9e2e-2ed992345d01.png)
but when I run `exit`
![image](https://user-images.githubusercontent.com/10000914/54448735-a6c95180-4709-11e9-9897-f07ad8442d2f.png)

**Comment by romkatv** [comment]
After some more reading (I never heard of pipenv) and fighting through the usual Linux bullshit I managed to reproduce this. And then I figured out what's going on. pipeenv is being too nice. Upon exit, it waits for the shell's child processes to finish (that would be gitstatusd -- the companion process that gives Powerlevel10k git info). gitstatusd will actually finish automatically once the parent shell goes away but here we have a deadlock. I fixed this issue by hooking into `zshexit` and killing gitstatusd explicitly.

For the record, here's how I reproduced it:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  apt update && apt install -y zsh git python3 python3-pip python3-venv
  python3 -m pip install --user pipenv
  git clone https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  cat >~/.zshrc <<END
    export PATH=$HOME/.local/bin:\$PATH
    source ~/powerlevel10k/powerlevel10k.zsh-theme
END
  mkdir ~/environments
  cd ~/environments
  python3 -m venv project_env
  zsh -i'
```

Once the prompt appears, type `pipenv shell` and then `exit`. It used to hang there but it doesn't anymore.

Please `git pull` Powerlevel10k and let me know if the issue is resolved.

**Comment by iboyperson** [comment]
This issue is indeed resolved. Thank you for your great work!

**Comment by romkatv** [comment]
Phew. Thanks for your assistance tracking this bug down.
