### ISSUE TITLE
Spaces in powerline on shell startup

### ISSUE THREAD

**Issue by EtherealMochi** [romkatv/powerlevel10k#1700]
I am getting this on shell startup via WSL2 on a new ZSH install. It happens no matter what settings I am using. I have the default .zshrc file that is used on first install of ZSH.
In my .zshenv I have one exported env: `ZDOTDIR=$HOME/.zsh`

Things I have tried:

1. Comment out everything in .zshrc except for lines to load P10K.
    ```
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
      source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi
    
    # Set Prompt
    source $ZDOTDIR/plugins/powerlevel10k/powerlevel10k.zsh-theme
    # To customize prompt, run `p10k configure` or edit ~/.zsh/.p10k.zsh.
    [[ ! -f ~/.zsh/.p10k.zsh ]] || source ~/.zsh/.p10k.zsh
    ```
2. Run p10k configure and change prompt style. Issue is still the same.
3. Change font in Windows Terminal, no change. 
4. In .zshrc, remove instant prompt lines. This resolves the issue but the prompt takes about 1 second to show up. 

![image](https://user-images.githubusercontent.com/51897953/147976540-bd3addf5-a40b-4c74-b8b0-5ea440967884.png)

**Comment by romkatv** [comment]
Looks like a broken terminal to me. If you cannot switch to a different terminal, run `p10k configure` and choose Lean style. In fact, you might want to do that even if you *can* switch to a different terminal.

**Comment by EtherealMochi** [comment]
If I use the lean style my prompt flashes just as this one does. After the 1 second flash on any style I do have the prompt looking correctly as shown below. 

![image](https://user-images.githubusercontent.com/51897953/147982898-77080ac6-eda5-4b57-878d-7507cf3174b0.png)

If I disable instant prompt I still have to wait about 1 second for my prompt to come up. I have tried WSLtty, windows terminal, and Mobaxterm and all have the same issue but do show correctly after that 1 second. Do you have any other ideas?

**Comment by romkatv** [comment]
> @romkatv If I use the lean style my prompt flashes just as this one does.

What do you mean by "flashes"?

**Comment by EtherealMochi** [comment]
> > @romkatv If I use the lean style my prompt flashes just as this one does.
> 
> What do you mean by "flashes"?

It almost looks like its loading twice when using any of the prompts. I only have one source command in my zshrc that is tied to the theme file and then I have the statement to load .p10k.zsh.  On start up the prompt displays with the the space background missing then it will flash and load the background text colors. I honestly don't know if this is normal or not with these things as I just started using ZSH a few days ago. When using no ZSH config at all, its instantaneous with no flashing/flickering of the prompt.

Quick animation to show what it looks like when starting the prompt or loading a new tab. I will admit that on the lean option it is not noticeable as much. On that version it was so quick the gif recorder didn't catch it. 
![Animation](https://user-images.githubusercontent.com/51897953/148126018-89d91da6-37f5-485b-8eb2-897cbb655772.gif)

**Comment by romkatv** [comment]
That doesn't look like Lean style.

**Comment by romkatv** [comment]
???

Does it work with lean style?
