### ISSUE TITLE
Double width icon test in p10k configure does not work on kitty

### ISSUE THREAD

**Issue by xsrvmy** [romkatv/powerlevel10k#1702]
The kitty terminal emulator shrinks icons that are wider into single width, unless they are followed by a space. This means that the "Do all these icons fit between the crosses" step does not work properly on kitty because kitty makes them fit.

A possible fix is to add an extra step, asking if the icons become bigger when a space follows them, is the user answers yes.

**Comment by romkatv** [comment]
An extra step would mean everyone has to go through it. Using a non-monospaced font is a terrible idea and few do that (thankfully). Even fewer do that while using Kitty.

**Comment by xsrvmy** [comment]
> Using a non-monospaced font is a terrible idea

That's pretty debatable for icons actually

Didn't consider the impact of adding this extra step actually. The other way is add a seperate line with only icons and spaces and ask the user to answer "no" if the icons are bigger on the second line, but that might be confusing.

Perhaps the best way to handle this is just to clarify in the "no" option that if you know your font has wide icons, answer no regardless.

**Comment by romkatv** [comment]
> That's pretty debatable for icons actually

Have you tried my font? It has large icons and is monospaced.

> Perhaps the best way to handle this is just to clarify in the "no" option that if you know your font has wide icons, answer no regardless.

That's an extra sentence that 0.01% of users might benefit from (I'm being generous here). It'll probably confuse more users than that and cause them to reply No when they should've replied Yes (almost everyone uses a monospaced font).

If someone is using Kitty and a non-monospaced font, they probably know that icon size depends on the next character being a space (another reason to avoid non-monospaced fonts), so they expect that nothing works for them out of the box. They'll be fine.

**Comment by xsrvmy** [comment]
I use Iosevka so that Chinese characters don't get spaces between them
But anyways let's close this.

**Comment by bruce3x** [comment]
@xsrvmy  Hello, have you finally solved the problem?

**Comment by anhari** [comment]
> @xsrvmy Hello, have you finally solved the problem? I'm using Iosevka and meet the same problem.

Use IosevkaTerm: https://github.com/be5invis/Iosevka/issues/1347#issuecomment-1117580971
