### ISSUE TITLE
Have you see issues with PIPE|127

### ISSUE THREAD

**Issue by JCzz** [romkatv/powerlevel10k#1703]
I have noticed in may prompt on MacOS,
that some times the exact same command will not work,
and the status will show `PIPE|127`

Like, this will not work
```
cat watch.json | jid
zsh: command not found:  jid
```

But this will:
`cat watch.json | jid`

**Comment by romkatv** [comment]
Powerlevel10k only displays prompt. It doesn't affect execution of command in any way.
