### ISSUE TITLE
Command execution time and timestamp in transient mode

### ISSUE THREAD

**Issue by scythargon** [romkatv/powerlevel10k#1705]
Hello! Happy New Year and thank you for your incredible work!:)

I've read this issue - https://github.com/romkatv/powerlevel10k/issues/1277 , all the related ones, plus `p10k help display`, but still didn't get how to achieve what I want, look, input prompt shows the execution time and timestamp on the right:

<img width="837" alt="Screenshot 2022-01-06 at 14 17 07" src="https://user-images.githubusercontent.com/1755870/148344696-7205b340-77d3-411d-9699-8219436d6439.png">

But once you hit enter or enter more commands - this information is not available anymore:

<img width="841" alt="Screenshot 2022-01-06 at 14 17 20" src="https://user-images.githubusercontent.com/1755870/148344775-815a19cb-405e-43e3-a55c-91639ab2781d.png">

I would like it to stay on the right in transient mode as well, here is my config file, though it's the most basic one - just generated it via the wizard. 

[p10k copy.txt](https://github.com/romkatv/powerlevel10k/files/7820157/p10k.copy.txt)

thank you!:)

**Comment by romkatv** [comment]
```diff
1537c1537
<   typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
---
>   typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true
1582c1582,1585
<   typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
---
>   typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
>
>   function p10k-on-post-prompt() { p10k display '1/left/(dir|vcs)'=hide }
>   function p10k-on-pre-prompt()  { p10k display '1/left/(dir|vcs)'=show }
```

**Comment by scythargon** [comment]
Ahhh got it now! Thanks a lot! Even found this [similar issue](https://github.com/romkatv/powerlevel10k/issues/316), but still could not figure it out myself

**Comment by romkatv** [comment]
You are welcome.
