### ISSUE TITLE
Feature request: Detect Amazon Linux

### ISSUE THREAD

**Issue by bokysan** [romkatv/powerlevel10k#1706]
Amazon Linux has `ID="amzn"`:

```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

Amazon logo is available:
- in [Font Awesome](https://fontawesome.com/v5.15/icons/amazon?style=brands)
- in [Nerd Fonts](https://www.nerdfonts.com/cheat-sheet) as `#f270` / `nf-fa-amazon`

**Comment by romkatv** [comment]
Done.

**Comment by bokysan** [comment]
Wow. Cool :)
