### ISSUE TITLE
Better understanding of custom *_prompt_info() functions

### ISSUE THREAD

**Issue by danstreeter** [romkatv/powerlevel10k#1709]
Hey, sorry for raising an issue on this, but I'm super stuck...

I'm trying to start writing my own prompt 'plugin' for want of a better word for Backblaze B2 - very similar to the way the AWS one works where you get the profile currently set to your environment in the left or right prompts depending on where `aws` has been added into the `.p10k.zsh` `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` arrays.

I just want to see which B2 Profile I current have set to my env before I go and start manipulating remote files etc...

The implementation of the plugin is an aside at this moment in time... im just really struggling to get anything to work as I would expect; taking guidance from existing known working plugins... (aws is the one I'm using as my example)

I'm 99% sure I've missed something simple but crucial, or not got one thing right, but then some of the things I mention below make me think there is something odd going on. (Or, quite possibly not even barking up the right tree)

So - I have done the following:

- Confirmed the custom location of my custom plugins dir as set by `ZSH_CUSTOM` in `.zshrc`
- Created a plugin in `$ZSH_CUSTOM/my_b2_profile/my_b2_profile.plugin.zsh` with the following content in to mirror the raw output of what the aws plugin does:
```bash
function b2hello() {
  echo "Hello Backblaze B2 Profile Plugin"
}


# AWS prompt
function my_b2_profile_prompt_info() {
  echo "<aws:b2profile>"
}
```
- Added `my_b2_profile` to the `.zshrc` plugins array
- Confirmed it is loading by running `b2hello` from a terminal and getting my "Hello...." text echoed back to me
- Confirmed this function wasnt being loaded by anything else by removing it from the plugins array and re-testing, getting a 'command not found' error
- Added `my_b2_profile` to the `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` array in `.p10k.zsh` and getting nothing
- Confirming my `.p10k.zsh` file in modificaiton is correct by removing `aws` from the `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` array and confirming that previously working aws plugin funcitonality now does not occur.

So at this point I'm thinking "Ok its something to do with my simple plugin code"... and here is where the madness begins...

- I thought, maybe its not just a raw string being passed to the prompt... so I edit the `aws.plugin.zsh` function `aws_prompt_info()` to output my simple static string... no change - i still get 'exepected' aws plugin funcitonality; the environment set in $AWS_PROFILE - even when the code is not even referencing that env var... its literally echoing `<aws:b2profile>` - thats odd...

- I then think, ok maybe its not loading THAT version of the aws plugin, (At this stage I am editing the 'core', within `~/.oh-my-zsh/plugins` directory, not custom. So I rename that folder... and i get a plugin not found error when starting a new terminal.
So its certainly loading the plugin that I am editing...

- Next - I remove the ENTIRE function from `aws.plugin.zsh` - it STILL operates in the same way, even when running `aws_prompt_info` raw on the command line returns a command not found error. (How is the prompt being populated from a function which doesnt exist!?)

I then removed the contents of the `~/.cache` directory thinking it was loading up function definitions for prompt usage from the cache - and it all got recreated when a new terminal was booted... but STLL worked as expected.
---

I'm now SUPER confused.... where _does_ p10k get the "*prompt_info" for a plugin from that is used in the left or right prompt areas.

Is there a cache which i'm not busting somewhere else?

Why does the aws one work unbreakably, when I cannot even get my simple one to be picked up.

Apologies for the long post, but I've been trying to debug this since about 1100 today (its 1600 now) and i've never seen my google search result history so purple for anything related to p10k & oh-my-zsh plugins! =)

Thanks for any help and guidance you can offer.

**Comment by romkatv** [comment]
Are you trying to implement a custom prompt segment? If so, search for "example" in `~/.p10k.configure`.

**Comment by danstreeter** [comment]
I dont think I am - but obviously may be wrong... That functionality seems to load up into into a segment when what I want is exactly what the aws oh-my-zsh plugin will be doing.

_Eventually_ (once I've written it) it will be dynamiclly collecting the B2 profile from an environment variable and displaying it in the left/right prompt areas in context when performing a b2... command

Basically EXACTLY the same functionality as the AWS one, but with the B2 command.

Ending up with this:
![image](https://user-images.githubusercontent.com/20464844/148654152-fa369f8d-93a1-4b17-936d-727d16e6ab69.png)

The 'example' search points to a " (see prompt_example function below)" reference which then points to function using `p10k segment`:
```bash
function prompt_example() {
    p10k segment -f 208 -i '⭐' -t 'hello, %n'
  }
```

If I enter a new function in there `prompt_dan` then add `dan` to my left prompt elements i sure get the prompt, but I cannot seem to bake out that usage into the custom plugin file - it doesnt run there.

This is what I believe (again, I'm probably wrong and barking up the wrong tree) I am trying to replicate: https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/aws/aws.plugin.zsh#L156

**Comment by romkatv** [comment]
> ![image](https://user-images.githubusercontent.com/20464844/148654152-fa369f8d-93a1-4b17-936d-727d16e6ab69.png)

That's `aws` prompt segment. It doesn't have anything to do with ohmyzsh (powerlevel10k doesn't use ohmyzsh). You can implement the basics of this segment like this:

```zsh
function prompt_my_aws() {
  local profile=${AWS_VAULT:-${AWSUME_PROFILE:-${AWS_PROFILE:-$AWS_DEFAULT_PROFILE}}}
  [[ -n $profile ]] || return
  p10k segment -f 208 -ri AWS_ICON -t ${profile//\%/%%}
}

# Show my_aws only when the the command you are typing invokes one of these tools.
# Tip: Remove the next line to always show my_aws.
typeset -g POWERLEVEL9K_MY_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi|terragrunt'
```

Try it. `my_aws` prompt segment should behave just like the builtin `aws`.

**Comment by danstreeter** [comment]
Waa - Well now I'm REALLY confused!!! I guess because of the overlap between keywords and plugin names etc

I'll give that a whirl - but if p10k isnt using that omz plugin file... where is p10k getting its implementation of the aws prompt segment from?

**Comment by romkatv** [comment]
> Waa - Well now I'm REALLY confused!!! I guess because of the overlap between keywords and plugin names etc

It's really quite simple. Your prompt is rendered by powerlevel10k.

> where is p10k getting its implementation of the aws prompt segment from?

powerlevel10k has all necessary code to display prompt. As for `aws` prompt segment, there is not much code in it. I've posted the implementation in my previous comment.

**Comment by danstreeter** [comment]
Appreciate the post above, that worked (I had no doubt it wouldnt!) so I can migrate that over to my intentions.

My question about 'where' was regarding the already existing, working 'I'm not aware I did anything to make it work' version of the prompt...

My confusion has derived from the misunderstanding that this was being driven by the omz plugin as the code link I sent a while back looks like it outputs what I would expect to be the format being rendered. (Clearly now I understand it isnt, as you've explained)

But still leaves me with the question of... where does my current `aws` left prompt element reference get implemented?

If I comment it out, with no other changes the prompt dissapears, so as you've also explained - clearly p10k is doing this, and not the omz plugin... But as far as I am aware right now, the only reference to an 'aws' interface is the omz plugin - hence why i was looking there.

**Comment by romkatv** [comment]
> But still leaves me with the question of... where does my current `aws` left prompt element reference get implemented?

The source code of powerlevel10k is here: https://github.com/romkatv/powerlevel10k. On your machine it's wherever you cloned the repo, most likely in `~/.oh-my-zsh/custom}/themes/powerlevel10k`. If you search for "aws" in there, you'll find many hits.

**Comment by danstreeter** [comment]
Perfect, thank you - exactly what I needed! Much appreciated.
