### ISSUE TITLE
Show AWS Region

### ISSUE THREAD

**Issue by stuart-warren** [romkatv/powerlevel10k#1715]
Similar to #1349 I'd really like to be able to see the aws region next to the profile if possible

Even if it's just reading from ${AWS_DEFAULT_REGION} which I set

does this make sense, or is something really bad. The call to `aws configure` is a bit slow

```diff
diff --git a/internal/p10k.zsh b/internal/p10k.zsh
index 845bd97..1db63dd 100644
--- a/internal/p10k.zsh
+++ b/internal/p10k.zsh
@@ -1116,6 +1116,7 @@ _p9k_prompt_anaconda_init() {
 # AWS Profile
 prompt_aws() {
   local aws_profile="${AWS_VAULT:-${AWSUME_PROFILE:-${AWS_PROFILE:-$AWS_DEFAULT_PROFILE}}}"
+  local aws_region="${AWS_DEFAULT_REGION:-$(aws configure get region --profile ${aws_profile})}"
   local pat class
   for pat class in "${_POWERLEVEL9K_AWS_CLASSES[@]}"; do
     if [[ $aws_profile == ${~pat} ]]; then
@@ -1123,7 +1124,7 @@ prompt_aws() {
       break
     fi
   done
-  _p9k_prompt_segment "$0$state" red white 'AWS_ICON' 0 '' "${aws_profile//\%/%%}"
+  _p9k_prompt_segment "$0$state" red white 'AWS_ICON' 0 '' "${aws_profile//\%/%%} [${aws_region//\%/%%}]"
 }
 
 _p9k_prompt_aws_init() {

```

**Comment by romkatv** [comment]
> Similar to #1349 

That issues has been resolved. Does it not work for you?

**Comment by romkatv** [comment]
Your diff is based on an ancient version of powerlevel10k. Try updating and running `p10k configure`. You should see region.

**Comment by stuart-warren** [comment]
ah, interesting, you are right, i had an old version 🤦 

👍  got a bit stumped by the need to start typing the command again, but it does work well enough now

Thanks and sorry

**Comment by romkatv** [comment]
> got a bit stumped by the need to start typing the command again

Do you mean this?

https://github.com/romkatv/powerlevel10k/blob/683a485232d75978a79199a305c4fc4843772a77/config/p10k-lean.zsh#L1280-L1282

**Comment by stuart-warren** [comment]
yes, I had that commented out before, but forgot about it until i accidentally typed `aws` and the prompt appeared
