### ISSUE TITLE
p10k configure does not ask about font visibility

### ISSUE THREAD

**Issue by seolcu** [romkatv/powerlevel10k#1717]
Hi, I have installed the latest release of p10k now.

I remember that in the older releases, p10k configure firstly asked me about the font visibility, like 'do you see this diamond?'.

However this prompt does not show now and the style setting(selecting between lean, classic, rainbow and whatever) shows first.

How can I fix this?

I am using oh my zsh, with Konsole and Yakuake, and the MesloLGS NF font is properly setted.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
