### ISSUE TITLE
Show python venv prompt

### ISSUE THREAD

**Issue by LarsKumbier** [romkatv/powerlevel10k#1718]
![grafik](https://user-images.githubusercontent.com/647850/149472313-df269dcc-ea47-4ca7-94ff-ac3dd96cd7bc.png)

I'm running p10k on Manjaro and I have seen different issues to this topic already - I still believe, my issue is different.

I'm activating a python venv (`.env`) without the prompt option and - as expected - get venvs' directory name in the right bar (image 1).

However, if I create a venv with the `--prompt MyProject` option and activate it, I also only get the venvs' directory name instead of the expected prompt name (image 2). I would expect this to show instead of the directory name, similar to how bash handles it (image 3).

**Comment by romkatv** [comment]
> However, if I create a venv with the `--prompt MyProject` option and activate it, I also only get the venvs' directory name instead of the expected prompt name (image 2).

Your expectation is reasonable. For this to happen, venv will need to be changed so that `activate` sets `VIRTUAL_ENV_PROMPT=MyProject`. The name of this parameter can be different but the value must be the same as what was passed via `--prompt`. If and when this is implemented in venv, please open an issue here and I'll update powerlevel10k.

**Comment by LarsKumbier** [comment]
It kind-of does:
![grafik](https://user-images.githubusercontent.com/647850/149509787-db0047c0-55a7-44f0-a409-ba1f51f95ac0.png)

`VIRTUAL_ENV_PROMPT` is filled, but unfortunately has some extra information - this could be stripped by length or by removing any non-alphanumeric characters at the beginning and at the end, leaving the rest intact.

there's also a config file that contains the prompt as having been entered by the user.

**Comment by romkatv** [comment]
Interesting. On Ubuntu 21.10 there is no `VIRTUAL_ENV_PROMPT` but on Majnaro there is one indeed.

I've updated powerlevel10k to respect this variable if its value is different from the default. Please let me know whether it works for you.

**Comment by LarsKumbier** [comment]
Perfect, thanks a lot for the prompt help! Can I send you a coffee or something?

**Comment by romkatv** [comment]
> Perfect, thanks a lot for the prompt help!

You are welcome. Thanks for filing the issue.

> Can I send you a coffee or something?

Saying thanks is more than enough.

**Comment by LarsKumbier** [comment]
Then thanks again! :D

**Comment by vyacheslavkovalev** [comment]
Is it correct if I get root directory name shown in bar? 
<img width="1036" alt="Screenshot 2024-02-20 at 22 42 33" src="https://github.com/romkatv/powerlevel10k/assets/120056179/0c736aed-6fee-4e13-9cb4-83c7b5da71e1">

**Comment by romkatv** [comment]
It's quite useful to know *which* venv you have active, don't you find? If you don't care, go ahead and disable that prompt segment or reduce it to just an icon.

**Comment by vyacheslavkovalev** [comment]
Oh, sure, this upgrade is cool. Just thought something wrong with me. Cause before it was only .venv name. Thanks.
