### ISSUE TITLE
OS icon's visual glitch

### ISSUE THREAD

**Issue by hummblebee** [romkatv/powerlevel10k#1719]
Hi

I've setup powerlevel10k and very much enjoying it! Only one minor issue bothering me and that is the OS icon has a vertical line drawn next to it, making it look like a boxed icon!
![Screenshot from 2022-01-14 21-27-01](https://user-images.githubusercontent.com/18480836/149563438-54ced448-8caa-452a-a76f-d17ed0f09875.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by hummblebee** [comment]
The only option that worked was applying the recommended font, although it's still not perfect but looks better now.

Thank you!

**Comment by romkatv** [comment]
There is also this option:

> Type `p10k configure` and select *Lean*. 

It removes visual glitches completely.
