### ISSUE TITLE
ram segment suddenly generating invalid commands

### ISSUE THREAD

**Issue by rjorgenson-ns** [romkatv/powerlevel10k#1722]
I recently updated p10k, not sure from what, but it's been a while, and on one particular system my prompt started spitting this out
```
WARNING:root:could not open file '/etc/apt/sources.list'

-v_p9k__ram_free=xG: command not found
```
I have the 'ram_joined' segment configured and on this particular system the only element included is `ram_free`. For what it's worth `/etc/apt/sources.list` does not exist on this system, but this error is also not generated when removing this segment. The same behavior is observed using just the `ram` segment unjoined and moving the position of the `ram` segment.
```
POWERLEVEL9K_RAM_BACKGROUND="black"
POWERLEVEL9K_RAM_FOREGROUND="249"
POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=('pyenv' 'virtualenv' 'nvm' 'rvm' 'load' 'ram_joined' 'disk_usage' 'battery' 'time')
```
This particular host is an older system I don't have control over and is running `zsh 5.1.1 (x86_64-ubuntu-linux-gnu)`.  I have not had this issue on any other system I run zsh one which all have newer versions of zsh. Possible that this is a breaking change and the minimum version requirement should be bumped (5.1 on the README) or it might be something that could be fixed. I tried giving it a look but p10k has gotten very complex since the early p9k days when I was hacking on it and I got lost =[ It's possible that this is erroring out because of the system it's run on, if you need any specific information about that let me know but it's a pretty bog standard Ubuntu 16 setup.

**Comment by romkatv** [comment]
Thanks for the report. I've increased the minimum required version from 5.1 to 5.3.

**Comment by rjorgenson-ns** [comment]
👍
