### ISSUE TITLE
[BUG] Asdf + Ruby do not show version on the right side

### ISSUE THREAD

**Issue by kvokka** [romkatv/powerlevel10k#1725]
With new installation

```bash
❯ asdf local ruby 2.7.2
❯ cat .tool-versions
ruby 2.7.2
❯ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin21]

     ~/tmp/                                                                                  1.76    19:42:29   
❯                                                                                                                    100%  
```

The ruby version does not print on the right side (with nodejs and golang it works correctly). 

Using default file `.p10k.zsh`, also tried to override `typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(asdf)` with the same result.

### versions

zsh 5.8
asdf 0.9.0
ohmyzsh latest (957dca698cd0a0cafc6d2551eeff19fe223f41bd)
powerlevel10k version v1.16.0

**Comment by romkatv** [comment]
What's the output of the following command?

```zsh
asdf global ruby
```

**Comment by kvokka** [comment]
> What's the output of the following command?
> 
> ```shell
> asdf global ruby
> ```

```bash
❯ asdf global ruby
Usage: asdf global <name> <version>
❯ asdf current ruby
ruby            2.7.2           /Users/mike/.tool-versions
```

(I tried with local & global versions, no difference)

**Comment by romkatv** [comment]
I don't have asdf installed and don't remember how to ask it for the global version of the tool. Since you have it install and are using it, perchance you know the command? Or to put it another way, what's the global ruby version in asdf on your machine?

**Comment by kvokka** [comment]
Yes, I have it installed. To see the current ruby version you should run `asdf current ruby`. Ruby global version is `2.7.2` and it works correctly.

**Comment by romkatv** [comment]
Do I understand it correctly that you've set both local and the global version of ruby in asdf to `2.7.2`?

Have you seen this?

https://github.com/romkatv/powerlevel10k/blob/683a485232d75978a79199a305c4fc4843772a77/config/p10k-classic.zsh#L568-L602

**Comment by kvokka** [comment]
Yes, it is correct.

I read the docs, and tried (in 3 different attempts ofc) to set 

```
  typeset -g POWERLEVEL9K_ASDF_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_ASDF_SOURCES=(local global)
  typeset -g POWERLEVEL9K_ASDF_SOURCES=(global)
```

Nothing changed.

Another trait is, about `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW` variable.

`POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false`

<img width="827" alt="Screenshot 2022-01-18 at 23 09 04" src="https://user-images.githubusercontent.com/15954013/150033355-fd363aea-ba99-4828-af9f-8774d6f90ec5.png">

`POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=true`

<img width="827" alt="Screenshot 2022-01-18 at 23 09 26" src="https://user-images.githubusercontent.com/15954013/150033382-0b6911cd-5507-472b-b225-ca2eb3a0eef5.png">

Look at the right side. This might be connected. (Hope it might help)

**Comment by romkatv** [comment]
> `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=true`

That's the parameter I was referring to.

> <img alt="Screenshot 2022-01-18 at 23 09 26" width="827" src="https://user-images.githubusercontent.com/15954013/150033382-0b6911cd-5507-472b-b225-ca2eb3a0eef5.png">

You'll need to make your terminal window wider.

**Comment by kvokka** [comment]
> > `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=true`
> 
> That's the parameter I was referring to.
> 
> > <img alt="Screenshot 2022-01-18 at 23 09 26" width="827" src="https://user-images.githubusercontent.com/15954013/150033382-0b6911cd-5507-472b-b225-ca2eb3a0eef5.png">
> 
> You'll need to make your terminal window wider.

It did not make any changes. 

Anyway, it is another case, which somehow might be connected with the subject (or my misunderstanding of the feature).

**Comment by romkatv** [comment]
> It did not make any changes.

Then it's not wide enough.

**Comment by kvokka** [comment]
<img width="837" alt="Screenshot 2022-01-19 at 10 01 50" src="https://user-images.githubusercontent.com/15954013/150108402-0f370e13-c65d-45b4-b4d3-e5134bde284f.png">

Can this be enough?

The main issue is that asdf + ruby does not detect ruby (and I can not see the ruby version).

**Comment by romkatv** [comment]
> Can this be enough?

Depends how many asdf tool you have. Can you move `asdf` from right to left prompt?

> The main issue is that asdf + ruby does not detect ruby (and I can not see the ruby version).

I understand. I've posted above why I believe it's working as intended. Now we are trying to verify it.

**Comment by kvokka** [comment]
> > Can this be enough?
> 
> Depends how many asdf tool you have. Can you move `asdf` from right to left prompt?

On the left side with `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=true` I see all the tools

<img width="837" alt="Screenshot 2022-01-19 at 13 16 04" src="https://user-images.githubusercontent.com/15954013/150138675-8bb47267-784d-45a1-9a51-606a07a11d52.png">

(Meaning you were right saying that it was not enough)

with `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false` it does not show only ruby badge.

> > The main issue is that asdf + ruby does not detect ruby (and I can not see the ruby version).
> 
> I understand. I've posted above why I believe it's working as intended. Now we are trying to verify it.

I hope that it's only my bad and misunderstanding of the setup. Thank you for all the help with this situation!

**Comment by romkatv** [comment]
It looks kinda crazy, isn't it? That's why `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW` defaults to `false`.

Note that you can set `ALWAYS_SHOW` individually for every tool. For example, if you want to see `ruby` version at all times (even when the local version is the same as global), you can set `POWERLEVEL9K_ASDF_RUBY_PROMPT_ALWAYS_SHOW=true`. I don't know why you would want that though. Usually asdf users want to see tool versions either if they aren't the same as global OR if they are being overridden locally. You achieve the former by default. You can achieve the latter with `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=true` together with `POWERLEVEL9K_ASDF_SOURCES=(shell local)`.

If anything is still not clear, please read the comments carefully (the ones I've linked to earlier).

**Comment by kvokka** [comment]
Thank you so much for the answer! This gave me an idea to try out the different version from the global and it works as it should.
So, by default tool does *not* show the version if it matches the global setting. It is wiser than the previous tools I used and I like it.

<img width="1669" alt="Screenshot 2022-01-19 at 13 50 19" src="https://user-images.githubusercontent.com/15954013/150143676-bfbe4b34-2f6d-468c-99bf-3cb634dd3c28.png">

Thank you for all the help and your patience. Hope this thread helps someone else too.

**Comment by romkatv** [comment]
> So, by default tool does _not_ show the version if it matches the global setting. It is wiser than the previous tools I used and I like it.

Correct. I'll just post the parameter with its comment once again in case you've missed it the first time.

```zsh
# If set to false, hide tool versions that are the same as global. 
typeset -g POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false 
```

You should have this ☝️ in your `~/.p10k.zsh`.

**Comment by Patolord** [comment]
> Thank you so much for the answer! This gave me an idea to try out the different version from the global and it works as it should. So, by default tool does _not_ show the version if it matches the global setting. It is wiser than the previous tools I used and I like it.
> 
> <img alt="Screenshot 2022-01-19 at 13 50 19" width="1669" src="https://user-images.githubusercontent.com/15954013/150143676-bfbe4b34-2f6d-468c-99bf-3cb634dd3c28.png">
> 
> Thank you for all the help and your patience. Hope this thread helps someone else too.

It helped me 2 years in the future  :)
