### ISSUE TITLE
No handler installed for fd 16

### ISSUE THREAD

**Issue by wang1zhen** [romkatv/powerlevel10k#1727]
Running p10k on Debian WSL2
After idling for a while, the following lines shows:
```
_p9k_deschedule_redraw:zle:2: No handler installed for fd 16
_p9k_deschedule_redraw:3: file descriptor 16 used by shell, not closed
```

I have `fd-find` installed, and for debian, I have also linked `ln -s $(which fdfind) ~/.local/bin/fd`,
```
❯ fd --version
fd 8.3.1
```

**Comment by romkatv** [comment]
Does your zshrc source anything else other than powerlevel10k?

**Comment by wang1zhen** [comment]
I have the following plugins enabled,
```
romkatv/powerlevel10k
romkatv/zsh-defer
zsh-users/zsh-autosuggestions
zsh-users/zsh-completions
zsh-users/zsh-history-substring-search
davidde/git
rupa/z
trystan2k/zsh-tab-title
zsh-users/zsh-syntax-highlighting
```
As I have searched, this might be an issue concerning [this issue](https://github.com/marlonrichert/zsh-autocomplete/issues/166) of zsh-autocomplete, and as discussed in the issue, this should has already been fixed I suppose?

**Comment by romkatv** [comment]
I don't know what causes it but I venture a guess it's not powerlevel10k.
