### ISSUE TITLE
Typing backspace in instant prompt gives strange code "^?"

### ISSUE THREAD

**Issue by jvzaniolo** [romkatv/powerlevel10k#1728]
**Typing backspace in instant prompt gives strange code "^?"**

![CleanShot 2022-01-19 at 11 29 14](https://user-images.githubusercontent.com/54036572/150150854-82e57c7e-c186-4cbd-87fe-ff405e4e2e27.png)

**Description**

When typing the "backspace" key in instant prompt, it returns a strange code: ^?

**Expected behavior**

Erase the last typed character

**Steps to reproduce**

When in an instant prompt, type the backspace key.

**Comment by jvzaniolo** [comment]
Got it. Is there any workaround?

**Comment by romkatv** [comment]
No. Powerlevel10k cannot magically make zle load instantly. All it can do is display prompt.

**Comment by NyaMisty** [comment]
> No. Powerlevel10k cannot magically make zle load instantly. All it can do is display prompt.

Hi, but can we make p10k load zle first then the instant prompt?

**Comment by romkatv** [comment]
> Hi, but can we make p10k load zle first then the instant prompt?

That's exactly what happens if you disable instant prompt.
