### ISSUE TITLE
Does the command execution time support milliseconds?

### ISSUE THREAD

**Issue by JiaoZiLang** [romkatv/powerlevel10k#1729]

**Comment by romkatv** [comment]
Yes.

**Comment by pedroserigatto** [comment]
And how do I set it to show execution time to the milliseconds? (I only want to show 1 digit though)
What do I put in TIME_FORMAT to display milliseconds?

```
  # Show duration of the last command if takes at least this many seconds.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0

  # Show this many fractional digits. Zero means round to seconds.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1

  # Duration format: 1d 2h 3m 4s.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
```

**Comment by romkatv** [comment]
Yep, exactly like that.

**Comment by pedroserigatto** [comment]
Actually, this format 'd h m s' does not show milliseconds, only shows up to seconds.
I suppose the Threshold=0 and Precision=1 is correct, but no the 'd h m s'.

**Comment by romkatv** [comment]
Let's start from the beginning. Describe what you see and what you expect.

**Comment by pedroserigatto** [comment]
Never mind, I restarted my session in iTerm2 and it started showing milliseconds!
Thanks!
![image](https://user-images.githubusercontent.com/65415397/150539462-221a8585-6b06-4918-8f60-9c92b8bdbe88.png)

**Comment by PabloLION** [comment]
For the new comers from mac like me: 
the `typeset` thing from above like this doesn't work.
> `typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1`

Instead, add them like `POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1` to your `~/.zshrc`
origin: https://blog.technicalfever.com/2019/03/01/zsh/

**Comment by romkatv** [comment]
@PabloLION That's not a good advice. If you are using powerlevel10k, it's highly recommended to run `p10k configure` to begin with. After that you can edit `~/.p10k.zsh` to customize prompt.

**Comment by PabloLION** [comment]
Thanks for the info, @romkatv . I'll do this next week.

**Comment by alvinfebriando** [comment]
is it possible to change it to 100 ms instead of 0.1 s?

**Comment by romkatv** [comment]
> is it possible to change it to 100 ms instead of 0.1 s?

Yes.

```zsh
POWERLEVEL9K_COMMAND_EXECUTION_TIME_CONTENT_EXPANSION='$((int(1000 * P9K_COMMAND_DURATION_SECONDS)))'
```

**Comment by AWH1122** [comment]
Is it possible to only show the execution time in milliseconds when the runtime is below a certain threshold? If so, how can this be done?

**Comment by romkatv** [comment]
> Is it possible to only show the execution time in milliseconds when the runtime is below a certain threshold? If so, how can this be done?

```zsh
POWERLEVEL9K_COMMAND_EXECUTION_TIME_CONTENT_EXPANSION='${$((P9K_COMMAND_DURATION_SECONDS < 1 ? int(1000 * P9K_COMMAND_DURATION_SECONDS) : -1)):/-1/$P9K_CONTENT}'
```

**Comment by AWH1122** [comment]
This does not seem to display ms as the units when the execution time is below the threshold. Is there a way to do this?

**Comment by romkatv** [comment]
I'm afraid I've already spent more time on this than I could afford, but at least I can tell you that yes, that's also possible.

**Comment by Laurensdc** [comment]
Alright everyone, I put my time in as well. This one should do the trick!

I am proud and ashamed at the same time.

```shell
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_CONTENT_EXPANSION='${$((P9K_COMMAND_DURATION_SECONDS < 1 ? int(1000 * P9K_COMMAND_DURATION_SECONDS) : -1)):/-1/$P9K_CONTENT}${${$((P9K_COMMAND_DURATION_SECONDS < 1)):/1/ms}:/0/}'
```

<img width="732" alt="image" src="https://github.com/user-attachments/assets/1c388ac7-1f8e-4474-bbc3-f6136d8021cb">

**Comment by AWH1122** [comment]
Works perfectly. Thanks!

**Comment by romkatv** [comment]
A simpler alternative:

```zsh
POWERLEVEL9K_COMMAND_EXECUTION_TIME_CONTENT_EXPANSION='${P9K_CONTENT:/0s/$((int(1000 * P9K_COMMAND_DURATION_SECONDS)))ms}'
```

**Comment by AWH1122** [comment]
Doesn't seem to work for me but @Laurensdc solution works fine.
