### ISSUE TITLE
Issue on Visual Studio Code

### ISSUE THREAD

**Issue by MikeYV** [romkatv/powerlevel10k#173]
When open terminal in visual studio I get this error

> _p9k_declare:37: character not in range  

This is my settings.json

```json
{
    "terminal.external.osxExec": "iTerm.app",
    "terminal.integrated.shell.osx": "/bin/zsh",
    "terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular'"
}
```

**Comment by romkatv** [comment]
Thanks for the bug report. Should be fixed now. Please update powerlevel10k and try again.
