### ISSUE TITLE
custom segment expansion % -> %b

### ISSUE THREAD

**Issue by a-kest** [romkatv/powerlevel10k#1732]
Hey there, I wanted to build a custom load function that displays the Cpu usage in `%`.

This is my code: 
I do use a launchd agent to generate the data every few seconds, so that the terminal is a bit more responsive; anyways. I am using a Mac :/
```
function prompt_my_cpu_load() {
  integer cpu_load="$(<"MY_FOLDER"/lauchd_tests/p10k_support/usage.log)"
  if (( cpu_load >= 70 )); then
    p10k segment -s CRITICAL -f red    -t "${cpu_load}" +e +r
  elif (( cpu_load >= 50 )); then
    p10k segment -s WARNING  -f yellow -t "${cpu_load}" +e +r
  elif (( cpu_load < 10 )); then
    p10k segment -s NORMAL   -f green  -t "0${cpu_load}" +e +r
  else
    p10k segment -s NORMAL   -f green  -t "${cpu_load}" +e +r
  fi
}

typeset -g POWERLEVEL9K_MY_CPU_LOAD_VISUAL_IDENTIFIER_EXPANSION='%'
```

The problem is, that no matter if I place the `%` sign in the `VISUAL_IDENTIFIER_EXPANSION` or prepend it after the cpu_load variable during the promt function, I do get:

```
%b 54
```

instead of 

```
% 54
```

which is what I am expecting at 54% cpu usage.

What am I doing wrong, why is the `%` sign expanded to `%b`?

**Comment by romkatv** [comment]
The value of `-t` undergoes [prompt expansion](https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html). Use `%%` to display the percent sign.

Note that you can also use `-i` when invoking `p10k segment` to specify the icon. This way you won't have to use `POWERLEVEL9K_MY_CPU_LOAD_VISUAL_IDENTIFIER_EXPANSION`. The latter is essentially an override.

**Comment by a-kest** [comment]
Oh wow, that was an easy fix. Thanks a lot.
