### ISSUE TITLE
Is there a way to increase the limit of characters of the decorations?

### ISSUE THREAD

**Issue by MessiasLima** [romkatv/powerlevel10k#1733]
Hello! 

I have a question and I'd like your help if it was possible.

Sometimes when I'm working, the branch names are truncated even when I have space enough to show it.

Is there anything that I can do to the decorator fill the available space and show the whole name of the branch?
![Screenshot 2022-01-24 at 15 37 06](https://user-images.githubusercontent.com/10220064/150815532-ee172301-2c3b-425a-a277-48cab6944b20.png)

Congrats on your amazing job!

Thank you in advance

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and find this: https://github.com/romkatv/powerlevel10k/blob/683a485232d75978a79199a305c4fc4843772a77/config/p10k-classic.zsh#L388-L391

Do what the tip says.

**Comment by MessiasLima** [comment]
That's perfect! Thank you!
