### ISSUE TITLE
Problem after try to install JEnv

### ISSUE THREAD

**Issue by AndreCDiniz** [romkatv/powerlevel10k#1737]
Last login: Tue Jan 25 16:18:04 on ttys000

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

/Users/andrefelipecarvalhodiniz/.zshrc:121: command not found: ‘export
/Users/andrefelipecarvalhodiniz/.zshrc:122: parse error near `then'

I tried to follow the tutorial in this site: 
https://medium.com/@rflpazini/controlando-múltiplas-versões-do-jdk-com-jenv-bf5a7b796cee

So I used the commands bellow and after this the error occurs:

Bash 
$ echo ‘export PATH=”$HOME/.jenv/bin:$PATH”’ >> ~/.bash_profile
$ echo ‘eval “$(jenv init -)”’ >> ~/.bash_profile
$ source ~/.bash_profile

Zsh
$ echo ‘export PATH=”$HOME/.jenv/bin:$PATH”’ >> ~/.zshrc
$ echo ‘eval “$(jenv init -)”’ >> ~/.zshrc
$ source ~/.zshrc

**Comment by romkatv** [comment]
This is the important part:

```text
/Users/andrefelipecarvalhodiniz/.zshrc:121: command not found: ‘export
/Users/andrefelipecarvalhodiniz/.zshrc:122: parse error near `then'
```

You need to fix these errors. They have nothing to do with powerlevel10k.
