### ISSUE TITLE
no such file or directory: /root/internal/p10k.zsh

### ISSUE THREAD

**Issue by martinburger** [romkatv/powerlevel10k#174]
On one of my servers, I am using zsh version 5.1.1 and the latest version of prezto.

When I do an SSH login, I get the following error:

```
(anon):source:29: no such file or directory: /root/internal/p10k.zsh
```

As soon as I set

```
POWERLEVEL9K_INSTALLATION_DIR=/root/.zprezto/modules/prompt/external/powerlevel10k
```

in file `.zshenv`, powerlevel10k loads as expected.

This issue seems to be related to line 49 in file `.zprezto/modules/prompt/external/powerlevel10k/powerlevel9k.zsh-theme`:

```
     49   source $__p9k_root_dir/internal/p10k.zsh || true
```

**Comment by romkatv** [comment]
Thanks for the bug report.

I've fixed this in p10k and sent a PR to update p10k in prezto: https://github.com/sorin-ionescu/prezto/pull/1735. Once the PR is merged, you can update your prezto installation and the error should disappear.

**Comment by martinburger** [comment]
Just updated prezto. Works like a charm. Many thanks! :-)

**Comment by romkatv** [comment]
Thanks for verifying!
