### ISSUE TITLE
p10k + kitty causing terminal content to dissapear on resize.

### ISSUE THREAD

**Issue by KoalaV2** [romkatv/powerlevel10k#1740]
When using p10k and kitty ( even when disabling kittys shell integration ) the terminal content dissapears on a resize. I opened a issue earlier for kitty but was guided to here. https://github.com/kovidgoyal/kitty/issues/4577

https://user-images.githubusercontent.com/27083886/151380278-9f5fd858-4469-484b-a934-98dfb3e9b5ec.mp4

**Comment by romkatv** [comment]
Can you reproduce this after updating powerlevel10k to the latest version?

**Comment by KoalaV2** [comment]
Yep, still there if i update to latest. ( Doing a git pull from the directory since i installed it manually )

**Comment by romkatv** [comment]
Can you reproduce this if you remove everything from zshrc except powerlevel10k? If so, post all your rc files including .p10k.zsh.

**Comment by KoalaV2** [comment]
Yep, can reproduce if i comment everything except p10k. 

zshrc: https://github.com/KoalaV2/dotfiles/blob/main/.zshrc
zshenv: https://github.com/KoalaV2/dotfiles/blob/main/.zshenv
zprofile: https://github.com/KoalaV2/dotfiles/blob/main/.zprofile

p10k.zsh: https://termbin.com/mzjf0

**Comment by KoalaV2** [comment]
Of course, i completely commented out both .zshenv and .zprofile completely and relogged in to make sure the changes were applied. This is the .zshrc I'm now using where the issue persists.

```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.config/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

```

**Comment by romkatv** [comment]
Thanks. For the next tests please keep the minimal `.zshrc`.

What is the output of the following command?

```zsh
print -r -- ${_p9k__param_pat%%$'\1'*} && typeset -pm '_ksi_*|*INTEGRATION*|ZSH_(HI|AU)*'
```

**Comment by romkatv** [comment]
I see in the output that you've enabled kitty shell integration (or rather didn't disable it). Does the problem reproduce if you disable shell integration in `kitty.conf`? You can verify that shell integration is indeed disabled with the following command:

````zsh
(( $+_ksi_state )) && print enabled || print disabled
```

**Comment by KoalaV2** [comment]
Yep yep, disabled shell integration on the config, launched a new terminal and running that command i get `disabled` and the issue still persists.

**Comment by romkatv** [comment]
Can you double check that the issue does indeed persist after disabling kitty shell integration?

What's the output of the command from https://github.com/romkatv/powerlevel10k/issues/1740#issuecomment-1023423492?

**Comment by KoalaV2** [comment]
Actually now that you mention it again the issue seems to be gone when i disable the shell integration. Output of that command is also `disabled`.

**Comment by KoalaV2** [comment]
What i gathered from the other issue on the kitty repo is that there's a conflict between kittys and p10k's shell integration.

**Comment by romkatv** [comment]
Keep kitty integration disabled and add the following to `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_TERM_SHELL_INTEGRATION=true
```

Restart kitty *twice*. Does the issue still reproduce? If so, post the output of the command from https://github.com/romkatv/powerlevel10k/issues/1740#issuecomment-1023415470 (it's not the one that prints "enabled" or "disabled").

**Comment by KoalaV2** [comment]
When keeping kitty integration disabled and adding the line in `.p10k.zsh` ( on line 306 to be exact ) the issue does not persist. I have restarted kitty multiple times and it works just fine when kittys integration is disabled.  And included in the output of the command i get the newly added line ```
typeset POWERLEVEL9K_TERM_SHELL_INTEGRATION=true
```

**Comment by KoalaV2** [comment]
Actually the issue may have came back even when keeping the kitty shell integration disabled. A bit confused will test a bit more.

**Comment by KoalaV2** [comment]
Aaand yep. Issue is still there with kittys shell integration disabled and the line added on line 306. ```v134
typeset -i _POWERLEVEL9K_TERM_SHELL_INTEGRATION=1
typeset POWERLEVEL9K_TERM_SHELL_INTEGRATION=true```

**Comment by romkatv** [comment]
Keep everything as is and remove the following lines from zshrc:

```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

Does the issue still reproduce?

**Comment by KoalaV2** [comment]
Yep, sure does.

**Comment by romkatv** [comment]
Keep everything as is and remove the following lines from zshrc:

```zsh
source ~/.config/powerlevel10k/powerlevel10k.zsh-theme
```

Does the issue still reproduce?

By the way, we are doing remove debugging because 1) I don't have access to a system with Wayland and 2) I don't understand what you are doing to trigger the bug (I also don't understand what you are doing in that video).

**Comment by KoalaV2** [comment]
Oh absolutely. In the video i'm spawning a new terminal, running a command that spits out some sort of terminal output in this case sudo su so it's a prompt, and when i try to resize that window ( by moving it to floating ) it dissapears. And no the issue does not reproduce when removing the zsh-theme line from my .zshrc, just to clarify this is my current .zshrc
```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


```

**Comment by romkatv** [comment]
Keep everything as is and enable kitty integration. Does the issue reproduce?

**Comment by KoalaV2** [comment]
It does not, kittys shell integration works fine now. Could it be something with my theme then?

**Comment by KoalaV2** [comment]
Did some more testing with kitty shell integration enabled, the zshrc i had from the start and no modified line in .p10k.zsh but i commented the sourcing of the powerlevel10k.zsh-theme in my zshrc and it's fine. Uncommenting and the issue shows up.

**Comment by romkatv** [comment]
Thanks for all the info. I'll try to debug this later this week when I get some free time.

**Comment by KoalaV2** [comment]
Sounds good. I appreciate the help!

**Comment by romkatv** [comment]
I never was able to reproduce this issue but there is a chance that the fix I've made for https://github.com/romkatv/powerlevel10k/issues/1749 will fix your issue as well. Please update powerlevel10k and let me know whether it works for you now.

**Comment by KoalaV2** [comment]
Can confirm that fixes it, good work!

**Comment by romkatv** [comment]
Thanks for the confirmation!
