### ISSUE TITLE
p10k configure not displaying symbols in iTerm2 - macOS

### ISSUE THREAD

**Issue by BlazingFire007** [romkatv/powerlevel10k#1744]
Hello, I'm currently using powerlevel10k with Oh my zsh, iTerm2, and the "Snazzy" theme found [here](https://github.com/sindresorhus/iterm2-snazzy).

I'm using the [Menlo Font patched for power line](https://github.com/abertsch/Menlo-for-Powerline).

Whenever I run the p10k configure command, the diamond shows fine but neither of the locks will display.
<img width="576" alt="Screen Shot 2022-01-29 at 1 52 33 AM" src="https://user-images.githubusercontent.com/19998730/151652733-61b05bab-87e4-4351-a807-0d8d654a11a5.png">

<img width="569" alt="Screen Shot 2022-01-29 at 1 52 43 AM" src="https://user-images.githubusercontent.com/19998730/151652743-5e5134b6-e40e-4115-9cdd-8e955e131df2.png">
<img width="566" alt="Screen Shot 2022-01-29 at 1 52 56 AM" src="https://user-images.githubusercontent.com/19998730/151652752-78e6093d-9590-4835-9a68-df8653fb6e36.png">

## However, whenever I run the power line test script I found [here](https://gist.github.com/gdetrez/5845092#file-powerline-test-sh).

I get this result:
<img width="570" alt="Screen Shot 2022-01-29 at 1 54 42 AM" src="https://user-images.githubusercontent.com/19998730/151652811-05934455-9007-4321-9292-b5de11d99bbc.png">

Is this a problem with the patched font I'm using? If so, my apologies for making an issue.

And if it is, does anyone have a font recommendation that works but also looks very similar to menlo? It's far and away my favorite.

**Comment by BlazingFire007** [comment]
Well, this is embarrassing. I didn't realize Meslo was basically Menlo.

🤦‍♂️ My apologies.

**Comment by romkatv** [comment]
Yep. Meslo is monospace Menlo.

**Comment by BlazingFire007** [comment]
@romkatv Thank's for making such a cool project. I just discovered Terminal theming today lol. I've been using the default terminal app with espresso for the last year, but this is a game-changer!

**Comment by romkatv** [comment]
You are welcome.

👍 on your font taste. Menlo is fantastic.

**Comment by israel-camacho** [comment]
Hi guys... 
@eli-rich how did you solve it?  I am having the same issue with macOS Ventura Terminal and iTerm and haven't been able to solve it...
I did install powerline using hombrew and and also manual install by cloning the repo following the instructions in the [repo](https://github.com/romkatv/powerlevel10k#installation) nothing fancy here, taking into cosideration I have installed and make it run properly within Linux RHE8:
![Screenshot 2022-12-28 at 10 57 47](https://user-images.githubusercontent.com/91999110/209846476-550540cc-46f2-43b8-8488-5c069942cc7f.png)


I have already install Meslo LG S and Menlo fonts, but when I run p10k configuration I am not able to visualize the icons:
![Screenshot 2022-12-28 at 10 30 08](https://user-images.githubusercontent.com/91999110/209846042-3d7f905e-b6c6-4e23-b168-51ba145092eb.png)

This is my Terminal Settings:
![Screenshot 2022-12-28 at 10 52 10](https://user-images.githubusercontent.com/91999110/209846541-05b6d43b-45be-4142-a736-8150d329d645.png)
and I have tried all Meslo and Menlo configurations, none of them shows the icons:
![Screenshot 2022-12-28 at 10 52 25](https://user-images.githubusercontent.com/91999110/209846615-4ae21e47-6cff-4026-a68e-2cf8c197e84a.png)

I also ran the test scritp and is showed the icons, so I am not sure what could be wrong:

![Screenshot 2022-12-28 at 10 43 37](https://user-images.githubusercontent.com/91999110/209846776-1a0c5b64-d241-45a9-a062-ddd5258c2cdb.png)

Just in case you want to see it, this is my ~/.zshrc  file, nothing special there 
![Screenshot 2022-12-28 at 11 10 56](https://user-images.githubusercontent.com/91999110/209847976-c6f459d8-f5ef-41d7-b865-6f376727d9ea.png)

Hope any of you can came up with something I haven't seen 

Thanks in advance, best regards

**Comment by romkatv** [comment]
Follow the instructions in https://github.com/romkatv/powerlevel10k/blob/master/font.md.

**Comment by israel-camacho** [comment]
> Follow the instructions in https://github.com/romkatv/powerlevel10k/blob/master/font.md.

Thank you @romkatv I have already followed it... for some reason the MesloLGS NF family wasn't show it until I restart my machine... so it is working now
