### ISSUE TITLE
Show Python version in Anaconda prompt with predefined styles (`config/p10k-*.sh`)

### ISSUE THREAD

**Issue by XuehaiPan** [romkatv/powerlevel10k#1745]
Hi, thanks for creating and maintaining this awesome Zsh theme library!

## User Environment

`powerlevel10k` integrates with `oh-my-zsh` as a custom theme.

I use `POWERLEVEL9K_*` variables to configure my theme because I migrated from the predecessor Powerlevel9k to Powerlevel10k. I'm using my customized theme which is similar to `rainbow` in this repo. When in `tmux` sessions, I use the `lean` theme to get a more compact shell prompt.

## What Happened

I'm trying to always show Python versions when using Python virtual environments (`venv` and/or `conda`). When I'm using `rainbow`-like styles, the prompts will always show the Python version in the virtual environment. However, in `lean`-style, it will only givens `Py <envname>` without the version information. I found the configuration `POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION`
and `POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION` by searching `*_PYTHON_VERSION`. Then I tried:

```bash
source "${ZSH_CUSTOM}/themes/powerlevel10k/config/p10k-lean.zsh"
POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=true
POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
p10k reload
```

I got:

![Screenshotp10k](https://user-images.githubusercontent.com/16078332/151654461-0bb0ae48-c7ff-4b30-831c-c35ca3b4e2e2.png)

In `lean`-style, the virtualenv-prompt shows the Python version while anaconda-prompt does not. When both `venv` and `conda` environments are activated, the prompt will show `python --version`. In the screenshot above, the prompt will show the Python version in the `conda` environment because the `conda` environment is activated later (at the front of `PATH`).

## Configuration

Here is my configuration (`~/.zshrc`):

```bash
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Powerlevel10k configrations
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%K{white}%F{black} \ue795 \uf155 %f%k%F{white}\ue0b0%f "
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv anaconda pyenv context root_indicator dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time status background_jobs time ssh)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_VCS_SHORTEN_LENGTH=4
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=9
POWERLEVEL9K_VCS_SHORTEN_STRATEGY="truncate_middle"
GITSTATUS_NUM_THREADS=4

source "${ZSH}/oh-my-zsh.sh"

if [[ -n "${P10K_LEAN_STYLE}" ]]; then
	# Use Powerlevel10k Lean style
	source "${ZSH_CUSTOM}/themes/powerlevel10k/config/p10k-lean.zsh"
	POWERLEVEL9K_MODE="compatible"
	POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv anaconda pyenv context root_indicator dir vcs newline prompt_char)
	POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs time ssh)
	POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='·'
	POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
	POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
	POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
	POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
	POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=true    # <--------------------
	POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true  # <--------------------
	p10k reload
fi
```

where `P10K_LEAN_STYLE` is a user-defined variable, content of `zsh-lean`:

```bash
#!/bin/sh
P10K_LEAN_STYLE=true exec /usr/bin/zsh "$@"
```

**Comment by XuehaiPan** [comment]
`pyenv` segment shows `P9K_CONTENT`:

https://github.com/romkatv/powerlevel10k/blob/4f143b7b978e90ac7f36c77d71eaacc29baaec16/config/p10k-lean.zsh#L920-L930

`anaconda` segment does not:

https://github.com/romkatv/powerlevel10k/blob/4f143b7b978e90ac7f36c77d71eaacc29baaec16/config/p10k-lean.zsh#L901-L904

**Comment by romkatv** [comment]
Does your last comment mean you've figured out the solution?

**Comment by XuehaiPan** [comment]
> Does your last comment mean you've figured out the solution?

Not quietly. One more question: why it's different between `conda`-seg and `pyenv`-seg.

**Comment by romkatv** [comment]
For historical reasons I suppose.

Have you solved the original problem?

**Comment by XuehaiPan** [comment]
> Have you solved the original problem?

Yes, I guess. By adding `P9K_CONTENT` to `POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION`.

**Comment by romkatv** [comment]
Great! Closing then.
