### ISSUE TITLE
GIT status flag seems to be a command behind?

### ISSUE THREAD

**Issue by th3fallen** [romkatv/powerlevel10k#1747]
When doing something like a git reset --hard my git flag shows there are still changed files until I run any other command

![](https://p181.p1.n0.cdn.getcloudapp.com/items/kpu4WByN/87a704dd-3c86-4db0-abb2-eb67e70fdb66.jpg?v=19c377b07de555c157ae9b75f875e157)
![](https://p181.p1.n0.cdn.getcloudapp.com/items/d5uNnlzn/5ae5c1a4-85b3-4315-b6cf-021ce92c030a.jpg?v=473dec72c38565c692906bcd52d05509)

not sure what logs would be helpful for this issue?

**Comment by th3fallen** [comment]
per other issues similar to this one it' looks like you want the output of ```(
  emulate -L zsh -o xtrace -o err_return
  typeset -m 'ZSH_VERSION|ZSH_PATCHLEVEL'
  zsh --version
  git --version
  git config -l
  git status --ignore-submodules=dirty
  git status --ignored
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    zsh -feic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
      gitstatus_query MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    rm -rf $tmp
  }
) &>~/gitstatus.txt```

[gitstatus.txt](https://github.com/romkatv/powerlevel10k/files/7971556/gitstatus.txt)

**Comment by romkatv** [comment]
I'm really swamped right now. There is very low chance I'll be looking at this issue.

**Comment by th3fallen** [comment]
no worries, just wanted to report it for visibility. thanks for the honesty.

**Comment by romkatv** [comment]
Closing because I don't intend to debug this.
