### ISSUE TITLE
powerlevel10k: rainbow theme cuts off the last character of the branch name

### ISSUE THREAD

**Issue by enkeyz** [romkatv/powerlevel10k#1748]
As you can see, the 'n' character missing from the branch name when using rainbow theme.

![image](https://user-images.githubusercontent.com/17646853/151864770-b14147a4-0fdc-4953-b761-eeba04be0186.png)

Same thing with blurred head:
![image](https://user-images.githubusercontent.com/17646853/151865175-783efaad-650e-4bd0-99ff-d7fafc1fdfc2.png)

**Comment by romkatv** [comment]
Wow, that looks terrible.

I'm really swamped right now. I'm afraid I won't be able to look into this issue.

**Comment by enkeyz** [comment]
> Wow, that looks terrible.
> 
> I'm really swamped right now. I'm afraid I won't be able to look into this issue.

No worries, I'll just use the lean version for now.

**Comment by romkatv** [comment]
I should note that rainbow works fine for hundreds of thousands of people. There must be something unique to your config/os/machine that breaks it.

**Comment by enkeyz** [comment]
Found the issue: Manjaro uses the outdated zsh-theme-powerlevel10k package instead of zsh-theme-powerlevel10k-git.

**Comment by romkatv** [comment]
great 👍 

closing
