### ISSUE TITLE
[FEATURE REQUEST] Allow for configurations to be kept separate

### ISSUE THREAD

**Issue by jasonlyle88** [romkatv/powerlevel10k#1753]
I was recently in the situation where my cat decided to attack my keyboard and he messed up several configuration files. When I went back to reconstruct things, I found it rather difficult to discern what were my customizations and what all was just the standard out of the box powerlevel10k configurations from the configuration wizard.  I knew I had customized how certain things were displayed in the prompt, and modified a couple other things after the wizard... but there was not easy way to figure out what was what.

So, I just completely redid everything.

In doing so, I created two new files: `.p10k.pre.zsh` and `.p10k.post.zsh`. I then conditionally source these two files based on their existence.

I'll admit, right now, I'm not using the `.p10k.pre.zsh` for anything. However, all of my customizations are in the `.p10k.post.zsh` and it is very easy to identify my changes this way.

I just have a the following line at the beginning of my `.p10k.zsh`
`[[ -f "${HOME}/.p10k.pre.zsh" ]] && source "${HOME}/.p10k.pre.zsh"`

and this following line as the last thing in my `.p10k.zsh`
`[[ -f "${HOME}/.p10k.post.zsh" ]] && source "${HOME}/.p10k.post.zsh"`

I would also imagine the configuration wizard would want to look for the existence of these files and add a .bak or .old extension so they weren't executed with new runs and mess up the configurations from the wizard.

I would be open to other suggestions/methods to doing this, but I believe having a formal and dedicated place to keep these customizations would be a very nice feature to include!

**Comment by romkatv** [comment]
If you have a git repo for dotfiles, you can add the initial version of `~/.p10k.zsh` to it and then make your changes. This way you'll have the diff in a separate commit and will be able to cherry-pick that on top of a different base.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here.

**Comment by romkatv** [comment]
I'm not against it, I simply don't intend to work on it.

**Comment by jasonlyle88** [comment]
Fair enough! Can I take that to mean you would be open to a pull request that would implement this?
