### ISSUE TITLE
where a prompt style

### ISSUE THREAD

**Issue by Ryangithub10** [romkatv/powerlevel10k#1754]
hello author, i'm a your powerlevel10k user, and i want to ask you, where the prompt style, i mean i was install a powerlevel10k and configured, but i'm realized there is no configure for prompt style while configurating and i look other p10k user and they has prompt style. i don't know it's bug or what but please the help and sorry if my grammar not perfect, i'm not from england/amerika

**Comment by romkatv** [comment]
I don't understand what you are asking. Can you post a screenshot and explain what's wrong on it?

**Comment by Ryangithub10** [comment]
well, I thought you wouldn't understand
but, **I mean like this**

![Prompt style picture](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/p10k-configure-style.png)

but while i configure it, prompt style menu not showing or in otherword **disappear!**
and i'm just get lean style.

i hope you understand what i saying to you

**Comment by romkatv** [comment]
Can you post a screenshot of the problem?

**Comment by romkatv** [comment]
Perhaps you mean this? https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
