### ISSUE TITLE
Question about p10k element in prompt

### ISSUE THREAD

**Issue by franck-paul** [romkatv/powerlevel10k#1757]
What does mean this (right side) :  `3.6.4 followed by an unknown icon/character`, as in:
![sc-2022-02-08_10-21-13_PM2](https://user-images.githubusercontent.com/307049/153077752-cbd26a0f-87b7-4219-b139-231e2566f345.jpg)

And is there any list of all icons/characters and their signification?

By the way your theme is awesome!

**Comment by franck-paul** [comment]
Find it. It's the python version defined by ~/.python-version file.

The second question remains open.

**Comment by romkatv** [comment]
> And is there any list of all icons/characters and their signification?

Nope.

**Comment by franck-paul** [comment]
Thanks for answer!
