### ISSUE TITLE
is there a way to change prompt size only?

### ISSUE THREAD

**Issue by leeyoyo49** [romkatv/powerlevel10k#1759]
powerlevel10k worked perfectly well in my zsh terminal. 
However when I switched to vscode to open zsh, this gap between the prompt and segment appeared.
![截圖 2022-02-09 下午5 05 35](https://user-images.githubusercontent.com/51472776/153163490-828cf710-2fca-4b8a-9f00-9dd6bc8bcac7.png)
I tried changing font size/ line height in the vscode setting but it just doesn't work.
So, is there any way to increase the size of the prompt only?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols
