### ISSUE TITLE
Terminal freezes for seconds after entering a new directory

### ISSUE THREAD

**Issue by wornbb** [romkatv/powerlevel10k#1761]
Issue description:
Whenever I `cd` into a "new directory", the terminal will first display the prompt with git status loaded (very fast) then freeze for a few seconds. During the frozen period, the terminal does not respond to any user input. Most of the inputs during this period would be executed after a few seconds. However, the only exception I have found is `ctrl + c` shortcut. This shortcut will be ignored.

If I `cd` back to an "old directory" then everything is blazing fast. I am using zsh with tmux, so the "old" directory means the directories I have visited in this tmux panel. The frozen period will reappear if I open a new panel even if I am visiting a directory that's "old" to another panel.

I can reproduce this issue with or without tmux, with or without git status in my prompt by removing `vnc`, with various terminals, with or without instant prompt. It only happens if I `source ~/path/p10k.zsh-theme` which means it does NOT happen with vanilla zsh or with only instant prompt.

How to reproduce:
This issue only happens on my company's hosted machine where both the user home directory and workspace are NFS. I am able to reproduce the issue consistently with minimal configuration in my `.zshrc`. For minimal, I mean only lines to enabled instant prompt, source the `.p10k.zsh` and source the theme plugin.

Environment:
I am using zsh 5.8 installed in a NFS location and it cannot be set to my system default shell. I launch the shell by editing `.tmux.config`

**Comment by romkatv** [comment]
Does this issue reproduce with the following `.zshrc`?

```zsh
if [[ ! -e ~/powerlevel10k ]]; then
  git -C ~ clone --depth=1 https://github.com/romkatv/powerlevel10k.git
fi

POWERLEVEL9K_MODE=ascii
POWERLEVEL9K_DISABLE_HOT_RELOAD=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(prompt_char)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

source ~/powerlevel10k/powerlevel10k.zsh-theme
```

**Comment by romkatv** [comment]
If it does, try adding `POWERLEVEL9K_INSTANT_PROMPT=off`. Does it still reproduce?

**Comment by wornbb** [comment]
Yes to both suggestions. 
Notably, after adding `POWERLEVEL9K_INSTANT_PROMPT=off`, the old directories start to freeze even after the initial freeze. The subsequent freezes are shorter, though. It seems the instant prompt is helping to eliminate the subsequent freezes.

**Comment by romkatv** [comment]
What's the output of `${XDG_CACHE_HOME:-~/.cache}`? Is it on NFS? If yes, what happens if you add `export XDG_CACHE_HOME=/some/writable/directory/on/local/disk` at the top of `~/.zshrc`? Replace the path as appropriate.

**Comment by wornbb** [comment]
Thanks! It solves my problem!
