### ISSUE TITLE
Remove Prompt Symbol after Typing Command

### ISSUE THREAD

**Issue by CharlesARoy** [romkatv/powerlevel10k#1764]
Hello,

Just a quick question. Is there a way to stop showing the prompt symbol after typing commands?

For example, whether I use a transient prompt or not, after typing a command, the symbol remains. When using the NeoVim terminal, if I want to repeat an old command, I can easily yank it and paste it, but the prompt symbol is included which gets in the way.

![Prompt_example](https://user-images.githubusercontent.com/46253001/153513035-e57af1ad-4f8f-4078-b517-167a2e902bda.gif)

**Comment by romkatv** [comment]
How about this?

```zsh
POWERLEVEL9K_TRANSIENT_PROMPT=always
POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION=
```

It'll leave a space though. You can try this instead:

```zsh
POWERLEVEL9K_TRANSIENT_PROMPT=off
p10k-on-pre-prompt()  p10k display '1|2'=show
p10k-on-post-prompt() p10k display '1|2'=hide
```

This will remove prompt completely.

P.S.

The standard solution to this problem is to press <kbd>Ctrl+R</kbd>.

**Comment by CharlesARoy** [comment]
Thanks for the help Roman! The second option was exactly what I wanted.
