### ISSUE TITLE
git prompt broken with some (multiline?) git config

### ISSUE THREAD

**Issue by desbma** [romkatv/powerlevel10k#1766]
When I add this in my git config (this is to configure the delta pager output, see https://github.com/chtenb/delta/commit/603b80724200b31a35ac6bed6f9e160b922e0f40 for context):
```
[delta]
    minus-style = syntax "#330f0f"
    minus-emph-style = syntax "#4f1917"
    plus-style = syntax "#0e2f19"
    plus-emph-style = syntax "#174525"
    map-styles = \
       bold purple => syntax "#330f29", \
       bold blue => syntax "#271344", \
       bold cyan => syntax "#0d3531", \
       bold yellow => syntax "#222f14"
    zero-style = syntax
    whitespace-error-style = "#aaaaaa"

```

The git prompt does not show anymore. If I run `killall gitstatusd` it shows again, but will not on the next terminal. 
If I has to guess I'd say `gitstatusd` fails to parse the multiline configuration entry.
Of course the git configuration is perfectly valid and git works as expected.

Thanks

**Comment by desbma** [comment]
If that helps, when I manually sdend a command to gitstatusd, it outputs this error:

```
ERROR src/repo_cache.cc:66] git_repository_open_ext: "[removed].git/": failed to parse config file: invalid configuration key (in /home/desbma/.config/git/config:49)
```

**Comment by romkatv** [comment]
This is probably an issue with libgit2. Can you check whether `lg2 status` works? You'll need to compile lg2 from sources. It's in example, I think.

**Comment by desbma** [comment]
`lg2 status` works (libgit commit 416f7cb34762a75ae2ca14959caa59d94bc14919)

**Comment by romkatv** [comment]
Thanks for the details. So either there was a bug in libgit2 and it's got fixed (in which case I'll need to upgrade libgit2 dependency of gitstatusd) or I introduced a bug in my fork of libgit2 (in which case I would need to fix it).

I'm afraid I don't currently have time to do either for these. Maybe at some point in the future.

**Comment by iamhsa** [comment]
.

**Comment by romkatv** [comment]
Thanks for doing all the work here. I've cherry-picked the commit you've identified and released a new version of gitstatusd. Please update powerlevel10k and let me know whether the issue is resolved.

**Comment by desbma** [comment]
It's fixed, thanks.

**Comment by romkatv** [comment]
Thanks for verifying.
