### ISSUE TITLE
Cannot create /.p10k.zsh

### ISSUE THREAD

**Issue by leslieamartinez** [romkatv/powerlevel10k#1768]
This is the error I am getting when running **p10k configure**. My user account has ownership of these files. I tried backing up .p10k.zsh and removing that original. Same error any suggestions? Thanks

**p10k configure: cannot create /.p10k.zsh because / is readonly**

.rw-rw-r-- .p10k-ascii-8color.zsh
.r--r--r--    .p10k-ascii-8color.zsh.zwc
.rw-rw-r-- .p10k.zsh
.r--r--r--     .p10k.zsh.zwc

**Comment by romkatv** [comment]
The directory needs to be writable.

**Comment by leslieamartinez** [comment]
What directory is it writing to in /home/username?

**Comment by romkatv** [comment]
The algorithm for choosing which file to write is as follows:

1. If `POWERLEVEL9K_CONFIG_FILE` is defined, write to that.
2. Else if `ZDOTDIR` is defined, write to `$ZDOTDIR/.p10k.zsh`.
3. Else write to `~/.p10k.zsh`.

Since it tries to write to `/.p10k.zsh`, it means that either:

1. `POWERLEVEL9K_CONFIG_FILE` is set to `/.p10k.zsh`.
2. Or `ZDOTDIR` is set to `/`.
3. Or `HOME` is set to `/`.

**Comment by leslieamartinez** [comment]
That is strange my p10k.zsh has always been in my home directory. Not to often that I use `configure` so it must of changed at some point. You are correct though `POWERLEVEL9K_CONFIG_FILE` is now set to root. I could set it in .zshrc but where is this variable set so I can change it there. Thanks for your help.

**Comment by romkatv** [comment]
`.p10k.zsh` produced by the configuration wizard sets `POWERLEVEL9K_CONFIG_FILE` to itself.

**Comment by romkatv** [comment]
If you are sourcing `.p10k.zsh` through some unusual means, you'll need to modify that file to set `POWERLEVEL9K_CONFIG_FILE` correctly. Better yet, source `.10k.zsh` normally with `source ~/.p10k.zsh`.

**Comment by leslieamartinez** [comment]
I believe z4humans is sourcing `.p10.zsh`.

**Comment by romkatv** [comment]
OK.

Were you able to resolve this issue with the information I provided?

**Comment by leslieamartinez** [comment]
I set `POWERLEVEL9K_CONFIG_FILE=$HOME` in .zshrc.

[ERROR] p10k configure: ~ is a directory

**Comment by romkatv** [comment]
The error message is correct. `$HOME` (a.k.a. `~`) is a directory, not a file. You want this instead:

```zsh
POWERLEVEL9K_CONFIG_FILE=~/.p10k.zsh
```
