### ISSUE TITLE
unable to change color of unstaged symbol (exclamation mark)

### ISSUE THREAD

**Issue by cridemichel** [romkatv/powerlevel10k#177]
unstaged symbol for git status is actually yellow but with a white background it is almost unreadable and I was not able to change it by issuing:
```zsh
typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STASH_FOREGROUND="green"
```

thank you in advance for your help

best Cristiano

**Comment by romkatv** [comment]
If your config was generated by the configuration wizard, open `~/.p10k.zsh` and find these lines:

https://github.com/romkatv/powerlevel10k/blob/49063ee757c2339c2a0cde14e886896373cd6a54/config/p10k-lean.zsh#L302-L303

`227` is the color. You can change it to something else. To pick a good color, see:

https://github.com/romkatv/powerlevel10k/blob/49063ee757c2339c2a0cde14e886896373cd6a54/config/p10k-lean.zsh#L4-L6

If you wrote your config manually, you can do this:

```zsh
typeset -g POWERLEVEL9K_VCS_MODIFIED_UNSTAGED_FOREGROUND="green"
```

P.S.

p10k looks better on dark background. Almost no one uses light background nowadays, so I don't optimize for it.

**Comment by cridemichel** [comment]
> If your config was generated by the configuration wizard, open `~/.p10k.zsh` and find these lines:
> 
> https://github.com/romkatv/powerlevel10k/blob/49063ee757c2339c2a0cde14e886896373cd6a54/config/p10k-lean.zsh#L302-L303
> 
> `227` is the color. You can change it to something else. To pick a good color, see:
> 
> https://github.com/romkatv/powerlevel10k/blob/49063ee757c2339c2a0cde14e886896373cd6a54/config/p10k-lean.zsh#L4-L6
> 
> If you wrote your config manually, you can do this:
> 
> ```shell
> typeset -g POWERLEVEL9K_VCS_MODIFIED_UNSTAGED_FOREGROUND="green"
> ```
> 
> P.S.
> 
> p10k looks better on dark background. Almost no one uses light background nowadays, so I don't optimize for it.

I used the wizard  and by changing the line you pointed out it worked!
Thank you very much for the very prompt reply and congratulations for your fantastic
powerlevel10k!!

best C.

**Comment by romkatv** [comment]
> I used the wizard and by changing the line you pointed out it worked!

Good.

I went over all colors in the default configs and changed the ones that are difficult to see with white or solarized-light background. If you update powerlevel10k, restart zsh and run configuration wizard again, everything should look good without any additional configuration changes.

> Thank you very much for the very prompt reply and congratulations for your fantastic
> powerlevel10k!!

Thanks!

**Comment by eddyg** [comment]
> p10k looks better on dark background. Almost no one uses light background nowadays, so I don't optimize for it.

FWIW, I manually tweak **p10k** for a light background (which is somewhat of a pain, since I often pull your latest changes). Light backgrounds are _much_ more popular than you think*. I honestly wish there were separate light/dark color settings with a simple flag to toggle which one was active.

* see: https://www.quora.com/Which-is-better-for-the-eyes-a-white-background-with-black-text-a-black-background-with-white-text-or-sepia-mode and https://tidbits.com/2019/05/31/the-dark-side-of-dark-mode/

**Comment by romkatv** [comment]
@eddyg 

> FWIW, I manually tweak **p10k** for a light background

Could you share your config?

> (which is somewhat of a pain, since I often pull your latest changes).

FWIW, you don't have to update your config when I change the defaults. You can keep your config forever and your prompt won't break or change in any way when you update powerlevel10k.

**Comment by cridemichel** [comment]
thank you again!!
I try it out right now
