### ISSUE TITLE
mathfunc.so failed to load

### ISSUE THREAD

**Issue by dutchsnowden** [romkatv/powerlevel10k#1770]
/home/ownusername/.zsh/powerlevel10k/internal/p10k.zsh:9161: failed to load module `zsh/mathfunc': /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/x86_64-linux-gnu/zsh/5.8.1/zsh/mathfunc.so)

Since today I got this error. Is there anything that I can do about it other than reinstall?

**Comment by romkatv** [comment]
Looks like something is broken in your OS. Here's the command that you need to fix:

```zsh
zsh -fc 'zmodload zsh/mathfunc'
```

I don't know how you can fix it. It's not specific to powerlevel10k.

**Comment by dutchsnowden** [comment]
My ubuntu is definitely not broken. Most probably powerlevel10k is not compatible to yesterday's 22.04 dev upgrades. Autoremove got rid of some libs not used anymore, and it seems powerlevel10k used those in fact.


`❯ lsb_release -a
LSB Version:    core-11.1.0ubuntu3-noarch:security-11.1.0ubuntu3-noarch
Distributor ID: Ubuntu
Description:    Ubuntu Jammy Jellyfish (development branch)
Release:        22.04
Codename:       jammy`

**Comment by dutchsnowden** [comment]
`❯ grep remove /var/log/dpkg.log
2022-02-01 05:56:35 startup packages remove
2022-02-01 05:56:35 remove linux-headers-5.13.0-19:all 5.13.0-19.19 <none>
2022-02-06 20:21:12 startup packages remove
2022-02-06 20:21:12 remove libfl2:amd64 2.6.4-8build1 <none>
2022-02-06 20:21:12 remove libwebp6:amd64 0.6.1-2.1build1 <none>
`

**Comment by dutchsnowden** [comment]
❯ sudo apt list libc-bin
        Listing... Done
        libc-bin/jammy,now 2.34-0ubuntu3 amd64 [installed,automatic]
        libc-bin/jammy 2.34-0ubuntu3 i386

**Comment by dutchsnowden** [comment]
I guess you are right and it's a zsh dependancy problem. You can close this down, and sorry about it.

**Comment by dutchsnowden** [comment]
Yes, reinstalling zsh did nothing, still does not load that module, so while I will wait for not-broken zsh update, I just disabled the loading of module from p10k file. I am not using it anyway.

**Comment by killjoy1221** [comment]
libc6 was recently updated to 2.35 on ubuntu 22.04. The seems to have fixed the warning.

**Comment by dutchsnowden** [comment]
I agree. It was solved by update few days ago. Thank you so so much for your help!
