### ISSUE TITLE
My configuration wizard is different from others

### ISSUE THREAD

**Issue by rousseauuu** [romkatv/powerlevel10k#1771]
After typing `p10k configure` , the following scene appears:

![image](https://user-images.githubusercontent.com/61789557/154049603-3ad80ad1-6a59-4e26-b20b-b377907f3d83.png)
Obviously this is very different from other people's wizard.
I want to use this theme on ArchLiux(WSL).
I have installed `MesloLGS NF` font and set it as my Windows Terminal's default font.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
