### ISSUE TITLE
show icons for php, node.js, ruby version

### ISSUE THREAD

**Issue by StandardNerd** [romkatv/powerlevel10k#1772]
On my right hand side the php-, laravel-, node.js, and ruby version are shown but just the version number:

![image](https://user-images.githubusercontent.com/142894/154089810-7d52efd6-00ce-4f87-83bf-279c64dd1435.png)

How can I modify it with an icon/symbol that indicates the languages?

~/.p10k.zsh
`                                                                                                         
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(                                                                                           
    php_version                                                                                                                             
    laravel_version                                                                                                                         
    node_version                                                                                                                            
    ruby_version                                                                                                                            
  )     
  `

**Comment by panchalkalpesh** [comment]
@StandardNerd  Are you able to see any Icons when you run:
```
p10k configure
```

**Comment by StandardNerd** [comment]
I could resolve this issue by reinstalling p10k. thanks!
