### ISSUE TITLE
?9 characters on right side of prompt elements

### ISSUE THREAD

**Issue by jkergal** [romkatv/powerlevel10k#1773]
Hello!

First, thank you so much for the beautiful work you did on this tool!

I've got an issue configuring powerlevel10k, there is some weird characters "?9" appearring on the right side of prompt elements :

![image](https://user-images.githubusercontent.com/89657288/154286264-a0379762-6395-4d4b-8d07-8fae6238859e.png)

Have you got any idea? Thank you in advance!

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by jkergal** [comment]
thank you so much for your help 💯
