### ISSUE TITLE
Truncate folders to current folder

### ISSUE THREAD

**Issue by Firestar-Reimu** [romkatv/powerlevel10k#1774]
https://github.com/romkatv/powerlevel10k/issues/493

I want to truncate to current folder, what should I do, does p10k support this?

-   Full: `~/work/project/src/backend`
-   Completely shortened: `~/w/p/s/backend`
-   With important directories not shortened: `~/w/project/s/backend`
-  **What I want: `backend`**

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_SHORTEN_FOLDER_MARKER` and change its value to `truncate_to_last`.

**Comment by dansanduleac** [comment]
Shouldn't this be `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last`?

**Comment by romkatv** [comment]
@dansanduleac Indeed.

**Comment by scratchmex** [comment]
I do not see `POWERLEVEL9K_SHORTEN_STRATEGY` in `~/.p10k.zsh`. What am I missing?

**Comment by romkatv** [comment]
I can think of many reasons. They would fall in these rough categories:

1. It's not being visible. For example, your monitor is turned off, or the file isn't open in an editor, or the editor isn't showing the right part of the file.
2. Something prevents you from seeing it. Things like lack of light, or closed eyes.
3. This string is actually missing from the file.

There could be more.

**Comment by scratchmex** [comment]
I don't know if you are joking but the actual problem was that I was using the pure style instead of lean. Thank you for the reply

**Comment by romkatv** [comment]
That would be (3) form my list.

I was half joking. What kind of reply did you expect?

P.S.

Lean style is better than Pure on all accounts. Pure exists for users who are used to https://github.com/sindresorhus/pure. It's a complete emulation of that theme.
