### ISSUE TITLE
Remove Right Prompt

### ISSUE THREAD

**Issue by DonCammne** [romkatv/powerlevel10k#1776]
I'm using Manjaro with Pop Shell (tiling window) and when I open a new window, the terminal resize and the classic zsh bug appears. I read that a pacth for zsh is available but I don't know how to install it, thus I thought to solve the problem by removing the right prompt from powerlevel10k.
I followed the instruction from this thread https://github.com/romkatv/powerlevel10k/issues/175 and comment out all elements of 
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS but the current time shows anyway on the right.
How can I remove the right prompt correctly? Is there another solution for this resize issue?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#mitigation
