### ISSUE TITLE
Misplaced Slash Separator on Right Side

### ISSUE THREAD

**Issue by gsemaj** [romkatv/powerlevel10k#1777]
I installed this theme with the recommended font and configured my prompt to use the slash separator style. For some reason, the right side of the prompt makes it look like the separator is one character too far to the left.
![image](https://user-images.githubusercontent.com/5123173/154539227-0c8e7a82-79fa-4b4a-8815-4f2e0cbaaf1d.png)
I couldn't find any issues related to this, but the screenshots on the repo don't seem to show this issue. For additional context, I'm running this on WSL2 in Windows Terminal with font size 11. I can include the rest of my configuration if that's not enough.

Sorry if this issue is poorly phrased, I'm new to ZSH configuration!

**Comment by romkatv** [comment]
Please run `p10k configure` and when it asks you whether all icons fit between the crosses answer *Yes* (because they do).

**Comment by gsemaj** [comment]
Ahhh ok, they were super tight so I thought I was taking the safe route. Thanks for the clarification!

**Comment by romkatv** [comment]
On that screen the wizard is essentially asking whether you font is monospace. Yours is. With non-monospace fonts p10k has to insert extra spaces at some points.

**Comment by romkatv** [comment]
By the way, your terminal will look better if you make the background darker.

**Comment by gsemaj** [comment]
Thanks again! My terminal is translucent, and I took that screenshot against a lighter background. Still messing with the opacity settings :)
