### ISSUE TITLE
[Feature Request] Change what is shown and what isn't, when entering an smb folder

### ISSUE THREAD

**Issue by Auravendill** [romkatv/powerlevel10k#1778]
I've noticed, that when I enter a folder, that is connected via smb, that the prompt gets ridiculously long and the interesting information gets shortened, while the in my eyes less important stuff stays.

This looks e.g. like this:
     /run/us/1/gv/smb-share:server=vault-tec-media,share=e/B/Exa/example Folder    main !40 ?8

If I could suggest how it should look like, I would say like this:
    smb:vault-tec-media e/Bilder/Example/example Folder    main !40 ?8

The way it currently is, the left part is taking up 2/3 of a line, when I use it on my smaller monitor (HD+) and abbreviates the folder names.

**Comment by romkatv** [comment]
You can create a named directory:

```zsh
hash -d smb='/run/us/1/gv/smb-share:server=vault-tec-media,share=e'
```

This should go into `~/.zshrc`. Replace the path with the right path.

**Comment by Auravendill** [comment]
I've added that into my .zshrc, but I doesn't seem to change anything. Does it have to be in a certain position within the file? Or am I missing something else?

**Comment by romkatv** [comment]
It can be anywhere but you need to specify the path correctly. Once you put it in `~/.zshrc`, restart zsh with `exec zsh`.

**Comment by Auravendill** [comment]
Ah, I found the issue, the path was shortened in that part as well. So the real entry is: `hash -d smb='/run/user/1000/gvfs/smb-share:server=vault-tec-media,share=e'`

The result looks like this: `    ~smb/Bilder    main !40 ?8 ` Idk why it inserts a ~ before smb, but I guess a single char is too minor to care about, isn't it?

Shall I close the issue?

**Comment by romkatv** [comment]
Note that `~smb` is a full-fledged bidirectional alias similar to how `~` is an alias for you home directory. You can type `cd ~smb` or `ls ~smb/B<TAB>` and it'll work. This is a zsh feature. It's not specific to powerlevel10k.
