### ISSUE TITLE
Configuration help with context

### ISSUE THREAD

**Issue by 5u623l20** [romkatv/powerlevel10k#178]
I am not sure whether if my issue is related to #170 but I just need some help with the configuration. My requirement is simple:
1. If the user is non-root print %n in fg[red]
Done with "POWERLEVEL9K_CONTEXT_FOREGROUND=009"
2. If the user is root print %n in fg[green]
Done with "POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=010"
3. If any of the above is remotely logged in print %n@%M in respective color based on USER.
Unfortunately I cannot make this happen. I have tried with POWERLEVEL9K_ALWAYS_SHOW_USER=true which should conditionally add the hostname but no luck.
❯ typeset -m 'USER|DEFAULT_USER|_P9K_SSH|POWERLEVEL9K*_CONTEXT*|ALWAYS'
DEFAULT_USER=subzero
POWERLEVEL9K_CONTEXT_TEMPLATE=%n
POWERLEVEL9K_CONTEXT_REMOTE_CONTENT_EXPANSION=%n@%M
POWERLEVEL9K_CONTEXT_REMOTE_TEMPLATE=%n@%M
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=010
_P9K_SSH=1
POWERLEVEL9K_CONTEXT_FOREGROUND=009
USER=root

**Comment by romkatv** [comment]
I'll paraphrase.

- Always show username.
- Show host if and only if connected over SSH.
- Red if not root, green if root.

Is this what you want?

**Comment by 5u623l20** [comment]
Right. So far the following works for me:
1. DEFAULT_USER gets %n when logged in locally with red
2. DEFAULT_USER gets %n@%M when logged in remotely with red
3. root always gets %n@%m in both the cases in green.

**Comment by romkatv** [comment]
> Right. So far the following works for me:
> 
> 1. DEFAULT_USER gets %n when logged in locally with red
> 2. DEFAULT_USER gets %n@%M when logged in remotely with red
> 3. root always gets %n@%m in both the cases in green.
>    The problem for me is actually with 3 only. The rest works properly.

Could you clarify whether the algorithm I described in https://github.com/romkatv/powerlevel10k/issues/178#issuecomment-522691531 is what you want or not? If it isn't, please specify how it should be changed.

What confuses me is the mention of `DEFAULT_USER`, which doesn't exist in my algorithm. Do you need something special when `$USER` == `$DEFAULT_USER`?

**Comment by 5u623l20** [comment]
> > Right. So far the following works for me:
> > 
> > 1. DEFAULT_USER gets %n when logged in locally with red
> > 2. DEFAULT_USER gets %n@%M when logged in remotely with red
> > 3. root always gets %n@%m in both the cases in green.
> >    The problem for me is actually with 3 only. The rest works properly.
> 
> Could you clarify whether the algorithm I described in [#178 (comment)](https://github.com/romkatv/powerlevel10k/issues/178#issuecomment-522691531) is what you want or not? If it isn't, please specify how it should be changed.
Yes this is what I want.
> 
> What confuses me is the mention of `DEFAULT_USER`, which doesn't exist in my algorithm. Do you need something special when `$USER` == `$DEFAULT_USER`?
No I don't need anything special. But if I don't add DEFAULT_USER="subzero" in .zshrc I am getting %n@%m when I am logged in locally. I might be wrong with my configuration or the concepts. This is just for helping to identify the problem.

**Comment by romkatv** [comment]
This should work:

```zsh
# Context is green if root, red otherwise.
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%F{%(#.green.red)}'
if [[ -n ${SSH_CONNECTION:-} ]]; then
  # When in SSH: username@hostname.
  POWERLEVEL9K_CONTEXT_TEMPLATE+='%n@%m'
else
  # Locally: username.
  POWERLEVEL9K_CONTEXT_TEMPLATE+='%n'
fi
```

The SSH check in p10k is more robust than this but it rarely matters in practice. I'll think how to support this use-case better in p10k but in the meantime this configuration should serve you fine.

**Comment by 5u623l20** [comment]
Yeaps that works but I thought if it could be done through basic configurations. Thanks for the tips.

**Comment by romkatv** [comment]
This configuration should also work and it will take advantage of the robust SSH check implemented in p10k:

```zsh
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=red
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=green
typeset -g POWERLEVEL9K_ALWAYS_SHOW_USER=true
typeset -g DEFAULT_USER="$(whoami)"
```

**Comment by 5u623l20** [comment]
Thanks.
