### ISSUE TITLE
libvterm

### ISSUE THREAD

**Issue by ChauhanT** [romkatv/powerlevel10k#1781]
Hi, 

First, I am a very happy user of powerlevel10k for several years now, and would like to thank you for the effort and time you put into this project - and for sharing it with the community. 

**Issue**
I use powerlevel10k on konsole and it works quite flawlessly. I also use it in emacs through the emacs-libvterm package (https://github.com/akermu/emacs-libvterm#shell-side-configuration) and it worked perfectly up until a few days ago. Recently, I have been getting this error (including only the first and then the final few lines to keep it short) : 
```
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

>>> OMITTED <<<

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

manpath: can't set the locale; make sure $LC_* and $LANG are correct
```
I am not able to figure out what is causing this, despite going through the link in the error message - I re-configured my powerlevel10k but to no avail. I have not messed around with the locale, and I get no such errors on konsole. 

And if this is not the right place for this discussion, please let me know and I will be happy to delete this issue immediately.

Cheers!

**Comment by romkatv** [comment]
Try to disable powerlevel10k temporarily. The error will become more obvious. Or rather it'll be clear that the error is not caused by powerlevel10k. Once you fix it, reenable powerlevel10k.

**Comment by ChauhanT** [comment]
Thanks! Ok, closing. Just needed to regenerate the locales. On Debian (apt-based) systems this would be:
```
sudo dpkg-reconfigure locales
```
Still don't know why they got unset. But life is too short to take on unsolicited challenges of unknown complexity ^_^

Cheers!
