### ISSUE TITLE
[Feature request]: Perlbrew

### ISSUE THREAD

**Issue by lmburns** [romkatv/powerlevel10k#1782]
I see that [`plenv`](https://github.com/tokuhirom/plenv) is supported, but [`perlbrew`](https://github.com/gugod/App-perlbrew) isn't and was wondering if that would be possible?

**Comment by romkatv** [comment]
I'm short on free time and won't be able to work on this in the foreseeable future. If you send a PR with a clean implementation, I'll merge it.

**Comment by romkatv** [comment]
Closed by #1786. Thanks for the contribution!
