### ISSUE TITLE
No icon shown in prompt

### ISSUE THREAD

**Issue by K0923** [romkatv/powerlevel10k#1784]
OS: Arch Linux x86_64 
 Kernel: 5.16.10-arch1-1 
 Utime: 1 hour, 3 mins 
 Packages: 819 (pacman) 
 Shell: zsh 5.8.1 
 Resolution: 1920x1200 
 WM: i3 
 Theme: Adwaita [GTK3] 
 Icons: Adwaita [GTK3] 
 Terminal: konsole 
 CPU: Intel i7-10700K (16) @ 5.100GHz 
 GPU: NVIDIA GeForce RTX 3090 
 GPU: Intel CometLake-S GT2 [UHD Graphics 630] 
 Memory: 805MiB / 64026MB 
 
The configure wizard didn't have the icon setting steps, and no icon shown in the prompt

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
