### ISSUE TITLE
Remove git status numbers and "Py" from the prompt when activating a virtualenv

### ISSUE THREAD

**Issue by briangow** [romkatv/powerlevel10k#1785]
I've been trying to customize my prompt in powerlevel10k to my liking. When activating a virtual environment, my preference would be for the name of the virtual environment to be before the directory in the prompt:

`/dir/ branch status# > source venv_name/bin/activate`
`(venv_name) /dir/ branch status# >`

Where status# are the vcs git status numbers (*num_staged_files |num_unstaged_files ?num_untracked_files). However, based on answers to previous issues I don't think it is possible to move the venv_name before the /dir/. I have been able to achieve this prompt:

`/dir/ branch status# > source venv_name/bin/activate`
`/dir/ Py venv_name branch status# >`

by 
1. moving `virtualenv` from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` 
2. creating this setting near the other `VIRTUALENV` variables: `typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=()`

I would like to know how to remove the "Py" text and the status# from the prompt, leading to this behavior:

`/dir/ branch > source venv_name/bin/activate`
`/dir/ venv_name branch >`

Is this possible?

**Comment by romkatv** [comment]
> However, based on answers to previous issues I don't think it is possible to move the venv_name before the /dir/.

It is possible. Prompt segments appear on screen in the order they are listed in `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.

> I would like to know how to remove the "Py" text [...]

That "Py" is an icon. If you used a font with icons, it would be a python logo, but in your font it's "Py". You can set the icon to an empty string like this:

```zsh
# Custom icon.
typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION=''
```

You should already have this parameter in `~/,p10k.zsh` but you need to uncomment it.

> I would like to know how to remove [...] the status# from the prompt

See https://github.com/romkatv/powerlevel10k#how-do-i-change-the-format-of-git-status

**Comment by briangow** [comment]
Thank you for your quick reply and sorry for the delay from my side. 

> It is possible. Prompt segments appear on screen in the order they are listed in POWERLEVEL9K_LEFT_PROMPT_ELEMENTS

For some reason this doesn't work as described for me - I can't seem to get my environment name to show before the dir. Here is the relevant code from my `.p10k.zsh` file: 

```
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # os_icon               # os identifier
	virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
	dir                     # current directory
    # vcs                     # git status
    # prompt_char             # prompt symbol
  )
```

and a screenshot showing my prompt after activating my python virtual environment:

![image](https://user-images.githubusercontent.com/4754434/156433070-81f7904a-a093-40fc-89f3-688d9443c999.png)

> That "Py" is an icon. If you used a font with icons, it would be a python logo, but in your font it's "Py". You can set the icon to an empty string like this:

That worked as desired!

> See [romkatv/powerlevel10k#how-do-i-change-the-format-of-git-status](https://github.com/romkatv/powerlevel10k#how-do-i-change-the-format-of-git-status)

Thanks I was able to achieve what I wanted by commenting out the variables towards the bottom of `my_git_formatter` (`VCS_STATUS_COMMITS_BEHIND` , etc)

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
typeset -pm '*POWERLEVEL9K_LEFT_PROMPT_ELEMENTS'
```

**Comment by briangow** [comment]
Hmm, it's:

```
typeset -pm '*POWERLEVEL9K_LEFT_PROMPT_ELEMENTS'                                                  3s
typeset -a _POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( context dir virtualenv vcs )
typeset -a POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( context dir virtualenv vcs )
```

**Comment by briangow** [comment]
I figured out why it was showing `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( context dir virtualenv vcs )` even though my `.p10k.zsh` had:
```  
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # os_icon               # os identifier
	virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
	dir                     # current directory
    # vcs                     # git status
    # prompt_char             # prompt symbol
  )
```

When trying to customize this earlier I had added a `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` into my `.zshrc` file. This was overriding the `.p10k.zsh` setting.

**Comment by briangow** [comment]
Yes, thanks for all of the help!
