### ISSUE TITLE
Git Bug - Charactere ?4

### ISSUE THREAD

**Issue by leoberbert** [romkatv/powerlevel10k#1788]
Dear,

After installing powerline and all its dependencies, I'm having problems when I access a git repository. The character below is displayed:

~/.oh-my-zsh   master ?4

![image](https://user-images.githubusercontent.com/16724862/156253220-2c664713-a3fd-430e-9e8d-4d1263d4d8c1.png)

Regards,

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by leoberbert** [comment]
Dear,

Even with this configuration, the problem persists.

![image](https://user-images.githubusercontent.com/16724862/162104943-fcf77382-1d5d-4a7e-9abe-c2793168a6bd.png)

Is there another way to fix this problem?

Regards,

**Comment by romkatv** [comment]
> See https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

☝️
