### ISSUE TITLE
Warning for theme not found but seems to work anyway

### ISSUE THREAD

**Issue by Draawa** [romkatv/powerlevel10k#1790]
Hello,

Everytime I open iTerm, i get the following message :
theme 'powerlevel10k/powerlevel10k' not found

Although, the theme looks loaded to me.
oh my zsh and powerlevel10k are both installed at the root of my home folder as followed by the install instructions here so the path doesn't look wrong to me either.

What did I do wrong ?

**Comment by romkatv** [comment]
You probably have this line in `~/.zshrc`:

```zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
```

You need to remove it.

**Comment by Draawa** [comment]
> You probably have this line in `~/.zshrc`:
> 
> ```shell
> ZSH_THEME="powerlevel10k/powerlevel10k"
> ```
> 
> You need to remove it.

Thanks for your answer, I have it indeed.
Removing it fixed the problem !

Though why is it said in the installation instruction to actually specify this line if not necessary ?

**Comment by romkatv** [comment]
What the installation instructions say is correct but that's not what you've done.
