### ISSUE TITLE
offline install issues on aarch64 device

### ISSUE THREAD

**Issue by greyskysoul** [romkatv/powerlevel10k#1793]
Hi,
I followed(https://github.com/romkatv/powerlevel10k#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access) to install p10k on an offline aarch64 device, still get [fetching gitstatusd...]every time.
This guide works on my x86 pc though.Maybe this is a bug on aarch64?

**Comment by romkatv** [comment]
The instructions should work if you execute them correctly. If you post here all commands that you are running with an indication on which machine you are running each command, I'll be able to tell you which command is incorrect.

**Comment by greyskysoul** [comment]
Sorry, I checked the guide again and solved the problem.It's because I forgot to change the target_uname.
