### ISSUE TITLE
Prompt/Theme does not load in tmux (or neovim Toggleterm) 

### ISSUE THREAD

**Issue by hgoumner** [romkatv/powerlevel10k#1794]
Hello,

first of all I'd like to thank you for the awesome theme. I've been using it for several months now and i really like it.

I'm having an issue when starting a tmux session though. The prompt/theme does not seem to load, although the other zsh plugins do (i'm not using oh-my-zsh). I have to manually "source ~/.zshrc" for the theme to load, as opposed to it happening automatically as expected. Unfortunately i couldn't find anything in the README or in the issues here that could solve my problem. Does anyone have any ideas?

I have this at the top of my .zshrc:

```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

And this at the bottom:

```
# # To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
# typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
```

Thanks in advance.

**Comment by romkatv** [comment]
> I'm having an issue when starting a tmux session though.

How do you start a tmux session?

> The prompt/theme does not seem to load,

What does it mean exactly?

**Comment by hgoumner** [comment]
Thanks for the super fast reply.

I start tmux just by entering the 'tmux' command (i have a tmux config file, here are my dotfiles: [https://github.com/hgoumner/config_repo](https://github.com/hgoumner/config_repo))

And it means that instead of getting the prompt that i have with coloring, git info, batteries, etc. i get the basic prompt, that is:

```[user@work]~%```

**Comment by romkatv** [comment]
What happens if you put the following snippet at the very top of `~/.zshrc`?

```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ ! -e ~/powerlevel10k ]]; then
  git -C ~ clone --quiet --depth=1 https://github.com/romkatv/powerlevel10k.git
fi

source ~/.config/zsh/.p10k.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
return
```

**Comment by hgoumner** [comment]
That works. So should i try sourcing the p10k and the powerlevel files at the top of the .zshrc before loading the other plugins/settings in my .zshrc?

**Comment by hgoumner** [comment]
No need to answer, i already tried it and it works :)

Thanks again for the help and the work you do.

**Comment by romkatv** [comment]
> That works. So should i try sourcing the p10k and the powerlevel files at the top of the .zshrc before loading the other plugins/settings in my .zshrc?

No, you definitely should not.

What that test has established is that powerlevel10k works fine and there is an error in your `~/.zshrc` in the part that you left out. You need to fix that error. If you post your `~/.zshrc` I might help you although I cannot commit to it because it's not really a powerlevel10k issue.

**Comment by hgoumner** [comment]
> > That works. So should i try sourcing the p10k and the powerlevel files at the top of the .zshrc before loading the other plugins/settings in my .zshrc?
> 
> No, you definitely should not.
> 
> What that test has established is that powerlevel10k works fine and there is an error in your `~/.zshrc` in the part that you left out. You need to fix that error. If you post your `~/.zshrc` I might help you although I cannot commit to it because it's not really a powerlevel10k issue.

I found the error. It was not loading the 'powerlevel10k.zsh-theme' because the location where it was looking was not right. I fixed it and now it works. Thanks again :)

**Comment by romkatv** [comment]
Great. Closing as resolved.
