### ISSUE TITLE
Context and Icons not showing on p10k iterm2 MacOS

### ISSUE THREAD

**Issue by gVallverdu** [romkatv/powerlevel10k#1795]
Hi

I open a new issue from #996 . I have go a similar issue. Here is the output of my terminal:

![term1](https://user-images.githubusercontent.com/5417018/157067925-38e96dcc-bfb7-4fbc-8d7e-d63ba7643801.png)

As you can see icons do not display correctly. Nevertheless, you can see that fonts are installed in `/Library/Fonts`. I set MesloLGS in the preferences of iTerm2, but it does not work.

![term2](https://user-images.githubusercontent.com/5417018/157076108-4c4a0272-3955-4855-aaa2-f45fd6c93182.png)

Another point is that context does not appear in the prompt, but I set it in the `.p10k.zsh` at this stage of the file generated from `p10k configure`:

```zsh
  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon               # os identifier
    context                 # use @ hostname
    dir                     # current directory
    vcs                     # git status
    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )
```

Thank you for any help

**Comment by anhthi92** [comment]
How fix this error ? thank u.

**Comment by romkatv** [comment]
Icons: https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render
Context: https://github.com/romkatv/powerlevel10k#how-do-i-add-username-andor-hostname-to-prompt
