### ISSUE TITLE
vscode terminal not showing powerlevel as expected

### ISSUE THREAD

**Issue by Dreamyplayer** [romkatv/powerlevel10k#1797]
I don't know this is a bug or something in my vscode but powerLevel10k not showing as expected or as configured.
works fine in my terminal but not on vscode
- Linux
- elementary os
- vscode-insiders

Normal terminal
![Screenshot from 2022-03-14 12-34-39](https://user-images.githubusercontent.com/33060433/158122100-d36f427b-5109-4a3b-aa37-4c166525d62e.png)

in My vscode terminal
![Screenshot from 2022-03-14 12-32-01](https://user-images.githubusercontent.com/33060433/158122147-9f90c0a3-f295-41f2-88e3-e02bacd0a75d.png)
![Screenshot from 2022-03-14 12-44-46](https://user-images.githubusercontent.com/33060433/158122712-6f342c44-caff-4954-b350-b32e1dba4f0c.png)

- I installed all recommended fonts in my system.

Vscode settings JSON
```json
  "terminal.integrated.fontSize": 15,
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "terminal.integrated.shellIntegration.enabled": true,
  "terminal.integrated.defaultProfile.linux": "zsh",
```

**Comment by romkatv** [comment]
> in My vscode terminal ![Screenshot from 2022-03-14 12-32-01](https://user-images.githubusercontent.com/33060433/158122147-9f90c0a3-f295-41f2-88e3-e02bacd0a75d.png) ![Screenshot from 2022-03-14 12-44-46](https://user-images.githubusercontent.com/33060433/158122712-6f342c44-caff-4954-b350-b32e1dba4f0c.png)

What in your opinion is wrong on this screenshot?

**Comment by Dreamyplayer** [comment]
in terminal screenshot it's not same
in vscode terminal they are overlapping over another with different color after /mika there is  `)` with blue color
and main !3 ?3 not that colors

**Comment by romkatv** [comment]
- Colors: https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors
- Bad powerline rendering: https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by Dreamyplayer** [comment]
i don't understand not working i checked both links 
![Screenshot from 2022-03-14 13-18-48](https://user-images.githubusercontent.com/33060433/158127731-17c30bd2-5c38-4141-8686-a752a95e1d28.png)

**Comment by romkatv** [comment]
The links I posted above provide the best explanation I can muster.

**Comment by Dreamyplayer** [comment]
Okay, i'll try to fix
