### ISSUE TITLE
_p9k_init:hash:121: no such command: tput

### ISSUE THREAD

**Issue by gapplef** [romkatv/powerlevel10k#18]
zsh 5.4.2, Ubuntu 18.04, zplug plugin manager
After replace `zplug "bhilburn/powerlevel9k", use:powerlevel9k.zsh-theme` with `zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme`
It report `_p9k_init:hash:121: no such command: tput` every time open the zsh.
But the theme seems still take effect and works fine.

**Comment by romkatv** [comment]
Thanks for the report. This is now fixed.
