### ISSUE TITLE
Color substitution stopped working

### ISSUE THREAD

**Issue by horseinthesky** [romkatv/powerlevel10k#1800]
I've used this way of cooring my prefixies:
```
DEFAULT_PREFIX_COLOR="#928374"
typeset -g POWERLEVEL9K_{CUSTOM_HOST,VCS}_PREFIX='%F{$DEFAULT_PREFIX_COLOR}on '
typeset -g POWERLEVEL9K_DIR_PREFIX='%F{$DEFAULT_PREFIX_COLOR}in '
typeset -g POWERLEVEL9K_VIRTUALENV_PREFIX='%F{$DEFAULT_PREFIX_COLOR}via '
typeset -g POWERLEVEL9K_PYENV_PREFIX='%F{$DEFAULT_PREFIX_COLOR}via '
typeset -g POWERLEVEL9K_BATTERY_PREFIX='%F{$DEFAULT_PREFIX_COLOR}at '
```
for a several years now.

Haven't updated p10k for a long time. It stopped using the `DEFAULT_PREFIX_COLOR` color for prefixes.

Putting the value like:
```
typeset -g POWERLEVEL9K_DIR_PREFIX='%F{#928374}in '
```
works though.

What am I doing wrong? Can I make it use the color from a variable? Thank you.

**Comment by horseinthesky** [comment]
@romkatv That helped. Thank you. I wonder what made it change the behavior.

**Comment by romkatv** [comment]
I've fixed a bug there. The expansion wasn't intended.
