### ISSUE TITLE
How Shorten os_icon ？

### ISSUE THREAD

**Issue by xiaobao996** [romkatv/powerlevel10k#1805]
How to customize the width on both sides of os_icon ？
How to customize the width on both sides of context ？

**Comment by romkatv** [comment]
What does "width on both sides" mean?

**Comment by xiaobao996** [comment]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/25027918/159002833-5b08f852-d901-4b36-b144-1cdc0f22f011.png">
how  Shorten red  circle ?

**Comment by romkatv** [comment]
Are you asking how to remove spaces around Apple logo? If so, replace `os_icon` and `context` with `os_icon_joined` and `context_joined` respectively.

**Comment by xiaobao996** [comment]
Perfect! Thank you very much.
Is there a document for all parameters ?

**Comment by romkatv** [comment]
> Is there a document for all parameters ?

No, there isn't.
