### ISSUE TITLE
icons in my terminal don't look like the document. I tried rerunning the p10k configure several time not fixing the issue.

### ISSUE THREAD

**Issue by devrang** [romkatv/powerlevel10k#1806]
Please see attached screenshot.  ~ 

issue is p10K configure wizard, is not prompting to install Meslo. I installed it via brew but I'm not seeing same thing as the font as in install instruction.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by devrang** [comment]
This instruction resolved the issue. https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k

**Comment by devrang** [comment]
Follow this step if you are having the same issue. https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k
