### ISSUE TITLE
[Feature request] minimize automatically generated p10k configuration

### ISSUE THREAD

**Issue by thegoldgoat** [romkatv/powerlevel10k#1807]
Have an option to automatically remove comments and empty lines from `~/.p10k.zsh` automatically generated configuration

```
❯ ll original.zsh
-rw-r--r-- 1 andrea andrea 84K Mar 19 09:49 original.zsh

~ ············································································································ 09:53:49
❯ ll .p10k.zsh
-rw-r--r-- 1 andrea andrea 21K Mar 19 09:51 .p10k.zsh
```

84K vs 21K just with:

```bash
sed '/^[[:blank:]]*#/d;s/#.*//' -i ~/.p10k.zsh
sed '/^$/d' -i ~/.p10k.zsh
```

While I am not sure if it this has any significant performance improvement, I guess most people don't need to look at the automatically generated configuration, hence it can be minified

**Comment by romkatv** [comment]
> While I am not sure if it this has any significant performance improvement

It doesn't.

> I guess most people don't need to look at the automatically generated configuration

Probably true.

> hence it can be minified

Can be, yes. Should be?

Anyway, it's not something I would implement or merge.

**Comment by thegoldgoat** [comment]
> Anyway, it's not something I would implement or merge.

I see, thanks anyway for the response :)
