### ISSUE TITLE
Customize already set 'Segments'

### ISSUE THREAD

**Issue by besnija** [romkatv/powerlevel10k#1809]
Hi there,

First I'd like to thank you so much for this best-of-the-line prompt. It is ahead of its time!

It would be great if there were a way to customize the already (not user set) set segments with the `p10k segment` command. What I wanted to do was simply add a `%B` so the text of some segments is bolded without having to change the font or meddle with the `~/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh`.
Now I've accomplished to add some on the `~/.p10.zsh` but others like the `Segment to diplay Node version` or the `GO prompt` I just couldn't do without making the git file "dirty", so as a workaround I've copied these segment conf's to my `~/.zshrc` file and added in the necessary `%B`.

An example:

```
prompt_go_version() {
    _p9k_cached_cmd 0 '' go version || return
    [[ $_p9k__ret == (#b)*go([[:digit:].]##)* ]] || return
    local v=$match[1]
    if (( _POWERLEVEL9K_GO_VERSION_PROJECT_ONLY )); then
      local p=$GOPATH
      if [[ -z $p ]]; then
        if [[ -d $HOME/go ]]; then
          p=$HOME/go
        else
          p="$(go env GOPATH 2>/dev/null)" && [[ -n $p ]] || return
        fi
      fi
      if [[ $_p9k__cwd/ != $p/* && $_p9k__cwd_a/ != $p/* ]]; then
        _p9k_upglob go.mod && return
      fi
    fi
    _p9k_prompt_segment "$0" "green" "grey93" "GO_ICON" 0 '' "%B${v//\%/%%}" <<<----- right here
 }

  _p9k_prompt_go_version_init() {
    typeset -g "_p9k__segment_cond_${_p9k__prompt_side}[_p9k__segment_index]"='$commands[go]'
}
```

**Comment by romkatv** [comment]
You are trying to make `go_version` bold? If so, use this:

```zsh
POWERLEVEL9K_GO_VERSION_CONTENT_EXPANSION='%B${P9K_CONTENT}'
```

`CONTENT_EXPANSION` works with all segments. It allows you to patch segments without changing the code.

**Comment by besnija** [comment]
Oh that is awesome!
Is this available with all segments using the same syntax?

**Comment by romkatv** [comment]
> Is this available with all segments using the same syntax?

See my previous comment.
