### ISSUE TITLE
Always show commit identifier

### ISSUE THREAD

**Issue by fedemengo** [romkatv/powerlevel10k#181]
How can I configure the theme to always show the commit hash I'm currently on?

**Comment by romkatv** [comment]
Do you have a file named `~/.p10k.zsh`?

**Comment by romkatv** [comment]
> Do you have a file named `~/.p10k.zsh`?

If the answer is yes, open the file and find these lines:

https://github.com/romkatv/powerlevel10k/blob/e537a0ee628341741f20a7d2d96ea1c4fac74c4a/config/p10k-lean.zsh#L279-L286

Replace them with this:

```zsh
# '@72f5c8a' if in a non-empty repo, followed by a space if on a branch.
vcs+='${VCS_STATUS_COMMIT:+%f@%76F${VCS_STATUS_COMMIT[1,8]}${VCS_STATUS_LOCAL_BRANCH:+ }}'
# If on a branch...
vcs+='${VCS_STATUS_LOCAL_BRANCH:+%76F'${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}
# If local branch name is at most 32 characters long, show it in full.
vcs+='${${${$(($#VCS_STATUS_LOCAL_BRANCH<=32)):#0}:+${VCS_STATUS_LOCAL_BRANCH//\%/%%}}'
# If local branch name is over 32 characters long, show the first 12 … the last 12.
vcs+=':-${VCS_STATUS_LOCAL_BRANCH[1,12]//\%/%%}%28F…%76F${VCS_STATUS_LOCAL_BRANCH[-12,-1]//\%/%%}}}'
```

Customize it to your liking. There are enough comments to allow for tinkering even for non-experts in ZSH.

If you don't have `~/.p10k.zsh`, add `POWERLEVEL9K_SHOW_CHANGESET=true` to your `~/.zshrc`. If this doesn't work, post the output of `typeset -m 'POWERLEVEL9K_*'`.

**Comment by fedemengo** [comment]
Thanks!

**Comment by romkatv** [comment]
> Thanks!

Thanks a lot for reporting this!

**Comment by romkatv** [comment]
> > Thanks!
> 
> Thanks a lot for reporting this!

This is really awkward but I posted this comment to the wrong issue :man_facepalming:

I'm glad you have your configuration sorted out and all :grin:

**Comment by cybercussion** [comment]
I see the reference made to #if on branch...  in the ~/.p10k.zsh however I have no code like that. 
Is that deprecated since the time of this thread?

I don't se any option working right now for getting the commit sha-1 to show up.

**Comment by romkatv** [comment]
If you want Git status in your prompt to always show the current commit, run `p10k configure` to generate `~/.p10k.zsh`. Then open `~/.p10k.zsh` and search for this piece:

```zsh
# Display the current Git commit if there is no branch or tag.
# Tip: To always display the current Git commit, remove `[[ -z $where ]] &&` from the next line.
[[ -z $where ]] && res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"
```

Heed the tip.
