### ISSUE TITLE
leading slash in dir cut off

### ISSUE THREAD

**Issue by tbennett6421** [romkatv/powerlevel10k#1810]
I have a weird transient issue with the leading slash getting cut off of the prompt which appears to be related to the folder icon.

During the `p10k configure` the icon test that shows whether things are overlapping did have overlaps. So I choose the appropriate option (N)

![image](https://user-images.githubusercontent.com/6843296/159765269-abf7522c-d84b-4f81-9f3f-ccad1fae02a5.png)

The following is a video that describes this bug. I was unable to produce an animated gif that accurately showed this.
https://youtu.be/sOIth0DBQhE

I have no modifications from the wizard aside from the following
```
  # Context format when running with privileges: bold user@hostname.
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%B%n💀%m'
```

**Comment by romkatv** [comment]
When you select it, slash appears. This is a sign of a bug in the terminal. Please file a bug against it.

**Comment by tbennett6421** [comment]
Issue in zsh? or the terminal application?
Is there a way to selectively disable the dir icons?

**Comment by romkatv** [comment]
You can verify that the bug is in the terminal emulator by trying a different terminal emulator.

**Comment by tbennett6421** [comment]
Tried with gnome-terminal and it works, appears the affected terminal emulator is exo-open. I will look into filing with them. Thank you for the assistance.

**Comment by romkatv** [comment]
You are welcome.
