### ISSUE TITLE
How to restart Configuration Wizard?

### ISSUE THREAD

**Issue by xareelee** [romkatv/powerlevel10k#1811]
Thanks for this awesome project! I use powerlevel10k for many years.

For some reasons, I want to try to redesign my prompt by Configuration Wizard. How do I launch the wizard again?

I did not find a clue in README, and hope you can answer this. Thanks.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#configuration-wizard

**Comment by xareelee** [comment]
@romkatv Thanks! Maybe add a little hint/note below `p10k configure` (feature request): 

> You can redesign a new prompt again by the same command `p10k configure`, and save the new configuration in a new path.

BTW, is that possible to provide a design with two-line prompt instead of left/right prompt in Configuration Wizard? The original design has issues when resizing the window, and leads messy prompt. **The prompts are re-rendered for multiple times when resizing the window**:

<img width="851" alt="Screen Shot 2022-03-24 at 06 54 31" src="https://user-images.githubusercontent.com/804308/159809806-1d3a0ac2-f365-4e9e-bc81-d2d1de560b9a.png">


I want to move the right prompt elements to the first line to avoid this issue.

<img width="785" alt="Screen Shot 2022-03-24 at 07 06 36" src="https://user-images.githubusercontent.com/804308/159810921-83cf2f27-a33c-4a85-8dbe-f64cec51f8ba.png">

**Comment by xareelee** [comment]
Another suggestion: adding an image link in this question to show what is correct would be helpful.

<img width="381" alt="Screen Shot 2022-03-24 at 06 30 02" src="https://user-images.githubusercontent.com/804308/159811179-3c3e289c-3374-4028-841b-f069bc60e691.png">

**Comment by romkatv** [comment]
> @romkatv Thanks! Maybe add a little hint/note below `p10k configure` (feature request):

It's already as clear as it gets. There is a also a comment in your `~/.zshrc`.

> BTW, is that possible to provide a design with two-line prompt instead of left/right prompt in Configuration Wizard?

There is two-line prompt in there. You can also open `~/.p10k.zsh` and move segments around. It's not very difficult. See `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in there (close to the top).

> The original design has issues when resizing the window, and leads messy prompt.

See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window.

> Another suggestion: adding an image link in this question to show what is correct would be helpful.
> 
> <img alt="Screen Shot 2022-03-24 at 06 30 02" width="381" src="https://user-images.githubusercontent.com/804308/159811179-3c3e289c-3374-4028-841b-f069bc60e691.png">

There is no "correct". You just need to answer the question truthfully so that p10k knows what kind of fond you are using.

**Comment by xareelee** [comment]
Ok, Thanks! 👍
