### ISSUE TITLE
[Question] Font used in this terminal.

### ISSUE THREAD

**Issue by barryblando** [romkatv/powerlevel10k#1812]
What font is this? from a dark-shade to light-shade. It's perfectly rendered. 

![extravagant-style](https://user-images.githubusercontent.com/5582213/160098694-2d5cbfe2-5cd3-4738-88f8-642ca935229d.png)

I'm using Cascadia Code nerd-font and these are the built-in character shades. Also using Windows Terminal

![2022-03-25_18-02-19](https://user-images.githubusercontent.com/5582213/160099493-9f19965e-bbc2-43e2-a9c2-0dd5f8231b42.jpg)

**Comment by romkatv** [comment]
Some terminals have built-in support for [block elements](https://en.wikipedia.org/wiki/Block_Elements), meaning that they don't even look at the glyph from the font but draw it as they see fit. E.g., all terminals based on VTE have this feature. Window Terminal doesn't.

**Comment by romkatv** [comment]
There is also this: https://github.com/romkatv/powerlevel10k#how-were-these-screenshots-and-animated-gifs-created
