### ISSUE TITLE
Move cache files to ~/.cache/p10k

### ISSUE THREAD

**Issue by LeviOP** [romkatv/powerlevel10k#1817]
Currently, my `~/.cache` folder has 5 items in it from p10k. Having random loose files in directories, especially ones so close to home (`~/.cache`, `~/.local`, `~/.config`), really annoys me. Moving all of the cache files for p10k into their own folder within the cache folder would be much nicer. It appears as though changing it would be simple, only requiring line 6325 in p10k.zsh be changed from 
```zsh
typeset -g __p9k_instant_prompt_dump_file=${XDG_CACHE_HOME:-~/.cache}/p10k-dump-${(%):-%n}.zsh
```
to 
```zsh
typeset -g __p9k_instant_prompt_dump_file=${XDG_CACHE_HOME:-~/.cache}/p10k/p10k-dump-${(%):-%n}.zsh
```
If you don't want to make this change, would method I suggested result in the changed I want?

**Comment by romkatv** [comment]
You can set `XDG_CACHE_HOME` before sourcing p10k.

**Comment by LeviOP** [comment]
I already do have `XDG_CACHE_HOME` set. The files are in the right place (`~/.cache`), but I don't like them there. I think it would be better if all of the cache files were in a directory inside the cache directory. For example, in my cache folder, I have gitstatus, npm, nvim, zsh, and other directories that contain cache for their purposes respectively. P10k, on the other hand, has dumped five files directly into .cache without putting them in their own folder.

**Comment by romkatv** [comment]
Try setting `XDG_CACHE_HOME` before sourcing p10k. You can change immediately afterwards.

**Comment by LeviOP** [comment]
I understand that I _could_ do this, but I'd prefer not to have to, cluttering my zshrc and potentially messing something else up. Could I instead use the change I suggested above by setting `__p9k_instant_prompt_dump_file` to be in the directory I want?

**Comment by romkatv** [comment]
Sure, you can edit the source code. It's MIT licensed, so you are free to edit it.

Do I understand correctly that you've resolved the original problem?

**Comment by romkatv** [comment]
> It was a question of whether or not it would work

I don't know if it would work. There is no reason to modify the code anyway given that there is a parameter that you can set.

**Comment by romkatv** [comment]
You can choose whatever you prefer. Set the parameter or modify the code.

**Comment by ppwwyyxx** [comment]
I'm experiencing lagging in p10k startup time. I guess it's because p10k does IO on the cache files too frequently. I did the following to move the cache to /tmp:
```
local __old_xdg_home=$XDG_CACHE_HOME
export GITSTATUS_CACHE_DIR=$HOME/.cache/gitstatus
export XDG_CACHE_HOME=/tmp/.cache
# source p10k ...
export XDG_CACHE_HOME=$__old_xdg_home
```
and things feels faster now.

**Comment by romkatv** [comment]
If this helped, it means your `XDG_CACHE_HOME` is on a slow filesystem, which isn't a good idea. `XDG_CACHE_HOME` should be pointing to a directory on a local machine (not NFS or anything like that) that survives through reboots. Note that `/tmp` on many distributions does not survive through reboots.

**Comment by ppwwyyxx** [comment]
I think the very few cache files produced by p10k do not have to survive through reboots so I'd rather put them in tmpfs for faster speed. 

In general `XDG_CACHE_HOME` should survive reboots - that's why I have to restore its value after loading p10k. This is a bit annoying:
* If we could have an option `P10K_CACHE_HOME` then we could point it to `$HOME/.cache/p10k` (would solve the issue for OP) or `/tmp/.cache` (would solve the issue for me)

**Comment by romkatv** [comment]
`XDG_CACHE_HOME` should point to a local filesystem (not a network filesystem) that survives reboots. If you do that, powerlevel10k (and all other tools) will work fine.

**Comment by ppwwyyxx** [comment]
> XDG_CACHE_HOME should point to a local filesystem 

Local filesystems have different speed, and is surely slower than RAM (which is where my '/tmp' is mounted).

The IO of the cache files seems to affect the startup speed - therefore there are reasons to optimize its location.
Therefore I'm suggesting adding an option to configure its location.

> that survives reboots

That is true for `XDG_CACHE_HOME`. But as I said, the few performance-sensitive cache files of p10k __do not have to__  survive reboots. -- Sure, the prompt could start a bit slowly the first time after reboot, but that's not a big deal if caching in RAM can improve speed in __every__ prompt start.

Given this difference, it's useful to have a p10k-specific option, other than `XDG_CACHE_HOME`. (and it would also solve this original issue)

**Comment by romkatv** [comment]
Is your home directory on a local filesystem or something like NFS?

**Comment by ppwwyyxx** [comment]
It's a local file system.

**Comment by romkatv** [comment]
Could you open an issue and describe how to reproduce this:

> I'm experiencing lagging in p10k startup time.

**Comment by alberti42** [comment]
This is the patch file I am currently applying to the git repo:

[patch_cache_dir.patch](https://github.com/user-attachments/files/18399860/patch_cache_dir.patch)

Probably a better way forward would be to introduce a variable for the location of p10k cache dir and to make a pull request.

**Comment by romkatv** [comment]
@alberti42 You can do this:

```zsh
() {
  local XDG_CACHE_HOME=/bla/bla
  source /bla/bla/powerlevel10k.zsh-theme
}
```

**Comment by alberti42** [comment]
@romkatv Thank you very much. This is a very effective fix! It makes the patch unnecessary. For the benefit of others, this is how I load powerlevel10k in my zshrc:

```zsh
() {
  local XDG_CACHE_HOME=${XDG_CACHE_HOME:-~/.cache}/p10k # Covenient fix to change the cache folder to ~/.cache/p10k
  zinit depth=1 lucid light-mode for @romkatv/powerlevel10k
  [[ -f ~/.p10k.zsh ]] && __zcompile_if_needed_and_source $DOTFILES_DIR/.p10k.zsh
}
```

Of course early in the `.zshrc` or even in `.zshenv`:
```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then  
  __zcompile_if_needed_and_source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

**Comment by romkatv** [comment]
And I'm sorry that I haven't documented this feature even thought I use it myself (via zsh4humans). The vast majority of features in this project are undocumented but won't break if you rely on them.

**Comment by alberti42** [comment]
@romkatv Thank you a lot for the amazing prompt powerlevel10k.

PS: Thanks for the correction about `.zshenv`. Indeed, everything related to the prompt should go in `.zshrc`.
