### ISSUE TITLE
Keine Eingabe im Repository wenn theme powerlevel10k installiert ist

### ISSUE THREAD

**Issue by enilee** [romkatv/powerlevel10k#1819]
Hi,

ich nutze schon lange das Theme powerlevel10k.
Leider gibt es Probleme in der Kombination mit verschiedenen Komponenten.
Wenn das Theme deaktiviert ist nicht mehr.

Problembeschreibung:
wenn das besagte Theme installiert, konfiguriert und das Terminal in ein git repo gewechselt hat, blinkt zwar der Cursor, aber ich kann keinen Buchstaben Tippen! Die Branch etc wird korrekt und Farbig dargstellt, eine Eingabe ist nicht mehr möglich.
Befinde ich mich nicht in einem Repo, funktioniert die Eingabe.

Mein System und Umgebung:

Verbindung mit dem Linux-Server via NFS
iMac (Retina 5K, 27 Zoll, Ende 2015)
OSX: BIG SUR 11.6.5 (20G527)
git version 2.32.0 (Apple Git-132)
zsh 5.8 (x86_64-apple-darwin20.0)
zsh plugin (git)
Homebrew 3.4.4

Falls noch weitere Informationen benötigt werden, bitte melden.

Besten dank und LG

**Comment by romkatv** [comment]
How can I reproduce this issue?

**Comment by enilee** [comment]
Hey, thanks for the fast message.

if i go in a git Repository and would like to type something like "gst" oder anything else, nothing happens. I can´t wrote anything.
I reinstall git, reinstalled zsh, and your Theme - the same behave

Your Theme is for me the best in color and style. but i cant use it anymore

**Comment by romkatv** [comment]
I'm afraid this information is not enough to reproduce the problem on my own machine. I would need a detailed list of instructions, including all installation commands.

**Comment by enilee** [comment]
okay, i installed the following:

1. /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
2. brew install git
3. brew install zsh
4. git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
5. configure powerlevel10k
6. done.

Then i have on linux Server a git repo. I connected via NFS and go in the Git repo folder via Terminal
I see the colored "master" Branch and the blinked cursor, but i cant type any char in the Terminal.

i hope it helps to reproduce.

**Comment by enilee** [comment]
I installed all via brew, this is for me a "normal" easy and fast way - i havn´t problems with this way in the past.

Exactly, the Git repo is on a linux Server and i use NFS für the connection.
I dont know if this information useful?!

Sorry for my bad english and the "bad issue/informations" but I don't know myself what other information would be important

This is my configuration... 
[my zshrc config.txt.zip](https://github.com/romkatv/powerlevel10k/files/8372300/my.zshrc.config.txt.zip)


time git status: [16:23:18] [cost 1465.122s] gst

**Comment by romkatv** [comment]
If I understand correctly, the problem is caused by very slow `git` on NFS. See this comment for a solution: https://github.com/romkatv/powerlevel10k/issues/246#issuecomment-860272520

**Comment by enilee** [comment]
Good Morning,

this solution doesn´t help in my case (solution: https://github.com/romkatv/powerlevel10k/issues/246#issuecomment-860272520)

if i used SMB connection, the connection hanging every day if i worked a few hours.
As a result, if I want to shut down the Mac, it always crashes and I have to make a hard restart.
that's why I want to use NFS, but this doesn't work with the powerlevel10k or only slowly with other plugins

If we find no solution, please close The issue.... but i mean, i wasn´t the only one who use this combination von OSX, NFS, GIT, ZSH, POWERLEVEL10K...

**Comment by romkatv** [comment]
> this solution doesn´t help in my case (solution: [#246 (comment)](https://github.com/romkatv/powerlevel10k/issues/246#issuecomment-860272520))

Have you tried **option 3** from this link?

**Comment by enilee** [comment]
i use POWERLEVEL10K not POWERLEVEL9K - i think after your msg, i can use it anyway.
how do I know the right pattern and the right syntax?

**Comment by enilee** [comment]
Thanks very much for your help an explanation.
I tested, if i can connect with NFS, actually i can´t. I hope I will come to this this or next week.

**Comment by romkatv** [comment]
> I tested, if i can connect with NFS, actually i can´t.

I don't understand what you are trying to say.

**Comment by enilee** [comment]
Hi,
 apologize for the late feedback.

Unfortunately I can no longer connect to our server with NFS at the moment, there are problems. 
For this reason, I cannot test it.

I got a new MacBook with the new operating system "Monterey". NFS works with only 2 adjustments.
I will also install and test POWERLEVEL10K there and give Feedback.

Maybe it's BIG SUR Problem, I'm not sure.

Unfortunately, I don't have much time at the moment because a lot comes at once.

Forgive me;)

**Comment by enilee** [comment]
Good morning,
thank you. 
I will test it as soon as I have time and if I can reconnect to the server.
