### ISSUE TITLE
Prompt displays loading

### ISSUE THREAD

**Issue by msreekm** [romkatv/powerlevel10k#182]
Prompt displays loading when inside a git directory.

~/learn/flutter_architecture_samples > loading

zsh --version                                                                             
zsh 5.3 (x86_64-apple-darwin18.0)

**Comment by romkatv** [comment]
Thanks for the report. I'll need a bit more info to figure out what's going on.

Did it work before? If yes, when did it stop working. If it never worked, when did you install powerlevel10k?

How did you install powerlevel10k?

Do you see the same error if you update to the latest version of powerlevel10k?

Please type the following command:

```zsh
echo 'GITSTATUS_LOG_LEVEL=DEBUG' >>! ~/.zshrc
cd ~/learn/flutter_architecture_samples
zsh
```

Then type another command and attach its output:

```zsh
cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K
```

**Comment by romkatv** [comment]
Never mind, I think I know what's going on.

Please update powerlevel10k and try again. Should work now.

**Comment by romkatv** [comment]
Closing the issue as I believe it's been fixed. Please reopen if not.

**Comment by LHY-iS-Learning** [comment]
Hi, I have the same issue after I updated powerlevel10k.
My situation is when opening a new zsh, it starts to loading, even if its not a git repo.
I tried to run previous command and it indicating 
`+gitstatus_start_impl:74> [[ $'bye\C-_0' == hello0 ]]`
this command failed.
Thanks in advance!
