### ISSUE TITLE
NO EXISTE EL FICHERO O EL DIRECTORIO

### ISSUE THREAD

**Issue by Dari0GR** [romkatv/powerlevel10k#1821]
Cuando ejecuto zsh me salen 3 lineas con lo siguiente:
/home/daga/.zshrc:source:46: no existe el fichero o el directorio: /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
/home/daga/.zshrc:source:47: no existe el fichero o el directorio: /usr/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
/home/daga/.zshrc:source:60: no existe el fichero o el directorio: /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

me podrían ayudar por favor? Soy nuevo en esto, recién estoy comenzando.

**Comment by romkatv** [comment]
This has nothing to do with powerlevel10k.

**Comment by Dari0GR** [comment]
Pero despues de clonar "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc" y configurar me salieron esas lineas. Cuando inicio ZSH me salen esas 3 lineas. ¿Si no tiene nada que ver con powerlevel10k entonces con que? Igual orientame un poco si te es posible por favor

**Comment by romkatv** [comment]
Seriously, this has nothing to do with powerlevel10k.
