### ISSUE TITLE
P10k not working on rpi

### ISSUE THREAD

**Issue by Padmanabh82** [romkatv/powerlevel10k#1822]
Hi folks,
I am Padmanabh. I was installing p10k on a rasspbery pi 4 with `Oh-my-zsh`. I followed every step for installation (mentioned steps for oh my zsh on installation.md) but ot doesn't affect anything, then i tried to run p10k wizard but then it showed cant find command named `p10k`. Someone please help me here

**Comment by romkatv** [comment]
Powerlevel10k works fine on a rasspbery pi 4.

> i tried to run p10k wizard but then it showed cant find command named `p10k`.

This mean your zshrc is not sourcing powerlevel10k.

**Comment by Padmanabh82** [comment]
>This mean your zshrc is not sourcing powerlevel10k
@romkatv I did understood, what do you mean by "not 
sourcing" ??

**Comment by romkatv** [comment]
By "sourcing" I mean the `source` builtin.

Anyway, follow the installation instructions and everything should work. Make sure to apply all steps in the instructions.

**Comment by Padmanabh82** [comment]
I used `git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k` it work successfully then added `ZSH_THEME="powerlevel10k/powerlevel10k` to zshrc file, what's next. I done these steps before making issue, so what can I do next ????

**Comment by romkatv** [comment]
If you attach your `~/.zshrc`, I might be able to help.

**Comment by Padmanabh82** [comment]
And sorry for my terrible English 😅

**Comment by Padmanabh82** [comment]
Ok, I will send it. Can I send you tomorrow??

**Comment by romkatv** [comment]
You can do it any time you like. Make sure it's the `.zshrc` from the machine on which you are having issues (rpi).

**Comment by Padmanabh82** [comment]
Yea, sure

**Comment by Padmanabh82** [comment]
@romkatv ```
# Set up the prompt
autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

#Plugins
export ZSH="/home/pi/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    zsh-autosuggestions
    copyfile
    copybuffer
    dirhistory
    web-search
    jsontools
    sudo
)

ZSH_AUTOSUGGEST_STRATEGY=(
	history
	completion
)

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'
```

**Comment by romkatv** [comment]
You delete this line: https://github.com/ohmyzsh/ohmyzsh/blob/69a45a9c98291dc485ee9c46c9bf79ec8533217b/templates/zshrc.zsh-template#L75

You need to put it back.

**Comment by Padmanabh82** [comment]
Oh, ok i will try it

**Comment by Padmanabh82** [comment]
thanks @romkatv my Oh-my-zsh wasn't install correctly. this is fasted support i have seen in OSS communities
