### ISSUE TITLE
failed retrieving file 'cmake-3.22.3-1-x86_64.pkg.tar.zst'

### ISSUE THREAD

**Issue by coderoutsider** [romkatv/powerlevel10k#1824]
Hello. I'm trying to install the powerlevel10k theme, but after I launch the following command in the ArchWSL terminal: 
yay -S --noconfirm zsh-theme-powerlevel10k-git

The error appears at the end of the installation:
cmake-3.22.3-1-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'cmake-3.22.3-1-x86_64.pkg.tar.zst' from mirrors.kernel.org : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
 -> error installing repo packages

How do i solve?
Thank you for your help.

**Comment by romkatv** [comment]
Works for me. I see that it's pulling cmake-3.23.0-1. 

Try updating something?

**Comment by coderoutsider** [comment]
Sorry, I'm a beginner. I do not know how to answer. But if it helps, after I give the command:
yay -S --noconfirm zsh-theme-powerlevel10k-git

This appears, before the error I mentioned at the end appears:
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make:5]  hicolor-icon-theme-0.17-2  jsoncpp-1.9.5-1  rhash-1.4.2-1  cmake-3.22.3-1  wget-1.21.3-1
[Aur:1]  zsh-theme-powerlevel10k-git-r3918.25e5f59-1

  1 zsh-theme-powerlevel10k-git      (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (1/0): zsh-theme-powerlevel10k-git
  1 zsh-theme-powerlevel10k-git      (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: (1/1) Parsing SRCINFO: zsh-theme-powerlevel10k-git
resolving dependencies...
looking for conflicting packages...

Packages (5) cmake-3.22.3-1  hicolor-icon-theme-0.17-2  jsoncpp-1.9.5-1  rhash-1.4.2-1
             wget-1.21.3-1

Total Download Size:    9.91 MiB
Total Installed Size:  66.51 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...

**Comment by romkatv** [comment]
Try updating your OS.

**Comment by coderoutsider** [comment]
Thank you very much. It worked out. Have a good day. =]

**Comment by romkatv** [comment]
You are welcome.

**Comment by renatomrv** [comment]
Works for me too! (only update arch | sudo pacman -Syu)
