### ISSUE TITLE
Auto-complete problem when add "POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=true"

### ISSUE THREAD

**Issue by Ritzier** [romkatv/powerlevel10k#1825]
Add to .p10k.zsh:
```
typeset -g POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=true
```
When I using 'Tab' key it will show all the file in current directory, but when i use "Tab" key again it select the current file and other file with be black and gone!

I don't know how to expain this.....

**Comment by romkatv** [comment]
It's a bug in zsh. See https://www.zsh.org/mla/workers/2019/msg00161.html

**Comment by Ritzier** [comment]
Have any solution for that?

**Comment by Ritzier** [comment]
Or how do I add the command with the right way

**Comment by romkatv** [comment]
> Have any solution for that?

No.

**Comment by Ritzier** [comment]
Okay...
