### ISSUE TITLE
Color theme is not workin

### ISSUE THREAD

**Issue by fams** [romkatv/powerlevel10k#183]
My terminal is not showing the colors in prompt, even the theme choice is not working
I'm using oh-my-zsh and iTerm2
The bar is working with agnoster
powerlevel10k
![image](https://user-images.githubusercontent.com/481179/63454857-01d24380-c422-11e9-818e-8889f6fdce63.png)

agnoster
![image](https://user-images.githubusercontent.com/481179/63454931-20d0d580-c422-11e9-8348-b0d7a1612fec.png)

My color scheme on iTerm2
![image](https://user-images.githubusercontent.com/481179/63454971-334b0f00-c422-11e9-9f98-e769065a6420.png)

**Comment by romkatv** [comment]
For some reason iTerm doesn't export `TERM` for you or something in your configuration unsets it. If `TERM` is not set, `zsh` cannot use colors. You can verify this by disabling powerlevel10k and typing `print -P '%F{red}red text'`. The output should be red but for you it won't be.

To work around this problem, type this command:

```zsh
echo 'export TERM=xterm-256color` >>! ~/.zshrc
```

**Comment by eddyg** [comment]
For reference, there is a setting in `iTerm2` for this, and it is settable on a per-Profile basis.

Go to **Preferences**, select **Profiles** tab, select your Profile(s), then go to the **Terminal** tab, and make sure **Report Terminal Type** is set to `xterm-256color`.

**Comment by romkatv** [comment]
@eddyg Do you know why a small fraction of iTerm users has this issue? Does it mean they've manually changed this option?

**Comment by eddyg** [comment]
It's been a _long_ time since I installed `iTerm` "fresh" so I can't remember all the changes I needed to make... and I'm not familiar with the iTerm2 code base, but [a quick search through the source](https://github.com/gnachman/iTerm2/blob/master/sources/iTermProfilePreferences.m#L386), indicates the default for this setting may be `xterm`?

**Comment by romkatv** [comment]
Weird. Does iTerm really announce to all shells by default that it cannot display colors? Why would it do that? I don't understand why they even have an option to change the value of `TERM` but OK, maybe for testing or something. But having a wrong value by default? Bizarre.

I only use iTerm to test Powerlevel10k and I think I didn't have to change this option. Also, judging by the tiny number of users reporting this issue (this one is only second), I'd be surprised if the default was broken.

Oh well. Thanks for posting the instructions for changing this option in iTerm, @eddyg. I'll be referring other users to it when they somehow end up with invalid `TERM`.

**Comment by fams** [comment]
Yes, this solve the problem.
Thanks 

> For reference, there is a setting in `iTerm2` for this, and it is settable on a per-Profile basis.
> 
> Go to **Preferences**, select **Profiles** tab, select your Profile(s), then go to the **Terminal** tab, and make sure **Report Terminal Type** is set to `xterm-256color`.

**Comment by gnachman** [comment]
The default was `xterm` a looong time ago. Ever since ~2011, users on macOS 10.7 and later get a default of `xterm-256color`. If you ever used it on macOS 10.7 or pre-2011 then you'd get stuck with `xterm`.
