### ISSUE TITLE
Heads and tails not showing correctly in VSCode & default Terminal on Mac

### ISSUE THREAD

**Issue by titouv** [romkatv/powerlevel10k#1830]
This is how my terminal in showing with a default configuration using configuration wizard.
I think there is a color problem since the head color shouldn't be different compared to the previous color.
This problem doesn't occurs in more advanced Terminal like iTerm2 but occus in VisualStudio Code and the default mac os terminal (with default ANSI colors).

Note : Occurs only in classic mode in Unicode mode, not rainbow, or ASCII for example
![in default terminal](https://user-images.githubusercontent.com/39600279/161861534-2f58a226-1101-4565-b5ee-dc0e4d0e8787.png)
![in VSCode (slightly different config)](https://user-images.githubusercontent.com/39600279/161861622-5c109877-653c-4537-bac9-359382a65b1c.png)
![detail](https://user-images.githubusercontent.com/39600279/161862493-95fdf930-b9b4-4116-a74d-6bcb0f5a096f.png)

Thanks in advance

**Comment by romkatv** [comment]
I believe vscode devs made this change intentionally. They consider it a feature. There is an option somewhere in vscode settings to turn it off.

**Comment by romkatv** [comment]
It has something to do with contrast I think. Try searching for "contrast" in there.

**Comment by romkatv** [comment]
Here: https://github.com/microsoft/vscode/issues/146406#issuecomment-1084825473

**Comment by titouv** [comment]
Thanks !
I managed to set up the correction in VScode, but I don't find any contrast settings in the mac os default terminal.
Since the usage of this terminal, is not recommended with p10k, i think this issue can be closed ?

**Comment by romkatv** [comment]
Apple Terminal used to be the only terminal with this bug before vscode copied it. Apple Terminal doesn't have an option to turn it off.

**Comment by titouv** [comment]
Ok nice to know, thanks for your quick response
