### ISSUE TITLE
[question] How to trigger installing `gitstatusd` in Dockerfile

### ISSUE THREAD

**Issue by gabyx** [romkatv/powerlevel10k#1831]
I am using powerlevel10k in a Dockerfile:
I am setup `.p10k.zsh` in `.zshrc` and then run once:

```shell
zsh -c ". ~/.zshrc" </dev/null ||
    die "Could not source '.zshrc'."
```

to install all plugins ahead (such that they are already inplace in the image.)

How can I trigger that `gitstatusd` is installed as well?

**Comment by romkatv** [comment]
```zsh
script -fqec zsh /dev/null </dev/null >/dev/null
```

**Comment by gabyx** [comment]
Ok, :) what does that do?

**Comment by romkatv** [comment]
Have you already checked `man script`?

It basically does the same thing as starting `zsh` interactively and exiting it.

**Comment by romkatv** [comment]
> But the question is then how to start a shell interactively inside dockerfile?

See above.

> Is that the workaround?

Not sure what you mean.

**Comment by gabyx** [comment]
Ok, that starts `gitstatusd`, but is hangs, because the shell is not exiting. Do you know how to exit?

**Comment by gabyx** [comment]
Oh great. Something learned `script`. I actually did
```
script -fqec zsh /dev/null <(echo "exit 0") >/dev/null
```
which of course is pipeing a file...

**Comment by gabyx** [comment]
Thanks a lot, by the waz powerlevel10k is best!

**Comment by romkatv** [comment]
> Thanks a lot, by the way powerlevel10k is best!

You are welcome. And thanks ^^
