### ISSUE TITLE
WSL2 issue on ubuntu zsh shell

### ISSUE THREAD

**Issue by prathikshetty2002** [romkatv/powerlevel10k#1832]
There is a problem with powerlevel 10k on ubuntu zsh shell , it doesn't load the theme properly. Their is unicode error , instead of icons it displays some question marks.

![Screenshot 2022-04-07 024655](https://user-images.githubusercontent.com/63772910/162072504-14fb079a-a573-4e5c-91a7-668119ef59cf.png)

But it seems to work perfectly fine with ubuntu on my windows terminal. 

![Screenshot 2022-04-07 024837](https://user-images.githubusercontent.com/63772910/162072765-0673dec8-497d-4d0b-8caf-94093137519d.png)

I have tried reinstalling and repeated the process no benefit at all. Also Vscode seems to throw this kind of error! Folks any solutions for it, would be appreciated. <3

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by prathikshetty2002** [comment]
> See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

Thanks , but it seems like i have to reinstall the whole setup. I have used nerd fonts cascadia code . It works like a charm on windows.terminal.wsl but seems broken on my Ubuntu zsh shell still. 

I ran pk10 configure after curl into the font files on my Linux WSL machine. I got otf ttf wottf files. But still the ? Mark is persistent somehow. Well thanks for linking the documentation. I am trying to resolve this issue💻📍

I am trying to do the same procedure with powerline fonts maybe it does any better. Will update the issue .

**Comment by romkatv** [comment]
> I ran pk10 configure after curl into the font files on my Linux WSL machine.But unable to see Unicode icons . I got otf ttf wottf files. But still the ? Mark is persistent somehow.

Have you tried changing the font as described the docs? Here's the quote:

> **Windows Console Host** (the old thing): Click the icon in the top left corner, then *Properties → Font* and set *Font* to `MesloLGS NF`.

**Comment by prathikshetty2002** [comment]
> > I ran pk10 configure after curl into the font files on my Linux WSL machine.But unable to see Unicode icons . I got otf ttf wottf files. But still the ? Mark is persistent somehow.
> 
> Have you tried changing the font as described the docs? Here's the quote:
> 
> > **Windows Console Host** (the old thing): Click the icon in the top left corner, then *Properties → Font* and set *Font* to `MesloLGS NF`.

Yes i have set this property of font face to Caskaydia cove nerd font in terminal properties. Should I explicitly set it to MesloLGS NF? Or any nerd font works.  I'm trying it thanks for the suggestion ✔️

**Comment by romkatv** [comment]
You can use any font that has all the glyphs that you want to be displayed in prompt. The font that powerlevel10k recommends has all glyphs.

**Comment by prathikshetty2002** [comment]
> You can use any font that has all the glyphs that you want to be displayed in prompt. The font that powerlevel10k recommends has all glyphs.

Oh i get it know. Nerd fonts too must have all the glyphs since I can see those nice icons in my prompt window. But just be some configuration issue with my shell environment. I will reinstall once clean. Can you suggest any documentation that may be helpful for this prompt setup with powerlevel10k.
I really like the powerlevel10k fonts they are really cool <3 . Just want to fix the broken prompt on my Ubuntu shell.

**Comment by romkatv** [comment]
I don't think reinstalling anything could help. Powerlevel10k doesn't suggest it anywhere.

> Can you suggest any documentation that may be helpful for this prompt setup with powerlevel10k.

I already linked it above.

**Comment by prathikshetty2002** [comment]
> I don't think reinstalling anything could help. Powerlevel10k documentation doesn't suggest this action anywhere.
> 
> > Can you suggest any documentation that may be helpful for this prompt setup with powerlevel10k.
> 
> I already linked it above.

Thanks ,i think i have found a solution. I am following the docs linked by you. I will update about further issues if any. I am glad you answered my queries ,it was my first time raising an issue 🧑‍💻

**Comment by romkatv** [comment]
> i have found a solution

I'm glad. Closing as resolved.
