### ISSUE TITLE
Use ZSH_THEME=

### ISSUE THREAD

**Issue by AtomicNess123** [romkatv/powerlevel10k#1835]
I have installed powerlevel10k some time ago. 
I want now to use ZSH_THEME="crunch", but it does not take effect.
Is there any guidelines on how to revert to using ZSH_THEME?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k

**Comment by AtomicNess123** [comment]
Thanks. Isn't it possible to disable quickly powerleve10k to enable any ZSH_THEME? Or have them both overlapped?

**Comment by romkatv** [comment]
It is. You can selectively follow the instructions I linked above. Modify your zshrc without deleting any files.
