### ISSUE TITLE
Rainbow colors transparent/overlapping

### ISSUE THREAD

**Issue by keifererikson** [romkatv/powerlevel10k#1836]
Hello!

I have an odd issue with my p10k rainbow colors appearing semi-transparent or overlapping each other. I'm wondering if anyone may know what could cause this?

I set vscode to the default theme for these photos.

- Slanted
![image](https://user-images.githubusercontent.com/9795658/162557272-00b1dbec-e645-4901-a988-f688e1d5ad63.png)

- Rounded
![image](https://user-images.githubusercontent.com/9795658/162557368-4f244a0e-9edc-4645-ab13-1cef9bb7f4fc.png)

Thanks for your time.

**Comment by keifererikson** [comment]
After doing some digging into this, I've found a solution when using vscode. "Terminal > Integrated: Minimum Contrast Ratio" setting defaults to "4.5" Changing this setting to "1" solved the issue for me. 
Is there any way to solve this issue with a setting in p10k? I'm hoping to be able to leave this setting as default in vscode if possible.

![image](https://user-images.githubusercontent.com/9795658/162557804-659ad511-55ed-4cad-ac71-e0493a941a41.png)

**Comment by romkatv** [comment]
Dup of https://github.com/romkatv/powerlevel10k/issues/1830

There is nothing that I can do in powerlevel10k to work around this unfortunate vscode behavior.

**Comment by keifererikson** [comment]
Sounds great. Thanks for the confirmation @romkatv !
