### ISSUE TITLE
Question mark displayed in git repo directory

### ISSUE THREAD

**Issue by RunningXinLiu** [romkatv/powerlevel10k#1838]
Hi,

I am using mac os Monterey version 12.3.1. I have installed iterm2, oh-my-zsh, and powerlevel10k.

I have gone through the p10k config process and there was no problem displaying the icons. I have copied icons in nerd font cheat sheet, and I didn't see any problem displaying the icons. 

The question mark only appears when I entered a git repo locally. And it was followed by a number "11". Please see the screen shot below.
![image](https://user-images.githubusercontent.com/44730577/162864010-14df7288-9db6-4ebd-8408-24634bdb907b.png)

I have tried to reinstall the fonts and re-configured p10k several times but the question mark is still there. Please help me figure this out.

Best,
Xin

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#question-mark-in-prompt

**Comment by RunningXinLiu** [comment]
Thank you, Roman. It was my fault. I am new to git and GitHub. I realized that the question mark is about my git branch.
