### ISSUE TITLE
Have the majority of ryanoasis patched-fonts been tested in p10k?

### ISSUE THREAD

**Issue by Ttibsi** [romkatv/powerlevel10k#1839]
I'm referring to these fonts: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts He was the one that patched the recommended font, so I'm assuming that it _should_ work with all the p10k displays, but has there been any research done into this at all? (even incidental). Thank you. :)

**Comment by romkatv** [comment]
> He was the one that patched the recommended font

Who's "he"? See https://github.com/romkatv/powerlevel10k#how-was-the-recommended-font-created

> Have the majority of ryanoasis patched-fonts been tested in p10k?

I wouldn't know. It's an odd question to ask. Why do you care about *the majority* of fonts?

**Comment by Ttibsi** [comment]
> Who's "he"? See https://github.com/romkatv/powerlevel10k#how-was-the-recommended-font-created

Ah, I missed this part (emphasis mine)

> extra glyphs have been added to Meslo **with scripts forked from Nerd Fonts**

So you created the nerd version of the font instead of ryanoasis?

> Why do you care about the majority of fonts?

Looking to see what options I have. I don't expect every single font ever created to be rigorously tested, but I'm sure you've tried out or seen in use at least a handful of different nerd fonts with p10k, correct?

**Comment by romkatv** [comment]
> So you created the nerd version of the font instead of ryanoasis?

I'm not sure how to answer this question. The link I posed above explains how the font was created.

> I'm sure you've tried out or seen in use at least a handful of different nerd fonts with p10k, correct?

If by "a handful" you mean 5, then no. Again, it's a weird question to ask. Is my answer helpful to you? If I said "yes", would *that* help you?

**Comment by Ttibsi** [comment]
Apologies, thank you for your time
