### ISSUE TITLE
Custom prompt segment background and foreground not showing

### ISSUE THREAD

**Issue by JPUnD** [romkatv/powerlevel10k#184]
Hi there,

Trying to create a custom function, in my case a simple echo, i am not able to change both it's background and foreground colors.

As seen in Powerlevel9k Wiki:
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context time battery dir vcs virtualenv custom_wifi_signal)
POWERLEVEL9K_CUSTOM_WIFI_SIGNAL="echo signal: \$(nmcli device wifi | grep yes | awk '{print \$8}')"
POWERLEVEL9K_CUSTOM_WIFI_SIGNAL_BACKGROUND="blue"
POWERLEVEL9K_CUSTOM_WIFI_SIGNAL_FOREGROUND="yellow"
```

In my .zshrc:
```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh custom_name anaconda dir_writable dir)
POWERLEVEL9K_CUSTOM_NAME="echo UD"
POWERLVEL9K_CUSTOM_NAME_BACKGROUND="yellow"
POWERLVEL9K_CUSTOM_NAME_BACKGROUND="green"
```

Expected result: A prompt saying "UD" with yellow letter and green background

What i got: [image](https://i.imgur.com/p4ggLFD.png)

I've also tried using hexadecimal color values, and changing colors in other prompts (such as anaconda) is working as expected.

System information:
Manjaro (stable)
Kernel 4.19.66
Latest version of oh-my-zsh

**Comment by romkatv** [comment]
> ```zsh
> POWERLVEL9K_CUSTOM_NAME_BACKGROUND="yellow"
> POWERLVEL9K_CUSTOM_NAME_BACKGROUND="green"
> ```

There are a couple of types here. Once they are fixed, it should work as intended.

```zsh
POWERLEVEL9K_CUSTOM_NAME_FOREGROUND="yellow"
POWERLEVEL9K_CUSTOM_NAME_BACKGROUND="green"
```

**Comment by romkatv** [comment]
By the way, Powerlevel10k has a better API for custom segments. If you have `~/.p10k.zsh`, open it and search for `prompt_example`. If you don't have `~/.p10k.zsh`, run `p10k configure`.

**Comment by JPUnD** [comment]
ah shit im retarded, thanks for the help and thanks for the tip!
