### ISSUE TITLE
Configuration wizard missing

### ISSUE THREAD

**Issue by okJiang** [romkatv/powerlevel10k#1840]
when I typed `p10k configure`, the result is follow:

I did not see:
- Prompt stype
- Prompt heads
- Prompt tails
- ...

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163380823-96d1be22-f938-4f1f-8ca4-2fbef1f759aa.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381491-1e55b55a-356c-4ffc-a35f-318d065978d6.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381511-67b8d01d-cccf-4abb-bbe4-718e1ac308af.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381532-18984339-a4cf-4502-a1a1-ff0585485030.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381562-271b7490-8105-493b-a6db-ac7d5b362238.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381575-b34dbdb9-d5db-42b0-ba4d-b419c5469131.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381590-ccd3900a-20d4-4da8-ace1-ab2fbfc089be.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381626-a0b12777-0c49-4d93-9619-873e0a9e7d8f.png">

<img width="585" alt="image" src="https://user-images.githubusercontent.com/23556834/163381647-33a75299-e913-4d43-8ee5-f8a01ce4ee18.png">

I have seen https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard. I complete the verification:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/23556834/163383063-eac30a4e-367a-4ca6-813c-eb6d088e1fc8.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/23556834/163383130-4df0ed3a-eb87-4da9-831f-6f40bd79e1ee.png">

**Comment by okJiang** [comment]
m1 12.3.1

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard. In particular:

> If the terminal can display fewer than 256 colors, configuration wizard preselects Lean style with 8 colors. All other styles require at least 256 colors. *Fix*: Use a terminal with 256 color support and make sure that `TERM` environment variable is set correctly. Verify with `print $terminfo[colors]`.

**Comment by okJiang** [comment]
@romkatv  Thank you sooo much!! I did not set `TERM` correctly.

I made it after

```
export TERM=xterm-256color
```
