### ISSUE TITLE
there will be two or more prompts when terminal width is narrow

### ISSUE THREAD

**Issue by tjx666** [romkatv/powerlevel10k#1841]
In VSCode:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/41773861/163671276-21e6adfd-2b6c-4394-821d-99c9f06263d2.png">

In Iterm2:

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/41773861/163671296-32e0638c-bc02-4a8a-97bf-9ffd78c0b0a7.png">

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
