### ISSUE TITLE
[Q] p10k display glob pattern with exclude 

### ISSUE THREAD

**Issue by edshamis** [romkatv/powerlevel10k#1843]
In p10k-on-pre-prompt() I want to show all segments on the right side  besides one.
I can put in `p10k-on-pre-prompt()`:
```
p10k display '*/right/*'=show;
p10k display '*/right/time'=hide;
```
But then the time segment blinks for a millisecond on function

Can p10k support glob with exclude to make it one p10k command?
For example: `p10k display '*/right/*(!time)'=show;`

My post/pre functions:
```
function p10k-on-post-prompt() {
  if [[ $p10k_last_prompt_pwd == $PWD ]]; then
    p10k display '1/left/*'=hide;
  else
    p10k display '1/left/*'=show;
  fi
  p10k_last_prompt_pwd=$PWD;
  p10k display '*/right/*'=hide;
  p10k display '*/right/(status|time)'=show;
}
function p10k-on-pre-prompt() {
  p10k display '1/left/*'=show;
  p10k display '*/right/*'=show;
  p10k display '*/right/time'=hide;
}
```

[Link to my .p10k.zsh in gist](https://gist.github.com/5c552ac65fbddbff8bdbe0dfde41f735)
[Raw](https://gist.githubusercontent.com/edshamis/5c552ac65fbddbff8bdbe0dfde41f735/raw/193bfbeba42ed90f58486c679faea11bbd87da09/.p10k.zsh)

**Comment by romkatv** [comment]
Try this:

```zsh
p10k display '*/right/*'=show '*/right/time'=hide
```

Or this:

```zsh
p10k display '*/right/^time'=show
```

The glob syntax is documented at https://zsh.sourceforge.io/Doc/Release/Expansion.html#Filename-Generation. `EXTENDED_GLOB` is set.

**Comment by edshamis** [comment]
I tried to read the doc and debug a bit.
This works good:
```
p10k display '(1/left/*|*/right/*)'=show '*/right/time'=hide;
```
This doesn't:
```
p10k display '(1/left/*|*/right/^time)'=show;
```
I suspected EXTENDED_GLOB, but you say it's on...

**Comment by romkatv** [comment]
> This doesn't:
> 
> ```
> p10k display '(1/left/*|*/right/^time)'=show;
> ```


Works for me. At this point you'll have to give me a full config and describe what you expect it to do and what it actually does on your machine.

**Comment by romkatv** [comment]
By the way, you can test pattern matching against prompt segments with this one-liner:

```zsh
() { local -A reply; p10k display -a "$1"; print -rC1 -- ${(ok)reply} } '(1/left/*|*/right/^time)'
```

**Comment by edshamis** [comment]
Ok. I created a new user, installed z4h and passed p10k init wizard for lean two line prompt with time enabled.
I want to disable time for current prompt while printing it for executed commands + transient effect. For this I edit .p10k.zsh with
```
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
function p10k-on-post-prompt() {
  if [[ $p10k_last_prompt_pwd == $PWD ]]; then
    p10k display '1/left/*'=hide '*/right/*'=hide '*/right/(status|time)'=show;
  else
    p10k display '1/left/*'=show '*/right/*'=hide '*/right/(status|time)'=show;
  fi
  p10k_last_prompt_pwd=$PWD;
}
function p10k-on-pre-prompt() {
  p10k display '(1/left/*|*/right/^time)'=show;
  # p10k display '(1/left/*|*/right/*)'=show '*/right/time'=hide;
}
```
Transient prompt works, current prompt still shows time.

If I comment out `p10k display '(1/left/*|*/right/^time)'=show;` and uncomment `p10k display '(1/left/*|*/right/*)'=show '*/right/time'=hide;`  current prompt hides time — like i want it.

Globbing works fine with provided one-liner. 

[Gist with my .zshrc & .p10k.zsh](https://gist.github.com/edshamis/2f881d2634d3f9bd0f3bdfc800b04a6f)

**Comment by romkatv** [comment]
Here's a diff against your config that should do what you want:

```zsh
--- .p10k.zsh.orig      2022-04-21 10:12:20.405125700 +0200
+++ .p10k.zsh   2022-04-21 10:33:21.569950700 +0200
@@ -100,9 +100,11 @@
     todo                    # todo items (https://github.com/todotxt/todo.txt-cli)
     timewarrior             # timewarrior tracking status (https://timewarrior.net/)
     taskwarrior             # taskwarrior task count (https://taskwarrior.org/)
-    time                    # current time
     # =========================[ Line #2 ]=========================
     newline
+    # NOTE: These segments are shown only for completed commands.
+    status                  # exit code of the previous command
+    time                    # current time
     # ip                    # ip address and bandwidth usage for a specified network interface
     # public_ip             # public IP address
     # proxy                 # system-wide http/https/ftp proxy
@@ -1541,7 +1543,7 @@
   # If set to true, time will update when you hit enter. This way prompts for the past
   # commands will contain the start times of their commands as opposed to the default
   # behavior where they contain the end times of their preceding commands.
-  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
+  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true
   # Custom icon.
   # typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION='⭐'
   # Custom prefix.
@@ -1587,18 +1589,10 @@
   #   - same-dir: Trim down prompt when accepting a command line unless this is the first command
   #               typed after changing current working directory.
   typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off
-function p10k-on-post-prompt() {
-  if [[ $p10k_last_prompt_pwd == $PWD ]]; then
-    p10k display '1/left/*'=hide '*/right/*'=hide '*/right/(status|time)'=show;
-  else
-    p10k display '1/left/*'=show '*/right/*'=hide '*/right/(status|time)'=show;
-  fi
-  p10k_last_prompt_pwd=$PWD;
-}
-function p10k-on-pre-prompt() {
-  p10k display '(1/left/*|*/right/^time)'=show;
-  # p10k display '(1/left/*|*/right/*)'=show '*/right/time'=hide;
-}
+
+  function p10k-on-pre-prompt()  p10k display '1'=show              '2/right'=hide
+  function p10k-on-post-prompt() p10k display '(1|empty_line)=hide' '2/right'=show
+
   # Instant prompt mode.
   #
   #   - off:     Disable instant prompt. Choose this if you've tried instant prompt and found
```

Edit: I just now realized you want some custom login on cwd changes, which my diff removes. You can add it back if you want -- should be straightforward enough. FWIW, when I started using transient prompt I was worried that I would lose too much context, so I also didn't shorten prompt after a cwd change. Eventually I took the plunge to always shorten prompt and I don't regret it.

**Comment by romkatv** [comment]
> If I comment out `p10k display '(1/left/*|*/right/^time)'=show;` and uncomment `p10k display '(1/left/*|*/right/*)'=show '*/right/time'=hide;` current prompt hides time — like i want it.

Did you expect  `p10k display '(1/left/*|*/right/^time)'=show` to hide time? It cannot hide anything because the only argument of `p10k display` is of the form `<PATTERN>=show`. It will *show* change the status of all segments matching `<PATTERN>` to `show`. It doesn't change the status of segments not matching the pattern.

**Comment by edshamis** [comment]
Thanks for the diff and the clarification! I totally missed it.
If you have some spare time, I'd like to understand better with additional
questions:

1. Is it beneficial in terms of performance to use just one p10k display
command with multiple arguments in pre/post-prompt function vs multiple
commands with single argument?

2. Is it possible to access current command exit state in post-prompt
function to print it instead of past command state?

3. Is it possible to configure first line left segment not to overwrite the
right one but to continue together to the new line?

**Comment by romkatv** [comment]
> 1. Is it beneficial in terms of performance to use just one p10k display command with multiple arguments in pre/post-prompt function vs multiple commands with single argument?

It's a bit faster, yes, but the difference is unlikely to matter. You can measure it with [zsh-bench](https://github.com/romkatv/zsh-bench). If you ever find yourself caring about interactive zsh performance, make sure to read the doc at the homepage of zsh-bench.

> 2. Is it possible to access current command exit state in post-prompt function to print it instead of past command state?

That would require knowing the future. Try running `( sleep 5; exit $((RANDOM % 2)) )`. The exit status of this command won't be known for 5 seconds. Yet prompt has to be displayed before the command starts running. This prompt cannot be changed when the command finishes running because commands can alter the content of the TTY (e.g., insert `clear` in that command).

There is an FAQ entry for this: https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them

> 3. Is it possible to configure first line left segment not to overwrite the right one but to continue together to the new line?

Nope. Left prompt will contract as much as it can in order not to clash with right prompt. Once it cannot contract any longer, right prompt gets hidden. This is how it works in zsh proper (without powerlevel10k), too.

**Comment by edshamis** [comment]
Huge thanks! I really enjoy your z4h and p10k))

**Comment by romkatv** [comment]
You are welcome. Closing as resolved.
