### ISSUE TITLE
Disabling automated zcompile trigger 

### ISSUE THREAD

**Issue by arandomliz** [romkatv/powerlevel10k#1845]
I might have quite an interesting issue, but on my setup the built-in `zcompile` command doesn't work at all. The error is given as
```
zcompile: can't write zwc file: FILE.zwc
```

This happens even with `zsh -f` and a minimal zsh file with just `echo` in it. I believe it might be the environment it is running in that results in this issue.

A hot fix for now would be to disable all `zcompile` triggers. Is this possible?

### Environment
```
zsh: 5.8.1
uname -a: Linux Elisabeths-iPad 4.20.69-ish iSH 1.2.3 (298) Dec 17 2021 06:08:24 i686 Linux
```

**Comment by romkatv** [comment]
There is no option in powerlevel10k to disable zcompile.

**Comment by arandomliz** [comment]
hmh okay. I've traced the issue and it is a faulty implementation of linux `open` on my environment - especially how permissions on newly created files are managed. The bug fix will probably take a while until it will be rolled out and reach my device.

As a hot fix would it be possible to run zsh once with sudo privileges to create all zwc files (zcompile works here) and never be bothered again? Or are there zwc files that are recreated on every startup?

**Comment by romkatv** [comment]
> As a hot fix: would it be possible to run zsh once with sudo privileges to create all zwc files (zcompile works here) and never be bothered again?

Sure, try it.

> Or are there zwc files that are recreated on every startup?

`*.zwc` are generated only when missing or when they are older than the corresponding source files.

**Comment by arandomliz** [comment]
Yeah. That worked out. I just had to change the euid of my user temporarily to 0 because _permission checking_ of my emulation environment. - I'm a bit horrified that that is even possible
