### ISSUE TITLE
p10k configure does not prompt to install fonts

### ISSUE THREAD

**Issue by FrederickEngelhardt** [romkatv/powerlevel10k#1848]
So far I'm seeing `p10k configure` not install the required fonts for the icons. I can reproduce this with both a oh-my-zsh install and a manual install. 

I had the older (meslo LG S), (meslo LG M), (meslo LG L), (meslo LG DZ). All with the `for powerlines` added to their names.

Is there a conflict or something else going on?

### Notes
Manual install of fonts did work for me. 

I'm submitting this bug only because there was no prompt to install. It requires you to open the fonts with FontBook.app (my default is FTXViewer.app) for some reason.

**Comment by romkatv** [comment]
The prompt to install fonts is best effort. It's displayed only on Termux and on iTerm under some circumstances.

**Comment by FrederickEngelhardt** [comment]
Noting that this script works for triggering the auto install. Tested it on intel and apple silicon macs.

```zsh
installFonts(){
    # Install the fonts manually and trigger fontBook
    FONT_NAME="MesloLGS\ NF\ Regular.ttf"
    curl -L "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf" --output $HOME/Downloads/$FONT_NAME
    open -b com.apple.FontBook $HOME/Downloads/$FONT_NAME
}

installFonts
```
