### ISSUE TITLE
Gitstatusd does not ignore files marked by skip-worktree

### ISSUE THREAD

**Issue by NickTheTurtle** [romkatv/powerlevel10k#1849]
If I mark a file with skip-worktree (`git update-index --skip-worktree <file>`) and delete it, gitstatusd will include it as an untracked change.

However, if run `git status --ignore-submodules=dirty` or `git status`, it correctly notes that there is nothing to commit, the working tree is clean.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/12247846/165356202-832780c2-db31-456f-8d08-e53ba485d68a.png">

**Comment by romkatv** [comment]
libgit2 probably doesn't support skip-worktree. You can verify this by building `lg2` from libgit2 and running `lg2 status`.
