### ISSUE TITLE
Feature request :: Add Timestamp to Transient Prompt

### ISSUE THREAD

**Issue by T313C0mun1s7** [romkatv/powerlevel10k#1851]
I would do this myself if I knew how.

It is helpful to know when the last command you ran was initiated, especially when you are waiting for it to complete. I already added timestamps to my history, but that does not help on still running commands. The transient prompt provides nothing beyond the ">" but an option to precede it with the time stamp in the same format as configured for the main prompt would be nice. 

Thank you for your consideration. I know you are very busy, and I am hoping this would be a simple enough addition so as not to impose on you too greatly.

**Comment by romkatv** [comment]
There are many issues that contain a solution. Here's one: https://github.com/romkatv/powerlevel10k/issues/1705

You can search for "p10k-on-pre-prompt" for others.

**Comment by T313C0mun1s7** [comment]
Thank you.

**Comment by romkatv** [comment]
Did you manage to find a solution that works for you?

**Comment by T313C0mun1s7** [comment]
It means manually modifying files, which of course are going to complain about needing to be stashed the next time git wants to update oh-my-zsh. I'm also fairly certain this means my changes would be lost anyhow. So not really. Unless you added the option as a feature, I guess I will just have to do without.

**Comment by romkatv** [comment]
> It means manually modifying files

Correct.

> going to complain about needing to be stashed the next time git wants to update oh-my-zsh

oh-my-zsh won't complain about the content of `~/.p10k.zsh`.

> Unless you added the option as a feature, I guess I will just have to do without.

Sorry, it's not something I would consider adding to the wizard. The wizard only has the basic options and its job is to generate `~/.p10k.zsh` that serves as a reasonable starting point. After that you can do additional customization by modifying `~/.p10k.zsh`.
