### ISSUE TITLE
sourcing ~/.zshrc breaks a couple aspects of my console/prompt

### ISSUE THREAD

**Issue by miloofcroton** [romkatv/powerlevel10k#1852]
I am using Volta to manage Node.js versions, and Volta seems to break if I run source `~/.zshrc`. I don't know why, but I have to completely close and open the terminal to get it working again.

The transient prompt also breaks if I source `~/.zshrc`. Again, I have to restart the console to get it back.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#weird-things-happen-after-typing-source-zshrc

**Comment by miloofcroton** [comment]
> https://github.com/romkatv/powerlevel10k#weird-things-happen-after-typing-source-zshrc

Thanks! I missed that in the docs.
