### ISSUE TITLE
zshrc file gives %{%K{black}%F{blue}%}%{%F{default}%} %(!.%{%F{yellow}%}.)%n@%m %{%K{blue}%F{black}%}%{%F{black}%} %~

### ISSUE THREAD

**Issue by Tvega8** [romkatv/powerlevel10k#1853]
i configured my p10k and got this feedback  %{%K{black}%F{blue}%}%{%F{default}%} %(!.%{%F{yellow}%}.)%n@%m %{%K{blue}%F{black}%}%{%F{black}%} %~ from my .zshrc
How can I fix this?

**Comment by romkatv** [comment]
This isn't coming from powerlevel10k. You can verify this by disabling or uninstalling powerlevel10k.
