### ISSUE TITLE
show full date Y-M-D H:M:S on Right Status Bar Prompt

### ISSUE THREAD

**Issue by mr-pmillz** [romkatv/powerlevel10k#1855]
How can i get my `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` to show the full date

currently it shows,

```shell
01:52:31 PM 
```

![image](https://user-images.githubusercontent.com/58376398/166299340-d0e96667-4b63-4342-b2ba-0c91bf07c1a9.png)

I would like it to show the output of the date command formatted like so

❯ date '+%Y-%m-%d_%H:%M:%S'
2022-05-02_13:56:02

using this date format `%Y-%m-%d_%H:%M:%S`

or the current date format it has now plus `%Y-%m-%d `

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and search for `POWERLEVEL9K_TIME_FORMAT`. Read comments above it and adjust the value to your liking.

**Comment by mr-pmillz** [comment]
oh wow, yeah i thought that was how to do it too.

for some reason, it didn't work the first time i tried it.

works now though :) 

```bash
POWERLEVEL9K_TIME_FORMAT='%D{%Y-%m-%d %I:%M:%S %p}'
```

haha, i guess i should've tried harder LOL. i swear i tried this, but if at first you don't succeed. 💯 

Thank you @romkatv
