### ISSUE TITLE
Condensed font does not show up properly in git prompt summary

### ISSUE THREAD

**Issue by thinkoid** [romkatv/powerlevel10k#1859]
Typing too fast I accidentally send the issue out before filling the content. So, I use Iosevka font and the git prompt is messed up, like in the image attached. Any remedy?
 
![github](https://user-images.githubusercontent.com/8246305/166584810-8bfdb549-e7db-4191-8515-d8a26ba1c4ba.png)

**Comment by romkatv** [comment]
This looks like a bug in the font or in the terminal.

**Comment by thinkoid** [comment]
`xterm` looks the same so I have to believe it's the font. I guess we can close this, then?

**Comment by romkatv** [comment]
Yep, must be an issue with the font.
