### ISSUE TITLE
VCS_STASH_ICON to render same as powerlevel9k

### ISSUE THREAD

**Issue by 1Mark** [romkatv/powerlevel10k#1860]
How can I can powerlevel10k to render the VCS_STASH_ICON in the same was as powerlevel9k according to the readme it uses `*` which is what I see in the terminal. But I'd like it to render the same as `'\uF01C '` which is what I see and expect as per `powerlevel10k/internal/icons.zsh` but not sure why it's rendering `*` instead I'm using font `Meslo LG S DZ Regular Nerd Font Complete.ttf `

**Comment by romkatv** [comment]
If you use powerlevel10k with a config for powerlevel9k, you'll get the same prompt. Delete `~/.p10k.zsh`, put a bunch of `POWERLEVEL9K_*` parameters in `~/.zshrc` and you are done.

Alternatively, you can open `~/.p10k.zsh` and edit `my_git_formatter` in there. Replace `*` with `$'\uF01C'`.

You can also flip `POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING` to `false` in `~/.p10k.zsh`. This will enable the stock git formatter and won't use `my_git_formatter` anymore.

**Comment by 1Mark** [comment]
`Replace * with $'\uF01C'` didn't work for me but when I copied and pasted the actual symbol into the file worked great.

**Comment by romkatv** [comment]
> `Replace * with $'\uF01C'` didn't work for me

You need to be aware of quotes when you do this. The original line is this:

```zsh
res+=" ${clean}*${VCS_STATUS_STASHES}"
```

Note that `*` is within double quotes. So if you want to replace it with $'\uF01C'`, you need to close and re-open double quotes:

```zsh
res+=" ${clean}"$'\uF01C'"${VCS_STATUS_STASHES}"
```

Copy-pasting the actual symbol will also work but it'll make your config difficult to edit or view with the vast majority of fonts. The symbol is from Unicode Private Use Area, which means that the Unicode standard doesn't prescribe anything at all about its appearance. It can look like a banana in one font and as a horse in another. In most fonts there is no glyph whatsoever for this code point.

**Comment by 1Mark** [comment]
Thank you for your concern. I will update the file accordingly. 

Out of curiousity this particular icon in powerlevel10k seems less clear why is `*` the default now?

**Comment by romkatv** [comment]
ASCII symbols like `*`, `?` and `!` are a lot easier to read and look good in all fonts. The defaults in powerlevel9k require a patched font and look barely legible.
