### ISSUE TITLE
Documentation request: How to install Powerlevel10K on Windows 11

### ISSUE THREAD

**Issue by ditlef9** [romkatv/powerlevel10k#1862]
I am running Windows 11 and I cannot find any exe-file or bat-file to install Powerlevel10k. The documentation doesn't cover how to do this.

**Comment by romkatv** [comment]
Powerlevel10k is a zsh theme. Zsh themes require zsh. Once you have installed zsh, follow the installation instructions for powerlevel10k.

**Comment by romkatv** [comment]
There is no exe or bat file to install Powerlevel10k on Windows. All supported installation options are documented.
