### ISSUE TITLE
How to disable auto path compression?

### ISSUE THREAD

**Issue by Mactarvish** [romkatv/powerlevel10k#1863]
I noted that p10k may compress some component on the path:
![image](https://user-images.githubusercontent.com/13399458/167832807-078409fc-de06-46a3-a55b-f1e7c0733d59.png)

I hope to show the whole path, how to do it ? Thanks.

**Comment by romkatv** [comment]
Open `~/p10k.zsh` and change the values of the following parameters as shown below:

```zsh
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0
```

The meaning of these parameters is documented in comments above them.

**Comment by Mactarvish** [comment]
Thanks.

**Comment by Mactarvish** [comment]
> Open `~/p10k.zsh` and change the values of the following parameters as shown below:
> 
> ```shell
> typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=
> typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0
> typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0
> ```
> 
> The meaning of these parameters is documented in comments above them.

should be `~/.p10k.zsh`
