### ISSUE TITLE
VSCode terminal cutting off MesloLGS NF icons

### ISSUE THREAD

**Issue by IlanCosman** [romkatv/powerlevel10k#1864]
This can be simply demonstrated by `echo '  '` (the apple logo with spaces on either side).

In VSCode the apple logo is cut off. Changing font size does not help.

Reference correct image from default Terminal: <img width="33" alt="Screen Shot 2022-05-11 at 3 23 20 PM" src="https://user-images.githubusercontent.com/6318351/167958304-44ef6e08-aaaf-4781-b1ec-5517448ef154.png">
 
Bad image from VSCode terminal: <img width="55" alt="Screen Shot 2022-05-11 at 3 26 07 PM" src="https://user-images.githubusercontent.com/6318351/167958340-10650523-95e8-4c72-8ce0-ac202a0302e2.png">

**Comment by romkatv** [comment]
Looks like a bug in vscode terminal.

**Comment by slipmp** [comment]
> As a quick (and hopefully temporary) fix - setting `"terminal.integrated.gpuAcceleration": "canvas"` in settings.json seems to work.

This solution worked for me, thank you!

**Comment by GBrachetta** [comment]
I wonder why has this been closed. Is the workaround above the definitive solution to this?

**Comment by romkatv** [comment]
> I wonder why has this been closed.

The bug is in VSCode and not in powerlevel10k. It's been fixed in the insider build of VSCode, so you can either install that or wait for it to be released.

**Comment by pripishchik** [comment]
@romkatv the icon on the right is a bit cut off, terminal font is `MesloLGS NF`, how to fix?

![image](https://user-images.githubusercontent.com/125473856/219811233-d03a5b8f-bd06-4e97-bca9-02b69939fe47.png)
![2023-02-18_00-40](https://user-images.githubusercontent.com/125473856/219811258-b950eefb-58df-48be-9515-1ebaee511f63.png)

**Comment by pripishchik** [comment]
@romkatv with `FiraCode Nerd Font` it looks even worse.

![image](https://user-images.githubusercontent.com/125473856/219812484-93d9854e-830d-498d-a688-a7e0e37cde23.png)

**Comment by romkatv** [comment]
@pripishchik You can try this:

```zsh
ZLE_RPROMPT_INDENT=1
```

It'll essentially add a space on the right side of prompt.

**Comment by pripishchik** [comment]
@romkatv yes, but I have set `ZLE_RPROMPT_INDENT` to 0 intentionally to remove that space in ubuntu terminal.

**Comment by pripishchik** [comment]
I guess there is bug in VS Code then since in ubuntu terminal there is no such issue.

**Comment by romkatv** [comment]
You can do it conditionally based on the terminal. Like this:

```zsh
if [[ $TERM_PROGRAM != vscode ]]; then
  ZLE_RPROMPT_INDENT=1
fi
```

**Comment by pripishchik** [comment]
@romkatv yes, it works now, but then the question is why the icon is cut off with `ZLE_RPROMPT_INDENT` set to 0 while the text that appears on the right is not (see the screenshot, gcloud example)?

![image](https://user-images.githubusercontent.com/125473856/219903424-42657835-118a-41ac-89ec-f2e81828f9e5.png)

**Comment by romkatv** [comment]
The glyph of the gear icon that you see on the right has a negative rightside bearing, while the glyph for the lower-case `m` has zero rightside bearing. vscode chooses to cut off the terminal content at the edge of the terminal rather than allowing it to overflow to the margin.

**Comment by hologerry** [comment]
The issue is still there with all the settings metioned above.
<img width="878" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11660168/134ef563-6ced-403f-95d2-7efc33984c76">

**Comment by romkatv** [comment]
It makes sense for this behavior to still be observable. No party acknowledged it as a bug or made a promise to change it.

**Comment by hologerry** [comment]
> It makes sense for this behavior to still be observable. No party acknowledged it as a bug or made a promise to change it.

Thanks, but it's weird...

**Comment by hologerry** [comment]
I find a "solution" for reference, just install a 2.x version of the nerd font from the release page: https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3. since the icons on latest version of no 'Mono' are too large.
and set `"terminal.integrated.fontFamily": "'MesloLGM Nerd Font'",`.

**Comment by romkatv** [comment]
Note that this font has icons with inconsistent sizes, and most icons are too small.

**Comment by hologerry** [comment]
ok...
is there any other 'solution' or workaround?

**Comment by romkatv** [comment]
Run `p10k configure` and select Lean style with Few Icons. You'll have important icons anyway but the decorative icons will disappear. Incidentally, the icons on the very left are decorative (the apple logo is meaningless, you already know you are on macOS), so nothing will be cut off.

**Comment by gosentetsu** [comment]
I tried newest Meslo font then solved this problem.
```
brew install --cask font-meslo-lg-nerd-font
```

And set VSCode Terminal font as `'MesloLGS Nerd Font'`
