### ISSUE TITLE
Not seeing arrow shaped prompt style in p10k configure.

### ISSUE THREAD

**Issue by sharjeelmazhar** [romkatv/powerlevel10k#1866]
Everything was working fine till this evening, i put my Arch Linux on conda env: pip update, and when i got back, the whole p10k was messed up it was giving me an error. I tried to solve it but couldn't, so deleted oh my zsh and p10k and i reinstalled the oh my zsh and as well as p10k from scratch, it solved the error message but still i don't see any prompt for arrow shape "<some text/icons>" (this type of prompt which end with a sharp arrow like bead) by running p10k configure. Kindly please help me resolve this issue. 
The screenshot of the p10k configure is attached herewith.
![IMG-20220513-WA0000](https://user-images.githubusercontent.com/73254881/168164161-346da497-f371-4ba0-aec2-1fce69875f09.jpg)

I want this kind of prompt
![IMG-20220513-WA0001](https://user-images.githubusercontent.com/73254881/168164216-80aedb6b-5f13-4630-a0f2-7ef111f46fc8.jpg)

Thank you.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
