### ISSUE TITLE
About the display of icons

### ISSUE THREAD

**Issue by NeysaBan** [romkatv/powerlevel10k#1867]
When I configure, the icon can be displayed normally
![Snipaste_2022-05-15_23-50-23](https://user-images.githubusercontent.com/48760129/168481790-241a5592-9bc4-490f-a770-37735cd74f32.png)

However, when using the following command, they can't display normally
![Snipaste_2022-05-15_23-50-02](https://user-images.githubusercontent.com/48760129/168482005-61f2f9e2-f831-4570-bb70-0ddecb3b85d0.png)

We can also see from the above picture that the icon de cannot be displayed correctly on the command line.😭
And it should be noted that I have installed and set the font.

**Comment by NeysaBan** [comment]
so how could I do to make the icon display normally😥

**Comment by romkatv** [comment]
I don't see anything wrong with the pictures you've posted.

The second screenshot was taken after choosing ASCII in the configuration wizard. If you want to see fancy icons in prompt, choose UNICODE instead.

**Comment by NeysaBan** [comment]
oh😂.... Thanks a lot!!!
