### ISSUE TITLE
sparse-checkout will disappear branch info

### ISSUE THREAD

**Issue by frankcbliu** [romkatv/powerlevel10k#1868]
hello!
when i use `git sparse-checkout` to check out my branch, the branch info on the prompt will disappear.
 
here is the normal checkout:
![image](https://user-images.githubusercontent.com/36353894/168751227-ac79b23f-77fe-4d09-bb75-422bc87626f0.png)
as u see, the branch name in this checkout is normal.

but when i use spare-checkout, the branch info disappear.

here is the spare-checkout:
![image](https://user-images.githubusercontent.com/36353894/168751094-3b6dec67-e46d-4981-a800-4eea36954f80.png)

i am not sure what makes this problem, how can i get back the branch info ?

**Comment by romkatv** [comment]
Powerlevel10k uses gitstatus to retrieve information about git repositories. gitstatus, in turn, uses libgit2. libgit2 doesn't support sparse checkouts. See https://github.com/libgit2/libgit2/issues/6044.

**Comment by frankcbliu** [comment]
> Powerlevel10k uses gitstatus to retrieve information about git repositories. gitstatus, in turn, uses libgit2. libgit2 doesn't support sparse checkouts. See [libgit2/libgit2#6044](https://github.com/libgit2/libgit2/issues/6044).

ok, i see. thanks for your quickly reply~

**Comment by mikehdt** [comment]
It does look like there's been an effort recently to support this, which is fantastic news:
https://github.com/libgit2/libgit2/pull/6202
