### ISSUE TITLE
macOS icon display problem in Visual Studio Code

### ISSUE THREAD

**Issue by anthonypillot** [romkatv/powerlevel10k#1869]
After a new release of `Powerlevel10k` (or `oh-my-zsh`, I don't really know which one is in case of), my integrated vscode terminal do not display correctly icons (Cf. my screenshot).

![image](https://user-images.githubusercontent.com/51130139/168767078-4965c94d-ddab-44ae-bb8b-de2e49dd00a5.png)

- macOS version: `12.3.1 (21E258)`.
- Visual Studio Code version: Version: `1.67.1 (Intel Chip)`.

Thanks in advance.

**Comment by romkatv** [comment]
If you mean icons being cut off, this is a bug in VSCode. It has been fixed in the insider build. As a workaround you can set `"terminal.integrated.gpuAcceleration": "canvas"` in VSCode settings.
