### ISSUE TITLE
How do I change the styles?

### ISSUE THREAD

**Issue by ledicjp** [romkatv/powerlevel10k#1870]
Sorry for creating an issue but when I run the configuration wizard its first question is if I see the diamond symbol, it never asks me about the style lean, classic, rainbow, pure or anything. It always just picks the lean style. I've tried reinstalling p10k to force the wizard to a "first-run" but it still didn't ask about the style choice. What am I doing wrong?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
