### ISSUE TITLE
Make prompts flush with terminal

### ISSUE THREAD

**Issue by aw632** [romkatv/powerlevel10k#1871]
I'm using iTerm2 with Powerlevel10k and the default recommended font. I've noticed that the prompts are not flush with the terminal (the box with the checkmark and the box with the Apple logo). is there any way to extend these so they are flush with the edges of the terminal window?

![image](https://user-images.githubusercontent.com/63763293/169382523-8cac05e4-8dcb-4ac1-b8c8-540c1067fafc.png)

**Comment by romkatv** [comment]
This boundary is drawn by your terminal. Powerlevel10k cannot remove or add it.
