### ISSUE TITLE
Emit terminal bell after long processes

### ISSUE THREAD

**Issue by jkoop** [romkatv/powerlevel10k#1874]
I'm easily distracted, so if a command takes longer than 20 seconds (make this a setting?) emit a terminal bell symbol ([0x07](https://en.wikipedia.org/wiki/Bell_character)) to notify me when its done.

Please?

**Comment by jkoop** [comment]
I suppose the whole thing should be a setting (default off)...

**Comment by romkatv** [comment]
Powerlevel10k provides prompt and nothing else. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect
