### ISSUE TITLE
zsh: command not found: -zsh :: how dow I remove that> it says that every time I open the terminal 

### ISSUE THREAD

**Issue by alantothe** [romkatv/powerlevel10k#1875]
❯ -zsh
zsh: command not found: -zsh

first thing that pops up in the terminal

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with a different theme?

**Comment by alantothe** [comment]
Hi, for some reason my preferences on the terminal had the "run command -zsh" selected I just unchecked it and that message went away. Thanks for help 


Picture of Preferences <img width="453" alt="Screen Shot 2022-05-22 at 3 46 29 PM" src="https://user-images.githubusercontent.com/104442054/169713164-6cb2bc11-0df0-4a61-a1c3-865a68c4827f.png">

**Comment by romkatv** [comment]
Thanks for the update. Glad you've resolved this issue.
