### ISSUE TITLE
Allow longer left prompt / reduce gap to prevent cutting off git information?

### ISSUE THREAD

**Issue by BioSehnsucht** [romkatv/powerlevel10k#1879]
This is a minor annoyance and I'm hoping there's a setting I can change to solve it. I'm using Manjaro KDE Plasma and only discovered `p10k configure` today, and thought I'd see if making some changes to the default settings might solve this (like going to a 2-line prompt), but it still happens after playing around with it.

When the directory path is long enough, the git branch status will get truncated by the end of the prompt, ideally as long as there's a gap between left and right prompts, it should just keep using space to have all the information.

![image](https://user-images.githubusercontent.com/135569/170775525-d345884c-f5dc-4600-b6a1-c9edfcf7dc55.png)

This can be seen in the above screenshot where 'master' is cut off, and you can't see the '?' for untracked files, or anything else that might come after.

I glanced through the ~/.p10k.zsh file but nothing looked like a setting for this particular aspect (some kind of length limit on left prompt).

**Comment by romkatv** [comment]
You are using some kind of buggy terminal. Try a different one.

**Comment by romkatv** [comment]
It's possible that the bug in the terminal doesn't trigger if you switch to Lean style. Another thing to try.

**Comment by BioSehnsucht** [comment]
I did just try another terminal app and can confirm the issue didn't occur there.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/1227

**Comment by BioSehnsucht** [comment]
Now that I knew what to look for, there was even a Manjaro support forum post with the solution. I've posted a new thread over there asking that they add the font to be installed by default (and configure it in the Konsole/Yakuake profiles) since it's needed to properly support the default configuration ...

**Comment by romkatv** [comment]
Could you post a link to the two forum posts you mentioned?
