### ISSUE TITLE
howto reduce space after subversion icon

### ISSUE THREAD

**Issue by cridemichel** [romkatv/powerlevel10k#188]
is it possible to reduce the space after the subversion icon (see the screenshot below)?

![Schermata 2019-08-25 alle 11 37 33](https://user-images.githubusercontent.com/15322138/63648229-ebcbc800-c72c-11e9-81c5-36d1ea6feb2b.png)

best Cristiano

**Comment by romkatv** [comment]
Three ways to do it.

1. Switch to a monospace font. For example, [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k).

2. Set a custom icon for subversion.
2.1. Open `~/.p10k.zsh`.
2.2. Add `POWERLEVEL9K_VCS_SVN_ICON='\uE7A8'`

3. Remove space from all cvs icons, be it subversion, git or hg.
2.1. Open `~/.p10k.zsh`.
2.2. Search for `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION`.
2.3. Uncomment that line and set value to `'${P9K_VISUAL_IDENTIFIER// }'` (including the single quotes).
