### ISSUE TITLE
prompt_context:2: command not found: prompt_segment

### ISSUE THREAD

**Issue by yinwhm12** [romkatv/powerlevel10k#1881]
Hello, I absolutely love p10k!
But I have some problems and need your help.
Modify the vim ~/.zshrc file and add the following code:

`prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
  fi
}`

but I failed to do that.

my macOS Monterey is 12.4 version
zsh 5.8.1 (x86_64-apple-darwin21.0)
iTerm2 Build 3.4.15

Looking forward to your reply, thank you very much!

**Comment by romkatv** [comment]
Well, remove that line. Duh!

**Comment by yinwhm12** [comment]
> 

is not supported "prompt_segment"? What do I need to change to hide my hostname? Hope to get your reply, thank you!

**Comment by yinwhm12** [comment]
Very Thank you! I run p10k configure and get it.
