### ISSUE TITLE
How to remove the timestamp

### ISSUE THREAD

**Issue by isknurul007** [romkatv/powerlevel10k#1884]
Hello,
How do I remove the timestamp from the terminal

<img width="917" alt="2022-06-02 07_03_02-Ubuntu" src="https://user-images.githubusercontent.com/106715990/171528725-42522d61-5e0b-4262-b7af-1c37b4d6d456.png">

And when I go to root directory, it shows "**!w**"  and then "/",  is there any way to remove this "**!w**" ?

**Comment by romkatv** [comment]
> How do I remove the timestamp from the terminal

Open `~/.p10k.zsh` and remove `command_execution_time` from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

> And when I go to root directory, it shows "!w" and then "/", is there any way to remove this "!w" ?

Open `~/.p10k.zsh`, search for `POWERLEVEL9K_DIR_SHOW_WRITABLE` and change its value from `v3` to `false`.

**Comment by isknurul007** [comment]
Thank you very much @Roman
