### ISSUE TITLE
some part of prompt appears in right side

### ISSUE THREAD

**Issue by sandeepDevJs** [romkatv/powerlevel10k#1886]
I just installed powerlevel10k in my windows terminal..
everything went greate but some part of prompt appears in right.
see below imafe
![image](https://user-images.githubusercontent.com/73023903/171810871-a1eb80e7-c127-4c0a-b62a-c97eb2aae1c1.png)

I dont want things in the right side.

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and either move prompt segments from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or delete them.

This might be relevant too: https://github.com/romkatv/powerlevel10k#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style

**Comment by sandeepDevJs** [comment]
Thanks! it worked out.
