### ISSUE TITLE
Question: How to run a shell script after zsh and powerlevel10k are fully initialized

### ISSUE THREAD

**Issue by tanyu-tci** [romkatv/powerlevel10k#1887]
I want to execute a script for switching to another user after starting iterm2.
I wrote this script before the instant prompt preamble,However, when the window is maximized, the display content will not follow the change, and will always be the size of the initial window.

**Comment by romkatv** [comment]
> I want to execute a script for switching to another user after starting iterm2.

For switching to another *what*?

> I wrote this script before the instant prompt preamble,However, when the window is maximized, the display content will not follow the change, and will always be the size of the initial window.

Could you describe what you do, what you expect and what actually happens?

**Comment by tanyu-tci** [comment]
I added this code at the beginning of the `.zshrc` file:
```
if [[ `echo $TERM_PROGRAM` == "iTerm.app" ]]; then
  ./switch_user.sh
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```
want to execute a script for switching to another user after starting iterm2.
`switch_user.sh` is like this
```
expect -c "spawn sudo su prd
expect \":\"
send \"$pw\r\"
interact
"
``` 
This is the effect of using the script to automatically switch users,
[image](https://1drv.ms/u/s!Avtq-OjRB7B3gZIV_lQhhjiA__yLng)
when the window is maximized, the display content will not follow the change, and will always be the size of the initial window.

This is the effect after manually switching users, I think this is the correct realistic effect:
[image](https://1drv.ms/u/s!Avtq-OjRB7B3gZIWq-gEWpysyFUKOg)

I don't know if it's a problem with macos itself or something else

**Comment by romkatv** [comment]
This problem is not related to powerlevel10k. You can confirm this by disabling it or replacing it with another theme. The problem is caused by `expect` not forwarding SIGWINCH to its child process.

The right way to achieve what you want is by creating `/usr/loca/user/switch-to-prd` with the following content:

```zsh
exec sudo -iu prd
```

Then adding this at the top of `~/.zshrc`:

```zsh
[[ $USER == prd ]] || exec /usr/loca/user/switch-to-prd
```

And finally running `visudo` and adding `yourusername ALL=NOPASSWD: /usr/loca/user/switch-to-prd` in there.

If this doesn't work, please ask for help elsewhere given that this is not a powerlevel10k issue.

**Comment by tanyu-tci** [comment]
thank you very much.  I'm sorry about the issue of not being powerlevel10k
