### ISSUE TITLE
Show Package & Laravel prompt for Laravel projects with NodeJS frontend

### ISSUE THREAD

**Issue by skgeorgi** [romkatv/powerlevel10k#1888]
I would love to see both the package & laravel prompt simultaneous for Jetstream projects (Laravel with Intertia.js & Vue.js) as there is a package.json file in there as well:
![grafik](https://user-images.githubusercontent.com/6859554/171830308-3d347abf-3791-4e6d-ad8e-1e5624949536.png)

Currently, only the laravel prompt is displayed:
![grafik](https://user-images.githubusercontent.com/6859554/171829834-66af8080-2e44-4ca6-a2a2-d446bd470dfc.png)

Thank you so much for the great work! I really appreciate it!

**Comment by romkatv** [comment]
Try the following:

1. Open `~/.p10k.zsh`.
2. Search for "package" and uncomment the first hit.
3. Restart zsh with `exec zsh`.
4. If desired, you can customize the display of `package` by uncommenting `POWERLEVEL9K_PACKAGE_CONTENT_EXPANSION` and tweaking its value. See comments above it.

**Comment by skgeorgi** [comment]
Thanks for the quick reply! The package prompt is already uncommented and works fine in pure nodejs projects:
![grafik](https://user-images.githubusercontent.com/6859554/171833368-7af05624-05a7-4146-909e-8ef519711956.png)

Only in hybrid projects only the laravel prompt is displayed.

**Comment by romkatv** [comment]
What is the content of `package.json` in a hybrid project?

**Comment by skgeorgi** [comment]
Here is the content of `package.json`:
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@inertiajs/inertia": "^0.8.4",
        "@inertiajs/inertia-vue3": "^0.3.5",
        "@inertiajs/progress": "^0.2.4",
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.3.0",
        "@vue/compiler-sfc": "^3.2.22",
        "laravel-mix": "^6.0.39",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "postcss-import": "^12.0.1",
        "resolve-url-loader": "^4.0.0",
        "sass": "^1.43.2",
        "sass-loader": "^12.2.0",
        "tailwindcss": "^2.0.1",
        "vue": "^3.2.22",
        "vue-loader": "^16.8.3",
        "webpack": "^5.64.0"
    },
    "dependencies": {
        "axios": "^0.21"
    }
}
```

**Comment by skgeorgi** [comment]
My mistake! There is nothing to display in the package.json. It works as intended when adding missing `name` and `version`.
