### ISSUE TITLE
Custom prompt is broken

### ISSUE THREAD

**Issue by skyjia** [romkatv/powerlevel10k#189]
My custom prompt is broken since the commit https://github.com/romkatv/powerlevel10k/commit/cb1f6c48156e503a85a782194218c38ac28fec4b on master branch.

Please advise.

```zsh
prompt_custom_proxy_check() {
    if [ -z ${http_proxy+x} ]; then
        echo -n "";
    else
        echo -n "\ue78c $http_proxy";
    fi
}
POWERLEVEL9K_CUSTOM_PROXY_CHECK="prompt_custom_proxy_check"
POWERLEVEL9K_CUSTOM_PROXY_CHECK_BACKGROUND='cyan2'
POWERLEVEL9K_CUSTOM_PROXY_CHECK_FOREGROUND='black'
```

```zsh
zsh --version
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
```

**Comment by romkatv** [comment]
Sorry about that. Fixed.

P.S.

Powerlevel10k has a better API for custom prompts. Here's how yours would look like:

```zsh
prompt_proxy_check() {
  if [[ -n $http_proxy ]]; then
    p10k segment -b cyan2 -f black -i $'\ue78c' -t "$http_proxy"
  fi
}
```

You can now add `proxy_check` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` and configure it the same way as any builtin prompt segment.

This API is faster than the old-style custom prompts and it's more flexible. Type `p10k help segment` for more info.

**Comment by romkatv** [comment]
FYI: I just added `proxy` prompt segment to powerlevel10k. It's not exactly identical to your `prompt_proxy_check` but it might work for you.

To turn it on, you can either manually add `proxy` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`/`POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`, or uncomment `proxy` in `~/.p10k.zsh` after running `p10k configure`.

**Comment by skyjia** [comment]
Thanks! It does help.
