### ISSUE TITLE
How to customize the os_icon segment?

### ISSUE THREAD

**Issue by MainKt** [romkatv/powerlevel10k#1890]
Hello, 
I'm trying to turn the default ![Screenshot from 2022-06-04 18-19-40](https://user-images.githubusercontent.com/89859744/171999783-50cae74a-b24e-4eca-ac8d-7c6a6884f0f5.png)  
 into something like  ![Screenshot from 2022-06-04 18-19-24](https://user-images.githubusercontent.com/89859744/171999804-d3d4ea17-1f8b-4bd3-b9f9-a507c196a34a.png)

Can you please help me out?

Thank you so much for p10k :heart:

**Comment by romkatv** [comment]
You can modify colors in your `~/.p10k.zsh`: https://github.com/romkatv/powerlevel10k/blob/89ecd6539aad247fb85ca4ea4304b1704a9ef035/config/p10k-rainbow.zsh

Here's a one-liner to print colormap.

```zsh
for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
```

**Comment by MainKt** [comment]
thank you :)
