### ISSUE TITLE
zsh: command not found anaconda-navigator

### ISSUE THREAD

**Issue by Axo-Fv** [romkatv/powerlevel10k#1893]
Yesterday I installed p10k and today I want to use anaconda-navigator, but it seems that in someway my path variables are not in p10k. Where do I have to add or uncomment a line to fix this?

**Comment by Axo-Fv** [comment]
I think that I solved through `/home/Axo-Fv/anaconda3/bin/conda init zsh`. Is this the right way?

**Comment by romkatv** [comment]
Powerlevel10k doesn't do anything related to `PATH` or Conda. It only provides prompt.
