### ISSUE TITLE
Instant prompt not working properly with msys2 in Windows Terminal

### ISSUE THREAD

**Issue by cbconne** [romkatv/powerlevel10k#1894]
1. Open zsh, loading .zshrc file, and I can see powerlevel10k;
2. As expected, I should now be able to type commands (just plugins don't work like highlighting and autocompletion), but the terminal doesn't show any characters when I type the command;
3. Until .zshrc is loaded, the command I entered before is displayed in the terminal.

This looks like the command I entered in 2 does enter it just doesn't show in the terminal.
I have tried using msys2 directly instead of going through the Windows Terminal, it work well. I have also tried using Windows Terminal + ssh to connect to a remote linux machine with the same zsh configuration, it also work well.

**Comment by romkatv** [comment]
How can I reproduce this? How do you use msys2 in Windows Terminal?

**Comment by cbconne** [comment]
> How can I reproduce this? How do you use msys2 in Windows Terminal?

I refer to this document of msys2 for configuration. https://www.msys2.org/docs/terminals/
I installed zsh on windows via msys2, then oh-my-zsh and powerlevel10k, then the above problem occurs. I thought it was caused by the slow loading speed of oh-my-zsh at first, so I uninstalled oh-my-zsh and switched to zinit, but the same situation happened.

**Comment by cbconne** [comment]
I tried a few more and it looks like it's not just the windows terminal that is the problem, I have a similar situation when using the vscode terminal. And I've found that starting msys2 directly (via the default Mintty terminal) isn't entirely without problems: I can type text after booting, but after zsh loads there is a very obvious process of deleting and retyping my previous text.

![MSYS2 MSYS 2022-06-13 12-52-58_](https://user-images.githubusercontent.com/44186296/173282388-eb086949-bc60-44fe-8441-e7b03792231e.gif)

So I think it might be a problem with msys2.

**Comment by romkatv** [comment]
Oh, I see what you mean. This is a side effect of a slow terminal, slow zsh, or both. As for why it works the way it does, see https://github.com/romkatv/zsh-bench#instant-prompt

**Comment by cbconne** [comment]
Well, seems like it's difficult to get the best zsh experience on windows. Thank you.

**Comment by romkatv** [comment]
WSL + Windows Terminal are great. I highly recommend them. MSYS2 has no advantages over WSL1 (WSL2 is a different matter).

**Comment by cbconne** [comment]
> WSL + Windows Terminal are great. I highly recommend them. MSYS2 has no advantages over WSL1 (WSL2 is a different matter).

Yeah! I'm trying WSL and it's really good. Thank very much for your advice!
