### ISSUE TITLE
Suggestion: devcontainer badge

### ISSUE THREAD

**Issue by felipecrs** [romkatv/powerlevel10k#1895]
I use development containers as much as possible for my projects, and where I work, and since I install my dotfiles in the devcontainers too, their prompts are like mine from outside (which is confusing, some times).

It would be useful to have a badge/icon/glyph in the prompt to identify whether I'm running inside a devcontainer or not.

My dotfiles has a collection of environment variables to look at to identify such scenarios, currently:

- VS Code Remote Containers
- GitHub Codespaces
- Gitpod

https://github.com/felipecrs/dotfiles/blob/2e9f037775ed05ecc860153d3953d49476eba35c/home/.chezmoi.yaml.tmpl#L23

**Comment by romkatv** [comment]
You can implement it as a custom prompt segment. Something like this:

```zsh
function prompt_my_container() {
  if [[ -n $REMOTE_CONTAINERS$CODESPACES$VSCODE_REMOTE_CONTAINERS_SESSION$GITPOD_HOST ]]; then
    p10k segment -b yellow -f red -i 'icon'
  fi
}
```

Replace `icon` with whatever icon you want to display and add `my_container` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. See `p10k help segment` for documentation.

**Comment by felipecrs** [comment]
I ended up with this:

```bash
function prompt_my_devcontainer() {
  if [[ -n $REMOTE_CONTAINERS$CODESPACES$VSCODE_REMOTE_CONTAINERS_SESSION$GITPOD_HOST ]]; then
    p10k segment -f blue -i 'ﰭ' -t 'devcontainer'
  fi
}
```

```diff
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    ...
    toolbox                 # toolbox name (https://github.com/containers/toolbox)
+   my_devcontainer         # devcontainer indicator
    context                 # user@hostname
    nordvpn                 # nordvpn connection status, linux only (https://nordvpn.com/)
    ...
```

![image](https://user-images.githubusercontent.com/29582865/173197663-313cd7a7-92d0-4447-841f-e9de10f5bcc4.png)

Which is _Okay_ for me but may not be for widespread use (and that was my intention when I opened the issue).

I decided to go for an icon+text as there isn't a known icon for "devcontainers" (refs https://github.com/devcontainers/spec/issues/42).

Nevertheless, thanks so much for the implementation suggestion!
