### ISSUE TITLE
Empty Line At The Bottom

### ISSUE THREAD

**Issue by isknurul007** [romkatv/powerlevel10k#1896]
Hello Sir,
How do I remove the empty line at the bottom?

<img width="446" alt="powerlevel10k" src="https://user-images.githubusercontent.com/106715990/173217058-e5b28621-1ff3-494b-a82b-6060ff35be8a.png">

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with another theme?

**Comment by isknurul007** [comment]
Cursor is at the bottom when using oh_my_zsh **frontcube** theme

<img width="530" alt="frontcube" src="https://user-images.githubusercontent.com/106715990/173234912-c95f4318-97e6-4705-bd73-cb7259858532.png">

**Comment by romkatv** [comment]
What happens if you replace your `~/.zshrc` with this?

```zsh
if [[ ! -e ~/powerlevel10k ]]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  make -C ~/powerlevel10k pkg
fi

POWERLEVEL9K_MODE=ascii
POWERLEVEL9K_DISABLE_HOT_RELOAD=true

source ~/powerlevel10k/powerlevel10k.zsh-theme
```

**Comment by isknurul007** [comment]
Hello Sir,

Found the issue... getting this empty line if the text font size is more than 15 in terminator, and If I keep it 15 or less than 15 then it works fine

**Comment by romkatv** [comment]
I'm glad you've found the culprit.
