### ISSUE TITLE
I use Zsh as my shell. I have installed 4 recommended fonts, but I still can't display icons on my terminal

### ISSUE THREAD

**Issue by AlienwareBoy** [romkatv/powerlevel10k#1897]
I use Zsh as my shell. I have installed 4 recommended fonts, but I still can't display icons on my terminal
<img width="530" alt="image" src="https://user-images.githubusercontent.com/25809878/173244069-04dce1a1-6940-42ba-8346-b097d4db009a.png">

**Comment by romkatv** [comment]
Please follow the instructions at https://github.com/romkatv/powerlevel10k/blob/master/font.md#manual-font-installation. Note that there are four numbered steps in there. All are necessary.
