### ISSUE TITLE
Feature request: with transient prompt, possibility to do a "snapshot" of the entire current prompt (not remove it from the previous commands list)

### ISSUE THREAD

**Issue by mzannoni** [romkatv/powerlevel10k#1898]
I've found out that there is one thing I miss when using transient prompt: some of the output that could be interesting to keep (e.g. the time it took a command to run) is anyhow deleted.

It would be very interesting if it was possible, e.g. through a key binding, to keep the entire current prompt, instead of just the stdin/stdout/stderr string.

The main use I'd find for this it to be able to "keep note" of the run time of a completed command, without having to copy past / note down somewhere else. I could see also some other interesting use for this, when for instance generating bug reports or documentation.

I could also help adding this feature, maybe as a plugin. Some hints towards where to look for this to be developed from someone already familiar with the code base would be of great help.

**Comment by mzannoni** [comment]
Just came to my mind one "easy" workaround could be to toggle the transient prompt, hit enter, that toggle the transient prompt back on.
Is it possible to toggle it from the command line?

**Comment by romkatv** [comment]
You can customize prompt for completed commands. By default it consists only of `prompt_char` but you can enable arbitrary prompt segments in there. For example, you can enable `command_execution_time`, which display how long each command took to execute. If you attach your `~/.p10k.zsh`, I'll show you how to do it.

Note that prompts for past commands cannot be modified. Once a command starts executing, the corresponding prompt is fixed forever. So you cannot have a keybinding that enables or disables `command_execution_time` for past prompts. You can, however, create a keybinding that will affect the current and all future prompts. Here's how:

```zsh
function toggle-transient-prompt() {
  if [[ $POWERLEVEL9K_TRANSIENT_PROMPT == always ]]; then
    POWERLEVEL9K_TRANSIENT_PROMPT=off
  else
    POWERLEVEL9K_TRANSIENT_PROMPT=always
  fi
  p10k reload
  if zle; then
    zle push-input
    zle accept-line
  fi
}

zle -N toggle-transient-prompt
bindkey '^T' toggle-transient-prompt  # Ctrl-T to toggle transient prompt in powerlevel10k
```

**Comment by mzannoni** [comment]
Thanks a lot. This one works to toggle the transient prompt.
However, since it calls one command to do that, the prompt I'm actually interested in (the current one, before running any command, which has information on the last executed command) is lost.

Are you saying that there is no way to "save" the current prompt, but only future ones?
It would still be useful, I'd have to remember to toggle the transient prompt before executing something for which I want to keep the running time (but sometimes I may not know in advance...).

**Comment by romkatv** [comment]
Thanks for the explanation. Yes, this is possible. If you attach your `~/.p10k.zsh` I can show you how.

**Comment by mzannoni** [comment]
Thanks a lot for you feedback, I appreciate a lot.
You can find the latest version of my `.p10k.zsh` [here](https://gitlab.com/mzannoni/bill_kinda_notes/-/blob/6c8d7f63e9e8931490edfb81d97e79f5c8279b41/generic/zsh/p10k_mz).

**Comment by mzannoni** [comment]
Thanks a lot for the tips.
It is not exactly what I had in mind :smile: but it's a good workaround, which I think I'll be using.

And it also offers me some good hints where to look for, if I wanna try implement something along this line myself.

**Comment by romkatv** [comment]
The documentation for `p10k display` can be found in the output of `p10k help display`. `p10k-on-pre-prompt` is executed before a new prompt is rendered, while `p10k-on-post-prompt` is executed when you press enter and before the command starts executing. Hopefully this should be enough to implement what you have in mind.
