### ISSUE TITLE
Shorten Strategy not respecting package files order

### ISSUE THREAD

**Issue by gabrielboliveira** [romkatv/powerlevel10k#190]
Hi! First, thanks for this wonderful theme.

I'm having a few problems using the `truncate_with_package_name` option for shorten strategy. Basically on projects that contains both `package.json` and `composer.json`, the theme doesn't respect the order of files I chose. It always picks `composer.json`.

For example:

composer.json:
```json
{
    "name": "a"
}
```

package.json:
```json
{
    "name": "b"
}
```

.zshrc:
```sh
POWERLEVEL9K_DIR_PACKAGE_FILES=( composer.json package.json )
# or
POWERLEVEL9K_DIR_PACKAGE_FILES=( package.json composer.json )
```

Doesn't matter which one I put on `.zshrc`, the result will always be `a`. I would suggest that it follows the order of `DIR_PACKAGE_FILES` variable, and if that file doesn't contains a "name" attribute, picks the next one.

I'm not sure if its a bug or expected behavior. But for example, I work on a few Laravel projects that customizes the "package.json" and others "composer.json", always keeping the "composer.json" content. Sometimes that's just the default "laravel/laravel" 😄 

Thanks!

**Comment by romkatv** [comment]
It's not difficult to do what you are asking but first I'd like to make sure this is what you really want.

To the best of my knowledge, there is only one good shortening in p10k and it's not `truncate_with_package_name`. Rather than tuning `truncate_with_package_name`, I'd prefer to make the default work better so that it satisfies your needs.

Have you tried running `p10k configure`? If not, please update powerlevel10k and run it. You might want to install [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k) beforehand to ensure everything renders properly. Then see if the directory in your prompt behaves satisfactorily. If something is lacking, please describe what you want changed.

The config generated by `p10k configure` enabled directory truncation as described in https://asciinema.org/a/258376. See the description of the for the specification of the algorithm. The important thing for you is that directories that contain `composer.json` or `package.json` are rendered in a different (brighter) color. They also never get shortened. Unlike with `truncate_with_package_name`, no directories get renamed. This is a good thing IMO.

**Comment by gabrielboliveira** [comment]
@romkatv Thanks for your feedback! I already had configured everything, and since I didn't find how to solve this specific problem opened this issue.

So this is my current usage:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/11093090/63865273-948a5980-c9b1-11e9-804a-a89b35d0f3df.png">
<img width="263" alt="image" src="https://user-images.githubusercontent.com/11093090/63865281-9a803a80-c9b1-11e9-97b3-d5cf168955a2.png">

I like to have just the project name, without the path. My suggestion would be that I could have several files under `POWERLEVEL9K_DIR_PACKAGE_FILES`, and it would use the others as fallback. For that example above, no matter if I have package.json or composer.json as first, it would always pick the composer.json name.

If for some reason one of them doesn't have a `name` attribute, would be good to use the next file as fallback, but respecting the orders. Right now to have the images result I have to leave only `package.json` on the array.

Does that makes sense?

**Comment by romkatv** [comment]
> Have you tried running p10k configure? If not, please update powerlevel10k and run it. You might want to install the recommended font beforehand to ensure everything renders properly. Then see if the directory in your prompt behaves satisfactorily. If something is lacking, please describe what you want changed.

Have you tried it?

> I like to have just the project name, without the path.

You don't want to have the current directory in your prompt? Is this correct?

Could you provide an example of a directory and its files and describe what you want your prompt to show?

**Comment by gabrielboliveira** [comment]
> Have you tried it?

Yes, still didn't work as expected.

> You don't want to have the current directory in your prompt? Is this correct?

Yeah, exactly.

The directory should have 2 files: composer.json and package.json as described on the first comment.

**Comment by romkatv** [comment]
> Yeah, exactly.

Then I think you shouldn't put `dir` in your configuration.

> The directory should have 2 files: composer.json and package.json as described on the first comment.

Sorry, this isn't enough for me to understand what you want.

From the very first post you've made I though I knew what you wanted. Your second comment confused me somewhat. Now I'm not sure we are even talking about the same thing. A few examples of what you want your prompt to look like in different situations would help a lot.

**Comment by gabrielboliveira** [comment]
No problem, let me explain everything again.

Assume these variables and these files:

```sh
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_with_package_name"
POWERLEVEL9K_DIR_PACKAGE_FILES=(package.json composer.json)
```

composer.json:
```json
{
    "name": "composer"
}
```

package.json:
```json
{
    "name": "package"
}
```

In this case, since the `package.json` comes before `composer.json` on the `POWERLEVEL9K_DIR_PACKAGE_FILES` variable, it should print `package` as this image:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/11093090/63865273-948a5980-c9b1-11e9-804a-a89b35d0f3df.png">

If you remove the "name" attribute from package.json and keep it empty, should show "composer", since it will read the next file on `POWERLEVEL9K_DIR_PACKAGE_FILES`:

package.json:
```json
{
}
```

<img width="263" alt="image" src="https://user-images.githubusercontent.com/11093090/63865281-9a803a80-c9b1-11e9-97b3-d5cf168955a2.png">

-----------

> Then I think you shouldn't put dir in your configuration.

The thing is, the `truncate_with_package_name` only truncates when it finds the package name attribute on files mentioned on DIR_PACKAGE_FILES. Otherwise it keeps the directory as usual:

<img width="188" alt="image" src="https://user-images.githubusercontent.com/11093090/63872026-4bd89d80-c9bd-11e9-8276-fd77f023365f.png">

**Comment by romkatv** [comment]
I don't think what you are asking for is a good idea but I was unable to figure out your real needs. So, for the sake of progress on this issue I'll abandon my attempts at understanding your needs and will focus on the specific things you are asking for.

> No problem, let me explain everything again.
> 
> Assume these variables and these files:
> 
> ```shell
> POWERLEVEL9K_SHORTEN_STRATEGY="truncate_with_package_name"
> POWERLEVEL9K_DIR_PACKAGE_FILES=(package.json composer.json)
> ```
> 
> composer.json:
> 
> ```json
> {
>     "name": "composer"
> }
> ```
> 
> package.json:
> 
> ```json
> {
>     "name": "package"
> }
> ```
> 
> In this case, since the `package.json` comes before `composer.json` on the `POWERLEVEL9K_DIR_PACKAGE_FILES` variable, it should print `package` as this image:
> 
> <img alt="image" width="256" src="https://user-images.githubusercontent.com/11093090/63865273-948a5980-c9b1-11e9-804a-a89b35d0f3df.png">
> 
> If you remove the "name" attribute from package.json and keep it empty, should show "composer", since it will read the next file on `POWERLEVEL9K_DIR_PACKAGE_FILES`:
> 
> package.json:
> 
> ```json
> {
> }
> ```
> 
> <img alt="image" width="263" src="https://user-images.githubusercontent.com/11093090/63865281-9a803a80-c9b1-11e9-97b3-d5cf168955a2.png">

You like everything about `truncate_with_package_name` except that it doesn't guarantee which file it'll pick `name` from if there is more than one. Is this correct?

If there is more than one match against the first pattern, do you care which one will get picked? For example, given `POWERLEVEL9K_DIR_PACKAGE_FILES=('*.json' 'foo' 'bar.json')` the first pattern might match more than one file. Is it OK to pick `name` from a random match in this case?

> The thing is, the `truncate_with_package_name` only truncates when it finds the package name attribute on files mentioned on DIR_PACKAGE_FILES. Otherwise it keeps the directory as usual:
> 
> <img alt="image" width="188" src="https://user-images.githubusercontent.com/11093090/63872026-4bd89d80-c9bd-11e9-8276-fd77f023365f.png">

And this is what you want, right? You do want to see the whole current directory in this case?

Also, when you in a subdirectory of a directory with `package.json` in it, you want to see the subdirectory?

**Comment by gabrielboliveira** [comment]
Shouldn't be that hard to understand, sorry if I can't properly explain. 

On directories that **have** any of files from `POWERLEVEL9K_DIR_PACKAGE_FILES`, it should try reading the "name" from those. 

If it finds in the first one, stop there and show that value. This is what I meant on my last comment about removing the "name" from `package.json`. 

If there's no name on it, continue to the next one.

The thing I like from `truncate_with_package_name` is that if it **has** a valid name on any of those files, it shows only that, without the full directory. But if it doesn't really have any valid file with "name" attribute, shows the directory path.

That works well when working with Node and PHP projects with `composer.json` and `package.json` files.

But really, this was more a suggestion or a simple feature request. This looks like a very specific use case for me 😄

**Comment by romkatv** [comment]
> Shouldn't be that hard to understand, sorry if I can't properly explain.

I understood what you are asking me to implement from the first issue description. I then asked what you actually need and got confused because I thought you are answering my questions while in fact you kept repeating what changes you want to see in p10k.

Anyway, I've implemented what you asked for.

**Comment by gabrielboliveira** [comment]
Thanks! will try that out right away
