### ISSUE TITLE
Access prompt elements from shell

### ISSUE THREAD

**Issue by yhshin11** [romkatv/powerlevel10k#1900]
Hi all. Is there a way to access the displayed prompt elements from the shell somehow?

For example, if the zsh prompt is currently displaying the following elements, is there a way to access the `dir` and `vcs` elements from the shell?

```
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    # os_icon               # os identifier
    dir                     # current directory
    vcs                     # git status
    # =========================[ Line #2 ]=========================
    newline                 # \n
    # prompt_char           # prompt symbol
  )
```

The reason I'm asking is I am trying to customize my tmux configuration to display the current working directory, vcs, etc. For consistency, it would be nice if tmux could access these prompt elements from zsh directly so I don't need to figure how to format these myself.

Cheers!

**Comment by romkatv** [comment]
No, it's not possible.

**Comment by yhshin11** [comment]
Fair enough. Thanks
