### ISSUE TITLE
GPL License Compliance

### ISSUE THREAD

**Issue by ISCAS-Vulab** [romkatv/powerlevel10k#1902]
The gitstatus in the project is released under the GPL-3.0 license. According to the GPL-3.0 license, the overall project also needs to be released under GPL-3.0 license. The project is licensed under the MIT license. Should it be changed to GPL-3.0？

**Comment by romkatv** [comment]
> The gitstatus in the project is released under the GPL-3.0 license.

Correct.

> According to the GPL-3.0 license, the overall project also needs to be released under GPL-3.0 license.

I don't think this is true.
