### ISSUE TITLE
Keep Transient Prompt on the same line

### ISSUE THREAD

**Issue by dripware** [romkatv/powerlevel10k#1904]
hello. thanks for the amazing plugin.
i don't know how to word this but i want the transient prompt to be on the same line when i execute a command.
i wrote this shell script to demonstrate what i want.
```zsh
#!/usr/bin/env
__prompt_flusher(){
  echo -ne "\r\033[2K>$BUFFER" # clear line
  zle accept-line
}
zle -N __prompt_flusher
bindkey '^M' __prompt_flusher
```
[![asciicast](https://asciinema.org/a/qdIkW48GIKpeMiIKxcA1NlsLp.svg)](https://asciinema.org/a/qdIkW48GIKpeMiIKxcA1NlsLp)
this script simply clears the prompt line and replaces its content with a ">" character and the command entered. however doing this. the command loses its syntax highlighting (i'm using [`fast-syntax-highlighting`](https://github.com/zdharma-continuum/fast-syntax-highlighting/blob/master/fast-string-highlight)). also i want to use the powerlevel10k prompt icon.

**Comment by romkatv** [comment]
Transient prompt in powerlevel10k works just like in the ascinema you posted.

**Comment by dripware** [comment]
you are right. the reason why the prompt wasn't staying on the same line was because `POWERLEVEL9K_PROMPT_ADD_NEWLINE=true` in `p10k.zsh`. i turned it off and it fixed the issue. 
thanks
