### ISSUE TITLE
Keep some of the prompt information with Transient Prompt

### ISSUE THREAD

**Issue by dripware** [romkatv/powerlevel10k#1905]
is it possible to keep some information in the prompt after executing the command (working directory, time, etc. ) when using transient prompt?
when i'm looking back at my terminal emulators history i found out that most the time i  use the prompt colors to quickly identify where a command output ends and where one starts. but when using transient prompt it's not as obvious anymore. so my solution to that was to see if i can keep some of the colors from the full prompt in the transient prompt.

also is it possible to do this with #1904 at the same time?

thanks!

**Comment by romkatv** [comment]
> is it possible to keep some information in the prompt after executing the command (working directory, time, etc. ) when using transient prompt?

Yes. If you search through issues, you'll find dozens of similar ones, all with solutions. Please give it a shot.

**Comment by dripware** [comment]
thanks for your help.
i managed to do it like this:
```zsh
function p10k-on-post-prompt() {
  p10k display '1/left/*'=hide
  p10k display '1/left/(dir|prompt_char)'=show
}
function p10k-on-pre-prompt() {
  echo
  p10k display '1/left/(vcs)'=show
}
```
if i'm correct. this is just doing transient prompt but manually with more control.

**Comment by romkatv** [comment]
> if i'm correct. this is just doing transient prompt but manually with more control.

That's right.

You shouldn't use that `echo` though. Instead, show/hide `empty_line`.

**Comment by dripware** [comment]
thanks for the tip!
one more question tho.
how can i make it dynamic? instead of hard coding `p10k display '1/left/(vcs)'-show` how can i make it so that it in `p10k-on-pre-prompt` restores the `POWERLEVEL9K_LEFT_ELEMENTS` and `POWERLEVEL10K_RIGHT_ELEMENTS`

**Comment by romkatv** [comment]
You can specify which elements you want to hide and show. You can use wildcards in there (e.g., `1/left/*`). This is documented in `p10k help display`.
