### ISSUE TITLE
'ls' command in vscode terminal

### ISSUE THREAD

**Issue by teedy8023mars** [romkatv/powerlevel10k#1907]
![Screen Shot 2022-06-20 at 5 29 28 AM](https://user-images.githubusercontent.com/31605638/174501005-347cb256-7bfb-4a4a-932d-43117b0b508f.png)
'ls' in vscode command, there is a six-dot icon beside the 'folder' icon.
But in iTerm, there isn't.( and I set the font as 'MesloLGS NF' for both terminals
![Screen Shot 2022-06-20 at 5 32 04 AM](https://user-images.githubusercontent.com/31605638/174501084-132595fd-a13c-4e94-bf8d-85afc0866847.png)

**Comment by romkatv** [comment]
Powerlevel10k has no influence on this. You can verify this by disabling powerlevel10k or replacing it with another theme. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect
