### ISSUE TITLE
Black arrow instead of 0-color

### ISSUE THREAD

**Issue by vomidug** [romkatv/powerlevel10k#1910]
Hi

I am using p10k inside kitty term with transparent background and found out, that arrow symbol between context and dir sections seems to be hardcoded as black. It's definitely not a big deal, but probably there is a way to fix it?

Screenshot provided

Thanks in advance.

![image](https://user-images.githubusercontent.com/38423889/174736178-f04e8af0-e76e-4e6c-9a4b-890e953214ac.png)

**Comment by romkatv** [comment]
Apparently Kitty displays background with the color code 0 as transparent. There might be an option in it to turn this off. If there isn't, you'll have to manually edit `~/.p10k.zsh` and replace all 0 backgrounds with something else.

**Comment by vomidug** [comment]
Kitty displays 0 as transparent, that is true, but what is wrong with it's settings? The rest of 0-backgrounds are rendered transparent as expecxted
I've tried alacritty and it shows the same black arrow - psb screenshot
![image](https://user-images.githubusercontent.com/38423889/174786596-b5cdac68-e054-4e7b-9c16-d5793b08bb96.png)

**Comment by romkatv** [comment]
> Kitty displays 0 as transparent, that is true, but what is wrong with it's settings?

I mean that Kitty might have an option to disable this unfortunate behavior. I don't know why anyone would want to lose the ability to display text with background 0.

> I've tried alacritty and it shows the same black arrow - psb screenshot

Maybe it has an option to disable this.

Anyway, closing as there is nothing to do in powerlevel10k to remedy this. You either need to use a terminal without this issue, configure your existing terminal to respect background 0, or manually change background 0 in `~/.p10k.zsh` with a different color.
