### ISSUE TITLE
Use icons from other fonts

### ISSUE THREAD

**Issue by hensz** [romkatv/powerlevel10k#1911]
Hi!

For reasons I want to use Fira Code instead of the patched Meslo fonts. Is it possible (and if yes: how?) to use the icons provided by my preferred font? As you can see here
https://github.com/tonsky/FiraCode/blob/master/extras/console.png
Fire Code contains icons like the lock or the branch symbol.

In this issue
https://github.com/tonsky/FiraCode/issues/1053
the creator of Fira Code explains that the code that Fira Code uses for e.g. the branch icon is the more common one, and Meslo NF is the only one that uses different codes.

I know that I can define which codes are used for which symbol (e.g. as mentioned in the isse:  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uE0A0'), but I don't know which icons exist at all, and which codes these have for my font. Is there a list of icons with codes?

There seems to be some kind of common understanding of powerline icon codes:
https://github.com/ryanoasis/powerline-extra-symbols
Would it be possible to simply support these codes for powerlevel10k, e.g. by providing a dedicated configuration for these codes? This would enable using all nerd fonts from this repo, and most likely even more: https://github.com/ryanoasis/nerd-fonts

**Comment by romkatv** [comment]
All nerd fonts have the same icons with the same codes. You can use FiraMono from nerd fonts and it'll work (although icons will be smaller than in my font).

> I don't know which icons exist at all, and which codes these have for my font. Is there a list of icons with codes?

That would be a question to your font provider. You can also use an app that allows you to browse glyphs from a font. Most popular operating systems come with an app like this by default.

> There seems to be some kind of common understanding of powerline icon codes: https://github.com/ryanoasis/powerline-extra-symbols. Would it be possible to simply support these codes for powerlevel10k

Powerline glyphs are supported by powerlevel10k by default.

**Comment by hensz** [comment]
Fira Mono has no ligatures. If I use the regular Fira Code, the lock icon is not displayed properly:
![image](https://user-images.githubusercontent.com/1984979/174972501-c6d873bd-25b0-4f27-af63-4ccd6e3d63e0.png)

> Most popular operating systems come with an app like this by default.

I agree that Windows is not that popular ;-)
However my question was aiming to something different: I want to know which icons powerlevel10k supports and which are the variables that contain the code, so that I can manually redefine the icon codes.

> Powerline glyphs are supported by powerlevel10k by default.

As stated in the issue https://github.com/tonsky/FiraCode/issues/1053 the codes are different. Powerlevel10k expects the branch symbol to be at code U+F126, while for the powerline glyphs the branch symbol is at code U+E0A0, as you can also see here: https://github.com/ryanoasis/powerline-extra-symbols/blob/master/img/fontforge.png

**Comment by hensz** [comment]
> > If I use the regular Fira Code, the lock icon is not displayed properly

> Then you should reply No. ... (It doesn't ask about all glyphs it can use because if your font doesn't have one Font Awesome or Powerline glyph, then it won't have the rest of them.)

The thing is: If I answer No, no other icons are displayed, but my font has this icon, albeit with a different code. And even if it had other icons that powerlevel10k could display correctly, the configuration wouldn't try, since as you said, it assumes that if the font doesn't have one, it also has no others.

> Windows is the most popular desktop operating system. It comes with Character Map app preinstalled.

I didn't know that Character Map also displays the unicode encoding. Thanks for pointing that out.

> > I want to know which icons powerlevel10k supports

> What exactly does it mean? Powerlevel10k supports all icons.

With "supports" I meant which icons are used by powerlevel10k for prompt etc. These are obviously not all of the hundreds of icons a font contains, but only a subset, like the branch symbol, the lock and some more.

> > which are the variables that contain the code, so that I can manually redefine the icon codes.

> All variables are in ~/.p10k.zsh.

Yes, they are scattered throughout this file. But can you perhaps provide a compact list of the variables (ideally with the codes that powerlevel10k uses to display these icons)? Also it would be helpful to know what the icon is used for. Of course, the branch icon is rather clear, but others like POWERLEVEL9K_VCS_UNTRACKED_ICON or POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION (is this an icon?) not necessarily.

> If you are referring to https://github.com/tonsky/FiraCode/issues/1053#issuecomment-632921957, that comment is misleading. I've added my own comment there that should help.

Yes, I was referring to this. In your comment you wrote this:
"Run p10k configure and answer questions correctly to let Powerlevel10k know which glyphs your font has. Powerlevel10k won't use glyphs that you font doesn't have."

However, my font does have these glyphs, but with a different code. How can I tell powerlevel10k to use the glyphs from the Powerline glyphs, and not from the Font Awesome glyphs? If I answer "no" when asked for the lock icon, no symbols are displayed.

My assumption was, that I can somehow tell powerlevel10k to use glyphs with a different code, just as suggested in the comment, e.g.   typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uE0A0'
In my case this doesn't work, at least I don't see any effect.
But if this would technically work, can you provide a configuration that sets all icons that powerlevel10k "knows" or uses to the respective values from the Powerline extra symbols? Or is this not possible?

**Comment by romkatv** [comment]
> The thing is: If I answer No, no other icons are displayed, but my font has this icon, albeit with a different code.

Your font does not have this icon at all. It has no Font Awesome icons.

> And even if it had other icons that powerlevel10k could display correctly, the configuration wouldn't try, since as you said, it assumes that if the font doesn't have one, it also has no others.

The assumption is correct. Your font does not have any Font Awesome icons.

Your font has the "branch" icon from Powerline, and you can by heeding this comment: https://github.com/romkatv/powerlevel10k/blob/0c197ed4a51e10ed613e48a080f23b1ee7968006/config/p10k-rainbow.zsh#L354-L355

> With "supports" I meant which icons are used by powerlevel10k for prompt etc.

Powerlevel10k can display all icons from all fonts. Configuration wizard is a generator for `~/.p10k.zsh` that can produce thousands of different configs depending on your choices. You can also write this file by hand.

> Yes, they are scattered throughout this file. But can you perhaps provide a compact list of the variables (ideally with the codes that powerlevel10k uses to display these icons)?

I can scan the file and point out every variable related to icons. You can do the same, so I won't.

> Also it would be helpful to know what the icon is used for. Of course, the branch icon is rather clear, but others like POWERLEVEL9K_VCS_UNTRACKED_ICON or POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION (is this an icon?) not necessarily.

The comments in `~/.p10k.zsh` is all documentation that there is. It's far from perfect but it is what it is.

> Yes, I was referring to this. In your comment you wrote this: "Run p10k configure and answer questions correctly to let Powerlevel10k know which glyphs your font has. Powerlevel10k won't use glyphs that you font doesn't have."
> 
> However, my font does have these glyphs, but with a different code.

This isn't so.

> How can I tell powerlevel10k to use the glyphs from the Powerline glyphs, and not from the Font Awesome glyphs?

By correctly answering questions in the wizard.

When you go with powerline but without font awesome, the generated config doesn't use the "branch" icon but you already know how to change that.

> If I answer "no" when asked for the lock icon, no symbols are displayed.

Because your font doesn't have icons other than the tiny set from powerline. The only glyph in there that can even be called an icon is the "branch".

> My assumption was, that I can somehow tell powerlevel10k to use glyphs with a different code, just as suggested in the comment, e.g. typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uE0A0' In my case this doesn't work, at least I don't see any effect.

Which comment are you referring to? The one for branch is here and it's different from what you quoted: https://github.com/romkatv/powerlevel10k/blob/0c197ed4a51e10ed613e48a080f23b1ee7968006/config/p10k-rainbow.zsh#L354-L355

> But if this would technically work, can you provide a configuration that sets all icons that powerlevel10k "knows" or uses to the respective values from the Powerline extra symbols? Or is this not possible?

This is already the case. The only icon from powerline that isn't enabled by default (it's in fact the only icon that powerline has) is branch. There is a comment telling you how to enable it.

**Comment by romkatv** [comment]
Closing as I've already spent more time on this than reasonable. I won't comment here further.

**Comment by romkatv** [comment]
My apologies, I just realized there is a typo in the comment and this is the source of confusion. It should be like this:

```zsh
# Branch icon. Set this parameter to '\UE0A0 ' for the popular Powerline branch icon.
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
```

I'll fix it in the code. Sorry again for not noticing it and doubling down. The rest of my comments are correct as far as I can tell.

**Comment by romkatv** [comment]
Thanks for the update.

As I mentioned earlier, you can also use Fira from Nerd Fonts and you'll get all icons. If you want ligatures (usually a terrible idea in a terminal but I'm not the one to judge), use the non-monospace version.

**Comment by romkatv** [comment]
> What do you mean with "from Nerd Fonts"? This project: https://github.com/ryanoasis/nerd-fonts ?

Yes. Specifically, [this font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete%20Windows%20Compatible.ttf). It's a good idea to also install bold, italic and bold-italic. Otherwise your terminal will attempt to synthesize bold and italic glyphs based on the regular font.

> I tried FIra Code from there, but still I don't have all icons, only the powerline ones.

Double-check that this is true (it's **extremely** implausible) and open a bug against Nerd Fonts.

**Comment by romkatv** [comment]
I'm glad it all worked out in the end.
