### ISSUE TITLE
Terminal in Atom displays wrong path

### ISSUE THREAD

**Issue by andrzej-natzka** [romkatv/powerlevel10k#1912]
I installed Powerlevel10k on Oh-my-zsh.
In Atom I have terminal package installed: platformio-ide-terminal
When I start atom from iterm2 by typing `atom .` and then start terminal in atom I see following as a prompt:
`
5:31m%
5:31m5:31m5:39m~5:39m5:31m5:31m5:31m5:31m 5:31m5:76m❯5:76m5:76m5:76m
`
It is not the case when I start Atom as a program. Vs code works fine. Strangely on my other mac it works fine.
I verified .zshrc and on both macs and it is the same. I have the same packaged installed on both in atom. Configuration for terminal in atom is as well the same. Any idea what can be wrong ?

**Comment by romkatv** [comment]
When you start one terminal form another, you can end up with environment variables from both. Some of these environment variables say what terminal you are using. As a result, programs running in the terminal can be confused.

**Comment by andrzej-natzka** [comment]
It is quite convenient to run it from destination but I got your point. Thanks for quick reply.

**Comment by romkatv** [comment]
You can probably figure out which environment variable(s) cause the issue and unset them before you start the terminal. You can try this instead of `atom .`:

```zsh
( unset -pm '*TERM*'; atom . )
```

**Comment by andrzej-natzka** [comment]
This did not help, but thx for this tip. I noticed I have iterm2 beta version on one of my mac. After retruning to stable all works fine. Thanks for quick help ! Awesome support !

**Comment by andrzej-natzka** [comment]
Thanks!

**Comment by romkatv** [comment]
> This did not help

That's surprising. Ah! I've made a typo in the command. `unset -pm` should've been `unset -m`.
