### ISSUE TITLE
Text cut off

### ISSUE THREAD

**Issue by holiq** [romkatv/powerlevel10k#1917]
I use powerlevel and font [Meslo Nerd Font patched for Powerlevel10k](https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k) on my termux, but in my neovim, the italic text is cut off like in the screenshot below, if i use another font the italic text is not cut off but the icon at the prompt does not appear or error, so how to fix that?
![Screenshot_20220624-173212_Termux](https://user-images.githubusercontent.com/30729921/175522263-a9678bc8-471b-433d-9d5e-0f1d0bf94b14.png)

**Comment by romkatv** [comment]
File a bug against Termux.

**Comment by holiq** [comment]
> 

Okay thank you
