### ISSUE TITLE
feature idea - verbose prompt

### ISSUE THREAD

**Issue by rwmitchell** [romkatv/powerlevel10k#1918]
P10K is great!  Love it!

Would it be possible to have a command  to break down the current prompt as a list showing the prompt value along with a more descriptive label?

Many parts of a prompt may only appear when certain conditions are met.  Given their infrequency, it is easy to forget their significance.  A command to fully describe the current prompt values would be useful.

**Comment by romkatv** [comment]
It's a good idea but it's not something I'm going to implement due to time constraints. It's already on my list of potential improvements. Closing as Won't Fix. Sorry.
