### ISSUE TITLE
[not a issue] How can I disable dir shorten?

### ISSUE THREAD

**Issue by TylerTemp** [romkatv/powerlevel10k#192]
Hi, I realize the config of `POWERLEVEL9K_SHORTEN_STRATEGY` and `~/.p10k.zsh` config, but I can not manage to set the dir shortening strategy as:

1.  Shorten my `$HOME` prefixed path as `~`
2.  Keep any other folder untouched

Any help? Thanks

**Comment by romkatv** [comment]
It's not clear from your request what you want changed so I'll make guesses.

If the current directory in your prompt shows weird things such as `~_p9k_pwd`, add `unsetopt auto_name_dirs` to your `~/.zshrc`.

By default the current directory gets shortened until all of the following conditions are satisfied:

1. The current directory is at most 80 characters long.
2. Left prompt doesn't overflow the line.
3. Left prompt doesn't overlap right prompt.
4. If the prompt is a one-liner:
4.1. The empty space between the left and the right prompts is at least 40 characters.
4.2. The empty space between the left and the right prompts is at least 50% of the terminal width.

To disable (1), open `~/.p10k.zsh` and search for `POWERLEVEL9K_DIR_MAX_LENGTH`. Either increase its value or set it to empty for infinity.

To disable (4.1), open `~/.p10k.zsh` and add `typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0`.

To disable (4.2), open `~/.p10k.zsh` and add `typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0`.

**Try the tweaks listed above first. It's likely that you won't need to completely disable directory shortening.**

To completely disable directory shortening, open `~/.p10k.zsh` and search for `POWERLEVEL9K_SHORTEN_STRATEGY` and `POWERLEVEL9K_SHORTEN_DIR_LENGTH`. Remove or comment-out both of these parameters. **This is unlikely to be the best solution for you. It's virtually always preferable to shorten the current directory than to allow prompt to wrap around on the next line.**

**Comment by romkatv** [comment]
Closing due to the lack of activity. Please reopen if the issue is not resolved.

**Comment by TylerTemp** [comment]
Hi, 

`POWERLEVEL9K_SHORTEN_STRATEGY` and `POWERLEVEL9K_SHORTEN_DIR_LENGTH` works! Thanks a lot.

And sorry I didn't see that there are comments inside `.p10k.sh` file
