### ISSUE TITLE
Using the SHORTEN_STRATEGY in other segments

### ISSUE THREAD

**Issue by jnordwick** [romkatv/powerlevel10k#1920]
Is there a way to either call  a function or decorate a directory in a (custom) segment so that they will pass through the the same shortening code that cwd does? I have a couple segments for adding the dirstack to the prompt - one for just top element and one segment that does top 5  horizontal, and it would be nice if they all displayed the same.

**Comment by romkatv** [comment]
Nope, powerlevel10k doesn't have this.
