### ISSUE TITLE
branch name shortening is too short or should not display folder

### ISSUE THREAD

**Issue by kaurov** [romkatv/powerlevel10k#1921]
If the GIT branch consists the folder 
git checkout -b feature/som-337-validate-objectbricks-in-attributes-field

then it is shortened as 'feature/som-…ibutes-field'.
In my case, som-337 is the most important information.

<img width="1125" alt="Screenshot 2022-07-01 at 11 18 59" src="https://user-images.githubusercontent.com/2579907/176865791-294291d8-5cbf-45a3-abb8-ebb4c0f4754c.png">

How to configure powerlevel10k either to hide folder 'feature' (super) either to leave 15 characters more (ok)?

**Comment by romkatv** [comment]
For branch shortening, see this: https://github.com/romkatv/powerlevel10k/blob/cf67cad46557d57d5d2399e6d893c317126e037c/config/p10k-classic.zsh#L389-L392

Consider switching to two-line prompt to get more space.

**Comment by kaurov** [comment]
Thanks!
