### ISSUE TITLE
New in git 2.37: faster git status with fsmonitor 

### ISSUE THREAD

**Issue by aluxian** [romkatv/powerlevel10k#1923]
Have you seen this new feature in git?

https://github.blog/2022-06-29-improve-git-monorepo-performance-with-a-file-system-monitor/

Is it useful at all for optimising the git integration in powerlevel10k or does the current implementation already do the same and even more?

I haven’t checked the code of powerlevel10k but I am impressed by the benchmarking effort put in by @romkatv. That’s clever. 

This is just a suggestion, feel free to close when it has run its course.

**Comment by romkatv** [comment]
Thanks for letting me know. I don't think there is anything to do in powerlevel10k or gitstatus w.r.t. to it.
