### ISSUE TITLE
Git Foreground Colors

### ISSUE THREAD

**Issue by AndyP3r3z** [romkatv/powerlevel10k#1925]
Is there a way to change the ' on' and git symbol foreground colors?
I'm finishing up setting the git status colors. I've changed succesfully de branch text and icon, but for some reason I can't find where to change the word ' on' and the git symbol text color.
Found that the characters can be changed:

`POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION` for the git symbol, and
`POWERLEVEL9K_VCS_PREFIX` for de ' on' string.

But I don't really want to change those, I just want them to have a different foreground color. 
Here's a screenshot of how it looks right now (maybe with this you'll understand why I want them to have another color).

![image](https://user-images.githubusercontent.com/99506413/177010340-e11b92e2-2505-4f18-9329-e9f2d754f44f.png)

Thanks in advance for your help.

**Comment by romkatv** [comment]
Try this:

```zsh
typeset -g POWERLEVEL9K_VCS_PREFIX='%F{red}on%f '
```

**Comment by romkatv** [comment]
The color of the icon is controlled by `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR`.
