### ISSUE TITLE
Remove asterisk before kubecontext

### ISSUE THREAD

**Issue by danielc103** [romkatv/powerlevel10k#1931]
Can't seem figure how to remove the asterisk in the kubecontext 

```(☸️⎈ infra-dev)```

expecting 

```(☸️ infra-dev)```

```
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION=

POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='%{$fg[blue]%}$P9K_KUBECONTEXT_NAME%{$reset_color%}'

POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'

# Custom prefix.
typeset -g POWERLEVEL9K_KUBECONTEXT_PREFIX='(☸️'
typeset -g POWERLEVEL9K_KUBECONTEXT_SUFFIX=')'
```

**Comment by romkatv** [comment]
It's the icon. See https://github.com/romkatv/powerlevel10k/issues/1929#issuecomment-1176520202

**Comment by romkatv** [comment]
This is a second issue with the same terrible configuration. Where did you get it? Whoever created it doesn't understand how to configure powerlevel10k.

**Comment by danielc103** [comment]
uncommenting `POWERLEVEL9K_KUBECONTEXT_DEFAULT_VISUAL_IDENTIFIER_EXPANSION` and setting it to empty worked. thank you!

as for the configuration setting the colors, I believe this was a google search long ago. I'm using my kubecontext more often now so I wanted to move it around and clean it up.

**Comment by romkatv** [comment]
If you run `p10k configure`, you'll likely get a better config. The one you are using is a manually edited version. I don't know all the changes but the ones I noticed are clearly for the worse (hence this issue you opened).
