### ISSUE TITLE
Bug: Check icon in the right prompt has no padding when icons or texts are appended

### ISSUE THREAD

**Issue by k14lb3** [romkatv/powerlevel10k#1932]
There seems to be no padding added on the check icon when something is appended (icons, text).

![image](https://user-images.githubusercontent.com/76220140/178093309-9a0ef1d4-e968-4d21-91be-486177c89ced.png)

![image](https://user-images.githubusercontent.com/76220140/178093548-a754f465-ecf7-4153-be28-ba700c8281fb.png)

Using terminal in nvim using [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim).

![image](https://user-images.githubusercontent.com/76220140/178094133-95bd4f3e-9fbc-4e00-8c24-58fe156292f2.png)

**Comment by romkatv** [comment]
That's an issue with your font. You work around this by manually adding a space. You can do it like this:

1. Open `~/.p10k.zsh`.
2. Search for `POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION` and `POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION` and add space at the end of the value.
3. Restart zsh with `exec zsh`.

Alternatively, use [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/font.md).

**Comment by k14lb3** [comment]
Thank you. :)
