### ISSUE TITLE
How can I activate the command guesser?

### ISSUE THREAD

**Issue by RAMBOMAN03** [romkatv/powerlevel10k#1935]
Hello. I'm new in Linux. I've a Linux Parrot and I want to use P10k. It's great but p10k don't guess my code like it have to do! It's because I have commented in the .p10k.zsh. all of the "sources"? 

Thanks for all

**Comment by romkatv** [comment]
There is nothing in powerlevel10k that could be described as "command guesser". See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by RAMBOMAN03** [comment]
Well, I mean that while you are typing, in the line below you are typing, the p10k show you a command. This command, the p10k will remember and save in a history. Isn't it?

Anyway, it doesn't matter. Thanks you for all.

**Comment by romkatv** [comment]
> Well, I mean that while you are typing, in the line below you are typing, the p10k show you a command. This command, the p10k will remember and save in a history. Isn't it?

Powerlevel10k doesn't do anything like that. It's not intended to. See the link above.
