### ISSUE TITLE
How to change git prompt background and foreground color?

### ISSUE THREAD

**Issue by braindotai** [romkatv/powerlevel10k#1936]
Hi there, just installed ohmyzsh with powerline plugin, loving it so far and trying to make it more custom. I managed to change the few default colours but struggling with git promp,
Currently it looks like this
![image](https://user-images.githubusercontent.com/50226064/178188367-028e3e4f-8f67-440a-a686-d3c694ee0a2d.png)
How to change git prompt's parrot green and foreground black color?
I tried to look into docs but couldn't find. 
Thanks for your time.

**Comment by romkatv** [comment]
Background: https://github.com/romkatv/powerlevel10k/blob/be3724bc806a2dd7fbcb281a153b11ab19d8923d/config/p10k-rainbow.zsh#L347-L352

Foreground: https://github.com/romkatv/powerlevel10k/blob/be3724bc806a2dd7fbcb281a153b11ab19d8923d/config/p10k-rainbow.zsh#L379-L384

Before customizing these you might want to run `p10k configure` and try *Classic* and *Lean* styles. Both of these use different foreground colors for different parts of git status.
