### ISSUE TITLE
Python virtual environment prompt doesn't use the prompt configured on creation

### ISSUE THREAD

**Issue by Jackenmen** [romkatv/powerlevel10k#1937]
# Summary

powerlevel10k generally doesn't currently show the custom prompt configured on virtual environment creation.

# Observed behavior

virtualenv on all Python versions:
![image](https://user-images.githubusercontent.com/6032823/178191047-66ea18c6-a8d0-4969-b0d2-9c88a4fa95fc.png)

<details>
<summary>venv module on Python 3.9 and below</summary>

![image](https://user-images.githubusercontent.com/6032823/178191040-e2d2aa94-9bf2-47c5-bd8d-6375b8d3f42d.png)

</details>

# Additional information

It seems that there is partial support for this functionality - it works with the venv module on Python 3.10 and above:

<details>
<summary>venv module on Python 3.10</summary>

![image](https://user-images.githubusercontent.com/6032823/178191187-641ad462-8350-4f00-93e5-03e6b62f4b94.png)

</details>

However, it would be great if powerlevel10k supported virtualenv as well as the venv module from the versions earlier than 3.10. The information about the prompt is stored in the `pyvenv.cfg` file in the root of the virtual environment so that could be used to get the custom prompt (note that it's not filled when no custom prompt is set).

**Comment by mdragossh** [comment]
Have the same problem, p10k doesn't display if I'm using virtual environment or not. Hard to understand what I'm using and where my packages are.

**Comment by mdragossh** [comment]
My mistake, sorry, somehow similar to this.
