### ISSUE TITLE
I can't get rid of an error -> [theme 'powerlevel10k/powerlevel10k' not found] even after deleting 109 line

### ISSUE THREAD

**Issue by RamazanZholdas** [romkatv/powerlevel10k#1939]
i removed this line: 
source ~/powerlevel10k/powerlevel10k.zsh-theme
but after removing powerlevel10k stopped working

**Comment by romkatv** [comment]
You need to put that like back and delete the line with `ZSH_THEME="powerlevel10k/powerlevel10k"`.

**Comment by RamazanZholdas** [comment]
Thx

**Comment by RamazanZholdas** [comment]
j
