### ISSUE TITLE
Trying to copy configuration from another distro

### ISSUE THREAD

**Issue by thierrywalt** [romkatv/powerlevel10k#1941]
Hey there. Not sure it is the right place to ask for help but here it goes... I am trying to copy the Konsole layout from Manjaro to Kubuntu, as it comes with neat icons [here](https://ibb.co/8dYjC1h). I think it is using p10k, since I see this file on /usr/share/zsh/. I installed zsh, oh my zsh, and powerlevel10l via oh my zsh. I copied the general zsh configuration file, /usr/share/zsh/manjaro-zsh-config; the scripts and plugins folder, and the p10k.zsh file. Now it looks something like this, very similar but instead of icons it has squares [here](https://ibb.co/jwJkgXK). Where do these icons come from? I was gonna coppy the p10k.zsh file here, but it is huge.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/font.md

**Comment by thierrywalt** [comment]
> See https://github.com/romkatv/powerlevel10k/blob/master/font.md

Perfect, that did it!
