### ISSUE TITLE
[oh-my-zsh] theme 'powerlevel10k' not found

### ISSUE THREAD

**Issue by silent-night-no-trace** [romkatv/powerlevel10k#1942]
I use powerlevel10k  
Set ZSH_THEME="powerlevel10k/powerlevel10k" in ~/.zshrc.

open zsh 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/21052733/178696533-ec160ce4-5e34-488e-94e4-28fceff9bbcc.png">

**Comment by romkatv** [comment]
Follow installation instructions: https://github.com/romkatv/powerlevel10k#oh-my-zsh

**Comment by silent-night-no-trace** [comment]
I use  as follows 

1.Clone the repository:

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
Users in mainland China can use the official mirror on gitee.com for faster download.
中国大陆用户可以使用 gitee.com 上的官方镜像加速下载.

git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
2.Set ZSH_THEME="powerlevel10k/powerlevel10k" in ~/.zshrc.

**Comment by silent-night-no-trace** [comment]
Still have the above problem

**Comment by romkatv** [comment]
What's is the output of the following command?

```zsh
ls -l -- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
```

**Comment by silent-night-no-trace** [comment]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/21052733/178944995-95b68ceb-6d8d-41f1-9ea2-067f34bd1ca1.png">

**Comment by silent-night-no-trace** [comment]
now output

**Comment by romkatv** [comment]
You didn't run the command I asked. Please do and post its output here.

**Comment by silent-night-no-trace** [comment]
see image

**Comment by silent-night-no-trace** [comment]
ok, i try  install again

**Comment by silent-night-no-trace** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/21052733/178946989-95083446-43dc-4d90-8764-9f8a8e6464c6.png">

**Comment by lmwenda** [comment]
I got this issue as well and this command: 
`ls -l -- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k`
doesn't work

**Comment by romkatv** [comment]
@lmwenda Follow installation instructions: https://github.com/romkatv/powerlevel10k#installation

**Comment by lmwenda** [comment]
For me powerlevel10k is installed properly and has taken effect however but it still says its not found which is annoying.

**Comment by romkatv** [comment]
> For me powerlevel10k is installed properly

This is probably not so. Please see the installation instructions and follow them very carefully. If some steps aren't clear, ask what they mean.

**Comment by rcoundon** [comment]
I'm also seeing this, the output of running `ls -l -- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k` is:

```
❯ ls -l -- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
total 432
-rw-r--r--   1 rosscoundon  staff   1354 27 Jun 14:40 LICENSE
-rw-r--r--   1 rosscoundon  staff    354 27 Jun 14:40 Makefile
-rw-r--r--   1 rosscoundon  staff  99837  5 Sep 16:13 README.md
drwxr-xr-x   8 rosscoundon  staff    256 11 Jul 11:53 config
-rw-r--r--   1 rosscoundon  staff   8691  2 Sep 17:57 font.md
drwxr-xr-x  24 rosscoundon  staff    768 27 Jun 14:43 gitstatus
drwxr-xr-x  14 rosscoundon  staff    448 23 Sep 15:45 internal
-rw-r--r--   1 rosscoundon  staff  62099 27 Jun 14:40 powerlevel10k.png
-rw-r--r--   1 rosscoundon  staff   3913 27 Jun 14:40 powerlevel10k.zsh-theme
-r--r--r--   1 rosscoundon  staff   8552 27 Jun 14:43 powerlevel10k.zsh-theme.zwc
-rw-r--r--   1 rosscoundon  staff     97 27 Jun 14:40 powerlevel9k.zsh-theme
-r--r--r--   1 rosscoundon  staff    576 27 Jun 14:43 powerlevel9k.zsh-theme.zwc
-rw-r--r--   1 rosscoundon  staff     97 27 Jun 14:40 prompt_powerlevel10k_setup
-rw-r--r--   1 rosscoundon  staff     97 27 Jun 14:40 prompt_powerlevel9k_setup
```

Cloning the repo fails because it's already there - i.e. a non-empty directory. However, when launching a new terminal session I get the error:

```
[oh-my-zsh] theme 'powerlevel10k/powerlevel10k' not found
```

However, things do seem to be working:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/9136570/192897540-e33dd1dc-8033-4b33-a6ce-67778f45762d.png">

I'm using an M1 Macbook Pro, in case that's a factor

**Comment by romkatv** [comment]
@rcoundon Please follow the installation instructions carefully.

**Comment by rcoundon** [comment]
> @rcoundon Please follow the installation instructions carefully.

I believe I have.

**Comment by romkatv** [comment]
> > @rcoundon Please follow the installation instructions carefully.
> 
> I believe I have.

In this case please file a bug against Oh My Zsh. The error message is coming from it.

**Comment by anwarulislam** [comment]
How did I solve it?

`code .zshrc`

Find for this line: 

`source <(ng completion script)`

Comment out this line and save.

**Comment by rcoundon** [comment]
> > > @rcoundon Please follow the installation instructions carefully.
> > 
> > 
> > I believe I have.
> 
> In this case please file a bug against Oh My Zsh. The error message is coming from it.

Thought I'd report back. I've just been through the process of uninstalling Oh My Zsh and reinstalling, then reapplying Powerlevel10k and it's now working correctly.

**Comment by choilive** [comment]
FWIW-  also having this issue after installing powerlevel10k

**Comment by romkatv** [comment]
> FWIW- also having this issue after installing powerlevel10k

Use the same resolution.

**Comment by wupn1** [comment]
> My mistake was removing the last character when pasting `git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k`
> 
> So the repo was cloned to `powerlevel10` instead of `powerlevel10k`

It also help me. Thanks a lot.

**Comment by anantmi3** [comment]
SOLVED this issue without reinstalling.

Just follow the steps: -
1. copy your folder `/powerlevel10k` and paste it inside `/.oh-my-zsh/custom}/themes/`
2. restart your terminal
3. Start `zsh `again

After that it does not give the error again.

**Comment by tedtalksbits** [comment]
> What's is the output of the following command?
> 
> ```shell
> ls -l -- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
> ```

SOLVED apparently I didn't clone the repo (though I thought I did) Thanks a bunch

**Comment by uncleSlayer** [comment]
> SOLVED this issue without reinstalling.
> 
> Just follow the steps: -
> 
> 1. copy your folder `/powerlevel10k` and paste it inside `/.oh-my-zsh/themes/`
> 2. restart your terminal
> 3. Start `zsh `again
> 
> After that it does not give the error again.

thanks this worked for me too.

**Comment by turkalpmd** [comment]
> git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

Perfect solution, it is work on my local

**Comment by jdkruzr** [comment]
I think it's probably worth noting that I have also encountered this problem -- I was using p10k for literally three years with no issues, and then as of last week I started getting this error message. It's literally not there anymore. Something deleted p10k from my Mac and I have no idea what.

**Comment by romkatv** [comment]
> Something deleted p10k from my Mac and I have no idea what.

I can assure you that p10k didn't delete itself.

**Comment by jdkruzr** [comment]
I don't imagine it did! I do wonder if something related to the OS upgrade I did last week did something to break my home directory or somehow otherwise cleared out the contents of something related to zsh.

**Comment by fabriciomasiero** [comment]
> Closing because the communication isn't working. You'll have to ask for help elsewhere.

Why????


Why can't you just be polite and kind? This is not the kind of help we need. If you're going to do this, please don't help, so you only push away those who need help. Be nice not an asshole

**Comment by romkatv** [comment]
@fabriciomasiero Please refrain from discussing anything other than powerlevel10k on this forum.

**Comment by tristan-pv01** [comment]
I'm having the same issue; could this be due to installing with Homebrew? The repo cloned during installation but wasn't in the themes directory; [turkalpmd](https://github.com/turkalpmd)'s solution fixed this but perhaps the Mac installation documentation needs updating.

**Comment by romkatv** [comment]
The docs list several installation options. You need to pick one. Do not run one command from one installation option (say, oh my zsh) and another command from a different option (say, homebrew). Pick one method and stick with it. If the instructions of a chosen option contain several steps, perform all of them.

**Comment by tristan-pv01** [comment]
For your reference, I followed both Homebrew installation steps, then the oh my zsh instructions when those didn't work on their own.

**Comment by romkatv** [comment]
> [turkalpmd](https://github.com/turkalpmd)'s solution fixed this

That solution is literally copy-pasted from the installation instructions.

https://github.com/romkatv/powerlevel10k#oh-my-zsh

**Comment by CasperCheuk** [comment]
i just copy packages to oh-my-zsh dir ;problem solved. 
like this :
cp -rf /home/casper/powerlevel10k /home/casper/.oh-my-zsh/custom/themes/

**Comment by zenaku07** [comment]
Clone Powerlevel10k into your Oh My Zsh custom themes directory:
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
 Set the theme name correctly in your `~/.zshrc`:
```ZSH_THEME="powerlevel10k/powerlevel10k"```

Save the `~/.zshrc` file and restart your terminal or run `source ~/.zshrc`.

Now, verify that the theme is in the right directory:

ls -l $ZSH_CUSTOM/themes/powerlevel10k

You should see the `powerlevel10k.zsh-theme` file listed in the output.

With the correct installation and theme path set in your `~/.zshrc`, the warning message should disappear, and Powerlevel10k should be loaded successfully as your Zsh theme.

**Comment by tonykuttai** [comment]
> Follow the installation instructions: https://github.com/romkatv/powerlevel10k#oh-my-zsh. Specifically, make sure to perform this step:
> 
> 1. Clone the repository:
>    ```shell
>    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Users in China can use the official mirror on gitee.com for faster download.
>    中国用户可以使用 gitee.com 上的官方镜像加速下载.
>    ```shell
>    git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
>    ```
> 
> Once done, restart zsh with `exec zsh`.

This worked for me. 
Thanks

**Comment by jerky33** [comment]
FYI, I accidentally ran the manual install when I should have run the command for the Oh-my-zsh script and I ended up with extra lines at the end of my ~/.zshrc file. Once I removed the incorrect theme folder in ~/powerlevel10k/ and the unneeded lines from the bottom of ~/.zshrc file and ran the correct command everything worked as expected.
I hope this helps someone that may have mad the same mistake I did.
Regards

**Comment by OvidiuMihalcea** [comment]
I already had a functional installation of the PowerLevel10k, but I had that error. For me the issue was that the ZSH_CUSTOM vas set to a value other than $HOME. I've commented that line, and I've sourced the .zshrc file with source ~/.zshrc

**Comment by romkatv** [comment]
@aronreisx Your config is probably loading powerlevel10k twice, and potentially from two different places. You can verify this by removing the line that sets `ZSH_THEME` and restarting zsh with `exec zsh`. If you still see powerlevel10k after doing this, your config was indeed loading powerlevel10k twice. With `ZSH_THEME`, it is now being loaded only once. It's a very good idea to load powerlevel10k just once from a single place.

**Comment by malahmen** [comment]
> Clone Powerlevel10k into your Oh My Zsh custom themes directory:
> 
> ```shell
> git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
> ```
> 
> Set the theme name correctly in your `~/.zshrc`:
> 
> ```shell
> ZSH_THEME="powerlevel10k/powerlevel10k"
> ```
> 
> Save the `~/.zshrc` file and restart your terminal or run `source ~/.zshrc`.
> 
> Now, verify that the theme is in the right directory:
> 
> ```shell
> ls -l $ZSH_CUSTOM/themes/powerlevel10k
> ```
> 
> You should see the `powerlevel10k.zsh-theme` file listed in the output.
> 
> With the correct installation and theme path set in your `~/.zshrc`, the warning message should disappear, and Powerlevel10k should be loaded successfully as your Zsh theme.

I've followed the install instructions just once.
repository was properly cloned and in place.
the theme was applied and showing as configured.
but I had the stupid message every time.
somehow my .zshrc file had `ZSH_THEME="powerlevel10k"`  and not `ZSH_THEME="powerlevel10k/powerlevel10k"`.

didn't figured out how that happened.

**Comment by jzadra** [comment]
This is happening to me as well.

**Comment by ZewenKong** [comment]
> SOLVED this issue without reinstalling.
> 
> Just follow the steps: -
> 
> 1. copy your folder `/powerlevel10k` and paste it inside `/.oh-my-zsh/themes/`
> 2. restart your terminal
> 3. Start `zsh `again
> 
> After that it does not give the error again.

Thank you :)

**Comment by tuybenites** [comment]
> SOLVED this issue without reinstalling.
> 
> Just follow the steps: -
> 
> 1. copy your folder `/powerlevel10k` and paste it inside `/.oh-my-zsh/themes/`
> 2. restart your terminal
> 3. Start `zsh `again
> 
> After that it does not give the error again.

Thanks, that worked for me! :)
I'm using Git Bash in Windows.
