### ISSUE TITLE
os_icon not working as expected

### ISSUE THREAD

**Issue by Amit0617** [romkatv/powerlevel10k#1943]
I found os icon on someone else's terminal. I felt the need for it. 
I am tired of saying I use arch btw with my terminal screenshots. I want my terminal to say this itself. 

Looked into `~/.p10k.zsh` (I have set up it through zsh4humans,  if that affects). Found `os_icon` and uncommented it, but results aren't really beautiful.
![Screenshot_20220714_154035](https://user-images.githubusercontent.com/71893015/178959058-eedad7fe-0bbb-4ea7-bf2d-eba5020ad019.png)
As you can see my terminal supports the required unicode/glyph/ascii (whatever it is) after installing some nerd font packages. However, I know there is custom icon option which can be used to get it as i want but i thought if there is something to correct.

**Comment by romkatv** [comment]
Run `p10k configure`. Also consider using the font powerlevel10k recommends -- it'll give you larger icons.

**Comment by Amit0617** [comment]
> Run `p10k configure`. 
Yeah, that's how I had set up it.

> Also consider using the font powerlevel10k recommends -- it'll give you larger icons.
Thanks now I can get the larger icon. But it doesn't give yet the arch icon in the terminal. Should I do it through custom icon?

**Comment by romkatv** [comment]
> > Run `p10k configure`.
> 
> Yeah, that's how I had set up it.

Run it again and choose prompt with icons. When you ran it before installing the font with glyphs, you didn't have this option.

**Comment by Amit0617** [comment]
Installed the following font (telling just to make sure that's what was expected)
`yay ttf-meslo-nerd-font-powerlevel10k`
tried `p10k configure`, but I still didn't get the os-icon customisation option. One more thing is - that the lock is not showing up in terminal when configuring it, even after installing the required font. (however, the arch icon renders in the terminal as you can see it in the screenshot)

**Comment by Amit0617** [comment]
thanks! I have been compromising on terminal for many options for a long time just because I hadn't fonts set up right! This link should be recommended at the time when the user says "no" for identifying lock icons.
