### ISSUE TITLE
There is no choice for prompt style in `p10k configure`

### ISSUE THREAD

**Issue by YangEfei** [romkatv/powerlevel10k#1946]
Hi there.
I'm using `p10k configure` to set my p10k style.
But there's no choice for prompt style in it.

I thought it maybe because of the previous choices I made which are not suitable for rainbow style, and I have tried different combinations. But all of them can not find prompt style options.

And I tried to replace my `~/.p10k.zsh` with [p10k-rainbow.zsh](https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-rainbow.zsh), it works well.

So how can I get the prompt style options in `p10k configure`?
Thanks a lot!

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by YangEfei** [comment]
Thanks for your reply! @romkatv 
I append this command into .zshrc and it works correctly.
`export TERM=xterm-256color`
