### ISSUE TITLE
Additional space

### ISSUE THREAD

**Issue by KaspianDev** [romkatv/powerlevel10k#1947]
Hey, i noticed empty space character at end of the line, can I fix it somehow? (i tried few terminals and it's the same)
![OnPaste 20220715-144708](https://user-images.githubusercontent.com/34658474/179225902-6d26e3e6-4128-40cb-90e6-736a1375e502.png)

**Comment by romkatv** [comment]
Add this to .zshrc:

    ZLE_RPROMPT_INDENT=0

**Comment by KaspianDev** [comment]
Thank you!
