### ISSUE TITLE
Feature request: show that previous command ended with a partial line (didn't end with eol/newline)

### ISSUE THREAD

**Issue by Kache** [romkatv/powerlevel10k#1948]
By default, `zsh` will add an `%` to partial lines (See `PROMPT_SP` under https://zsh.sourceforge.io/Doc/Release/Options.html#Prompting):
<img width="213" alt="image" src="https://user-images.githubusercontent.com/133218/179299240-c7778d61-6789-46ba-89cf-8a590a3af043.png">

I've been trying to improve the behavior via different `PROMPT_EOL_MARK` settings:

```
PROMPT_EOL_MARK=''
PROMPT_EOL_MARK='%F{red}␤%f'
PROMPT_EOL_MARK='%F{red}🅽%f'
PROMPT_EOL_MARK='%U%F{red}⮒%f%u'
PROMPT_EOL_MARK='%K{red} '
```

Which look like:

<img width="422" alt="image" src="https://user-images.githubusercontent.com/133218/179302085-c72225c2-53f1-46a0-b493-68e308632fa9.png">

But I realize what I'd really like is to use `PROMPT_EOL_MARK=''` as to not "munge" the output and instead have powerlevel10k notify me on the next prompt somehow, perhaps by turning the OS icon (apple) red? Or using one of the above symbols? etc

**Comment by romkatv** [comment]
That's not possible.

**Comment by romkatv** [comment]
To clarify, this is technically impossible because zsh doesn't know whether the previous command's output has an unterminated line or not.
