### ISSUE TITLE
Prefetching (loading) gitstatusd

### ISSUE THREAD

**Issue by Enquestor** [romkatv/powerlevel10k#1949]
I've created a container that has p10k preinstalled with zsh + oh-my-zsh. 

However, whenever I start the container with:
```
docker run -it name/ubuntu /bin/zsh
```

I'll have to wait for p10k to load gitstatusd:
```
[powerlevel10k] fetching gitstatusd .. [ok]
```

Is there any way that I could prefetch or start gitstatusd in advance to avoid waiting every time?

**Comment by romkatv** [comment]
It's downloading `~/.cache/gitstatus/gitstatusd-linux-x86_64`. If you copy this file into the container, it won't have to be downloaded.

**Comment by Enquestor** [comment]
Thanks for the heads up!
