### ISSUE TITLE
Show the context prompt on Fedora Toolbox

### ISSUE THREAD

**Issue by alosarjos** [romkatv/powerlevel10k#195]
Hi!
I see from https://github.com/romkatv/powerlevel10k/issues/170 that the context is only shown when being privileged user or when I'm in a SSH session. Fedora provides a tool called Toolbox that is like running a container in the computer and SSHing into it. Can this be added to show the context when using toolbox?

I attatch a capture of how to enter the toolbox and how the context change.

I've commented the line  
`typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION= 
`
to show this

![Captura de pantalla de 2019-09-01 10-01-20](https://user-images.githubusercontent.com/29999427/64073518-7b2e2980-cc9f-11e9-9499-15480155032e.png)

**Comment by romkatv** [comment]
To display context when in a toolbox container:

```zsh
if ! [[ -f /run/.containerenv && -f /run/.toolboxenv ]]; then
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
fi
```

You can also display diamond when in a toolbox container, similar to the default bash prompt.

```zsh
if [[ -f /run/.containerenv && -f /run/.toolboxenv ]]; then
  # Display diamond when in a toolbox: ⬢ user@host.
  typeset -g POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION='⬢'
else
  # When not in a toolbox, don't show context unless running with privileges or in SSH.
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
fi
```

I'm not sure that my check for running within a toolbox container is correct. I was greeted with a chain of cryptic errors when attempting to run toolbox in docker (I don't use Fedora myself and I didn't feel like spinning up a VM). Please let me know if the suggested config works for you.

**Comment by alosarjos** [comment]
Oh, wow! Thanks a lot for the fast response!
Yes, your solution is working perfectly. I just removed showing the username inside the context since it's the same as the host machine username. So I ended up with this:


```shell
if [[ -f /run/.containerenv && -f /run/.toolboxenv ]]; then
  # Display diamond when in a toolbox: ⬢ user@host.
    typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%180F%m'
    typeset -g POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION='⬢'
  else
  # When not in a toolbox, don't show context unless running with privileges or in SSH.
    typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
  fi
```

Thanks a lot!

**Comment by romkatv** [comment]
:+1:

**Comment by BrunoVernay** [comment]
Just to be sure, you put these lines in .p10k.zsh near line 860, right.   It doesn't seem to work ...

**Comment by BrunoVernay** [comment]
I tried to add these lines in .p10k.zsh around line 850, but it does not work ... even if I type them, without the tests, on the command line, it does not work...
Any idea what it could be?

**Comment by romkatv** [comment]
@BrunoVernay Try copy-pasting this whole command.

```zsh
() {
emulate -L zsh -o err_return
mv ~/.p10k.zsh ~/.p10k.zsh.bak
>~/.p10k.zsh <<\END
if [[ -f /run/.containerenv && -f /run/.toolboxenv ]]; then
  # Display diamond when in a toolbox: ⬢ user@host.
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%180F%m'
  typeset -g POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION='⬢'
else
  # When not in a toolbox, don't show context unless running with privileges or in SSH.
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
fi
END
exec zsh
}
```

Does it make `context` behave as you like? If so, figure out how to incorporate these changes to your own config. You are the only one who knows what it contains and what's around line 850.

**Comment by BrunoVernay** [comment]
(I meant line 860 in .p10k.zsh)
I tried your commands and even just using a `.p10k.zsh` with
```
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%180F%m'
typeset -g POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION='⬢'
```
I end up with  | current directory > ........   < # command < hh:mm:ss

Actually I can even change POWERLEVEL9K_CONTEXT_TEMPLATE to whatever, it has no effect. (I source the file, restart ...)


I don't even know how to debug this stuff, I guess I should ask zsh or oh-my-zsh ?  Is there a way to trace the execution?

**Comment by BrunoVernay** [comment]
My issue had nothing to do with toolbox, but was related to #640 .
It would be nice to integrate toobox (podman whatever) in powerlevel10k. I guess if you do not have Fedora that might be difficult
