### ISSUE TITLE
How to get all the features of P10k on all users? Just showing in default user

### ISSUE THREAD

**Issue by UnknownMasterCoder** [romkatv/powerlevel10k#1953]
Hi there Roman.

I have a doubt and I've couldn't find some sort of solution to my problem in the web. The problem is that I have my zsh personalized as normal with p10k and I have a context segment into my shell, but when I turned to root, the shell stays as ubuntu default. I dont know what is causing this problem, if you could give me a hand I will appreciate it.

I attach s screenshot of my problem, the expected is keep all the segments as they are, just change the name of context for obviously "root@...." but keep all same, the colors, the segments, etc.
I dont know why in root all the segments just dissapear, and I have removed the line `POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=` which is supposed to enable all the context. But I think the problem is deeper than that.

Thanks and greetings from Colombia

![image](https://user-images.githubusercontent.com/42448705/179873997-c9c380c4-a36f-4435-b2c7-8ef9b6432951.png)

**Comment by romkatv** [comment]
One option is to use `sudo -E zsh` instead of `su root`. Another option is to install powerlevel10k as root and copy `~/.p10k.zsh` to root.

**Comment by UnknownMasterCoder** [comment]
I've already used `sudo -E zsh` and it worked, but what does that command do? Does that config stays if I restart my sytem?

And how can I install p10k as root?

Thanks a lot

**Comment by romkatv** [comment]
> I've already used `sudo -E zsh` and it worked, but what does that command do?

`-E` preserves the environment, the most relevant for us here being `HOME`. Check `man sudo` for details.

> Does that config stays if I restart my sytem?

I'm not sure I understand what you are asking. `sudo -E zsh` does what it does regardless of how many times you restart your system.

> And how can I install p10k as root?

The same way as you did it for non-root.

**Comment by UnknownMasterCoder** [comment]
> I'm not sure I understand what you are asking. sudo -E zsh does what it does regardless of how many times you restart your system.

Yeah I was talking about that. thanks

Roman, i think i just screwed it up. 

Now when I go root with `sudo -E zsh` I get the next message:
![image](https://user-images.githubusercontent.com/42448705/180132613-69f22923-096f-49a2-ac2f-8d74b384764f.png)
![image](https://user-images.githubusercontent.com/42448705/180132669-2ea03272-3396-4add-a9db-ad2cc0b3f513.png)

I was just trying to install oh-my-zsh as root, all I do was:
1. Login as root
2. change default shell with `chsh`
3. install oh-my-zsh with: `su
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`
4. Then I restart the shell and go root with your command.

Help me please.. how do I uninstall oh-my-zsh from root (even if I dont see it installed it)
Greetings

**Comment by romkatv** [comment]
The message you are seeing has two parts:

```text
PART 1

--- console output produced during zsh initialization follows ---

PART 2
```

*PART 1* comes from powerlevel10k and it says that *PART 2* is not empty. If you make *PART 2* disappear, *PART 1* will disappear on its own. *PART 1* is not coming from oh-my-zsh. Read what it says and do what it suggests. If you cannot, open an issue against oh-my-zsh.

**Comment by UnknownMasterCoder** [comment]
Hi there Roman, you were right I solved that issue by giving root permissions to the oh-my-zsh files mentioned in the error. But I give up trying to get p10k on root (native) because all these errors I get was while trying to install oh-my-zsh and p10k as root as you told me before. So I use the `sudo -E zsh` to get the p10k settings in root. But I have now a few questions.

1. I've connected to a SSH machine, but I can't get the p10k personalization, it shows like if it wasnt installed, how can I solve this to show my p10k theme in any SSH machine?
![image](https://user-images.githubusercontent.com/42448705/182691275-098089b1-0e07-4cfc-852c-23f5d1b136ae.png)

2. I was looking that you develop a segment to show wifi speed, but this only works on Mac. So I tried to make my own wifi segment with `speedtest` because in other thread some guy says it could be with `nmcli` but I wasnt able to install it in my WSL. So I created that segment, but I have a big problem and I don't know if you could help me on this. The issue is that speed test takes almost 25 secs to get the speed rate, so every time I enter a void command in zsh, it loads the wifi segment, so it gets working 25 seconds while getting the wifi rate. It works well, but every time I exec a command it brings the 25 sec wait to get the wifi speed. If you see there, every time I enter a new linea it keeps getting the wifi information (the 25 secs)
![image](https://user-images.githubusercontent.com/42448705/182724798-b4d7f7b2-6bc4-46f2-8f18-4264f338730d.png)

3. Working with my vcs I have a question, at the moment I do a commit, it state returns to clean... is there an option to change the color of the segment, when i got something after a commit? just previous a push? But without changing the clean state of the repo when I have no changes to do. If know what I mean just when I do a commit and the arrows appear, I dont want the color to be "clear" but another different color
![image](https://user-images.githubusercontent.com/42448705/182727921-27ad5cdc-aa9a-4ae4-8cb5-3e4cc16193c8.png)

Thanks a lot!

**Comment by romkatv** [comment]
The discussion has moved to https://github.com/romkatv/powerlevel10k/issues/1973.

**Comment by Loco00003** [comment]
Hello, I just installed powerlvl10k, nad my problem happens to be the opposite of this one, I installed powerklvl10k as root, but I normal user still has the default prompt, do you know what can I do to fix this?

![imagen_2024-01-11_192637272](https://github.com/romkatv/powerlevel10k/assets/125228777/65e47e88-b5f9-4084-ab9d-715a0cea6c43)

**Comment by romkatv** [comment]
If you want to have powerelevel10k when logged in as a certain user, you need to install powerlevel10k under that user.

**Comment by Loco00003** [comment]
> If you want to have powerelevel10k when logged in as a certain user, you need to install powerlevel10k under that user.

Thanks,it's working now  , thanks for your reply.
