### ISSUE TITLE
I don't install miniforge but there is a base?

### ISSUE THREAD

**Issue by Seannnnnnnion** [romkatv/powerlevel10k#1954]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/44387683/179999043-26b7824f-0df4-47f5-8c94-4a542f2462d8.png">

**Comment by romkatv** [comment]
Is something on this screenshot incorrect/unexpected in your opinion? If so, what is it?

**Comment by Seannnnnnnion** [comment]
> Is something on this screenshot incorrect/unexpected in your opinion? If so, what is it?

I find the reason ,because I use app cleanner delete some config🥲

**Comment by romkatv** [comment]
I'm glad you've resolved this issue.
