### ISSUE TITLE
graph configuration

### ISSUE THREAD

**Issue by darkfallen777** [romkatv/powerlevel10k#1955]
![image](https://user-images.githubusercontent.com/60336109/180168159-eb220674-d329-48ed-bf05-f3a3483c020f.png)
I'm so sorry.
But how to configure these graphics, I do not have a configuration file p10
![image](https://user-images.githubusercontent.com/60336109/180168281-baea9e5f-7264-4873-ad78-aa5e020656ca.png)
![image](https://user-images.githubusercontent.com/60336109/180168313-ac72d6d0-93f6-4e82-aabc-ebe2a160f26c.png)

**Comment by romkatv** [comment]
I don't understand what you are asking. Please rephrase/clarify.

**Comment by darkfallen777** [comment]
Sorry. 
I cloned your repository and installed the powerlevel theme
It came up with this.![image](https://user-images.githubusercontent.com/60336109/180173941-4cefcf7e-eb47-49cf-8bf3-8c22ee745dc3.png)
I opened your instructions and found that you have to run p10k configure. But I don't have that file![image](https://user-images.githubusercontent.com/60336109/180174410-23493179-dd16-4fba-988c-98599395468e.png)
How to set up this visualization from the screenshot
![image](https://user-images.githubusercontent.com/60336109/180174538-990c2aa0-9846-485c-a0d7-abaa151a16d6.png)

**Comment by romkatv** [comment]
> Sorry. I cloned your repository and installed the powerlevel theme It came up with this.![image](https://user-images.githubusercontent.com/60336109/180173941-4cefcf7e-eb47-49cf-8bf3-8c22ee745dc3.png)

What happens if at this point you run `p10k configure`?

**Comment by darkfallen777** [comment]
This is unbelievable, I ran it twice and there was an error.
![image](https://user-images.githubusercontent.com/60336109/180187526-d76eb266-f8b7-4667-9afb-43424c417fac.png)
Can you tell me how to add promt and expand its functionality?

**Comment by darkfallen777** [comment]
![image](https://user-images.githubusercontent.com/60336109/180188641-fd26a712-a768-48f3-be44-89ba8d3377f4.png)
How to fix this output

**Comment by romkatv** [comment]
> This is unbelievable, I ran it twice and there was an error.

What was the error? Can you post a screenshot that shows you running `p10k configure` and getting an error?

> Can you tell me how to add promt and expand its functionality?

See docs: https://github.com/romkatv/powerlevel10k. If you ask a more specific question, I might be able to give a more specific answer.

> ![image](https://user-images.githubusercontent.com/60336109/180188641-fd26a712-a768-48f3-be44-89ba8d3377f4.png) How to fix this output

Do you mean the output of `ll`? This is outside of scope of powerlevel10k. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by darkfallen777** [comment]
how to get rid of these hieroglyphs?
![image](https://user-images.githubusercontent.com/60336109/180216691-bf5947b9-6796-42bd-a238-8cfb3c9bceed.png)
![image](https://user-images.githubusercontent.com/60336109/180216820-7c42a34e-78bb-4bfc-9a58-58fd19ffd3b1.png)
