### ISSUE TITLE
Node version not being displayed

### ISSUE THREAD

**Issue by brunocasarotti** [romkatv/powerlevel10k#1956]
Hi folks, when I run the command `nvm use node` I was expecting to see the node version on my terminal but I don´t see anything. Am i missing something? My `.p10k.zsh` is untouched.

![image](https://user-images.githubusercontent.com/20110633/180260968-24de3260-e98f-41b3-8739-9b58e84ab7ab.png)

**Comment by romkatv** [comment]
> Hi folks, when I run the command `nvm use node` I was expecting to see the node version on my terminal

Powerlevel10k doesn't do that. `nvm` segment shows the project's node version if it's not the same as the default. There is also `package` segment (disabled by default) that shows stuff from `package.json`. There is nothing in powerlevel10k that is affected by `nvm use`.
