### ISSUE TITLE
`no such file or directory: p10k.zsh` after installation with Antigen

### ISSUE THREAD

**Issue by oliversalzburg** [romkatv/powerlevel10k#1957]
I've installed powerlevel10k through Antigen, more precisely <https://github.com/gantsign/ansible_role_antigen>. When I open a terminal now, I get the error:

```shell
(anon):source:27: no such file or directory: /home/oliver/.antigen/bin/internal/p10k.zsh
```

I'm not sure which piece in the puzzle is causing this to fail. So I'm starting here :)

I just found #1629, which this might be a duplicate of.

**Comment by oliversalzburg** [comment]
It seems like the message originates from https://github.com/romkatv/powerlevel10k/blob/master/powerlevel10k.zsh-theme#L77 I'm not sure yet why `$__p9k_root_dir` would be incorrectly set in my environment.

**Comment by romkatv** [comment]
> I just found #1629, which this might be a duplicate of.

It's a dup, yes. You can ask for help from ansible_role_antigen or from antigen. If something indicates an issue with powerlevel10k, open a new issue please with more details and a precise description how this can be reproduced.
