### ISSUE TITLE
[powerlevel10k] fetching gitstatusd .. / [ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by MuhammadrizoDeveloper** [romkatv/powerlevel10k#1958]
full Error message:

[powerlevel10k] fetching gitstatusd .. /
[ERROR]: gitstatus failed to initialize.

  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh

**Comment by MuhammadrizoDeveloper** [comment]
full Error message:

[powerlevel10k] fetching gitstatusd .. /
[ERROR]: gitstatus failed to initialize.


  Add the following parameter to ~/.zshrc for extra diagnostics on error:

    GITSTATUS_LOG_LEVEL=DEBUG

  Restart Zsh to retry gitstatus initialization:

    exec zsh

**Comment by MuhammadrizoDeveloper** [comment]
.

**Comment by romkatv** [comment]
Please do what the error message says.

**Comment by ndhungw** [comment]
on Mac mini M1
```
[powerlevel10k] fetching gitstatusd .. /                                        
[ERROR]: gitstatus failed to initialize.

Failed to download gitstatusd-darwin-arm64 from any mirror:

  1. https://github.com/romkatv/gitstatus/releases/download/v1.5.4/gitstatusd-darwin-arm64.tar.gz
  2. https://gitee.com/romkatv/gitstatus/raw/release-v1.5.4/release/gitstatusd-darwin-arm64.tar.gz

Check your internet connection, then restart your shell.
```

**Comment by ndhungw** [comment]
just figure out:
.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install

make this change in the fetch function:

```
        for cmd in 'curl -kfsSL' 'wget -qO-' 'curl -q -kfsSL' 'wget --no-config -qO-'; do
```

to 
```
        for cmd in 'curl --proxy <your-proxy-domain> -kfsSL' 'wget -qO-' 'curl -q -kfsSL' 'wget --no-config -qO-'; do
```

**Comment by romkatv** [comment]
Modifying the source code isn't a great idea. Instead, add this to `~/.zshrc`:

```zsh
export HTTPS_PROXY=<your-proxy>
```

Or this:

```zsh
export ALL_PROXY=<your-proxy>
```

See `man curl`.

**Comment by Light-coder777** [comment]
> ```shell
> export ALL_PROXY=<your-proxy>
> ```

I have tried it still it's showing the same error

**Comment by romkatv** [comment]
> > ```shell
> > export ALL_PROXY=<your-proxy>
> > ```
> 
> I have tried it still it's showing the same error

If `curl` doesn't respect an environment variable that `man curl` promises to respect, file a bug against `curl`. My guess is that `curl` is fine though and the issue is on your side.

**Comment by ju4niko** [comment]
> ```shell
> ```shell
> export ALL_PROXY=<your-proxy>
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> I have tried it still it's showing the same error
> ```

I have the same issue in my rig (macbook air M2)

**Comment by romkatv** [comment]
The same resolution then.

**Comment by ju4niko** [comment]
not in my very case I'm affraid, the culprit was the fact that I'd migrated from an intel mac to a M2 one, migration scripts didn't update most of curl and friends tools, after updating with mac ports it started to work.

Anyway, thank you very much for taking the time in answering and for the awesome p10k!

cheers!

Saludos cordiales.

Juan A. Montenegro
***@***.***

**Comment by romkatv** [comment]
Thanks for the update! Hopefully it'll help someone with a similar problem.
