### ISSUE TITLE
Any way to increase space between the two lines in two line prompt ?

### ISSUE THREAD

**Issue by drjkpalli** [romkatv/powerlevel10k#1959]
<img width="932" alt="Screen Shot 2022-07-23 at 5 12 04 PM" src="https://user-images.githubusercontent.com/67685865/180603544-49eb2360-d271-46ec-93fe-c8be398fcd6a.png">
 
Hi guys, is there a setting to increase this spacing ?
Using Powerlevel 10k with oh-my-zsh

zsh is my default shell (on my Mac OS Monterey terminal.)

**Comment by romkatv** [comment]
You can insert an extra empty line in there. Search for `newline` in `~/.p10k.zsh` and add one extra after it. You can also configure your terminal to have more space between lines in general.

**Comment by drjkpalli** [comment]
Hi Roman,
thanks for the help.

adding an entire line would waste too much space and increasing space between lines is making the rainbow weird like this.

<img width="941" alt="Screen Shot 2022-07-25 at 10 59 00 PM" src="https://user-images.githubusercontent.com/67685865/180839150-a111fe48-ccd6-49c6-bd43-c6e98d6dec43.png">

**Comment by romkatv** [comment]
There are no other options.

**Comment by drjkpalli** [comment]
I understand. Thank you for your help anyways.
