### ISSUE TITLE
Getting "no matches found: options[-1]" error when running the configuration wizard

### ISSUE THREAD

**Issue by palicand** [romkatv/powerlevel10k#196]
OS: Ubuntu 18.04.3
ZSH version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
ZSH plugins are managed by [zplug](https://github.com/zplug/zplug)
The font I am using in the terminal is `Iosevka SS09 Term`.

Hello. I am running into trouble configuring the theme. After confirming that I can see the Python logo properly, the configuration crashes with `Choice [ynrq]: y(anon):1153: no matches found: options[-1]`. 

The exact configuration path I take is
1) diamond - yes
2) lock - yes
3) Debian logo - no
4) Python logo - yes
5) crash

If, for example, I answer no twice to the lock question, the configuration skips to the style question and everything proceeds correctly. If you need any more information, I'll gladly provide it.

**Comment by romkatv** [comment]
Sorry about that. Please update powerlevel10k and try again.

**Comment by palicand** [comment]
Probably the fastest bugfix I've seen on github! Everything works, thanks!

**Comment by romkatv** [comment]
Thanks for the confirmation!
