### ISSUE TITLE
Round style misalignment

### ISSUE THREAD

**Issue by YTGhost** [romkatv/powerlevel10k#1961]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/40822107/180901199-d946eac3-b072-4719-a9b1-38c7411e5045.png">
hi guys, the round style now appears unaligned.

Using M1 pro macbook, with oh-my-zsh and iterm2

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by YTGhost** [comment]
> See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

After I set the font size of iTerm2 to 13, it looks perfect. Thanks, it is a pretty good zsh theme.

**Comment by romkatv** [comment]
> After I set the font size of iTerm2 to 13, it looks perfect.

👍 

> Thanks, it is a pretty good zsh theme.

Thank you.
