### ISSUE TITLE
pyenv plugin disappeared after changing global version

### ISSUE THREAD

**Issue by saveriogzz** [romkatv/powerlevel10k#1962]
hello!
I ran the command `pyenv global x.y.z` to change the version of pyenv, and now the plugin has disappeared. I tried also setting a local version of pyenv with `pyenv local x.y.z` but it's not working.
Would you possibly know what I'm doing wrong?
Thanks!

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and find this block: https://github.com/romkatv/powerlevel10k/blob/e72264e01cb24431455ed6e398a769bca0da7ffe/config/p10k-lean.zsh#L915-L917

Read the comment and change the value if you like.

**Comment by saveriogzz** [comment]
Brilliant! Thanks @romkatv :)
