### ISSUE TITLE
Consider moving default installation path somewhere else so the home directory stays clean

### ISSUE THREAD

**Issue by CodingSpiderFox** [romkatv/powerlevel10k#1963]
The more utilities are installed on the system, the bigger the home directory tends to become.

The README.md states for manual installation

```
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
```

Wouldn't it be possible to do the initial clone to the ~/.config/ directory (or another common directory)?

e.g.

```
mkdir -p ~/.config
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/powerlevel10k
echo 'source ~/.config/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
```

**Comment by romkatv** [comment]
You can install it in another directory if you want.

**Comment by CodingSpiderFox** [comment]
That's good :)
I only thought that it would be nicer to have the default install instructions in the README.md suggesting it that way ;)

**Comment by CodingSpiderFox** [comment]
What I mean is that I find it better when configuration files are all placed inside the .config folder in the home directory so the home directory itself stays as clean as possible

**Comment by romkatv** [comment]
Cool 👍
