### ISSUE TITLE
Unable to see unicode characters

### ISSUE THREAD

**Issue by Devarth123** [romkatv/powerlevel10k#1964]
![1659340750](https://user-images.githubusercontent.com/95016816/182016003-6bfaed71-1726-4930-970c-5f25d0f5c2d5.png)

**Comment by romkatv** [comment]
Your font is missing some glyphs. In particular, it's missing https://graphemica.com/%E2%9D%AF. You can either switch to a different font (for example, [this one](https://github.com/romkatv/powerlevel10k/blob/master/font.md)) or use a prompt style for which your font has all gyphs (one sure way is to choose Lean and then ASCII on the next screen).

**Comment by Devarth123** [comment]
Thanks that worked!
