### ISSUE TITLE
Is it possible to show the command in a new line automatically when the window is narrow?

### ISSUE THREAD

**Issue by liqiao-ponyai** [romkatv/powerlevel10k#1967]
Like this:
When there is a lot of space:
![2022-08-01 16-33-24 的屏幕截图](https://user-images.githubusercontent.com/86951976/182107888-b644596d-d69b-4002-932c-d605a4891b2d.png)

When there isn’t much space:
![2022-08-01 16-33-42 的屏幕截图](https://user-images.githubusercontent.com/86951976/182107883-c04af56e-f696-4923-9c94-9e97f855c8cc.png)

**Comment by romkatv** [comment]
You can try to do do something like this via `p10k display`, see `p10k help display`. However, I wouldn't recommend it. My advice is to stick with two-line prompt and enable transient prompt. Also switch to Lean style to save space. See https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard.
