### ISSUE TITLE
Weird symbol left of prompt

### ISSUE THREAD

**Issue by aagrawal05** [romkatv/powerlevel10k#1968]
Hi, I'm on macOS, just completed the configuration wizard, but i'm getting this weird fragment on the beginning of every line as well as this weird space at the end of the line
<img width="1440" alt="Screenshot 2022-08-01 at 10 03 48 PM" src="https://user-images.githubusercontent.com/58559719/182165768-c3644513-a437-49d3-b996-a804a18795d9.png">

Here is my .zshrc and .p10k.zsh if necessary (changed file to .txt for github).
[p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/9234559/p10k.zsh.txt)
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/9234560/zshrc.txt)

**Comment by romkatv** [comment]
https://stackoverflow.com/a/38913948/1095235
