### ISSUE TITLE
Change directory hint color

### ISSUE THREAD

**Issue by capdavid** [romkatv/powerlevel10k#1971]
Hi, I couldn't find anywhere how to change this color and background. When you are in a directory after typing `cd` and pressing `TAB`, directory hint shows up. How to change these colors (both background and foreground)?

![image](https://user-images.githubusercontent.com/11329983/182635808-a514181e-7e88-4c62-977c-d4b3ded4bc4c.png)

what is also weird in some places they look like this and in other places they look like this: 

![image](https://user-images.githubusercontent.com/11329983/182635940-d6e7fb32-502d-45fa-9c6b-c9493def5e51.png)

I'd appreciate some help with this 🙏 As you can see the first example is not readable. 

I would also like to mention I want to change the colors in powerlevel config, not in iTerm color palette.

**Comment by romkatv** [comment]
Powerlevel10k doesn't affect these colors any way. It only provides prompt. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by capdavid** [comment]
Ok thank you very much, I found a setting for .zshrc
```_ls_colors=":ow=01;31" 
zstyle ':completion:*:default' list-colors "${(s.:.)_ls_colors}"
LS_COLORS+=$_ls_colors
```
