### ISSUE TITLE
Theme powerlevel10k/powerlevel10k not found

### ISSUE THREAD

**Issue by darymhurst** [romkatv/powerlevel10k#1972]
Getting the error `theme 'powerlevel10k/powerlevel10k' not found` after following all the install steps.

I'm also curious to know how the setting `ZSH_THEME="powerlevel10k/powerlevel10k"` actually works when the theme name is usually a single word and refers to a file under `$ZSH/themes`. In my themes folder I see all the default oh-my-zsh themes but nothing relating to powerlevel10k.

**Comment by AghaAmil** [comment]
I have been facing with the same issue on my M1 Mac, I appreciate if you assist us in this regards.
I am using iTerm2 as well as my default terminal.

**Comment by romkatv** [comment]
> Getting the error `theme 'powerlevel10k/powerlevel10k' not found` after following all the install steps.

What's the output of the following command?

```zsh
ls -l --- ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
```

If it's an error, you need to follow the installation instructions pricisely.

> I'm also curious to know how the setting `ZSH_THEME="powerlevel10k/powerlevel10k"` actually works

You can see it in the source of Oh My Zsh.

**Comment by romkatv** [comment]
> I have been facing with the same issue on my M1 Mac

Please follow the installation instructions very carefully.

**Comment by AghaAmil** [comment]
Dear Romkatv,
As I checked again, My installation procedure was not correct based on the instructions, you have provided. I uninstalled oh-my-zsh and re-installed everything again based on the instructions and now everything works fine.

Thanks for the support and the amazing thing that you have done.

**Comment by romkatv** [comment]
Thanks for the update. I'm glad the issues has been sorted out.
