### ISSUE TITLE
p10k theme not working with SSH machine and other questions

### ISSUE THREAD

**Issue by UnknownMasterCoder** [romkatv/powerlevel10k#1973]
Hi there Roman, you were right I solved that issue by giving root permissions to the oh-my-zsh files mentioned in the error. But I give up trying to get p10k on root (native) because all these errors I get was while trying to install oh-my-zsh and p10k as root as you told me before. So I use the `sudo -E zsh` to get the p10k settings in root. But I have now a few questions.

1. I've connected to a SSH machine, but I can't get the p10k personalization, it shows like if it wasnt installed, how can I solve this to show my p10k theme in any SSH machine?
![image](https://user-images.githubusercontent.com/42448705/182691275-098089b1-0e07-4cfc-852c-23f5d1b136ae.png)

2. I was looking that you develop a segment to show wifi speed, but this only works on Mac. So I tried to make my own wifi segment with `speedtest` because in other thread some guy says it could be with `nmcli` but I wasnt able to install it in my WSL. So I created that segment, but I have a big problem and I don't know if you could help me on this. The issue is that speed test takes almost 25 secs to get the speed rate, so every time I enter a void command in zsh, it loads the wifi segment, so it gets working 25 seconds while getting the wifi rate. It works well, but every time I exec a command it brings the 25 sec wait to get the wifi speed. If you see there, every time I enter a new linea it keeps getting the wifi information (the 25 secs)
![image](https://user-images.githubusercontent.com/42448705/182724798-b4d7f7b2-6bc4-46f2-8f18-4264f338730d.png)

3. Working with my vcs I have a question, at the moment I do a commit, it state returns to clean... is there an option to change the color of the segment, when i got something after a commit? just previous a push? But without changing the clean state of the repo when I have no changes to do. If know what I mean just when I do a commit and the arrows appear, I dont want the color to be "clear" but another different color
![image](https://user-images.githubusercontent.com/42448705/182727921-27ad5cdc-aa9a-4ae4-8cb5-3e4cc16193c8.png)

Thanks a lot!

**Comment by romkatv** [comment]
> 1. I've connected to a SSH machine, but I can't get the p10k personalization, it shows like if it wasnt installed, how can I solve this to show my p10k theme in any SSH machine?

You need to install powerlevel10k on every machine where you want to have powerlevel10k.

With https://github.com/romkatv/zsh4humans this can be automated (when you SSH to a machine, powerlevel10k can be installed automatically) but I don't recommend that you use.

> 2. I was looking that you develop a segment to show wifi speed, but this only works on Mac. So I tried to make my own wifi segment with `speedtest` because in other thread some guy says it could be with `nmcli` but I wasnt able to install it in my WSL. So I created that segment, but I have a big problem and I don't know if you could help me on this. The issue is that speed test takes almost 25 secs to get the speed rate, so every time I enter a void command in zsh, it loads the wifi segment, so it gets working 25 seconds while getting the wifi rate. It works well, but every time I exec a command it brings the 25 sec wait to get the wifi speed. If you see there, every time I enter a new linea it keeps getting the wifi information (the 25 secs)

Writing fast code is often more difficult than writing slow code. This is one of those cases. Unfortunately there is no simple trick you can use to turn slow code into fast one.

> 3. Working with my vcs I have a question, at the moment I do a commit, it state returns to clean... is there an option to change the color of the segment, when i got something after a commit? just previous a push? But without changing the clean state of the repo when I have no changes to do. If know what I mean just when I do a commit and the arrows appear, I dont want the color to be "clear" but another different color

See https://github.com/romkatv/powerlevel10k#how-do-i-change-the-format-of-git-status.
