### ISSUE TITLE
Won't work with Warp

### ISSUE THREAD

**Issue by rhnkyr** [romkatv/powerlevel10k#1974]
Hi,

thanks for this beauty. Unfortunately it won't work with https://www.warp.dev/ 

Any workaround or suggestion to make it work?

**Comment by romkatv** [comment]
I'm not aware of any workarounds.

**Comment by greatnessinabox** [comment]
@rhnkyr they have added support for this now. I was able to get this working by going to Settings > Features > Honor user's custom prompt (PS1) setting

**Comment by krlozadan** [comment]
Update: they changed it and now you can find it under Settings > Appearance > Prompt
