### ISSUE TITLE
Question on one of the elements in the right prompt

### ISSUE THREAD

**Issue by hanj0415** [romkatv/powerlevel10k#1975]
Sorry for the dumb question. What is the representation of the middle section of the right prompt with the red highlight (system ⌂).
![2022-08-05_15-54-16](https://user-images.githubusercontent.com/59560208/183023272-8d24e1bc-b373-4d99-89bb-1221a1a4178d.jpg)

I have several macs however only one of mac has those in the prompt and never goes away, so wondering why.
And I couldn't get any clue from the descriptions of the batteries.

**Comment by romkatv** [comment]
This must be one of the `node` segments: https://github.com/romkatv/powerlevel10k/blob/f9fd384d8d64022e24c83bb03ba69e415c7fa90e/config/p10k-rainbow.zsh#L51-L53

You must have an override for `node` and this segment shows it. You can either remove the override (how you can do that depends on what kind of node version manager you are using) or simply remove the segment from `p10k.zsh`. The former is, of course, a better solution.

**Comment by hanj0415** [comment]
Thank you very much for the quick answer!
