### ISSUE TITLE
Avast File Shield Alert

### ISSUE THREAD

**Issue by RonanJackson** [romkatv/powerlevel10k#1976]
My zgenom was updating today and Avast blocked the powerlevel10k file path: .zgenom/romkatv/powerlevel10k/__/gitstatic/build

Process: /usr/local/Cellar/zsh/5.9/bin/zsh

Threat name: BV:Downloader-APK [Drp]

Can someone clarify what could be causing this?

Is this an actual threat?

**Comment by romkatv** [comment]
Assuming that `.zgenom/romkatv/powerlevel10k/__/gitstatic/build` is the same as https://github.com/romkatv/powerlevel10k/blob/master/gitstatus/build, this alert is a false positive. In other words, this file is not a *threat*. Consider reporting this issue to Avast.
