### ISSUE TITLE
How to change OS icon or add emoji befor prompt path

### ISSUE THREAD

**Issue by lokize** [romkatv/powerlevel10k#1981]
Hi, how to change the icon of os system or add emoji before path in powerlevel10k?

![image](https://user-images.githubusercontent.com/19701630/184456532-faaee48c-a5b2-4a63-b36d-bfa548d59ee6.png)

I using wsl2 with centOS 9 Stream

**Comment by romkatv** [comment]
1. Install a font that has icons and configure your terminal to use it. For example, [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/font.md).
2. Run `p10k configure`.
3. Select prompt style with icons.

**Comment by lokize** [comment]
thank you very much for help, I don't know why but even before choosing the icons were not appearing but today after restarting the computer and trying again it worked, could you tell me in which line of the configuration I change the operating system icon?

![image](https://user-images.githubusercontent.com/19701630/184498118-511cffd5-3477-41a8-999a-03ca71456fb9.png)

**Comment by romkatv** [comment]
Your prompt shows the logo of your OS on the left. You mentioned earlier that you are using centOS and the logon on your screenshot is indeed of centOS. The logo is correct. If you want to replace it with a different logo, open `~/.p10k.zsh`, search for `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`, uncomment it and set the value to what you like.

**Comment by lokize** [comment]
Thank you, perfect its worked!
