### ISSUE TITLE
The powerlevel10k will open multiple background zsh

### ISSUE THREAD

**Issue by luyuduan** [romkatv/powerlevel10k#1982]
Hello, I have a question about the theme plugin to open multiple background zsh, after entering zsh to open zsh, multiple zsh processes appear in the background, after deleting powerlevel10k, only one zsh process will be opened in the background
Environment: WSL2, 5.10.102.1-microsoft-standard-WSL2
powerlevel10k is installed by default

![image](https://user-images.githubusercontent.com/37297576/184466197-a2b37ae1-8fe2-4d81-bb3b-3a97305500ae.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#why-does-powerlevel10k-spawn-extra-processes
