### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Dan-Essin** [romkatv/powerlevel10k#1983]
I would like to completely eliminate the elements that display on the right-hand side of the screen.
I have studied the source and I can see reference to right_side but cannot figure out where those get incorporated into the output or the PROMPT definition

It's probably a simple thing. Help would be appreciated

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` and remove all elements from it.
