### ISSUE TITLE
Passwords showing during SSH sessions.

### ISSUE THREAD

**Issue by shad0wcrawl3r** [romkatv/powerlevel10k#1984]
I have been using this theme for awhile now. And recently installed the theme on my remote machine (office). 
While typing passwords with "sudo", I can see the last few letters I typed on my screen.
I can only replicate this issue on VS code right now. But trying the same with bash seems to work fine.   
Cant get this issue to replicate while Trying with other themes (agnoster, fishy and cypher) as well. 

![image](https://user-images.githubusercontent.com/46002059/184522082-724d3f41-b8ef-4178-9fd2-002f579d8e73.png)

**Comment by romkatv** [comment]
Fascinating. If you ever figure out how powerlevel10k can affect something when it's not running (e.g., when you are entering your password), please post an update. I'm going to close this issue because I don't intend to do anything here.

**Comment by romkatv** [comment]
By the way, this is almost certainly a bug in the terminal.
