### ISSUE TITLE
Weird symbol and number beside `master`  

### ISSUE THREAD

**Issue by cjj1120** [romkatv/powerlevel10k#1985]
<img width="645" alt="image" src="https://user-images.githubusercontent.com/50688209/184531046-3fcd6824-b2cb-43b1-9a18-fcb07bb1f16f.png">

I can't seem to get rid of these weird random (* 1 ?), have tried to set the font to recommended `MesloLGS NF`, didn't work either. Also tried Nerd font, the python symbol can be rendered correctly, now sure how to get rid of those weird symbols.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by cjj1120** [comment]
my bad, thanks for the prompt reply
