### ISSUE TITLE
Delay after command execution is completed

### ISSUE THREAD

**Issue by hungdh0x5e** [romkatv/powerlevel10k#1987]
Hi,
Sometimes I get a delay prompt after command execution is completed. How can I debug this problem or fix it?

Thanks

**Demo**: press `enter` at 00:02, but have to wait until 00:07 to continue.

https://user-images.githubusercontent.com/11895605/184794103-a5f019e8-51ac-4343-8c53-345f5b04fec3.mov

**Comment by romkatv** [comment]
The first step to debug this would be to figure out what is causing the delay. Start with an empty `.zshrc`. If there is no delay, add powerlevel10k to it. If there is no delay, it's not powerlevel10k. If there is delay, post all your startup files and all files that they source.
