### ISSUE TITLE
Icon `\ufcd2` is aligned to the right

### ISSUE THREAD

**Issue by babaolanqiu** [romkatv/powerlevel10k#1988]
I'm using termux and installed the patched font as default. When I use [lsd](https://github.com/Peltoche/lsd), the `.R` files are aligned to the right. 
![Screenshot_20220818-105005_Termux](https://user-images.githubusercontent.com/32609824/185284556-ba7c0479-4201-415d-8619-a82ec0d79c97.jpg)
It seems to be a problem of icon `\ufcd2`. Is this supposed to be a right-aligned icon? How to fix it? Thanks.

**Comment by romkatv** [comment]
U+FCD2 is [ARABIC LIGATURE NOON WITH JEEM INITIAL FORM](https://www.fileformat.info/info/unicode/char/fcd2/index.htm). It's Right-to-Left Arabic. I've never seen a terminal that aligns characters of this type to the right but apparently Termux does.

I don't think it's a good idea for `lsd` to use this character. There is a proper Rust logo in Nerd Fonts under U+E7A8.

In any case, this is not related to powerlevel10k. It's an issue between `lsd` and Termux. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by babaolanqiu** [comment]
Duly noted. Thanks for advice!
