### ISSUE TITLE
# Enable Powerlevel10k instant prompt. Should stay close to the top of \n~

### ISSUE THREAD

**Issue by Osamah-learn** [romkatv/powerlevel10k#1989]
### Any help ? : 

<img width="1242" alt="Screenshot 2022-08-18 at 13 13 38" src="https://user-images.githubusercontent.com/77615959/185371247-d2b08c6c-512b-4ea7-af64-3d3630b5ed79.png">

**Comment by romkatv** [comment]
Your `.zshrc` is broken. You need to open it with a text editor and fix it. If you cannot, delete it and start over.

Note that this error is not specific to powerlevel10k. If you delete or disable powerlevel10k, you'll still get this error.

**Comment by Osamah-learn** [comment]
I fixed it by removing zshrc and installing it again, and then I went to System Preferences > Users and Groups > Right click on the user > Advance options > Then change the home directory like the screen below :
<img width="617" alt="Screenshot 2022-08-18 at 17 01 25" src="https://user-images.githubusercontent.com/77615959/185414939-16f682b0-8081-47b5-a667-383ceefa6dd8.png">
