### ISSUE TITLE
Truncating node version

### ISSUE THREAD

**Issue by Jimmy-JS** [romkatv/powerlevel10k#1990]
Hi, Just wondering is there any possibility to truncate the node version shown in the terminal?

![image](https://user-images.githubusercontent.com/9798426/185600742-f9032665-6aa2-4a72-810e-3ff4f146795f.png)
For example here is showing ` 16.11.1`. while I want to make it compact by just showing ` 16` (only the v16) without the minor and patch version.

How can I do that? because in .p10k.zsh, I only see that it's possible to truncate only the git branch name.

Thank you!

**Comment by romkatv** [comment]
What prompt segment is displaying `16.11.1` on your screenshot?

**Comment by Jimmy-JS** [comment]
@romkatv It's node_version segment. it shows the node version on terminal

**Comment by romkatv** [comment]
Thanks. I asked because there are several segments that can show node version and they all use the same icon.

Try this:

```zsh
# Remove everything after the first dot from the content of node_version.
POWERLEVEL9K_NODE_VERSION_CONTENT_EXPANSION='${P9K_CONTENT##.*}'
```

**Comment by Jimmy-JS** [comment]
Thanks for the quick response @romkatv 
However I tried to add those in `.p10k.zsh`
![image](https://user-images.githubusercontent.com/9798426/185609897-c2a3d3d4-e44d-482c-8fe7-43f520b0637e.png)

But still showing full node version (including minor and patch):
![image](https://user-images.githubusercontent.com/9798426/185609968-35060a44-ca35-4b72-bc65-afa7b4189d82.png)

Here is my left segments config:
![image](https://user-images.githubusercontent.com/9798426/185610103-e2ae611b-dad8-4c2c-a661-04dbd4c2db1f.png)

Thank you!

**Comment by romkatv** [comment]
Sorry, there was a typo in my comment. Should be this:

```zsh
# Remove everything after the first dot from the content of node_version.
POWERLEVEL9K_NODE_VERSION_CONTENT_EXPANSION='${P9K_CONTENT%%.*}'
```

Also, you don't need to set this parameter twice. Just once is enough. Use `typeset -g` for consistency with other parameters.

**Comment by Jimmy-JS** [comment]
Yes, that works perfectly!
I just found the solution and want to post it here but you already give the correct one already.

Thank you for your help! @romkatv
