### ISSUE TITLE
AVAST Antivirus flags build file as malware/virus

### ISSUE THREAD

**Issue by wombat-hue** [romkatv/powerlevel10k#1991]
When I followed the installation instructions and cloned the repository, I got the following error from Avast Antivirus on MacOS 12 Monterey that a harmful file was detected and moved to quarantine:

Threat name: BV:Downloader-APK [Dr-build  
Infected file: build
Location: ~/.oh-my-zsh/custom/themes/power10k/gitstatus

I ran Virustotal  on the URL: https://github.com/romkatv/powerlevel10k/blob/master/gitstatus/build, but it passed.  Any reason that Avast is flagging this file as harmful?

**Comment by romkatv** [comment]
I don't know why Avast does what it does. You could ask Avast devs.
