### ISSUE TITLE
Prompt rendering incorrectly when new tab is opened

### ISSUE THREAD

**Issue by Jont828** [romkatv/powerlevel10k#1992]
I'm using this on WSL in the Windows terminal and I'm having an issue where the prompt renders with gaps when I first open a new tab. However, the prompt renders correctly every time after that. What's also strange is that this issue only repros around 75% of the time I open a new tab, and resizing the windows seems to fix the issue. Is this a bug with Windows or my GPU driver? Any suggestions about how to fix this would be greatly appreciated!

![image](https://user-images.githubusercontent.com/17480384/186105367-84cbc426-a991-45ea-975c-2b657668185d.png)

**Comment by romkatv** [comment]
Thanks for reporting this. I filed a bug against Microsoft Terminal: https://github.com/microsoft/terminal/issues/13825.

As a workaround consider running `p10k configure` and choosing Lean style. It has many advantages in addition to being resilient to numerous terminal bugs.
