### ISSUE TITLE
Gitstatus failed to initialize on WSL ubuntu 22.04 LTS Oh My Zsh

### ISSUE THREAD

**Issue by John-Ingram** [romkatv/powerlevel10k#1993]
I have installed p10k according to the appropriate instructions in the readme for oh my zsh.
This is a new wsl install, but not the first time I've installed p10k on oh my zsh on wsl. I have tried downloading gitstsatus manually using the approach described [here](https://github.com/romkatv/powerlevel10k/issues/706#issuecomment-627274660), but I get the following error when running the install:

```
❯ ~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f                                                      
/usr/bin/gzip: 1: ELF: not found                                                                                
/usr/bin/gzip: 3: : not found                                                                                     
/usr/bin/gzip: 4: Syntax error: "(" unexpected                                                                       
tar: Child returned status 2                                                                                         
tar: Error is not recoverable: exiting now
```

When I execute zsh I get this error:
https://gist.github.com/John-Ingram/77cef3359e82549cfcdf72bde15aab32

**Comment by romkatv** [comment]
It's a bug in your OS. See https://github.com/microsoft/WSL/issues/8219#issuecomment-1110508016.
