### ISSUE TITLE
VCS prompt segment won't show anything if local branch is behind or ahead of remote repository

### ISSUE THREAD

**Issue by mario-amazing** [romkatv/powerlevel10k#1995]
I can't see VCS segment on different from the master branch.
I have almost default p10k configure
Steps to reproduce: 
1. touch blah
2. git add blah
3. git commit -m "blah"

Actual result -> no VCS (ahead/behind) information:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/9537753/186787109-58ef1bbd-7ae4-4cbf-a0bd-83c9eb544877.png">

Expected result -> same as on the master `↑1`:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/9537753/186787867-e4c0771a-b805-4f31-97a9-50240c5cebb9.png">

**Comment by romkatv** [comment]
What is the output of `git status` in both cases?

**Comment by mario-amazing** [comment]
First case: 
```
On branch add_vim_plugins
nothing to commit, working tree clean
```
Second:
```
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

**Comment by romkatv** [comment]
In the second case (master) `git status` is telling you that your local branch is ahead of the remote by 1 commit. Powerlevel10k shows the same info in prompt.

In the first case (add_vim_plugins) `git status` doesn't say anything about the remote because this branch has none. It's neither ahead nor behind because there is nothing to compare it with.

**Comment by mario-amazing** [comment]
So maybe you know the reason, why it could be? 
Because this branch has the remote version and looks the same as the master.

**Comment by romkatv** [comment]
The reason is that this branch has no remote.

**Comment by mario-amazing** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/9537753/187027531-4edcddb9-a002-444a-8ce4-ba60c34ad16f.png">
Got it, I need to run `git branch -u origin/add_vim_plugins` to fix it.
Thanks!
