### ISSUE TITLE
Question: What does ${(%):-%n} do?

### ISSUE THREAD

**Issue by txhx38** [romkatv/powerlevel10k#1996]
The instant prompt is started this line:
```bash
source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
```
How does the `${(%):-%n}` part work?
It somehow expands to my username but how?
I can't find nothing about it on the internet. (Just found [this](https://stackoverflow.com/questions/69034753/what-n-means) but it doesn't explain everything.)

**Comment by romkatv** [comment]
The link to stackoverflow has the answer.

**Comment by txhx38** [comment]
Where comes the username from?

**Comment by romkatv** [comment]
I don't think I can explain it in more detail than the accepted answer on stackoverflow. In any case, this isn't the right place to ask general questions about zsh.
