### ISSUE TITLE
Gitstatus failed to initialize on WSL ubuntu 22.04 LTS Oh My Zsh permission denied

### ISSUE THREAD

**Issue by yejunyu** [romkatv/powerlevel10k#1997]
+_gitstatus_install_main:431> tar -C /tmp/gitstatus-install.NJmQ7Ml9qm -xzf /tmp/gitstatus-install.NJmQ7Ml9qm/2.tar.gz
@@@@����: Permission denied
    /usr/bin/gzip: 3: : not found
    /usr/bin/gzip: 4: Syntax error: "(" unexpected
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now
    +_gitstatus_install_main:431> exit
    +_gitstatus_install_main:447> local ret=2
    +_gitstatus_install_main:448> rm -rf -- /tmp/gitstatus-install.NJmQ7Ml9qm
    +_gitstatus_install_main:449> [ 2 '=' 0 ']'

**Comment by romkatv** [comment]
It's a bug in your OS. See https://github.com/microsoft/WSL/issues/8219#issuecomment-1110508016.

**Comment by yejunyu** [comment]
ok，thank you
