### ISSUE TITLE
Tags and revisions

### ISSUE THREAD

**Issue by aagon** [romkatv/powerlevel10k#20]
Hello 

First of all thank you for the time you spent on this project. Optimisation is frequently dismissed as unimportant or at least not worth one's time, so it is good to see someone do this important but thankless job. The improvements are impressive, and will make installing this fancy prompts on weaker machines thinkable.

You mentioned the fact that tags and revisions aren't shown in the prompt. I don't yet know what revisions are, but tags got pretty important to me after I began browsing the linux kernel repo. You said that an issue was to be raised if we wanted the feature, which is what I am doing right now.

To the extent that your time permits it, if it's not too bad for performance, I'd like you to add the tag/revision feature (and I think I do not speak for myself alone), please.

Thank you very much in advance,

rico

**Comment by romkatv** [comment]
Done.
