### ISSUE TITLE
[EROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by GrozmanGit** [romkatv/powerlevel10k#2001]
[https://paste.ofcode.org/DLjUYBTz3HB4D4s7nCHh9m](url)

Already updated powerlevel10k;

**Commands ran (after update):** 

     Command 1: 
     curl -fsSLo /home/cnife/.cache/gitstatus/gitstatusd-linux-x86_64.tmp.5140.tar.gz -- 
     https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-linux-x86_64.tar.gz

**Error:** 
curl: (23) Failure writing output to destination
     
     Command 2: ~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f
**Error:** 
/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by romkatv** [comment]
It's a bug in your OS. See https://github.com/microsoft/WSL/issues/8219#issuecomment-1110508016.

**Comment by GrozmanGit** [comment]
Issue has been resolved.
