### ISSUE TITLE
Instant prompt causes ZSH to crash on macOS with tmux

### ISSUE THREAD

**Issue by jaseemabid** [romkatv/powerlevel10k#2003]
On macOS, Terminal.app + tmux crashes 9/10 times if this feature is enabled. 

```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

My .zshrc contains a `exec tmux attach` at the end of it if that makes a difference.

```
$ uname -a 

Darwin 0x14.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 x86_64

$ tmux -V
tmux 3.3a
``` 

p10k version https://github.com/romkatv/powerlevel10k/commit/3bfbb8294fd61d3fb9f75f944b178eb9c8c2c0f7

Related to https://github.com/romkatv/powerlevel10k/issues/617#issuecomment-1233530214

**Comment by romkatv** [comment]
Please open a bug against the program that crashes.
