### ISSUE TITLE
Feature request: Can support custom format for `proxy` segment ?

### ISSUE THREAD

**Issue by Yarnus** [romkatv/powerlevel10k#2004]
Hi there,

In short, is there any way to hide the green highlight areas ?

<img width="912" alt="image" src="https://user-images.githubusercontent.com/18589312/188406851-e81e2c26-cfd7-440c-b3f0-8dbd0fa09f00.png">

**Comment by romkatv** [comment]
If you want to keep the icon but get rid of IP:port, open `~/.p10k.zsh` and add the following line to it:

```zsh
typeset -g POWERLEVEL9K_PROXY_CONTENT_EXPANSION=
```

The best place to add it would be next to `POWERLEVEL9K_PROXY_VISUAL_IDENTIFIER_EXPANSION`.

**Comment by Yarnus** [comment]
Thanks ~ it works.
