### ISSUE TITLE
kubecontext prompt segment is not updating when k8s context changes

### ISSUE THREAD

**Issue by robertocamp** [romkatv/powerlevel10k#2007]
I have the kubecontext prompt segment enabled. However, the content of the prompt segment is not changing when I change contexts in Kubernetes (`kubectl config use-context xyz`).

The prompt segment only updates the kubernetes cluster name if I source the ~/.zshrc file.

Is this feature not meant to be dynamic and update when 'kubectl config use-context` is updated?

macOS: 12.5.1
zsh: 5.8.1
kubectl:  1.2.2

**Comment by romkatv** [comment]
> Is this feature not meant to be dynamic and update when 'kubectl config use-context` is updated?

Yes.

If it's not updating, something must be wrong. What's the output of the following command?

```zsh
ls -l -- ${(s.:.)${KUBECONFIG:-$HOME/.kube/config}}
```

**Comment by robertocamp** [comment]
Thanks for the response and command. It seems to be working now and the instant prompt changes when I change contexts.  Everthing seemed to click after a Macbook restart.
