### ISSUE TITLE
TRANSIENT_PROMPT breaks after sourcing ./zshrc

### ISSUE THREAD

**Issue by jmac05r1** [romkatv/powerlevel10k#2008]
On a new open terminal (transient_prompt) works as intended "set to always".   Once you source /.zshrc it acts as if its set to never? 
<img width="1428" alt="Screen Shot 2022-09-06 at 11 44 41 PM" src="https://user-images.githubusercontent.com/2049166/188790822-72ad9320-d92e-4eef-b547-78b221f4d229.png">

I have to completely quit out of terminal and open once again for it to work properly.

Any ideas?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#weird-things-happen-after-typing-source-zshrc

**Comment by jmac05r1** [comment]
Thank you!
