### ISSUE TITLE
Strange error messages when using theme

### ISSUE THREAD

**Issue by ENate** [romkatv/powerlevel10k#2009]
build_right_prompt:12: command not found: prompt_direnv
build_right_prompt:12: command not found: prompt_asdf
build_right_prompt:12: command not found: prompt_goenv
build_right_prompt:12: command not found: prompt_nodenv
build_right_prompt:12: command not found: prompt_fvm
build_right_prompt:12: command not found: prompt_luaenv
build_right_prompt:12: command not found: prompt_jenv
build_right_prompt:12: command not found: prompt_plenv
build_right_prompt:12: command not found: prompt_perlbrew
build_right_prompt:12: command not found: prompt_phpenv
build_right_prompt:12: command not found: prompt_scalaenv
build_right_prompt:12: command not found: prompt_haskell_stack
error: error executing jsonpath "{.contexts[?(@.name==\"\")].context.namespace}": Error executing template: <nil> is not array or slice and cannot be filtered. Printing more information for debugging the template:
        template was:
                {.contexts[?(@.name=="")].context.namespace}
        object given to jsonpath engine was:
                map[string]interface {}{"apiVersion":"v1", "clusters":interface {}(nil), "contexts":interface {}(nil), "current-context":"", "kind":"Config", "preferences":map[string]interface {}{}, "users":interface {}(nil)}

build_right_prompt:12: command not found: prompt_terraform
build_right_prompt:12: command not found: prompt_azure
build_right_prompt:12: command not found: prompt_gcloud
build_right_prompt:12: command not found: prompt_google_app_cred
build_right_prompt:12: command not found: prompt_toolbox
build_right_prompt:12: command not found: prompt_nordvpn
build_right_prompt:12: command not found: prompt_ranger
build_right_prompt:12: command not found: prompt_nnn
build_right_prompt:12: command not found: prompt_xplr
build_right_prompt:12: command not found: prompt_vim_shell
build_right_prompt:12: command not found: prompt_midnight_commander
build_right_prompt:12: command not found: prompt_nix_shell
build_right_prompt:12: command not found: prompt_timewarrior
build_right_prompt:12: command not found: prompt_taskwarrior

**Comment by romkatv** [comment]
This isn't coming from powerlevel10k.

**Comment by ENate** [comment]
@romkatv Usually this comes up whenever I try to use zsh - with powerlevel10k being the randomly chosen theme.

**Comment by romkatv** [comment]
Something produces these errors but it's not powerlevel10k.

**Comment by ENate** [comment]
I will check again because I had a link at the cmd prompt showing up with these errors earlier. Thanks
