### ISSUE TITLE
Asking to configure Powerlevel10k even if I already have defined before

### ISSUE THREAD

**Issue by gandarez** [romkatv/powerlevel10k#201]
After updated iTerm2 and restarted the machine every single terminal that I open  asks me to configure again. I set the variable `POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true` and then it's loading the default settings.

<img width="578" alt="Screen Shot 2019-09-05 at 12 09 32" src="https://user-images.githubusercontent.com/782854/64354771-7090ce80-cfd6-11e9-89e6-bb815147997d.png">
<img width="482" alt="Screen Shot 2019-09-05 at 12 12 44" src="https://user-images.githubusercontent.com/782854/64354801-7be3fa00-cfd6-11e9-8076-9e3c0353b681.png">

**Comment by romkatv** [comment]
Please post your `~/.zshrc`.

**Comment by gandarez** [comment]
[p10k.log](https://github.com/romkatv/powerlevel10k/files/3580060/p10k.log)

**Comment by romkatv** [comment]
> [p10k.log](https://github.com/romkatv/powerlevel10k/files/3580060/p10k.log)

This doesn't look like `~/.zshrc`.

**Comment by gandarez** [comment]
try this zip file
[powerlevel10k.zip](https://github.com/romkatv/powerlevel10k/files/3580099/powerlevel10k.zip)

**Comment by romkatv** [comment]
`~/.p10k.zsh` is missing a closing curly bracket on line 725. Once I add it, everything works. Does this also fix the issue for you?

I see that this you've manually edited this file. Did you remove that curly bracket?

P.S.

Please don't use functions that start with `_p9k` or `__p9k`. They are internal and can be changed without notice. You can replace this line in your `~/.zshrc`:

```zsh
_p9k_prompt_segment "$0" "white" "blue" "" 0 '' "${artist//\%/%%} - ${track//%\%%}"
```

With this:

```zsh
p10k segment -b white -f blue -t "${artist//\%/%%} - ${track//%\%%}"
```

Run `p10k help segment` for documentation.

**Comment by gandarez** [comment]
Thanks for the tip about using `p10k`. That worked.

**Comment by gandarez** [comment]
`p10k segment -b white -f blue -r 'TIME_ICON' -t "${v//\%/%%}"`

When I set the icon with argument `-r` seems to not working because when I open a new terminal it shows the help and my function cant print anything,

**Comment by romkatv** [comment]
`-r` doesn't take an argument. What you want is `-i TIME_ICON -r`.

**Comment by gandarez** [comment]
Tks

**Comment by unclemez7** [comment]
Hello !
i know this have been closed but i'm facing this issue now and can't fix it with all provided above.
Attached you will find my .zshrc and my .pk10.zsh

Thanks !


[config_files.tar.gz](https://github.com/romkatv/powerlevel10k/files/3665755/config_files.tar.gz)

**Comment by gauravprwl14** [comment]
facing the same issue. please help

**Comment by romkatv** [comment]
@gauravprwl14 See https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration-wizard-runs-automatically-every-time-zsh-is-started
