### ISSUE TITLE
Why the design is not showing, instead shows some texts in command prompt

### ISSUE THREAD

**Issue by shaheem-pp** [romkatv/powerlevel10k#2010]
<img width="874" alt="Screenshot 2022-09-07 at 7 20 17 PM" src="https://user-images.githubusercontent.com/46243023/188895284-aa239e14-6b65-4c28-8ac1-a552f0e920a6.png">

**Comment by romkatv** [comment]
It's not powerlevel10k that is doing it.

**Comment by shaheem-pp** [comment]
issue fixed
