### ISSUE TITLE
Iterm and other terminals in VScode and Pycharm shows the icons except Mac Terminal

### ISSUE THREAD

**Issue by shaheem-pp** [romkatv/powerlevel10k#2011]
<img width="70" alt="Screenshot 2022-09-07 at 7 28 28 PM" src="https://user-images.githubusercontent.com/46243023/188897275-e90156f2-87e9-46cd-819e-33dccd356fe0.png">

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render
