### ISSUE TITLE
rvm prompt element is always displayed

### ISSUE THREAD

**Issue by PSalant726** [romkatv/powerlevel10k#2013]
The `rvm` prompt element is displayed in every directory. I have not modified the relevant config produced by `p10k configure`:
```sh
#######################[ rvm: ruby version from rvm (https://rvm.io) ]########################
  # Rvm color.
  typeset -g POWERLEVEL9K_RVM_FOREGROUND=168
  # Don't show @gemset at the end.
  typeset -g POWERLEVEL9K_RVM_SHOW_GEMSET=false
  # Don't show ruby- at the front.
  typeset -g POWERLEVEL9K_RVM_SHOW_PREFIX=false
  # Custom icon.
  # typeset -g POWERLEVEL9K_RVM_VISUAL_IDENTIFIER_EXPANSION='⭐'
```

Is it possible to configure this element to only display when the current directory is a ruby project? If so, how?

**Comment by romkatv** [comment]
> Is it possible to configure this element to only display when the current directory is a ruby project?

Possibly. Is there some special file at the root directory of a ruby project? Something with a special name or perhaps with a special extension?

(I don't use ruby myself, so if this question comes as naive that's because I really am when it comes to this subject.)

**Comment by PSalant726** [comment]
To start I think it would be fine to limit the display of this section directories that contain a file literally called `Gemfile` or `Rakefile`, or any `.rb` file.

**Comment by romkatv** [comment]
Try this:

```zsh
typeset -g POWERLEVEL9K_RVM_SHOW_ON_UPGLOB='Gemfile|Rakefile|*.rb'
```

This will show `rvm` segment only if there is `Gemfile`, `Rakefile` or `*.rb` in the current directory or one of its ancestor directories. This is a generic parameter that works for every segment, similar to how `POWERLEVEL9K_<segment>_FOREGROUND` works.

**Comment by romkatv** [comment]
You might also want to try [Show on command](https://github.com/romkatv/powerlevel10k#show-on-command).

**Comment by PSalant726** [comment]
Thanks! The `POWERLEVEL9K_RVM_SHOW_ON_UPGLOB` is good enough for me for now.

Separately, is there any way to enable an element to utilize "show on command" _and_ have that overridden such that the element always appears when a directory contains a certain file name/pattern?

**Comment by romkatv** [comment]
You can do that by hooking `p10k-on-pre-prompt` and `p10k-on-post-widget` and manually showing/hiding the segment with `p10k display`. It's not super difficult but there is no decent documentation for it.

**Comment by PSalant726** [comment]
Thanks for the tip. Closing this issue, as it has been resolved by config changes.
