### ISSUE TITLE
[Question][VCS] Is it possible to show commit count difference between local and multiple remote branch

### ISSUE THREAD

**Issue by XuehaiPan** [romkatv/powerlevel10k#2014]
Hi, I wonder if the VCS segment can track commit count with multiple remote repositories. It would be handy for open-source project maintainers.

For example, I have a forked repo (as `origin`) and the original repo (as `upstream`).

Can the VCS segment show the commit count difference between:

```
local branch <--> remote tracking branch on `origin`
local branch <--> same branch name on `upstream`
```

In the following example:

![image](https://user-images.githubusercontent.com/16078332/189592854-81f75e73-dfa0-46b5-bc86-d61aae59578b.png)

I want to show that the local branch has 12 commits behind the `origin` and 95 commits behind the `upstream`. With this, I can decide whether I should merge/rebase the upstream into my own fork (origin).

Thanks very much!

**Comment by romkatv** [comment]
Powerlevel10k can simultaneously show how far your branch is ahead/behind `{upstream}` and `{push}`. To take advantage of this, you first need to configure both remotes. See https://magit.vc/manual/magit/The-Two-Remotes.html. Then you'll need to use a decent p10k config. Run `p10k configure` for a good starting point.

**Comment by XuehaiPan** [comment]
Thanks for the answer. I tried to set different `{push}` and `{upstream}`, but only the ahead/behind count of `{upstream}` is shown:

My local `.git/config`:

```gitconfig
[branch "master"]
	remote = origin
	merge = refs/heads/master
	pushRemote = upstream
[remote]
	pushDefault = origin
[push]
	default = current
```

Command output from the command line (See [What do different symbols in Git status mean?](https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean)):

```console
$ git rev-list --right-only --count HEAD...@{upstream}
12
$ git rev-list --right-only --count HEAD...@{push}    
95
```

Only the number between `{upstream}` is shown:

![image](https://user-images.githubusercontent.com/16078332/189606891-a5f06e03-c8fc-4f72-b0fc-a20efbd942c6.png)

Also, only `{upstream}` can be found in source code `internal/p10k.zsh`, while `{push}` only appears in the README:

```console
$ rg '\{push\}'                                   
README.md
1122:| `⇠42`     | this many commits behind the push remote                             | `git rev-list --right-only --count HEAD...@{push}`     |
1123:| `⇢42`     | this many commits ahead of the push remote                           | `git rev-list --left-only --count HEAD...@{push}`      |

$ rg '\{upstream\}'
README.md
1118:| `master`  | remote tracking branch; only shown if different from local branch    | `git rev-parse --abbrev-ref --symbolic-full-name @{upstream}` |
1120:| `⇣42`     | this many commits behind the remote                                  | `git rev-list --right-only --count HEAD...@{upstream}` |
1121:| `⇡42`     | this many commits ahead of the remote                                | `git rev-list --left-only --count HEAD...@{upstream}`  |

internal/p10k.zsh
3609:  ahead="$(git rev-list --count "${hook_com[branch]}"@{upstream}..HEAD 2>/dev/null)"
3614:  behind="$(git rev-list --count HEAD.."${hook_com[branch]}"@{upstream} 2>/dev/null)"
3625:  remote="$(git rev-parse --verify HEAD@{upstream} --symbolic-full-name 2>/dev/null)"
```

**Comment by romkatv** [comment]
You need to do both things that I mentioned in my previous comment. See the part that starts with "Then".

**Comment by XuehaiPan** [comment]
> You need to do both things that I mentioned in my previous comment. See the part that starts with "Then".

Thanks very much! I previously use `POWERLEVEL9K_*` variables to configure my prompt. It works by replacing them with `source ~/.p10k.zsh`.
