### ISSUE TITLE
Old not like new | prompt configuration

### ISSUE THREAD

**Issue by Data-007** [romkatv/powerlevel10k#2015]
Hi
I have installed on Arch, powerlevel10k  on ZSH. I used to have a nice prompt but now something is different!!
![OldPrompt](https://user-images.githubusercontent.com/53057579/189604607-be1d25cd-a9c9-46e8-83a6-0a43868e3a2c.png)
please see old prompt above, even after running the wiz and selecting rainbow EXACTLY how I like it I don't get that at all. What I get now is shown below.
![NewPrompt](https://user-images.githubusercontent.com/53057579/189605267-e1a1f66a-f848-4044-b33f-43c54f32b541.png)

I have even gone to the bother of going to a prompt generator site and creating a ps1 file/code but where to put it?

--

Data

**Comment by romkatv** [comment]
The config for powerlevel10k is in `~/.p10k.zsh`. If you still have the old file, copy it over.

**Comment by Data-007** [comment]
Hi
No I don't have the old file, this is a fresh install of Arch/Linux, I took a picture on my phone of all the units/pkg's for Pl10k.
It was a bit squint, hence the poor snip of it, the original shot was taken over a year ago. 
Is this fixable? where does PL10K get its Prompt from?

--
Data

**Comment by Data-007** [comment]
Hi From what I can see from going through the wizard then it should be settable again, it's just setting the prompt up, as in the username @ the machine name, then the working directory......

--
Data

**Comment by Data-007** [comment]
Hi
Thanks for that comment a few comments ago, Ive gone to the file you mentioned and have managed to 
alter it but it still needs work! I know google is my friend but where to find it, and how to set up the file?
I 'll highlight the progress I've made below.
![NewOne](https://user-images.githubusercontent.com/53057579/189634581-f2eb22c4-f49d-4e21-afbc-7970ba769f5b.png)
It resembles partly the old one.

--
Data

**Comment by romkatv** [comment]
There is a bit of documentation on https://github.com/romkatv/powerlevel10k but you'll mostly need to read comments in `~/.p10k.zsh`.
