### ISSUE TITLE
[Feature Request] Custom VCS segment configuration with `POWERLEVEL9K_*` variables

### ISSUE THREAD

**Issue by XuehaiPan** [romkatv/powerlevel10k#2017]
Thanks for the great framework. It allows user defines their custom theme in a very convenient way. Originally posted in https://github.com/romkatv/powerlevel10k/pull/2016#issuecomment-1243759018, it would be very helpful to define the `vcs` segment via arrays like `POWERLEVEL9K_{LEFT,RIGHT}_PROMPT_ELEMENTS`:

https://github.com/romkatv/powerlevel10k/blob/4bbb198a606b69dfb2d86ac33686e3d41f6d0141/config/p10k-rainbow.zsh#L26-L34

So the user does not need to define a `my_git_formatter` function anymore. The `my_git_formatter` is the only function rather than a variable that I can find in the `.p10k.zsh` and the presets in `config/*.zsh`. And it takes 99 lines long. Looking forward to an alternative by defining a `vcs` segment by variables. Thanks very much!

**Comment by romkatv** [comment]
This is not something I'll be implementing or merging. Configuration parameters aren't flexible enough. If 99 lines is too long for you, write fewer lines.

**Comment by XuehaiPan** [comment]
> Configuration parameters aren't flexible enough.

This is not intended to supersede the functions but to introduce an alternative to define a `vsc` segment.

> This is not something I'll be implementing or merging.

It's fine. Sorry for bothering you. If the feature request is accepted, I can implement and document it.

**Comment by romkatv** [comment]
> This is not intended to supersede the functions but to introduce an alternative to define a `vsc` segment.

I understand that.

> > This is not something I'll be implementing or merging.
> 
> It's fine. Sorry for bothering you. If the feature request is accepted, I can implement and document it.

I don't want to have this in powerlevel10k.
