### ISSUE TITLE
Display the `battery` element only when the battery level is low

### ISSUE THREAD

**Issue by PSalant726** [romkatv/powerlevel10k#2018]
I would love to be able to add a line to `.p10k.zsh` like:
```sh
typeset -g POWERLEVEL9K_BATTERY_DISPLAY_THRESHOLD=20
```
which would result in the `battery` segment being hidden unless the current battery level is <= 20%.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/988.

**Comment by PSalant726** [comment]
Thank you!

Separately, is there complete configuration reference documentation somewhere? The `POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD` mentioned in #988 is not referenced in the `.p10k.zsh` file. This is the second time an existing option would have solved my problem, but I was not able to discover that it exists (see #2013).

**Comment by romkatv** [comment]
Nope, there is no reference, unfortunately. If it helps, here a rule of thumb: if your idea for prompt customization is sensible, powerlevel10k can do that. Look at the code to find out how or open an issue to ask a question.
