### ISSUE TITLE
default colors are different from powerlevel9k

### ISSUE THREAD

**Issue by ConorSheehan1** [romkatv/powerlevel10k#202]
Is there a way I can get the same look as pk9 using `p10k configure`?
Or do I need to edit .pk10.zsh manually? 

I love the improved performance, but I prefer the colors from the default powerlevel9k.
<img width="710" alt="Screenshot 2019-09-05 at 18 04 52" src="https://user-images.githubusercontent.com/16896053/64363104-af8b4800-d007-11e9-87d8-d8246b6e5034.png">

When I run `p10k configure` I get these two options
<img width="729" alt="Screenshot 2019-09-05 at 18 00 07" src="https://user-images.githubusercontent.com/16896053/64363114-b31ecf00-d007-11e9-977f-1e14b18ddfb7.png">

I've been using classic, since it's closer to what I want, but still not ideal.

I actually found p10k from this gist, where both have the same color scheme, but I can't seem to find the config they used https://gist.github.com/kevin-smets/8568070

**Comment by romkatv** [comment]
> default colors are different from powerlevel9k

They are the same.

> I prefer the colors from the default powerlevel9k.

Don't use the config from `p10k configure`.

```zsh
rm ~/.p10k.zsh
echo 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true' >>! ~/.zshrc
```

This will give you the default prompt identical to p9k. You can customize it just like p9k and it'll look the same as p9k.

> I actually found p10k from this gist, where both have the same color scheme, but I can't seem to find the config they used https://gist.github.com/kevin-smets/8568070

That the default prompt with no customization whatsoever. The actual colors you see depend on your Terminal's color scheme. You can adjust colors in `iTerm2 → Preferences → Profiles → Colors`.

P.S.

Lean style is better than either of these. Prompt with background colors (especially the rainbow-style) grabs more attention than any prompt deserves.

**Comment by ConorSheehan1** [comment]
That's exactly what I was looking for, thanks!
