### ISSUE TITLE
Bold fonts with directory shorten strategy set to "truncate_to_unique"

### ISSUE THREAD

**Issue by tgdfool2** [romkatv/powerlevel10k#2020]
Hi All,

I would like to set the font as **bold** for the current directory when using the `trucate_to_unique` strategy. How can I achieve this? I managed to set all the other segments as bold, but not the directory. Here is how my current setup looks like:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/66017789/190127737-4d309859-7a11-4ae0-901b-98a2da330ba7.png">

I also tried with `truncate_from_right` and also here, I am not able to get **bold** fonts.

Thanks in advance for your help!

**Comment by tgdfool2** [comment]
Looks like setting `POWERLEVEL9K_DIR_PATH_HIGHLIGHT_BOLD=true` makes the right most directory bold. But it is rather an undocumented feature; found it by chance in a forum.

Any way to get the full path highlighted in bold?

**Comment by romkatv** [comment]
> Any way to get the full path highlighted in bold?

I don't think there is a way to make the whole directory bold when using `trucate_to_unique`. For some other truncation strategies `POWERLEVEL9K_DIR_CONTENT_EXPANSION='%B$P9K_CONTENT%b'` should work.

**Comment by tgdfool2** [comment]
Thanks for your answer @romkatv. 

Quickly tested this setting with `truncate_from_right` and it does almost the job. The icon and middle segments remain plain though:
![image](https://user-images.githubusercontent.com/66017789/190596796-69c79b56-22d0-45d3-98da-4880dc9c8d42.png)

**Comment by romkatv** [comment]
That doesn't surprise me.
