### ISSUE TITLE
How to display current version of php and laravel using docker?

### ISSUE THREAD

**Issue by felipe-dsdev** [romkatv/powerlevel10k#2021]
My application is in a docker container, it is possible to get the versions (I use docker-compose.yml), or if there is any way to customize the command that gets the versions?

For php I can use the command `docker-compose exec app php --version` (with app being the name of the container), for example.

**Comment by romkatv** [comment]
You can implement a custom prompt segment. Search for "example" in `~/.p10k.zsh` and check out `p10k help segment`.
