### ISSUE TITLE
Trim down prompt when accepting an empty command

### ISSUE THREAD

**Issue by violin0622** [romkatv/powerlevel10k#2023]
Is it possible to trim down the prompt when accepting an empty command (press enter without command, which makes a new line ) ?

I've tried transient prompt, but it trims down prompts after execute. 

I searched for issues but still have no idea how to custom `p10k-on-post-prompt()` or `p10k-on-pre-prompt()`

**Comment by romkatv** [comment]
Suppose the content of your terminal window is this:

```text
~/project master █
```

Then you press ENTER. What should the content of the terminal window become?

**Comment by violin0622** [comment]
Here's what it looks like now, prompt will trim down to "❯" after I press "enter".:
![截屏2022-09-16 12 00 16 3](https://user-images.githubusercontent.com/6880156/190554778-e031283c-197b-4a14-baf9-f47d68d446ef.png)


And what I expect is (made image by PS):  
![截屏2022-09-16 12 00 16](https://user-images.githubusercontent.com/6880156/190554831-b85571ba-7b6b-4c61-9191-9eb5a7f43003.png)
Prompt will only trim when I input no command and just press "enter".

**Comment by romkatv** [comment]
Interesting. I'd like to understand a bit more. Why do you press ENTER without entering a command? What are you trying to achieve by doing it?

**Comment by violin0622** [comment]
People press several ENTER between commands for  the purpose of separating the output, make it easier to look back . It's especially useful when output has many lines.

**Comment by romkatv** [comment]
In this case perhaps you want this?

1. Open `~/.p10k.zsh`.
2. Search for `POWERLEVEL9K_PROMPT_ADD_NEWLINE` and flit its value to `true`.
3. Add `typeset -g POWERLEVEL9K_SHOW_RULER=true`.
4. Restart zsh with `exec zsh`.

You can try (2) and (3) independently. You can also customize ruler with these parameters:

```zsh
typeset -g POWERLEVEL9K_RULER_CHAR='·'
typeset -g POWERLEVEL9K_RULER_FOREGROUND=238
```

Or these:

```zsh
typeset -g POWERLEVEL9K_RULER_CHAR=' '
typeset -g POWERLEVEL9K_RULER_BACKGROUND=236
```

**Comment by violin0622** [comment]
Good. It's not as I originally expect but it works too.
