### ISSUE TITLE
Resizing terminal window makes everything go crazy

### ISSUE THREAD

**Issue by Smoukus** [romkatv/powerlevel10k#2024]
[Screencast from 15.09.2022 16:59:14.webm](https://user-images.githubusercontent.com/48409293/190438126-a18274ad-0643-47e2-bcb4-72cdd227dc12.webm)
Video showcases perfectly what I'm talking about.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
