### ISSUE TITLE
[feature request] shorten anchors

### ISSUE THREAD

**Issue by yshui** [romkatv/powerlevel10k#2025]
I am looking for ways to achieve this behavior: highlight anchors in path, but also shorten them.

I think whether to display anchors in bold should be separate from whether they are shortened. Displaying them in bold gives me a useful hint where inside a project I am (anchors are usually project roots), whether I also want to shorten them could be a separate decision (in this case, I do want to).

**Comment by romkatv** [comment]
This sounds reasonable. If you send a clean PR that adds `POWERLEVEL9K_DIR[_<STATE>]_ANCHOR_SHORTEN` (defaults to `true`), I'll merge it. It's unlikely that I'll implement this myself.

**Comment by yshui** [comment]
After some thought I think it's better to not change the behavior of anchors, and instead change whether markers are considered anchors. In other word, I want to add `POWERLEVEL9K_DIR_MARKER_IS_ANCHOR` (defaults to `true`) and `POWERLEVEL9K_DIR_MARKER_BOLD` (defaults to `false`).

I will look into it, I am not familiar with shell programming.

**Comment by romkatv** [comment]
I'm a lot less enthusiastic about `POWERLEVEL9K_DIR_MARKER_IS_ANCHOR` and `POWERLEVEL9K_DIR_MARKER_BOLD`. If markers are not anchors, then anchor styling shouldn't apply to them, which necessitates a new set of flags for styling markers. That's a lot of new parameters. Moreover, what if someone wants markers to NOT be shortened but wants to style them differently from head/tail anchors? This doesn't look pretty.

**Comment by yshui** [comment]
Hmm, but this is one of my itches I want to scratch: I want anchors to be bold but shortened, except at least the last one (i.e. the cwd). 

Maybe something like `DIR_SHORTEN_ANCHORS_EXCEPT` (defaults to `false`), and accept `first|last` like `TRUNCATE_BEFORE_MARKER` does.

**Comment by romkatv** [comment]
Would `POWERLEVEL9K_DIR[_<STATE>]_MARKER_SHORTEN` (defaults to `true`) be OK? If so, I'll merge a PR that adds these parameters provided that it's clean.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here.
