### ISSUE TITLE
adding parentheses to the virtualenv prompt

### ISSUE THREAD

**Issue by xeros-and-ones** [romkatv/powerlevel10k#2027]
i'm so sorry if the question seem stupid or noob :stuck_out_tongue: 

i added the virtualenv prompt in the p10k.zsh with the show python version set to true but the appear just like that, and i want to move them to the left prompts but when i do it's harder to destigish and the virtualenv, os icon and dirname get all mushed.

is there a way to add the virtual env to appear iside parenthises so it's easier to read when i put it on the left

`╭─( test_venv 3.10.6 )──   ~/Documents`
something like that is what i'm after.

**Comment by romkatv** [comment]
Try this:

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_PREFIX='('
typeset -g POWERLEVEL9K_VIRTUALENV_SUFFIX=')'
```

**Comment by xeros-and-ones** [comment]
thank you for the quick reply.
is the prefix and suffix commands available for all virtual evironments and version prompts like (anaconda, goenv, go_version, nodeenv, nodenv, nvm, node_version, rust_version, dotnet_version) if i wanna unify the look of all these prompts to appear on the left with same style ?

**Comment by xeros-and-ones** [comment]
thanks so much for the helpful answers.
Hope you have a fantastic day. :clinking_glasses:

**Comment by romkatv** [comment]
Thank you. Have a great day!
