### ISSUE TITLE
egrep is depricated warning

### ISSUE THREAD

**Issue by Spock117** [romkatv/powerlevel10k#2029]
Hi all,
I get this warning when I start my terminal.
```
egrep: warning: egrep is obsolescent; using grep -E
```
I also got another warning but I suppressed it by adding:
```
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
```
to `.zshrc`. I know its a minor thing but can it be fixed?

**Comment by romkatv** [comment]
Does powerlevel10k generate the warning quoted in the OP?

**Comment by luc14n0** [comment]
> Does powerlevel10k generate the warning quoted in the OP?

Oh, sorry for not seeing it before. But no, here I don't get any warnings when using `POWERLEVEL9K_INSTANT_PROMPT=verbose`.

**Comment by romkatv** [comment]
Since powerlevel10k doesn't produce or trigger the egrep warning, there is nothing to fix in powerlevel10k w.r.t. this warning.
