### ISSUE TITLE
uwanted question mark and number after git

### ISSUE THREAD

**Issue by Grzyb9k** [romkatv/powerlevel10k#2030]
![obraz](https://user-images.githubusercontent.com/73300122/191906691-62cb96d6-3d96-4ee4-9306-00e06a1312f4.png)

After git branch information i have question mark and number one, what is this? How i can remove this?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by Grzyb9k** [comment]
Thanks ;)
