### ISSUE TITLE
Prompt disappear when conda env does not have a name

### ISSUE THREAD

**Issue by liblaf** [romkatv/powerlevel10k#2034]
Normally I have a prompt on the right side like this:

![image](https://user-images.githubusercontent.com/30631553/192134698-a3c5b688-8de7-4c26-8235-14befb216c7e.png)

After I activated a conda environment with prefix but without name:

```console
conda activate ./envs
```

The dotted line and prompt on the right disappeared!

![image](https://user-images.githubusercontent.com/30631553/192134743-6a162d85-a205-451d-900e-b6b038335b96.png)

However, the prompt on the left and the second line is not affected.

**Comment by romkatv** [comment]
Try making the terminal window wider. You'll see what's going on.

**Comment by liblaf** [comment]
Thanks a lot! It turns out that the `${CONDA_PROMPT_MODIFIER}` (which is the absolute path to env prefix) is too long to fit in terminal window. Now I have configured `${CONDA_PROMPT_MODIFIER}` with:

```console
conda config --set env_prompt '({name}) '
```

Now it only shows the last segment of prefix.
