### ISSUE TITLE
Is Meslo a MUST font? I used to use iosevka in the past without any trouble.

### ISSUE THREAD

**Issue by josefson** [romkatv/powerlevel10k#2038]
I recenlty upgraded all my stack and some itens are being shown broken:

![image](https://user-images.githubusercontent.com/5399654/192874722-077d12bc-59f6-4b46-944e-f1d6f4c0fe7a.png)
Upon reading the installation section I see the usage of the meslo font to be used which wasn't prior.
Asking the user to change its terminal font entirely for a prompt is a bit too much IMHO. Is there a workaround this?

**Comment by romkatv** [comment]
If your font is missing glyphs that you would like to use in prompt, then you need to either fix your font, switch to a different font, or configure prompt to use different glyphs. There are no other options.

**Comment by josefson** [comment]
Gotcha, thanks!
