### ISSUE TITLE
POWERLEVEL9K_VCS_BACKENDS=(hg) painfully slow

### ISSUE THREAD

**Issue by danrneal** [romkatv/powerlevel10k#2039]
I know the README states that this is expected so this is a feature requests rather than a bug report.

I was wondering if there is any chance of hg getting any love and being optimized.  I know very few people use hg but there are dozens of us!!!

**Comment by romkatv** [comment]
There is practically zero chance I'll ever be working on this. Sorry.

**Comment by danrneal** [comment]
Is there any chance at just gutting the feature set. Maybe just keep the
color changing prompt and that's it.  That way it's fast even if less
informative?

**Comment by romkatv** [comment]
I have many things on my TODO list that I consider higher priority than improving `hg`, and the majority of those will never be done.

If this is something you care about, consider implementing a custom prompt segment that shows what you need. Search for "example" in `~/.p10k.zsh` and see `p10k help segment`.

**Comment by danrneal** [comment]
Fair enough.  Is there a list of features that hg currently (halfway) supports?  That way I can try to replicated them outside of in a segment?

**Comment by romkatv** [comment]
Nope. This segment uses `vcs_info`, so I would recommend simply read its documentation and implementing what you like on top. See https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Version-Control-Information

**Comment by danrneal** [comment]
Thanks! That was just what I was looking for.

On a related note, is there a way to re-render a segment?  zle reset-prompt doesn't work to re-render the prompt in place (I'm assuming that is intentional).  However I have found a way to asynchronously do the expensive call of "is the workspace dirty", and then want to update the color of the segment asynchronously so as to keep the speed.

**Comment by romkatv** [comment]
Here's an outline of async prompt segment:

```zsh
function my_hg_status() {
  local dir=$1
  # invoke commands here and print to stdout
}

function my_hg_callback() {
  typeset -g my_gh_content="$3"
  p10k display -r
}

async_stop_worker         my_hg_worker
async_start_worker        my_hg_worker -u
async_unregister_callback my_hg_worker
async_register_callback   my_hg_worker my_hg_callback

function prompt_my_hg() {
  # Optional:
  #
  #   typeset -g my_gh_content=
  
  # Optional:
  #
  #   typeset -g my_gh_content='loading'

  async_job my_hg_worker my_hg_status $PWD
  p10k segment -e -t '$my_gh_content'
}
```

It won't be as good as builtin prompt segments (p10k's async engine is light years ahead of zsh-async but unfortunately it's not exposed via the public API) but it'll do the job.

**Comment by danrneal** [comment]
This works for the main content, but it seems `-e` doesn't apply to the background argument.  Is there a way to asynchronously update the background as well as the text?

**Comment by romkatv** [comment]
Please post your current working code and describe where it falls short.

**Comment by danrneal** [comment]
I have 2 copies of not quite working code.  They change the content correctly but the background color changes get ignored.  I suspect because the -e parameter only works on the -t input but not the -b or the -s inputs.

```
function my_hg_status() {
  local dir=$1
  echo $(eval "hg status -mard")
}

function my_hg_callback() {
  if [[ -n $3 ]]; then
    typeset -g my_hg_content="$WORKSPACE ●"
    typeset -g my_hg_background=yellow
  else
    typeset -g my_hg_content="$WORKSPACE"
    typeset -g my_hg_background=green
  fi

  p10k display -r
}  

async_stop_worker         my_hg_worker
async_start_worker        my_hg_worker -u
async_unregister_callback my_hg_worker
async_register_callback   my_hg_worker my_hg_callback
   
function prompt_my_hg() {
  typeset -g my_hg_content=$WORKSPACE
  typeset -g my_hg_background=blue
   
  async_job my_hg_worker my_hg_status $PWD
  p10k segment -e -f white -b '$my_hg_background' -t '$my_hg_content'
}  
```

```
In p10k.zsh
  typeset -g POWERLEVEL9K_MY_HG_UNKNOWN_CONTENT_EXPANSION=$WORKSPACE
  typeset -g POWERLEVEL9K_MY_HG_CLEAN_CONTENT_EXPANSION=$WORKSPACE
  typeset -g POWERLEVEL9K_MY_HG_DIRTY_CONTENT_EXPANSION="$WORKSPACE ●"
  typeset -g POWERLEVEL9K_MY_HG_UNKNOWN_BACKGROUND=blue
  typeset -g POWERLEVEL9K_MY_HG_CLEAN_BACKGROUND=green
  typeset -g POWERLEVEL9K_MY_HG_DIRTY_BACKGROUND=yellow


function my_hg_status() {
  local dir=$1
  echo $(eval "hg status -mard")
}

function my_hg_callback() {
  if [[ -n $3 ]]; then
    typeset -g state=DIRTY
  else
    typeset -g state=CLEAN
  fi

  p10k display -r
}  

async_stop_worker         my_hg_worker
async_start_worker        my_hg_worker -u
async_unregister_callback my_hg_worker
async_register_callback   my_hg_worker my_hg_callback
   
function prompt_my_hg() {
  typeset -g state=UNKNOWN
 
  async_job my_hg_worker my_hg_status $PWD
  p10k segment -s $state -f white
}

**Comment by romkatv** [comment]
I took the first version of your code (you didn't give me enough info to pick one, so I didn't even look at the second) and modified it. Untested.

```zsh
function my_hg_status() {
  local dir=$1
  # Bug on the next line: `dir` is unused.
  hg status -mard
}

function my_hg_callback() {
  # Bug in this function: WORKSPACE is unset.

  if [[ -n $3 ]]; then
    typeset -g my_hg_content="$WORKSPACE ●"
    typeset -g my_hg_state=DIRTY
  else
    typeset -g my_hg_content="$WORKSPACE"
    typeset -g my_hg_state=CLEAN
  fi

  p10k display -r
}  

async_stop_worker         my_hg_worker
async_start_worker        my_hg_worker -u
async_unregister_callback my_hg_worker
async_register_callback   my_hg_worker my_hg_callback
   
function prompt_my_hg() {
  typeset -g my_hg_state=UNKNOWN
  async_job my_hg_worker my_hg_status $PWD

  p10k segment -e -f white -s UNKNOWN -b blue   -c '${(M)my_hg_state:#UNKNOWN}' -t loading
  p10k segment -e -f white -s CLEAN   -b green  -c '${(M)my_hg_state:#CLEAN}'   -t '$my_hg_content'
  p10k segment -e -f white -s DIRTY   -b yellow -c '${(M)my_hg_state:#DIRTY}'   -t '$my_hg_content'
}
```

See `p10k help segment` for documentation.

**Comment by danrneal** [comment]
Absolutely brilliant!  Closing this, thank you for all your help.

**Comment by steakknife** [comment]
Reopening a dead horse. Thanks for this. I'm looking to do something similar for a VCS that's sparse/slower and works much like `hg`. I'm probably going to "fork" the `hg` stuff.
