### ISSUE TITLE
Unknown icon on non-customized font

### ISSUE THREAD

**Issue by stevenguh** [romkatv/powerlevel10k#204]
I used `p10k configure` to setup. I can't see the icon on the first 3 pages on the configure so I selected `n`. So I assume it should be configured by p10k so I won't see unknown character with regular font; however, when I navigate to a "system protected" directory like `~/Library/HomeKit` it shows the icon like the image and the text a copied below.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/3455662/64469486-96001280-d165-11e9-854e-b01ea899ae81.png">

` ~/Library/HomeKit`

I assumed that's a lock icon? If it is, can we have an option to use the emoji icon configured in the `p10k configure`?

Thank you for creating p10k :)

EDIT: I did some more goggling. U+E0A2 is the unknown character, and it is used as a [locked icon ](https://github.com/ryanoasis/powerline-extra-symbols)

**Comment by romkatv** [comment]
Thanks for the bug report. Fixed. Once you update powerlevel10k you should see ∅ in front of the current directory if it's not writable.

**Comment by romkatv** [comment]
Forgot to mention that you'll need to run `p10k configure` after updating powerlevel10k.
