### ISSUE TITLE
wrong file path in VScode integrated terminal

### ISSUE THREAD

**Issue by SwitWu** [romkatv/powerlevel10k#2043]
When I first opened the VScode, the terminal showed the right path. However, after running a command like `pwd`, an anomaly happened. Please look at the following screenshot.
<img width="1163" alt="QQ20221004-145335@2x" src="https://user-images.githubusercontent.com/39337667/193754840-ab4b8810-10c9-401f-b0ee-c6b24d967bf3.png">

**Comment by romkatv** [comment]
Directory can be shortened to give you more space for typing commands. See https://github.com/romkatv/powerlevel10k#current-directory-that-just-works.

You can customize directory shortening by editing `~/.p10k.zsh`. See these parameters: https://github.com/romkatv/powerlevel10k/blob/843dcf016710a4fe39f8ad65da2929f9128436fd/config/p10k-rainbow.zsh#L261-L274.

Tip: run `p10k configure` and select two-line prompt. This will give you a lot more space for prompt and for typing commands. Enable *Transient Prompt* to avoid the biggest downside of two-line prompt.

**Comment by SwitWu** [comment]
I see! Thank you very much!

**Comment by romkatv** [comment]
You are welcome.
