### ISSUE TITLE
Is there any way to supply the configure parameters as cli arguments?

### ISSUE THREAD

**Issue by AnderssonPeter** [romkatv/powerlevel10k#2044]
I'm currently setting up a cloud init file and I'm wondering if i can create a config file without having to copy the base theme file and patching it by hand?

**Comment by romkatv** [comment]
Run `p10k configure` once, save `~/.p10k.zsh`, use it forever everywhere.

**Comment by AnderssonPeter** [comment]
@romkatv that would require me to yml encode the entire file adding a huge amount of text.

**Comment by romkatv** [comment]
There must be a way to get a file into the cloud environment. You managed to get the whole powerlevel10k in there, which is massive in comparison.

Closing because I don't intend to do anything here.

**Comment by AnderssonPeter** [comment]
Ah your right i could download a gist.

**Comment by romkatv** [comment]
The best way is to store all dotfiles (.zshrc, .zshenv, .p10k.zsh, .vimrc, .gitconfig, etc.) in a single git repository.

**Comment by noahkiss** [comment]
> The best way is to store all dotfiles (.zshrc, .zshenv, .p10k.zsh, .vimrc, .gitconfig, etc.) in a single git repository.

Any suggestions for how to let p10k handle the font install on new computers without overwriting the rest of the configuration file?

**Comment by romkatv** [comment]
How you automate font installation depends on your OS. Links to the font files are here: https://github.com/romkatv/powerlevel10k#manual-font-installation
