### ISSUE TITLE
How can I use Icons from NerdFonts with normal format (instead of Bold format)

### ISSUE THREAD

**Issue by Lodan23** [romkatv/powerlevel10k#2045]
I'm using a hashtag (#) to identify when I am logged as root. In the .p10k.zsh I've witten this:

```
# Context format when running with privileges: bold user@hostname.
typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='\uf292'
```

But what I got is the Hashtag in bold (at least is what I'm interpreting)
![image](https://user-images.githubusercontent.com/100961502/194105416-110d7fbd-fd99-428b-8874-a4ba1a1d5f3e.png)

**Comment by Lodan23** [comment]
Thank you very much for your extremely fast answer. Trying a lot of stuff I've discovered that writting any other character towards the icon, its size become smaller.

This is an example (I've added a "." right after "\uf292"):
```
# Context format when running with privileges: bold user@hostname.
typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='\uf292.'
```
![image](https://user-images.githubusercontent.com/100961502/194171650-dcc4a392-e868-48cf-93cd-09315c9c1fd2.png)

Do you know why is this happening? If I could add an "invisible" character It would work for me.

Thanks in advance.

**Comment by NVZVN** [comment]
Hi Roman,

Hope you are well.

I had unsubscribed to this thread a few days ago on github but I am still
receiving updates to your email.

Is there a way you could prevent the emails from coming in?

Thank you so much, and have a great day ahead!

Kind regards
Naz

**Comment by romkatv** [comment]
> Hi Roman, Hope you are well. I had unsubscribed to this thread a few days ago on github but I am still receiving updates to your email. Is there a way you could prevent the emails from coming in? Thank you so much, and have a great day ahead! Kind regards Naz

Sounds like a bug in GitHub.

**Comment by romkatv** [comment]
> Thank you very much for your extremely fast answer. Trying a lot of stuff I've discovered that writting any other character next to the icon, its size become smaller.

If that's how your terminal renders it, then that's how it renders it. Once again, you can try it for yourself with a plain `print`.

```zsh
print '\uf292.'
```

Or yellow:

```zsh
print -P '%F{yellow}\uf292.%f'
```

If you don't like how it looks, use something else. Powerlevel10k cannot make glyphs look differently from how they look.
