### ISSUE TITLE
POWERLEVEL9K_DIR_FOREGROUND seems to have no effect

### ISSUE THREAD

**Issue by TheShiftedBit** [romkatv/powerlevel10k#2046]
I've tried configuring the color of my prompt, but I can't change the color of "regular" directories to anything other than black:

![Screenshot from 2022-10-06 00-19-46](https://user-images.githubusercontent.com/5598357/194213126-63c7b9dc-aa28-465e-a5dc-813892a0b4f1.png)

In particular, changing `POWERLEVEL9K_DIR_FOREGROUND` doesn't seem to do anything. I can change the color of anchor directories, shortened directories, etc; but not directories that don't fit into any particular category.

To reproduce, run `p10k configure`, and then choose the following options:
```
diamond question: yes.
lock question: yes.
debian logo question: yes.
icon spacing question: yes.
prompt style: (3) Rainbow.
Character set: (1) Unicode.
Show current time: (1) No.
Prompt separators: (3) Slanted.
Prompt heads: (1) Sharp.
Prompt tails: (1) Flat.
Prompt Height: (1) One Line.
Prompt Spacing: (2) Sparse.
Icons: (1) Few icons.
Prompt Flow: (1) Concise.
Enable Transient Prompt? (n) No.
Instant Prompt Mode: (3) Off.
```
Then, edit `POWERLEVEL9K_DIR_FOREGROUND` to a different color and source the config.
The color will not change.

I'm on commit `843dcf016710a4fe39f8ad65da2929f9128436fd`.

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style

**Comment by TheShiftedBit** [comment]
I saw that; unfortunately, it doesn't really help.

 > Type p10k configure and choose a more readable prompt style.

If I change the style to something other than rainbow, the regular directory text is still black, so it's even harder to read:
![Screenshot from 2022-10-06 10-44-30](https://user-images.githubusercontent.com/5598357/194344866-24cb9b89-fb9d-4907-9851-0c2afa020b11.png)

 > [Change terminal color palette](https://github.com/romkatv/powerlevel10k#change-the-color-palette-used-by-your-terminal). Try Tango Dark or Solarized Dark, or change just the "blue" color.

This works of course - I can change the text color by redefining what "black" is. But I'd rather not redefine black to white, as that would make any other program that uses black unreadable.

 > [Change directory background and/or foreground color](https://github.com/romkatv/powerlevel10k#set-colors-through-Powerlevel10k-configuration-parameters). The parameters you are looking for are called `POWERLEVEL9K_DIR_BACKGROUND`, `POWERLEVEL9K_DIR_FOREGROUND`, `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND`, `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND` and `POWERLEVEL9K_DIR_ANCHOR_BOLD`. You can find them in ~/.p10k.zsh.

This is where the issue happens. All the settings work _except_ `POWERLEVEL9K_DIR_FOREGROUND`, which seems to have no effect. The text always renders black.

Since `POWERLEVEL9K_DIR_FOREGROUND` is suggested everywhere but has no effect, I am reasonably confident this is a bug in powerlevel10k.

**Comment by romkatv** [comment]
Please try the following:

1. Open `~/.p10k.zsh` with a text editor.
2. Search for `POWERLEVEL9K_DIR_FOREGROUND`. You should find the line that sets this parameter. Change the value of this parameter to `1`. Here's how it should look like:
   ```zsh
    typeset -g POWERLEVEL9K_DIR_FOREGROUND=1
   ```
3. Repeat the previous step for `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND` and `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND`.
4. Save the file.
5. Run `exec zsh` to restart zsh.
6. Run the following command to print the values of the parameters you just set:
   ```zsh
   typeset -pm '*POWERLEVEL9K_DIR_*FOREGROUND'
   ```
7. Verify that the parameters are set as expected and not overwritten by any other config files. The output of the above command should look like this:
   ```text
   typeset _POWERLEVEL9K_DIR_FOREGROUND=1
   typeset POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=1
   typeset POWERLEVEL9K_DIR_FOREGROUND=1
   typeset _POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=1
   typeset _POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=1
   typeset POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=1
   ```
8. Verify that the current directory in prompt is rendered with red foreground.

**Comment by romkatv** [comment]
> I wanted to disable the `dir` prompt segment when I was below certain directories

You can do this with the generic `POWERLEVEL9K_<segment>_DISABLED_DIR_PATTERN` parameter. Try this:

```zsh
POWERLEVEL9K_DIR_DISABLED_DIR_PATTERN='(/foo/bar|/tmp)(|/*)'
```

This will disable `dir` whenever `$PWD` matches `(/foo/bar|/tmp)(|/*)`. You can test it like this:

```zsh
[[ $PWD == (/foo/bar|/tmp)(|/*)
```

This matches whenever you are under `/foo/bar` or `/tmp`.

**Comment by romkatv** [comment]
It's likely that instead of creating your own segment for the current directory you can use named directories instead. See https://github.com/romkatv/powerlevel10k/issues/1518#issuecomment-890808101. If static named directories don't work for you, try [dynamic named directories](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Dynamic-named-directories). If you can describe what exactly you are doing, I can give more specific pointers.

**Comment by TheShiftedBit** [comment]
Oh, I wasn't familiar with that feature. That gets me pretty much what I was going for. Thanks!
