### ISSUE TITLE
After using the powerlevel10k for some time, the icons stopped displaying correctly.

### ISSUE THREAD

**Issue by KKQC** [romkatv/powerlevel10k#2047]
<img width="577" alt="Bildschirmfoto 2022-10-06 um 08 48 30" src="https://user-images.githubusercontent.com/69313475/194233333-a27c9318-4fe4-4376-b6eb-e9e42f64251a.png">

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render
