### ISSUE TITLE
p10k configure written in /tmp

### ISSUE THREAD

**Issue by SJoJoK** [romkatv/powerlevel10k#2050]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/50450335/194555018-22fd7f21-bed3-40de-93d1-fd56838f3478.png">
I wonder how to set it on ~/.p10k?
(my username is sjk)

**Comment by romkatv** [comment]
The config gets written to `POWERLEVEL9K_CONFIG_FILE`. If this parameter is not set, to `$ZDOTDIR/.p10k.zsh`. If `ZDOTDIR` is not set, to `$HOME/.p10k.zsh`.

**Comment by romkatv** [comment]
If you don't know what's going on and if you are using Visual Studio Code Terminal, file a bug against it.

**Comment by SJoJoK** [comment]
> If you don't know what's going on and if you are using Visual Studio Code Terminal, file a bug against it.

yes i'm using VSC, thanks for replying (I dont rememeber i set something like $ZDOTDIR...)

**Comment by romkatv** [comment]
It's probably vscode that set it. If this is true, it's a bug in vscode.

**Comment by SJoJoK** [comment]
> It's probably vscode that set it. If this is true, it's a bug in vscode.

ok i'm gonna open an issue on it

**Comment by kema-dev** [comment]
Same issue here, happens using VSCode's terminal, not other term

**Comment by romkatv** [comment]
Thanks for the confirmation. Then it's definitely a bug in vscode. Closing. Please post a link to a vscode issue when you file it.

**Comment by SJoJoK** [comment]
Related vscode issue: https://github.com/microsoft/vscode/issues/157128
