### ISSUE TITLE
zsh crashes when using fzf-tab with ffmpeg

### ISSUE THREAD

**Issue by beyond9thousand** [romkatv/powerlevel10k#2051]
https://peertube.bgzashtita.es/w/wNEeZ29TViscSMAMRxX6qc

**Comment by romkatv** [comment]
Please describe what you do, what you expect and what you observe.

**Comment by beyond9thousand** [comment]
Sorry, I assumed the video would be enough.

Anyway, whenever completion is called with `fzf-tab` for `ffmpeg`, the shell seems to crash/segfault. You can take a look at the link to see a demonstration of the same. The same does not happen with other prompts.

**Comment by romkatv** [comment]
If zsh crashes, that's a bug in zsh.

**Comment by beyond9thousand** [comment]
Don't mean to be rude, but as I pointed out earlier - the same does not happen when using other zsh prompts. Are you suggesting that zsh would be to blame regardless? /genuine

**Comment by romkatv** [comment]
Yes, of course. Zsh crashing is a big in zsh.

**Comment by romkatv** [comment]
When something crashes, you usually want to make it dump `core` and then use a debugger. This is beyond the scope of powerlevel10k though. Closing as "not my issue".
