### ISSUE TITLE
Prompt gets stuck at bottom of window in MacOSX

### ISSUE THREAD

**Issue by chrisbrown-sfdc** [romkatv/powerlevel10k#2055]
This doesn't seem to be a hang, but does seem to be some incompatibility between what zsh/powerlevel10k is doing in working with macosx terminal.  Workaround: control-L, however this won't work while in a subprompt such as a ssh-agent-key request.

1. powerlevel10k fresh install with:
```
zstyle :omz:plugins:ssh-agent lifetime 4h
zstyle :omz:plugins:ssh-agent lazy yes

plugins=(git ssh-agent)
```

2. Enter commands until the bottom of the window is reached.
3. Try to enter another command such as `ls`.

Expected:
Both the ls result and the next prompt appear on new lines.

Actual:
ls result isn't shown and the prompt overwrites the prompt where I typed `ls`

**Comment by chrisbrown-sfdc** [comment]
Additional note: I've noticed that sometimes the shell only fills the top portion of the terminal window.  When this happens, the issue does not occur.  This makes me think that the shell is not correctly detecting the size of the terminal and thinks (in the broken case) that it is much larger than it actually is.

**Comment by chrisbrown-sfdc** [comment]
Resizing the window doesn't seem to affect zsh/pl10k at all - it doesn't seem to notice the size change whether in foreground or not, and if the window is made smaller than the size it thinks it is, this issue occurs.  Once the issue has occurred, resizing it larger doesn't helm until ctl-L is pressed.

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with a different theme?

**Comment by chrisbrown-sfdc** [comment]
I had a different theme before (af-magic) and I didn't see anything like this with that.  I'll try again and see if I can trigger it.

**Comment by chrisbrown-sfdc** [comment]
Maybe also worthy of note: vim _is_ aware of the actual screen size.

**Comment by romkatv** [comment]
Something is breaking your TTY somehow. It's possible that `reset` will restore it but maybe not. I'm 99.9% sure it's not powerlevel10k that's doing it.

**Comment by chrisbrown-sfdc** [comment]
`reset` did do something, and I think I see what you mean.  I'll see if I can figure out what that other thing is.  Thanks!

**Comment by romkatv** [comment]
One possibility is that you have incorrect `TERM` environment variable.

Try disabling everything, even Oh My Zsh, and leaving just powerlevel10k. Your `~/.zshrc` should look like this:

```zsh
source ~/.p10k.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

Delete all other rc files (`.zshenv`, etc.). Then restart your terminal. Does it get rid of the issue?

**Comment by chrisbrown-sfdc** [comment]
Unfortunately (or maybe fortunately since that's a sign that it's something running later) a freshly started shell doesn't have this problem (without the changes shown above).  I'll narrow it down and if I can, but I think you're right, this isn't p10k, it's something else.  (also noted that when in the broken state, while vim knows the size, less does not)

**Comment by romkatv** [comment]
Closing as this is unlikely to be a powerlevel10k issue. Please post an update if you find out what's causing the issue.

**Comment by chrisbrown-sfdc** [comment]
You can leave this closed...  Just adding a note in case anyone (including me) gets here in the future: This problem seems to be caused when 'git commit' asks for my gpg password.  This brings up a 'text window' that seems to mess with the state of the window after.  I was able to work around this by adding to `~/.gnupg/gpg-agent.conf`:
```
pinentry-program /usr/local/bin/pinentry-tty
```
(Specific to mac - for most OS's you probably want /usr/bin, not /usr/local/bin.)

**Comment by romkatv** [comment]
Thanks for the update.
