### ISSUE TITLE
Strange code 1 after ‘Last Login' 

### ISSUE THREAD

**Issue by pherm** [romkatv/powerlevel10k#2058]
Hi, I installed powerlevel10k to work with .zshrc. I deactivated the 'Last Login' by creating a .hushlogin file.

However, I get this message when I open iterm2. A message that returns '1' each time I open Iterm app. Can you help me understand what it depends on and how to remove it? Thank you

<img width="760" alt="Senza nome 2" src="https://user-images.githubusercontent.com/26284332/195366452-aa592118-24ba-43a7-af67-602088a3994a.png">

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with a different theme?

**Comment by pherm** [comment]
i change in ZSH_THEME="robbyrussell" and run: source ~/.zshrc 

But the theme does not change and nothing happens, even if I do not pass any theme

**Comment by romkatv** [comment]
Restart zsh with `exec zsh` after changing rc files.

**Comment by romkatv** [comment]
Once you change the theme, close iTerm and open it again. Do you still get that "1"?

**Comment by pherm** [comment]
i do it: exec zsh, close iterm and re-open. No theme changed. nothing happen

**Comment by romkatv** [comment]
Are you saying you cannot switch to a different theme?

**Comment by pherm** [comment]
yeah, correct

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k

**Comment by pherm** [comment]
I have now managed to change theme. The value 1 still appears.
