### ISSUE TITLE
node_version segments not working with both fnm and nvm

### ISSUE THREAD

**Issue by oscargong** [romkatv/powerlevel10k#2063]
I uncomment `node_version` on `.p10k.zsh`, but it does not show up
I tried both fnm and nvm, with antigen and znap, none of them working. 

The entire .zshrc: 
- fnm + znap : https://codeshare.io/zyWg4r
- nvm + antigen: https://codeshare.io/EB4eRv

![](https://user-images.githubusercontent.com/108839639/196236569-8cf6cf2c-eaf9-4aaa-a0a6-d07cba58cb8f.png)

**Comment by romkatv** [comment]
1. Open `~/.p10k.zsh`.
2. Find this block: https://github.com/romkatv/powerlevel10k/blob/8091c8a3a8a845c70046684235a01cd500075def/config/p10k-lean.zsh#L993-L994
3. Flip `true` to `false`.
4. Save.
5. Restart zsh with `exec zsh`.

**Comment by oscargong** [comment]
Hi @romkatv, 
Thanks for your reply. It shows up now. 
I didn't know it only shows for folder which contains `package.json` file by default.
