### ISSUE TITLE
font icons problem

### ISSUE THREAD

**Issue by Mask6asok** [romkatv/powerlevel10k#2064]
![2022-10-17_11-45](https://user-images.githubusercontent.com/46475699/196328102-515b3852-2417-4af3-a0d4-27413cf7d8f1.png)
when i use p10k on ubuntu 22.04, i found gnome terminal show some margin on the top of prompt
but in the vscode terminal, there is no margin, what should i do to fix this problem in gnome termial

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by Mask6asok** [comment]
it is not working, i think there is some change i made so powerline can not work beautifully

**Comment by romkatv** [comment]
I don't think I can add anything on top of what the FAQ already says. Closing.

**Comment by Mask6asok** [comment]
i finally know what is the problem: i use ubuntu on chinese, so the terminal show some margin on the top of the line. when i change to english i become beautiful :)

**Comment by romkatv** [comment]
Thanks for the update. I'm glad you found a solution.
