### ISSUE TITLE
Exit code indicator seems to be lagging?

### ISSUE THREAD

**Issue by InCogNiTo124** [romkatv/powerlevel10k#2065]
I am not sure if this is a bug, but the exit code indicator of my transient prompt seems to be lagging. This is a behaviour when I enter a failing command: 

https://user-images.githubusercontent.com/12953598/196510113-7e1b7474-6f11-41c0-84bb-02f76602d6ee.mp4

Here, I expect for the red arrow to be **at the transient prompt** (third line), and not at the actual prompt.

It gets confusing afterwards:

https://user-images.githubusercontent.com/12953598/196511857-d8af48ff-f57d-4863-90a2-a3be52dc4334.mp4

Here it seems the `false` command exited nicely, but `true` command had failed. Is there any way for this to be fixed, or at least configured?

**Comment by InCogNiTo124** [comment]
In short, I want for the red arrow to be next to the command that failed and not in the next line

**Comment by eddyg** [comment]
This isn't possible, see this [FAQ entry](https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them).

**Comment by InCogNiTo124** [comment]
Ah, I see. Thanks.
