### ISSUE TITLE
gitstatus_stop_p9k_

### ISSUE THREAD

**Issue by ianzone** [romkatv/powerlevel10k#2068]
got this for the newly installed p10k, have no idea what it is.
gitstatus_stop_p9k_:zle:41: No handler installed for fd 16
gitstatus_stop_p9k_:49: failed to close file descriptor 16: bad file descriptor

**Comment by romkatv** [comment]
Every time this error got reported, it was caused by some code other than powerlevel10k. If you disable all plugins and whatnot, it'll go away.
