### ISSUE TITLE
How to refresh CWD displayed on shell prompt if you change directory with shortcut?

### ISSUE THREAD

**Issue by gavvvr** [romkatv/powerlevel10k#2069]
Hi. Thanks for the beautiful and blazing fast zsh theme.

I've actually created this issue to ask a question.
Suppose I have a `bindkey` shortcut for to change directory. For demonstrating the problem let's just move one level up:

```zsh
my-cd-func () {
    cd ..
    # zle reset-prompt
}

zle -N my-cd-func
bindkey '^Z' my-cd-func
```

Unfortunately, if I press ctrl+Z with powerlevel10k enabled, the CWD won't be refreshed until I refresh it "manually" (by pressing enter or ctrl+C)

As you can see there is a commented out `zle reset-prompt`. I found this solution by quick googling [here](https://stackoverflow.com/a/62208777/3581539), but unfortunately it does not work when powerlevel10k is enabled. An interesting thing is that the `zle reset-prompt` solves the problem when no theme is applied to zsh.

One more observation: if you call `my-cd-func` manually by typing function name in zsh shell and pressing enter, there is no issue: the CWD gets refreshed.

How to properly refresh the CWD displayed after jumping to another directory by using a `bindkey` shortcut?

PS actually the problem I am trying to solve it to configure a `bindkey` in my `.zshrc` to call [zoxide's `__zoxide_zi` function](https://github.com/ajeetdsouza/zoxide/tree/v0.8.3#flags), as if I typed the name of this function and pressed enter. Unfortunately, as soon as I invoke the function with the bind and select the directory where I would like to jump, the CWD  displayed on the shell prompt does not get updated.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/2048

**Comment by gavvvr** [comment]
Thank you @romkatv.

I've used your snippet from 2048 to redraw p10k prompt after jump to another directory with zoxide
