### ISSUE TITLE
Style VCS section in true color

### ISSUE THREAD

**Issue by volny** [romkatv/powerlevel10k#207]
Can the custom git status that comes with `p10k configure` be adapted to use true color (hex color values)?

The colors are hard-coded into strings, like

```
vcs+='${${VCS_STATUS_LOCAL_BRANCH:+%76F'${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}
```

In this case, how can the `76` color value be swapped out for something like `#99c794`?

**Comment by romkatv** [comment]
> Can the custom git status that comes with `p10k configure` be adapted to use true color (hex color values)?

Yes. Open `~/.p10k.zsh` with your favorite editor and change colors to your liking.

> 
> The colors are hard-coded into strings, like
> 
> ```
> vcs+='${${VCS_STATUS_LOCAL_BRANCH:+%76F'${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}
> ```
> 
> In this case, how can the `76` color value be swapped out for something like `#99c794`?

In ZSH foreground colors can be specified in two ways: `%F{color}` and `%colorF`.

The first syntax works with colors specified by name (`%F{green}`), by decimal code (`%F{76}`), and by hexadecimal code (`%F{#99c794}`). The second syntax works only with decimal color codes (`%76F`).

Note that the closing curly (`}`) needs to be escaped when it's on the right hand side of `${...:-...}` or `${...:+...}`. This is the reason I used `%76F` in the config -- it's easier on the eye than `%F{76\}`. It's also a notch faster.

Thus, if you want to display green components of `vcs` prompt segment in color `#99c794`, you need to replace `%76F` with `%F{#99c794\}`.

P.S.

Please update powerlevel10k to the latest version and run `p10k cofigure` before making these edits. You'll need to pick up https://github.com/romkatv/powerlevel10k/commit/9ce277d17999448af21afcf3f4695892692351c6 to ensure that hexadecimal colors don't leak into `vcs` prompt in `LOADING` state.

**Comment by volny** [comment]
Awesome, works like a charm. Thank you!
