### ISSUE TITLE
Support iTerm2 custom prefs folder

### ISSUE THREAD

**Issue by tekumara** [romkatv/powerlevel10k#2074]
`install_font` assumes the [default iTerm2 folder](https://github.com/romkatv/powerlevel10k/blob/5ee784787fe3c1855ee6f365cbf045712843989e/internal/wizard.zsh#L546) (ie: _~/Library/Preferences/_)

Would be nice to support cases where [prefs are loaded from a custom folder](https://github.com/tekumara/setup/blob/07a619536332954412f029d083c8a1c52ed5d284/install/defaults.sh#L11).

**Comment by romkatv** [comment]
The automatic font installation is best effort. If it doesn't work, you'll need to install the font manually.
