### ISSUE TITLE
Every time i open iterm2, i will be prompted with an introduction to prompt?how to close that?

### ISSUE THREAD

**Issue by byesec** [romkatv/powerlevel10k#2075]
I've selected Off in the configuration（Instant Prompt Mode）

<img width="685" alt="image" src="https://user-images.githubusercontent.com/69515281/198914602-002b972e-1a0b-4c8b-b2d7-c6d3b846dfb8.png">

how to close that?

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with another theme?
