### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by danielotieno** [romkatv/powerlevel10k#2077]
Every time I open iTerm 2, I'm getting the following error. 

```
[ERROR]: gitstatus failed to initialize.

Directory is not writable: /Users/myusername/.cache

Make it writable, then restart your shell.
```

**Comment by romkatv** [comment]
Have you tried making `/Users/myusername/.cache` writable?

**Comment by danielotieno** [comment]
Yes

**Comment by romkatv** [comment]
Did it help?

**Comment by danielotieno** [comment]
I'm getting 

`_p9k_dump_state:sysopen:6: can't open file /Users/myusername/.cache/p10k-dump-myusername.zsh.tmp.15464: permission denied`

**Comment by danielotieno** [comment]
Thank you very much @romkatv It has worked 

`[powerlevel10k] fetching gitstatusd .. [ok]`

**Comment by romkatv** [comment]
👍
