### ISSUE TITLE
git or icon

### ISSUE THREAD

**Issue by xuyastc** [romkatv/powerlevel10k#2078]
Hi, it's my pleasure to message you. I want to know, what is this? Where to set it? Because I want it to appear as git, not Icon
 
<img width="617" alt="QQ20221031-194302@2x" src="https://user-images.githubusercontent.com/37319368/199000213-4b3d0cd9-39f8-4b22-a6c7-b56797d7d0fc.png">

Please help me

**Comment by romkatv** [comment]
If the remote is on github, you see the github logo. If there is no remote or it's not on one of the popular providers, you get plain "git". You can customize it by uncommenting and changing the value of `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION` in `~/.p10k.zsh`.

**Comment by xuyastc** [comment]
git  what is the value. Where does this value come from?
<img width="116" alt="image" src="https://user-images.githubusercontent.com/37319368/199008410-44458473-cb16-4441-8706-addc5df565e5.png">

**Comment by xuyastc** [comment]
I want it all to be git

**Comment by romkatv** [comment]
```zsh
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=$'\uF1D3'
```

**Comment by xuyastc** [comment]
perfect, thanks
