### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by devsquad-alvaro-meireles** [romkatv/powerlevel10k#2079]
Hi! I'm starting to use the PowerLevel10k and I want to understand something...

1. Why in my case the visual of the rainbow style isn't equal to the example in the readme?:

My Rainbow Style:
![image](https://user-images.githubusercontent.com/98560934/199038198-32541d75-86eb-4033-b1a7-eb731744c95e.png)

What I want:
![image](https://user-images.githubusercontent.com/98560934/199038758-b25dabf7-dd6f-4e8f-9669-90e20f1dce13.png)

2. Why in my case I'm seeing "%" in the terminal, ahead of the PHP version?
![image](https://user-images.githubusercontent.com/98560934/199038198-32541d75-86eb-4033-b1a7-eb731744c95e.png)

**Comment by romkatv** [comment]
> 1. Why in my case the visual of the rainbow style isn't equal to the example in the readme?

Run `p10k configure` and select the style that most matches the example in the readme. If none match, see https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard.

> 2. Why in my case I'm seeing "%" in the terminal, ahead of the PHP version?

You have background jobs. Type `jobs` to see them.
