### ISSUE TITLE
p10k segment command doesn't work or I do something wrong

### ISSUE THREAD

**Issue by krzyhon** [romkatv/powerlevel10k#208]
Morning!

Let's say I have a function as below:

prompt_foo(){
  local message="My message"
  local color='%F{blue}'
  local symbol="\uf580"

  p10k segment -t $message -i $symbol -f $color -b clear;
}

I use it in right prompt. The problem is that only $message variable is resolved but $color and $symbol not. I've tried  option [{+|-}re] in many combination but without success.
What am I doing wrong?

Regards,
Krzyhon

**Comment by romkatv** [comment]
Try this:

```zsh
p10k segment -t $message -i $'\uf580' -f blue
```

Fixes applied:

1. `"\uf580"` is not the same thing as `$'\uf580'. Try this: `print -lr "\uf580" `$'\uf580'`.
2. '%F{blue}' is not a color, `blue` is.
3. `clear` is not a color. If you want transparent background, don't pass `-b`.

Would you mind sharing how you came up with this code? The examples and documentation in `~/.p10k.zsh` and in `p10k help segment` should've pointed you in the right direction.

**Comment by krzyhon** [comment]
Below is my function (found somewhere on internet) to showing battery level

`zsh_battery_level(){
  local percentage1=`pmset -g ps  |  sed -n 's/.*[[:blank:]]+*\(.*%\).*/\1/p'`
  local percentage=`echo "${percentage1//\%}"`
  local color='%F{red}'
  local symbol="\uf00d"
  pmset -g ps | grep "discharging" > /dev/null
  if [ $? -eq 0 ]; then
    local charging="false";
  else
    local charging="true";
  fi
  if [ $percentage -le 20 ]
  then symbol="\uf579" ; color='%F{red}' ;

  elif [ $percentage -gt 19 ] && [ $percentage -le 30 ]
  then symbol="\uf57a" ; color='%F{red}' ;

  elif [ $percentage -gt 29 ] && [ $percentage -le 40 ]
  then symbol="\uf57b" ; color='%F{yellow}' ;

  elif [ $percentage -gt 39 ] && [ $percentage -le 50 ]
  then symbol="\uf57c" ; color='%F{yellow}' ;

  elif [ $percentage -gt 49 ] && [ $percentage -le 60 ]
  then symbol="\uf57d" ; color='%F{blue}' ;

  elif [ $percentage -gt 59 ] && [ $percentage -le 70 ]
  then symbol="\uf57e" ; color='%F{blue}' ;

  elif [ $percentage -gt 69 ] && [ $percentage -le 80 ]
  then symbol="\uf57f" ; color='%F{blue}' ;

  elif [ $percentage -gt 79 ] && [ $percentage -le 90 ]
  then symbol="\uf580" ; color='%F{blue}' ;

  elif [ $percentage -gt 89 ] && [ $percentage -le 99 ]
  then symbol="\uf581" ; color='%F{blue}' ;

  elif [ $percentage -gt 98 ]
  then symbol="\uf578" ; color='%F{green}' ;

  fi
  if [ $charging = "true" ];
  then color='%F{green}'; if [ $percentage -gt 98 ]; then symbol='\uf584'; fi
  fi
  
  #echo -n "%{$color%}$percentage%% %{$color%}$symbol" ;
  p10k segment -t $percentage%% -i $symbol -f $color -b clear;

}
`

A few weeks ago it stopped working. I noticed that the 'echo' command stop working and I changed it to 'p10k segment' command.

In that function the _color_ and _symbol_ change depending on battery level and that is why i set variables which then I want to use in 'p10k segment' command .

**Comment by romkatv** [comment]
Powerlevel10k has a builtin `battery` prompt segment. It'll look similar to yours with the following configuration options:

```zsh
# Show battery in red when it's below this level and not connected to power supply.
typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=red
# Show battery in green when it's charging.
typeset -g POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=green
# Show battery in blue when not connected to power supply.
typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=blue
# Show battery in green when fully charged.
typeset -g POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND=green
# Battery pictograms going from low to high level of charge.
typeset -g POWERLEVEL9K_BATTERY_STAGES=$'\uf579\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'
# Pictogram to show when the battery is fully charged and connected to power supply.
typeset -g POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_EXPANSION=$'\uf584'
# Don't show the remaining time to charge/discharge.
typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
```

The implementation in Powerlevel10k is much faster than in your `prompt_battery_level`.

**Comment by krzyhon** [comment]
Great! It works! Thanks.

But i have another function to display WIFI signal strength. It is built in the same manner as for battery. Is a builtin prompt segment for wifi?

**Comment by romkatv** [comment]
Not yet but I can implement it. Could you post your wifi signal strength function here?

**Comment by krzyhon** [comment]
`  local signal=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | grep agrCtlRSSI | awk '{print $2}' | sed 's/-//g')
  local noise=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | grep agrCtlNoise | awk '{print $2}' | sed 's/-//g')
`
It works on Mac OS 10.14

**Comment by romkatv** [comment]
Can you post the function you are using?

**Comment by krzyhon** [comment]
Sure, sorry ;)

`prompt_wifi_signal(){
  #source on quality levels - http://www.wireless-nets.com/resources/tutorials/define_SNR_values.html
  #source on signal levels  - http://www.speedguide.net/faq/how-to-read-rssisignal-and-snrnoise-ratings-440
  local signal=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | grep agrCtlRSSI | awk '{print $2}' | sed 's/-//g')
  local noise=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I | grep agrCtlNoise | awk '{print $2}' | sed 's/-//g')

  local SNR=0
  if [[ $noise -ne 0 ]] ;
    then SNR=$(bc <<<"scale=2; $signal / $noise") ;
  fi

  #local net=$(curl -D- -o /dev/null -s http://www.google.com | grep HTTP/1.1 | awk '{print $2}')
  local net=200
  local color='%F{yellow}'
  local symbol="\uf197"

  # Excellent Signal (5 bars)
  if [[ ! -z "${signal// }" ]] && [[ $SNR -gt .40 ]] ; 
    then p10k segment -t $'\uf1eb' -f green -b clear; # color='%F{green}' ; symbol="\uf1eb" ;
  fi

  # Good Signal (3-4 bars)
  if [[ ! -z "${signal// }" ]] && [[ ! $SNR -gt .40 ]] && [[ $SNR -gt .25 ]] ; 
    then p10k segment -t $'\uf1eb' -f blue -b clear; # color='%F{blue}' ; symbol="\uf1eb" ;
  fi

  # Low Signal (2 bars)
  if [[ ! -z "${signal// }" ]] && [[ ! $SNR -gt .25 ]] && [[ $SNR -gt .15 ]] ; 
    then p10k segment -t $'\uf1eb' -f yellow -b clear; # color='%F{yellow}' ; symbol="\uf1eb" ;
  fi

  # Very Low Signal (1 bar)
  if [[ ! -z "${signal// }" ]] && [[ ! $SNR -gt .15 ]] && [[ $SNR -gt .10 ]] ; 
    then p10k segment -t $'\uf1eb' -f red -b clear; # color='%F{red}' ; symbol="\uf1eb" ;
  fi

  # No Signal - No Internet
  if [[ ! -z "${signal// }" ]] && [[ ! $SNR -gt .10 ]] ; 
    then p10k segment -t $'\uf011' -f red -b clear; # color='%F{red}' ; symbol="\uf011";
  fi

  if [[ -z "${signal// }" ]] && [[ "$net" -ne 200 ]] ; 
    then p10k segment -t $'\uf011' -f red -b clear; # color='%F{red}' ; symbol="\uf011" ;
  fi

  # Ethernet Connection (no wifi, hardline)
  if [[ -z "${signal// }" ]] && [[ "$net" -eq 200 ]] ; 
    then p10k segment -t $'\uf197' -f blue -b clear; # color='%F{blue}' ; symbol="\uf197" ;
  fi

  #echo -n "%{$color%}$symbol " # \f1eb is wifi bars
  #p10k segment -t $'\uf1eb' -f green -b clear;
}`

**Comment by romkatv** [comment]
Thanks.

Note that there is no such color as `clear`. If you want to have transparent background, *don't pass `-b` at all*.

**Comment by romkatv** [comment]
I opened https://github.com/romkatv/powerlevel10k/issues/209 to implement `wifi_signal` in powerlevel10k. I'm closing this issue as I believe currently everything works fine for you.

**Comment by krzyhon** [comment]
Yes, thanks.

**Comment by krzyhon** [comment]
Hello once again!
Is it possible to set the background color to transparent for the builtin prompt battery segment?

**Comment by romkatv** [comment]
> Hello once again!
> Is it possible to set the background color to transparent for the builtin prompt battery segment?

Yes, just like with any prompt segment.

```zsh
POWERLEVEL9K_BATTERY_BACKGROUND=
```

P.S.

Have you used the p10k configuration wizard? If not, type `p10k configure`. Run it a few times to see different styles. If you like the results, open `~/.p10k.zsh` and uncomment extra segments that you want (such as `battery`). You might also want to move segments around (e.g., move `battery` to the first prompt line, or move it to the left prompt). If you don't like what you get from `p10k configure`, simply `rm ~/.p10k.zsh` and you are back to your prompt config.

**Comment by krzyhon** [comment]
No I haven't. I configured all manually. But I will try. 
Thanks.

**Comment by horseinthesky** [comment]
I more question regarding battery: is there a way to have the following behavior in terms of color?:
1) Chaged/charging - green
2) Disconnected high - green
3) Disconnected average - yellow
4) Disconnected low - red

I've played with `p10k configure` and there is a `LOW_THRESHOLD` level but no `HIGH_THRESHOLD`.

**Comment by romkatv** [comment]
@horseinthesky Please open a new issue. It's just a few more seconds compared to commenting on unrelated issues but it has several benefits such as not spamming other people and allowing other users to search through issues effectively.

**Comment by romkatv** [comment]
> I opened #209 to implement `wifi_signal` in powerlevel10k. I'm closing this issue as I believe currently everything works fine for you.

@krzyhon

I've implemented `wifi` segment. See https://github.com/romkatv/powerlevel10k/issues/209#issuecomment-581355715. Please give it a try.

**Comment by krzyhon** [comment]
@romkatv 

It works, thank you.

**Comment by romkatv** [comment]
> It works, thank you.

Thanks for verifying!
