### ISSUE TITLE
Change directory in MC (Midnight Commander)

### ISSUE THREAD

**Issue by andreyugolnik** [romkatv/powerlevel10k#2080]
Something went wrong. I recently switched to zsh + oh my zsh + powerlevel10k and ran into a problem I couldn't solve.

How to play:

1. Change directory in MC to something. In my case, switching can take a long time (sometimes almost a few seconds).
2. Press Ctrl+O.
3. Press Enter. The directory has changed to something else (such as the home directory).
4. Press Ctrl+O again. MC shows the directory from point 3.

**Comment by andreyugolnik** [comment]
Hm. MC works fine without any problems with bash under Linux and macOS.

**Comment by romkatv** [comment]
Powerlevel10k also works fine without MC.

**Comment by rozhok** [comment]
I have the same issue. MC responsiveness is super slow when running under the zsh+powerlevel10k comparing to the bare-bones shell.
