### ISSUE TITLE
FEATURE REQUEST: Persist command_execution_time when transient prompt is enabled

### ISSUE THREAD

**Issue by jck** [romkatv/powerlevel10k#2081]
similar to this: https://github.com/romkatv/powerlevel10k/issues/1601

**Comment by romkatv** [comment]
This is already supported but you'll need to make changes to `~/.p10k.zsh` by hand.

See examples:

- https://github.com/romkatv/powerlevel10k/issues/1705
- https://github.com/romkatv/powerlevel10k/issues/917
- https://github.com/romkatv/powerlevel10k/issues/1277
