### ISSUE TITLE
Prompts are messed up

### ISSUE THREAD

**Issue by ZoltanPrime** [romkatv/powerlevel10k#2082]
I'm not sure if this is just a me problem or if it's a bug with the p10k prompts themselves, but I'm going to share this just in case.

The chevron at the end of the prompt is very large for some reason, the prompt separators, heads, and tails, are enlarged and have obvious seams, and some of the icons, particularly the distro icon, are a little small.  Increasing the font size does make the icon larger, but it also obviously makes the font and the entire prompt larger.  I've attached some photos to point out what I'm talking about.

![p10k-issue-1](https://user-images.githubusercontent.com/114794759/200161264-f6387295-5df6-4950-a866-a04f43fbce77.png)
![p10k-issue-2](https://user-images.githubusercontent.com/114794759/200161267-112f97b5-41fc-4e7a-ab36-68de45c0a8a6.png)
![p10k-rainbow-separators](https://user-images.githubusercontent.com/114794759/200161272-fff49682-86cb-4a45-a873-fdaa7619f90b.png)
![p10k-small-icons](https://user-images.githubusercontent.com/114794759/200161275-f7636069-3dd6-442c-aa49-30d92c4a2984.png)

**Comment by romkatv** [comment]
> The chevron at the end of the prompt is very large for some reason, the prompt separators, heads, and tails, are enlarged and have obvious seams

See https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols.

> some of the icons, particularly the distro icon, are a little small.

That's how your font renders them. Try a different font. E.g., this: https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k
