### ISSUE TITLE
Cannot select Prompt Separators in the Configuration wizard.

### ISSUE THREAD

**Issue by parkgang** [romkatv/powerlevel10k#2084]
```
Windows@11 for WSL2
zsh 5.9 (x86_64-pc-linux-gnu)
Windows Terminal 1.15
```

![image](https://user-images.githubusercontent.com/63892989/200218985-588ee9d1-1987-47bb-9758-2819ebf907f9.png)

![image](https://user-images.githubusercontent.com/63892989/200229111-50edb82f-f156-4eab-b52c-692744612c89.png)

When setting the theme wizard in the WSL2 environment, there was no question asking whether special characters are visible without breaking, or what to do with Prompt Separators.

So I can only use the flat settings like below, do you know why it wasn't shown in the wizard?

All fonts related to MesloLGS NF have been downloaded.

I've also read the troubleshooting section, but I didn't find any issues with missing icon display settings like Prompt Separators, although I saw some prompt styles missing in the configuration wizard steps.

**Comment by parkgang** [comment]
I was able to solve the problem myself, it was a locale issue.

In the same way as before, when configuring `powerlevel10k` in the `WSL` environment, there were many experiences and articles that worked intentionally without changing the locale, so I did not doubt the locale.

If I add the setting below to my `.zshrc` , it works as intended.

```shell
export LANG="en_US.UTF-8"
```

For reference, the difference between before and after setting the locale is as follows.

| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/63892989/200231090-b19cd4de-db5c-4782-ace4-2a2b6300a7b3.png) | ![image](https://user-images.githubusercontent.com/63892989/200231099-8f14a7b1-0c2e-4018-91dc-6b7747876607.png) |

**Comment by romkatv** [comment]
C.UTF-8 works fine for me on WSL.

**Comment by romkatv** [comment]
Can you confirm that running `p10k configure` with your current settings shows the diamond question on the first screen and that after manually running `export LC_ALL=C.UTF-8` the next `p10k configure` does NOT show the diamond on the first screen?

If this is so, what is the output of the following command when your locale is C.UTF-8?

```zsh
zmodload zsh/langinfo && print -r -- ${langinfo[CODESET]}
```

**Comment by parkgang** [comment]
Wenn das Gebietsschema auf `C.UTF-8` eingestellt ist und ein beliebiger Befehl in die Shell eingegeben wird, tritt der folgende Fehler auf.

![image](https://user-images.githubusercontent.com/63892989/200442172-eaa6629e-fdf2-4c41-985b-de8a52572d7a.png)

> If this is so, what is the output of the following command when your locale is C.UTF-8?
>
> ``` 
> zmodload zsh/langinfo && print -r -- ${langinfo[CODESET]}
> ```

Beim Aufruf wird `ANSI_X3.4-1968` ausgegeben.

![image](https://user-images.githubusercontent.com/63892989/200443145-1b88ad29-3838-42a6-a0ef-a4f62228594b.png)

If it is set to `en_US.UTF-8`, the command you mentioned will come out in `UTF-8`.

![image](https://user-images.githubusercontent.com/63892989/200442892-42a0ef68-540d-4b47-96d2-279c93c2bf70.png)

**Comment by parkgang** [comment]
I want to output the time displayed by powerlevel10k according to my environment locale.

Applying a locale other than `en_US.UTF-8` causes a problem, so I'll open the issue again.

**Comment by romkatv** [comment]
> > [...] what is the output of the following command when your locale is C.UTF-8?
> > ```
> > zmodload zsh/langinfo && print -r -- ${langinfo[CODESET]}
> > ```
> 
> Beim Aufruf wird `ANSI_X3.4-1968` ausgegeben.
> 
> ![image](https://user-images.githubusercontent.com/63892989/200443145-1b88ad29-3838-42a6-a0ef-a4f62228594b.png)

This is the culprit of the problem. The locale called "C.UTF-8" on your machine isn't in fact a UTF-8 locale. At least zsh doesn't think that it is. You can reproduct this issue without using powerlevel10k. Here's how:

```zsh
zsh -fc 'export LC_ALL=C.UTF-8 && zmodload zsh/langinfo && print -r -- ${langinfo[CODESET]}'
```

The expected output of this command is "UTF-8" but on your machine the output is "ANSI_X3.4-1968". If you are using a stock operating system without manual changes to any relevant parts, please report this bug against your operating system.
