### ISSUE TITLE
Console output during zsh initialization detected.

### ISSUE THREAD

**Issue by CodingArctic** [romkatv/powerlevel10k#2085]
Hi, I've just installed powerlevel10k, but when I run my terminal I get this message.

```text
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --
```

I've tried following the instructions to do the recommended option, but the link takes me to a wiki page that really doesn't explain to me how to change ~/.zshrc in a way that will stop this from happening. I was just wondering if someone could tell me in which way I should change the file?

**Comment by romkatv** [comment]
> `-- console output produced during zsh initialization follows --`

Is there anything in the output after this line?

If not, could you attach your `.zshrc`?

**Comment by CodingArctic** [comment]
> 

This is what follows:
`/home/arctic/.zshrc:source:347: no such file or directory: /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme`

I've put the contents of my .zshrc on [this](https://pastebin.com/8VKcffsn) pastebin if that'd help.

**Comment by romkatv** [comment]
> This is what follows: `/home/arctic/.zshrc:source:347: no such file or directory: /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme`

That's the actual error message. Everything that precedes it essentially says: "Look, you have errors! It's bad!". So you need to fix this error. The easiest way is to delete line 347 of `~/.zshrc`. This line is trying to source a file that doesn't exist. The only effect of this line is an error message.

**Comment by CodingArctic** [comment]
> > This is what follows: `/home/arctic/.zshrc:source:347: no such file or directory: /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme`
> 
> That's the actual error message. Everything that precedes it essentially says: "Look, you have errors! It's bad!". So you need to fix this error. The easiest way is to delete line 347 of `~/.zshrc`. This line is trying to source a file that doesn't exist. The only effect of this line is an error message.

Got it, thank you! Fixed now.
