### ISSUE TITLE
Error "job table full or recursion limit exceeded" in VSCode integrated terminal.

### ISSUE THREAD

**Issue by vinibortoletto** [romkatv/powerlevel10k#2086]
When I try to open a directory from VSCode integrated terminal I get the error `job table full or recursion limit exceeded` and the theme is not applied. And it only happens when Powerlevel10k theme is enabled, others Oh My Zsh themes works fine.

![Screenshot from 2022-11-13 15-13-54](https://user-images.githubusercontent.com/47364504/201537615-14f4ec59-cf80-4b38-9bf3-6cb849e320af.png)
![Screenshot from 2022-11-13 15-14-13](https://user-images.githubusercontent.com/47364504/201537617-17b838a3-97fe-4e02-b148-d48431fce689.png)

**Comment by romkatv** [comment]
This looks like a bug in vscode. Please file an issue against it and post a link to it here.

**Comment by vinibortoletto** [comment]
https://github.com/microsoft/vscode/issues/166303
