### ISSUE TITLE
Frame colors are all the same for powerlevel10k rainbow

### ISSUE THREAD

**Issue by SehiiRohoza** [romkatv/powerlevel10k#2087]
Hello,

Today I tried powerlevel10k rainbow theme but noticed that Frame colors are the same despite if you choose Lightest, Light, Dark and Darkest.  I tried and few and found no difference at all.  Furthermore, it looks quite different if you compare to the preview here https://github.com/romkatv/powerlevel10k. 

How to reproduce:
1. Run `p10k configure`
2. Select `rainbow`
3. Try Lightest, Light, Dark and Darkest.

**Comment by romkatv** [comment]
Can you post a screenshot that shows frames with colors that are supposed to be different but aren't?

**Comment by SehiiRohoza** [comment]
Sure, pls find screenshots attached:
- how it looks:
![issue](https://user-images.githubusercontent.com/58945782/201548563-7aaf7bac-71ad-4187-856b-5b6f3257d701.png)
- what is expected:
![expected](https://user-images.githubusercontent.com/58945782/201548565-e1b48272-0a43-4bc4-b02d-ff259e4a3cdd.png)

**Comment by romkatv** [comment]
These colors are not the same.

**Comment by SehiiRohoza** [comment]
I see no difference, but maybe it's something wrong with me.

Could you please tell me how can I get the same appearance as at the example on the second screenshot?

**Comment by romkatv** [comment]
Which one? The screenshot has two prompts.

**Comment by SehiiRohoza** [comment]
> Which one? The screenshot has two prompts.

As for me colors on the example are the same, and difference only in options. I want to have same light blue background for the path.

**Comment by romkatv** [comment]
> As for me colors on the example are the same, and difference only in options.

Which example? What do you mean by options?

On [this screenshot](https://user-images.githubusercontent.com/58945782/201548563-7aaf7bac-71ad-4187-856b-5b6f3257d701.png) the four prompts have different frame colors. Frame is the thin line to the left and right of prompt.

> I want to have same light blue background for the path.

See https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors and https://github.com/romkatv/powerlevel10k#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style.

**Comment by SehiiRohoza** [comment]
Let me change my question. Which option from the 1st screenshot provide me with the same color scheme as second prompt on the 2nd screenshot?

**Comment by romkatv** [comment]
None. The only choice there is frame color.

**Comment by romkatv** [comment]
See also https://github.com/romkatv/powerlevel10k#how-were-these-screenshots-and-animated-gifs-created

**Comment by SehiiRohoza** [comment]
Thanks! It's clear now!

**Comment by romkatv** [comment]
I added a hint pointing to the frame when asking for frame color.

![image](https://user-images.githubusercontent.com/1282067/201671465-65efac99-d4a4-45b3-942f-0c55020f1a21.png)

See top-right. Hopefully this will help people who get confused by this question.
