### ISSUE TITLE
Question: What Triggers the Git Brand Icon to Display?

### ISSUE THREAD

**Issue by aj-cruz** [romkatv/powerlevel10k#2089]
When I clone other people's repos I see the GitHub icon next to the git/branch icon, but every single one of my own GitHub repos shows  the text "GIT" next to the branch icon instead of the GitHub icon.  
It seems to be something in the .git folder, but I can't figure out what it is exactly.

**Comment by romkatv** [comment]
If the remote is on github.com, you'll see github logo.

**Comment by aj-cruz** [comment]
thanks, does it have to be a public repo then?

**Comment by romkatv** [comment]
No, just on github.com. Try it. Create a branch, configure a remote and point it to github.com. You'll get the github logo. Or simply clone any repo from github.

**Comment by aj-cruz** [comment]
In that case something isn't working right. All my repos are on GitHub, but they're all private. Actually, I have one repo that is a public fork that has a hotfix branch I created, that one doesn't render the icon either. However, repos I clone from other people render the icon.

**Comment by romkatv** [comment]
> All my repos are on GitHub, but they're all private.

Please try it again. Clone any of your repos and check whether the icon is showing.

>  I have one repo that is a public fork that has a hotfix branch I created, that one doesn't render the icon either.

My guess is that your branch doesn't have an upstream. Try running `git push` while your branch is active and see what happens. If it tells you there is no upstream, then this is it. The icon is telling you the same thing.

**Comment by aj-cruz** [comment]
Ah I see. Ya when I git push I get:
```
fatal: The current branch eos-vlan-fix has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin eos-vlan-fix
```
I'll fix that. Thank you for the responses I appreciate it.

**Comment by romkatv** [comment]
You are welcome.

**Comment by romkatv** [comment]
Basically github logo => `git push` will push to github.com.
