### ISSUE TITLE
[feature] Add wifi_signal prompt

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#209]
See https://github.com/romkatv/powerlevel10k/issues/208#issuecomment-529478357 for macOS implementation.

**Comment by Hobadee** [comment]
FWIW, here is my custom WiFi prompt from PL9k.  It *should* also work on *NIX, but I never actually tested it there, just stole from some other *NIX users and bolted together with my OSX config.

``` zsh
if [[ $OSTYPE == darwin* ]]; then
    zsh_wifi_signal(){
        local output=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I)
        local airport=$(echo $output | grep 'AirPort' | awk -F': ' '{print $2}')

        if [ "$airport" = "Off" ]; then
                local color='%F{black}'
                echo -n "%{$color%}Wifi Off"
        else
                local ssid=$(echo $output | grep ' SSID' | awk -F': ' '{print $2}')
                local speed=$(echo $output | grep 'lastTxRate' | awk -F': ' '{print $2}')
                local color='%F{green}'

                [[ $speed -gt 100 ]] && color='%F{green}'
                [[ $speed -lt 50 ]] && color='%F{red}'

                echo -n "%{$color%}$speed Mbps \uf1eb%{%f%}" # removed char not in my PowerLine font
        fi
    }
elif [[ -x $(command -v nmcli) ]]; then
    zsh_wifi_signal(){
        local signal=$(nmcli device wifi | grep yes | awk '{print $8}')
        local color='%F{yellow}'
        [[ $signal -gt 75 ]] && color='%F{green}'
        [[ $signal -lt 50 ]] && color='%F{red}'
        echo -n "%{$color%}\uf230  $signal%{%f%}" # \uf230 is 
    }
else
    zsh_wifi_signal(){
        # No WiFi or no way to find WiFi signal.  Null function.
    }
fi
```

**Comment by romkatv** [comment]
This is done. The new segment is called `wifi`. It's configured in `~/.p10k.zsh` generated by `p10k configure` but commented out by default. It's very fast.

By default it uses the same color and icon regardless of signal strength and displays wireless transmit rate in megabits per second.

![image](https://user-images.githubusercontent.com/1282067/73647283-73721700-467b-11ea-9009-a8066b5fbdeb.png)

You can also configure it to use different colors and/or icons depending on signal strength (bars).

```zsh
# Wifi colors and icons for different signal strength levels (low to high).
typeset -g my_wifi_fg=(68 68 68 68 68)                           # <-- change these values
typeset -g my_wifi_icon=('WiFi' 'WiFi' 'WiFi' 'WiFi' 'WiFi')     # <-- change these values

typeset -g POWERLEVEL9K_WIFI_CONTENT_EXPANSION='%F{${my_wifi_fg[P9K_WIFI_BARS+1]}}$P9K_WIFI_LAST_TX_RATE Mbps'
typeset -g POWERLEVEL9K_WIFI_VISUAL_IDENTIFIER_EXPANSION='%F{${my_wifi_fg[P9K_WIFI_BARS+1]}}${my_wifi_icon[P9K_WIFI_BARS+1]}'
```

The following parameters are accessible within the expansions:

| Parameter               | Meaning                                                                                  |
|-------------------------|------------------------------------------------------------------------------------------|
| `P9K_WIFI_SSID`         | service set identifier, a.k.a. network name                                              |
| `P9K_WIFI_LINK_AUTH`    | authentication protocol such as "wpa2-psk"                                               |
| `P9K_WIFI_LAST_TX_RATE` | wireless transmit rate in megabits per second                                            |
| `P9K_WIFI_RSSI`         | signal strength in dBm, from -120 to 0                                                   |
| `P9K_WIFI_NOISE`        | noise in dBm, from -120 to 0                                                             |
| `P9K_WIFI_BARS`         | signal strength in bars, from 0 to 4 (derived from `P9K_WIFI_RSSI` and `P9K_WIFI_NOISE`) |

If you want to display SSID in prompt, put `$P9K_WIFI_SSID` somewhere in `POWERLEVEL9K_WIFI_CONTENT_EXPANSION`.

All parameters except `P9K_WIFI_BARS` are extracted from the output of the following command:

```zsh
/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I
```

Please give it a try and let me know whether it works for you.

**Comment by maxzinkus** [comment]
For `nmcli` version 1.20.4, this doesn't work. Here's a header and an example line of `nmcli device wifi` output:

```
IN-USE  SSID          MODE   CHAN  RATE        SIGNAL  BARS  SECURITY
*       REDACTED      Infra  149   405 Mbit/s  68      ▂▄▆_  WPA2
```

**Comment by romkatv** [comment]
@maxzinkus I implemented it only on macOS. I don't have a device where `nmcli` outputs anything useful and I was unable to find enough sample outputs to fake this tool for local development.

If you have the knowledge and the ability to add `nmcli` support, a PR would be most welcome.

**Comment by maxzinkus** [comment]
I can add it, but it seems like it’ll be pretty version-fragile. Should I guard it with an os check (e.g. `Ubuntu`), an os+version check (e.g. `Ubuntu 19.10`), or an `nmcli` version check?

**Comment by romkatv** [comment]
> I can add it, but it seems like it’ll be pretty version-fragile.

In this case let's not add it.

The state of WiFi connection is not tied to a shell session. It exists and changes independently. It can (and usually does) change when you aren't typing anything. It's useful to see WiFi state when you aren't working in terminal. All this implies that it's better to place WiFi state indicator on the system level (e.g., in task bar) rather than in prompt. The primary function of `wifi` prompt segment is thus decorative.

I'm fine with having decorative prompt segments in powerlevel10k (the configuration wizard can enable two of them if you indicate that you want them) but only if they are likely to be popular and not too cumbersome to support. `wifi` segment on Linux doesn't seem to clear the bar. No one's asked for it yet (no one has asked for `wifi` on macOS either; I've filed this feature request myself), which hints at lack of demand. Your suggestion that an implementation of `wifi` segment on top of `nmcli` may be fragile makes me wary of potential issues, which I won't be able to debug as I have no access to a machine where `nmcli` works.

**Comment by romkatv** [comment]
Timed out waiting for anyone to try the new segment. Closing the issue.
