### ISSUE TITLE
P10k command line is missing symbols (right part) when Unicode

### ISSUE THREAD

**Issue by psnajdr** [romkatv/powerlevel10k#2091]
Hi, I am using p10k on a successfully migrated Macbook Pro M1. Using the same config on my old machine, but in this case, some symbols are missing when I select Unicode while configuring p10k

<img width="775" alt="image" src="https://user-images.githubusercontent.com/118261778/201887176-262fe2fd-a0a4-4168-aac7-1d00812d9e21.png">

when I use ASCII, it works because it´s not using symbols.

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
locale && print -r -- ${langinfo[CODESET]} && typeset -pm '*POWERLEVEL9K_STATUS_*'
```

**Comment by psnajdr** [comment]
LANG="C.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
UTF-8
typeset -i _POWERLEVEL9K_STATUS_OK=1
typeset _POWERLEVEL9K_STATUS_OK_BACKGROUND=0
typeset POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='???'
typeset -i _POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=0
typeset POWERLEVEL9K_STATUS_ERROR=true
typeset POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=3
typeset POWERLEVEL9K_STATUS_ERROR_FOREGROUND=3
typeset _POWERLEVEL9K_STATUS_ERROR_FOREGROUND=3
typeset _POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='???'
typeset _POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=1
typeset POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=1
typeset POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1
typeset _POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='???'
typeset _POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1
typeset _POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='???'
typeset -i _POWERLEVEL9K_STATUS_OK_PIPE=1
typeset POWERLEVEL9K_STATUS_OK_BACKGROUND=0
typeset POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset -i _POWERLEVEL9K_STATUS_SHOW_PIPESTATUS=1
typeset POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='???'
typeset _POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
typeset _POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=3
typeset -i _POWERLEVEL9K_STATUS_ERROR_PIPE=1
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=3
typeset POWERLEVEL9K_STATUS_OK=true
typeset -i _POWERLEVEL9K_STATUS_CROSS=0
typeset -i _POWERLEVEL9K_STATUS_VERBOSE=1
typeset _POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0
typeset -i _POWERLEVEL9K_STATUS_ERROR=1
typeset _POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=1
typeset -i _POWERLEVEL9K_STATUS_ERROR_SIGNAL=1
typeset _POWERLEVEL9K_STATUS_OK_FOREGROUND=2
typeset POWERLEVEL9K_STATUS_OK_PIPE=true
typeset _POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='???'
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
typeset -i _POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=0
typeset POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
typeset POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
typeset _POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='???'
typeset _POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=3
typeset POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='???'
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='???'
typeset POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='???'
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=1
typeset POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0
typeset -i _POWERLEVEL9K_STATUS_HIDE_SIGNAME=0
typeset POWERLEVEL9K_STATUS_OK_FOREGROUND=2
typeset -i _POWERLEVEL9K_STATUS_EXTENDED_STATES=1
typeset POWERLEVEL9K_STATUS_EXTENDED_STATES=true

**Comment by psnajdr** [comment]
One hint: until I enable "context" on the left part, everything works. When I enable context on the left, remove it from the right and comment out the line for showing context all the time, it stops working.

**Comment by romkatv** [comment]
There is something in your zsh rc files that sets your locale to `C`. You need to find it and get rid of it. If you cannot find it, you might be able to work around this by adding the following line all over the place in `~/.zshrc`.

```zsh
export LC_ALL=C.UTF-8
```

Note that this is a last resort measure that you should only undertake if you cannot understand what your zsh rc files are doing. The right fix is to get rid of the faulty line(s) that modify locale.

**Comment by psnajdr** [comment]
After configure and before enabling "context"  

<img width="769" alt="image" src="https://user-images.githubusercontent.com/118261778/201900614-cd44ba8c-df8b-42b6-a1f8-11e330fe8451.png">
