### ISSUE TITLE
Resizing issue.

### ISSUE THREAD

**Issue by TheRadioDept** [romkatv/powerlevel10k#2092]
Hello. I have a resizing issue after enabling powerlevel10k. I saw the same issue was opened before, and I saw a patch version, but how do I apply this patch? 
Sorry if this is stupid question, but I honestly have no idea how to do that. 

Thanks in advance.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
