### ISSUE TITLE
_p9k_preexec2:2: scalar parameter _p9k__timer_start created globally in function _p9k_preexec2

### ISSUE THREAD

**Issue by ratijas** [romkatv/powerlevel10k#2094]
This warning appears with a special zsh option `set -o warncreateglobal`.

I see that this variable is supposed to be defined somewhere in other helper function `_p9k_init_vars` few hundred lines below, but apparently it gets referenced before that?

**Comment by ratijas** [comment]
Set this option in zshrc before loading p10k, I guess. My setup is https://github.com/ratijas/dotfiles with `rcup -B orange -t zsh`, if that would help

**Comment by romkatv** [comment]
> Set this option in zshrc before loading p10k, I guess.

Here's what I've tried:

1. Run this:
   ```zsh
   docker run -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 -it --rm alpine sh -uec '
     apk add git zsh nano vim
     git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
     cp ~/powerlevel10k/config/p10k-lean-8colors.zsh ~/.p10k.zsh
     cat >~/.zshrc <<END
   setopt warn_create_global
   source ~/.p10k.zsh
   source ~/powerlevel10k/powerlevel10k.zsh-theme
   END
     exec zsh'
   ```
2. Run `true`.

Result: no warnings.

> My setup is https://github.com/ratijas/dotfiles

Is every file and line required to reproduce the problem?

**Comment by ratijas** [comment]
Hmm, actually, it only happens if I'm trying to `source ~/.zshrc` from a non-interactive script (which I'm doing to load all aliases, 'cause I don't know any better way)

**Comment by romkatv** [comment]
A better way is to use scripts instead of aliases. Create a directory (commonly `~/bin`), and create executable files there, and add the directory to `PATH` in `~/.zshenv`:

```zsh
typeset -gaU path=(~/bin $path)
```

**Comment by ratijas** [comment]
> Is every file and line required to reproduce the problem?

eh, of course not. But if testing is in Docker anyway, maybe (just maybe) it would something to start with.

> A better way is to use scripts instead of aliases. Create a directory (commonly ~/bin), and create executable files there, and add the directory to PATH in ~/.zshenv:

Thanks, I do have ~/bin in my path, and a bunch of larger scripts there. It has pros and cons. Sure, I can call them from wherever, but OTOH they can't in turn expand just as alises do, so can't stack together etc.

**Comment by romkatv** [comment]
If you really must use aliases from scripts, define then in a separate file and `source` it from scripts and from `~/.zshrc` alike.

Another alternative is to define aliases in `~/.zshenv`. This file is sourced automatically by all instances of zsh, even non-interactive ones (a.k.a. scripts).
