### ISSUE TITLE
Advice needed. Git status indicator for multiple repos

### ISSUE THREAD

**Issue by edshamis** [romkatv/powerlevel10k#2095]
Hi, Roman! As always thank you for your time. I want to add prompt segment showing for each of multiple git repos if it's dirty. I'll highly appreciate if you can guide me how to proceed in an optimal way. I've already had some experience with p10k customizing prompt with your dotfiles-public/private mechanic.

**Comment by romkatv** [comment]
There is no easy way to achieve this. You can try using gitstatus directly or create a periodic background job that invokes `git` for all repos you care about. Once you figure out how to obtain the data, you can display it with a custom prompt segment. See `p10k help segment` for the latter.

**Comment by edshamis** [comment]
So the plan is to set cron job with script to run gitstatusd for each of predefined repos then populate the results in the prompt. Correct? Any caverns?

**Comment by romkatv** [comment]
If you go with a cron job, it's easier to just use plain `git` in it to figure out which repos are dirty. Don't bother with gitstatusd. Write the result to some file. Finally, create a custom prompt segment to show the content of that file.

**Comment by edshamis** [comment]
zsh-async seems promising, I'll look at it. Thanks! I wonder if reading from file will slow down prompt redrawing.

**Comment by romkatv** [comment]
> I wonder if reading from file will slow down prompt redrawing.

If you read a small file like this, it'll be super fast:

```zsh
local content
content=$(</path/to-file)
```
