### ISSUE TITLE
[question] Any method to display time from init process?

### ISSUE THREAD

**Issue by Freed-Wu** [romkatv/powerlevel10k#2096]
Such as

```
❯ ps auwx
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   1104     4 pts/0    Ss   14:38   0:00 /sbin/docker-init -- /bin/bash /pai_bootstrap.sh
...
```

I hope it can display `current time - 14:38`. Because my server's platform only allow me use 3 hours to debug code. If I can see the time from init process, I can know when I must save my code and restart a docker to debug code.

TIA!

**Comment by romkatv** [comment]
Add this to `~/.p10k.zsh`:

```zsh
typeset -g my_init_start_time=${$(ps -p 1 -o start=)## *}

function prompt_my_init_start_time() {
  p10k segment -b yellow -f red -i 'T0' -t "${my_init_start_time//\%/%%}"
}
```

Then add `my_init_start_time` somewhere within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

You can change `T0` to the icon of your liking.

**Comment by Freed-Wu** [comment]
Good!

**Comment by Freed-Wu** [comment]
This is finished:
```zsh
  if [[ $(ps -p 1 -ocmd=) == '/sbin/docker-init '* ]]; then
    typeset -g init_start_time=${$(ps -p 1 -ostart=)## *}
  fi
  function prompt_init_start_time() {
    if [[ $(ps -p 1 -ocmd=) == '/sbin/docker-init '* ]]; then
      p10k segment -b yellow -f red -i ⭐ -t ${(f)$(pdd --sub "$init_start_time")[1]}
    fi
  }
```

![screen-2022-11-20-18-43-04](https://user-images.githubusercontent.com/32936898/202897757-305b5400-cc36-442b-9daa-4e3d36db4549.jpg)

**Comment by romkatv** [comment]
Consider changing it to this:

```zsh
if [[ $(ps -p 1 -ocmd=) == '/sbin/docker-init '* ]]; then
  typeset -g init_start_time=${$(ps -p 1 -ostart=)## *}
  init_start_time=${(f)$(pdd --sub "$init_start_time")[1]}
else
  typeset -g init_start_time=
fi

function prompt_init_start_time() {
  if [[ -n $init_start_time ]]; then
    p10k segment -b yellow -f red -i ⭐ -t "${init_start_time//\%/%%}"
  fi
}
```

This will improve performance by at least 3 orders of magnitude and fix a potential bug with quoting.

**Comment by romkatv** [comment]
Also, it's a *really* bad idea to drop `my_` prefix from my earlier code. Now you cannot safely update powerlevel10k and have to stick with the current version. Any update may break you if I add a prompt segment by the same name.
