### ISSUE TITLE
When link is included in rprompt, extra padding is added.

### ISSUE THREAD

**Issue by danrneal** [romkatv/powerlevel10k#2098]
Links can be added to a prompt like so: gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

However when I add a link to a segment, it adds a bunch of padding to the right (presumably due to non-printing chars).

![Screenshot from 2022-11-21 16-55-21](https://user-images.githubusercontent.com/34819234/203188284-fee8ff16-8be5-41a5-9531-422b39fbf093.png)

Does p10k have a workaround for this?

**Comment by romkatv** [comment]
In zsh, non-printable characters in prompt must be surrounded with `%{..%}`. This isn't specific to powerlevel10k.

**Comment by danrneal** [comment]
Doh.  I knew that.... Thanks for the reminder.
