### ISSUE TITLE
'failed printing to stdout: Broken pipe (os error 32)' when using 'Open in Terminal' in macOS Finder

### ISSUE THREAD

**Issue by hoohugokim** [romkatv/powerlevel10k#2099]
Hi, first of all thank you for this great zsh theme, always so grateful ;) Just wanted to ask about a small caveat:

https://user-images.githubusercontent.com/25841608/203261898-ccfbf652-7ea2-42bb-b8d0-cf3911ba06d0.mov

```
(eval):source:1: no such file or directory: /dev/fd/12source
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1015:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
↑ (error prompt)

So, the error above appears when I use the 'Open in Terminal' feature in macOS Finder app, only when the path is different with the last path used. Other than the prompted error, there is seemingly no issue with the functionality.

Wanted to do the backtracing as the prompt suggests, but could not due to my lack of knowledge in Rust 😞. The environment is as follows:

macOS: 12.6.2 (Monterey)
Terminal: iTerm2 v3.4.18
Other .zshrc setup: Oh My Zsh, zplug, conda (tested one by one, the error only comes when the p10k is fully set up with ~/.p10k.zsh)

Please let me know if there is any more information I need to provide. Thanks!

**Comment by romkatv** [comment]
Please file a bug against iTerm. I don't know what it's doing when you click *Open in Terminal* but it's not what it should be doing. It should change the current directory before executing shell.

**Comment by hoohugokim** [comment]
Hmm... I also tried with default macOS Terminal and [Hyper.is](https://hyper.is) too, and I can reproduce it the same:

![Screen Shot 2022-11-22 at 8 41 20 PM](https://user-images.githubusercontent.com/25841608/203305729-17048417-0a47-46b6-9245-ad59582ded91.png)
![Screen Shot 2022-11-22 at 8 34 24 PM](https://user-images.githubusercontent.com/25841608/203305718-16642704-71c2-4dc4-b953-6c54159d13fa.png)

If 'Open in Terminal' is some quirky macOS-specific feature that is not worth troubleshooting, I will just close the issue :)

**Comment by romkatv** [comment]
Wow, your .zshrc is very confused. It's loading several themes and using several plugin managers. Now that I look at it, I'm thinking the error message comes from starship.

In any case, this cannot possibly be a bug in powerlevel10k, so I'm closing it.
