### ISSUE TITLE
Not showing the correct time in Kali Linux after setting up powerlevel10k & Oh-My-zsh

### ISSUE THREAD

**Issue by febin-mathew** [romkatv/powerlevel10k#2102]
Hello there, i'm facing an issue after setting up powerlevel10k in Kali Linux. 
The system time in Kali is correct as shown in the image below(default system time), but when i set the status "Show Current Time" in p10k configure, It's showing a different time in the terminal.

How do i set this right, to the default system time?

![image](https://user-images.githubusercontent.com/74891320/203896365-1a771855-30a1-4a9d-8cc3-59a72c8a7053.png)

Also I'm unable to change the OS icon in prompt (image of a duck) to Kali/Debian...
I just tried to change the OS icon to ArchLinux as shown below,

typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF303'

but nothing was reflected in the terminal (even after restarting Kali Linux machine).

**Comment by romkatv** [comment]
> The system time in Kali is correct as shown in the image below(default system time), but when i set the status "Show Current Time" in p10k configure, It's showing a different time in the terminal.

Please post a screenshot that show prompt and the output of `date`.

> Also I'm unable to change the OS icon in prompt (image of a duck) to Kali/Debian...

Open `~/.p10k.zsh`, uncomment `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`, set its value to whatever you like, restart zsh with `exec zsh`.

**Comment by febin-mathew** [comment]
> > The system time in Kali is correct as shown in the image below(default system time), but when i set the status "Show Current Time" in p10k configure, It's showing a different time in the terminal.
> 
> Please post a screenshot that show prompt and the output of `date`.
> 
> > Also I'm unable to change the OS icon in prompt (image of a duck) to Kali/Debian...
> 
> Open `~/.p10k.zsh`, uncomment `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`, set its value to whatever you like, save the file, restart zsh with `exec zsh`.

![image](https://user-images.githubusercontent.com/74891320/203987262-92a647c0-6601-4298-99c8-cd826b8d1e1e.png)

The rectangle shown in RED is the system time (06:01 PM), but when i enable "Show Current Time" in p10k configure, it shows a different time in the terminal prompt (07:31 AM (12hr format) - rectangle shown in BLUE).
Shouldn't the time be the same as the system time, ie 06:01 PM

**Comment by febin-mathew** [comment]
> > The system time in Kali is correct as shown in the image below(default system time), but when i set the status "Show Current Time" in p10k configure, It's showing a different time in the terminal.
> 
> Please post a screenshot that show prompt and the output of `date`.
> 
> > Also I'm unable to change the OS icon in prompt (image of a duck) to Kali/Debian...
> 
> Open `~/.p10k.zsh`, uncomment `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`, set its value to whatever you like, save the file, restart zsh with `exec zsh`.

![image](https://user-images.githubusercontent.com/74891320/203993344-9ad604ef-6944-4888-aed6-9449bd8ddf0e.png)

DATE and TIME of Kali is shown in BLUE box. SYSTEM time is shown in RED box. How do i change the time of KALI to match the System Time

**Comment by romkatv** [comment]
Powerlevel10k shows the same time as `date`. It cannot show any other time.

**Comment by febin-mathew** [comment]
> Powerlevel10k shows the same time as `date`. It cannot show any other time.

Yes sir. I've fixed the issue now. 
My timezone was correct in Kali machine. But when i checked it in the terminal the timezone ended up being in another country...
Not sure how.

I changed the timezone to my country via the `sudo timedatectl set-timezone COUNTRY-NAME`
Thank you for the help.
