### ISSUE TITLE
dotnet_version not updating correctly

### ISSUE THREAD

**Issue by jooooel** [romkatv/powerlevel10k#2103]
I'm not really sure how it works, but there seems to be cases where the cached value (`_p9k_cached_cmd_stdout`) of `dotnet_version` doesn't update.

Not sure what matters here, but I'd be happy to give more context as to versions, terminal etc. Currently running iTerm2 on an M1 Mac.

I have multiple versions of .NET installed, the latest is .NET 7. If I go into a directory with a global.json with an older version specified, it still shows .NET 7 as the version. 

`dotnet --version` is giving the expected value, so that's why I'm wondering about the cached value, and how/when that is updated.

**Comment by romkatv** [comment]
What's the output of `whence dotnet`?

**Comment by jooooel** [comment]
`/usr/local/share/dotnet/dotnet`

**Comment by romkatv** [comment]
That's surprising. How do you have multiple versions of dotnet installed and how are you switching between them?

**Comment by jooooel** [comment]
With the later versions of .NET you can have multiple versions installed alongside each other. Exactly how that works, I don't know 🤷. But by default it chooses the latest one. Otherwise I have to override that using a `global.json`

**Comment by romkatv** [comment]
> Otherwise I have to override that using a `global.json`

Can you specify how exactly? Where is this file located? What's the content? How are you modifying it?

**Comment by jooooel** [comment]
I'll try to summarise it with a picture

1. First I'm in a folder where both p10k and `dotnet --version` (correctly) show .NET 7 as the version
2. I go to `/tye` where there is a `global.json` setting the version to .NET 6. p10k still shows .NET 7, but `dotnet --version` correctly shows .NET 6

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/9303280/204130600-e53b1319-7524-4fa9-8309-531157133d64.png">

**Comment by romkatv** [comment]
Thanks for the info. I've pushed a fix. Please give it a try.

**Comment by jooooel** [comment]
It works!

Thank you for the very fast reply and fix! 🎉

**Comment by romkatv** [comment]
Thanks for filing the issue and assisting with fixing it.
