### ISSUE TITLE
Background of the last segment char

### ISSUE THREAD

**Issue by fernandodlhdt** [romkatv/powerlevel10k#2104]
Hello @romkatv,

First, thanks for this awesome project.

I would like to know how would be possible to achieve a filler like a gray bar between left and right elements (snapshot edited to show what I want):

![image](https://user-images.githubusercontent.com/108667997/204256561-f8467b31-bde6-4d0e-9f98-df9125a7f9a7.png)

This is what I achieved so far:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/108667997/204256794-7575a433-0730-4d87-9196-60e5f9be3c25.png">

Is it possible to get rid of the black triangles at both sides?

**Comment by romkatv** [comment]
Try this:

```zsh
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=244
POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='%K{244}\uE0B0%k'
POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%K{244}\uE0B2%k'
```

**Comment by fernandodlhdt** [comment]
Thanks!! Completely forgot about the possibility to change the color of the chars on the go.
