### ISSUE TITLE
Make transient prompt only trim right side?

### ISSUE THREAD

**Issue by ColonelPhantom** [romkatv/powerlevel10k#2105]
I personally prefer not using transient prompts; I dislike seeing my input 'jumping around'. However, it does have benefits in that it gets rid of the resize issue.

As such I think it would be nice if there was an alternative option for the transient prompt that only removes the right side, while keeping the left prompt intact. This way resizing will not have any issues, while behaving more closely to a non-transient prompt.

**Comment by romkatv** [comment]
> I dislike seeing my input 'jumping around'

Use a two-line prompt with `prompt_char`. This way input will have fixed offset.

> Make transient prompt only trim right side?

Try this:

```zsh
POWERLEVEL9K_TRANSIENT_PROMPT=off
p10k-on-pre-prompt()  p10k display '*/right'=show
p10k-on-post-prompt() p10k display '*/right'=hide
```

> This way resizing will not have any issues

If you are referring to https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window, then it won't fix it.

**Comment by ColonelPhantom** [comment]
> Use a two-line prompt with `prompt_char`. This way input will have fixed offset.

Sure, but it will still make the header jump. I recognize that it's quite neat, just not my thing :)

> Try this:
> 
> ```shell
> POWERLEVEL9K_TRANSIENT_PROMPT=off
> p10k-on-pre-prompt()  p10k display '*/right'=show
> p10k-on-post-prompt() p10k display '*/right'=hide
> ```

Works great, thanks!

> If you are referring to https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window, then it won't fix it.

While it's still not perfect (if the prompt line needs to reflow, some minor issues appear), already entered prompts will now remain on one line upon doing some horizontal resizing. So for me, this works around most of the worst issues.
