### ISSUE TITLE
SHOW_ON_COMMAND and ZSH menu bad behavior

### ISSUE THREAD

**Issue by paoll** [romkatv/powerlevel10k#2106]
First, huge thanks for your work, that's very impressive. 

I have an issue when using zsh completion menu and SHOW_ON_COMMAND, with some fields in the menu disappearing. 

On my `.zshrc`, I do have `zstyle ':completion:*' menu select` and I'm using `  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|k|kn|kx|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|argocd'`

https://user-images.githubusercontent.com/14123876/204492335-7fdf5ccb-8c74-4254-b5d7-6355d9dd4966.mov

I don't know how to sort that out while keeping completion menu

**Comment by romkatv** [comment]
It' a bug in zsh: https://www.zsh.org/mla/workers/2019/msg00161.html

**Comment by paoll** [comment]
Thank you very much for your feedback 👍
