### ISSUE TITLE
Slow startup if tmux is on

### ISSUE THREAD

**Issue by huyvohcmc** [romkatv/powerlevel10k#2109]
I wonder if this is a normal behavior, when I have tmux on every time I open a new pane the prompt show up very fast:
```
~/stuff/neovim ❯
```
 but the git branch takes a few seconds to appear:
```
~/stuff/neovim master ❯
```
I use the pure style and already enabled instant prompt ([zshrc config](https://github.com/huyvohcmc/dotfiles/blob/master/zsh/.zshrc)).

OS: macOS Ventura 13.0.1
zsh 5.9 (x86_64-apple-darwin21.3.0)
tmux 3.3a

**Comment by romkatv** [comment]
> I wonder if this is a normal behavior, when I have tmux on every time I open a new pane the prompt show up very fast:
> 
> ```
> ~/stuff/neovim ❯
> ```

Good. You can start typing at that point.

> but the git branch takes a few seconds to appear:
> 
> ```
> ~/stuff/neovim master ❯
> ```

That's normal.

Try the following experiment. Disable powerlevel10k by commenting out these lines in zshrc:

```zsh
source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

Then open a new pane and see how long it takes for prompt to appear.

**Comment by romkatv** [comment]
Have you tried it? Where were the results?

**Comment by huyvohcmc** [comment]
> Have you tried it? Where were the results?

It seems to be the same.

**Comment by romkatv** [comment]
Do I understand it correctly that when you open a new pane without powerlevel10k you see an empty pane for several seconds and then prompt appears?

**Comment by huyvohcmc** [comment]
Yes, it's correct what you say.

**Comment by romkatv** [comment]
Then yes, it's working as intended. Powerlevel10k cannot make your zshrc evaluate faster. It can add prompt quickly so that you can start typing though. That's what [Instant Prompt](https://github.com/romkatv/powerlevel10k#instant-prompt) does.
