### ISSUE TITLE
Error in powerlevel10k theme.

### ISSUE THREAD

**Issue by Future-Flash** [romkatv/powerlevel10k#2110]
Hello! My name is Future-Flash and I love your powerlevel10k zsh theme, but today, when I was doing a distro upgrade, some patched font icons went wrong. After I ran the command "p10k configure" then it show a patched font icons error. So here it is,
![Screenshot from 2022-12-04 21-39-24](https://user-images.githubusercontent.com/107536952/205502035-2f284770-8626-4d16-b48b-29b6fae966b4.png)

Thank you,
From Future-Flash

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render
