### ISSUE TITLE
What does the symbol ? after my branch means?

### ISSUE THREAD

**Issue by MMMMMoris** [romkatv/powerlevel10k#2111]
![image](https://user-images.githubusercontent.com/63332824/205544261-69c90078-0e5d-4201-b64e-a5f5db19536d.png)
It looks strange, well I am new to git and github, perhaps there are something I cannot perceive. Help will be appreciated.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean
