### ISSUE TITLE
Powerlevel10k broken in Pycharm terminal

### ISSUE THREAD

**Issue by nickzorostreb** [romkatv/powerlevel10k#2113]
I've run into an issue with Pycharm in the last three or four versions (2022.x) where Powerlevel10k stops rendering properly:
![Screen Shot 2022-12-07 at 9 58 25 AM](https://user-images.githubusercontent.com/99297355/206229408-36fffa92-1e28-4e4d-94ea-18c7826acfdb.png)

I'm on MacOSX 10.15.7 (Catalina) using Pycharm 2022.3 and Powerlevel10k on master and oh-my-zsh
For Pycharm, I'm using the same terminal font that I'm using in iterm2: MesloLGS NF

I've tried a few things to fix this to no avail:
- `unset ITERM_SHELL_INTEGRATION_INSTALLED && p10k reload` from [Issue 1128](https://github.com/romkatv/powerlevel10k/issues/1128)
- Clearing the p10k files out of `.cache` (that worked for a time but is no longer)
- Setting the Pycharm terminal font to different powerline font

For now, I'm using a different zsh theme when I'm in the Pycharm terminal.  Any help on this would be greatly appreciated.

**Comment by romkatv** [comment]
Please file a bug against pycharm.
