### ISSUE TITLE
EndeavourOS Icon missing

### ISSUE THREAD

**Issue by Pukimaa** [romkatv/powerlevel10k#2114]
I am using EndeavourOS and this theme only shows the default Linux Tux. (See Screenshot)
![Screenshot](https://user-images.githubusercontent.com/58347116/206471319-7940f208-c4bf-4939-bbe7-006c73aa5e12.png)

Here's an svg of the logo:
![EndeavourOS Logo](https://github.com/endeavouros-team/endeavouros-theming/raw/master/EndeavourOS-icon.png)

**EDIT**:
Here's the Icon from Nerd Fonts:  ( `f322`)

**Comment by romkatv** [comment]
If your are using a font that has a glyph for EndeavourOS logo, you can configure Powerlevel10k to display it by setting `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` in `~/.p10k.zsh`.

**Comment by Pukimaa** [comment]
Yes, but I would still want this to be added so I don't have to do it manually.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/pull/2033.
