### ISSUE TITLE
Wrong OS Icon Displayed

### ISSUE THREAD

**Issue by Yuxin-Ren-SZ** [romkatv/powerlevel10k#2115]
I'm running Ubuntu 22.04 on VirtualBox 7.0+ with guest addition installed.

![image](https://user-images.githubusercontent.com/45218090/206625147-958e1e3a-417c-4fbe-8761-9b778861421a.png)

As screenshot shows, it display the icon for Linux but not Ubuntu. However, on another virtual machine that I installed earlier it shows ubuntu icon correctly. How may I fix it?

By the way, is this related to the guest addition installed?

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
typeset -p POWERLEVEL9K_MODE && cat /etc/os-release
```

**Comment by Yuxin-Ren-SZ** [comment]
Thank you very much for your response! Here is the output and screenshot

```
typeset POWERLEVEL9K_MODE=awesome-fontconfig
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
![image](https://user-images.githubusercontent.com/45218090/206871157-e1a4c70d-45fd-4b72-991c-ab298573ee20.png)

**Comment by romkatv** [comment]
When running `p10k configure` you've indicated that you font does not have the necessary icon. If you believe that it actually does, run `p10k configure` again.

**Comment by Yuxin-Ren-SZ** [comment]
So, it should be fixed by reinstall the fonts and config again? (the italic version of font can't be installed)

**Comment by romkatv** [comment]
I don't know whether you need to install and/or change the terminal font but you definitely need to run `p10k configure`.

**Comment by Yuxin-Ren-SZ** [comment]
Thanks a lot, it is fixed now but the way to fix it is quite frastrating:

I keep clicking install for NF itatlic font. It will fail multiple times, but until it does not fail, the p10k config can shows the diamond icon correctly.

**Comment by romkatv** [comment]
You might want to find a bug against your OS.
