### ISSUE TITLE
Feature request: same-branch mode for transient prompt

### ISSUE THREAD

**Issue by mrenvoize** [romkatv/powerlevel10k#2116]
This is an enhancement/feature request.. I love the transient mode. I see there's an option for same-dir to keep the last directory you were in.. Whilst I don't find this useful, I'd love to have a similar feature for keeping the prompt upon changing git branch.. I often quickly checkout another branch to do something then want to go back, and having that 'last branch' info available in the scrollback would be really helpful.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/902#issuecomment-660874958. Instead of `PWD` you would be checking `VCS_STATUS_LOCAL_BRANCH`.

**Comment by mrenvoize** [comment]
Thanks for the info, that's really helpful, :-).
