### ISSUE TITLE
Q: How can I add Sapling support?

### ISSUE THREAD

**Issue by vegerot** [romkatv/powerlevel10k#2117]
I spent the last 45 minutes trying to wrap my head around this source code to do it myself but gave up 😁.  Turns out this is really complicated!

All I want to do is append `$(_scm_prompt)` to my prompt in any directory that contains a `.sl` directory (or its parent does).

The prompt I'm referencing is here https://github.com/facebook/sapling/blob/main/eden/scm/contrib/scm-prompt.sh#L29-L30 .

How can do this?  Thanks!

**Comment by romkatv** [comment]
There are docs: https://github.com/romkatv/powerlevel10k#extensible

Open `~/.p10k.zsh` and add this:

```zsh
function prompt_my_scm() {
  [[ -n ./(../)#.sl(#qN) ]] || return
  local content
  content=$(_scm_prompt) || return
  p10k segment -b yellow -f red -i 'scm' -t "$content"
}
```

Then add `my_scm` anywhere within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

**Comment by romkatv** [comment]
Keep in mind that if `_scm_prompt` is slow, your prompt will be slow. `_scm_prompt` may be *very* slow from a cursory look at its source code. I've never seen it but it seems to show git status info? In this case you shouldn't need it because powerlevel10k has `vcs` that you can configure. It's orders of magnitude faster.

**Comment by vegerot** [comment]
@romkatv _scm_prompt shows [Sapling](https://sapling-scm.com/docs/introduction/) status info.

Instead of adding a new element to the prompt, I was hoping to add Sapling support to the `vcs` prompt

**Comment by romkatv** [comment]
> Instead of adding a new element to the prompt, I was hoping to add Sapling support to the `vcs` prompt

What would be the difference?

**Comment by vegerot** [comment]
@romkatv I'm messing something up here 🤡 

I have 
```zsh
  function my_sapling_status() {
    p10k segment -b yellow -f red -i 'scm' -t "yomomma"
  }

  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    my_sapling_status       # sapling status
    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )
```
but my prompt remains unchanged 
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/5297725/209196134-45d8d527-8a8a-4555-b1ca-ed6af51be996.png">

Even if I do something silly like
```zsh
  function my_sapling_status() {
    reboot
    p10k segment -b yellow -f red -i 'scm' -t "yomomma"
  }

  # The list of segments shown on the left. Fill it with the most important segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    my_sapling_status       # sapling status
    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )
```
nothing happens

**Comment by romkatv** [comment]
The function should be called `prompt_my_sapling_status` (note the prefix `prompt_`).

**Comment by vegerot** [comment]
🤦‍♀️ I figured it out.  It has to be called `prompt_my_sapling_status`.  My bad!

This is easy to miss, so maybe we could more explicitly call this out in `p10k help segments` or in the _extensible_  section in the README

**Comment by romkatv** [comment]
There is one example in `p10k help segment` and another in `~/.p10k.zsh` (search for "example"). Should be enough.
