### ISSUE TITLE
(maybe) miss added big files in gitstatus/bin took too much space

### ISSUE THREAD

**Issue by 0n3W4y7ick3t** [romkatv/powerlevel10k#2118]
More info:
`git clone https://github.com/romkatv/powerlevel10k/` from this repo takes 76MiB disk space,

by run
``` bash
git rev-list --objects --all \
| git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
| awk '/^blob/ {print substr($0,6)}' \
| sort --numeric-sort --key=2 \
| cut --complement --characters=13-40 \
| numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```
I found out there are many big files in `gitstatus/bin` which seem like someone accidently added them:

![image](https://user-images.githubusercontent.com/118800175/206902641-b76318c4-3ac5-4a79-974d-d1a69612d466.png)
Maybe you want to remove these?

**Comment by 0n3W4y7ick3t** [comment]
How I solved this (it just takes 6.1M afterwards and everything works just like as before)
By last command, the file I would like to remove is in `gitstatus/bin`, so I run this command:
```bash
git filter-branch --prune-empty -d /dev/shm/scratch \\
  --index-filter "git rm --cached -rf --ignore-unmatch gitstatus/bin" \\
  --tag-name-filter cat -- --all
```
after that. delete old backup and do a garbage collection:
```bash
rm -rf .git/refs/original/
git reflog expire --expire=now --all
git gc --aggressive --prune=now
```
Lastly,  replace remote repo with local ones: `git push --all --force`, you may want to test it on a temporary repo first.

**Comment by romkatv** [comment]
> More info: `git clone https://github.com/romkatv/powerlevel10k/` from this repo takes 76MiB disk space

Why are you running this command?

**Comment by 0n3W4y7ick3t** [comment]
And I did another test `git clone file:///path/to/old/powerlevel10k path/to/new`, size of the new one is ~4MiB

**Comment by 0n3W4y7ick3t** [comment]
> > More info: `git clone https://github.com/romkatv/powerlevel10k/` from this repo takes 76MiB disk space
> 
> Why are you running this command?

To install this theme

**Comment by romkatv** [comment]
Please follow the installation instructions to install the theme.

**Comment by 0n3W4y7ick3t** [comment]
> Please follow the installation instructions to install the theme.

I'm a idiot, closing this now, sry for the bother lmao.

**Comment by romkatv** [comment]
No harm done.
