### ISSUE TITLE
How can I autocomplete commands and add suggestions?

### ISSUE THREAD

**Issue by akex06** [romkatv/powerlevel10k#2120]
I've seen a tutorial on how to install powerlevel10k with zsh and it says it autocompletes automatically

**Comment by romkatv** [comment]
Powerlevel10k doesn't autocomplete anything. https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by akex06** [comment]
Thanks for the fast response, do you know any way of achieving what I am looking for?

**Comment by romkatv** [comment]
You can google it.
