### ISSUE TITLE
Command history keeps getting pushed up when reducing the window width

### ISSUE THREAD

**Issue by jadin-press** [romkatv/powerlevel10k#2121]
I've attached a screen recording to show what's happening. There seems to be a split-second delay after changing the width where the prompt becomes too long and is forced to wrap to a second line.

https://user-images.githubusercontent.com/64460552/207015687-4518a5c4-ab6f-4991-af1c-2d0debbf7458.mp4

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by jadin-press** [comment]
> https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

Ah I see. Thanks for your response!
