### ISSUE TITLE
remove/disable folder icon in directory prompt

### ISSUE THREAD

**Issue by fav-sheppe** [romkatv/powerlevel10k#2122]
Hi, is there a way to remove the little folder icon in the directory prompt, while also keeping the other icons (lock and home)? I've tried `typeset -g POWERLEVEL9K_FOLDER_ICON=''` in .p10k.zsh but that has not worked for me. And uncommenting `typeset -g POWERLEVEL9K_DIR_CLASSES=()` removed all icons. Thank you.

**Comment by romkatv** [comment]
```zsh
typeset -g POWERLEVEL9K_FOLDER_ICON=
```

**Comment by romkatv** [comment]
Oh, I see that you've tried it and it didn't work. Try again. It does work.
