### ISSUE TITLE
Cannot display normally on code-server of Termux

### ISSUE THREAD

**Issue by MMMMMoris** [romkatv/powerlevel10k#2123]
![Screenshot_2022-12-14-04-01-49-766_com android chrome](https://user-images.githubusercontent.com/63332824/207433093-d3cc4f5c-7474-4ad2-863e-8085cec7c6a1.jpg)
I install termux on my XiaoMi Pad 5 and install ubuntu with proot-distro, also I install code-server on ubuntu, everything looks perfect until I open code-server on my browser. 
The fonts that display normally on Termux cannot display on code-server, and i cannot find out the reason. When I login ubuntu in termux, the fonts display normally as well, however it's just unable to display on browser. Is it because that I didn't install these fonts on my MIUI ? It is not reasonable......

**Comment by romkatv** [comment]
The font used by your browser is independent from any other font.

**Comment by romkatv** [comment]
If you want to change the font in vscode, see https://github.com/romkatv/powerlevel10k/blob/master/font.md

**Comment by MMMMMoris** [comment]
> If you want to change the font in vscode, see https://github.com/romkatv/powerlevel10k/blob/master/font.md

Well, it doen't work, when I change it to MesloLGS NF, nothing happens except the space between letters get bigger. I thought I can quote the fonts like quoting it in css. Is there anyway to solve this?

**Comment by romkatv** [comment]
If you are unable to change the font in vscode, ask for help in places where people ask for help with vscode.

**Comment by MMMMMoris** [comment]
> If you are unable to change the font in vscode, ask for help in places where people ask for help with vscode.
![image](https://user-images.githubusercontent.com/63332824/207440155-f3ed3ebd-2660-4269-ae5d-6d13e013da21.png)
No, I mean, my vscode on PC works with these fonts like the pic above, it's just not working on ubuntu installed on termux

**Comment by MMMMMoris** [comment]
Is it because the worng name of the fonts?  I use MesloLGS NF as its name still, perhaps it has a different name on termux or another way to quote it?

**Comment by romkatv** [comment]
In which application does the font not work? On which OS are you running the application? Have you installed the font on that OS?

**Comment by romkatv** [comment]
Do keep in mind that you'll get better help if you search for it in places dedicated to the application in which you cannot change font.

**Comment by MMMMMoris** [comment]
> In which application does the font not work? On which OS are you running the application? Have you installed the font on that OS?

Android, termux installed, and ubuntu is installed on termux. All these fonts works well on termux, except the code-server

**Comment by romkatv** [comment]
What is the name of the application that is rendering your terminal? From which OS did you start it?

**Comment by MMMMMoris** [comment]
> 

Just code-server rendering my terminal I think. Perhaps it's hard to discribe, but I will try, I use zsh and  oh-my-zsh on termux . As to from which OS, I jsut access 127.0.0.1:8080 on my Chrome

**Comment by MMMMMoris** [comment]
Here is my Termux terminal while running code-server
![Screenshot_2022-12-14-05-02-26-265_com termux](https://user-images.githubusercontent.com/63332824/207442879-acd7fa09-91d1-4db2-a500-c276197e4cf1.jpg)

**Comment by romkatv** [comment]
Let me try it another way. Your screenshot shows a window. To which application does this window belong? On which OS did you start the application that drew the window?

**Comment by romkatv** [comment]
Termux and ubuntu aren't relevant here. Only the terminal and the OS under which it runs matter.

**Comment by romkatv** [comment]
I'm going to close this issue. Sorry.

**Comment by MMMMMoris** [comment]
> I'm going to close this issue. Sorry.

I am sorry, I don't get it still

**Comment by romkatv** [comment]
You are trying to change the font in some app. Please ask for help in places where people go to get help with this app.

**Comment by romkatv** [comment]
I don't know how to change font in that app.

**Comment by MMMMMoris** [comment]
Ok, i will show you a video,recording the process I do to open the code-server window, and you will see what is happening, is that okay?

**Comment by romkatv** [comment]
Sorry, I really don't know how to change font there. I only know zsh.

**Comment by MMMMMoris** [comment]
> Sorry, I really don't know how to change font there. I only know zsh.

But, I am just using zsh...

**Comment by romkatv** [comment]
If you run bash, the font will still be the same. It's the terminal that has fonts. Shells do not have fonts.

**Comment by romkatv** [comment]
To change font in your terminal you need to do something with the terminal and maybe the OS that runs it. I cannot help you with that. This task has nothing to do with zsh.

**Comment by MMMMMoris** [comment]
https://user-images.githubusercontent.com/63332824/207446916-2e16ba27-1079-4cf2-b200-d6c0aee87ae3.mp4

**Comment by MMMMMoris** [comment]
> To change font in your terminal you need to do something with the terminal and maybe the OS that runs it. I cannot help you with that. This task has nothing to do with zsh.

Have a look, please

**Comment by romkatv** [comment]
Please ask for help in a place where people go to when they need help with code-server, or with chrome, or with android.

**Comment by MMMMMoris** [comment]
> Please ask for help in a place where people go to when they need help with code-server, or with chrome, or with android.

Okay, thanks for your dedication anyway, have a good day!

**Comment by romkatv** [comment]
Thank you. I hope you find the solution. If you do, please post an update here.
