### ISSUE TITLE
Feature request: add configuration for gitstatus to use GIT_SUBMODULE_IGNORE_ALL

### ISSUE THREAD

**Issue by taschini** [romkatv/powerlevel10k#2124]
Gitstatus uses only GIT_SUBMODULE_IGNORE_DIRTY.  It would be nice to have the possibility to configure it to use GIT_SUBMODULE_IGNORE_ALL.  This should not cause any performance degradation.

I understand this would have to be a global configuration setting, not a repository-specific one.

**Comment by romkatv** [comment]
If you send a clean PR, I'll merge it.
