### ISSUE TITLE
Shorten current directory and git branch names in prompt

### ISSUE THREAD

**Issue by ky0n** [romkatv/powerlevel10k#2127]
The current path and the branch names of git can make the left prompt so long, that there is almost no space between the left and right prompt. How is this configurable? I know it was possible in powerlevel9k at least for paths.

**Comment by romkatv** [comment]
Run `p10k configure` and choose classic, rainbow or lean style.

**Comment by ky0n** [comment]
thats not really a lot of options there and has other implications.. with powerlevel9k you could specify various kinds of truncation strategies to shorten the prompts. It  has a segment on the readme https://github.com/Powerlevel9k/powerlevel9k. Something like this is not possible with p10k ?

**Comment by romkatv** [comment]
> thats not really a lot of options

I believe it's more shortening options than any other theme.

>  with powerlevel9k you could specify various kinds of truncation strategies to shorten the prompts

Powerlevel10k has all those and more. You can take an existing powerlevel9k config and use it with powerlevel10k. It'll give you the same prompt.

**Comment by ky0n** [comment]
Okay, thanks. I will try to do it that way.
