### ISSUE TITLE
update nodejs icon

### ISSUE THREAD

**Issue by tjx666** [romkatv/powerlevel10k#2128]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/41773861/208305231-7970afab-ef88-476c-b282-714fe214fb10.png">

I see startship using this:

<img width="731" alt="image" src="https://user-images.githubusercontent.com/41773861/208305377-2e2e571f-f135-4639-92d4-2e9a6b1035b1.png">

**Comment by romkatv** [comment]
You can use this icon if you like.

1. Open `~/.p10k.zsh`.
2. Add one line: `typeset -g POWERLEVEL9K_NODE_ICON='\uF898'`.
3. Save.
4. Restart zsh with `exec zsh`.

**Comment by tjx666** [comment]
@romkatv Where can I search for a icon unicode I need? I want to custom pnpm version segment, where can I find the zsh example?

**Comment by romkatv** [comment]
You can search for icons here: https://www.nerdfonts.com/cheat-sheet
