### ISSUE TITLE
Align color scheme with alacritty terminal

### ISSUE THREAD

**Issue by kaykhan** [romkatv/powerlevel10k#2130]
Hi i switched my terminals recently frm the default ubuntu gnome shell terminal to alacritty and noticed the colors are saturated in alactritty compared to the default terminal. Is there some easy way to get the color scheme applied to the alacritty terminal?

![image](https://user-images.githubusercontent.com/5202527/208661290-5d13d3f7-d2ee-4283-9d6c-ec7856fc8cd8.png)

In the alacritty config i know i can set some basic colors https://github.com/alacritty/alacritty/blob/master/alacritty.yml#L284-L292

But im not sure where to find these color values in my currentl gnome shell using powerlevel10k

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors

**Comment by kaykhan** [comment]
> https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors

Hey, i was just reading that as you commneted but unfortunately its still not clear what i should be doing? Is there some way to get access to the colors for 

```
  #  black:   '#'
  #  red:     '#'
  #  green:   '#'
  #  yellow:  '#'
  #  blue:    '#'
  #  magenta: '#'
  #  cyan:    '#'
  #  white:   '#'
  ```
  
  So i can apply them to my alacritty config.
  
  I dont want to change any colors for powerlevel10k, i think they are fine. I jsut want to apply the same colors in alacritty

**Comment by romkatv** [comment]
Your question boils down to this: what colors does you GNOME terminal use. You might be able to find the answer in GNOME terminal settings. Or you can figure it out from the screenshot.

P.S.

I would just stay with GNOME terminal to be honest. It's better than Alacritty in my opinion.
