### ISSUE TITLE
Show transient prompt when running process

### ISSUE THREAD

**Issue by jimburch** [romkatv/powerlevel10k#2131]
I love how p10k's transient prompt cuts down on clutter in iTerm, but I'd like to be able to see the most recent path/branch when running a process

<img width="649" alt="image" src="https://user-images.githubusercontent.com/49823725/208708402-0d012b32-30db-4945-a6eb-4bc996aec440.png">

Transient prompt makes it disappear entirely

**Comment by romkatv** [comment]
This is impossible due to the nature of the terminal. Once a command starts executing, the content of the terminal above that cannot be changed.
