### ISSUE TITLE
Press tab to path expansion/completion only works for first path

### ISSUE THREAD

**Issue by yangwooko** [romkatv/powerlevel10k#2132]
For example, if I type "diff path1" and then tab, zsh properly expand/complete the path. But, after finishing entering the first path, press tab would not expand/compete path. 

For example, "diff path1/file1 path2" then press tab, nothing happens. (I am using MacOS + iterm + zsh + p10k).

**Comment by romkatv** [comment]
Powerlevel10k doesn't do anything w.r.t. completions. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by yangwooko** [comment]
Oh... I checked again and found that this issue is related with oh-my-zsh. Sorry.
