### ISSUE TITLE
node/nvm version behavior (doesn't show even if a package.json file is present and use the nvm version)

### ISSUE THREAD

**Issue by dongchirua** [romkatv/powerlevel10k#2134]
Hi, I expect my terminal to show nodejs version of the current project. I also tried to create `.nvmrc` and specified node version in `package.json` but it doesn't work. Here is my screen record

![](https://media.giphy.com/media/TLsey03ZcEn5xYLhl0/giphy.gif)

I am not sure if I missed any config or there is a problem in `powerlevel10k`

Notes:

1.  Work normally in Python (Conda), Java (Jenv)
2. Project is set to use Node 16

Thanks for this awesome theme!

**Comment by romkatv** [comment]
If you expect `nvm` segment to be shown in prompt, keep in mind that it's hidden unless the current node version differs from the default.

if you expect `package` segment to be shown in prompt, you need to uncomment it in `~/.p10k.zsh`.
