### ISSUE TITLE
vscode got mutiple lines of prompts, I don't know why

### ISSUE THREAD

**Issue by MMMMMoris** [romkatv/powerlevel10k#2135]
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/63332824/209574079-114bc37c-fcc0-4803-a970-ee14b1b19df6.png">
check it out,
seems to be some kind of bug.

platform: Windows ARM64, MSYS2 terminal, z-shell

**Comment by romkatv** [comment]
This might help: https://github.com/romkatv/powerlevel10k#prompt-wrapping-around-in-a-weird-way.

**Comment by MMMMMoris** [comment]
> This might help: https://github.com/romkatv/powerlevel10k#prompt-wrapping-around-in-a-weird-way.

No, it doesn't work... :(

I have tried every method you mentioned on that link

**Comment by MMMMMoris** [comment]
> This might help: https://github.com/romkatv/powerlevel10k#prompt-wrapping-around-in-a-weird-way.

I got something like this through diagnosis
<img width="352" alt="image" src="https://user-images.githubusercontent.com/63332824/209627226-c58ab505-43c3-43b9-bf8d-8785628d88d7.png">

**Comment by romkatv** [comment]
You might have some luck trying it in a different terminal or running `p10k configure` and selecting ASCII instead of UNICODE.

**Comment by MMMMMoris** [comment]
> You might have some luck trying it in a different terminal or running `p10k configure` and selecting ASCII instead of UNICODE.

You are right, I tried ASCII, it functions normally. But I cannot see the icons in that case... What is the reason?

**Comment by romkatv** [comment]
There are no icons in ASCII mode. This is intended.

I don't know why your terminal fails at rendering when using icons.

**Comment by romkatv** [comment]
Please run the following command and post a screenshot of the output:

```zsh
() {
  emulate -L zsh
  setopt err_return no_unset
  locale
  zmodload zsh/langinfo
  print -r -- "TERM=$TERM CODESET=$langinfo[CODESET]"
  local text=$'\uE0B0'
  local -i len=${(m)#text}
  local frame="+-${(pl.$len..-.):-}-+"
  print -lr -- $frame "| $text |" $frame
}
```

**Comment by MMMMMoris** [comment]
> Please run the following command and post a screenshot of the output:
> 
> ```shell
> () {
>   emulate -L zsh
>   setopt err_return no_unset
>   locale
>   zmodload zsh/langinfo
>   print -r -- "TERM=$TERM CODESET=$langinfo[CODESET]"
>   local text=$'\uE0B0'
>   local -i len=${(m)#text}
>   local frame="+-${(pl.$len..-.):-}-+"
>   print -lr -- $frame "| $text |" $frame
> }
> ```

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/63332824/209641453-ab2486cb-6d3c-4feb-a151-7f7db4cd69d8.png">
Here it is

**Comment by romkatv** [comment]
How about this?

```zsh
() {
  emulate -L zsh
  setopt err_return no_unset
  local text=$'\uE0B2 \uF17A \uF015 \uE0B0'
  local -i len=${(m)#text}
  local -i pad='COLUMNS - len'
  typeset -p COLUMNS len pad
  print -r -- $text${(pl.$pad..-.):-}
}
```

**Comment by MMMMMoris** [comment]
> How about this?
> 
> ```shell
> () {
>   emulate -L zsh
>   setopt err_return no_unset
>   local text=$'\uE0B2 \uF17A \uF015 \uE0B0'
>   local -i len=${(m)#text}
>   local -i pad='COLUMNS - len'
>   typeset -p COLUMNS len pad
>   print -r -- $text${(pl.$pad..-.):-}
> }
> ```

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/63332824/209642802-ae89678c-31d7-40ad-b133-d4f89e1b7719.png">
Check it out

**Comment by romkatv** [comment]
Your terminal is broken. See how it added a line break before the last "----". Apparently it thinks that UNICODE glyphs from Private Use Area are wide. If you are lucky, you might be able to find a setting in the terminal that makes them narrow.

**Comment by MMMMMoris** [comment]
> Your terminal is broken. See how it added a line break before the last "----". Apparently it thinks that UNICODE glyphs from Private Use Area are wide. If you are lucky, you might be able to find a setting in the terminal that makes them narrow.

Do you have any advise? I even uninstalled vscode once ,deleted its user profile as well, while I reinstall it, it's the same situation

**Comment by MMMMMoris** [comment]
> Your terminal is broken. See how it added a line break before the last "----". Apparently it thinks that UNICODE glyphs from Private Use Area are wide. If you are lucky, you might be able to find a setting in the terminal that makes them narrow.

Seems I have found the soution. Vscode sync my setting of another PC, which got the different setting config. Here is the one functions normally.
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/63332824/209645115-20802e3c-15d7-47e1-aac0-9b7078aa470c.png">

**Comment by romkatv** [comment]
This must have fixed the setting that controls the width of UNICODE glyphs from Private Use Area.

In case someone stumbles upon this, you can verify whether your terminal is broken in this exact way by executing the following script in `zsh`, `bash` or `sh`:

```shell
for i in $(seq $(tput cols)); do printf .; done
printf '\n\n\356\202\260'
for i in $(seq $(($(tput cols) - 1))); do printf .; done
printf '\n'
```

The correct output looks like this:

![image](https://user-images.githubusercontent.com/1282067/209646092-0ede6f07-16de-4901-b201-c9e20253b865.png)

In a broken terminal it'll look like this:

![image](https://user-images.githubusercontent.com/1282067/209646254-4130dfdd-2358-4e71-957a-5563dbdc2881.png)

Note the erroneous line break before the last dot.
