### ISSUE TITLE
Changing of Background color after adding custom prompt

### ISSUE THREAD

**Issue by DeeptangshuSaha** [romkatv/powerlevel10k#2136]
I added a custom segment to my prompt. It is to just print a Japanese text nothing much. But after adding that a new problem has raised. It now changes the background color only for the `dir` part of the prompt in my left prompt.
```bash
# Current directory background color.
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=033
  # Default current directory foreground color.
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
  # If directory is too long, shorten some of its segments to the shortest possible unique
  # prefix. The shortened directory can be tab-completed to the original.
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  # Replace removed segment suffixes with this symbol.
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  # Color of the shortened directory segments.
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
  # Color of the anchor directory segments. Anchor segments are never shortened. The first
  # segment is always an anchor.
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
  # Display anchor directory segments in bold.
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  # Don't shorten directories that contain any of these files. They are anchors.
  local anchor_files=(
    .bzr
    .citc
    .git
    .hg
    .node-version
    .python-version
    .go-version
    .ruby-version
    .lua-version
    .java-version
    .perl-version
    .php-version
    .tool-version
    .shorten_folder_marker
    .svn
    .terraform
    CVS
    Cargo.toml
    composer.json
    go.mod
    package.json
    stack.yaml
  )
```

The above part shows the `dir` part of my code.
![my_term](https://user-images.githubusercontent.com/64020655/209811243-1ff0d824-c34c-4201-bf84-00b6975558b4.png)
I am talking about the black background behind the tilde sign as well as the directory name.
Please help me this is my first time adding custom segment.

**Comment by romkatv** [comment]
Do I understand correctly that you have two `.p10k.zsh` files and with one of them `dir` is displayed correctly while with the other it has incorrect background? If so, please attach both of these files.

**Comment by DeeptangshuSaha** [comment]
No, Its only one `.p10k.zsh` file one is when i comment out the custom prompt and execute it and one when it is there and i execute it.

**Comment by romkatv** [comment]
Two versions of the same file? Please attach both.

**Comment by DeeptangshuSaha** [comment]
Actually I just tried to delete all non-needed space in the below snippet
```bash
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    crown
    os_icon
    # os identifier
    dir         
    # current directory
    vcs     
    # git status
    # prompt_char
    # prompt symbol
  )
```
There were a lot of  trailing spaces after `os_icon, dir` I just deleted those and it started to work as expected.

**Comment by DeeptangshuSaha** [comment]
Yup It was quiet the weird fix but it works.
