### ISSUE TITLE
Change virtualenv segment to display env name before Python version

### ISSUE THREAD

**Issue by julien10** [romkatv/powerlevel10k#2137]
Hi,

I could not find any explanation on how to change the order of the virtualenv segment parts.

Currently, the virtualenv name is displayed after the Python version:

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/3885059/209818473-2db323a7-c1b0-427a-ace6-4cad3a82cdb1.png">

I would like to have it the other way around, with the virtualenv name and then the Python version (`image-tools 3.10.9` instead of `3.10.9 image-tools`).

These are all the lines related to virtualenv segment configuration, I do not see anything which seems to be related to what I want:
```
  ###[ virtualenv: python virtual environment (https://docs.python.org/3/library/venv.html) ]###
  # Python virtual environment color.
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=202
  # Don't show Python version next to the virtual environment name.
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
  # If set to "false", won't show virtualenv if pyenv is already shown.
  # If set to "if-different", won't show virtualenv if it's the same as pyenv.
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=if-different
  # Separate environment name from Python version only with a space.
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
  # Custom icon.
  # typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='⭐'
```

Is it possible? If so, how?

Thanks in advance!

**Comment by romkatv** [comment]
Try this:

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION='${P9K_CONTENT[(w)2]} ${P9K_CONTENT[(w)1]}'
```

**Comment by julien10** [comment]
Yep, it works. Thanks for your quick answer!

**Comment by romkatv** [comment]
I'm glad that it works.

`POWERLEVEL9K_<segment>_CONTENT_EXPANSION` is a generic parameter, meaning that it works with all segments. This parameter allows you to transform the content of a segment. In this case we are setting the value to `${P9K_CONTENT[(w)2]} ${P9K_CONTENT[(w)1]}`, which swaps the position of the two words (`P9K_CONTENT` holds the original content).
