### ISSUE TITLE
status segment shows ok for exitcode !=0 in pipe

### ISSUE THREAD

**Issue by vgropp** [romkatv/powerlevel10k#2139]
i noticed a unexpected behavior when using POWERLEVEL9K_STATUS_EXTENDED_STATES=true and errors in piped cmd:
![image](https://user-images.githubusercontent.com/3162772/210238233-43114da3-f779-4d37-a471-ef4468202d02.png)

I did expect not a "OK" but an error like 
![image](https://user-images.githubusercontent.com/3162772/210238477-da3720c7-e792-41ff-baab-6e8cadb5c811.png)

The problem seems to be, in https://github.com/romkatv/powerlevel10k/blob/33916e91a743a73472a15f3fc27dd0aa9f7abbdf/internal/p10k.zsh#L3281 only the status is checked and not both _p9k__status and _p9k__pipestatus
changing it to 
```
(( _p9k__status )) || [[ "$_p9k__pipestatus" == *[1-9]* ]] && local state=ERROR || local state=OK
```
fixes the issue for me.  Do you want me to create a PR or do you know a better fix?

**Comment by romkatv** [comment]
What happens if you run `echo $?` after a command that you believe to be incorrectly classified by powerlevel10k as successful?

**Comment by vgropp** [comment]
as expected i get 0
```
echo foo | cat a | cat; echo $?  
cat: a: No such file or directory
0
```
So is this expected behavior? I expected showing this as an error using POWERLEVEL9K_STATUS_EXTENDED_STATES. Is this a different styling? As the background to the OK status segment is not correct (you can see the difference in the first screenshot). Is it possible to style this? 

My current config:
```
 ##########################[ status: exit code of the last command ]###########################
  # Enable OK_PIPE, ERROR_PIPE and ERROR_SIGNAL status states to allow us to enable, disable and
  # style them independently from the regular OK and ERROR state.
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true

  # Status on success. No content, just an icon. No need to show it if prompt_char is enabled as
  # it will signify success by turning green.
  typeset -g POWERLEVEL9K_STATUS_OK=true
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=239

  # Status when some part of a pipe command fails but the overall exit status is zero. It may look
  # like this: 1|0.
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0

  # Status when it's just an error code (e.g., '1'). No need to show it if prompt_char is enabled as
  # it will signify error by turning red.
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1

  # Status when the last command was terminated by a signal.
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  # Use terse signal names: "INT" instead of "SIGINT(2)".
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=1

  # Status when some part of a pipe command fails and the overall exit status is also non-zero.
  # It may look like this: 1|0.
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=1
```

**Comment by romkatv** [comment]
If you want to style a successful command differently when some part of its pipeline fails, change the values of `POWERLEVEL9K_STATUS_ERROR_PIPE_*` parameters.

If you want a pipeline such as `false | true` to set a non-zero error code, add `setopt pipe_fail` to `~/.zshrc`.

**Comment by romkatv** [comment]
Note that `setopt pipe_fail` isn't specific to powerlevel10k. See `man zshoptions`.

**Comment by vgropp** [comment]
ok, thanks for the hint to pipe_fail, i wasn't aware of it and it fixes my issue, but changes the behavior.

Regarding the issue, i do set `POWERLEVEL9K_STATUS_ERROR_PIPE_*`  as you can see in https://github.com/romkatv/powerlevel10k/issues/2139#issuecomment-1368972098. And looking at the code, the status is always OK, even with POWERLEVEL9K_STATUS_EXTENDED_STATES=true, so `POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND` seems to have no effect.

**Comment by romkatv** [comment]
Sorry, I meant `POWERLEVEL9K_STATUS_OK_PIPE_*`. The comment in the block you've quoted are pretty good. The parameters work as documented there.

**Comment by vgropp** [comment]
now i get it, thanks for the hint. And yes, it is documented but i didn't read carefully enough to spot this feature. 

Thanks for your help
