### ISSUE TITLE
How to reset the settings?

### ISSUE THREAD

**Issue by rafakwolf** [romkatv/powerlevel10k#214]

**Comment by romkatv** [comment]
Take a look at the bottom of your `~/.zshrc`. Does that help?

Edit: To change settings, run `p10k configure` or (advanced!) manually edit `~/.p10k.zsh`.

**Comment by minseongkimdev** [comment]
`p10k configure` command would be helpful

**Comment by bochainwu** [comment]
thanks🙏

**Comment by geyang** [comment]
for all who get here from google and are disappointed of the lack of a clear answer --- Just run:

```bash
rm .p10k.zsh
```
then restart the terminal.

**Comment by romkatv** [comment]
To change settings, run `p10k configure` or manually edit `~/.p10k.zsh`.

**Comment by TodoshiTakato** [comment]
> To change settings, run `p10k configure` or manually edit `~/.p10k.zsh`.

If I manually changed my `~/.p10k.zsh` configuration file, is there any command to reload config for current terminal session?

**Comment by romkatv** [comment]
> > To change settings, run `p10k configure` or manually edit `~/.p10k.zsh`.
> 
> If I manually changed my `~/.p10k.zsh` configuration file, is there any command to reload config for current terminal session?

```zsh
source ~/.p10k.zsh
```

**Comment by Th3Unkn0wn1-cyber** [comment]
> To change settings, run `p10k configure` or manually edit `~/.p10k.zsh`.

it says:
bash: p10k: command not found
although i've installed it and for '~/.p10k.zsh' im too dumb

**Comment by romkatv** [comment]
> `p10k configure` command would be helpful

Yes it would! I've edited my own answer.
