### ISSUE TITLE
Size of tilde symbol differs when truncating directory path

### ISSUE THREAD

**Issue by jsr-p** [romkatv/powerlevel10k#2140]
When truncating the directory path by applying
`typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last` 
the tilde symbol looks like 
![truncate_last](https://user-images.githubusercontent.com/49307119/210270555-e1725ce3-5b5d-43f8-8eda-ea186d309cd4.png)
However, when truncating the directory path by instead applying
`typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=1`
and letting `POWERLEVEL9K_SHORTEN_STRATEGY` be equal to its default value, the tilde symbol looks like 
![maxdir1](https://user-images.githubusercontent.com/49307119/210270740-f8e5a31f-649e-4144-b549-fba0a81e4629.png)
What is the reason for this difference?

**Comment by romkatv** [comment]
If you change the value of `POWERLEVEL9K_SHORTEN_STRATEGY`, many parameters related to directory styling will stop working. In this case you are noticing that `POWERLEVEL9K_DIR_ANCHOR_BOLD=true` no longer works.

**Comment by jsr-p** [comment]
Thanks for the quick response @romkatv :smile: 
I thought it was a bug. But this is the intended behavior of setting 
`typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last`, or?

**Comment by romkatv** [comment]
Correct, this is intended. When I'm adding new parameters that affect `dir`, I only implement them for the default truncation strategy. In theory it's possible to implement some of them for other truncation strategies but those strategies are too niche to justify spending time on them.

**Comment by jsr-p** [comment]
All right. Thanks a lot for the answer (and the theme)! :smiley:
