### ISSUE TITLE
Change the home tilde symbol

### ISSUE THREAD

**Issue by glepnir** [romkatv/powerlevel10k#2141]
how do i change the  home `~` symbol . thanks (btw add an issue tempalte would be better )

**Comment by romkatv** [comment]
Please attach your `~/.p10k.zsh`, a screenshot of your prompt and a description of what you want to be changed in your prompt.

**Comment by glepnir** [comment]
p10k is too long .  question is simple change this symbol . I had tried the `PROMPT_HOME_ICON` failed 
![image](https://user-images.githubusercontent.com/41671631/210318946-60beab3c-878d-415e-8cae-e356efa45eeb.png)

**Comment by romkatv** [comment]
> p10k is too long

Too long for what?

What do you want to change `~` to? Note that `~` is a real directory, it's not an icon. You type `cd ~` or `ls ~/.p10k.zsh`.

**Comment by glepnir** [comment]
> What do you want to change ~ to? Note that ~ is a real directory, it's not an icon.

oh fine .. I want change it to a emoji icon . it's not an icon so this is disabled. close then thanks.

**Comment by romkatv** [comment]
What do you want to see when your current directory is `~/foo`?
