### ISSUE TITLE
Right prompt leaving a gap at the end.

### ISSUE THREAD

**Issue by copypasteonly** [romkatv/powerlevel10k#2143]
As you can see at the image below the right prompt always leaves a gap at the end. I tried all other styles of prompts and the right prompt always leaves a gap. I'm using kitty as my terminal emulator if that matters. Here's my [p10k and zshrc](https://gist.github.com/copypasteonly/eac28b0356fb836b5142984a1a717b17).

![prompt](https://user-images.githubusercontent.com/89444867/210634509-38a03759-fe6d-4caf-b578-7b7118a4e128.png)

**Comment by romkatv** [comment]
Add `ZLE_RPROMPT_INDENT=0` to `~/.zshrc`. It's documented at https://zsh.sourceforge.io/Doc/Release/Parameters.html.

**Comment by copypasteonly** [comment]
> Add `ZLE_RPROMPT_INDENT=0` to `~/.zshrc`. It's documented at https://zsh.sourceforge.io/Doc/Release/Parameters.html.

Oh wow didn't know it was this simple, thanks so much for your work and the support!
