### ISSUE TITLE
git branch name not showing full path

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [romkatv/powerlevel10k#2144]
Hello, I notice that if a branch name exceeds some length it won't display the full name on the path.

Below is the case when I'm using a one-liner
![image](https://user-images.githubusercontent.com/35159954/210689572-b3e7e5b2-ce32-45f8-bceb-2d03b404eefc.png)

Then, I tried to change using two-liner and produce the same thing
![image](https://user-images.githubusercontent.com/35159954/210689757-7327b230-e0e0-4fb9-9546-5590e2a25234.png)

If the picture above is confusing, I'll explain here: Let's say I have a full branch name `this-is-my-branch-name` but then my prompt only shows `this-is.....nch-name`

Is there any solution to this?

**Comment by cedrus-8864** [comment]
You can try this way. 
Edit `~/.p10k.zsh` and comment line **386**. Like the below image.

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/45024643/210759039-e5824882-68b1-4300-a87b-383ed9ecab3d.png">

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and find this block: https://github.com/romkatv/powerlevel10k/blob/33916e91a743a73472a15f3fc27dd0aa9f7abbdf/config/p10k-classic.zsh#L393-L394

Do what the tip says.

**Comment by bhaskoro-muthohar** [comment]
Thanks!

**Comment by bhaskoro-muthohar** [comment]
> You can try this way. Edit `~/.p10k.zsh` and comment line **386**. Like the below image.
> 
> <img alt="image" width="1055" src="https://user-images.githubusercontent.com/45024643/210759039-e5824882-68b1-4300-a87b-383ed9ecab3d.png">



> Open `~/.p10k.zsh` and find this block:
> 
> https://github.com/romkatv/powerlevel10k/blob/33916e91a743a73472a15f3fc27dd0aa9f7abbdf/config/p10k-classic.zsh#L393-L394
> 
> Do what the tip says.

Thanks!
