### ISSUE TITLE
Tab completion list is erased by Powerlevel10K on gitstatus async prompt update.

### ISSUE THREAD

**Issue by carljohnesan** [romkatv/powerlevel10k#2145]
Hi. I've tried using Zsh second time in my life today and liked your prompt and settled on it.
I've downloaded Zim first, done minimal configuration, and then installed p10k according to instructions for Zim.

I've spotted bug rather quickly, however.
While skimming through FreeBsd kernel tree I encountered very annoying bug that in the middle of tab completion git branch name becomes green (probably indicating that it finished loading) and the tab completion list I was navigating through disappears (I still can navigate completion list but it's not visible).

I'm sure it's related to how p10k updates prompt, I hope it's possible to fix because I hit this bug every time I `cd` into a directory and invoke tab completion (even gitstatusd needs few seconds to "scan" kernel codebase).

If problem might be in completion configuration then I'm using default one provided by Zim and here it is: https://github.com/zimfw/completion/blob/master/init.zsh

Here's how it looks (I have trouble posting video so here's screenshots from it):

before git segment loaded:
![Screen Shot 2023-01-05 at 7 51 24 PM](https://user-images.githubusercontent.com/47556468/210847307-a3580808-cafe-46d0-91f2-98846e6919d6.png)

after git segment loaded:
![Screen Shot 2023-01-05 at 7 51 35 PM](https://user-images.githubusercontent.com/47556468/210847381-e0783c12-2166-41b8-b94b-6aa6a011d599.png)

-----------------------------
And another two

![Screen Shot 2023-01-05 at 7 52 01 PM](https://user-images.githubusercontent.com/47556468/210847444-a41144a7-93f3-49a5-ada7-354908997554.png)

![Screen Shot 2023-01-05 at 7 52 10 PM](https://user-images.githubusercontent.com/47556468/210847514-e3afdfd4-f5d9-4cde-a25e-0d31c0ed15ce.png)

This is pretty hard to live with...

Anyway:
OS Mac OS X 10.15.7
iTerm2
zsh 5.7.1

**Comment by romkatv** [comment]
It's a bug in zsh: https://www.zsh.org/mla/workers/2019/msg00161.html

**Comment by carljohnesan** [comment]
Oh, sorry to bother you then. But it really is unbearable bug. Are they not gonna fix it? It's been almost three years since you reported it. If so then it's sad

**Comment by romkatv** [comment]
Zsh is a free and open-source project maintained by unpaid volunteers. Bugs usually get fixed by those who care about them. If you do, give it a shot. I don't use menu completion myself.

**Comment by carljohnesan** [comment]
I get it. Thank you for answering me!
