### ISSUE TITLE
Something wrong with powerlevel10k

### ISSUE THREAD

**Issue by sysfox** [romkatv/powerlevel10k#2147]
Hi
Something went wrong when I use ITerm2 with powerlevel10k
It seems like a bug,
![a](https://user-images.githubusercontent.com/99103591/211143479-024fbe80-fd78-4e9f-99a3-a251f7e01740.gif)

Environment:
macOS 13.1
powerlevel10k latest (mirror on gitee)
iTerm2 latest
oh-my-zsh latest

**Comment by sysfox** [comment]
How to solve the problem？

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by sysfox** [comment]
OK，Thanks
