### ISSUE TITLE
OSC 8 formatting is not cleared

### ISSUE THREAD

**Issue by Syphdias** [romkatv/powerlevel10k#2148]
It's been a while since I ran into a bug...

I noticed that some formatting is not cleared.
![image](https://user-images.githubusercontent.com/16988672/211191117-edf922aa-8dba-4314-8aed-4ea60a1f9760.png)

It looks like this is some sort of linking. I can hold Ctrl and click on it to open an editor. Kinda cool, didn't know that was a thing. Apparently this is specified by OSC 8.

I looked a bit into it and is looks like this is something that terminal emulators can implement (I tried it in Tilix and Terminator). A small example that I found by looking at what `systemctl` does:
```
echo -e "\e]8;;http://example.com\asomething\e]8;;\a"
```
It used `\x07` or `\a` which I think usually triggers the terminal bell, but not in this case, apparently.

I also found [this](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda), which describes it a bit differently and uses `\e\\` instead of `\a`. The section for [escape sequences](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#the-escape-sequence) goes more into detail.

What triggers the bug is, not terminating the link properly. Some ways to do it:
```
echo -e "\e]8;;http://example.com\asomething"        
echo -e "\e]8;;http://example.com\asomething\e]8;;"
echo -e "\e]8;;http://example.com\asomething\a"
```
To fix, wither one of these seems to work:
```
echo -e "\e]8;;\a"
echo -e "\e]8;;\e\\"
```

There is probably a section that already does some resetting like `\e[0m`. Maybe adding one of the fixes will do the trick but I do not know if
a) which of the two fixes would be better
b) this has side effects (~especially on [terminal emulators without the implementation](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#backward-compatibility)~)

**Comment by romkatv** [comment]
> I noticed that some formatting is not cleared. ![image](https://user-images.githubusercontent.com/16988672/211191117-edf922aa-8dba-4314-8aed-4ea60a1f9760.png)

Could've been worse. Truncating the output intended for the terminal can brick it.

If you are willing to accept the risks and want to mitigate the effect of this particular problem, it's too late to do that in prompt. The right place for a workaround is `PROMPT_EOL_MARK`. You can try this:

```zsh
PROMPT_EOL_MARK=$'%{\e]8;;\a\e]8;;\a%}%K{red} %k'
```

**Comment by Syphdias** [comment]
> If you are willing to accept the risks and want to mitigate the effect of this particular problem, it's too late to do that in prompt. The right place for a workaround is `PROMPT_EOL_MARK`. You can try this:
> 
> ```shell
> PROMPT_EOL_MARK=$'%{\e]8;;\a\e]8;;\a%}%K{red} %k'
> ```

Yes, that works, thank you!

**Comment by Syphdias** [comment]
Note when using `PROMPT_EOL_MARK` with https://github.com/romkatv/zsh4humans : This needs to be set after `z4h init`
