### ISSUE TITLE
syntax highlighting and autosuggestion not working

### ISSUE THREAD

**Issue by niravsheth-arch** [romkatv/powerlevel10k#2149]
Hello,

First of all I'm new with Linux so please bare with me. zsh-autosuggestion and syntax highlighting was working after installing powerlevel 10k it's no longer working.
I'm running ArcoLinux (Arch Linux) XFCE, ZSH is v5.9.
Terminal is Alacritty
OMZ is already preinstalled in OS under /usr/share/
zsh-autocompletion and zsh-syntax-highlighting is installed in /usr/share/zsh/plugins

When it was working I did not specify in plugins= under .zhrc I guess because its installed under /usr/share

I can provide you .zshrc and .p10k file.

Can you please provide assistance? I also tried changing default to 
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION=' \$'

Thank you.

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k?

**Comment by niravsheth-arch** [comment]
> 

by running powerlevel10k_plugin_unload 
want to make sure

**Comment by romkatv** [comment]
Try to disable it completely by undoing the steps you did during the installation. If in doubt, follow these instructions: https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k

**Comment by niravsheth-arch** [comment]
> Try to disable it completely by undoing the steps you did during the installation. If in doubt, follow these instructions: https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k

Followed your instruction via link and its removed

**Comment by romkatv** [comment]
And?

**Comment by niravsheth-arch** [comment]
highlighting is now working

**Comment by niravsheth-arch** [comment]
I think I know whats going on, I made a backup of .zshrc file and the backup contained the following 
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

**Comment by romkatv** [comment]
Is the issue resolved?

**Comment by niravsheth-arch** [comment]
So if I install powerlevel10k will it still work? do I need to modify anything in .zshrc?

**Comment by romkatv** [comment]
If you follow the installation instructions of powerlevel10k, it'll work.

**Comment by niravsheth-arch** [comment]
I will using the following per the instructions
yay -S --noconfirm zsh-theme-powerlevel10k-git
echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
then p10k configuration

Anything I should change?

**Comment by romkatv** [comment]
There is no need to change anything w.r.t. the installation instructions.

**Comment by niravsheth-arch** [comment]
Everything is working now, thank you very much Roman!

**Comment by romkatv** [comment]
You are welcome.
