### ISSUE TITLE
Tab title issue

### ISSUE THREAD

**Issue by rcornacchia** [romkatv/powerlevel10k#215]
Love this upgrade, thanks for building this!

I upgraded to powerlevel10k, but now it seems the title of the tab is intermittently `zsh` rather than the current directory of the tab. Any idea how to fix?

**Comment by rcornacchia** [comment]
Found an iterm setting that resolved this

**Comment by UpBra** [comment]
Preferences -> Profiles -> General.

Not intuitive but in the "Title" dropdown you can un-check "Job Name"
