### ISSUE TITLE
Does iTerm2 shell integration work with powerlevel10k?

### ISSUE THREAD

**Issue by AndreaPi** [romkatv/powerlevel10k#2150]
Hi,

I recently started using zsh,  Oh my zsh! and powerlevel10k in iTerm2 on a Mac, and I'm very happy with them. Friends told me to try [iTerm2 Shell Integration](https://iterm2.com/documentation-shell-integration.html) which apparently has some cool features. Do you know if this works smoothly with powerlevel10k, or should I expect some glitches?

**Comment by romkatv** [comment]
Yes, it works fine.

**Comment by romkatv** [comment]
You could just try it by the way.
