### ISSUE TITLE
Change cursor shape for instant prompt

### ISSUE THREAD

**Issue by quicknir** [romkatv/powerlevel10k#2151]
I'm using similar code to https://github.com/romkatv/powerlevel10k/issues/687 to change my cursor shape as I change modes. It works well, but there's just a tiny nitpick: when I open a new window, the rendering with instant prompt first renders with the regular shaped cursor. Then a moment after, when init is done, the cursor changes into the beam. 

Is there any way to feed the initial cursor shape to p10k, so that it gets handled by the instant prompt rendering?

**Comment by romkatv** [comment]
Replace every `echo` in that code with `>$TTY echo`.

**Comment by romkatv** [comment]
Also make sure that this line is at the very top of `~/.zshrc`, above the instant prompt preamble:

```zsh
# Use beam shape cursor on startup.
echo -ne '\e[6 q'
```

You can put `>$TTY` in there for consistency (although it doesn't matter).

**Comment by quicknir** [comment]
Ah nice! Yes, I had already tried the >$TTY echo, but that line at the very top of zshrc is what I was missing. Thanks! And since I'm here, just wanted to say thanks for powerline10k, I switched to it from my modified version of sorin a couple weeks ago, and it was even nicer, and significantly easier than I hoped. The two line + sparse + transient stuff is really incredible. Thanks for all of it!

**Comment by romkatv** [comment]
Thank you ❤️
