### ISSUE TITLE
there is not output but warn after today update

### ISSUE THREAD

**Issue by tjx666** [romkatv/powerlevel10k#2153]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/211998439-0372f4ec-6263-40d8-a13a-f8749b280f0c.png">

**Comment by markusgod** [comment]
same
![image](https://user-images.githubusercontent.com/20001291/212006747-f30cf7e4-5dc3-4d41-8ed2-bdbf75024f4a.png)

**Comment by romkatv** [comment]
This is caused by a bug in Oh My Zsh. This bug has already been fixed, so you need to update Oh My Zsh.

See https://github.com/ohmyzsh/ohmyzsh/issues/11314#issuecomment-1379492472. Here's the fix: https://github.com/ohmyzsh/ohmyzsh/commit/17ea97332b2f2285e3c2e1a00f6745fb1fe1cec5
