### ISSUE TITLE
context to show user@hostname when via ssh fails after running tmux

### ISSUE THREAD

**Issue by Halfwalker** [romkatv/powerlevel10k#2154]
Context is a great segment.  Seeing the user@hostname is a perfect reminder that you're NOT local ...
![image](https://user-images.githubusercontent.com/1365031/212162653-46cc66f5-235d-483b-8803-f662348890d3.png)
The trouble comes when running tmux after ssh'ing into a remote box.  It now thinks you're local (since tmux was run locally)
![image](https://user-images.githubusercontent.com/1365031/212162800-397348a7-2af3-4cb7-a1dd-43f0f02c0815.png)
This has now bitten me a 2nd time ...  Painful.  

Is there any way to have context see that it was remote before ?  Or anything we can put in the tmux config to inform context that it's remote (only when it really is via ssh)

**Comment by romkatv** [comment]
It's impossible in general to figure out whether your shell is in ssh or not. If you know of a way, please do share.

**Comment by Halfwalker** [comment]
How about checking for the SSH_CONNECTION env var ?  That's only there when the shell is from an ssh session isn't it ?

**Comment by romkatv** [comment]
That's the one powerlevel10k is looking for. It looks for a few other things but none of them are reliable. You can unset the vars (which you must have done) and spawn the shell as a child of another process (you've done this too) and then it'll be impossible to tell that the shell is running on one machine and the terminal on another.

**Comment by Halfwalker** [comment]
Hrm - not explicitly messing with SSH vars.  In fact, when the tmux session is started, the SSH_CONNECTION var is still set
```
env | fgrep SSH
P9K_SSH=0
SSH_AUTH_SOCK=/tmp/ssh-QsXmhyKLzY/agent.20513
SSH_CONNECTION=47.1.1.1 60898 192.168.2.103 22
```
In comparison to before the tmux session started
```
❯ env | fgrep SSH
SSH_CLIENT=47.19.105.250 60898 22
SSH_CONNECTION=47.1.1.1 60898 192.168.2.103 22
SSH_TTY=/dev/pts/15
SSH_AUTH_SOCK=/tmp/ssh-QsXmhyKLzY/agent.20513
P9K_SSH=1
```
I notice the *P9K_SSH* being different in each, somehow being set to 0 when under tmux

**Comment by romkatv** [comment]
Did you start tmux on that machine while logged in locally?

**Comment by Halfwalker** [comment]
I had other tmux sessions running on ryzen2 that were started locally, yes.  The one above though, was via ssh session from outside.

**Comment by romkatv** [comment]
What runs on your local machine doesn't factor in this. The remote machine isn't affected by anything you run locally, whether it's tmux or not.

I think somehow tmux was started wit `P9K_SSH=0` and it's propagating this value to all new shells. I think I can implement a workaround for this but it would be nice if you could confirm this. It would also be fantastic if you can figure out how to reproduce this.

**Comment by Halfwalker** [comment]
Sorry, by locally I meant on ryzen2.

So on that ryzen2 I've started a couple of tmux session after local login and starting alacritty.  If I open a new alacritty terminal, here's the SSH env vars :
![image](https://user-images.githubusercontent.com/1365031/212222674-685c25df-5be3-462a-a4e9-8d7244b0e625.png)
Starting tmux after that doesn't change anything - same SSH and P9K vars.

From another system here at home, ssh'ing into ryzen2 shows as expected
![image](https://user-images.githubusercontent.com/1365031/212223078-89d18521-c05f-4566-b095-1db2ec0a829b.png)
But starting tmux from there - the **SSH_CONNECTION** var is still there, but the context user@hostname is not
![image](https://user-images.githubusercontent.com/1365031/212223200-0e71a17d-d96a-4f90-b44d-87345d6fafe1.png)
That's with NO _~/.tmux.conf_ at all - just raw tmux, so there was nothing in the tmux config to set `P9K_SSH=0`

In that tmux session, if I _manually_ set `P9K_SSH=1` and hit enter, the user@hostname shows up correctly
![image](https://user-images.githubusercontent.com/1365031/212224656-852d7231-425f-4f04-aded-4843a091ebca.png)
But `ctrl-A c` to open a new pane still has `P9K_SSH=0` so no user@hostname

**Comment by romkatv** [comment]
That's exactly what I thought. When you started tmux on ryzen2, P9K_SSH was set to 0. Now, whenever tmux spawns a new shell, it copies that value over.

I've change the code a little so that `P9K_SSH` isn't trusted in this case. Could you update powerlevel10k on ryzen2 and check whether it works correctly now?

**Comment by Halfwalker** [comment]
Dang, no luck.

I pulled a clean install of zprezto, then went into the powerlevel10k repo under that and did a `git pull` to be sure
```
❯ pwd
/home/deano/.zprezto/modules/prompt/external/powerlevel10k

❯ git status
HEAD detached at 8a676a9
nothing to commit, working tree clean
❯ git pull
remote: Enumerating objects: 15530, done.
remote: Counting objects: 100% (15529/15529), done.
remote: Compressing objects: 100% (5134/5134), done.
remote: Total 15483 (delta 10198), reused 13660 (delta 10151), pack-reused 0
Receiving objects: 100% (15483/15483), 69.18 MiB | 31.64 MiB/s, done.
Resolving deltas: 100% (10198/10198), completed with 42 local objects.
From https://github.com/romkatv/powerlevel10k
 * [new tag]         v1.0       -> v1.0
 * [new tag]         v1.1       -> v1.1
 * [new tag]         v1.10.0    -> v1.10.0
 * [new tag]         v1.10.1    -> v1.10.1
 * [new tag]         v1.11.0    -> v1.11.0
 * [new tag]         v1.12.0    -> v1.12.0
 * [new tag]         v1.13.0    -> v1.13.0
 * [new tag]         v1.14.0    -> v1.14.0
 * [new tag]         v1.14.1    -> v1.14.1
 * [new tag]         v1.14.2    -> v1.14.2
 * [new tag]         v1.14.3    -> v1.14.3
 * [new tag]         v1.14.4    -> v1.14.4
 * [new tag]         v1.14.5    -> v1.14.5
 * [new tag]         v1.14.6    -> v1.14.6
 * [new tag]         v1.15.0    -> v1.15.0
 * [new tag]         v1.16.0    -> v1.16.0
 * [new tag]         v1.16.1    -> v1.16.1
 * [new tag]         v1.2.0     -> v1.2.0
 * [new tag]         v1.3.0     -> v1.3.0
 * [new tag]         v1.4.0     -> v1.4.0
 * [new tag]         v1.5.0     -> v1.5.0
 * [new tag]         v1.6.0     -> v1.6.0
 * [new tag]         v1.6.1     -> v1.6.1
 * [new tag]         v1.7.0     -> v1.7.0
 * [new tag]         v1.8.0     -> v1.8.0
 * [new tag]         v1.8.1     -> v1.8.1
 * [new tag]         v1.8.2     -> v1.8.2
 * [new tag]         v1.9.0     -> v1.9.0
 * [new tag]         v1.9.1     -> v1.9.1
fatal: refusing to merge unrelated histories
```
fatal ?

ssh into ryzen2
![image](https://user-images.githubusercontent.com/1365031/212336687-6f293d2c-a9db-494e-b679-e4bda58324c2.png)

Run tmux
![image](https://user-images.githubusercontent.com/1365031/212336798-f8c7157a-13ff-46f0-9413-bae7e781990e.png)

The process info via `ps axf`
```
 7908 ?        Ss     0:00 /usr/sbin/sshd -D
13721 ?        Ss     0:00  \_ sshd: deano [priv]
13824 ?        S      0:00      \_ sshd: deano@pts/16
13825 pts/16   Ss     0:00          \_ -zsh
13953 pts/17   Ss+    0:00              \_ -zsh
22611 pts/16   S+     0:00              \_ tmux
```

Interesting - it appears that the new tmux session is somehow attached to another parent though ?  This is the only `ps axf` running
```
 9607 ?        Ss   489:42 tmux
 1779 pts/2    Ss+    0:11  \_ -zsh
 2798 pts/7    Ss+    0:08  \_ -zsh
 6889 pts/8    Ss+    0:24  \_ -zsh
27969 pts/13   Ss+    1:11  \_ -zsh
 7680 pts/12   Ss+    0:04  \_ -zsh
18757 pts/4    Ss     0:01  \_ -zsh
20204 pts/4    S+     0:01  |   \_ /usr/bin/python3 /usr/local/bin/pipenv shell
20523 pts/5    Ss+    0:22  |       \_ /bin/zsh -i
22572 pts/9    Ss+    0:20  \_ -zsh
19049 pts/10   Ss+    0:22  \_ -zsh
30078 pts/11   Ss+    0:18  \_ -zsh
31886 pts/14   Ss+    0:17  \_ -zsh
22612 pts/18   Ss     0:00  \_ -zsh
22778 pts/19   Ss+    0:00  |   \_ -zsh
25220 pts/18   R+     0:00  |   \_ ps axf
```

Exiting all the other tmux sessions and trying again - this is a clean ssh into ryzen2
![image](https://user-images.githubusercontent.com/1365031/212338416-73fbea1d-4224-446d-b650-ba6054dae8ef.png)

Running tmux
![image](https://user-images.githubusercontent.com/1365031/212338540-233761f6-df22-4031-8798-040d08e9ccdc.png)

And that's it.  So having an existing tmux seems to pull the new tmux sessions into it, and the new one inherits the environment space of the first running one (which wasn't via ssh).  And to confirm, now running a tmux session local on ryzen2, it gets the user@hostname, since it inherits the env space from the tmux session via the ssh test.

Which makes sense - tmux is client/server.  First one starts a daemon that any subsequent ones attach to.

Maybe only check the **SSH_CONNECTION** var ?

**Comment by romkatv** [comment]
You need to have the latest version of powerlevel10k on ryzen2. What you have on other machines doesn't matter.

Keep in mind that an error on `git pull` means it didn't work.

**Comment by romkatv** [comment]
> Maybe only check the SSH_CONNECTION var ?

That would be simply worse. It's also unnecessary given that I've already pushed a fix.

**Comment by Halfwalker** [comment]
All references to tmux are on ryzen2, either locally, or via ssh.  The use case is : ryzen2 is the home desktop machine.  Most stuff happens here, including the tmux sessions I leave running all the time.  When at work I will sometimes ssh into ryzen2 for things, and by default will start up tmux in that ssh session.  It's then that I really _need_ to know a particular terminal is a remote one or not ...

Wonder what the problem is with zprezto/powerlevel10k ?  It was a clean new clone of zprezto, then to be sure I went down into the powerlevel10k dir and `git pull`

Interesting - running `screen` instead works fine.  This is after running `screen`
![image](https://user-images.githubusercontent.com/1365031/212342513-edde8775-9e81-4e88-b3d7-92cf7dc0d7ba.png)

Again, makes sense - screen attaches to the current tty.  But I have a lot of workflows around tmux, so really want to get that working.

**Comment by romkatv** [comment]
I didn't update the powerlevel10k submodule in prezto.

I'd appreciate if you could confirm whether my fix works for you.

**Comment by Halfwalker** [comment]
Should I clone powerlevel10k clean into `~/.zprezto/modules/prompt/external/powerlevel10k` ?

**Comment by romkatv** [comment]
The best would be to clone powerlevel10k to a separate directory and modify your zshrc so that if sources powerlevel10k and nothing else.

**Comment by Halfwalker** [comment]
OK, installed zsh and just powerlevel10k on another machine.  ssh'ing into it (named xeon.local)
![image](https://user-images.githubusercontent.com/1365031/212351288-2a5c80ef-28fe-4b41-a1ac-c51bad5e12c9.png)

Then running tmux
![image](https://user-images.githubusercontent.com/1365031/212351374-dbd4de66-02ee-4232-998c-5167af044436.png)

Which is as expected, since it's the first tmux session.  Then, running tmux on the xeon.local console FIRST (so there's an existing local non-ssh tmux daemon)
![image](https://user-images.githubusercontent.com/1365031/212351843-3e0a5639-7b97-4c56-9de2-cd0b771d1f5e.png)

And it works :)  So now, just need to get powerlevel10k updated in zprezto :smiley:

**Comment by romkatv** [comment]
Thanks for verifying! Closing as fixed.

I'll send a PR to prezto tomorrow.

**Comment by romkatv** [comment]
> I'll send a PR to prezto tomorrow.

https://github.com/sorin-ionescu/prezto/pull/2030
