### ISSUE TITLE
Prompt style doesn't show up in p10k configure - git bash windows

### ISSUE THREAD

**Issue by devcaco** [romkatv/powerlevel10k#2157]
Hello. I'm in windows 11 with the Git Bash Terminal and I installed oh my zsh and powerlevel10k. How ever the p10k configuration wizard does not asks for the prompt style. It goes directly to the diamond question..

![Screen Shot 2023-01-15 at 10 14 27 AM](https://user-images.githubusercontent.com/41708561/212549555-8079c654-1b91-4ba4-b7c7-f925922448d9.png)

Any ideas how I can configure the style?

**Comment by romkatv** [comment]
That's always the first question in the wizard. Try answering it,

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by devcaco** [comment]
Thanks. I found the problem. I was using Mintty as the terminal and had to change the option Term=xterm and set it to 256Color.

**Comment by romkatv** [comment]
Thanks for the update.
