### ISSUE TITLE
Truncated path after activating a python virtual environment

### ISSUE THREAD

**Issue by idantene** [romkatv/powerlevel10k#2158]
EDITED: Nevermind, I missed the `shorten`-related options.

**Comment by romkatv** [comment]
The current directory gets automatically shortened to give you more space for typing commands. Specifically, by default powerlevel10k will try to give you at least 40 columns and at least 50% of the terminal width for typing commands. This is configurable here: https://github.com/romkatv/powerlevel10k/blob/a066b55f855c8e488d3ea9e26e861bdd5ecd4fe8/config/p10k-lean.zsh#L257-L270

Also see https://github.com/romkatv/powerlevel10k#current-directory-that-just-works.

**Comment by romkatv** [comment]
In the future please don't delete the content of your issue. It can be helpful for future users.

**Comment by idantene** [comment]
@romkatv Sorry, I regretted opening the issue once I found this (had a D'oh moment).

I'll undo that edit, and thanks for your super-fast reply!
