### ISSUE TITLE
Not displaying git status on some repo

### ISSUE THREAD

**Issue by volpeo** [romkatv/powerlevel10k#216]
Hi there, 

I've been a user of oh-my-zsh for years and I wanted a cool upgrade with powerlevel10k.
It worked like a charm until I opened an old project, it doesn't display **git status** on this repo.

Facts:
- it works on a recent repo
- it works well without powerlevel10k (with default oh-my-zsh theme)
- it doesn't work even with base configuration
- it doesn't work even on master branch (on foodtruck delivery repo)
- `echo $VCS_STATUS_LOCAL_BRANCH` respond with an empty line on the non working repo

Here is a screenshot of one repo working well, one not so much:
<img width="950" alt="Capture d’écran 2019-09-15 à 14 12 57" src="https://user-images.githubusercontent.com/466015/64921493-24a70c00-d7c4-11e9-838c-7e8dd9d0f9ff.png">

I tried this:
- put `GITSTATUS_ENABLE_LOGGING=1` in my `.zshrc`
- `cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K` that gave me a log with this error:

```shell
[2019-09-15 14:35:44 000000011b31e5c0 ERROR src/git.cc:107] !git_stash_foreach(repo, cb, &res): failed to parse signature - malformed e-mail
[2019-09-15 14:35:44 000000011b31e5c0 INFO src/response.cc:69] Replying without git status
[2019-09-15 14:35:44 000000011b31e5c0 ERROR src/gitstatus.cc:177] Error processing request: "1568550944.3620100021 _p9k_vcs_resume 0" for "/Users/sylvain/Work/FoodtruckAgency/foodtruck_
```

Can't find anything valuable about that, and I don't understand why it works without powerlevel10k.

Does anyone has a clue on this?

**Comment by volpeo** [comment]
Just figured out that it was stashed changes that was breaking everything (should have read the log more than twice). Maybe it was missing an email in the config in the past when I stashed things.
**Dropped them all fixed it**

**Comment by romkatv** [comment]
Thanks for the report. I've submitted https://github.com/romkatv/gitstatus/commit/923303be2a2a9450d3657cdf92e67eb938760e6f to report zero stashes for Git repositories with broken stashes. I don't have an ETA for the next release but I undrestand that you've solved your problem by deleting broken stashes.
