### ISSUE TITLE
Git status not visible for some repositories

### ISSUE THREAD

**Issue by lucianbc** [romkatv/powerlevel10k#2161]
In some repositories, p10k does not show the git status in my prompt. For other repositories, it does. This is unrelated to the terminal session or anything else. If I just `cd` from one repo to another, for some repos I get the git status, for others I don't. This seems to be machine related, as for one repo I get the git status on my remote machine, but not on my local one. Some repos are broken on both remote and local machine.

Do you have any suggestion for how to debug this?

**Comment by romkatv** [comment]
Some of your repos probably use sparse checkout or split index. Powerlevel10k doesn't support that because libgit2 doesn't. If you don't really needs these features, consider disabling them.

**Comment by lucianbc** [comment]
@romkatv yes, that was indeed the issue. Thank you!
