### ISSUE TITLE
Extra breathing room for the history when the transient prompt is enabled

### ISSUE THREAD

**Issue by raxityo** [romkatv/powerlevel10k#2163]
Hi, is there a way to customize the space in the command history between the executions when the transient prompt is enabled?

For example, in the following screenshot, I would like to add an extra empty line between each execution where the arrows are:

![](https://user-images.githubusercontent.com/767683/213494294-79ec6a24-fa32-4fe3-8f6d-2f9158419cb6.png)

Thanks!

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and replace `typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true` with this:

```zsh
p10k-on-pre-prompt() p10k display empty_line=print
```

**Comment by raxityo** [comment]
Aha, that's it! Thanks so much! 💜

**Comment by olearydj** [comment]
When using the pre-prompt() code above, a diamond character is printed in the blank line. Is it possible to avoid this?

<img width="410" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/42705243/03e4abec-31fd-4a20-b5b6-e933bfe88b11">

**Comment by olearydj** [comment]
@raxityo brilliant - thanks so much!
