### ISSUE TITLE
Icons missing or not working

### ISSUE THREAD

**Issue by hotsno** [romkatv/powerlevel10k#2167]
The patched Meslo Nerd font seems to be missing some icons or there are some issues displaying them.

<img width="103" alt="image" src="https://user-images.githubusercontent.com/71658949/213627159-846426bc-9b49-46b6-b30a-0e19497e40b6.png">

With stock Meslo Nerd font: 

<img width="172" alt="image" src="https://user-images.githubusercontent.com/71658949/213627736-9dbe07aa-ab75-46c7-bde8-b3dc23efbbc9.png">

Here is what I get when I highlight it and copy/paste:  
Not sure if that's helpful, I'm not knowledgable about this.

Edit: I guess it's because this patched font hasn't been updated in a while, huh. Any chance it could be updated?

**Comment by romkatv** [comment]
You are correct, MesloLGS NF predates these icons. I'll see if I can rebuild it.

For future reference, that lightning symbol is U+EA86 (nf-cod-symbol_event).

**Comment by 8FordPrefect8** [comment]
I see that the font size in the above picture doesn't fit the rest for many symbols.
I just yesterday installed and configured p10k and noticed the same. My Arch icon and my home house icon are tiny and not affected by changing the size, whereas the check and cross and hour glass are affected by it.

**Comment by romkatv** [comment]
@8FordPrefect8 That's the reason I've made MesloLGS NF in the first place.

**Comment by 8FordPrefect8** [comment]
Hmm I installed the patched version from AUR and have this issue. The provided picture above with stock Meslo NF doesn't seem to have it. Might it be worth trying the stock one? Benefit is, it is in official repo.

**Comment by romkatv** [comment]
@8FordPrefect8 Please open a new issue. Describe what you do, what you expect and what you observe.

**Comment by romkatv** [comment]
I've opened #2217. Closing all issues that require rebuilding the font.
