### ISSUE TITLE
powerlevel10k is expanding hash and directory highlight is taking a lot of time.

### ISSUE THREAD

**Issue by kpal99** [romkatv/powerlevel10k#2168]
Hi, My directory structure is quite complex. Right now, `POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique` is set. 
So, the prompt takes a lot of time to highlight the parts of directory, which it will eventually use to shorten directory path preserving uniqueness (I guess). 
I used hashes in zshrc to remedy that 
```
hash -d repo=/path/to/my/code/repo
hash -d rfoobar=/foo/to/my/code/bar
```
When I am doing `cd ~repo` the prompt is showing `> ~repo`
but when I am doing `cd ~foobar` the prompt is expanding to full directory path and doing all the highlight. 
I want hashes to be in the prompt and not find uniqueness in underlying directory structure until the hash. 
Is there something wrong in my way of implementing hashes? Any help in the matter would be highly appreciated.

**Comment by romkatv** [comment]
> So, the prompt takes a lot of time to highlight the parts of directory

Could you clarify what this means? Is something being slow? If so, what is being slow from your point of view?

> but when I am doing `cd ~foobar` the prompt is expanding to full directory path and doing all the highlight.

Please use real hash names and real directory mappings, otherwise it's unclear what's going on. If the directory names contain sensitive information, replace some characters with `X` but do not change the number of characters and do not change slashes.

**Comment by kpal99** [comment]
> Could you clarify what this means? Is something being slow? If so, what is being slow from your point of view?
Let's first talk without the hashes, 
when i am doing `cd /afs/cern.ch/work/k/kpal/private/` prompt is getting stuck for a lot of time (around 10-20 sec) and highlighting `afs` and `private` of the directory path. While it's stuck I am not able to type and do things. The prompt stucks only once, for the first time when I do `cd /afs/cern.ch/work/k/kpal/private/` after a login (and expands every time with highlight). 
I defined the hashes as:
```
hash -d eos=/eos/user/k/kpal
hash -d afs_pr=/afs/cern.ch/work/k/kpal/private/
```
when I do `cd ~eos`, the prompt is `> ~eos`
but when I do `cd ~afs_pr` the prompt becomes `> /afs/cern.ch/work/k/kpal/private` and is getting stuck (for the first visit to ~afs_pr after login) for a lot of time (around 10-20 sec) and highlighting `afs` and `private` of the directory path.

**Comment by romkatv** [comment]
I'm unable to reproduce this. If I execute `hash -d afs_pr=/afs/cern.ch/work/k/kpal/private` followed by `cd ~afs_pr`, prompt shows `~afs_pr`.

Could you attach your `.zshrc` and `.p10k.zsh`?
