### ISSUE TITLE
Gitstatus not updating asynchronously

### ISSUE THREAD

**Issue by m4kamran** [romkatv/powerlevel10k#2172]
Hi,

I installed powerlevel10k with oh-my-zsh on a macos ventura, but I the git status indicator is not updated in the background. It only updated the status when I press enter.

But from what I understand it should call git status in the background and update the prompt right?

**Comment by romkatv** [comment]
Prompt refreshes only when you execute a command or press enter without a command. See https://github.com/romkatv/gitstatus/issues/368#issuecomment-1387269889 if you want to refresh prompt periodically.

**Comment by m4kamran** [comment]
> Prompt refreshes only when you execute a command or press enter without a command. See [romkatv/gitstatus#368 (comment)](https://github.com/romkatv/gitstatus/issues/368#issuecomment-1387269889) if you want to refresh prompt periodically.

How expensive in terms of performance do you think it would be If we run it let's say every 5 seconds?

**Comment by romkatv** [comment]
Depends on the size of the git repo. Try it and check system resource usage.
