### ISSUE TITLE
一个问题 A problem

### ISSUE THREAD

**Issue by linux-rm** [romkatv/powerlevel10k#2173]
![Screenshot](https://user-images.githubusercontent.com/100938047/214463257-7662850c-ed39-435b-865e-fe1a826142c4.jpg)

在调整终端大小时,终端混乱
When resizing the terminal, the terminal is confused

===

提示:
Tips:

ESC[H                  to(0, 0)
ESC[{x};{y}H
ESC[{x};{y}f         to(x,y)

ESC[#A                up
ESC[#B                down
ESC[#C                right
ESC[#D                left

ESC[#E                down # lines and x=0
ESC[#F                up # lines and x=0

ESC[#G                y=#
ESC[6n                 ask where
ESC[M                  up 1 line
ESC[7                   save (DEC)
ESC[8                   return (DEC)
ESC[s                   save (SCO)
ESC[u                   return (SCO)

===

ESC[3J                 clear saved line
ESC[K                   same as ESC[0K
ESC[0K                 clear to line end
ESC[1K                 clear before
ESC[2K                 clear the line

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by linux-rm** [comment]
OK
