### ISSUE TITLE
The _p9k_upglob function should ignore directory names matching with the parameters

### ISSUE THREAD

**Issue by gandalfmagic** [romkatv/powerlevel10k#2175]
It would be useful if the `_p9k_upglob` could ignore every directory whose name matches one of the parameters (if it make sense for all the use cases of the function).

For example I have a directory called `workspace.java` in my home directory, and so the java version is always shown in the prompt.

**Comment by romkatv** [comment]
> I have a directory called workspace.java in my home directory, and so the java version is always shown in the prompt.

Thank you, this part is useful. Fixed.
