### ISSUE TITLE
low contrast for jq output on null values

### ISSUE THREAD

**Issue by mcandre** [romkatv/powerlevel10k#2177]
Hi,

I rather enjoy powerlevel10k!

Unfortunately, I noticed a conflict in a powerlevel10k color scheme vs. jq color scheme. In short, documents with `null` values can render with low contrast, basically dark-on-dark.

https://github.com/mcandre/dotfiles/blob/master/.p10k.zsh

https://stedolan.github.io/jq/

As a workaround, I am disabling color for jq by aliasing it to `jq -M`. However, I would like some advice for how to resolve the color conflict. Perhaps jq could apply a light background color to help frame the dark foreground color.

Related:

https://github.com/stedolan/jq/issues/2113

**Comment by romkatv** [comment]
Powerlevel10k has no effect on the content and colors of the output of `jq`. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect.
