### ISSUE TITLE
Display subshell in prompt

### ISSUE THREAD

**Issue by larstomas** [romkatv/powerlevel10k#2178]
Hi, 
Just installed powerlevel10k.
Is it possible to show current shell level ($SHLVL) or the number of the subshell ($ZSH_SUBSHELL) in p10k prompt?

**Comment by larstomas** [comment]
https://zsh.sourceforge.io/Doc/Release/Parameters.html#index-SHLVL

**Comment by romkatv** [comment]
You can do that with a custom prompt segment. Search for "example" in `~/.p10k.zsh` and see `p10k help segment`.

**Comment by larstomas** [comment]
Thank you, for the quick answer!
