### ISSUE TITLE
p10k theme occupies `meta key` from tmux

### ISSUE THREAD

**Issue by spgyip** [romkatv/powerlevel10k#2179]
p10k is an excellent theme for me, but there is a `meta key` trouble with tmux.

I am using `meta key` as bind-key on tmux handling pane/window jobs, for example 

```
# Split panes
bind-key -T root -N "Split horizonal window" M-\\ split-window -h
bind-key -T root -N "Split vertical window" M-- split-window -v
```

and also there are some default bind keys in tmux

```
 M-n         Move to the next window with a bell or activity marker.
 M-o         Rotate the panes in the current window backwards.
 M-p         Move to the previous window with a bell or activity marker.
```

It seems p10k occupies the `meta key`, and all these bind keys are useless.

Any suggestion?

**Comment by spgyip** [comment]
Maybe it's my iTerm2 problem, leave it ..

**Comment by romkatv** [comment]
Powerlevel10k has no effect on key bindings. It only provides prompt.
