### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by AdonisN** [romkatv/powerlevel10k#218]
I ran the command for installing the recommended font for debian and it just messed up my terminal and i can barely read anything. How can I reset back to the default font?

**Comment by romkatv** [comment]
That sounds awful!

> I ran the command for installing the recommended font for debian

The documentation for Powerlevel10k doesn't mention "debian", so I'll need extra information to know what happened.

- Which command did you run?
- What's your Terminal?

Please attach a screenshot of your messed-up terminal.

**Comment by AdonisN** [comment]
I ran `sudo apt install libglib2.0-bin && gsettings set org.gnome.desktop.interface monospace-font-name 'MesloLGS NF 11``. Now things look like this (only in the terminal so far, don't know if anything else is messed up like this)
![Screenshot from 2019-09-16 15-05-50](https://user-images.githubusercontent.com/31827201/64999266-1edd2380-d8b5-11e9-8f55-9c61ed4a2653.png)
Also, directories aren't color coded (nothing is). Before I had blue directories, green executables and so on.

**Comment by AdonisN** [comment]
Also, I really like how it shows it the image you posted for this shell, but mine doesn't show the "Master" part. Since we're already here, I wanted to suggest an option for the frame while setting up p10k.
![Screenshot from 2019-09-16 15-17-48](https://user-images.githubusercontent.com/31827201/64999750-ed655780-d8b6-11e9-972d-f9b55d674ea7.png)
I would like there to be an option to have (2) with (3); So the frame with the green arrow.


Another issue is that while im doing ``p10k configure`` the first question it ask: Whether it looks like a diamond. I get this weird symbol...
![Screenshot from 2019-09-16 15-24-28](https://user-images.githubusercontent.com/31827201/64999931-9d3ac500-d8b7-11e9-9ee0-3830f587de7e.png)

**Comment by romkatv** [comment]
Judging by your screenshot, your terminal is configured to use a non-existing font. Run `fc-list | grep 'MesloLGS NF'`. If there is nothing in the output, the font is indeed missing. Have you followed the [instructions](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k) for installing this font?

> Download these four ttf files:
> - [MesloLGS NF Regular.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf)
> - [MesloLGS NF Bold.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold.ttf)
> - [MesloLGS NF Italic.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Italic.ttf)
> - [MesloLGS NF Bold Italic.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold%20Italic.ttf)
>
> Double-click on each file and press "Install". This will make `MesloLGS NF` font available to all
applications on your system.

(On Debian you can also install fonts by copying them to `~/.local/share/fonts` and then running `fc-cache -fv ~/.local/share/fonts`.)

If for some reason you are unable to install MesloLGS NF, you can set your font to something else. To get the list of installed fonts you can use either `fc-list` (command line mode) or `gnome-font-viewer` (gui). To set your font, use either `gsettings` like before or install GNOME Tweaks with `sudo apt install gnome-tweak-tool`, run `gnome-tweaks` and change *Fonts → Monospace*.

> I would like there to be an option to have (2) with (3)...

You can choose *Full* frame during the configuration, then open `~/.p10k.zsh`, search for `prompt_char` and uncomment this line:

```zsh
      # prompt_char           # prompt symbol
```

**Comment by AdonisN** [comment]
Thanks a lot. I have another question: I'm missing my settings apps

**Comment by AdonisN** [comment]
Thank you! And... something came up now. I just logged in a while ago and
the terminal is highlighting everything. When Im root (does not have zsh)
its not doing it. So wanted to ask if you'd know how to go about fixing it.
Been searching on the web but everything I get is on how to highlight
things; i want to un-highlight. Heres a screenshot of the terminal.

**Comment by AdonisN** [comment]
Alright, the highlighting has somehow fixed on its own. But my directories
aren't highlighted. Im thinking about reinstalling p10k to see if that
works. What do you think?
