### ISSUE TITLE
underline when I type

### ISSUE THREAD

**Issue by bunnycodego** [romkatv/powerlevel10k#2180]
When I type for example :  cd Desktop, there is an underline under Desktop, how can we disable this underline? Thank you!
![iShot_2023-02-03_10 34 03](https://user-images.githubusercontent.com/81451316/216643325-a4a7c0fe-3bd2-4634-afa0-359af84974d3.jpg)

**Comment by romkatv** [comment]
You've likely installed https://github.com/zsh-users/zsh-syntax-highlighting. The underline is telling you that there is indeed a file or directory with that name.

In any case, this isn't in the department of powerlevel10k. Closing.

**Comment by bunnycodego** [comment]
oh that makes sense! thank you!
