### ISSUE TITLE
Ruby version in prompt disappears when using rbenv with Ruby 3.2.0

### ISSUE THREAD

**Issue by gwillcox-r7** [romkatv/powerlevel10k#2181]
For some reason, only when using Ruby 3.2.0 in a .ruby-version file in the current directory and when one has Ruby 3.2.0 installed, the prompt stops showing the currently used Ruby 3.2.0 version.

Here is what it looks like with Ruby 3.0.5 as the .ruby-version file and Ruby 3.0.5 installed:

![image](https://user-images.githubusercontent.com/63261883/216727781-a490ed82-4053-4433-8cad-a55b474a52f6.png)

However lets change this to Ruby 3.2.0 now:

![image](https://user-images.githubusercontent.com/63261883/216727914-6772898f-b50d-44e9-a70a-5bf31a7d5bb0.png)

Not sure why this is occurring as if I change it to a nonexistant Ruby version it returns fine:

![image](https://user-images.githubusercontent.com/63261883/216728009-600dab27-6011-4335-9128-c2d7d9b1819e.png)

**Comment by romkatv** [comment]
You can customize the display of `rbenv` prompt segment by editing `~/.p10k.zsh`. The relevant parameters are here: https://github.com/romkatv/powerlevel10k/blob/a30145b0f82d06770e924e9eac064ed223a94e6b/config/p10k-classic.zsh#L1088-L1099

**Comment by gwillcox-r7** [comment]
Thanks looks like I misread one line and didn't notice it would hide the display if it was the same as `global`.  Bit confusing that the default settings both state that it will hide the Ruby version if it doesn't come from `shell`. `local`, or `global` yet the next line down just hides `global` by default, which seems to conflict the purpose of setting it within `POWERLEVEL9K_RBENV_SOURCES` earlier? Just a thought though, as I found this confusing upon review.

In any case, going to close this issue down as setting `typeset -g POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=true` solved this for me.

**Comment by romkatv** [comment]
The comments are correct. Both parameters work as described.
