### ISSUE TITLE
Update nerd font KUBERNETES_ICON to use actual kubernetes icon.

### ISSUE THREAD

**Issue by tmoschou** [romkatv/powerlevel10k#2184]
The nerd font / material design Kubernetes icon is now available since nerd-font v2.3.0. See https://github.com/ryanoasis/nerd-fonts/issues/444

Currently using Unicode Helm Symbol U+2388 (⎈) rather than U+F10FE 
<img width="149" alt="Screenshot 2023-02-06 at 2 35 43 pm" src="https://user-images.githubusercontent.com/5567550/216881510-172891fc-c8a6-45c1-9c46-18bce37c9f32.png">

It will require users have an updated version of nerd-font (v2.3.0+), which updates the material design icon set.

Semi-related, should be noted from the [nerd-font v2.3.0 release notes](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.0).

> **Material Design Icons**
> With this release the Material Design Icons are updated. Note that the old codepoints are deprecated now and new codepoints are used. The old codepoints are still available (and not updated) to make the transition as smooth as possible for users of the MDIs.
> 
> **Please change your setup to use the new codepoints!**
> 
> The old codepoints will be dropped with v3.0.0 because they are wrong/forbidden and cause a lot of problems for people that use non-latin letters. The old codepoints are F500 - FD46. The new codepoints are F0001 - F1AF0. The [cheat sheet](https://www.nerdfonts.com/cheat-sheet) can be used to find the new codepoints.
>
> If you are interested in the reasons, https://github.com/ryanoasis/nerd-fonts/issues/365 is the main thread.

I'm not sure if powerlevel10k can do some version detection of nerd font, `< v2.3.0`, `== v2.3.x`, `>= v3.0.0`

**Comment by romkatv** [comment]
I've opened #2217. Closing all issues that require rebuilding the font.
