### ISSUE TITLE
Time it 'took' not showing, displaying a tool icon instead

### ISSUE THREAD

**Issue by jkemp814** [romkatv/powerlevel10k#2185]
Hello everyone,

I have a question about the powerlevel10k plugin on Fedora Linux 37 Silverblue, using GNOME Terminal, ZSH, Oh-My-ZSH.

To the right side prompt, where what looks like should be a timer, show instead a little gear/tool icon. (command_execution_time?)

Do I need a special package installation to display, what I think should be, the timer? In the pictures posted, I see 5s, as if it saying it took 5s for the command to carry out? I'm using Nerd Font Iosekva fonts, which are excellent at symbols. During the config, all symbols matched.

Here is a screenshot:
![Screenshot from 2023-02-07 16-06-30](https://user-images.githubusercontent.com/12059343/217417737-65422eab-19af-4ae2-ac0c-dd721bcd32ac.png)

**Comment by jkemp814** [comment]
Okay, so I went into another 'toolbox' in Fedora Silverblue and noticed for the first time, the hostname of the toolbox is showing next to that 'tool icon'. Excellent!

![Screenshot from 2023-02-07 22-01-08](https://user-images.githubusercontent.com/12059343/217439286-28b78463-16ac-488a-87a4-cb1a12045919.png)

Those of us in the Fedora Silverblue community have long ask for a way to know which toolbox we are in. They all display fedora-toolbox-37, ot which ever version Fedora Silverblue you are using, or which image the toolbox is running. 

Can I ask which package that segment may be using to get that information? Because the top image I posted is another toolbox, name fedora-toolbox-37.  Which only shows the tool icon, nnot the hostname. So there must be a package in the fedora-develop-37 toolbox reporting the actual name of the toolbox.

**Comment by jkemp814** [comment]
How do I determine what the second segment on the right? The 18.12.1 with the home looking icon?

**Comment by jkemp814** [comment]
I found out what the second segment is: node_version # node.js version

**Comment by romkatv** [comment]
> Do I need a special package installation to display, what I think should be, the timer?

This segment is called `command_execution_time` and it's enabled by default. Try running `sleep 5` and see if it shows up. If it doesn't, you need to enable it in `~/.p10k.zsh`. Also note this parameter: https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-classic.zsh#L539-L540

It's unclear to me whether you've asked any other questions that you haven't consequently answered yourself. If you did, please post them again.

**Comment by jkemp814** [comment]
I found out that is the toolbox hostname. It works in one toolbox, (dev) but not my regular toolbox. So there seems to be a package in the 'dev' toolbox enabling the toolbox segment to function. That's why I posted the two screenshots. Notice in one it shows the hostname with the tool icon, but not the other. That's one, the first image, only shows the icon/symbol.

**Comment by jkemp814** [comment]
Closes #2185

**Comment by romkatv** [comment]
The segment with the toolbox icon is called `toolbox`. It shows the name of the toolbox you are in. By default it shows just the icon without a name if the name is matches `fedora-toolbox-*`. This name is long and boring (it's the default), so hiding it is a good idea. This is configurable here: https://github.com/romkatv/powerlevel10k/blob/a30145b0f82d06770e924e9eac064ed223a94e6b/config/p10k-classic.zsh#L1486-L1487
