### ISSUE TITLE
powerlevel10k Causes problems with terminal window zoom style

### ISSUE THREAD

**Issue by wangmings** [romkatv/powerlevel10k#2187]
# powerlevel10k There is a problem with setting a different theme to enlarge the terminal window

## In the following demonstration, you can see that every time you zoom in or out of the terminal window, powerlevel10k automatically wraps the text and has a problem with the display style

![text](https://user-images.githubusercontent.com/44308153/217727732-a770294d-0447-4ae3-b8dd-361698c55b97.gif)

## terminal window magnification
![截屏2023-02-09 下午1 44 01](https://user-images.githubusercontent.com/44308153/217728516-89e8d6f1-3698-4bc9-9fa2-79ab221b28aa.png)

## terminal window shrink
![截屏2023-02-09 下午1 44 36](https://user-images.githubusercontent.com/44308153/217728543-f4e3eb77-e5eb-4393-b8c4-4931f1df5d37.png)

## Zoom Terminal Window
![截屏2023-02-09 下午1 48 14](https://user-images.githubusercontent.com/44308153/217729382-d8a4dde4-d8d6-4c48-9c5f-01c537fb6171.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
