### ISSUE TITLE
Change Colors for Old Commands?

### ISSUE THREAD

**Issue by TheZenTester** [romkatv/powerlevel10k#2188]
Hello,

I was curious if it was possible to change the colors for the \*\_DIR\_\*FOREGROUND and \*\_DIR\_\*BACKGROUND variables *of commands which were previously run.  See screenshot below for clarification.

I came across this thread, which was really helpful: https://github.com/romkatv/powerlevel10k/issues/805

I've got two separate .p10k.zsh files, one for my regular terminal & profile - which is a bit more colorful, and a second p10k file (called `p10k-report.zsh`) for when I want to change my profile to add a screenshot to a report, which is intended to be more black/white contrast.

Example of commands run in standard profile, with regular `p10k.zsh`:
![image](https://user-images.githubusercontent.com/96437320/218127487-b8ef52c6-861b-4195-89b3-507489c3f3bb.png)

Changing to the `p10k-report.zsh`, but showing all previous commands as well:
![image](https://user-images.githubusercontent.com/96437320/218127969-dd8a8d6e-329f-40a0-ae3a-0910774aacf1.png)

Switching back to standard profile:
![image](https://user-images.githubusercontent.com/96437320/218128233-15408409-b5a8-460b-bc87-9c358f1eaf87.png)

Notice how while the entire background/command line will change colors two things do not:
1. the commands that were run
2. the DIR_BACKGROUND and DIR_FOREGROUND colors remain for the profile in which it was run

Any advice or guidance on how to change those colors so ALL previous commands, and ALL directory foreground/background values would change, regardless of the profile they were run in, would be greatly appreciated!

**Comment by romkatv** [comment]
It's impossible to change the content of the terminal above the last (current) prompt. This includes text and attributes such as colors.
