### ISSUE TITLE
OVERWRITE vi mode

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#219]
`INSERT` mode can either insert (default) or overwrite characters. It would be nice to indicate which mode is active.

From https://github.com/romkatv/powerlevel10k/issues/64#issuecomment-531585388 by @thetic:

> See descriptions of `overwrite` mode, bound to `R` in `vi-mode`:
> 
> > `ZLE_STATE` (scalar)
> >
> > Contains a set of space-separated words that describe the current zle state.
> > _[...]_
> > The string contains _[...]_ `overwrite` if characters to be inserted overwrite existing characters.
> 
> http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html

**Comment by errantepiphany** [comment]
I might be confused on what this issue is trying to accomplish, but this is what I do:

![p10k_vi-modes](https://user-images.githubusercontent.com/392133/65077800-b308c280-d969-11e9-9c23-210344885db4.png)b

```
POWERLEVEL9K_MODE=nerdfont-complete
POWERLEVEL9K_VI_INSERT_MODE_STRING='  INSERT'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=11
POWERLEVEL9K_VI_COMMAND_MODE_STRING='  NORMAL'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND=10
POWERLEVEL9K_VI_VISUAL_MODE_STRING='  VISUAL'
POWERLEVEL9K_VI_MODE_VISUAL_FOREGROUND=12
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=11
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=10
POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=12
POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=9
POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS}_CONTENT_EXPANSION=' ☰ '
```

The vim icon can be found by looking up "vim" here:
https://www.nerdfonts.com/cheat-sheet

**Comment by romkatv** [comment]
@errantepiphany This feature request is about adding another state to `prompt_char` and `vi_mode` called `OVERWRITE`. Your config doesn't seem relevant, or am I missing something?

**Comment by errantepiphany** [comment]
@romkatv No, I just didn't understand what the feature request was about, that's all. Thanks for correcting me. :)

**Comment by romkatv** [comment]
This is done.

When using `vi_mode` segment, the new mode can be enabled by defining `POWERLEVEL9K_VI_OVERWRITE_MODE_STRING`.

```zsh
POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=OVERWRITE
```

When using `prompt_char`, the new mode can be enabled by defining `POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true`. The prompt symbol in `OVERWRITE` state defaults to` '▶'`. It can be customized by defining `POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION`.

```zsh
POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_CONTENT_EXPANSION=R
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_CONTENT_EXPANSION=R
```
