### ISSUE TITLE
how to show node version only when contains package.json in current directory

### ISSUE THREAD

**Issue by tjx666** [romkatv/powerlevel10k#2190]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/218319046-5bb957ad-0a3f-4833-8c18-24c1c06c89bd.png">

I try:

> typeset -g POWERLEVEL9K_ASDF_NODEJS_SHOW_ON_UPGLOB='package.json'

but doesn't work:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/218319094-dc677f12-7f84-4713-b732-b75ee308c0e5.png">

**Comment by romkatv** [comment]
1. Figure out the name of the prompt segment that you want to be shown only when `package.json` exists in the current directory. You can do this by removing the elements from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` one by one and restarting zsh after every change.
2. Once you know the name of the segment, add the following line to `~/.p10k.zsh`:
   ```zsh
   typeset -g POWERLEVEL9K_<SEGMENT>_SHOW_ON_UPGLOB='package.json'
   ```
   Replace `<SEGMENT>` with the name of the segment with all capital letters.
