### ISSUE TITLE
How to set up multiple command line lines?

### ISSUE THREAD

**Issue by HyeonjungNoh** [romkatv/powerlevel10k#2191]
![KakaoTalk_Photo_2023-02-13-14-03-14](https://user-images.githubusercontent.com/119148065/218374841-3f0d7055-38cc-47fe-bc31-6da6c073d61d.jpeg)

when I finsih setting the powerleve and open the terminal 
and hit enter is displayed like this

: >
: >
: >
: 🍎 > 🏠 ~

but I want it to come out like this.
: 🍎 > 🏠 ~
: 🍎 > 🏠 ~
: 🍎 > 🏠 ~

As in the picture, if you hit source ~/.zshrc, it comes out as you want. 
but when I close the terminal and run it again, 
: > 
: >
: >
: 🍎 > 🏠 ~
stilll comes up.
How should I set it up? Please let me knew.😂

**Comment by romkatv** [comment]
Never use `source ~/.zshrc`. If you want to restart `zsh`, use `exec zsh`.

If you want to disable transient prompt, run `p10k configure` and answer *No* when asked whether you want transient prompt.

**Comment by HyeonjungNoh** [comment]
Thank you very much!
