### ISSUE TITLE
Incorrect "node battery" position in VS Code until the terminal is manually resized

### ISSUE THREAD

**Issue by pripishchik** [romkatv/powerlevel10k#2193]
![2023-02-15_19-32](https://user-images.githubusercontent.com/125473856/219108031-ced0e544-aff8-4387-9e13-fb385d81ba51.png)

**Comment by romkatv** [comment]
It's a bug in VS Code terminal. It reports incorrect size.

**Comment by romkatv** [comment]
You can confirm this by adding the following snippet at the very top of `~/.zshrc`:

```zsh
typeset -p COLUMNS
```

Then open a new terminal and type `typeset -p COLUMNS`. The output must be the same as in the first line. If it's different, it's a bug in the terminal.

**Comment by pripishchik** [comment]
@romkatv 

![2023-02-15_19-44](https://user-images.githubusercontent.com/125473856/219110403-6180b5a7-5add-491a-8367-637e1c7c6932.png)

**Comment by romkatv** [comment]
Resize it and run that command again. My guess is that the terminal isn't really 130 columns wide. You can also try this:

```zsh
repeat COLUMNS; print -n .
```

If this doesn't fill the whole width of the terminal, the terminal is buggy.

**Comment by pripishchik** [comment]
If the terminal gets "killed" and then re-opend - the battery position is correct.
If VS Code closes when the integrated terminal is open/hidden (not "killed") and then reopens, the battery position is incorrect.

![2023-02-15_19-52](https://user-images.githubusercontent.com/125473856/219112255-464d6f36-ccf2-48fb-984f-0303be841471.png)

**Comment by pripishchik** [comment]
![2023-02-15_19-55](https://user-images.githubusercontent.com/125473856/219112973-99ca3855-5bce-4785-96f5-b2dd1491942d.png)

**Comment by romkatv** [comment]
This isn't specific to powerlevel10k or even zsh. You can use `repeat COLUMNS print -n .` and `typeset -p COLUMNS` to see that the terminal is incorrectly reporting its width sometimes. You can see it in your own screenshot.

**Comment by romkatv** [comment]
Your terminal is 141 columns wide but it's incorrectly reporting its own width as 130 in some cases.

Closing as this isn't a powerlevel10k issue or even a zsh issue.

**Comment by pripishchik** [comment]
Yes, true, maybe you could suggest any workaround for this? Like on terminal open run some "re-size" command to not resize the terminal manually every time VS Code opens?

**Comment by romkatv** [comment]
You can open an issue against vscode and ask them for a workaround. It's also likely that many people have already reported this issue and you might be able to find those issues and see resolutions.
