### ISSUE TITLE
Icons not being rendered

### ISSUE THREAD

**Issue by gaurishhs** [romkatv/powerlevel10k#2194]
Hello! I have been using p10k for a while but since yesterday icons are not being rendered in my terminal. In a node + git project this is what i get

```bash
> sc
> cd resultism
~/Desktop/Coding/resultism main !9 ?21                                 18:20:21
> 
```

My `.zshrc`:

```sh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Custom Variables
EDITOR=nano

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.config/zsh/zshhistory
setopt appendhistory

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots) # Include hidden files.

# aliases
--Aliases here----
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# export PATH="/Users/gaurish/.deta/bin:$PATH"

# bun completions
[ -s "/Users/gaurish/.bun/_bun" ] && source "/Users/gaurish/.bun/_bun"

# bun
export BUN_INSTALL="/Users/gaurish/.bun"
# export PATH="$BUN_INSTALL/bin:$PATH"
# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# pnpm
export PNPM_HOME="/Users/gaurish/Library/pnpm"
# export PATH="$PNPM_HOME:$PATH"
# pnpm end
# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

![Screenshot 2023-02-18 at 6 23 04 PM](https://user-images.githubusercontent.com/78847111/219866854-d4461734-d5be-4aae-aab0-e80e1bcf9940.png)

I have tried disabling Instant prompt it still remains as-is

**Comment by gaurishhs** [comment]
Git icon?

**Comment by romkatv** [comment]
If the git icon was shown before in your prompt but is no longer shown, it means the previous prompt config was set to display this icon and the current prompt config is set to not display it. You can generate a new prompt config by running `p10k configure`. At some point it'll ask you whether you want *Many Icons* or *Few Icons*. The first choice will display the git icon, while the second will hide it. This question only affects decorative icons that have virtually no informational value. Functional icons are shown either way. You can verify this by running `sleep 10&` and noticing the icon of a wheel that means you have background jobs.

**Comment by gaurishhs** [comment]
https://user-images.githubusercontent.com/78847111/219935536-803571f1-657f-4ae3-be41-e721e3984846.mov

**Comment by romkatv** [comment]
See FAQ: https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by gaurishhs** [comment]
oh okay.. Thanks
