### ISSUE TITLE
How move username to the left?

### ISSUE THREAD

**Issue by ammnt** [romkatv/powerlevel10k#2195]
Hello, Sir!

First, I just want to say thank you for your great project👏🏼Please explain how to move username to the left - to the beginning of line:

![image](https://user-images.githubusercontent.com/45385632/220591585-a4c1bb9f-c080-4a6c-8a14-3f5ac77bc5ea.png)

Thank you.
Best regards👍🏼

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and move `context` from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`.

**Comment by ammnt** [comment]
@romkatv, thank a lot!🙂
