### ISSUE TITLE
powerline colors broken

### ISSUE THREAD

**Issue by dsolerh** [romkatv/powerlevel10k#2197]
I installed the theme following all the steps in the guide and then when I get to the config the icons are broken in the powerline:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/55502191/221345304-3351e08f-49e3-43d7-a2f8-9845b9d98c71.png">
And also there is almost no spacing between the lines

**Comment by romkatv** [comment]
For powerline glyph badness, see: https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols.

For changing colors, see: https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors.

If you want to adjust line height, check your terminal settings.
