### ISSUE TITLE
prompt status error in MacOs

### ISSUE THREAD

**Issue by shahules786** [romkatv/powerlevel10k#2199]
I installed powerlevel10k as in the documentation. But once I use `exec zsh` I get this error 
```
prompt_status:16: bad math expression: operand expected at end of string
prompt_context:33: command not found: _prompt_segment
${(e)_p9k_t[7]}prompt_dir:245: command not found: _prompt_segment
nano .zshrc
prompt_status:16: bad math expression: operand expected at end of string
```
Can you help?

**Comment by romkatv** [comment]
My guess is that you've defined function `prompt_status` somewhere (perhaps in `~/.zshrc`) and this function invokes `_prompt_segment`, which doesn't exist. The solution here is to delete `prompt_status`.

**Comment by shahules786** [comment]
I had the `powerlevel9k` theme activated in the source. I removed the line and now it works like charm!
if anyone is facing same issue make sure you remove line that looks like this
`source /opt/homebrew/opt/powerlevel9k/powerlevel9k.zsh-theme`
