### ISSUE TITLE
POWERLEVEL9K_PROMPT_ADD_NEWLINE no longer respected

### ISSUE THREAD

**Issue by errantepiphany** [romkatv/powerlevel10k#220]
**OS:** Fedora release 30 (Thirty) x86_64
**Kernel:** 5.2.14-200.fc30.x86_64
**Shell:** zsh 5.7.1

I finally got around to using the "p10k configure" script (with tweaks) vs. hacking up my own .p10k.zsh script several weeks ago, and love what I can do with it. However, in a recent commit on master (and sorry - I don't know which one yet without doing some digging), the **POWERLEVEL9K_PROMPT_ADD_NEWLINE** var no longer does anything.

Here is my relevant ~/.zshrc section (I use zplug):

```
zplug "romkatv/powerlevel10k"
if zplug check "romkatv/powerlevel10k"; then
    [[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
fi
```

Here is my ~/.p10k.zsh script in it's entirety (I stripped out everything else):

```
if [[ -o 'aliases' ]]; then
  'builtin' 'unsetopt' 'aliases'
  local p9k_classic_restore_aliases=1
else
  local p9k_classic_restore_aliases=0
fi
() {
  emulate -L zsh
  setopt no_unset extended_glob
  zmodload zsh/langinfo
  if [[ ${langinfo[CODESET]:-} != (utf|UTF)(-|)8 ]]; then
    local LC_ALL=${${(@M)$(locale -a):#*.(utf|UTF)(-|)8}[1]:-en_US.UTF-8}
  fi
  unset -m 'POWERLEVEL9K_*'
  typeset -ga POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
      dir
  )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  )
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
}
(( ! p9k_classic_restore_aliases )) || setopt aliases
'builtin' 'unset' 'p9k_classic_restore_aliases'
```

It doesn't matter if the **POWERLEVEL9K_PROMPT_ADD_NEWLINE** variable is set to true or false... the result is the same: there is no blank line in between prompts in the terminal anymore.

![no-newline](https://user-images.githubusercontent.com/392133/65046045-dd3c8f00-d92d-11e9-8ecd-6a216eb9c68b.png)

Again, I apologize I don't know which commit it was yet, but _I believe it was within the last couple weeks._

Thank you!

**Comment by romkatv** [comment]
Can you reproduce this with all plugins disabled? For example, do prompts get separated by an empty line when executing the following command?

```zsh
(
  emulate -L zsh
  setopt err_return no_unset
  local tmp && tmp=$(mktemp -d "${TMPDIR:-/tmp}"/p10k.XXXXXXXXXX)
  {
    cd $tmp
    git clone --depth 1 https://github.com/romkatv/powerlevel10k.git
    echo "source ${(q)tmp}/powerlevel10k/powerlevel10k.zsh-theme" >>$tmp/.zshrc
    ZDOTDIR=$tmp POWERLEVEL9K_PROMPT_ADD_NEWLINE=true zsh -d
  } always {
    cd || true
    rm -rf $tmp
  }
)
```

**Comment by errantepiphany** [comment]
@romkatv , sorry for the delayed response - I was in meetings. Yes, the command you provided above does result in empty lines between prompts.

**Comment by romkatv** [comment]
This means there is something in your config files that causes the issue. Can you try to figure out what that is?

**Comment by errantepiphany** [comment]
My ~/.p10k.zsh config, or my ~/.zshrc config? Because my ~/.p10k.zsh config is included in the bug description above, in its entirety.

**Comment by errantepiphany** [comment]
Just FYI, it doesn't matter if I use either of these lines in my ~/.zshrc file. The result is the same:

`zplug "romkatv/powerlevel10k"`

`zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme`

**Comment by errantepiphany** [comment]
Oh, another useful bit of info: After updating to latest master of p10k in github, I started from scratch with a new "p10k configure" - follwing the wizard, and the issue showed there too.

**Comment by romkatv** [comment]
> My ~/.p10k.zsh config, or my ~/.zshrc config?

I don't know what's necessary to reproduce the issue but the information you've provided isn't enough. Can you try to provide sufficient instructions, preferably in terms of code, that I can follow to reproduce this?

Here's what I've tried based on your bug report:

```zsh
docker run -e LANG=C.UTF-8 -e TERM -it --rm fedora bash -uexc '
  dnf install -y zsh git gawk
  git clone https://github.com/zplug/zplug ~/.zplug
  echo "
    POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
    source ~/.zplug/init.zsh
    zplug romkatv/powerlevel10k, use:powerlevel10k.zsh-theme
    zplug check || zplug install
    zplug load --verbose" >~/.zshrc
  exec zsh'
```

This works fine -- there are empty lines between prompts.

Initially I've tried it with your `~/.p10k.zsh` and it also works fine. I've shortened it to just `POWERLEVEL9K_PROMPT_ADD_NEWLINE=true` because nothing else seems relevant there. I suppose your'll be able to reproduce this issue even if your replace the whole content of your `~/.p10k.zsh` with `POWERLEVEL9K_PROMPT_ADD_NEWLINE=true`.

There is something in your configuration that is causing the issue. Please find out what it is.

**Comment by errantepiphany** [comment]
@romkatv I figured it out. :)

```
docker run -e LANG=C.UTF-8 -e TERM -it --rm fedora bash -uexc '
  dnf install -y zsh git gawk
  git clone https://github.com/zplug/zplug ~/.zplug
  echo "

    # backwards compatibility options
    # https://stackoverflow.com/questions/6715388/variable-expansion-is-different-in-zsh-from-that-in-bash
    setopt SH_WORD_SPLIT # makes zsh behave like bash w/r/t variable expansion

    POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
    source ~/.zplug/init.zsh
    zplug romkatv/powerlevel10k, use:powerlevel10k.zsh-theme
    zplug check || zplug install
    zplug load --verbose" >~/.zshrc
  exec zsh'
```

It's the **setopt SH_WORD_SPLIT** that I had in my ~/.zshrc that was causing the problem. I guess this didn't hurt anything in previous versions of p10k, but now it does...

**Comment by romkatv** [comment]
> @romkatv I figured it out. :)

\o/

Fixed!

> It's the setopt *SH_WORD_SPLIT*

Funny. The default zsh behavior (with `SH_WORD_SPLIT` unset) was the primary reason I switched from bash to zsh.

**Comment by errantepiphany** [comment]
LOL. I'm sorry I had bothered you with this!

Perhaps this might be a good addition to the FAQ?

**Comment by romkatv** [comment]
This was a real bug in p10k. Thanks for reporting! I've fixed it. If you update powerlevel10k, you'll get the empty lines even with `SH_WORD_SPLIT`.

**Comment by errantepiphany** [comment]
Updated and confirmed! Thanks so much!
