### ISSUE TITLE
gitstatus problem

### ISSUE THREAD

**Issue by matiux** [romkatv/powerlevel10k#2200]
Sometime I get this warning but I don't understand in the specific when and doing what:
```
gitstatus_stop_p9k_:zle:41: No handler installed for fd 14
gitstatus_stop_p9k_:49: failed to close file descriptor 14: bad file descriptor
```
Can you direct me toward some checks to understand problem in detail?

Are there some info that I can give to you to contextualize the problem?
Thanks

**Comment by romkatv** [comment]
Can you reproduce this problem if you disable everything (all plugins) except for powerlevel10k?
