### ISSUE TITLE
Xshell cannot show the color

### ISSUE THREAD

**Issue by pplmx** [romkatv/powerlevel10k#2202]
I know this is caused by the Xshell, but I have no idea to fix it, do you have any solution?
Thanks in advance.

## Here is the session by the Xshell.
![image](https://user-images.githubusercontent.com/26994103/222400160-9a8d2fd1-046b-4dc7-9cfd-3756a5285230.png)

## And this is from the Windows Terminal
![image](https://user-images.githubusercontent.com/26994103/222400462-bb045183-0754-43bc-905e-33a33a097e5c.png)

## Xshell config
![image](https://user-images.githubusercontent.com/26994103/222400835-7605f0fa-5194-4ea0-8ae5-bf6752fd2b1e.png)

**Comment by romkatv** [comment]
Option 1: Enable 256 colors in Xshell. I don't use Xshell, so I don't know how to do that or whether it can even display 256 colors.

Option 2: Run `p10k configure` from Xshell. The wizard will notice that your terminal cannot display 256 colors and will generate a prompt config that uses only 8 colors.

**Comment by pplmx** [comment]
Thanks your advice.
Here is my final solution. FYI.

- Append the following to `~/.zshrc` on the linux
```shell
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
   export TERM='xterm-256color'
else
   export TERM='xterm-color'
fi
```

**Comment by Konjac-XZ** [comment]
For those of you who came later: perhaps you were expecting consistent behavior with ssh in Windows Terminal.

And you can try this:

![image](https://github.com/user-attachments/assets/1c2563f7-ec62-4e05-bb02-873602ddbc1a)

This option basically solved my problem.
