### ISSUE TITLE
need a way to change prompt separator and replace `~` with absolute path

### ISSUE THREAD

**Issue by galactica147** [romkatv/powerlevel10k#2204]
Hi, thanks for this fatalistic tool to make things much easier to use out of the box! 
After reading the docs, I haven't figured out how to achieve the following two things: 

1. how to change prompt separator between `context` and `dir` so that I could have them in this format: `context:dir`, e.g., username@hostname:/Users/username/work/
2. if I `cd` into a subfolder of home, how could I always replace that `~` with the absolute path in the `dir` of the prompt? 
e.g., 
from:
```
~: cd ~/work/
```
to
```
/Users/username/work: 
```

```
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # os_icon               # os identifier
    context                 # username@hostname
    dir                     # current directory
    vcs                     # git status
    # prompt_char           # prompt symbol
  )
```

Thanks!

**Comment by romkatv** [comment]
Have you replaced `dir` with `dir_joined`?

**Comment by galactica147** [comment]
not when I posted my previous reply, but it seemed to not make any differences when it use `dir_joined` in `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`:
```
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    context                 # username@hostname
    dir_joined             # current directory
    vcs                        # git status
  )
```

**Comment by romkatv** [comment]
Please attach your `~/.p10k.zsh`. You'll need to change the extension to `.txt` to please github.

**Comment by galactica147** [comment]
[p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/10884717/p10k.zsh.txt)

**Comment by romkatv** [comment]
You need to add this:

```zsh
typeset -g POWERLEVEL9K_CONTEXT_LEFT_RIGHT_WHITESPACE=
```

**Comment by galactica147** [comment]
That worked! One last bit, is there a way to turn on and off the folder path abbreviation? 
By default, it'll only show first few characters when possible.

**Comment by romkatv** [comment]
You can disable directory shortening with these parameters:

```zsh
POWERLEVEL9K_DIR_MAX_LENGTH=
POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0
POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0
```

Note that your config already defines these parameters. You need to find them and change their values.

P.S.

What you are doing is very strange. If you are are looking for ways to create a functional prompt, check out https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard.

**Comment by galactica147** [comment]
i'm just trying to make the prompt more `rsync` friendly as I have to do that quite often. Will definitely play with the wizard more and try out the transient mode -- so far I've always been a single-line prompt user. 

All in all, thanks a lot for this great tool and super responsive answers.
