### ISSUE TITLE
current directory is missing from prompt

### ISSUE THREAD

**Issue by p1r473** [romkatv/powerlevel10k#2205]
Hi,
My current directory that usually displays on the prompt is empty
Any idea what could have happened?
![image](https://user-images.githubusercontent.com/9235633/222878064-e51d47c8-a470-492b-803c-5d8be3f983ff.png)

**Comment by romkatv** [comment]
The screenshot shows `/home/pi` as the current directory in prompt. Do you expect something else? Can you describe what you expect to see?

**Comment by p1r473** [comment]
> The screenshot shows `/home/pi` as the current directory in prompt. Do you expect something else? Can you describe what you expect to see?

Where do you see /home/pi?
It just looks black to me.
IT SHOULD say /home/pi but I cant see it.

Are my colors messed up?

**Comment by p1r473** [comment]
I cant see any text there at all. Do you have super vision?
![image](https://user-images.githubusercontent.com/9235633/222885966-84fcc0af-b39a-4f0d-a9d6-60ff7cdde7ff.png)

**Comment by romkatv** [comment]
> Where do you see /home/pi?

It's blue on black within the red rectangle. If it's difficult for you to see blue on black in your terminal, it's a good idea to go to the terminal's settings and change the color scheme.

**Comment by p1r473** [comment]
Oh my goodness I am such an idiot
I had flux on, which makes my screen yellow, as a blue light filter
The blue txt was filtered out

Sorry, thats embarrasing lmao

**Comment by p1r473** [comment]
Thanks so much @romkatv 
Keep up the great work!
