### ISSUE TITLE
Directory substitutions

### ISSUE THREAD

**Issue by JulianGodd** [romkatv/powerlevel10k#2206]
Is it possible to replace certain directory names with symbols like in starship.rs?

In their config you put:
```
[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""
```

It will then use these when in directories with the given name instead of the full text

**Comment by romkatv** [comment]
There is no builtin support for this but you can achieve the same effect by using a custom prompt segment for the icons and hiding the real directory with `p10k display` when you have an icon for it.

**Comment by rrpolanco** [comment]
@romkatv Do you happen to have an example for how this can be achieved?
