### ISSUE TITLE
Font inconsistency in VSCode integrated terminal

### ISSUE THREAD

**Issue by uforek** [romkatv/powerlevel10k#2207]
I'm using Gnome Terminal with MonoLisa font. All icons appear fine. When I use VSCode's integrated terminal, using MonoLisa font, the icons appear as [X]. Am I missing something obvious here? I'm totally stumped.

**Comment by romkatv** [comment]
Mono Lisa doesn't have nerd font icons (e.g., U+F306). If GNOME Terminal is able to display this icon, it's either using a different font to start with, or a fallback font with the icons. If the latter, you can configure VSCode to use the same fallback font.

**Comment by uforek** [comment]
> Mono Lisa doesn't have nerd font icons (e.g., U+F306). If GNOME Terminal is able to display this icon, it's either using a different font to start with, or a fallback font with the icons. If the latter, you can configure VSCode to use the same fallback font.

This was the issue. It seems that Gnome Terminal was using a fallback (Didn't know this). By setting a secondary font in VSCode, this fixed the issue.
