### ISSUE TITLE
Separators (Not an issue)

### ISSUE THREAD

**Issue by paulomoran21** [romkatv/powerlevel10k#2208]
I've been trying to customize an specific separator of the prompt but I can't figure out how.
I'm trying to do something like this:
![imagen](https://user-images.githubusercontent.com/101068782/222997751-4cd783c1-2731-483f-a0fa-85b85b8b0d85.png)
I've tried to do empty segments, but the space is to big.
I've also triend to do three consecutive angled seaprators, but it afects to all prompt and can't change color for a specific one.
I don't know how to do it.

**Comment by romkatv** [comment]
Powerlevel10k does not support separators like that.

**Comment by paulomoran21** [comment]
Thanks
