### ISSUE TITLE
How do I change the color of a powerline symbol/separator?

### ISSUE THREAD

**Issue by jby** [romkatv/powerlevel10k#2211]
I've managed to figure out how to move the `user@hostname` to the left by reading the docs, and I've even managed to remove the black background from it, but how do I change the color of the powerline symbol/separator here:
<img width="304" alt="Screenshot 2023-03-07 at 10 58 24" src="https://user-images.githubusercontent.com/1584888/223389178-841e1a65-b844-49cb-ac35-f653f4b4ebde.png">
Since I don't have a black background in my terminal, the completely black symbol sticks out and I'd rather it didn't - so can I change the color of it? If so how?

**Comment by jby** [comment]
It's **only** black when 'in context' on localhost (i.e. without context) it's not black, so it has to be in the context-setup somewhere - I'm just unable to find it apparently...

**Comment by romkatv** [comment]
> Since I don't have a black background in my terminal, the completely black symbol sticks out and I'd rather it didn't - so can I change the color of it? If so how?

This will replace the black triangle in your screenshot with a transparent triangle:

```zsh
typeset -g POWERLEVEL9K_CONTEXT_LEFT_SEGMENT_SEPARATOR='%S%k%F{4}\uE0B0%s'
```

This assumes that your `dir` segment's background color is "4". If it's not, you'll need to replace "4" with the correct number.

> It's only black when 'in context' on localhost (i.e. without context) it's not black, so it has to be in the context-setup somewhere - I'm just unable to find it apparently...

I don't understand what you mean here. Hopefully the code snippet I posted above will allow you to achieve what you want.

**Comment by jby** [comment]
Actually I did set my context background to "", nothing - I removed the '0' in there:
` typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=`
I was hoping I could the same with the separator, but your code above seems to set it to the correct (or at least close enough) color.
Thanks @romkatv!

**Comment by romkatv** [comment]
> your code above seems to set it to the correct (or at least close enough) color.

Do you mean that it's not transparent? Could you post a screenshot?

**Comment by romkatv** [comment]
Keep in mind that you can customize the color of the triangle independently for different context states similarly to how you customize the background color.

```zsh
# When in ssh, make the background and the right triangle transparent.
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_LEFT_SEGMENT_SEPARATOR='%S%k%F{4}\uE0B0%s'
```

**Comment by jby** [comment]
It might be transparent - hard to tell, but I'm satisfied.
Before, above, and after, below: 
<img width="288" alt="Screenshot 2023-03-07 at 11 26 21" src="https://user-images.githubusercontent.com/1584888/223396025-a408bab5-2b9c-4623-8b12-52cda1ace3d1.png">

**Comment by romkatv** [comment]
Thanks for posting a screenshot. It's transparent, as intended. These colors aren't "close", it's literally the same color as the backdrop of your terminal.

**Comment by jby** [comment]
> Keep in mind that you can customize the color of the triangle independently for different context states similarly to how you customize the background color.
> 
> ```shell
> # When in ssh, make the background and the right triangle transparent.
> typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=
> typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_LEFT_SEGMENT_SEPARATOR='%S%k%F{4}\uE0B0%s'
> ```

Yes, I figured - I just couldn't figure out what to look for (SEGMENT_SEPARATOR apparently wasn't obvious enough... :doh: )
👍

**Comment by jby** [comment]
> Thanks for posting a screenshot. It's transparent, as intended. These colors aren't "close", it's literally the same color as the backdrop of your terminal.

👍

**Comment by jby** [comment]
Does that mean that "4" and "" is the same?

**Comment by romkatv** [comment]
> Does that mean that "4" and "" is the same? Or does it depend on context (not as in the 'context' in the prompt)?

Color "4" is blue and "" is the default background/foreground color. There is one exception where "" is equivalent to "0" (the right triangle), which is done for bug compatibility with powerlevel9k.
