### ISSUE TITLE
Console output during zsh initialization detected

### ISSUE THREAD

**Issue by neodev27** [romkatv/powerlevel10k#2213]
I wanted add a figlet lolcat header to my zsh but the warning comes out. I dont want to change it from "verbose", but i dont wanna see the warning too, what i should do?

**Comment by romkatv** [comment]
Put it at the very top of zshrc.

**Comment by neodev27** [comment]
Ok

**Comment by neodev27** [comment]
It worked, thanks mister.

**Comment by romkatv** [comment]
You are welcome.
