### ISSUE TITLE
change color of icon 

### ISSUE THREAD

**Issue by cabraham03** [romkatv/powerlevel10k#2214]
I want to change the color of those icon in the prompt, how could I do it ???
from grey and black to white 
![icons](https://user-images.githubusercontent.com/9662585/223559625-de956f54-1a85-424c-b999-4dfa140d20e0.png)

Thanks

**Comment by romkatv** [comment]
To do that you need to edit `~/.p10k.zsh`.

**Comment by cabraham03** [comment]
yes I know that I need to edit .p10k.zsh, but I don't remember the line, I just have looking for it in the web before to pot it here, but I just didn't found it !!!.... any way thanks !!!

**Comment by romkatv** [comment]
The color of the grey line can be changed by editing parameters whose names start with `POWERLEVEL9K_MULTILINE`. I don't know how you've added the triangle, so I cannot say how to change its color (the default config doesn't have this triangle).

**Comment by cabraham03** [comment]
I found it:
POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND 

thanks !!
