### ISSUE TITLE
Git icon not showing when git tag is active

### ISSUE THREAD

**Issue by pripishchik** [romkatv/powerlevel10k#2219]
![image](https://user-images.githubusercontent.com/125473856/224115156-67ea2a1e-8cc8-4696-9ab5-f9dc461e5018.png)

**Comment by romkatv** [comment]
Please describe the issue: what you do, what you expect, and what actually happens.

**Comment by pripishchik** [comment]
@romkatv I expect git icon instead of "git" when I checkout to git tag.

**Comment by romkatv** [comment]
- If the remote of the current branch is on github, you'll see a github logo.
- If the remote of the current branch is on gitlab, you'll see a github logo.
- If you are not on a branch, or the branch doesn't have a remote, or the remote isn't on github or gitlab, you'll see "git".

Does this help?

**Comment by pripishchik** [comment]
yes, it does, but then how to show github icon when I am on github tag?

**Comment by romkatv** [comment]
You can do it but note that you'll lose information by doing that. Currently, when you see a github logo, you know that `git pull` and `git push` will talk to github.com. If you always display the github logo, it'll be meaningless.

Anyway, here's how you can do it:

```zsh
typeset -g POWERLEVEL9K_VCS_GIT_ICON='\uF113'
```

I'll repeat that it's not a good idea.

**Comment by pripishchik** [comment]
nice, thanks, it works. but I am wondering isn't is possible to determine which icon to display (github, gitlab etc.) when a tag is active instead of a remote branch?

**Comment by romkatv** [comment]
The correct icon is the default one.
