### ISSUE TITLE
Directories w/ no color code

### ISSUE THREAD

**Issue by AdonisN** [romkatv/powerlevel10k#222]
Everything in the terminal, does not have a color code. Like directories and executables.

**Comment by romkatv** [comment]
Do you have reasons to suspect this problem to be related to Powerlevel10k? For example, do you get those colors if you disable Powerlevel10k?

**Comment by AdonisN** [comment]
How to I disable it?

**Comment by romkatv** [comment]
> How to I disable it?

Do the opposite of what you did to enable it.

**Comment by AdonisN** [comment]
I've removed zsh and set my shell back to bash and my directories are color coded (blue). Then, I installed zsh back and put zsh as the shell and the directories aren't color coded.

**Comment by AdonisN** [comment]
I've just added ```--color=auto``` to the ls command. That fixed it, but Im sure there's some other way to set the colors automatically.

**Comment by romkatv** [comment]
> I've removed zsh and set my shell back to bash and my directories are color coded (blue).

Run `bash` followed by `type ls` (you don't have to change your default shell for this). Does it say that `ls` is aliased to `ls --color=auto'? If yes, this is the reason you are getting colors in bash. The alias is likely defined in `~/.bashrc`. You can achieve the same results in zsh by defining the same alias in `~/.zshrc`.

Closing this issue as it doesn't appear to have anything to do with powerlevel10k.
