### ISSUE TITLE
difference among ZSH_THEME and use source ?

### ISSUE THREAD

**Issue by cabraham03** [romkatv/powerlevel10k#2220]
what is the difference among ZSH_THEME="powerlevel10k/powerlevel10k" and source ~/powerlevel10k/powerlevel10k.zsh-theme, which one I need to use ?

its there any problem with ZSH_THEME using Oh My Zsh ?, I have problems to recognize some icons (used in the prompt) that come with the recommended fonts, it just appear as interrogate symbol (?), I'm using a macOS !!!

thanks !!

**Comment by romkatv** [comment]
If you are using Oh My Zsh, then use `ZSH_THEME="powerlevel10k/powerlevel10k"`. If you aren't using Oh My Zsh and have manually cloned powerlevel10k to the home directory, then use `source ~/powerlevel10k/powerlevel10k.zsh-theme`.
