### ISSUE TITLE
Show git user/email

### ISSUE THREAD

**Issue by delanym** [romkatv/powerlevel10k#2221]
How can I add the active git user/email to the prompt?
This will be the global user/email unless a repository user/email has been set.

**Comment by romkatv** [comment]
Powerlevel10k doesn't support this. You can implement a custom prompt segment to display this info. Search for "example" in `~/.p10k.zsh` and see `p10k help segment` for docs.

**Comment by delanym** [comment]
Thanks

``` sh
function prompt_git_email() {
  p10k segment -f red -t $(git config user.email)
}
```

**Comment by quazar-omega** [comment]
I was trying to achieve the same just now and I came up with this to show it only when inside a git repository
```
function prompt_git_user() {
  p10k segment -c "$(git rev-parse --show-toplevel 2> /dev/null)" -b 2 -f 'black' -t "$(git config user.name)"
}
```
But I was wondering if it could be made into an option for the main git segment, since they both pertain to git it would be nice to bundle them together in a format like: 
- `<user.name>@<branch>`
- `<user.email>@<branch>` 
-  `<user.name> | <user.email>@<branch>`

Is it possible? If it, is would it be too slow?

**Comment by romkatv** [comment]
> ```
> function prompt_git_user() {
>   p10k segment -c "$(git rev-parse --show-toplevel 2> /dev/null)" -b 2 -f 'black' -t "$(git config user.name)"
> }
> ```

This is not a good idea because the condition specified via `-c` undergoes parameter expansion and process substitution. Use this instead:

```zsh
if condition; then
  p10k segment ...
fi
```

> But I was wondering if it could be made into an option for the main git segment, since they both pertain to git it would be nice to bundle them together in a format like:
> 
> * `<user.name>@<branch>`
> * `<user.email>@<branch>`
> * `<user.name> | <user.email>@<branch>`
> 
> Is it possible? If it, is would it be too slow?

It's possible. If implemented properly, it won't be slow. If you send a clean PR to https://github.com/romkatv/gitstatus, I'll merge it.

**Comment by quazar-omega** [comment]
> Use this instead

Oh, alright thanks! I thought that the condition had to put into it since there was an option about it, that makes sense though. So it comes out to be:
```bash
function prompt_git_user() {
  if [ "$(git rev-parse --show-toplevel 2> /dev/null)" ]; then
    p10k segment -b 2 -f 'black' -t "$(git config user.name)"
  fi
}
```
correct?

> If you send a clean PR

I'd be glad to try to implement it, could you give me some pointers on what to look at first?

**Comment by romkatv** [comment]
> > Use this instead
> 
> Oh, alright thanks! I thought that the condition had to put into it since there was an option about it, that makes sense though. So it comes out to be:
> 
> ```shell
> function prompt_git_user() {
>   if [ "$(git rev-parse --show-toplevel 2> /dev/null)" ]; then
>     p10k segment -b 2 -f 'black' -t "$(git config user.name)"
>   fi
> }
> ```
> 
> correct?

I don't want to endorse this code because it's slow. It's syntactically correct though.

> > If you send a clean PR
> 
> I'd be glad to try to implement it, could you give me some pointers on what to look at first?

Sorry, I'm not offering to provide guidance on this. I also don't recommend that you actually do this unless you really want to.

**Comment by quazar-omega** [comment]
> I don't want to endorse this code because it's slow

I understand, I just used the method I know so I didn't expect it to be very good, just functional.

> Sorry, I'm not offering to provide guidance on this

It's ok, I'll see if I'm able to figure things out and make a pull request if I succeed, thanks again!
