### ISSUE TITLE
Classes FOREGROUND color only sets icon and slash's path but not the dir - p10k

### ISSUE THREAD

**Issue by hugo-HDSF** [romkatv/powerlevel10k#2227]
On macOS 13.1 (22C65) in iTerm2 I'm trying to customize my shell using p10k.

I've made decent progress with my POWERLEVEL9K_DIR_CLASSES:

the path is white
all my BACKGROUNDS are dark

I hope to specify a dir with a light BACKGROUND and so set a black FOREGROUND, but it only changed the icon and separator color but not the text color, see below:

```
typeset -g POWERLEVEL9K_DIR_CLASSES=(
       '~/work(|/*)'               WORK      ''
       '~/Projets/Android(|/*)'    ANDROID   ''
       '~/Projets(|/*)'            PROJETS   '󰣪')
```

base 1 : 

```
typeset -g POWERLEVEL9K_DIR_PROJETS_BACKGROUND=160
```
result : 

<img width="172" alt="image" src="https://user-images.githubusercontent.com/116161276/225910156-408b91ef-a078-4956-b2d1-40699dcc97d0.png">

problem :

```
typeset -g POWERLEVEL9K_DIR_ANDROID_BACKGROUND=148
typeset -g POWERLEVEL9K_DIR_ANDROID_FOREGROUND=232
```
the result : (all text should be black)

<img width="220" alt="image" src="https://user-images.githubusercontent.com/116161276/225909810-14fc921a-cc2d-48e5-98e0-b91e7c11c722.png">

what's making this behave like that ?

**Comment by romkatv** [comment]
Sorry, I misread the issue. I'll take a closer look later.

**Comment by hugo-HDSF** [comment]
Just bumping the post again 👀

**Comment by romkatv** [comment]
Some dir segments are considered important, so called *anchors*. Anchors are never shortened and they can be styled differently. Shortened segments can also be styled differently. See https://github.com/romkatv/powerlevel10k#current-directory-that-just-works for a short description. There is also a demo there where you can see this in action.

Your config has these parameters:

```zsh
# Color of the shortened directory segments.
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
# Color of the anchor directory segments.
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
```

When the current directory is `~/Projets/Android`, powerlevel10k first checks for `POWERLEVEL9K_DIR_ANDROID_ANCHOR_FOREGROUND` to figure out how to style anchors. This parameter isn't defined, so it falls back to `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND`. This is why `~/Projets/Android` has white-colored segments.

If you are defining `POWERLEVEL9K_DIR_ANDROID_FOREGROUND`, you'll probably want to define `POWERLEVEL9K_DIR_ANDROID_SHORTENED_FOREGROUND` and `POWERLEVEL9K_DIR_ANDROID_ANCHOR_FOREGROUND` as well.

**Comment by hugo-HDSF** [comment]
thank you so much, now I get it ! also just wanted to mention that I really appreciate your work 🙏🏻.
