### ISSUE TITLE
Possible to show actual execution timestamp rather than when prompt was rendered?

### ISSUE THREAD

**Issue by joshfrench** [romkatv/powerlevel10k#2228]
I've seen #917 and the various tickets that refer to it, but I'm wondering if there's a way to update the time segment at preexec so that the timestamp reflects the moment I hit enter, not whenever the prompt was first rendered. In other words, if I start typing a command at 12:00 and then wait 60 seconds before hitting enter, I'd like to see 12:01 in the historical output.

**Comment by romkatv** [comment]
Do you mean this? https://github.com/romkatv/powerlevel10k/blob/cb9788b12a1fade6be631ad905928f9a5f7eb03f/config/p10k-lean.zsh#L1564-L1567

**Comment by joshfrench** [comment]
I do :) Thank you!

**Comment by romkatv** [comment]
You are welcome.
