### ISSUE TITLE
VScode head and tail glitches

### ISSUE THREAD

**Issue by lehoanganh1998** [romkatv/powerlevel10k#2229]
Hi, I just installed power10k. The problem is that it works fine outside but the integrated terminal in VScode has some issue
![image](https://user-images.githubusercontent.com/21298948/226091367-8746d40c-573b-4f03-85e5-78dc5ccaf580.png)
It seem not correctly align

**Comment by romkatv** [comment]
Run `p10k configure` and when it asks you whether the icons fit between the crosses, answer *yes* (because they do with your font).

**Comment by lehoanganh1998** [comment]
i tried but not work. It works in terminator but not in vscode
![image](https://user-images.githubusercontent.com/21298948/226095355-6b8f3527-e50d-4b67-a451-5599ec3384a2.png)
Did i do something wrong here?

**Comment by romkatv** [comment]
If you are using the latest version of powerlevel10k, then this is a bug in vscode. As a workaround, consider using Lean style.

**Comment by SakuraWald** [comment]
> Run `p10k configure` and when it asks you whether the icons fit between the crosses, answer _yes_ (because they do with your font).

This works.
