### ISSUE TITLE
Rainbow theme misaligned on right

### ISSUE THREAD

**Issue by HenryGessau** [romkatv/powerlevel10k#2231]
On Windows 11 with `cmd.exe` in Windows Terminal, with [clink](https://github.com/chrisant996/clink) and [Oh My Posh](https://ohmyposh.dev) installed.

I am using the `powerlevel10k_rainbow` theme that comes with `oh-my-posh`:
https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/powerlevel10k_rainbow.omp.json

The right-edge bracketing characters are misaligned:

![image](https://user-images.githubusercontent.com/1934506/226134312-09ff7e38-e3bc-4da2-aa73-7a603af6e449.png)

**Comment by romkatv** [comment]
Powerlevel10k is a zsh theme. You aren't using it.
