### ISSUE TITLE
Git status is wrong

### ISSUE THREAD

**Issue by pwang-stripe** [romkatv/powerlevel10k#2232]
The git change numbers are wrong after each git write command. Opening a new terminal tab has correct numbers

<img width="685" alt="Screen Shot 2023-03-20 at 5 00 56 PM" src="https://user-images.githubusercontent.com/54011163/226490778-f257f682-1455-49d4-838a-f11afc58dd76.png">

**Comment by pololi-stripe** [comment]
👋 A coworker helped find the issue:
1. `gitstatusd` uses a forked version of `libgit2` that has some performance improvements.
2. git 2.40.0 index.skipHash incompatible with libgit2 https://github.com/libgit2/libgit2/issues/6531

The solution is to 
```
git config --global index.skipHash false
```

**Comment by romkatv** [comment]
Thanks for getting to the bottom of it and posting your findings.
