### ISSUE TITLE
[help] interface name on vpn_ip

### ISSUE THREAD

**Issue by ikuamike** [romkatv/powerlevel10k#2233]
I've read the documentation but not finding a way to do this. Is there a way to have the interface name next to the IP when vpn_ip is enabled?

In my case I have enabled showing of all VPN IPs using POWERLEVEL9K_VPN_IP_SHOW_ALL=true. I've put the icon as shown but I would like to show the interface name instead for example tap0, tun0, tun1.

![image](https://user-images.githubusercontent.com/5783614/226763446-6ef8ad20-8a6d-48b0-9316-3383b6bf7c67.png)

TIA.

**Comment by romkatv** [comment]
Powerlevel10k doesn't have such an option.

**Comment by ikuamike** [comment]
okay, thanks.
