### ISSUE TITLE
Cannot turn off Node.js ("system") version in the right prompt

### ISSUE THREAD

**Issue by gsbabil** [romkatv/powerlevel10k#2238]
Hi @romkatv, Everyone,

I hope you are all doing well.

- 📌 My issue is that the right prompt is always showing the `Node.js` version `system` irrespective of the directory I'm in. 
  - I tried setting the following `NODE` specific variables in `.p10k.zsh` to turn it off, but it still keeps reappearing.

```shell
typeset -g POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=false
typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=false
typeset -g POWERLEVEL9K_NODENV_SOURCES=(shell local)
```

- Ideally, I'd only like this to show up in directories where I have a Node.js project _e.g._ where I have `*.js` or `package.json` files. 

- 📌 Could someone please help me debug this, or point me to the correct settings to turn it off? My freshly generated `.p10k.zsh` file is attached below.  Thanks a lot!

  - 📌 [dot-p10k-zsh.txt](https://github.com/romkatv/powerlevel10k/files/11064380/dot-p10k-zsh.txt)

<img width="1596" alt="image" src="https://user-images.githubusercontent.com/1061108/227583353-6a42e397-a456-4d08-84c8-30cd42649893.png">

**Comment by romkatv** [comment]
Try disabling all node prompt segments: nvm, nodenv, etc.

**Comment by gsbabil** [comment]
Hi @romkatv, 

removing `nvm` from `typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(...)` did the trick.

Thank you!

**Comment by romkatv** [comment]
👍

**Comment by thedarb** [comment]
Oh my god, thank you. This has been driving me nuts for weeks!
