### ISSUE TITLE
Font rendering for MesloLGF NS in iTerm2

### ISSUE THREAD

**Issue by bartonfriedland** [romkatv/powerlevel10k#2241]
Hi, I'm having some challenges with the font rendering on a Mac M2.

The MesloLFG NS font is installed and is selected in the iTerm2 profile as follows:

<img width="1055" alt="Screenshot 2023-03-27 at 21 04 25" src="https://user-images.githubusercontent.com/2925476/228041355-406af400-1db6-4a63-b6a4-c27562e00e7d.png">

However, when I run p10k configure, I get:

<img width="668" alt="Screenshot 2023-03-27 at 21 05 25" src="https://user-images.githubusercontent.com/2925476/228041656-393a87a6-0d5d-41b8-9e53-ef2c6f908bf7.png">

It looks like my encoding is set right:

<img width="766" alt="Screenshot 2023-03-27 at 21 06 43" src="https://user-images.githubusercontent.com/2925476/228041834-d6f15ef5-79e1-4140-acbb-aa6c86a1d05b.png">

What might I try to be able to use the icons and coloured bars?

**Comment by romkatv** [comment]
Uncheck this. 
![image](https://user-images.githubusercontent.com/1282067/228044481-8218cdfb-3460-4961-a19c-07fd4e9c6a2c.png)

**Comment by bartonfriedland** [comment]
Thank you so much! That enabled the icons:

<img width="738" alt="Screenshot 2023-03-27 at 21 28 13" src="https://user-images.githubusercontent.com/2925476/228046497-35344676-764a-499c-b8b8-70d02e4d5725.png">

The glyphs do not show up still as they do on my other mac:

<img width="738" alt="Screenshot 2023-03-27 at 21 31 37" src="https://user-images.githubusercontent.com/2925476/228047114-bfba1f5a-f3c2-4bda-b3ab-f2bfc14fa084.png">

I must be missing something else  - I'd be grateful if you could point me in the right direction.

**Comment by romkatv** [comment]
The font looks fine. If you want to change the prompt style to Classic, run `p10k configure` and choose that.

**Comment by bartonfriedland** [comment]
On the machine that has the prompts already, when I run `p10k configure` I get a prompt choice:
<img width="738" alt="Screenshot 2023-03-27 at 21 52 04" src="https://user-images.githubusercontent.com/2925476/228051360-256b7a25-3390-47c2-b128-76100c891384.png">

However, on the M2 system that I tweaked the alternative font setting, I do not get this - after the checking of the icons and spacing, the wizard goes to the character set screen and never asks about prompt:

<img width="731" alt="Screenshot 2023-03-27 at 21 54 02" src="https://user-images.githubusercontent.com/2925476/228051781-dfd0a03d-9f5c-43e5-a5a0-4f82710945ee.png">

How might I address this?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by bartonfriedland** [comment]
Thanks for this and all of your amazing work. I was able to set these in the iTerm settings here:

<img width="1049" alt="Screenshot 2023-03-27 at 22 23 20" src="https://user-images.githubusercontent.com/2925476/228058502-3f918916-e761-455a-bbba-eaa9958686e8.png">

**Comment by romkatv** [comment]
I'm glad you managed to find a fix.

Interestingly enough, both problems were caused by changing the terminal settings. Your fixes rolled back the settings to their default values. This might suggest that it's best to avoid changing settings until you are sure what they are doing.
