### ISSUE TITLE
Support for prefixes

### ISSUE THREAD

**Issue by illegitimate-egg** [romkatv/powerlevel10k#2246]
I think prefixes should be a segment. It's used by a lot of software, [nix](https://github.com/nix-community/nix-zsh-completions) for instance. When run with `prompt_nix_shell_setup`, the shell should have the prefix `[nix-shell]` but instead the shell does not change at all.

**Comment by romkatv** [comment]
Please describe what you do, what you expect and what you observe.

**Comment by illegitimate-egg** [comment]
When you're in a nix develop environment, the shell is replaced entirely, but that's because develop is obsoleted by shell. The shell command, in a normal scenario, would put a `[nix-shell]` before the rest of your shell, so the entire shell would look like this `[nix-shell](user@system ~)$ `. Is there some way that you can bring support for this into power level 10k?

**Comment by romkatv** [comment]
`nix_shell` prompt segment is supposed to do that. Did you enable it?

**Comment by illegitimate-egg** [comment]
Pretty sure I did, I've got the `prompt_nix_shell_setup` command in my .zshrc

**Comment by romkatv** [comment]
I don't know what `prompt_nix_shell_setup` is. To enable `nix_shell` prompt segment in powerlevel10k you need to add `nix_shell` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in `~/.p10k.zsh`. If you run `p10k configure` and select Lean, Rainbow or Classic, it'll be in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` by default.

**Comment by illegitimate-egg** [comment]
Interesting, because my config was setup with rainbow and doesn't show the prompt

**Comment by romkatv** [comment]
Is `nix_shell` prompt segment enabled in your setup?

**Comment by illegitimate-egg** [comment]
Yes

**Comment by romkatv** [comment]
What is the output of the following command when you are in nix shell?

```zsh
typeset -pm 'IN_NIX_SHELL|POWERLEVEL9K_LEFT_PROMPT_ELEMENTS|POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS'
```

**Comment by illegitimate-egg** [comment]
`typeset -a POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status command_execution_time background_jobs direnv asdf virtualenv anaconda pyenv goenv nodenv nvm nodeenv rbenv rvm fvm luaenv jenv plenv perlbrew phpenv scalaenv haskell_stack kubecontext terraform aws aws_eb_env azure gcloud google_app_cred toolbox context nordvpn ranger nnn lf xplr vim_shell midnight_commander nix_shell vi_mode todo timewarrior taskwarrior time )
typeset -a POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon dir vcs )`

**Comment by illegitimate-egg** [comment]
Here's a [video](https://youtu.be/2SIElBMs0Ks) to visualize what's going on.

**Comment by romkatv** [comment]
Apparently `IN_NIX_SHELL` is not set, even though you are in nix-shell. Do you know why? Is there are different env variable that gets set, and which I can use in powerlevel10k to see that you are in nix shell?

**Comment by illegitimate-egg** [comment]
Hmm, I'm not using an official nix distribution so it's possible that that's causing the issue, I can try with official nix, just give me a minute

**Comment by illegitimate-egg** [comment]
Strangely, the problem persists with an official nix distribution, shell is technically still in experimental but its use is already widespread

**Comment by romkatv** [comment]
Found this: https://github.com/NixOS/nix/issues/3862#issuecomment-664575263. I don't understand what it says about `IN_NIX_SHELL` and `nix develop`.

The issue suggest a workaround that involves parsing `PATH`. I can try it if you can tell me what your `PATH` is when you are in nix shell.

**Comment by illegitimate-egg** [comment]
Path normally: 
```
/home/cameronpeck/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/cameronpeck/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/cameronpeck/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```
Path in Nix Shell:
```
/home/cameronpeck/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/store/djvgvpfisbyfbh5wj7w5yd8zhnyncxsj-hexedit-0.0.1/bin:/home/cameronpeck/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/cameronpeck/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/cameronpeck/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

**Comment by illegitimate-egg** [comment]
Would it be possible to resolve by awk/greping for `/nix/store`?

**Comment by romkatv** [comment]
> Would it be possible to resolve by awk/greping for `/nix/store`?

Of course, but that would be silly. A more extreme case of the same approach would be to invoke a web service from C when you need to add two numbers.

Anyway, I've pushed https://github.com/romkatv/powerlevel10k/commit/614a6ed1ca8bcad6a5960457c6cd3acd15bc0456, which should display `nix_shell` (just the icon with no content) when `path` contains `/nix/store/*`. Please give it a try and let me know whether it works for you.

**Comment by illegitimate-egg** [comment]
Alright, give me a minute to try. Also when I said grep/awk I kind of just meant it as a blanket term for run a regex on that thing

**Comment by romkatv** [comment]
That's rather unorthodox 🤣

**Comment by illegitimate-egg** [comment]
Yea well a lot of things I do are unorthodox lol

**Comment by illegitimate-egg** [comment]
Yea, it's fixed! Thanks

**Comment by romkatv** [comment]
Awesome! Thanks for verifying and filing the issue in the first place.

**Comment by illegitimate-egg** [comment]
And thanks for fixing it

**Comment by romkatv** [comment]
Alright, I've reverted the default behavior back to what it was.

Now, if you want to see the nix shell icon in prompt when `PATH` contains `/nix/store`, you need to explicitly define `POWERLEVEL9K_NIX_SHELL_INFER_FROM_PATH=true` in `~/.p10k.zsh`.
