### ISSUE TITLE
[bug] wrong git status

### ISSUE THREAD

**Issue by Freed-Wu** [romkatv/powerlevel10k#2247]
```zsh
# $ uname -r
# 6.2.7-arch1-1
# $ zsh --version
# zsh 5.9 (x86_64-pc-linux-gnu)
# $ cd /dev/shm
# $ vi test.zsh
# $ ls
# test.zsh
# $ cat test.zsh
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
. ~/.local/share/zinit/plugins/powerlevel10k/powerlevel10k.zsh-theme
# $ zsh -df
# $ . ./test.zsh
# $ git init
# $ git add -A
```

# Acutal
![screen-2023-04-01-22-56-20](https://user-images.githubusercontent.com/32936898/229296672-1ca640e3-c60c-4699-8cc7-afe4530a1018.jpg)

# Expected
after `git add -A`, `?` should be changed to `!`

# Version

p10k: latest
zsh: 5.9
OS: 6.2.7

**Comment by romkatv** [comment]
Cannot reproduce. You probably have some non-default setting in your global gitconfig that is relevant. Could be this: https://github.com/romkatv/powerlevel10k/issues/2232#issuecomment-1478166292

P.S.

The quality of this issue's description is top notch.

**Comment by Freed-Wu** [comment]
<https://github.com/romkatv/powerlevel10k/issues/2232#issuecomment-1478166292> works for me. Thanks!
