### ISSUE TITLE
Cant change the theme

### ISSUE THREAD

**Issue by ooxofficial** [romkatv/powerlevel10k#2250]
I cant change the theme, i changed it to random and it still says Random theme {{random theme}} loaded but loads powerlevel10k

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k

**Comment by ooxofficial** [comment]
thank you!

**Comment by romkatv** [comment]
You are welcome.
