### ISSUE TITLE
blank space between left/right prompt and edge of terminal

### ISSUE THREAD

**Issue by noriah** [romkatv/powerlevel10k#2251]
I have been trying for quite some time to remove the space between the left/right prompt and the edge of the terminal.

![image](https://user-images.githubusercontent.com/1609931/230286411-7da0e5a2-f910-469f-92dc-ed54caf9cc0c.png)

I have tried `ZLE_RPROMPT_INDENT=0` before p10k loads. That does fix the right indent by one space. Without it the right prompt has two spaces between the end and the terminal edge.

Is there a way to achieve this?

You can find my [p10k.zsh here](https://github.com/noriah/den/blob/14ab384fffc2662479826a100c9c1de966768b7a/etc/burrow/p10k.zsh) 

Thanks

**Comment by romkatv** [comment]
Add this:

```zsh
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' \uE0B1'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' \uE0B3'
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' \uE0B1 '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' \uE0B3 '
```

**Comment by noriah** [comment]
That works just as expected.

I have discovered that many of the double wide symbols in nerdfonts don't do well without having that space. I am guessing that is why it was present in the first place. I will have to work on that. Otherwise works as expected.

Thank you!
