### ISSUE TITLE
intermittent p10k issues in terminal

### ISSUE THREAD

**Issue by ArjunDandagi** [romkatv/powerlevel10k#2252]
Hi Thanks for the great customization on terminal , 
I have installed this recently on my iterm2 , with ohmyzsh. 

i keep getting this error. 
```bash
_p9k_deschedule_redraw:zle:2: No handler installed for fd 18
_p9k_deschedule_redraw:3: file descriptor 18 used by shell, not closed
```
kindly help.

**Comment by romkatv** [comment]
Try disabling all plugins and leaving only powerleve10k. Does the issue reproduce if you do that?

**Comment by ArjunDandagi** [comment]
Hi @romkatv  , you mean the omz plugins ? 
i have this in my `zshrc` 

```bash 
plugins=(aws fzf fzf-tab git colored-man-pages thefuck zsh-autosuggestions  zsh-syntax-highlighting web-search)
```

**Comment by romkatv** [comment]
Disabling those would be a start. If you have any other plugins, disable them too.
