### ISSUE TITLE
Get truncation to second last folder instead of last folder

### ISSUE THREAD

**Issue by V4G4X** [romkatv/powerlevel10k#2253]
I have a path `~/foo/bar/git_repo/nested_git_repo/baz`.

I want it shortened to `~/.../nested_git_repo/baz`.  
That is when the depth is more than 3, I want the folders between depth 1 and depth n-2 to be truncated. 

Other valid examples:
1. `~/foo`
2. `~/foo/bar`
3. `~/.../bar/git-repo`
4. `/`
5. `/usr`
6. `/usr/lib`
7. `/.../lib/zsh`

How would I have to configure my `.p10k.zsh` to achieve this?

**Comment by romkatv** [comment]
Powerlevel10k does not have an option to achieve this. You can, however, implement it as a custom prompt segment. This will get you started:

```zsh
function prompt_my_dir() {
  p10k segment -b blue -f red -t '%~'
}
```

See `p10k help segment` for documentation.

**Comment by V4G4X** [comment]
Is this an already existing feature request?

**Comment by romkatv** [comment]
No. I rarely implement feature requests unless they appeal to me personally. If you send a clean PR, I'll merge it. However, your best bet is to either implement a custom prompt segment or use a different truncation method. For example, you can try this:

```zsh
POWERLEVEL9K_SHORTEN_STRATEGY=default
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER='...'
```

Or this:

```zsh
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_DELIMITER=
POWERLEVEL9K_SHORTEN_FOLDER_MARKER=
POWERLEVEL9K_DIR_MAX_LENGTH=0
```
