### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by vecinohk** [romkatv/powerlevel10k#2256]
Hi,

I have read many times that this can be caused by an unsupported font. In my case, I use the Consolas font in the application https://tabby.sh/ and the icons disappear only sometimes ... for example, out of 10 times everything is ok 7 times and the icons are missing 3 times.

I know Nerd Fonts is the recommended font, but I like Consolas better. Is it because of the font please? Can I solve it in another way so that I can stay with the Consolas font?

I use Arch Linux.

Thank you

Image: https://ibb.co/YQP6vvr

**Comment by romkatv** [comment]
If your terminal is unable to display a certain glyph, you have these options:

1. Use a different font. This will help if the font you are currently using doesn't have necessary glyphs.
2. Use a different terminal. This will help if the terminal you are currently using is buggy.
3. Don't use the glyph in question: run `p10k configure` and select ASCII mode.

**Comment by vecinohk** [comment]
Thanks for the explanation and the helpful tips. I close - the error is in my environment.
