### ISSUE TITLE
asdf yarn

### ISSUE THREAD

**Issue by tarikkavaz** [romkatv/powerlevel10k#2259]
I can see all my active asdf plugin's like node python and ruby from my .tool-version
all of then have a settings for their foreground, background and icon, but not for yarn
I have tried, 
```
typeset -g POWERLEVEL9K_YARN_BACKGROUND=208
typeset -g POWERLEVEL9K_YARN_FOREGROUND=0
``` 
with no luck. do I miss something?

**Comment by romkatv** [comment]
> I can see all my active asdf plugin's like node python and ruby from my .tool-version
> all of then have a settings for their foreground, background and icon, but not for yarn

`yarn` works like all the other tools.

**Comment by tarikkavaz** [comment]
> > I can see all my active asdf plugin's like node python and ruby from my .tool-version
> > all of then have a settings for their foreground, background and icon, but not for yarn
> 
> `yarn` works like all the other tools.

Yes it does :)
