### ISSUE TITLE
work incorrectly in `emulate sh` mode

### ISSUE THREAD

**Issue by CyrilTaylor** [romkatv/powerlevel10k#226]
work incorrectly in `emulate sh` mode

```log
_p9k_wrapper__p9k_zle_line_finish:2: bad output format specification
_p9k_precmd:setopt:28: no such option: prompt{cr,percent,sp,subst}
```

**Comment by romkatv** [comment]
Thanks for the report. Should be fixed now. Please verify that it works for you.

**Comment by CyrilTaylor** [comment]
Could you create a release branch or release tags? After `git pull`, this issue repeated. Release tags is better.

**Comment by romkatv** [comment]
The release branch is called `master`. Every commit to this branch is essentially a release tag.

If you want `git pull` to checkout the latest released version, then stay on `master`. If you want `git pull` to have no effect on your work tree, then checkout a specific commit.

**Comment by CyrilTaylor** [comment]
After reboot, it's work fine. THANKS for your help.

and there is another issue about `emulate` mode. It will show an warning with up & down key.

```log
# emulate sh
/usr/bin/zsh:3: up-line-or-beginning-search: function not defined by file
/usr/bin/zsh:3: down-line-or-beginning-search: function not defined by file
```

**Comment by romkatv** [comment]
> and there is another issue about `emulate` mode. It will show an warning with up & down key & type special char.
> 
> ```
> # emulate sh
> # up key
> /usr/bin/zsh:3: up-line-or-beginning-search: function not defined by file
> # down key
> /usr/bin/zsh:3: down-line-or-beginning-search: function not defined by file
> # type ~ # $ ^ ( ) = `
> url-quote-magic:12: bad pattern: (#b)([^:]##):*
> ```

This isn't related to powerlevel10k. If you disable your theme, you'll get the same errors.
