### ISSUE TITLE
Filter todo.txt prompt with only tasks that are due today

### ISSUE THREAD

**Issue by andreatitolo** [romkatv/powerlevel10k#2260]
Hi! Thanks for this theme :). I was wondering if it could be possible to filter the todo.txt prompt to show only tasks that are due today. As far as I understand, the prompt show the output of `todo.sh -p ls`, which will show all the task in the todo file. I'm definitely a newbie to this, so apologies if this is a silly question, but is there a way to modify the `typeset -g POWERLEVEL9K_TODO_CONTENT_EXPANSION='$P9K_TODO_FILTERED_TASK_COUNT'` to show the output of something like `todo.sh -p ls due:$(date +'%Y-%m-%d')`?

Thank you again!

**Comment by romkatv** [comment]
Powerlevel10k does not have such an option. If you send a clean PR that adds a new option, I'll merge it.
