### ISSUE TITLE
Unexpected extra triangle icon after every command

### ISSUE THREAD

**Issue by wajda** [romkatv/powerlevel10k#2263]
Mac M1, iTerm2, Oh-my-zsh.
Installed everything from scratch, no custom config. The symbol appears right after installing powerlevel10k theme.

<img width="523" alt="Screenshot 2023-04-13 at 13 02 58" src="https://user-images.githubusercontent.com/795479/231740868-d37df40e-31a6-4656-b3f7-06b869b3566d.png">
<img width="55" alt="Screenshot 2023-04-13 at 13 02 43" src="https://user-images.githubusercontent.com/795479/231740904-9a51a340-8f3d-4932-9289-e40c19a0e5bf.png">

**Comment by romkatv** [comment]
https://stackoverflow.com/a/41661660
