### ISSUE TITLE
ZSH Style Problem

### ISSUE THREAD

**Issue by ash-miku** [romkatv/powerlevel10k#2265]
Do not know since when, there is a small blue arrow on left newline, excuse me, is this a bug？
![image](https://user-images.githubusercontent.com/29676159/231926006-fe78fa48-0c47-4b49-8903-2b07797d91f9.png)

**Comment by romkatv** [comment]
https://stackoverflow.com/a/41661660

**Comment by ash-miku** [comment]
It works, thank you very much!
