### ISSUE TITLE
Customization of prompt

### ISSUE THREAD

**Issue by TheShiningBoots** [romkatv/powerlevel10k#2269]
Hey, I am new user and would like to do the following:

Replace the tilde character with the text [theshiningboots@archlinux]
Have the above text be colored if possible like this: [theshiningboots@archlinux] where:
       ``[] and @ are uncolored, theshiningboots is one color and archlinux is another``

Have the text be replace only if the home dir is open, for eg
![image](https://user-images.githubusercontent.com/104355165/232210661-197b524a-3bc1-4e75-a99b-0033ec1c68ea.png)
in the above photo ~ should be replaced with the text but if a person opens another directory like:
![image](https://user-images.githubusercontent.com/104355165/232213898-f70fcb71-7198-48d4-adc0-a75781a4db28.png)
    the `tilde` character should persist (~) and not get replaced by the text.

[A pastebin to my current config can be found here](https://pastebin.com/ULjfpmiy)

**Comment by romkatv** [comment]
Sorry, I don't write configs on demand.

**Comment by TheShiningBoots** [comment]
Oh well, i never really asked for it, just wanted some help to get myself to the right direction. Like maybe a config option or something, I am sorry for the misunderstanding. Hope you can help now?

**Comment by romkatv** [comment]
See FAQ for how to display username@hostname even when it's "obvious": https://github.com/romkatv/powerlevel10k#how-do-i-add-username-andor-hostname-to-prompt. See `~/.p10k.zsh` for how to change its format.
