### ISSUE TITLE
[question] How can i only show nvm when its not the the default (system)

### ISSUE THREAD

**Issue by MaxL** [romkatv/powerlevel10k#227]
Hello, thanks for this really great update to P9K. I noticed one difference to (my conffiguration) of p9k though. The nvm extension i have in the right prompt would only be visible if it wasn't the default. It stilla cts liek this for rbenv which is great, would love for it to also work for nvm.

**Comment by romkatv** [comment]
Please post the output of the following command while having `nvm` prompt from p10k that you don't want to see:

```zsh
() {
  emulate -L zsh
  setopt xtrace
  typeset -m 'POWERLEVEL9K_*|ZSH_VERSION'
  uname -a
  nvm_version current
  nvm_version default
}
```

- What does p10k prompt show? A screenshot would be best.
- What does p9k prompt show with the same config and in the same directory? A screenshot would be best.

**Comment by MaxL** [comment]
ah sorry @romkatv it was because of `export NVM_LAZY_LOAD=true` ... thanks so much for putting me on the right track

**Comment by romkatv** [comment]
Glad you found a way to make it work.
