### ISSUE TITLE
Abnormal prompt display

### ISSUE THREAD

**Issue by GrooveWJH** [romkatv/powerlevel10k#2270]
## on Tabby, There are some anomalies on both ends of the prompt:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/68369010/232243020-a04943a2-2469-479c-8de5-b18619f9b363.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/68369010/232243051-22b34487-9092-4b2e-b063-d32710e98628.png">

## on Terminal, It works well...
<img width="896" alt="image" src="https://user-images.githubusercontent.com/68369010/232243318-3edda3c8-af21-437f-ad67-395184a3e78c.png">

**Comment by romkatv** [comment]
Some terminals are buggier than others.

**Comment by GrooveWJH** [comment]
> Some terminals are buggier than others.

Thx.<3 
I will post an issue to Tabby.
