### ISSUE TITLE
Question regarding settings

### ISSUE THREAD

**Issue by masterjg** [romkatv/powerlevel10k#2271]
Right now this is what I have configured with wizard:
![1](https://user-images.githubusercontent.com/11464772/232245252-cca5d710-c1f7-479e-8208-5c1684ee8c5f.jpg)

Which settings in ~/.p10k.zsh should I tackle to achieve something that has no spacing and no icons on the left side second line, i.e. ?
![2](https://user-images.githubusercontent.com/11464772/232245467-96834cfb-98a8-45fd-9227-2ef0ed639c6e.jpg)

**Comment by romkatv** [comment]
Run `p10k configure` and choose *Right* when asked about *Frame*. This will give you `prompt_char` on the left, which packs a lot of info into a single character.

**Comment by masterjg** [comment]
> Run `p10k configure` and choose _Right_ when asked about _Frame_. This will give you `prompt_char` on the left, which packs a lot of info into a single character.

Is it possible to not have the prompt_char and just have plain vertical cursor? I really like how currently all the success/error statuses are shown on the right side

**Comment by romkatv** [comment]
You can also do this on top of your config (the one that does not have `prompt_char`):

```zsh
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
```

The last three are actually empty by default but your config sets non-empty values for them. Instead of overriding these parameters twice, you can just delete your own overrides.

Do note that giving up prompt char requires a dozen or so characters to show the same information (status and keymap).

**Comment by masterjg** [comment]
> You can also do this on top of your config (the one that does not have `prompt_char`):
> 
> ```shell
> POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
> POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
> POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
> POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
> ```
> 
> The last three are actually empty by default but your config sets non-empty values for them. Instead of overriding these parameters twice, you can just delete your own overrides.
> 
> Do note that giving up prompt char requires a dozen or so characters to show the same information (status and keymap).

Superb! Just what I needed. Thanks.

One last small nuisance: 
How do I remove the padding on the left side?
![3](https://user-images.githubusercontent.com/11464772/232246849-4a9e80ee-da98-4f42-abf0-25f1aabb549d.jpg)
to
![4](https://user-images.githubusercontent.com/11464772/232246864-e106e895-02f3-464d-a69a-1cc359e2b766.jpg)

**Comment by romkatv** [comment]
```zsh
ZLE_RPROMPT_INDENT=0
```

This is a core zsh parameter not related to powerlevel10k, so it's best to put it directly in `~/.zshrc` rather than in `~/.p10k.zsh`. This parameters is documented on https://zsh.sourceforge.io/Doc/Release/Parameters.html.

**Comment by masterjg** [comment]
That's it - you've solved all my issues. Thank you very much!

**Comment by romkatv** [comment]
You are very welcome.

**Comment by masterjg** [comment]
Hm... after reboot for some reason I now see one empty line between first and second lines... Very weird behaviour as previously it worked.

`typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=​​`
![Screenshot from 2023-04-15 22-41-29](https://user-images.githubusercontent.com/11464772/232250212-31285e91-dd34-4a4b-907e-2a13983fd72c.png)

`typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=​​' '`
![Screenshot from 2023-04-15 22-43-40](https://user-images.githubusercontent.com/11464772/232250274-b9573e83-0340-47b6-93be-4c817bcf6ff3.png)

As if setting `POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR` to empty value means newline. Not sure what's up...

**Comment by romkatv** [comment]
Have you looked at the docs I linked?

**Comment by masterjg** [comment]
> Have you looked at the docs I linked?

https://zsh.sourceforge.io/Doc/Release/Parameters.html these docs? I've checked just `ZLE_RPROMPT_INDENT` as you've mentioned. And this var is set to `0` and right side looks good:
![Screenshot from 2023-04-15 22-51-11](https://user-images.githubusercontent.com/11464772/232250526-1de6d408-6020-4720-8310-d29a8d213c0f.png)

**Comment by romkatv** [comment]
Yes, that doc. I'll quote it for you:

> ZLE_RPROMPT_INDENT <S>
> If set, used to give the indentation between the right hand side of the right prompt in the line editor as given by RPS1 or RPROMPT and the right hand side of the screen. If not set, the value 1 is used.
>
< Typically this will be used to set the value to 0 so that the prompt appears flush with the right hand side of the screen. This is not the default as many terminals do not handle this correctly, in particular when the prompt appears at the extreme bottom right of the screen. Recent virtual terminals are more likely to handle this case correctly. Some experimentation is necessary.

**Comment by masterjg** [comment]
Right now it is set to **zero** (`ZLE_RPROMPT_INDENT=0`) in `.zshrc` as you've suggested. Not sure how this can affect that extra line when `POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=` and yet not add line when `POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR='' `

**Comment by masterjg** [comment]
Looks like you're right as if I force back `ZLE_RPROMPT_INDENT=1` I don't have this empty line...

**Comment by romkatv** [comment]
The docs I quoted explain what's going on.
