### ISSUE TITLE
How can I fix the font missing problem

### ISSUE THREAD

**Issue by chi0819** [romkatv/powerlevel10k#2273]
<img width="1003" alt="Screen Shot 2023-04-18 at 12 43 08 PM" src="https://user-images.githubusercontent.com/130915572/232673895-92cd109f-b971-4673-a01e-982f54f89fb2.png">

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by chi0819** [comment]
Thank you!

**Comment by chi0819** [comment]
> https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

Thank you
