### ISSUE TITLE
Feature request / bug fix: when copying branch name, copy the full branch name

### ISSUE THREAD

**Issue by wtruppel** [romkatv/powerlevel10k#2278]
When copying the branch name from the console, take into consideration that it may be truncated so copy the _entire_ branch name, not the truncated one.

Also, maybe have an option in the configuration to _not_ abbreviate branch names at all.

<img width="275" alt="1" src="https://user-images.githubusercontent.com/91148917/233621442-71e327a6-6538-4488-8c9a-a685ea15fdc3.png">

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/045f006c50d782a6d3acbd8a07d1595322ff7e43/config/p10k-classic.zsh#L393-L394

**Comment by wtruppel** [comment]
Thanks, @romkatv. I still think it should be an option in the configuration, tho, so I won't close the issue myself.

**Comment by romkatv** [comment]
Configuration wizard exposes only the most basic options. For everything else you can edit the config file that it generates.
