### ISSUE TITLE
No icons on Arch Linux ARM

### ISSUE THREAD

**Issue by jclsn** [romkatv/powerlevel10k#2279]
I just did a fresh install of Alarm and p10k doesn't give me the options to use icons. Fonts should not matter, because I only connect to it via ssh or do they? Is there any other package or configuration that could be missing? The default Alarm installation is pretty basic

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
