### ISSUE TITLE
Why does this theme just say minikube?

### ISSUE THREAD

**Issue by zemuldo** [romkatv/powerlevel10k#228]
Hi, Let me first say kudos to the nice piece of work on this theme. Its the best I have come across, just curious. I don't get why the terminal only say minikube

```
╭─░▒▓ ~ ▓▒░················································░▒▓ ✔ | at minikube ⎈ | at 18:59:37 ▓▒░─╮
╰─ cd Code/api.zemuldo.com                                                                        ─╯

╭─░▒▓ ~/Code/api.zemuldo.com | on master ▓▒░···············░▒▓ ✔ | at minikube ⎈ | at 18:59:41 ▓▒░─╮
╰─
```

**Comment by romkatv** [comment]
What do you mean by "only say minikube"? The prompt you copy-pasted seems to contain more than just `minukube`.

Do you expect to see something else instead of `minikube`? Or perhaps something in addition to `minikube`? If so, could you describe what you expect to see?

**Comment by zemuldo** [comment]
I mean i understand `on master` means the current directory has a git repo that is on branch master. I also understand `| at 18:59:41` as the time but I don't understand `at minikube ⎈` because I have `minikube` installed but it's not running. So I am just asking why the terminal is having `at minikube ⎈`

**Comment by romkatv** [comment]
This is `kubecontext` prompt segment. It shows your current kubernetes context. Type `kubectl config current-context` -- you'll see `minikube` printed out. This is your current kubernetes context. This is what your prompt shows.

If you don't want to see it, open `~/.p10k.zsh` and search for `kubecontext`. Comment out the first occurrence.

**Comment by zemuldo** [comment]
Thank you. That was very helpful.
