### ISSUE TITLE
can the clock on the right stay along with the command history (without color)

### ISSUE THREAD

**Issue by thevikas** [romkatv/powerlevel10k#2280]
I use timestamping my promps and many times check times when they started. 
How to keep the clock on the right stay along with the command history?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/2081.

**Comment by thevikas** [comment]
https://github.com/romkatv/powerlevel10k/issues/1705#issuecomment-1006347304

this worked for me. super thanks.
