### ISSUE TITLE
Can't set folder icon color separately?

### ISSUE THREAD

**Issue by pro-sumer** [romkatv/powerlevel10k#2282]
I want to display the folder icon (determined by `POWERLEVEL9K_DIR_CLASSES`) in its own color, but don't know how to do that... Currently powerlevel10k is displayed this icon using `POWERLEVEL9K_DIR_FOREGROUND`, but I want (non-anchor) folder segments and the folder icon to each have a different colour.

Is this currently possible? If so, how?

**Comment by pro-sumer** [comment]
Thanks!

`POWERLEVEL9K_DIR_VISUAL_IDENTIFIER_COLOR` is even good enough for my use case it seems.

(My mistake: I was trying `POWERLEVEL9K_DIR_VISUAL_IDENTIFIER_FOREGROUND`; so `FOREGROUND` instead of `COLOR`...)

**Comment by romkatv** [comment]
The name `VISUAL_IDENTIFIER_COLOR` comes from powerlevel9k. I would've called it `ICON_FOREGROUND` myself.
