### ISSUE TITLE
Where to find documentation for P10k settings

### ISSUE THREAD

**Issue by LostInCompilation** [romkatv/powerlevel10k#2283]
Not really an issue, but I'm a bit lost.
I'm a long time user but finally want to customize my shell how I like it. I'm searching for documentation of all the settings available for the `.p10k.zsh` file. P9k had some of the variables documented in the Readme, but I cannot find such documentation for P10k.

For example I'm searching for available value for `POWERLEVEL9K_SHORTEN_STRATEGY`.

Is there something like a documentation?

**Comment by romkatv** [comment]
The only documentation is README.md and the comments that you can find in `~/.p10k.zsh` after running `p10k configure`. There is no reference for all parameters.

**Comment by LostInCompilation** [comment]
Is there some other way to find out, what values a paramter can be set to? The comments in `~/.p10k.zs` are only rudimentary explanations and often do not document all possible values for parameters.

Would writing a reference for all parameters be something to consider? I think a lot of them can be migrated from https://github.com/Powerlevel9k/powerlevel9k/blob/master/README.md

**Comment by romkatv** [comment]
> Is there some other way to find out, what values a paramter can be set to?

You could could read the code.

> Would writing a reference for all parameters be something to consider?

Yes.

**Comment by LostInCompilation** [comment]
Should I open an issue to request parameter documentation being written?

**Comment by romkatv** [comment]
There is no need for that. I know that it would be nice to have a reference but at the same time it's not something I'm going to do.

**Comment by LostInCompilation** [comment]
Many parameters are documented in P9k's Readme. Maybe migrating them over to P10k's Readme would be a good start.

**Comment by romkatv** [comment]
Yeah, perhaps it would be.

Anyway, closing because I believe I've answered all your questions.

**Comment by LostInCompilation** [comment]
Really sounds like you absolutely doesn't want to do any documentation 😄 This repo probably has tens of thousands of users, see it as a motivation to allow them to configure their prompts way more.

**Comment by romkatv** [comment]
> Really sounds like you absolutely doesn't want to do any documentation 😄

Pretty much. It's more than that. I don't want to do 99.99999% of things that would actually be good for someone. Just like you. Just like everybody. I have one life to live and I have to choose my battles.

**Comment by LostInCompilation** [comment]
Man that's quiet a... uhm saddening perspective on doing good things for others.

**Comment by romkatv** [comment]
Why just for others? I'm also not doing 99.99999% of things that would be good for me. Just like you.
