### ISSUE TITLE
Lean style asks Unicode vs ASCII with no discernible difference

### ISSUE THREAD

**Issue by benediktwerner** [romkatv/powerlevel10k#2288]
<img width="704" alt="Bildschirmfoto 2023-05-01 um 16 45 42" src="https://user-images.githubusercontent.com/19309705/235470362-2db132ac-1ae3-4449-86ae-e347fe0ab734.png">

Would be nice if it would either not ask this or explain what difference it makes that isn't visible (if any?).

**Comment by romkatv** [comment]
This mostly makes a difference for the following screens. On this screen only the second line character differs.

How would you improve it?

**Comment by benediktwerner** [comment]
Ah, I didn't even notice that the prompt character changes. Seems rather obvious in hindsight though.

Maybe it would make sense to add some of the other elements from later pages? Presumably, ASCII also doesn't support some of the more elaborate design choices, so maybe it would also make sense to add a sentence explaining that? Or like, "Unicode (recommended)" and "ASCII (for maximum compatibility; doesn't allow more elaborate designs)".

But I guess maybe I'm also just blind. Feel free to close if you think it's fine as it is, seems like I'm the first person that didn't get it 😅

**Comment by romkatv** [comment]
Indeed, this is the first issue related to ASCII/UNICODE distinction. It doesn't seem like extra info on this screen of the wizard is justified at this point (and I definitely don't want to say that UNICODE is recommended). Closing with no action. Will revisit if someone else provides similar feedback.

**Comment by manueljordan** [comment]
Hello

> How would you improve it?

Perhaps by changing the title to something like:

* Character Set (observe the ">" prompt character)
