### ISSUE TITLE
[Manual Install] Uses .p10k.zsh rather than .zshrc, how to fix?

### ISSUE THREAD

**Issue by gwennshinguji** [romkatv/powerlevel10k#229]
Hello, I manually installed p10k on my laptop and any changes i make on .p10k.zsh are met with:

`/home/[username]/.p10k.zsh:34: parse error near ')'`

This doesn't happen on my desktop, my desktop has it just using .zshrc.

How can I get p10k to use .zshrc rather than .p10k.zsh?

**Comment by romkatv** [comment]
@gwennshinguji Have you managed to solve this problem? Could you mention how? It'll help future users who encounter the same error.

**Comment by gwennshinguji** [comment]
i don't exactly remember but it definitely was a user error. i believe i either forgot or had one too many parantheses on the config.
