### ISSUE TITLE
p10k configure shows Debian swirl on Mac OS when installed with homebrew

### ISSUE THREAD

**Issue by karimbenbourenane** [romkatv/powerlevel10k#2290]
When installing using the recommended manual install, on Mac OS, the installer uses the apple logo glyph: 

```
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
```

However, when installing with [homebrew](https://github.com/Homebrew) , it uses the latest release at https://github.com/romkatv/powerlevel10k/releases/tag/v1.17.0.

This release doesn't seem to be agnostic; it shows the Debian logo during the `p10k configure` step regardless of the OS it's running on.

Would you be able to create releases that can auto-detect the target OS and display the correct OS logo so we do not have to rely on a non-release version of p10k by cloning the master branch of this repo?

**Comment by romkatv** [comment]
> When installing using the recommended manual install, on Mac OS, the installer uses the apple logo glyph

What do you mean by this? What is "the installer" and how does it use the Apple logo?

**Comment by karimbenbourenane** [comment]
My apologies for the incorrect language. I am referring to running `p10k configure`.

**Comment by romkatv** [comment]
How does `p10k configure` use the Apple Logo?

**Comment by karimbenbourenane** [comment]
Please see attached screenshot for how a `homebrew` installed p10k looks when configure is run: 
<img width="682" alt="Screenshot 2023-05-03 at 09 17 01" src="https://user-images.githubusercontent.com/274071/235927334-01af8596-9468-4b80-91a1-6e58549a7ae6.png">

**Comment by romkatv** [comment]
This question, just like the others before it, is there in order to detect font capabilities. You can recall that it asks about diamond, lock, etc.

**Comment by karimbenbourenane** [comment]
I recall diamond, lock, etc, but installing this package as a custom oh-my-zsh plugin shows a different character than the Debian swirl. I cannot recall exactly what that character was, and I think your question is to point out that it isn't an apple logo. I am currently installing as an oh-my-zsh custom plugin to display the difference.

**Comment by romkatv** [comment]
I think the newest version asks about an arrow but I don't remember if it can also ask about the debian logo in some circumstances. In any case, the question about the debian logo does not imply that you are running a debian OS or anything like that. It asks whether the logo renders correctly with your terminal and font.

FWIW, I've made the most recent changes in this area in order to support the new Nerd Font fonts.

**Comment by karimbenbourenane** [comment]
Ok @romaktv a second apology for misremembering. It was not an apple logo in place of the Debian swirl. It was the up arrow. Here is what `p10k configure` looks like when installed with the ohmyzsh route:

<img width="682" alt="Screenshot 2023-05-03 at 09 23 15" src="https://user-images.githubusercontent.com/274071/235928988-d8c65821-b93c-4537-8dbd-1e603e626fcc.png">

**Comment by romkatv** [comment]
That is correct.

**Comment by karimbenbourenane** [comment]
I understand that the specific character chosen is pretty inconsequential since this is a screen rendering diagnostic, but I thought I would bring it up in case there was some bug present that displays one icon for homebrew'd installs and a different icon for ohmyzsh installs. If there's no problem we can just close this issue. Thanks for looking into this.

**Comment by romkatv** [comment]
There is no problem. The icon in master is different because I changed this part of the code recently to support the new release of Nerd Fonts. When I cut a new release of powerlevel10k, Homebrew will also display the new icon. It's a small change, so I'm not rushing with the release.

**Comment by karimbenbourenane** [comment]
Excellent. Thanks for your attention @romkatv 👍
