### ISSUE TITLE
Feature Request: Show CPU Architecture (Rosetta Terminal MacOS)

### ISSUE THREAD

**Issue by jmealo** [romkatv/powerlevel10k#2298]
Hello,

I just installed this and am already loving it. I was wondering if it'd make sense to add some icon or indicator when you're in a Rosetta Terminal on OSX. In the latest versions of Mac OS, you can no longer Duplicate the built-in `Terminal.app` to have a dedicated Rosetta terminal. The easiest workaround is to use `Terminal.app` for one CPU architecture and `iTerm` (or similar) for others. It would be awesome if the setup process or built-in prompt showed which you were on.

Thanks,
Jeff

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for "cpu_arch" and uncomment the first hit. Does this do what you want?

**Comment by jmealo** [comment]
@romkatv: **Wow, this is perfect!** The output isn't exactly what I'm expecting `(i486/arm64e)` vs `(arm64/amd64)` but it'll do nicely. **Excellent work!** Closing issue.

**Comment by jmealo** [comment]
@romkatv: Do you accept tips/donations? I didn't see a link.
