### ISSUE TITLE
Transient prompt color appears to be off by 1

### ISSUE THREAD

**Issue by jaustinj** [romkatv/powerlevel10k#2301]
POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION_FOREGROUND color seems to be off by one in many cases.

See example below:

<img width="419" alt="Screenshot 2023-05-08 224401" src="https://user-images.githubusercontent.com/33203110/236996420-f0601f65-175a-494f-a05f-fa7980aad7ed.png">

My first command seems to always return green, even if an error.  My second command will then return the color of the first command, the third will return the color of the second, and so on. 

In image above:
Line 1 is invalid, but returns a green ">"
Line 2 is valid, but returns a red ">"
Line 3 is valid and returns green
Line 4 is invalid but returns green
Line 5 is invalid and returns red
Line 6 is valid but returns red

I ran p10k configure right before this series of commands to make sure I didn't have issues with my configuration. 

Working in Windows Terminal - WSL2 - Ubuntu

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them

**Comment by jaustinj** [comment]
Thank you, missed this in the docs
