### ISSUE TITLE
It seem lost some color

### ISSUE THREAD

**Issue by huankong233** [romkatv/powerlevel10k#2303]
![image](https://github.com/romkatv/powerlevel10k/assets/49610758/edda6c84-b2cf-4b8c-b13d-809afcd0382e)

It seem lost some color

I am using xshell and turn on the true color option.

**Comment by huankong233** [comment]
![image](https://github.com/romkatv/powerlevel10k/assets/49610758/5fc6a579-c230-4e2d-b739-9b7f4c978c97)

**Comment by romkatv** [comment]
The screenshot looks fine to me. If you don't like the look of black on black, you can do one of the following:

- Change the background color in the terminal settings.
- Change the black color (color 0) in the terminal settings.
- Change the background color of `status` and `context` from 0 to something else. You'll need to edit `~/.p10k.zsh` for this.

Lastly, consider switching to *Lean* style to avoid this and similar issues altogether.
