### ISSUE TITLE
Resizing & creating new windows create a new line when 'Instant Prompt' is enabled

### ISSUE THREAD

**Issue by lightbluepoppy** [romkatv/powerlevel10k#2306]
This bug occurs only when 'instant prompt' is enabled

**How to Reproduce**
1. Open Kitty
2. Open Amethyst and set the layout to 'Tall'
3. Press ⇧⌥H and ⇧⌥L to resize, or ⌘N to create a new window

**Screenshots**
![kitty_bug](https://github.com/kovidgoyal/kitty/assets/65863981/5db32568-3dbf-46b3-82f9-d83affcbf0e0)

**How I solved the problem**
Disable 'instant prompt' with the `p10k configure` wizard

![p10k](https://github.com/romkatv/powerlevel10k/assets/65863981/1846898a-49e3-41ce-adef-b54360a56bed)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by lightbluepoppy** [comment]
> https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

Then I wonder why I was able to solve the problem by simply disabling 'instant prompt'.

**Comment by rwmitchell** [comment]
Thanks for the tip!  Seems to work for iTerm.  Didn't know that fix was even possible.
