### ISSUE TITLE
Can't change option: monitor

### ISSUE THREAD

**Issue by Saoma1** [romkatv/powerlevel10k#2308]
When trying to attach debbuger in Vscode I receive following error:

```
(anon):setopt:7: can't change option: monitor
[[31mERROR[39m]: gitstatus failed to initialize.
Add the following parameter to [4m~/.zshrc[24m for extra diagnostics on error:
[1mGITSTATUS_LOG_LEVEL=DEBUG[0m
Restart Zsh to retry gitstatus initialization:
[32m[4mexec[24m[32m zsh[39m
```

when I uncomment the source line in `.zshrc`, `source ~/powerlevel10k/powerlevel10k.zsh-theme`, it works again.

I also tried to add `GITSTATUS_LOG_LEVEL=DEBUG` to `.zshrc`, this produced following error:

```
[[31mERROR[39m]: gitstatus failed to initialize.
Zsh log ([4m/private/var/folders/js/74z16rf92nv48wl9_8szcbz80000gp/T/gitstatus.POWERLEVEL9K.502.9605.1684325672.1.xtrace.log[24m):
[33m
+(anon):7> setopt monitor
(anon):setopt:7: can't change option: monitor
+(anon):7> return
[39m
System information:
[33m
zsh:      5.9
uname -a: Darwin FW-DK4TL95VKX 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
[39m
If you need help, open an issue and attach this whole error message to it:

```

It should be noted that everything was working fine about a month ago.

Specs:
Apple M1 Pro
macOs Ventura 13.3.1

**Comment by romkatv** [comment]
The error `can't change option: monitor` happens when you are trying to load gitstatus in a shell without a controlling terminal. The solution is to not do that. I don't know how you can achieve this in your particular case.
