### ISSUE TITLE
WSL2 - WindowsTerminal - Debian not showing worktree branches

### ISSUE THREAD

**Issue by art3xias23** [romkatv/powerlevel10k#2312]
Hi, I've seen some people experiencing this issue, just wanted to confirm if someone with basic knowledge of ZSH can resolve it.

When running debian on wsl2 - Windows10 and using zsh via windows terminal I'm not able to see the branch names of worktrees. Only the main repo with the .git directory displays the branch name.

![image](https://github.com/romkatv/powerlevel10k/assets/23562239/ed8c41af-420d-4944-8366-3f6ec35d4931)

This is my wsl setup. 

![image](https://github.com/romkatv/powerlevel10k/assets/23562239/498b1743-1010-414c-b988-f39e9dcc7854)

[Here](https://github.com/art3xias23/wsl-dotfiles) are my dotfiles.

**Comment by romkatv** [comment]
What are "worktree branches"? How can I reproduce this from scratch starting with `git init` in an empty directory?

**Comment by art3xias23** [comment]
Hi @romkatv,

appreciate the quick response.


1. You are in C:\repos\MainRepo
2. `git init`
3. `git worktree add -b somebranch ../Unknown`
4. `cd ../Unknown`

You should now have
C:\repos\MainRepo
C:\repos\Unknown

When in unknown the branch name will not be displayed
When in MainRepo the master branch will be displayed

**Comment by romkatv** [comment]
Thanks for the details. gitstatusd doesn't support split worktrees because libgit2 doesn't. See https://github.com/libgit2/libgit2/issues/6044.
