### ISSUE TITLE
Time Is Shown in UTC instead of A Correct Time Zone

### ISSUE THREAD

**Issue by wvjgsuhp** [romkatv/powerlevel10k#2313]
![image](https://github.com/romkatv/powerlevel10k/assets/20987347/484184c5-4bf2-41e5-bd7d-164395fb9546)

Time is displayed in UTC instead of my time zone in WSL2.

**Comment by romkatv** [comment]
Powerlevel10k uses strftime. If you can induce the latter to display the time you want, powerlevel10k will follow.
