### ISSUE TITLE
[WARNING]: Console output during zsh initialization detected

### ISSUE THREAD

**Issue by jeancarloshm** [romkatv/powerlevel10k#2314]
I have a problem with my zsh, this started after I installed mongodb but I don't know why, I think it has to be a path error but I don't know how to fix it. Can you please help me out?

This is what I get once I open the terminal:

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.`

`You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

`/Users/jeancarlosherrera/.zshrc:export:117: not valid in this context: Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jeancarlosherrera/Development/flutter/bin`

I already tried the suggestions but none worked.

This is what I have in line 117:
`export PATH=/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/jeancarlosherrera/Development/flutter/bin:/opt/homebrew/Cellar/mongodb-community@6.0/bin
`
Also, I tried to uninstall zsh using homebrew to install it again and see if that solved my problem, but I get this error:

`brew uninstall zsh
Error: No such keg: /opt/homebrew/Cellar/zsh
`

**Comment by rwmitchell** [comment]
It looks like ```VMware Fusion.app``` has an embedded space.  Try putting the PATH assignment in quotes, as in:

```export PATH="path:path:path"```

**Comment by jeancarloshm** [comment]
Thankss, it worked!
