### ISSUE TITLE
gpg signing breaks due to instant prompt redirecting stdin (EVEN AFTER instantprompt is meant to cleanup)

### ISSUE THREAD

**Issue by Frontear** [romkatv/powerlevel10k#2316]
Can find the relevant .zshrc from my dotfiles over at https://github.com/Frontear/dotfiles. When attempting to sign via gpg (i use `echo "test" | gpg --clearsign` to test it), i get an invalid error warning me gpg has an inappriopriate ioctl device for stdin. Doing some digging I discovered the main fix was to do `GPG_TTY=$(tty)` to plug the running tty session and therefore give proper io handles. 

Upon giving it more discovery, I noticed p10k instant prompt redirects stdin to /dev/null, so i tried to comment out the `source p10k-instant-prompt` blip, and voila, gpg signs normally WITHOUT needing `GPG_TTY` exported.

Now i wouldn't have too much issue with this if it p10k didn't claim to cleanup after itself and fix the standardio redirects. As it stands it does NOT correctly fix stdin, who knows if stdout or stderr is affected in a different way. Please look into this and fix it.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-export-gpg_tty-when-using-instant-prompt

**Comment by Frontear** [comment]
right im aware of this fix, i just find it strange that it should be necessary, since instant prompt fixes stdin after plugin init, why is gpg still not working?

**Comment by romkatv** [comment]
Powerlevel10k restores stdin after replacing instant prompt with the regular one. If it didn't, the shell wouldn't have worked at all.

**Comment by romkatv** [comment]
> im aware if this fix

In this case I highly recommend that you use it.
