### ISSUE TITLE
Can't see Python virtualenv activation

### ISSUE THREAD

**Issue by shufanhao** [romkatv/powerlevel10k#2317]
Hi Team,

When I am activating a Python virtual environment I can't see the name like "(venv)".

```
cd code/Scripts
typeset -pm 'VIRTUAL_ENV|POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV'
typeset POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=true
source venv/bin/activate
typeset -pm 'VIRTUAL_ENV|POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV'
export VIRTUAL_ENV=/Users/haofan/code/Scripts/venv
typeset POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=true
 ~/code/Scripts  fix/bug
```

<img width="1451" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11540660/fef316dc-7150-483f-842a-0224860a409c">

**Comment by romkatv** [comment]
On the right hand side you can see `Scripts py` in blue. This means that a Python virtual environment from "Scripts" is currently active. This is more useful than seeing "venv": both tell you that a virtual environment is active but the latter does not tell you what *kind* of environment it is.

That said, you can configure powerlevel10k to display the less meaningful "venv" by adding the following line to `~/.p10k.zsh`:

    typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=()

As I mentioned above, this will make prompt less informative, so I don't recommend it.

**Comment by shufanhao** [comment]
thank you. that works.
