### ISSUE TITLE
Prompt heads are different color

### ISSUE THREAD

**Issue by tstutson** [romkatv/powerlevel10k#2319]
Using built in M2 Mac terminal.app

Installed the recommended fonts (MesloLGS NF Regular 11), and went through `pk10 configure`, but my prompt heads are a different color for some reason:
![image](https://github.com/romkatv/powerlevel10k/assets/29063616/2ee0e6af-a714-4635-ba4d-a23770cb7ab8)

Also tried changing font size, as well as opacity to see what happened, and it appears the prompt heads ignore opacity all together: 
![image](https://github.com/romkatv/powerlevel10k/assets/29063616/585151ec-c61b-4f08-ab6b-85e9316dd086)

Any help would be appreciated

**Comment by romkatv** [comment]
If this Apple Terminal, there is nothing you can do. If this is any other terminal, there is likely a setting that fixes this. I remember that iTerm2 has this setting but don't remember how it's called. It has something to do with opacity and/or transparency. Basically, you want background color to be non-transparent.

**Comment by romkatv** [comment]
I see your reaction but I cannot interpret it. Can you elaborate? Which terminal is this?
