### ISSUE TITLE
my terminal looks like bad

### ISSUE THREAD

**Issue by lintiancheng01** [romkatv/powerlevel10k#2321]
when i change my theme to ZSH_THEME="powerlevel10k/powerlevel10k" it's bad . and i think my font is ok. but when i change my theme to agnoster , it‘s good，can you tell me why。
error:
<img width="608" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/129168041/19596b13-e051-4160-92a3-27dac1e4a270">
<img width="614" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/129168041/ad06a1bf-e1b8-4afe-87ec-897fc86aba48">
find:
<img width="538" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/129168041/edd07f75-7ba0-4456-accf-14ddf11a16b8">

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style and https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors.

**Comment by lintiancheng01** [comment]
I don't understand why powerlevel10 root my color matching is not compatible, the address is https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Dracula.itermcolors

I think others can, why?
https://sspai.com/post/53008

<img width="1066" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/129168041/767cd398-5e49-423d-af11-bbeab13d0108">
<img width="1027" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/129168041/129eaa4b-844a-47aa-9dde-6c89893998d9">

**Comment by lintiancheng01** [comment]
Why does my color scheme seem to have changed after I used powerlevel10 theme? When I use agnoster theme, my color scheme is OK

**Comment by romkatv** [comment]
Please read what I linked above.
