### ISSUE TITLE
`gitstatusd` not up-to-date with `git status` (`VCS_STATUS_` vars not getting updated).

### ISSUE THREAD

**Issue by jonnylangefeld** [romkatv/powerlevel10k#2322]
I recently discovered that in one of my linux boxes my `vcs` ps1 prompt is not always accurate. The `VCS_STATUS_` vars don't match with what's in `git status`. The easiest steps to find a simple discrepancy was the following:

* on a clean master branch that's up-to-date with remote, there's not symbols and everything looks good
* I create a new file `foo` and get the `?` symbol indicating one untracked file. `git status` (`gst` in the screenshot below) as well as `VCS_STATUS_NUM_UNTRACKED` show 1 untracked file. So far so good.
* but then when I `git add foo` (`ga foo` in the screenshot below), the ps1 prompt doesn't change to the `+` as it should because the file is now staged `VCS_STATUS_NUM_UNTRACKED` shows still `1` and `VCS_STATUS_NUM_STAGED_NEW` still shows `0`, but the two should now be switched. `git status` correctly shows the new file.
![Screenshot 2023-05-24 at 5 47 54 PM](https://github.com/romkatv/powerlevel10k/assets/18717376/dc4f0cc4-13fa-45ba-8bb2-e5951845b859)

* If I now open a new terminal window and navigate to the same directory, everything is correct again. `VCS_STATUS_NUM_UNTRACKED` is `0` and `VCS_STATUS_NUM_STAGED_NEW` is `1` and the ps1 shows the plus symbol.
New terminal window, no other changes:
![Screenshot 2023-05-24 at 5 48 50 PM](https://github.com/romkatv/powerlevel10k/assets/18717376/bef16b68-2b97-4f2e-8d33-0f38d49910d1)

Somehow my `VCS_STATUS_` vars don't get updated after a completed command. 
**Why could that be and how could I debug this?**

`p10k` installed via `git clone https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k`.

<details>
<summary>`POWERLEVEL` variables in `~/.zshrc`:</summary>

```bash
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

POWERLEVEL9K_DIR_PATH_SEPARATOR="  "
ZSH_THEME=powerlevel10k/powerlevel10k
POWERLEVEL9K_MODE="awesome-patched"

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs custom_kube_ps1)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# `os_dir` color customization
POWERLEVEL9K_OS_ICON_FOREGROUND='255'
POWERLEVEL9K_OS_ICON_BACKGROUND='023'

# `vcs` color customization
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='236'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='035'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='035'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='215'

# `dir` color customization
POWERLEVEL9K_DIR_HOME_FOREGROUND='255'
POWERLEVEL9K_DIR_HOME_BACKGROUND='025'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='255'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='025'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='255'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='025'
POWERLEVEL9K_DIR_ETC_FOREGROUND='255'
POWERLEVEL9K_DIR_ETC_BACKGROUND='025'

POWERLEVEL9K_CUSTOM_KUBE_PS1='kube_ps1'
POWERLEVEL9K_CUSTOM_KUBE_PS1_BACKGROUND=none
POWERLEVEL9K_CUSTOM_KUBE_PS1_SUBSEGMENT_SEPARATOR=""
POWERLEVEL9K_CUSTOM_KUBE_PS1_SEPARATOR=""

```

</details>

[my `~/.p10k.zsh`](https://pastebin.com/raw/2BszD9rb)

**Comment by jonnylangefeld** [comment]
I completely reinstalled `oh-my-zsh` and `powerlevel10k` via
```
uninstall_oh_my_zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
```

And reduced the `~/.zshrc` to the bare minimum:
```
╰─ cat ~/.zshrc
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(git)
source $ZSH/oh-my-zsh.sh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

And I made sure there is no `~/.bashrc`, `~/.bash_profile`, `~/.profile`, `~/.zprofile` existing.

And it's still happening:
<img width="565" alt="Screenshot 2023-05-24 at 7 20 15 PM" src="https://github.com/romkatv/powerlevel10k/assets/18717376/3251d02a-a870-4235-b595-7819bfd3c12b">

It's probably the system. But what could it be?

**Comment by romkatv** [comment]
Perhaps https://github.com/romkatv/powerlevel10k/issues/2232#issuecomment-1478166292
