### ISSUE TITLE
where to change the color in the pic ? what is the setting key ?

### ISSUE THREAD

**Issue by StackTc** [romkatv/powerlevel10k#2325]
<img width="517" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/22773866/c6c5bf37-63e1-4766-be20-a14a095a016c">

**Comment by StackTc** [comment]
the number 2

**Comment by romkatv** [comment]
What terminal is this?

**Comment by StackTc** [comment]
iterm2

**Comment by StackTc** [comment]
it's the same in macos terminals . the color is different 
<img width="452" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/22773866/43799cdc-bfd7-4d64-9cd0-5a654dc5f23c">

**Comment by romkatv** [comment]
The setting in iTerm2 is called "Minimal Contrast". You need to set it to 0.

**Comment by StackTc** [comment]
it was zero.
<img width="1002" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/22773866/0ebf2a49-0e27-4e20-bbca-787886e44d10">

**Comment by StackTc** [comment]
it was zero.
<img width="991" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/22773866/e35187a9-0089-4f8a-8695-9723e5aa96dc">

**Comment by romkatv** [comment]
Then I don't know. Perhaps iTerm2 devs might know.

**Comment by romkatv** [comment]
I can see from your screenshot that you didn't enable builtin rendering of powerline glyphs. I think it's on *Text* tab. It's a good idea to enable it.

**Comment by StackTc** [comment]
where is the setting of builtin rendering of powerline glyphs.

![image](https://github.com/romkatv/powerlevel10k/assets/22773866/7110a174-a318-4477-b17f-467c716eef34)

**Comment by romkatv** [comment]
> where is the setting of builtin rendering of powerline glyphs.

I'm sure you'll find it.

**Comment by StackTc** [comment]
> > where is the setting of builtin rendering of powerline glyphs.
> 
> I'm sure you'll find it.

you are smart
