### ISSUE TITLE
安装powerlevel10k后，zsh终端的~/.zlogin文件配置的lolcat颜色消失了

### ISSUE THREAD

**Issue by misaki10032** [romkatv/powerlevel10k#2326]
安装powerlevel10k后，zsh终端的~/.zlogin文件配置的lolcat颜色消失了

**Comment by romkatv** [comment]
Move `lolcat` to the top of `~/.zshrc`.

**Comment by misaki10032** [comment]
抱歉，没太理解您的意思，是将`lolcat`环境变量配置在`~/.zshrc`最上面么？

**Comment by romkatv** [comment]
I suppose your are invoking `lolcat` from `.zshrc`. Move that line to the top.
