### ISSUE TITLE
No prompt style options

### ISSUE THREAD

**Issue by 4be** [romkatv/powerlevel10k#2327]
Hi all,

Im trying to choose rainbow style on my current theme

but when i run 

`p10k configure`

this is what i saw when command run 

<img width="456" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/35648390/78db5336-240a-416d-bc7c-96a4a5bfc0bc">

there is no config for style like other tutorial / sampe

my file
~/.zshrc 

https://pastebin.com/gcVVFzAC

heres my p10k files, srry for external link got limit issue

https://pastebin.com/Qy4Qz1Gu

thank you

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by 4be** [comment]
now i can use style 

<img width="781" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/35648390/fb16e8f4-71d6-4bb3-913e-df6e161c2e56">

but it cannot split terminal on vscode ? or because its required more width to use it ?
my current laptop resolution 1920 x 1080 

cannot split into half on my vscode?

**Comment by romkatv** [comment]
The error is not related to powerlevel10k or even to zsh.

**Comment by 4be** [comment]
thank you @romkatv, 
Closing comment, hope this will help who might face the same issue
