### ISSUE TITLE
The segments of context ,which display "user@hostname" only valid for root.

### ISSUE THREAD

**Issue by hestmain** [romkatv/powerlevel10k#2328]
The segments of context ,which display "user@hostname" only valid for root.

Like this:
I have uncommented the comments of "context"  for root and other users.
![BUG](https://github.com/romkatv/powerlevel10k/assets/126085381/7fd2a47d-42b7-4342-ab81-8d9c50f34937)
It did work for root.
![BUG1](https://github.com/romkatv/powerlevel10k/assets/126085381/a2523754-ea8d-4d6e-9835-34ea2454c3ba)
But It didn't work for other users.
![BUG2](https://github.com/romkatv/powerlevel10k/assets/126085381/5adf7b46-d582-4ca1-a454-bcf04d8014ac)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-add-username-andor-hostname-to-prompt

**Comment by hestmain** [comment]
Got it , thanks!
