### ISSUE TITLE
Git icons do not honor color styling in function my_git_formatter

### ISSUE THREAD

**Issue by vegardhw** [romkatv/powerlevel10k#2330]
Thumbs up for your great work on powerlevel10k @romkatv - highly appreciated 🙌

The problem I have is that the git/github icons are not following the color styling scheme as defined in the my_git_formatter function. I have set new values for "clean", "modified", "untracked" and "conflicted" and it reflects on the branch name but not the icon.

Result:

![screenshot](https://github.com/romkatv/powerlevel10k/assets/14834153/7c97a8e3-783f-4a8a-9841-f26eaa9534c9)

How can I adjust the same colors for the icon? 🙂

**Comment by romkatv** [comment]
The color of the icon can be set with `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR`.

**Comment by vegardhw** [comment]
Ah, missed that one. Thank you sir! 👍

**Comment by romkatv** [comment]
You are welcome.
