### ISSUE TITLE
Feature request: Allow adding the OS icon to the context, perhaps by doing variable expansion

### ISSUE THREAD

**Issue by noamraph** [romkatv/powerlevel10k#2332]
Hi,
First, thanks for your great work! You make my life better every day!

Now, to the feature request. I moved the "context" segment to the left, since it's important for me to know on which host I am. I also like the OS icon. So it looks like this:

![image](https://github.com/romkatv/powerlevel10k/assets/1553464/3fda168e-c007-4bc8-a641-f836d43ec86a)

However, I would like to shorten it a bit, since really the OS icon is a feature of the host:
![image](https://github.com/romkatv/powerlevel10k/assets/1553464/e9c231bd-3787-47b9-a7b5-0e0c3935ae6d)

I managed to achieve this by replacing this line:

```diff
diff --git a/internal/p10k.zsh b/internal/p10k.zsh
index ac4783e..97e303c 100644
--- a/internal/p10k.zsh
+++ b/internal/p10k.zsh
@@ -1597,7 +1597,7 @@ prompt_context() {
         text=${(P)var}
         text=${(g::)text}
       else
-        text=$_POWERLEVEL9K_CONTEXT_TEMPLATE
+        text=$(eval echo $_POWERLEVEL9K_CONTEXT_TEMPLATE)
       fi
     fi
     _p9k_prompt_segment "$0_$state" "$_p9k_color1" yellow '' 0 "$cond" "$text"
```

and putting this in my configuration file:

```
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='$_p9k_os_icon %m'
```

You may consider adding this feature.

Thanks again, whatevery you decide!
Noam

**Comment by romkatv** [comment]
Try replacing `context` with `context_joined`.

**Comment by romkatv** [comment]
Good idea. Done.
