### ISSUE TITLE
Powerlevel10k Python Versions

### ISSUE THREAD

**Issue by JW1297** [romkatv/powerlevel10k#2333]
Hi, 

I'm just setting up a new MacBook Pro and have only recently started learning about virtual environments - I used to do all of my data science work globally.

I installed iTerm, brew, set up Powerlevel10k and created a virtual environment called 'project-1' in a folder called 'data-science-library'.

There are a few issues that I would really like help with:

1. When I activate my virtual environment in iTerm, my banner on the right hand side changes from < base <  3.10.10 to < project-1 < base < 3.10.10 (see screenshots). Is this normal? I feel like I'm layering python on python here, and all I want to do is to configure iTerm to be able to set up virtual environments for my data science projects. I've not seen it appear like this for other people, so not sure if I have set up my virtual environment incorrectly, or if I have configured iTerm incorrectly, or if this is normal. Please help.
2. Not sure if this is linked to the point above, but after activating my virtual environment, I installed numpy and pandas and these are both present in the 'lib' folder. Then I open Jupyter notebook in this virtual environment and import numpy and pandas and everything is running as expected. But then out of curiosity I imported matplotlib and seaborn, where I expected them not to run (because they haven't been installed) but to my great surprise they did. Starting to get really confused now about why this is and why Jupyter is allowing me to use seaborn and matplotlib when I've not installed them. 

I would really appreciate an explanation (for a dummy like me).

Thanks,

Joe

<img width="1290" alt="Before" src="https://github.com/romkatv/powerlevel10k/assets/114872686/dcd3276c-cf21-4a6a-be99-8d70d8cd2fba">

<img width="1288" alt="After" src="https://github.com/romkatv/powerlevel10k/assets/114872686/a8891983-b0ac-447e-b0e3-ed54c6d5115d">

**Comment by romkatv** [comment]
90% of your question isn't about prompt, so I'm afraid it's not something I can help with. Your prompt looks fine though. I don't see anything problematic with it.

**Comment by JW1297** [comment]
Ok apologies to ask other questions. Would you be able to help me with the 10%? Like why do I have < Venv name < base < python version as my banner on the right?

**Comment by romkatv** [comment]
> why do I have < Venv name < base < python version as my banner on the right?

These are all different prompt segments. You can find out which one is which by disabling prompt segments one by one in `~/.p10k.zsh`. They are close to the top.
