### ISSUE TITLE
Utilize new Git 2.41 `for-each-ref` formatting atom to indicate # of commits ahead/behind

### ISSUE THREAD

**Issue by timtyrrell** [romkatv/powerlevel10k#2335]
Feature Request:

This [Github blog post on Git 2.41](https://github.blog/2023-06-01-highlights-from-git-2-41/) highlights a fantastic optimization using the `for-each-ref` formatting atom, `%(ahead-behind:<base>`, to allow for one query to retrieve the "ahead" and "behind" data.

**Comment by romkatv** [comment]
Thanks for the info. I'll keep it in mind if I ever write code that invokes git.
