### ISSUE TITLE
[Bug] Resizing window causing new lines to be entered in terminal

### ISSUE THREAD

**Issue by Vignesh-Ganesan-008** [romkatv/powerlevel10k#2336]
# [Bug]
I've been using p10k for about 6 months with no issues.
I wanted to change my terminal appearance again so I ran `p10k configure` and changed a few options.
After this, I started facing this issue where, when I resize my terminal window new lines are inserted automatically in the terminal. The same thing happens in vs code integrated terminal as well.

## Apologies for the poor quality.Had to compress it to 480p and split it into three to update it here
https://github.com/romkatv/powerlevel10k/assets/58505455/c8f4212b-90ac-45c5-8b52-0cff20117a7a
https://github.com/romkatv/powerlevel10k/assets/58505455/fcb8cd62-9908-454b-9b36-680d8075e746
https://github.com/romkatv/powerlevel10k/assets/58505455/3f49dd3a-3e2d-4ddb-bbe0-4a64b0eaa0b0

MacOS: Venture 13.3.1 (a) 
Terminal App: Mac Default terminal

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

**Comment by DarshitSolanki04** [comment]
> See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window

Same thing is happening with me too.

Ubuntu: Linux ubuntu22-04 5.15.0-73-generic
Terminal App: ZSH

P.S. - Sure I will check the link. Just mentioning here so that others can know that it is a common problem.
