### ISSUE TITLE
Add OCS99 support to provide pwd to Windows Terminal

### ISSUE THREAD

**Issue by daviewales** [romkatv/powerlevel10k#2337]
Windows Terminal supports OSC99 to determine the current directory from the shell.
It would be nice if powerlevel10k had built-in support to add the OSC99 escape sequence to the prompt, so duplicating tabs and panes pick up the current directory in Windows Terminal. (`Shift+Ctrl+D` and `Shift+Alt+D` respectively.)

The [Microsoft docs](https://learn.microsoft.com/en-us/windows/terminal/tutorials/new-tab-same-directory#zsh) recommend adding the following to your `~/.zshrc` to support this behaviour:

``` zsh
keep_current_path() {
  printf "\e]9;9;%s\e\\" "$(wslpath -w "$PWD")"
}
precmd_functions+=(keep_current_path)
```

Is this in scope to automatically support in powerlevel10k?

Related: 

- https://github.com/microsoft/terminal/issues/3158
- [OhMyPosh](https://ohmyposh.dev/docs/configuration/overview#general-settings) has a configuration for this.

**Comment by romkatv** [comment]
If a feature is not directly related to prompt, and if it can be implemented with a single piece of code that works with all prompts, then it's out of scope for powerlevel10k. In other words, if something can be implemented as an independent plugin, it should be implemented as an independent plugin.

The code snippet provided by Microsoft has a few bugs (some more serious than others) and has much bigger impact on performance than it has to. You can use this plugin instead: https://github.com/romkatv/windows-terminal-zsh-integration.

If you are using zsh4humans, you don't need this plugin. Just make sure that you are on the latest version (run `z4h update` to be safe) and enable shell integration:

```zsh
zstyle ':z4h:' term-shell-integration yes
```

**Comment by daviewales** [comment]
Thank you! Very helpful.
