### ISSUE TITLE
azhw:zle-line-finish:3: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by NoahPsight** [romkatv/powerlevel10k#2341]
My console gets spammed with this message before EVERY command

azhw:zle-line-finish:3: maximum nested function level reached; increase FUNCNEST?

I did "echo $FUNCNEST" and it was set to 500 which should be way more than plenty.

**Comment by romkatv** [comment]
Have you reported it to azhw, whatever that is?

**Comment by romkatv** [comment]
A quick search reveals that `azhw:zle-line-finish` is defined by `add-zle-hook-widget`, which suggests that you are using powerlevel10k with something else. Try to figure out what that *something else* is and report a bug against *that*.

**Comment by NoahPsight** [comment]
This has nothing to do with p10k but zsh_autocomplete; apologies
