### ISSUE TITLE
[question] how to customize POWERLEVEL9K_VCS_GIT_HOOKS

### ISSUE THREAD

**Issue by MushiTheMoshi** [romkatv/powerlevel10k#2342]
hi there,

Awesome work done here , really appreciated all the effort.

Would like to have repository name in LEFT side, though can't find where how to setup this, I found POWERLEVEL9K_VCS_GIT_HOOKS have some options though not too sure if I can create my own hook like `git remote -v` or something similar.

Any help is much appreciated.

Regards,
Julio

**Comment by romkatv** [comment]
1. Run `p10k configure` and choose Rainbow, Classic or Lean style.
2. Open `~/.p10k.zsh` and search for `my_git_formatter`.
3. Add `$VCS_STATUS_REMOTE_NAME` where you see fit within `my_git_formatter`.

**Comment by MushiTheMoshi** [comment]
hey, can you provide an example? every attempt resets the whole style...
