### ISSUE TITLE
Clarification regarding directory classes

### ISSUE THREAD

**Issue by Rahlir** [romkatv/powerlevel10k#2345]
I apologize if this is a wrong way to flag this since it's not really an issue but rather a request for clarification / for better documentation.

I tried to define my own directory classes when I noticed that defining POWERLEVEL9K_DIR_CLASSES actually removes all the icons such as `home` or `open folder`. After inspecting the `internal/` code, I realized that actually there is a default definition of `POWERLEVEL9K_DIR_CLASSES` and, hence, redefining the variable as suggested in the generated config will remove all the icons used by default. I think this is not really clear from the documentation. It might be useful to at least document the default setting of the variable in the generated config. Personally, I was just trying to add new custom directory class, so I needed to _add_ new class to the variable rather than redefine the entire variable.

Secondly, I was wondering why in the documentation it states that `POWERLEVEL9K_DIR_CLASSES` should be an array with 3*N elements where the third element is `An empty string.`. It seems that the default variable sets the icon in the third element. I understand that the icon can also be set using a variable suffix `*_VISUAL_IDENTIFIER_EXPANSION`. Is there a difference? Is it discouraged to set the icon using the third element of the array variable instead of the suffix variable?

Thanks

**Comment by romkatv** [comment]
The docs are indeed lacking. I'm glad you figured out the semantics of `POWERLEVEL9K_DIR_CLASSES`.

> Secondly, I was wondering why in the documentation it states that `POWERLEVEL9K_DIR_CLASSES` should be an array with 3*N elements where the third element is `An empty string.`. It seems that the default variable sets the icon in the third element. I understand that the icon can also be set using a variable suffix `*_VISUAL_IDENTIFIER_EXPANSION`. Is there a difference?

Both approaches work. I documented only one of them because it's more flexible.
