### ISSUE TITLE
how to close gitstaus init

### ISSUE THREAD

**Issue by songzenghui** [romkatv/powerlevel10k#2347]
My env has no internet, so download gitstatusd always failed.
How can i close these function?
![image](https://github.com/romkatv/powerlevel10k/assets/25813311/2fa52c6e-d3c9-49b9-83ce-4a0b6142c2f8)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access

**Comment by songzenghui** [comment]
thank
