### ISSUE TITLE
There is a problem with VScode line wrapping

### ISSUE THREAD

**Issue by Shermonbin** [romkatv/powerlevel10k#2348]
When I enter the carriage return, the symbol "/" appears on the next line, and when I enter at the bottom, the cursor moves to the next line.
![image](https://github.com/romkatv/powerlevel10k/assets/62007827/3c3e781d-32f5-4128-b34d-c80890afe2bb)
![image](https://github.com/romkatv/powerlevel10k/assets/62007827/7b22ffad-ae1b-49eb-84fb-b5607e5ec5ab)

* Windows10，22H2
* git-bash
* VScode1.78.2

**Comment by romkatv** [comment]
Try this:

1. Add the following at the very top of `~/.zshrc`:
   ```zsh
   PS1=$'\uF17A '
   RPS1=$'\uF17A'
   return
   ```
2. Restart your terminal.

Does this work fine?

**Comment by Shermonbin** [comment]
This work fine. Thanks

**Comment by romkatv** [comment]
Then I don't know why rendering doesn't work as expected. Sorry. If you find out, please post an update.

**Comment by huankong233** [comment]
> 

 is the `return` needed?

why i add it in my ~/.zshrc

then it  running in a wrong way

![image](https://github.com/romkatv/powerlevel10k/assets/49610758/f0e7aac1-bad5-481c-94fd-5135ddb6fc3e)

I delete the `return` 

It appears like this:

![image](https://github.com/romkatv/powerlevel10k/assets/49610758/22959835-9ce5-471e-abf5-10ef90c7737d)

sometimes there is a `\` sometimes there is not


enviroment:

- Windows10，22H2
- git-bash 
- VScode1.79.2

**Comment by markspl** [comment]
Hi! I noticed the same issue on my VSCode internal terminal (no WSL setup).

**Environment**
- Windows: Version 10.0.19045 Build 19045
- VSCode :1.84.2
- git: 2.43.0.windows.1
- zsh: 5.9 (x86_64-pc-msys
- oh-my-zsh: commit 18073af (Nov 22th)

Default terminal profile on VSCode terminal: Git Bash

zsh is "installed" on git-bash, and oh-my-zsh was installed with basic install way (curl install.sh command).

I can't repeat the issue on Windows Terminal (git-bash)

What I've tested:
- Different p10k configure styles
    - with and without empty rows
    - with and without compact rows
    - different other style combinations
- disabling plugins "git" and "zsh-autosuggestions"

I noticed, that sometimes after opening another zsh session inside zsh, and exit, it doesn't show " \ " symbol any more on the main session. 

Plus, sometimes I can see how it flashes the symbol quickly on screen.

For example:
```
❯ ls            <-- shows " \ "
❯ bash
❯ bash
❯ ls
❯ ls
❯ ls
❯ bye
❯ ls             <-- doesn't show anymore " \ "
❯ ls                   .  
❯ ls                   .
❯ ls                   .
❯ ls                   .
❯ ls                   .
❯ bye                  .
❯ ls                   . ( top-most session ) 
❯ ls                   .
❯ ls                   .
❯ ls                   .
❯ ls                   .
                 <-- still shows empty row correctly without " \ "
~/testing                                                                                                                                                                                                                                                      20:23:43 
❯
```

**Comment by jathek** [comment]
I was able to fix this on my system by disabling VS Code's `terminal.integrated.windowsEnableConpty` setting.

**Comment by BestLemoon** [comment]
> I was able to fix this on my system by disabling VS Code's `terminal.integrated.windowsEnableConpty` setting.
> 
> The actual issue is from `~\.oh-my-zsh\lib\termsupport.zsh`, in the omz_termsupport_cwd function at the bottom of the file. The printf line somehow causes issues in VS Code when ConPTY is enabled.

Thanks for the solution. It works quite well in ASCII mode, but when I selected Unicode mode, it seemed that always shows two command lines. Quite strange, so I chose ASCII mode now
