### ISSUE TITLE
Why does Powerlevel10k exists?

### ISSUE THREAD

**Issue by bsarrazin** [romkatv/powerlevel10k#235]
I am wondering why this project exists? Maybe it would be a nice paragraph to add to the README?

What is wrong with 9K and what is 10K trying to improve?

I'm just curious to understand why I should consider upgrading?

Thank you for the info!

**Comment by eddyg** [comment]
See https://asciinema.org/a/249531 for one reason.

**Comment by romkatv** [comment]
> I am wondering why this project exists?

It exists because I created it.

> What is wrong with 9K and what is 10K trying to improve?
> I'm just curious to understand why I should consider upgrading?

From the top of the Powerlevel10k homepage:

> Powerlevel10k can be used as a [fast](https://github.com/romkatv/powerlevel10k/blob/master/README.md#is-it-really-fast) drop-in replacement for [Powerlevel9k](https://github.com/bhilburn/powerlevel9k).

And then below:

> To go beyond the functionality of Powerlevel9k, type `p10k configure` and explore the unique styles and features Powerlevel10k has to offer.

So you can consider upgrading from Powerlevel9k if you'd like to make your prompt faster and/or to take advantage of additional features. 

> Thank you for the info!

You are most welcome.
