### ISSUE TITLE
Error after every command

### ISSUE THREAD

**Issue by mlopezcoria** [romkatv/powerlevel10k#2350]
Hello,

I've installed p10k in CentOS 7. It works fine but after every command I get this error message:`-v_p9k__ram_free=${$((my_git_formatter(1)))+${my_git_format}}G `

I think some package is missing but I can't figure out which one.

Thank you for your help, in advance.

**Comment by romkatv** [comment]
Can you reproduce this if you disable all zsh frameworks and plugins apart from powerlevel10k?
