### ISSUE TITLE
Prompt does not change when entered vi mode with vi-find-prev-char

### ISSUE THREAD

**Issue by aoyama-val** [romkatv/powerlevel10k#2351]
~/.zshrc
```shell
bindkey -e
bindkey "^[^[" vi-find-prev-char

source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
source ~/.p10k.zsh
```

[dot.p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/11787818/dot.p10k.zsh.txt)

Type `^[^[` (Esc Esc) and it enters vi mode and waits for a key, but the prompt does not change to indicate the mode.
Is this a feature? Is there any config to change the prompt on this operation?

- p10k from homebrew
- zsh 5.9 (x86_64-apple-darwin22.0)

**Comment by romkatv** [comment]
`vi-find-prev-char` does not enter vi mode. You can see this if you position the cursor at the very end of the buffer before invoking the widget. If `vi-find-prev-char` entered vi mode, it would move the cursor to the left, the same way as `^X^V` (Ctrl-X-V). It does not.

**Comment by aoyama-val** [comment]
Thanks for the quick response.
But while waiting for a key, I would like the prompt to change to indicate that. Is not this possible?

**Comment by romkatv** [comment]
It might be possible but I'm not sure. Powerlevel10k doesn't have an option to enable this though.
