### ISSUE TITLE
`p10k configure --remember-choices`

### ISSUE THREAD

**Issue by felipecrs** [romkatv/powerlevel10k#2352]
I find myself rebasing my p10k configuration often as PRs gets merged here.

To do that, I basically run `p10k configure` and answer the questions again with the same answers as before.

It would be great if I could simply run something like `p10k configure --remember-choices` so that I would not need to go through the questionnaire again if I just want to regenerate my config file.

**Comment by romkatv** [comment]
The choices aren't static and may change arbitrarily when a new version of powerlevel10k is released. As such, `--remember-choices` is impossible.

The solution is to not run `p10k configure` when PRs are merged. There is no need for that.

**Comment by felipecrs** [comment]
> The choices aren't static and may change arbitrarily when a new version of powerlevel10k is released. As such, `--remember-choices` is impossible.

I believe you can simply fallback to the questionnaire if a stored choice doesn't match.

> The solution is to not run `p10k configure` when PRs are merged. There is no need for that.

If I don't do that, I won't get the new features. Example:

- #2311

**Comment by romkatv** [comment]
> I believe you can simply fallback to the questionnaire if a stored choice doesn't match.

I won't be adding a flag that cannot be implemented properly. Sorry.

**Comment by romkatv** [comment]
As for new features, you'll get all of them if you update powerlevel10k. If there is a new segment you want, you can add it to your config.

**Comment by felipecrs** [comment]
> As for new features, you'll get all of them if you update powerlevel10k. If there is a new segment you want, you can add it to your config.

The thing is, I want the exact prompts that P10k ships by default, and this changes over time. In fact I do not make any change to my p10k config after running `p10k configure`.

> I won't be adding a flag that cannot be implemented properly. Sorry.

I didn't mean it was a bullet proof solution, but it would still be a nice time saver. At least for use cases like mine. Anyway, I understand, thank you.
