### ISSUE TITLE
Question - Square Icons in Ubuntu 22 Docker Container ( running VSCode-Server)

### ISSUE THREAD

**Issue by Les-Fleming** [romkatv/powerlevel10k#2353]
I am running VSCode-Server in an Ubuntu container with docker desktop and I am having an issue with the displaying of the icons - in that they are showing as square icons. If I run p10k configure, the diamond is displayed correctly however the lock icon is not. I have tried various different installation of fonts to no avail and have reverted the fonts back to the following:

Location: /usr/share/fonts/truetype/
- 'MesloLGS NF Bold Italic.ttf' 
-  'MesloLGS NF Bold.ttf' 
-  'MesloLGS NF Italic.ttf'  
- 'MesloLGS NF Regular.ttf'

> ❯ fc-list 'MesloLGS NF'
/usr/share/fonts/truetype/meslo/MesloLGS NF Regular.ttf: MesloLGS NF:style=Regular
/usr/share/fonts/truetype/meslo/MesloLGS NF Italic.ttf: MesloLGS NF:style=Italic
/usr/share/fonts/truetype/meslo/MesloLGS NF Bold Italic.ttf: MesloLGS NF:style=Bold Italic
/usr/share/fonts/truetype/meslo/MesloLGS NF Bold.ttf: MesloLGS NF:style=Bold

Host O/S: Ventura 13.4
Docker Desktop Version: 4.20.1 (110738)
Version: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
<img width="882" alt="Screenshot 2023-06-20 at 14 13 51" 
src="https://github.com/romkatv/powerlevel10k/assets/95048020/995f0b8b-38c6-40ea-968d-e306784a2ac5">
<img width="513" alt="Screenshot 2023-06-20 at 14 25 12" src="https://github.com/romkatv/powerlevel10k/assets/95048020/3f3e7673-5134-4071-9947-0b4d90411923">

Am I missing something with Ubuntu 22 for displaying the icons correctly?

Les

**Comment by romkatv** [comment]
You need to install the font on windows.

**Comment by romkatv** [comment]
Sorry, I meant on your host os, whether it's windows or something else.

**Comment by Les-Fleming** [comment]
Hey Roman, thanks for responding. Not sure I follow. My underlying O/S is MacOS and powerlevel10k works perfectly fine on that. It's within in the docker container I have installed the fonts with powerlevel10k.

**Comment by Les-Fleming** [comment]
The change of font is within the container which is abstracted from my host o/s. If I understand your response correctly, you believe this to be possibly an issue with container o/s or the terminal rendered within.

**Comment by Les-Fleming** [comment]
That is exactly what I have done Roman as stated in the detailed description. Feel free to close this out!

**Comment by romkatv** [comment]
The description of the issue suggests that you've installed the font on the vm where the vscode server runs. My point is that you need to install it where the client runs. Try it. In general, fonts are used at the point where fonts are rendered and text turns into pixels.
