### ISSUE TITLE
p10k shows messy display and cursor location when in tmux

### ISSUE THREAD

**Issue by hermit100m** [romkatv/powerlevel10k#2354]
After following the instructions in https://github.com/romkatv/powerlevel10k/issues/1656 and https://gist.github.com/bbqtd/a4ac060d6f6b9ea6fe3aabe735aa9d95, it can show the Unicode in tmux for p10k, however I get the messy display:
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/e5605660-6a9f-45df-a984-ce39b6c216ca)

Inside tmux with ascii (instead of unicode), there is also problem with display:
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/e042be21-9a53-420e-869b-133f8e0ea5de)

Out of tmux it's fine:
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/97311fa0-e271-4f4d-8098-1c80329da271)

Thank you for your kind help!

**Comment by romkatv** [comment]
Run this when in `tmux`:

    PS1='╰─ ' RPS1='─╯' zsh -f

Does it work correctly?

**Comment by hermit100m** [comment]
> 
Thank you for your reply!
It works with problem:
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/565989b3-cdab-4441-8318-dc8067ad360e)

**Comment by romkatv** [comment]
Your screenshot shows that it does not work correctly. Compare with the same command outside of `tmux`.

This is a problem with your setup and not with powerlevel10k. It's possible that you can fix it by passing `-u` to `tmux` and/or by fixing your locale (it must be UTF-8). Once you fix your setup, powerlevel10k will work.

**Comment by hermit100m** [comment]
> 

I set locale in ~/.zshrc and source ~/.zshrc, and restart tmux with 'tmux -u new -s tmp', however the problem remains:

In ~/.zshrc:
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/3927619d-585b-49e4-a2ad-29b16ad3ad9d)

![image](https://github.com/romkatv/powerlevel10k/assets/20102036/0ce5e083-cf35-4500-a883-448c13d1e15d)

![image](https://github.com/romkatv/powerlevel10k/assets/20102036/91fe0ea6-3cc9-4ec6-84ba-3b87435af504)

**Comment by romkatv** [comment]
You might have better luck asking for help from people who use and/or develop tmux. As I mentioned above, this isn't a problem with powerlevel10k (you can reproduce it with the `zsh -f` command I gave you).

**Comment by hermit100m** [comment]
> You might have better luck asking for help from people who use and/or develop tmux. As I mentioned above, this isn't a problem with powerlevel10k (you can reproduce it with the `zsh -f` command I gave you).

You are right. This is what I try:

bash (inside tmux):
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/5c0fcb8f-a554-4f9e-92ec-a61ca6a64d07)

bash (out of tmux):
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/2c506663-4502-456e-a341-0569e633961c)

These above show that the problem probably occur in tmux.  I will refer to the tmux repo for help.
Thank you so much again!
