### ISSUE TITLE
p10k command prompts disappear in tmux

### ISSUE THREAD

**Issue by hermit100m** [romkatv/powerlevel10k#2355]
I installed p10k and is behaves fine outside tmux. However when in tmux sessions, p10k command prompts disappear after I enter 'Enter' for a command. Screenshot:

Outside tmux (normal):
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/9cd459d6-29eb-4587-986f-1fdff8e3212d)

Inside tmux (abnormal):
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/544721da-0600-4b34-b870-43e6d8cec09b)

Where could the problem be? Thank you for your help!

**Comment by romkatv** [comment]
Run `p10k configure`. When it asks whether you want *Transient Prompt*, choose **No**.

**Comment by hermit100m** [comment]
> Transient

This surely solve my problem! Thank you so much!
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/b5314e8a-7961-4a2d-8cca-c59a3a67c69f)

But I am still a little confused why there is such a difference between the behaviors inside and outside a tmux session, when configuring p10k with 'Transient Prompt'. I would appreciate it if you can explain the reasons. Thank you!

**Comment by hermit100m** [comment]
> My best guess is that you did something outside of tmux that broke transient prompt. For example, maybe you ran `source ~/.zshrc` (never run this command).

> Please open a new issue. Before you do, make sure you can reproduce the problem after disabling all plugins except for powerlevel10k.

I set 'Transient Prompt' when i run 'p10k configure':
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/da58591f-60fc-4024-ac4d-58207bf48a11)

Then I run 'source ~/.zshrc' outside of tmux, I sometimes get the following output:
"gitstatus_stop_p9k_:zle:41: No handler installed for fd 16                                                                                                                                                   
gitstatus_stop_p9k_:49: failed to close file descriptor 16: bad file descriptor"
![image](https://github.com/romkatv/powerlevel10k/assets/20102036/9bd2d319-b678-417e-9816-7a7f30daeefa)

I am not sure if this is related to the difference that I detailed above.
Thank you again for your kind explanation!

**Comment by romkatv** [comment]
> Then when I run 'source ~/.zshrc'

When you run this command, anything can happen. Getting errors isn't the worst outcome.
