### ISSUE TITLE
Unable to change the colour of the chezmoi segment

### ISSUE THREAD

**Issue by Logicer16** [romkatv/powerlevel10k#2356]
`POWERLEVEL9K_CHEZMOI_FOREGROUND` and `POWERLEVEL9K_CHEZMOI_BACKGROUND` seem to have been added as part of #2311. However changing these values does not appear to have an effect on the colour of the segment.

Modifying equivalent values for different segments still works as expected.

**Comment by romkatv** [comment]
The segment is called `chezmoi_shell`.

**Comment by Logicer16** [comment]
Ah, sorry. Seems I was looking at something outdated. Thanks for your help
