### ISSUE TITLE
Seeing the phantom untracked changes issue in prompt.

### ISSUE THREAD

**Issue by whazlewo** [romkatv/powerlevel10k#2357]
I've seen this issue where the git status in the prompt does not match the actual git status come up a few times in old issues. 
e.g. https://github.com/romkatv/powerlevel10k/issues/2232#issuecomment-1478166292

My setup:
macOS 13.4 build 22F66
iTerm2
P10k version 1.19.0

So here's what I did to get started looking for it.

* commented out all zsh plugins
* reinstalled P10k 
* re-ran P10k config
* re-cloned repo

When I run `git status` I get the following:
<img width="924" alt="248336230-f5202c70-7a56-4bef-b992-058d24469ab4" src="https://github.com/romkatv/powerlevel10k/assets/4400337/5d9b54b2-6caf-4fa8-a2a0-5443c6a22e1d">

I did `GITSTATUS_LOG_LEVEL=DEBUG exec zsh` and looked at the output. There I found several references to unstaged changes and one untracked file:
<img width="1646" alt="Screenshot 2023-06-23 at 10 48 21 AM" src="https://github.com/romkatv/powerlevel10k/assets/4400337/39e97b2d-dd90-46e2-9fb7-8e2c60bbcb7f">

So I ran a command I saw in a previous issue on that "config" file.
<img width="853" alt="Screenshot 2023-06-23 at 10 47 57 AM" src="https://github.com/romkatv/powerlevel10k/assets/4400337/b8ad1dff-9906-42f6-abb0-c2b73b0d163b">

I tried this just out of curiosity, but it had no effect
https://github.com/romkatv/powerlevel10k/issues/2232#issuecomment-1478166292

I made sure it was not just my repo by checking a random public repo I had cloned
<img width="735" alt="Screenshot 2023-06-23 at 10 51 27 AM" src="https://github.com/romkatv/powerlevel10k/assets/4400337/f31c4855-b216-4c9d-95a4-d512200b77d7">

I'm a bit stumped. Any idea what I could try next?

**Comment by romkatv** [comment]
Check if you have a global git config or if any of the git environment variables are defined (they all start with `GIT`).

**Comment by whazlewo** [comment]
```
~/.config/git
>  env | grep GIT
```
No results

My global looks like this:

```
[user]
	name = Richie Hazlewood
	email = richie.hazlewood@workday.com
[pull]
	rebase = false
[filter "lfs"]
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
[fetch]
	prune = true
[alias]
prune-merged = !git-prune-merged
[credential "https://ghe.megaleo.com"]
	helper = 
	helper = !/opt/homebrew/bin/gh auth git-credential
[credential "https://github.com"]
	helper = 
	helper = !/opt/homebrew/bin/gh auth git-credential
[credential "https://gist.github.com"]
	helper = 
	helper = !/opt/homebrew/bin/gh auth git-credential
[core]
	editor = vim
	worktree = /Users/richie.hazlewood/.config/git
[color]
	ui = true
[init]
	defaultBranch = main
[push]
	autoSetupRemote = true
[index]
	skipHash = false
```

**Comment by romkatv** [comment]
> `worktree = /Users/<redacted>/.config/git`

Probably this. If not, try removing things one by one until you find the culprit.

**Comment by whazlewo** [comment]
Testing...

**Comment by whazlewo** [comment]
I believe this fixed it! Now I need to go read up and understand what the heck that config option was for. 
Thank you!
