### ISSUE TITLE
How to control the padding?

### ISSUE THREAD

**Issue by Erimus-Koo** [romkatv/powerlevel10k#2359]
For example, there are 2 letters before the cloud icon, the first is a separator and the second is a space, can I remove this space? And the same situation is on the right side.
<img width="420" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/17139670/565b6f59-a171-4dca-a080-6f41255a1094">

I have modified a Tmux theme that allows users to customize the padding on each side of the object.

![](https://user-images.githubusercontent.com/17139670/248256215-38a6529d-69ba-49a7-addc-d73c5c0fa234.png)

Can I do the same thing in p10k?

There're 6 values that should be set:
- Left side
  - Leftmost padding (If there is no background color, this padding might be 0)
  - Left padding (padding from the separator, usually 1)
  - Right padding (If the separator has enough space visually, padding might be 0) 
- Right side
  - Left padding (If the separator has enough space visually, padding might be 0) 
  - Right padding (padding from the separator, usually 1)
  - Rightmost padding (If there is no background color, this padding might be 0)

Reducing padding can make the display more compact, especially on small screens, which makes the design more user-friendly.

**Comment by romkatv** [comment]
You can remove various spaces around segments with these parameters:

```zsh
POWERLEVEL9K_LEFT_LEFT_WHITESPACE=
POWERLEVEL9K_LEFT_RIGHT_WHITESPACE=
POWERLEVEL9K_RIGHT_LEFT_WHITESPACE=
POWERLEVEL9K_RIGHT_RIGHT_WHITESPACE=
```

If your terminal screen is narrow, consider switching to *Lean* style and choose *No* when asked whether you want many icons. This will disable decorative icons only. Meaningful icons will still be displayed as normal.

**Comment by Erimus-Koo** [comment]
Thanks, it worked.

And may I control the leftmost and rightmost separately?
For example, the leftmost has no space, and the follows on left left have one space.

Same on the right side. A space after `4s`, and no space after time.
<img width="611" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/17139670/7ada5799-37ea-4226-bef2-676db35ad5b6">

**Comment by Erimus-Koo** [comment]
I got a tricky method to archive it.

For example, in right side:
```
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' ' # a SPACE + a semisphere
  POWERLEVEL9K_RIGHT_LEFT_WHITESPACE=''
  POWERLEVEL9K_RIGHT_RIGHT_WHITESPACE=''
```

And for the right side prompts, the left end is 0, the right side is 0, and the inner separator has a space.

<img width="168" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/17139670/ab10dbfc-08c5-419d-8c6e-44f5c3ffe8ac">

**Comment by Erimus-Koo** [comment]
<img width="130" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/17139670/d772b7ed-fb05-458e-93ac-42727c5eae15">
The green frame is the separator and has 2 letters.
