### ISSUE TITLE
What's the difference between the  MesloNGS fonts linked in fonts.md and the ones provided in official nerd fonts repo?

### ISSUE THREAD

**Issue by superusercode** [romkatv/powerlevel10k#2360]
Per https://github.com/matthewjberger/scoop-nerd-fonts/issues/241 it's not clear if the fonts provided from the [fonts](https://github.com/romkatv/powerlevel10k/blob/master/font.md) page have any differences with the official nerd fonts repository (https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip). Are there any benefits to using the specific one patched here?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#how-was-the-recommended-font-created
