### ISSUE TITLE
[Feature] Indicate whether the git branch is tracked

### ISSUE THREAD

**Issue by bazzilic** [romkatv/powerlevel10k#2361]
This is a request to add an indicator of whether the git branch is tracked or not. It's often a very useful piece of information to have at a glance.

In Oh-My-Posh plugin for PowerShell, the git prompt indicated whether the branch is tracked next to the branch name. So, for an untracked branch, it would just show the branch name, and for a tracked branch that is up to date with the remote, it would show the `≡` symbol. For tracked branches that are ahead/behind it would do the same as Powerlevel does currently with the up/down arrow symbols.

![image](https://github.com/romkatv/powerlevel10k/assets/1805832/b4b690c1-d19d-4833-8533-3a4259505a4b)

**Comment by romkatv** [comment]
I've implemented this. If you update powerlevel10k, run `p10k configure` and select any style except *Pure*, you'll see `=` in git status when your local branch is up to date with the remote.

If many people complain or get confused by the new icon, I'll revert the change.

Note that you can achieve this by editing `my_git_formatter` within your `~/.p10k.zsh`. Something like this:

```diff
-  (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}⇣${VCS_STATUS_COMMITS_BEHIND}"
-  (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
-  (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}"
+  if (( VCS_STATUS_COMMITS_AHEAD || VCS_STATUS_COMMITS_BEHIND )); then
+    (( VCS_STATUS_COMMITS_BEHIND )) && res+=" ${clean}⇣${VCS_STATUS_COMMITS_BEHIND}"
+    (( VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND )) && res+=" "
+    (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}"
+  elif [[ -n $VCS_STATUS_REMOTE_BRANCH ]]; then
+    res+=" ${clean}≡"
+  fi
```

You don't need to update powerlevel10k or run `p10k configure` if you opt for the manual edit approach.

**Comment by gozssky** [comment]
![image](https://github.com/romkatv/powerlevel10k/assets/17199941/1b1d959e-15bc-4f5b-80cf-ea4d09e7e31d)

The new icon takes up more prompt space. I would prefer the old version.

**Comment by romkatv** [comment]
@gozssky See https://github.com/romkatv/powerlevel10k/issues/2377#issuecomment-1627633992.

**Comment by romkatv** [comment]
> If many people complain or get confused by the new icon, I'll revert the change.

I've received 3 complaints and reverted the change.

Note that the original commit and the revert commit only affect the content of configs generated by the configuration wizard. Neither of these commits affects the behavior of powerlevel10k with a fixed config. Thus, if you want to see/hide `=` for up to date branches, run `p10k configure`. If that doesn't produce the desired results, manually edit `my_git_formatter` in `~/.p10k.zsh`.

**Comment by bazzilic** [comment]
Can this be configurable (enable/disable) in the `p10k configure`?

**Comment by romkatv** [comment]
Only important options make their way into the configuration wizard. An option that hardly makes a difference isn't worth everyone's time when they are running the wizard. It is perfectly suitable for customization through editing `~/.p10k.zsh` though.
