### ISSUE TITLE
conda env is disappear after reopen iTerm2

### ISSUE THREAD

**Issue by xiao333ma** [romkatv/powerlevel10k#2363]
follow this instruction [#809](https://devops.woa.com/console/pipeline/tencentmap-ios/p-fe5f8b559cad4cb5a31b7e7f6a4d7544/detail/b-c2d5ee884a2b4027998b9249e0ea6ead), the `conda env` can show on the right side, but when i reopen iTerm2, it's disappear. how to keep it, please help me
 
![image](https://github.com/romkatv/powerlevel10k/assets/13362118/d68558bb-7f45-4e7b-ae5e-9aedc64ed7f2)

**Comment by romkatv** [comment]
Please describe what you do, what you expect and what you observe.

**Comment by xiao333ma** [comment]
I want to display `conda env` continuously on the right side. what should i do?

**Comment by romkatv** [comment]
1. Remove all zsh startup files, including .zshrc.
2. Install powerlevel10k.
3. Restart the terminal.
4. When the configuration wizard pops up, select any style except *Pure*.

**Comment by xiao333ma** [comment]
Thank you so much. it's work.
