### ISSUE TITLE
[Issues]: How to use the Backspace key to delete only one character.

### ISSUE THREAD

**Issue by Killing11L** [romkatv/powerlevel10k#2365]
May I ask why the whole source word will be deleted when I use the backspace button? What I want is to delete only one character. thank you

![image](https://github.com/romkatv/powerlevel10k/assets/66837406/a86924fd-6aa4-41bf-89ed-bf7ec0793375)

**Comment by romkatv** [comment]
Powerlevel10k has no effect on the behavior of keys. It only displays prompt.

**Comment by Killing11L** [comment]
> Powerlevel10k has no effect on the behavior of keys. It only displays prompt.
Thank you, but could you please ask me what direction I should try to solve this problem? This is my first time using zsh, thank you very much.

**Comment by romkatv** [comment]
Maybe this will help: https://www.reddit.com/r/zsh/comments/13plztr/hi_someone_know_how_i_can_fix_this_zsh_jump/. If it does not, please ask for help elsewhere. The issue tracker on powerlevel10k is for issues with powerlevel10k.

**Comment by Killing11L** [comment]
> Maybe this will help: https://www.reddit.com/r/zsh/comments/13plztr/hi_someone_know_how_i_can_fix_this_zsh_jump/. If it does not, please ask for help elsewhere. The issue tracker on powerlevel10k is for issues with powerlevel10k.

Okay, thank you very much. Sorry to interrupt.
