### ISSUE TITLE
Prompt spans to a third line when using Warp

### ISSUE THREAD

**Issue by sfxandy** [romkatv/powerlevel10k#2366]
When using the latest build of Powerlevel10k on Warp (great work on the integration BTW!), my prompt seems to split over three lines. 

<img width="705" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/137955820/ee45a27a-0ef2-4d56-aa3a-3c1a5a6b17b2">

I've tried `p10k configure` a couple of times and even if I choose to have the prompt display on a single line, the cursor begins immediately on the next line.  Hopefully the screenshot above demonstrates the issue.

**Comment by romkatv** [comment]
It's a bug in warp. I don't know if or when it'll be fixed. I have no affiliation with that project. See https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1608852450
