### ISSUE TITLE
Weird behaviour in IntelliJ prompt

### ISSUE THREAD

**Issue by chrisclayson** [romkatv/powerlevel10k#2367]
Hi,

I've started using powerlevel10k in the last few days and am LOVING it.

I just thought I'd report a bit of weird behaviour that I'm experiencing the in console in IntelliJ in case you have any pointers (ultimately might be JetBrains problem).

So my prompt works perfectly in native MacOS terminal and in iTerm2 (my preference), however, it seems that in IntelliJ it when it redraws the prompt (for example when updating VCS info) it does it on a new line:
![image](https://github.com/romkatv/powerlevel10k/assets/8633930/f29f1727-188d-49cb-8ce1-e21e4fcde589)

It then puts the cursor on a blank line, rather than after the prompt where it should be. Its as if its adding a newline every time it draws the prompt.

This is what it looks like in iTerm2, which is perfect:

![image](https://github.com/romkatv/powerlevel10k/assets/8633930/4ad56a8e-6642-4572-89b8-d965faafe155)

I have tried disabling Instant prompt, still no joy ... if I disable VCS I, obviously, don't get the new lines from redrawing the VCS info, but still get the new line before the cursor.

Here's the weird part ... if I use IntelliJ on my other Mac it works fine 🤷🏻  I have compared the configuration of both machines and they are the same, I've even tried a totally fresh install of IntelliJ and still no joy.

Is there PowerLevel config that might be affecting this behaviour, or am best off looking towards the IntelliJ as the source of the problem?

Any advice you could give would be great :-)

**Comment by chrisclayson** [comment]
Just as an informational, it seems to be something to do with the way that the IntelliJ console renders certain nerd font icons. I modified my config to remove the icons displayed with `jvm` and `nvm` segments, plus one of my own custom segments, and it all works fine.

It seems that the IntelliJ install on both my machines were misbehaving in different ways ... the one on the Apple Silicon Mac was inserting the additional newlines (as described), but what I had not noticed was that the Intel build Mac was adding additional spaces, which weren't immediately noticeable.

Either way, you're right, its an issue with the IntelliJ console ... I'll report to them :-)

**Comment by romkatv** [comment]
Thanks for the update!
