### ISSUE TITLE
Unable to locate credentials. aws-vault

### ISSUE THREAD

**Issue by timur-khakhalev** [romkatv/powerlevel10k#2368]
Hi! I have WSL2 and p10k, zsh and after I installed aws-vault (several month ago) on every terminal startup I got an error` "Unable to locate credentials. You can configure credentials by running "aws configure""` 
I understand that p10k or something is trying to do some aws but I cant find where this command is fires.

I tried to grep by string "aws" in my home folder but didnt found something that can do this command on startup.

I have next config files in my home dir:
```
 .gitconfig-personal  .shell.pre-oh-my-zsh
..                    .gitconfig-work      .ssh
.Makefile.swp         .gnupg               .v8flags.9.6.180.15-node.13.63a9f0ea7bb98050796b649e85481845.json
.aws                  .java                .viminfo
.aws-sam              .local               .vscode-server
.awsvault             .mongodb             .wget-hsts
.bash_history         .motd_shown          .xsession
.bashrc               .ngrok2              .zcompdump
.cache                .node_repl_history   .zcompdump-DESKTOP-ER4032A-5.8
.cdk                  .npm                 .zsh_history
.config               .nuxtrc              .zshrc
.cookiecutter_replay  .nvm                 .zshrc.save
.cubestore            .oh-my-zsh           .zshrc.save.1
.curl-format.txt      .p10k.zsh           
.dbus                 .password-store     
.docker               .pki                 
.ffbinaries-cache     .profile             
.fzf                  .pycharm_helpers     
.fzf.bash             .python_history     
.fzf.zsh              .s3cfg               
.gitconfig            .selected_editor
```

So I checked .zshrc, .bashrc, .p10k.zsh, .profile but didnt found aws command which invokes on startup

Is there any other ways to find out source of problem?

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with a different theme?

**Comment by timur-khakhalev** [comment]
> What happens if you disable powerlevel10k or replace it with a different theme?

I commented string "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh" at .zhrc, on next terminal startup p10k started configuring, I quit, but got this error "Unable to locate credentials. You can configure credentials by running "aws configure"" again

**Comment by romkatv** [comment]
What happens if you disable the whole of powerlevel10k rather than just your own config?

**Comment by timur-khakhalev** [comment]
> What happens if you disable the whole of powerlevel10k rather than just your own config?

Commented strings that grep gave me at this FAQ https://github.com/romkatv/powerlevel10k#how-do-i-uninstall-powerlevel10k

but got an error again

**Comment by romkatv** [comment]
You've disabled powerlevel10k and the error still persists. This means the error is not coming from powerlevel10k. Closing.

**Comment by timur-khakhalev** [comment]
Thanks for help, I tried to uninstall aws cli and found that at my .zshrc I have an alias that uses command $(aws ...) so when terminal starts, alias trying to invoke this command.
Thank you

**Comment by romkatv** [comment]
Depending on what that alias does, perhaps it should have single quotes as the initializer instead of double quotes.
