### ISSUE TITLE
The prompt keeps duplicating over time in the iTerm2 hotkey window

### ISSUE THREAD

**Issue by navinthomas** [romkatv/powerlevel10k#2370]
### Description

- The powerlevel10k prompt keeps duplicating over time in the iTerm2 hotkey window, when there is no user interaction for a while.
- This seems to happen only in the iTerm2 hotkey window. The issue has not observed in the normal windows of iTerm2.

### Troubleshooting done

- Updated powerlevel10k to latest available version
  - local powerlevel10k git repo's latest commit: 20323d6f8cd267805a793dafc840d22330653867
  - local powerlevel10k git repo's release tag: v1.19.0
- Tested if issue is reproducible on the default ZSH_THEME (`robbyrussell`)
  - Issue not reproducible on the `robbyrussell` theme, but becomes reproducible again when ZSH_THEME was changed back to `powerlevel10k/powerlevel10k`
- Ensured that iTerm2 is on the latest version
  -  iTerm2 version: Build 3.4.19

### Screenshots
Screenshot 1
<img width="1840" alt="SCR-20230701-qitz" src="https://github.com/romkatv/powerlevel10k/assets/34918736/cf208254-432b-43bd-ba05-9d9d8fee7bb1">
Screenshot 2
<img width="1840" alt="SCR-20230628-jnmm" src="https://github.com/romkatv/powerlevel10k/assets/34918736/d8ea1567-72a0-4fc2-8116-8afe60e1bd6e">

**Comment by romkatv** [comment]
Please file a bug against iTerm2.

**Comment by navinthomas** [comment]
@romkatv Considering that this issue does not appear in the `robbyrussell` theme, could it likely be specific to powerlevel10k?

**Comment by romkatv** [comment]
From your description I understand that the issue is specific to powerlevel10k on iTerm2.

**Comment by navinthomas** [comment]
I have noticed that the prompt duplication happens when the system goes to sleep. For some reason, it happens only for the hotkey window and not the other windows.

**Comment by romkatv** [comment]
In this case it's probably https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window. The windows likely gets resides when the system goes to sleep or wakes up.
