### ISSUE TITLE
Last VCS tag in prompt

### ISSUE THREAD

**Issue by rwmitchell** [romkatv/powerlevel10k#2371]
If the current commit has a tag, it'll be displayed in the prompt.  Is it possible to the most recent tag?

**Comment by romkatv** [comment]
What?

**Comment by rwmitchell** [comment]
for example, if P10K is back one version, the prompt can be configured to display:

<img width="302" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/15944841/0484517d-2261-4fc6-bf8e-e81fdf5b12c1">

but if on the latest commit, the tag info is no longer displayed.  I realize what I'm asking may not be the intended use of tags, but knowing the last release name (and possibly how many commits since that release) would be useful to me.

**Comment by romkatv** [comment]
Oh, I see what you mean. No, powerlevel10k cannot do this.
