### ISSUE TITLE
strange string

### ISSUE THREAD

**Issue by huankong233** [romkatv/powerlevel10k#2372]
![image](https://github.com/romkatv/powerlevel10k/assets/49610758/24beaa71-1a29-4506-bf0a-a02d725de807)

font:"MesloLGS Nerd Font Mono"

- vscode
- git-bash
- windows

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by huankong233** [comment]
> https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

thanks, I got what this mean just now 😂

**Comment by huankong233** [comment]
> https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

please have a see [issues](https://github.com/romkatv/powerlevel10k/issues/2348)
