### ISSUE TITLE
My configuration wizard can't show all prompt style

### ISSUE THREAD

**Issue by Kennyezzz** [romkatv/powerlevel10k#2373]
What I use:
![image](https://github.com/romkatv/powerlevel10k/assets/94801292/490cc74c-dd95-432a-8cdb-d5fdf450f30c)
My windows terminal setting:
```json
    "profiles": 
    {
        "defaults": 
        {
            "colorScheme": "One Half Dark (modded)",
            "font": 
            {
                "face": "MesloLGS NF"
            },
            "opacity": 88
        },
```
When I use configuration wizard, it can't show all prompt style although I have follow the steps from [Some prompt styles are missing from the configuration wizard](https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard), and the icons in configuration wizard show correctly, but it still can't show the prompt styles with icons.
![image](https://github.com/romkatv/powerlevel10k/assets/94801292/f84dcbf4-2a93-47fe-979f-db97c4913b80)

**Comment by romkatv** [comment]
Everything on your screenshot looks fine to me. What do you see as a problem?

**Comment by Kennyezzz** [comment]
I found what I miss, it is not choosing Unicode when setting character set.
![image](https://github.com/romkatv/powerlevel10k/assets/94801292/6bf9780c-1c4b-4486-920a-2fb5f4264676)
![image](https://github.com/romkatv/powerlevel10k/assets/94801292/c48aea95-255b-4549-93fe-fd926a716a21)
