### ISSUE TITLE
Tiny icon issue

### ISSUE THREAD

**Issue by Erimus-Koo** [romkatv/powerlevel10k#2375]
<img width="712" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/17139670/70649488-bbb7-4b95-a44b-90204328732e">

There's a default python icon follows the `pyenv`, and it's a little small.
And I find a bigger one in my `JetBrainsMono Nerd Font`, it looks better.

```
small one:  \ue73c
big one:    \ue606
```

I'm not sure if it appears in all nerd fonts.
Maybe there's some doc about nerd font?

And can I change the icon manually?

**Comment by romkatv** [comment]
To change the icon, add the following line to `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_PYTHON_ICON='\uE606'
```

Or with an extra space:

```zsh
typeset -g POWERLEVEL9K_PYTHON_ICON='\uE606 '
```

**Comment by romkatv** [comment]
In the future if you want to change an icon for some prompt segment, you can open `~/.p10k.zsh`, find the section that relation to the prompt segment you are after, and edit the parameters present in there. One of them is for the icon and it has the appropriate comment on it.

**Comment by Erimus-Koo** [comment]
Got it, I noticed there're so many stars. 

I found that I can also change the icon by modifying this line
```
typeset -g POWERLEVEL9K_PYENV_VISUAL_IDENTIFIER_EXPANSION=
```

**Comment by romkatv** [comment]
That's the intended parameter for changing this icon. I gave you a different (undocumented) parameter because I didn't know the name of the segment on your screenshot. The parameter I gave you changes the python icon in all segments that use that icon.
