### ISSUE TITLE
transient prompt uses different left segment end than interactive prompt

### ISSUE THREAD

**Issue by prashantv** [romkatv/powerlevel10k#2376]
I'm setting `typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=':'` so that my prompt ends with `:` (this is not the actual character I want to use, but it makes the repro clearer)

The interactive prompt uses the `:` correctly,
```
~
>:**CURSOR**
```

However, the transient prompt shows a blank space between the prompt and command instead of the expected `:`,
```
> echo hello
hello
> echo world
world
~
>:**CURSOR**
```

I'm not sure where the blank space is coming from. I've tried making the end separator blank (so I could put the character I want in the prompt character), but that also didn't work -- there's still a space between the prompt and command.
```
> echo hello
hello
> echo world
world
/Users/prashant
>**CURSOR**
```

**Comment by romkatv** [comment]
Thanks for the report. Fixed.

**Comment by prashantv** [comment]
Thank you for such a fast fix!

**Comment by romkatv** [comment]
Have you tried it? Does it work for you?

**Comment by prashantv** [comment]
Yes, tried it, and verified that it works as expected now, and separator is used in the transient prompts.

**Comment by romkatv** [comment]
Thanks for verifying.
