### ISSUE TITLE
how to remove '=' from git dir

### ISSUE THREAD

**Issue by eldoranstars** [romkatv/powerlevel10k#2377]
### Steps to reproduce
wsl --install
```
sudo apt update && sudo apt upgrade -y
sudo apt install zsh -y
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="powerlevel10k\/powerlevel10k"/g' ~/.zshrc
```
What happened?
![image](https://github.com/romkatv/powerlevel10k/assets/45801218/c2b2ecb1-5207-4506-80b7-c234ebc955cd)
What was expected?
![image](https://github.com/romkatv/powerlevel10k/assets/45801218/c159eb3d-d391-4efa-a089-e63a8b052041)

I want to remove = symbol
can you help me plz?

**Comment by romkatv** [comment]
`=` means the branch you are on is up to date with the remote. You can remove it as follows:

1. Open `~/.p10k.zsh`.
2. Locate and delete this line: https://github.com/romkatv/powerlevel10k/blob/20323d6f8cd267805a793dafc840d22330653867/config/p10k-lean.zsh#L429
3. Save your changes.
4. Restart zsh with `exec zsh`.

**Comment by eldoranstars** [comment]
it symbol come after v1.19.0 release, test it
TY!
