### ISSUE TITLE
bug: Azure subscription color classes is bugging

### ISSUE THREAD

**Issue by benm-stm** [romkatv/powerlevel10k#2378]
when defining colors for the different subscription based on patterns, the latter one is loosing the name context
Also the documentation doesn't mention azure as supported in this feature
```sh
typeset -g POWERLEVEL9K_AZURE_CLASSES=(
      '*prod*'  PROD
      '*test*'  TEST           
      '*'       DEFAULT)

typeset -g POWERLEVEL9K_AZURE_DEFAULT_FOREGROUND=32
typeset -g POWERLEVEL9K_AZURE_TEST_FOREGROUND=green
typeset -g POWERLEVEL9K_AZURE_PROD_FOREGROUND=red
```

Also the documentation for azure is not found

**Comment by romkatv** [comment]
Fixed by #2379
