### ISSUE TITLE
'=' before the end sign appearing on every prompt with a git directory

### ISSUE THREAD

**Issue by roysupriyo10** [romkatv/powerlevel10k#2380]
Ever since one of the last updates, I have been getting an '=' sign on the prompts inside a git directory. Attached image for description. Any help on how to remove it would be appreciated (by changing the prompt configs perhaps?).

![20230712_08h03m26s_grim](https://github.com/romkatv/powerlevel10k/assets/54949943/99851465-12de-43b7-a872-25dd9d6f94b8)

![20230712_08h07m23s_grim](https://github.com/romkatv/powerlevel10k/assets/54949943/ae3c953b-6a2a-4f8b-ad1c-171793065467)

![20230712_08h07m58s_grim](https://github.com/romkatv/powerlevel10k/assets/54949943/6579f749-0606-4358-a338-488b51da1c05)

However, only when there are no commits but the branch is ahead of HEAD, the '=' sign disappears

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/2377#issuecomment-1627633992

**Comment by roysupriyo10** [comment]
I think you have done enough to provide for a way to do this manually to the OP of the requestor. You could mention in the documentation if someone would want a feature such as this. In any case, now that I think of it, the feature is actually kind of useful. However, I would implement it manually using your posted config if I ever wanted to

**Comment by romkatv** [comment]
There is a comment in the generated `~/.p10k.zsh` explaining how to achieve this: https://github.com/romkatv/powerlevel10k/blob/932954a8b1e31ae540e9df5e5e464100d46e53ec/config/p10k-lean.zsh#L428-L429

There are other tips of this kind, too.

**Comment by roysupriyo10** [comment]
thanks
