### ISSUE TITLE
Clion: Powerlevel10k broken on Clion IDE

### ISSUE THREAD

**Issue by pront** [romkatv/powerlevel10k#2381]
Similar to: https://github.com/romkatv/powerlevel10k/issues/1128

![pavlos rontidis@COMP-LPF0JYPP2Q~ 2023-07-13 at 9 59 53 AM](https://github.com/romkatv/powerlevel10k/assets/1138161/d015c2d0-b0e3-4cb2-899e-d16e1174b843)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

If this does not help, file a bug against Clion.

**Comment by pront** [comment]
Changing the Console Font to "MesloLGS NF" helps. It's not perfect, but better.
