### ISSUE TITLE
Add prompt segment for current history mode: global vs. per-directory

### ISSUE THREAD

**Issue by cohml** [romkatv/powerlevel10k#2384]
The `per-directory-history` zsh plugin allows users to toggle between directory-specific command histories and overall command histories. This allows for much more rapid and effective history searching. It's awesome.

However, it is kind of annoying to have to manually check my history to deduce which mode I'm in. E.g. `history | wc -l` --> huge number indicates "global history mode", while a smaller number indicates per-directory history mode. Note that simply scrolling through the last few commands is not always clear, as these may be generic, e.g., `ls -l`.

In the P10K spirit of an info-packed prompt, it would be so useful to add a prompt element which concisely shows which mode your history is in. For example:

    ~/some_dir [G]    # global history mode
    ~/some_dir [D]    # per-directory history mode

From a quick skim of your source code, it seems like the `POWERLEVEL9K_*_PROMPT_ELEMENTS` variables may be the most sensible place to set this. But maybe there's a better way.

**Comment by cohml** [comment]
It appears that the `per-directory-history` plugin sets a `_per_directory_history_is_global` variable which is `true` if mode == global else `false`.

That could be a nice, simple way to detect the mode within P10K and update the prompt accordingly.

**Comment by rwmitchell** [comment]
Concur!

I use per-directory-history but never toggle to global because there is no clear indication which mode is being used.

**Comment by romkatv** [comment]
You can use a custom prompt segment for this.

```zsh
function prompt_my_history() {
  if [[ $_per_directory_history_is_global == true ]]; then
    p10k segment -b yellow -f red -t G
  else
    p10k segment -b yellow -f red -t L
  fi
}
```

Put this in `~/.p10k.zsh` and add `my_history` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in the same file. You can customize colors and the icon the same way as for all other segments.

See `p10k help segment` for docs.

**Comment by cohml** [comment]
Wow, this is perfect and works like an absolute charm! Thank you for making it so easy!

For @rwmitchell, and others in the future interested to know, here is the entirety of what I added to my `p10k.zsh` file to get this working, added around line 1650 where the discussion of custom prompt segments is located:

    function boldface() {
      echo "\033[1m${1}\033[0m"
    }
    function prompt_my_history_mode() {
      if [[ $_per_directory_history_is_global = true ]]; then
        p10k segment -f '#e57374' -t "$(boldface G)"
      else
        p10k segment -f '#e57374' -t "$(boldface L)"
      fi
    }
    echo "${plugins}" | grep -q "per-directory-history" && POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
      my_history_mode
      ${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS}
    )

This will add the proposed segment only when the `per-directory-history` plugin is enabled.

The result (for me) looks as follows:

<img width="857" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/62400541/ebef542f-5a24-4d6a-aa06-921d3eb27365">
<img width="857" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/62400541/05f28231-a069-4fa3-85ce-824e2f1ef8a4">

@romkatv If you think this segment or a simplified version might be more widely useful, I'd be happy to submit a PR for it. Otherwise, my feelings are not hurt :)

Thanks again!

**Comment by rwmitchell** [comment]
I'm going to assume Roman is not going to add it because he's trying minimize complexity while maximizing only the most commonly used features.  As it isn't hard to add custom segments, I've added (and dropped some) several of my own, it isn't necessary to add everyone's pet feature.

While these do not need to be added to p10k, I love sharing ideas people come up with, either to use outright or to modify.  The question becomes where to share them, that encourages community activity and easily discoverable by other p10k users.

**Comment by romkatv** [comment]
I added `per_directory_history` to Powerlevel10k. It's enabled by default in configs generated by `p10k configure` (except if you choose Pure style).

**Comment by cohml** [comment]
That's awesome! Thanks!
