### ISSUE TITLE
ish-app ，ERROR: gitstatus failed to initialize

### ISSUE THREAD

**Issue by yasencoder** [romkatv/powerlevel10k#2389]
I installed the theme Powerlevel10k for the ish app, but when I opened the app, I encountered an error message: gitstatus failed to initialize
![image](https://github.com/romkatv/powerlevel10k/assets/16420441/58d8f8d7-7ce4-4f3d-8794-0952841b14b4)

**Comment by romkatv** [comment]
It's a bug in iSH: https://github.com/ish-app/ish/issues/783
