### ISSUE TITLE
Whitespaces added to segments

### ISSUE THREAD

**Issue by brainbug89** [romkatv/powerlevel10k#239]
I noticed a different to powerlevel9k after loading powerlevel10k with
```
git clone https://github.com/romkatv/powerlevel10k.git /tmp/powerlevel10k
source /tmp/powerlevel10k/powerlevel10k.zsh-theme
```

As you can see powerlevel10k adds whitespaces after every segment:
![image](https://user-images.githubusercontent.com/21130949/65774929-801bb700-e13f-11e9-85b2-49ee3a98353f.png)

Before powerlevel10k was sourced, powerlevel9k was used.

**Comment by romkatv** [comment]
From FAQ:

> Powerlevel10k strives to be bug-compatible with Powerlevel9k but not when it comes to egregious bugs. If you accidentally rely on these bugs, your prompt will differ between Powerlevel9k and Powerlevel10k. Some examples:
>
> - Powerlevel9k doesn't respect `ZLE_RPROMPT_INDENT`. As a result, right prompt in Powerlevel10k can have an extra space at the end compared to Powerlevel9k. Set `ZLE_RPROMPT_INDENT=0` if you don't want that space.

This bug has also been fixed in the development branch of powerlevel9k.

**Comment by romkatv** [comment]
Sorry, I've missed that you are also pointing out to extra spaces after some icons.

Powerlevel9k deals with the problem of non-monospace fonts in an inconsistent way while Powerlevel10k does it consistently. To configure Powerlevel10k for your prompt you'll probably want to define `POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER// }'`.

You might also want to run `p10k configure` a few times (it handles fonts automatically). If you don't like the results, remove the two lines from the bottom of `~/.zshrc` that `p10k configure` adds. It won't change anything else.

**Comment by brainbug89** [comment]
Thanks `ZLE_RPROMPT_INDENT=0` helped me. I can live with the spaces after the icons.
