### ISSUE TITLE
Font detection wizard for MesloLGS NF does not give access to all os icons

### ISSUE THREAD

**Issue by mgkurtz** [romkatv/powerlevel10k#2392]
The font detection wizard notices, that the up to date MesloLGS NF provides an upward arrow in the old `\uFC35` and comes to the wrong conclusion, that this uses an older Nerd Font, setting `POWERLEVEL9K_MODE=nerdfont-complete`, where `POWERLEVEL9K_MODE=nerdfont-v3` would work as well and provide more symbols, especially some Linux OS logos.

Perhaps we can ask for `\UF0737` first?

**Comment by romkatv** [comment]
If your font contains both v2 and v3 symbols, the wizard currently defaults to v2. If you want to force v3, you can lie to the wizard about the v2 symbol and say that it does not render for you.

The current behavior of the wizard is temporary. I'll change it when all popular terminals fix outstanding bugs with the rendering of symbols that cannot be encoded as 2 bytes in UTF-16.

**Comment by mgkurtz** [comment]
Ah, okay. Thanks a lot for the quick reply.
