### ISSUE TITLE
ish-app，[ERROR]: gitstatus failed to initialize

### ISSUE THREAD

**Issue by yasencoder** [romkatv/powerlevel10k#2393]
I encountered an error message after installing powerlevel10k on my iPhone using ish.

![image](https://github.com/romkatv/powerlevel10k/assets/16420441/a7e58bd9-f5da-4696-987c-49c536479110)

**Comment by yasencoder** [comment]
Why close my issue？I need help

**Comment by romkatv** [comment]
You filled two identical issues. Here's the other one: https://github.com/romkatv/powerlevel10k/issues/2389#issuecomment-1649193192

**Comment by yasencoder** [comment]
I’m so sorry
