### ISSUE TITLE
p10k configure error message unless `setopt multibyte` is on

### ISSUE THREAD

**Issue by phord** [romkatv/powerlevel10k#2397]
Why must I manually enable the multibyte option before running p10k configure?

If this really is necessary, maybe it should be mentioned in the README.

    > p10k configure
    [ERROR] p10k configure: multibyte option is not set

    > setopt multibyte
    > p10k configure

    New config: ~/.p10k.zsh.
        :

**Comment by romkatv** [comment]
Why do you have multibyte disabled? What's your use case?

**Comment by romkatv** [comment]
I took a look at the code and was unable to figure out why the hard requirement for `MULTIBYTE` exists. I've replaced it with graceful degradation similar to what happens when you run `p10k configure` without a UTF-8 locale.

I'm still curious to know why you've disabled `MULTIBYTE` in your shell.

**Comment by phord** [comment]
I don't know why it's disabled in my shell. I think it goes back to a bug in Gnome Terminal that was fixed 5 years ago. 

It was annoying to get a fatal error message telling me about a specific cause but which then offered no advice for how to fix it.

**Comment by romkatv** [comment]
Thanks for the explanation.

How you fix it depends on your configs. In a nutshell, you need to find and delete the piece of code in your zsh startup files that disables `multibyte`.

**Comment by phord** [comment]
Yes, I did figure out how to fix it.  I just felt like the error message could have been more helpful.  

I did check my config history to see why I turned it off.  But it was in my config before my dotfiles repo existed, so it goes back more than 10 years.  Bit-rot, I guess.
