### ISSUE TITLE
Is it possible to overwrite username?

### ISSUE THREAD

**Issue by AdelleBernal** [romkatv/powerlevel10k#2398]
I am attempting to change my username for something different in order to record videos of my workflow. Instead of hiding the username, is it possible to change it without having to create a new user? Thanks.

**Comment by romkatv** [comment]
I infer from your question that your prompt displays the username. I assume that it's a part of the `context` prompt segment. If this is indeed the case, take a look at these lines in `~/.p10k.zsh`: https://github.com/romkatv/powerlevel10k/blob/9bb15e9ffbf43663a77949ea31d6f18c74e8981c/config/p10k-lean.zsh#L897-L902

Here `%n` expands to the username. You can replace it with something else. For example:

```zsh
# Default context format (no privileges, no SSH): fakeusername@hostname.
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='fakeusername@%m'
```
