### ISSUE TITLE
Store cache in a specific zsh / powerlevel10k folder ?

### ISSUE THREAD

**Issue by Murazaki** [romkatv/powerlevel10k#2399]
I see a lot of cache files are saved in `${XDG_CACHE_HOME:-$HOME/.cache}` in the root of the cache folder. Could we clean the root of .cache and put all of those files in a specific folder ?
That might help on the clean up too.

maybe just give it a environment variable like :
`ZCACHEDIR=${XDG_CACHE_HOME:-$HOME/.cache}/zsh`

or more specifically maybe :
`P10KCACHEDIR=${XDG_CACHE_HOME:-$HOME/.cache}/zsh/p10k`

and of course make sure the folder exists :
`mkdir -p $ZCACHEDIR`
`mkdir -p $P10KCACHEDIR`

**Comment by romkatv** [comment]
You can override `XDG_CACHE_HOME` when sourcing powerlevel10k. Instead of this:

```zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

Do this:

```zsh
XDG_CACHE_HOME=~/.cache/p10k source ~/powerlevel10k/powerlevel10k.zsh-theme
```

This isn't the default because this may cause issues when using stuff like `sudo -Es`. I don't recommend doing this unless you actually have a reason (in which case please share what that reason is).

**Comment by Murazaki** [comment]
I'm running a NixOS installation and I realized most of my tools follow [XDG Base Directories Spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), but that p10k files are on the root, while the rest are on proper folders.

While it is true that the spec is not very precise on storing data inside the cache folder, it seems like a good thing to keep those separate (which could in the future give the possibility to proper folder restricted access and on demand access to other app folders. In this paradigm, having those files in the root might also mean that they are not properly protected, and as shell functionality files, it might become unsafe).

**Comment by romkatv** [comment]
Powerlevel10k cache files are properly protected.

Unless you are solving a real problem, I highly recommend doing nothing in this regard. If you really want to change the location of p10k cache files, follow the recipe I've given above.

**Comment by Murazaki** [comment]
Sorry to come back to this, but it does break some configuration in NixOS to have to source plugins manually, and I don't find it very safe to modify XDG_CACHE_HOME, even just to source this file, as it is the common XDG cache folder variable.

It would help if there was and intermediary parameter, like P10K_CACHE_HOME, that would take its stand in the code, and that would default to XDG_CACHE_HOME. Thank you for your understanding.

**Comment by romkatv** [comment]
Unless you are solving a real problem, I highly recommend doing nothing in this regard. If you really want to change the location of p10k cache files, follow the recipe I've given above.

**Comment by Murazaki** [comment]
This depends clearly on your definition of a real problem. having files being created in the wrong place is clearly a real problem for me.
I'll do it myself then.

**Comment by romkatv** [comment]
By real problem I mean that it affects some kind of workflow. Basically, if you cannot do something that you want to do.

It's your choice of course. The code is open source and you may modify it freely.

**Comment by Murazaki** [comment]
FYI I've been using this update to differentiate P10K_CACHE_HOME from XDG_CACHE_HOME, thus letting me change it without the risk of breaking any complementary scripts to p10k.

Merge updates have been so stable I did not had any conflicts.

https://github.com/romkatv/powerlevel10k/compare/master...Murazaki:powerlevel10k:feature/xdg-cache-subfolder-handling

**Comment by romkatv** [comment]
FWIW, if you use zsh4humans, all cache files, including those from powerlevel10k and gitstatus, are stored under `${XDG_CACHE_HOME:-$HOME/.cache}/zsh4humans`, which is also overridable by setting `Z4H`.
