### ISSUE TITLE
Powerlevel10K prompt me to configure again and again at each terminal launch

### ISSUE THREAD

**Issue by theunclemez** [romkatv/powerlevel10k#240]
Hello !

i've done my configuration of PK10 like i usually do (following the instructions in here) but this time it is prompting me to configure again and again whatever i do it loops !
Attached you will find my zshrc and pk10.zsh in a zipped file so you look if i'm getting things wrong and advice me how to fix that !

Blessings !
[config_files.tar.gz](https://github.com/romkatv/powerlevel10k/files/3665759/config_files.tar.gz)

**Comment by romkatv** [comment]
You have this line in your `~/.zshrc`:

```zsh
alias fixpng="find . -type f -name "*.png" -exec convert {} -strip {} \;"
```

It's broken. You need to either remove it or fix it.

**Comment by theunclemez** [comment]
Thank you so much, it's working now !
Blessings !

**Comment by romkatv** [comment]
👍
