### ISSUE TITLE
Mark Re-positioning

### ISSUE THREAD

**Issue by kedricsty** [romkatv/powerlevel10k#2400]
Hi, this is my first time using powerlevel10k and iterm2. I realised that the mark (blue arrow at left margin) is in the middle of 2 prompts every time I press return key. Also, when I clear to last mark (option+cmd+L), the cursor ends up at the far right margin and the prompt looks cut off. May I know how to fix this issue with the mark? My intention is to make clear to last mark work the same as default mac terminal.

<img width="725" alt="Screenshot 2023-07-31 at 13 17 59" src="https://github.com/romkatv/powerlevel10k/assets/141002208/d9e8b726-4d41-441e-b987-226b60e70385">
<img width="730" alt="Screenshot 2023-07-31 at 13 24 55" src="https://github.com/romkatv/powerlevel10k/assets/141002208/9f249765-6dfc-4b1f-aba8-f88e5904d8f9">
<img width="730" alt="Screenshot 2023-07-31 at 13 25 21" src="https://github.com/romkatv/powerlevel10k/assets/141002208/3670bc49-af50-4eac-a278-2965eb38e6a3">

**Comment by romkatv** [comment]
iTerm2 displays the mark at the start of prompt. You cannot move the mark to the middle of prompt.

Clear to last mark (<kbd>Option+Cmd+L</kbd>) doesn't handle zsh right prompt very gracefully.

Neither of these issues is specific to powerlevel10k. This is just how iTerm2 does it. You can reproduce this without powerlevel10k as follows:

1. Download the iTerm2 shell integration script:
   ```zsh
   curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh
   ```
2. Start zsh without startup files and with the specified left and right prompt:
   ```zsh
   PROMPT=$'\n%~%# ' RPROMPT='%n@%m' zsh -f
   ```
3. Enable iTerm2 shell integration:
   ```zsh
   source ~/.iterm2_shell_integration.zsh
   ```
4. Observe both issues that you've reported above.
