### ISSUE TITLE
Slanted left character is off by one character

### ISSUE THREAD

**Issue by Murazaki** [romkatv/powerlevel10k#2401]
Here it is with different machines running it :

❌ NixOS on WSL through Tabby
❌ Debian ssh through Tabby 
✅ Windows Cygwin through Tabby
❌ NixOS through Gnome Console (Wayland WSLg)

![image](https://github.com/romkatv/powerlevel10k/assets/938538/061cb536-5064-4b72-9336-798e81d2155c)

Font is Fira Code Mono (NF) on most apart from Gnome Console which must be Consolas (didn't change the default from Gnome)
Tried with Droid Mono, Hack Mono, Ubuntu Mono, Roboto Mono. No changes.

**Comment by Murazaki** [comment]
Same issue on Mac
![image](https://github.com/romkatv/powerlevel10k/assets/938538/3b59dd13-a0ca-4c93-a5da-fb43eecaae43)

**Comment by Murazaki** [comment]
Meslo LGS does work better.

The issue seems to be linked with ligatures ? https://github.com/Eugeny/tabby/issues/778

Gonna try switching to hterm, don't know if I can do that on all of them.

**Comment by romkatv** [comment]
Run `p10k configure`. When it asks whether icons fit between the crosses, take a screenshot and think carefully what the correct answer is. Post the screenshot here and specify how you've answered this question in the post before filing the issue.

**Comment by romkatv** [comment]
The icons do not fit between the crosses, so "no" is the correct answer. Basically, the question is asking whether your font is monospace. It's not. Usually non-monospace fonts have wide triangles that are used in the *slanted* prompt. Your font for some reason have them as narrow. I could add yet another question to the wizard to accommodate fonts such as yours but more questions is more work for everyone running the wizard. A better solution is to use the recommended font, or to avoid the slanted style (try *Lean*), or both.

**Comment by Murazaki** [comment]
I see. It's a shame because it ends up making it look clunky, like it doesn't work. Also some icons have the issue and thus can't be used if it's badly parametered.

> Basically, the question is asking whether your font is monospace. It's not. 

Well, the thing is right now it works whether the font is monospaced or not. And The icons are pretty small in monospace, so I might keep it like this (even though they might look better if they were slightly less big).

FiraCode Nerd Font Mono
![image](https://github.com/romkatv/powerlevel10k/assets/938538/5b09009a-76b3-46c0-9f69-0da6972efb70)

FiraCode Nerd Font
![image](https://github.com/romkatv/powerlevel10k/assets/938538/c22f4104-c421-4af3-8182-096daa42417f)

**Comment by romkatv** [comment]
Both of these fonts are suboptimal: one has icons that are way too large (not monospace), the other has icons that are way too small. The recommended font does not have these issues. It's your choice though.

**Comment by Murazaki** [comment]
FiraCode Nerd Font Mono is not monospace ? 😭

Yeah, I don't like the narrow shape of Meslo. Gonna try others. Thanks.

**Comment by romkatv** [comment]
> FiraCode Nerd Font Mono is not monospace ? 😭

Do the icons fit between the crosses?

**Comment by Murazaki** [comment]
> Do the icons fit between the crosses?

That sounds like a bad joke now 😄 they do : 
![image](https://github.com/romkatv/powerlevel10k/assets/938538/331505b5-aea4-4e36-b098-aef88390e344)

**Comment by Murazaki** [comment]
Sorry for the confusion, I realized it too late ! Thanks for the support 😄
