### ISSUE TITLE
vi mode indicator not working with vi cursor style changing

### ISSUE THREAD

**Issue by ShinyZero0** [romkatv/powerlevel10k#2402]
i tried [this code](https://gist.github.com/LukeSmithxyz/e62f26e55ea8b0ed41a65912fbebbe52) 
or [this newer one](https://github.com/LukeSmithxyz/voidrice/blob/master/.config/zsh/.zshrc#L39C6-L39C6) 
to get my cursor change to block
```zsh
bindkey -v
export KEYTIMEOUT=1

# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.
```
and with both cursor is working but prompt vi mode indicator always shows insert mode. Is there any fix or alternative way to make cursor change which plays whell with p10k?

**Comment by romkatv** [comment]
You need to run your code before sourcing powerlevel10k.
