### ISSUE TITLE
Terraform version not showing

### ISSUE THREAD

**Issue by aschleifer** [romkatv/powerlevel10k#2403]
Hi,

I'm on archlinux with powerlevel10k and I use `tfenv` to handle different terraform versions. When I enable `terraform_version` (by adding it to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` I don't see the version in the prompt.

When I run `terraform --version` it correctly shows me the version that tfenv is set to at that moment. The version however is determined by a ` .terraform-version` file in the repository.

Could it be that powerlevel10k is not executing the `terraform --version` command inside the folder but rather in some global scope and thus doesn't see the version file?

**Comment by romkatv** [comment]
Dup of https://github.com/romkatv/powerlevel10k/issues/2049
