### ISSUE TITLE
Change background color of command_execution_time

### ISSUE THREAD

**Issue by aschleifer** [romkatv/powerlevel10k#2404]
Hello,

I'm sorry if I'm just overlooking a configuration option, but I can't seem to figure out how to change the background color of the `command_execution_time` element. 

Currently it always has a red background which feels very alerting, but while I do want to know how long a command took, I don't see this as something that needs to focus my attention always.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/f851f41fc14d5bd66266b4b4af917d50c1c8b7fe/config/p10k-rainbow.zsh#L546-L548

**Comment by romkatv** [comment]
If you haven't yet discovered `p10k configure`, it's a good idea to run this command.

**Comment by aschleifer** [comment]
Never used that command to be honest. I always configured the options myself. e.g. https://gitlab.com/Segaja/dotfiles_base/-/blob/main/base/.config/zsh/.zshrc?ref_type=heads#L101-120

Thanks for the hint. I will play around with it. Do you have a reference what these color codes are?

**Comment by romkatv** [comment]
> Do you have a reference what these color codes are?

See the top of the file I linked.

**Comment by aschleifer** [comment]
Do you think I should change my approach about how to configure p10k? Since my entire zsh configuration is under version control i might give `p10k configure` a go just to see what it can do for me.

**Comment by romkatv** [comment]
You absolutely should.

`p10k configure` generates `~/.p10k.zsh` and adds one line to .zshrc to source it. You can easily remove that line to go back to your config.

**Comment by aschleifer** [comment]
Sorry if this issue escalates a bit, but on the subject of configuration: Is there a way to make `disk`, `ram` and `load` only show if they are above certain threshold? Basically I'm only interested if they peak.

**Comment by romkatv** [comment]
Yes, it is possible to show `disk`, `ram` and `load` only when they are above a certain threshold. For `disk` and `load` you should be able to figure out how to do that by looking at `~/.p10k.zsh`. For `ram` you can do something like this:

```zsh
# Hide ram if it's at least 1GB.
POWERLEVEL9K_RAM_CONTENT_EXPANSION='${P9K_CONTENT:#*G}'
POWERLEVEL9K_RAM_VISUAL_IDENTIFIER_EXPANSION='${${P9K_CONTENT:#*G}:+$P9K_VISUAL_IDENTIFIER}'
```

However, it's very unlikely that you want these prompt segments in the first place. Disk usage, RAM and CPU load aren't properties of the shell but of the machine itself. If you want to see them, it's best to display them outside of the terminal (in the task bar or something similar).

**Comment by aschleifer** [comment]
> However, it's very unlikely that you want these prompt segments in the first place. Disk usage, RAM and CPU load aren't properties of the shell but of the machine itself. If you want to see them, it's best to display them outside of the terminal (in the task bar or something similar).

You are partly right about this and I already removed them from my desktop environment setups. But for my server I want to keep them easily visible, if they are too high. So I will try to incorporate your suggestion on that setup.

**Comment by romkatv** [comment]
If you are connecting to the server via SSH, you could print some diagnostics from `.zlogin`. Just an alternative to doing it via prompt.
