### ISSUE TITLE
Wrong git stats in prompt

### ISSUE THREAD

**Issue by constantin-harabara** [romkatv/powerlevel10k#2406]
I'm not sure if this is `powerlevel's` issue or `oh-my-zsh`. At least I tried `avit` theme and couldn't replicate the issue there. 
After changing the branches, I see some uncommitted changes in the prompt, while my working directory is actually clean.
Here is a picture to demostrate this
<img width="485" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/73463710/d7f6d0fb-3f57-497f-a40f-86ed010fc6a1">

Would love some help

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#incorrect-git-status-in-prompt

**Comment by constantin-harabara** [comment]
Thanks a lot!
