### ISSUE TITLE
Suggestions Not Working On Kali

### ISSUE THREAD

**Issue by Evilcarbon** [romkatv/powerlevel10k#2407]
Hello guys my suggestion is not working. On regular zsh I get autocomplete suggestion but on this I will need to press up direction key also while entering a folder name I usually get a bold text if the folder exist else i get a regular font among other suggestion features.. Is there a way to fix this?

**Comment by romkatv** [comment]
How is this related to powerlevel10k?

**Comment by Evilcarbon** [comment]
It seems you're very stupid. I just told you that the suggestions i use to get while working on my terminal doesn't work anymore after using powerlevel10k while others work. I thought this was a community. It's funny how you closed it. If you don't have something reasonable to talk about then why close the issue?
