### ISSUE TITLE
[Feature] Option to disable the right prompt

### ISSUE THREAD

**Issue by Affan-7** [romkatv/powerlevel10k#2409]
I was using powerlevel10k with terminator. And I  also faced [this resizing bug](https://github.com/romkatv/powerlevel10k/issues/1012).  After wasting a lot of time trying to fix that bug I commented every line of the `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` under the `~/.p10k.zsh` file. This problem may be faced by a lot of people. I know there are some other mitigations to this, but they are difficult to implement and time consuming for someone who doesn't have a lot of knowledge in customizing `ZSH` and dealing with `ZSH` source code.

**My request is can you please add an step to disable the right prompt while running `p10k configure`?**

**It will save a lot of time for sure!**

**Comment by romkatv** [comment]
Workarounds are described in this section: https://github.com/romkatv/powerlevel10k#mitigation

It seems like this is the option you've chosen:

> - Avoid long lines between the start of prompt and cursor.
>   1. Disable ruler with `POWERLEVEL9K_SHOW_RULER=false`.
>   2. Disable prompt connection with `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '`.
>   3. Disable right frame with `POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=''`,
>      `POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=''` and
>      `POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=''`.
>   4. Set `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()`. Right prompt on the last prompt line will cause
>      resizing issues only when the cursor is below it. This isn't very common, so you might want to
>      keep some elements in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` provided that none of them are
>      succeeded by `newline`.

I'm glad you managed to find this.

I won't be adding an option to the configuration wizard for this option. Everyone who realizes what this option means would have little trouble implementing it in their own config. They would also be in a position to decide what to do with the prompt elements that are in right prompt by default, and to decide whether other workarounds are more appropriate.
