### ISSUE TITLE
Disable Backgound for prompt segments?

### ISSUE THREAD

**Issue by Samsu-F** [romkatv/powerlevel10k#2411]
Hello,
so far I have been using a terminal theme that uses the same color values for the default background and for color 0. Therefore, the p10k segments that use color 0 as foreground or background appear to have no color. However, after changing the terminal theme, color 0 is black, so this no longer works. Is there any way to disable the background for prompt segments to make them look like before?

![Screenshot_my_colors_currently](https://github.com/romkatv/powerlevel10k/assets/92742829/8b9ee24c-6102-4cca-8fd7-e81e083a534a)

![Screenshot_my_colors_desired](https://github.com/romkatv/powerlevel10k/assets/92742829/b3c3386b-ebde-4d91-9879-c7364cc00f98)

The first screenshot shows what my right prompt currently looks like and the second one shows what I want it to look like, but with the new theme.

**Comment by romkatv** [comment]
You can set the background to `''` (empty) to make it transparent. You'll also need to hide the leading triangle in the right prompt with this parameter:

```zsh
POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
```

Pro tip: Try *Lean* style.

**Comment by Samsu-F** [comment]
Sorry, I think I didn't explain my problem clearly.
I only want some of the segments (i.e. status ok and background jobs) to have no background, the other segments of the right prompt should stay the same.

I want this
![Screenshot_my_colors_currently_2](https://github.com/romkatv/powerlevel10k/assets/92742829/41246df6-01d2-4ced-84d7-72e8de5e7b0f)

to look like this
![Screenshot_my_colors_desired_2](https://github.com/romkatv/powerlevel10k/assets/92742829/149ba89a-bd14-43b0-bc59-19ca98c3694a)

so unfortunately setting the background to `''` and removing the triangle does not work and lean style is also  not what I want.

**Comment by romkatv** [comment]
You can set the background color individually per segment.

**Comment by Samsu-F** [comment]
I know, but if I set `POWERLEVEL9K_STATUS_OK_BACKGROUND` and `POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND` to `''`, it looks like this:

![Screenshot_empty_colors](https://github.com/romkatv/powerlevel10k/assets/92742829/a7dd4b6a-463f-494f-b33b-e9843205f035)


If I also set `POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL` to `''`, it looks like this:

![Screenshot_empty_first_char](https://github.com/romkatv/powerlevel10k/assets/92742829/a4405465-fbf0-40a8-ad27-b02be0d74e1a)

Both of them do not achieve what I want

**Comment by romkatv** [comment]
I guess there is no way to do this.

**Comment by Samsu-F** [comment]
Too bad :(
P10k strictly uses the ANSI 8-bit color palette and there is no way to use the 24-bit palette, right?

**Comment by romkatv** [comment]
Powerlevel10k does not place any restrictions on the color palette. If your terminal supports 24-bit colors and your zsh is recent enough, you can use 24-bit colors with p10k.

```zsh
POWERLEVEL9K_STATUS_OK_BACKGROUND='#ffffff'
```

**Comment by Samsu-F** [comment]
Thats great, then I can just use the same color as my background. Thank you very much!
