### ISSUE TITLE
rust not respecting rust-toolchain.toml

### ISSUE THREAD

**Issue by steakknife** [romkatv/powerlevel10k#2413]
## Problem

The rust prompt doesn't show the correct version.

![image](https://github.com/romkatv/powerlevel10k/assets/224304/f55df94c-08a9-428c-b6fa-02d78080bcb6)

<details>
<summary>MCE</summary>

```shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y  --no-modify-path
source ~/.cargo/env
rustup toolchain install nightly --profile minimal
cd $(mktemp -d) && cargo init --name deleteme
print '[toolchain]\nchannel = "nightly"' > rust-toolchain.toml
```

</details>

### +Expected vs. -actual

```diff
- Shows the stable version `1.71.1`
+ Shows the nightly version `1.73.0-nightly (a6f8aa5a0 2023-08-11)`
```

## Attempted resolution(s)

- Add `typeset -g POWERLEVEL9K_RUST_VERSION_CONTENT_EXPANSION='${P9K_RUST_VERSION#rustc }` per #418 

## Resolution methodology

Somewhere after ` if (( $+commands[rustup] )); then`, the simplest way to get the current toolchain for a given directory and environment is `rustup show active-toolchain -v | tail -1`. I've verified this command always works with complicated workspace crates. It was unclear to me how to modify `internal/p10k.zsh` so I was unable to cut a PR.

**Comment by romkatv** [comment]
`rustup` has added two things since I implemented `rust_version` segment in p10k:

1. `rust-toolchain` can now be in TOML format. The old format is still supported.
2. If `rust-toolchain` is missing, `rust-toolchain.toml` is used.

Powerlevel10k needs to be modified to support these. Details: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

No ETA.

**Comment by steakknife** [comment]
Good luck with that because I am moving onto an alternative that is more
maintainable than this fragile mess.

**Comment by desbma** [comment]
I am having a similar issue:
```
➜ rustc -V
rustc 1.72.0 (5680fa18f 2023-08-23)
➜ rustup show
Default host: x86_64-unknown-linux-gnu
...

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
beta-x86_64-unknown-linux-gnu
nightly-2022-11-01-x86_64-unknown-linux-gnu
nightly-2022-11-02-x86_64-unknown-linux-gnu
nightly-2022-11-27-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.47.0-x86_64-unknown-linux-gnu
1.61.0-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

x86_64-apple-darwin
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.72.0 (5680fa18f 2023-08-23)
```

Yet the prompt shows `1.74.0-nightly`.

**Comment by romkatv** [comment]
This is fixed. Sorry that it took so long.

@steakknife If you don't mind my asking, which alternative have you moved to?
