### ISSUE TITLE
Need help to create the theme with prompt gap 

### ISSUE THREAD

**Issue by ciscohack** [romkatv/powerlevel10k#2414]
Hello Roman,

Can you please help me to achieve the theme output as below screenshot?

<img width="910" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/c4796486-9fae-4de9-b5f6-2ad3adc28265">
and 

<img width="756" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/a07e0733-f598-4206-9009-e3e5b30d0677">

I tried my hand with the rainbow theme style but failed to achieve my prompt looks very weird if try to change some Unicode characters... I know your powerlevel10k has a lot of flexibility to achieve any style we want but I am not able to do it.... please guide me through

My current prompt look like this

<img width="1998" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/105dc479-110c-4849-b07f-f469dd53a188">

**Comment by romkatv** [comment]
Powerlevel10k does not have an option for this.

**Comment by ciscohack** [comment]
@romkatv Thanks Roman for your response. Sad that our powerlevel10k doesn't have this option I thought it doesn't have any limitations and I thought I am not able to do it as I don't know how to do. 

I am sure you would have some answer to my problem even though it has limitation... will you add this option support in future releases and any trick to create the problem i have mentioned above.

**Comment by romkatv** [comment]
I might add an option for this in the future but I cannot promise it.

As for a workaround, consider using a different prompt style. If you value functionality over hype, try Lean style.

**Comment by ciscohack** [comment]
> I might add an option for this in the future but I cannot promise it.
> 
> As for a workaround, consider using a different prompt style. If you value functionality over hype, try Lean style.

Thank you so much ... I will wait then don't want functionality compromised but I like prompt customisation to change feel and being bored to see the same prompt all time ....thanks once again

**Comment by rwmitchell** [comment]
@ciscohack I am curious, how was your desired prompt generated?

**Comment by ciscohack** [comment]
> @ciscohack I am curious, how was your desired prompt generated?

With powerlevel10k configure... Wait for Roman to make it happen some day

**Comment by romkatv** [comment]
You can enable gaps in Classic style fairly easily.

1. Run `p10k configure` and select *Classic* style.
2. Open `~/.p10k.zsh` and changes the values of two parameters:
   ```zsh
   typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0B0%S\uE0B0%s'
   typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0B2%s\uE0B2'
   ```

Here `238` is the value of `POWERLEVEL9K_BACKGROUND`. It may be different in your config, in which case you'll need to replace `238` above with your actual `POWERLEVEL9K_BACKGROUND`. You can search for it in `~/.p10k.zsh` or simply run `typeset -p POWERLEVEL9K_BACKGROUND`.

That was for "angled" connections between prompt segments. You can also try round:

```zsh
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0B4%S\uE0B4%s'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0B6%s\uE0B6'
```

Or slanted:

```zsh
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0BC%S\uE0BC%s'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0BA%s\uE0BA'
```

**Comment by ciscohack** [comment]
> You can enable gaps in Classic style fairly easily.
> 
> 1. Run `p10k configure` and select _Classic_ style.
> 2. Open `~/.p10k.zsh` and changes the values of two parameters:
>    ```shell
>    typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0B0%S\uE0B0%s'
>    typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0B2%s\uE0B2'
>    ```
> 
> Here `238` is the value of `POWERLEVEL9K_BACKGROUND`. It may be different in your config, in which case you'll need to replace `238` above with your actual `POWERLEVEL9K_BACKGROUND`. You can search for it in `~/.p10k.zsh` or simply run `typeset -p POWERLEVEL9K_BACKGROUND`.
> 
> That was for "angled" connections between prompt segments. You can also try round:
> 
> ```shell
> typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0B4%S\uE0B4%s'
> typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0B6%s\uE0B6'
> ```
> 
> Or slanted:
> 
> ```shell
> typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0BC%S\uE0BC%s'
> typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0BA%s\uE0BA'
> ```

Thanks, Roman, this genius never disappoints.. thanks for taking the time and giving me an alternate. I  will use this but looking forward to native support in future for other styles like a rainbow and other. Thanks once again and please keep the request in your todo list.  I just noticed their is one more ticket for a similar request. So I am hopeful if you get time you will add this request as native support

**Comment by romkatv** [comment]
I don't understand what you are asking. Can you make it grammatical, or rephrase?

**Comment by ciscohack** [comment]
> I don't understand what you are asking. Can you make the question grammatical, or rephrase?

Sorry for my bad English. couldn't explain my ask. I was asking if is it possible to hide the status_ok prompt arrow icon and only show ticks for status_ok

<img width="479" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/5078e47a-4a82-4347-9f5b-82f2276a4f76">

**Comment by romkatv** [comment]
If you want to remove the background from `status`, try this:

```zsh
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0B4%S\uE0B4%s'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0B6%s\uE0B6'
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='%k%238F\uE0B6'
typeset -g POWERLEVEL9K_STATUS_BACKGROUND=
```

Pro tip: use a two-line prompt with `prompt_char` in it (the green `❯` on the left hand side in the wizard). This will remove the need for `status` in most cases. Enable transient prompt to mitigate the main disadvantage of a two-line prompt.

P.S.

Your font is missing an icon for whatever it is that shows "72%" on your screenshot.

**Comment by ciscohack** [comment]
> If you want to remove the background from `status`, try this:
> 
> ```shell
> typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k%238F\uE0B4%S\uE0B4%s'
> typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k%238F%S\uE0B6%s\uE0B6'
> typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='%k%238F\uE0B6'
> typeset -g POWERLEVEL9K_STATUS_BACKGROUND=
> ```
> 
> Pro tip: use a two-line prompt with `prompt_char` in it (the green `❯` on the left hand side in the wizard). This will remove the need for `status` in most cases. Enable transient prompt to mitigate the main disadvantage of a two-line prompt.
> 
> P.S.
> 
> Your font is missing an icon for whatever it is that shows "72%" on your screenshot.

You are amazing, my friend Roman. Thank you so much for your assistance. I'm currently using a monospace font, but it appears to be missing some unicode characters. Although you recommended the menslo font, I've chosen not to use it for personal taste as I don't like it due to some reason.

In the future, I kindly request that you add the prompt gap feature to other theme styles. This will help me achieve a better-looking prompt. Currently, the rainbow feature is not working, so I'm using the classic style. Although it's a bit dull, I'm managing with your customization suggestions. Thank you once again for your help.

**Comment by ciscohack** [comment]
@romkatv  I have just tested Meslo NF font latest one you rebuilt that also not showing the battery icon in the classic theme 

Tried other nerd fonts but classic style not showing the battery icon

<img width="185" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/3f515b86-0f92-47cc-9e54-5e589d0afa51">

**Comment by romkatv** [comment]
It's not Meslo LGS NF on your screenshot.

**Comment by ciscohack** [comment]
No i have tested meslo NF.. Ok wait I send you meslo NF screenshot

**Comment by ciscohack** [comment]
@romkatv here is the screenshot with Meslo NF

<img width="182" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/6f888d49-a7fa-4474-b869-ff314a25352b">

**Comment by romkatv** [comment]
Try this:

1. Update powerlevel10k to the latest version.
2. Make sure the terminal is using the latest version of Meslo LGS NF for all glyphs (both ASCII and non-ASCII).
3. Run `p10k configure` and generate a new configuration file.
4. Uncomment `battery` in `~/.p10k.zsh`.
5. Restart zsh with `exec zsh`.

If this does not help, double-check everything and especially (2).

**Comment by ciscohack** [comment]
@romkatv I have recently installed your shell along with powerlevel10k. So I am using an updated one only. I am using kitty terminal but the only difference is I ran p10k configure command yesterday with monospace nerd font. 

I will test again as you have mentioned and let you know

this is my kitty config font setting 

<img width="420" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/b40cb153-4b9e-4ee9-80b7-6a58e65df3bf">

**Comment by romkatv** [comment]
You need to use only MesloLGS NF. Don't use any other fonts.

In case it's not clear: the issue is on your side.

**Comment by ciscohack** [comment]
<img width="185" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/5e2fa5c1-be3d-4b5a-9b06-7d6922f4e4b2">

new config with Meslo NF font

**Comment by ciscohack** [comment]
@romkatv  Thanks! you are correct. It seems kitty terminal issue. working fine in iterm2

**Comment by romkatv** [comment]
It may also be a configuration issue, hence my stressing that you need to double check (or even triple check) how the terminal is configured.

**Comment by ciscohack** [comment]
@romkatv Yes you are 100% correct.. it is a Config mistake from my side and after debug I able to identified the root cause.. In kitty terminal there is symbol setting and I put it nerd symbol font Config there that's doesn't have some unicode character due to this it was misbehaving... I have removed the configuration and everything started working as expected...


Now will wait when this Gap style will be available for rainbow style to use colored theme with gap as you suggested.. Rest all issue now fixed... Thanks a lot for your help my friend.

**Comment by romkatv** [comment]
> Now will wait when this Gap style will be available for rainbow style to use colored theme with gap as you suggested.

Please don't take my earlier comment as a promise to actually implement this feature.

**Comment by ciscohack** [comment]
> promise

Ok.. Anyway I am hoping for postive only... Whenever i reached to you for help.. I never went away empty hand. So optimistic it will coming and i don't things its something very tough for your.. But let see

**Comment by ciscohack** [comment]
@romkatv Hi Roman, How are you? just checking if the requested prompt gap feature is coming for rainbow themes in the near future.. please consider the request not urgent but it definitely to have it in future

**Comment by romkatv** [comment]
I don't have any specific plans related to this feature. I hope I never made you believe otherwise.

**Comment by ciscohack** [comment]
> I don't have any specific plans related to this feature. I hope I never made you believe otherwise.

okay, my friend understood thanks. Sorry, thought we would get this feature in our power but seems we are not. Anyway thank you so much
