### ISSUE TITLE
There will be a line break error when using Git-Bash in the terminal of Intellij IDEA

### ISSUE THREAD

**Issue by FoundAdd** [romkatv/powerlevel10k#2418]
I use Git-Bash in the terminal of Intellij IDEA. After installing zsh today, I changed the theme to powerlevel10k. When I completed the configuration according to the prompts, I found that p10k will have a newline error at the end of each line, and this problem is in git -bash window does not appear.

#### This is an abnormal image in the terminal of IDEA
![image](https://github.com/romkatv/powerlevel10k/assets/58539321/d15063fd-d2e2-4e87-8770-91e1c236ee83)

#### This is a normal image in Git-Bash
![image](https://github.com/romkatv/powerlevel10k/assets/58539321/c474d294-33d6-45d2-820b-9b688a9f1b3c)

**Comment by romkatv** [comment]
It's a bug in your terminal. As a workaround you can try running `p10k configure` and choosing ASCII instead of Unicode when asked about the charset.

**Comment by FoundAdd** [comment]
> It's a bug in your terminal. As a workaround you can try running `p10k configure` and choosing ASCII instead of Unicode when asked about the charset.

Thanks, it's useful.Now it works fine.
