### ISSUE TITLE
Complete wrong colors picking pure theme

### ISSUE THREAD

**Issue by ivanafanasyeu** [romkatv/powerlevel10k#2419]
Expecrations, have colors like on the screenshot here:
https://github.com/sindresorhus/pure

reality: ![Screenshot 2023-08-29 at 16 54 03](https://github.com/romkatv/powerlevel10k/assets/25664253/3cab2860-0bc6-4cef-b2c8-86275c35971e)

**Comment by romkatv** [comment]
These are exactly the same colors as you would get with https://github.com/sindresorhus/pure. Try it.

If you want the same colors as on the screenshot, make sure your terminal supports 24-bit colors. Then run `p10k configure` and select Pure style with Snazzy colors.

Pro tip: use Lean style. It's better.
