### ISSUE TITLE
Prompt segments/powerline glyphs not displaying in anything other than ~

### ISSUE THREAD

**Issue by ronasimi** [romkatv/powerlevel10k#242]
no longer able to see powerline glyphs/git status icons since update today (October 2 2019). 
![screenshot-20191002-13:22:25](https://user-images.githubusercontent.com/3991859/66066562-c4c89900-e517-11e9-9a4a-ef5ce001eebf.png)

**Comment by romkatv** [comment]
Thanks for the report.

Can you tell me anything else? What's your config?

On the screenshot I can see that while in home directory there are powerline symbol but after `cd` there are none. Is it always like that? If you `cd` back home, do powerline symbols reappear? What if you type `zsh` while in home directory? What if you type `zsh` while *not* in home directory?

Any information would be helpful.

**Comment by ronasimi** [comment]
It looks like it's not loading most of the powerlevel10k segment icons.  If I cd back to ~ the powerline glyphs are OK.  If I reload zsh from any other directory, the glyphs are still missing.
The relevant section from my .zshrc is:

`# POWERLEVEL10K OPTIONS
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_IGNORE_TERM_COLORS=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir_writable context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs vcs)
DEFAULT_USER="ron"
POWERLEVEL9K_CONTEXT_TEMPLATE="%n@`hostname -f`"
POWERLEVEL9K_ALWAYS_SHOW_USER=true
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="white"
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND="black"
POWERLEVEL9K_CONTEXT_SUDO_BACKROUND="orange"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="white"
POWERLEVEL9K_CONTEXT_ROOT_BACKROUND="red"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="white"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="white"`

which worked OK until the latest update.

**Comment by romkatv** [comment]
Thanks for the extra info. I've reverted the latest change for now. Will debug and roll forward later.

**Comment by ronasimi** [comment]
Reverting that definitely fixed the issue.  Thanks for the speedy response, as usual.

**Comment by romkatv** [comment]
FYI: I've rolled the commit forward after fixing some bugs and improving performance. It's an ambitious change, so please be on lookout for potential breakages.
