### ISSUE TITLE
My icons aren't showing up correctly. I have the MesloLGS NF fonts installed and my terminal is using that, but whenever I initialize a Git repo, the icon next to the master branch looks weird

### ISSUE THREAD

**Issue by VishwaV10** [romkatv/powerlevel10k#2420]
<img width="316" alt="Screenshot 2023-08-31 at 9 16 54 AM" src="https://github.com/romkatv/powerlevel10k/assets/90657995/c66d2283-c93c-42b8-a6f6-ebd796241ae8">

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean
