### ISSUE TITLE
Support for drawing the gap-line on the actual input line 'post prompt'/accept?

### ISSUE THREAD

**Issue by joerohde** [romkatv/powerlevel10k#2421]
Using the `on-pre` and `on-post` I can do pretty much anything.

Except... When I collapse my prompt down to 1 line retaining the important 'historic' information...  I really really wish I could retain the gap line I had in the (now hidden) first line.

On a whim I tried: `p10k display '2/gap'=show` in the `on-post` with the first line hidden.  Didn't expect it to work, and it didn't.

And given the nature of when the gap has to be computed I don't see a way to do it with a custom `prompt_` function, or in the pre/post callbacks.

I'm not suggesting that `p10k display 'N/gap'=show` in a 'post prompt context' is the right way to go, it's just the simplest usage model that came to mind (and it would silently bail like it does now in any still interactive setting).

Hope I didn't miss something while I was digging around.  Well... Kind of hope I did actually. :)

I'm getting by with a similarly styled RULER for now, though it defeats the purpose of collapsing to 1 line.

**Comment by romkatv** [comment]
What are you trying to achieve? Perchance showing and hiding the *ruler* will help?

**Comment by joerohde** [comment]
The ruler is the work around I'm using.  What I'm after is ruler-like behavior without taking up the extra line.

What I have now:
![image](https://github.com/romkatv/powerlevel10k/assets/25186855/7ec6eb95-1f64-4d42-aedb-9ab31968db27)

What I'm going for:
![image](https://github.com/romkatv/powerlevel10k/assets/25186855/ca915b90-3ac3-46f5-a636-b9bf8c565b93)

Looks a little crowded with commands that only have 1 line of output.  But basically, I'm just going for a prompt where the transient bit 'left behind' is only 1 line of info, still containing a nice divider.

**Comment by romkatv** [comment]
This is technically possible but currently not supported by powerlevel10k.

**Comment by joerohde** [comment]
Even the smallest of suggestions would be great if you have an idea?  Seems like it would need to be somewhere after all sizes have been computed.  Basically, where the 'gap' loop render is now.   But with my quick look, I didn't see anything to hook/set without having to change the main script.

**Comment by rwmitchell** [comment]
If you're looking for a divider, my config separates output with a green/red lines:

![image](https://github.com/romkatv/powerlevel10k/assets/15944841/c489e6a8-903b-4a46-a25d-68c00a01b9e6)

I can  share, if interested.
