### ISSUE TITLE
make prompt below input line

### ISSUE THREAD

**Issue by xitsu521674** [romkatv/powerlevel10k#2422]
Is it possible to set multiline prompt with prompt below the input line? Thx.

**Comment by romkatv** [comment]
No.

**Comment by romkatv** [comment]
To clarify, this is impossible in zsh (and not just in powerlevel10k). I'm not aware of any shell that supports prompt below the input line.

**Comment by xitsu521674** [comment]
> To clarify, this is impossible in zsh (and not just in powerlevel10k). I'm not aware of any shell that supports prompt below the input line.

Great appreciation for the clarifying. It seems I have some misunderstanding about what a shell can do.

**Comment by rwmitchell** [comment]
Can you provide a screenshot of the goal, on the off-chance this is just a misunderstanding?

**Comment by xitsu521674** [comment]
> Can you provide a screenshot of the goal, on the off-chance this is just a misunderstanding?

![image](https://github.com/romkatv/powerlevel10k/assets/80415369/da3a91ad-7c77-4660-8bed-f5fc341d2cb7)

**Comment by rwmitchell** [comment]
Is that a mockup or does that work somewhere?  What happens when the command entered exceeds the line length?  Does the second line just disappear?

**Comment by romkatv** [comment]
It's a mockup. It doesn't work anywhere.
