### ISSUE TITLE
[ERROR]: gitstatus failed to initialize.

### ISSUE THREAD

**Issue by capnahab** [romkatv/powerlevel10k#2423]
Last login: Thu Sep  7 06:16:32 on ttys000
/etc/zshrc:7: command not found: locale

[ERROR]: gitstatus failed to initialize.

  Zsh log (/private/var/folders/3t/m3cn50hx38l29x6_mv9t0sdw0000gn/T/gitstatus.POWERLEVEL9K.501.42454.1694063792.1.xtrace.log):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/3t/m3cn50hx38l29x6_mv9t0sdw0000gn/T/gitstatus.POWERLEVEL9K.501.42454.1694063792.1.lock
    +(anon):15> [[ 17 == <1-> ]]
    +(anon):18> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> [[ darwin22.0 == cygwin* ]]
    +(anon):41> sysopen -r -o cloexec -u resp_fd /dev/fd/16
    +(anon):44> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=42480'
    +(anon):46> [[ 19 == <1-> ]]
    +(anon):47> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):48> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):51> ((  ! async  ))
    +(anon):41> _gitstatus_daemon_p9k_
    +_gitstatus_daemon_p9k_:1> local -i pipe_fd
    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):51> ((  ! async  ))
    +(anon):52> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):54> local pgid
    +(anon):55> ((  0 < 20  ))
    +(anon):56> [[ -t 19 ]]
    +(anon):57> sysread -s 20 -t 10.0000000000 -i 19 'pgid[$#pgid+1]'
    +(anon):57> return

  Daemon log (/private/var/folders/3t/m3cn50hx38l29x6_mv9t0sdw0000gn/T/gitstatus.POWERLEVEL9K.501.42454.1694063792.1.daemon.log):

    +_gitstatus_daemon_p9k_:3> local pgid=42480
    +_gitstatus_daemon_p9k_:4> [[ 42480 == <1-> ]]
    +_gitstatus_daemon_p9k_:5> cd -q /
    +_gitstatus_daemon_p9k_:9> trap '' PIPE
    +_gitstatus_daemon_p9k_:11> local uname_sm
    +_gitstatus_daemon_p9k_:90> ((  lock_fd == -1  ))
    +_gitstatus_daemon_p9k_:12> uname_sm=+_gitstatus_daemon_p9k_:12> uname -sm
    +_gitstatus_daemon_p9k_:93> zsystem flock -- /private/var/folders/3t/m3cn50hx38l29x6_mv9t0sdw0000gn/T/gitstatus.POWERLEVEL9K.501.42454.1694063792.1.lock
    _gitstatus_daemon_p9k_:12: command not found: uname
    +_gitstatus_daemon_p9k_:12> uname_sm=''
    +_gitstatus_daemon_p9k_:12> return
    +_gitstatus_daemon_p9k_:84> local -i ret=127
    +_gitstatus_daemon_p9k_:85> zf_rm -f -- /private/var/folders/3t/m3cn50hx38l29x6_mv9t0sdw0000gn/T/gitstatus.POWERLEVEL9K.501.42454.1694063792.1.lock /private/var/folders/3t/m3cn50hx38l29x6_mv9t0sdw0000gn/T/gitstatus.POWERLEVEL9K.501.42454.1694063792.1.fifo
    +_gitstatus_daemon_p9k_:86> kill -- -42480

  System information:

    zsh:      5.9
    uname -a: Darwin M.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64

  If you need help, open an issue and attach this whole error message to it:

Mac Ventura, M1 Macbook Pro

**Comment by romkatv** [comment]
Your `PATH` is broken, likely by something in your `~/.zshrc`, `~/.zshenv` or similar.

**Comment by capnahab** [comment]
You are right, many thanks
