### ISSUE TITLE
Instant prompt slow down after long time no action

### ISSUE THREAD

**Issue by gary-ruizhang** [romkatv/powerlevel10k#2427]
I have a tmux session which include several windows. If I switch to a window not used for a long time and then split a new pane on it. Instant prompt would not work at the first time in this case. After that everything will be fine.

**Comment by romkatv** [comment]
What do you mean by "Instant prompt would not work" or "Instant prompt slow down"?

**Comment by gary-ruizhang** [comment]
> What do you mean by "Instant prompt would not work" or "Instant prompt slow down"?

Split a pane in tmux will create a new shell session. Here I split a pane below and the instant prompt not work. 
![CleanShot 2023-09-09 at 16 54 13@2x](https://github.com/romkatv/powerlevel10k/assets/32344731/a751884e-5450-4b9e-a1af-d819d687e810)
If I close this pane and then split again, It will be fine.
![CleanShot 2023-09-09 at 16 56 16@2x](https://github.com/romkatv/powerlevel10k/assets/32344731/6b9d92ed-7dd0-455a-97b0-a01e6b9e99f5)

**Comment by romkatv** [comment]
What do you need to do for that the split pane to result in no instant prompt?

**Comment by gary-ruizhang** [comment]
> What do you need to do for that the split pane to result in no instant prompt?

This sometimes happen when I am inactive for a long time.

**Comment by romkatv** [comment]
This is very unlikely. There are no timeouts in powerlevel10k that could do this. There must be some *action* you take that causes this. Perhaps you open a terminal with a different `TERM` value?

**Comment by gary-ruizhang** [comment]
> This is very unlikely. There are no timeouts in powerlevel10k that could do this. There must be some _action_ you take that causes this. Perhaps you open a terminal with a different `TERM` value?
Looks like the cache file is deleted after a while. Will p10k delete these files after reach a limit? 
<img width="1791" alt="CleanShot 2023-09-09 at 17 35 16@2x" src="https://github.com/romkatv/powerlevel10k/assets/32344731/d5c8498a-326c-4a51-8b63-0205356ef951">

**Comment by romkatv** [comment]
No, the cache is not deleted after a while. It can be deleted when you *do* something. Try to figure out what that is. One example is that you open a terminal with a different `TERM` value.

**Comment by gary-ruizhang** [comment]
> No, the cache is not deleted after a while. It can be deleted when you _do_ something. Try to figure out what that is. One example is that you open a terminal with a different `TERM` value.

It's the issue of `TERM` env, if I open a different terminal emulator, these cache files also been deleted. Looks like it's the issue of tmux config `terminal-overrides` and `default-terminal`
