### ISSUE TITLE
Possible ambiguity in the README regarding how to update Powerlevel10k

### ISSUE THREAD

**Issue by vicaba** [romkatv/powerlevel10k#2428]
Hello,
I was looking for a way to update Powerlevel10k. I have seen that there are two sections talking about update.
* The first one is [How do I update Powerlevel10k?](https://github.com/romkatv/powerlevel10k#how-do-i-update-powerlevel10k), that list several ways to update it using package managers.
* The second one is [How to package Powerlevel10k for distribution?](https://github.com/romkatv/powerlevel10k#how-do-i-update-powerlevel10k), that says that it can't be packaged and seems to imply that it has to be done manually.

Isn't the first one invalidating the second?

**Comment by romkatv** [comment]
If you want to update powerlevel10k on your machine, follow the update instructions. If you want to package powerlevel10k for a Linux/BSD distribution, follow the packaging instructions.

**Comment by vicaba** [comment]
Ok!
