### ISSUE TITLE
Wrong installation instructions for homebrew

### ISSUE THREAD

**Issue by mstipic** [romkatv/powerlevel10k#2429]
The path of zsh-theme changed, please fix command line in readme on homebrew installation guide:
```
from
echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc
to
echo "source $HOMEBREW_PREFIX/share/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc
```

more info:
https://formulae.brew.sh/formula/powerlevel10k

**Comment by romkatv** [comment]
Thanks for the report. Fixed.

**Comment by kaushikgopal** [comment]
fyi, i think the installation path is incorrect "after" above fix. From what i'm observing via a Homebrew install:

## M1 machines:
```
source "/opt/homebrew/opt/powerlevel10k/powerlevel10k.zsh-theme"
```

Yes, it does seem like the zsh-them gets installed in /opt/homebrew/opt directory 🤔 

## Intel machines:

```
source "/usr/local/share/powerlevel10k/powerlevel10k.zsh-theme"
```

# Environment details

```
#> brew --version
Homebrew 4.1.12
```

powerlevel10k version is v1.19.0

I believe a comprehensive installation script is the following:

```
# Check if the brew prefix is `/opt/homebrew/opt`
if [[ "${brew_prefix}" == "/opt/homebrew" ]]; then
  source "${brew_prefix}/opt/powerlevel10k/powerlevel10k.zsh-theme"
else
  source "${brew_prefix}/powerlevel10k/powerlevel10k.zsh-theme"
fi
```

**Comment by romkatv** [comment]
> Yes, it does seem like the zsh-them gets installed in /opt/homebrew/opt directory 🤔

You must still be using the old powerlevel10k package.

**Comment by kaushikgopal** [comment]
> > Yes, it does seem like the zsh-them gets installed in /opt/homebrew/opt directory 🤔
> 
> You must still be using the old powerlevel10k package.

is 1.19.0 the right package version?  (or am i referencing something different here)

<img width="660" alt="screenshot-20230927-001253" src="https://github.com/romkatv/powerlevel10k/assets/1042037/e0e64238-2a57-4160-9f87-8d12daa9ec2f">

**Comment by romkatv** [comment]
This is the right package. Is the caveat message lying about the location of the installed files?

**Comment by kaushikgopal** [comment]
> This is the right package. Is the caveat message lying about the location of the installed files?

indeed. caveat messsage `/opt/homewbrew/share/` does *not* have the powerlevel10k message (on my M1). it's lying about location. whereas running the same on the intel machine reports the correct path.


![screenshot-20230928-001273](https://github.com/romkatv/powerlevel10k/assets/1042037/5d734991-96f3-4340-bab4-5001ed9157ab)

**Comment by romkatv** [comment]
> indeed. caveat message reports the directory `/opt/homewbrew/share/` - but that folder does _not_ have the powerlevel10k package (on my M1). it's lying about location.

If this is so, it's an issue with the package. I don't own the package.

**Comment by qianbinbin** [comment]
On my Intel mac, I'd used `source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme` in ~/.zshrc and it worked fine, but recently after upgrading to 1.20.0, brew reports `source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme`.

```sh
 ~  ll /usr/local/opt/powerlevel10k
... /usr/local/opt/powerlevel10k@ -> ../Cellar/powerlevel10k/1.20.0
 ~  ll /usr/local/share/powerlevel10k
... /usr/local/share/powerlevel10k@ -> ../Cellar/powerlevel10k/1.20.0/share/powerlevel10k
```

The `opt` path still exists but seems wrong (missing the `/share/powerlevel10k` part).

**Comment by romkatv** [comment]
Could you clarify? Do the [homebrew installation instructions](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#homebrew) work for you? If they do, what is the problem? If they do not, please post the output of the following command:

```zsh
() {
  emulate -L zsh -o xtrace
  brew ls --formula powerlevel10k
  brew info powerlevel10k
  brew --prefix
  typeset -p HOMEBREW_PREFIX
  ls -ld -- "$(brew --prefix)"
  ls -ld -- "$(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme"
  ls -ld -- /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
}
```

**Comment by qianbinbin** [comment]
> Could you clarify? Do the [homebrew installation instructions](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#homebrew) work for you?

Yes, sorry to bother you. I'm just curious why the old `opt` path worked before but now doesn't.

The output is:

```
+(anon):2> brew ls --formula powerlevel10k
/usr/local/Cellar/powerlevel10k/1.20.0/share/powerlevel10k/ (96 files)
+(anon):3> brew info powerlevel10k
==> powerlevel10k: stable 1.20.0, HEAD
Theme for zsh
https://github.com/romkatv/powerlevel10k
/usr/local/Cellar/powerlevel10k/1.20.0 (98 files, 4.6MB) *
  Built from source on 2024-01-27 at 23:50:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/powerlevel10k.rb
License: MIT
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate this theme, add the following at the end of your .zshrc:

  source /usr/local/share/powerlevel10k/powerlevel10k.zsh-theme

You will also need to restart your terminal for this change to take effect.
==> Analytics
install: 3,423 (30 days), 8,448 (90 days), 13,068 (365 days)
install-on-request: 3,418 (30 days), 8,431 (90 days), 13,037 (365 days)
build-error: 0 (30 days)
+(anon):4> brew --prefix
/usr/local
+(anon):5> typeset -p HOMEBREW_PREFIX
(anon):typeset:5: no such variable: HOMEBREW_PREFIX
+(anon):6> brew --prefix
+(anon):6> ls -G -ld -- /usr/local
drwxr-xr-x  16 root  wheel  512  7 26  2023 /usr/local
+(anon):7> brew --prefix
+(anon):7> ls -G -ld -- /usr/local/share/powerlevel10k/powerlevel10k.zsh-theme
-rw-r--r--  1 qianbinbin  admin  3913  1 26 14:58 /usr/local/share/powerlevel10k/powerlevel10k.zsh-theme
+(anon):8> ls -G -ld -- /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
ls: /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme: No such file or directory
```

**Comment by romkatv** [comment]
> Do the [homebrew installation instructions](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#homebrew) work for you?

If I understand correctly, the answer is *Yes*.

> I'm just curious why the old `opt` path worked before but now doesn't.

I don't know. I don't own Homebrew or the powerlevel10k package for Homebrew.

**Comment by RodneyBollinger** [comment]
Since this is still happening. I do have a workaround for anyone reaching this page looking for answers. It looks like the package (1.20.0) has move the location of the file.

On M1 Macs, in your ~.zshrc file please change your source statement to:
source /opt/homebrew/opt/powerlevel10k/share/powerlevel10k/powerlevel10k.zsh-theme

This worked perfectly on my M1 MBP. Your mileage may vary. Good luck!

**Comment by romkatv** [comment]
@RodneyBollinger Do the [homebrew installation instructions](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#homebrew) work for you?

**Comment by RodneyBollinger** [comment]
I didn’t want to uninstall and re-install. It just stopped working when I
updated to 1.20 via homebrew, so I went and tracked down where the file now
lives and changed my sourcing accordingly.

I will have to try the uninstall/reinstall on my other machine at some
point. I’ve actually been using Warp in that one and the p10k theme didn’t
break there. I know, odd, right?

- Rodney

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
echo "source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme"
```

**Comment by RodneyBollinger** [comment]
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

- Rodney

**Comment by romkatv** [comment]
> source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

What happens if you execute *that*?

**Comment by RodneyBollinger** [comment]
That appears to work as well.

- Rodney

**Comment by romkatv** [comment]
Great. Then I conclude that the installation instructions are correct. Thank you for confirming it.

**Comment by RodneyBollinger** [comment]
Yes, great! What I see is the first powerlevel10k in /opt/homebrew/opt is a
symbolic and so is the first one in /opt/homebrew/share. Both symbolically
point to different ways to get to the same file. That’s why they both
worked.

Glad I could help!

- Rodney

**Comment by romkatv** [comment]
While they both work, the official instructions have the advantage of being official, so they are more likely to keep working. I would recommend anyone stumbling on your comment in this issue to follow the official instructions instead of the advice given in the comment.

**Comment by RodneyBollinger** [comment]
Comment removed
