### ISSUE TITLE
Regular Expression problemas

### ISSUE THREAD

**Issue by santenana** [romkatv/powerlevel10k#2431]
Hi I download recently powerlevel10K to personalize mu bash, but when I try to use regular expressison in a VIM document the regular expression cannto be readed or at leas I think so, because when I execute the VIM show a message ./my_vim.sh: 24: [[ : Permission denied, the error is in line 24, PD: I give all kind of permissions to the .sh docuement and the error contiue and I think is a problem of the 10K because in a regular bash of linux there is no issue with the regular expressions.

best regards :3

**Comment by romkatv** [comment]
This problem is unrelated to powerlevel10k. You'll get the same error without powerlevel10k.

**Comment by santenana** [comment]
I don't think so, as I told. I try in another linux shell and works normally the same code, anyway I forgot to mencion but I use zsh with Powerlvl10k, and if the powerlevel10k is not releated with the error, Is zsh's fautl?

**Comment by romkatv** [comment]
What happens if you uninstall powerlevel10k but leave everything else unchanged?
