### ISSUE TITLE
No colors in the rainbow mod

### ISSUE THREAD

**Issue by hungngodev** [romkatv/powerlevel10k#2433]
<img width="648" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/0982313e-fc89-4fac-aa93-c1000f463cf1">
There is no color, or any icons appear in the PATH. I have chosen the rainbow mode multiple times in the p10k configure. 
I can provide any further files if that helps

**Comment by romkatv** [comment]
What do you mean by "no colors" or "any icons appear in the PATH"?

The screenshot is what you actually get, right? How is it different from what you expect?

**Comment by hungngodev** [comment]
<img width="350" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/74891cec-59d5-4c92-8aa2-f6355382b633">
****
Thanks for the reply
The online article about powerlevel10k is like this? Is there a way to configure it like that? How do you get the icons and the color changes for each directory ( unlike mine, which is one color for the whole path)?

**Comment by rwmitchell** [comment]
Those color changes are not occurring at the sub-directory level.

The first color is the OS icon.  The second color is the current full/partial path.  The third color is git information.

**Comment by hungngodev** [comment]
Do you know how to configure those icons?

**Comment by romkatv** [comment]
In order to get these icons you need to choose in the configuration wizard UNICODE (instead of ASCII) and then "Many Icons" instead of "Few Icons". If you don't see these options when running the wizard, see https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by hungngodev** [comment]
Oh, thank you so much. Is there any way I could change the color of the icon and the box that wraps the path?

**Comment by romkatv** [comment]
1. Open `~/.p10k.zsh`.
2. Search for `POWERLEVEL9K_DIR_BACKGROUND` and change its value to whatever you like.
3. Add `typeset -g POWERLEVEL9K_DIR_VISUAL_IDENTIFIER_COLOR=1` next to it (the value is up to you).
4. Restart zsh with `exec zsh`.

**Comment by hungngodev** [comment]
Hi, it works. Thank you so much. Do you know how to change the color of bolded directory. I have changed this line
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=042
  # Default current directory foreground color.
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=000
However it only changes the color of the "/Documents" in the path in the picture below. 
<img width="644" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/7e43875b-708d-4d88-8d43-8a75449173ad">

**Comment by romkatv** [comment]
There is also the FAQ: https://github.com/romkatv/powerlevel10k#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style

**Comment by hungngodev** [comment]
Thank you os much for your help!!

**Comment by romkatv** [comment]
You are welcome.
