### ISSUE TITLE
Prompt dir segment not updated after jumping to different directory with z.lua+fzf

### ISSUE THREAD

**Issue by rrpolanco** [romkatv/powerlevel10k#2434]
I'm seeing an issue where my prompt does not get updated/refreshed after selecting a destination with z.lua + fzf.

This is what I see. I select the `~/Downloads` directory and hit <kbd>Enter</kbd> but my prompt does not update _until_ I hit <kbd>Enter</kbd> again.
![zlua_issue_186](https://github.com/romkatv/powerlevel10k/assets/6497491/45cd1233-6fa0-4aa0-a39e-9f5d9728b8c1)

This is not an issue when I use starship prompt.

Any help is appreciated.

**Comment by romkatv** [comment]
Could you open an issue against z.lua? If they say that powerlevel10k needs to be changed, reopen this issue.

**Comment by rrpolanco** [comment]
Hmm, ok. Again, this works with starship prompt so it seems like there may be something in p10k that I have misconfigured or perhaps a bug. I have started a discussion with z.lua folks: https://github.com/skywind3000/z.lua/issues/186#issuecomment-1726664918
