### ISSUE TITLE
`No command GNU found` in termux

### ISSUE THREAD

**Issue by hasezoey** [romkatv/powerlevel10k#2435]
Since installing and setting powerlevel10k as the theme, i get the error `No command GNU found, did you mean:`, i am pretty sure this is another termux ZSH issue, but i am unsuccessful in finding where it originates from. 
What i did find is that it is related to the theme and not the configuration(`.p10k.zsh`) or instant prompt.
Aside from that (long) message, everything seems to work just fine.

Does anyone here maybe know where the issue may be coming from or how to better investigate?

Termux Android, with powerlevel10k 873c4ff09c559a507d33e528df7e27a8a48705d7 and oh-my-zsh 1c55a0fe5246487ec9f18e03b7f28862b76cb7ab

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k?

**Comment by hasezoey** [comment]
nevermind i was just dumb and didnt realize that i copied the gnu nano header while copying the instant-prompt code into the beginning of the file
