### ISSUE TITLE
What's this character?

### ISSUE THREAD

**Issue by John-Gee** [romkatv/powerlevel10k#2438]
Hey sorry to bother you again,, but reading the issues I got to change the base look and I'm almost where I want it (I think).
So I already know using the wrong font will make things not exactly padding-free or centered, I get that.
But I think there is an extra character and I'd like to know what it is, and if I can remove it.

![image](https://github.com/romkatv/powerlevel10k/assets/1646210/0957565b-3c89-4757-87c7-524fa0668b93)

I'm talking about the one one the left of the 'ok'. Does it mean something? Can I remove it?
I'm selecting the text, that's why the colors are reversed; without selecting it it's just black like a space/padding.

Thank you!

**Comment by romkatv** [comment]
Here's how it looks when all prompt segments have background colors distinct from the terminal background color:

![](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-styles-high-contrast.png)

Your terminal is configured in such a way to render color 0 with exactly the same hue as the terminal background. This can be surprising. You have several options:

- Change color 0 in the terminal settings.
- Change the background color in the terminal settings.
- Replace color `0` in `~/.p10k.zsh` with a different color.

**Comment by John-Gee** [comment]
Oooh yes I see, it's not a character it's the arrow thing. Sorry I should have seen it from the not ok or time ones.

Good guess on the terminal, indeed for standard and bright I have the same as for color 0, faint is the only different one; that does not seem like a great idea so I'll have to change that, not sure to what since I've been with that colorset for decades.

If you don't mind me asking, how do you feel about the different lengths of prompts on the right, ex :
![image](https://github.com/romkatv/powerlevel10k/assets/1646210/10325bba-8dd8-4ec5-8dd1-46d5209fa968)

(Please do not mind the extra padding on the first one, that was before I removed the ZSH padding.)

It seems unclean, yet except with padding a single character will never take as much space as a time.

Actually with a prompt char on the 2nd line of the left (I never tried that before yesterday), do we even need the status on the right? Maybe if it gave the actual number?

Thanks a lot again!

**Comment by romkatv** [comment]
> Actually with a prompt char on the 2nd line of the left (I never tried that before yesterday), do we even need the status on the right? Maybe if it gave the actual number?

If you run `p10k configure` and select any style with the `prompt_char` in it, you'll notice that the OK status is no longer displayed. You'll still get the informative status from things like `false | true` or when kill a process with Ctrl-C.

You might want to take a look at this: https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard

**Comment by John-Gee** [comment]
> If you run `p10k configure` and select any style with the `prompt_char` in it, you'll notice that the OK status is no longer displayed. You'll still get the informative status from things like `false | true` or when kill a process with Ctrl-C.

I realized that when reading p10k.sh
 
> You might want to take a look at this: [romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard](https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard)

Yeah that is useful thank you!
