### ISSUE TITLE
How to modify the color of  command

### ISSUE THREAD

**Issue by BarryAlllen** [romkatv/powerlevel10k#2440]
How to modify the color of a command in p10k.zsh? The default color is green, but I want to change it to yellow. I have tried many methods but they cannot be implemented
![微信截图_20230927161611](https://github.com/romkatv/powerlevel10k/assets/63345686/68f398f5-8de8-43a9-99dc-95cf54c4cdc8)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

**Comment by BarryAlllen** [comment]
> https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

Thanks
