### ISSUE TITLE
Some segments show weird character sequence when changing directory in a git repository

### ISSUE THREAD

**Issue by dfucci** [romkatv/powerlevel10k#2443]
When some segments are enabled (I tested with `time` and `battery`), `cd`ing in a folder containing a git repository causes extra characters to appear on the righthand-side segment. See screenshot.
These characters disappear after a `clear`.  
This behaviour happens independently of the segment position (left or right) and order (beginning, middle, end of the segment). 

Specs
-  zsh 5.9 (x86_64-apple-darwin23.0) 
- Latest version of PowerLevel10k installed with OhMyZsh

<img width="756" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/68000/f6337527-459a-4b26-a7ff-60a0c241fe4c">

**Comment by romkatv** [comment]
- What terminal are you using?
- Can you reproduce it with another terminal?
- Can you reproduce it after `p10k configure` and without manual changes to `~/.p10k.zsh`? If not, what do you need to change in `~/.p10k.zsh` for the issue to surface?

**Comment by dfucci** [comment]
> * What terminal are you using?
kitty
> * Can you reproduce it with another terminal?
Yes. Same exact issue in iTerm. In Terminal.app instead of that character sequence I get `7;EndPrompt
`
> * Can you reproduce it after `p10k configure` and without manual changes to `~/.p10k.zsh`? If not, what do you need to change in `~/.p10k.zsh` for the issue to surface?
Yes. The extra characters are shown also after a `p10k configure` using rainbow style.

**Comment by romkatv** [comment]
Try this:

1. Run: `zsh -f`
2. Run:
   ```zsh
   source -- ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/config/p10k-rainbow.zsh
   source -- ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme
   ```

Is the problem still reproducible? If not, try this:

1. Run: `zsh -f`
2. Run:
   ```zsh
   source -- ${ZDOTDIR:-~}/.p10k.zsh
   source -- ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme
   ```

Is the problem still reproducible?

**Comment by dfucci** [comment]
> Try this:
> 
> 1. Run: `zsh -f`
> 2. Run:
>    ```shell
>    source -- ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/config/p10k-rainbow.zsh
>    source -- ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme
>    ```
> 
> Is the problem still reproducible? 

This is not reproducible, but because that theme does not include a segment that is associated to the behaviour (e.g., `time` or `battery`)

If not, try this:
> 
> 1. Run: `zsh -f`
> 2. Run:
>    ```shell
>    source -- ${ZDOTDIR:-~}/.p10k.zsh
>    source -- ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k/powerlevel10k.zsh-theme
>    ```
> 
> Is the problem still reproducible?

This seems to solve the issue.

**Comment by romkatv** [comment]
> This seems to solve the issue.

This means there is something in your zsh rc files that causes the issue. Try to identify what that is.

**Comment by dfucci** [comment]
Thanks. Removing the `zsh-autosuggestions` plugin in my zshrc seems to fix the issue.
