### ISSUE TITLE
custom colima plugin right prompt element doesn't show

### ISSUE THREAD

**Issue by hugo-HDSF** [romkatv/powerlevel10k#2444]
I'm trying to make my own plugin for colima that shows on the right pompt element (just like nvm or aws does) the name of the last vm running when using "colima start [PROFIL]" OR if the vm was already running and we open a new terminal, it parses the output of ```colima list``` to identify which first profile is currently running (simpler than figuring out the last one that was run since there's no way of knowing that if multiples vms are already running...)
Sadly, it doesn't show anything, even when running the "colima start [PROFIL]" command, here is my code so far....:
(I've tried to put my plugin is ```/.oh-my-zsh/custom/plugins/colima/colima.plugin.zsh```but I've read later that this custom folder it just to override existing plugins.

/.oh-my-zsh/plugins/colima/colima.plugin.zsh:
```
function colima_prompt_info() {
  local _colima_to_show
  # Grabbing the profile name of the last running VM
  local colima_vm=$(colima list 2>/dev/null | awk '/Running/ {print $1}' | tail -n 1)

  if [[ -n "$colima_vm" ]]; then
    _colima_to_show+="${ZSH_THEME_COLIMA_PREFIX="<colima:"}${colima_vm}${ZSH_THEME_COLIMA_SUFFIX=">"}"
    echo "$_colima_to_show"
  fi
}
```
/.zshrc :
```
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(colima zsh-autosuggestions git docker docker-compose autojump zsh-syntax-highlighting npm)
```

/.p10k.zsh:
```
# The list of segments shown on the right. Fill it with less important segments.
# Right prompt on the last prompt line (where you are typing your commands) gets
# automatically hidden when the input line reaches it. Right prompt above the
# last prompt line gets hidden if it would overlap with left prompt.
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    direnv                  # direnv status (https://direnv.net/)
    asdf                    # asdf version manager (https://github.com/asdf-vm/asdf)
    colima                  # colima vm infos
    virtualenv   ........
    .......
```

**Comment by rwmitchell** [comment]
> (I've tried to put my plugin is `/.oh-my-zsh/custom/plugins/colima/colima.plugin.zsh`but I've read later that this custom folder it just to override existing plugins.

I don't believe that is true.  I have a number of my own plugins loaded from that directory.
It is true that those get loaded last, so they'll overwrite anything with the same name set previously.

**Comment by romkatv** [comment]
See `p10k help segment` and search for "example" in `~/.p10k.zsh`.
