### ISSUE TITLE
Question: Conditional SHOW_ON_COMMAND based on command line args?

### ISSUE THREAD

**Issue by torgeir** [romkatv/powerlevel10k#2445]
Thanks for a great fork!

I was wondering if there is a way to match on the arguments given to a command `<cmd> <args>` when using POWERLEVEL9K_<cmd>_SHOW_ON_COMMAND?

Say, if I did this

```
POWERLEVEL9K_T_NPM_SHOW_ON_COMMAND="npm"
..
function prompt_t_npm () {
  NPM_SCRIPTS=$([[ -f package.json ]] && cat package.json | jq -r '.scripts | keys | sort | join(" ")')
  p10k segment -t "%F{orange}$NPM_SCRIPTS"
}
..
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  ...
  t_npm
  ...
)
```

Can I, inside `prompt_t_npm`, or in some other way, match on the full command as written out in the command line prompt, so I can reach its arguments as well? I would like this p10k segment to appear only if I typed `npm run` and not if i typed `npm`.

Thanks!

**Comment by romkatv** [comment]
You can look at the full command line: `$PREBUFFER$BUFFER`.

**Comment by romkatv** [comment]
To clarify, you need to remove `POWERLEVEL9K_T_NPM_SHOW_ON_COMMAND` and add this:

```zsh
# This function is invoked whenever the command line changes.
function p10k-on-post-widget() {
  # If the command line is equal to "npm run", show prompt segment segment "t_npm".
  # Otherwise hide it.
  if [[ $PREBUFFER$BUFFER == 'npm run' ]]; then
    p10k display '*/t_npm'=show
  else
    p10k display '*/t_npm'=hide
  fi
}
```

**Comment by torgeir** [comment]
Thanks. That will work fine on my end.

What do you think about adding this information to the calls that powerline10k make to `prompt_<name>`, so that these types of additions could be self-contained, only inside the functions that extend the prompt?

**Comment by romkatv** [comment]
The job of `prompt_<name>` is to render a prompt segment. They are relatively expensive (the one you wrote is EXTREMELY expensive, and is likely visibly slowing down your prompt). Invoking them on every key press would be inefficient and cause input latency when typing. Besides, it wouldn't allow you the flexibility that the current architecture provides, in which you can show/hide any combination of segments depending on the content of the command line.

**Comment by romkatv** [comment]
> the one you wrote is EXTREMELY expensive, and is likely visibly slowing down your prompt

You can check if this is true by doing the following:

1. Press and hold ENTER with your current zsh config.
2. Remove all `t_*` segments from `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`, restart zsh with `exec zsh` and again try pressing and holding ENTER.

You probably will see the difference with the naked eye. Alternatively, you can use https://github.com/romkatv/zsh-bench to get a numerical measurement of prompt latency (see "prompt lag (ms)" in https://github.com/romkatv/zsh-bench#what-it-measures).

**Comment by torgeir** [comment]
Thanks. With `POWERLEVEL9K_T_NPM_SHOW_ON_COMMAND="npm"` will they not only run when prefixed by `npm `? I was not suggesting they run on every keypress without the prefixed command.

As long as the speed is OK, the benefits of the contextual information far outweighs my need for speed for such operations. This is of course personal preference.

I get and appreciate you wanting to keep p10k efficient and speedy! Will definitely check out your suggestions.

**Comment by romkatv** [comment]
> With `POWERLEVEL9K_T_NPM_SHOW_ON_COMMAND="npm"` will they not only run when prefixed by `npm `?

No. `prompt_*` functions run once before every prompt.

**Comment by torgeir** [comment]
Oh, alright. I will move to using `p10k-on-post-widget` for all of these then. Thanks again.
