### ISSUE TITLE
prompt keeps being redrawn when clearing terminal if using `POWERLEVEL9K_PROMPT_ON_NEWLINE`

### ISSUE THREAD

**Issue by xfzv** [romkatv/powerlevel10k#2446]
I'm using Kitty:

```console
❯ kitty --version
kitty 0.30.1 created by Kovid Goyal
```

I don't like the default behavior for `ctrl+l` which is to clear the screen without keeping the scrollback, so I added the following in my `zsh` config, as per [Kitty website instructions](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Reset-the-terminal):

```zsh
ctrl_l() {
    builtin print -rn -- $'\r\e[0J\e[H\e[22J' >"$TTY"
    builtin zle .reset-prompt
    builtin zle -R
}
zle -N ctrl_l
bindkey '^l' ctrl_l
```

This works as expected but `powerlevel10k` prompt keeps being redrawn everytime I press `ctrl+l` (I have to scroll up to see it):

![image](https://github.com/romkatv/powerlevel10k/assets/78810647/20bdb8d3-d54e-47f6-8a49-dfa4ed3cf367)

Disabling `POWERLEVEL9K_PROMPT_ON_NEWLINE="true"` in my config file solves the issue.

Is there any workaround for this?

Thanks.

**Comment by romkatv** [comment]
You can try this:

```zsh
# A simplified (and slightly worse) version of:
# https://github.com/romkatv/zsh4humans/blob/v5/fn/z4h-clear-screen-soft-top
function clear-screen-soft-top() {
  [[ -t 1 ]] || return
  zmodload zsh/terminfo
  echoti civis
  print -rn -- "${(pl:$((2 * LINES))::\n:)}"$'\e[H\e[2J'
  zle .reset-prompt
  zle -R
  print -rn -- ${${terminfo[cnorm]-}:/*$'\e[?25h'(|'\e'*)/$'\e[?25h'}
}

zle -N clear-screen-soft-top
bindkey '^L' clear-screen-soft-top
```

**Comment by romkatv** [comment]
You might have luck modifying it if you understand how it works. The same goes for your first version. You could also ask the author of the first snippet for help.

Given that the code you are asking for help with isn't a part of powerlevel10k and is at best tangentially related, I'm going to close this issue.
