### ISSUE TITLE
[Feature Request] Support Azure Devops (ADO) as VCS remote icon

### ISSUE THREAD

**Issue by FedeAbella** [romkatv/powerlevel10k#2447]
I've been using p10k for a while, and I love that it shows me if a local branch has a set remote (e.g. Github, which is the usual for me), by changing the icon.

I'm now on a project which uses an ADO repo, but p10k keeps showing the `git`  icon even when the branch is tracked.

I've confirmed with `git remote -v` that the branch is indeed tracked (I'd just cloned the repo):
![image](https://github.com/romkatv/powerlevel10k/assets/65520926/dde3fc43-1b04-4573-862d-dadd50d788e5)

**Comment by romkatv** [comment]
I've added an icon for Azure to vcs. Please update powerlevel10k and see if it works for you.

**Comment by FedeAbella** [comment]
What a ride! Was about to say it didn't work after `source`, then double checked the FAQ to find out that wasn't enough (yay for reading!), then turned out my Meslo font wasn't the patched one, but after doing the *right* steps, it's working!

![image](https://github.com/romkatv/powerlevel10k/assets/65520926/5b40c3ab-82dd-4308-b619-46b001e5c637)

Thanks! That was really fast!

**Comment by romkatv** [comment]
Thanks for verifying!
