### ISSUE TITLE
Only show Python version in Virtualenv

### ISSUE THREAD

**Issue by UnknownUser95** [romkatv/powerlevel10k#2452]
I have tried for quite some time to remove the virtualenv name from the prompt, but I cannot figure out how.
I managed to limit it down to the `POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION` setting, but I have no idea how it is made up.
In the output of `typeset` I only found the already created string.

---

As of now, the virtualenv output is `<Python version> <venv name>` (e.g. `3.11.5 venv`). Since I have `POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=()` in my config, the name is already only the folder name, but I don't want the folder name at all (e.g. only `3.11.5`).

**Comment by romkatv** [comment]
```zsh
POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION='${P9K_CONTENT%% *}'
```

**Comment by UnknownUser95** [comment]
thank you so much!

**Comment by romkatv** [comment]
You are welcome.

This parameter instructs powerlevel10k to remove the content of `virtualenv` prompt segment after the first space.
