### ISSUE TITLE
Transient prompt not working

### ISSUE THREAD

**Issue by IgorOldani** [romkatv/powerlevel10k#2453]
I installed powerlevel10k and went through the config. Everything is working except the transient prompt feature. I'm using iTerm2. What could be the issue? I've reviewed .zshrc and .p10k.zsh many times but no clue.

**Comment by romkatv** [comment]
Let's first establish what exactly isn't working. Please do the following:

1. Close your terminal app.
2. Open your terminal app.
3. Press ENTER.
4. Post a screenshot of your terminal app.

**Comment by IgorOldani** [comment]
Sorry I think I missunderstood the Transient Prompt. I thought it would collapse the previous command in just one line, but it seems that the real purpose is just remove the prompt from the previous command. Am I right? Here's the screenshot:

<img width="797" alt="Screenshot 2023-10-15 at 16 14 37" src="https://github.com/romkatv/powerlevel10k/assets/37940825/e77a24b7-29e2-4870-8e7f-5cc97d323d63">

**Comment by romkatv** [comment]
Transient prompt is working as intended on your screenshot.
