### ISSUE TITLE
Custom git-crypt segment using VCS_STATUS_RESULT not working as expected

### ISSUE THREAD

**Issue by lcrockett** [romkatv/powerlevel10k#2454]
# What i'm trying to achieve

Only if i'm in a git directory, i'd like to determine the status of 2 files in order to conclude wether git-crypt (if used) is locked or unlocked. That means the following workflow:

1) Am I in a git directory (`[[ "$VCS_STATUS_RESULT" =~ ^ok-.*$ ]]`) ? Yes -> continue
2) Is `$VCS_STATUS_WORKDIR/.git-crypt/keys/default` a directory AND does `$VCS_STATUS_WORKDIR/.git/git-crypt/keys/default` not exist ? Then git-crypt is used but locked
3) Is `$VCS_STATUS_WORKDIR/.git-crypt/keys/default` a directory AND does `$VCS_STATUS_WORKDIR/.git/git-crypt/keys/default` exist ? Then git-crypt is used and unlocked

# What I did to try and achieve my goal

I've made a custom prompt to determine the above and set the appropriate segment and identifier. See below. The custom prompt is included in my `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` list.

# What problem am I running into

For some reason the prompt seems to initialize (I think), but not show up. I determine this by opening a new shell and briefly (a second or so) seeing the prompt appear only to disappear right after and not coming back, even after hitting enter a few times or moving directories.

# What steps did I take to troubleshoot

I've made two different prompts (see below). One of them exposes the `$VCS_STATUS_RESULT` variable output in another made up variable that I access in my conditionals. When I take this approach the prompt seems to work-ish. 2 problems with this approach;
1) the prompt doesn't show up right away, I have to hit enter or type any command for the segment to appear on the prompt;
2) once I leave the git directory the custom prompt keeps following me, seems obvious to me as i've set a made up variable to determine if i'm in a git directory that doesn't get properly cleared once leaving a git directory.

# What is next

Some pointers and tips to help me achieve my goal would be greatly appreciated as i'm not exactly sure why I can't seem to access the `$VCS_` variables within my custom prompt function. If you need any additional details, let me know. I'm trying to avoid running git commands for a live result of my conditionals and use shell variables instead in order to ensure the prompt does not become too expensive and to avoid lag as much as possible.

<details>
  <summary># Example: non-working</summary>
  
  ```bash
    function prompt_my_gitcryptstatus() {
      if [[ "$VCS_STATUS_RESULT" =~ ^ok-.*$ ]]; then
          if [[ -d "$VCS_STATUS_WORKDIR/.git-crypt/keys/default" ]] && [[ ! -e "$VCS_STATUS_WORKDIR/.git/git-crypt/keys/default" ]]; then
              POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT="locked"
              p10k segment -t "$POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT"
          fi
  
          if [[ -d "$VCS_STATUS_WORKDIR/.git-crypt/keys/default" ]] && [[ -e "$VCS_STATUS_WORKDIR/.git/git-crypt/keys/default" ]]; then
              POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT="unlocked"
              p10k segment -t "$POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT"
          fi
      fi
    }
  
    function instant_prompt_my_gitcryptstatus() {
        prompt_my_gitcryptstatus
    }
  
    typeset -g POWERLEVEL9K_MY_GITCRYPTSTATUS_FOREGROUND=76
    typeset -g POWERLEVEL9K_MY_GITCRYPTSTATUS_VISUAL_IDENTIFIER_EXPANSION=''
  ```
</details>

<details>
  <summary># Example: working-ish</summary>

  ```bash
    function prompt_my_gitcryptstatus() {
      if [[ "$VCS_STATUS_RESULT" =~ ^ok-.*$ ]]; then
          export SELF_VCS_STATUS_RESULT="$VCS_STATUS_RESULT"
          export SELF_VCS_STATUS_WORKDIR="$VCS_STATUS_WORKDIR"
      fi
  
      if [[ "$SELF_VCS_STATUS_RESULT" =~ ^ok-.*$ ]]; then
          if [[ -d "$SELF_VCS_STATUS_WORKDIR/.git-crypt/keys/default" ]] && [[ ! -e "$SELF_VCS_STATUS_WORKDIR/.git/git-crypt/keys/default" ]]; then
              POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT="locked"
              p10k segment -t "$POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT"
          fi
  
          if [[ -d "$SELF_VCS_STATUS_WORKDIR/.git-crypt/keys/default" ]] && [[ -e "$SELF_VCS_STATUS_WORKDIR/.git/git-crypt/keys/default" ]]; then
              POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT="unlocked"
              p10k segment -t "$POWERLEVEL9K_MY_GITCRYPTSTATUS_SEGMENT"
          fi
      fi
    }
  
    function instant_prompt_my_gitcryptstatus() {
        prompt_my_gitcryptstatus
    }
  
    typeset -g POWERLEVEL9K_MY_GITCRYPTSTATUS_FOREGROUND=76
    typeset -g POWERLEVEL9K_MY_GITCRYPTSTATUS_VISUAL_IDENTIFIER_EXPANSION=''
  ```
</details>

**Comment by romkatv** [comment]
Try this:

```zsh
function prompt_my_gitcryptstatus() {
  emulate -L zsh -o extended_glob
  local dotgit=( ./(../)#.git(/NY1) )
  # Bail if there is no '.git' directory in the current directory or above.
  (( $#dotgit )) || return
  # Bail if there is no '.git-crypt/keys/default' directory next to '.git'.
  [[ -d $dotgit-crypt/keys/default ]] || return
  # Check if there is 'git-crypt/keys/default' within '.git'.
  if [[ -e $dotgit/git-crypt/keys/default ]]; then
    # Unlocked: green nf-fa-user_secret icon.
    p10k segment -i $'\UF21B' -f 76
  else
    # Locked: red nf-fa-user_secret icon plus nf-seti-lock.
    p10k segment -i $'\UF21B' -f 160 -t $'\UE672'
  fi
}
```

This doesn't do exactly what you specified but it'll probably work just fine.

You can look up icons at https://www.nerdfonts.com/cheat-sheet. For example, typing "lock" will show all icons with "lock" in their identifiers, including "nf-seti-lock" that I used above.

Do NOT define `instant_prompt_my_gitcryptstatus`. Prompt segments of this kind can only be rendered in the full prompt.

You *can* define parameters such as `POWERLEVEL9K_MY_GITCRYPTSTATUS_FOREGROUND` and `POWERLEVEL9K_MY_GITCRYPTSTATUS_VISUAL_IDENTIFIER_EXPANSION` but you don't have to. These are essentially overrides. Rather than overriding, you can specify exactly what you want within the body of `prompt_my_gitcryptstatus`.

**Comment by lcrockett** [comment]
Works like a charmadillo, thanks for that and the additional suggestion in printing behaviour. 

I use both instant and transient prompts BTW. so i'm confused about your comment not to define `instant_prompt_my_bla`. Am I never supposed to define it or only if I am using an instant prompt ? I initially defined it based on [this](https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-classic.zsh#L1682-L1683) reference.

<details>
  <summary>Implemented custom prompt</summary>

  ```bash
﻿﻿  function prompt_my_gitcryptstatus() {
      emulate -L zsh -o extended_glob
      local dotgit=( ./(../)#.git(/NY1) )

      (( $#dotgit )) || return
      [[ -d "$dotgit-crypt/keys/default" ]] || return

      if [[ -e "$dotgit/git-crypt/keys/default" ]]; then
          p10k segment -f 76 -i ''
      else
          p10k segment -f 160 -i ''
      fi
  }
  ```
</details>

**Comment by romkatv** [comment]
> Am I never supposed to define it, or should it only be defined when using an instant prompt ? I initially defined it based on [this](https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-classic.zsh#L1682-L1683) reference.

From the link you posted:

> It is imperative that `instant_prompt_*` always makes the same `p10k segment` calls regardless of environment. If this rule is not observed, the content of instant prompt will be incorrect.

It's a bit fuzzy on what constitutes the "environment" but it does include the content of the filesystem. Hence you should not define `instant_prompt_my_gitcryptstatus`. A bit more info on how instant prompt works: https://github.com/romkatv/zsh-bench/blob/master/README.md#instant-prompt

> ![image](https://github.com/romkatv/powerlevel10k/assets/1282067/279cb042-2e5a-4c95-9d43-e03489dbbb38)

If you want to be able to share your code with others and (perhaps even more importantly) be able to see it and edit it yourself in any editor, do not use characters from Unicode Private Use Area in it. Such characters have no prescribed meaning or presentation. Fonts are free to display them as absolutely anything, and most fonts will display nothing. This is what you see in the screenshot I took from Chrome. Use `$'\UXXXX'` instead, the same as in my code that I posted above.

Also note that the double quotes you added don't do anything. They don't hurt though.

**Comment by lcrockett** [comment]
Thank you for the additional explanation. I've incorporated your suggestions into my custom prompt and updated other custom ones that also used `instant_prompt_*`. 

Cheers on your advice and a fantastic Z shell theme !
