### ISSUE TITLE
Keep the transient prompt at the bottom after a user browses the history

### ISSUE THREAD

**Issue by StayPirate** [romkatv/powerlevel10k#2456]
@romkatv as you mentioned [here](https://github.com/romkatv/powerlevel10k/issues/2442#issuecomment-1746204964):

> In particular, in zsh4humans prompt stays at bottom even when you press Ctrl-R or Tab.

Indeed I face the problem of the transient prompt not being kept at the bottom every time I use Ctrl-R to browse the history. Do you think there's any quick fix I may implement to avoid this?

I see your zsh4humans does that, but it's no longer supported, hence I would refrain to start using it.

### Setup

My current setup is based on your suggestion on [this other issue](https://github.com/romkatv/powerlevel10k/issues/2442#issuecomment-1746204964) and [looks like that](https://github.com/StayPirate/dotfiles/commit/6a258a788fd623f69a5721ad6d3b319b7154c952):

```zsh
# Put the $PROMPT at the bottom of the terminal
# https://github.com/romkatv/powerlevel10k/issues/2442

clear-screen-soft-bottom() {
  [[ -t 1 ]] || return
  zmodload zsh/terminfo
  echoti civis
  print -rn -- "${(pl:$((2 * LINES - 1))::\n:)}"
  zle -I
  zle -R
  print -rn -- ${${terminfo[cnorm]-}:/*$'\e[?25h'(|'\e'*)/$'\e[?25h'}
}
```

### Screenshots

- Initial
    ![image](https://github.com/romkatv/powerlevel10k/assets/37073343/2f015ae7-983d-4ce6-b462-819fa708cc90)
- I hit `Ctrl-R` to browse the history
    ![image](https://github.com/romkatv/powerlevel10k/assets/37073343/7ff5b006-3fe3-4511-b696-aa25a06699f2)
- Press `Enter` to select an entry from the history
    ![image](https://github.com/romkatv/powerlevel10k/assets/37073343/b5e96e94-24ce-4f27-b9b9-16e86332d13f)

**Comment by romkatv** [comment]
Also, I don't see transient prompt on your screenshots.

**Comment by StayPirate** [comment]
> On your screenshot fzf scrolled the terminal screen. If that's not what you want, don't invoke fzf in this way.

Wow, you're right. I haven't thought about that. I managed to fix it by calling `clear-screen-soft-bottom()` from the function where I use `fzf`. Thanks for your input.
