### ISSUE TITLE
Bold font is invisible/unable to be rendered

### ISSUE THREAD

**Issue by Cheezik** [romkatv/powerlevel10k#2457]
hello, im getting this really strange thing, The bold text form the p10k config. 
(im using debian 10)

Simply put the bold text in the config wizzard is unable to be rendered? 

![image](https://github.com/romkatv/powerlevel10k/assets/80171791/0117f0fe-8788-4631-8927-12c7cdcb7428)

i have made sure that i have the correct font, and the bold text option in my terminal preferences enabled

![image](https://github.com/romkatv/powerlevel10k/assets/80171791/6baa39b1-395b-43cb-bae6-3605274f7a9d)

Im awere that the defualt monospace is set to Bold, I was just testing if that wont help

im unsure if im doing something wrong or its not fault on my end
maybe if there is something that i have enabe/disable or is there option for using just the normal text

thanks in advance

**Comment by romkatv** [comment]
Try a different font, a different color scheme, a different terminal, etc. Keep in mind that this issue isn't specific to powerlevel10k or zsh. It's just your terminal.

**Comment by Cheezik** [comment]
okay, after some messing around i found the issue

for some **_darn_** reason **the Bold text collor was set to BLACK?!**

thanks again for suggesting diffrent color scheme, _im stupid for not checking that before opening issue_ 
Have a great rest of your day!
