### ISSUE TITLE
Typing "yes" in prompt is printing character 'y' infinitely. I am using Oh my Zsh.

### ISSUE THREAD

**Issue by bhanusumanth** [romkatv/powerlevel10k#2458]
I have set Instant Prompt and transient promt Enabled
When I type "yes" in terminal, its printing 'y' continuously

![render1697657107473](https://github.com/romkatv/powerlevel10k/assets/24877676/240529bc-228d-4c7a-8dab-29d31460e39c)

The output capture tool didn't record the powerlevel theme, but the functionality remains unchanged.

**Comment by romkatv** [comment]
Type `man yes` for docs.

**Comment by bhanusumanth** [comment]
whoopsies, I am not aware of that command. Thanks for quick response!

**Comment by romkatv** [comment]
In the future please don't open an issue for "problems" of this kind. The fact that you are using powerlevel10k doesn't mean it's appropriate to ask here for help with your terminal problems.

**Comment by bhanusumanth** [comment]
Sorry about that. I am kinda new to linux terminals. It wont happen again. Thanks

**Comment by romkatv** [comment]
There are places where these questions are fine. Perhaps /r/commandline or /r/linux4noobs. When filing an issue against a specific piece of software, you need to have a reasonable level of confidence that the software is indeed at fault. Not so for questions on general forums like the ones I mentioned above.

In any case, have fun exploring Linux and the command line.
