### ISSUE TITLE
weird next line prompt behavior - jetbrains

### ISSUE THREAD

**Issue by hugo-HDSF** [romkatv/powerlevel10k#2462]
Hello, 
I have a behavior that is getting quite annoying, whenever there is a background process going on, for exemple, let's say I jump into a directory with a `.git`, it will process and prompt the git status as it should, but it will also prompt an empty line right after : right before I can write any comand line, but when I'm not on a directory that requires a git process or anything else, it doesn't : 

when Im in a repository for exemple :
<img width="642" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/116161276/e716090e-0cc4-482a-b096-495080a5420b">

<when I'm not :
<img width="636" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/116161276/2822f3c0-df77-440f-ad02-b3b53dc20f60">

someone has any idea why this behavior happens ?

**Comment by romkatv** [comment]
If you can reproduce this with a pristine config after `p10k configure`, this would imply a bug in your terminal.

**Comment by hugo-HDSF** [comment]
I did a fresh `p10k configure` as you mentioned and then just did a conflict comparison beetween last and new `.p10k.zsh`, seems like I had many problems undergoinG anyway, it's working as entended now so far.

**Comment by hugo-HDSF** [comment]
seems like this behavior was happening because of `prompt_char` not being enabled and `vi_mode` being enabled, inverting it patches it for me.
```typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                 # os identifier
    dir                     # current directory
    vcs                     # git status
    # =========================[ Line #2 ]=========================
    newline                 # \n
    prompt_char             # prompt symbol
  )```
  ```
 typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    # vi_mode               # vi mode (you don't need this if you've enabled prompt_char)

```

**Comment by romkatv** [comment]
This change shouldn't cause any issues, so it's a bug in the terminal after all.

**Comment by romkatv** [comment]
Given that we are dealing with a terminal bug, here are the options:

- Fix the bug in the terminal.
- Use a different terminal.
- Avoid triggering the bug in the terminal. Removing all segments from the right side and disabling the gap (AKA connection) might do the trick.

**Comment by hugo-HDSF** [comment]
I'd be quite interested in doing that : "Removing all segments from the right side and disabling the gap (AKA connection) might do the trick." i know the issue here shouldn't be related to p10K but more to jetbrains then, but i've read that when defining a custom prompt, especially one that includes colors or other formatting, it's common to use escape sequences. These sequences are interpreted by the terminal to apply the desired formatting, but they themselves don't occupy space. However, if not correctly interpreted or enclosed, they might cause the terminal to miscalculate the width of the prompt.

**Comment by romkatv** [comment]
If you implement a custom prompt segment, you can definitely make mistakes. This is why I asked you to reproduce the issue with a pristine config, and so you did.

**Comment by romkatv** [comment]
> I'd be quite interested in doing that : "Removing all segments from the right side and disabling the gap (AKA connection) might do the trick."

Go ahead and try it. It's a simple change in `~/.p10k.zsh`.
