### ISSUE TITLE
Configure the color of the git and font weight of the current directory

### ISSUE THREAD

**Issue by hungngodev** [romkatv/powerlevel10k#2463]
<img width="651" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/ef2d62d6-ef28-4561-851b-b6ccbd133440">
How can I make the current directory bold like the Mech/views? Also, could you help me configure the git prompt at the end?
<img width="113" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/9e0a771b-d544-4016-836f-a723412e08f6">
Thank you!

**Comment by romkatv** [comment]
> How can I make the current directory bold

```zsh
POWERLEVEL9K_SHORTEN_STRATEGY=default
POWERLEVEL9K_SHORTEN_DIR_LENGTH=-1
POWERLEVEL9K_DIR_CONTENT_EXPANSION='%B$P9K_CONTENT%b'
```

> Also, could you help me configure the git prompt at the end?

https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by hungngodev** [comment]
I have seen that post and tried it but it does not work to make the current directory bold.

**Comment by romkatv** [comment]
Try this:

1. Run `zsh -f`.
2. Run the code I posted above.
3. Run `source ~/powerlevel10k/powerlevel10k.zsh-theme` (you might need to change the path to the file here).
4. Observe that the directory is rendered in bold.

**Comment by hungngodev** [comment]
<img width="1312" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/573c0300-99b1-4eaf-84bc-37a08a4e2969">
It does not execute anything on my end. Thank you for the reply.

**Comment by romkatv** [comment]
You missed `source` and what I wrote in the parentheses.

**Comment by hungngodev** [comment]
<img width="726" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/152f0e7d-0d99-47aa-8cb0-c184c506d86e">
I have tried including the source also.

**Comment by romkatv** [comment]
You missed what I wrote in the parentheses.

**Comment by hungngodev** [comment]
'%B$P9K_CONTENT%b' . Do you mean this line?

**Comment by romkatv** [comment]
> 3. Run `source ~/powerlevel10k/powerlevel10k.zsh-theme` (you might need to change the path to the file here).

Note the part in the parentheses. Basically, if powerlevel10k is not in your home directory, change the path.

**Comment by hungngodev** [comment]
<img width="1312" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/24e91529-48b6-4fee-b1bd-452464194bf6">
I have changed it but it appears to me that it does not change. My apology for bothering you.

**Comment by romkatv** [comment]
The correct path is `~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme`.

**Comment by hungngodev** [comment]
<img width="1309" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/105379889/b4756d27-82f0-47c4-9aa7-d2c054da74b0">
Hi it works but I just want to change the boldness of the current directory but it changes almost everything.
