### ISSUE TITLE
Add `stable` git branch

### ISSUE THREAD

**Issue by chfast** [romkatv/powerlevel10k#2464]
There are some zsh/omz plugin auto-upgrade conventions which just do `git pull`. This does not work for powerlevel10k which have proper releases (git tags). If there is the `stable` branch which points to the latest release the convention will work.

**Comment by romkatv** [comment]
`master` is the stable branch. It's safe to `git pull` it at any point. Think of it as a rolling release system. The numbered releases are simply checkpoints at arbitrary intervals. They are as stable as `master`.

**Comment by chfast** [comment]
Thanks.
