### ISSUE TITLE
Fill right and left prompt gap with same background color as last segment shown

### ISSUE THREAD

**Issue by hugo-HDSF** [romkatv/powerlevel10k#2465]
Is there a way to fill the GAP between left and right prompt on the first prompt line POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND with the same background color as the last segment background color shown ?

**Comment by romkatv** [comment]
No.

**Comment by hugo-HDSF** [comment]
okok, that was a really quick reply ! also, from my last issue, I tried to remove the gap between left and right prompt, but couldn't figure it out even tho you said it was really simple... sorry, I'm not the smartest fish of the sea...

**Comment by romkatv** [comment]
Run `p10k configure`. When it asks you about *Prompt Connection*, choose *Disconnected* (the first option).
