### ISSUE TITLE
having this issue with color

### ISSUE THREAD

**Issue by ssamin69** [romkatv/powerlevel10k#2466]
![IMG-20231026-WA0000.jpg](https://github.com/romkatv/powerlevel10k/assets/72408262/3012e245-4f24-4b0d-be5a-53acbf404734)

but when done error it doesn't do that

![IMG-20231026-WA0001.jpg](https://github.com/romkatv/powerlevel10k/assets/72408262/fbc3cd78-3b74-4c18-b4bc-d0cf0fce781d)

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
print -r -- ${terminfo[colors]}
```

If it's less than 256, your `TERM` is likely incorrect. If any of your zsh startup files (e.g., `~/.zshrc`) set `TERM`, you need to delete that. If none do, you need to configure your terminal to set a more reasonable `TERM`.

**Comment by ssamin69** [comment]
the output is 256

![image](https://github.com/romkatv/powerlevel10k/assets/72408262/102462b1-c0c8-4251-8615-d43fe0cc5967)

**Comment by romkatv** [comment]
Perhaps that's how colors look in your terminal? You can test it with this command:

```zsh
for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
```

**Comment by ssamin69** [comment]
heres the output 

![image](https://github.com/romkatv/powerlevel10k/assets/72408262/d1adb9e6-37e7-494d-a923-d06de6abc51c)


![image](https://github.com/romkatv/powerlevel10k/assets/72408262/d4946b26-c91c-44f4-83a7-71b04baf4594)


btw im using pywal for colorscheme

**Comment by romkatv** [comment]
As you can see in the output, the first 16 colors are shades of grey. Powerlevel10k simply respects your (rather bizarre, I have to admit) choice.

**Comment by ssamin69** [comment]
i see, so should i change the color for that specific part by doing some configuration? maybe similar to the "errors" one ? that should fix it right?

**Comment by romkatv** [comment]
You've configured your terminal to use shades of grey for all colors. This is an extremely uncommon choice. It almost looks like a joke. Most users prefer to see red as red, blue as blue, etc. If you don't *actually* want to see red, blue and all other colors as shades of grey, configure your terminal to use a more conventional color scheme.

**Comment by ssamin69** [comment]
understandable but i just like grey and wanted my whole setup as grey its actually a personal choice. btw thanks for your time :)

**Comment by romkatv** [comment]
Sure, then it's working as intended. You wanted a grey terminal and you've got a grey terminal, which includes grey powerlevel10k.

What was the problem then?

**Comment by ssamin69** [comment]
the problem was that little black portion at the letf corner of the tail when theres no error done. i guess my terminal colorscheme causing it.

**Comment by romkatv** [comment]
Take a look at the top of the image you posted earlier:

> ![image](https://github.com/romkatv/powerlevel10k/assets/72408262/d4946b26-c91c-44f4-83a7-71b04baf4594)

Note how for all colors except 0 the background and the foreground have the same color. This is normal. Color 0 is displayed abnormally by your terminal. If you can fix that (basically, make the background be the same as foreground), it'll look well in your prompt too.

P.S.

Both of us wasted an incredible amount of time here because the issue description is not descriptive.

**Comment by ssamin69** [comment]
sorry about not being descriptive. Anyway, thanks again for helping, ill configure my colors to see if i can fix it. have a nice day.
