### ISSUE TITLE
instant prompt feature prevents oh my zsh self update

### ISSUE THREAD

**Issue by FischLu** [romkatv/powerlevel10k#2467]
Today I realize that I haven't seen Oh My Zsh auto-update for a while. In the past, every once in a while (about every 1 or 2 weeks), when I opened a new console window, Oh My Zsh would automatically update. So, I go into the ~/.oh-my-zsh directory to check the Git log and indeed, it has been a long time since the last update. To investigate the reason, I take the following steps:

- First, I manually update Oh My Zsh to the latest version.
- `cd ~/.oh-my-zsh` and `git reset --hard HEAD^` This will get 1 commit back in the history of oh-my-zsh 
- Edit my .zshrc and uncomment `DISABLE_UPDATE_PROMPT="true"`, this will make omz to automatically update without prompting
- Edit my .zshrc adding `zstyle ':omz:update' frequency 0` before sourcing oh-my-zsh.sh, this will make omz to do update every time I open a session
- Comment out p10k instant prompt part at the top of my .zshrc
- Open a new session, I see the automatic updating, omz git repository is also updated to the newest version.

Now I redo `cd ~/.oh-my-zsh`, `git reset --hard HEAD^` and uncomment instant prompt, I cannot see auto update when I open new session. The omz git repository is still 1 commit behind the latest HEAD.

I have repeated above steps several times, and never see auto update when I enable instant prompt. Any help? thanks!

**Comment by romkatv** [comment]
If you really want to have omz auto update when starting zsh (it's a very bad idea in my opinion), you can do it like this:

```zsh
ZSH=~/.oh-my-zsh
ZSH_CACHE_DIR=$ZSH/cache
source $ZSH/tools/check_for_upgrade.sh

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

zstyle :omz:update mode disabled
# the rest of .zshrc
```

Why is omz auto-update a bad idea? It performs network I/O whenever you start your shell. It also blocks you from doing what you need when you are about to do it. It can also break your shell with no easy way to recover. The advantages, in comparison, are miniscule.

**Comment by FischLu** [comment]
Thank you for the information, OK, maybe disable auto update is a better idea, I update it in crontab then.

**Comment by romkatv** [comment]
FWIW, I'd personally choose to never update ohmyzsh over any kind of auto-update. OMZ does not have a staging or QA environment, no process for cutting releases. The risks that come with updates aren't worth the benefits. The latter are close to zero.
