### ISSUE TITLE
iTerm2 Integration Carrot w/ transient multiline prompt misaligned

### ISSUE THREAD

**Issue by HeroCC** [romkatv/powerlevel10k#2468]
Hello! I have small bug I'd like to report. When using iTerm2's shell integration, the prompt carrot is misaligned -- two lines above the actual prompt. Once a command is executed this becomes correctly aligned, but the actual prompt line is not. Here is a screenshot:

<img width="402" alt="Screenshot 2023-10-27 at 4 05 23 PM" src="https://github.com/romkatv/powerlevel10k/assets/2124489/9c4eee41-1f44-44b4-8759-fe0531256dea">

Note the blue carrot is above the green `❯`.

I was able to reproduce in a pure environment by opening iTerm2 and running this command:
```console
$ docker run -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 -it --rm alpine sh -uec '
  apk add git zsh nano vim curl
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  echo "source ~/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc
  wget https://iterm2.com/shell_integration/install_shell_integration.sh -O - | SHELL=zsh zsh
  cd ~/powerlevel10k
  exec zsh'
# select font stuff glyphs, lean prompt, unicode, 256 colors, no time, two lines, disconnected, no frame, sparse, concise, transient, verbose, apply changes
```

Thanks for your help!

**Comment by romkatv** [comment]
The marker cannot be moved. As you've correctly noted, it's obviously in the right place after you press ENTER. Therefore, it's in the right place before you press ENTER, too.

**Comment by romkatv** [comment]
Keep in mind you can hide those marks: https://stackoverflow.com/questions/41123922/iterm2-hide-marks

**Comment by HeroCC** [comment]
I'm also able to make it be off by one even after running commands, though I am not able to reproduce it with docker. I think it has something to do with the `Last login` from MacOS?

<img width="370" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/2124489/f7bb055e-849b-4377-b6e8-54934a2a060f">

> Therefore, it's in the right place before you press ENTER, too.

I'm a bit confused by this -- [the docs](https://iterm2.com/documentation-shell-integration.html) (under the multi-line configuration section) say it should point to the prompt line, and I suppose the while prompt may start up there, isn't the line itself the one where the user types?

> Keep in mind you can hide those marks

They come with some nice accessibility & usability features, so Ideally I'd like to keep using them.

**Comment by romkatv** [comment]
iTerm2 displays the mark on the first line of each prompt. If prompt takes more than one line, the mark still stays on the first line of each prompt.

> They come with some nice accessibility & usability features, so Ideally I'd like to keep using them.

If you hide the marks, nothing else will change. All features will work but the marks will no longer be displayed. I find them rather useless -- I already can see my prompt, there is no need to have an extra mark next to it.

**Comment by HeroCC** [comment]
If this is a `wontfix` or a feature request instead of a bug that's fine too. But regardless, since iTerm2 provides the facility to move the indicator, I'd like to do something similar with my p10k configuration just like any other prompt element.

**Comment by romkatv** [comment]
iTerm2 does not provide the facility to move the indicator.

**Comment by HeroCC** [comment]
Interesting, am I misinterpreting this statement from the docs then? It seems to describe this scenario.

> If you have a multi-line prompt and would like to customize the mark's location, add this to your PS1 at the location where the mark should appear:
For zsh: `%{$(iterm2_prompt_mark)%}`

**Comment by romkatv** [comment]
Once a mark has been set for a prompt, it cannot be moved. Prompt in powerlevel10k is dynamic and can be changed. If you start with a 3 line prompt, the prompt can be contracted to a single line. This happens when you are using transient prompt but you can also update prompt dynamically based on the content of the commandline or anything else. A mark on any prompt line other than the first will result in a misplaced mark when the prompt is contracted to a single line. Thus, the only prompt line where a mark can be placed is the first one. Powerlevl10k places the mark on the first line. This is intended and correct.

**Comment by abahocodes** [comment]
@HeroCC This is a marker added by the terminal. You can remove it with the instructions here.
https://github.com/ohmyzsh/ohmyzsh/issues/5088

**Comment by HeroCC** [comment]
> This is a marker added by the terminal. You can remove it with the instructions here

Thanks for responding, but I actually like the carrot & the iTerm features. I want to move it to align with the last line of my prompt, rather than the first.

**Comment by brandon-fryslie** [comment]
iTerm uses this mark to know where your prompt begins and ends.  I know this because I just spent a while getting everything working on my own custom prompt (written in pure zsh).  If you did figure out how to move it, it would cause some issues in other functionality, ie, the Captured Output would include parts of your prompt (which is obviously not ideal).
