### ISSUE TITLE
hiccup in the prompt rendering 

### ISSUE THREAD

**Issue by Ghasak** [romkatv/powerlevel10k#2469]
Hello,

First and foremost, I'd like to express my gratitude for your fantastic theme—it truly stands out, and It unmistakably sets the benchmark to all other developers in the world. 

I'm a noob, so I appreciate your patience and support. I recently transitioned to using your theme as my daily drive,  and added some customized functions to my prompt. While exploring its capabilities, I observed a rendering issue related to the third line, specifically when using the 'autojump' plugin. The lag becomes noticeable when I use the 'j' command to jump to a different location. Interestingly, I observed the same behavior with the 'zoxide' plugin, suggesting a potential compatibility issue with the theme's auto-rendering function.

For a clearer understanding, I've attached a video that demonstrates the problem.

References:
1. [Zoxide Plugin](https://github.com/ajeetdsouza/zoxide)
2. [Autojump Plugin](https://github.com/wting/autojump)

https://github.com/romkatv/powerlevel10k/assets/27670946/6bf4bc05-a69a-4dca-a815-346949fafcef

Thank you for your time and consideration.
**NOTE**: I also attached an image at the moment where the third line will not be rendered
![image](https://github.com/romkatv/powerlevel10k/assets/27670946/a49b0c65-8044-4066-8dd3-3f7c2c3cf7fe)

**Comment by romkatv** [comment]
Sounds like a bug in `j`.

**Comment by Ghasak** [comment]
my basic configurations are

```zsh 
    # =========================[ Line #1 ]=========================
    os_icon                  # os identifier
    user_name_and_machine
    #context                 # user@hostname
    dir                      # current directory
    newline
    ROBOT
    vi_mode                  # vi mode (you don't need this if you've enabled prompt_char)
    dice
    vcs                      # git status
    # =========================[ Line #2 ]=========================
    newline                  # \n
    #prompt_char             # prompt symbol
  )

```
and 
```zsh
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
      # =========================[ Line #2 ]=========================
    newline
    ELAPSE_TIME
    newline
    rust_version          # rustc version (https://www.rust-lang.org)
    virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
    anaconda                # conda environment (https://conda.io/)
    pyenv                   # python environment (https://github.com/pyenv/pyenv)
   
  )
```

**Comment by Ghasak** [comment]
Hi @romkatv 
> Sounds like a bug in `j`.

but I tried also zoxide , same thing! 
https://github.com/ajeetdsouza/zoxide

**Comment by romkatv** [comment]
Could be the same bug. They might be copying code from each other.

I'm afraid I don't feel enthusiastic about debugging this. If you can provide complete self-contained instructions how to reproduce this, I'll give it a go. If you file a bug against `j`, its dev(s) might be more helpful.

**Comment by Ghasak** [comment]
@romkatv -san, 
Greeting from Tokyo,
Firstly, I deeply appreciate your responsiveness and understanding. I recognize the complexity of the issue and your concern.
If it's not too much of a burden, could you possibly take a moment to review my configuration file? It was generated using the `p10k configure` command. [Here's the link to my config file](https://github.com/Ghasak/gdotfiles/blob/main/.p10k.zsh). To replicate the behavior I've described,

1. The file should be placed in the home directory, 
2. Either `autojump` or `zoxide` should be installed.
3. My `zshrc` config file can be found [here](https://github.com/Ghasak/gdotfiles/blob/main/.zshrc) has the following `.oh-my-zsh` plugins:

```zsh
plugins=(git
        # zsh-autocomplete
        # other plugins...
        # auto suggestions from here:
        # https://github.com/zsh-users/zsh-autosuggestions/blob/master/install.md
        zsh-autosuggestions
        # auto jump from here:
        #autojump
        # syntax zsh-syntax-highlighting from here:
        # https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/install.md
        #zsh-syntax-highlighting # Problem occured not used anymore
        # I use instead fast-syntax-highlighting
        # https://github.com/zdharma-continuum/fast-syntax-highlighting
        fast-syntax-highlighting
        # adding vim support to my current zsh:
        # vi-mode
        # https://github.com/jeffreytse/zsh-vi-mode
        zsh-vi-mode
        # replace zsh's default completion selection menu with fzf!
        # https://github.com/aloxaf/fzf-tab
        fzf-tab
        # clipboard
        clipboard
  )
  # **************************************************************************
#                     ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE
#           This will alter the default for Auto-completetion
# **************************************************************************
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#97A7B3, bg=#ADB6C4  ,bold,underline"

# **************************************************************************
# Configurations for fzf-tab
# **************************************************************************
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# preview directory's content with exa when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'exa -1 --color=always $realpath'
# switch group using `,` and `.`
zstyle ':fzf-tab:*' switch-group ',' '.'
zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

# **************************************************************************
# Configurations for fzf-vi-mode
# **************************************************************************
function zvm_config() {
  # ZVM_LINE_INIT_MODE=$ZVM_MODE_NORMAL
  ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
  ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
}
# **************************************************************************
# Souce all the plugins
# **************************************************************************
source $ZSH/oh-my-zsh.sh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```
For clarity, I'm using a MacBook with macOS Sonoma 14.0 on an Apple M1 Max.

I completely understand if this may seem like a bug originating from the `auto jump` or `zoxide` utility commands, and possibly beyond the purview of your outstanding project. However, if you could guide me, even with some preliminary insights or direction on how to address this, I would then be better equipped to approach the respective developers and bring this to their attention on their corresponding repos.

If you feel this exceeds the scope of support you're willing to provide, I completely understand. We can then consider closing this issue. Regardless, I'm truly grateful for your time, support, and quick attention to my concerns.

Warm regards,

**Comment by romkatv** [comment]
Please reduce your `.zshrc` to the absolute minimum. Start with this:

```zsh
eval "$(zoxide init zsh --cmd j)"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(prompt_char)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
source ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme
```

Does the issue still reproduce with this `.zshrc`? If not, what is the smallest change you need to make so that the issue reproduces?

**Comment by Ghasak** [comment]
I will check now and let you know,

**Comment by Ghasak** [comment]
@romkatv-san,

Deep gratitude for your invaluable guidance. Your insights on debugging greatly enhanced my understanding of how to systematically address unforeseen behaviors. As you suggested, I began with the most basic configuration.

My investigation led me to a function in the [zsh-vim-mode](https://github.com/jeffreytse/zsh-vi-mode) plugin. It was unrelated to the theme, other plugins, or any external configurations.

```zsh 
# Configurations for fzf-vi-mode
function zvm_config() {
  ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
  ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
}
```

Specifically, the `ZVM_VI_INSERT_ESCAPE_BINDKEY=jk` command led to the hiccup. It toggles to the `normal` mode using the `jk` keybinding, and I overlooked the `j` conflicting with `jk`.

I'm thrilled to report the issue's resolution, and I'll be closing the related issue thread. Your assistance was instrumental, and should you ever find yourself in Tokyo, a sushi dinner is on me to show my appreciation.

You wouldn't believe the relief I feel right now; it was an issue that had me on edge for so long.

**Comment by Ghasak** [comment]
The issue is resolved! 
I just needed to remove the command ` ZVM_VI_INSERT_ESCAPE_BINDKEY=jk` from my configuration file.

**Comment by romkatv** [comment]
I'm glad you managed to solve resolve this issue by yourself.

> [...] should you ever find yourself in Tokyo, a sushi dinner is on me to show my appreciation.

I don't deserve it but I'm might just call you up on this generous offer :D

**Comment by Ghasak** [comment]
Hi @romkatv -san,
Absolutely, I will be more than happy to show you many good local great restaurants, until that time, have a great productive days Sir!
