### ISSUE TITLE
Bold prompt segments

### ISSUE THREAD

**Issue by maximbaz** [romkatv/powerlevel10k#247]
Hey, just a quick question, is it possible to make segments bold?

I've seen your request in https://github.com/Powerlevel9k/powerlevel9k/issues/1223, it seems to be claimed as implemented, but at the same as far as I understand you have your own implementation of the prompt that doesn't necessarily follow powerlevel9k (right?).

For example I tried this, doesn't seem to have any effect:

```
typeset -g POWERLEVEL9K_TIME_BOLD=true
```

Not saying this is super urgent, just curious if this is implemented or if not is it something you want?

**Comment by romkatv** [comment]
There is no such parameter at the moment. You can achieve the same result in most cases with a content expansion.

```zsh
typeset -g POWERLEVEL9K_TIME_CONTENT_EXPANSION='%B${P9K_CONTENT}'
```

`CONTENT_EXPANSION` applies at the very end, after the whole segment is built. It allows you to augment (like above) or replace (this is how you replace `user` segment content with empty string). `VISUAL_IDENTIFIER_EXPANSION` is similar but for icons. Note that segments whole icon and content are both empty (after expansions) are not rendered.

**Comment by maximbaz** [comment]
I see, interesting concept with `CONTENT_EXPANSION`! I've just tested and it works well for me, so I'm happy with the solution (thanks!) and will close, feel free to reopen if at some point you want to implement `_BOLD` options 👍
