### ISSUE TITLE
`PS1`  env variable acquiring noice when loading multiple Python virtual environments

### ISSUE THREAD

**Issue by kmontocam** [romkatv/powerlevel10k#2470]
Hello there, I just noticed this weird effect when loading two or more virtual environments. 

<img width="1552" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/80984024/db6e1fa6-af43-420e-a071-926debc31275">
<img width="1552" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/80984024/82d0b97c-4d33-473b-a31b-2b0518fdd6b6">

This was using python3's implementation of venv, but I get the same results using a conda virtual environment. I do not think this is part of the expected behavior, that is why I am documenting it.

Thank you for the work done on this theme, I find it pretty awesome

**Comment by romkatv** [comment]
The fact that `PS1` is exported is not normal. The expected result of running `env | grep "PS1"` is empty. You can try to figure out who exports `PS1` by adding `env | grep "PS1"` in various places within `.zshrc`. Start by adding it at the top. If there is no "PS1" in the environment at that point, move your instrumentation to the bottom. Note that you'll need to restart your terminal (or open a new tab) when making changes of this kind within `.zshrc`.

**Comment by kmontocam** [comment]
The activation/sourcing of a virtual environment is what is exporting `PS1`. That is the convention across many shells (including zsh), it is used to give the client a reference of which python interpreter is included to their `PATH`. Without p10k installed, it also modifies the variable.

Example of this on a debian machine:
<img width="713" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/80984024/bda271ae-4c3b-4575-9427-211c0a3822b2">

A more elaborated example with a config with p10k
<img width="1552" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/80984024/d0bf15a7-8027-4d64-a44c-4017a72feed3">

**Comment by romkatv** [comment]
Thanks for the details. I've filed https://github.com/python/cpython/issues/111501.

Is there anything else I can help with?

**Comment by kmontocam** [comment]
No, thank you ! I might as well have a look at different Virtual Environment clients. I personally use both python3's implementation and [conda](https://www.google.com/search?client=safari&rls=en&q=conda&ie=UTF-8&oe=UTF-8). And conda does not modify `PS1` by default in zsh. I'll let you know if I find something interesting

**Comment by romkatv** [comment]
Modifying PS1 is not the problem. Exporting it is.

**Comment by romkatv** [comment]
Closing as it's not a powerlevel10k problem. It's also unlikely to be a problem for you in practice.
