### ISSUE TITLE
this prompt line have some wrong

### ISSUE THREAD

**Issue by sgfcz** [romkatv/powerlevel10k#2474]
![Uploading image.png…]()
![shot](https://github.com/romkatv/powerlevel10k/assets/43927011/a796061e-a459-4cbe-b501-778b5685d9fd)

like this
this is linux mint + oh my zsh + hack mono font

**Comment by user1689** [comment]
change a font which recommend by official

**Comment by sgfcz** [comment]
> change a font which recommend by official

yeah， I am change font for MesloLGS NF，this‘s same result

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols
