### ISSUE TITLE
Light/Dark Mode on MacOS

### ISSUE THREAD

**Issue by benzwd** [romkatv/powerlevel10k#2475]
Hi,

I use the MacOS terminal with the PowerLevel10k theme but when my Mac switches between the different themes (dark/light) the terminal color does not follow (the original terminal follows the theme according to the defined mode)

Do you know if there is a setting to restore the original behavior ?

Thanks !

**Comment by romkatv** [comment]
The *original behavior* in what sense?

**Comment by TT--** [comment]
I think maybe they mean the ability to auto switch colors based on the system light/dark setting.
(Is it possible?)

**Comment by romkatv** [comment]
Flipping the light/dark setting in the terminal changes the default background and foreground colors. Your prompt will be affected if and only if it uses the default colors. If you are using the builtin p10k configuration wizard, the only style that may be affected by the light/dark switch is *Lean*.
