### ISSUE TITLE
weird display

### ISSUE THREAD

**Issue by 49-3** [romkatv/powerlevel10k#2477]
hi, can we make something to avoid it doing some weird display like this 
![image](https://github.com/romkatv/powerlevel10k/assets/132607493/c0e2e54b-dadc-493a-9a4b-2f0eb6a96108)

it's sometime randomly but it  do all time on terminal resize

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window
