### ISSUE TITLE
Customizing kubecontext further

### ISSUE THREAD

**Issue by kritag** [romkatv/powerlevel10k#2478]
I love the show-on-demand kubecontext and the look and feel of kubecontext in p10k in general. That being said, coming from kube-ps1 it lacks a lot of necessary functions when it comes to customizing what's being displayed.

First of all, with kube-ps1 I'm able to truncate words and have the prompt displayed the way I like with:
![Untitled](https://github.com/romkatv/powerlevel10k/assets/3776749/07bb1c7e-ba49-4126-85fb-079425ca9f2c)

```shell
 function get_cluster_short() {
   echo "$1" | cut -d "/" -f 1,2 | cut -d ":" -f 1 | cut -d "-" -f 1,2,3,4| sed 's/api-//g'
 }
 KUBE_PS1_CLUSTER_FUNCTION=get_cluster_short

``` 
working with ocp, my kubecontext-information would be way too long for comfort. With this I'm going from
![Untitled2](https://github.com/romkatv/powerlevel10k/assets/3776749/b5a2f804-e786-4fd4-9f38-dfe1dff7fae4)

```
foo-name/api-xy-redacted12-redact-com:port/firstname.lastname@email.domain:foo-name
``` 
to
```
foo-name/xy-redacted:foo-name
``` 
I have not been able to do this with anything that powerlevel10k provides, but managing a lot of clusters you kinda need to get rid of superfluous information and keep it simple and consise, so please consider adding some sort of support for tihs.

Secondly, touching on the first sentiment here, having kube-ps1 display different, customizable colors is hugely helpful to reduce clutter and improve visibility. I have yellow for my cluster and cyan for the namespace. As a bonus, for OCP it would be great to be able to change the project as well.

I would rathern ot use kube-ps1 with p10k, and I'd much rather use the built in kubecontext, but as it stands it's missing (or I'm not able to find it in the docs) functionality I consider important.

**Comment by romkatv** [comment]
Powerlevel10k supports all of the customizations you mentioned. I have to admit it can be challenging to use them. If you can give an example of the output of `typeset -pm 'P9K_KUBECONTEXT*'` (replace sensitive bits with placeholders if you must but keep the punctuation intact) and describe what you want to be displayed in the prompt, I'll show you how to achieve that.

**Comment by kritag** [comment]
Here we go:
```shell
❯ typeset -pm 'P9K_KUBECONTEXT*'
typeset P9K_KUBECONTEXT_CLOUD_ZONE=''
typeset P9K_KUBECONTEXT_CLUSTER=api-<actual cluster name>-host-biz:<port number>
typeset P9K_KUBECONTEXT_NAMESPACE=aac-test
typeset P9K_KUBECONTEXT_CLOUD_NAME=''
typeset P9K_KUBECONTEXT_NAME=<OCP project name>/api-<actual cluster name>-host-biz:<port number>/firstname.lastname@company.biz
typeset P9K_KUBECONTEXT_CLOUD_CLUSTER=''
typeset P9K_KUBECONTEXT_CLOUD_ACCOUNT=''
typeset P9K_KUBECONTEXT_USER=firstname.lastname@company.biz/api-<actual cluster name>-host-biz:<port number>
``` 

So what I'm looking for is the prompt showing `<OCP project name>/<actual cluster name>:<namespace>`

`<actual cluster name>` might be foo, foo-bar, foo-bar-baz, etc.
Would be extra nice if different colors can be shown for `<OCP project name>` , `<actual cluster name>` and `<namespace>` , but I would definitely be happy to have `<OCP project name>/<actual cluster name>` and `<namespace>` be different colors.

**Comment by romkatv** [comment]
- `<OCP project name>` in red: `%F{1}${P9K_KUBECONTEXT_NAME%%/*}%f`
- `<actual cluster name>` in green: `%F{2}${${P9K_KUBECONTEXT_CLUSTER#api-}%-*-*:*}%f`
- `<namespace>` in yellow: `%F{3}$P9K_KUBECONTEXT_NAMESPACE%f`.

You can try these things like so:

```zsh
print -Pr -- "%F{1}${P9K_KUBECONTEXT_NAME%%/*}%f"
```

Note that this is all plain zsh. `${var%pattern}` and `${var#pattern}` are even plain POSIX.

Combining all of these:

```zsh
typeset -g POWERLEVEL9K_KUBECONTEXT_CONTENT_EXPANSION='%F{1}${P9K_KUBECONTEXT_NAME%%/*}%f/%F{2}${${P9K_KUBECONTEXT_CLUSTER#api-}%-*-*:*}%f:%F{3}$P9K_KUBECONTEXT_NAMESPACE%f'
```

If you already have some `POWERLEVEL9K_KUBECONTEXT_*_CONTENT_EXPANSION` parameters in `~/.p10k.zsh`, set those as appropriate.

**Comment by romkatv** [comment]
As a bonus, this is over 1000 times faster than `get_cluster_short`.

**Comment by kritag** [comment]
Holy crap, I'm amazed! It works like a charm! Thank you ever so much, this looks so good! :D. Incredibly quick replies too, I'm amazed!

**Comment by romkatv** [comment]
You are very welcome.
