### ISSUE TITLE
Powerlevel10K theme not running in Warp

### ISSUE THREAD

**Issue by Esti-01** [romkatv/powerlevel10k#2479]
I currently use iTerm2 as my default terminal with oh my zsh 'Powerlevel10k' theme, but my friend recommended the Warp terminal as he thinks I would prefer Warp instead of iTerm2 as it is more modernised. 
I have installed Warp, but I have realised that my theme is not showing on this terminal, so I have re-configured p10k. Still, my theme is not showing on the terminal. I have also changed the font in the settings to MesloLGS NF. 
Could someone explain why p10k is working in iTerm2 but not in Warp? 
If there is a solution, I will uninstall iTerm2 and use Warp as my primary terminal.

This is the output I received when I re-configure p10k:
![Warp](https://github.com/romkatv/powerlevel10k/assets/92370451/77592e32-5276-4dab-b060-a7413833c1c1)

**Comment by romkatv** [comment]
Warp has a setting to honor your custom prompt. You need to enable it.

In the future it might make more sense to ask your friend for help with Warp.

**Comment by Esti-01** [comment]
@romkatv Thank you so much. It works now.
