### ISSUE TITLE
Add azure segment

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#248]
See https://github.com/maximbaz/dotfiles/pull/15#discussion_r331985660 by @maximbaz.

Implementation 1: `az account show --query name --output tsv 2>/dev/null`.
Implementation 2: `jq -r '.subscriptions[] | select(.isDefault == true) | .name' $HOME/.azure/azureProfile.json`.

**Comment by romkatv** [comment]
This is done. The new segment is called `azure`. If you run `p10k configure`, you'll see it in your `~/.p10k.zsh` but it's disabled. You'll need to search for `azure` and uncomment the first hit. I'll enable it by default some time later if no one reports any issues with it.

**Comment by romkatv** [comment]
@maximbaz and @ijoseph FYI: see the comment above.

**Comment by maximbaz** [comment]
Works well, could you share why you ended up going for the first implementation? Caching helps, but changing subscriptions is painfully slow as prompt hangs for a few seconds every time p10k decides to execute `az` command.

**Comment by maximbaz** [comment]
Check this out: https://github.com/denysdovhan/spaceship-prompt/pull/740/files

It seems quite powerful, they also use the faster json parsing approach, they check for access token as well (so that the section is only shown when you are actually logged in, this is awesome idea!), and they show something called group (I've never seen those personally).

**Comment by maximbaz** [comment]
I've cleaned up their code a bit (e.g. by properly parsing JWT payload and padding it before decoding), but didn't implement the group as I don't use them so not sure if my implementation will be correct (and if we need it at all).

I'm sure you can convert this to a fancier syntax including all perf optimizations, but hope this helps anyway:

```zsh
function prompt_azure() {
    local jwt_payload="$(cat "$HOME/.azure/accessTokens.json" | jq -r '. | sort_by(.expiresOn) | reverse | .[0].accessToken' | cut -d '.' -f 2)"
    local len=$((${#jwt_payload} % 4))
    if [ $len -eq 2 ]; then jwt_payload+='=='
    elif [ $len -eq 3 ]; then jwt_payload+='='
    fi

    local access_token_expiry="$(echo "$jwt_payload" | tr '_-' '/+' | base64 --decode | jq -r '.exp')"
    if [[ $(date +"%s") -gt "$access_token_expiry" ]]; then
        return
    fi

    local val="$(jq -r '.subscriptions[] | select(.isDefault == true) | .name' "$HOME/.azure/azureProfile.json")"
    p10k segment -f 208 -t "$val"
}
```

**Comment by romkatv** [comment]
Just wanted to let you know that I've seen your questions and pointers (much appreciated!). I'll need a bit more time to figure out a proper reply. I'm reading the code of azure-cli and implementing something in p10k but it's not finished yet. From what I can tell, your implementation is indeed more correct than the one in the Spaceship PR but it's still not quite right. I'll post more in the next few days. Reopening the issue.

**Comment by romkatv** [comment]
Need your expert help to figure out a few things as I don't use azure myself.

> changing subscriptions is painfully slow as prompt hangs for a few seconds every time p10k decides to execute `az` command

I rolled out a different kind of caching across all p10k sections but I'm not sure it'll work with your workflow. How do you change subscriptions and how many of them do you have?

> they check for access token as well (so that the section is only shown when you are actually logged in, this is awesome idea!)

I see that the Spaceship PR hides azure section if all access tokens are expired, and I also see that you think it's an awesome idea. This means it **must** be a good idea but I cannot figure out why. Can you describe what you do with azure that makes this part of the code desirable? That is, how do you end up in a situation where:

1. `az account show --query name --output tsv` succeeds and prints something.
2. All access tokens in `~/.azure/accessTokens.json` are expired.
3. You don't want to see azure section.

Also, could you say why you don't want to see azure section? Is it because some `az` commands in this state fail or work differently than when you have active access tokens? If so, which commands are those and how is their behavior affected by the presence or absence of active access tokens?

Here's what I've tried.

1. Type `az login` and login in the browser window that opens with my personal Microsoft account.
2. Verify that there are active tokens in `~/.azure/accessTokens.json`. Their expiration is one hour in the future.
3. Wait for one hour.

In this state `az account show --query name --output tsv` succeeds and prints something, and all access tokens in `~/.azure/accessTokens.json` are expired. However, all `az` commands still behave as before. The ones that need an access token simply generate a new one from the refresh token, which never expires.

It seems like access tokens are an implementation detail. The existence or absence of active access tokens is not externally observable -- `az` behaves identically. If this is so, then it's unclear why prompt should look any different depending on the absence or presence of active access tokens. What am I missing?

Another things I've tried is to logout with `az logout`. This makes `az account show --query name --output tsv` return an error and print nothing to stderr. I conclude that an implementation of azure prompt that always prints the output of this command without looking at access tokens *will not* display azure subscription when logged out. This contradicts your statement that checking for access token is needed "so that the section is only shown when you are actually logged in".

I must be missing something. Maybe it's related to different kinds of accounts? Or authentication with certificates vs passwords?

**Comment by maximbaz** [comment]
> I rolled out a different kind of caching across all p10k sections but I'm not sure it'll work with your workflow. How do you change subscriptions and how many of them do you have?

I have around 10. I change them quite often using `az account set --subscription <name>` command, and of course after that p10k has to refresh its cache and display the new subscription name in the prompt, and this needs to be fast 🙂 

> I see that the Spaceship PR hides azure section if all access tokens are expired, and I also see that you think it's an awesome idea. This means it **must** be a good idea but I cannot figure out why. 

Oh it's simply to prevent cluttering the prompt! The majority of sections are context specific (e.g. virtualenv version is shown only when you are in the context of the python project you are working on, terraform workspace is shown only when you are in the context of a specific infra work, etc), but azure prompt is global and so it stays in the prompt forever, even if you are not working on azure right now.

I think it's a neat feature simply from this perspective, the Azure context will be shown if you have been working with Azure within the past hour (and during this time you do want to see the azure subscription); but as soon as you stopped executing `az`, token is not being refreshed anymore and therefore the segment becomes hidden because you don't need this information anymore.

Personally, I have two such segments that stay in my view at all times for no good reason, `azure` and `kubecontext` segment, I would really love to adapt kubecontext to also get hidden if I haven't been using `kubectl` commands for some time (but that's a story for another time I guess).

> In this state `az account show --query name --output tsv` succeeds and prints something, and all access tokens in `~/.azure/accessTokens.json` are expired. However, all `az` commands still behave as before. The ones that need an access token simply generate a new one from the refresh token, which never expires.

This depends on your security configuration, I think what you see (login once and you have access forever thanks to refresh tokens) is probably the standard behavior, but it's not how real-world subscriptions are configured (at least at my job). For me, once the token expires, I will not be able to do anything until I run `az login` again, even though my token was refreshed (notice the `azure` segment is shown, but I'm getting an error). But unfortunately I don't think we can determine if I have access to run `az` commands or not, I think the error is being thrown by Azure servers.

![image](https://user-images.githubusercontent.com/1177900/66641404-fb3e9c00-ec1a-11e9-9839-9d73c2e8d6b3.png)


So (at least in my view), the check for `accessTokens.json` file is really not to determine if you have access or not, but rather to just unclutter the prompt.

**Comment by romkatv** [comment]
Thanks for the explanation.

It seems that making prompt content depend on the status of access tokens isn't exactly what you want. You want the prompt to get hidden if you haven't been using `az` for some time. Maybe for an hour, or maybe for 30 minutes. If Microsoft (or your org) changes `az` so that TTL on tokens becomes 7d rather than 1h, you still would want azure to disappear from your prompt after a shorter period of time. Correct?

What do you think of the following UX?

1. If you don't use `az` for `T` seconds (configurable), azure prompt disappears.
2. When you start typing an `az` command, azure prompt appears (before you even press enter).
3. You can also type `p10k hide az` to manually remove azure prompt without waiting for `T` seconds.

`kubecontext` can work the same way, with `kubectl` replacing `az`.

This logic assumes that you "use" azure only via `az` command. Is this correct? In other words, is it correct that the last `az` command constitutes the last use of azure and therefore azure prompt should be hidden after `T` since the last `az` command?

Alternatively, what do you think about showing azure prompt only while you are typing an `az` command? Is it better or worse?

**Comment by maximbaz** [comment]
> It seems that making prompt content depend on the status of access tokens isn't exactly what you want. You want the prompt to get hidden if you haven't been using az for some time. Maybe for an hour, or maybe for 30 minutes. If Microsoft (or your org) changes az so that TTL on tokens becomes 7d rather than 1h, you still would want azure to disappear from your prompt after a shorter period of time. Correct?

You are absolutely correct! I saw a specific solution that only works for `az`, but you are looking for a proper generic solution that can be applied to similar cases like `kubecontext`.

> What do you think of the following UX? ...

What you describe sounds ideal 👍 

> This logic assumes that you "use" azure only via az command. Is this correct?

Mmmm now that I'm thinking about it, the answer is "no". For example, when I use `terraform` to create some azure resources, it internally uses `az` (or maybe even parses files directly) to know to which subscription to deploy to. For `kubecontext` there are also multiple commands (the most famous would probably be `kubectl` and `helm`). Maybe it's just a matter of making the list of commands configurable...?

Also, would it work for aliases? Say I created an alias `al` to run `azure storage account list`, will you be able to detect that I've just executed `az`?

> Alternatively, what do you think about showing azure prompt only while you are typing an az command? Is it better or worse?

I have an impression that there are examples when this will not be desired but I can't think of one at the moment. We can certainly start with it, if it's simpler to implement than the approach with `T` seconds, and I will be able to give you feedback after I use it for a bit.

**Comment by romkatv** [comment]
> Also, would it work for aliases?

Yes, aliases will work out of the box. Other commands using azure might pose a problem.

Maybe the maximum access time among `~/.azure/**` would be a good proxy for the last time azure was used? Want to give it a try and report how well (or badly) it works for you?

1. Update powerlevel10k to the latest version.
2. Enable `azure` prompt.
3. Add this to your config:

```zsh
function azure_last_use_time() {
  emulate -L zsh
  local -a files=(${AZURE_CONFIG_DIR:-$HOME/.azure}/**(N))
  (( $#files )) || return 0
  local atime=()
  zstat -A atime +atime -- $files 2>/dev/null || return 0
  return ${${(n)atime}[-1]}
}

functions -M azure_last_use_time 2>/dev/null

typeset -g POWERLEVEL9K_AZURE_CONTENT_EXPANSION='${${$((EPOCHREALTIME-azure_last_use_time()>300)):#1}:+$P9K_CONTENT}'
typeset -g POWERLEVEL9K_AZURE_VISUAL_IDENTIFIER_EXPANSION=${POWERLEVEL9K_AZURE_CONTENT_EXPANSION/CONTENT/VISUAL_IDENTIFIER}
```

You can also manually type `azure_last_use_time; echo $?` to check which commands update access time and which don't.

> We can certainly start with [showing prompt only while a relevant command is being typed]...

If you want to give it a try, see this gist: https://gist.github.com/romkatv/33f02f42245967072f8d00fc1db0f7fc. Run this code after defining your `POWERLEVEL9K` parameters (e.g., at the bottom of your p10k config). It'll make `kubecontext` appear when and only when you are typing a `kubectl` command or an alias for it.

Perhaps you can use this approach with kubernetes and the other approach (mentioned above) with azure and see which one you like best? I'll be eagerly awaiting for your experience report.

P.S.

I really appreciate your help with this. UX design is difficult and time consuming but the rewards of getting it right are sweet.

**Comment by maximbaz** [comment]
> Maybe the maximum access time among ~/.azure/** would be a good proxy for the last time azure was used? Want to give it a try and report how well (or badly) it works for you?

Nice idea, but I know for sure many people mount their file systems with `noatime` to disable access time for performance reasons, see for example [here](https://gms.tf/btrfs-requires-noatime.html). I use btrfs and I also have access time disabled (because basically every guide online tells you to do so), and so for me `azure_last_use_time; echo $?` returns a timestamp of something in April.

Should we try the approach of providing a list of executables that should trigger showing `azure` segment for the next `N` seconds? For `azure` I would simply configure `az` and `terraform`, at least for the moment I can't recall any other binary.

> If you want to give it a try, see this gist: https://gist.github.com/romkatv/33f02f42245967072f8d00fc1db0f7fc. Run this code after defining your POWERLEVEL9K parameters (e.g., at the bottom of your p10k config). It'll make kubecontext appear when and only when you are typing a kubectl command or an alias for it.

Oh wow, I can see you have also been thinking about how to hide `kubecontext` segment when you don't need it! 😄 

It works, but has a slight issue, I dont think it traverses aliases recursively. For example:

```
alias k='kubectl'
alias kg='k get'
alias kgp='kg pod'
```

The segment shows up when I type `k` or `kubectl`, but doesn't show up when I type `kg` or `kgp`. Is it something you know how to easily fix?

**Comment by maximbaz** [comment]
To be fair so far there was not a single time when I felt pain because of the lack of support for recording access time; it is also very possible that access time is buggy in btrfs and that is the primary reason for this being mentioned in all the guides 🙂 

> Maybe a combination of things will work. p10k will consider azure used when any of the following happens: ...

I feel the answer depends on whether you want a generic solution or something specific to azure. 

If you consider `azure` specifically, modification time alone is probably sufficient, it's sort of what spaceship PR is doing, any call to `az` (and most probably `terraform` when it talks to Azure) will result in refreshing access token (and therefore file modification), so access time and `az` command used is already included in the "modification time" check.

If you want a generic solution that for example can be reused in `kubecontext`, modification time will not help (as far as I can see nothing is being modified when you run `kubectl get pod`), and to cover the majority environments the best approach is probably to just watch for a certain command to be used (e.g. `az`).

> Fixed.

You know, I'm playing with your gist and it actually feels very pleasant; I wonder if you were right from the start and all that's really necessary is to show azure subscription when we type `az` (or `terraform` in my case). And then we don't need to overload every segment with some specific show/hide code, but instead we will have a single generic solution for these kinds of segments.

What do you think about this? About integrating your gist in the p10k itself, so that I would "turn it on" for specific segments with something like this:

```
typeset -g POWERLEVEL9K_AZURE_SHOW_WHEN=az,terraform
typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_WHEN=kubectl,helm
```

You are right about "terraform doesnt always use azure", but I feel it's a decent approach nonetheless (after all, we are making a significant improvement of how many times `azure` segment is shown when it is not really needed).

**Comment by romkatv** [comment]
> To be fair so far there was not a single time when I felt pain because of the lack of support for recording access time.

Maybe you never used access time in your day-to-day activities and therefore you don't think of it when you need to do something?

Here's an example where I use it often. I read source code of some large project checked out to my local disk. Then later I want to find the same file I was reading. I vaguely remember something about its content but it's not enough to find it. By restricting my search to files accessed in the last week I can easily find it.

Would such a solution occur to you if were in the same situation?

I'm not saying that p10k won't support users who disable atime. It should. My tangent about the usefulness of atime doesn't inform the decisions w.r.t. p10k implementation. I suggest that we drop it.

> If you consider `azure` specifically, modification time alone is probably sufficient, it's sort of what spaceship PR is doing

That PR looks confused though. The code is looking at token expiration, which we've agreed isn't the right thing to do, and it's doing it incorrectly.

> any call to `az` (and most probably `terraform` when it talks to Azure) will result in refreshing access token (and therefore file modification), so access time and `az` command used is already included in the "modification time" check.

That's a good observation!

On my system access token doesn't get refreshed until it expires but mtime of `~/.azure/commands` changes! Thus, replacing `atime` with `mtime` in `azure_last_use_time` has a good chance of working in practice.

> If you want a generic solution that for example can be reused in `kubecontext`, modification time will not help (as far as I can see nothing is being modified when you run `kubectl get pod`), and to cover the majority environments the best approach is probably to just watch for a certain command to be used (e.g. `az`).

I did propose a generic solution, yes. So far we've discovered that it will likely work correctly with azure (even for users who disable atime). I suppose you are saying that it will also work for kubernetes?

I'll highlight the important point in the algorithm I proposed: "p10k will consider azure used when **any** of the following happens..."

> You know, I'm playing with your gist and it actually feels very pleasant; I wonder if you were right from the start and all that's really necessary is to show azure subscription when we type `az` (or `terraform` in my case).

I don't think I said that.

It seems obvious that while you are typing an `az` command (naturally, this is configurable, but the default is just `az`) azure prompt should be visible.

The question is whether azure should stay visible after you execute the command. And if yes, then when should it get hidden? This seems like a good place for another parameter.

So we end up with two parameters.

- `AZURE_COMMAND` -- a pattern for azure commands.
- `AZURE_LINGER_SECONDS` -- for how long azure should be visible after the last use.

Azure prompt is shown if the current command matches `AZURE_COMMAND` or if azure was last used less than `AZURE_LINGER_SECONDS` seconds ago.

Azure is considered used when atime or mtime of anything under `~/.azure` changes, or when a command matching `AZURE_COMMAND` succeeds.

Here are some interesting combinations of the parameters:

- `AZURE_COMMAND="" AZURE_LINGER_SECONDS=infinity`. This is the current implementation in p10k. It's nice that parameters allow for backward compatibility.
- `AZURE_COMMAND="(az|*/az)" AZURE_LINGER_SECONDS=0`. This is the way `kubecontext` behaves with the code from my gist.
- `AZURE_COMMAND="" AZURE_LINGER_SECONDS=3600`. This is sort of what that Spaceship PR does, but better.

Note that the same algorithm and the same parameters can work with kubernetes.

The p10k config for new users will set `AZURE_COMMAND="(az|*/az)"`. What should `AZURE_LINGER_SECONDS` be? Infinity is the most backward compatible, while zero is also a viable option. Anything in between will confuse users, I'm afraid. Users will have hard time figuring out that azure prompt disappears 1h after last use.

Sorry for the verbiage and rambling...

WDYT?

**Comment by maximbaz** [comment]
I like this 🙂 

A short answer is: if `AZURE_COMMAND` and `AZURE_LINGER_SECONDS` are implemented (and presumably the same for `KUBECONTEXT_`), this would allow for all possible combinations and satisfy everyone (me for sure! 😄).

I'd only question one thing, do you want to implement this part: "Azure is considered used when atime or mtime of anything under ~/.azure changes". It won't hurt and _maybe_ would benefit the segment, but it's something that is specific to azure and will not be reused in other segments directly.

I recommend going for `AZURE_COMMAND="(az|*/az)" AZURE_LINGER_SECONDS=infinity` as the default, it will be the less confusing option for everyone who has not been following this thread.

-----

Been using the gist during this time, there's one other slightly annoying issue: it breaks `zsh-syntax-highlighting` a bit. Compare:

Without gist (red until command doesn't exist, green once I finished typing "echo"):

![before](https://user-images.githubusercontent.com/1177900/66658115-191ef780-ec41-11e9-9f10-b5ad838f8f20.gif)


And this is with gist applied:

![after](https://user-images.githubusercontent.com/1177900/66658131-21773280-ec41-11e9-867b-8f2aba552c77.gif)

**Comment by romkatv** [comment]
> I'd only question one thing, do you want to implement this part: "Azure is considered used when atime or mtime of anything under ~/.azure changes".

I think so. Without it `LINGER` with non-zero and non-infinite value works badly.

What I like about looking at `~/.azure` changes is that it doesn't require any configuration on the part of users. If they want to see azure 1h after last use, the only thing they need to specify is "1h", which is a purely UI preference rather than a techical parameter. `COMMAND` parameter is certainly expert-only. Almost no one will set it manually.

> It won't hurt and _maybe_ would benefit the segment, but it's something that is specific to azure and will not be reused in other segments directly.

p10k has to have some azure-specific code, right? I mean, there should be `prompt_azure()` function. It already has to know about the location of azure internal files to implement caching.

Anyway, I'll sleep on it. Thanks for your feedback!

> I recommend going for `AZURE_COMMAND="(az|*/az)" AZURE_LINGER_SECONDS=infinity` as the default, it will be the less confusing option for everyone who has not been following this thread.

Sounds reasonable. I also can add a question in the wizard to choose between zero and infinity if I see that kubernetes or azure are installed.

> Been using the gist during this time, there's one other slightly annoying issue: it breaks `zsh-syntax-highlighting` a bit.

This looks like https://github.com/zsh-users/zsh/commit/c5519372808d78519e1bac2db165d19a34534f74. I submitted in April but there hasn't been a release of zsh yet. Build zsh from HEAD if you care.

You can verify that it's indeed this bug by starting zsh without my gist, typing `ech`, hitting esc-x and then typing `reset-prompt`. If the color of `ech` changes, it's indeed this bug that trips syntax highlighting.

**Comment by maximbaz** [comment]
> This looks like zsh-users/zsh@c551937. I submitted in April but there hasn't been a release of zsh yet. Build zsh from HEAD if you care.

Just built and installed zsh from HEAD, sadly still reproduces 😞 

Typing `esc-x` and then `reset-prompt` at any point of time fixes the colors indeed.

**Comment by romkatv** [comment]
> Just built and installed zsh from HEAD, sadly still reproduces 

Doesn't reproduce for me. Might be related to the order in which widgets are wrapped, or how many times.

Just to be on the safe side, `$ZSH_PATCHLEVEL` confirms you are using a locally built `zsh`?

> Typing `esc-x` and then `reset-prompt` at any point of time fixes the colors indeed.

Could you clarify? What I was suggesting is that `reset-prompt` would turn the color from red to grey if you aren't using my gist. You are experiencing something else, right? What is it? When does `reset-prompt` changes the color of `BUFFER` and from which to which?

**Comment by maximbaz** [comment]
```
❯ echo $ZSH_PATCHLEVEL
zsh-5.7.1-142-g72c6dbe
```

Without the gist `reset-prompt` has no effect: 
- I type "ech", it is red, and when I run `reset-prompt` it stays red.
- I type "echo", it is green, and when I run `reset-prompt` it stays green.

With the gist `reset-prompt` fixes the colors:
- I type "ech", it is white, and when I run `reset-prompt` it becomes red.
- I type "echo", it is white, and when I run `reset-prompt` it becomes green.

**Comment by romkatv** [comment]
Thanks for the info. I'll need to reproduce this locally and find a fix/workaround.

**Comment by maximbaz** [comment]
I confirm that I don't reproduce this with the minimal .zshrc as below:

```
source /tmp/colors-bug/powerlevel10k/powerlevel10k.zsh-theme
source /tmp/colors-bug/p10k-transient-kubecontext.zsh
source /tmp/colors-bug/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  kubecontext
  newline
  prompt_char
)
```

I will bisect and find the minimal config to reproduce and get back to you (in a separate ticket perhaps, not to steer focus away from `azure` segment).

**Comment by romkatv** [comment]
This has been finished long time ago.
