### ISSUE TITLE
Wrong `upwards arrow` in installation prompt (3rd question)

### ISSUE THREAD

**Issue by AustralEpitech** [romkatv/powerlevel10k#2481]
I checked with multiple fonts, the character displayed is not the [upwards arrow](https://graphemica.com/%F0%9F%A0%89) `🠉` but the [arabic ligature qaf with alef maksura isolated form](https://graphemica.com/%EF%B0%B5) `ﰵ`.  
The URL displayed as reference is good though.  
Strangely, the page favicon is actually an arrow?

**Comment by AustralEpitech** [comment]
I'm not sure I understand. The character _is_ not an arrow. Are there any fonts that draw it as an arrow? Because even the fonts recommended in the README don't.
Is it intentional and you are supposed to answer no to the question? If that's the case, I would suggest specifying it or reversing the question so that you answer "yes" like the rest of the questions.

**Comment by romkatv** [comment]
The question has two answers: yes and no. You need to choose the right one. If you do, things will work. Please give it a try.

If I reverse the question so that the answer becomes *Yes* for you, it may become *No* for somebody else. Besides, if you prefer to answer all questions with *Yes*, I can imagine other people preferring *No* instead. It's just so much easier if you answer *Yes* or *No* depending on what the question asks.

**Comment by AustralEpitech** [comment]
I don't care if I have to answer no. My problem is when you have to even with the recommended setup. But I guess it's just personal preference
For the arrow, if I click on the link, I get an arrow. If on the same site, I copy-paste the character from my terminal, I get a different result (the arabic ligature). So there is a mistake either in the link or in the character?
character : ﰵ
link : https://graphemica.com/%F0%9F%A0%89

**Comment by romkatv** [comment]
The screen shows you *something* and asks whether it looks like an *upward arrow*. If you don't know how an *upward arrow* is supposed to look, you can click the link. What you see in there is the *upward arrow*. Does your terminal display the same thing or not? Answer yes or no.

Is there a way to make this question clearer?

P.S.

With the recommended font the answer is yes. You are using a different font at least for this specific glyph. That's OK, powerlevel10k works with all fonts.

**Comment by AustralEpitech** [comment]
My mistake, I made a mistake in the config of my terminal. Thank for your answers and your patience.
