### ISSUE TITLE
For git, show only nearest git root + sub-paths, not entire path

### ISSUE THREAD

**Issue by johnmanko** [romkatv/powerlevel10k#2482]
I'm not sure if this requires a change to p10k, so here is goes...

I'd like p10k to halt display of parent paths if it hits a git directory.  For instance, assume the following paths:

1. `~/Documents/development/docs/manuals/specs` (no git in this path)
2. `~/Documents/development/projects/my-project/src/app` (nearest git is `my-project`)

For path 1, the prompt should show the entire path since nowhere in the path is there a git directory.

For path 2, p10k should strip `~/Documents/development/projects/` once it sees that `my-project` is a git project, and only display: `my-project/src/app`.

Is this possible now?  If not, can it be implemented?

**Comment by romkatv** [comment]
Search for "POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER" within `~/.p10k.zsh`. Does that do what you want?

**Comment by johnmanko** [comment]
@romkatv That's perfect!  Thanks!
