### ISSUE TITLE
[Need Help]The right prompt disappered if the left prompt and right prompt are too long.

### ISSUE THREAD

**Issue by shenmishajing** [romkatv/powerlevel10k#2485]
<img width="1433" alt="Screenshot 2023-11-14 at 20 59 24" src="https://github.com/romkatv/powerlevel10k/assets/32559715/5af7eb87-2d80-4e87-b1ca-c4d9535571db">
Is there any solution to make them display in two lines, instead of removing the right prompt?

**Comment by romkatv** [comment]
No, that's not possible.

To save some horizontal space I recommend that you run `p10k configure` and choose Lean style without the clock.

**Comment by shenmishajing** [comment]
Ok, it's disappointing. I will try the Lean style, but will we support this?

**Comment by shenmishajing** [comment]
Ok, I got it. Thanks for your reply. I avoid missing the conda info by moving it from the right prompt to the left prompt.
