### ISSUE TITLE
Fingerprint Dialog appears after promt instead of before in iTerm2

### ISSUE THREAD

**Issue by 155martinmoreno** [romkatv/powerlevel10k#2486]
Hi! 
first off, thanks for your project. 
I'm new to it, but it looks great so far.

I've setup Mac's Touch ID sensor to enable sudo access on the terminal following [this guide](https://dev.to/equiman/how-to-use-macos-s-touch-id-on-terminal-5fhg), and it works great until I install powerlevel10k.

The expected behavior is that after typing `sudo ls` I see the Touch ID dialog.

But what actually happens is that I see the password prompt *first*, and the dialog only *after*.

You can check the video of the behavior:
(you'll see the user/password dialog instead of fingerprint cos biometrics is disabled when recording the screen)

https://github.com/romkatv/powerlevel10k/assets/8753819/ebf7d2ac-ff00-4642-b885-e1511ec29a35

Interestingly, it does not matter if I enter the password correctly or not on the prompt, it shows the dialog anyway.

Am I missing any configuration?

Thanks

**Comment by romkatv** [comment]
Try disabling powerlevel10k without make any other changes to your zsh configs. Does this fix the problem?

**Comment by 155martinmoreno** [comment]
You are absolutely right, and it's **not** related. Sorry for that.

For the curious ones:
It turns out Apple rolled out a minor OS update that rolled back the `/etc/pam.d/sudo` to the original, and I added the needed line in the wrong order (last instead of first).

Thanks again.
