### ISSUE TITLE
How to hide icon from execution_timer

### ISSUE THREAD

**Issue by ciscohack** [romkatv/powerlevel10k#2489]
Hi Roman,

I need your help to hide the icons in front of execution time. Can you please point me the option to achieve the task

<img width="230" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/72fa9ae9-4e16-476a-881d-0f9f42ace08c">

**Comment by romkatv** [comment]
1. Open `~/.p10k.zsh`.
2. Search for `POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION`.
3. Uncomment the parameter and set its value to `''` (empty).
4. Save your changes and restart zsh with `exec zsh`.

You can change icons for all segments in the same manner.
