### ISSUE TITLE
My aliases desapear after last update on p10k

### ISSUE THREAD

**Issue by hugoeustaquio** [romkatv/powerlevel10k#249]
I know this isn't a tech support, but I wold be grateful if some of you can help me.

I'm using this plugin for some time, via antibody. On my last update I noticed that all my aliases was gone. So I started commenting one by one on my config, and I found that if I disable powerlevel10k everything works fine.

So I'm wondering what can I do... As you can see on the image above I have my aliases defined and it doesn't work. If I disable powerlevel it work as it should. But I'd like to keep using both my aliases and p10k.

Any ideas?
![img_error_p10k](https://user-images.githubusercontent.com/8718536/66321473-016d0980-e8f7-11e9-81fd-26fae6f1b7da.png)

**Comment by romkatv** [comment]
Could you update powerlevel10k to the latest version and try again? And delete antibody cache if it has one. There was a bug that I've fixed a few days ago.

**Comment by hugoeustaquio** [comment]
Thanks, its working like a charm!

**Comment by romkatv** [comment]
> Thanks, its working like a charm!

Thanks for the confirmation. My apologies for breaking aliases in the first place.
