### ISSUE TITLE
sudo -E zsh steals ownership of my ~/.gitconfig ?

### ISSUE THREAD

**Issue by iago-lito** [romkatv/powerlevel10k#2491]
I am trying `sudo -E zsh` to check whether p10k prompt is correctly showing out as root with a red context. It does work as expected, except that my `~/.gitconfig` becomes owned by root then. Is that expected? How to avoid it?

**Comment by iago-lito** [comment]
Oops, the same happens indeed. Sorry. Maybe I should move this to oh-m-zsh?

**Comment by romkatv** [comment]
It's a good idea to verify that disabling oh-my-zsh makes a difference.

**Comment by romkatv** [comment]
When you run `sudo -E zsh`, the shell you see if running as root but the home directory is still your regular home directory. Any file you create in the home directory will be owned by root. This is working as intended.

The solution that professionals usually employ is to never run an interactive shell as root. Only run non-interactive individual commands as root.

**Comment by iago-lito** [comment]
> Any file you create in the home directory will be owned by root. This is working as intended.

Well, the file `~/.gitconfig` already exists and is owned by me (as a regular user) *before* I actually run `sudo -E zsh`. The problem is that it becomes owned by `root` after the command (without actually being modified).

> The solution that professionals usually employ is to never run an interactive shell as root. Only run non-interactive individual commands as root.

Although I do understand this, it does not explain that [this sort of feature](https://github.com/romkatv/powerlevel10k/blob/174ce9bf0166c657404a21f4dc9608da935f7325/config/p10k-pure.zsh#L100) is even available, does it? ^ ^"

**Comment by iago-lito** [comment]
I suspect it has to see with the `git` plugin, although I'm not confident enough how all this work to prove it yet..

**Comment by romkatv** [comment]
> Well, the file `~/.gitconfig` already exists and is owned by me (as a regular user) _before_ I actually run `sudo -E zsh`. The problem is that it becomes owned by `root` after the command (without actually being modified).

Something in your zsh startup files does it. You can verify this by running `sudo zsh -E zsh -f`. This will start zsh without evaluating any startup files.

> Although I do understand this, it does not explain that [this sort of feature](https://github.com/romkatv/powerlevel10k/blob/174ce9bf0166c657404a21f4dc9608da935f7325/config/p10k-pure.zsh#L100) is even available, does it? ^ ^"

Running an interactive shell as root and `/root` as the home directory isn't nearly as problematic as what you are doing. Besides, the job of powerlevel10k is to tell you what the shell environment *is*, not to judge it.

**Comment by iago-lito** [comment]
> start zsh without evaluating any startup files

Indeed, I can confirm that `sudo -E zsh -f` does not steal the ownership of my `.gitconfig`. Thank you. I can try to narrow this down now :)

> the job of powerlevel10k is to tell you what the shell environment is, not to judge it.

Very true ;)

> Running an interactive shell as root and `/root` as the home directory isn't nearly as problematic

Oh, I think understand that. Are you suggesting that I should rather configure `/root/.zshrc` ? Like, installing oh-my-zsh as root and running `p10k configure` as root? Then I would just `sudo su` instead of `sudo -E zsh`?

**Comment by romkatv** [comment]
The most conventional approach to this problem by professionals is to never run an interactive shell as root. It's just an all around dangerous thing to do. It's also a good idea to avoid modifying any startup files under `/root` or to change the login shell of root (except maybe setting it to `/bin/false` or something).

**Comment by iago-lito** [comment]
Okay. Thank you for clearing things up :)

**Comment by romkatv** [comment]
Sure thing.
