### ISSUE TITLE
git plugin ignoring global excludes

### ISSUE THREAD

**Issue by wbrefvem** [romkatv/powerlevel10k#2492]
I've tried this with my global gitignore in a few places with no luck. The plugin <i>does</i> seem to respect the local gitignore.

Steps reproduce:
1. Initialize git repo
2. Create file
3. Write file name to some global gitignore file, e.g. `~/.gitignore`
4. Make sure global gitignore is configured explictly with `git config --global core.excludesfile /path/to/gitignore`
5. Run git status to see that git is ignoring
Result: there should be `?1` in the git portion of the terminal prompt.

System info:
```
// Git
$ git version
git version 2.39.3 (Apple Git-145)

// OS
$ sw_vers
ProductName:		macOS
ProductVersion:		14.1.1
BuildVersion:		        23B81

// powerlevel10k, installed at ~/.oh-my-zsh/custom/themes/powerlevel10k
$ git rev-parse --short HEAD 
174ce9b
```

**Comment by romkatv** [comment]
Does the issue go away if you restart your terminal or restart zsh with `exec zsh`?

**Comment by wbrefvem** [comment]
> Does the issue go away if you restart your terminal or restart zsh with `exec zsh`?

Yes, it appears to go away in a new Terminal. In fact, I can no longer reproduce it. I'm not quite sure what's going on. I'm using a new laptop and still getting my dev env set up, so there may be some weirdness on my end causing this.

**Comment by romkatv** [comment]
I'm glad that it works now.
