### ISSUE TITLE
Corners appearing weird if set as rounded

### ISSUE THREAD

**Issue by xplosionmind** [romkatv/powerlevel10k#2494]
I am using SpaceMono Nerd Font Regular, and [this](https://paste.yunohost.org/raw/necemehufi) is my `.p10k.zsh` configuration file.

As you can see at the bottom of this screenshot, the corners appear weird, even if during setup I set them to be rounded.

![Screenshot from 2023-11-24 08-09-55](https://github.com/romkatv/powerlevel10k/assets/42862428/509748fb-f7dc-470d-893f-e03aaa5d02ec)

**Comment by romkatv** [comment]
Please run `p10k configure` and send a screenshot of your terminal when the wizard is asking "Do all these icons fit between the crosses?" You can quit the wizard afterwards to avoid changing `~/.p10k.zsh`.

**Comment by xplosionmind** [comment]
Thanks a lot for your quick reply, @romkatv!

> "Do all these icons fit between the crosses?"

They do not:

![Screenshot from 2023-11-24 08-41-06](https://github.com/romkatv/powerlevel10k/assets/42862428/a1b3f06b-ed44-464d-abf7-b55357dcaf77)

Also worth noting:

![Screenshot from 2023-11-24 08-41-20](https://github.com/romkatv/powerlevel10k/assets/42862428/04863378-b556-4c39-b013-dced1a21e6e0)

**Comment by romkatv** [comment]
Thanks for the confirmation. Both of these screens look as expected.

I think your terminal has built-in support for rendering powerline glyphs, which the wizard does not expect. I'll probably need to add more questions to the wizard to detect this. For now you can do the following:

1. Open `~/.p10k.zsh` in a text editor.
2. Find these lines:
   ```zsh
   # The left end of left prompt.
   typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0BA '
   # The right end of right prompt.
   typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0BC '
   ```
3. Replace them with these lines:
   ```zsh
   # The left end of left prompt.
   typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0BA '
   # The right end of right prompt.
   typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0BC '
   ```
   This change removes trailing spaces from the values of the two parameters.
4. Save the file and restart zsh with `exec zsh`.

**Comment by xplosionmind** [comment]
It is perfect now, thanks a lot @romkatv ❤️
