### ISSUE TITLE
icons are not showing for Powerline fonts except MesloLGS NF

### ISSUE THREAD

**Issue by NishayKumar** [romkatv/powerlevel10k#2496]
<img width="1078" alt="Screenshot 2023-11-28 at 1 14 24 AM" src="https://github.com/romkatv/powerlevel10k/assets/114150640/fa7a41ba-ff2f-4616-b353-594a719f61ba">
<img width="1093" alt="Screenshot 2023-11-28 at 1 14 34 AM" src="https://github.com/romkatv/powerlevel10k/assets/114150640/fd66b52e-fb28-4696-81de-9fe45a4d67a5">
<img width="1076" alt="Screenshot 2023-11-28 at 1 15 48 AM" src="https://github.com/romkatv/powerlevel10k/assets/114150640/346acb42-637f-426f-b319-fe4f5015abc9">

**Comment by NishayKumar** [comment]
After running the command the icons are removed. Does the icons only work for "MesloLGS NF" font?

**Comment by romkatv** [comment]
The icons come from your font. If the terminal used by your font does not have icons, they cannot be displayed in the terminal.

If you want to try different fonts with icons, check out https://www.nerdfonts.com/. Remember to run `p10k configure` after changing fonts. When minor issue in other fonts become tiring, switch back to "MesloLGS NF" and forget about this phase of your life.
