### ISSUE TITLE
Add variables for my_git_formatter() so implementation doesn't need to be changed

### ISSUE THREAD

**Issue by kulack** [romkatv/powerlevel10k#2499]
Thanks for reading!

I'd love it if there could be variables for my_git_formatter() function in .p10.zsh so that we can re-run p10 configure repeatedly and have the config for git colors separate from the implementation of the my_git_formatter() method so it wouldn't be replaced.

In https://github.com/romkatv/powerlevel10k/issues/519 it seemed like no changes were desired and there was an excellent work around there and the my_git_formatter() function hasn't changed for a long time, so it seems unlikely that this issue will be worth changing.

I would propose that using variables instead of depending on the implementation of my_git_formatter might be a bit better than that work around.

If the default p10k was something like this (I ignored any issues of POWERLEVEL9K compatibility in this patch) it might make it a bit easier to set the variables external to the p10k file

Thanks again for reading!

```
diff --git a/config/p10k-lean.zsh b/config/p10k-lean.zsh
index 7cb97e9..4841719 100644
--- a/config/p10k-lean.zsh
+++ b/config/p10k-lean.zsh
@@ -367,17 +367,17 @@
     if (( $1 )); then
       # Styling for up-to-date Git status.
       local       meta='%f'     # default foreground
-      local      clean='%76F'   # green foreground
-      local   modified='%178F'  # yellow foreground
-      local  untracked='%39F'   # blue foreground
-      local conflicted='%196F'  # red foreground
+      local      clean="%${POWERLEVEL9K_VCS_CLEAN_FOREGROUND}F"       # green foreground
+      local   modified='%${POWERLEVEL9K_VCS_MODIFIED_FOREGROUND}F'    # yellow foreground
+      local  untracked='%${POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND}F'   # blue foreground
+      local conflicted='%${POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND}F'  # red foreground
     else
       # Styling for incomplete and stale Git status.
-      local       meta='%244F'  # grey foreground
-      local      clean='%244F'  # grey foreground
-      local   modified='%244F'  # grey foreground
-      local  untracked='%244F'  # grey foreground
-      local conflicted='%244F'  # grey foreground
+      local       meta='%${POWERLEVEL9K_VCS_STALE_FOREGROUND}F'
+      local      clean='%${POWERLEVEL9K_VCS_STALE_FOREGROUND}F'
+      local   modified='%${POWERLEVEL9K_VCS_STALE_FOREGROUND}F'
+      local  untracked='%${POWERLEVEL9K_VCS_STALE_FOREGROUND}F'
+      local conflicted='%${POWERLEVEL9K_VCS_STALE_FOREGROUND}F'
     fi
 
     local res
@@ -497,9 +497,11 @@
 
   # These settings are used for repositories other than Git or when gitstatusd fails and
   # Powerlevel10k has to fall back to using vcs_info.
-  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
-  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=76
-  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
+  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76       # green foreground
+  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=39   # yellow foreground
+  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178   # blue foreground
+  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=196 # red foreground
+  typeset -g POWERLEVEL9K_VCS_STALE_FOREGROUND=244      # grey foreground
 
   ##########################[ status: exit code of the last command ]###########################
   # Enable OK_PIPE, ERROR_PIPE and ERROR_SIGNAL status states to allow us to enable, disable and
```

**Comment by romkatv** [comment]
`p10k configure` is a config generator. It's similar in spirit to the [sample kitty.conf](https://sw.kovidgoyal.net/kitty/conf/#sample-kitty-conf) or the [sample alacritty.yml](https://github.com/tmcdonell/config-alacritty/blob/master/alacritty.yml). You download these files and then edit. The only difference is that `p10k configure` has not one but multiple files that you can "download" before you start editing.

`POWERLEVEL9K_*` parameters are those that are understood by powerlevel10k proper. You can add parameters to your `~/.p10k.zsh` that are understood by that same file but I would not advise using the same naming convention for them. Prefixing your own parameter with `my_` or something similar is a good idea, for it'll help you avoid clashes.

That said, there is little to no value in splitting your config into multiple files, with one of them recognizing parameters sets by another. What are you trying to acomplish?
