### ISSUE TITLE
/etc/zshrc_Apple_Terminal and p10k instant prompt

### ISSUE THREAD

**Issue by rwmitchell** [romkatv/powerlevel10k#2502]
Currently in my .zshrc file, I have  (near the top):

```
[[ -e /etc/zshrc_Apple_Terminal ]] && source /etc/zshrc_Apple_Terminal

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -f ~/.p10k.use ]]; then
  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  fi
else
  printf "No instant prompt here\n"
fi
```

Previously I was sourcing zshrc_Apple_Terminal after p10k's instant prompt code.

It appears the cache file closes stderr, Apple then opens a new output file, getting file descriptor 2 (previously stderr).
Apple then writes to both stderr and its new file, putting the output of both into the same file, which Apple then attempts to run.  The 'stderr' output isn't code, so instead running the code generates  a 'command not found' error.

Moving the order as above seems to have fixed everything, this may help others.

ps: at one point I was using the file ~/.p10k.use to quickly enable/disable p10k by rm'ing or touching the file.

**Comment by rwmitchell** [comment]
The issue returned when replacing my code with your lines above.  The issue remained after moving sourcing zshrc_Apple_Terminal to above sourcing the instant-prompt cache.

I restored my original code and the issue still remained.

After making each change, I tested the change by running "exec zsh" and checking the contents of the Apple created file as well as observing the error..  I reran "exec zsh" many times after each change and created new terminal sessions to check the results, which were inconsistent (having both success and failing).

The apple session is not always created (or deleted before I can check).  i give up.  This issue can be deleted.

**Comment by romkatv** [comment]
Thanks for confirming that you can reproduce the issue with the `.zshrc` I provided.

Please describe which steps lead to the problem. We already know the first step: create `.zshrc` with the predefined content. What do you do next? And what exactly happens that you consider unexpected/incorrect?

Here's what I've tried myself:

1. Create `.zshrc` with the content from https://github.com/romkatv/powerlevel10k/issues/2502#issuecomment-1846922616.
2. Make sure that `zsh` is the login shell (this is the default).
3. Make sure that Terminal.app launches the login shell on startup (this is the default).
4. Close Terminal.app if it was open.
5. Open Terminal.app.
6. Type `ls` and press Enter.
7. Type `exit` and press Enter. This causes Terminal.app to close.
8. Open Terminal.app.

- Expected: no errors appear at any point.
- What actually happens: no errors appear at any point, as expected.

Are my steps missing something that is required to reproduce the problem? Or perhaps my expectations are incorrect?
