### ISSUE TITLE
Strange unremovable gap in right side of prompt

### ISSUE THREAD

**Issue by Hellscaped** [romkatv/powerlevel10k#2506]
I have no clue how to fix this, its been here for a lil while.

I''m using Terminator, by the way.
![image](https://github.com/romkatv/powerlevel10k/assets/72767525/2a854550-c9fd-46ce-86e5-cad053eccbd9)

**Comment by Hellscaped** [comment]
Strangely enough, regenerating the configuration fixed it. I had to tell it there was no overlap even when there was.

**Comment by Hellscaped** [comment]
Still an issue, so not closing this

**Comment by romkatv** [comment]
Add `ZLE_RPROMPT_INDENT=0` to .zshrc. See https://zsh.sourceforge.io/Doc/Release/Parameters.html#Parameters-Used-By-The-Shell for documentation.

**Comment by romkatv** [comment]
Ah, I think you mean the other gap (I missed it at first). For that one, see https://github.com/romkatv/powerlevel10k/issues/2494#issuecomment-1825268079. The parameter you'll need to manually edit is `POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL`.

An alternative is to use the [recommended font](https://github.com/romkatv/powerlevel10k/blob/master/font.md). It'll solve this issue and many others that you are otherwise likely to have.

**Comment by Hellscaped** [comment]
> Ah, I think you mean the other gap (I missed it at first). For that one, see [#2494 (comment)](https://github.com/romkatv/powerlevel10k/issues/2494#issuecomment-1825268079). The parameter you'll need to manually edit is `POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL`.
> 
> An alternative is to use the [recommended font](https://github.com/romkatv/powerlevel10k/blob/master/font.md?rgh-link-date=2023-12-11T07%3A41%3A48Z). It'll solve this issue and many others that you are otherwise likely to have.

I'm using the recommended font, Meslo LGS NF

**Comment by romkatv** [comment]
It does not look like Meslo LGS NF. Can you run `p10k configure` and post a screenshot of the screen that asks whether all icons fit between the crosses?

In addition, please post a screenshot of the terminal settings screen related to fonts.

**Comment by Hellscaped** [comment]
> It does not look like Meslo LGS NF. Can you run `p10k configure` and post a screenshot of the screen that asks whether all icons fit between the crosses?
> 
> In addition, please post a screenshot of the terminal settings screen related to fonts.

![image](https://github.com/romkatv/powerlevel10k/assets/72767525/520dd02a-6b74-42b0-8445-c9cdfbb70f02)

**Comment by romkatv** [comment]
Thanks.

The recommended font is called "MesloLGS NF" (literally). Your terminal is configured with a different font that has a similar name.
