### ISSUE TITLE
Strange duplication prompt line

### ISSUE THREAD

**Issue by DeathKing** [romkatv/powerlevel10k#2507]
I'm using p10k with instant prompt, but there's always a strange, duplicated prompt line after the p10k prompt been loaded (as you can see from the video). 

I've regenerated configuration file for many times and have no clue about this. Any idea?

BTW, the zsh is 5.9 (x86_64-apple-darwin23.0)

<img width="385" alt="duplications" src="https://github.com/romkatv/powerlevel10k/assets/895809/2168fcfd-14ae-4652-be51-08919b62edfd">

https://github.com/romkatv/powerlevel10k/assets/895809/eba68ae1-daf6-49d5-8f27-f3653e4555ca

**Comment by romkatv** [comment]
This usually happens when you are attempt to use two zsh themes in your `.zshrc`.

**Comment by DeathKing** [comment]
@romkatv Thanks a lot, it turns out that I also use the `pure.zsh` theme.
