### ISSUE TITLE
MobaXterm not visible fonts properly 

### ISSUE THREAD

**Issue by latapundla** [romkatv/powerlevel10k#2508]
Hello Team,
I am not able to see my mobaXterm font whil open ssh terminal can any one suggest
![MobaXterm](https://github.com/romkatv/powerlevel10k/assets/39549135/98585818-1aa4-478f-86ad-b4103907f785)

**Comment by romkatv** [comment]
What happens if you disable powerlevel10k or replace it with another theme?

**Comment by latapundla** [comment]
Hi, 
Thanks for replay I have done reset entire setting now it's working fine 
Thanks
