### ISSUE TITLE
VSC icons aren't shown on non-HTTPS repositories

### ISSUE THREAD

**Issue by 5ouma** [romkatv/powerlevel10k#2509]
After you made strict the remote Git URL matching on https://github.com/romkatv/powerlevel10k/commit/7fd76370f53f87f956c811766a452c83ced4014b, some repositories don't show their VCS icons. (I'm not sure other than GitHub)

It occurs when I set GitHub remote URLs as SSH, not HTTPS like these.
- `git@github.com:<owner>/<repository>.git`
- `ssh://git@github.com/<owner>/<repository>.git`

If you set HTTPS URLs like this, p10k correctly shows the GitHub icon.
- `https://github.com/<owner>/<repository>.git`

|     SSH remote URL     |  HTTPS remote URL   |
|:----------------------:|:-------------------:|
| ![without-github-icon] | ![with-github-icon] |

[with-github-icon]: https://github.com/romkatv/powerlevel10k/assets/101255979/339802d4-5533-493b-91c6-d863a3259603
[without-github-icon]: https://github.com/romkatv/powerlevel10k/assets/101255979/5e2d6bd7-f4f1-4e07-9b3a-6c1c3674a06b

**Comment by romkatv** [comment]
What is the output of `typeset -p VCS_STATUS_REMOTE_URL` when the incorrect icon is being shown?

**Comment by 5ouma** [comment]
It said `typeset VCS_STATUS_REMOTE_URL=github:<owner>/<repository>.git` with both SSH URLs.
- `git@github.com:<owner>/<repository>.git`
- `ssh://git@github.com/<owner>/<repository>.git`

With HTTPS URL
- `typeset VCS_STATUS_REMOTE_URL=https://github.com/<owner>/<repository>`

**Comment by romkatv** [comment]
I'm not sure I understand your answer. Could you `cd` to the repository and run the command I asked?

**Comment by romkatv** [comment]
After my change the github icon is shown only when the remote is on github.com. Your remote isn't on github.com, so you get the regular "git" icon.

Is this a hosted GitHub instance? Is it standard practice for this host to be called "github"?

**Comment by 5ouma** [comment]
No, it's a completely original GitHub remote.
If I clone via SSH like `git@github.com:5ouma/5ouma.git` which is copied from a button on GitHub, it becomes that type of URL.

**Comment by romkatv** [comment]
That is very interesting. Let's try to figure out how that happens. Please run the following command and post its output here:

```zsh
cd /tmp && git clone git@github.com:5ouma/5ouma.git && cd 5ouma && git remote -vv && git pull
```

**Comment by 5ouma** [comment]
Here we go.
```shell
Cloning into '5ouma'...
remote: Enumerating objects: 144, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 144 (delta 16), reused 17 (delta 5), pack-reused 113
Receiving objects: 100% (144/144), 291.28 KiB | 532.00 KiB/s, done.
Resolving deltas: 100% (61/61), done.
origin	github:5ouma/5ouma.git (fetch)
origin	github:5ouma/5ouma.git (push)
Already up to date.
```

**Comment by romkatv** [comment]
Thanks.

Do you know why this rewriting of the remote URI happens? Do you have something in `~/.gitconfig` that does it? Or perhaps something in `~/.ssh/config`?

**Comment by romkatv** [comment]
Additional question: What is the output of `ssh -G github`?

**Comment by 5ouma** [comment]
Oh... I force Git to use the SSH URL to use various Git profiles.
```
[url "github:5ouma"]
  pushInsteadOf = https://github.com/5ouma
  InsteadOf = git@github.com:5ouma
  InsteadOf = ssh://git@github.com/5ouma
```

```
Host github
  HostName github.com
  User git
  IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
  IdentityFile ~/.ssh/git/github.pub
  IdentitiesOnly yes
```

**Comment by 5ouma** [comment]
```
user git
hostname github.com
port 22
addressfamily any
batchmode no
canonicalizefallbacklocal yes
canonicalizehostname false
challengeresponseauthentication yes
checkhostip no
compression no
controlmaster false
enablesshkeysign no
clearallforwardings no
exitonforwardfailure no
fingerprinthash SHA256
forwardx11 no
forwardx11trusted no
gatewayports no
gssapiauthentication no
gssapidelegatecredentials no
hashknownhosts no
hostbasedauthentication no
identitiesonly yes
kbdinteractiveauthentication yes
nohostauthenticationforlocalhost no
passwordauthentication yes
permitlocalcommand no
proxyusefdpass no
pubkeyauthentication yes
requesttty auto
streamlocalbindunlink no
stricthostkeychecking ask
tcpkeepalive yes
tunnel false
verifyhostkeydns false
visualhostkey no
updatehostkeys true
canonicalizemaxdots 1
connectionattempts 1
forwardx11timeout 1200
numberofpasswordprompts 3
serveralivecountmax 3
serveraliveinterval 0
ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
hostkeyalgorithms ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
hostbasedacceptedalgorithms ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
identityagent /Users/souma/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock
kexalgorithms curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
casignaturealgorithms ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
loglevel INFO
macs umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
securitykeyprovider $SSH_SK_PROVIDER
pubkeyacceptedalgorithms ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
xauthlocation xauth
identityfile ~/.ssh/git/github.pub
canonicaldomains
globalknownhostsfile /etc/ssh/ssh_known_hosts /etc/ssh/ssh_known_hosts2
userknownhostsfile /Users/souma/.ssh/known_hosts /Users/souma/.ssh/known_hosts2
sendenv LANG
sendenv LC_*
logverbose
permitremoteopen any
addkeystoagent false
forwardagent no
connecttimeout none
tunneldevice any:any
controlpersist no
escapechar ~
ipqos af21 cs1
rekeylimit 0 0
streamlocalbindmask 0177
syslogfacility USER
```

**Comment by romkatv** [comment]
That all makes sense now.

In your configs you could replace `[url "github:5ouma"]` with `[url "anything:5ouma"]` and `Host github` with `Host anything` and all git commands would still work. However, the remote URL would look like `anything:5ouma/5ouma.git`. Since "anything" is not "github.com" or its subdomain, powerlevel10k won't recognize it as pointing to GitHub. In the past this used to work because any remote URL that contains "github" as a substring was classified as GitHub.

Is it common to use a config of this kind? Have you copied it from somewhere?

**Comment by 5ouma** [comment]
I'm not sure it's common, but I set it to change the SSH `Host` URL.
However, I tried to change them to `github.com` and `<any-subdomain>.github.com` on git config and ssh config, and it worked correctly!

**Comment by romkatv** [comment]
I'm inclined to treat this as Working as Intended. Powerlevel10k does not know that the hostname "github" is resolved to "git@github.com".

**Comment by 5ouma** [comment]
This Issue occurred due to my specific configs. I replaced URLs with not `github.com` URLs on `git/config` for SSH config.
I changed to URLs containing `github.com` or to its subdomains, and it fixed with the GitHub icon.
