### ISSUE TITLE
Upwards arrow and Python logo aren't showing up

### ISSUE THREAD

**Issue by vinrepos** [romkatv/powerlevel10k#2511]
Hi so I have got some symbols working but the upwards arrow and python one aren't showing up. I'm sure the powerline fonts and Meslo fonts are in use. How do I troubleshoot the missing fonts now?

I'm using a Ubuntu 22 server with no GUI.

Working ones:

![image](https://github.com/romkatv/powerlevel10k/assets/104124987/26d1ec45-b309-44ee-b2b9-5a5db947a54a)

![image](https://github.com/romkatv/powerlevel10k/assets/104124987/1b9fb39a-70bd-4c0e-a757-b53b677affb4)

![image](https://github.com/romkatv/powerlevel10k/assets/104124987/87e5687b-d60a-4109-90bb-5da9eed61764)

Non-working ones:

![image](https://github.com/romkatv/powerlevel10k/assets/104124987/21cafcc9-bb90-4524-9740-c495c3338447)

![image](https://github.com/romkatv/powerlevel10k/assets/104124987/0f9672ad-87cf-4596-bc41-4b7b2927cc57)

![image](https://github.com/romkatv/powerlevel10k/assets/104124987/5214e16e-771e-49a3-b283-e372d306daa4)

The output of terminfo colour:

```
> print $terminfo[colors]
256
```

Any suggestions would be great. Thanks.

**Comment by romkatv** [comment]
What happens if you answer all questions truthfully? Do you get a working prompt? Does it look acceptable to you?

**Comment by vinrepos** [comment]
Hi @romkatv  - If I answer all the questions properly then yeah the terminal looks alright to me. But then I'm wondering what could I be missing?

Here's an example:

![VFYUpdQeIKRH](https://github.com/romkatv/powerlevel10k/assets/104124987/3099b5ec-96dd-455f-8b5a-85b83f52f8cd)

**Comment by romkatv** [comment]
Your screenshot looks fine to me. You aren't missing anything.

**Comment by romkatv** [comment]
By the way, your terminal is not using the recommended font (MesloLGS NF). It's using some other font that I cannot identify from the screenshot. This is the reason that you had to answer some questions with "No". It's alright though, powerlevel10k works with all fonts.

**Comment by vinrepos** [comment]
Hi @romkatv  Yeah you're spot on about the Meslo font usage. I tried logging on through another terminal and ran the configuration wizard again, and it has picked up the Upward arrow (in the 2nd attempt though). This also gave me the Ubuntu character in the prompt instead of the default tux character.

![image](https://github.com/romkatv/powerlevel10k/assets/104124987/c0a01e73-99cf-42b3-a39c-128281a3c481)

**Comment by romkatv** [comment]
This other terminal of yours can also render bold text. That's nice.

You can see that the two terminals are using different fonts by comparing how the character `i` looks in them. This is how I knew the first terminal is using something other than MesloLGS NF.

If you'd like to configure your first terminal to use MesloLGS NF, check out https://github.com/romkatv/powerlevel10k/blob/master/font.md. Switching to the other terminal or even doing nothing are also reasonable options.

**Comment by vinrepos** [comment]
Nice one thanks for you help, I'll mark this as closed now. Cheers.
