### ISSUE TITLE
Support for Monaspace?

### ISSUE THREAD

**Issue by javentous** [romkatv/powerlevel10k#2514]
Hey, thanks for the work. I like using p10k and have been using it for half a year now, prefer it to ohmyzsh by quite a bit.

https://monaspace.githubnext.com

Monaspace is new font family with a bunch of cool features, anyway p10k could support it in some capacity (to whatever capacity it can and is not limited by software which it depends on or interacts with which has it's own limits therein)

**Comment by romkatv** [comment]
If your terminal can use this font, run `p10k configure` and you should be set. Is anything missing if you do that?

**Comment by VAggrippino** [comment]
I've been using p10k _with_ OhMyZsh for a long time. I tried out Monaspace, too. Unfortunately, it doesn't seem to support many of p10k's style options. I'm sure all of the functional features will work fine, though.

It's probably the font that needs to support p10k, though. Not the other way around. It says something like that [in the README](https://github.com/romkatv/powerlevel10k#fonts).

I'm using Monaspace in VSCode, but sticking with Meslo (the recommended font patched specifically for p10k) in the terminal.

In VSCode the font is set like a `font-family` would be in CSS. So, I set it to `'Monaspace Neon Var', 'MesloLGS NF'` and the integrated terminal falls back perfectly to Meslo with all the p10k style because it doesn't support Monaspace which is _technically_ a variable-width font.

**Comment by javentous** [comment]
This might show the feature I was talking about a bit more...

https://github.com/romkatv/powerlevel10k/assets/12705383/67eb2c5f-eb96-4d76-9aac-24caaee627f3

**Comment by romkatv** [comment]
I'm afraid this video doesn't explain what you mean by "support for Monaspace" in the context of powerlevel10k.

**Comment by vufly** [comment]
@javentous I think you have to patch these Monaspace fonts with [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts#font-patcher) if you want to use some special characters as you mention "style"

**Comment by javentous** [comment]
> I'm afraid this video doesn't explain what you mean by "support for Monaspace" in the context of powerlevel10k.

very strange, apologies for the miscommunication, there seems to be a misunderstanding of the subject (i.e. feature), let me attempt to clarify

NOTE: perhaps this is out of the scope of p10k

at present when using terminal & p10k, there is no texture healing, i.e. the phenomena demonstrated in the provided video. this feature is new, it was introduced with monaspace, vscode has it. when the feature is used, the fonts change dynamically as seen in the provided video. as other fonts do not have this feature, and only monaspace does (at present), supporting the texture healing feature can allow for its use broadly (i.e. opening the gates for using other fonts which choose to support texture healing)

thanks for the responses, appreciate that you took the time out of your day(s) and again the software is awesome, i literally use it everyday i use a computer.

**Comment by romkatv** [comment]
> It would also seem to me this is a terminal issue, not a pk10 issue.

This 👆, although I wouldn't use the word "issue".

**Comment by javentous** [comment]
> > It would also seem to me this is a terminal issue, not a pk10 issue.
> 
> This 👆, although I wouldn't use the word "issue".

that's fair.

i don't appreciate your comment regarding my use of the word "issue".
i'd like to be charitable in my interpretation of your comment, as you've been cordial thus far; however even in your prior comment there was a lack of understanding in what i attempted to communicate and does not appear that my method or style is amenable to you for whatever reason (I presume as a maintainer of a larger project with many issues, the goal is perhaps not to spend too much time on what you or others consider rather minor issues, you have your own heuristic which appear to work for you and i respect that); and i'm cognizant of the context (i.e. environment) i'm making this current comment in. i'm not very familiar, i've only begun interacting recently; however my broad understanding is that disciplinarian grammarian, i.e. linguistic _prescriptivists_ or perhaps colloquially contemporarily known as _tone police_.

i've now taking a look at the [`GitHub Community Guidelines`](https://docs.github.com/articles/github-community-guidelines) appended at the bottom of the page i am on, as as footnote, and there is a relevant tidbit i'll quote and italicize:

> # [What if someone or something offends you?](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#what-if-something-or-someone-offends-you)
> While some disagreements can be _resolved with direct, respectful communication between community members_, we understand that is not always the case. We encourage our community to contact GitHub Support through the GitHub Support portal when they believe content or activity they’ve encountered violates our policies. However, if you run into something or someone on the site that you find objectionable, here are some ways GitHub enables you to take action:
> [ ... ]

as well as looking at the code of conduct:

> # [Pledge](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#pledge)
> - In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in GitHub Community a harassment-free experience for everyone, _regardless of_ age, body size, disability, ethnicity, gender identity and _expression, level of experience_, nationality, personal appearance, race, religion, or sexual identity and orientation.
> # [Standards](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct#standards)
> [ ... ]
> ## [Best practices for maintaining a strong community](https://docs.github.com/en/site-policy/github-terms/github-community-code-of-conduct#best-practices-for-maintaining-a-strong-community)
> - Engage with consideration and respect.
>   - _**Be welcoming and open-minded** - New users join our community each day_. Some are well-established developers, _while others are just beginning_. Be open to other ideas and experience levels. Make room for opinions other than your own and _be welcoming to new collaborators and those just getting started_.
>    - _**Be respectful** - Working in a collaborative environment means disagreements may happen_. But remember to criticize ideas, not people. _Share thoughtful, constructive criticism_ and be courteous to those you interact with. If you’re unable to engage respectfully, consider taking a step back or using some of our moderation tools to deescalate a tense situation.
>    - _**Be empathetic** - GitHub is a global community with people from a wide variety of backgrounds and perspectives_, many of _which may not be your own_. Try to _put yourself in others’ shoes and understand their feelings_ before you address them. Do your best to help make GitHub a community where others feel safe to make contributions, _participate in discussions_, and share different ideas.
> - Contribute in a positive and constructive way.
>   - _**Improve the discussion**_. Help us make this a great place for discussion by always _working to improve the discussion in some way_, however small. _If you are not sure your post adds to the conversation_, think over what you want to say and try again later.
>
>      The topics discussed here matter to us, and we want you to act as if they matter to you, too. _Be respectful of the topics_ and _the people discussing them, even if you disagree with some of what is being said_.
>   - _**Be clear and stay on topic**_. GitHub Community is for collaboration, sharing ideas, and helping each other get stuff done. _Off-topic comments are a distraction_ (sometimes welcome, but usually not) from getting work done and being productive. _Staying on topic_ helps produce positive and productive discussions.
>    [ ... ]
>   - _**Share mindfully**_. When asking others to give you feedback or collaborate on a project, only share valuable and relevant resources to provide context. Don't post links that don't add value to the discussion, and don't post unsolicited links to your own projects or sites on other user's threads.
>    [ ... ] 

and so on and so forth;

i was going to go through the etymology and uses of the word "issue". the various canonical texts and lexicons is a part of so ideally folks who may read this have some knowledge they can walk away with, just some tidbit or trivia that would foment into a deeper understanding of language and prevent what _appears_ to be prescriptivism (which i cannot confirm as i do not know what you think; similarly cannot blame you for, for your service of maintaining an open source project which does plenty of good for all close to indiscriminately. i apologize for taking issue with your issue of my use of issue for an issue(s). the only definition or use (recall, from the point-of-view of a lexicographer or linguist, all use of language is valid, as it being used–i.e. the praxis of language–renders it valid, in at least _some_ sense) i'll paraphrase is the following:

> The maintainer of the kernel _issued_ forth an edict;
>   What it said some sought to know,
>   For patterns came to and fro:
>   All were trained in regular expressions,
>   Though it did not help with the suppression,
>   Of some key information, a secret key;
>   To gain the rights to the vault which be,
>   So much for now, a break will we take,
>   In our compilation; of sacred kernel make,
>   Ever yonder those who come will try,
>   Perhaps what's needed is that faithful cry;
>   'It's now it's here, the queen we've bopped!
>   It's finally the year, the year of linux desktop!

**Comment by romkatv** [comment]
> i don't appreciate your comment regarding my use of the word "issue".

I believe there's a misunderstanding. You didn't use the word "issue". My previous comment was in response to @rwmitchell, agreeing with him but with the clarification that it's normal for terminals to function as they do. To draw an analogy, if my car doesn't start, it's an issue with the car. However, if my car can't fly, while it might be a problem for me, it's not an issue with the car itself. To extend this analogy, think of powerlevel10k as a steering wheel. Before we can integrate altitude control into it, the car itself would need to develop wings.

**Comment by rwmitchell** [comment]
Thanks @romkatv, just throw me under the bus. (I joke)

I agree with your analogy.  I was thinking more of, if monaspace is going to be supported, it needs to be in the terminal and not that it was a flaw/shorting of the terminal.

Whether this is a valid terminal feature is a different point.  I've been using terminals since they were made out of paper.  There have been a lot of things I didn't think belonged in the terminal only to see gnachman implement them wonderfully.

**Comment by romkatv** [comment]
Some of the things offered by Monaspace can be supported by terminals without extending the TTY protocol. Namely, what they call *texture healing*, which is basically ligatures. Other features would require TTY extensions and collaboration from programs running in the terminal. This includes support for extended font faces.

**Comment by javentous** [comment]
understood, my bad, i apologize for the rant. i was triggered by what i conceived, mistakenly, that it was targeted at myself.

again sorry, i really like powerlevel10k. thanks for making/using it (along with all others ofc);
i hope you liked my poem at least...

**Comment by romkatv** [comment]
No harm done. I'm glad we've resolved the misunderstanding.
