### ISSUE TITLE
local repo issue

### ISSUE THREAD

**Issue by A-NIZZY** [romkatv/powerlevel10k#2515]
hi is there any way i can clone this repository without it saying this: fatal: could not create leading directories of '/themes/powerlevel10k': Read-only file system

**Comment by rwmitchell** [comment]
I used:

`git clone https://github.com/romkatv/powerlevel10k.git`

and it worked ok for me:

<img width="722" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/15944841/26965551-c0b3-4932-88aa-80f7c4024744">


Maybe the issue is where you are doing the clone?

**Comment by A-NIZZY** [comment]
ok I'll try it. thanks

**Comment by romkatv** [comment]
@A-NIZZY Which installation instructions of powerlevel10k are you following? Which command are you running that gives you this error?

**Comment by Geryon90** [comment]
Чтобы ошибка ушла:
1. Еще раз установите Oh my zsh  по ссылке с сайта. У меня тоже отображалась версия, но оказывается он не был установлен.
2. Снова вводите команду git clone https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
