### ISSUE TITLE
Could you add `` as another type of prompt separator?

### ISSUE THREAD

**Issue by pcroland** [romkatv/powerlevel10k#2516]
https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/cert.omp.json
This character:
![img](https://telegra.ph//file/c6fe65db8be325aa1e9cc.png)
It would look like something like this with p10k:
![img](https://telegra.ph//file/00f27de50f7ac54f67988.png)

**Comment by romkatv** [comment]
You can edit `~/.p10k.zsh` to achieve this effect. These are the relevant parameters: https://github.com/romkatv/powerlevel10k/blob/cc6ed4be416b70fe4e3f97d17061c751abaca04f/config/p10k-rainbow.zsh#L162-L180

**Comment by pcroland** [comment]
Thanks
