### ISSUE TITLE
Slow startup time due to gcloud cli

### ISSUE THREAD

**Issue by maround95** [romkatv/powerlevel10k#2517]
Hello!
I want to thank you for the amazing project, been using it for years.

I noticed that when I have the gcloud cli installed and configured, shell startup time is heavily impacted. I traced it back to the p10k gcloud segment.
I am using the instant prompt feature but querying for the segment data using the cli is happening on startup (is this expected?) and synchronously for some reason.
I have forked the master branch and made a change to read the data (Account and ProjectId) from the gcloud config file instead of invoking the slow python cli, however I do not want to make a PR since this seems like a workaround and does not solve the underlying issue if any.
Your input would be appreciated.

#https://github.com/maround95/powerlevel10k/tree/gcloud-startup

**Comment by romkatv** [comment]
> I am using the instant prompt feature but querying for the segment data using the cli is happening on startup (is this expected?) and synchronously for some reason.

Yes, this is expected. What isn't expected is that you notice it. This means that Instant Prompt likely isn't working. Moreover, caching is likely not working either.

There is a decent description of what Instant Prompt does at https://github.com/romkatv/zsh-bench/blob/master/README.md#instant-prompt. It might be useful to read it.

To understand what's going on, I'll need a more precise description of the problem. Which steps lead to "slow startup time". Can you reproduce it at will? What exactly is slow and by how much? What is in your zsh startup files?

If you could run [zsh-bench](https://github.com/romkatv/zsh-bench) and post the results, that would also help.

**Comment by romkatv** [comment]
`zsh-bench` results that you've posted show about 20ms for `first_prompt_lag_ms` and 50ms for `first_command_lag_ms`. This is indistinguishable from instantaneous. See https://github.com/romkatv/zsh-bench?tab=readme-ov-file#how-fast-is-fast.

> Curiously it happens more consistently when I invoke tmux.

This is most likely it. Powerlevel10k wipes caches when you switch terminals, and tmux is a different terminal compared to the outer terminal you are using. Most people use just a single terminal for everything, so caches don't get busted all the time.

If you configure zsh to always start tmux automatically, you'll have tmux in all your terminals and instant prompt will always work. You can do it by adding the following bit at the very top of `.zshrc`:

```zsh
if [[ -z ${TMUX+X}${ZSH_SCRIPT+X}${ZSH_EXECUTION_STRING+X} && -v commands[tmux] ]]; then
  exec tmux
fi
```

This needs to go above the instant prompt stanza. It works the same way as running `tmux` manually immediately after starting zsh but without busting powerlevel10k caches. If you usually start tmux with some flags, pass them in there too.

What I like to do is to automatically start tmux with `tmux -u new -A -D -t default`. If I need several tmux sessions on the same machine, I create one with `tmux switchc -t "$(tmux new -dP)"` (or with an extra `-s` if I want to name the session).

> `set -g default-terminal "xterm-256color"`

This is really not a good idea. tmux is incompatible with xterm-256color. From `man tmux`:

> For tmux to work correctly, [default-terminal] must be set to ‘screen’, ‘tmux’ or a derivative of them.

You can see the incompatibility by comparing the output of `infocmp screen` and `infocmp xterm`.

**Comment by maround95** [comment]
Thanks for your valuable insights.
I had suspected that cache invalidation happens when the terminal changes, and as such setting the terminal in tmux to match the outer terminal was my attempt to test that theory. It however did not make a difference in that case.

I will set my zsh config to launch tmux on startup.
Out of curiosity, why is the gcloud info computed synchronously on startup? Is it needed for the correct functioning of the segment later?

This issue can be marked as resolved from my end.
It may still be worthwhile pursuing prefetching any data asynchronously on startup too, most probably the functionality already exists in some form, however I have only looked at the gcloud segment superficially.

I want to thank you again for the great work you're doing. Happy holidays!

**Comment by romkatv** [comment]
> Out of curiosity, why is the gcloud info computed synchronously on startup? Is it needed for the correct functioning of the segment later?

Something like that. With additional effort it would be possible to make this part faster or non-blocking, but it wasn't a necessity when I wrote it because I generally assume that caching works.
