### ISSUE TITLE
prompt is 2-colored in tmux

### ISSUE THREAD

**Issue by Kha1r0** [romkatv/powerlevel10k#2520]
in normal terminal it looks fine:
![image](https://github.com/romkatv/powerlevel10k/assets/115714947/d774d27d-b5c8-4d0f-a8f7-488788d0d3af)
but in tmux it's 2-colored while the rest of the terminal looks normal
![Screenshot 2023-12-26 at 23 17 40](https://github.com/romkatv/powerlevel10k/assets/115714947/1ef65890-2409-4c86-9c18-13ada294b6c0)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/434#issuecomment-1820463283

**Comment by Kha1r0** [comment]
ah, i had to write it into `~/.tmux.conf`, not in `~/.tmux`.

**Comment by Kha1r0** [comment]
Thank you! @romkatv

**Comment by romkatv** [comment]
You are welcome.
