### ISSUE TITLE
[question] why POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL will result in hang

### ISSUE THREAD

**Issue by Freed-Wu** [romkatv/powerlevel10k#2521]
Hey, I met a very weird thing:

I have a server Ubuntu 22.04. its `$SHELL` is `zsh`. When I `ssh server`, it will work.
However, when I `ssh` another server CentOS 7, then `ssh` my server Ubuntu 22.04, it will hang.

I try to find the reason and I comment and uncomment my `~/.zshrc`. Finally I find one line of code. If I comment it, it will not hang:

`.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
```

I have solved this problem by comment this line. I just curious why this weird thing occur? Will comment this line result in any side effect? Thanks for any answer.

Environment:

CentOS:

bash 4.2
linux 3.10.0-1160.66.1.el7.x86_64
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017

Ubuntu:

linux 5.15.0-1045-intel-iotg
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

**Comment by romkatv** [comment]
It's very unlikely that this line has this effect.

**Comment by Freed-Wu** [comment]
Oh, I see. Thanks for your answer!
