### ISSUE TITLE
The git icon is displayed incorrectly, but the icon can be displayed normally when booting the configuration.

### ISSUE THREAD

**Issue by jaxonister** [romkatv/powerlevel10k#2523]
boot configuration
<img width="399" alt="企业微信截图_5ceb4633-74de-4d78-a3ea-e6003231a79a" src="https://github.com/romkatv/powerlevel10k/assets/42506435/2b86619a-7818-4384-85b5-602d6007160c">

item2
<img width="278" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/42506435/9c0e4b52-fba8-46b1-8ddc-171965814da2">

terminal

![image](https://github.com/romkatv/powerlevel10k/assets/42506435/84fa9bb1-147b-4a2b-971a-17b5d191e173)

**Comment by romkatv** [comment]
Which icon is incorrect and why do you think so?

**Comment by jaxonister** [comment]
⇡6 ?8 represents what？

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean

**Comment by jaxonister** [comment]
How do I close this state display?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#how-do-i-change-the-format-of-git-status

**Comment by jaxonister** [comment]
Comments This few lines can be closed
![image](https://github.com/romkatv/powerlevel10k/assets/42506435/73c817ed-fcbb-4a58-b7dc-e2dd7bdf7f51)
