### ISSUE TITLE
need help to create prompt style

### ISSUE THREAD

**Issue by ciscohack** [romkatv/powerlevel10k#2528]
Hi Roman,

Can you please help me to create a prompt style like this? I know this is a simple prompt but I am not able to mimic it. I created p10k config with a single-line prompt but was not able to add username@<anyname> ~> like this ... here is my prompt at the moment. 

<img width="109" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/a6b96ce3-3ff9-4cbf-b81f-59aa30ae153c">

guide me on what config I add to mimic the prompt as in the below screenshot.

<img width="302" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/11479557/640ed2ed-473c-4264-a07a-b0cbedb86a43">

**Comment by romkatv** [comment]
Please see the FAQ: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#how-do-i-add-username-andor-hostname-to-prompt

**Comment by ciscohack** [comment]
> @romkatv Thanks for the update. Yes I did check this context option but it's not giving me results that's why I asked. I have context prompt enabled for the left side prompt

Sorry there was a typo on my side .. issue resolved and it's working now thanks

**Comment by romkatv** [comment]
Awesome 👍
