### ISSUE TITLE
transient prompt not working

### ISSUE THREAD

**Issue by cridemichel** [romkatv/powerlevel10k#2529]
Hi, 
I am using oh-my-zshell (up-to-date) and powerlevel10k (up-to-date from github repository) for several years by now.
Recently, transient prompt stopped working and the culprit is the vi-mode pluging. Indeed, if I remove this plugin
it works just fine. Attached you can find my .p10k.zsh e .zshrc files, 

best regards, 
Cristiano

[myp10kzsh.zip](https://github.com/romkatv/powerlevel10k/files/13858698/myp10kzsh.zip)
[myzshrc.zip](https://github.com/romkatv/powerlevel10k/files/13858833/myzshrc.zip)

**Comment by cridemichel** [comment]
setting 
VI_MODE_SET_CURSOR=true
in .zsrhc issues disappears...

**Comment by romkatv** [comment]
This plugin is ridden with bugs and it doesn't do anything useful. You'll be better off with just `bindkey -v` plus a few key bindings.
