### ISSUE TITLE
Wrong Python environment names

### ISSUE THREAD

**Issue by vict0rsch** [romkatv/powerlevel10k#2530]
Hi,

when I activate a new environment, for some reason its name "sticks" to the Python segment:

1. No Python seg
2. Activate env
3. Right name is displayed
4. Activate other env
5. Right name is displayed
6. Deactivate
7. No Python segment (as expected)
8. Activate first environment
9. **Second name is displayed**, and for any subsequent env

![SCR-20240110-ohmz](https://github.com/romkatv/powerlevel10k/assets/9283470/93a9b91e-59cd-47a4-b292-8534f4355f83)

```bash
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
  # Don't show Python version next to the virtual environment name.
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
  # If set to "false", won't show virtualenv if pyenv is already shown.
  # If set to "if-different", won't show virtualenv if it's the same as pyenv.
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
  # Separate environment name from Python version only with a space.
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
```

When setting `POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION` to true, it displays the **correct** Python version but still the wrong name.

**Comment by romkatv** [comment]
What is the output of the following command when the wrong name is displayed?

```zsh
typeset -p VIRTUAL_ENV
```

**Comment by vict0rsch** [comment]
![SCR-20240110-okfy](https://github.com/romkatv/powerlevel10k/assets/9283470/1d67e6cd-6af2-4680-80be-e1b272992118)
Right env, wrong display

**Comment by romkatv** [comment]
Which segment is displaying "gfn-113" on the right? You can figure this out by commenting out all segments within `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in `~/.p10k.zsh` except one.

**Comment by vict0rsch** [comment]
With `virtualenv` only in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`:

![SCR-20240110-omru](https://github.com/romkatv/powerlevel10k/assets/9283470/98cd09df-ce93-4734-ac91-8bbd180522d9)

**Comment by vict0rsch** [comment]
(and still:
```
❯ typeset -p VIRTUAL_ENV
export VIRTUAL_ENV=/Users/victor/.virtualenvs/gflownet
```
)

**Comment by vict0rsch** [comment]
(`venv activate $NAME` is a function to execute `source ~/.virtualenvs/$NAME/bin/activate`

**Comment by romkatv** [comment]
What's the output of this command?

```zsh
typeset -p VIRTUAL_ENV_PROMPT
```

**Comment by vict0rsch** [comment]
Looks like we're getting somewhere indeed 

![SCR-20240111-kqoh](https://github.com/romkatv/powerlevel10k/assets/9283470/4434e513-849a-44c4-ada3-3a76e80b2668)

**Comment by romkatv** [comment]
There you go. Powerlevel10k respects this override. If you don't want it, disable it in the virtualenv. I don't know how but I recall there is a way.

**Comment by vict0rsch** [comment]
Ok thanks!

Putting `export VIRTUAL_ENV_DISABLE_PROMPT=1` in my `.zshrc` fixes the issue.

**Comment by romkatv** [comment]
👍
