### ISSUE TITLE
Add time autoupdate

### ISSUE THREAD

**Issue by user-naa** [romkatv/powerlevel10k#2531]
Will be very good if time and cpu load autoupdate in last promt every second

**Comment by romkatv** [comment]
There is an option to enable time ticking in real time but I strongly recommend against it. Configure your OS to display the current time instead.

**Comment by user-naa** [comment]
Thank you! But can I do it for cpu load? I want to see it in real time

**Comment by romkatv** [comment]
You cannot with powerlevel10k, but any decent OS should allow you to add an indicator for CPU load that you can see at all times.
