### ISSUE TITLE
Allow changing git prompt colors

### ISSUE THREAD

**Issue by qdii** [romkatv/powerlevel10k#2532]
Git colors are currently hardcoded in .p10k.zsh. It would be nice to have environment variables colors to be able to tweak it!

**Comment by romkatv** [comment]
`.p10k.zsh` is your personal config. Everything you see in it is hard-coded in the config. Also, everything you see can be changed by editing the config.

**Comment by qdii** [comment]
Ah, I was afraid that `p10k configure`, or a package manager would overwrite the changes I make in this file.

Do I understand from your comment that they wouldn't?

**Comment by romkatv** [comment]
`p10k configure` is a config generator. Its job is to generate `.p10k.zsh`, which you can then manually customize to your needs. Since it's a config generator, it overrides `.p10k.zsh` if you have it already (it asks you before doing that).

Updating powerlevel10k will not change `.p10k.zsh`. Moreover, configs are backward compatible forever, so you should definitely save your config the same way you (hopefully) save `.zshrc`. You don't need to run `p10k configure` on every machine or every time you (re)install powerlevel10k. Keep using the config that you like.

**Comment by rwmitchell** [comment]
It's good to have two backups of ```.p10k.zsh```.  Make the first backup after running ```p10k configure``` BEFORE making any changes.  Make the second backup after customizing it.

When updating pk10 and then needing to rerun configure, you can compare the first backup with the newly generated .p10k.zsh.   This will only show the changes made by p10k, making it easier to apply those changes to your version.

I guess that depends on how many changes you make, I make quite a few.

**Comment by romkatv** [comment]
You don't need to run `p10k configure` after an update. Just like you don't need to wipe your `.zshrc` after updating zsh.

If you like your prompt, keep `.p10k.zsh` and your prompt will keep working forever, even if you update powerlevel10k.

**Comment by rwmitchell** [comment]
No, not every time, but sometimes you do add new features.  If those features are desired, then rerunning configure is an easy way to pick them up.

**Comment by qdii** [comment]
Ah ok, so if I understand correctly: this feature isn't _required_, since people can just edit their `.p10k.zsh` and it's guaranteed to be backward-compatible, but it might still be _nice to have_ for those who prefer to get the latest gadgets by re-running `p10k configure`.

Would it make sense for me to send a PR for this feature?

**Comment by romkatv** [comment]
Where would you put parameters that control colors git status colors? I suppose in a config. That's `.p10k.zsh`, and the parameters are already in there. If we add a second config file, where do we stop?

**Comment by qdii** [comment]
I see your point.

I think what confuses me is that `.p10k.zsh` seems to be a file that I will occasionally want to regenerate occasionally with `p10k configure` to get the newest features, and so I would prefer to keep it untouched and put my customization in `.zshrc`, my window manager launcher code, etc.

But this problem goes way beyond the scope of this issue, so I'll close it: the preferred solution at this stage is to modify `.p10k.zsh`.
