### ISSUE TITLE
Dynamically loading p10k right-prompt segments. 

### ISSUE THREAD

**Issue by dzonekl** [romkatv/powerlevel10k#2535]
I am looking packaging / integrating  `zsh` theme into another `zsh` based CLI tool, and p(9..10)k shares the same idea I have about using the `zsh` right-prompt to show context.  If I am not mistaken, what I see from the p10k code, is that the `prompt_` functions are coded into the main zsh file. 

**What if these would be loadable (Like other .zsh plugins)?** 

First challenge for me is to understand the inner workings of the right prompt segments. Is there any documentation I can look at (I could contribute documentation on contributing prompt segments, while studying the code)

I understand it's not a small thing to ask for, but as this functionality for me is so important, I am willing to put time into it.

**Comment by romkatv** [comment]
If you want to implement a custom prompt segment, search for "example" in your `~/.p10k.zsh` (assuming you've run `p10k configure` and chosen any style other than *Pure*). In addition, read the output of `p10k help segment`. Lastly, there is a short demo here: https://github.com/romkatv/powerlevel10k/blob/master/README.md#extensible

**Comment by dzonekl** [comment]
Thanks @romkatv for pointing that out, I missed that going through the docs. So adding segments is supported, great stuff. 
I guess the function `prompt_my_segment_name` can be added to `.ZDOTDIR` or added to `$fpath` with perhaps `autoload` ?   Out of curiosity, why is most of the code in one main file `p10k.zsh` ? Is it for performance reasons ? 
I wonder because, it's challenging to grasp what's happening in there. Wouldn't be more manageable to group functionality in separate files and and source them ? or using `fpath` ? Not sure what the performance penalty is for sourcing or autoloading...

**Comment by romkatv** [comment]
> I guess the function `prompt_my_segment_name` can be added to `.ZDOTDIR`

I'm not sure what you mean by that.

> ... or added to `$fpath` with perhaps `autoload`?

You can autoload functions in zsh if that's what you are asking.

> Out of curiosity, why is most of the code in one main file `p10k.zsh` ?

No particular reason.

> it's challenging to grasp what's happening in there.

Interesting. For me, it isn't.

**Comment by dzonekl** [comment]
> > I guess the function `prompt_my_segment_name` can be added to `.ZDOTDIR`
> 
> I'm not sure what you mean by that.
.ZDOTDIR is a reference to where the `.zshrc` and other `.z*` files are located. So where the function could be loaded. 
Where would you put the function for user defined prompt segments ? 

> No particular reason.
> 
> > it's challenging to grasp what's happening in there.
> 
> Interesting. For me, it isn't.

The `prompt_` functions start at line 1125 and at 5934, this is 4809 out of 9421 
so that is 51% of the code if I am not mistaken. This means the other 49 % is p10k logic which 
does many things, like `instant prompt` `dealing with vcs`, `initialisation`, `caching`, `defining colors` and so on... 

This sits above and below the `prompt_functions` so that is 5000 lines of scrolling before I pass that point (Unless I know what to look for and could search for it). 

Then there is structure, with main functions and smaller functions, which belong together forming a piece of functionality. However I will only know that by navigating function calling and see what belongs together. Grouping them in a single file will it make it quicker to grasp.

When grouped, you would name them, and then these would be easy to comprehend and you could even throw in some unit tests, to avoid regression.

`typeset -g` is used 253 times in the code. So these vars need to be accessed globally by this whole code base? 

I have never build large `.zsh` prior to the project I am doing now, and there I stick to separation of concern, modularity, var scoping to make working with code very pleasant, readable, testable .. But perhaps I am naive and a massive single 10k file with many globals is the way to go. 

Now I am tempted to chop this up...

**Comment by romkatv** [comment]
> .ZDOTDIR is a reference to where the .zshrc and other .z* files are located. So where the function could be loaded.

If you want to autoload the function, you need to put it in a directory listed in `fpath`. `$ZDOTDIR` is not in `fpath` by default.

> Where would you put the function for user defined prompt segments?

`.p10k.zsh` is a reasonable choice but you can put it anywhere you like. 

> Now I am tempted to chop this up...

Yeah, let's close the issue? I believe I've answered your questions?

**Comment by dzonekl** [comment]
Yes, closing thank you.
