### ISSUE TITLE
VCS Icon for GitLab (self hosted) not working

### ISSUE THREAD

**Issue by mlschindler** [romkatv/powerlevel10k#2537]
We run a self hosted gitlab server. this used to not be a problem as the VCS prompt elements would populate fine with the GitLab icon. Now it just uses the git icon. GitHub, etc work fine. I think this is because the field parser expects a domain of *.gitlab.com when attempting to do an icon lookup, though that wouldn't explain why this used to work fine. 

Any ideas?

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
typeset -p VCS_STATUS_REMOTE_URL
```

**Comment by mlschindler** [comment]
`typeset VCS_STATUS_REMOTE_URL=ssh://git@gitlab-master.[redacted].com:12051/tools`

I have redacted the apex domain

**Comment by romkatv** [comment]
Thanks.

The change in the icon is caused by https://github.com/romkatv/powerlevel10k/commit/7fd76370f53f87f956c811766a452c83ced4014b. Please take a look at this commit's description.

The icons are now more meaningful: a GitLab logo means you are pushing to gitlab.com. I can imagine that it may be important for you to know whether you are pushing to gitlab.com or to `gitlab-master.[redacted].com`, so by default icons aren't the same for these remotes.

You can go to the old behavior by putting the following parameter in `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_VCS_GIT_REMOTE_ICONS=(
  '*github*' VCS_GIT_GITHUB_ICON
  '*gitlab*' VCS_GIT_GITHUB_ICON
  '*'        VCS_GIT_ICON
)
```

You can also set `POWERLEVEL9K_VCS_GIT_REMOTE_ICONS` in a way that will give you a different icon for `gitlab-master.[redacted].com`, or even a different icon for individual repos. The commit I linked above shows how.

**Comment by juhannc** [comment]
Given the commit message in 7fd7637, is there an easy way to incorporate the company logo or do I need to (re-)patch my fonts?

**Comment by romkatv** [comment]
Your terminal can display only glyphs that exist in your font(s).

**Comment by juhannc** [comment]
Thank you, guess I have to re-patch then

**Comment by romkatv** [comment]
You have to modify your font(s) only if you intend to display a glyph that isn't already present there. You can do that, of course, but I personally wouldn't. There are likely many glyphs in the font that you could use to label git repos hosted on your company's hosted gitlab instance.

**Comment by romkatv** [comment]
It may not be clear from the commit comment but you can do this:

```zsh
POWERLEVEL9K_VCS_GIT_DLR_ICON='DLR'
```

It can be any text. Does not have to be a logo.

**Comment by juhannc** [comment]
Someone read my GitHub profile 😄 

But that's actually a nice idea, thank you! :)

**Comment by juhannc** [comment]
One final question though, where exactly would I need to put the

```text
typeset -g POWERLEVEL9K_VCS_GIT_REMOTE_ICONS=(
      'company-gitlab-url' VCS_GIT_MY_DLR_ICON
    )
POWERLEVEL9K_VCS_GIT_DLR_ICON='DLR'
```

text?

Right before the `[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh` in my `.zshrc`? Right after it? somewhere inside the `.p10k.zsh`?

**Comment by romkatv** [comment]
> Someone read my GitHub profile 😄

Ah, now I see my mistake. I should've looked it up before making presumptions: https://github.com/search?q=%22gitlab-master%22&type=code

> somewhere inside the `.p10k.zsh`?

Yes, `.p10k.zsh` is the standard name for a powerlevel10k config. Search for "POWERLEVEL9K_VCS_" in there and add your parameters somewhere in that section.

**Comment by juhannc** [comment]
> > Someone read my GitHub profile 😄
> 
> Ah, now I see my mistake. I should've looked it up before making presumptions: [github.com/search?q=%22gitlab-master%22&type=code](https://github.com/search?q=%22gitlab-master%22&type=code)

That's not quite our GitLab URL, but I guess one could easily figure it out by scanning other GitHub repos from my company and trying to find references to our GitLab :D

> > somewhere inside the `.p10k.zsh`?
> 
> Yes, `.p10k.zsh` is the standard name for a powerlevel10k config. Search for "POWERLEVEL9K_VCS_" in there and add your parameters somewhere in that section.

I did that, and also used the opportunity to re-create my powerlevel10k config file. However, if I put

```shell
  typeset -g POWERLEVEL9K_VCS_GIT_REMOTE_ICONS=(
      '*dlr*' VCS_GIT_DLR_ICON
      '?*'    VCS_GIT_ICON
      '*'     ''
    )
  POWERLEVEL9K_VCS_GIT_DLR_ICON='DLR'
```

in my config file (right at the start of the [ vcs: git status ] section), it overwrites the default settings from [`powerlevel10k/internal/p10k.zsh`](https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L7398-L7427). Is there a way to only add additional remote icons or would I need to copy over the default icons?

**Comment by romkatv** [comment]
There is no way to add extra elements to the default value of `POWERLEVEL9K_VCS_GIT_REMOTE_ICONS`. You can only override this parameter completely.

**Comment by juhannc** [comment]
Alright, thank you :)

**Comment by rwmitchell** [comment]
@juhannc If it is ok to share, I'd like to see the final prompt you come up with.

**Comment by juhannc** [comment]
> @juhannc If it is ok to share, I'd like to see the final prompt you come up with.

Do you mean my `p10k.zsh` config? Or just my `POWERLEVEL9K_VCS_GIT_REMOTE_ICONS`? I'm sorry, I cannot quite follow

**Comment by rwmitchell** [comment]
A screenshot of the actual prompt with the custom git icon.
The relevant settings to get that would also be nice.
I'm unclear where the VCS_GIT_DLR_ICON came from.

**Comment by romkatv** [comment]
> I'm unclear where the VCS_GIT_DLR_ICON came from.

See https://github.com/romkatv/powerlevel10k/commit/7fd76370f53f87f956c811766a452c83ced4014b.

**Comment by juhannc** [comment]
> A screenshot of the actual prompt with the custom git icon. The relevant settings to get that would also be nice. I'm unclear where the VCS_GIT_DLR_ICON came from.

In my `p10k.zsh`:

```shell
  #####################################[ vcs: git status ]######################################
  # Custom git repo indicators.
  # They are based on the official list from
  # https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L7398-L7427
  # It should be checked periodically for updates.
  typeset -g POWERLEVEL9K_VCS_GIT_REMOTE_ICONS=(
      'archlinux.org'                  VCS_GIT_ARCHLINUX_ICON
      'dev.azure.com|visualstudio.com' VCS_GIT_AZURE_ICON
      'bitbucket.org'                  VCS_GIT_BITBUCKET_ICON
      'codeberg.org'                   VCS_GIT_CODEBERG_ICON
      'debian.org'                     VCS_GIT_DEBIAN_ICON
      'freebsd.org'                    VCS_GIT_FREEBSD_ICON
      'freedesktop.org'                VCS_GIT_FREEDESKTOP_ICON
      'gitea.com|gitea.io'             VCS_GIT_GITEA_ICON
      'github.com'                     VCS_GIT_GITHUB_ICON
      'gitlab.com'                     VCS_GIT_GITLAB_ICON
      'gnome.org'                      VCS_GIT_GNOME_ICON
      'gnu.org'                        VCS_GIT_GNU_ICON
      'kde.org'                        VCS_GIT_KDE_ICON
      'kernel.org'                     VCS_GIT_LINUX_ICON
      'sourcehut.org'                  VCS_GIT_SOURCEHUT_ICON
      '*dlr*'                          VCS_GIT_DLR_ICON
      '?*'                             VCS_GIT_ICON
      '*'                              ''
    )
  POWERLEVEL9K_VCS_GIT_DLR_ICON='DLR'
```

This results in:

<img width="813" alt="Bildschirmfoto 2024-01-17 um 17 00 24" src="https://github.com/romkatv/powerlevel10k/assets/16680666/3b7b25c4-3fde-4f94-889c-de47c120213d">

**Comment by romkatv** [comment]
I don't think any values of your `POWERLEVEL9K_VCS_GIT_REMOTE_ICONS` other than the last 3 (`*dlr*`, `?*` and `*`) have any effect. `$VCS_STATUS_REMOTE_URL` must fully match these patterns for them to work. Here's the default pattern for GitHub: `(|[A-Za-z0-9][A-Za-z0-9+.-]#://)(|[^:/?#]#[.@])((#i)github.com)(|[/:?#]*)`. Note that it contains a bunch of other things apart from "github.com".

**Comment by juhannc** [comment]
Actually, it appears I made an error when I tested it earlier. Because I only get the generic git icon for GitHub repos now with my config. But it doesn't matter if I'm using the full config or just my companies url

**Comment by mlschindler** [comment]
> Thanks.
> 
> The change in the icon is caused by [7fd7637](https://github.com/romkatv/powerlevel10k/commit/7fd76370f53f87f956c811766a452c83ced4014b). Please take a look at this commit's description.
> 
> The icons are now more meaningful: a GitLab logo means you are pushing to gitlab.com. I can imagine that it may be important for you to know whether you are pushing to gitlab.com or to `gitlab-master.[redacted].com`, so by default icons aren't the same for these remotes.
> 
> You can go to the old behavior by putting the following parameter in `~/.p10k.zsh`:
> 
> ```shell
> typeset -g POWERLEVEL9K_VCS_GIT_REMOTE_ICONS=(
>   '*github*' VCS_GIT_GITHUB_ICON
>   '*gitlab*' VCS_GIT_GITHUB_ICON
>   '*'        VCS_GIT_ICON
> )
> ```
> 
> You can also set `POWERLEVEL9K_VCS_GIT_REMOTE_ICONS` in a way that will give you a different icon for `gitlab-master.[redacted].com`, or even a different icon for individual repos. The commit I linked above shows how.


Thank you @romkatv this worked perfectly for me!
