### ISSUE TITLE
git status color

### ISSUE THREAD

**Issue by rwmitchell** [romkatv/powerlevel10k#2541]
Is there a variable containing the current git status color?

the different vcs background colors can be set in .p10krc, but I don't see how to  find the current status color being used.

I have my own vcs add-on segment to show the most recent tag string, but I don't know how to set the background color to match the vcs segment.

**Comment by romkatv** [comment]
> Is there a variable containing the current git status color?

No.

> I have my own vcs add-on segment to show the most recent tag string, but I don't know how to set the background color to match the vcs segment.

If you have `my_git_formatter`, you can incorporate extra data in there. This function does not need to specify the background color, for this comes out automatically.

Pro tip: get rid of background colors altogether.

**Comment by rwmitchell** [comment]
I had been using ```my_git_formatter``` but recently stopped because I preferred the glyphs over the ascii git symbols.  Is there a way for it to use the nerd font glyphs - or more likely, did I do something in it to break them from being used?

Here is my git tag segment:

```
function prompt_git_tag() {
  GIT_TAG=${$(git describe --tags 2> /dev/null)%-*}
  [[ $GIT_TAG > "" ]] && p10k segment -f 124 -b 2 -t " %B${GIT_TAG}%b" # bold TAG red
}
```

and use it as:

```
    vcs                     # git status
    git_tag_joined          # show tag/version info
```

When I remove ```-b 2``` I get a black background segment


My test example with the background color is:

<img width="287" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/15944841/e0aec678-d5bf-4515-9e81-88c82e8e02fe">


and with ```-b 2``` removed:

<img width="293" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/15944841/dda55f6a-4130-48d7-96f8-66914094fdd3">

**Comment by romkatv** [comment]
> I had been using `my_git_formatter` but recently stopped because I preferred the glyphs over the ascii git symbols. Is there a way for it to use the nerd font glyphs

Of course. You can use any glyphs in there in place of the ascii characters. In fact, the default code isn't limited to ascii: `⇡` isn't ascii.

`my_git_formatter` gives you freedom. This is why it's in the default configs generated by the wizard.


> Here is my git tag segment:
> 
> ```
> function prompt_git_tag() {
>   GIT_TAG=${$(git describe --tags 2> /dev/null)%-*}
>   [[ $GIT_TAG > "" ]] && p10k segment -f 124 -b 2 -t " %B${GIT_TAG}%b" # bold TAG red
> }
> ```

Note that this can slow down your prompt quite a bit. On my machine, it slows down prompt by about 10x when the current working directory is a medium size repo. In other words, it increases the lag on every command by 900%.

**Comment by rwmitchell** [comment]
I must be doing something wrong then, when I set:  ```typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true``` the git symbols revert to simple ascii chars.

<img width="269" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/15944841/3cb1a7f3-a6f4-42d4-8591-67a804a00a55">

Does to require manually setting all of the *VCS_*_ICON vars?  If so, they should be included in my_git_formatter()

The prompt still seems responsive on my system, maybe my repos are just really simple or my meat cpu is too slow to notice.

**Comment by romkatv** [comment]
The symbols are defined by `my_git_formatter`. It should be easy to understand what it does if you take a look. You don't have to define or to refer to `VCS_ICON` parameters. If you want the function to print `BLAH` instead of `!`, replace `!` with `BLAH`. It's really that easy.

You can benchmark prompt with https://github.com/romkatv/zsh-bench.
