### ISSUE TITLE
Show the directory where the command was executed

### ISSUE THREAD

**Issue by aohanhongzhi** [romkatv/powerlevel10k#2542]
How do I set it up so that the path of the history command is also shown, so that I know what directory the command was executed in?

<img width="532" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/37319319/6afd737e-5cc3-4d4e-aa7f-acfdcae6a1f8">

**Comment by romkatv** [comment]
Run `p10k configure` and answer **No** when the wizard asks you whether you want to enable *Transient Prompt*.

**Comment by aohanhongzhi** [comment]
> Run `p10k configure` and answer **No** when the wizard asks you whether you want to enable _Transient Prompt_.

thank you very much!

<img width="559" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/37319319/ced1f66d-ad63-4ce1-8334-7f4563ae5abe">
