### ISSUE TITLE
[WARNING]: In ubuntu Console output during zsh initialization detected.

### ISSUE THREAD

**Issue by RoshanKhetpal** [romkatv/powerlevel10k#2544]
I feel frustrated every time I open my terminal and see a huge block of text.

```
[WARNING]: Console output during zsh initialization detected.
When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows 

```

I am currently using Ubuntu 22.04, and despite trying multiple solutions, I am still unable to resolve this issue. I have configured p10k four times, but it still doesn't work for me.

Every time I run this `echo $POWERLEVEL9K_INSTANT_PROMPT` Could you provide me with the command to check the selected prompt in a new terminal tab? Currently, it keeps displaying the same message.
![Screenshot from 2024-01-22 20-54-09](https://github.com/romkatv/powerlevel10k/assets/112322609/f2253cb7-80bb-4589-a3ea-c039691c74b9)

**Comment by cerebrl** [comment]
Can we assume that you've run the `typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet` or `typeset -g POWERLEVEL9K_INSTANT_PROMPT=off` manually?

**Comment by RoshanKhetpal** [comment]
> Can we assume that you've run the `typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet` or `typeset -g POWERLEVEL9K_INSTANT_PROMPT=off` manually?

Yes, these are the same commands I'm getting in the terminal. Even I've tried by changing version `typeset -g POWERLEVEL10K_INSTANT_PROMPT=quiet`, despite my efforts, the warning screen remains visible.

**Comment by romkatv** [comment]
Please execute the following command after you see the warning, and post the output here.

```zsh
typeset -p P9K_STARTUP_CONSOLE_OUTPUT
```

**Comment by RoshanKhetpal** [comment]
> Please execute the following command after you see the warning, and post the output here.
> 
> ```shell
> typeset -p P9K_STARTUP_CONSOLE_OUTPUT
> ```

Thanks for the swift reply. I've executed this command and got this message.
![Screenshot from 2024-01-22 22-43-34](https://github.com/romkatv/powerlevel10k/assets/112322609/206ed8c0-5561-4cd1-83ae-50f4b4af15e9)

**Comment by romkatv** [comment]
Can yo confirm that you actually see this message from oh-my-zsh every time you start your terminal? This is the most important part of the error message. You've posted the boilerplate in the issue description but not the actual error.

The solution is to open `~/.zshrc` and delete this line:

```zsh
ZSH_THEME="powerlevel10k/powerlevel10k"
```

**Comment by RoshanKhetpal** [comment]
> Can yo confirm that you actually see this message from oh-my-zsh every time you start your terminal? This is the most important part of the error message. You've posted the boilerplate in the issue description but not the actual error.
> 
> The solution is to open `~/.zshrc` and delete this line:
> 
> ```shell
> ZSH_THEME="powerlevel10k/powerlevel10k"
> ```
Thank you very much, it's working, I've removed `ZSH_THEME="powerlevel10k/powerlevel10k"` from line number 18 from `~/.zshrc` configuration file.
![Screenshot from 2024-01-23 12-36-44](https://github.com/romkatv/powerlevel10k/assets/112322609/4b9c0fe2-8177-4d79-a224-e0841ec6000d)

 And this is a good and short trick because I did this in a different. But thanks for the short trick.

#### The solution I tried, but I would highly recommend you to follow @romkatv https://github.com/romkatv/powerlevel10k/issues/2544#issuecomment-1904460094 this trick to remove that verbose prompt screen from your terminal.

#### The solution I tried 👇🏻👇🏻

Here's the solution, after stumbling through various solutions I finally found a solution.

If you are getting this every time you open your terminal👇🏻👇🏻
![Screenshot from 2024-01-22 21-41-52](https://github.com/romkatv/powerlevel10k/assets/112322609/592ff94d-23f6-46ca-8df8-00ba99526c89)

To solve this, you need to reconfigure your powerlevel10k, open up the terminal, and run this command `p10k configure`.
set all the styles you want. But when you're on this screen that says `Instant Prompt Mode`, you need to take care of this just type `2` to select `quiet` prompt. After this, you won't be getting those warnings again.


![Screenshot from 2024-01-22 21-48-43](https://github.com/romkatv/powerlevel10k/assets/112322609/e84bca3a-2b59-4029-a647-78611224dd02)

Previously, I selected `verbose`, but if this command `typeset -g POWERLEVEL10K_INSTANT_PROMPT=quiet` is not working, then reconfiguring is the only solution.

We just need to select `off` or `quiet` prompt. But I would recommend you to select `quiet` option.

There we go, I'm not getting those warnings or suggestions anymore.

![Screenshot from 2024-01-22 22-20-21](https://github.com/romkatv/powerlevel10k/assets/112322609/2015dbb7-1831-417e-a9e6-69ffe09d26d7)

But still I'm getting this `[oh-my-zsh] theme 'powerlevel10k/powerlevel10k' not found` this text in one line. this is because My powerlevel10k theme is not found in [oh-my-zsh] configuration. So in order to solve this, you just need to copy your `powerlevel10k` folder from your home directory, and paste it to your `.oh-my-zsh/themes/`, and you're good to go.

Let's see these following steps practically👍

**Step 1-> Copy `powerlevel10k folder.**
![Screenshot from 2024-01-22 22-29-55](https://github.com/romkatv/powerlevel10k/assets/112322609/d0294cac-8260-42b5-a3fd-1b8db64cda55)

**Step 2-> paste it to your `.oh-my-zsh/themes/`**
![Screenshot from 2024-01-22 22-30-51](https://github.com/romkatv/powerlevel10k/assets/112322609/5eddb7dc-1fa0-418e-ade0-2adac4900421)

**Step 3-> Here as you can see the `powerlevel10k` folder is visible in `themes` folder.**
![Screenshot from 2024-01-22 22-31-37](https://github.com/romkatv/powerlevel10k/assets/112322609/92e05ab1-03ac-4e1a-83c9-97ca9775d477)

**And now I'm getting a clean terminal.**
![Screenshot from 2024-01-22 22-39-22](https://github.com/romkatv/powerlevel10k/assets/112322609/72fccca9-f37a-4e14-85b0-765ff1b7775d)


#### I just showed you the second way to that, but still I would recommend you all to follow this https://github.com/romkatv/powerlevel10k/issues/2544#issuecomment-1904460094

**Comment by romkatv** [comment]
> The solution I tried, but I would highly recommend you to follow @romkatv [#2544 (comment)](https://github.com/romkatv/powerlevel10k/issues/2544#issuecomment-1904460094) this trick to remove that verbose prompt screen from your terminal.

You don't need to do that. The solution I posted earlier is the right one.

> I just showed you the second way to that

You've ended up loading powerlevel10k twice, from two different places. I highly recommend that you undo what you've done. If you've added `SH_THEME="powerlevel10k/powerlevel10k"` back, make sure to delete it.

In short: do what I suggested in my previous comment and don't do anything else. If you've done something else already, undo that.

**Comment by RoshanKhetpal** [comment]
@romkatv Yes, that's what I did after undoing everything, I followed your solution. Thank you so much for your kind response. The solution you provided was effective.
