### ISSUE TITLE
Powerlevel10k zsh theme on ios

### ISSUE THREAD

**Issue by myrayuoo** [romkatv/powerlevel10k#2547]
Whenever I use powerlevel10k for zsh on my iPhone, I seem to get errors every-time I startup my terminal

**Comment by romkatv** [comment]
How exactly have you installed powerlevel10k on iOS? What errors are you getting?

**Comment by myrayuoo** [comment]
My jailbroken phone using NewTerm with oh-my-zsh and Powerlevel10k theme encounters errors during startup these are the errors I get:

(anon) : sysopen:41: can't open file /dev/ fd/14: no su ch file or directory
[ERROR]: gitstatus failed to initialize.
Add the following parameter to ~/.shre for extra diagnostics on error:
GITSTATUS_LOG_LEVEL=DEBUG
Restart Zsh to retry gitstatus initialization:
exec zsh
_P9k_worker_start: sysopen: 12: can't open file / dev/ f d/11: no such file or directory
(anon) : sysopen: 41: can't open file / dev/ fd/12: no su ch file or directory
[ERROR]: gitstatus failed to initialize.
Add the following parameter to ~/zshre for extra diagnostics on error:
GITSTATUS_LOG_LEVEL=DEBUG
Restart Zsh to retry gitstatus initialization:

**Comment by romkatv** [comment]
This is caused by a bug in your jailbroken phone. It appears to be quite similar to this bug in iSH: https://github.com/ish-app/ish/issues/783

**Comment by blake2200** [comment]
> Whenever I use powerlevel10k for zsh on my iPhone, I seem to get errors every-time I startup my terminal

Miles DM me on ig x or reddit
