### ISSUE TITLE
Newline is not added when switching to root

### ISSUE THREAD

**Issue by maximbaz** [romkatv/powerlevel10k#255]
Here's how I made it work in my spaceship fork:

![image](https://user-images.githubusercontent.com/1177900/66505048-cf140580-eaca-11e9-885b-cd3badfb5f7a.png)

Here's how it works with p10k:

![image](https://user-images.githubusercontent.com/1177900/66505165-100c1a00-eacb-11e9-940b-233ab3e2c6e8.png)

Behavior in spaceship:
- Newline is not added on the very first line (✅ you have this solved properly)
- Newline is added when you switch to root (❌ this needs to be fixed)

The way I implemented it was [quite simple](https://github.com/maximbaz/spaceship-prompt/commit/a0d18062448e58e4db80a2a6c2fa669945a6688d):

```
[[ $UID == 0 ]] && SPACESHIP_PROMPT_NEED_NEWLINE=true
```

I tried to figure out how to patch p10k but couldn't wrap my head around it, maybe you could help with that 🙂

**Comment by romkatv** [comment]
p10k doesn't print new line before the first prompt. This is nice, because it allows you to print or not print that line depending on your needs.

It looks like you want root zsh to always have an empty line when it starts. You can do this by adding this to your `~/.zshrc`:

```zsh
(( EUID )) || echo
```

**Comment by maximbaz** [comment]
This is a good workaround, do you think it shouldn't become the default behavior for everybody?

**Comment by romkatv** [comment]
> This is a good workaround

This is not a workaround. I think this is much better than a parameter. You can use regular zsh to decide to print the first newline, and hence you can use any condition you want. Some people want that `echo` unconditionally, and they can have it.

> do you think it shouldn't become the default behavior for everybody?

Probably not. Isn't it weird that a root shell prints an empty line when it starts but non-root doesn't? How can I explain it to users?

Type `zsh` or `exec zsh` -- no empty line. Type `sudo zsh` or `exec sudo zsh` -- you have a new line. Now, while being root, once again type `zsh` or `exec zsh` -- this time you get the new lines even though it's the same commands as before. Odd?

**Comment by maximbaz** [comment]
Fair enough 😄 👍

**Comment by romkatv** [comment]
> ```shell
> (( EUID )) || echo
> ```

Heads up: Once you update powerlevel10k, this line will be printed automatically. You'll need to remove this workaround from your configs.

You also might find this useful: https://www.reddit.com/r/zsh/comments/dsh1g3/new_powerlevel10k_feature_transient_prompt/.

**Comment by maximbaz** [comment]
From the guy who loves weird setup ( 😝 ), a hash symbol is being printed now

![hash](https://user-images.githubusercontent.com/1177900/68479832-97b48800-0233-11ea-9b10-9438093312fa.gif)

**Comment by romkatv** [comment]
Thanks for the report. My initial attempts to reproduce this didn't succeed.

What terminal are you using?

Are you on the latest version of p10k? (Please update just in case.)

If you simply hit enter, is there an empty line between prompts?

This happens only when you remove `(( EUID )) || echo`? How does it look if you put that line back?

Are your dotfiiles on github up-to-date?

Does this happen if you disable instant prompt? (Add `POWERLEVEL9K_INSTANT_PROMPT=off` at the very top of `~/.zshrc`, before the instant prompt preamble.)

Does this happen if you disable p10k altogether and use the default zsh prompt?

**Comment by romkatv** [comment]
I think I figured it out. You are using `terminal` module from prezto which prints to stdout instead `$TTY`. I've already written a workaround for such bugs but there was a bug in my workaround. I've fixed it now. Please update powerlevel10k and try again.

**Comment by maximbaz** [comment]
Sorry my report wasn't detailed, but as usual you have solved it so quickly :) It's working fine now, your workaround is good!

**Comment by romkatv** [comment]
Thanks for the confirmation!
