### ISSUE TITLE
incorrect git remote icon after updating

### ISSUE THREAD

**Issue by kylegrieder** [romkatv/powerlevel10k#2550]
_I don't update my plugins and themes as often as I should. I recently implemented a package which will do this for me, so hopefully I'll identify similar issues sooner._

After updating, I noticed that on my company's gitlab repositories, I'm no longer seeing the `gitlab` icon in my prompt, I'm only seeing the standard `git` icon. I looked at the git history for this repo and noticed a [commit](https://github.com/romkatv/powerlevel10k/commit/7fd76370f53f87f956c811766a452c83ced4014b) about this from Dec 2 2023. The commit message is:

```
When you choose "Many icons" option in the configuration wizard,
git repositories with a remote receive an icon that depends on
the remote's URL. In the past the matching of the URL was rather
lax: both https://foo.bar/github.com and https://github.com.foo.bar/
were recognized as belonging to github.com. This is no longer the
case.

If you start seeing the plain "git" icon where you were used to
seeing a github/gitlab/etc logo, please open an issue. Make sure
to mention the remote URL of your repo.
```

This seems to be my exact issue. 

*Configuration nuances of note:*
I use ssh as opposed to https for all of my git pulls/pushes. I have a few different configurations in my .ssh/config file, specifically two different configs for gitlab, one being my personal gitlab ssh key, and another being for my company gitlab ssh key. This is outlined as follows, with sensitive data being replaced with `<slugs>`.

```
// .ssh/config

Host gitlab.com-<company_name>
    UseKeychain yes
    HostName gitlab.com
    User <company_gitlab_username>
    IdentityFile ~/.ssh/<company_ssh_key_filename>
 
 Host gitlab.com
    UseKeychain yes
    HostName gitlab.com
    User <personal_gitlab_username>
    IdentityFile ~/.ssh/<personal_ssh_key_filename>
```

What this means is that in my company git repos, the remote url looks something like this: 
`git@gitlab.com-<company_name>:<repo_name>`

In personal repos, the remote url looks like this:
`git@gitlab.com:<repo_name>`

**It should also be noted that in personal gitlab repos, I am seeing the `gitlab` icon, not the default `git` icon, meaning things are working as intended.**

Please let me know how I can help resolve this issue. I'm happy to troubleshoot and report my feedback.

**Comment by romkatv** [comment]
Thanks for the detailed description of the issue. From my point of view, everything is now working as intended: the remote is not on gitlab.com, so it was incorrect for powerlevel10k to display the GitLab logo in the past. Does this match your point of view?

If you want to adjust the icons shows in different git repos, see the commit message you've quoted. There is also a discussion in a recently filed issue that is quite similar: https://github.com/romkatv/powerlevel10k/issues/2537

**Comment by kylegrieder** [comment]
The remote is in gitlab.com though. Prior to updating, the `gitlab` icon was showing in my company repos.

**Comment by romkatv** [comment]
> The remote is in gitlab.com though.

That's a good point.

Do you have a suggestion of what I could do here?

**Comment by kylegrieder** [comment]
Its hard for me to know what a good suggestion would be because I don't have context of why it was changed in the first place. I thought it was working well before, when the matching rules were more lax. What problems were being caused by the less strict rules?

**Comment by romkatv** [comment]
> What problems were being caused by the less strict rules?

From the commit message: "In the past the matching of the URL was rather lax: both https://foo.bar/github.com and https://github.com.foo.bar/ were recognized as belonging to github.com."

**Comment by kylegrieder** [comment]
Ah yeah, that makes sense actually. Could a potential solution be to look at the url including the protocol and match based on `https://github.com/*` or `git@github.com:*`? That would prevent matching on `https://foo.bar/github.com` and `https://github.com.foo.bar`.

**Comment by romkatv** [comment]
That's what the current code does: it shows a GitHub logo when the remote URL belongs to the github.com domain. Similarly for GitLab. In git@gitlab.com-foo:bar, the domain is gitlab.com-foo. This is not the same domain as gitlab.com, so no GitLab logo.

**Comment by kylegrieder** [comment]
> That's what the current code does: it shows a GitHub logo when the remote URL belongs to the github.com domain. 

I'm talking about using both the protocol and domain, not just the domain itself. Based on the protocol (`https` or `git`), the "domain" might look different. If the protocol is `https` then the domain of the remote url would actually be that - the url domain. If the protocol is `git` (`ssh`), then the url "domain" isn't actually referencing the url domain, it is referencing the `Host` of the ssh config (see my initial issue description). 

>  In `git@gitlab.com-foo:bar`, the domain is gitlab.com-foo

Based on my initial issue description and what I've written above, this statement is false. in `git@gitlab.com-foo:bar` the "domain" isn't `gitlab.com-foo`. The `gitlab.com-foo` would be referencing a ssh config that looks like this:

```
# ~/.ssh/config

Host gitlab.com-foo
    HostName gitlab.com
    User gitlab-username
    IdentityFile ~/.ssh/gitlab-identity-file
```

If there isn't a matching profile in ~/.ssh/config, based on my experience, git assumes that the "domain" in the remote url is the `HostName`, and will default to using the `id_rsa` identity file. 

You could do separate logic for the `git` protocol which then parses the `~/.ssh/config` file, finds a matching config profile, and uses the `HostName` property from that config to find the right icon. If you don't find a patching config profile, you can fallback to https protocol logic.

**Comment by romkatv** [comment]
You can as easily configure redirections in `/etc/hosts`, which would equally affect git and https remotes. You can also slap an IP address of gitlab.com in the remote, too. Or you could configure you DNS server to alias foo.bar to gitlab.com. Plenty of other options that allow you to obscure the fact that the packets will eventually reach gitlab.com servers. Powerlevel10k cannot in general resolve these indirections, so it does something sensible and easy to understand: it shows a gitlab logo when the host within the remote URL is on the gitlab.com domain. It does that for all protocols.

**Comment by romkatv** [comment]
I don't see anything I can do in powerlevel10k to make things better w.r.t. these icons. The current code makes sense, and the recent change was a bug fix. You'd been accidentally relying on the bug, so your workflow was affected. Thankfully, I've added a way to configure icons based on remotes that allows you to get the previous behavior easily. So if you want those icons back, go ahead and configure stuff as described in the commit message. The issue I linked to has some examples, too.

**Comment by kylegrieder** [comment]
> You'd been accidentally relying on the bug

I don't see it as a bug, just a change in the feature itself. Lax matching isn't inherently a bug, just a difference of opinion. As an analogy - some people would call cyan more green, others would call it more blue (its technically in the middle on the spectrum). Doesn't mean either is wrong. 

I respect your analysis and will likely implement the solution in the thread you linked above. I have no intention of cloning repos hosted at gitub.com.foo.bar, or anything similar, so lax matching shouldn't have any adverse effects on my workflow.

**Comment by romkatv** [comment]
Consider this remote URL: https://gitlab.com/nsfw-stash.git. This used to be classified as BitBucket. 
I don't want to delve into the whole opinion vs bug discussion too much but this isn't some grey zone. It's plain wrong to classify this remote as BitBucket.

**Comment by kylegrieder** [comment]
I think that is two different issues. 

`https://gitlab.com/user/nsfw-stash.git` is clearly not a BitBucket url. I think its safe to say that is a bug. 

`github.com.foo.bar` could reasonably be expected to be a github url, depending on how strict your parsing is. Meaning, depending on how one might want the feature to work, maybe `github.com.foo.bar` should show the github icon. As the project owner/maintainer, its your right to determine that and I respect your decision.

**Comment by romkatv** [comment]
The previous version of the code had obviously wrong results on some inputs. The new code does not. Whether the new code is best is a matter of opinion, but there is no clear example showing that this code is wrong. And don't forget that you can easily achieve the previous behavior with a configuration option.
