### ISSUE TITLE
wezterm.sh triggers p10k instant prompt warning in tmux

### ISSUE THREAD

**Issue by stepanzak** [romkatv/powerlevel10k#2551]
Every time a new zsh prompt is opened in tmux, p10k prints this instant prompt error:
`[WARNING]: Console output during zsh initialization detected.`
and the usual instructions. After the line `-- console output produced during zsh initialization follows --`, no visible character is printed.
Behavior is exactly same as described in #2299 . Removing the file `/etc/profile.d/wezterm.sh` ( [this file](https://github.com/wez/wezterm/blob/main/assets/shell-integration/wezterm.sh) ) stops this from happening.
The only difference between this issue and #2299 that I found is that this time, `exec zsh` doesn't trigger the warning, only new tmux window or split. Doing `tmux split bash` that creates new split with bash running and then running `zsh` from that also doesn't trigger the warning.

**Comment by romkatv** [comment]
Please execute the following command after you see the warning, and post the output here.

```zsh
typeset -p P9K_STARTUP_CONSOLE_OUTPUT
```

**Comment by stepanzak** [comment]
`$ typeset -p P9K_STARTUP_CONSOLE_OUTPUT`
```
typeset -a P9K_STARTUP_CONSOLE_OUTPUT=( $'\C-[]133;A;cl=m;aid=2465\C-G\C-[Ptmux;\C-[\C-[]1337;SetUserVar=WEZTERM_PROG=\C-G\C-[\\\C-[Ptmux;\C-[\C-[]1337;SetUserVar=WEZTERM_USER=c3RlcGth\C-G\C-[\\\C-[Ptmux;\C-[\C-[]1337;SetUserVar=WEZTERM_IN_TMUX=MQ==\C-G\C-[\\\C-[Ptmux;\C-[\C-[]1337;SetUserVar=WEZTERM_HOST=c3RlcGlrdXYtbGFwdG9w\C-G\C-[\\\C-[Ptmux;\C-[\C-[]7;file://stepikuv-laptop/home/stepka/\C-[\\\C-[\\\C-[]7;file://stepikuv-laptop/home/stepka/\C-[\\' $'\C-[\\' )
```

**Comment by romkatv** [comment]
I think there is a bug in the transitive closure of your zsh startup files. Among other things, the following gets written to the terminal when you start it:

```text
\033Ptmux;\033\033]7;file://stepikuv-laptop/home/stepka/\033\\\033\\
```

The end of this sequence looks wrong. I think it should be `\033\033\\` and not `\033\\\033\\`. I haven't looked very closely but I think there might be a bug in `wezterm set-working-directory`. Could you run the following command and post the output?

```zsh
print -r -- ${(qqqq):-"$(wezterm set-working-directory)"}
```

**Comment by stepanzak** [comment]
`$ print -r -- ${(qqqq):-"$(wezterm set-working-directory)"}`
```
$'\033Ptmux;\033\033]7;file://stepikuv-laptop/home/stepka/\033\\\033\\\033]7;file://stepikuv-laptop/home/stepka/\033\\'
```

**Comment by romkatv** [comment]
Yep, that looks wrong to me. It should be like this:

```text
\033Ptmux;\033\033]7;file://stepikuv-laptop/home/stepka/\033\033\\\033\\\033]7;file://stepikuv-laptop/home/stepka/\033\\
```

Could you open a bug against wezterm? You don't need to mention powerlevel10k in the description, for the issue concerns just the output of `wezterm set-working-directory`. Give them the actual output you are seeing (your post above) and the expected output (this post of mine). Please link to this issue and post a link to the wezterm issue here.

**Comment by stepanzak** [comment]
It's now fixed on Wezterm's side.
