### ISSUE TITLE
gitstatus showing multiple branch names/same branch multiple times

### ISSUE THREAD

**Issue by pcroland** [romkatv/powerlevel10k#2555]
![img](https://telegra.ph//file/cd940719de2b8c04f1456.png)
I don't know if it's a p10k bug or not or if I messed up something in this repository.

**Comment by romkatv** [comment]
Where on your screenshot does gitstatus showing multiple branch names/same branch multiple times?

**Comment by romkatv** [comment]
Ah, do you mean "wip" after the branch name? It comes from here: https://github.com/romkatv/powerlevel10k/blob/62341054d8aa40ade03fc55bdbc95b9ff2d8d2b6/config/p10k-rainbow.zsh#L427-L430

If you don't want it, remove that block in `~/.p10k.zsh`.

**Comment by pcroland** [comment]
Oh, thank you. The repo does have a wip branch, I thought it was displaying that :D
