### ISSUE TITLE
Adding user in prompt char when root

### ISSUE THREAD

**Issue by mimosinnet** [romkatv/powerlevel10k#2558]
Modifying the POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION variable allows to show the root user in root context and, at the same time, have the context at the RIGHT_PROMPT: 

`typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='%(!.%n ❯.❯)'`

![2024 02 05_09 26 44](https://github.com/romkatv/powerlevel10k/assets/175618/4e68e78d-238c-49e0-b900-b1985d96c30b)

I wonder if this is the right approach, as I would need to add the same code to all the other prompt_char VI variables.

Thank you for this great work.

**Comment by romkatv** [comment]
Sure, if this modification does what you want, it's a fine way to achieve it.
