### ISSUE TITLE
Arrow prompt hex/rgb colors:

### ISSUE THREAD

**Issue by johanaller** [romkatv/powerlevel10k#2559]
Hi! What is rgb or hex of the default colors? When I run the configuration I pick this:

<img width="382" alt="Skärmavbild 2024-02-05 kl  11 11 44" src="https://github.com/romkatv/powerlevel10k/assets/93586332/2e32b400-514e-4b51-b3cb-aa1daedb8abf">

but instead I get these colors: 

<img width="665" alt="Skärmavbild 2024-02-05 kl  11 12 28" src="https://github.com/romkatv/powerlevel10k/assets/93586332/f081b70f-fc4d-48ec-a830-7bc31060e490">

Now I need the rgb or hex colors to set it to the same as in config.

Thanks!

**Comment by rwmitchell** [comment]
If you are referring to the green/yellow change, that is because your local git directory has changes.

**Comment by johanaller** [comment]
> If you are referring to the green/yellow change, that is because your local git directory has changes.

Thanks for the reply! Ok didn't know that. But even when going to unchanged directory I find that the green used is different from the screenshot / configuration colos. However, changing to iterm2 , iterm2 has the right colors. Must be something with the color mapping.

Notice the difference between the yellow colors.

I think this is an issue maybe with ansi color configuration. Will try to solve it that way.Thanks!

![Skärmavbild 2024-02-05 kl  13 44 11](https://github.com/romkatv/powerlevel10k/assets/93586332/9f36917f-ca27-4ecc-b814-d9b83b39a7b1)

**Comment by romkatv** [comment]
If you run `p10k configure` and note the green background color of git status, and then navigate to a clean git repo *in the same terminal*, you'll see the same exact shade of green. It won't necessarily be the same in a different terminal though. See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#how-do-i-change-prompt-colors

**Comment by johanaller** [comment]
OK thanks! Will be closing this!
