### ISSUE TITLE
Change color of listed folders - is LSCOLORS really correct?

### ISSUE THREAD

**Issue by johanaller** [romkatv/powerlevel10k#2560]
Hi! I want to change the color of listed folders:

![Skärmavbild 2024-02-05 kl  13 48 22](https://github.com/romkatv/powerlevel10k/assets/93586332/3e257463-2279-4523-91bb-c87cbc189bc1)

I have tried changinging the ansi colors as you can see. I changed both "Cyan" and "Blue" . But nothing changes,

<img width="591" alt="Skärmavbild 2024-02-05 kl  13 52 05" src="https://github.com/romkatv/powerlevel10k/assets/93586332/d051dc43-6df4-429b-9b13-9f2850c2f9c8">

I am trying to look into LSCOLORS variable that I read about in oher issue but it seems it doesn't take rgb colors, only ansi colors, but I find no staright forward way to convert from one to the other. And is LSColor really the right variable?

I also tried adding this to my .zshrc but nothing changes:

`export LSCOLORS=Exxxxxxxxxxxxxxxx
`

**Comment by mimosinnet** [comment]
As [stated in the documentation](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect), the color of listed folders is not defined by powerlevel10k. You should look at your distribution documentation.

**Comment by romkatv** [comment]
> As [stated in the documentation](https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect), the color of listed folders is not defined by powerlevel10k.

This is correct.
