### ISSUE TITLE
Understanding git tags and vcs segment

### ISSUE THREAD

**Issue by rwmitchell** [romkatv/powerlevel10k#2563]
Just noticed on a git repo cloned from github.com, the prompt shows the tag as part of the VCS info:

![image](https://github.com/romkatv/powerlevel10k/assets/15944841/4aaf7186-08b6-4380-be4d-77804295b0e8)

In the above example the tag is duplicated because I've added my own segment to do that.
My personal git repos ( kept on local RPis ) don't show the fancy tag info:

![image](https://github.com/romkatv/powerlevel10k/assets/15944841/09aa528b-70f3-4d33-bf17-19a3ac842203)

What am I doing different in my personal git repos that doesn't trigger the tag info from being shown?

git log shows:
* commit: 540505e1f355668a378e743fc61cfeb4592e9e41  (tag: v3.20)     # for mine
* commit: b18dd4f94335c3c774ed60bbfaa8241b0ade4631  (tag: v1.23.3)  # for the other (back a rev to not show HEAD)

Does the VCS segment show the tab because it is hosted on GitHub or is there something else going on?

**Comment by romkatv** [comment]
Docs: https://github.com/romkatv/powerlevel10k/blob/5bba4b849b04da665d9776930f47371ebb9974a4/gitstatus/gitstatus.plugin.zsh#L122-L123

**Comment by rwmitchell** [comment]
ah!  that was why I did that.  I wanted the tag info to show all the time.  The "-31" means there has been 31 commits since the v3.20 tag.
