### ISSUE TITLE
Bold Battery text

### ISSUE THREAD

**Issue by mayurankv** [romkatv/powerlevel10k#2566]
Is there a way to make the battery percentage bold? I can set `POWERLEVEL9K_BATTERY_CONTENT_EXPANSION` but I cannot determine what to put inside this to replicate the default behaviour in order to add `%B ... %b`. The code in p10k.zsh appears to be relatively complex so ideally I wouldn't duplicate that by pulling the battery percentage myself. I tried doing `%B$msg%b` but this didn't work as expected. I would appreciate any advice.

**Comment by romkatv** [comment]
Does this do what you are after?

```zsh
typeset -g POWERLEVEL9K_BATTERY_CONTENT_EXPANSION='%B${P9K_CONTENT}%b'
```

**Comment by mayurankv** [comment]
Yes it does, thank you!

**Comment by romkatv** [comment]
You are welcome.

In general, `POWERLEVEL9K_*` parameters are the ones that you set to affect powerlevel10k, and `P9K_*` parameters are the ones powerlevel10k sets for you. There are `P9K_*` parameters available within content expansions of various segments: `P9K_KUBECONTEXT_NAME` within `kubecontext`, `P9K_AWS_PROFILE` within `aws`, etc. In addition, `P9K_CONTENT` is available within expansions of all segments.

**Comment by mayurankv** [comment]
Ah that makes sense, that will definitely be really helpful!
