### ISSUE TITLE
Default Conda segment shows $CONDA_PREFIX if no environment active

### ISSUE THREAD

**Issue by mayurankv** [romkatv/powerlevel10k#2568]
The default conda segment shows $CONDA_PREFIX if no environment is active due to `typeset -g POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-${CONDA_PREFIX:t}}'`. This falls back onto `CONDA_PREFIX`'s (truncated) value. I would expect nothing to show when no environment is active. This can be fixed by replacing `${CONDA_PREFIX:t}` with `""` but I'm not sure this is the best way to fix it.

**Comment by romkatv** [comment]
Why do you have `CONDA_PREFIX` when no Conda environment is active? How did you achieve this?

**Comment by mayurankv** [comment]
Ahh dammit, I only rarely use conda and I'm still translating some badly written conigs from a few years ago. I'd hardcoded it in one of those botched files that I still source for some helper functions (same place HOME was hardcoded). Sorry for the naivety!
