### ISSUE TITLE
go_version doesn't work 

### ISSUE THREAD

**Issue by darkBuddha** [romkatv/powerlevel10k#2569]
Hi, on Debian 12, the Go version is not detected if installed from the Go website and in `/usr/local/go/bin/go`.

**Comment by romkatv** [comment]
Please run the following command and post its output here.

```zsh
(
  emulate -L zsh -o xtrace -o extended_glob
  rehash
  typeset -pm '*POWERLEVEL9K_GO_VERSION_PROJECT_ONLY|GOPATH|HOME'
  print -rC1 -- ./(../)#(go.mod)(#qN)
  which go
  go env GOPATH
  go version
)
```

**Comment by romkatv** [comment]
Switch your current directory to a go project and run the following command:

```zsh
(
  emulate -L zsh -o xtrace -o extended_glob
  typeset -pm 'POWERLEVEL9K_(LEFT|RIGHT)_PROMPT_ELEMENTS'
  print -rC1 -- ./(../)#(go.mod)(#qN)
)
```

Post a screenshot that shows the output of the command and your prompt.

**Comment by romkatv** [comment]
You can set `POWERLEVEL9K_GO_VERSION_PROJECT_ONLY` to `false` in `~/.p10k.zsh` if you want to always see `go_version`. In general, it's a good idea to check the config when the behavior of some prompt segment is surprising or unclear. The config is very long but it's not difficult to find the right section that corresponds to the segment in question. Here's `go_version`: https://github.com/romkatv/powerlevel10k/blob/5bba4b849b04da665d9776930f47371ebb9974a4/config/p10k-lean.zsh#L1040-L1046

Tool versions set by managers are shown only when an override is in effect.
