### ISSUE TITLE
[Android - Termux] Issue with gitstatus failing to initialize.

### ISSUE THREAD

**Issue by AvinashReddy3108** [romkatv/powerlevel10k#257]
**Describe the bug**
`gitstatus` fails to initialize in powerlevel10k installation in Android (Termux)

**To Reproduce**
1. Install Termux on your device from Google Play ([here](https://play.google.com/store/apps/details?id=com.termux))
2. Do `pkg upgrade -y` to update packages.
3. Install `git` and `zsh` using
```
pkg install git zsh -y
```
4. Install `oh-my-zsh` for Termux using
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
```
5. Do a [Manual Installation](https://github.com/romkatv/powerlevel10k#manual) of powerlevel10k
6. Exit Termux, open it again to complete the initial wizard.

**Expected behavior**
The shell should start up without the `gitstatus` issue.

**Additional context**
- This is a clean install of my ROM, Termux and p10k, no manual modification to the `.zshrc` file was made.

- Tried all the commands for extra disgonostics, but it doesn't show anything except my ROM info. (it shows only my zsh: 5.7.1 and uname -a output.)

**Comment by romkatv** [comment]
> Tried all the commands for extra disgonostics, but it doesn't show anything except my ROM info.

Could you post it?

**Comment by AvinashReddy3108** [comment]
> > Tried all the commands for extra diagnostics, but it doesn't show anything except my ROM info.
> 
> Could you post it?

The output of the diagnostics commands ? On it.
(Doing a clean install of Termux and p10k, just in case.)

**Comment by romkatv** [comment]
> > Could you post it?
> 
> The output of the diagnostics commands ?

Yes.

> Exit Termux, open it again to complete the initial wizard.

What do you mean by this? Did some application ask you to exit Termux?

Also, when powerlevel10k ran for the first time, did it present you with a configuration dialog? If yes, then did you see the error from gitstatus after exiting the dialog?

**Comment by AvinashReddy3108** [comment]
> What do you mean by this? Did some application ask you to exit Termux?

No, I did it for the sake of the configuration wizard.

> Also, when powerlevel10k ran for the first time, did it present you with a configuration dialog? If yes, then did you see the error from gitstatus after exiting the dialog?

Yeah, the configuration wizard went smooth, but I faced the gitstatus error right after the configuration was done.

**Comment by AvinashReddy3108** [comment]
Sometimes it asks me to execute this for diagnostics, which returns no output at all.
`GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K`

After exiting the Termux app and opening it again, it asks me to do this.
`GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start POWERLEVEL9K`

Which returns this. :arrow_down: 
```
gitstatus_start:181: failed to close file descriptor 14: bad file descriptor
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Your system information:

    zsh:      5.7.1
    uname -a: Linux localhost 3.10.108-lineageos-g506361dbc46e #1 SMP PREEMPT Sat Sep 15 02:00:43 EDT 2018 aarch64 Android

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
```

**Comment by romkatv** [comment]
Found a stupid bug that I've introduced recently. Should be fixed now. Please `git pull` the latest version of powerlevel10k and try again.

**Comment by AvinashReddy3108** [comment]
Ok, on it.

**Comment by AvinashReddy3108** [comment]
Yup, it works good now.
Thanks for the fix :+1:

**Comment by romkatv** [comment]
Thanks for reporting the bug!
