### ISSUE TITLE
How to show a loading indicator?

### ISSUE THREAD

**Issue by Myzel394** [romkatv/powerlevel10k#2570]
How do I start a loading indicator / loading text on startup? I found out about the instant prompt feature and tried to analyze the contents of the file, but it seems to me as if it's generated and shouldn't be edited manually.

Is there some way to show the prompt with the text "loading..."? (and make it vanish once everything is loaded)

I tried adding a simple "echo 'Loading...'" at the very beginning but that text keeps staying even everything is loaded.

**Comment by romkatv** [comment]
Add this to `~/.p10k.zsh`:

```zsh
function prompt_my_loading() {}

function instant_prompt_my_loading() {
  p10k segment -b yellow -f red -t loading
}
```

Then add `my_loading` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

Finally, restart zsh **twice** with `exec zsh`.

See `p10k help segment` and search "instant_prompt_example" within `~/.p10k.zsh` for docs.

**Comment by Myzel394** [comment]
Ahh that's smart, thank for the quick reply!
