### ISSUE TITLE
Slow prompt on certain directories

### ISSUE THREAD

**Issue by TimSousa1** [romkatv/powerlevel10k#2571]
When disabling p10k the issue goes away.
I've tried running zsh-bench but nothing out of the normal shows up..
Here are the results..
**with** p10k
```
creates_tty=0
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=0
has_git_prompt=1
first_prompt_lag_ms=17.113
first_command_lag_ms=368.443
command_lag_ms=34.912
input_lag_ms=10.211
exit_time_ms=338.010
```
**without** p10k
```
creates_tty=0
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=0
has_git_prompt=1
first_prompt_lag_ms=317.071
first_command_lag_ms=324.661
command_lag_ms=5.564
input_lag_ms=7.578
exit_time_ms=320.420
```
The weirdest thing to me is that this only happens inside certain directories

https://github.com/romkatv/powerlevel10k/assets/80922715/328b19ec-5f48-4f3a-9776-eee93884ba2f

Pretty weird huh?
Out of curiosity (but not with much hope) I tried multiple styles, with and without transient prompts and without the conda initialize section of the .zshrc file and the issue is still present
There might not be much in [my .p10k.zsh](https://github.com/TimSousa1/.config/blob/ccec0d58e6d43ec7ece03b6e7cc0f7b5d319f4a9/.p10k.zsh) (since it's just the default setup), but it might still be useful; and since we're at it you may have a look at [my .zshrc](https://github.com/TimSousa1/.config/blob/ccec0d58e6d43ec7ece03b6e7cc0f7b5d319f4a9/.zshrc) too

**Comment by romkatv** [comment]
Please add the following at the very top of `~/.zshrc`:

```
source ~/.p10k.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme
return
```

Restart zsh with `exec zsh`. Is prompt still slow in the home directory?

- If not, figure out which lines in `~/.zshrc` are to blame. You can do that by reverting the change described above and then commenting out one thing at a time and restarting zsh with `exec zsh` after each modification.
- If yes, figure out which prompt segments are to blame. You can do that by commenting out one element of `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` at a time within `~/.p10k.zsh` and restarting zsh with `exec zsh` after each modification.

P.S.

This looks unintended and potentially very slow: https://github.com/TimSousa1/.config/blob/ccec0d58e6d43ec7ece03b6e7cc0f7b5d319f4a9/.zshrc#L47-L49

You probably want to remove that regardless of what happens with the investigation.

**Comment by TimSousa1** [comment]
> P.S.
>
> This looks unintended and potentially very slow: https://github.com/TimSousa1/.config/blob/ccec0d58e6d43ec7ece03b6e7cc0f7b5d319f4a9/.zshrc#L47-L49
>
> You probably want to remove that regardless of what happens with the investigation.

Yeah.. looks like my old version was still in there..
I started by removing it and the issue went away
Silly me..
Thanks for the swift response!
Closing now
