### ISSUE TITLE
LXQt on Ubuntu is unable to display a few special characters

### ISSUE THREAD

**Issue by vin-blip** [romkatv/powerlevel10k#2574]
I've installed LXQT on my Ubuntu server and have set the default system fonts and terminal fonts as Meslo but still can't see the lock icon in both attempts. The first diamond icon appears just fine though. 

![RbxwWkBNUaVb](https://github.com/romkatv/powerlevel10k/assets/10230911/e9d3c35d-a08e-44ee-97de-bd0957763421)

Can anyone suggest any potential solutions, please?

**Comment by romkatv** [comment]
Try this font: https://github.com/romkatv/powerlevel10k/blob/master/font.md

**Comment by vin-blip** [comment]
Thanks @romkatv  - The Meslo NGF font worked a treat!
