### ISSUE TITLE
Moving zsh-config to ZDOTDIR/.p10k.zsh does not work

### ISSUE THREAD

**Issue by kingcrunch** [romkatv/powerlevel10k#2578]
Following #945 it should be possible to move the `.p10k.zsh`-file to `ZDOTDIR. It does not work.

```
# zshenv
export ZDOTDIR=$HOME/.config/zsh
. $HOME/.config/zsh/.zshenv
```

It seems, that powerlevel10k still uses $HOME/.p10k.zsh, because a) it works flawless if $HOME/.p10k.zsh exists (which is unexpected now), and b) it runs the configuration when I move the file to $ZDOTDIR/.p10k.zsh

**Comment by romkatv** [comment]
What is the output of the following command?

```
zsh --sourcetrace -lixc '' 2>&1 | grep -E '(<sourcetrace>|\.p10k\.zsh)$'
```

**Comment by blackhat-hemsworth** [comment]
I ran into the same issue and addressed it by changing 

`[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh`

to

`[[ ! -f ${ZDOTDIR}/.p10k.zsh ]] || source ${ZDOTDIR}/.p10k.zsh`

in .zshrc
