### ISSUE TITLE
segment displayed incorrectly when there is a hyperlink

### ISSUE THREAD

**Issue by Simon-Chenzw** [romkatv/powerlevel10k#2582]
```
p10k segment -b 1 -f 3 -i '⭐' -t $'\e]8;;http://example.com\e\\This is a link\e]8;;\e\\'
```
It works in my terminal, but the segment is in the wrong position.

![image](https://github.com/romkatv/powerlevel10k/assets/54612990/c44418b6-37a1-4196-be16-d3f22f30a6b9)

Is this the expected behavior? Is there any way to fix it?

**Comment by romkatv** [comment]
Note that this does not work either:

```zsh
RPS1=$'\e]8;;http://example.com\e\\This is a link\e]8;;\e\\' zsh -f
```

Non-printable characters within zsh prompt must be encased in `%{...%}`. Try this:

```zsh
p10k segment -b 1 -f 3 -i '⭐' -t $'%{\e]8;;http://example.com\e\\%}This is a link%{\e]8;;\e\\%}'
```

Docs: `man zshmisc`

**Comment by Simon-Chenzw** [comment]
Oh, I missed this part. Thank for the reply.
