### ISSUE TITLE
Terminal keeps printing file path when idle

### ISSUE THREAD

**Issue by turbanisch** [romkatv/powerlevel10k#2587]
I noticed a minor bug (I suppose) using powerlevel10k in the built-in MacOS terminal: The file path keeps getting printed although no command was used and the terminal was not resized. In longer file paths, sometimes it will print versions with abbreviated elements, sometimes without abbreviations. 

It's a minor annoyance for sure but still I'm wondering whether there is a way to turn it off? 

<img width="833" alt="Screenshot 2024-02-25 at 16 09 51" src="https://github.com/romkatv/powerlevel10k/assets/51969412/e6ab95c7-e4d9-4200-9c52-5886db1ff7fa">
<img width="833" alt="Screenshot 2024-02-25 at 16 49 08" src="https://github.com/romkatv/powerlevel10k/assets/51969412/e83645c8-ddc3-4ff8-851f-436d1c3715fd">

**Comment by romkatv** [comment]
Probably https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#horrific-mess-when-resizing-terminal-window
