### ISSUE TITLE
[ERORR] gitstatus faile to initialize

### ISSUE THREAD

**Issue by m4teoarg** [romkatv/powerlevel10k#2589]
prompt_vcs:17: vcs_info function definition file not found

A qué se debe este error?

**Comment by romkatv** [comment]
Please follow the instructions you've got with that error message.

**Comment by m4teoarg** [comment]
"The error persists, how can it be resolved?"
![Screenshot_20240226-111025 (1)](https://github.com/romkatv/powerlevel10k/assets/140857022/def263c2-a558-4f9b-ade5-682b2627fb83)

**Comment by romkatv** [comment]
This is either a bug in the zsh package, in which case you need to escalate it to whoever supplied you with the package. Or you've incorrectly modified `fpath`/`FPATH` in your zsh startup files, in which case you need to fix your startup files.

**Comment by m4teoarg** [comment]
"More information please, shell zsh installed correctly."

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
zsh -fc 'autoload -Uz +X add-zsh-hook || typeset -p fpath'
```

Post it as text. Do not post screenshots of your terminal.

**Comment by m4teoarg** [comment]
zsh -fc 'autoload -Uz +X add-zsh-hook || typeset -p fpath'
"The command doesn't display anything in the console."

**Comment by m4teoarg** [comment]
typeset -aT FPATH fpath=( /usr/local/share/zsh/site-functions /usr/share/zsh/vendor-functions /usr/share/zsh/vendor-completions /usr/share/zsh/functions/Calendar /usr/share/zsh/functions/Chpwd /usr/share/zsh/functions/Completion /usr/share/zsh/functions/Completion/AIX /usr/share/zsh/functions/Completion/BSD /usr/share/zsh/functions/Completion/Base /usr/share/zsh/functions/Completion/Cygwin /usr/share/zsh/functions/Completion/Darwin /usr/share/zsh/functions/Completion/Debian /usr/share/zsh/functions/Completion/Linux /usr/share/zsh/functions/Completion/Mandriva /usr/share/zsh/functions/Completion/Redhat /usr/share/zsh/functions/Completion/Solaris /usr/share/zsh/functions/Completion/Unix /usr/share/zsh/functions/Completion/X /usr/share/zsh/functions/Completion/Zsh /usr/share/zsh/functions/Completion/openSUSE /usr/share/zsh/functions/Exceptions /usr/share/zsh/functions/MIME /usr/share/zsh/functions/Math /usr/share/zsh/functions/Misc /usr/share/zsh/functions/Newuser /usr/share/zsh/functions/Prompts /usr/share/zsh/functions/TCP /usr/share/zsh/functions/VCS_Info /usr/share/zsh/functions/VCS_Info/Backends /usr/share/zsh/functions/Zftp /usr/share/zsh/functions/Zle )

**Comment by m4teoarg** [comment]
I don't understand what the problem is."

**Comment by romkatv** [comment]
This means your zsh startup files set `fpath`/`FPATH` to an incorrect value. It's probably in `.zshrc`. You can test this by adding the following line at the very top of `.zshrc`:

```zsh
return
```

Now once again run this command:

zsh -ic 'autoload -Uz +X add-zsh-hook || typeset -p fpath'

If it produces no output, the problem is in `.zshrc`. You can either try to identify it, or delete `.zshrc` and start over.

**Comment by m4teoarg** [comment]
zsh compinit: insecure files, run compaudit for list.
Ignore insecure files and continue [y] or abort compinit [n]? ytypeset -aT FPATH fpath=( /usr/local/share/zsh/site-functions /usr/share/zsh/vendor-functions /usr/share/zsh/vendor-completions /usr/share/zsh/functions/Calendar /usr/share/zsh/functions/Chpwd /usr/share/zsh/functions/Completion /usr/share/zsh/functions/Completion/AIX /usr/share/zsh/functions/Completion/BSD /usr/share/zsh/functions/Completion/Base /usr/share/zsh/functions/Completion/Cygwin /usr/share/zsh/functions/Completion/Darwin /usr/share/zsh/functions/Completion/Debian /usr/share/zsh/functions/Completion/Linux /usr/share/zsh/functions/Completion/Mandriva /usr/share/zsh/functions/Completion/Redhat /usr/share/zsh/functions/Completion/Solaris /usr/share/zsh/functions/Completion/Unix /usr/share/zsh/functions/Completion/X /usr/share/zsh/functions/Completion/Zsh /usr/share/zsh/functions/Completion/openSUSE /usr/share/zsh/functions/Exceptions /usr/share/zsh/functions/MIME /usr/share/zsh/functions/Math /usr/share/zsh/functions/Misc /usr/share/zsh/functions/Newuser /usr/share/zsh/functions/Prompts /usr/share/zsh/functions/TCP /usr/share/zsh/functions/VCS_Info /usr/share/zsh/functions/VCS_Info/Backends /usr/share/zsh/functions/Zftp /usr/share/zsh/functions/Zle )

**Comment by romkatv** [comment]
Try running this command:

```zsh
() {
  emulate -L zsh -o xtrace -o err_return
  command mkdir -p ~/zsh-backup
  command mv -f ~/.{zshenv,zprofile,zshrc,zlogin,zlogout,p10k.zsh}{,.zwc} ~/zsh-backup/ 2>/dev/null || builtin true
  command rm -rf ~/powerlevel10k
  command git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  builtin print -r 'POWERLEVEL9K_MODE=ascii' >>~/.p10k.zsh
  builtin print -r 'POWERLEVEL9K_DISABLE_HOT_RELOAD=true' >>~/.p10k.zsh
  builtin print -r 'POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)' >>~/.p10k.zsh
  builtin print -r 'POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()' >>~/.p10k.zsh
  builtin print -r 'source ~/.p10k.zsh' >>~/.zshrc
  builtin print -r 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
  builtin unset FPATH ZDOTDIR
  builtin exec zsh
}
```

Does it get rid of the errors?

**Comment by m4teoarg** [comment]
Is the script structure correct?

```#!/bin/zsh

setup_powerlevel10k() {
  emulate -L zsh -o xtrace -o err_return
  command mkdir -p ~/zsh-backup
  command mv -f ~/.{zshenv,zprofile,zshrc,zlogin,zlogout,p10k.zsh}{,.zwc} ~/zsh-backup/ 2>/dev/null || builtin true
  command rm -rf ~/powerlevel10k
  command git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
  builtin print -r 'POWERLEVEL9K_MODE=ascii'                     >>~/.p10k.zsh
  builtin print -r 'POWERLEVEL9K_DISABLE_HOT_RELOAD=true'        >>~/.p10k.zsh
  builtin print -r 'POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)' >>~/.p10k.zsh
  builtin print -r 'POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()'       >>~/.p10k.zsh
  builtin print -r 'source ~/.p10k.zsh'                             >>~/.zshrc
  builtin print -r 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
  builtin unset FPATH ZDOTDIR
  builtin exec zsh
}

setup_powerlevel10k```

Afterwards, can I run p10k configure?

**Comment by romkatv** [comment]
Copy the command I posted and paste it into a running instance of zsh. You can then run `p10k configure`.

**Comment by m4teoarg** [comment]
"Thank you very much"

**Comment by romkatv** [comment]
You are welcome. Note that your old zsh startup files are in `~/zsh-backup`.
