### ISSUE TITLE
[Feature Request] Always fresh git branch and status

### ISSUE THREAD

**Issue by CallumHoward** [romkatv/powerlevel10k#2590]
I have multiple shells open when working on a feature branch. When switching branches, if I want the current prompt to show up-to-date git branch and status information I need to switch to each one and press enter for it to be refreshed.

<img width="862" alt="Screenshot 2024-03-01 at 3 08 01 am" src="https://github.com/romkatv/powerlevel10k/assets/7144420/0da74990-0c2f-43e3-bf6b-727f63fbff6e">

It would be amazing if the status of all current idle prompts are updated when one of them is. Ideally some sort of pub/sub, but I would even be satisfied with a dumb solution like a 5 second slow poll to recheck git status.

**Comment by romkatv** [comment]
See https://github.com/romkatv/gitstatus/issues/368. Does that help?

**Comment by CallumHoward** [comment]
Amazing, that's working great. Thank you very much!

**Comment by romkatv** [comment]
You are very welcome.
