### ISSUE TITLE
Italic font does not installs

### ISSUE THREAD

**Issue by t-scutulatus** [romkatv/powerlevel10k#2591]
I tried installing the "MesloLGS NF Italic.ttf" without success.

Is it corrupted?  I can open and see it, but it doesn't installs.

**Comment by romkatv** [comment]
It's not corrupted.

**Comment by ved-asole** [comment]
Same issue. It does not installs for me also after clicking on install :  [MesloLGS NF Italic.ttf](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf)

Shows installing but then stops :

![image](https://github.com/user-attachments/assets/ffccfd93-88ec-4dec-bab6-eaf6d9c7c9a8)

![image](https://github.com/user-attachments/assets/5b7219a9-37f1-417b-acee-623dc8197423)

**Comment by romkatv** [comment]
It's still not corrupted. The issue is not with the font.
