### ISSUE TITLE
p10k extra space in prompt

### ISSUE THREAD

**Issue by gspeiliu** [romkatv/powerlevel10k#2594]
I am trying to use p10k and configure it shows conda environment and context on the left side.
It successfully shows the conda python envonrment but with an extra space.
The prompt is as follows
I just copy and paste the prompt in here.
╭─ Py (base)  lxxx@XXXX ~                                                                                          2m 49s
╰─❯

You can see that there are two spaces between the end of the close parenthesis and the beginning of my user name starting with l.
How can I get rid of one space from them, and BTW, how to make it doesn't start with Py (I mean delete Py at the beginning)

**Comment by romkatv** [comment]
> You can see that there are two spaces between the end of the close parenthesis and the beginning of my user name starting with l.

I see only one space in there.

```text
╭─ Py (base) lxxx@XXXX ~ 2m 49s
           ^.^
```

The first `^` is pointing at `)`, the second at `l`. The dot in between is aligned with the space.

> How can I get rid of one space from them, and BTW, how to make it doesn't start with Py (I mean delete Py at the beginning)

This is the icon of this prompt segment. If you use a capable font, it'll be a python logo. In ascii mode (which is what you appear to be using), it's "Py". Icons are great for prompt segments that you don't see all the time. Without the icon it can be confusing seeing something like "base" or "system" in prompt.

In any case, you hide the icon by setting its value to empty:

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION=
```
