### ISSUE TITLE
Battery icon not shown (NF 3.0)

### ISSUE THREAD

**Issue by dhnam** [romkatv/powerlevel10k#2596]
So I'm really loving p10k, and had been used it quite a while. (Thank you for making this wonderful theme)

Anyway, I custom-patched a font (which is happened to be nerd font v3.0 as I used docker), and applied the font.

There was a little bit of problem: battery icon is not shown properly.

![스크린샷 2024-03-09 012728](https://github.com/romkatv/powerlevel10k/assets/8546820/c8265f33-169c-4141-919c-af603d7d684a)

I was quite embarrassed, and edited `~/.p10k.zsh`. (btw I customized my p10k so I didn't want to use configure)

```
(...)
  # Defines character set used by powerlevel10k. It's best to let `p10k configure` set it for you.
  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  # When set to `moderate`, some icons will have an extra space after them. This is meant to avoid
  # icon overlap when using non-monospace fonts. When set to `none`, spaces are not added.
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
(...)
```

So I set my typeset to `nerdfont-v3`, and loaded p10k again - even halted entire system (I used wsl btw, so terminated it) and restarted, but still battery icon is not shown properly.

![스크린샷 2024-03-09 013156](https://github.com/romkatv/powerlevel10k/assets/8546820/6855382b-75ff-430c-9550-076ebe931376)

This is proof that font itself has battery icon - well, NF 3.0 battery icon, not icon removed.

**Comment by dhnam** [comment]
Alright, I edited my `~/.p10k.zsh` a little bit more.
![스크린샷 2024-03-09 020241](https://github.com/romkatv/powerlevel10k/assets/8546820/9c297e6a-73fd-41fb-b735-f275b81e82f0)

Looks like I need to change 'battery' section as well.

I edited this, so it'll be good, I hoped.

![스크린샷 2024-03-09 020214](https://github.com/romkatv/powerlevel10k/assets/8546820/cc9ee002-e751-427a-a3a1-cce1064f5b6b)

Well, it didn't go well.

**Comment by dhnam** [comment]
I slept; I woke up; and I see everything is working perfectly fine, somehow....?

![image](https://github.com/romkatv/powerlevel10k/assets/8546820/c56bf0fc-693d-4f44-a3f2-6b9c21918e94)

I don't understand it, but it works now.

**Comment by dhnam** [comment]
I cannot reproduce this. I'll close it.

**Comment by jacogasp** [comment]
Hello @dhnam, I used to have your issue with the battery icons.
I tried to change the battery stages character as you suggested and it worked, thanks!

```
# Battery pictograms going from low to high level of charge.
# typeset -g POWERLEVEL9K_BATTERY_STAGES='\uf58d\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'
typeset -g POWERLEVEL9K_BATTERY_STAGES='\UF008E\UF007A\UF007B\UF007C\UF007D\UF007E\UF007F\UF0080\UF0081\UF0082\UF0079'
```

I found also this conversion map that I leave here for reference https://gist.github.com/mischw/78e8e42c2ebb1069560a2fc4573b1425#file-convert_unicode_nerdfont3-py-L116
