### ISSUE TITLE
How to Change Color of GIT_REMOTE_ICONS

### ISSUE THREAD

**Issue by KadlagAkash** [romkatv/powerlevel10k#2597]
While customizing my colors in Powerlevel10k, I encountered a challenge in changing the color of the GitHub icon. 

<img width="899" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/100425384/72474b50-ccd7-47bc-b8a0-d0064a81796d">

I'm looking to set its color to #16, but couldn't find a straightforward way to do so. Any guidance would be much appreciated!

**Comment by romkatv** [comment]
The parameter you are looking for is called `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR`.

**Comment by KadlagAkash** [comment]
Hey Thanks ...



Added this in .pk10.zsh
<img width="857" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/100425384/94f8f9b0-80de-4fad-9cc2-4c502a4feaf4">



And All Set
<img width="805" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/100425384/5b4e1fff-194e-4eaa-8e39-37fd4eed7535">

**Comment by KadlagAkash** [comment]
Hey Thanks ...



Added this in .pk10.zsh
<img width="857" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/100425384/94f8f9b0-80de-4fad-9cc2-4c502a4feaf4">



And All Set
<img width="805" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/100425384/5b4e1fff-194e-4eaa-8e39-37fd4eed7535">

**Comment by romkatv** [comment]
Great!

Tip for the future: post code as text rather than as image. Text is a better medium for code.

**Comment by KadlagAkash** [comment]
Thanks for the valuable tip! 
Posting code as text makes a lot of sense. I'll make sure to follow this practice moving forward. 

Appreciate your guidance as I navigate through the nuances of contributing.
