### ISSUE TITLE
Update font installation instructions for MobaXTerm

### ISSUE THREAD

**Issue by ajhoffman1229** [romkatv/powerlevel10k#2599]
I was having some trouble installing the MesloLGS font on MobaXTerm using the instructions in the README here. Today, I stumbled on this page on Stack Exchange's superuser page that resolved the issue for me:
https://superuser.com/questions/1134268/mobaxterm-powerline-font-issue

If users have existing sessions, they will need to _change the fonts for the individual sessions_ rather than just the font in the program settings. Users can click the Sessions button (with the big star in the menu), right click on their session of choice and go to _Edit Session > Terminal Settings > Font settings_ to update the fonts for existing sessions.

**Comment by romkatv** [comment]
Thanks for filing the issue. I've updated the docs: https://github.com/romkatv/powerlevel10k/commit/d39e4268355f7a10f7758982db2a59e485d2659a

**Comment by ajhoffman1229** [comment]
Excellent, thanks for the quick response and update!
