### ISSUE TITLE
Using \local does not set variable

### ISSUE THREAD

**Issue by evolarium** [romkatv/powerlevel10k#26]
I have bisected the issue to 5ee0054298263d0043d2f6da35d3ea949b04f434, but I can't tell what change might be causing the issue.

To test, you can try:

\local var=1

As of that commit, the variable will not be set.  Prior to that, it was working fine.  I noticed the issue when conda stopped working, as it uses \local in it's functions to avoid aliases.

**Comment by romkatv** [comment]
Wow... Didn't think such thing was possible. The irony is palpable. Conda is being very clever with its use of `\local` instead of the regular `local` and gets burned.

Fixed. Please `git pull`.

**Comment by romkatv** [comment]
P.S. Thank you very much for reporting! And extra thanks for concise yet complete description of the problem.

**Comment by romkatv** [comment]
I believe this is fixed. Please reopen if not.
