### ISSUE TITLE
Helm custom segment integration

### ISSUE THREAD

**Issue by Hypn0sis** [romkatv/powerlevel10k#2601]
Hi there, 
not a real issue, I just wanted to know if there's someone that has already implemented a custom segment for Helm paths.
Thanks in advance.
Teo

**Comment by romkatv** [comment]
If you describe what you want the segment to do, I might be able to help.

**Comment by Hypn0sis** [comment]
I don't know exactly how to realize it, but I saw a ohmyzsh plugin (don't
know its name) that shows in prompt the version of the chart helm. I think
that it is necessary to parse the yaml file included in dir.

Il sab 16 mar 2024, 07:41 Roman Perepelitsa ***@***.***> ha
scritto:

**Comment by romkatv** [comment]
> shows in prompt the version of the chart helm

This isn't specific enough for me to understand what you need (I don't use helm myself). Closing.
