### ISSUE TITLE
Working tree indicators not working after distribution update

### ISSUE THREAD

**Issue by delanym** [romkatv/powerlevel10k#2604]
My shell is zsh. Since updating from Ubuntu Lobster to Minotaur the state of the working tree is not displayed correctly.
This is after a checkout to a different branch:

![image](https://github.com/romkatv/powerlevel10k/assets/5310238/34bb0014-4be9-4723-8495-44f5f1d75d4d)

If I open a new terminal the prompt displays correctly.

**Comment by romkatv** [comment]
Perhaps https://github.com/romkatv/powerlevel10k#incorrect-git-status-in-prompt?

Also seee https://github.com/romkatv/powerlevel10k/issues/2580.

**Comment by delanym** [comment]
`git config --global feature.manyFiles false` resolved the issue.

Seem skipHash is now supported in libgit2
https://github.com/romkatv/powerlevel10k/issues/2387#issuecomment-1993392997

**Comment by romkatv** [comment]
> Seem skipHash is now supported in libgit2
> [#2387 (comment)](https://github.com/romkatv/powerlevel10k/issues/2387#issuecomment-1993392997)

Yes, some kind of `skipHash ` support was added to libgit2 recently. I need to take a look but haven't gotten around to do doing it yet.

**Comment by ahmedelgabri** [comment]
Sorry to comment on an old issue, but I was just hitting the same problem. Setting `feature.manyFiles`, didn't fix it for me though.

```
▲ git config --get-all --show-origin feature.manyFiles
file:/Users/ahmedelgabri/.gitconfig     false
```

**Comment by delanym** [comment]
What version of os/git/powerlevel10k are you using?

**Comment by ahmedelgabri** [comment]
> What version of os/git/powerlevel10k are you using?

Two machines:

Machine one:

- M2, macOS 14.6.1 Sonoma
- git version 2.45.2
- powerlevel10k 1.20.0

Machine two:

- Intell, macOS 12.7.6 Monterey
- git version 2.45.2
- powerlevel10k 1.20.0

**Comment by ahmedelgabri** [comment]
I narrowed it down to that it's happening only when using the `pure` theme, other themes are working fine. So, for now, I switched to `lean` with a look similar to `pure`.
