### ISSUE TITLE
golang icon does not change

### ISSUE THREAD

**Issue by polo871209** [romkatv/powerlevel10k#2608]
Hi, 

I have uncomment this line but my terminal still shows the default one.
`typeset -g POWERLEVEL9K_ASDF_GOLANG_VISUAL_IDENTIFIER_EXPANSION='⭐'`
<img width="116" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/95681896/3e96db35-062e-477d-b8c0-7af1904ee258">

**Comment by romkatv** [comment]
Have you restarted zsh after making this change?

Are you sure this is `asdf` that you see in prompt? Does this segment disappear if you disable `asdf` segment?

**Comment by polo871209** [comment]
@romkatv you are right man... that is indeed not asdf... following line solve my problem! My bad, thanks for me instant respond

`POWERLEVEL9K_GO_VERSION_VISUAL_IDENTIFIER_EXPANSION`

**Comment by romkatv** [comment]
I'm glad you solved the problem.

By the way, you can use https://www.nerdfonts.com/cheat-sheet to find icons. If you type "go" in the search bar, you can see a few decent options for `go_version` icons. `\UE627` looks reasonable.
