### ISSUE TITLE
Font rendering error in Mac Terminal

### ISSUE THREAD

**Issue by DataSailor** [romkatv/powerlevel10k#2611]
I configured p10k in zsh and installed the recommended fonts.
But the display effect seems a bit off.

<img width="703" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/39119487/87999b57-3e94-4fed-83e5-8c1d5894f22a">

I'm not sure if this is a problem with the p10k theme, because it seems to display normally in the tabby terminal on the same machine.

How should I fix it?

**Comment by romkatv** [comment]
You might be able to make segment separators look a bit better by adjusting some kind of font height setting in the terminal options. I don't think there is a way to fix the mismatch in color between segment backgrounds and triangles at the edges of right and left prompt. It's the only terminal I know of with this particular defect.

All these issues disappear if you switch to Lean style. It also saves horizontal space and makes it easier to see the actual content of your prompt. You'll immediately see the difference in readability when looking at the current time segment, for example. It'll be even better with black (or nearly black) terminal background.

**Comment by DataSailor** [comment]
Thank you, I have now switched to the Lean style and it looks great.
