### ISSUE TITLE
Can't get Kubecontext to work

### ISSUE THREAD

**Issue by stepjanssen** [romkatv/powerlevel10k#2612]
I'm using OC for kubernetes. I checked .kube/config and the config file contains what it should, but p10k just won't show anything. I also disabled show on command, since I read it should always show 'default' in another issue, but that didn't work either.

Can it be a permissions issue? Or maybe the fact that I don't have kubectl installed, since I only use OC?

**Comment by romkatv** [comment]
What is OC?

**Comment by stepjanssen** [comment]
Openshift CLI, it's in the default config for 'show on command'.

**Comment by romkatv** [comment]
I see. The current implementation of kubecontext requires `kubectl`. Is there anything that makes it difficult for you install it?

**Comment by stepjanssen** [comment]
I don't think so. So installing `cubectl` next to `oc` should probably make kubecontext work for servers managed through `oc`?

**Comment by romkatv** [comment]
Try it.

**Comment by stepjanssen** [comment]
I did, it worked! Hopefully this issue helps someone down the line. Thanks for the help!

**Comment by romkatv** [comment]
Thanks for verifying and confirming that it works for setups like yours.
