### ISSUE TITLE
$<2> appearing at the left part of the prompt making the prompt overflow to next line

### ISSUE THREAD

**Issue by Coqueiro** [romkatv/powerlevel10k#2616]
Hello! I'm experiencing this weird `$<2>` symbol at the left part of the prompt, making the prompt overflow to the following line. Because of the nature of the symbol, it's tough to search on the internet to see if someone has the same issue.

![image](https://github.com/romkatv/powerlevel10k/assets/8795402/f0be539a-ae30-4322-8230-2a9392b5ecc7)

Does someone know what config might be causing this?

Terminal: Kitty
Client OS: MacOS Ventura
Remote OS: Raspbian 6.6 (connecting through ssh session)

---------

For SE indexing:
dollar sign less than sign 2 greater sign (dunno if it will be helpful, but 🤷 )

**Comment by Coqueiro** [comment]
Thanks for the guidance. I did precisely as you instructed, and the problem persists.
Also, since then, I have created sessions directly in Raspbian using LXTerminal and ssh through Windows' command line, and they didn't show the same visual glitch.

**Comment by romkatv** [comment]
> Thanks for the guidance. I did precisely as you instructed, and the problem persists.

Next, get your system to this state once again: you should have the same code snippet at the top of `.zshrc` and you should see `$<2>` in prompt after restarting your terminal. Once you are there, add the following line at the top of `.zshrc`, above even the code snippet you added there earlier.

```zsh
return
```

Restart your terminal. Do you still experience the visual glitch?

**Comment by Coqueiro** [comment]
No sign of the glitch, just the usual vanilla zsh:
<img width="331" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/8795402/7f5dfe84-84a5-4c90-98b1-483ff1ef11ac">

**Comment by romkatv** [comment]
Let's try to narrow it down further. Put this at the top of `~/.zshrc`:

```zsh
if [[ ! -e ~/powerlevel10k ]]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
fi
source ~/powerlevel10k/powerlevel10k.zsh-theme
POWERLEVEL9K_MODE=ascii
POWERLEVEL9K_DISABLE_HOT_RELOAD=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
return
```

Do you get `$<2>` with this setup?

(If you get the idea of what we are doing, you can continue on your own until you arrive at the smallest possible config that reproduces the problem.)

**Comment by Coqueiro** [comment]
I'll try once I'm at my home network.
I can try a few steps on my own as well. Unfortunately, I've been using the same powerlevel10k config for over four years now, and just recently, I started playing with it again, customizing my home server, so I feel like I forgot everything 😅

**Comment by mean-ui-thread** [comment]
In case it helps anyone else: I was getting this `$<2>` when `TERM` was `vt102` instead of `linux`.

I was able to resolve this issue by adding this line at the top of my `~/.zshrc`

```bash
[[ "$TERM" == "vt102" ]] && export TERM="linux"
```

and the `$<2>` went away
