### ISSUE TITLE
asdf python and active virtualenv with other asdf tools

### ISSUE THREAD

**Issue by fkabs** [romkatv/powerlevel10k#2619]
I am facing an issue and was wondering if anybody has a tip to fix this....
I am using asdf as my version manager and python virtual environments to isolate my projects. In the example below, I have defined _Ruby 3.3.0_ and _Python 3.11.6_ as my local asdf tools, as well as an active virtualenv _demoenv_. The right prompt shows the correct information:

<img width="1085" alt="01" src="https://github.com/romkatv/powerlevel10k/assets/1120646/7e26f254-1e29-49b2-829f-e8cf61bdee6b">

<p>&nbsp;</p>

I now want to disable the asdf python part of the asdf segment when an active virtualenv is detected. I'm using following fix in `~/.p10k.zsh` right now originally posted by @romkatv in https://github.com/romkatv/powerlevel10k/issues/481#issuecomment-727567290:

```zsh
function p10k-on-pre-prompt() {
  if [[ -n ${VIRTUAL_ENV-} ]]; then
    p10k display '*/asdf'=hide
  else
    p10k display '*/asdf'=show
  fi
}
```

<p>&nbsp;</p>

This of course does what it should do and disables the whole asdf segment:

<img width="1083" alt="02" src="https://github.com/romkatv/powerlevel10k/assets/1120646/9bd02574-a87f-48be-a56f-e358c510f140">

<p>&nbsp;</p>

Is there a possibility to only disable the "asdf python" part of the asdf segment when a virtualenv is detected or is this currently not possible as the asdf segment is rendered as a whole (with all active tools)?

**Comment by romkatv** [comment]
Try this:

```zsh
POWERLEVEL9K_ASDF_PYTHON_CONTENT_EXPANSION='${${${+VIRTUAL_ENV}/1}/0/$P9K_CONTENT}'
POWERLEVEL9K_ASDF_PYTHON_VISUAL_IDENTIFIER_EXPANSION='${${${+VIRTUAL_ENV}/1}/0/$P9K_VISUAL_IDENTIFIER}'
```

I haven't tested it. It might work.
