### ISSUE TITLE
/etc/zshenv weirdness prevents start

### ISSUE THREAD

**Issue by genedelisa** [romkatv/powerlevel10k#262]
I had one line in my /etc/zshenv files. Just  print "/etc/zshenv" so I knew it was being sourced.

I tried starting powerlevel10k, but got this in response:

gitstatus_start_impl:70: bad math expression: operand expected at `/etc/zshen...'

I though it was how I installed it. So, I tried using antibody and got the same thing. Downloaded this repo, same thing. I didn't see anyone complaining about this, so I figured the problem was me.

I commented out the print, and it still barfed.

I emptied out /etc/zshenv completely and it worked.

**Comment by romkatv** [comment]
Thanks for the report. Fixed. Please update powerlevel10k and try again.

P.S.

> I had one line in my /etc/zshenv files. Just print "/etc/zshenv" so I knew it was being sourced.

Brutal. Every `zsh` process sources this file. It's possible to disable sourcing of all other configuration files through command line flags, but not `/etc/zshenv`. Even `zsh --no-rcs --no-global-rcs -c '...'` will source it. If this file prints to stdout, stdout of all zsh processes will be amended. This will break all scripts that use `$(zsh -c '...')`.

If you must print from `/etc/zshenv`, I would recommend sending the output to stderr.

**Comment by genedelisa** [comment]
Wow, fixed on a Saturday morning! 

I just moved to zsh after 25 years of bash. I didn't need the print in /etc/zshenv,
I just wanted to see the startup sourcing in action to learn. 

Thanks for this project. It's a winner.

**Comment by romkatv** [comment]
> Wow, fixed on a Saturday morning!
> 
> I just moved to zsh after 25 years of bash. I didn't need the print in /etc/zshenv,
> I just wanted to see the startup sourcing in action to learn.

Makes sense. I usually use this:

- Show interactive startup: `zsh -xic ''`
- Show non-interactive startup: `zsh -xc ''`
- Show only global portion of interactive startup: `zsh -xifc ''`.
- Show only user-specific portion of interactive startup: `zsh -xidc ''`.

You get the idea.
