### ISSUE TITLE
who can tell me which url or ip address from p10k to use to test public_ip? it's important for me!!! 

### ISSUE THREAD

**Issue by anfan4730** [romkatv/powerlevel10k#2620]
I already browsed most of web page , but  can't help me find it and i also used tcpdump tool to try grab it and but  tcpdump tool told me more ip address ~~but i dont't know which.
i need someone help from who kown this answer,thanks.

**Comment by anfan4730** [comment]
![WeChata417064905395e71a270c6833fc1acae](https://github.com/romkatv/powerlevel10k/assets/165348670/6fa5d690-ae20-4070-96f4-49e7a38e3646)
![WeChata417064905395e71a270c6833fc1acae](https://github.com/romkatv/powerlevel10k/assets/165348670/c2b877a5-7188-454c-bbc2-7c02db62448b)

**Comment by anfan4730** [comment]
![WeChat0a3e25ab923333d3c647984af79ef9c8](https://github.com/romkatv/powerlevel10k/assets/165348670/9e05fccf-88c1-4604-9d4f-0262e4fc3a0c)
![WeChata417064905395e71a270c6833fc1acae](https://github.com/romkatv/powerlevel10k/assets/165348670/84b99026-e67b-4e8c-b996-767f9c420658)

**Comment by romkatv** [comment]
Powerlevel10k can use several methods to resolve the public IP address of the host. You can specify which ones are actually used, and in which order, by defining `POWERLEVEL9K_PUBLIC_IP_METHODS`. Here's the default:

```zsh
typeset -g POWERLEVEL9K_PUBLIC_IP_METHODS=( dig curl wget )
```

When using `dig`, the resolution is done by talking to `resolver1.opendns.com`. When using `curl` or `wget`, it's `https://v4.ident.me/`, which you can override by defining `POWERLEVEL9K_PUBLIC_IP_HOST`.

What are you trying to achieve?

**Comment by anfan4730** [comment]
> Powerlevel10k can use several methods to resolve the public IP address of the host. You can specify which ones are actually used, and in which order, by defining `POWERLEVEL9K_PUBLIC_IP_METHODS`. Here's the default:
> 
> ```shell
> typeset -g POWERLEVEL9K_PUBLIC_IP_METHODS=( dig curl wget )
> ```
> 
> When using `dig`, the resolution is done by talking to `resolver1.opendns.com`. When using `curl` or `wget`, it's `https://v4.ident.me/`, which you can override by defining `POWERLEVEL9K_PUBLIC_IP_HOST`.
> 
> What are you trying to achieve?

Your answer perfectly solved my problem .Thanks

**Comment by romkatv** [comment]
You are welcome.

What were you trying to achieve?

**Comment by anfan4730** [comment]
> You are welcome.
> 
> What were you trying to achieve?

I just want to know now i used public ip  ?Because i have some public ip. Do you understand what I mean

**Comment by romkatv** [comment]
I don't understand what you mean. Never mind. Closing.
