### ISSUE TITLE
os_icon shows the text `OSX` but apple-logo

### ISSUE THREAD

**Issue by prateethvnayak** [romkatv/powerlevel10k#2623]
Hey, I installed the p10k via brew and also have the recommended font installed, but the os_icon is not able to render the apple-logo. Instead I see the text `OSX`. 

Here is my .zshrc
```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


autoload -Uz colors && colors
setopt PROMPT_SUBST

# Load dotfiles:
for file in ~/.{aliases,private}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

I am loading some dot-files and that is it.

**Comment by romkatv** [comment]
What happens if you run `p10k configure`? How do you answer the first Y/N questions that ask you how things look like?

**Comment by J-Siu** [comment]
For other who reach here. This happen if you pick "pure". I run 'p10k configure' again and picking "lean" fixed this.

**Comment by romkatv** [comment]
*Pure* does not display "OSX" unless you manually edit `~/.p10k.zsh`.

**Comment by J-Siu** [comment]
@romkatv Yes I did add "context" into my .p10k.zsh.
