### ISSUE TITLE
When using Devbox, prompt says impure nix 

### ISSUE THREAD

**Issue by yagupta** [romkatv/powerlevel10k#2629]
<img width="812" alt="Screenshot 2024-04-03 at 2 49 47 PM" src="https://github.com/romkatv/powerlevel10k/assets/2133869/30d66a7c-288a-4307-b779-44c986134ab5">

**Comment by romkatv** [comment]
What is the issue?

**Comment by yagupta** [comment]
I would like to know that I am in a Devbox environment, https://www.jetpack.io/devbox - they use NIX. Is there any way to configure the shell so that instead of saying impure nix, it says I am in the Devbox environment?

**Comment by romkatv** [comment]
Is there a command or a file that can be used to detect that the shell is in the Devbox environment?

**Comment by romkatv** [comment]
Also, perhaps this tip is enough for your needs? https://github.com/romkatv/powerlevel10k/blob/da9b03777c4f2390c7e3f5c720ee4689336f811b/config/p10k-lean.zsh#L767-L768

**Comment by yagupta** [comment]
thanks & now I feel really stupid for not reading this earlier.

**Comment by romkatv** [comment]
To be fair, the config is intimidatingly large.
