### ISSUE TITLE
Weird space between POWERLEVEL9K_HOME_ICON and Directory path

### ISSUE THREAD

**Issue by jasursadikov** [romkatv/powerlevel10k#2636]
I have the following code in my `.zshrc`:
```  zsh
HOME_ICONS=('🛖' '🎪' '⛺' '🏠' '🏕️' '🏚️' '🏛️')
HOME_ICON_INDEX=$(($RANDOM % ${#HOME_ICONS[@]} + 1))
HOME_ICON="${HOME_ICONS[HOME_ICON_INDEX]}"
typeset -g POWERLEVEL9K_HOME_ICON=$HOME_ICON
```
And randmoly loose space between direcotry path and icon:
![image](https://github.com/romkatv/powerlevel10k/assets/14846427/97508932-4fc1-424f-923e-56b1a2cf979b)

**Comment by romkatv** [comment]
Please run the following command and post a screenshot:

```zsh
printf '%sX\n' '🛖' '🎪' '⛺' '🏠' '🏕️' '🏚️' '🏛️'
```

**Comment by jasursadikov** [comment]
![image](https://github.com/romkatv/powerlevel10k/assets/14846427/d32e0c67-58b6-4ea8-81ca-f3c9648da9ee)

**Comment by jasursadikov** [comment]
Ok, fine then, I am using vanila GNOME console. There are literelly no tweaks available tbd.

**Comment by rodhash** [comment]
> I have the following code in my `.zshrc`:
> 
> ```shell
> HOME_ICONS=('🛖' '🎪' '⛺' '🏠' '🏕️' '🏚️' '🏛️')
> HOME_ICON_INDEX=$(($RANDOM % ${#HOME_ICONS[@]} + 1))
> HOME_ICON="${HOME_ICONS[HOME_ICON_INDEX]}"
> typeset -g POWERLEVEL9K_HOME_ICON=$HOME_ICON
> ```
> 
> And randmoly loose space between direcotry path and icon: ![image](https://private-user-images.githubusercontent.com/14846427/320624251-97508932-4fc1-424f-923e-56b1a2cf979b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDQxMzcsIm5iZiI6MTcxNDQ0MzgzNywicGF0aCI6Ii8xNDg0NjQyNy8zMjA2MjQyNTEtOTc1MDg5MzItNGZjMS00MjRmLTkyM2UtNTZiMWEyY2Y5NzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAyMjM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1ZmY4ODczNjllN2I0YjUwMDBiMjAzM2I0YzAwYzVmOGM0ZmY1MGRkM2VhOTU5ZWI4OWYyYTZhMjRkMjAzYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bqzJPDMz83UspkggOzTkxEZzRJrFHvQ2kznbU_3Ch8U)

Interesting .. thanks for posting
