### ISSUE TITLE
Expose "wip" string to edit

### ISSUE THREAD

**Issue by jasursadikov** [romkatv/powerlevel10k#2638]
It would be nice to edit "wip" prompt part from `.zshrc` file
This part does take care in `.p10k.zsh`
``` zsh
    # Display "wip" if the latest commit's summary contains "wip" or "WIP".
    if [[ $VCS_STATUS_COMMIT_SUMMARY == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]]; then
      res+=" ${modified}wip" # < would be nice to have wip in typeset thing.
    fi
```

**Comment by romkatv** [comment]
You can replace that string with something else.

**Comment by jasursadikov** [comment]
Yeah, sure, but then whenever I am reconfiguring p10k, I should revert the change. I am keeping all those changes inside my `.zshrc` rather than keeping those in `.p10k.zsh`

**Comment by romkatv** [comment]
The only supported way to customize powerlevel10k after generating a config is by editing `~/.p10k.zsh`.

There is a bit of discussion related to this topic here: https://github.com/romkatv/powerlevel10k/issues/2586. There are older issues, too, but they aren't easy to find.
