### ISSUE TITLE
[Question] right prompt element

### ISSUE THREAD

**Issue by weileong17** [romkatv/powerlevel10k#264]
Hi, I just started to use powerlevel10k, I am wondering what is this ? 259746466876577077-cf....
Is something wrong?
![Screenshot 2019-10-13 at 5 01 46 PM](https://user-images.githubusercontent.com/52274545/66713293-6636d100-eddb-11e9-9613-5022a1edc8d2.png)

**Comment by romkatv** [comment]
This looks like the current kubernetes context. Type `kubectl config get-contexts`. Does the output have this?

**Comment by weileong17** [comment]
Yes, you are right. Thanks for the help. Just found out I can customise in POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS. Thanks for the help!

**Comment by romkatv** [comment]
Yes, you can comment out `kubecontext` in `~/.p10k.zsh` if you don't want to see it. If you do want to see your current kubernetes context but in a different shape, search for `kubecontext` in that file and read the comments above parameters that control this segment.
