### ISSUE TITLE
need to run `exec zsh` every time on every pane (WARP)

### ISSUE THREAD

**Issue by marcosdipaolo** [romkatv/powerlevel10k#2641]
Hey there, this isn't the first time I install the theme on WARP but this time I'm not able to set it right. 

I need to run `exec zsh` in order to activate the theme every time on every pane. 
On a new pane, if I type `$SHELL` I get `/bin/zsh`.

Any ideas?

I wonder if I should just add the command to my `~/.zshrc`

**Comment by romkatv** [comment]
See https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1604551784.

You'll probably also need to check out this: https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1605005256

**Comment by marcosdipaolo** [comment]
hey @romkatv 
thanks for your answer, but none of these posts helped me.

**Comment by romkatv** [comment]
Have you enabled "Honor user's custom prompt (PS1)"?

**Comment by marcosdipaolo** [comment]
hey @romkatv 
sorry i didn't mention it, but I don't have that setting
I'm on MacOs Sonoma 14
![image](https://github.com/romkatv/powerlevel10k/assets/22824656/32c8f219-e6fb-427f-b68b-1a5efcfd3770)

**Comment by romkatv** [comment]
You need to find that setting. If you cannot, use whatever help channels Warp provides.

**Comment by marcosdipaolo** [comment]
@romkatv yeap!, you were right. `Appearance > Prompt` and you need to select the PS1
![image](https://github.com/romkatv/powerlevel10k/assets/22824656/368ade0f-8bbc-48c8-b67b-dfa385af1fc0)

**Comment by romkatv** [comment]
I'm glad it worked out for you.
