### ISSUE TITLE
Problem with internal/p10k.zsh customisation

### ISSUE THREAD

**Issue by ogipierogi** [romkatv/powerlevel10k#2644]
I make changes in https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh, namely in https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L7459-L7475.
The problem is that even if I restart iTerm, the changes are not effective. Currently I can only customise that file if I make it empty and save file, restart iTerm, then paste code changes and save, restart iTerm again.
What might be the problem that just saving change and shell restart does not work?

**Comment by romkatv** [comment]
Modifying that file isn't exactly customization. You are editing the internal code of the software. The code is open, so you can do it, but you are on your own.
