### ISSUE TITLE
Ability to Use .ico/.icns or .svg, etc. as segment icons?

### ISSUE THREAD

**Issue by BuildBackBuehler** [romkatv/powerlevel10k#2645]
Hi all, first off, my apologies if this has been asked before, I couldn't find anything on it, but hard to when you don't know what to search for in the first place! 

I'm looking to do the above. I'm hoping I don't have to create a font with the images I want to use (unless its easy but I don't know how to make a font, period haha). I started with the file location in the visual identifier expansion typeset variable...thing. Figure maybe some zsh/unicode voodoo [img] type wraps will do it. 

I'm using Wezterm so I was hoping imgcat might do it, but, at least the way I inserted it into the visual expansion it isn't :/

**Comment by romkatv** [comment]
Powerlevel10k cannot do this.
