### ISSUE TITLE
prompt sometimes does not fit when using wide characters in git part

### ISSUE THREAD

**Issue by Mellbourn** [romkatv/powerlevel10k#2646]
In some git repos with long paths, when I have something to push and a staged change, so I have multiple git status icons, the p10k prompt shows twice, and does not fit:

<img width="770" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1785727/3433e332-09e0-40d2-86d9-308029fc871b">

It seems to be related to me using double-wide characters for the statuses in `.p10k.zsh`, e.g. "⬇️" and "🥦". If I change them to single-width characters it works again.

This only happens when the prompt is fairly long, as in the image.

I tried rerunning the `p10k configure` command, and I was very careful to answer the questions about character rendering correctly, but it made no difference.

It is also a new phenomenon, this happened the first time maybe a day ago. I've had these settings for a long time, and they have been working fine.

This is on macOS Sonoma 14.4.1, everything is updated to the latest versions.

**Comment by romkatv** [comment]
If your terminal prints some wide characters as narrow, you can either try to find an option in the terminal settings to fix that (something like "respect UNICODE 9") or use `%G` to let zsh know what your terminal is doing.

**Comment by Mellbourn** [comment]
I'm using iTerm2 3.4.23 and I already have the `Use Unicode version 9+ widths` option enabled. (Disabling it did not help).

I tested surround all the special characters with `%{` and `%G%}` e.g. 

```sh
(( VCS_STATUS_NUM_STAGED     )) && res+=" %{🥦%G%}${staged}${VCS_STATUS_NUM_STAGED}"
```

but it made no difference. I also tested putting the `%G` first, e.g. `%{%G⬇️%}`, but again no difference.

**Comment by romkatv** [comment]
You can test it with this command:

```zsh
PS1='>' RPS1='...' zsh -f
```

Replace `...` with your test string. You want the cursor to be right after `>`.

**Comment by romkatv** [comment]
Just to clarify what I'm saying: it's not specific to powerlevel10k.

**Comment by Mellbourn** [comment]
After a lot of testing, I realized that the problem was related to the ⬆️ and ⬇️ characters specifically.
My workaround is to replace them with 🔼 and 🔽, and now everything works again.
I guess that this is related to the fact that ⬆️ and ⬇️  are two codepoints, as opposed to one, but I'm still not entirely clear what was wrong in the first place.

Anyway, I'm fine with the workaround. Thank you for helping.

**Comment by romkatv** [comment]
Do I understand correctly that you've used the test I posted above to confirm that it's not a powerlevel10k issue?

**Comment by Mellbourn** [comment]
Your test above does indeed illustrate that there is an issue with ⬆️ and ⬇️ characters as opposed to 🔼 and 🔽.
