### ISSUE TITLE
A strange vertical line

### ISSUE THREAD

**Issue by matiux** [romkatv/powerlevel10k#2647]
Please, take a look at this video. Is that vertical line normal? I'm referring to the vertical line on the left between the edge of the window and the prompt
Is it possible to remove it?

https://github.com/romkatv/powerlevel10k/assets/821668/03633380-6894-44a6-8799-587978be1294

**Comment by romkatv** [comment]
Your terminal is doing that to mark the location of prompt. There is probably a setting that turns it off.

**Comment by matiux** [comment]
Maybe some dirt in the tests I was doing. After rebooting, no problem. Thanks
