### ISSUE TITLE
_p9k_taskwarrior_init_data:32: bad floating point constant

### ISSUE THREAD

**Issue by igbanam** [romkatv/powerlevel10k#2648]
I recently upgraded taskwarrior to 3.0.1 and I get this error

```
_p9k_taskwarrior_init_data:32: bad floating point constant
```

This looks similar to #1365.

Commenting out this line "fixes" it — i.e. allows me to get the prompt back — but I'm unsure if it's the right fix.

The output of the command string in "ts" is 3.0.1

```
$ task +PENDING -OVERDUE list rc.verbose=nothing rc.color=0 rc._forcecolor=0 rc.report.list.labels= rc.report.list.columns=due.epoch </dev/null 2>/dev/null
3.0.1
```

…thus…

```
$ ($(command task +PENDING -OVERDUE list rc.verbose=nothing rc.color=0 rc._forcecolor=0 rc.report.list.labels= rc.report.list.columns=due.epoch </dev/null 2>/dev/null))
zsh: command not found: 3.0.1
```

I think this is the error here? …but my zsh-fu is not even at beginner level 

https://github.com/romkatv/powerlevel10k/blob/178fcda3487afb3bd540d784cf472c60ec0de94a/internal/p10k.zsh#L5268

**Comment by romkatv** [comment]
The output of "3.0.1" does not look like what we are trying to get. I suppose there was a backward-incompatible change in the command line API of `task`, so we now need to invoke a different command if the version of `task` is 3.x.

The PR you sent is on the wrong track, I'm afraid. I suggest that you disable taskwarrior prompt segment in your `~/.p10k.zsh` and reverd the change you've made to powerlevel10k.

**Comment by romkatv** [comment]
> Also, how does one disable the task bit for p10k?

Open `~/.p10k.zsh` and search for "timewarrior". You'll know what to do.

**Comment by romkatv** [comment]
> I'm realizing `ts` may have meant "timestamp"

It's an array of pending tasks.

**Comment by cridemichel** [comment]
Hi, 
I do not know if this can help but after having had same issue, I started reusing my own segment function, i.e.
```zsh
function prompt_mytaskwarrior() {
  emulate -L zsh
  setopt pipefail
  (( $+commands[task] ))          || return
  local line IFS
  task +PENDING count 2>/dev/null | read -r lineP || return
  task +OVERDUE count 2>/dev/null | read -r lineO || return
  [[ "${lineP}" == "0" ]] && return
  lineP="⇡${lineP}"
  if [[ "${lineO}" == "0" ]]
  then
    lineO=""
  else
    lineO="!${lineO}"
  fi
  local tags="${lineP}${lineO}"
  [[ -n $tags ]] || return
  p10k segment -f 208 -i $'' -t $tags
}
```
and it works flawlessly, i.e. I added this function to my .zshrc and I replaced "taskwarrior" with" mytaskwarrior" in ".p10k.zsh"

best C.

**Comment by romkatv** [comment]
Thanks! That's great know.

**Comment by romkatv** [comment]
Thanks for the confirmation. Closing.
