### ISSUE TITLE
Non-existing character

### ISSUE THREAD

**Issue by psprint** [romkatv/powerlevel10k#265]
With the Iosevka fonts some character isn't available and renders as a square:
![2019-10-13-132240_1246x48_scrot](https://user-images.githubusercontent.com/6049288/66714894-0a5d4f80-edbd-11e9-8d6e-1678b8761eb7.png)

**Comment by romkatv** [comment]
Thanks for the report. I'll add another questions to the configuration wizard to detect fonts with poor choice of glyphs. I was under the impression that all modern fonts have `↵` but apparently this isn't so.

In the meantime you can set `POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION` and related options.

**Comment by romkatv** [comment]
Should be fixed now. Please update powerlevel10k and run `p10k configure`.

**Comment by psprint** [comment]
I confirm that the icon is fixed. Thanks.

**Comment by romkatv** [comment]
Thanks for the confirmation.
