### ISSUE TITLE
alias expansion

### ISSUE THREAD

**Issue by p1r473** [romkatv/powerlevel10k#2655]
Hi,
[I've added ](https://github.com/romkatv/powerlevel10k/issues/1095#issuecomment-723541436)
```
function prompt_my_alias() {
  p10k segment -b blue -f yellow -e -t '${my_expanded_command//\%/%%}'
}

function p10k-on-post-widget() {
  emulate -L zsh
  local buf=$PREBUFFER$BUFFER
  local words=(${(Z+C+)buf})
  words[1]=$aliases[$words[1]]
  local cmd
  [[ -n $words[1] ]] && cmd="$words"
  if [[ $cmd != $my_expanded_command ]]; then
    my_expanded_command="$cmd"
    p10k display -r
  fi
}

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(my_alias)
```

to my ~/.p10k.zsh however I cant seem to get alias expansion to work

**Comment by romkatv** [comment]
What are you trying to achieve?

**Comment by p1r473** [comment]
I am trying to get the aliases to autoexpand as  I type them
For example. Ive aliased ssh. So when I type ssh, it should expand to what its aliased to
Adding in some debug statements shows it does print stuff in the debug statements but it never expands the prompt to show the alias

```
function p10k-on-post-widget() {
  emulate -L zsh
  local buf=$PREBUFFER$BUFFER
  local words=(${(Z+C+)buf})
  words[1]=$aliases[$words[1]]  # This might be prematurely replacing the command without proper checking
  local cmd=${words[1]}
  if [[ -n $cmd ]] && [[ $cmd != $my_expanded_command ]]; then
    my_expanded_command="$cmd"
    p10k display -r
  fi
  print "Buffer: $buf"
  print "Command: $cmd"
  print "Expanded Command: $my_expanded_command"
}
```

**Comment by romkatv** [comment]
Powerlevel10k is a prompt. It doesn't do anything other than displaying prompt. What you are trying to achieve cannot be done through powerlevel10k because auto-expanding aliases isn't about displaying prompt.

**Comment by p1r473** [comment]
Can you explain to me what that code is supposed to do then that I found on that other issue?
I am trying to get the alias to show what its aliased to

**Comment by romkatv** [comment]
The first two functions define a prompt segment. The last line adds that segment to right prompt.

**Comment by p1r473** [comment]
So there is no way to get the prompt to change what I am typing to be an expanded alias?

Like so:
ssh is an alias to custom_ssh

So if I type on the prompt
> alias
it expands to 
> custom_alias

**Comment by romkatv** [comment]
Zsh is very flexible, so you can of course achieve this. Only not with powerlevel10k because powerlevel10k is a prompt. It cannot do anything other than display prompt.
