### ISSUE TITLE
license question re possibly-derivative work

### ISSUE THREAD

**Issue by olets** [romkatv/powerlevel10k#2656]
(Tried sending this as a Reddit message but it _looks_ like Reddit ate it. Sorry if you get it twice)

I'm developing a project based on https://gist.github.com/subnut/3af65306fbecd35fe2dda81f59acf2b2. That gist is "inspired" by p10k. From a cursory study of p10k, I see quite a lot of overlap between the gist and p10k's transient prompt code, but I haven't tried extracting p10k's transient prompt code so don't know if the overlap is superficial. I'm wondering if I should license my project as a continuation of the p10k license, or if I can use a new license of my choosing. Would you take a look at the gist and let me know what you think? Thank you!

**Comment by romkatv** [comment]
I'm not a lawyer, but if I wrote that code in the gist based on somebody else's MIT code, I would've honored the terms of MIT license. There is no real downside to doing so given how permissive the license is.

**Comment by olets** [comment]
Cool yep wondering your feels as author, not law.

**Comment by romkatv** [comment]
My feels are that it's cool to respect the license under which I release my code.
