### ISSUE TITLE
The Right Prompt is on the new line.

### ISSUE THREAD

**Issue by TheTalify** [romkatv/powerlevel10k#2657]
Welp this is the issue
![Screenshot from 2024-04-27 21-49-51](https://github.com/romkatv/powerlevel10k/assets/95576315/beda060f-cf25-452f-a7f6-c8b9ddbb0475)
Well the right prompt is on the newline. Also when I resize teh screen it goes like this
![Screenshot from 2024-04-27 21-51-23](https://github.com/romkatv/powerlevel10k/assets/95576315/35aef603-e962-4fbf-8ce1-0435a0dd1d6a)

**Comment by romkatv** [comment]
For the first problem, try this: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#right-prompt-is-in-the-wrong-place

For the second problem, see this: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#horrific-mess-when-resizing-terminal-window

**Comment by TheTalify** [comment]
The thing is that only with gnome ubuntu terminal I'm having this problem. On other trminals that I downloaded for testing this... they dont have this issue.
As for the font, I'm using the one that is recommended. I've run the diagnosis and it seems that this terminal is adding extra spaces which causes this problem. Is there any fix for this?

**Comment by romkatv** [comment]
The link I posted is all I have.

**Comment by TheTalify** [comment]
Ahh well in that link it was fixed by updating the font but I already have it.

**Comment by romkatv** [comment]
In that link there is a ton of stuff.
