### ISSUE TITLE
Prompt Style not showing in p10k configure

### ISSUE THREAD

**Issue by hussein-jafarinia** [romkatv/powerlevel10k#2659]
Prompt Style not showing in p10k configure. This issue is different from what we had before in
issue #434 or issue #642 and the previous solutions do not work.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by hussein-jafarinia** [comment]
> See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

Everything is working as the link suggests except print -P '%F{#ff0000}red%f' just prints a white "red".
I still think it should be due to the new version because everything was working fine until I after a month I installed the latest version on a new docker container (which was exactly the same in everything including software and hardware).

**Comment by romkatv** [comment]
Please run `p10k configure` and post screenshots of all screens up to the screen with the style, or the first screen that follows it. Also indicate your answers to the questions presented by the wizard.

**Comment by hussein-jafarinia** [comment]
I found out what's the reason. When I enter the docker container with ```docker exec -it [container_name] /bin/zsh``` or ```docker exec -it [container_name] /usr/bin/zsh``` (going from the main server t docker contianer) it happens. If I set a port for the docker container and connect to it directly everything becomes normal.
<img width="1618" alt="Screenshot 2024-04-28 at 15 57 06" src="https://github.com/romkatv/powerlevel10k/assets/19488284/e4640ece-f765-498b-af63-6b9218825b89">
<img width="1618" alt="Screenshot 2024-04-28 at 15 57 19" src="https://github.com/romkatv/powerlevel10k/assets/19488284/a8d26ed1-23cd-44cc-be0f-6022a4f5a396">
<img width="1618" alt="Screenshot 2024-04-28 at 15 57 21" src="https://github.com/romkatv/powerlevel10k/assets/19488284/71a43c11-1315-463d-a7bd-ca65a13604f8">
<img width="1618" alt="Screenshot 2024-04-28 at 15 57 25" src="https://github.com/romkatv/powerlevel10k/assets/19488284/ec867bad-0f82-4bc8-9646-3745a7c4571b">
<img width="1618" alt="Screenshot 2024-04-28 at 15 57 29" src="https://github.com/romkatv/powerlevel10k/assets/19488284/3a0bbd97-d161-41cb-b974-be6496d2127c">
<img width="1618" alt="Screenshot 2024-04-28 at 15 57 36" src="https://github.com/romkatv/powerlevel10k/assets/19488284/a07a90e0-57f5-4406-81b5-1d95ba3eae8f">
My answers are yes-yes-yes-yes-unicode-24hour

**Comment by romkatv** [comment]
What is the output of `print $terminfo[colors]`?

**Comment by hussein-jafarinia** [comment]
8

**Comment by romkatv** [comment]
From the [FAQ](https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard) linked above:

> If the terminal can display fewer than 256 colors, configuration wizard preselects Lean style with 8 colors. All other styles require at least 256 colors. Fix: Use a terminal with 256 color support and make sure that `TERM` environment variable is set correctly. Verify with print `$terminfo[colors]`.

**Comment by romkatv** [comment]
You can use `-e TERM` when launching docker to propagate `TERM` from your terminal.

**Comment by hussein-jafarinia** [comment]
Wow. Solved! Thank you very much :))

**Comment by romkatv** [comment]
You are welcome.
