### ISSUE TITLE
Bump gitstatus release to 1.5.5

### ISSUE THREAD

**Issue by cluesch** [romkatv/powerlevel10k#2660]
If there is no `gitstatusd` binary available the Installer says:
```
[ERROR]: gitstatus failed to initialize.

There is no prebuilt gitstatusd for openbsd amd64.

See: https://github.com/romkatv/gitstatus#compiling
```

After compiling the startup still fails, debug reveals the following:
```
    +_gitstatus_install_main:143> daemon=/home/cluesch/.zim/modules/powerlevel10k/gitstatus/usrbin/gitstatusd
    +_gitstatus_install_main:145> [ -n /home/cluesch/.zim/modules/powerlevel10k/gitstatus/usrbin/gitstatusd ']'
    +_gitstatus_install_main:146> local gitstatus_version='' libgit2_version=''
    +_gitstatus_install_main:147> . /home/cluesch/.zim/modules/powerlevel10k/gitstatus/build.info
    +/home/cluesch/.zim/modules/powerlevel10k/gitstatus/build.info:6> gitstatus_version=v1.5.4
    +/home/cluesch/.zim/modules/powerlevel10k/gitstatus/build.info:21> libgit2_version=tag-2ecf33948a4df9ef45a66c68b8ef24a5e60eaac6
    +/home/cluesch/.zim/modules/powerlevel10k/gitstatus/build.info:22> libgit2_sha256=4ce11d71ee576dbbc410b9fa33a9642809cc1fa687b315f7c23eeb825b251e93
    +_gitstatus_install_main:151> [ -z v1.5.4 ']'
    +_gitstatus_install_main:155> local version=v1.5.4
    +_gitstatus_install_main:156> _gitstatus_install_daemon_found 0 _gitstatus_set_daemon_p9k_
    +_gitstatus_install_daemon_found:1> local installed=0
    +_gitstatus_install_daemon_found:2> shift
    +_gitstatus_install_daemon_found:3> [ 1 '=' 0 ']'
    +_gitstatus_install_daemon_found:3> _gitstatus_set_daemon_p9k_ /home/cluesch/.zim/modules/powerlevel10k/gitstatus/usrbin/gitstatusd v1.5.4 0
    +_gitstatus_set_daemon_p9k_:1> _gitstatus_zsh_daemon=/home/cluesch/.zim/modules/powerlevel10k/gitstatus/usrbin/gitstatusd
    +_gitstatus_set_daemon_p9k_:2> _gitstatus_zsh_version=v1.5.4
    +_gitstatus_set_daemon_p9k_:3> _gitstatus_zsh_downloaded=0
    +_gitstatus_install_main:157> return
    +_gitstatus_daemon_p9k_:49> [[ -n /home/cluesch/.zim/modules/powerlevel10k/gitstatus/usrbin/gitstatusd ]]
    +_gitstatus_daemon_p9k_:50> [[ -n v1.5.4 ]]
    +_gitstatus_daemon_p9k_:51> [[ 0 == [01] ]]
    +_gitstatus_daemon_p9k_:53> ((  UID == EUID  ))
    +_gitstatus_daemon_p9k_:54> local home=/home/cluesch
    +_gitstatus_daemon_p9k_:62> [[ -x /home/cluesch/.zim/modules/powerlevel10k/gitstatus/usrbin/gitstatusd ]]
    +_gitstatus_daemon_p9k_:63> HOME=/home/cluesch /home/cluesch/.zim/modules/powerlevel10k/gitstatus/usrbin/gitstatusd -G v1.5.4 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 8
    Version mismatch. Wanted (pattern): "v1.5.4". Actual: "v1.5.5".
    +_gitstatus_daemon_p9k_:64> local -i ret=11
```

So Powerlevel10k recommends to build using the instructions over at [gitstatus](https://github.com/romkatv/gitstatus) which targets the latest release, however it still uses the previous one.

**Comment by cluesch** [comment]
The solution is actually to not just copy the `gitstatusd` binary after build, but also the `build.info` ded, but this information is absent from the build instructions, or to build using the source in the Powerlevel10k module directory.

**Comment by romkatv** [comment]
Which commands have you run to compile gistatusd? Did any of them involve `git`?

**Comment by romkatv** [comment]
I think I see what happened. Basically, you need to follow the compiling instructions from gitstatus but skip the `git clone` part. Start with `cd ~/.zim/modules/powerlevel10k/gitstatus` and then invoke `build` with appropriate flags. Don't copy anything anywhere.

**Comment by cluesch** [comment]
I started with the compiling instructions in https://github.com/romkatv/gitstatus#compiling which lead me to clone the gitstatusd repository. I think you might want people to start reading at https://github.com/romkatv/gitstatus/blob/a952c3f6f2d542b17a7923b356c9785ce42eb80f/README.md?plain=1#L515 instead at the beginning of compiling.

**Comment by romkatv** [comment]
> I think I see what happened. Basically, you need to follow the compiling instructions from gitstatus but skip the `git clone` part. Start with `cd ~/.zim/modules/powerlevel10k/gitstatus` and then invoke `build` with appropriate flags. Don't copy anything anywhere.

Please try this and let me know if it helps.

**Comment by cluesch** [comment]
That works as well, my way there was more convoluted, but worked out the same:

```shell
git clone --depth=1 https://github.com/romkatv/gitstatus.git
cd gitstatus
doas pkg_add cmake gmake gcc g++ wget
zsh ./build -w
cp -p usrbin/gitstatusd ~/.zim/modules/powerlevel10k/gitstatus/usrbin
cp -p build.info ~/.zim/modules/powerlevel10k/gitstatus
```

**Comment by romkatv** [comment]
Your way works by accident.

**Comment by romkatv** [comment]
To elaborate, your way disables a safety check that is there for a reason. It just so happens that these two versions are backward compatible enough that the check can be bypassed without damage to your system. This isn't true in general.

**Comment by cluesch** [comment]
I was afraid of that as well, but thought, what the heck, the changes in 1.5.5 were minimal...

**Comment by romkatv** [comment]
Everything is WAI, or is there anything that you think is missing?

**Comment by cluesch** [comment]
Just as before. When gitstatusd is not there during the installation of Powerlevel10k, do not talk about compiling it standalone, but tell people to go to `~/.zim/modules/powerlevel10k/gitstatus` and run `./build`.

**Comment by romkatv** [comment]
It's already in the linked docs. You need to read a but further in that section.
