### ISSUE TITLE
How to show `python3 --version` on the prompt?

### ISSUE THREAD

**Issue by sumanth-lingappa** [romkatv/powerlevel10k#2661]
Thank you for a fantastic tool. I can't work without this.

I recently enabled displaying python version number inside venv.
However, `pyenv` version is also appearing.

## What I want

I need `python3 -V` and not `pyenv` inside and outside the vitualenv.

## system level prompt

![image](https://github.com/romkatv/powerlevel10k/assets/42572246/861649a9-2841-416a-b609-122a9448db8b)

## inside venv prompt

![image](https://github.com/romkatv/powerlevel10k/assets/42572246/22a4e6ea-dac8-40f6-b68a-f4774087b19a)

## p10k.sh file

```bash
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
      # =========================[ Line #1 ]=========================
      status                  # exit code of the last command
      command_execution_time  # duration of the last command
      background_jobs         # presence of background jobs
      direnv                  # direnv status (https://direnv.net/)
      asdf                    # asdf version manager (https://github.com/asdf-vm/asdf)
      virtualenv              # python virtual environment (https://docs.python.org/3/library/venv.html)
      anaconda                # conda environment (https://conda.io/)
      pyenv                   # python environment (https://github.com/pyenv/pyenv)
      goenv                   # go environment (https://github.com/syndbg/goenv)
      nodenv                  # node.js version from nodenv (https://github.com/nodenv/nodenv)
      nvm                     # node.js version from nvm (https://github.com/nvm-sh/nvm)
      nodeenv                 # node.js environment (https://github.com/ekalinin/nodeenv)
      # node_version          # node.js version
      # go_version            # go version (https://golang.org)
      # rust_version          # rustc version (https://www.rust-lang.org)
      # dotnet_version        # .NET version (https://dotnet.microsoft.com)
      # php_version           # php version (https://www.php.net/)
      # laravel_version       # laravel php framework version (https://laravel.com/)
```

**Comment by romkatv** [comment]
Powerlevel10k currently does not have an option to display the output of `python3 -V` at all times. You could implement a custom prompt segment for this. Search for `prompt_example` in `~/.p10k.zsh` and see the output of `p10k help segment`.

**Comment by sumanth-lingappa** [comment]
Thank you @romkatv.
However, I am getting double python prompts when inside python virtual env 🤔 
is there way way to either to -
- disable the custom prompt inside venv, OR
- have the same mechanism which displays python version inside venv to display it outside the venv.

my code

```bash
function prompt_python_version() {
    p10k segment -f 208 -i '🐍' -t "$(python3 -V)"
}
```

outside venv
<img width="349" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/42572246/f98f7223-d2b9-450f-bf66-f63c0d9cbbdc">

inside venv
<img width="421" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/42572246/cb43a503-325e-4f0c-a095-32ab2bca1782">

**Comment by romkatv** [comment]
I suggest a couple changes to `prompt_python_version`:

```zsh
function prompt_python_version() {
  p10k segment -f 208 -i '🐍' -t "${${$(python3 -V)#* }//\%/%%}"
}
```

This gets rid of "Python " because the preceding icon already says the same. It also escapes percent signs in the output of `python3 -V`. The latter is rather pedantic because it's unlikely that percent signs will be present there.

Don't show `python_version` inside venv:

```zsh
function prompt_python_version() {
  if [[ -z $VIRTUAL_ENV ]]; then
    p10k segment -f 208 -i '🐍' -t "${${$(python3 -V)#* }//\%/%%}"
  fi
}
```

Show venv when it's active:

```zsh
function prompt_python_version() {
  local venv=${VIRTUAL_ENV:t}
  if [[ $venv == (virtualenv|venv|.venv|env) ]]; then
    venv=${VIRTUAL_ENV:h:t}
  fi
  p10k segment -f 208 -i '🐍' -t "${${$(python3 -V)#* }//\%/%%}${venv:+ ${venv//\%/%%}}"
}
```

**Comment by sumanth-lingappa** [comment]
That's awesome :-)

Thanks a lot for your work. I can't imaging my day without p10k 😄
