### ISSUE TITLE
How to add an at-sign to my prompt?

### ISSUE THREAD

**Issue by punisherVX** [romkatv/powerlevel10k#2664]
I have tried writing my own function and adding it to the left prompt but nothing I try works.

```
function prompt_at() {
      p10k segment -f white -t "@"
  }

```
Then add this to my POWERLEVEL9K_LEFT_PROMPT_ELEMENTS

```
user
prompt_at
host

```
I *would* use context for this but I can't change the color for each element individually.  I just need a white at-sign and I am done!!!

Thanks.

**Comment by romkatv** [comment]
Use `context` instead. You can style different parts of it like this:

```zsh
POWERLEVEL9K_CONTEXT_TEMPLATE='%F{1}%n%f@%F{2}%m'
```
