### ISSUE TITLE
[ERROR] p10k configure: no TTY

### ISSUE THREAD

**Issue by andyd0** [romkatv/powerlevel10k#2665]
Hi. This just started today and I'm unclear why. What could be causing this error?

**Comment by romkatv** [comment]
This error pops up when you run `p10k configure` in process without a controlling TTY.

**Comment by andyd0** [comment]
Not sure what you mean - if I open a tab in Iterm, I see the error. Just started

**Comment by romkatv** [comment]
That's what the error means 🤷
