### ISSUE TITLE
Adding a class to directory classes

### ISSUE THREAD

**Issue by tobias-groeger** [romkatv/powerlevel10k#2667]
Hi, is there a way to add a new directory class (to `POWERLEVEL9K_DIR_CLASSES`) while still keeping all the default classes intact? As stated in https://github.com/romkatv/powerlevel10k/issues/2345, defining the `POWERLEVEL9K_DIR_CLASSES` variable as suggested in the generated config will remove all classes used by default.

Additionally, in that issue the user seems to have figured out how to add his class to this variable, however I am unable to achieve the same. Simply adding to the variable instead of overwriting it doesn't seem to work and also removes all defaults.

**Comment by romkatv** [comment]
You have to define all classes by yourself. It's not too difficult though. Definitely less work than creating this issue, for example.

**Comment by tobias-groeger** [comment]
Ok, thanks for the quick answer.
