### ISSUE TITLE
_p9k_deschedule_redraw:zle:2: No handler installed for fd 22

### ISSUE THREAD

**Issue by p1r473** [romkatv/powerlevel10k#2668]
Was playing around with tab completes in my shell and got this
```
_p9k_deschedule_redraw:zle:2: No handler installed for fd 22
_p9k_deschedule_redraw:3: file descriptor 22 used by shell, not closed
```

Hard to replicate. Any ideas?
I am using a lot of ZSH plugins, so perhaps conflicting?
Could it be related to https://github.com/romkatv/powerlevel10k/issues/1554 ?

I will test `ZSH_AUTOSUGGEST_USE_ASYNC='false'`

**Comment by romkatv** [comment]
Is there a reason you think it might be *not* a dup of https://github.com/romkatv/powerlevel10k/issues/1554?

**Comment by p1r473** [comment]
Wow Roman you are fast!
No problem, I will close as a duplicate unless ZSH_AUTOSUGGEST_USE_ASYNC='false' doesnt work
Thanks for the great work and support 👍
