### ISSUE TITLE
SSH breaks prompt

### ISSUE THREAD

**Issue by cmhuggins** [romkatv/powerlevel10k#267]
When using ssh to connect to my home computer, I have noticed that the ssh sessions slightly breaks powerline10k.

![p10k ssh](https://user-images.githubusercontent.com/4612427/67010699-c5366780-f0b3-11e9-8eb6-4aed24e3513c.png)

Other useful information (pertains to both machines):
OS: ArchLinux
Shell: ZSH 5.7.1 (x86_64-pc-linux-gnu)
Oh-My-Zsh: git (up-to-date)
Powerlevel10k: Installed using the instructions for Oh-My-Zsh
p10k is configured with `p10k configure`, no custom changes

`unset ZLE_RPROMPT_INDENT` has no effect

~/.zshrc (both machines, comments taken out): 
[zshrcNoComments.txt](https://github.com/romkatv/powerlevel10k/files/3739385/zshrcNoComments.txt)

~/.p10k.zsh (both machines):
[p10kConfig.txt](https://github.com/romkatv/powerlevel10k/files/3739401/p10kConfig.txt)

EDIT: Here is a more 'broken' configuration:
![p10k ssh broke](https://user-images.githubusercontent.com/4612427/67012327-d0d75d80-f0b6-11e9-8172-14f337cdcbce.png)
~/.p10k.zsh:
[p10kConfigBroken.txt](https://github.com/romkatv/powerlevel10k/files/3739450/p10kConfigBroken.txt)

**Comment by romkatv** [comment]
My guess is that your locale isn't Unicode-capable. Type `locale` to verify.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/153.

**Comment by cmhuggins** [comment]
It would appear my googling skills need work, that fixed it. Thank you!
