### ISSUE TITLE
Color mismatch in Prompt Segement Seperators

### ISSUE THREAD

**Issue by vipintom** [romkatv/powerlevel10k#2670]
![CleanShot 2024-05-06 at 14 31 30@2x](https://github.com/romkatv/powerlevel10k/assets/11923260/033e248b-db7d-4f7c-964a-9467f6e1b9ef)

I was unable to figure out how the colors for prompt separators colors are handled in the config file. Any help would be much appreciated.

**Comment by romkatv** [comment]
Some terminals have an option to disable this unhelpful behavior. It usually mentions something like "minimum contrast". The only terminal I know of that has this behavior by default and no setting to turn it off, is Apple Terminal.

The solution to most of these issues is to use Lean style. As a bonus, it looks better.

**Comment by vipintom** [comment]
I forgot to mention I was using p10k in iTerm2 on Mac. It was indeed minimum contrast settings in iTerm2 which was causing this issue. 

Thanks for the prompt reply. I must admit , I love what you are doing with p10k even if we disagree on which style looks better 😅

![CleanShot 2024-05-06 at 14 43 17@2x](https://github.com/romkatv/powerlevel10k/assets/11923260/b6b13d4a-543b-414f-93d4-0239ed06e7c0)
