### ISSUE TITLE
No options for Classic and Rainbow styles in p10k configure 

### ISSUE THREAD

**Issue by TsubasaEX** [romkatv/powerlevel10k#2672]
No options for Classic and Rainbow styles in p10k configure.

I tried the steps here for installation but I can't get other styles except lean one.

1. `git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k`

2. `Set ZSH_THEME="powerlevel10k/powerlevel10k" in ~/.zshrc.`

![image](https://github.com/romkatv/powerlevel10k/assets/34151841/7c17dee9-f325-44ad-906f-9d9da4e2ba53)

**Comment by romkatv** [comment]
See FAQ: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by TsubasaEX** [comment]
Thank you for the prompt reply.

I followed the FAQ and run the commands to check my environment but don't get the cause here.
![image](https://github.com/romkatv/powerlevel10k/assets/34151841/8adddb39-92dc-4a0a-8ef0-f34e80f0cf9d)

What I missed here is I don't get the following selection to select the prompt styles. The picture is from one of the tutorials on youtube.

![image](https://github.com/romkatv/powerlevel10k/assets/34151841/7a6c120b-4042-41a2-b58d-271cd40f8ca9)

**Comment by romkatv** [comment]
From the FAQ linked above:

> If the terminal can display fewer than 256 colors, configuration wizard preselects Lean style with 8 colors. All other styles require at least 256 colors. Fix: Use a terminal with 256 color support and make sure that `TERM` environment variable is set correctly. Verify with `print $terminfo[colors]`.

Your screenshot indicates that the output of `print $terminfo[colors]` is `8`, so this is the culprit.

**Comment by TsubasaEX** [comment]
Thank you for pointing this out. Finally, I change my env with ` TERM=xterm-256color` and it works perfectly.

Really appreciate your prompt support!! :thumbsup:  :thumbsup:  :thumbsup: I will enjoy your powerful and stylish features. :smile:
![image](https://github.com/romkatv/powerlevel10k/assets/34151841/7d9da630-1aec-4efe-a74a-59cec3388ba1)

**Comment by romkatv** [comment]
Nice!
