### ISSUE TITLE
Setting background with "p10k segment -b" is never used

### ISSUE THREAD

**Issue by ddribin** [romkatv/powerlevel10k#2674]
Hello,

I am trying to create a custom segment using `p10k segment`, and I've noticed that setting the background color with `-b` is never used. Trying to set it to `red` does not work:

```
  function prompt_drd_dev_env() {
    if [[ ! -z $DRD_DEV_ENV ]]; then
      p10k segment -b red -f white -t "$DRD_DEV_ENV"
    fi
  }
```

<img width="777" alt="p10k-bg-option" src="https://github.com/romkatv/powerlevel10k/assets/20428/a7349288-0c74-4355-aa93-2af3de229b30">

But using the configuration variable `POWERLEVEL9K_DRD_DEV_ENV_BACKGROUND` does work:

```
  typeset -g POWERLEVEL9K_DRD_DEV_ENV_BACKGROUND='red'
  function prompt_drd_dev_env() {
    if [[ ! -z $DRD_DEV_ENV ]]; then
      p10k segment -f white -t "$DRD_DEV_ENV"
    fi
  }
```

<img width="777" alt="p10k-bg-var" src="https://github.com/romkatv/powerlevel10k/assets/20428/32a6ece5-79e5-45b4-b8d0-04d70d78c5c0">

Using `-b` and the variable *still* does not work, as this still has a red background, as above:

```
  typeset -g POWERLEVEL9K_DRD_DEV_ENV_BACKGROUND='red'
  function prompt_drd_dev_env() {
    if [[ ! -z $DRD_DEV_ENV ]]; then
      p10k segment -b blue -f white -t "$DRD_DEV_ENV"
    fi
  }
```

I found Issue #2632, which sounds like this is intended behavior. But I'm not seeing how the `-b` color is ever used. What is the point of `-b` if it is always overridden?

I am using the P10k from git at commit 16e5848.

**Comment by romkatv** [comment]
I've replied in the other issue: https://github.com/romkatv/powerlevel10k/issues/2632#issuecomment-2103862027

**Comment by ddribin** [comment]
Alright. Let's close this one.
