### ISSUE TITLE
Configure not asking if i can see these icons

### ISSUE THREAD

**Issue by glensc** [romkatv/powerlevel10k#2676]
<img width="606" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/c136722b-072a-4a09-a9b4-9e124097654d">

it asks only spacing, but it don't see them correctly. so I pressed Y and it finishes with a prompt with squares.

Problems:
1. it should ask can I see them
2. offer some alternatives how to fix

also, if I press N, then at some point it also shows the icons, but with squares

<img width="700" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/1f4c2c50-a29d-4f93-8f87-870b49a2ca7c">

**Comment by romkatv** [comment]
> <img alt="image" width="606" src="https://private-user-images.githubusercontent.com/199095/331857012-c136722b-072a-4a09-a9b4-9e124097654d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTE3NjksIm5iZiI6MTcxNjE5MTQ2OSwicGF0aCI6Ii8xOTkwOTUvMzMxODU3MDEyLWMxMzY3MjJiLTA3MmEtNGEwOS1hOWI0LTllMTI0MDk3NjU0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwNzUxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDcyNjUzNGE0NWE5YTc1MzA4ZjdkNWUzZDBlZDI3MDkyMmU4ZGNlMjI3NzFhOWU4ZWIyM2Q4MWZkNjA2MmMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KIoecsTbMUF8DyzAg52q98SW8d2Pb7JmRgIn94tlXz4">
> it asks only spacing

Is this the very first screen that you see when running `p10k configure`? If not, how do the preceding screens look like and what are your answers to the questions they ask?

What font are you using?

**Comment by glensc** [comment]
font: dunno. something default that came with [Kitty](https://sw.kovidgoyal.net/kitty/) (font not configured in Kitty)

<details><summary>kitty.conf</summary>

```
font_size 15.0
url_excluded_characters \n
copy_on_select yes
select_by_word_characters @-./_~?&=%+#:!
mouse_map cmd+left release grabbed,ungrabbed mouse_handle_click link
enable_audio_bell no
include Solarized8 Dark.conf
map alt+c send_text normal,application,kitty \ec
map alt+l send_text normal,application,kitty \el
map alt+p send_text normal,application,kitty \ep
map alt+1 send_text normal,application,kitty \e1
map alt+2 send_text normal,application,kitty \e2
map alt+3 send_text normal,application,kitty \e3
map alt+4 send_text normal,application,kitty \e4
map alt+5 send_text normal,application,kitty \e5
map alt+6 send_text normal,application,kitty \e6
map alt+7 send_text normal,application,kitty \e7
map alt+8 send_text normal,application,kitty \e8
map alt+9 send_text normal,application,kitty \e9
map alt+\ send_text normal,application,kitty \e\
map § send_text normal,application,kitty `
map ± send_text normal,application,kitty ~
map cmd+d new_window_with_cwd
map shift+page_up       scroll_page_up
map shift+page_down       scroll_page_down
map cmd+right next_tab
map cmd+left previous_tab
include current-theme.conf
```

</details>

**Comment by romkatv** [comment]
Please answer all questions I've asked.

Also, as a quick solution you can try the recommended font: https://github.com/romkatv/powerlevel10k/blob/master/font.md

**Comment by glensc** [comment]
screens. no. i'll share them one by one

1. Answer: `y`

<img width="797" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/43bb05a6-7c8f-458d-a1aa-0118c1b0d3fa">

2. Answer `y`

<img width="668" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/19e3c69d-282a-44db-b68c-073909ca6041">

3. Answer: `n`
<img width="690" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/3e50b96e-5135-4193-b752-f1d8aa9a9ed0">

4. Answer `y`

<img width="676" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/3cbeec5c-0e86-4994-8e2b-a5e93eceb3e0">

5. Answer: `1`

<img width="663" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/7967dabc-9050-4671-8500-286db564af14">


6. Answer: `q`

<img width="682" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/199095/0cd9b951-c862-4de6-b6e8-a23c7d8e54c2">

**Comment by romkatv** [comment]
Thanks! Apparently, Kitty does something weird with its default font. Please try the recommended font.

**Comment by glensc** [comment]
On another laptop (macOS 14) works fine. With the same Kitty config (The bug report is on macOS 10.15.7)

**Comment by romkatv** [comment]
Interesting. I've no idea what could be the cause. Do try the recommended font.

**Comment by glensc** [comment]
From https://sw.kovidgoyal.net/kitty/conf/#fonts, I can find list fonts command, not sure if that's useful:

```
❯ kitty +list-fonts
Andale Mono
    Andale Mono Regular

Apple Braille
    Apple Braille Outline 6 Dot
    Apple Braille Outline 8 Dot
    Apple Braille Pinpoint 6 Dot
    Apple Braille Pinpoint 8 Dot
    Apple Braille Regular

Apple Color Emoji
    Apple Color Emoji Regular

Courier
    Courier Bold
    Courier Bold Oblique
    Courier Oblique
    Courier Regular

Courier New
    Courier New Bold
    Courier New Bold Italic
    Courier New Italic
    Courier New Regular

GB18030 Bitmap
    GB18030 Bitmap Regular

Menlo
    Menlo Bold
    Menlo Bold Italic
    Menlo Italic
    Menlo Regular

Monaco
    Monaco Regular

PT Mono
    PT Mono Bold
    PT Mono Regular

Symbols Nerd Font
    Symbols Nerd Font Regular

Symbols Nerd Font Mono
    Symbols Nerd Font Mono Regular

```

I seem to have Nerd installed, maybe some older variant...

**Comment by romkatv** [comment]
Why not try the recommended font? Seriously, just try it.

**Comment by glensc** [comment]
@romkatv Patience. I have never said I will not try it! Working in parallel on font setup.

**Comment by romkatv** [comment]
Sorry, I ran out of patience.

**Comment by glensc** [comment]
However, the bug report included second part:
- configure could be improved and ask do you see the icons in the middle there.

but I understand it also needs to identify what is the cause.

**Comment by glensc** [comment]
Currently unable to figure out why kitty doesn't reload config with new font, certainly not a reason t o run out of patience if my test is not complete.

**Comment by glensc** [comment]
Seems my first dump of kitty config was inaccurate:
- https://github.com/romkatv/powerlevel10k/issues/2676#issuecomment-2123160297

at the time, Kitty was running with this line enabled additionally:

```
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E634,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF Symbols Nerd Font Mono
```

however, after was able to reload Kitty with recommended font and result was success, tested also reverted font change, also success.

so I to conclude that running older version of Kitty caused the problem, forcefully quitting Kitty and ensuring new process is started I can see needed fonts with original config.

**Comment by niderhoff** [comment]
See kitty documentation:

> If you are trying to use a font patched with [Nerd Fonts](https://nerdfonts.com/) symbols, don’t do that as patching destroys fonts. There is no need, simply install the standalone Symbols Nerd Font Mono (the file NerdFontsSymbolsOnly.zip from the [Nerd Fonts releases page](https://github.com/ryanoasis/nerd-fonts/releases)). kitty should pick up symbols from it automatically, and you can tell it to do so explicitly in case it doesn’t with the [symbol_map](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map) directive: (...)

https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

**Comment by romkatv** [comment]
> patching destroys fonts

🙄
