### ISSUE TITLE
Two prompts appear at start

### ISSUE THREAD

**Issue by bakai-taalaibek** [romkatv/powerlevel10k#2677]
When I open a terminal, two prompts appear one after another:

![image](https://github.com/romkatv/powerlevel10k/assets/121804957/4eb6666d-fed0-4f46-9728-9957084a46d5)

The problem exists even if I fully clear the ~/.zshrc file, leaving only things that are required by powerlevel10k. If I disable powerlevel10k there is no such problem. 

This problem only exists in the Tilix terminal. I couldn't reproduce it in native gnome terminal.

**Comment by romkatv** [comment]
Please do the following:

1. Add this line at the very top of `.zshrc`:
   ```zsh
   typeset -pm 'LINES|COLUMNS|TERM|LC_*|LANG'
   ```
2. Restart your terminal.
3. Run this command:
   ```zsh
   typeset -pm 'LINES|COLUMNS|TERM|LC_*|LANG'
   ```
4. Post a screenshot of your terminal window.

**Comment by bakai-taalaibek** [comment]
![image](https://github.com/romkatv/powerlevel10k/assets/121804957/0219b28d-4bc4-4998-b96b-3c07de1b1e96)

**Comment by romkatv** [comment]
This looks like a bug in the terminal: it reports its own horizontal size (`COLUMNS`) as 133 when you open it, and as 140 a little later when you run the command.

**Comment by bakai-taalaibek** [comment]
I actually set it as 133, because with that setting the terminal opens at full screen. Now I set columns at 140 and lines at 34, but I still get two prompts at start
![image](https://github.com/romkatv/powerlevel10k/assets/121804957/02fe3e9c-7854-4b67-8667-18af9960ee1f)

**Comment by romkatv** [comment]
Hm... I don't have any ideas as to what might be causing this.

**Comment by bakai-taalaibek** [comment]
It's a very weird bug. Check out the video. When terminal opens as a small video it has one prompt, when it is maximized it has two prompts sometimes. When you resize the window weird things happen with the prompt. 

https://github.com/romkatv/powerlevel10k/assets/121804957/3d8e179a-07a4-4416-9896-6c62ec98b36a

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#horrific-mess-when-resizing-terminal-window

**Comment by bakai-taalaibek** [comment]
Ok, thanks.

**Comment by bakai-taalaibek** [comment]
Is it possible to delay or disallow appearance of the right frame, right prompt and connection on startup? That would solve my problem because apparently Tilix renders the windows twice on startup: the initial rendering of a smaller window and then rendering of maximized window. So if the appearance of the right prompt is delayed it may appear only after the maximized window is rendered. Or maybe the right prompt simply shouldn't appear on startup at all.

**Comment by romkatv** [comment]
Powerlevel10k does not have a setting for this.

I am not sure I understand the behavior of Tilix that you are describing but it does sound like a bug in Tilix to me.

**Comment by bakai-taalaibek** [comment]
The default gnome terminal behaves similarly. 

I think the terminal initially assumes that it is going to be opened as a small window, but then it is maximized. Because of this, the prompt is rendered twice.

**Comment by romkatv** [comment]
> The default gnome terminal behaves similarly.

This implies that the issue must be in VTE, as both terminals are based on it.

> I think the terminal initially assumes that it is going to be opened as a small window, but then it is maximized. Because of this, the prompt is rendered twice.

That would be the bug I was referring to.
