### ISSUE TITLE
VCS plugin doesn't use icons

### ISSUE THREAD

**Issue by Bilge** [romkatv/powerlevel10k#2678]
I can't believe I just installed a font with 10,077 icons just to have ASCII indicators in my command bar.

![image](https://github.com/romkatv/powerlevel10k/assets/470626/8158cb07-d4c9-45ba-8937-1651bac7fea5)

I'm really supposed to memorize what these symbols mean instead of having clear icons?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#what-do-different-symbols-in-git-status-mean

https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#how-do-i-change-the-format-of-git-status

**Comment by Bilge** [comment]
Why should I have to be the one to come up with the appropriate icons? This should be working out-of-the-box.

**Comment by romkatv** [comment]
It's working as intended.

**Comment by Bilge** [comment]
Tragic.

**Comment by rwmitchell** [comment]
Either your terminal is not using the font you think it is or you didn't properly run pk10 configure.
Glyphs work and the last person who needs any help is romkatv.

**Comment by romkatv** [comment]
The prompt on the screenshot provided by the OP looks as intended for Rainbow style. The git repo has 2 stashes, 7 staged changes, 8 unstaged changes, and 10 untracked files. I am positive that the OP knows this much. They state that there is a better way to present this information but provide no evidence in support of this claim. They also say they aren't qualified to produce such evidence.
