### ISSUE TITLE
Prompt distance short, cursor in prompt, former input in prompt

### ISSUE THREAD

**Issue by FranzFelberer** [romkatv/powerlevel10k#268]
Dear all,

at almost fresh ubuntu 18.04 installation I experience the following problems:

* the prompt distance is not the whole terminal size
* strange ?-like character in some cases
* the input appears in the prompt after using tab (cdcd)

![image](https://user-images.githubusercontent.com/20334762/67064755-fffbd680-f16b-11e9-93b2-58ae2d08be29.png)

any help is very much appreciate.

**Comment by romkatv** [comment]
Looks the same as https://github.com/romkatv/powerlevel10k/issues/267.

**Comment by FranzFelberer** [comment]
Thanks, that did the trick.
