### ISSUE TITLE
Git Icons Not Displaying Properly in VSCode

### ISSUE THREAD

**Issue by LKrs13** [romkatv/powerlevel10k#2688]
**Description:**
Hello,

I am experiencing an issue where icons do not display properly in the integrated terminal of Visual Studio Code when using the Powerlevel10k theme. Instead of the expected icons, I see incorrect or missing symbols.

![image](https://github.com/romkatv/powerlevel10k/assets/76753387/fc002e9f-376f-4d99-be12-a53f41014029)

**Steps to Reproduce:**
1. Install Powerlevel10k theme in Zsh.
2. Open the integrated terminal in Visual Studio Code.
3. Observe the GitHub icons.

**Expected Behavior:**
The GitHub icons should display correctly in the VSCode terminal, similar to how they appear in other terminal emulators.

**Actual Behavior:**
The GitHub icons are either missing or incorrectly displayed.

**Attempts to Resolve:**
1. Installed the Menlo font and set it as the integrated terminal font in VSCode.
2. Tried different configurations and settings in the VSCode terminal settings.

Neither of these steps resolved the issue.

**Environment:**
- **OS:** VSCode on Windows connected by Remote SSH to Linux
- **VSCode Version:** 1.89
- **Zsh Version:** 5.9
- **Font:** Menlo

**Additional Context:**
I'm fine with either a solution to correctly display the GitHub icons or a method to remove them from the prompt altogether. Any guidance or suggestions would be greatly appreciated.

Thank you for your assistance!

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#what-do-different-symbols-in-git-status-mean
