### ISSUE TITLE
Prompt Color Mismatch After Latest iTerm2 Update

### ISSUE THREAD

**Issue by eddyjaga** [romkatv/powerlevel10k#2692]
After updating to the latest version of iTerm2, I noticed that the prompt color in my terminal is not displaying correctly. 

<img width="838" alt="Screenshot 2024-05-27 at 9 15 50 AM" src="https://github.com/romkatv/powerlevel10k/assets/82800286/ac802c45-c66c-41f2-8635-34bcaa2d65a1">

### System Info:

- iTerm2 version [3.5.0]
- macOS version: Sonoma 14.5
- Shell: zsh
- Theme: Powerlevel10k

**Comment by romkatv** [comment]
Try changing Preferences > Profiles > Colors > Minimum contrast.
