### ISSUE TITLE
p10k doesnt load if I switch users

### ISSUE THREAD

**Issue by p1r473** [romkatv/powerlevel10k#2695]
Hi,
If I log in as root or pi p10k loads perfect
![image](https://github.com/romkatv/powerlevel10k/assets/9235633/80fc7812-c7af-4f9a-b858-d092b77a9e30)
![image](https://github.com/romkatv/powerlevel10k/assets/9235633/39a2b2ba-a693-48ef-a880-ab947b16c2eb)

However if I log in as root and then su pi, p10k doesnt load
Notice the prompt that says pi@hostname is missing from the right
![image](https://github.com/romkatv/powerlevel10k/assets/9235633/057e6f31-c088-41c1-81f6-427df949e315)

**Comment by p1r473** [comment]
So just source .p10k.zsh in my .zshrc? Thanks I will try that!

**Comment by p1r473** [comment]
Hey @romkatv I added `source ~/.p10k.zsh` to the .zshrc for both root and pi users and issue remains even after a new session

It seems to work when I do `su pi` but not `su - pi`

**Comment by romkatv** [comment]
If you want to install powerlevel10k for root, you need to log in as root and then install powerlevel10k as usual. I don't recommend doing that but you can.

**Comment by p1r473** [comment]
Its installed for both root and pi
The issue is it doesnt load when I log in as root and switch to pi
But if I log in as root or as Pi it works fine

**Comment by romkatv** [comment]
If you want to activate powerlevel10k, you need to source it. Usually you source it from a zsh startup file. You can find the list of zsh startup files here: https://zsh.sourceforge.io/Intro/intro_3.html

**Comment by p1r473** [comment]
Hey @romkatv I added source ~/.p10k.zsh to the .zshrc for both root and pi users and issue remains even after a new session

If I su - pi, p10k doesn't load

**Comment by p1r473** [comment]
Hey @romkatv I added source ~/.p10k.zsh to the .zshrc for both root and pi users and issue remains even after a new session

If I su - pi, p10k doesn't load

**Comment by romkatv** [comment]
I've seen your comment the first time you sent it. There is no need to delete and send it again.

I've nothing else to add to this issue.

**Comment by p1r473** [comment]
@romkatv any idea why that's happening?

**Comment by p1r473** [comment]
I figured it out.

The behavior I'm  experiencing with `su - pi` is due to the way Zsh initialization files are sourced in different login scenarios. When you use `su - pi`, it initiates a login shell for the `pi` user, and Zsh only reads `.zshrc` for interactive non-login shells. For login shells, Zsh reads `.zprofile`, `.zlogin`, and `.zshenv` files instead.

**Comment by p1r473** [comment]
Update: issue was due to the Pi user unable to access the Root user .zsh files due to file permissions. doh!
