### ISSUE TITLE
Error converting string from  to UTF-8 on Prompt

### ISSUE THREAD

**Issue by NJJoshi** [romkatv/powerlevel10k#2696]
After installation of plugin, I am getting prompt like 

"iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8"

This is happening on iTem 2 Terminal.

**Comment by romkatv** [comment]
This isn't a powerlevel10k issue.

**Comment by Chiroyce1** [comment]
Same issue here - i dont think its related to p10k but help would be appreciated.

**Comment by romkatv** [comment]
You could try to Google the error message. Here's one of the first links: https://gitlab.com/gnachman/iterm2/-/issues/11543. I haven't tried it myself.
