### ISSUE TITLE
Unable to set POWERLEVEL9K_VCS_BRANCH_ICON with Pure

### ISSUE THREAD

**Issue by ahmedelgabri** [romkatv/powerlevel10k#2700]
I'm trying to migrate from Pure, this is my current pure prompt looks like 

<img width="232" alt="Screenshot 2024-06-08 at 22 57 19" src="https://github.com/romkatv/powerlevel10k/assets/63876/76f7fff2-502e-4d05-8d11-9565dbc5120a">

This is my current p10k pure one

<img width="295" alt="Screenshot 2024-06-08 at 22 58 22" src="https://github.com/romkatv/powerlevel10k/assets/63876/a963f8f8-498b-4407-a099-17d4d3bce264">

I still can't manage to set `POWERLEVEL9K_VCS_BRANCH_ICON` though, the only way I managed to get it working was by manually running the following, but whatever I do inside the file is not reflected in new sessions.

```shell
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON="  "
p10k reload
```

Yet this will still not respect the space after the icon and it will render like this

<img width="326" alt="Screenshot 2024-06-08 at 23 01 15" src="https://github.com/romkatv/powerlevel10k/assets/63876/4a6a901d-da29-4451-88e2-1928ab83f39a">

**Comment by ahmedelgabri** [comment]
@romkatv all the edits were done inside `.p10k.zsh` file inside `$ZDOTDIR/.p10k.zsh`

**Comment by ahmedelgabri** [comment]
Here is a video showing the problem, I made the 2nd change to prove that the file is read correctly but some changes are applied while others are not, in this case, `POWERLEVEL9K_VCS_BRANCH_ICON`


https://github.com/romkatv/powerlevel10k/assets/63876/500b0eaa-7ee1-4709-aaa1-7a1b64599edf

**Comment by Syphdias** [comment]
I just replaced my `.p10k.zsh` with the pure config and tried what you did and it worked.
Do you overwrite it maybe on a later line? Or you have it in another file you source? Does `echo $POWERLEVEL9K_VCS_BRANCH_ICON` print the icon?

**Comment by ahmedelgabri** [comment]
> Do you overwrite it maybe on a later line? Or you have it in another file you source?

Yeah, I found out the problem was here, I had a different file which I source that I tried to set it up there first 🤦🏼 

But the problem with respecting the space is still there.

**Comment by ahmedelgabri** [comment]
Ok, I managed to do what I want using the following instead 

```shell
# I set the icon here
typeset -g POWERLEVEL9K_VCS_PREFIX='  '
# I remove the icon from here
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=
```
