### ISSUE TITLE
why icon change to the question mark?

### ISSUE THREAD

**Issue by wnz27** [romkatv/powerlevel10k#2701]
<img width="1461" alt="截屏2024-06-09 16 34 03" src="https://github.com/romkatv/powerlevel10k/assets/12094918/0af853ea-df94-4765-b750-f2b118599f66">

see the pic

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#icons-glyphs-or-powerline-symbols-dont-render

**Comment by wnz27** [comment]
> https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#icons-glyphs-or-powerline-symbols-dont-render

thanks  !
