### ISSUE TITLE
Console output during zsh initialization detected

### ISSUE THREAD

**Issue by shadan-arif** [romkatv/powerlevel10k#2702]
My Warning goes like this:

```
[WARNING]: Console output during zsh initialization detected.
When using Powerlevel10k with instant prompt, console output during zsh initialization may indicate issues.
You can:
- Recommended: Change ~/. zshrc so that it does not perform console I/0
after the instant prompt preamble.
See the link below for details.
* You will not see this error message again.
* Zsh will start quickly and prompt will update smoothly.
- Suppress this warning either by running p10k configure or by manually defining the following parameter:
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
* You will not see this error message again.
* Zsh will start quickly but prompt will jump down after initialization.
- Disable instant prompt either by running p10k configure or by manually defining the following parameter:
typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
* You will not see this error message again.
* Zsh will start slowly.
- Do nothing.
* You will see this error message every time you start zsh.
* Zsh will
start quickly but prompt will jump down after initialization.
For details, see:
https://github.com/romkatv/powerlevel10k#instant-prompt
-- console output produced during zsh initialization follows --
iconv: iconv_open, -t): Invalid argument
Error converting string from to UTF-8
```

There is no resolution despite turning off the instant prompt for the power level 10k . Every time I use any command like pwd, ls, etc. I am being shown these two lines at the end of every response.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/issues/2152#issuecomment-2156400844

**Comment by shadan-arif** [comment]
> [#2152 (comment)](https://github.com/romkatv/powerlevel10k/issues/2152#issuecomment-2156400844)

Thanks a lot for your reply; I found a solution down a few links in the article.

Note the below code didn't work for me:
`echo 'export LANG=en_US.UTF-8' >> ~/.zshrc`

Rather, navigate inside the **Environment** (Settings - Profile - Terminal - iterm2), change LANG to something with UTF-8 eliminated the issue.
<img width="956" alt="Screenshot 2024-06-09 at 2 51 26 PM" src="https://github.com/romkatv/powerlevel10k/assets/67832174/3b5d1b58-6f85-4322-ae4d-cb794c162f17">

**Comment by shadan-arif** [comment]
> [#2152 (comment)](https://github.com/romkatv/powerlevel10k/issues/2152#issuecomment-2156400844)

Thanks a lot for your reply; I found a solution down a few links in the article.

Note the below code didn't work for me:
`echo 'export LANG=en_US.UTF-8' >> ~/.zshrc`

Rather, navigate inside the **Environment** (Settings - Profile - Terminal - iterm2), change LANG to something with UTF-8 eliminated the issue.
<img width="956" alt="Screenshot 2024-06-09 at 2 51 26 PM" src="https://github.com/romkatv/powerlevel10k/assets/67832174/3b5d1b58-6f85-4322-ae4d-cb794c162f17">
