### ISSUE TITLE
timewarrior segment not showing?

### ISSUE THREAD

**Issue by niderhoff** [romkatv/powerlevel10k#2707]
Hello, am I supposed to see the timewarrior segment? what does it look like??

<img width="796" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/5991543/6b9eb119-2152-40b0-b01d-fe540fd78e41">

using Jet Brains Mono Nerd Font
p.s. while we're at it.. what is the small DB icon ..?

I changed to Meslo and it looks the same

<img width="1209" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/5991543/6d440290-dccd-4056-8c1c-b0b71fa95d36">

**Comment by romkatv** [comment]
I'm guessing that "small DB icon" is the timewarrior icon in your font. You can verify with this:

```zsh
print_icon TIMEWARRIOR_ICON
```

It looks better with the [recommended font](https://github.com/romkatv/powerlevel10k/blob/master/font.md).

**Comment by niderhoff** [comment]
Yes, you are right. I am using kitty, so I guess I need to fiddle around with my symbol_map

**Comment by romkatv** [comment]
You can print all icons with `get_icon_names`.

**Comment by rwmitchell** [comment]
get_icon_names is pretty cool but it would visually parse better if the icon was on left :-)

**Comment by romkatv** [comment]
```zsh
get_icon_names | awk -F: '{print $2, $1}'
```
