### ISSUE TITLE
When I move a file in Git, the git indicator becomes gray and stays gray no matter what, until I close the terminal.

### ISSUE THREAD

**Issue by amirashabani** [romkatv/powerlevel10k#271]
**Step to reproduce**:

![powerlevel10k rename](https://user-images.githubusercontent.com/23696447/67138626-48da8a80-f253-11e9-9864-9874ea523779.png)

As you can see, when I make changes by moving a file to another folder and then adding the change to stage, the git indicator becomes gray. It stays gray even after commit the changes, even if I `cd` out of the folder, even if I remove the `.git` folder.

![powerlevel10k gray](https://user-images.githubusercontent.com/23696447/67138650-8e975300-f253-11e9-8efd-62a31806ba09.png)

The only way I can get rid of this gray indicator is to close the terminal and reopen. What's going on?

**Comment by romkatv** [comment]
Please update powerlevel10k to the latest version and try again. If this doesn't help, please post the output of `uname -a`.

**Comment by amirashabani** [comment]
@romkatv Should've updated first. Thanks. The problem is fixed.

**Comment by romkatv** [comment]
> @romkatv Should've updated first.

The bug was still there when you opened the issue. I just fixed it.

Thanks for the report!
