### ISSUE TITLE
Promptbar graphic broken issue

### ISSUE THREAD

**Issue by circumeo** [romkatv/powerlevel10k#2712]
<img width="1416" alt="스크린샷 2024-06-23 오후 3 47 46 2" src="https://github.com/romkatv/powerlevel10k/assets/76243664/96b6ca1b-72a0-4bb2-8593-02086779e583">

The prompt graphic is broken like the picture above, can you tell me what the cause is?

Thank you in advance 🙏

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#sub-pixel-imperfections-around-powerline-symbols
