### ISSUE TITLE
unexpected symbol when creating a virtual environment

### ISSUE THREAD

**Issue by baoson1110** [romkatv/powerlevel10k#2713]
![image](https://github.com/romkatv/powerlevel10k/assets/75264215/d7b1ee82-2834-413c-aaf9-bc8a113b8655)

Please help me how to delete this unexpected symbol when I create a python virtual environment. Many thanks

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#what-do-different-symbols-in-git-status-mean

**Comment by baoson1110** [comment]
oh, i understand, thank you
