### ISSUE TITLE
The venv doesn't  show when activated

### ISSUE THREAD

**Issue by baoson1110** [romkatv/powerlevel10k#2715]
Hello team,

I have a question that why my venv name doesn't show when activated, it just shows the repository name 
![image](https://github.com/romkatv/powerlevel10k/assets/75264215/ebdada26-9796-479a-904f-5941a9e2111f)

Many thanks

**Comment by baoson1110** [comment]
i tried to set the POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV to true, but nothing happens :(

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/2317

**Comment by baoson1110** [comment]
thank you, it works ^^
