### ISSUE TITLE
OS Icon not working for EndeavourOS

### ISSUE THREAD

**Issue by Conava** [romkatv/powerlevel10k#2716]
The Powerlevel10k theme is only showing the Tux logo at the beginning of the line.

I am using the recommended Meslo Nerd Font. It did work on this exact machine before, but I upgraded my SSD and had to reinstall everything. Now its just the Tux Penguin showing up.

` typeset -pm 'POWERLEVEL9K_MODE|_p9k_os*' && cat /etc/os-release`

```
typeset _p9k_os=Linux
typeset _p9k_os_icon=
typeset POWERLEVEL9K_MODE=nerdfont-complete
NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"
```

**Comment by Syphdias** [comment]
I tired to fix it. Not sure, if I did. Roman will know :sweat_smile: 
You could try `POWERLEVEL9K_MODE=nerdfont-v3` as temporary workaround.

**Comment by Conava** [comment]
> You could try `POWERLEVEL9K_MODE=nerdfont-v3` as temporary workaround.

Thank you! I hope that fixes it.
I just found a different workaround for the meantime, maybe it also helps to identify the issue: I ran the config assistant again and tried a few different options. When asked if the Symbol was an up arrow I selected no (even though it was) and afterwards the logo was shown as expected.

**Comment by romkatv** [comment]
> When asked if the Symbol was an up arrow I selected no (even though it was) and afterwards the logo was shown as expected.

That's a valid workaround. If you update powerlevel10k, it will no longer be necessary. See https://github.com/romkatv/powerlevel10k/pull/2717#issuecomment-2196212506.
