### ISSUE TITLE
Arrows not displayed

### ISSUE THREAD

**Issue by sergeyzwezdin** [romkatv/powerlevel10k#272]
Hello,

Just installed powerlevel10k for . oh-myzsh from scratch.

After customization wizad I've got what I need, but there is one issue:

![image](https://user-images.githubusercontent.com/800755/67139335-8f86af80-f268-11e9-9690-3b0bc2b1ea3c.png)

It seems `?` symbol should actually be an arrow. I use `MesloLGS NG` font in iTerm2.

Could you advise how to fix it?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-do-i-have-a-question-mark-symbol-in-my-prompt-is-my-font-broken.

**Comment by sergeyzwezdin** [comment]
Aha! Thank you! 😀👍🏻🔥
