### ISSUE TITLE
Minimizing window broking my terminal

### ISSUE THREAD

**Issue by onlive1337** [romkatv/powerlevel10k#2720]
![image](https://github.com/romkatv/powerlevel10k/assets/102153021/ee817ff1-ebfe-4986-847d-1a5b4e96c568)
kinda this

**Comment by onlive1337** [comment]
using Pop Os btw

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#horrific-mess-when-resizing-terminal-window
