### ISSUE TITLE
How to change the icon?

### ISSUE THREAD

**Issue by zhouhao27** [romkatv/powerlevel10k#2722]
<img width="737" alt="Screenshot 2024-07-06 at 2 19 17 PM" src="https://github.com/romkatv/powerlevel10k/assets/8099731/5174bcea-6324-439a-bd94-718cb75771cc">

How to change the icon beside the `base`? Thanks.

**Comment by romkatv** [comment]
`POWERLEVEL9K_PYTHON_ICON='blah'`

**Comment by zhouhao27** [comment]
> POWERLEVEL9K_PYTHON_ICON=

Sorry. In which file? I could not find this setting.

**Comment by romkatv** [comment]
`~/.p10k.zsh`

**Comment by zhouhao27** [comment]
> `~/.p10k.zsh`

It works. Thanks.
