### ISSUE TITLE
History and auto suggestions

### ISSUE THREAD

**Issue by official-biswadeb941** [romkatv/powerlevel10k#2724]
Hey bro ...what you made is awesome but can you please tell me how to enable autosuggestion and history keeper for oh my zsh.................bro pls help me with this

**Comment by rwmitchell** [comment]
P10K makes a really nice prompt and it is awesome, but it doesn't do anything to enable zsh features.  For that, head over to oh-my-zsh.

**Comment by kyhyco** [comment]
Install autosuggestion - https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#homebrew

Super easy.

Not sure what this "history keeper" is though.

**Comment by official-biswadeb941** [comment]
thanks for the help
