### ISSUE TITLE
The top padding is disappeared after update

### ISSUE THREAD

**Issue by amirashabani** [romkatv/powerlevel10k#273]
I updated my `powerlevel10k` theme:

![powerlevel10k is updated](https://user-images.githubusercontent.com/23696447/67144777-7b05df80-f287-11e9-949f-4551fe03170a.png)

And now, every time I open a terminal, the top padding is gone.

![powerlevel10k top padding](https://user-images.githubusercontent.com/23696447/67144802-df28a380-f287-11e9-8bfd-9364ece98e94.png)

If I clear the screen, the padding is back.

![powerlevel10k padding is back](https://user-images.githubusercontent.com/23696447/67144812-febfcc00-f287-11e9-9f92-ddb2386605e4.png)

I don't know which version I had before update, but it happened after update.

How can I fix it, so that the padding is always there? 

Here's the output of `uname -a`, if it's relevant.
```

~ ❯ uname -a
Linux shabani 5.3.5-arch1-1-ARCH #1 SMP PREEMPT Mon Oct 7 19:03:08 UTC 2019 x86_64 GNU/Linux
```

**Comment by romkatv** [comment]
If you want to have an empty line every time you start `zsh`, type this:

```zsh
echo echo >>! ~/.zshrc
```

**Comment by romkatv** [comment]
Edit: It's better to add that `echo` at the top of `~/.zshrc` rather than at the bottom.
