### ISSUE TITLE
Mixed 'manual' and 'oh-my-zsh' installations.

### ISSUE THREAD

**Issue by Diego-MX** [romkatv/powerlevel10k#2735]
I am trying to use previously saved file configurations into a new computer. 

My configurations are backed up into `.p10k.zsh` -which I understand came from a manual configuration-. 

Then I tried to use `oh-my-zsh` installation, and I noticed it is read from `.oh-my-zsh/.../powerlevel10k.zsh-theme`.  

So I have two questions:  
- Can I copy or link `.p10k.zsh` into `.oh-my-zsh/.../powerlevel10k.zsh-theme`?  
- Is it recommended to use `.oh-my-zsh` with `p10k`  for the other plugins?  

I did find [this answer][reddit-ans] in Reddit which shed some light on the purpose of the two.  
But I'll appreciate any extra inputs, and may try the first answer anyhow.   

Thank you. 

[reddit-ans]: https://www.reddit.com/r/zsh/comments/196so1a/zsh_vs_p10k/

**Comment by romkatv** [comment]
`~/.p10k.zsh` is created by the configuration wizard. It contains configuration options for powerlevel10k. The same file is used regardless of the installation option you choose.

You can use the oh-my-zsh installation on your new machine. If you put `~/.p10k.zsh` from the old machine in the same location, the configuration wizard won't trigger, and you'll get the same prompt as before. If you don't put this file at this location, you'll be going through the wizard once again, and it'll create a new `~/.p10k.zsh`.

**Comment by Diego-MX** [comment]
Awesome.  I found out how to use my old configuration with `~/.p10k.zsh`.  
I changed some sym-links, but in the end it was easily done.  

Thanks.
