### ISSUE TITLE
Cannot exit zsh with Ctrl-D when using instant prompt

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#274]
See https://www.reddit.com/r/zsh/comments/dk53ow/new_powerlevel10k_feature_instant_prompt/f4ccwba/.

**Comment by MichaelAquilina** [comment]
without instant_prompt;
```
[[ -o ignore_eof ]] && echo "ignore_eof set" || echo "ignore_eof unset"
ignore_eof unset
```

with instant_prompt
```
[[ -o ignore_eof ]] && echo "ignore_eof set" || echo "ignore_eof unset"
ignore_eof unset
```

looks to be exactly the same

**Comment by MichaelAquilina** [comment]
Pressing `ctrl+D` after waiting around 10 seconds still shows the same issue

I keep my zshrc here if you are curious to take a peek about anything that could be interfering:
https://github.com/MichaelAquilina/swayconfig/blob/2000a7ae154bb3c9092adf494a709879702c1f9b/zshrc

**Comment by romkatv** [comment]
Thanks, this is useful. I'll try to reproduce this with your config. Probably has something to do with zplug.

**Comment by romkatv** [comment]
Cannot reproduce, unfortunately. Here's what I've tried.

1. Type this command:

```zsh
docker run -e LANG=C.UTF-8 -e TERM -it --rm debian:buster bash -uexc '
  apt update
  apt install -y zsh git curl gawk sudo nano libnotify-bin
  useradd -ms /bin/zsh test
  sudo -u test git clone https://github.com/zplug/zplug ~test/.zplug
  sudo -u test curl -fsSLo ~test/config https://raw.githubusercontent.com/MichaelAquilina/swayconfig/2000a7ae154bb3c9092adf494a709879702c1f9b/zshrc
  sudo -u test tee -a ~test/.zshrc >/dev/null <<END
export LANG=${LANG@Q}
export TERM=${TERM@Q}
if [[ -r "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh" ]]; then
  source "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh"
fi
function xdg-settings() {}
function dircolors() { command dircolors }
source ~/config
END
  exec su - test'
```
2. Once prompt appears, type `zplug install`.
3. Type `zsh`. Powerlevel10k prompt appears. Hit Ctrl-D to exit.
4. Repeat step 3.
5. Type `zsh`. Then again `zsh`. Hit Ctrl-D twice to get back to the login zsh.

As you can see in the docker command, I've made a few changes to your config.

1. Export `LANG` and `TERM`. I had to set these manually because I start with clean environment.
2. Enable instant prompt.
3. Make `xdg-settings` a no-op. I don't have it installed and it probably doesn't matter.
4. Effectively replace `dircolors ~/.dircolors` with plain `dircolors`. I don't have `~/.dircolors`. Probably doesn't matter.

Could you check whether the same thing works locally on your system?

1. Type this command. It assumes you have `sudo` and `useradd`/`userdel`. If not, please adjust accordingly.
```zsh
() {
  emulate -L zsh
  setopt err_return no_unset
  sudo useradd -ms =zsh test
  {
    sudo -Hu test git clone https://github.com/zplug/zplug ~test/.zplug
    sudo -Hu test curl -fsSLo ~test/config https://raw.githubusercontent.com/MichaelAquilina/swayconfig/2000a7ae154bb3c9092adf494a709879702c1f9b/zshrc
    sudo -Hu test tee -a ~test/.zshrc >/dev/null <<END
if [[ -r "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh" ]]; then
  source "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh"
fi
function xdg-settings() {}
function dircolors() { command dircolors }
source ~/config
END
    sudo su - test
 } always {
   sudo userdel -r test 2>/dev/null
 }
}
```
2. Perform steps 2-5 from above.

Let me know whether this works.

P.S.

zplug likes to hang shell. E.g., if I add `zplug check || zplug install` to `~/.zshrc` the way documentation suggests, it'll hang for good. Or if I run `zplug install` while having `POSIX` or `C` locale -- it'll hang for good, too. Maybe it's related.

**Comment by MichaelAquilina** [comment]
Interestingly this issue only seems to occur on `kitty` terminal (https://github.com/kovidgoyal/kitty). So it might potentially be a bug there.

**Comment by romkatv** [comment]
Thanks for this vital piece of information! I'll try to reproduce it with kitty tomorrow.

**Comment by romkatv** [comment]
Wasn't able to reproduce and no one else has complained. Closing. Please reopen if you are able to supple instructions that I can follow to reproduce the issue.

**Comment by romkatv** [comment]
Finally gotten down to it. Unlike all other terminals, kitty doesn't terminate until the number of open file descriptors to the TTY goes down to zero. This nasty bug is classified as feature in kitty :shrug: 

I've implemented a workaround in powerlevel10k. If you update, powerlevel10k will no longer hold open file descriptors to the TTY after the parent zsh fnishes, kitty should close when you hit Ctrl-D. That is, unless something else holds open file descriptors to the TTY, which can very well be.

**Comment by MichaelAquilina** [comment]
Thanks for this @romkatv !

**Comment by nyuszika7h** [comment]
This is not specific to KiTTY. I just installed powerlevel10k from git master and I have this issue with the default Windows console (WSL), Windows Terminal, mintty/wsltty, and also when using tmux over SSH. I can't close zsh with Ctrl+D until it has finished loading.

**Comment by romkatv** [comment]
> until it has finished loading

What does "finished loading" mean?

**Comment by nyuszika7h** [comment]
When the instant prompt shows up, I can't close zsh with Ctrl+D yet. But after the pyenv and rvm info shows up, it works fine.

**Comment by romkatv** [comment]
Makes sense. When instant prompt shows up, you cannot close with `exit` either, or run `ls`. Shell isn't ready to do anything yet.

This issue is about kitty not being able to be closed when pressing <kbd>Ctrl-D</kbd> *at any time*. You can reproduce it like this:

1. Configure kitty to start bash or zsh.
2. Start kitty.
3. Type `sleep 3600 & disown`.
4. Press <kbd>Ctrl-D</kbd>.
5. Kitty hangs (to be fair, kitty's developer says it doesn't hang, it just doesn't close).

There is a setting in Kitty that turns this behavior off.

Note that these steps don't depend on powerlevel10k. It's just how kitty works.

Also note that powerlevel10k no longer prevents kitty from closing.

**Comment by nyuszika7h** [comment]
Ah, I see, I misunderstood it. It's not a big deal since I don't usually want to immediately close zsh like that anyway.

**Comment by MichaelAquilina** [comment]
@romkatv I seem to be experiencing this same issue since I pulled the latest version of powerlevel10k

Confirmed this by commenting out this line:

```bash
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

**Comment by romkatv** [comment]
@MichaelAquilina please describe the issue you ate experiencing.

**Comment by MichaelAquilina** [comment]
It's the same one I experienced before the fix you mentioned here: https://github.com/romkatv/powerlevel10k/issues/274#issuecomment-622965319-permalink

Basically if I try to exit ((ctrl+D) or running `exit`), the shell stays open until I force close it with my window manager

![2020-05-19_15-20-29](https://user-images.githubusercontent.com/2650040/82338042-52dc8b80-99e4-11ea-9b38-563f173da466.png)
![2020-05-19_15-21-03](https://user-images.githubusercontent.com/2650040/82338094-60921100-99e4-11ea-8c8d-ea77afd49cca.png)

**Comment by romkatv** [comment]
Does it help if you set `close_on_child_death yes` in kitty config?

See https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.close_on_child_death.

**Comment by MichaelAquilina** [comment]
Seems like that works. Should this still be considered a regression?

**Comment by romkatv** [comment]
> Seems like that works. Should this still be considered a regression?

I cannot reproduce this. There is some interplay with something else you have.

What kitty does by default is absolutely awful. The config change merely makes the closing behavior sane and identical to all other terminals. At this point I don’t want to spend any more time just because kitty made a terrible choice for its default.

**Comment by MichaelAquilina** [comment]
I think that's fair enough if the workarounds introduce needless complexity. Might be worth adding something to the README as a warning to kitty users (and anyone else experiencing similiar issues) though?

**Comment by romkatv** [comment]
Not worth including anything in readme. If it was a popular or high quality terminal, things works be different.

**Comment by arrdem** [comment]
Another kitty user here ```close_on_child_death yes``` did indeed do the trick. Sigh. Thanks folks.
