### ISSUE TITLE
How to set POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES?

### ISSUE THREAD

**Issue by princox** [romkatv/powerlevel10k#2745]
hello, I'm huge fan of this project.

I'd like to change python virtualenv's name

example)
1. generated virtualenv: `python -m venv child`
2. current directory path: parent/child
3. current display in teminal : (parent)

I know default setting is `typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=(virtualenv venv .venv env)`
I don't know how to change name it parent to child

help me please.

Thank you for reading.

**Comment by romkatv** [comment]
What is the output of the following command when the venv is active?

```zsh
typeset -pm '*POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES|VIRTUAL_ENV'
```

**Comment by princox** [comment]
export VIRTUAL_ENV=/Users/princox/Documents/langchain_projects/freecodecamp_llm/venv
typeset -a POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=( virtualenv venv .venv env )
typeset _POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES='virtualenv|venv|.venv|env'

> What is the output of the following command when the venv is active?
> 
> ```shell
> typeset -pm '*POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES|VIRTUAL_ENV'
> ```

**Comment by romkatv** [comment]
Can you confirm that you currently see `freecodecamp_llm` in prompt (which identifies the project from which the virtual environment is active) but you want to see `venv` instead (which does not tell you which virtual environment is active)?

**Comment by romkatv** [comment]
If so, open `~/.p10k.zsh` and add `typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=()` to it. Then restart zsh with `exec zsh`.

**Comment by princox** [comment]
> typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=()

Thank you so much, this may be a mundane answer to you, but it was a big deal to me. I will try to be like you and create tools that are useful to others.

Have a good night. Thank you so much!!!

**Comment by romkatv** [comment]
You are welcome.

**Comment by realbogdanov** [comment]
> If so, open `~/.p10k.zsh` and add `typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=()` to it. Then restart zsh with `exec zsh`.

Thank you so much!!!!!!!!
