### ISSUE TITLE
aws profile not showing 

### ISSUE THREAD

**Issue by ravisrma** [romkatv/powerlevel10k#2749]
![Pasted image](https://github.com/user-attachments/assets/4d8b7a0b-2454-4bb6-9d1e-7efff1fbb6cf)

**Comment by sdhmh** [comment]
type aws and you will see it

**Comment by ravisrma** [comment]
![Pasted image 1](https://github.com/user-attachments/assets/a63038b7-4fd2-462c-84ba-246ba3d8d5ac)
not showing

**Comment by ravisrma** [comment]
see

**Comment by Syphdias** [comment]
For future reference, if one wants to change this behaviour: It can be done in the `.p10k.zsh` file by changing or removing `POWERLEVEL9K_AWS_SHOW_ON_COMMAND`.

This is from the lean config, what you can expect to find in your `.p10k.zsh`:
https://github.com/romkatv/powerlevel10k/blob/119e4039ef9068fa96490a90c559e7594843ec22/config/p10k-lean.zsh#L1351-L1354

PS: There are similar options for other segments like the `terraform` segment.

**Comment by romkatv** [comment]
Thanks, Christian.

There is also an FAQ entry for it: https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#why-some-prompt-segments-appear-and-disappear-as-im-typing
