### ISSUE TITLE
remove vertical line

### ISSUE THREAD

**Issue by SueRichard** [romkatv/powerlevel10k#2754]
Hi, i want to remove this vertile line. How should i do?

![image](https://github.com/user-attachments/assets/d6b3c3e0-8624-4f5b-8c0e-68ac13a38e59)

env: win11
bash: git bash
zsh: 5.9
p10k

try:
1.add those in p10.zsh

1.1

`typeset -g POWERLEVEL9K_VCS_LEFT_SEPARATOR='\u200B'`
`typeset -g POWERLEVEL9K_DIR_RIGHT_SEPARATOR='\u200B' `

1.2

`typeset -g POWERLEVEL9K_VCS_LEFT_SEPARATOR=''`
`typeset -g POWERLEVEL9K_DIR_RIGHT_SEPARATOR=''`

all did not take effect, this line still here. Could you let me know where I can modify to delete or remove this line?

2. I do not change follow

`typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''`
`typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''`

because I want to keep separator '\uE0B0'

Thx!

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#sub-pixel-imperfections-around-powerline-symbols

**Comment by SueRichard** [comment]
Thx for your replying, i try another terminal is all right. Such as vscode, but in idea inner terminal although i changed the shell to git bash has this problem.
