### ISSUE TITLE
MesloLGS NF Italic does not get installed on Ubuntu

### ISSUE THREAD

**Issue by ved-asole** [romkatv/powerlevel10k#2756]
It does not installs for me also after clicking on install :  [MesloLGS NF Italic.ttf](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf)

Shows installing but then stops :

![image](https://github.com/user-attachments/assets/ffccfd93-88ec-4dec-bab6-eaf6d9c7c9a8)

![image](https://github.com/user-attachments/assets/5b7219a9-37f1-417b-acee-623dc8197423)

**Comment by romkatv** [comment]
It's just a font, you install it like any other. If that doesn't work, file an issue with the OS provider.

**Comment by ved-asole** [comment]
ok, Thanks

**Comment by ved-asole** [comment]
Raised a question for Ubuntu : https://askubuntu.com/questions/1526818/meslolgs-nf-italic-font-does-not-get-installed
