### ISSUE TITLE
upward arrow character doesn't render properly?

### ISSUE THREAD

**Issue by mkdeak** [romkatv/powerlevel10k#276]
I just installed p10k with oh-my-zsh for my iTerm2, I followed these notes: https://gist.github.com/kevin-smets/8568070 

Everything looked alright except for (what I assume to be) the upward arrow character. (see attached screenshot) 

I tried reconfiguring p10k and also reinstalling fonts but I couldn't fix it. 

![image](https://user-images.githubusercontent.com/11228599/67163180-c7265200-f363-11e9-8caf-1d1a36a79834.png)

Any ideas what I did wrong?

**Comment by romkatv** [comment]
Could you update powerlevel10k to the latest version (`git -C $ZSH_CUSTOM/themes/powerlevel10k pull`), restart zsh and run `p10k configure` again? If this issue is still there, please post the output of `git status` and `typeset -m 'VCS_STATUS_*'` while in that directory.

**Comment by romkatv** [comment]
Oh, you are referring to that question mark, right? If so, see https://github.com/romkatv/powerlevel10k/#why-do-i-have-a-question-mark-symbol-in-my-prompt-is-my-font-broken.

**Comment by mkdeak** [comment]
> Oh, you are referring to that question mark, right? If so, see 

Yes! And the linked article makes complete sense -- sorry for the dumb question!
