### ISSUE TITLE
[oh-my-zsh] errors

### ISSUE THREAD

**Issue by klazustrem** [romkatv/powerlevel10k#2768]
/Users/klazustrem/.p10k.zsh: line 25: local: can only be used in a function
/Users/klazustrem/.p10k.zsh: line 29: builtin: setopt: not a shell builtin
/Users/klazustrem/.p10k.zsh: line 31: syntax error near unexpected token ')
/Users/klazustrem/.p10k.zsh: line 31: '() {'

**Comment by romkatv** [comment]
?

**Comment by klazustrem** [comment]
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/1d2d1dd8-4b15-4a6f-96bd-30cca3903397">
i cant get rid of this

**Comment by romkatv** [comment]
Try deleting lines 13, 14, 15 and 16 of `~/.zshrc`.

**Comment by klazustrem** [comment]
i dont really know im pretty new to allat started in the morning

**Comment by klazustrem** [comment]
@romkatv

**Comment by romkatv** [comment]
> how to delete them

With a text editor.
