### ISSUE TITLE
Escape sequences cause padding to brake

### ISSUE THREAD

**Issue by canTuncPekkan** [romkatv/powerlevel10k#2777]
![broken](https://github.com/user-attachments/assets/e2b05677-c4c5-48c7-8d2b-b4e394ac1a01)
<img width="1322" alt="Normal" src="https://github.com/user-attachments/assets/fc0e976d-c9eb-4f63-bfbc-a685d011f378">

when ANSI Escape Codes 
ESC[5m and ESC[25m (set blinking mode and reset blinking mode)
are used the padding counts them as characters, causing the left side bars not to mach up with each other

here is the line that causes it 
` typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=$'\e[5m\e[25m'` ( is the clock icon)

**Comment by romkatv** [comment]
Enclose them in `%{...%}`.
