### ISSUE TITLE
Support for TTY

### ISSUE THREAD

**Issue by davidmogar** [romkatv/powerlevel10k#278]
Hello,

I'm using lean in urxvt with Meslo don't and I have to say that works quite well. Now, I also usually jump into a /dev/tty and there, there are no poweline fonts. Happens also over SSH from PuTTY, although I could configure this.

My question is, is there any way to configure powerlevel10k to be more TTY friendly? Specially regarding missing symbols as I don't really mind about colors there.

I've been trying to find a solution to that but what I do right now is to unset any theme if I'm in a TTY and not in my urxvt. Not ideal.

Thanks in advance for any answer!

**Comment by romkatv** [comment]
Powerlevel10k supports TTY. You just need to create a config restricted to colors 0-7 and ascii.

You can start by copying `p10k-lean.zsh` and then changing all colors and icons manually. Here's a very short version:

```zsh
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir newline prompt_char)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=
typeset -g POWERLEVEL9K_DIR_FOREGROUND=4
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=2
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=1
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='>'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='<'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='^'
typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
```

**Comment by romkatv** [comment]
FYI: Lean, Classic and Rainbow styles in the configuration wizard now have an option to use ASCII charset. Lean style also has an option to use 8 colors. Combining these two you'll get prompt that works everywhere.
