### ISSUE TITLE
Multiple -zsh processes from p10k

### ISSUE THREAD

**Issue by smartinellimarco** [romkatv/powerlevel10k#2780]
For each terminal tab opened, I am seeing multiple instances of the -zsh command:

```bash
❯ ps
  PID TTY           TIME CMD
85912 ttys000    0:00.21 -zsh
85924 ttys000    0:00.00 -zsh
85937 ttys000    0:00.00 -zsh
85938 ttys000    0:00.00 -zsh
85940 ttys000    0:00.02 /Users/marco/.cache/gitstatus/gitstatusd-darwin-arm64 -G v1.5.4 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 16
```

After digging around and bisecting my config, it looks like p10k is creating these extra processes. 

I think this might be related to [issue #2642](https://github.com/romkatv/powerlevel10k/issues/2642), but I’m not sure if this is expected behavior or not.

**Comment by romkatv** [comment]
It's expected. See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#why-does-powerlevel10k-spawn-extra-processes.
