### ISSUE TITLE
MacOS 15.1 show ???

### ISSUE THREAD

**Issue by zouchengli** [romkatv/powerlevel10k#2785]
![image](https://github.com/user-attachments/assets/cf20d338-7e53-4bee-8999-196c232ca595)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#icons-glyphs-or-powerline-symbols-dont-render

**Comment by zouchengli** [comment]
![image](https://github.com/user-attachments/assets/841356d5-fc6c-467d-93b9-b70fd18b95b0)
OK ! because today upgrade my MacOS Terminal auto changed font family.
![image](https://github.com/user-attachments/assets/96dd4daf-f319-4307-9d77-d105a7c54908)
