### ISSUE TITLE
Prompt settings not available anymore in a new configuration

### ISSUE THREAD

**Issue by masterlog80** [romkatv/powerlevel10k#2787]
Hello,
I have just installed `powerlevel10k` on a new Ubuntu 24.04 device and proceeded with the documentation. However, completing the configuration with `p10k configure` didn't let me set the Prompt settings (e.g. *Style* and *Color*) like before. I have attached some screenshots from a Youtube video.
Is there a way to adjust those settings as well (especially setting *Style* as *Classic* or eventually *Rainbow*).

Regards, 

<img src="https://github.com/user-attachments/assets/83c87831-78a4-4225-b216-bbc91d3e1db8" width=50% height=50%>
<img src="https://github.com/user-attachments/assets/e869ae10-ff7d-4810-8e7f-7afaeb45ec5b" width=50% height=50%>

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by masterlog80** [comment]
Hello @romkatv,
Thank you for getting back. Here is my version:
```
zsh --version
zsh 5.9 (x86_64-ubuntu-linux-gnu)
```
and:
```
locale -a
C
C.utf8
POSIX
en_US.utf8
```
Any ideas?

**Comment by romkatv** [comment]
All my ideas are written down in the doc I've linked. Do read it.

**Comment by masterlog80** [comment]
Uh.... nevermind. I switched to a different terminal ran `p10k configure` again and the missing setting come back!
