### ISSUE TITLE
git show "master !3 ?1"

### ISSUE THREAD

**Issue by sechelper** [romkatv/powerlevel10k#2797]
help me

<img width="300" alt="企业微信截图_b0357ead-86af-48c5-a2fd-9ce88369ed6f" src="https://github.com/user-attachments/assets/b706d2c9-c92e-4cc3-88fb-62a274b266f4">

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#what-do-different-symbols-in-git-status-mean

**Comment by sechelper** [comment]
This code "!3 ?1" not there

Thank you for your reply. I have already started using Pure mode.

**Comment by romkatv** [comment]
> This code "!3 ?1" not there

It is.

> I have already started using Pure mode.

Pure is worse than Lean.
