### ISSUE TITLE
Unwanted characters in shell after upgrade to v0.6.6.r239.g0103fe8-1

### ISSUE THREAD

**Issue by Forger7** [romkatv/powerlevel10k#28]
After upgrading to said version a new terminal window shows the following output: 
![Screenshot_20190316_140233](https://user-images.githubusercontent.com/5951156/54475661-2a5f6d00-47f4-11e9-9fba-e1ef86ea26f8.png)
 
${(Q)${:-}}  ${(Q)${:-user@host}}   ${(Q)${:-\~}}  ${_P9K_HOOK1+${_P9K_HOOK2-${_P9K_HOOK2=}$(echo >&12)}}${_P9K_HOOK1=}                                                                             ✔  334  13:59:47 

**Comment by romkatv** [comment]
Ouch! That looks awful :-/

Something seems to be unsetting `prompt_subst`. Could you `git pull` and try again? I've moved `setopt prompt_subst` so that it runs on every prompt.

**Comment by Forger7** [comment]
That's working, thank you.

**Comment by romkatv** [comment]
Thanks for verifying!
