### ISSUE TITLE
Powerlevel10k potentially breaks login screen on Ubuntu 19.10

### ISSUE THREAD

**Issue by fractal** [romkatv/powerlevel10k#280]
There's a bug that affects gnome-keyring, and the login screen and i'll describe the steps i've done to reproduce it twice, although i don't have full details as to what exactly is causing it.

Issue can be summarized as follows:

On Ubuntu 19.10, but not at least 18.04 (another computer i have using the older release), there's an issue that prevents the user to login to a gnome session

The issue shows up when checking the session manager:

```
service gdm3 status
Process: ExecStartPre: /usr/share/gdm/generate-config (code=exited,status=0/SUCCESS)
Process: ExecStartPre: /usr/lib/gdm3/gdm-wait-for-drm (code=exited,status=0/SUCCESS)
...

gdm-password: gkr-pam: unable to local control file
```

Relevant components:

  * gdm3 3.34.1-1
  * gnome-shell 3.34.1-1
  * gnome-keyring 3.34.0-1
  * zsh 5.77.1-ubuntu2
	
	
	

This does not occur on a fresh installation of Ubuntu. It only happens once some of these tools are installed:

  * zsh (ubuntu package https://packages.ubuntu.com/eoan/zsh , manually change shell for user) - https://askubuntu.com/questions/131823/how-to-make-zsh-the-default-shell
	* oh-my-zsh  (brings in lots of plugins, although only git was sourced) - https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH
	* powerlevel10k  (shell theme ) - https://github.com/romkatv/powerlevel10k

The tools would appear to work fine, until you reboot the machine, and are asked to login, at which point gkr-pam complains that it can't locate control file.

Unfortunately i don't have better details because eventually i broke so much my login that i decided to reinstall the system from scratch.

Upon installation, i started from fresh, with no zsh, and everything worked. Once zsh was installed, it will no longer work.

A fix for this was to revert to bash shell.

The key change was to no include this line at the top of .bashrc

```
#exec zsh
```

So i can confirm the issue is there, but that's as far as i got after several hours of investigations.

I appreciate that this bug may not be a oh-my-zsh specific bug, but seems that its part of the problem, so i wanted to raise it here given the severity.

https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1849081
https://github.com/robbyrussell/oh-my-zsh/issues/8296

https://gitlab.gnome.org/GNOME/gnome-keyring/issues/28
https://gitlab.gnome.org/GNOME/gnome-keyring/issues/26

https://github.com/GNOME/gnome-keyring/blob/master/pam/gkr-pam-module.c#L676
https://github.com/GNOME/gnome-keyring/blob/master/pam/gkr-pam-module.c#L847

https://github.com/GNOME/gnome-keyring/commit/443a821cba105e8f277828a67b3d019b67f1324a
https://github.com/GNOME/gnome-keyring/commit/b22d058a055ec3e0f31ae16417f16b42baadb42f

https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1817128
https://bugs.launchpad.net/ubuntu/+source/gnome-keyring/+bug/1818616

**System:**
 - OS: Linux Ubuntu 19.10
 - Zsh version 5.77.1
 - Terminal emulator Gnome Terminal

**Comment by romkatv** [comment]
> Some info about instant prompt: https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-instant-prompt. It doesn't mention the issue you are experiencing as I'm still trying to figure out what to do about it.

I added a note there:

> **IMPORTANT UPDATE**: Instant prompt is incompatible with zsh startup configs that may require
console input. This includes asking for a keyring password and *[Y/N]* confirmations. It is
currently **NOT RECOMMENDED** that you enable instant prompt.

**Comment by romkatv** [comment]
I see that you've posted the same issue in many places. Please close all instances except for this to avoid wasting people's time.

**Comment by romkatv** [comment]
Please attach your `~/.zshrc` to the issue (either as a file attachment, or just paste its content).

> Upon installation, i started from fresh, with no zsh, and everything worked. Once zsh was installed, it will no longer work.

What what working and what no longer works? Please describe what you are doing, what you expect to happen and what is actually happening.

>  there's an issue that prevents the user to login to a gnome session

What do you do to login to a gnome session? How does it look when it works? And when it doesn't?

**Comment by romkatv** [comment]
Closing as the reporter is MIA. I've done all I could based on the little information that was provided.

**Comment by fractal** [comment]
Using the latest ZSH + oh_my_zsh + Powerlevel10k is working.

An important part of fixing this problem also seems to be related to not include the following line on 
the first line of   `.bashrc`

```bash
exec zsh
```

This was suggested to enable zsh but seems to interfere with login screen somehow.

Thanks for the support!

**Comment by romkatv** [comment]
> Using the latest ZSH + oh_my_zsh + Powerlevel10k is working.

Glad it's working. FYI: I don't know what the problem was. The issue description is scarce on details and you haven't answered any of my questions.

> the first line of `.bashrc`
> 
> ```shell
> exec zsh
> ```
>
> This was suggested to enable zsh but seems to interfere with login screen somehow.

That's a bizarre suggestion. It will certainly break Bash but won't "enable zsh".

To start zsh manually, type `zsh`. To make zsh your login shell, type `chsh -s "$(which zsh)"`. If `chsh` complains that zsh is an invalid shell, type `sudo tee -a /etc/shells <<<"$(which zsh)"`.

**Comment by mcornella** [comment]
Normally that suggestion is given when you don't have admin permissions to add zsh as a default shell. But the `exec zsh` line should be run only when the session is interactive, see https://unix.stackexchange.com/a/26782.

**Comment by romkatv** [comment]
> Normally that suggestion is given when you don't have admin permissions to add zsh as a default shell.

Login shell nowadays is largely irrelevant. Most users aren't logging through TTY but straight into desktop environment. All modern graphical terminal emulators allow you to choose what to run. By default it's your login shell but you can change it to anything else.

> But the `exec zsh` line should be run only when the session is interactive, see https://unix.stackexchange.com/a/26782.

This will replace every interactive `bash` with `zsh`, dropping all arguments in the process. `bash -ic true` will connect to `$TTY`. `bash --norc` will read configs despite being told not to. This can break lots of things for very little gain.

FWIW, I don't know how `exec zsh` led to this issue. Originally I thought I understood what the OP meant but after reading the bug description a few more times I realized I was imagining things. There is seemingly a lot of information in the description but it's an illusion. There is just many words. I've no idea what the problem was and how (or if) it was fixed.

**Comment by FreezeSoul** [comment]
it's very useful!
