### ISSUE TITLE
Can I stop fetching gitstatusd?

### ISSUE THREAD

**Issue by hjsg1010** [romkatv/powerlevel10k#2800]
[powerlevel10k] fetching gitstatusd .. |                                              
[ERROR]: gitstatus failed to initialize.

Failed to download gitstatusd-linux-x86_64 from any mirror:

  1. https://github.com/romkatv/gitstatus/releases/download/v1.5.4/gitstatusd-linux-x86_64.tar.gz
  2. https://gitee.com/romkatv/gitstatus/raw/release-v1.5.4/release/gitstatusd-linux-x86_64.tar.gz

Check your internet connection, then restart your shell.

---
I can't fetching gitstatusd becasue I'm at the internal server. 
What I tried is

unzip gitstatusd-linux-x86_64.tar.gz
move gitstatusd file to ./local/bin/
chmod +x ~/.local/bin/gitstatusd

```
# edit .p10k.zsh
POWERLEVEL10K_GITSTATUS_EXECUTABLE="$HOME/.local/bin/gitstatusd"
```
---

somtimes it works, however when I open new terminal, the first error message occurs.

Please help me.

also I have question about git icons.
I want to change 'git' to github icons. and I don't know why I get '?' (I set my configure to use many icons )
(sorry I will update pictures later due to internal server issues :(  )

**Comment by romkatv** [comment]
> I can't fetching gitstatusd becasue I'm at the internal server.

See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access.

> I want to change 'git' to github icons

```zsh
typeset -g POWERLEVEL9K_VCS_GIT_ICON='\uF113'
```

It's not a good idea though because now every branch on every repo will look as if it had a remote on github.com.

> I don't know why I get '?'

See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#what-do-different-symbols-in-git-status-mean

**Comment by hjsg1010** [comment]
> > I can't fetching gitstatusd becasue I'm at the internal server.
> 
> See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#how-do-i-install-powerlevel10k-on-a-machine-without-internet-access.
> 
> > I want to change 'git' to github icons
> 
> ```shell
> typeset -g POWERLEVEL9K_VCS_GIT_ICON='\uF113'
> ```
> 
> It's not a good idea though because now every branch on every repo will look as if it had a remote on github.com.
> 
> > I don't know why I get '?'
> 
> See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#what-do-different-symbols-in-git-status-mean

Oh Sorry, 
I should have reviewed the README more carefully.
Thank you so much for your assistance.
Wishing you a pleasant and fulfilling end to the year
