### ISSUE TITLE
iTerm2: vertical split causes an unexpected spawn of new prompt

### ISSUE THREAD

**Issue by zzJinux** [romkatv/powerlevel10k#2802]
https://github.com/user-attachments/assets/0227f943-2769-4d53-a39e-1ed44495f0c3

The horizontal split is not relevant.

I don't know whether the root cause is from iTerm2, zsh, or p10k. The only clue I found is that turning off p10k got rid of the issue. It might be related to #1670, possibly.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#horrific-mess-when-resizing-terminal-window

**Comment by zzJinux** [comment]
@romkatv I've seen it. I was curious if the new prompt spawning shares the same root cause, and so it is. Thank you.
