### ISSUE TITLE
Shorten the last directory name (basename)

### ISSUE THREAD

**Issue by MahdiNazemi** [romkatv/powerlevel10k#2803]
Is there a way to shorten the `basename` of a path in addition to all the previous segments?

I have tried the following settings but they did not help.
`typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique`
`typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=0`
`typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=0`

**Comment by romkatv** [comment]
Works for me.

![image](https://github.com/user-attachments/assets/20f0c1ff-57b5-4e00-8ffe-39546a753333)

**Comment by romkatv** [comment]
What exactly do you do after running `p10k configure`?

**Comment by romkatv** [comment]
Can you upload a config in which `POWERLEVEL9K_SHORTEN_DIR_LENGTH=2` works as you expect but `POWERLEVEL9K_SHORTEN_DIR_LENGTH=0` does not?

**Comment by romkatv** [comment]
Your config works for me as expected. Let's see if it works on your machine. Please run the following command and post a screenshot of your terminal when it finishes.

```zsh
zsh -fise <<\END
cd -- ~/repos/transformers
tmp=/tmp/p10k-test
rm -rf -- $tmp
mkdir -- $tmp
git -C $tmp clone --depth=1 https://github.com/romkatv/powerlevel10k.git
curl -fsSLo $tmp/p10k.zsh https://github.com/user-attachments/files/18136994/p10k.zsh.txt
sed -i.bak 's/POWERLEVEL9K_SHORTEN_DIR_LENGTH=1/POWERLEVEL9K_SHORTEN_DIR_LENGTH=0/' $tmp/p10k.zsh
source -- $tmp/p10k.zsh
source -- $tmp/powerlevel10k/powerlevel10k.zsh-theme
END
```

**Comment by romkatv** [comment]
That's very interesting. Let's see if the content of the directory you are in is relevant. Please do the same with this command:

```zsh
zsh -fise <<\END
tmp=/tmp/p10k-test
rm -rf -- $tmp
mkdir -- $tmp
git -C $tmp clone --depth=1 https://github.com/romkatv/powerlevel10k.git
curl -fsSLo $tmp/p10k.zsh https://github.com/user-attachments/files/18136994/p10k.zsh.txt
sed -i.bak 's/POWERLEVEL9K_SHORTEN_DIR_LENGTH=1/POWERLEVEL9K_SHORTEN_DIR_LENGTH=0/' $tmp/p10k.zsh
mkdir -p -- $tmp/repos/transformers
cd -- $tmp/repos/transformers
source -- $tmp/p10k.zsh
typeset -p POWERLEVEL9K_SHORTEN_DIR_LENGTH
source -- $tmp/powerlevel10k/powerlevel10k.zsh-theme
END
```

**Comment by romkatv** [comment]
Try setting `POWERLEVEL9K_SHORTEN_FOLDER_MARKER=''`.

**Comment by romkatv** [comment]
You are very welcome.
