### ISSUE TITLE
Resizing the window will mess up the layout

### ISSUE THREAD

**Issue by cdllmq** [romkatv/powerlevel10k#2807]
<img width="675" alt="Snipaste_2024-12-26_20-03-28" src="https://github.com/user-attachments/assets/d197010b-a256-4096-bde2-df433bd44932" />
After I installed the "Powerlevel10k" theme, the interface became very chaotic after resizing the window, and I had to restart the terminal to restore it。
I love this theme so much, can you fix this problem?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k?tab=readme-ov-file#horrific-mess-when-resizing-terminal-window
