### ISSUE TITLE
Artefacts generated upon window resize

### ISSUE THREAD

**Issue by AlfredJKwack** [romkatv/powerlevel10k#281]
Hi,

MacOs, when decreasing the terminal.app window width, the theme generates artefacts.

<img width="689" alt="Screenshot 2019-10-21 at 13 53 35" src="https://user-images.githubusercontent.com/557102/67203035-9bee4200-f3f9-11e9-82f0-7eb9f6d98559.png">

I hope someone can take a look.

**Comment by romkatv** [comment]
That's how zsh does it. Nothing I can do about it. Every prompt that spans the whole line will create a mess when you resize your window. See https://github.com/romkatv/powerlevel10k/issues/175.

By the way, the font you are using, and the terminal, aren't working very well with the style you chose. There are gaps between the parts of the frame that shouldn't be there. The colors of those pointy triangles look wrong, too. Try installing iTerm2 and then running `p10k configure` form it.

**Comment by AlfredJKwack** [comment]
Thanks Roman! I should have realized this had nothing to do with 10k. Appreciate all the work you've put into this.

I'll take your pointers re. the fonts and iTerm2. I agree that the font was not great; [Nerd-fonts](https://github.com/ryanoasis/nerd-fonts/) have come to the rescue in the meantime. iTerm2 will come down the line.

**Comment by romkatv** [comment]
I recommended iTerm2 because it'll automatically install [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k). iTerm2 is also a better terminal overall. It's not *that* much different though.

**Comment by ben2talk** [comment]
Anyone looking at this - note that KiTTY redraws fine when resized.
