### ISSUE TITLE
gitstatus broken post-`ad48c1e`

### ISSUE THREAD

**Issue by pdelre** [romkatv/powerlevel10k#282]
gitstatusd is broken for a large repo after the commit `ad48c1e`. I'm not sure how to get additional information but happy to do so. I've created the issue in this repo as I can checkout `e1f5e46` to workaround the issue but realize this might not be where the true issue resides.

_`ad48c1e` output: stuck at `loading`_

```
pdelre@laptop ~/my/large/project loading
$ 
```

_`e1f5e46` output: loads status_

```
pdelre@laptop ~/my/large/project my_branch!?
$ 
```

**Comment by romkatv** [comment]
Please `cd` into `~/my/large/project`, type the following command and post its output.

```zsh
() {
  emulate -L zsh
  setopt err_return
  typeset -m 'ZSH_VERSION|ZSH_PATCHLEVEL'
  zsh --version
  uname -a
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    zsh -dfeic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start MY
      function process-git-status() {}
      gitstatus_query -c process-git-status -t 5 MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_XTRACE_MY
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    rm -rf $tmp
  }
}
```

**Comment by romkatv** [comment]
Apparently, gitstatusd segfaults. I'll need to see the `core` file to figure out what's going on.

Please do the following:

1. Enable core dumps: https://stackoverflow.com/questions/9412156/how-to-generate-core-dumps-in-mac-os-x/12118329
2. Run the same command again to make gitstatusd segfault.
3. Find the core file in `/cores`, zip it and attach to this issue.

**Comment by romkatv** [comment]
I suppose this repo isn't public?

Does this problem reproduce if you clone this repo in another location?

What's the output of `git status` in that repo?

**Comment by pdelre** [comment]
> I suppose this repo isn't public?

Correct

> Does this problem reproduce if you clone this repo in another location?

It does not reproduce on a fresh clone.

> What's the output of git status in that repo?

As expected. 1 modified file, 1 untracked file. Stashing all changes also has no effect.

> I'll need to see the `core` file to figure out what's going on.

The full dump is 1.5G, which I might have issues uploading. Does this diagnostic file give you anything (located in `~/Library/Logs/DiagnosticReports/gitstatusd-darwin-x86_64_2019-10-21-154055_alt00311.crash`)?

[gitstatusd-darwin-x86_64_2019-10-21-154055_alt00311.crash.txt](https://github.com/romkatv/powerlevel10k/files/3752678/gitstatusd-darwin-x86_64_2019-10-21-154055_alt00311.crash.txt)

**Comment by romkatv** [comment]
Let's try old-school methods first. If they don't work, I'll set up an ftp server where you can upload the core.

I've forked gitstatus, added a ton of logging into it and built an unstripped binary without optimizations or parallelism. This should make debugging much easier. You might even be able to get a decent stack trace on your machine if this becomes necessary.

Please type the following command, then zip `/tmp/gitstatus-debug.log` and attach it to this issue. Store the core file somewhere so that you have one that matches the logs that you'll send me. I might ask you to do things with that core.

```zsh
{ [[ -d ~/gitstatus-debug ]] && git -C ~/gitstatus-debug pull || git clone https://github.com/romkatv/gitstatus-debug.git ~/gitstatus-debug; } && ~/gitstatus-debug/test.zsh &>/tmp/gitstatus-debug.log
```

**Comment by pdelre** [comment]
Attached is the full log but here is the highlight.

```
[2019-10-22 08:37:49 0000000109dcd5c0 DEBUG src/gitstatus.cc:98] GetRemote()
[2019-10-22 08:37:49 0000000109dcd5c0 DEBUG src/git.cc:178] git_branch_remote()
[2019-10-22 08:37:49 0000000109dcd5c0 DEBUG src/git.cc:188] git_reference_lookup()
[2019-10-22 08:37:49 0000000109dcd5c0 DEBUG src/git.cc:198] git_remote_name()
Assertion failed: (remote), function git_remote_name, file /var/folders/4y/ygyf9gbd37v1jz23pbqr50v80000gn/T/gitstatus/libgit2/src/remote.c, line 584.
```

[gitstatus-debug.log](https://github.com/romkatv/powerlevel10k/files/3755640/gitstatus-debug.log)

**Comment by romkatv** [comment]
Thanks! Got lucky with the assert there.

You have a branch that's tracking another branch on the same (local) repo. I didn't know it was possible. That is, if you run `git push`, you'll simply push from your current local branch to another local branch (all in the same directory). Likewise with `git pull`. Have you set this up intentionally?

Please run the same command again as last time. It shouldn't crash. If it does, please attach its log.

**Comment by pdelre** [comment]
Yes, that is correct. I have my feature branch pointing to my local `master` via [`branch. autosetupmerge`](https://stackoverflow.com/a/22147540). I've found this configuration works well in large monorepos with a rapidly changing `master`.

The patch does not appear to crash. It does log an ERROR however; is that intentional?

```
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/gitstatus.cc:98] GetRemote()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/git.cc:178] git_branch_remote()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/git.cc:188] git_reference_lookup()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/git.cc:198] git_remote_name()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/git.cc:200] git_branch_name()
[2019-10-22 09:52:27 00000001136d15c0 ERROR src/git.cc:204] std::strstr(branch, name.c_str()) == branch:
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/git.cc:192] git_reference_free()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/git.cc:181] git_remote_free()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/git.cc:183] git_buf_free()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/gitstatus.cc:67] git_reference_free()
[2019-10-22 09:52:27 00000001136d15c0 DEBUG src/gitstatus.cc:56] git_config_free()
[2019-10-22 09:52:27 00000001136d15c0 INFO src/response.cc:69] Replying without git status
[2019-10-22 09:52:27 00000001136d15c0 INFO src/timer.cc:64] Timing for: request: 11.665ms cpu
[2019-10-22 09:52:27 00000001136d15c0 ERROR src/gitstatus.cc:186] Error processing request: "test" for "/Users/pdelre/my/large/project"
[2019-10-22 09:52:27 00000001136d15c0 INFO src/request.cc:111] EOF. Exiting.
'test'
'0'
```

**Comment by romkatv** [comment]
> The patch does not appear to crash.

Good!

> It does log an ERROR however; is that intentional?

Totally a bug. Please try again.

P.S.

I just noticed that your prompt looks like Bash prompt. If you are indeed using Bash, I apologies for sending you Zsh commands to run. The last command (the one that you need to retry now) should work in Bash though.

**Comment by pdelre** [comment]
That looks much better!

```
[2019-10-22 10:27:20 00000001109375c0 INFO src/gitstatus.cc:184] Successfully processed request: "test" for "/Users/pdelre/my/large/project"
[2019-10-22 10:27:20 00000001109375c0 INFO src/request.cc:111] EOF. Exiting.
'test'
'1'
'/Users/pdelre/my/large/project'
'6603c002cf4dc66d87c0c892cee744810068de3e'
'feature'
'master'
'.'
''
''
'107194'
'0'
'0'
'0'
'0'
'0'
'0'
'14'
''
'0'
```

> I just noticed that your prompt looks like Bash prompt.

Hmm, certainly using ZSH..

**Comment by romkatv** [comment]
> That looks much better!

Yep, looks like it works now. Could you replace your regular gitstatusd binary with this version and verify that prompt also works? It'll be very slow though. I'll cut a proper release once I have your confirmation.

> Hmm, certainly using ZSH..

Good choice. I've got misled by that dollar in your (fake) prompt.

**Comment by pdelre** [comment]
Confirmed it's working within p10k's current `master` (`e92da0e`).

**Comment by romkatv** [comment]
I've pushed a new gitstatusd binary but only for darwin. I'll rebuild binaries for other platforms when there are more substantial changes or if someone trips over the same bug on another OS.

Please update powerlevel10k and close the issue if it's resolved for you.

P.S.

If you've enabled core dumps just for this issue, you'll probably want to disable them now.

**Comment by pdelre** [comment]
Thank you for your time, projects, and empathy for ensuring I don't forget about disabling core dumps!

**Comment by romkatv** [comment]
My pleasure. I thank you, in turn, for reporting this bug and providing superb debugging assistance.

**Comment by nixmaniack** [comment]
I think I have the same issue where the git info gets stuck in `loading` state forever. And, I do have the same branching setup as you mentioned. 
> You have a branch that's tracking another branch on the same (local) repo

I'm on Linux (Ubuntu 19.04), should I be waiting for updated binary based on your comment @romkatv?
>  I'll rebuild binaries for other platforms

**Comment by romkatv** [comment]
> I'm on Linux (Ubuntu 19.04), should I be waiting for updated binary based on your comment @romkatv?

I've already released the fixed binaries for Lunux.

Are you sure the bug is reproducible with the latest version of powerlevel10k? (The version of Ubuntu doesn't matter. Just make sure you are on https://github.com/romkatv/powerlevel10k/commit/a7db19ec7e349bf34260fdc93b6ca7346af6e218 or later.)

**Comment by nixmaniack** [comment]
I saw there were a lot of stale `gitstatusd` processes. I killed them and updated to latest version. I don't see the issue now. I'll update if I see it again. Thanks!

**Comment by romkatv** [comment]
> I saw there were a lot of stale `gitstatusd` processes.

This is something else entirely. How do you know they were stale?

**Comment by nixmaniack** [comment]
> How do you know they were stale?

I had killed all my terminals and started afresh.

**Comment by romkatv** [comment]
> > How do you know they were stale?
> 
> I had killed all my terminals and started afresh.

If you've killed terminals in a way that orphaned their shells, then it makes sense that gitstatusd kept on running. There should always be one gitstatusd process for every interactive zsh. If you close/kill zsh, gitstatusd will exit. But if zsh gets adopted by `init`, gitstatusd won't exit.

Anyway, it's unclear to me what to make of your report.
