### ISSUE TITLE
todo prompt show count after filter

### ISSUE THREAD

**Issue by LHY-iS-Learning** [romkatv/powerlevel10k#283]
todo.txt has the option to filter certain tasks before display to user, but the current p10k prompt is showing the task number before the filtering. 
![image](https://user-images.githubusercontent.com/21372855/67232247-f514a080-f40e-11e9-95c8-1b9055a5e66f.png)
I believe it is reasonable to show the count after the filter(1 in this case).
It would be an easy fix to change _p9k_cache_val[2] to p9k_cache_val[1].
`  _p9k_prompt_segment "$0" "grey50" "$_p9k_color1" 'TODO_ICON' 0 '' "${_p9k_cache_val[1]}"
`
If you believe its not necessary, is there anyway we can modify the .p10k.conf file to achieve this effect?
Thanks!

**Comment by romkatv** [comment]
`$p9k_cache_val[1]` is always equal to 1.

> todo.txt has the option to filter certain tasks before display to user

How can I set it up? Could you point me at the documentation for this filtering?

**Comment by LHY-iS-Learning** [comment]
Ops, I thought 1 means the the first number....
[https://github.com/todotxt/todo.txt-cli/blob/d589fd0570e2e473906bd96d882e91bce65fd1a3/todo.cfg#L80](url)
According to the config file, it has TODOTXT_FINAL_FILTER can be any command to post-process the result from todo.sh.
I'm using the filter to display only today's tasks and ignore future tasks.

**Comment by LHY-iS-Learning** [comment]
`	if [[ $count == (#b)'TODO: '([[:digit:]]##)' of '[[:digit:]]##' '* ]]; then
`
This should achieve the goal.

**Comment by romkatv** [comment]
Done. See the commit message in https://github.com/romkatv/powerlevel10k/commit/cf01e98ef086fc6fe2aa373d4e9609f55a8ed72a.
