### ISSUE TITLE
Meslo NF icon size

### ISSUE THREAD

**Issue by gigglearrows** [romkatv/powerlevel10k#284]
I noticed that after installing the nerdfonts fonts the icons are a lot smaller than the text. Is it supposed to be like this, or is it just a bug?

![](https://i.imgur.com/kuS8lmm.png)

As you can see, the folder icon, os icon and checkmark icons are really small compared to the regular text, and also small compared to icons in other fonts.

**Comment by romkatv** [comment]
Yes, this is expected. It's a feature. This font is made for productivity rather than decoration.

**Comment by gerryhernandez** [comment]
Are there any alternative fonts that work nicely but have larger icons? I understand this font is aimed at productivity and not decoration, but icon legibility can go a long way in reducing fatigue.

**Comment by romkatv** [comment]
> Are there any alternative fonts that work nicely but have larger icons?

[Nerd Fonts](https://github.com/ryanoasis/nerd-fonts) has the best collection of programmer's fonts. There are many variants for each font. Nerd Fonts uses the keyword "Monospace" to mean "normal size icons". Fonts without "Monospace" in their name have oversized icons that overlap the next character to the right. These are the ones you want.

For example, here's Meslo with oversized icons: [Meslo LG S Regular Nerd Font Complete.ttf](https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Meslo/S/Regular/complete/Meslo%20LG%20S%20Regular%20Nerd%20Font%20Complete.ttf). Download this file, double-click on it and press "Install", then set "MesloLGS Nerd Font" as your terminal font. Don't forget to run `p10k configure` afterwards. You'll notice that the answer to the question \#4 (*Do all these icons fit between the crosses?*) is now in the negative.

> I understand this font is aimed at productivity and not decoration, but icon legibility can go a long way in reducing fatigue.

Tip: When `p10k configure` asks whether you want few or many icons, answer "few". The extra icons from "many" are purely decorative. All informative icons will be displayed either way. This will go a long way towards reducing eye strain.

**Comment by gerryhernandez** [comment]
Perfect explanation and thanks a ton for the help! Exactly what I needed. :)
