### ISSUE TITLE
prompt_char stops updating after re-sourcing zshrc

### ISSUE THREAD

**Issue by jelinekto** [romkatv/powerlevel10k#285]
It gets stuck with `VIINS_CONTENT_EXPANSION`.

[~/.zshrc](https://github.com/jelinekto/gitconfigs/blob/master/%2Claptoop%2Cdesktoop%2C/home%2Cjeli%2C.zshrc)

[~/.p10k.zsh](https://github.com/jelinekto/gitconfigs/blob/master/%2Claptoop%2Cdesktoop%2C/home%2Cjeli%2C.p10k.zsh)

**Comment by romkatv** [comment]
This part from your `zshrc` breaks it:

```zsh
# Change cursor shape based on vi mode
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins
    echo -ne "\e[5 q"
}
zle -N zle-line-init
```

If you want to source `zshrc` multiple times, you have to write it very carefully. Even if you do, things will often break. It's much better to use `exec zsh` instead.

**Comment by jelinekto** [comment]
Now I feel dumb, it didn't even occur to me I could use `source` like this... Thanks for the tip!

**Comment by romkatv** [comment]
When using `exec zsh` as a means for reloading zsh without creating a new process, watch out for things of this sort:

```zsh
PATH+=$HOME/bin
```

With every `exec zsh` your `PATH` will get longer. Not a big deal but can be surprising.

You only need to think about reentrancy when changing exported environment variables. There aren't many, so it's not that much work. And it's easy to verify that everything is fine. Simply type `env`, then `exec zsh` and another `env`. Verify that the output of `env` is identical.
