### ISSUE TITLE
_p9k_precmd_impl:96: nice(5) failed: operation not permitted

### ISSUE THREAD

**Issue by hallux4** [romkatv/powerlevel10k#287]
Hello,

I use :
Windows Subsystem for Linux.
Windows Ubuntu Terminal
OhMyZSH
tmux

Since I changed my ZSH Theme for the powerlevel10k, I sometimes get this error message.
``` bash
_p9k_precmd_impl:96: nice(5) failed: operation not permitted
```

My .zshrc already have this line but it doesn't help.
``` bash
unsetopt BG_NICE
```

Does someone have an idea to solve this ?
A way to hide the message or disable a feature maybe ?

**Comment by hallux4** [comment]
![git-issue](https://user-images.githubusercontent.com/4824472/67492759-81da8b00-f6a9-11e9-9a1e-334d715cd818.PNG)

I think it should be up to date.

**Comment by romkatv** [comment]
I can see that `git pull` actually pulled stuff, so you weren't on the latest version.

I don't know what `rl` does but is it possible that it doesn't restart `zsh`? Can you try `exec zsh` and see if it fixes your error?

**Comment by hallux4** [comment]
It's strange I cloned the repository 2 days ago.
2019-10-22 13:37  git clone https://github.com/romkatv/powerlevel10k.git powerlevel10k

The ```rl``` just source the config files.
I restarted the process using the Windows service "LxssManager".

I seems that after the updating and the restart the problems is gone.
Thanks for your help ;)

**Comment by romkatv** [comment]
> It's strange I cloned the repository 2 days ago.

I've fixed it yesterday.

> The `rl` just source the config files.

Reloading config files yields unpredictable results. Things can break in very strange ways. It's almost never equivalent to restarting zsh. With most zsh configs, if you simply source them for a second time without any changes, you'll have a different state than what you had. It'll be worse than before. Often slower, often using more ram, sometimes subtly broken.

If you want to restart zsh without creating a new process, use `exec zsh`. It can also break things, but the things it'll break are much fewer and they are a subset of what gets broken when you source your config for the second time.

**Comment by hallux4** [comment]
Thanks you for all the tips and your quick answers ;)

**Comment by romkatv** [comment]
You are most welcome.
