### ISSUE TITLE
directory not being shown correctl

### ISSUE THREAD

**Issue by docwhat** [romkatv/powerlevel10k#29]
Using [these p9k settings](https://github.com/docwhat/dotfiles/blob/7edfee5ef57732d42f0577430f25513c76f61c4f/zsh/plugins/prompt.pre) I get a case where when entering git directories the directory part of the prompt stops updating and the git info doesn't show up.

<img width="434" alt="Screen Shot 2019-03-16 at 11 49 09 PM" src="https://user-images.githubusercontent.com/40799/54484935-2825fe80-4846-11e9-8206-a6fd884138fd.png">

**Comment by romkatv** [comment]
Thank you for the high quality bug report. I just fixed this regression -- an embarrassing typo that I made a couple days ago on a code-path I don't test. Please let me know if this (or anything else) still doesn't work for you.
