### ISSUE TITLE
Modifying the theme (Antibody)

### ISSUE THREAD

**Issue by ChiDal** [romkatv/powerlevel10k#292]
I have modified ```~/.cache/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-romkatv-SLASH-powerlevel10k/config/p10k-lean.zsh``` to change the default prompt symbol (at line 190).
The change is not reflected in my prompt after reloading the bundle (statically).
How do I go about modifying the theme?

**Comment by romkatv** [comment]
From https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration:

> On the first run Powerlevel10k configuration wizard will ask you a few questions and configure
> your prompt. If it doesn't trigger automatically, type `p10k configure`. You can further customize
> your prompt by editing `~/.p10k.zsh`.

Does this answer your question?

**Comment by ChiDal** [comment]
Yes. Sorry
