### ISSUE TITLE
terminal not showing all icon properly

### ISSUE THREAD

**Issue by C2FO-Ruchin** [romkatv/powerlevel10k#293]
![image](https://user-images.githubusercontent.com/56113982/67641301-71374880-f927-11e9-8f67-30d9a26c3d79.png)

Please suggest.

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k/blob/master/README.md

**Comment by romkatv** [comment]
Meant to link to this question in the FAQ: https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-my-icons-andor-powerline-symbols-look-bad

**Comment by romkatv** [comment]
If you are on macOS using iTerm2, `p10k configure` can install the font for you automatically.

**Comment by C2FO-Ruchin** [comment]
Already tried. You can see all icon appears in get_icon_names
![image](https://user-images.githubusercontent.com/56113982/67641591-fa9b4a80-f928-11e9-948a-123b472e85f4.png)

**Comment by romkatv** [comment]
I can see that this is not the recommended font. First, it looks different. Second, the output of `get_icon_names` shows that some glyphs are missing.

If you want to keep your own font, you can do that too. Just run `p10k configure` to have configuration settings that align with the capabilities of your font. Naturally, you won't be able to use some styles that require symbols you are missing. If you want to get access to all styles, install the recommended font. If you are using macOS and iTerm2, `p10k configure` can install it for you. You just need to say "Yes" when asked. Also don't forget to click `iTerm2 → Quit iTerm2` or press `⌘ Q` after installing the recommended font.

**Comment by C2FO-Ruchin** [comment]
It is working fine now. You are awesome. Thanks

**Comment by romkatv** [comment]
> It is working fine now. You are awesome. Thanks

👍
