### ISSUE TITLE
Add timewarrior segment

### ISSUE THREAD

**Issue by real-or-random** [romkatv/powerlevel10k#295]
timewarrior is a cli time tracker, see https://timewarrior.net/

I created this simple user-defined segment:
https://gist.github.com/real-or-random/6c789a436ec6ef391a48c910b1d6f147

It shows the current tracking status, i.e., it shows the tags such as "work", "gaming", etc. If there's interest to create a full segment, I'd be willing to help. I think showing the active tags is useful and what most timewarrior users would need. Possible extensions are options to display the current interval length for example.

**Comment by romkatv** [comment]
Thanks for opening the issue. I like this. Taskwarrior segment could be quite useful.

Is your implementation fast? Could you run the following command and post its output?

```zsh
time (repeat 100 timew 2>/dev/null | read -r)
```

**Comment by real-or-random** [comment]
I don't notice any delay, and I tried to make sure it's only a single invocation of timewarrior (and read is a builtin). But no idea what counts as fast.

`( repeat 100; do; timew 2> /dev/null | read -r; done; )  0,60s user 0,54s system 100% cpu 1,141 total`

**Comment by romkatv** [comment]
Thanks. That's 11.4ms per call. Over 10x slower than the upper bound of acceptable latency for a prompt segment. Powerlevel10k promises to be instantly fast with any prompt configuration, but with just 3 segments as slow as this prompt lag will be noticeable.

I'll need to find a way to make it faster before timewarrior prompt segment can be included in powerlevel10k.

**Comment by real-or-random** [comment]
Makes sense. I've just noticed it's even much much slower when time tracking is active... :/
`( repeat 100; do; timew 2> /dev/null | read -r; done; )  3,65s user 0,25s system 98% cpu 3,949 total`

A more direct way is to
1. Get current month and year.
2. Open ~/.timewarrior/data/YYYY-MM.data
3. Look at the last line. 
 - If it's of the form `inc 20191029T072518Z - 20191029T102007Z # tag1 tag2`, then time tracking is not active.
 - If it's of the form `inc 20191029T111149Z # tag1 tag2`, then tracking is active with the listed tags.

**Comment by romkatv** [comment]
> Makes sense. I've just noticed it's even much much slower when time tracking is active... :/
> `( repeat 100; do; timew 2> /dev/null | read -r; done; ) 3,65s user 0,25s system 98% cpu 3,949 total`

40ms should be noticeable with the naked eye. Try going to your home directory and hitting ENTER a few times. Then type `POWERLEVEL9K_TIMEWARRIOR_DISABLED=true` and again hit ENTER a few times. You'll likely feel the difference.

> A more direct way is to
> 
> 1. Get current month and year.
> 2. Open ~/.timewarrior/data/YYYY-MM.data
> 3. Look at the last line.
> 
> * If it's of the form `inc 20191029T072518Z - 20191029T102007Z # tag1 tag2`, then time tracking is not active.
> * If it's of the form `inc 20191029T111149Z # tag1 tag2`, then tracking is active with the listed tags.

This is closer to how p10k implements most segments.

**Comment by real-or-random** [comment]
> 40ms should be noticeable with the naked eye. Try going to your home directory and hitting ENTER a few times. Then type `POWERLEVEL9K_TIMEWARRIOR_DISABLED=true` and again hit ENTER a few times. You'll likely feel the difference.

Yep certainly. My comment about no noticeable delay was unfortunately only true without active tracking...

**Comment by romkatv** [comment]
It's certainly possible to implement this segment efficiently, and likely not too difficult. It just requires time. I cannot promise to get to it soon.

In the meantime you can use your own implementation if its latency isn't too high for the benefit it provides. Here's a cleaned-up version with a few minor issues fixed.

```zsh
function prompt_timewarrior() {
  emulate -L zsh
  setopt pipefail
  (( $+commands[timew] ))          || return
  local line IFS
  timew 2>/dev/null | read -r line || return
  local tags=${line#Tracking }
  [[ -n $tags && $tags != $line ]] || return
  p10k segment -f 208 -i $'\uFA1A' -t $tags
}
```

**Comment by romkatv** [comment]
I've added `timewarrior` prompt segment. Please update powerlevel10k and give it a try. If you've defined your own `prompt_timewarrior` function, don't forget to remove it.

**Comment by real-or-random** [comment]
Thanks! Works like a charm so far.

One thing: I'm not 100% convinced about the choice of the shield icon:
 - The shield has nothing to do with time tracking. I think most people associate a shield with security (sandbox, firewalls etc.)
 - Timewarrior itself uses a helmet, so the shield is not really associated with timewarrior either. So then there's just the "warrior" thing, but then *task*warrior is the more popular project.

I think nf-mdi-chart_timeline, nf-mdi-timelapse or nf-mdi-timetable would fit better. Not sure if we can't even use them here.

**Comment by romkatv** [comment]
I chose the shield based on the following logic. The project's name is timewarrior, and there is a related project called taskwarrior that (some? most?) users use together with timewarrior. The logo of timewarrior is a helmet. There is no helmet, so I looked for substitutes. One is a sword. I didn't chose it because it looks bad in monospace fonts and also because sword is offensive while helmet is defensive. The next is shield. Looks great and has the same purpose as helmet.

Shield looks spectacularly good in all fonts I've tried. It's both its strength (it's easy to distinguish this icon) and weakness (it's easy to see that it's a shield, so you might ask why there is a shield next to timewarrior when the correct logo is a helmet). The first time a segment using a new item pops up, recognition is important. However, the longer you use your prompt, the more important it becomes to distinguish between different items. You simply remember that shield is timewarrior. This association becomes automatic.

I spent perhaps 2 minutes on this and I'm not attached to this icon choice. I can totally change the icon if there is a good alternative. nf-mdi-timelapse and nf-mdi-timetable won't work because they are wide (2 columns). Lots of p10k users are on terminals that cannot display wide characters. nf-mdi-chart_timeline is technically viable but it looks awful in monospace fonts. There is virtually no chance anyone will recognize what it shows.

Glancing over icons that have "task" or "time" in their names, there is nf-oct-tasklist and nf-weather-time_4. Both are worse than shield in their visual appeal and clarity but they aren't terrible.

**Comment by romkatv** [comment]
> Glancing over icons that have "task" or "time" in their names, there is nf-oct-tasklist and nf-weather-time_4. Both are worse than shield in their visual appeal and clarity but they aren't terrible.

If you strongly prefer one of these alternatives, I can change the default. Sword is also viable if you think it's better than shield.

Also just to be clear (you probably already know this): You can change the icon by editing `~/.p10k.zsh`. Search for this:

```zsh
# Custom icon.
# typeset -g POWERLEVEL9K_TIMEWARRIOR_VISUAL_IDENTIFIER_EXPANSION='⭐'
```

Uncomment and set value to the icon you of your choice.

**Comment by real-or-random** [comment]
I think some icon representing time is better than the shield. And I agree with your comments. I had not tested the icons in a real terminal in monospace. Icons that look reasonable on my machine are 
 -  nf-mdi-timer: I originally used this one. I think it's my favorite because the stopwatch really representing time tracking. It's more distinguishable than nf-weather-time_4, because the 9-variant is already used for wall-clock time.
 - nf-oct-watch: that one looks nice actually and it's clearly distinguishable from other symbols. My only concern is that this is then the wrong way around because I associate the wristband watch more with "wall-clock time" then the simple clock. But this icon is still a nice choice. (Moreover, it's in the "oct" space, which maybe better? I don't know about the tradeoffs here, but this one works in my non-terminal emacs whereas the "mdi" icons don't...)
 - nf-mdi-timer_sand: here the issue is that the sand timer is already used for execution time. But still it looks nice.

If we don't like any of these, then I still think that the sword is better than the shield (simply because the shield is really associated with security usually.)

**Comment by romkatv** [comment]
> * nf-mdi-timer: I originally used this one. I think it's my favorite because the stopwatch really representing time tracking. It's more distinguishable than nf-weather-time_4, because the 9-variant is already used for wall-clock time.

Wide unicode character. No go.

> * nf-mdi-timer_sand: here the issue is that the sand timer is already used for execution time. But still it looks nice.

Yep, I've skipped over all sand timer icons for the same reason.

> * nf-oct-watch: that one looks nice actually and it's clearly distinguishable from other symbols. My only concern is that this is then the wrong way around because I associate the wristband watch more with "wall-clock time" then the simple clock. But this icon is still a nice choice. (Moreover, it's in the "oct" space, which maybe better? I don't know about the tradeoffs here, but this one works in my non-terminal emacs whereas the "mdi" icons don't...)

This looks good! I've replaced shield with this icon.

Thanks for the thorough feedback and suggestions!

**Comment by real-or-random** [comment]
Great. :) Thanks for the work again!
