### ISSUE TITLE
Feature Request: retain POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS after configure

### ISSUE THREAD

**Issue by nedludd** [romkatv/powerlevel10k#296]
Whenever I run `p10k configure` I have to go in and re-edit `p10k.zsh` to comment or uncomment my settings in POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS.

It would be nice if these were retained after the configure.

**Comment by romkatv** [comment]
When you run `p10k configure` with a newer version of Powerlevel10k, the config can be completely different. There is no way to automatically transfer your edits, neither for a human, nor for a machine.

Note that you don't need to run `p10k configure` whenever you upgrade Powerlevel10k. If you are satisfied with your prompt, you can keep using your config forever. It'll work the same way even when you update Powerlevel10k.
