### ISSUE TITLE
Git Prompt Extension - Doesn't Update, Doesn't Go Away After Leaving Repository

### ISSUE THREAD

**Issue by bgenchel** [romkatv/powerlevel10k#297]
Running Mavericks on a 2019 MacBook Pro

.p10k.zsh top lines:
```
# Generated by Powerlevel10k configuration wizard on 2019-10-14 at 16:50 EDT.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 20131.
# Wizard options: nerdfont-complete + powerline, small icons, rainbow,
# slanted separators, sharp heads, flat tails, 1 line, sparse, many icons, concise.
# Type `p10k configure` to generate another config.
```

I am working on a repo that is not managed by github.

As it says in the title, i've noticed that the git line sometimes does not update after making changes in a repo, and also, sometimes stays on the prompt even after leaving the repo that caused its appearance.

Unfortunately, I can't include images because I don't want to show any details of the company I work for via my prompt or git changes.

**Comment by romkatv** [comment]
> Running Mavericks on a 2019 MacBook Pro

Wow. Didn't know it was possible.

Do you get an error saying "gitstatus failed to initialize" every time you start zsh? I think the oldest macOS version supported by gitstatusd is Sierra. Mavericks is 4 releases older.

> I am working on a repo that is not managed by github.

This shouldn't matter. There is nothing github-specified in powerlevel10k.

> Unfortunately, I can't include images because I don't want to show any details of the company I work for via my prompt or git changes.

Do you mean that this problem reproduces only on Git repositories owned by your employer?

**Comment by romkatv** [comment]
Closing as there is not enough information to do anything and the reporter is MIA.
