### ISSUE TITLE
The option os_icon does not work with POWERLEVEL9K_HOME_ICON

### ISSUE THREAD

**Issue by gusbemacbe** [romkatv/powerlevel10k#299]
Hello,

My customised theme is based on [pot-code/matrix-zsh-theme](https://github.com/pot-code/matrix-zsh-theme). 

I replaced the ⌘ symbol for the OS symbol detected by the zsh. I tried:

```
typeset -g POWERLEVEL9K_HOME_ICON=$(POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon))
typeset -g POWERLEVEL9K_HOME_ICON=(os_icon)
```

**Comment by romkatv** [comment]
> My customised theme is based on [pot-code/matrix-zsh-theme](https://github.com/pot-code/matrix-zsh-theme).

If you are using that theme, why did you open an issue against Powerlevel10k?

> I replaced the ⌘ symbol for the OS symbol detected by the zsh.

I don't understand this. Could you describe what you or zsh did in greater detail?

> I tried:
> 
> ```
> typeset -g POWERLEVEL9K_HOME_ICON=$(POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon))
> typeset -g POWERLEVEL9K_HOME_ICON=(os_icon)
> ```

What are you trying to achieve?

Have you tried running `p10k configure`? It often solves issue with configuration options.

**Comment by gusbemacbe** [comment]
> If you are using that theme, why did you open an issue against Powerlevel10k?

Did you not say any P9k theme work with the P10k? I am really confused. 

> I don't understand this. Could you describe what you or zsh did in greater detail?
> What are you trying to achieve?

The original is `POWERLEVEL9K_HOME_ICON="\ufb32"`. The `\ufb32` is the command key symbol. I replaced it for the option `os_icon`, which is the icon of native OS. 

> Have you tried running `p10k configure`? It often solves issue with configuration options.

Can I run run the `p10k configure p19k-matrix.zsh`?

**Comment by romkatv** [comment]
> > If you are using that theme, why did you open an issue against Powerlevel10k?
> 
> Did you not say any P9k theme work with the P10k? I am really confused.

It does. If I understand correctly, the config you choose works correctly but you are having difficulties modifying it. The author of that config is in a better position to help you with that.

> > I don't understand this. Could you describe what you or zsh did in greater detail?
> > What are you trying to achieve?
> 
> The original is `POWERLEVEL9K_HOME_ICON="\ufb32"`. The `\ufb32` is the command key symbol. I replaced it for the option `os_icon`, which is the icon of native OS.

You can replace `\ufb32` with any other text of your choIce.

> > Have you tried running `p10k configure`? It often solves issue with configuration options.
> 
> Can I run run the `p10k configure p19k-matrix.zsh`?

No.

**Comment by gusbemacbe** [comment]
> It does. If I understand correctly, the config you choose works correctly but you are having difficulties modifying it. The author of that config is in a better position to help you with that.

I am not sure if he can speak English.

> You can replace \ufb32 with any other text of your choIce.

My zshrc file is universal, imagine using an Arch icon on macOS. It is why I want to use `os_icon`, which detects the OS name, like `neofetch`, I am not sure if it is compatible with the `POWERLEVEL9K_HOME_ICON`.

**Comment by romkatv** [comment]
Add the following code snippet to your `~/.zshrc` after sourcing [matrix-zsh-theme](https://github.com/pot-code/matrix-zsh-theme/blob/1213a24ebf6a4072c9c51f16f08a1c7c3d60ca51/zshrc) to display `os_icon` in place of `HOME_ICON`:

```zsh
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[(I)dir]]=(
  os_icon dir_joined)

POWERLEVEL9K_OS_ICON_BACKGROUND=23
POWERLEVEL9K_OS_ICON_FOREGROUND=10
POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='${${(M)${(%):-%/}:#~}:+${P9K_CONTENT// }}'
POWERLEVEL9K_HOME_ICON=
```

P.S.

I don't endorse the use of that config. It gives you prompt of incomparably lower quality than what you get by running `p10k configure`. It's many times slower and barely functional.
