### ISSUE TITLE
why do I need ! (exclamation mark) after >> ?

### ISSUE THREAD

**Issue by t29mato** [romkatv/powerlevel10k#301]
Hi, I'm a newbie.
I've got a question.

`echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>! ~/.zshrc`
why do I need `!` (exclamation mark) after `>>` ?

**Comment by romkatv** [comment]
If you have `no_clobber` option set and the target file doesn't exist, `>>` will fail while `>>!` will succeed. In all other cases there is no difference.

P.S.

This isn't the right place to ask basic questions about zsh syntax. "What's the difference between `>>!` and `>>`" is a question suited for /r/zsh, stackoverflow or zsh-users mailing list.

**Comment by t29mato** [comment]
@romkatv 
I understood what you mean.

Actually, this is first time to create ticket in OSS projects for me.
From next time I will more consider which place is right to create issue.

Thank you so much!!
