### ISSUE TITLE
On Arch os_icon is cut off but no other icon is

### ISSUE THREAD

**Issue by mthw0** [romkatv/powerlevel10k#302]
As you can see, only the first half of the logo is shown, but the folder icon (also double-width glyph ) is shown correctly. Listing icons with `get_icon_names` works correctly. `echo $'\uf303'` also works.
I am using Konsole 19.08.2 and Hack Nerd Font (or any other Nerd font no-monospace). What other info should I post? 
![Screenshot_20191102_193852](https://user-images.githubusercontent.com/31957530/68075503-c1d7f700-fda8-11e9-83bb-78f66c0eb6d3.png)

**Comment by romkatv** [comment]
It's a bug in Konsole. Try this:

```zsh
echo $'%B\uf303%b '
```

You can:

- Fix the bug in Konsole.
- Switch to another terminal emulator.
- Change your font to monospace.
- Open `~/.p10k.zsh`, search for `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` and replace that line with these two:
```zsh
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='%B${P9K_CONTENT// } '
typeset -g POWERLEVEL9K_OS_ICON_LEFT_RIGHT_WHITESPACE=''
```
