### ISSUE TITLE
some characters look off in git branches. 

### ISSUE THREAD

**Issue by squarewave24** [romkatv/powerlevel10k#304]
i've setup powerline fonts with powerline10k theme. 

i seem these chars on dirty git branches: 

```
~/dev/my_folder  my_branch_name ⇡23 *1 
```

not sure if this is an issue with config, wrong font version, wrong theme or something else. 

`.zshrc`:
```
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="awesome-patched"
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

i tried a few powerline fonts.. including MesloGS NF, and SourcePro for PowerLine but no luck 

![image](https://user-images.githubusercontent.com/843437/68088489-cb577280-fe2d-11e9-9a4d-ac8f8b373c27.png)

![image](https://user-images.githubusercontent.com/843437/68088527-1a050c80-fe2e-11e9-82ff-9e9c0423636e.png)

**Comment by romkatv** [comment]
> i seem these chars on dirty git branches:

There is not much point in copy-pasting private use area glyphs. I cannot know what they look like without having your font installed. Screenshots work much better. Could you explain what you find problematic in it?

From the screenshot it looks like your terminal is monochrome. Is this intentional? Is this the was you want it?

**Comment by squarewave24** [comment]
there was a screenshot in original post. 

here's another one 

![image](https://user-images.githubusercontent.com/843437/68091138-ffd92780-fe49-11e9-982c-5c06aee1efd5.png)

**Comment by romkatv** [comment]
I was it. My question still stands.

**Comment by squarewave24** [comment]
ah sorry i responded to fast :) 

i was using iterm2 with default install, not entirely sure what monochrome means in that context. is that a setting? or are you saying iterm2 is not supported by this theme

**Comment by romkatv** [comment]
> i was using iterm2 with default install, not entirely sure what monochrome means in that context. is that a setting?

Your screenshots sport just two colors. Terminals (or terminal color schemes) with two colors are referred to as monochrome. A small minority of users prefer them but it's definitely not the default. I was merely wondering if your terminal is broken or if you intentionally made it monochrome.

Here's how Powerlevel10k prompt looks like if you don't force it to be monochrome:

![p10k](https://raw.githubusercontent.com/romkatv/powerlevel10k/master/powerlevel10k.png)

If you aren't sure what I'm talking about, try typing `export TERM=xterm-256color`.

> or are you saying iterm2 is not supported by this theme

It is supported.

Would you mind elaborating on the content of your problem? You've posted a couple of screenshot but haven't told me what you find unusual about them. Apparently it's not the unusual choice of colors. What is it then?

**Comment by squarewave24** [comment]
when i configured the theme i opted for no background colors, but there are still more than 2 

![image](https://user-images.githubusercontent.com/843437/68093661-e940c980-fe65-11e9-9375-0f9ce0c15842.png)

i think my problem is that some icons are still missing which is why i get those "funny" chars instead

**Comment by romkatv** [comment]
> when i configured the theme i opted for darker background colors, but there are still more than 2
> 
> ![image](https://user-images.githubusercontent.com/843437/68093661-e940c980-fe65-11e9-9375-0f9ce0c15842.png)

This looks as expected. I see that the second screenshot you've posted also looks as expected. Only the first screenshot appears to be taken from a broken terminal (unless you've intentionally made it monochrome).

> i think my problem is that some icons are still missing

No icons are missing on your screenshot. Apart from ASCII (`api`, `email`, `23`, `*1` and spaces) your screenshot also has `⇡` and two powerline glyphs (U+E0B1 and U+E0B0). All look as expected.

> which is why i get those "funny" chars instead

If you can tell me which characters you find funny, I'll tell you how to change them.

**Comment by squarewave24** [comment]
> > when i configured the theme i opted for darker background colors, but there are still more than 2
> > ![image](https://user-images.githubusercontent.com/843437/68093661-e940c980-fe65-11e9-9375-0f9ce0c15842.png)
> 
> This looks as expected. I see that the second screenshot you've posted also looks as expected. Only the first screenshot appears to be taken from a broken terminal (unless you've intentionally made it monochrome).
> 
> > i think my problem is that some icons are still missing
> 
> No icons are missing on your screenshot. Apart from ASCII (`api`, `email`, `23`, `*1` and spaces) your screenshot also has `⇡` and two powerline glyphs (U+E0B1 and U+E0B0). All look as expected.
> 
> > which is why i get those "funny" chars instead
> 
> If you can tell me which characters you find funny, I'll tell you how to change them.

thanks! glad it's working as expected. just curious where the `^23` and `*1` comes from so i can look up their meaning. is that part of zsh or part of the theme?

**Comment by romkatv** [comment]
> thanks! glad it's working as expected. just curious where the `^23` and `*1` comes from so i can look up their meaning.

`⇡23` means your branch is 23 commits ahead of the tracking remote. If you type `git push`, all these commits will be sent to the remote. `git status` will tell you the same thing.

`*1` means you have 1 stash. Type `git stash list` to see your stashes.

> is that part of zsh or part of the theme?

That thing you've screenshotted is called *prompt*. Zsh code that controls your prompt is usually called a *theme*. Powerlevel10k is a theme, so it controls your prompt. Everything in your prompt comes from  Powerlevel10k.

You can open `~/.p10k.zsh` and search for `my_git_formatter` to see how Git segment is constructed. You can also edit it if you want to omit some parts or change glyphs or colors.
