### ISSUE TITLE
Slanted theme's head and tail are not aligned with the horizontal bar in iTerm2

### ISSUE THREAD

**Issue by singularitti** [romkatv/powerlevel10k#307]
I do not know if it is clear to observe:
![iterm2](https://user-images.githubusercontent.com/25192197/68173730-e28b8280-ff49-11e9-9038-afc4b0526d88.png)
As you can see, the head and tail of the slanted bar are not aligned with the horizontal bar. The head is a bit lower and so is the tail. The `/` separator is a bit lower, too (not so obvious).

However, it looks fine on my VSCode integrated terminal.
![vscode](https://user-images.githubusercontent.com/25192197/68174334-b8d35b00-ff4b-11e9-930c-dd45cf0c7c8f.png)

```
> system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.15.1 (19B88)
      Kernel Version: Darwin 19.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: 
      User Name: 
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 
```

```
> zsh --version                                                                                                                         ─╯
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

[Here](https://pastebin.com/kKnf2pfh) is my `.p10k.zsh`. I am using `iTerm2.app` (build `3.3.6`) on macOS `10.15.1`. I am using the recommended font [MesloLGS NF Regular.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf) at size `12`. I will provide more information if this is not enough.

Besides, I am curious about how to make it look like the last one in the [headline figure](https://raw.githubusercontent.com/romkatv/powerlevel10k/master/powerlevel10k.png).

**Comment by romkatv** [comment]
> If you increase font size in iTerm2 to 40 (for example), you'll perfect alignment. Scaling is hard.

A quick experiment shows that 12 is the unlucky number. Rendering looks perfect with font sizes 11 and 13. FWIW, I'm using 13 as I find 12 a bit too small.

**Comment by singularitti** [comment]
Indeed, 11 and 13 both fix the problem.

**Comment by dejvizelo** [comment]
Sorry to revive such an old thread, but I'm facing the same problem with Alacritty. Changing the font size doesn't help. Has anything regarding this changed in the last 5 years?
