### ISSUE TITLE
Issue, new install, doesn't go to wizard config

### ISSUE THREAD

**Issue by nashokin** [romkatv/powerlevel10k#308]
Hi,

I get this error on my work laptop, I try to run it in WSL, running Ubuntu 18.04.
```
/home/nashokin/Dev/powerlevel10k/powerlevel10k.zsh-theme:12: command not found: ^M
/home/nashokin/Dev/powerlevel10k/powerlevel10k.zsh-theme:local:14: not valid in this context: __p9k_src_opts^M
```
I get no issues installing and running it on my home pc.

Any help how to resolve this will be much appreciated.

Thank you.

**Comment by romkatv** [comment]
You probably have `core.autocrlf=true` in the system-wide or user-wide git config. This will break many things for you so it's a good idea to fix it.

I've added local `.gitattributes` to powerlevel10k to ignore misguided user-defined settings. If you delete powerlevel10k directory and clone once it again, it'll work even if you don't fix your gitconfig.
