### ISSUE TITLE
[question] Some missing font ligatures

### ISSUE THREAD

**Issue by nashokin** [romkatv/powerlevel10k#309]
Hi, I have some missing font ligatures, please advice how to fix it, I haven't had those in powerlevel9k.

I'm using Ubuntu patched nerd-fonts [UbuntuMono](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/UbuntuMono/Regular), in cmder, which is an improved version of conemu.

Thank you for the advice, screen grabs below.

Missing ligature in the right red square:
![2019-11-06 15_14_55-cmd](https://user-images.githubusercontent.com/6571738/68268297-bedf4e00-00a9-11ea-8a46-706dfc3e7161.png)
Missing ligature (down arrow) before 21:
![2019-11-06 15_14_54-cmd](https://user-images.githubusercontent.com/6571738/68268298-bedf4e00-00a9-11ea-99d6-9e1f0c46f865.png)

**Comment by romkatv** [comment]
When `p10k configure` is asking which glyphs you can and cannot see, it's trying to infer which bucket your font falls into. It's infeasible to ask about every glyph, so the bucketing is necessarily coarse. The patched UbuntuMono is unusual in that it has a load of fancy symbols but is lacking the basic symbols that all modern fonts have, even without patching. When you tell `p10k configure` that you can see the diamond, lock and debian logo, it infers that your font can display pretty much anything. This conclusion would be true for virtually every font, but is false for the patched UbuntuMono.

You can do several things to fix this.

1. Use a different font. Saying that UbuntuMono is not very popular would be a massive understatement. If font popularity is even slightly correlated with quality, you'll likely be OK with a different font. Try [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k) or download any other monospaced font from Nerd Fonts.
2. Manually change symbols in your config that cannot be displayed. Open `~/.p10k.zsh`, search for `⇣` and `↵` and replace them them with something that UbuntuMono can display.
3. Use your old powerlevel9k config. Your prompt will look as before. If your old powerlevel9k config was empty (no `POWERLEVEL9K` parameters except maybe `POWERLEVEL9K_MODE`), define `POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true` to prevent configuration wizard from automatically launching every time you start zsh.
