### ISSUE TITLE
Please re-add trailing spaces after rprompt segments

### ISSUE THREAD

**Issue by ronasimi** [romkatv/powerlevel10k#31]
rprompt looks bad without trailing spaces after segments

**Comment by romkatv** [comment]
Thanks for the quick report. I see that my fix removed too many spaces. I've reverted the last commit for now; will figure out later how to get rid of the unwanted spaces without also removing the wanted ones.

**Comment by ronasimi** [comment]
That was quick :)

**Comment by romkatv** [comment]
:-D
