### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by jatin-cbs** [romkatv/powerlevel10k#310]
I am using fedora 31, I was only able to see diamond but lock and debian swirl were not as it should be any dependencies required ? If yes please mention in the documentation. :(

**Comment by romkatv** [comment]
> I was only able to see diamond but lock and debian swirl

This is fine. Powerlevel10k will still work.

> If yes please mention in the documentation. :(

From the [home page](https://github.com/romkatv/powerlevel10k/blob/master/README.md#fonts):

> The full choice of style options is available only when using [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts).

Followed by:

> ### Recommended: Meslo Nerd Font patched for Powerlevel10k
> 
> Download these four ttf files:
> - [MesloLGS NF Regular.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf)
> - [MesloLGS NF Bold.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold.ttf)
> - [MesloLGS NF Italic.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Italic.ttf)
> - [MesloLGS NF Bold Italic.ttf](https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Bold%20Italic.ttf)
> 
> Double-click on each file and press "Install". This will make `MesloLGS NF` font available to all applications on your system. Configure your terminal to use this font:
> 
> - **iTerm2**: Open *iTerm2 → Preferences → Profiles → Text* and set *Font* to `MesloLGS NF`.
> - **Hyper**: Open *Hyper → Edit → Preferences* and change the value of `fontFamily` under `module.exports.config` to `MesloLGS NF`.
> - **Visual Studio Code**: Open *File → Preferences → Settings*, enter `terminal.integrated.fontFamily` in the search box and set the value to `MesloLGS NF`.
> - **GNOME Terminal** (the default Ubuntu terminal): Open *Terminal → Preferences* and click on the selected profile under *Profiles*. Check *Custom font* under *Text Appearance* and select `MesloLGS NF Regular`.
> - **Konsole**: Open *Settings → Edit Current Profile → Appearance*, click *Select Font* and select `MesloLGS NF Regular`.
> - **Tilix**: Open *Tilix → Preferences* and click on the selected profile under *Profiles*. Check *Custom font* under *Text Appearance* and select `MesloLGS NF Regular`.
> - **Windows Console Host** (the old thing): Click the icon in the top left corner, then *Properties → Font* and set *Font* to `MesloLGS NF`.
> - **Windows Terminal** (the new thing): Open *Settings* (`Ctrl+,`), search for `fontFace` and set value to `MesloLGS NF` for every profile.
> - **Termux**: Type `p10k configure` and answer `Yes` when asked whether to install *Meslo Nerd Font*.
> 
> Run `p10k configure` to pick the best style for your new font.

**Comment by mokkenlab** [comment]
I have installed this fonts, but the icons still are not showing up. Linux Mint.

**Comment by mrm15** [comment]
i downloaded Fonts its Worked Thanks.
Mx linux

**Comment by pankajackson** [comment]
@romkatv Thanks, I was busy downloading fonts and config of zsh, oh-my-zsh and powerlevel10k. finally found the exact solution.
