### ISSUE TITLE
How do I ignore certain git repos?

### ISSUE THREAD

**Issue by AaronNBrock** [romkatv/powerlevel10k#311]
I use a git repo in my home directory to store my dotfiles, it'd be nice if powerline10k was able to ignore this repo, since it shows up whenever I'm _anywhere_ in my home directory.

**Comment by romkatv** [comment]
I added `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN`. Use it as follows:

```zsh
typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN=~
```

P.S.

Bare git repo gives you a better way to manage dotfiles. See https://www.atlassian.com/git/tutorials/dotfiles. If you adopt this solution, you won't need to define `POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN`. You'll also be able to overlay more than one Git repository over your home directory. I overlay two: [dotfiles-public](https://github.com/romkatv/dotfiles-public) for files I can share, and dotfiles-private for private stuff. The latter contains my shell history, for example.
