### ISSUE TITLE
How to change color theme. My OS is ubuntu.

### ISSUE THREAD

**Issue by kensang248** [romkatv/powerlevel10k#312]

**Comment by romkatv** [comment]
If you want to change the color scheme of your terminal, read the documentation for your terminal.

If you want to customize colors in powerlevel10k prompt, see [Configuration](https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration):

> On the first run Powerlevel10k configuration wizard will ask you a few questions and configure your prompt. If it doesn't trigger automatically, type `p10k configure`. You can further customize your prompt by editing `~/.p10k.zsh`.

**Comment by kensang248** [comment]
but i can't find out the way to change theme color my terminal when i run p10k configure . Help me, please.

**Comment by romkatv** [comment]
Read my reply again carefully. Don't skip any words or sentences. If this information isn't enough, there is nothing else I can do.

**Comment by kensang248** [comment]
> Read my reply again carefully. Don't skip any words or sentences. If this information isn't enough, there is nothing else I can do.

thank , i can change my self, thank for creating beautiful powerlevel 10k
