### ISSUE TITLE
Error when starting up zsh via wsl

### ISSUE THREAD

**Issue by devtechcorp** [romkatv/powerlevel10k#313]
Hello,

I ran into a strange bug today. When starting my wsl, it should log me into zsh. Unfortunately this text appears.
This is ubuntu 18.04 with zsh 5.7.1, I am using oh-my-zsh and a default p10k config.

``` sh
usage: gitstatus_start [OPTION]... NAME
is-at-least:24: bad math expression: operand expected at `<= 1 '
/home/<redacted username>/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh:34: unknown file attribute
(anon):13: unknown file attribute
```

When invoking zsh manually afterwards, everything works fine. I did not enable the faster shell startup

Do you need more information from my side?

 Thank you for this awesome theme btw. It is the only one that our corporate virus scanner is not killing completely.

Kind regards,

dev-tech

**Comment by romkatv** [comment]
What's the output of `echo $ZSH_VERSION` while in that shell?

**Comment by romkatv** [comment]
Timed out waiting for response. If this issue is still affecting you, please reopen and provide the information I've requested above.
