### ISSUE TITLE
Prompt is slow with some config

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#314]
Reported in https://www.reddit.com/r/zsh/comments/dsh1g3/new_powerlevel10k_feature_transient_prompt/f6qdl64/.

Please attach your config.

Is prompt slow when the current directory is `/`? If not, where is it slow and where is it fast?

**Comment by DesmondBaer** [comment]
My config:
https://gist.github.com/DesmondBaer/9a9621069a9a644904d840827a399cb8

It does not make a noticeable difference if I am in a git repo, my home directory or /.

**Comment by romkatv** [comment]
Thanks for posting your config.

It's fast for me. Prompt latency is 5.5ms -- indistinguishable from zero. It feels the same as my regular prompt.

![prompt](https://user-images.githubusercontent.com/1282067/68478827-2247b800-0231-11ea-9e58-d471f14551b5.gif)

It's possible that some prompt segment is slower for you than for me because of differences in our hardware and environment. For example, I'm testing on a Linux desktop without a battery, while you might be on a mac with a battery.

May I ask what machine you are using? And please post the output of the following command.

```zsh
() {
  emulate -L zsh
  uname -s
  uname -m
  echo $ZSH_VERSION
}
```

Could you try disabling prompt segments in `POWERLEVEL9K_{LEFT,RIGHT}_PROMPT_ELEMENTS` one by one until prompt gets fast? Which segment is the culprit of prompt lag?

Also just to clarify. Latency is high both with and without transient prompt, right?

P.S.

You have a typo: `POWERLEVEL9k_INSTANT_PROMPT_COMMAND_LINES`. It should be `9K` (upper-case K).

**Comment by romkatv** [comment]
Closing due to the lack of activity. If you are still affected by this issue, please provide answers to the questions I've posted above and reopen.
