### ISSUE TITLE
Console output during zsh initialization detected with minimal .zshrc

### ISSUE THREAD

**Issue by mjlbach** [romkatv/powerlevel10k#315]
After pulling master today, I noticed that I started seeing this error on my (previously fine) config. Even with a minimal example with the lean theme, I'm still seeing it.

``` zsh
 if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
 fi

source ~/.config/shell/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/shell/powerlevel10k/config/p10k-lean.zsh

(( ! ${+functions[p10k-instant-prompt-finalize]} )) || p10k-instant-prompt-finalize
```
Edit: I see we no longer have to have the tail end line, but I'm still getting the same issue after removing it

**Comment by romkatv** [comment]
What's the output?

**Comment by mjlbach** [comment]
Seems like a blank line... Only happens locally over gnome terminal?

```

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

~                                                                                            
❯ 

```

**Comment by romkatv** [comment]
I've added a few logging statements to powerlevel10k to figure out what's going on. Please do the following:

1. Install `hexdump` if you don't have it installed. It's in `bsdmainutils` debian package (in case you can install debian packages).
2. Add `POWERLEVEL9K_DEBUG_ISSUE_315=true` to `~/.zshrc`.
3. Update powerlevel10k: `git -C ~/.config/shell/powerlevel10k pull`.
4. Restart zsh.
5. The same error should appear because I haven't fixed anything. However, there should be more information at the end. Post it here.

**Comment by mjlbach** [comment]
I'm not seeing any additional output after following these steps. It's the same message as before

**Comment by romkatv** [comment]
Sorry, I forgot to mention that `POWERLEVEL9K_DEBUG_ISSUE_315` has to be defined at the bottom of `~/.zshrc` (`p10k-lean.zsh` unsets all `POWERLEVEL9K` parameters, so defining them before sourcing this file will have no effect.)

Please do the following:

1. Add `POWERLEVEL9K_DEBUG_ISSUE_315=true` *at the bottom* of `~/.zshrc`.
2. Restart zsh.
3. The same error should appear because I haven't fixed anything. However, there should be more information at the end. Post it here.

**Comment by mjlbach** [comment]
Ah got it

``` zsh

content=$'\C-[]7;file://localhost.localdomain/home/michael\C-[\\'
-rw-------. 1 michael michael 47 Nov 11 05:20 /tmp/p10k-instant-prompt-output-michael-47126
0000000 033   ]   7   ;   f   i   l   e   :   /   /   l   o   c   a   l
0000010   h   o   s   t   .   l   o   c   a   l   d   o   m   a   i   n
0000020   /   h   o   m   e   /   m   i   c   h   a   e   l 033   \    
000002f
```

**Comment by romkatv** [comment]
Thanks, that's very valuable info. Should be fixed now. Please update and try again.

**Comment by mjlbach** [comment]
Updated and it's fixed. Thank you!

**Comment by romkatv** [comment]
Wonderful! Thanks for the confirmation.

**Comment by Am86Shekari** [comment]
Hi
Please Look at my comment at here:
[https://github.com/romkatv/powerlevel10k/issues/472#issuecomment-792307244](url)

**Comment by romkatv** [comment]
> ```
> /home/shekari/.zshrc:4: command not found: -g
> /home/shekari/.zshrc:9: command not found: #
> ```

You need to fix errors on the indicated lines.

**Comment by KWONGTAKWAI** [comment]
type "typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet" to ~/.zshrc

**Comment by Am86Shekari** [comment]
> > ```
> > /home/shekari/.zshrc:4: command not found: -g
> > /home/shekari/.zshrc:9: command not found: #
> > ```
> 
> You need to fix errors on the indicated lines.

I do that and fix it thanks so much

**Comment by surprisedPikachu007** [comment]
This worked for me

set "typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet" in .p10k.zsh
