### ISSUE TITLE
Config file on Mac Catalina 10.15.1 ?

### ISSUE THREAD

**Issue by capnahab** [romkatv/powerlevel10k#317]
I am using Oh My Zsh , 5.7.1 , iTerm 3.3.6 , - I have the recommended fonts installed (MesloLGS NF). The config file fails to display as below. Consequently I have no p10k.zsh file created. 

![image](https://user-images.githubusercontent.com/11663529/68530669-c292ff00-034d-11ea-9f8d-be29ee204663.png)

If I use the mac terminal I get further and can get to the below, but can't save the config,

![image](https://user-images.githubusercontent.com/11663529/68530692-23223c00-034e-11ea-9217-0ca0ed0078a9.png)

**Comment by romkatv** [comment]
> I am using Oh My Zsh , 5.7.1 , iTerm 3.3.6 , - I have the recommended fonts installed (MesloLGS NF).

Both of your screenshots use fonts that aren't MesloLGS NF.

Please do the following.

1. Open iTerm.
2. Click *iTerm2 → Quit iTerm2* or press *⌘ Q*.
3. Open iTerm again.
4. Type `p10k configure`.
5. If the configuration wizard does *not* ask you whether to install *Meslo Nerd Font*, skip to (6).
5.1 Answer Yes and wait for the wizard to finish.
5.2 Click *iTerm2 → Quit iTerm2* or press *⌘ Q*.
5.3 Open iTerm again.
5.4 Type `p10k configure`.
6. Choose prompt of your choice.

> Consequently I have no p10k.zsh file created.

The configuration wizard will create a config regardless of you font. The only way to *not* create a config is to explicitly choose **(q)  Quit and do nothing.** Did you choose this?

P.S.

While you can use powerlevel10k with white background, it looks better with dark background. Try Tango or Solarized Dark.

**Comment by capnahab** [comment]
thanks, Fonts are installed. I didn't have the right iterm profile selected sorry but now I have. 

![image](https://user-images.githubusercontent.com/11663529/68536458-728c5a80-0396-11ea-916f-73b3b8cb1220.png)

The config isn't loading in the terminal correctly (- no questions) and even if I say yes to seeing the diamond etc I can't save the config. I only have options r or q , I have to do q as that's the only way I can exit the config. I have seen https://asciinema.org/a/259663 and I don't get any of that.

I wonder if mY fonts  are not installed properly for mac.


![image](https://user-images.githubusercontent.com/11663529/68536499-3efe0000-0397-11ea-868a-3e72b655c8dc.png)

**Comment by romkatv** [comment]
I can see that this time your terminal is using the correct font. This is good.

There is another problem now: bold text is rendered in white color, which makes it invisible on white background. This is why you cannot some of the text in the configuration wizard. It's still there but you cannot see it. You can reveal it by selecting a chunk of your screen with a mouse.

I can see from your screenshot that either you haven't installed MesloLGS NF through the configuration wizard, or you've manually tweaked font settings after following them. These manual tweaks are causing problems. For example, on the right side of your screenshot there is bad alignment of the two triangles which causes them to appear disconnected. Other manual tweaks are causing bold text to be displayed as white on white.

You need to uncheck *Use a different font for non-ASCII text*. This will fix bad alignment. If you haven't installed all 4 versions of MesloLGS NF, you need to install them and restart iTerm. If after that bold text is still invisible, you'll need to fix settings on the *iTerm2 → Preferences → Profiles → Colors* tab. It's possible that you have *Bold* checked there with its color being white. Either uncheck it or change the color. I highly recommend not tweaking colors manually on this tab. Instead, pick one of the values from *Color Presets...* dropdown menu at the bottom right. I'll repeat that powerlevel10k looks better on dark background. You can try it by choosing *Tango Dark* in *Color Presets...* in the dropdown.

You can test whether bold text is visible by printing some with the following command:

```zsh
print -P '%Bthis text is bold%b'
```

**Comment by capnahab** [comment]
you're a star, many thanks.  
![image](https://user-images.githubusercontent.com/11663529/68541858-12260900-03e8-11ea-85b3-e4db1a0b335d.png)

**Comment by romkatv** [comment]
Woot 🎉 😄
