### ISSUE TITLE
Icons not showing with nerdfont

### ISSUE THREAD

**Issue by Albatrous** [romkatv/powerlevel10k#319]
![Screenshot from 2019-11-10 19-39-24](https://user-images.githubusercontent.com/42671837/68544086-ddb74a80-03f1-11ea-8dba-b7c497652ad2.png)

I try to configure the p10k and use the **[nerdfont](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/complete/Hack%20Regular%20Nerd%20Font%20Complete.ttf)**, but still doesn't show any icons.

Here's my .zsrhc

```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="/home/albatrous/.oh-my-zsh"

POWERLEVEL9K_INSTALLATION_PATH="${HOME}/.antigen/bundles/powerlevel9k"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="▶ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MODE="nerdfont-complete"

source $ZSH/oh-my-zsh.sh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```
**EDIT:** Everything is fine, silly me~

**Comment by romkatv** [comment]
I'm glad you've solved this problem.

All those `POWERLEVEL9K` in your `~/.zshrc` don't do anything. It's a really good idea to remove them. If at some point they start doing something, your prompt will break.
