### ISSUE TITLE
prompt_powerlevel10k_setup  syntax error

### ISSUE THREAD

**Issue by black7375** [romkatv/powerlevel10k#32]
When execute `prompt_powerlevel10k_setup `

```
/romkatv/powerlevel10k/prompt_powerlevel10k_setup: line 25: conditional binary operator expected
/romkatv/powerlevel10k/prompt_powerlevel10k_setup: line 25: syntax error near `_P9K_SOURCED'
/romkatv/powerlevel10k/prompt_powerlevel10k_setup: line 25: `[[ -v _P9K_SOURCED ]] && return'
```

**Comment by romkatv** [comment]
What does `zsh --version` say? If it's below 5.2, you'll need to update zsh. See [the last item in the FAQ](https://github.com/romkatv/powerlevel10k#what-is-the-minimum-supported-zsh-version).

**Comment by black7375** [comment]
MY zsh version
`zsh 5.3 (x86_64-apple-darwin18.0)`

**Comment by romkatv** [comment]
Could you type the following and send me the results?

```zsh
X=1 zsh -df -c '[[ -v X ]] && echo OK'
```

**Comment by black7375** [comment]
Result:
`OK`

**Comment by romkatv** [comment]
You mean it works if you source `/romkatv/powerlevel10k/prompt_powerlevel9k_setup` (note that the directory is still powerlevel10k)?

**Comment by black7375** [comment]
ah.. I just checked, Nope.
have same problem.

It seems like a mistake with bhilburn/powerlevel9k

**Comment by romkatv** [comment]
To make sure I got it right. When you source `/romkatv/powerlevel10k/prompt_powerlevel9k_setup` you get an error, but when source the same file from powerlevel9k it works. Correct?

Are you executing `source /romkatv/powerlevel10k/prompt_powerlevel9k_setup` directly or is it done on your behalf by a plugin manager? If the latter, which plugin manager and how do you load powerlevel10k with it?

**Comment by black7375** [comment]
I use antigen.
```
antigen theme romkatv/powerlevel10k
```

**Comment by romkatv** [comment]
Does it work if you disable your current theme in antigen and source powerlevel10k directly? See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-use-powerlevel10k-with-zplug-prezto-oh-my-zsh-antigen-somethingelse.

**Comment by black7375** [comment]
There was nothing wrong with just running it.
But execute like this
https://github.com/black7375/BlaCk-Void-Zsh/blob/f841bd2010d3642440861e847a7c3cbef9b298b7/BlaCk-Void.zshrc#L302

I have a problem.

**Comment by romkatv** [comment]
Thanks for the info! I should now have everything necessary to reproduce this. I'll give it a shot a few hours later.

**Comment by romkatv** [comment]
Figured it out. That line where you call `prompt_powerlevel9k_setup` translates to `sh powerlevel10k/prompt_powerlevel9k_setup`. This file isn't a valid sh script, so you get errors.

I added `test -n "$ZSH_VERSION" || exit 1` at the top so that you won't get errors anymore. However, you need to remove `prompt_powerlevel9k_setup` from your code. It does not and cannot do anything useful.

Please reopen if this doesn't fix your issue.

**Comment by black7375** [comment]
Nice work!!
Thank you for your effort. :smile:
