### ISSUE TITLE
Feature Request: 12 hour clock option in wizard

### ISSUE THREAD

**Issue by jordanjennings** [romkatv/powerlevel10k#322]
Can you add an option to the wizard for a 12 hour clock? I know this is pretty easily customizable, but I like to stick with the wizard's configuration so I can try new configs on a whim and/or be up and running on new machines quickly. I would guess many users who think in 12 hour time (like me) would enjoy this feature.

Thanks for powerlevel10k, it is amazing and keeps getting better and better! (transient prompt is fantastic btw)

**Comment by romkatv** [comment]
The bar for adding another screen to the wizard is pretty high. I'm afraid that clock format is too niche for it. Sorry.

**Comment by jordanjennings** [comment]
Would you be open a PR that changes the existing screen from a Y/N to a 1/2/3?
1)  yes with 24 hour format
2) yes with 12 hour format 3
3) no clock

**Comment by romkatv** [comment]
Sounds good.

By the way, why do you enable clock in your prompt? What information does it provide that you don't already have?

**Comment by jordanjennings** [comment]
The only reason I use the clock is for the history to show when I ran previous commands. However, I just realized that only makes sense if you have enabled `POWERLEVEL9K_TIME_UPDATE_ON_COMMAND` (which I have). I also realized that transient prompt somewhat conflicts with this request as well, at least until it has an official way to keep certain parts of the prompt.

Here are some (unproven) theories:
- Most users want the clock to see when their commands executed and therefore would benefit from having `POWERLEVEL9K_TIME_UPDATE_ON_COMMAND` enabled by default
- The clock isn't generally beneficial on the current line of the prompt
(except maybe for remote SSH sessions it could be helpful to see the local time of the machine you're on, but even that that's easy enough to find out when you actually do want it)

With that said - a PR for this is probably premature / not worth it. Here's a higher level question that would help - is there a supported / official way to have a few tweaks that are kept and that override what the wizard sets? For this case, I'd want to set `POWERLEVEL9K_TIME_FORMAT` and `POWERLEVEL9K_TIME_UPDATE_ON_COMMAND` myself but let the wizard set everything else, and I'd want those values to persist across runs of the wizard.

**Comment by romkatv** [comment]
> The clock isn't generally beneficial on the current line of the prompt

Yep.

> Most users want the clock to see when their commands executed

If you are talking about real-life users rather than theoretical sages, then I'm pretty sure virtually everyone who enables `time` does it for aesthetic reasons. 

Zsh history is much better at recording and retrieving timestamps. If you are using iTerm, it has built-in command timestamps that can be toggled when you need them. This is also neat.

> Here's a higher level question that would help - is there a supported / official way to have a few tweaks that are kept and that override what the wizard sets?

There isn't. Moreover, there is no guarantee that after you upgrade powerlevel10k and run the wizard there will be such options or even `time` segment in `~/.p10k.zsh`. There is a guarantee that your prompt won't break when you update powerlevel10k provided that you keep your config.

**Comment by jordanjennings** [comment]
>Zsh history is much better at recording and retrieving timestamps. If you are using iTerm, it has built-in command timestamps that can be toggled when you need them. This is also neat.

Didn't know about this, very useful thanks!

>There isn't. Moreover, there is no guarantee that after you upgrade powerlevel10k and run the wizard there will be such options or even time segment in ~/.p10k.zsh. There is a guarantee that your prompt won't break when you update powerlevel10k provided that you keep your config.

What about just for the `POWERLEVEL9K_*` configs?

**Comment by romkatv** [comment]
> What about just for the `POWERLEVEL9K_*` configs?

That's what I meant. A config is just a set of `POWERLEVEL9K_*` parameters.

**Comment by romkatv** [comment]
If I understand correctly, you decided against sending a PR. If this is the case, let's close the issue.

**Comment by jordanjennings** [comment]
Correct, thanks!

**Comment by romkatv** [comment]
FYI: There is now an option to choose between 12h and 24h time format in the configuration wizard. Better late than never I guess :wink:

**Comment by jordanjennings** [comment]
Wow, looking at the release notes you have been super busy. Lots of great new stuff. Thanks as always for your work!

**Comment by romkatv** [comment]
Thanks!

Brand-new docs at https://github.com/romkatv/powerlevel10k are pretty good, too :wink: If it's been a while since you've last looked at powerlevel10k, I recommend scrolling through the features. It's more user friendly and less time consuming than reading release notes.
