### ISSUE TITLE
Problems with command output when there is no trailing newline

### ISSUE THREAD

**Issue by polothy** [romkatv/powerlevel10k#323]
Noticed that if I run a command that doesn't have a newline at the end of the output, I get an extra character at the end.  It's a % sign and the background color is white and foreground is black.

With pk10:
```
❯ echo -n "test"
test%

~
❯
```

If I switch to another prompt like pure, it works as expected.

```
❯ echo -n "test"
test
~
❯
```

I do have a right prompt that I didn't copy/paste in.

I also may not have the latest version, I'm using the prezto framework.

**Comment by polothy** [comment]
I do have this enabled:
```
  # Add an empty line before each prompt.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

```
But I disabled it and still has the problem.

**Comment by romkatv** [comment]
This is working as expected. If you don't want to know whether the output of the last command was missing LF at the end, set `PROMPT_EOL_MARK=''`.

**Comment by polothy** [comment]
Worked, thanks.

**Comment by romkatv** [comment]
You can also try something like this: `PROMPT_EOL_MARK='%K{red} '`. It's a nice feature. I don't take credit for it as it's provided by zsh itself rather than by p10k.

**Comment by polothy** [comment]
Yeah, after thinking about it, it is a nice feature.  I just thought something was buggy.
