### ISSUE TITLE
How to copy configuration to another user?

### ISSUE THREAD

**Issue by vortex852456** [romkatv/powerlevel10k#324]
I want to reuse an existing `.p10k.zsh` file for a new user. Whats steps shall I perform to accomplish this?

I already tried to copy the `.zshrc` and `.p10k.zsh` files to the new home-directory with no success.
When the new user logs in with zsh, he's stuck in an infinite loop: `Seems romkatv/powerlevel10k is already installed!`

This is my `.zshrc`:
```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/zsh-antigen/antigen.zsh

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt autocd
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/vortex/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git

# themes
antigen theme romkatv/powerlevel10k

# Tell Antigen that you're done.
antigen apply

export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ll='ls $LS_OPTIONS -la'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by romkatv** [comment]
> When the new user logs in with zsh, he's stuck in an infinite loop: `Seems romkatv/powerlevel10k is already installed!`

This is a bug in antigen that isn't specific to powerlevel10k. It does it with all themes. Maybe this will help you: https://github.com/zsh-users/antigen/issues?q=is+already+installed.

**Comment by vortex852456** [comment]
@romkatv Thank you for explantation and the link!
I guess I will switch to another plugin manager. I initially wasn't aware that antigen has had no commits for about 2 years.
