### ISSUE TITLE
Best way to use non powerlevel10k prompt on tty/console screens

### ISSUE THREAD

**Issue by dbasinge** [romkatv/powerlevel10k#325]
Is there a way to use powerlevel10k on a tty/console screen or to use a different zsh prompt on those screens?

**Comment by romkatv** [comment]
There is no reliable way to detect whether your terminal is connected to a TTY (e.g., ssh client simply doesn't pass this info to the server). The standard way to do something conditional on terminal capabilities is to look at `TERM` environment variable (`TERM` is usually propagated through ssh connections). Zsh knows how to infer terminal capabilities from the value of `TERM`, so we can just ask zsh if the terminal supports at least 256 colors.

```zsh
if zmodload zsh/terminfo && (( terminfo[colors] >= 256 )); then
  # capable terminal
else
  # might be TTY or some other not very capable terminal
fi
```

You can use powerlevel10k in one branch of the condition and some other theme in another.

Note that powerlevel10k works fine in TTY. You just need to create a configuration file restricted to 8 colors and ASCII. Here's one: [p10k-portable.zsh](https://gist.github.com/romkatv/bb483a78ef6d3b9733252b8570b5d5f5). I created it by running `p10k configure` and then editing `~/.p10k.zsh`.  See the [diff](https://gist.github.com/romkatv/bb483a78ef6d3b9733252b8570b5d5f5/revisions) to get an idea.

You can save this this config as `~/.p10k-portable.zsh`:

```zsh
curl -fsSLo ~/.p10k-portable.zsh https://gist.githubusercontent.com/romkatv/bb483a78ef6d3b9733252b8570b5d5f5/raw
```

And then modify your `~/.zshrc` like this:

```zsh
if zmodload zsh/terminfo && (( terminfo[colors] >= 256 )); then
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
else
  [[ ! -f ~/.p10k-portable.zsh ]] || source ~/.p10k-portable.zsh
fi
```

Naturally, you can edit `~/.p10k-portable.zsh` to suit your needs. E.g., if you don't want prompt to change when you press enter, set `POWERLEVEL9K_TRANSIENT_PROMPT=off`. There are plenty of comments in that file to help you.

**Comment by romkatv** [comment]
FYI: Lean, Classic and Rainbow styles in the configuration wizard now have an option to use ASCII charset. Lean style also has an option to use 8 colors. Combining these two you'll get prompt that works everywhere.

**Comment by tobiasBora** [comment]
Shouldn't powerlevel10k natively support for such usage? Like the prompt could detect when some stuff are not supported by TTY and automatically disable them.

**Comment by romkatv** [comment]
> Shouldn't powerlevel10k natively support for such usage? Like the prompt could detect when some stuff are not supported by TTY and automatically disable them.

No, it shouldn't do that.
