### ISSUE TITLE
Compatibility of P10K in iTerm2

### ISSUE THREAD

**Issue by hexid26** [romkatv/powerlevel10k#327]
I'm a Mac user. In both `Terminal` and `iTerm2`, there is a function in my favor named ***Select between marks*** (`Terminal`) or ***Select Output of Last Command*** (`iTerm2`). This function can be activated by **`⇧⌘A`** to select the output content of the previous command, which is conveniently for copying the output.

However, P10K seems to have a little problem in `iTerm2` with this function, as the snapshot below:
<img width="1680" alt="Screen Shot 2019-11-13 at 8 00 40 PM" src="https://user-images.githubusercontent.com/11417927/68763779-3dad2b80-0654-11ea-8e7e-c953149ea03f.png">

In the pic above, the left side is P9K, and the right side is P10K. Obviously, with P10K `iTerm2` CAN NOT capture the correct content. However, this function works well in `Terminal` with both `P9K` and `P10K`. The snapshot is as follows:
<img width="1680" alt="Screen Shot 2019-11-13 at 8 06 45 PM" src="https://user-images.githubusercontent.com/11417927/68763769-371eb400-0654-11ea-9a9b-9602ae5e45ef.png">

First, I think maybe this is a bug in `iTerm2` (because `P10K` works well in `Terminal`). So I test different themes in ZSH. With `P9K` and some ZSH build-in themes, the **`⇧⌘A`** function works well. So I have to consider that `P10K` may miss some marks defined in `iTerm2`.

After a few tests, I find the issue is quirky. In MacOS Catalina, `iTerm2`➕`P10K` makes the function fail. However, when I ssh to an Ubuntu machine(the same ZSH config with `P10K`) via this ZSH, this function works well.
I have 3 Mac devices (Catalina), with ssh connection, I find a phenomenon：
<img width="1680" alt="Screen Shot 2019-11-13 at 8 20 56 PM" src="https://user-images.githubusercontent.com/11417927/68763739-240be400-0654-11ea-9843-0b42fde0c90e.png">
In `iTerm2`➕`P10K`, **`⇧⌘A`** function selects the content from the last command to the first command (or the first command after ssh).

I don't know why. So I just report it as a quirky issue.

**Comment by romkatv** [comment]
Thanks for the report. Please update powerlevel10k and try again. It should work now.

There are still a couple of issues with iTerm and Apple Terminal integration after my fixes:
- There are too many marks in iTerm if instant prompt is enabled.
- There are no marks at all in Apple Terminal if instant prompt is enabled.
- Ctrl-C changes the color of wrong mark in iTerm. This appears to be a bug in iTerm because the behavior is equally broken even with the default prompt.

Since you aren't enabling transient prompt, these issues should have little effect on you. I'll figure out what to do about instant prompt some time later as it doesn't seem too bad.

**Comment by hexid26** [comment]
Thanks very much. This is an efficiently fix.
I pull the new version and then `iTerm2`➕`P10K` works well on **`⇧⌘A`**. It's cool.
About `instant prompt` and `transient prompt`, I'm sorry that I have no idea about that. Something like `Toolbelt` in the `iTerm2`(I set some Triggers to detect the output)?

**Comment by romkatv** [comment]
> About instant prompt and transient prompt, I'm sorry that I have no idea about that.

These are p10k features.

- When you open a new tab, usually there is a delay before the first prompt appears. If you enable instant prompt, there is no delay.
- If you enable transient prompt, p10k will trim down prompt when accepting a command. See [demo](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif).

Both of these features can be enabled from `p10k configure`.

P.S.

I've fixed marks when instant prompt and/or transient prompt is enabled on iTerm2. Apple Terminal still doesn't display any marks when transient prompt is enabled.

**Comment by hexid26** [comment]
'**trim down prompt when accepting a command**' This feature is awesome.
For mac users, I consider that most developers use `iTerm2` to replace `Terminal`🤣
Thank you again for this great job!

**Comment by romkatv** [comment]
> '**trim down prompt when accepting a command**' This feature is awesome.

I also like it. I have it enabled in my own prompt.

You can also enabled it manually without running `p10k configure`. See https://www.reddit.com/r/zsh/comments/dsh1g3/new_powerlevel10k_feature_transient_prompt/.

> For mac users, I consider that most developers use `iTerm2` to replace `Terminal`🤣

Indeed, most macOS p10k users are using iTerm2.
