### ISSUE TITLE
displays "at staging" on the right hand side

### ISSUE THREAD

**Issue by egze** [romkatv/powerlevel10k#331]
I installed powerlevel10k at home today and on the right hand side I see this:

<img width="403" alt="data_for_seo (zsh) 2019-11-16 17-15-43" src="https://user-images.githubusercontent.com/29657/68996014-bb5f7a00-0894-11ea-9dda-f9f047000767.png">

I have no idea what `at staging` is. At work I also have powerlevel10k and I don't have `at staging` there.

**Comment by romkatv** [comment]
That's your current kubernetes context. If you don't want to see it, comment out `kubecontext` in `~/.p10k.zsh`.
