### ISSUE TITLE
Feature: Transient prompt "smart" mode

### ISSUE THREAD

**Issue by jkugelman** [romkatv/powerlevel10k#334]
The new transient prompt feature is great. On Reddit you [posted about how to keep the clock visible](https://www.reddit.com/r/zsh/comments/dsh1g3/new_powerlevel10k_feature_transient_prompt/f6w9ept/?context=1). What do you think about a more generic, segment-agnostic method? A generalization of `same-dir` mode to all segments, if you will.

1. Hide segments that are the same. Show only segments that have changed.
2. Let user configure certain segments to always show or always hide, overriding the auto-detect logic.
3. Allow the connector between left and right prompts to be configured on/off.

Some use cases:

* If the directory has changed it's displayed, like `same-dir`.

* If the `time` has changed it's displayed. This would have the nice effect of sometimes hiding the clock. Mine has minute resolution so I'd only see a clock segment once a minute. On the other hand the `date` segment would just print once a day, which seems cool.

* User and host context, the OS icon, etc. would almost always be hidden.

* Git status would be shown if the user switches branches, makes changes, etc. It'd be nice to see the branch switching when scrolling back.

* Command execution time, error status... those would end up sticking in the transient prompt. They'd be candidates for the *always hide* feature.

I am hoping this is not complicated to implement. Might it be as simple as comparing the old and new text for each segment?

**Comment by jkugelman** [comment]
> Once transient prompt enters the picture, we essentially have two prompts but still only one set of parameters.

Maybe if transiency is generalized as an auto-hide mechanism it would avoid the Pandora's box of thinking of the transient prompt as a second prompt with its own set of configuration options. It would still be the same prompt, just with most segments hidden and a bit of tweaking.

I dunno, just spitballing!

**Comment by romkatv** [comment]
Thanks for sharing your thoughts. I'll play a bit of a devil's advocate below to tease more details from you.

> 1. Hide segments that are the same. Show only segments that have changed.

This doesn't work well for segments that aren't always displayed, which is most of them. For example, there is a segment that gets displayed when you are in a python virtual environment. If you look at your scrollback and see that there was no python virtual environment in the prompt when some command was executed, does it mean the environment was the same as previously or that it was absent altogether?

There is also a problem with visual appeal and the ease of extracting information. Hiding all prompt segments that don't changes makes for some messy scrollback.

> 2. Let user configure certain segments to always show or always hide, overriding the auto-detect logic.
> 3. Allow the connector between left and right prompts to be configured on/off.

These two are already implemented.

> Some use cases:
> 
> * If the directory has changed it's displayed, like `same-dir`.
> * If the `time` has changed it's displayed. This would have the nice effect of sometimes hiding the clock. Mine has minute resolution so I'd only see a clock segment once a minute. On the other hand the `date` segment would just print once a day, which seems cool.
> * User and host context, the OS icon, etc. would almost always be hidden.
> * Command execution time, error status... those would end up sticking in the transient prompt. They'd be candidates for the _always hide_ feature.

These use cases are already supported.

> * Git status would be shown if the user switches branches, makes changes, etc. It'd be nice to see the branch switching when scrolling back.

This can be implemented on top of the current API. It's a bit tricky but not excessively so. I don't see how it can be done with the API you are proposing though. How would you specify that `vcs` prompt should stick around when branch changes but not when the number of untracked files changes?

> I am hoping this is not complicated to implement. Might it be as simple as comparing the old and new text for each segment?

Not too difficult to implement but it doesn't fit the existing API and the utility is not clear. If there was a use case that appeals to non-trivial fraction of users and that can be implemented with the new API but not with the current API, then it would be a reason to consider adding the new API. Is there such use case? Seems like all use-case that you've listed are already supported by the existing API.

**Comment by jkugelman** [comment]
I should add some code examples so I'm not just describing my idea.

I think I'm proposing something that applies to both transient prompts and non-transient prompts. It's a bridge between the two modes.

To make up a new term, let's say that the *ghost prompt* is what's left behind before moving on to the next prompt. I'm using "ghost prompt" to cover both the transient and non-transient prompts. If in non-transient mode then the ghost prompt is your full prompt; in transient mode it's just the `prompt_char`; in auto mode it's something in between.

```zsh
# Like non-transient mode. Leave all the segments visible.
POWERLEVEL9K_GHOST_PROMPT_DEFAULT_DISPLAY=always
# Like transient mode. Hide all the segments.
POWERLEVEL9K_GHOST_PROMPT_DEFAULT_DISPLAY=never
# "Auto" mode. Hide segments that are the same.
POWERLEVEL9K_GHOST_PROMPT_DEFAULT_DISPLAY=if-changed
```

That setting would apply to all the segments in the ghost prompt. It would give the overall behavior. Then there could be segment-by-segment adjustments:

```zsh
# Like same-dir mode, except it only displays the directory segment, not the entire prompt.
# It's a lightweight same-dir.
POWERLEVEL9K_GHOST_PROMPT_DEFAULT_DISPLAY=never
POWERLEVEL9K_GHOST_PROMPT_DIR_DISPLAY=if-changed
POWERLEVEL9K_GHOST_PROMPT_STATUS_DISPLAY=always
```

And then there'd be a separate option for ghost prompt filler, separate from the 

```zsh
# Use a different gap filler than the normal prompt, if set.
POWERLEVEL9K_GHOST_PROMPT_MULTILINE_FIRST_PROMPT_GAP_CHAR=''
```
> > 1. Hide segments that are the same. Show only segments that have changed.
> 
> This doesn't work well for segments that aren't always displayed, which is most of them. For example, there is a segment that gets displayed when you are in a python virtual environment. If you look at your scrollback and see that there was no python virtual environment in the prompt when some command was executed, does it mean the environment was the same as previously or that it was absent altogether?

That's what happens already with the `dir` segment, though, no? If the transient prompt is off-screen what was the directory for all the commands?

A user could set `POWERLEVEL9K_GHOST_PROMPT_PYENV_DISPLAY=always` if they want that particular segment to stick around. But they should probably just let it go...


> There is also a problem with visual appeal and the ease of extracting information. Hiding all prompt segments that don't changes makes for some messy scrollback.

Yeah, you might be right.

There could be an option to force the entire prompt to be redisplayed when any segment changes. Something like:

```zsh
POWERLEVEL9K_GHOST_PROMPT_DEFAULT_DISPLAY=only-changed-segments
POWERLEVEL9K_GHOST_PROMPT_DEFAULT_DISPLAY=all-segments-if-any-changed
```

(Silly option values, but again, just spitballing!)

> > 1. Let user configure certain segments to always show or always hide, overriding the auto-detect logic.
> > 2. Allow the connector between left and right prompts to be configured on/off.
> 
> These two are already implemented.

For transient prompts, I mean.

> 
> > Some use cases:
> > 
> > * If the directory has changed it's displayed, like `same-dir`.
> > * If the `time` has changed it's displayed. This would have the nice effect of sometimes hiding the clock. Mine has minute resolution so I'd only see a clock segment once a minute. On the other hand the `date` segment would just print once a day, which seems cool.
> > * User and host context, the OS icon, etc. would almost always be hidden.
> > * Command execution time, error status... those would end up sticking in the transient prompt. They'd be candidates for the _always hide_ feature.
> 
> These use cases are already supported.

Are they? Maybe I'm missing some features of transient prompts?

What led me here was this specific wish list: I want the transient prompt to show the directory only when it changes, and *only* show the directory, not the rest of the segments. If the time changes minutes I want it in the transient prompt, but if I type a bunch of commands in quick succession I don't want the time printed over and over.

```zsh
[~] ............... 5:45 🕑           # full prompt
$ ls
foo bar baz
$ pwd
/home/jkugelman
                    5:46 🕑           # clock ticks
$ ls
foo bar baz
$ cd bar
[~/bar]                                # chdir but still 5:46
$ ls
quux
                   10:11 🕑           # user comes back a few hours later
$ cd ~/baz
[~/baz] .......... 11:12 🕑           # disappears again for another hour
$
```

**Comment by romkatv** [comment]
> I want the transient prompt to show the directory only when it changes, and *only* show the directory, not the rest of the segments. If the time changes minutes I want it in the transient prompt, but if I type a bunch of commands in quick succession I don't want the time printed over and over.

Thanks for describing your use case. Let's deal with it first. If it turns out that it cannot be implemented with the current API, we can discuss how the API should be extended.

Here's a config for the prompt you've described:

**DISCLAIMER: Experimental API. Not officially supported.**

```zsh
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir newline prompt_char)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(time)

typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=

typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=

typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=' '
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=' '
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='·'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=240

typeset -g POWERLEVEL9K_DIR_FOREGROUND=39

typeset -g POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='\$'
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

typeset -g POWERLEVEL9K_TIME_FOREGROUND=66
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

function p10k-on-post-prompt() {
  local current_dir=${(%):-%/}
  local current_time=${(%):-%D{%H:%M}}
  if [[ $current_dir == $last_dir && $current_time == $last_time ]]; then
    p10k display '1'=hide
  elif [[ $current_dir == $last_dir ]]; then
    p10k display '1/(left/dir|gap)'=hide
  elif [[ $current_time == $last_time ]]; then
    p10k display '1/(right/time|gap)'=hide
  fi
  last_dir=$current_dir
  last_time=$current_time
}

function p10k-on-pre-prompt() {
  # Unhide everything that may have been hidden by p10k-on-post-prompt.
  p10k display '1(|/left/dir|/right/time|/gap)'=show
}
```

The logic in `p10k-on-post-prompt` is straightforward. Importantly, it can easily be extended with extra rules. For example:

- Display full prompt every minute.
- Display full prompt when directory changes.
- Display time with second resolution but still hide it on 1 minute schedule.
- Hide directory when the new directory is a subdirectory of the previous.
- Display directory only when you `cd` into it for the first time in the session.

Is there an interesting/useful use case that cannot be implemented with this API?

**Comment by jkugelman** [comment]
Ah, I took your "experimental API" warning as an indication that you were exposing P10K internals and didn't want us to rely on it.

Did I read that wrong? It sounds like you do intend it to become public API, but it's not yet and you reserve the right to change it right now?

If so, this should be perfect and I'll happily withdraw my suggestions. Thanks!

**Comment by romkatv** [comment]
> It sounds like you do intend it to become public API, but it's not yet and you reserve the right to change it right now. Is that right?

Correct. It's experimental, not internal. Everything internal in p10k starts with an underscore.

> If so, this should be perfect and I'll happily withdraw my suggestions. Thanks!

Thanks for confirming that this API would work for you. Closing the issue.
