### ISSUE TITLE
Termux: gitstatus error on startup

### ISSUE THREAD

**Issue by aquintanar** [romkatv/powerlevel10k#337]
Error in startup using termux 0.81

> I checked that the file gitstatusd-android-armv8l is not in the filesystem

[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /data/data/com.termux/files/usr/tmp/gitstatus.5387.xtrace.1574201859.9925458431.18359 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local daemon='' os
    +gitstatus_start_impl:8> [[ -n '' ]]
    +gitstatus_start_impl:9> os=+gitstatus_start_impl:9> uname -s
    +gitstatus_start_impl:9> os=Linux
    +gitstatus_start_impl:9> [[ -n Linux ]]
    +gitstatus_start_impl:10> [[ Linux != Linux ||+gitstatus_start_impl:10> uname -o
    +gitstatus_start_impl:10> [[ Linux != Linux || Android != Android ]]
    +gitstatus_start_impl:10> os=Android
    +gitstatus_start_impl:11> [[ android != (mingw|msys)* ]]
    +gitstatus_start_impl:12> local arch
    +gitstatus_start_impl:12> arch=+gitstatus_start_impl:12> uname -m
    +gitstatus_start_impl:12> arch=armv8l
    +gitstatus_start_impl:12> [[ -n armv8l ]]
    +gitstatus_start_impl:13> daemon=/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv8l
    +gitstatus_start_impl:15> [[ -x /data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-armv8l ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: Linux localhost 3.18.19+ #1 SMP PREEMPT Fri Mar 29 03:55:18 UTC 2019 armv8l Android

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new

**Comment by romkatv** [comment]
There is no prebuilt gitstatusd binary for your CPU architecture. I only provide binaries for popular architectures and 32-bit ARMv8 didn't make the cut.

There are a few things you can try:

1. See if the 64-bit binary works. Run this:
```zsh
/data/data/com.termux/files/home/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-android-aarch64 --help
```
I think it should't work but if it does please let me know and I'll symlink armv8l to aarch64.
2. Build gitstatusd yourself. It's not too difficult. See https://github.com/romkatv/gitstatus/blob/master/README.md#compiling.
3. Add `POWERLEVEL9K_DISABLE_GITSTATUS=true` to your `~/.zshrc`. It'll get rid of the error message when starting zsh but your prompt will be **much** slower than it normally is, especially when your current directory is inside a Git repository.

Out of curiosity, what device are you using (manufacturer and model)?

**Comment by romkatv** [comment]
Would appreciate if you could reply.

**Comment by aquintanar** [comment]
   ~/.oh-my-zsh/cu/t/powerlevel10k/g/bin    master  ./gitstatusd-android-aarch64
WARNING: linker: ./gitstatusd-android-aarch64: unused DT entry: type 0x1d arg 0x19d6
WARNING: linker: ./gitstatusd-android-aarch64: unused DT entry: type 0x6ffffef5 arg 0xb48
WARNING: linker: ./gitstatusd-android-aarch64: unused DT entry: type 0x6ffffffe arg 0x4268
WARNING: linker: ./gitstatusd-android-aarch64: unused DT entry: type 0x6fffffff arg 0x2
CANNOT LINK EXECUTABLE DEPENDENCIES: "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 32-bit instead of 64-bit

**Comment by romkatv** [comment]
Well it was worth a try. Option (1) is out. Pick between (2) and (3).

> Out of curiosity, what device are you using (manufacturer and model)?

Is it a phone? A tablet? A smart TV? What's the model?

**Comment by aquintanar** [comment]
Amazon Fire HD 10 (2017)

I know that is not the best device for this.

**Comment by romkatv** [comment]
I think it should work just fine. I'm building `android-aarch64` binaries on Nexus 5x from 2015. p10k is snappy there.

As I mentioned, there is no real obstacle to using gitstatus on your device other than the fact that I didn't build a binary for it. You can build it yourself. Install clang, gnu make and cmake and run `build.zsh`. See https://github.com/romkatv/gitstatus/blob/master/README.md#compiling for details.

**Comment by brunodavi** [comment]
gitstatus failed to initialize.

Could you tell me the command to disable this error

**Comment by brunodavi** [comment]
POWERLEVEL9K_DISABLE_GITSTATUS=true

tested it but it didn't work

**Comment by romkatv** [comment]
@brunodavi Run this:

```zsh
echo 'POWERLEVEL9K_DISABLE_GITSTATUS=true' >>~/.zshrc
exec zsh
```
