### ISSUE TITLE
[feature] Add wttr.in weather info

### ISSUE THREAD

**Issue by madalincolea** [romkatv/powerlevel10k#338]
Would it be possible to add [wttr.in](wttr.in) weather info to the prompt?

Since it relies on curl I'm thinking it's a similar approach to the _public_ip_ one. 

Thanks!

**Comment by romkatv** [comment]
It's possible but I'm not eager to do it. Weather is not a property of your zsh session. It updates independently of shell state. If you want to see it when your terminal is open, you'll probably want to see it when it's closed. It's similar to battery. Both are poor fit for displaying in prompt and a good fit for displaying in your task tray or whatever area your desktop environment uses to display system-wide things.
