### ISSUE TITLE
ERROR: 'flowing:14: character not in range', '_p9k_get_icon:14: character not in range'

### ISSUE THREAD

**Issue by CommanderKronos** [romkatv/powerlevel10k#340]
I'm trying to install powerlevel10k for zsh, But i'm having trouble getting it to work. upon opening zsh I'm greeted with the Powerlevel10k configuration wizard. But immediatly after that the "control" diamond you're supposed to see doesn't show up. followed by the two errors in the title. 
I have gotten the nerd-fonts-complete package installed.
Info:

- WM: Awesome

- Terminal: Alacritty

- Current configured font: Hack Nerd Font

- Distro: Arch Linux

Does this mean some characters are missing? Or is something going wrong with the terminal not finding the characters? This error also comes up while using other terminal emulators like termite.

**Comment by romkatv** [comment]
Please type echo '\u276F'. If you get an error saying "zsh: character not in range", your locale doesn't support UTF-8. You need to fix it. See https://wiki.archlinux.org/index.php/locale.

**Comment by CommanderKronos** [comment]
Wow that's a lightning fast response. This fix worked immediatly. Thank you so much, now i've finally ascended to zsh with Powerlevel10k!

**Comment by romkatv** [comment]
Awesome! Glad you got it working.
