### ISSUE TITLE
virtualenv segment not removed after reloading zsh

### ISSUE THREAD

**Issue by le0nik** [romkatv/powerlevel10k#343]
Steps to reproduce(using Python 3.8.0):

1. Add virtualenv to your left segments in .zshrc: `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs virtualenv)`
2. Create virtual env in new folder: `$ python -m venv venv`
3. Activate virtual env: `$ source ./venv/bin/activate`. **Now you can see the virtualenv segment**.
4. Reload zsh: `$ exec zsh` or `$ src`(if https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/zsh_reload is installed). **Virtualenv segment is still visible** although virtualenv is not active. You can verify it by trying to run `deactivate` or using the virtualenv in any other way.

**Comment by romkatv** [comment]
`exec zsh` propagates all exported variables. If you want to use `exec zsh` in place of restarting zsh, it's your responsibility to unset exported variables in `~/.zshrc`.
