### ISSUE TITLE
Prompt separator does not align well when using nerd fonts from AUR

### ISSUE THREAD

**Issue by fikovnik** [romkatv/powerlevel10k#344]
I tried to use "MesloLGS Nerd Font" installed from AUR package nerd-fonts-meslo 2.0.0-1 and I get this one 1px line before the arrow in the prompt:

![Screenshot_2019-11-24_13-54-16](https://user-images.githubusercontent.com/374674/69494989-14956200-0ec2-11ea-9155-ad5442034d8b.png)

I tried couple of other nerd fonts (all installed from AUR) and it is the same.

Using font Dejavu Sans Mono for powerline installed from ttf-dejavu-sans-mono-powerline package works well.

Would you know what is wrong? Thanks you!

**Comment by romkatv** [comment]
Some terminals are better than others at scaling fonts. You can try changing font size, using a different terminal, or a different prompt style.

**Comment by lnicola** [comment]
@fikovnik I just ran into the same issue and switching from subpixel to to grayscale hinting fixed it.

It should be possible to do that for a specific font family and size, but I couldn't manage to get it working.

**Comment by romkatv** [comment]
Thanks for sharing, @lnicola. Perhaps it'll help someone else.

**Comment by lnicola** [comment]
@romkatv on a related note, the font selection instructions for Gnome Terminal are incomplete. They work for the font you recommend (MesloLGS NF), but the fonts on the Nerd Fonts package (at least the AUR one) don't show up in the font dialog.

See https://github.com/ryanoasis/nerd-fonts/issues/318 for the explanation and a workaround.

**Comment by romkatv** [comment]
The [instructions in the p10k readme](https://github.com/romkatv/powerlevel10k/blob/master/README.md#recommended-meslo-nerd-font-patched-for-powerlevel10k) are specifically for the recommended font. I wouldn't presume to write generic instructions that would work for any font.
