### ISSUE TITLE
Suggestion for improvement - make it easier to edit config after wizard

### ISSUE THREAD

**Issue by kmejka** [romkatv/powerlevel10k#345]
Hi, I love the work you've done with powerlevel10k, it's awesome! I especially appreciate the speed at which it functions.

The configuration wizard is also awesome, I have a suggestion though connected with it. I want to change some of the configuration parameters for my shell, and after running the configuration wizard I find it really hard to edit the configuration, with it being so big. Could you perhaps output which sections on the end config file are connected with which wizard options? 

For example, I'd like to change the `concise` option, but I'm not sure how to do it in the config file. I'll have to run the configuration wizard again to customize it. 

Thanks in advance!

**Comment by romkatv** [comment]
Options in the configuration wizard are for the most part independent from the things you can change by editing the resulting config. There is no section in the config that corresponds to concise/verbose option in the wizard. The effects of your choice are spread all over the config file. Conversely, there is no option in the wizard to display battery but it can easily be done by editing the config.

Please use the wizard to generate the starting config and then optionally edit it to further customize prompt.

**Comment by kmejka** [comment]
Hi @romkatv ok, I understand what you're saying. But could you then point me to a place where I can get familiar with the configuration parameters which I can edit in the config file?

**Comment by romkatv** [comment]
Open the config and read through. There are plenty of comments to help you.

**Comment by kmejka** [comment]
Hi @romkatv the configuration file generated by the wizard is several hundred lines long. Searching for something is pretty hard to do. My question was if there was some place where you could easily see the configuration parameters for it, especially since you're using a different tool to generate the git related prompt, which means that some config parameters from powerlevel9k don't work in powerlevel10k. 

I assume now that there is no such list, so I think that's the end of it. Thanks for your help.

**Comment by romkatv** [comment]
> My question was if there was some place where you could easily see the configuration parameters for it

Are you asking whether there is documentation that lists all parameters recognized by powerlevel10k? If so, then the answer is no, there is no such documentation. Note that such documentation would be longer than configs generated by `p10k configure`.

> the configuration file generated by the wizard is several hundred lines long. Searching for something is pretty hard to do

The bulk of the config is for specific prompt segments. For example, if you want to see which parameters you can tweak to configure `virtualenv` segment, search for `virtualenv` using the search function of your text editor.

There are also a few prompt-wide parameters at the top and at the bottom of the config.

> especially since you're using a different tool to generate the git related prompt, which means that some config parameters from powerlevel9k don't work in powerlevel10k.

All powerlevel9k parameters work with powerlevel10k. If you have a config that works with powerlevel9k, you can use it with powerlevel10k without any changes. So if you prefer to write your own config by hand, using powerlevel9k documentation as a reference, you can do so. The configuration wizard in powerlevel10k is something that you can but don't have to use.

There are additional parameters that powerlevel10k recognizes but powerlevel9k doesn't. This means that not all powerlevel10k configs work with powerlevel9k.
