### ISSUE TITLE
Git status is slow 

### ISSUE THREAD

**Issue by fzakaria** [romkatv/powerlevel10k#347]
I enabled zprof and it looks like ~1 second is spent starting gitstatus on every tab.
That seems pretty high -- maybe can this be delayed until we enter a first git directory?

```
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1        1028.71  1028.71   38.34%   1028.50  1028.50   38.33%  gitstatus_start_impl
 2)    3         871.52   290.51   32.48%    866.48   288.83   32.30%  _zsh_highlight_call_widget
 3)    1         506.71   506.71   18.89%    506.71   506.71   18.89%  _p9k_init_ssh
 4)   10         556.49    55.65   20.74%     49.04     4.90    1.83%  (anon)
 5)    1          38.60    38.60    1.44%     38.50    38.50    1.43%  _zsh_highlight_load_highlighters
 6)    1          34.45    34.45    1.28%     34.45    34.45    1.28%  compinit
 7)    1          18.87    18.87    0.70%     18.87    18.87    0.70%  handle_completion_insecurities
```

**Comment by romkatv** [comment]
What is the problem you are trying to solve by running zprof? If you want to speed up zsh startup, please enable instant prompt (requires zsh >= 5.4).

---

You can enable instant prompt either by running `p10k configure` or by manually adding the following
code snippet at the top of `~/.zshrc`:

```zsh
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

It's important that you copy the lines verbatim. Don't replace `source` with something else, don't
call `zcompile`, don't redirect output, etc.

---

P.S.

The numbers in your profile are about 100 times higher than on my machine. What hardware and OS is that?

**Comment by fzakaria** [comment]
@romkatv  -- i am running 5.7+ from HomeBrew.

I couldn't get the gitstatus to repeat so maybe it was a one-off.
Turns out the major delay in startup was from zsh-highlighting & zsh-autosuggestions which is a shame since I love those plugins.

I'll close.

**Comment by romkatv** [comment]
> Turns out the major delay in startup was from zsh-highlighting & zsh-autosuggestions which is a shame since I love those plugins.

If you enable instant prompt, zsh will start instantly even if you use two dozen of slow plugins. Please the the instructions above.

**Comment by fzakaria** [comment]
Oh nice!~
I actually had the instant stuff but my shell was /bin/zsh and not the latest from HomeBrew (i'm on OSX).
Just fixed it and now its blazing fast 👍
