### ISSUE TITLE
Weird glyphs

### ISSUE THREAD

**Issue by simmeringc** [romkatv/powerlevel10k#349]
What's the meaning behind these numbers? Is there a way I can get glyphs instead?

![image](https://user-images.githubusercontent.com/10622438/69691271-cdf36380-108b-11ea-844a-faa45c40e8c6.png)

**Comment by romkatv** [comment]
`*1 !2` means 1 stash, 2 unstaged changes.

You can see the meaning of all symbols and/or change the format of Git status by opening `~/.p10k.zsh` and searching for `my_git_formatter`.

**Comment by simmeringc** [comment]
Thanks for the reply. I thought other Powerline fonts besides Meslo NF would support glyphs, but not all of them do.
