### ISSUE TITLE
Python venv prompt - handling generic names

### ISSUE THREAD

**Issue by kontax** [romkatv/powerlevel10k#350]
When I create a python virtual environment, I generally place it in the same folder as the project under the folder name `.venv` (for better or worse). This leads to every virtual environment being called .venv, whereas what I'd like it to be called is the parent folder.

For example, if `$VIRTUAL_ENV=/dev/project/.venv`, then I'd like `(project)` to be in the prompt instead.

I looked into using `$POWERLEVELVIRTUALENV_CONTENT_EXPANSION` however I'm not sure it's possible to get what I want without removing all the other information such as python version, are there any other possibilities?

How this is handled in [spaceship](https://github.com/denysdovhan/spaceship-prompt/blob/master/sections/venv.zsh) is a list of generic virtualenv folders are checked, and if matched then `$VIRTUAL_ENV:h:t` is used instead of `$VIRTUAL_ENV:t`, is there any scope to do something similar, or do you think there could be compatibility issues?

**Comment by romkatv** [comment]
Done. The new parameter is called `POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES` and it defaults to `(virtualenv venv .venv)`.

**Comment by kontax** [comment]
That was quick, thanks!
