### ISSUE TITLE
unknown function: _p9k_on_expand

### ISSUE THREAD

**Issue by mdavis332** [romkatv/powerlevel10k#353]
My git clone of the p10k repo is currently behind by 790 commits. I did a `git pull` and upon reloading zsh, I get the constant error:

`zsh: unknown function: _p9k_on_expand`

Not sure what's up since the internal/p10k.zsh file seems to have that function defined. I wound up doing a `git reset` to go back to state prior to the pull.

**Comment by romkatv** [comment]
What did you do after `git pull`?

**Comment by mdavis332** [comment]
Nothing besides opening a new terminal to see if it worked. I thought my existing configs in ~/.zshrc would all still be good and I didn't see anything in the README to indicate changes were necessary. Certainly open to it though if more is needed after the `git pull`.

**Comment by romkatv** [comment]
Your previous config should just work unless it was using private names (they all start with underscore). I primarily asked to know how you restarted zsh after `git pull`. Opening a new terminal tab is good. Should work.

Are you using a plugin manager? Some of them have buggy caches that need to be deleted manually when you update "plugins".

**Comment by mdavis332** [comment]
Not using a plugin manager for p10k. Just `git clone`d the repo to my `~/.oh-my-zsh/custom/themes` and have the `ZSH_THEME=powerlevel10k/powerlevel10k` in my `~/.zshrc` file.

**Comment by romkatv** [comment]
Do you get the same error without your config? If no, please attach your config.

**Comment by mdavis332** [comment]
When you say "config," do you mean the `.zshrc` file? Interestingly, I had another computer to test on so I did a `git pull` on it to update p10k and it worked fine. I did a `diff` between the .zshrc files on both machines and only one difference existed - `source /usr/local/bin/virtualenvwrapper.sh`

I thought that might be it, but I added that python module to the working machine and added that source line to my .zshrc and the working machine kept working. 

So perhaps it's something other than the .zshrc causing it...

**Comment by romkatv** [comment]
Try to remove p10k and clone it afresh?

Either way, it seems like something is broken on one of your machines that prevents p10k from being sourced properly. Please update this issue when you learn what it is. Reopen it if anything indicates the problem is on p10k side.
