### ISSUE TITLE
Hanging indefinitely

### ISSUE THREAD

**Issue by cgurps** [romkatv/powerlevel10k#354]
Hey,

I'm using the latest version of ZSH (5.7.1). When I start ZSH with your theme, it hangs indefinitely (nothing appears on the screen). To get something I have to kill some process using CTRL-P then a naked prompt appears. After that if I enter some commands, the next prompts have the correct theme.

On top of that, I have the 
`zsh -dfmxc cd /; read; /usr/bin/setsid zsh -dfxc $'\n'\ \ \ \ \ \ \ \ exec\ \>\&4$'\n'\ \ \ \ \ \ \ \ echo\ \$\$$'\n'\ \ \ \ \ \ \ \ /home/users/thomascai/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64\ --lock-fd=3\ --parent-pid=136933\ --num-threads=32\`
command running at 100% on one core in the background. This process gets killed once I close the terminal.

The issue seems to be related to what you're saying in the comment on line 416 of [LINK](https://github.com/romkatv/powerlevel10k/blob/2d32241c20571f594719015fccd254e03badb0f1/gitstatus/gitstatus.plugin.zsh).

If you have any idea.

PS: even though you see that powerlevel10k is installed in the oh-my-zsh folder, I've made the test with a naked configuration and it gives me the same result!

**Comment by romkatv** [comment]
Please post your `~/.zshrc`.

**Comment by cgurps** [comment]
As I said this is my whole .zshrc: 
`source $HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme`

**Comment by romkatv** [comment]
> As I said this is my whole .zshrc:
> `source $HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme`

This is very odd indeed. It's almost incredible. Let's see if literally repeating your instructions reproduces this issue on your machine. Please run the following command and let me know what happens.

```zsh
(
  emulate -L zsh
  setopt no_unset err_return
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k
    >$tmp/.zshrc echo "source ${(q)tmp}/powerlevel10k/powerlevel10k.zsh-theme"
    ZDOTDIR=$tmp zsh
  } always {
    cd || true
    rm -rf $tmp
  }
)
```

**Comment by cgurps** [comment]
The is the output I get:
> Cloning into '/tmp/p10k.v7MBWmjRDH/powerlevel10k'...
> remote: Enumerating objects: 38, done.
> remote: Counting objects: 100% (38/38), done.
> remote: Compressing objects: 100% (34/34), done.
> remote: Total 38 (delta 3), reused 12 (delta 0), pack-reused 0
> Unpacking objects: 100% (38/38), done.
> (anon):39: unknown file attribute 
And then if I do the same steps a described before (CTRL+C and then enter) I get the right shell!

**Comment by cgurps** [comment]
Adding -x to your command, zsh stops at

```
+gitstatus_start_impl:1> [[ /dev/null == /dev/null ]]
+gitstatus_start_impl:6> ((  daemon_pid == -1  ))
+gitstatus_start_impl:69> ((  async  ))
+gitstatus_start_impl:72> local reply IFS=''
+gitstatus_start_impl:73> read -ru 23 reply
```

It seems to be related to [356](https://github.com/romkatv/powerlevel10k/issues/356)

**Comment by romkatv** [comment]
Thanks for the logs.

You have old `zsh` in your `PATH`, so when p10k tries to run zsh scripts through `command zsh`, it gets 5.0.2 instead of the newer zsh. It's not a good idea to have ancient zsh in your `PATH`.

I've implemented several workarounds in p10k to try to survive setups like yours. Please update powerlevel10k and try again. Errors should be gone although some features may be disabled.

**Comment by cgurps** [comment]
Wouldn't it be simpler if you provide a PK10_ ZSH_BIN variable so that the call to zsh is consistent?

**Comment by romkatv** [comment]
Do you mean that p10k will require that uses define this parameter? I don't think it's simpler than not requiring a parameter.

Please reopen if the issue is not resolved after updating powerlevel10k.

**Comment by cgurps** [comment]
It works now thank you!

**Comment by romkatv** [comment]
Thanks for the confirmation and for reporting the issue in the first place.

**Comment by cgurps** [comment]
You're welcome :+1:

**Comment by CoreyTrombley** [comment]
> > As I said this is my whole .zshrc:
> > `source $HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme`
> 
> This is very odd indeed. It's almost incredible. Let's see if literally repeating your instructions reproduces this issue on your machine. Please run the following command and let me know what happens.
> 
> ```shell
> (
>   emulate -L zsh
>   setopt no_unset err_return
>   tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
>   {
>     git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $tmp/powerlevel10k
>     >$tmp/.zshrc echo "source ${(q)tmp}/powerlevel10k/powerlevel10k.zsh-theme"
>     ZDOTDIR=$tmp zsh
>   } always {
>     cd || true
>     rm -rf $tmp
>   }
> )
> ```

This also solved my issue. Not sure what the cause was, but I also was having the same changing issue.
