### ISSUE TITLE
show  messy code：*22 !3 ?2

### ISSUE THREAD

**Issue by kuperxu** [romkatv/powerlevel10k#355]
I configure as The tutorial, But the display abnormal.
![image](https://user-images.githubusercontent.com/10049446/69793360-3a44a300-1203-11ea-8e88-40dc62f29b9c.png)

**Comment by romkatv** [comment]
This looks normal. See https://github.com/romkatv/powerlevel10k/issues/349.

**Comment by kuperxu** [comment]
thanks
