### ISSUE TITLE
Git: Modified and Untracked icons?

### ISSUE THREAD

**Issue by swarad07** [romkatv/powerlevel10k#360]
![Screenshot 2019-12-02 at 11 26 50 AM](https://user-images.githubusercontent.com/421882/69934011-b20e1880-14f6-11ea-9f51-45dc7797d39e.png)

Love the theme, I wanted to know if this is how modified and untracked files count is supposed to be displayed? `? and !`

I did `p10k configure` and I am able to see all icons clearly, I have also added the font files.

I was trying to find a list of all possible icons that can be shown and was not able to find any such information.

**Comment by romkatv** [comment]
> Love the theme, I wanted to know if this is how modified and untracked files count is supposed to be displayed? `? and !`

Yes. See https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean.

> I was trying to find a list of all possible icons that can be shown and was not able to find any such information.

There is no such list, sorry.

You might want to open `~/.p10k.zsh` and read through the content of `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` at the top to get an idea of what you prompt can display.
