### ISSUE TITLE
Custom POWERLEVEL9K_CONTEXT_FOREGROUND not setting correctly

### ISSUE THREAD

**Issue by jpetermans** [romkatv/powerlevel10k#362]
I most likely don't understand how setting custom colors are supposed to work, but a recent p10k update broke my custom config which sets `POWERLEVEL9K_CONTEXT_FOREGROUND` in a separate zsh file that runs at login. This worked fine until I updated today. Now I'm unable to set a custom color. My `POWERLEVEL9K_CONTEXT_{DEFAULT,REMOTE,REMOTE_SUDO}_TEMPLATE` still works, but I had to add the DEFAULT option to bring it back, so it seems like a change to the way CONTEXT is handled is the issue.

My login sources `powerlevel10k.zsh-theme`, then `config/p10k-lean.zsh`, then my custom file that sets various POWERLEVEL9K*. When I `echo $POWERLEVEL9K_CONTEXT_FOREGROUND`, the variable is set to my custom color, 28, but the prompt renders the color from p10k.zsh (I think) instead.

When setting `POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND`, it works, but `POWERLEVEL9K_CONTEXT_FOREGROUND `does not. Is there a default CONTEXT_FOREGROUND variable I should be using that changed from `POWERLEVEL9K_CONTEXT_FOREGROUND `?

**Comment by romkatv** [comment]
> I most likely don't understand how setting custom colors are supposed to work

When p10k renders prompt segment `foo` in state `BAR` it looks up foreground color as follows:

1. If `POWERLEVEL9K_FOO_BAR_FOREGROUND` is set, use that.
2. If `POWERLEVEL9K_FOO_FOREGROUND` is set, use that.
3. If `POWERLEVEL9K_FOREGROUND` is set, use that.
4. Use the hard-coded color for segment `foo` in state `BAR`.

> When setting `POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND`, it works, but `POWERLEVEL9K_CONTEXT_FOREGROUND` does not.

Prompt segment `context` can be in one of the following states:

- `ROOT`: privileged user (not necessarily `root` despite the name of this state).
- `REMOTE` and `REMOTE_SUDO`: non-privileged user connected over SSH. There is no meaningful difference between `REMOTE` and `REMOTE_SUDO`, so it's a good idea to treat them equally.
- `DEFAULT` and `SUDO`: non-privileged user not connected over SSH.  There is no meaningful difference between `DEFAULT` and `SUDO`, so it's a good idea to treat them equally.

Here's how `context` is configured in `p10k-lean.zsh`:

```zsh
##################################[ context: user@hostname ]##################################
# Context color when running with privileges.
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=178
# Context color in SSH without privileges.
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=180
# Default context color (no privileges, no SSH).
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=180

# Context format when running with privileges: bold user@hostname.
typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%B%n@%m'
# Context format when in SSH without privileges: user@hostname.
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
# Default context format (no privileges, no SSH): user@hostname.
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'

# Don't show context unless running with privileges or in SSH.
# Tip: Remove the next line to always show context.
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
```

Note that `FOREGROUND` parameters are explicitly defined for states `ROOT`, `REMOTE` and `REMOTE_SUDO` but not for `DEFAULT` or `SUDO`. Thus, if you define `POWERLEVEL9K_CONTEXT_FOREGROUND` after sourcing `p10k-lean.zsh`, it will affect `context` only in states `DEFAULT` and `SUDO`. Also note the last two lines of the configuration quoted above which hide `context` in states `DEFAULT` and `SUDO.

> My login sources `powerlevel10k.zsh-theme`, then `config/p10k-lean.zsh`, then my custom file

This setup is susceptible to breakage every time you update powerlevel10k. Please follow the documented configuration instructions to ensure that your prompt doesn't break when powerlevel10k is updated.

> [...] type `p10k configure`. You can further customize your prompt by editing `~/.p10k.zsh`.

If you are keeping your dotfiles in a Git repository (a very good idea), commit `~/.p10k.zsh` before and after editing it. This way you'll have a commit with just your changes that you'll be able to look at and perhaps apply to a different base `~/.p10k.zsh` in the future.

Note that applying your custom edits on top of a newer version of base `~/.p10k.zsh` (or `p10k-lean.zsh`) is non-trivial and cannot be automated. Your current setup essentially attempts to automate what cannot be automated. It ignores potential merge conflicts with broken prompt as the result.

Keep in mind that it's absolutely not necessary to run `p10k configure` and/or to re-apply your edits when you update powerlevel10k. You can simply keep your edited `~/.p10k.zsh` forever. Future versions of powerlevel10k may make your prompt faster but they won't change the way it looks and/or behaves.

**Comment by jpetermans** [comment]
Thanks for the detailed reply! I've made a few tweaks based on your response which fixed my issue and I'll look further into customizing based on editing `.p10k.zsh` instead of my secondary settings file.

**Comment by Emilv2** [comment]
@romkatv  
>     * `REMOTE` and `REMOTE_SUDO`: non-privileged user connected over SSH. There is no meaningful difference between `REMOTE` and `REMOTE_SUDO`, so it's a good idea to treat them equally.
> 
>     * `DEFAULT` and `SUDO`: non-privileged user not connected over SSH.  There is no meaningful difference between `DEFAULT` and `SUDO`, so it's a good idea to treat them equally.

Maybe it's a good idea to put that in the documentation/comments above these values? Right now this is not very clear.

**Comment by romkatv** [comment]
The current comments in the config say the same thing with fewer words, no?

**Comment by Emilv2** [comment]
Now I know it I see that it says that, but IMO if you don' know that it looks like splitting `POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE=...` into `POWERLEVEL9K_CONTEXT_REMOTE_TEMPLATE=...` and `POWERLEVEL9K_CONTEXT_REMOTE_SUDO_TEMPLATE=...` would give a difference.

**Comment by romkatv** [comment]
Indeed, not knowing what brace expansion does makes it difficult to understand config that uses brace expansion. I don’t think this warrants removing brace expansion.
