### ISSUE TITLE
Git branch is 'loading'

### ISSUE THREAD

**Issue by mbwhite** [romkatv/powerlevel10k#364]
Just started today, but the git branch in the prompt is being reported as 'loading'  

Advice on the best way to debug this welcome!

**Comment by romkatv** [comment]
Please do the following.

1. Add `GITSTATUS_LOG_LEVEL=DEBUG` to `~/.zshrc`.
2. Restart zsh. Note that `source ~/.zshrc` does not restart zsh.
3. When `loading` appears, type `cat $GITSTATUS_DAEMON_LOG_POWERLEVEL9K $GITSTATUS_XTRACE_POWERLEVEL9K` and post the output here.

**Comment by mbwhite** [comment]
I restarted and everything came back... but thanks for the debug info.
Could be useful for the future.
