### ISSUE TITLE
Add gcloud project inside prompt

### ISSUE THREAD

**Issue by mehdicopter** [romkatv/powerlevel10k#366]
Hello,

How can I display the current project used inside gcloud context and display it into prompt ?

**Comment by romkatv** [comment]
What's gcloud context? How can you print it?

**Comment by mehdicopter** [comment]
`gcloud config get-value project`

**Comment by mehdicopter** [comment]
There is an example on this repo : https://github.com/ocadaruma/zsh-gcloud-prompt

**Comment by mehdicopter** [comment]
❤️

**Comment by romkatv** [comment]
This is done. After updating powerlevel10k, you can either run `p10k configure` and then uncomment `gcloud` in `~/.p10k.zsh` or manually add `gcloud` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. You can customize the format of `gcloud` prompt segment through `POWERLEVEL9K_GCLOUD_CONTENT_EXPANSION`. Here's the default:

```zsh
# Google cloud format. Edit the next line if the default is too verbose.
# Note: ${X//\%/%%} is the same as $X but with all occurences of % replaced with %%.
typeset -g POWERLEVEL9K_GCLOUD_CONTENT_EXPANSION='${P9K_GCLOUD_ACCOUNT//\%/%%}:${P9K_GCLOUD_PROJECT//\%/%%}'
```
