### ISSUE TITLE
Rainbow Style not displaying correctly.

### ISSUE THREAD

**Issue by ad1tyawagh** [romkatv/powerlevel10k#369]
Hi. I have used patched Consolas font (Consolas NF) in Windows Terminal. But the prompt doesn't show up properly.
I have the same issue even when I use the MesloLGS NF.
![problem](https://user-images.githubusercontent.com/25822972/70466288-c8b10280-1ae8-11ea-9b39-ecbd52773b7d.jpg)
As you can see, I am getting vertical bars on the prompt at multiple places. Any idea why this is happening?

**Comment by romkatv** [comment]
How these glyphs are rendered is defined by the combination of your terminal, terminal settings and font. If these one-pixel imperfections bother you, you can try the following:

1. Change your terminal font size. Try going one point up or one point down.
2. Try a different font.
3. Some terminals have settings that allow you to manually specify offset for glyphs. If your terminal has them, try moving glyphs one pixel left/right or up/down.
4. Edit the font manually with FontForge.
5. Use *Lean* prompt style.

**Comment by ad1tyawagh** [comment]
Thanks a lot.
