### ISSUE TITLE
aws and kubecontext not shown while using purepower

### ISSUE THREAD

**Issue by Moulick** [romkatv/powerlevel10k#37]
When using the `purepower mode`, the `aws` and `kubecontext` prompt segmets/elements don't show up. They are visible when not using the purepower in powerlevel10k. 

I would love to use purepower but this is a deal breaker for me.
I'll assist you in any way I can.

**Comment by romkatv** [comment]
Please post your config.

**Comment by romkatv** [comment]
Have you added `aws` and `kubecontext` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and/or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in your `~/.purepower`? If not, this is the problem. To change your Pure Power configuration you need to edit `~/.purepower`. This is the only place where you set `POWERLEVEL9K` parameters when using Pure Power. For every segment you want to add you need to set its background to none. To keep the minimalist style of Pure Power you should also set the icon to an empty string (in general, every segment should be either an icon without text or text without an icon). Configuration for the existing segments in `~/.purepower` will serve you as an example.

Here's how configuration for `aws` might look like:

```zsh
typeset -g POWERLEVEL9K_AWS_BACKGROUND=none
typeset -g POWERLEVEL9K_AWS_FOREGROUND=012
typeset -g POWERLEVEL9K_AWS_ICON=
```

You need to add it to `~/.purepower` and also add `aws` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` array in the same file.

**Comment by Moulick** [comment]
Ahh okay, so the settings need to be done directly in the `~/.purepower` file itself. I thought it'll pickup from `~/.zshrc`. I'll do this and get back to you

**Comment by Moulick** [comment]
Thanks, that fixes it.

**Comment by romkatv** [comment]
Glad to hear that!

**Comment by Moulick** [comment]
If you update this file and I fetch the new one, I'll loose all my changes :(

**Comment by Moulick** [comment]
@romkatv  

> typeset -g POWERLEVEL9K_AWS_BACKGROUND=none
  typeset -g POWERLEVEL9K_AWS_FOREGROUND=003
  typeset -g POWERLEVEL9K_AWS_ICON=

>  typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=none
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=009
  typeset -g POWERLEVEL9K_KUBECONTEXT_ICON=

These are the two blocks I have added, but now the problem is that `POWERLEVEL9K_KUBECONTEXT_ICON=''` dosen't work. I still see the icon.

**Comment by romkatv** [comment]
> If you update this file and I fetch the new one, I'll loose all my changes :(

Don't fetch a new one. This isn't code. It's just a config with decent defaults for new users. You really don't want your prompt to change whenever I change the default for new users. Keep your own copy with your own edits to have stable prompt.

> typeset -g POWERLEVEL9K_KUBECONTEXT_ICON=

It's `POWERLEVEL9K_KUBERNETES_ICON`.

**Comment by Moulick** [comment]
Okay,
Btw where did you find this `POWERLEVEL9K_KUBERNETES_ICON`? 
Thanks a lot

**Comment by romkatv** [comment]
I just read the code.

This configuration is identical in Powerlevel9k and Powerlevel10k, so it's possible there is documentation somewhere on https://github.com/bhilburn/powerlevel9k/ that says you need to define `POWERLEVEL9K_KUBERNETES_ICON` to override icon in `kubecontext` prompt segment. I just don't use it because it's easier for me to read code directly.

**Comment by Moulick** [comment]
Yeah, I looked through the documentation and didn't find that there. Anyways, Thanks for your help
