### ISSUE TITLE
Prompt mismatch when export LANG=C

### ISSUE THREAD

**Issue by madobet** [romkatv/powerlevel10k#371]
Just like this:
![screenshot.png](https://i.loli.net/2019/12/11/qRTUS6dxNmjsXHW.png)

This is my setting for powerlevel10k:
```
[ "${ZSH_THEME}" != "powerlevel10k/powerlevel10k" ] && return 0
# -----------------------------------------------------------------------------
# _sub_theme=classic
# _sub_theme=lean
# _sub_theme=pure
_sub_theme=rainbow
_theme_path="${ZSH_CUSTOM:?unset/empty}/themes/powerlevel10k/config/p10k-${_sub_theme}.zsh"

[ -s "$_theme_path" ] && . "$_theme_path"
```

I've tried to disable all plugins and removed my settings, but not worked.

**Comment by romkatv** [comment]
Yep, it's expected that zsh prompt breaks when you use non-utf-8 encoding and have Unicode characters in prompt. Either use utf-8 encoding, or restrict prompt characters to ascii.
