### ISSUE TITLE
node/nvm version behavior (only show when a package.json file is present and use the nvm version)

### ISSUE THREAD

**Issue by leeallen337** [romkatv/powerlevel10k#373]
I'm unsure if this is possible since there are multiple node settings. I've attached a gif.

![Kapture 2019-12-11 at 21 35 31](https://user-images.githubusercontent.com/10897808/70677943-9a553380-1c5e-11ea-9fee-2e299a2f63e9.gif)

In that `node-starter` directory there is a `package.json` file and it doesn't show the node version initially which I would expect since in the config this setting is set:
```
typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
```
However, only after I use `nvm use` (since there is an `.nvmrc) does it show the node version, and when I do an `nvm use default` it goes back to not showing it again. Also if I do an `nvm use` and then navigate out of that directory to a directory that doesn't have a `package.json` file it still shows the node version.

### What behavior I would like to happen:
It always, but only, shows the node version when the directory has a `package.json` file. If the directory does not have a `package.json` file then don't show any node information.

Thanks for this awesome theme!

**Comment by romkatv** [comment]
At the top of `~/.p10k.zsh` you can find the following definition:

```zsh
# The list of segments shown on the right.
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  ...
  nodenv          # node.js version from nodenv (https://github.com/nodenv/nodenv)
  nvm             # node.js version from nvm (https://github.com/nvm-sh/nvm)
  nodeenv         # node.js environment (https://github.com/ekalinin/nodeenv)
  # node_version  # node.js version
  ...
)
```

There are several prompt segments that refer to node.js version. The last segment -- `node_version` -- is essentially a wrapper around `node --version`. **Note that it's commented out (disabled).** The other prompt segments fetch node version from various node version managers.

Below this, there is one section for each prompt segment that defines parameters specifically for that segment. For example, here's what the config has for `node_version`.

```zsh
####################[ node_version: node.js version ]#####################
# Show node version only when in a directory tree containing package.json.
typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
...
```

`POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true` works just like you would expect. However, it has no effect if `node_segment` isn't enabled.

> ### What behavior I would like to happen:
> It always, but only, shows the node version when the directory has a `package.json` file. If the directory does not have a `package.json` file then don't show any node information.

You can achieve the desired behavior by uncommenting `node_version` and commenting out the other three node segments.

> Thanks for this awesome theme!

Thanks :hugs:

**Comment by leeallen337** [comment]
This worked exactly like you said! Thanks 🙏

**Comment by romkatv** [comment]
Thanks for the confirmation.

**Comment by TimJi** [comment]
![螢幕錄製 2021-02-05 上午10 36 17](https://user-images.githubusercontent.com/11478166/106984255-2d75f480-67a2-11eb-917f-976579f3dda9.gif)
