### ISSUE TITLE
icon behavior when resizing terminal window

### ISSUE THREAD

**Issue by leeallen337** [romkatv/powerlevel10k#376]
I'm encountering weird behavior when I resize my terminal window. I've attached a gif of the behavior below. Most of the time I keep my terminal maximized so this isn't really a huge issue. 

When this does happen I can just do `ctrl+l` or enter `clear` and I have all the icons out of my screen. Although if I scroll up I obviously still see it. I never used powerleve9k so I don't know if this existed before.

Have you encountered this before?

Thanks!

![Kapture 2019-12-14 at 16 45 14](https://user-images.githubusercontent.com/10897808/70854973-454d3380-1e91-11ea-89a6-d16fa40f96ae.gif)

**Comment by romkatv** [comment]
It's not in my power to fix this. See https://github.com/romkatv/powerlevel10k/issues/175.

**Comment by leeallen337** [comment]
Thanks for the link with the explanation. i was sure I wasn't the only one and I had tried to search but couldn't find anything. It's good to know it doesn't affect left only themes.
