### ISSUE TITLE
Misaligned Icons on VS Code Terminal

### ISSUE THREAD

**Issue by menjilx** [romkatv/powerlevel10k#377]
Hi,
Did anyone experience this bug on the VS code terminal on MAC?
![image](https://user-images.githubusercontent.com/14908836/70857279-4aa88d80-1f26-11ea-9034-e2a4cf9edc73.png)

Thank you

**Comment by menjilx** [comment]
And is there a way to change the "blue" background color to something else?

**Comment by romkatv** [comment]
> Did anyone experience this bug on the VS code terminal on MAC?

How these glyphs are rendered is defined by the combination of your terminal, terminal settings and font. If these one-pixel imperfections bother you, you can try the following:

1. Change your terminal font size. Try going one point up or one point down.
2. Try a different font.
3. Some terminals have settings that allow you to manually specify offset for glyphs. If your terminal has them, try moving glyphs one pixel left/right or up/down.
4. Edit the font manually with FontForge.
5. Use *Lean* prompt style.

> And is there a way to change the "blue" background color to something else?

Yes. Open `~/.p10k.zsh` search for `POWERLEVEL9K_DIR_BACKGROUND` and change its value. Use the following command to see how colors with different codes look like:

```zsh
for i in {0..255}; do print -Pn "%${i}F${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'}; done
```

(This command is listed at the top of `~/.zshrc`.)

**Comment by menjilx** [comment]
Thank you @romkatv  will try this guide.
