### ISSUE TITLE
Powerlevel10k with sshrc

### ISSUE THREAD

**Issue by mariusz-zawadzki** [romkatv/powerlevel10k#378]
I have a question:

What is the minimal set of files required by Powerlvel10k template to work?
I would like to use this theme with 'sshrc' which has a limitation on size of files used to init a console (it copies some local files to be used on remote machine).

I was able to limit .oh-my-zsh  files and I would like to do the same with this theme.

**Comment by romkatv** [comment]
What is a Powerlevel10k template?

**Comment by mariusz-zawadzki** [comment]
*Theme not template I was thinking about this theme.

I like the customisation it proviedes And I wonder how to shirnk it's size.

I wonder for example if I can get rid of 'gitstatus' - I can live without it on remote env.

**Comment by romkatv** [comment]
> I wonder for example if I can get rid of 'gitstatus' - I can live without it on remote env.

Try it and see what happens.

This sort of trimming down of internal files is obvious unsupported, so you are on your own. A supported alternative would be adding something like this to `~/.sshrc`:

```zsh
if [[ -d ~/powerlevel10k ]]; then
  git -C ~/powerlevel10k pull
else
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
fi
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

**Comment by mariusz-zawadzki** [comment]
Thank you for the quickest response I ever got.

I will try trimming the gitstatus. The alternative would be great if hosts I ssh were long lived.

Thanks again!

**Comment by romkatv** [comment]
Note that it may be very difficult for you to update powerlevel10k after this kind of trimming. You'll either be stuck with the current version, or will have to manually merge all changes.
