### ISSUE TITLE
powerlevel10k.zsh-theme:1: command not found: powerlevel9k.zsh-theme

### ISSUE THREAD

**Issue by the-blank-x** [romkatv/powerlevel10k#38]
Distro: UPupBB
zsh: 5.4.2

When I `source /mnt/home/stuff/ztuff/powerlevel10k/powerlevel10k.zsh-theme`, I get:
`/mnt/home/stuff/ztuff/powerlevel10k/powerlevel10k.zsh-theme:1: command not found: powerlevel9k.zsh-theme`

**Comment by romkatv** [comment]
I'll need a bit more info to debug this.

1. What does `ls -l /mnt/home/stuff/ztuff/powerlevel10k` say?
2. How did you install Powerlevel10k?

**Comment by the-blank-x** [comment]
1. `total 160
-rwxr-xr-x 1 root root 13240 Mar 24 11:26 demo.png
-rwxr-xr-x 1 root root  4373 Mar 24 11:26 EXTENDED_CONFIGURATION.md
drwxr-xr-x 2 root root  4096 Mar 24 11:26 functions
drwxr-xr-x 3 root root  4096 Mar 24 11:26 gitstatus
-rwxr-xr-x 1 root root  1277 Mar 24 11:26 LICENSE
-rwxr-xr-x 1 root root    22 Mar 24 11:26 powerlevel10k.zsh-theme
-rwxr-xr-x 1 root root 89431 Mar 24 11:26 powerlevel9k.zsh-theme
-rwxr-xr-x 1 root root  6142 Mar 24 11:26 prompt.png
-rwxr-xr-x 1 root root    25 Mar 24 11:26 prompt_powerlevel10k_setup
-rwxr-xr-x 1 root root    22 Mar 24 11:26 prompt_powerlevel9k_setup
-rwxr-xr-x 1 root root 13590 Mar 24 11:26 README.md`
2. By running `git clone https://github.com/romkatv/powerlevel10k /mnt/home/stuff/ztuff/powerlevel10k` and adding `source /mnt/home/stuff/ztuff/powerlevel10k/powerlevel10k.zsh-theme` into .zshrc

**Comment by romkatv** [comment]
Looks like your `/mnt/home` partition doesn't support symbolic links. It also screwed up all permissions. You'll need to `git clone` to a posix-compliant filesystem.

**Comment by the-blank-x** [comment]
Thanks, that fixed the problem.
