### ISSUE TITLE
P10k New config

### ISSUE THREAD

**Issue by dennisvera** [romkatv/powerlevel10k#381]
Hello Roman, first, thank you for such a clean and beautiful theme. loving it. 
I am having this issue with the config, I have set the pk10 config to my fav style (lean) and it looks great, but every timeI quit iTerm2 i see a different style (rainbow). Why is the config changing every time I quit and reopen iTerm2?
thanks!

**Comment by romkatv** [comment]
Please attach `~/.zshrc` and `~/. p10k.zsh`.

**Comment by dennisvera** [comment]
@romkatv what do you mean by attach? 
I have previously updated the `~/.zshrc` file to run the pk10 theme, and configured the `~/.p10k.zsh` several times.

**Comment by romkatv** [comment]
Please attach the files to this issue so that I can see their content.

**Comment by dennisvera** [comment]
[ohmyzh.txt](https://github.com/romkatv/powerlevel10k/files/3974820/ohmyzh.txt)


[p10k.txt](https://github.com/romkatv/powerlevel10k/files/3974822/p10k.txt)

**Comment by romkatv** [comment]
At the bottom of `~/.zshrc` you have the following line:

```zsh
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fisource ~/powerlevel10k/powerlevel10k.zsh-theme
```

It causes zsh to bail out with syntax error. You need to replace this line with this:

```zsh
(( ! $+commands[rbenv] )) || eval "$(rbenv init -)"
```

**Comment by dennisvera** [comment]
@romkatv that worked! thank you 🙏

**Comment by romkatv** [comment]
Thanks for the confirmation.

**Comment by romkatv** [comment]
I've added an entry to the FAQ: https://github.com/romkatv/powerlevel10k#why-does-the-configuration-wizard-run-automatically-every-time-i-start-zsh.
