### ISSUE TITLE
Clipping Graphics - VSCode Terminal

### ISSUE THREAD

**Issue by EigenTheory** [romkatv/powerlevel10k#382]
I realize this is VSCode specific, but I have been unable to find a solution elsewhere. I have tried all of the fonts from Nerd Fonts and all other patched fonts I could find. The tops of my rows are being clipped in VSCode, and this doesn't happen with agnoster and powerline fonts. I have tried adjusting the font size, line spacing, and ligatures to no avail. Any help would be greatly appreciated...

<img width="363" alt="clipping" src="https://user-images.githubusercontent.com/1594192/71023809-20db9c00-20c9-11ea-892f-0ed45e312e9e.png">

**Comment by romkatv** [comment]
Yep, that looks like an issue with line spacing. Please ask on VS Code forums for help with this.
