### ISSUE TITLE
New line now appearing after ruler?

### ISSUE THREAD

**Issue by lucascosti** [romkatv/powerlevel10k#383]
Since a few months ago, I noticed that I am now seeing a blank new line _after_ the ruler.

I do have `POWERLEVEL9K_PROMPT_ADD_NEWLINE=true` which sets a new line _before_ the ruler, but now I am also seeing a new line after the ruler.

Stepping back through the powerlevel10k commits on master:
* https://github.com/romkatv/powerlevel10k/commit/2aca13130aa40a2dd407327b6601001d6707e577 Does not have a new line after the ruler (as expected)

  
![p10k2aca1313-nonewline](https://user-images.githubusercontent.com/4434330/71046515-44afe800-2184-11ea-9fe4-3d936139258a.png)

* The following commit https://github.com/romkatv/powerlevel10k/commit/123cf5f6766aa969b3fdce11100f2ac1575bd1d6 does have a new line after the ruler. 

![p10k123cf5f6-newline](https://user-images.githubusercontent.com/4434330/71046534-51344080-2184-11ea-8c6d-6e50d447441e.png)

~~I can't see anything obvious in that commit that might be causing it...~~ Edit: actually, it looks like this is where the dynamic branch stuff was merged in, so I think it might have something to do with it 🙂 

If a blank new line after the ruler is the intended functionality, is it possible to have that as a configurable option?

Here is my theme: https://github.com/lucascosti/zshrc/blob/master/zshscripts/themes/p10k-lucas.zsh
OS: macOS 10.15.2
Terminal: iTerm2 3.3.7

Thank you!

**Comment by romkatv** [comment]
Thanks for the bug report! Fixed.

By the way, few people use ruler nowadays because "prompt gap" seems to work better. You can try it by defining the following parameters:

```zsh
# Filler between left and right prompt on the first prompt line. You can set it to '·' or '─'
# to make it easier to see the alignment between left and right prompt and to separate prompt
# from command output. It serves the same purpose as ruler without increasing the number of
# prompt lines. You'll probably want to set POWERLEVEL9K_SHOW_RULER=false if using this.
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='─' # good alternative: '·'
# The color of the filler.
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=240
# End filler on the edge of the screen if there are no right segments on the first line.
typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
```

You'll probably want to disable ruler while trying this.

That dynamic stuff that you correctly identified as the culprit of the bug might also be useful to you. You can try it with this parameter:

```zsh
# Transient prompt works similarly to the builtin transient_rprompt option. It trims down prompt
# when accepting a command line. Supported values:
#
#   - off:      Don't change prompt when accepting a command line.
#   - always:   Trim down prompt when accepting a command line.
#   - same-dir: Trim down prompt when accepting a command line unless this is the first command
#               typed after changing current working directory.
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
```

I also recommend adding this at the bottom to speed up prompt a little bit.

```zsh
# Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
# For example, you can type POWERLEVEL9K_BACKGROUND=red and see your prompt turn red. Hot reload
# can slow down prompt by 1-2 milliseconds, so it's better to keep it turned off unless you
# really need it.
typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

# If p10k is already loaded, reload configuration.
# This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
(( ! $+functions[p10k] )) || p10k reload
```

If you'd like zsh to start faster, try [instant prompt](https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-instant-prompt).

**Comment by lucascosti** [comment]
Thanks for the fix and the tips! I'll check them out 😃
