### ISSUE TITLE
Some strange ?86 or ?87 symbols at prompt in home directory.

### ISSUE THREAD

**Issue by kasuskasus1** [romkatv/powerlevel10k#385]
Strangely seeing the following "?87" symbol at the end of the prompt. 
<img width="697" alt="Screenshot 2019-12-19 at 11 24 46" src="https://user-images.githubusercontent.com/9466135/71157210-9b83f300-2252-11ea-9d04-390aa8f71848.png">

`get_icon_names` lists all icons. What is this?

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-do-i-have-a-question-mark-symbol-in-my-prompt-is-my-font-broken

**Comment by kasuskasus1** [comment]
Thank you, sorry for dumb question, but hopes this helps someone in future!

**Comment by romkatv** [comment]
By the way, if you don't want to see Git status in your prompt while in home directory, add this parameter to `~/.p10k.zsh`:

```zsh
# Don't display Git status in prompt for Git repositories whose workdir matches
# this pattern.
typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
```
