### ISSUE TITLE
Openbsd

### ISSUE THREAD

**Issue by ralphee** [romkatv/powerlevel10k#386]
experience the following error with openbsd http://ix.io/24Rf

**Comment by romkatv** [comment]
There is no prebuilt gitstatusd binary for OpenBSD. I only provide binaries for popular operating systems and OpenBSD didn't make the cut.

There are a few things you can try:

1. Build gitstatusd yourself. It's not too difficult. See https://github.com/romkatv/gitstatus/blob/master/README.md#compiling.
2. Add `POWERLEVEL9K_DISABLE_GITSTATUS=true` to your `~/.zshrc`. It'll get rid of the error message when starting zsh but your prompt will be **much** slower than it normally is, especially when your current directory is inside a Git repository.
