### ISSUE TITLE
zsh quick installation: command not found: prompt_powerlevel9k_setup

### ISSUE THREAD

**Issue by maurycyg** [romkatv/powerlevel10k#387]
I've fresh installation of zsh 5.7.1 (x86_64-apple-darwin18.2.0) 

Followed the install instructions:
```
Oh My Zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
Set ZSH_THEME=powerlevel10k/powerlevel10k in your ~/.zshrc.
```

but when I try to initialise it I'm presented with this error
```
~|⇒ source ~/.zshrc
(anon):4: command not found: prompt_powerlevel9k_setup
~|⇒
```

I'm missing anything?

**Comment by romkatv** [comment]
What happens if you restart zsh?

**Comment by maurycyg** [comment]
Nothing was happening, I've eventually installed it with the manual method and that prompted the wizard

**Comment by romkatv** [comment]
Does this mean the issue is resolved or are you still seeing this error?

**Comment by maurycyg** [comment]
I think it's resolved as it is now, I can try and reproduce it later

**Comment by romkatv** [comment]
I'm glad it's working now for you.
