### ISSUE TITLE
Feature: More options for transient prompt

### ISSUE THREAD

**Issue by booch** [romkatv/powerlevel10k#389]
I just installed and configured the theme. It's great, but I was expecting something different from the examples shown when configuring the transient prompt. I expected the prompt to only show up if there was any output from the previous command.

I thought it would be really neat to add a mode to match my expectations. Unfortunately, it's not terribly easy for ZSH to determine the number of lines of output. There's https://unix.stackexchange.com/a/117109, but I don't know how feasible that would be.

Another option (that would have also met my expectations) would be to make the prompt transient only if the previous command ran for less than _n_ seconds.

I'm interested in your feedback on these ideas. I can try to create a PR, if you think either of these might be worth adding.

**Comment by romkatv** [comment]
> I expected the prompt to only show up if there was any output from the previous command.

I'm pretty sure this is impossible.

It's also unclear how useful it would be. Isn't it nice to see which commands you've just timed and whether they succeeded or not, even if they produced no output? I find it valuable.

> Another option (that would have also met my expectations) would be to make the prompt transient only if the previous command ran for less than n seconds.

I'm afraid this is also impossible.

You are correct that to implement any of these ideas it's necessary to know when a command that has just been executed has moved cursor and/or scrolled the terminal window. Unfortunately, neither of these are possible to do on the level of shell. The standard TTY protocol doesn't have support for this. If you are OK with a solution that requires a custom terminal, then it's possible. There is no terminal that I know of that already supports this but it's in theory possible to either fork and modify an existing terminal, or write a new terminal from scratch that has this capability.

**Comment by booch** [comment]
Thanks for the feedback, @romkatv. I thought it would be easy to get the execution time from `P9K_COMMAND_DURATION_SECONDS`, which we're already capturing at https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh#L4377.

**Comment by romkatv** [comment]
Perhaps I didn't understand your time-based suggestion. Suppose the full prompt looks like this:

```text
~/work ❯
```

Suppose we run these commands:

- `sleep 1`
- `sleep 3`
- `sleep 1`
- `sleep 3`

Finally, let's suppose that the cutoff for time-based transient prompt is 2 seconds.

How should the terminal window look like after all these commands have been executed?

**Comment by booch** [comment]
I was thinking it'd look like this (based on the Enable Transient Prompt? from the wizard):

```
❯ sleep 1
❯ sleep 3
 ~/src  master ▓▒░·········································░▒▓ 3s  16:23:42 
❯ sleep 1
❯ sleep 3
 ~/src  master ▓▒░·········································░▒▓ 3s  16:23:46 
```

I suspect I might not be quite understanding how transient is meant to work though.

**Comment by romkatv** [comment]
I'll change your rendering of the terminal window to make it simper. As I noted above, `~/work ❯` is the full prompt.

```text
~/work ❯ sleep 1
❯ sleep 3
~/work ❯ sleep 1
❯ sleep 3
~/work ❯ █
```

Is this what you want?

This is possible to implement. This is actually already implemented, so you can have this behavior by tweaking your configuration. May I ask why would you want this?

FWIW, the regular transient mode looks like this: [demo](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif). It's quite intuitive.

**Comment by booch** [comment]
Yeah, I think the transient mode probably isn't the right tool for what I was thinking. (It's a really cool idea, just different than the use case I was thinking of.) I think what I'm looking for would more appropriately be called a "conditional prompt" - where I get the full prompt in some situations, but a single-line simple prompt otherwise.

I use prompts with a background color that stands out to make it easier to see where each command was run when I scroll back in my terminal buffer history. But if I'm running commands without any output, I don't need all the extra separation.

I just switched over from 30 years of Bash, so I'm not quite familiar with Zsh and what tools it makes available. Honestly, just having the duration of the previous command in my prompt is already a big win. And having a consistent prompt is probably best, since we can't get the terminal to tell the shell how much output there was.

I'm not giving up 100% on the "no output" idea, but I realize that it'd be a multi-year effort to get all the major terminal 

I use prompts with a background color that stands out to make it easier to see where each command was run when I scroll back in my terminal buffer history. But if I'm running commands without any output, I don't need all the extra separation.

I just switched over from 30 years of Bash, so I'm not quite familiar with Zsh and what tools it makes available. Honestly, just having the duration of the previous command in my prompt is already a big win. And having a consistent prompt is probably best, since we can't get the terminal to tell the shell how much output there was.

I'm not giving up 100% on the "no output" idea, but I realize that it'd be a multi-year effort to get all the major terminal emulators to implement a feature to report how much output there was since the last query. (It'd have to be something like the Answerback or Report Cursor Position escape sequence.) It worked from Bracketed Past Mode, but that's probably more useful than my idea. 🤷‍♂

Thanks for the feedback and all your hard work on the theme and the wizard.

**Comment by romkatv** [comment]
> I think what I'm looking for would more appropriately be called a "conditional prompt" - where I get the full prompt in some situations, but a single-line simple prompt otherwise.

That's pretty much what p10k provides. There is an API that allows you to specify which prompt you want to be left behind every time you hit `enter`. When you enable transient prompt, it uses this generic mechanism to say *always replace prompt with `❯` when I hit `enter`*. You can use any condition you like, and specify any prompt you like.

> But if I'm running commands without any output, I don't need all the extra separation.

The problem is that you cannot use "without any output" as a condition.

Also, as I noted earlier, if this was possible, it's unlikely to be useful to you. There is no reasonable explanation why commands without output should shorten prompts while commands with output shouldn't.

**Comment by one000mph** [comment]
Hi @romkatv thanks for building such an awesome tool. I was wondering today if it's possible to trim the transient prompt down to just the `time` + `prompt_char`. I've tried a couple things but so far it hasn't worked. 
I was intrigued by what you said above
> always replace prompt with ❯ when I hit enter.
Is there documentation on how to customize this so I can get more than _just_ the prompt in past commands?

**Comment by romkatv** [comment]
@one000mph There is still no official documentation even though this feature is stable and supported. See https://github.com/romkatv/powerlevel10k/issues/316#issuecomment-551867287 for some info that should get you started.

**Comment by romkatv** [comment]
@one000mph This config does something similar to what you are asking: https://github.com/hipstersmoothie/dotfiles/blob/master/.p10.zsh.
