### ISSUE TITLE
Git status is very slow

### ISSUE THREAD

**Issue by qazip** [romkatv/powerlevel10k#39]
Hello there,

I've been using powerlevel10k for a few weeks now and I suddenly noticed that git status is very slow on a git folder I have. The coloring of the git status takes a few seconds to turn to orange (it stays grey for a few seconds). I remember testing powerlevel10k in this very same folder and it behaved ok. 

Other zsh themes are instant, such as "minimal" or "awesomepanda" or the likes. Did you make any changes to that recently?

**Comment by romkatv** [comment]
Ouch, that sucks. Several seconds is definitely more than you should have on any repo.

Is it slow everywhere or just in that repo? For example, if you go to the directory of powerlevel10k itself, is it fast or slow?

Is your git repo public? It would help tremendously if I could reproduce this.

Have you built gitstatusd yourself or are you using the bundled version from powerlevel10k?

What does `time git status` say in the same directory?

**Comment by romkatv** [comment]
Also please run this in the directory where git status is slow and post the results here:

```zsh
gitstatus_query POWERLEVEL9K && set | egrep '^VCS_STATUS'
```

**Comment by qazip** [comment]
@romkatv, I don't know how to explain this but... It is behaving correctly now. What the hell.

Really sorry, I have no idea what happened. I will close this and re-open if it ever happens again. Thanks for the great work btw!

**Comment by romkatv** [comment]
If this happens again, please perform the tests I've listed here: check the time of `git status`, check whether it's slow in other git repos, etc.

**Comment by qazip** [comment]
It happened again:
```
time git status
git status 0.82s user 0.06s system 98% cpu 0.893 total
```

But now it's back to normal so I can't check. I'll try to reproduce somehow, might be due to disk usage.. Btw, I'm using powerlevel10k from AUR.

**Comment by romkatv** [comment]
I just pushed a new release with a lot of changes. It may or may not help, but either way it's better to update your p10k.
