### ISSUE TITLE
[ER] show exit code ($?) if non-zero

### ISSUE THREAD

**Issue by gibfahn** [romkatv/powerlevel10k#393]
It's useful to have the prompt go red when the return code is non-zero, but it's even more useful to be able to easily know what the exit code was, for programs that use this to differentiate between failure modes, e.g. [bazel](https://docs.bazel.build/versions/master/guide.html#what-exit-code-will-i-get).

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and fine these lines:

```zsh
# Status when it's just an error code (e.g., '1'). No need to show it if prompt_char is enabled as
# it will signify error by turning red.
typeset -g POWERLEVEL9K_STATUS_ERROR=false
```

Replace `false` with `true`.

**Comment by gibfahn** [comment]
Works perfectly. I failed to read the config properly, sorry for the noise, and thanks for a great prompt!

**Comment by romkatv** [comment]
You are very welcome.

**Comment by kpal99** [comment]
# Status when it's just an error code (e.g., '1'). No need to show it if prompt_char is enabled as
# it will signify error by turning red. 

In case of error, I don't want prompt_char to turn red, instead white (on black background).
How can I do that. 
Thanks in advance.

**Comment by romkatv** [comment]
@kpal99 https://github.com/romkatv/powerlevel10k#how-do-i-change-prompt-colors
