### ISSUE TITLE
git indicator is greyed out indefinitely

### ISSUE THREAD

**Issue by marekdedic** [romkatv/powerlevel10k#394]
Hi,
when I navigate into a newly opened git repo, the git indicator remains greyed out indefinitely on the first line. When I press enter, on the new line it goes from grey to color almost instantly. I expect this to be the behaviour on the first line as well...

![Screenshot from 2019-12-25 12-21-33](https://user-images.githubusercontent.com/3134692/71444463-a090e880-2711-11ea-9dae-451470937ddf.png)

**Comment by romkatv** [comment]
This is a bug in zsh that has since been fixed. See https://github.com/romkatv/powerlevel10k/issues/326#issuecomment-553866148.

**Comment by marekdedic** [comment]
Oh, ok, so I just need to wait for the next ZSH version (not bothering me enough to build use master :) ). Thanks.

**Comment by romkatv** [comment]
The next release of zsh is right around the corner. It's currently being tested.
