### ISSUE TITLE
Allow showing delta from @{push} as well as @{upstream}

### ISSUE THREAD

**Issue by gibfahn** [romkatv/powerlevel10k#395]
Requires https://github.com/romkatv/gitstatus/issues/89

This would be really useful for the reasons I went into [here](https://fahn.co/posts/a-better-pull-request-workflow-with-git-push-branches.html), basically because it makes things much simpler when using the GitHub Pull Request workflow.

### Workaround

In case this is useful to anyone else, I currently work around it by adding the following lines to my `p10k.zsh`:

```sh

    local -a push_behind_ahead=(${(ps:\t:)"$(command git rev-list --left-right --count HEAD...@{push} 2>/dev/null)"})
    local VCS_STATUS_PUSH_COMMITS_AHEAD="${push_behind_ahead[1]}"
    local VCS_STATUS_PUSH_COMMITS_BEHIND="${push_behind_ahead[2]}"

    # ⇠42 if behind the @{push} branch.
    (( VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" ${clean}⇠${VCS_STATUS_PUSH_COMMITS_BEHIND}"
    (( VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND )) && res+=" "
    # ⇢42 if ahead of the @{push} branch; no leading space if also behind: ⇠42⇢42.
    (( VCS_STATUS_PUSH_COMMITS_AHEAD  )) && res+="${clean}⇢${VCS_STATUS_PUSH_COMMITS_AHEAD}"

```

You want to add them under this line:

```sh
    (( VCS_STATUS_COMMITS_AHEAD  )) && res+="${clean}⇡${VCS_STATUS_COMMITS_AHEAD}"
```

I tried to make it match the existing code as much as possible, to the point where if the gitstatus PR was shipped and the variables defined, in theory the second chunk could be PR'd directly against the repo.

**Comment by romkatv** [comment]
This is done.

**Comment by gibfahn** [comment]
Updated and tried this and it works perfectly, thanks!
