### ISSUE TITLE
zsh-vim-mode compatibility

### ISSUE THREAD

**Issue by CallumHoward** [romkatv/powerlevel10k#396]
Hello, thank you very much for this fast and powerful theme, I switched to p10k a few months back and have been loving it.
I switched from a minimal theme that I had customised quite a lot. I liked the look so I ported it over to p10k so it looks practically identical.

In my old theme I had this plugin: https://github.com/softmoth/zsh-vim-mode
With this config:
```zsh
MODE_INDICATOR_VIINS='%B%K{2}%F{15} INSERT %f%k%b'
MODE_INDICATOR_VICMD='%B%K{4}%F{15} NORMAL %f%k%v'
MODE_INDICATOR_REPLACE='%B%K{1}%F{15} REPLACE %f%k%b'
MODE_INDICATOR_SEARCH='%B%K{2}%F{15} SEARCH %f%k%b'
MODE_INDICATOR_VISUAL='%B%K{9}%F{15} VISUAL %f%k%b'
MODE_INDICATOR_VLINE='%B%K{9}%F{15} V-LINE %f%k%b'
```
Which looked like this:
![Screen Recording 2019-12-27 at 8 59 19 am 2019-12-27 09_04_46](https://user-images.githubusercontent.com/7144420/71491961-f8516000-2887-11ea-82fe-bb9a6d36c3d6.gif)

The reasons why I would like to use this plugin over the inbuilt `POWERLEVEL9K_PROMPT_CHAR`:
1. It has VLINE and SEARCH modes
2. It can be put in the right prompt
3. Using `setopt transientrprompt`, the indicator is only shown on the current line, it is removed before executing the line.
4. The plugin also offers some other nice features such as cursor styling and surround key bindings

I tried to replicate this in my `.p10k.zsh` [here](https://github.com/CallumHoward/dotfiles/commit/7664b256bac1f3e5cd7fddb207e94e015adc7eb0), however it seems like this custom prompt segment doesn't update when changing modes.

The plugin readme mentions using `setopt prompt_subst` and then adding a correctly quoted `${MODE_INDICATOR_PROMPT}` to the prompt string. I have tried every quoting style I can think of to no avail.

So the question for my issue is:
- Can you see how I can make this work with p10k?
- Or otherwise is it possible to make them compatible?
- Or can I make a custom prompt element with `$VIM_MODE_KEYMAP` (which the plugin sets) and have it update on mode change?

Btw, I had to comment this line from the plugin.
https://github.com/softmoth/zsh-vim-mode/blob/master/zsh-vim-mode.plugin.zsh#L12

`.p10k`: https://github.com/CallumHoward/dotfiles/blob/master/.p10k.zsh
dotfiles: https://github.com/CallumHoward/dotfiles

**Comment by romkatv** [comment]
There is `vi_mode` in p10k. Here are sample settings for it:

```zsh
POWERLEVEL9K_VI_INSERT_MODE_STRING=INSERT
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND=blue
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=white

POWERLEVEL9K_VI_COMMAND_MODE_STRING=NORMAL
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=blue
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND=white

POWERLEVEL9K_VI_VISUAL_MODE_STRING=VISUAL
POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND=blue
POWERLEVEL9K_VI_MODE_VISUAL_FOREGROUND=white

POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=OVERTYPE
POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND=blue
POWERLEVEL9K_VI_MODE_OVERWRITE_FOREGROUND=white
```

It doesn't have `VLINE` and `SEARCH` modes but these can be added. It also doesn't change your cursor and I don't want to add it because it's impossible to implement so that it works consistently.

You can put it in right prompt and it works with `transient_rprompt`. Note that in p10k you have full control over which parts of your prompt get hidden when you press enter. It can be full right prompt (the same as `transient_rprompt` option), some parts of right prompt, some parts of left prompt, etc. See [demo](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif).

> Can you see how I can make this work with p10k?
> Or otherwise is it possible to make them compatible?

Dunno, I haven't looked at it.

**Comment by CallumHoward** [comment]
Thanks for the fast response, I'll give that a try.

**Comment by CallumHoward** [comment]
That worked great for what I wanted, I wasn't too fussed about dynamic cursor anyhow, but I wanted the extended vim text object support and vim surround, which seems to work if I load the plugin. Thanks again!
