### ISSUE TITLE
consider adding a github sponsor button or patreon

### ISSUE THREAD

**Issue by AlJohri** [romkatv/powerlevel10k#397]
This project is pretty amazing! You should consider adding a [Github Sponsor Button](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) or [Patreon](https://www.patreon.com/) to support this work. Thanks!

**Comment by romkatv** [comment]
> This project is pretty amazing!

Thank you for the kind words! Your expression of gratitude is more than enough compensation for my work.
