### ISSUE TITLE
A confused things with me? pls help me

### ISSUE THREAD

**Issue by sukai-cheng** [romkatv/powerlevel10k#398]
I just want to know what it is?
![avatar](https://chengsukai.oss-cn-hangzhou.aliyuncs.com/%E5%8D%9A%E5%AE%A2/%E5%9B%BE%E7%89%87/p10k.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean.
