### ISSUE TITLE
git icon not changing depending on platform

### ISSUE THREAD

**Issue by kariasbolster** [romkatv/powerlevel10k#399]
Hi the git icon doesn't seem to change depending on which platform.

**Comment by romkatv** [comment]
Please post the output of `git remote -vv`, a screenshot, and a description of what you think is wrong on the screenshot.

**Comment by kariasbolster** [comment]
<img width="990" alt="Screen Shot 2019-12-28 at 12 34 16 AM" src="https://user-images.githubusercontent.com/16870304/71524922-8837ee00-290a-11ea-9ab2-bae5068f55eb.png">

As you can see the the git platform is gitlab but the icon is showing `POWERLEVEL9K_VCS_GIT_ICON=$'\uF113 '`
instead of
`POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$'\uF296 '`

**Comment by kariasbolster** [comment]
<img width="858" alt="Screen Shot 2019-12-28 at 12 46 56 AM" src="https://user-images.githubusercontent.com/16870304/71525304-11035980-290c-11ea-9c9d-72d73a3af1be.png">

You can see that git platform is gitlab but the icon being displayed is the default git icon `POWERLEVEL9K_VCS_GIT_ICON=$'\uF113 '` instead of the gitlab icon `POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$'\uF296 '`

**Comment by romkatv** [comment]
Thank you. Please post the output of the following command while being in the same directory as earlier:

```zsh
typeset -m 'POWERLEVEL9K_*|ZSH_VERSION|GITSTATUS_*|VCS_STATUS_*'
```

**Comment by kariasbolster** [comment]
Hi @romkatv 

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon user context dir vcs )
GITSTATUS_DAEMON_PID_POWERLEVEL9K=66206
VCS_STATUS_COMMITS_AHEAD=0
VCS_STATUS_COMMITS_BEHIND=0
ZSH_VERSION=5.7.1
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=' '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=' '
VCS_STATUS_TAG=''
VCS_STATUS_REMOTE_NAME=''
VCS_STATUS_NUM_STAGED=0
VCS_STATUS_HAS_UNTRACKED=0
VCS_STATUS_NUM_UNTRACKED=0
VCS_STATUS_RESULT=ok-async
VCS_STATUS_STASHES=23
VCS_STATUS_INDEX_SIZE=448
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_NUM_UNSTAGED_DELETED=0
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=' '
VCS_STATUS_WORKDIR=<dir>
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_NUM_UNSTAGED=0
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status root_indicator background_jobs history ram disk_usage battery time )
VCS_STATUS_ACTION=''
VCS_STATUS_LOCAL_BRANCH=DP-1622
VCS_STATUS_REMOTE_BRANCH=''
POWERLEVEL9K_VCS_GIT_ICON=' '
VCS_STATUS_NUM_STAGED_DELETED=0
POWERLEVEL9K_MODE=nerdfont-complete
GITSTATUS_XTRACE_POWERLEVEL9K=/dev/null
VCS_STATUS_COMMIT=4afcd4e310f3ea3405c543d25dbb59e444811d7b
VCS_STATUS_REMOTE_URL=''
VCS_STATUS_NUM_STAGED_NEW=0
VCS_STATUS_HAS_CONFLICTED=0
GITSTATUS_DAEMON_LOG_POWERLEVEL9K=/dev/null
VCS_STATUS_HAS_STAGED=0

**Comment by romkatv** [comment]
> `VCS_STATUS_REMOTE_NAME=''`

For some reason gitstatusd thinks there is no remote.

What is the output of the following command when ran in the same directory?

```zsh
() {
  emulate -L zsh -o err_return -o xtrace -o no_unset
  git rev-parse --abbrev-ref --symbolic-full-name @{u}
  local ref
  ref=$(command git symbolic-ref -q HEAD)
  local -a remote
  remote=($(command git for-each-ref --format='%(upstream:remotename) %(refname)' $ref))
  typeset -p ref remote
  git remote get-url $remote[1]
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    zsh -dfeic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
      gitstatus_query -p MY
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    rm -rf $tmp
  }
}
```

**Comment by kariasbolster** [comment]
```
+(anon):2> git rev-parse --abbrev-ref --symbolic-full-name '@{u}'
fatal: no upstream configured for branch 'DP-1622'
```

**Comment by romkatv** [comment]
Thanks, this explains it.

`POWERLEVEL9K_VCS_GIT_GITLAB_ICON` is displayed when the current branch's upstream is on gitlab.com. This icon lets you know that commands such as `git push` and `git pull` will talk to gitlab.com. Since your branch has no upstream, `git push` and `git pull` don't talk to anything, and p10k displays the generic `POWERLEVEL9K_VCS_GIT_ICON` icon.

**Comment by romkatv** [comment]
You can set upstream to `origin/DP-1622` with this command:

```zsh
git branch -u origin/DP-1622
```

**Comment by kariasbolster** [comment]
@romkatv Thank you very much.

**Comment by romkatv** [comment]
By the way, you might want to run `p10k configure`.
