### ISSUE TITLE
Is there an option to move python virtualenv before current directory?

### ISSUE THREAD

**Issue by Ambro17** [romkatv/powerlevel10k#401]
I didn't find the docs so i don't know if it's possible. This themes to be the best theme i tried until now, but i'm too used to read the active venv on the left side of my prompt.

Thanks in advance

**Comment by romkatv** [comment]
> I didn't find the docs...

Ouch! This hurts more than I thought it would. From the [Configuration](https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration) section of the home page:

> You can further customize your prompt by editing `~/.p10k.zsh`.

At the bottom of your `~/.zshrc` it says the same thing.

Please open the file and work your way from the top. It should take you just a few minutes to figure out how to do what you want.

**Comment by Ambro17** [comment]
i finally got around to what i wanted by reviewing my old 9k config and replicating on this new theme. All i had to do was move the virtualenv section from right to left on `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=`

**Comment by romkatv** [comment]
👍
