### ISSUE TITLE
Some dir shorten strategy broken when directory contains ` (backtick)

### ISSUE THREAD

**Issue by fpob** [romkatv/powerlevel10k#404]
Directory shorten strategy `truncate_to_unique` and `truncate_to_last` are broken when directory  contains ` (backtick) in name.

![Screenshot_2020-01-01_11-56-05](https://user-images.githubusercontent.com/6289078/71640637-04755d00-2c8e-11ea-9b67-314242e9f72c.png)

**Comment by romkatv** [comment]
Thanks for the bug report! Fixed.
