### ISSUE TITLE
[feature] add ability to display/mask prompts according to env var

### ISSUE THREAD

**Issue by gocho1** [romkatv/powerlevel10k#405]
Hi, 

I'm starting to use p10k and find it really customizable. Thanks a lot for it !

However, I can remark some differences due to how informations are sourced.

For example : 
For AWS, it is based on the env var AWS_PROFILE, that can be loaded in some ways (direnv is one of them)
This is perfect as it can display prompts only when relevant (i.e. when we are is AWS-related project folder)

On the contrary, I don't know similar way to load GCloud CLI configuration, as it is sourced from configuration files.
This mean it is always displayed, even if we don't need it (and so clutters the prompts with unneeded informations)

To be able to get similar behaviour, would that be relevant to have something like : 
```POWERLEVEL10K_GCLOUD_ENV_VAR=whatever```
where : 
- `whatever` is a customizable environment variable name 
- the Gcloud prompt would be displayed only when `whatever` is set

There could be a specific variable for all prompts that can not be sourced from env var natively.
If acceptable, I could contribute to it :)

**Comment by romkatv** [comment]
You can do it like this:

```zsh
typeset -g POWERLEVEL9K_GCLOUD_CONTENT_EXPANSION='${gloud_on+$P9K_CONTENT}'
typeset -g POWERLEVEL9K_GCLOUD_VISUAL_IDENTIFIER_EXPANSION='${gloud_on+$P9K_VISUAL_IDENTIFIER}'
```

This will hide `gcloud` prompt segment by default. Type `gloud_on=""` to show it. Type `unset gloud_on` to hide it again.

There is an experimental API in powerlevel10k that makes this task easier. It should eventually become public.
