### ISSUE TITLE
Right prompt 'always' shows 'docker-desktop'

### ISSUE THREAD

**Issue by alexgoldstone** [romkatv/powerlevel10k#406]
This is most likely not an issue with powerlevel10k rather than my lack of knowledge so apologies in advance however...

I updated MacOS to Catalina and updated my shell from Bash to zsh.

I immediately considered ohmyzsh and Prezto but opted to jump straight to the theming and installed powerlevel10k using the 'manual' process.

I was prompted to configure powerlevel10k on restarting my shell and have it working.

However the right prompt *always* shows 'docker-desktop' (screenshot attached).
<img width="572" alt="Screenshot 2020-01-02 at 10 30 42" src="https://user-images.githubusercontent.com/540888/71662883-f5081980-2d4a-11ea-866f-d710f5634de9.png">

I have looked at my .p10k.zsh file (also attached) and cannot work out what 'docker-desktop' is referring to. I am on Mac OS and Docker Desktop is not running.... When I start the docker decsktop application the right-prompt doesn't change even if I restart the shell.

[p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/4015542/p10k.zsh.txt)

Any guidance gratefully received.

**Comment by romkatv** [comment]
That's your current kubernetes context. If you don't want to see it, comment out `kubecontext` in `~/.p10k.zsh`.

**Comment by alexgoldstone** [comment]
@romkatv Thanks... I confirm this removed the right prompt... is there a way to have these things dynamic for example only show kubecontext when kubernetes is running locally and/or I am in a kubernetes context and not simply my Mac OS host?

**Comment by romkatv** [comment]
> only show kubecontext when kubernetes is running locally and/or I am in a kubernetes context

`kubecontext` shows which kubernetes context is used by all `kubectl` commands. The same context is used regardless of the host on which you run `kubectl` or whether you have a local kubernetes cluster running.

There is an experimental API in powerlevel10k that allows you to display the current kubernetes context only when the current command (the one you are still typing) is `kubectl`. This API will eventually become public and `p10k configure` will use it by default.
