### ISSUE TITLE
prompt init ends with return code 1 if instant prompt is enabled

### ISSUE THREAD

**Issue by jayree** [romkatv/powerlevel10k#407]
I'm using macOS 10.15.2 with zsh 5.7.1 (x86_64-apple-darwin19.0)

I've added powerlevel10k manually to .zshrc and used the wizard to create the .p10k.zsh without any additional modifications. 

Starting a new terminal ends up with exit code 1 <img width="57" alt="image" src="https://user-images.githubusercontent.com/14836154/71723594-88198000-2e2d-11ea-82e4-2ab87850ea60.png">

If I remove the instant prompt from .zshrc or if I remove `exec 2>&1` from the `p10k-instant-prompt-username.zsh` file, starting a new terminal ends up with exit code 0 <img width="39" alt="image" src="https://user-images.githubusercontent.com/14836154/71723961-ca8f8c80-2e2e-11ea-9216-a4c42f3f8ad2.png">

I have currently no idea how to investigate which command is exiting with an error. 

Please help. Thanks!

**Comment by romkatv** [comment]
Please attach your `~/.zshrc`.

**Comment by jayree** [comment]
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/4019158/zshrc.txt)

**Comment by romkatv** [comment]
Please attach `~/.p10k.zsh`.

**Comment by jayree** [comment]
@romkatv my `~/.p10k.zsh`
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4019194/p10k.txt)

**Comment by romkatv** [comment]
Do you have `~/.zlogin`? Please attach if so.

**Comment by jayree** [comment]
[zlogin.txt](https://github.com/romkatv/powerlevel10k/files/4019289/zlogin.txt)

**Comment by romkatv** [comment]
The error comes from `~/.zlogin`. This statement:

```zsh
# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    fortune -s
    print
  fi

} >&2
```

`[[ -o INTERACTIVE && -t 2 ]]` is false, so the whole expression is false.

I'll send a PR to prezto to fix this. In the meantime you can fix it locally. Either remove this whole block (best choice if you don't have `fortune` installed, or if you don't care for it) or replace it with this:

```zsh
# Execute code only if there is a TTY.
if [[ -o INTERACTIVE && -n ${TTY:-} ]]; then
  # Print a random, hopefully interesting, adage.
  if (( $+commands[fortune] )); then
    { fortune -s; print } >$TTY
  fi
fi
```

**Comment by romkatv** [comment]
PR sent: https://github.com/sorin-ionescu/prezto/pull/1775.

**Comment by jayree** [comment]
this fixed the error. Thanks a lot!

**Comment by romkatv** [comment]
Thanks for the confirmation. And extra thanks for reporting this issue and assisting in debugging it.

**Comment by romkatv** [comment]
> PR sent: [sorin-ionescu/prezto#1775](https://github.com/sorin-ionescu/prezto/pull/1775).

And merged.
