### ISSUE TITLE
Feature request: a highlight of modified files in the git repository

### ISSUE THREAD

**Issue by psprint** [romkatv/powerlevel10k#408]
Hi!
I have a little feature in my old prompt which shows the modified files sequentially in the prompt. I've demonstrated the feature here: https://asciinema.org/a/Az1odQ17JkPlnnTW6r0o9GMI0. The code that implements it is here: https://github.com/psprint/zprompts/blob/master/prompt_scala4_setup#L87.

I wonder could you maybe consider adding it to p10k?

BTW. From where could be the `_p9k_precmd` called? Zplugin unloaded the theme and removed the function from `precmd` hooks, however, it is still being called from somewhere.

**Comment by romkatv** [comment]
> I have a little feature in my old prompt which shows the modified files sequentially in the prompt.

Looks cute. I'm afraid this is too niche to warrant support in powerlevel10k. You can implement it as a user-defined segment if you like. See https://github.com/romkatv/powerlevel10k/blob/7b77d63e7e29fd81f691c9e43e3a3cadf72880a6/config/p10k-lean.zsh#L1014-L1021.

> BTW. From where could be the `_p9k_precmd` called? Zplugin unloaded the theme and removed the function from `precmd` hooks, however, it is still being called from somewhere.

Please clarify. Are you saying that p10k prompt doesn't disappear when you call `powerlevel10k_plugin_unload`? It would help if you could explain what you do (so that I can reproduce it), what you observe and what you expect.

**Comment by psprint** [comment]
OK, nevermind. I've did switch the prompt with `MYPROMPT` var, however there were other `unload''/load''` conditions that were depending on the `PWD`, hence the `_p9k_precmd` invocation on directory change.

**Comment by romkatv** [comment]
Thanks for the clarification. Closing as there doesn't seem anything to do.

**Comment by psprint** [comment]
I thought that maybe an extended version of the feature could make sense: a switching of the segments in an interval? I'm not using any segments currently, mostly because I don't need them but also because my font is large, so this could help me: e.g.:

```
 /                                              ✔ | root@sg | 12:42:21
after 2 seconds:
 /                                              ✔ | master *16 ?13 | 12:42:21
… 
 /                                              ✔ | root@sg | 12:42:21
…
…
```

**Comment by romkatv** [comment]
That sounds pretty cool! You can already do this. Here's a demo:

```zsh
docker run -e LANG=C.UTF-8 -e TERM -it --rm debian:buster bash -uexc '
  cd
  apt update
  apt install -y nano git curl zsh
  git clone --depth=1 https://github.com/romkatv/zsh-defer.git
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
  >~/.zshrc cat <<\END
source ~/zsh-defer/zsh-defer.plugin.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(context vcs history time)

rotate_period_sec=2
rotate_segments=(context vcs history)

# When Powerlevel10k gets initialized, it'll call this function if it's defined.
p10k-on-init() {
  emulate -L zsh
  typeset -gi active_segment=-1
  # Hide all rotated segments.
  p10k display "*/(${(j:|:)rotate_segments})"=hide
  # Start the rotation.
  _my_rotate
}

_my_rotate() {
  emulate -L zsh
  # Hide the previous active segment and show the next.
  p10k display "*/$rotate_segments[++active_segment]"=hide
  (( active_segment %= $#rotate_segments ))
  p10k display "*/$rotate_segments[active_segment+1]"=show
  # Rotate after 2 seconds.
  zsh-defer -a -t $rotate_period_sec  _my_rotate
}
END
  cd powerlevel10k
  exec zsh'
```

![p10k-rotate](https://user-images.githubusercontent.com/1282067/73358176-5665ce80-429e-11ea-948b-101c10e4703a.gif)

By the way, if you are using transient prompt, take advantage of two-line prompt. You'll get the benefit of extra space for typing commands (and all commands will start from the same offset) without the usual downside of reduced scrollback density.

**Comment by psprint** [comment]
I cannot run the example, an error occurs:

```
call: line 16: warning: here-document at line 6 delimited by end-of-file (wanted `END')
```

I've tried fiddling with the code, e.g.: removing `\` from `\END`, but no luck.

**Comment by romkatv** [comment]
Sorry about that. Fixed.

**Comment by psprint** [comment]
Ah, it's about the quotes inside the text.

**Comment by romkatv** [comment]
Yeah. I added comments after testing this command. Comments had apostrophes, so they broke stuff.

**Comment by psprint** [comment]
I have to say that the prompt looks nice when it's "active" like this. The transient prompt helps to make it OK. I think that such activeness can have one more plus: it lowers the "prompt-blindness" (a paraphrase of the "banner-blindness") – the lack of attention given to the prompt's contents.

**Comment by romkatv** [comment]
I'm not sure I understand your last comment.

> I have to say that the prompt looks nice when it's "active" like this.

Do you mean that you like when prompt segments rotate periodically?

> The transient prompt helps to make it OK.

Do you mean that rotating prompt is OK when transient prompt is enabled but not OK when transient prompt is disabled? Why?

> I think that such activeness can have one more plus: it lowers the "prompt-blindness" (a paraphrase of the "banner-blindness") – the lack of attention given to the prompt's contents.

FWIW, I don't really like rotating prompt. For me, the most important part in the terminal is the command line. Rotating prompt distracts me when I need to focus on typing the command I have in mind and need to concentrate to get all the flags right. I want prompt to have information ready if I need to consult it ("on which branch am I right now?") but not to push information in my face.

**Comment by psprint** [comment]
> Do you mean that you like when prompt segments rotate periodically?

Yes.

> Do you mean that rotating prompt is OK when transient prompt is enabled but not OK when transient prompt is disabled? Why?

Not that it's not OK, it's just that without the transient prompt the rotated segments would persist and be random across the scrollback.

> FWIW, I don't really like rotating prompt. For me, the most important part in the terminal is the command line. Rotating prompt distracts me when I need to focus on typing the command I have in mind and need to concentrate to get all the flags right. I want prompt to have information ready if I need to consult it ("on which branch am I right now?") but not to push information in my face.

Yes, I have such doubts too, however, I often feel that I'm missing the contents of the great prompts created currently. I rarely switch branches, so I rarely ask myself the question, however, just "keeping in touch" with the state could be enough reason to read the prompt.
