### ISSUE TITLE
Prompt showing wrong user / host name

### ISSUE THREAD

**Issue by bluenote10** [romkatv/powerlevel10k#409]
For some reason my prompt shows a user/host combination of `kubernetes-admin@kubernetes` which is not correct:

![image](https://user-images.githubusercontent.com/3620703/71896954-6f72d800-3155-11ea-96d3-e289838757e9.png)

 `$USER` / `$HOST` / `hostname` give the correct information.

Any ideas what could be causing this, i.e., how is this information determined internally?

**Comment by romkatv** [comment]
That's your current kubernetes context. If you don't want to see it, comment out `kubecontext` in `~/.p10k.zsh`.

**Comment by bluenote10** [comment]
Thanks, that removes it! Then my question probably should be: why is `user@host` missing? I've added `context` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`, but it doesn't show up.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-add-username-andor-hostname-to-prompt.
