### ISSUE TITLE
vcs_joined doesn't work

### ISSUE THREAD

**Issue by gimbo** [romkatv/powerlevel10k#41]
It seems that a prompt segment of `vcs_joined` doesn't work in powerlevel10k.

[This section of the powerlevel9k docs](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt#glue-segments-together) says:

> It is possible to display two segments as one, by adding `_joined` to your segment definition. The segments are always joined with their predecessor, so be sure that this is always visible.

So I'd expect it to work. However...

With a freshly cloned powerlevel10k (see below for git hash), and a `~/.zshrc` consisting only of this:

```
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time vcs)
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

... then everything works as expected. But if I add `_joined` to the `vcs` part, to give:

```
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(time vcs_joined)
source ~/powerlevel10k/powerlevel10k.zsh-theme
```

... then I get this output:

```
_p9k_vcs_gitstatus:16: command not found: gitstatus_query
prompt_vcs:12: command not found: vcs_info
```
(followed by the prompt, but without any vcs info).

Reporting this as a bug as my understanding is that you're aiming for full powerline9k compatability.

```
$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
```

```
$ cd ~/powerlevel10k
$ git rev-parse HEAD
e5dbe4fa2e5ba010968be2d35a987e74653ea115
```

**Comment by romkatv** [comment]
Thanks for the report! This is now fixed.

**Comment by gimbo** [comment]
That is very awesome and I confirm that it works for me - many thanks indeed! Loving this. (BTW, my adaption: [`gimbo.zsh`](https://github.com/gimbo/gimbo.zsh-theme/blob/master/gimbo.zsh).)

**Comment by romkatv** [comment]
Cute :+1:

You can save a fork by replacing `root=$(basename $x)` with `root=${x:t}`.

**Comment by gimbo** [comment]
Nice - thanks! Shell scripting isn't _quite_ my thing - I "get by" but don't grok it like, say, python. :-)
