### ISSUE TITLE
git prompt background color a little slow on MSYS2

### ISSUE THREAD

**Issue by Sleepful** [romkatv/powerlevel10k#410]
It takes like one second to fill in the color, but sometimes a little longer, if I hit a new line quickly enough before it fills in the color then it's left unfilled, screenshot showing behavior:

![image](https://user-images.githubusercontent.com/7144046/71900107-bd221d00-3122-11ea-9485-277fd660a2f1.png)

I don't know if this might be because I am using MSYS2 on Windows, if you have any idea of what could be making this slower than the rest of the prompt, I'd like to look into it. If the program uses fork() somewhere, it could be the culprit because fork() is really slow on MSYS2, but I have no idea if that's anywhere near the issue.

**Comment by romkatv** [comment]
What's the output of `time git status >/dev/null` in that directory?

**Comment by romkatv** [comment]
Somewhat unrelated: I see that your terminal is unable to property render color 8. I recommend adding `POWERLEVEL9K_VCS_LOADING_BACKGROUND=7` to `~/.p10k.zsh`. Search for `POWERLEVEL9K_VCS_LOADING_BACKGROUND` in that file, uncomment the line and change the value from 8 to 7.

**Comment by Sleepful** [comment]
`$ time git status >/dev/null` 
`git status > /dev/null  0.42s user 0.69s system 101% cpu 1.089 total`
`git status > /dev/null  0.03s user 0.33s system 153% cpu 0.233 total`

I now get the loading background though! That's much nicer, thank you
![image](https://user-images.githubusercontent.com/7144046/71901476-a630fa00-3125-11ea-8a93-aa4f4626a4a1.png)

**Comment by romkatv** [comment]
To display [Git repository information](https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean) in your prompt, powerlevel10k needs to execute something like `git status`. As you can see, this command takes a while to complete. To avoid blocking your prompt, powerlevel10k doesn't wait for `git status` to complete. Instead, it displays prompt instantly while running `git status` in the background. To indicate that Git information in your prompt may not be up to date, Git segment is displayed with a different background color while `git status` is in progress.

By default, the background color used for this purpose is `8`. Unfortunately, your terminal isn't capable of rendering it property, which is the reason you saw visual artifacts. You can use the following command to see how your terminal displays foreground and background colors with different color codes:

```zsh
for i in {0..255}; do print -Pn "%K{$i} %k%${i}F${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'}; don
```
