### ISSUE TITLE
p10k running not normal when terminal.app boot on MacOS

### ISSUE THREAD

**Issue by beagle4ce** [romkatv/powerlevel10k#413]
p10k already installed on my terminal.app with oh-my-zsh.

But p10k look not normal when the terminal.app every boot.

When i click Enter it's look likes 

❯ 
❯ 
❯ 
❯ 
❯ 
❯ 
❯ 
❯ 
❯ 
❯  beagle/home/Users/beagle

I think its should be like this when i click Enter

❯  beagle@ /home/Users/beagle
❯ beagle@ /home/Users/beagle
❯  beagle@ /home/Users/beagle

How setting or config to fix it?

thanks

**Comment by romkatv** [comment]
Please post a screenshot of your terminal.

**Comment by beagle4ce** [comment]
![image](https://user-images.githubusercontent.com/4271372/72156891-90575980-33f1-11ea-996a-7a01f1d3bbf8.png)
This is not normal


![image](https://user-images.githubusercontent.com/4271372/72157082-01970c80-33f2-11ea-971c-f6f30c17ad1b.png)
And this is normal

I need execute “ source ~/.zshrc ” to fix it when terminal client every starting

**Comment by romkatv** [comment]
Please attach `~/.zshrc` and `~/.p10k.zsh` to this issue (drag and drop these files into the edit box).

**Comment by beagle4ce** [comment]
[p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/4046205/p10k.zsh.txt)
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/4046206/zshrc.txt)

I add suffix of txt for allow to upload

**Comment by romkatv** [comment]
> ![image](https://user-images.githubusercontent.com/4271372/72156891-90575980-33f1-11ea-996a-7a01f1d3bbf8.png)

This ^^ is expected given that you've enabled *Transient Prompt*. If you don't want this behavior, run `p10k configure` and select *No* when asked whether you want to *Enable Transient Prompt*.

> ![image](https://user-images.githubusercontent.com/4271372/72157082-01970c80-33f2-11ea-971c-f6f30c17ad1b.png)
> And this is normal
> 
> I need execute “ source ~/.zshrc ” to fix it when terminal client every starting

This ^^ is unexpected. Typing `source ~/.zshrc` should not have this effect. I've managed to reproduce this locally and will try to fix it.

**Comment by romkatv** [comment]
OK, figured out what's going on. When you run `source ~/.zshrc`, oh-my-zsh overrides zle widgets that powerlevel10k needs.

In general, it's almost always a bad idea to run `source ~/.zshrc`. Don't do this. Use `exec zsh` instead. It's still not as good as restarting zsh but it's much better than `source ~/.zshrc`.

**Comment by beagle4ce** [comment]
Yes , It's figured out. thank you. 
And i appreciate your guidance，that good for me。
