### ISSUE TITLE
Feature request: Don't show show branch name if 'master'

### ISSUE THREAD

**Issue by beorn** [romkatv/powerlevel10k#414]
To create a super-minimalist prompt, perhaps it should be possible to just leave the branch icon while hiding the branch name if it is the most common (="default") one, which is 'master'?

**Comment by romkatv** [comment]
From https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status:

> ### How do I change the format of Git status?
> 
> To change the format of Git status, open `~/.p10k.zsh`, search for `my_git_formatter` and edit its
source code.

Open `~/.p10k.zsh` and find this section:

```zsh
local where  # branch or tag
if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
  res+="${clean}${POWERLEVEL9K_VCS_BRANCH_ICON}"
  where=${(V)VCS_STATUS_LOCAL_BRANCH}
elif [[ -n $VCS_STATUS_TAG ]]; then
  res+="${meta}#"
  where=${(V)VCS_STATUS_TAG}
fi

# If local branch name or tag is at most 32 characters long, show it in full.
# Otherwise show the first 12 … the last 12.
(( $#where > 32 )) && where[13,-13]="…"
res+="${clean}${where//\%/%%}"  # escape %

# Display the current Git commit if there is no branch or tag.
# Tip: To always display the current Git commit, remove `[[ -z $where ]] &&` from the next line.
[[ -z $where ]] && res+="${meta}@${clean}${VCS_STATUS_COMMIT[1,8]}"

# Show tracking branch name if it differs from local branch.
if [[ -n ${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH} ]]; then
  res+="${meta}:${clean}${(V)VCS_STATUS_REMOTE_BRANCH//\%/%%}"  # escape %
fi
```

Wrap it like this:

```zsh
if [[ $VCS_STATUS_LOCAL_BRANCH != master ]]; then
  ... the same section as quoted above ...
else
  res+="${clean}${POWERLEVEL9K_VCS_BRANCH_ICON}"
fi
```

**Comment by beorn** [comment]
Thanks!!!

I guess that's a bit equivalent of 'ejecting' and not being able to run the configurator anymore, but ok for me.  I was thinking maybe there was some truncate strategy variable or regexp variable that could be defined.  But if it's just for me then it's not worth it.

**Comment by romkatv** [comment]
> I guess that's a bit equivalent of 'ejecting' and not being able to run the configurator anymore, but ok for me.

It's not unusual to edit the config generated by `p10k configure`. The total configuration space is immense and the wizard is only meant to get you started. If you want to tailor everything to fit your preferences perfectly, editing the config is the way to go.

> I was thinking maybe there was some truncate strategy variable or regexp variable that could be defined. But if it's just for me then it's not worth it.

There is no such parameter. If there was, you would still have to edit the config to change its value.
