### ISSUE TITLE
Icons not showing properly

### ISSUE THREAD

**Issue by hwennnn** [romkatv/powerlevel10k#415]
<img width="698" alt="Screenshot 2020-01-12 at 11 16 29 PM" src="https://user-images.githubusercontent.com/54523581/72221022-a4d25800-3591-11ea-89ce-d602f1936c34.png">

As shown, the icons are not showing properly. Also I do try out every powershell fonts but it's still not working for me;;

This is my .zshrc profile:
<img width="698" alt="Screenshot 2020-01-12 at 11 19 14 PM" src="https://user-images.githubusercontent.com/54523581/72221058-f7137900-3591-11ea-9c03-350782031dc5.png">

**Comment by romkatv** [comment]
Have you tried this? https://github.com/romkatv/powerlevel10k#why-do-my-icons-andor-powerline-symbols-look-bad

**Comment by hwennnn** [comment]
Ohh it works for me! Thanks a lot!

**Comment by romkatv** [comment]
You are very welcome :hugs:

**Comment by hansspiess** [comment]
the hash has changed since then to https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render

**Comment by MajesticOl** [comment]
The funny thing is that nowhere is some kind of explanation how to actually install the recommended font inside the terminal. I drives me insane... just cant manage to install it...

**Comment by romkatv** [comment]
Use the documentation of your OS to find out how to install fonts for it.
