### ISSUE TITLE
Powerlevel10k breaks xcwd

### ISSUE THREAD

**Issue by TsarN** [romkatv/powerlevel10k#42]
I use [xcwd](https://github.com/schischi/xcwd) to open new terminal windows in the same directory as the current one. Unfortunately, with Powerlevel10k it always reports my home directory.
With sh/bash it works properly, it also works with other `oh-my-zsh` themes (including original Powerlevel9k). I use `suckless-terminal` as my terminal emulator.

If I understand correctly, the problem is that current directory is not propagated back to the terminal emulator for some reason.

**Comment by romkatv** [comment]
There are too many words that are new to me. You'll have to describe more precisely what you are doing, what you are expecting and what actually happens.

**Comment by TsarN** [comment]
Of course :) Usually when I change into some directory in bash/zsh, it updates current working directory of a terminal emulator window (as I understand it X window server stores this value per window). [xcwd](https://github.com/schischi/xcwd) reads this value from focused window and outputs it to `stdout`. Unfortunately, as soon as I enable Powerlevel10k in `zsh` it no longer reports actual current directory, but my home directory.

Here's what I do:

 - open a new terminal window (using zsh and this theme)
 - run `cd /some/directory/path`
 - run `xcwd`

Expected output (output without powerlevel10k or when using other shell (bash)): `/some/directory/path`.

What I get: `/home/tsarn` (my home directory)

I'd be happy to provide more details if needed.

**Comment by romkatv** [comment]
Fascinating.

Before I attempt to reproduce this, could you try one experiment?

1. Open zsh without Powerlevel10k in your terminal.
2. While still in your home directory, type `zsh -c 'sleep 60' &!`.
3. Change your current directory.

Is xcwd reporting the right current directory?

**Comment by TsarN** [comment]
Yes, it still reports it correctly (and still incorrectly with Powerlevel10k enabled)

**Comment by romkatv** [comment]
OK, I'll try to reproduce this when I get time but it may be not very soon. The biggest obstacle is that I don't use neither the terminal you use, nor xcwd. I also don't know how I'm supposed to type `xcwd` in one terminal while having focus on another terminal window. Is that how `xcwd` is supposed to be used? If so, how do I divorce window focus from keyboard focus?

**Comment by TsarN** [comment]
I mainly use [suckless terminal](https://st.suckless.org/), but I checked and the behavior seems to be the same in Termite and xterm. I use xcwd together with [this script](https://gist.github.com/TsarN/5ef4e87178637fe0b4c3708220a7e11c) to open a new terminal window when i press Win+Enter.
To divorce window focus something like `sleep 3; xcwd` may be used I think.

**Comment by romkatv** [comment]
Thanks for the info. I'll take a look later.

FWIW, the way I will approach this is to read the code of xcwd and try to figure out either how to enable logging in it or add logging myself. Then run it and see which process it finds and why. If you care about this, perhaps this is something you could do? It doesn't require any knowledge of Powerlevel10k.

**Comment by TsarN** [comment]
Yeah, I think I can do it, but won't be able to look into it until Friday.

**Comment by romkatv** [comment]
Thanks. Your help would be very valuable.

**Comment by TsarN** [comment]
So, I quickly glanced over `xcwd`'s source code and noticed that there's a `DEBUG` define. Convenient.
Here is the output:
```
Window ID = 41943045
_NET_WM_PID = 16276
Found 201 processes
      <long uninteresting list of unrelated processes omitted>
Read /proc/16332/cwd
/home/tsarn
```

PID 16276 (the one xcwd reports as _NET_WM_PID) is the PID of my terminal emulator (`st`). Process tree with Powerlevel10k enabled looks like this:

```
$ pstree -p 16276
st(16276)───zsh(16277)─┬─pstree(16493)
                       └─zsh(16330)───gitstatusd-linu(16332)─┬─{gitstatusd-linu}(16333)
                                                             ├─{gitstatusd-linu}(16334)
                                                             ├─{gitstatusd-linu}(16335)
                                                             ├─{gitstatusd-linu}(16336)
                                                             ├─{gitstatusd-linu}(16337)
                                                             ├─{gitstatusd-linu}(16338)
                                                             ├─{gitstatusd-linu}(16339)
                                                             └─{gitstatusd-linu}(16340)
```

`xcwd` appears to read `gitstatusd-linux(16332)`'s current directory (instead of `zsh(16277)`'s which is the correct one)

With Powerlevel10k disabled process tree looks like this:

```
$ pstree -p 16952
st(16952)───zsh(16953)───pstree(17081)
```

`xcwd` handles this much simpler process tree well and always reports the correct directory.

I have also noticed that sometimes `xcwd` reports correct directory even with Powerlevel10k enabled 
(but it never reports incorrectly with it disabled). So that's weird.

It might be easier to a hack in `xcwd` itself for these kinds of situations. I'll look into it when I have more time.

**Comment by romkatv** [comment]
The process tree looks as expected. This is where the extra `zsh` and `gitstatusd` are launched: https://github.com/romkatv/gitstatus/blob/e1a61e76ccc74bd9d0f637724af7a9c0641ae85b/gitstatus.plugin.zsh#L224. This is why I asked you to test with `zsh -c sleep` before. It's essentially the same thing but with `sleep` instead of `gitstatusd`. Somehow `sleep` doesn't confuse `xcwd` but `gitstatusd` does. You could try to figure out what germane difference there is. E.g., if you manually run `zsh -xc gitstatusd &>/dev/null &!`, will it confuse `xcwd`?

**Comment by TsarN** [comment]
I think it's random. I have now tested again with `sleep` subshell and plain `zsh` and it stopped working. I'll end up patching `xcwd` to just look into first child process of terminal emulator (or to ignore `gitstatusd`).

**Comment by romkatv** [comment]
Blacklisting `gitstatusd` may not help because you'll still have `zsh`. Looking at the deepest child process will only work if you don't have background processes. `xcwd` cannot distinguish between foreground and background processes, so it won't know which zsh is more legit.

It's possible to implement a workaround in gitstatusd by daemonizing it and thus breaking the link to its parent. I'd rather not do it because knowing that gitstatusd is a child of your interactive zsh is valuable.

If you change `xcwd` to look at the first child of the terminal, it won't work if you type `zsh` in your terminal, thus creating a foreground child.

**Comment by TsarN** [comment]
I see. Is there a way to distinguish `zsh` spawned from Powerlevel10k from other processes? I don't really use background processes or terminal multiplexers so I don't care about telling foreground and background processes apart.

**Comment by romkatv** [comment]
Cute :+1:

You can save a fork by replacing `root=$(basename $x)` with `root=${x:t}`.

**Comment by romkatv** [comment]
Sorry, wrong issue.

**Comment by romkatv** [comment]
> I see. Is there a way to distinguish zsh spawned from Powerlevel10k from other processes?

You could examine its command line arguments.

You could also do the following. Look at fd 0 of every process in the tree (on Linux you can do this by looking at `/proc/$PID/fd/0`) and check if it's a tty.

**Comment by TsarN** [comment]
I have made a [fork of xcwd](https://github.com/TsarN/xcwd) which only considers processes whose `stdout` is a tty. And it works! Thanks a lot for your help and for this amazing theme :)

**Comment by romkatv** [comment]
> I have made a fork of xcwd...

:100: Open source FTW!

P.S.

fd 0 is stdin. Your code is fine, it's indeed better to look for stdin than for stdout, but the readme needs to be updated.

If you want your code to be a bit more portable, use `open()` + `istty()` to checked for TTY. You can ditch `readlink()` -- `open()` can follow symlinks.
