### ISSUE TITLE
Problem with p10k wizard defaulting to 2 liner

### ISSUE THREAD

**Issue by Nickadiemus** [romkatv/powerlevel10k#421]
I've just installed powerlevel10k using the cli wizard to quickly set up and configure the powerline10k theme. I've run into the issue of having the prompt always be configured to a two line cli prompt as seen in the file below 

<img width="535" alt="Screen Shot 2020-01-15 at 5 02 13 PM" src="https://user-images.githubusercontent.com/15810541/72475440-e4c75400-37b8-11ea-958d-39d8fdada716.png">

I've tried running the p10k wizard multiple times to overwrite the `~/.p10k.zsh` and change the theme to 1 liner but have not had any luck with it :/

**Comment by romkatv** [comment]
Thanks for the bug report! Fixed. Please update powerlevel10k and run `p10k configure`.

**Comment by Nickadiemus** [comment]
@romkatv thanks for the quick fix!
