### ISSUE TITLE
Gitstatus subprocess Nice value

### ISSUE THREAD

**Issue by heavelock** [romkatv/powerlevel10k#423]
Hi!

Thanks for developing this great piece of software! It really helps a lot with responsivity of prompt especially on WSL  which is already slow and any additional lag is even more visible. Anyway, I have a problem/question. 

I think during spawning of gitstatus subprocess there somewhere some bug that sets the value of nice to `4294967291` instead of something like 2 digits long. It's kind of a bug that is not that much problematic but it's rather an annoyance since it's messing up with formatting of htop for example. 

Here is the screenshot from htop.

![obraz](https://user-images.githubusercontent.com/10303802/72510591-01f83300-384a-11ea-8bce-7aec6c4c4cf5.png)

**Comment by romkatv** [comment]
Thanks for the report. Fixed.
