### ISSUE TITLE
Configuration wizard can't update relativ symlink .zshrc

### ISSUE THREAD

**Issue by lnicola** [romkatv/powerlevel10k#426]
```
                           Apply changes to ~/.zshrc?

(y)  Yes (recommended).

(n)  No. I know which changes to apply and will do it myself.

(r)  Restart from the beginning.
(q)  Quit and do nothing.

Choice [ynrq]: yask_zshrc_edit:52: no such file or directory: /tmp/.zshrc.9AI18NXFn3

Powerlevel10k configuration wizard has been aborted. It will run again
next time unless you define at least one Powerlevel10k configuration option.
To define an option that does nothing except for disabling Powerlevel10k
configuration wizard, type the following command:

  echo 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true' >>! ~/.zshrc

To run Powerlevel10k configuration wizard right now, type:

  p10k configure
```

With `/tmp/.zshrc.9AI18NXFn3 -> dotfiles/.zshrc` (note the relative path).

**Comment by romkatv** [comment]
When I run the wizard with a setup similar to yours, there is no error. However, `~/.zshrc` ends up being a regular file, not a symlink. This is a bug that I'd like to get fixed (thanks for discovering and reporting it) but before that I'd like to understand why the behavior differs on our systems.

What is the output of `git rev-parse HEAD` in the `powerlevel10k` directory? If it's not `0a484d1d994de7febcdb1ffa9c9d2635c65c285d`, could you update powerlevel10k and try again?

Is it possible that `cp` on your system is not POSIX compliant? For example, does the following code succeed or fail for you?

```zsh
() {
  emulate -L zsh -o err_return -o extended_glob
  local tmp
  {
    tmp=$(mktemp -d ${TMPDIR:-/tmp}/cp-test.XXXXXXXXXX)
    touch $tmp/a
    ln -s a $tmp/b
    cp -p $tmp/b $tmp/c
    [[ -n $tmp/c(#qN.) ]]
  } always {
    (( $? )) && echo FAIL || echo SUCCESS
    [[ -n $tmp ]] && rm -f -- $tmp/{a,b,c} && rmdir -- $tmp
  }
}
```

**Comment by lnicola** [comment]
I'm on `0a484d1d994de7febcdb1ffa9c9d2635c65c285d`.

With your code I get:

```bash
 ~  () {                                                                                                                                                                                                    1 ✘ 
  emulate -L zsh -o err_return -o extended_glob
  local tmp
  {
    tmp=$(mktemp -d ${TMPDIR:-/tmp}/cp-test.XXXXXXXXXX)
    touch $tmp/a
    ln -s a $tmp/b
    cp -p $tmp/b $tmp/c
    [[ -n $tmp/c(#qN.) ]]
  } always {
    (( $? )) && echo FAIL || echo SUCCESS
    [[ -n $tmp ]] && rm -f -- $tmp/{a,b,c} && rmdir -- $tmp
  }
}
FAIL
```

```
+zsh:59> '(anon)'
+(anon):1> emulate -L zsh -o err_return -o extended_glob
+(anon):2> local tmp
+(anon):4> tmp=+(anon):4> mktemp -d /tmp/cp-test.XXXXXXXXXX
+(anon):4> tmp=/tmp/cp-test.DLE7AbbrtR 
+(anon):5> touch /tmp/cp-test.DLE7AbbrtR/a
+(anon):6> ln -s a /tmp/cp-test.DLE7AbbrtR/b
+(anon):7> cp -r -p /tmp/cp-test.DLE7AbbrtR/b /tmp/cp-test.DLE7AbbrtR/c
+(anon):8> [[ -n '' ]]
+(anon):10> ((  1  ))
+(anon):10> echo FAIL
```

**Comment by romkatv** [comment]
So `cp -p` turns into `cp -r -p`. What does this?

**Comment by lnicola** [comment]
The `alias cp="cp -r"` line in my `.zshrc`?

**Comment by lnicola** [comment]
That is, the script should probably use `command cp`, `command rm`, `command touch` and so on to avoid these situations.

**Comment by romkatv** [comment]
> The `alias cp="cp -r"` line in my `.zshrc`?

Does it come from your `.zshrc`?

When I add `alias cp='cp -r'` to my `~/.zshrc`, I can reproduce the failure with the command I posted earlier but it has no effect on the p10k wizard. The wizard disables aliases for itself: https://github.com/romkatv/powerlevel10k/blob/f85a3a56524f79c52ce367e9d55a2ef275b76155/internal/wizard.zsh#L2

Is it possible that your zsh config files override things like `setopt`? Any other ideas why on your system `cp -p` behaves contrary to how it should?

**Comment by romkatv** [comment]
> When I run the wizard with a setup similar to yours, there is no error. However, `~/.zshrc` ends up being a regular file, not a symlink. This is a bug that I'd like to get fixed (thanks for discovering and reporting it) but before that I'd like to understand why the behavior differs on our systems.

I've fixed this bug. It's still unclear what was causing the original error for you though.

**Comment by lnicola** [comment]
With `setopt noaliases`, the script above works. But no, I'm not sure what might have happened.

**Comment by romkatv** [comment]
> With `setopt noaliases`, the script above works. But no, I'm not sure what might have happened.

Could you update and try again? Since there is now explicit handling of symlinks, the code shouldn't get tripped by whatever it was being tripped by.

**Comment by lnicola** [comment]
It's working now. I still need to set up the font and look over the config file (it's huge). The colors are fine now, or at least match what the wizard shows:

![image](https://user-images.githubusercontent.com/308347/72683208-fb81e980-3add-11ea-8bcd-dc83d18becda.png)

Thanks!
