### ISSUE TITLE
Pre command hook does not work with p10k

### ISSUE THREAD

**Issue by alex-popov-tech** [romkatv/powerlevel10k#427]
Hello. I'm using p10k with zplugin as recommended:
https://github.com/alex-popov-tech/.dotfiles/blob/master/terminal/zshell/zsh_plugins#L8
as well with another plugin:
https://github.com/alex-popov-tech/.dotfiles/blob/master/terminal/zshell/zsh_plugins#L20
But the [hardcore](https://github.com/MichaelAquilina/zsh-you-should-use#hardcore-mode) option do not work in the current setup:
```
   ~ I git status
Found existing alias for "git status". You should use: "gst"
fatal: not a git repository (or any of the parent directories): .git
   ~ I export YSU_HARDCORE=1                       
   ~ I git status           
Found existing alias for "git status". You should use: "gst"
You Should Use hardcore mode enabled. Use your aliases!
fatal: not a git repository (or any of the parent directories): .git    <<<< that line should not be printed
```

however, if i will commend p10k plugin it works as expected:
```
start typing...git status       
Found existing alias for "git status". You should use: "gst"
fatal: not a git repository (or any of the parent directories): .git
start typing...export YSU_HARDCORE=1      
start typing...git status        
Found existing alias for "git status". You should use: "gst"
You Should Use hardcore mode enabled. Use your aliases!
```

Any ideas about what could go wrong here? I tried multiple plugins like this one, and with all of them had the same issue.

**Comment by romkatv** [comment]
> Hello. I'm using p10k with zplugin as recommended

The way you are loading p10k is unsupported. It may break at any time, or it could already be broken. See documentation: https://github.com/romkatv/powerlevel10k/blob/master/README.md#zplugin.

I know that zplugin "wiki" lists unsupported/invalid/broken uses of p10k. Despite its name, that's not a wiki, so I cannot edit it. There is an officially supported way for every broken p10k recipe from the zplugin wiki. E.g., for loading, see above.

You can make zsh start faster and smoother with a change like this: https://github.com/alex-popov-tech/.dotfiles/compare/master...romkatv:faster-zsh-startup. It enables instant prompt in p10k and disables deferred loading (`wait` ice) of zplugin.

> But the hardcore option do not work in the current setup

Thanks for the bug report! Fixed. Please update and try again.

**Comment by alex-popov-tech** [comment]
Hello @romkatv ! Thanks a lot for the fast response, I've updated p10k, and now it's working as expected.

The only my question is - I tried to compare instant prompt on/off and had the same results (~0.13s) using `for i in $(seq 1 10); do /usr/bin/time /bin/zsh -i -c exit; done;`. Is my prompt loading so quick so I can't see the profit of instant_prompt improvement?

**Comment by alex-popov-tech** [comment]
Okay, that explains! Thanks a lot
