### ISSUE TITLE
Added command to change prompt but need help changing color

### ISSUE THREAD

**Issue by tomglynch** [romkatv/powerlevel10k#429]
I've added the following to my .zshrc file, which has added the virtual environment i'm using to the right side of the prompt. 

```
export PYENV_ROOT="$HOME/.pyenv"

export PATH="$PYENV_ROOT/bin:$PATH"

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```
Unfortunately it is difficult to read due to it being black text on a dark blue background as seen in the image below:

![image](https://user-images.githubusercontent.com/17879963/72782185-41be8080-3c77-11ea-80c0-e5924a32908c.png)

Could someone help me fix this? I have spent a bit of time learning about oh-my-zsh and powerlevel10k however to change this one simple thing has left me very lost. Where in the config files can I change this?

Thanks,

Tom

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`. Close to the top you can see the most important parameters that define which segments are shown in your prompt. All generally useful prompt segments are listed in there. Some of them are enabled, others are commented out. One of them is of interest to you.

```zsh
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  ...
  pyenv  # python environment (https://github.com/pyenv/pyenv)
  ...
)
```

Search for `pyenv` to find the section in the config that lists parameters specific to this prompt segment. You should see the following lines:

```zsh
# Pyenv color.
# typeset -g POWERLEVEL9K_PYENV_FOREGROUND=0
# typeset -g POWERLEVEL9K_PYENV_BACKGROUND=4
```

You can uncomment these parameters and modify their values to change colors. Restart Zsh for your changes to take effect.

---

Prompt on your screenshot looks worse than expected. It appears that your terminal is using suboptimal color palete and is having trouble rendering several glyphs properly. What terminal are you using?

**Comment by tomglynch** [comment]
Thank you so much @romkatv, saved me a heap of time. This is a fantastic repo, you're doing a fantastic job.

**Comment by romkatv** [comment]
> This is a fantastic repo, you're doing a fantastic job.

Thank you! Made my day :hugs:
