### ISSUE TITLE
Remove the 'master' tab at the end of the prompt

### ISSUE THREAD

**Issue by classbproject** [romkatv/powerlevel10k#433]
Hi, I was hoping to know how you can remove the master tab (in yellow) at the end of the prompt as shown in the image. Also, what do those numbers next to master mean? 

<img width="352" alt="Screen Shot 2020-01-24 at 12 01 20" src="https://user-images.githubusercontent.com/19990466/73049375-68acca80-3ea2-11ea-8bae-bd54e80fdeb4.png">

**Comment by romkatv** [comment]
Does this help? https://stackoverflow.com/a/59509820/1095235

**Comment by classbproject** [comment]
Perfect! This worked like a charm. Thanks :)
