### ISSUE TITLE
Rainbow style don't show in p10k configure

### ISSUE THREAD

**Issue by farshidhss** [romkatv/powerlevel10k#434]
Hello! Thank you for the nice work. 
When I run p10k configure I only get the Lean and Classic styles. I wanted to switch to Rainbow. Anything that I'm missing?
![image](https://user-images.githubusercontent.com/4727688/73067003-d3acd000-3ea7-11ea-8cbd-d37bdf887d16.png)

**Comment by romkatv** [comment]
There is not enough room to display all styles. Try making your terminal window taller.

**Comment by farshidhss** [comment]
This is with a tall window:
![image](https://user-images.githubusercontent.com/4727688/73069850-2473f700-3eaf-11ea-9781-2c81ec0f6af1.png)

**Comment by romkatv** [comment]
Have you resized the window before running `p10k configure` or after?

**Comment by farshidhss** [comment]
Resized it before running the configure.

**Comment by romkatv** [comment]
Perhaps you are using a very old version of powerlevel10k? Try updating it.

**Comment by farshidhss** [comment]
I have updated using the following commands:
`git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>! ~/.zshrc`

but still can't see rainbow style.

































...
0
.0

..

**Comment by romkatv** [comment]
I just went through the code history. Pretty sure you are using the old version.

**Comment by farshidhss** [comment]
Thank you! I disabled the current theme (remove ZSH_THEME like in .zshrc) and then p10k configure actually showed the updated version 😄

**Comment by romkatv** [comment]
Great! This means you have the old version in `$ZSH_CUSTOM/themes/powerlevel10k`.

**Comment by tjirab** [comment]
In case you are running into this issue and you run `p10k configure` from a terminal multiplexer (like tmux), try to exit the multiplexer first and then run through the wizard again.

**Comment by Rocky-L** [comment]
I have the same issue on ubuntu 18.04, but it works fine on my M1 Macbookpro. I've tried all the methods above, none of them worked. I end up with manually modified the p10k.zsh file to make it a rainbow look on my ubuntu

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by cheonhyangzhang** [comment]
I have faced the same issue and my powerlevel10k is just installed, which means should be the latest version.  
My root cause is the same as @tjirab pointed out. I am running the `p10k configure` command inside of a tmux session and the wizard does not have the rainbow option. 
After exiting the tmux session, rainbow option is available.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by romkatv** [comment]
More specifically, the problem you are having can often be fixed by adding `set -g default-terminal screen-256color` to `~/.tmux.conf`.
