### ISSUE TITLE
disk_usage doesn't work properly

### ISSUE THREAD

**Issue by jD4rk** [romkatv/powerlevel10k#435]
First of all, compliment for your job....v10 of power level is really amazing.

After try it, I realized that **disk_usage** capability didn't work properly, in details:
- configuration color from custom .p10k.zsh are not apply cause an hard implementation of them in the file p10k.zsh 

>  if (( disk_usage >= _POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL )); then
>     state=critical
>     bg=
>     fg=red
>   elif (( disk_usage >= _POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL )); then
>     state=warning
>     bg=
>     fg=yellow
>   else
>     (( _POWERLEVEL9K_DISK_USAGE_ONLY_WARNING )) && return
>     state=normal
>     bg=
>     fg=$_p9k_color2
>   fi

Having made few changes into **battery status** to make it more suitable to my need I tried to update also the disk_usage function but I don't know why at the end it didn't show up in the prompt the right color

https://gist.github.com/jD4rk/6555ec85b00b11e649438671ddc27cd1
where 
>   _p9k_disk_usage_states=(
>     'ONLY_WARNING'  "$_p9k_color2"
>     'WARNING_LEVEL' 'yellow'
>     'CRITICAL'      'red'
> 

PS (about the gist file):
the few echo commands are kind of __really really basic and old-style__ debug message,
but according them the problem every variables are set properly and the issue should be on last call:
  **_p9k_prompt_segment $0_$state "$bg" "$fg" DISK_ICON 0 '' "$disk_usage%%"**

I try to figure out how _p9k_prompt_segment works but its a little bit too complicate for my bash level (just started to work with it a week ago)

**Comment by romkatv** [comment]
Please describe what you are doing, what you expect and what actually happens.

**Comment by jD4rk** [comment]
well the assigned color for the foreground (text/icon) are not applied to the context

**Comment by romkatv** [comment]
Please post the output of `typeset -pm 'POWERLEVEL9K_*'`, a screenshot of your prompt and an explanation of what is wrong on the screenshot.

**Comment by jD4rk** [comment]
typeset POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=8
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=76
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT_EXPANSION=Ⅴ
typeset -a POWERLEVEL9K_JENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_CONTENT_EXPANSION='${P9K_GOOGLE_APP_CRED_PROJECT_ID//\%/%%}'
typeset POWERLEVEL9K_SHORTEN_DELIMITER=''
typeset POWERLEVEL9K_RVM_SHOW_PREFIX=false
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset POWERLEVEL9K_CONTEXT_TEMPLATE=%n@%m
typeset POWERLEVEL9K_OS_ICON_FOREGROUND=7
typeset POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39
typeset POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset POWERLEVEL9K_PLENV_PROMPT_ALWAYS_SHOW=false
typeset -a POWERLEVEL9K_PYENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=90
typeset POWERLEVEL9K_GCLOUD_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT//\%/%%}'
typeset POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs'
typeset -a POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon dir newline vcs prompt_char )
typeset POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND=4
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
typeset -a POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES=( '*' DEFAULT )
typeset POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_BATTERY_VERBOSE=false
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
typeset POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=0
typeset POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=''
typeset POWERLEVEL9K_VPN_IP_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
typeset POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL=true
typeset POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
typeset POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
typeset POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=0
typeset POWERLEVEL9K_RVM_SHOW_GEMSET=false
typeset POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'
typeset -a POWERLEVEL9K_KUBECONTEXT_CLASSES=( '*' DEFAULT )
typeset POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=70
typeset POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi'
typeset POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=1
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset POWERLEVEL9K_CONTEXT_DEFAULT_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'
typeset POWERLEVEL9K_NODEENV_LEFT_DELIMITER=''
typeset POWERLEVEL9K_NORDVPN_CONNECTING_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_FOREGROUND=76
typeset POWERLEVEL9K_TIME_FOREGROUND=7
typeset POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=7
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=7
typeset POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=false
typeset POWERLEVEL9K_VI_INSERT_MODE_STRING=''
typeset POWERLEVEL9K_VCS_BRANCH_ICON=' '
typeset POWERLEVEL9K_RAM_FOREGROUND=3
typeset POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
typeset POWERLEVEL9K_STATUS_ERROR_BACKGROUND=''
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_LEFT_WHITESPACE=''
typeset POWERLEVEL9K_STATUS_OK=true
typeset POWERLEVEL9K_VI_VISUAL_MODE_STRING=VISUAL
typeset POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION=✘
typeset POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND=3
typeset POWERLEVEL9K_NORDVPN_DISCONNECTING_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=7
typeset POWERLEVEL9K_CONTEXT_SUDO_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_DIR_MAX_LENGTH=80
typeset -a POWERLEVEL9K_VCS_BACKENDS=( git )
typeset POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=76
typeset POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
typeset POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset POWERLEVEL9K_NORDVPN_DISCONNECTED_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -a POWERLEVEL9K_LUAENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_DIR_SHOW_WRITABLE=true
typeset POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=0
typeset POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=''
typeset POWERLEVEL9K_INSTANT_PROMPT=off
typeset POWERLEVEL9K_CONTEXT_REMOTE_TEMPLATE=%n@%m
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_CONTENT_EXPANSION=Ⅴ
typeset POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3
typeset POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
typeset POWERLEVEL9K_STATUS_ERROR=true
typeset POWERLEVEL9K_DIR_FOREGROUND=31
typeset POWERLEVEL9K_STATUS_OK_BACKGROUND=''
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=─
typeset POWERLEVEL9K_CONTEXT_BACKGROUND=0
typeset POWERLEVEL9K_TRANSIENT_PROMPT=always
typeset POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx'
typeset POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=%7F─╮
typeset POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=%7F─┤
typeset POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_NORDVPN_DISCONNECTED_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION=✔
typeset POWERLEVEL9K_CONTEXT_SUDO_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION=❮
typeset POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''
typeset POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset POWERLEVEL9K_SHORTEN_FOLDER_MARKER='(.bzr|.citc|.git|.hg|.node-version|.python-version|.ruby-version|.shorten_folder_marker|.svn|.terraform|CVS|Cargo.toml|composer.json|go.mod|package.json)'
typeset POWERLEVEL9K_CONTEXT_REMOTE_SUDO_TEMPLATE=%n@%m
typeset POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=0
typeset POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=''
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=%7F╭─
typeset POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=%7F├─
typeset POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_CONTENT_EXPANSION=▶
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND=196
typeset POWERLEVEL9K_NORDVPN_CONNECTING_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
typeset -a POWERLEVEL9K_RBENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_OS_ICON_BACKGROUND=''
typeset POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER=''
typeset POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_DISABLE_HOT_RELOAD=true
typeset POWERLEVEL9K_DIR_HYPERLINK=false
typeset POWERLEVEL9K_MIDNIGHT_COMMANDER_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
typeset POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM=-1
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
typeset POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=OVERTYPE
typeset POWERLEVEL9K_VCS_STAGED_MAX_NUM=-1
typeset POWERLEVEL9K_GOOGLE_APP_CRED_SHOW_ON_COMMAND='terraform|pulumi'
typeset POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED=false
typeset POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=%7F─╯
typeset POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1
typeset POWERLEVEL9K_VPN_IP_INTERFACE='(wg|(.*tun))[0-9]*'
typeset POWERLEVEL9K_BATTERY_LOW_FOREGROUND=1
typeset -a POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( background_jobs direnv virtualenv anaconda pyenv goenv nodenv nvm nodeenv rbenv rvm fvm luaenv jenv plenv kubecontext terraform aws aws_eb_env azure gcloud google_app_cred context nordvpn ranger nnn vim_shell midnight_commander vi_mode ram disk_usage todo battery newline status time )
typeset POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
typeset POWERLEVEL9K_NODEENV_RIGHT_DELIMITER=''
typeset POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
typeset -a POWERLEVEL9K_PLENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_VCS_CONFLICTED_MAX_NUM=-1
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_RIGHT_WHITESPACE=''
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION=✘
typeset POWERLEVEL9K_ANACONDA_LEFT_DELIMITER=''
typeset POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_EXPANSION='$(print_icon LOCK_ICON)'
typeset POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
typeset POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE=%n@%m
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%7F╰─ '
typeset POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset POWERLEVEL9K_DIRENV_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
typeset POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
typeset POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM=-1
typeset POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION=✔
typeset POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=3
typeset POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset POWERLEVEL9K_BATTERY_STAGES=
typeset POWERLEVEL9K_TIME_BACKGROUND=''
typeset POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=5
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=''
typeset POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
typeset POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=''
typeset POWERLEVEL9K_RAM_BACKGROUND=''
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_FOREGROUND=196
typeset POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=2
typeset POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM=-1
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=''
typeset POWERLEVEL9K_VI_MODE_FOREGROUND=0
typeset POWERLEVEL9K_STATUS_OK_PIPE=true
typeset POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=''
typeset POWERLEVEL9K_MODE=nerdfont-complete
typeset POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM=-1
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=''
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
typeset POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND=3
typeset POWERLEVEL9K_DISK_USAGE_BACKGROUND=''
typeset POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION=✘
typeset POWERLEVEL9K_VCS_LOADING_BACKGROUND=8
typeset POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
typeset POWERLEVEL9K_VIM_SHELL_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'
typeset POWERLEVEL9K_LOAD_WHICH=5
typeset POWERLEVEL9K_CONTEXT_FOREGROUND=3
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION=❮
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=196
typeset POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset -a POWERLEVEL9K_AWS_CLASSES=( '*' DEFAULT )
typeset POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
typeset POWERLEVEL9K_NODEENV_SHOW_NODE_VERSION=false
typeset POWERLEVEL9K_VI_COMMAND_MODE_STRING=NORMAL
typeset POWERLEVEL9K_STATUS_EXTENDED_STATES=true
typeset POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_CONTENT_EXPANSION=▶
typeset POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=''
typeset POWERLEVEL9K_DIR_BACKGROUND=''
typeset POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=3
typeset POWERLEVEL9K_NORDVPN_DISCONNECTING_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_ICON_BEFORE_CONTENT=''
typeset POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
typeset POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='%B${P9K_CONTENT}'
typeset POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform|pulumi'

**Comment by romkatv** [comment]
> Please post the output of `typeset -pm 'POWERLEVEL9K_*'`, a screenshot of your prompt and an explanation of what is wrong on the screenshot.

Thank you for posting your config. Please provide the remaining two bits of information I've asked for.

**Comment by jD4rk** [comment]
sorry i didn't read about that

<img width="1129" alt="Screenshot 2020-01-24 18 15 52" src="https://user-images.githubusercontent.com/8858312/73088990-a6771680-3ed5-11ea-8ebd-e88ea9de07f7.png">

according to some raw value injected into the original file (and as you can see from the three messages before the prompt coming from echo debug messages add into the code of p10k.zsh file)
I'm aspecting that the icon regard disk usage would be show with red color.....
but as per screen attached it's not!

**Comment by romkatv** [comment]
Thank you. I've fixed this bug some time ago in `worker` branch but it hasn't yet made it into `master`. I've cherry picked it now so that you don't have to wait until `worker` is merged.

I've also cherry picked https://github.com/romkatv/powerlevel10k/commit/8513fa63d951a202a0f22d040bc962f781f4fca1. This commit adds `disk_usage` to the standard config templates. If you update powerlevel10k and run `p10k configure`, you'll have all relevant `disk_usage` parameters already in `~/.p10k.zsh`. You'll only need to uncomment `disk_usage` segment to enable it.

> `POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=0`

Note that valid values for this parameter are `true` and `false`. If you specify any other value, you'll get something random.

**Comment by jD4rk** [comment]
alright, got it

I'll check out asap and check it out.

Thank for your super fast support
