### ISSUE TITLE
Can't remove VCS truncation

### ISSUE THREAD

**Issue by fylzero** [romkatv/powerlevel10k#437]
I have long branches like `feature/pay-576/reconciliation-reports` that appear as `feature/pay-…tion-reports`

I've tried adding and adjusting the Powerlevel9k values for this with no luck getting it to display the full branch names...

```
POWERLEVEL9K_VCS_SHORTEN_LENGTH=4
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=11
POWERLEVEL9K_VCS_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_VCS_SHORTEN_DELIMITER=".."
```

Not sure if this is a bug or if I am missing something in the config.  Any help appreciated.

**Comment by fylzero** [comment]
I figured out a workaround for now...  updated the 32 char limit to 120.

`
    # If local branch name or tag is at most 32 characters long, show it in full.
    # Otherwise show the first 12 … the last 12.
    (( $#where > 120 )) && where[13,-13]="…"
    res+="${clean}${where//\%/%%}"  # escape %
`

**Comment by romkatv** [comment]
From the [FAQ](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status):

> ### How do I change the format of Git status?
> 
> To change the format of Git status, open `~/.p10k.zsh`, search for `my_git_formatter` and edit its
> source code.

If you want to truncate branch name only when it's over 120 characters long, then your edit is the way to go.

If you have a config for powerlevel9k that you like, you can use it and it'll work just like in powerlevel9k. All parameters, including `POWERLEVEL9K_VCS_SHORTEN_*`, are supported. What you cannot do is to take some existing config and assume that defining one *extra* parameter will have the same effect as if this was the *only* defined parameter. For example, if `POWERLEVEL9K_HISTORY_BACKGROUND=blue` is the only `POWERLEVEL9K_*` parameter, it makes `history` prompt segment blue. However, if you define this parameter *in addition* to `POWERLEVEL9K_DISABLE_RPROMPT=true`, it won't have any effect. In other words, there may be interactions between different parameters.
