### ISSUE TITLE
Transient prompt stops working after desktop wakes from sleep 

### ISSUE THREAD

**Issue by paanvaannd** [romkatv/powerlevel10k#439]
* **OS info**:
  * Linux Mint 19.3 Cinnamon
  * Cinnamon version 4.4.8
  * Linux Kernel 5.0.0-37-generic
* **Terminal**: GNOME Terminal version 3.28.1
* **Shell**: zsh 5.4.2

p10k was configured using the `$ p10k configure` option to use the transient prompt feature. The feature works fine for the most part except that it stops working after my computer wakes from sleep. After that point, the prompt persists as usual, even after sourcing .zshrc once again.

The only way to get the transient prompt feature to work again is to either re-run `$ p10k configure` and select the same options once again or close the current window and open a new one.

**Comment by romkatv** [comment]
Typing `source ~/.zshrc` is almost always a very bad idea. If you want to restart zsh with little effort, use `exec zsh`.

Powerlevel10k doesn't hook into sleep/wake. If it gets affected by sleep/wake, please file a bug against your OS and/or hardware provider.

**Comment by romkatv** [comment]
By the way, if you type `source ~/.zshrc` (even without going to sleep), it can break transient mode. It can break many things in fact.

**Comment by paanvaannd** [comment]
> It can break many things in fact.

I wasn't aware of that! Thanks.

> Powerlevel10k doesn't hook into sleep/wake.

Ah, right.

> If it gets affected by sleep/wake, please file a bug against your OS and/or hardware provider.

Perhaps also something specific to GNOME Terminal? I'll try using a different emulator and see if that changes things. If not, then I'll file a bug against the OS or hardware provider.

Thanks!

**Comment by romkatv** [comment]
> Perhaps also something specific to GNOME Terminal?

Dunno. You are the first person to report this. I've used GNOME terminal myself for a long time -- no issues. It's difficult even to imagine how powerlevel10k could even in theory be affected by sleep/awake. It's just a plain zsh script. Before you report bugs anywhere else, double check that your report is factually correct.

**Comment by paanvaannd** [comment]
> Before you report bugs anywhere else, double check that your report is factually correct.

Do you have any suggestions as to how to better do this? So far as I knew when reporting the bug, my report was "factually correct" (I am not a developer, just a hobbyist trying to learn).

The only thing that was broken in the emulator for me was the transient prompt feature; nothing else. This only happened after a sleep/wake cycle, so I presumed this was a bug in the transient prompt feature given that it was the only thing that was acting up.

So, other than checking the interaction of p10k after a sleep/wake cycle with another terminal emulator and seeing if it doesn't work properly there, what else could I do to narrow down where the issue arises from?

**Comment by romkatv** [comment]
Just to clarify, I'm not saying that your report is factually incorrect. It's just very implausible. If you decide to report it somewhere, it's a very good idea to verify what what you describe is indeed true. Also try your bug report look in a way that shows that you've done the work at least to convince yourself about the truthiness of the bug report. I'm not talking about lying or deception here. The question is a matter of precise description that would allow others to replicate your results.

A good bug report describes a reproducible procedure which, when followed, leads to unexpected results. It's generally the job of the reported to ensure that every step and detail relevant for the reproduction of the unexpected result is included in the bug report, and everything irrelevant excluded.

From your original bug report I can infer the following procedure:

1. Install the following software on any laptop (Linux Mint 19.3 Cinnamon, zsh 5.4.2, powerlevel10k, etc.).
2. Type `p10k configure` and enable instant prompt.
3. Enter sleep mode.
4. Wake the laptop.
5. Observe: instant prompt is broken (unexpected).

Try to reproduce it yourself 3 times. If it always reproduces, reboot and again reproduce 3 times. If it always reproduces, start removing things to see what's relevant. E.g., if your `~/.zshrc` sources *anything* besides powerlevel10k, turn it off to see if it's relevant. Try another terminal. Try newer version of zsh, etc.
