### ISSUE TITLE
"command not found" when loading via Antigen

### ISSUE THREAD

**Issue by DomParfitt** [romkatv/powerlevel10k#440]
I have added P10k to my `zshrc` using `antigen` and now when I try to use `zsh` I get the following output any time I press a key:
```
(eval):2: command not found: -a
(eval):3: command not found: -i
(eval):4: command not found: MATCH
```

This was working fine for me yesterday but on a fresh build today it's giving me the above error. I have tried deleting my `p10k.zsh` file and removing any reference to it in my `zshrc` but this has not helped. The issue seems to come from running `antigen theme romkatv/powerlevel10k` either via `zshrc` or directly in the shell.

**Comment by romkatv** [comment]
That's awful.

Does it work if you load powerlevel10k without antigen? See https://github.com/romkatv/powerlevel10k/blob/master/README.md#manual.

**Comment by DomParfitt** [comment]
Doing it manually gives me a similar but slightly different error on the initial load of the shell but then the theme loads as expected and there are no more errors:
```
(anon):2: command not found: -a
(anon):3: command not found: -i
(anon):4: command not found: MATCH
```

**Comment by romkatv** [comment]
The initial errors are still from antigen. Antigen has a few bugs that interfere with anything that it loads. In this case p10k defines the following parameter:

```zsh
typeset -gr __p9k_intro='emulate -L zsh -o no_hist_expand -o extended_glob -o no_prompt_bang -o prompt_percent -o no_prompt_subst -o no_aliases -o no_bg_nice -o typeset_silent
local -a match mbegin mend reply
local -i MBEGIN MEND OPTIND
local MATCH REPLY OPTARG IFS=$'\'' \t\n\0'\''
[[ -z $_p9k_locale ]] || local LC_ALL=$_p9k_locale'
```

Note that this parameter is readonly, so it cannot be changed after the definition. If you try to print it after you load p10k with antigen, you'll notice that the value of this parameter is actually different. It's missing some instances of `local`. This is happening because Antigen is manually patching source code of plugins for reasons unknown to me.

I'll try to find a workaround but I cannot promise anything.

**Comment by DomParfitt** [comment]
No problem. Thanks for the quick response. 

I'll raise an issue with Antigen as well, see if it's something they can patch on their end.

**Comment by romkatv** [comment]
This is the code in Antigen that breaks p10k: https://github.com/zsh-users/antigen/blob/f5038faf456b412ef06cd17c6ae76404846d2c7e/src/lib/load.zsh#L84-L86.

A few examples of things that it breaks:

```zsh
local -i n=42

echo "foo() {
local -i n=42
}"
```

In both cases `local` gets removed by Antigen.

I've added a workaround to p10k (leading spaces before `local`). Please update and try again.

**Comment by DomParfitt** [comment]
@romkatv Thanks! Your workaround worked once I cleared out my Antigen cache.

Thanks again for the speedy response, really appreciate it.

**Comment by romkatv** [comment]
Thanks for reporting the issue and for confirmed that the fix is working.
