### ISSUE TITLE
tmux os_icon color/invisible

### ISSUE THREAD

**Issue by cubimon** [romkatv/powerlevel10k#446]
The os icon inside tmux is just white. Ofc low priority, has someone a suggestion?
![image](https://user-images.githubusercontent.com/3812715/73299678-eb6db680-420f-11ea-8ab6-38072855d6d8.png)

**Comment by cubimon** [comment]
nevermind, adding `set -g default-terminal "xterm-256color"` to `~/.tmux.conf` resolved this

**Comment by laishulu** [comment]
I have the same problem, but
`set -g default-terminal "xterm-256color"` does not work
