### ISSUE TITLE
Allow configuration of separator in background_jobs segment

### ISSUE THREAD

**Issue by ifreund** [romkatv/powerlevel10k#447]
I'd like to be able to get rid of the space between the icon and the job count such that my prompt would show `+1` instead of the current `+ 1` seen in the screenshot.

![image](https://user-images.githubusercontent.com/12723818/73396673-29d3a600-42e2-11ea-8e98-7d2a32bdeed4.png)

The most straightforward way I see of making this configurable would be a new `POWERLEVEL9K_BACKGROUND_JOBS_SEPARATOR` option defaulting to the current `' '`.

**Comment by romkatv** [comment]
Does this do what you want?

```zsh
# Show the number of background jobs.
POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
# Show the number of background jobs as `+N`.
POWERLEVEL9K_BACKGROUND_JOBS_CONTENT_EXPANSION='+${P9K_CONTENT:-1}'
# Hide the icon when there are background jobs.
POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION=
```

**Comment by ifreund** [comment]
Yes it does! Thank you so much.

Is there documentation for this `_CONTENT_EXPANSION` thing anywhere? I wasn't able to find any but may have missed something obvious. It seems super powerful, does it work with every segment?

**Comment by romkatv** [comment]
By the way, this prompt segment is so simple, you can just implement it yourself. Here's a complete implementation:

```zsh
prompt_my_jobs() p10k segment -f 70 -c '${${(%):-%j}:#0}' -e -t '+${(%):-%j}'
```

Now you can use `my_jobs` as a regular segment.

Just one line and no need to hunt those obscure parameters. Type `p10k help segment` if you haven't used it.

**Comment by ifreund** [comment]
Very cool, I'm going to go ahead and close this as it turns out what I wanted is already well supported in 3 separate ways.  Thanks for your work on this awesome prompt, I clearly still have much to learn about it.

**Comment by romkatv** [comment]
> Thanks for your work on this awesome prompt

Thanks! Docs are lagging very much behind the implementation. Improving them is currently my main focus. There should be great progress on this front within the next few weeks.
