### ISSUE TITLE
Feature request: add nix-shell prompt element.

### ISSUE THREAD

**Issue by magnetophon** [romkatv/powerlevel10k#448]
I tried to prepare a PR for this, based on the nnn commit, but I failed to get it working.
There is a handy env var to check, that nix-shell sets itself: IN_NIX_SHELL.

Thank for the great prompt!

**Comment by romkatv** [comment]
Done. The new segment is called `nix_shell`. It's enabled by default in configs generated by `p10k configure`. Please check if it works for you.

**Comment by magnetophon** [comment]
Wow, that was quick!
Works perfectly, thanks a lot!

**Comment by romkatv** [comment]
Thanks for the verification. Closing.

**Comment by vimpostor** [comment]
BTW the distinction in displaying `pure` and `impure` is completely useless. Users will only ever see the case with `impure`, as powerlevel10k will never see the light of day in `pure` mode. Also see the discussion in: https://discourse.nixos.org/t/how-to-tell-whats-making-a-flake-impure-inherit-macos-security/26105/4

> You traditionally do this by nix-shell --pure. It won’t inherit your PATH, HOME, USER, etc.
> Whenever you run that it is very unlikely that you get a zsh with p10k. So if you enter a pure shell, you probably will never get told this by your p10k prompt.

So maybe in hindsight it would have made more sense to make only showing the Nix icon the default, which can now be achieved with:
```zsh
typeset -g POWERLEVEL9K_NIX_SHELL_CONTENT_EXPANSION=
```
