### ISSUE TITLE
Gaps between prompt segments

### ISSUE THREAD

**Issue by itsthecheat** [romkatv/powerlevel10k#449]
I've looked everywhere to try and solve this problem but can't seem to get rid of these gaps. I'm using Hyper Terminal with Oh My Zsh. I went through the configuration, and made sure to install and add the recommended font in hyper. 

![Screen Shot 2020-01-30 at 6 13 59 PM](https://user-images.githubusercontent.com/17536124/73498818-60fe9180-438c-11ea-94e5-c7b3e0a64cd4.png)

I also did some tests with the following results:
![Screen Shot 2020-01-30 at 8 31 50 PM](https://user-images.githubusercontent.com/17536124/73505157-ac6e6b00-439f-11ea-9ed8-da15f14796e7.png)

**Comment by romkatv** [comment]
Could you clarify what you believe is wrong on the provided screenshots? What gaps are you referring to?

**Comment by romkatv** [comment]
If you are referring to sub-pixel gaps between prompt segments and powerline connections, please see https://github.com/romkatv/powerlevel10k/blob/master/README.md#sub-pixel-imperfections-around-powerline-symbols. Does it help?

**Comment by itsthecheat** [comment]
Yep, referring to the sub-pixel gaps. I changed the font size to 13 in Hyper and that fixed it. It's just not super ideal as the icons are already much smaller than the text. However, everything looks good using iTerm, including icons being a better size even though font and size are the same.
Hyper
![Screen Shot 2020-01-31 at 12 57 09 PM](https://user-images.githubusercontent.com/17536124/73562543-5a722780-4429-11ea-830b-8e3775cce3b5.png)
vs. iTerm
![Screen Shot 2020-01-31 at 12 57 15 PM](https://user-images.githubusercontent.com/17536124/73562585-6d84f780-4429-11ea-9ca1-2194528ddb0f.png)

I guess it's just something I'll have to play around with, thanks for your help!

**Comment by romkatv** [comment]
If you are on macOS, try iTerm2. It's very good.

**Comment by JagsterTheP** [comment]
I'm also struggling with the same problem in XFCE4 Terminal where only the Right arrow triangle segment is doing the problem.
