### ISSUE TITLE
[feature] Option for showing LAN IP

### ISSUE THREAD

**Issue by kevdogg** [romkatv/powerlevel10k#451]
Hi - I really like p10k.

You have an option for public_IP however wondering if you could add a context for LAN_IP

**Comment by Syphdias** [comment]
Did you try the `ip` segment? `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ip)`

**Comment by romkatv** [comment]
> Did you try the `ip` segment? `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ip)`

This should work.

This segment isn't exposed through `~/.p10k.zsh` because I don't know what purpose it serves. @kevdogg, could you share why you want to see LAN IP in prompt?

Here are the relevant parameters that affect `ip`. You can copy them to `~/.p10k.zsh`.

```zsh
# LAN IP foreground color.
typeset -g POWERLEVEL9K_IP_FOREGROUND=0

# LAN IP background color.
typeset -g POWERLEVEL9K_IP_BACKGROUND=6

# Regular expression for the network interface name from which LAN IP is extracted.
# Type `ifconfig || ip -4 a show` to see all available network interfaces.
typeset -g POWERLEVEL9K_IP_INTERFACE='.*'
```

You *must* override `POWERLEVEL9K_IP_INTERFACE` for `ip` segment to make any sense. If you keep the default value of `.*`, you'll see IP from a random network interface. It could be loopback, LAN, VPN or WAN. Definitely not what you want.

**Comment by kevdogg** [comment]
Ok just to  be clear.  Finding the active network interface - really complicated since ifconfig returns something very different on iOS vs linux.  So to dumb down the problem, assuming I know the active interface is eth0 (rather than having some complicated script figure out the active interface -- as it's possible -- and I've done -- but methods vary depending on OS), I usually just find the LAN IP via:
ifconfig eth0 | grep -w 'inet' | awk 'NR == 1 { print $2 }'| cut -d : -f2

Are you saying all I need to do in this case is have something like:
typeset -g POWERLEVEL9K_IP_INTERFACE='eth0'

**Comment by romkatv** [comment]
> Are you saying all I need to do in this case is have something like:
> typeset -g POWERLEVEL9K_IP_INTERFACE='eth0'

You need to open `~/.p10k.zsh`, add `ip` either to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` and define these parameters in the same file:

```zsh
# LAN IP foreground color.
typeset -g POWERLEVEL9K_IP_FOREGROUND=0

# LAN IP background color.
typeset -g POWERLEVEL9K_IP_BACKGROUND=6

# Regular expression for the network interface name from which LAN IP is extracted.
# Type `ifconfig || ip -4 a show` to see all available network interfaces.
typeset -g POWERLEVEL9K_IP_INTERFACE='eth0'
```

Adjust foreground/background colors as you like. If your prompt has no background color, do not define `POWERLEVEL9K_IP_BACKGROUND`.

> @kevdogg, could you share why you want to see LAN IP in prompt?

Could you answer this question :point_up: ?

**Comment by kevdogg** [comment]
Why do I want to see LAN IP in prompt?? Honestly I'm doing a lot of changes to my network defining VLANs and such and I have a lot of iterm2 terminals open to various VM's and jails -- either citrix vms or freenas jails/VMs.  Honestly sometimes I get confused what window goes with what machine.  It would nice in these situations to just have the LAN IP for easy reference

**Comment by romkatv** [comment]
Why not hostname?

**Comment by kevdogg** [comment]
Hostname is how I try to configure most things, but oftentimes I need to setup alias for example that tie the hostname to an IP address.   Also in setting up the VLANs sometimes I can ping hosts on the network by IP but due to some error on my part the names are resolving because of a misconfigured DNS option.

**Comment by romkatv** [comment]
Got it. Thanks for the explanation!

Did the parameters work for you?

**Comment by kevdogg** [comment]
Yes it did -- it was rather easy.  Only going to nitpick but its not a big deal.  eth0 is wired and the icon associated with it is a wireless icon.  Again not that big of deal.

**Comment by romkatv** [comment]
> Yes it did -- it was rather easy.

Thanks for the confirmation.

> Only going to nitpick but its not a big deal. eth0 is wired and the icon associated with it is a wireless icon. Again not that big of deal.

You can change. Try this:

```zsh
typeset -g POWERLEVEL9K_IP_VISUAL_IDENTIFIER_EXPANSION=$'\uF700'
```

Or this:

```zsh
typeset -g POWERLEVEL9K_IP_VISUAL_IDENTIFIER_EXPANSION=$'\uF6FF'
```

**Comment by jordantrizz** [comment]
Hello, sorry to raise the dead here, just thinking out loud here.

When running p10k on multiple hosts you might have different interface names. If you target eth0 then you're correct 80% of the time. But what about instances where vmbr0 exists? Should the interfaces be enumerated and checked which one has a private network? In the case of a docker host, you might have multiple br-* interfaces on 172.16.0.0/12.

Would it be worth overbuilding this?

Found this thread on StackOverflow https://stackoverflow.com/questions/13322485/how-to-get-the-primary-ip-address-of-the-local-machine-on-linux-and-os-x

Perhaps this would work?

```
typeset -g POWERLEVEL9K_IP_INTERFACE=$(ip -o route get to 8.8.8.8 | awk {' print $5 '})
```

**Comment by romkatv** [comment]
> Perhaps this would work?
> 
> ```
> typeset -g POWERLEVEL9K_IP_INTERFACE=$(ip -o route get to 8.8.8.8 | awk {' print $5 '})
> ```

If you like what this does, go ahead and use it.

**Comment by jordantrizz** [comment]
> If you like what this does, go ahead and use it.

It's been working well so far for Linux but obviously doesn't work for macOS, so I was looking through your code to see if there was any operating system detection and found $_p9k_os, but it's not initialized during sourcing .p10k.zsh so this fails. Any ideas?

```
    if [[ ${_p9k_os} == "OSX" ]]; then
        typeset -g POWERLEVEL9K_IP_INTERFACE=$(route get 8.8.8.8 | awk '/interface:/{print $2}')
    else
        typeset -g POWERLEVEL9K_IP_INTERFACE=$(ip -o route get to 8.8.8.8 | awk {' print $5 '})
    fi
```

**Comment by romkatv** [comment]
This is how you do things conditionally based on the OS:

```zsh
case $OSTYPE in
  darwin*)
    echo "This is macOS"
  ;;
  linux*)
    echo "This is Linux"
  ;;
  *)
    echo "This is something else"
  ;;
esac
```

This is not specific to Powerlevel10k.

**Comment by jordantrizz** [comment]
> This is not specific to Powerlevel10k.

I was curious how you would implement it, didn't know if you had OS detection already with a p10k variable.

For anyone else this is what I ended up using and it works well.

```
    # Set IP interface
    case $OSTYPE in
    darwin*)
        typeset -g POWERLEVEL9K_IP_INTERFACE=$(route get 8.8.8.8 | awk '/interface:/{print $2}')
    ;;
    linux*)
        typeset -g POWERLEVEL9K_IP_INTERFACE=$(ip -o route get to 8.8.8.8 | awk {' print $5 '})
    ;;
    *)
        typeset -g POWERLEVEL9K_IP_INTERFACE='eth0'
    ;;
    esac
```
