### ISSUE TITLE
[feature] vcs separate segments

### ISSUE THREAD

**Issue by dennis-tra** [romkatv/powerlevel10k#452]
Hi,

currently I'm using https://github.com/b-ryan/powerline-shell as my terminal shell but the performance of powerlevel10k is much better so I'm considering to switch. 

I really like about my current prompt that it has separately colored segments for commits ahead/behind, staged and untracked files. See this screenshot:
<img width="783" alt="1__dennistrautwein_Denniss-MBP____freiheit_golang_src_git_daimler_com_risingstars_apptwin-service" src="https://user-images.githubusercontent.com/11836793/73580225-0eed6700-4485-11ea-8b42-586a7b69ff2e.png">

I had a thorough look through the plenty customization options but couldn't find a way to rebuild the above prompt.

Can you help me out by creating such a prompt?

Thanks a lot in advance

**Comment by romkatv** [comment]
Here's an approximation. I don't know what the colors or icons are on the screenshot, so I used placeholders. This should let you get started.

```zsh
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs my_vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_VCS_CONTENT_EXPANSION=
POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION=
POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=
POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true

function prompt_my_vcs() {
  emulate -L zsh
  [[ $VCS_STATUS_RESULT == ok-* ]] || return

  if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
    p10k segment -f 7 -b 206 -t ${VCS_STATUS_LOCAL_BRANCH//\%/%%}
  else
    p10k segment -f 7 -b 206 -t @${VCS_STATUS_COMMIT[1,8]//\%/%%}
  fi

  (( VCS_STATUS_COMMITS_AHEAD  )) && p10k segment -f 7 -b 8 -t 'arrow-up'
  (( VCS_STATUS_COMMITS_BEHIND )) && p10k segment -f 7 -b 8 -t 'arrow-down'
  (( VCS_STATUS_NUM_UNSTAGED   )) && p10k segment -f 7 -b 214 -t 'pencil'
  (( VCS_STATUS_NUM_UNTRACKED  )) && p10k segment -f 7 -b 1 -t '?'
}
```

**Comment by dennis-tra** [comment]
Thanks @romkatv for the quick response. 

I've added your snippet to my `.p10k.zsh` (replaced the `my_git_formatter` content) and now I get the following error message:
```
[ERROR] p10k segment: can be called only during prompt rendering.
```
However the prompt that gets also rendered looks almost perfect. Thanks!

I presume that I didn't add the snippet in the right location. Could you give me another hint in the right direction?

**Comment by romkatv** [comment]
If you are patching `~/.p10k.zsh`, follow these steps.

1. Add `my_vcs` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`. Put it right after `vcs`.
2. Remove all parameters related to `vcs` including `my_git_formatter`. This section must be gone: https://github.com/romkatv/powerlevel10k/blob/b6cb9618a873ec0392c816a8d6e1e9fd4aa6adac/config/p10k-rainbow.zsh#L337-L443
3. Add the following code where you've just deleted a lot of stuff:
```zsh
####################################[ my_vcs: git status ]####################################
typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION=
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=
typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true

function prompt_my_vcs() {
  emulate -L zsh
  [[ $VCS_STATUS_RESULT == ok-* ]] || return

  if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
    p10k segment -f 7 -b 206 -t ${VCS_STATUS_LOCAL_BRANCH//\%/%%}
  else
    p10k segment -f 7 -b 206 -t @${VCS_STATUS_COMMIT[1,8]//\%/%%}
  fi

  (( VCS_STATUS_COMMITS_AHEAD  )) && p10k segment -f 7 -b 8   -t 'arrow-up'
  (( VCS_STATUS_COMMITS_BEHIND )) && p10k segment -f 7 -b 8   -t 'arrow-down'
  (( VCS_STATUS_NUM_UNSTAGED   )) && p10k segment -f 7 -b 214 -t 'pencil'
  (( VCS_STATUS_NUM_UNTRACKED  )) && p10k segment -f 7 -b 1   -t '?'
}
```
4. Customize `prompt_my_vcs` as needed. See the original `my_git_formatter` for a subset of `VCS_STATUS_*` parameters that are available. The full list is documented at https://github.com/romkatv/gitstatus/blob/master/gitstatus.plugin.zsh.

**Comment by dennis-tra** [comment]
Amazing, thanks for the fast reply!

**Comment by TrentonAdams** [comment]
@dennis-tra did you ever replicate close to what powerline-shell had?

**Comment by romkatv** [comment]
@TrentonAdams My first comment on this issue replicates the screenshot exactly modulo colors and (which I cannot infer from screenshot and which you can easily change).

**Comment by TrentonAdams** [comment]
@romkatv Oh, on mine the colors came up all weird when I tried your script.  Also, the screenshot doesn't show all variations of powerline-shell.

So it's...

1. Not showing number of added files
2. Not showing number of commits that need to be pushed
3. Not showing number of commits that need to be pulled
4. Not showing the the icons they used
5. Not showing green status on the branch name (development) when there's no changes, it shows pink.

So yeah, just hoping if he did the work to make it look the same then he could share. 😄 

![image](https://user-images.githubusercontent.com/534192/121417580-4dbbe880-c927-11eb-8269-91b10b41bdc7.png)

**Comment by romkatv** [comment]
> @romkatv Oh, on mine the colors came up all weird when I tried your script.

You can change colors. It's not rocket science.

> 1. Not showing number of added files
> 2. Not showing number of commits that need to be pushed
> 3. Not showing number of commits that need to be pulled

Just like on the scrrenshot. You can trivially change that.

> 4. Not showing the the icons they used

You can trivially change the icons.

> 5. Not showing green status on the branch name (development) when there's no changes, it shows pink.

Ditto.

> So yeah, just hoping if he did the work to make it look the same then he could share. 😄

Alright.

**Comment by TrentonAdams** [comment]
This worked for me, but I'm finding issues with it...

```zsh
####################################[ my_vcs: git status ]####################################
typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION=
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=
typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true

function prompt_my_vcs() {
  emulate -L zsh
  [[ $VCS_STATUS_RESULT == ok-* ]] || return

  if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
    p10k segment -f 0 -b 2 -t ${VCS_STATUS_LOCAL_BRANCH//\%/%%}
  else
    p10k segment -f 0 -b 2 -t @${VCS_STATUS_COMMIT[1,8]//\%/%%}
  fi

  echo num-untracked: $(($VCS_STATUS_NUM_UNTRACKED))
  (( VCS_STATUS_COMMITS_AHEAD  )) && p10k segment -f 0 -b 7   -t "⬆+${VCS_STATUS_COMMITS_AHEAD}"
  (( VCS_STATUS_COMMITS_BEHIND )) && p10k segment -f 0 -b 7   -t "⬇+${VCS_STATUS_COMMITS_BEHIND}"
  (( VCS_STATUS_NUM_UNSTAGED   )) && p10k segment -f 0  -b 214 -t "✎+${VCS_STATUS_NUM_UNSTAGED}"
  (( VCS_STATUS_NUM_STAGED     )) && p10k segment -f 2  -b 0   -t "✔+${VCS_STATUS_NUM_STAGED}"
  (( VCS_STATUS_NUM_UNTRACKED  )) && p10k segment -f 7  -b 1   -t "?+${VCS_STATUS_NUM_UNTRACKED}"
}

```

I run the following....
```zsh
touch blah{1..8} && git reset --hard HEAD^^ && git add blah1 blah2 && git commit -m 'blah1 blah2' && git add blah3 blah4 && git commit -m 'blah3 blah4' && git add blah5 blah6 ; echo hello >> .gitignore; echo hello >> README.md
```

And the output is correct for the commits ahead/behind statuses, but not the other ones...

Notice how there should be 2 for each status, not just one, yet unstaged, staged, and untracked, all show.

![image](https://user-images.githubusercontent.com/534192/121990585-3c297500-cd5b-11eb-8832-49b713abd132.png)

**Comment by romkatv** [comment]
@TrentonAdams Add this:

```zsh
# Enable counters for staged, unstaged, etc.
typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1
```

**Comment by TrentonAdams** [comment]
Worked perfectly, thank you!
