### ISSUE TITLE
Incompatability with SH_WORD_SPLIT set

### ISSUE THREAD

**Issue by aperum** [romkatv/powerlevel10k#453]
Since commit a971536 setting SH_WORD_SPLIT in zshrc to be compatible with sh produces multiple eval errors with each prompt and once with each entered char:

`(eval):1: bad pattern: [[`
`(eval):1: bad pattern: [[`
`(eval):1: bad pattern: [[`
`(eval):1: bad pattern: [[`
`(eval):1: bad pattern: [[`
`(eval):1: bad pattern: [[`
`machine|user>`
`(eval):1: bad pattern: [[`

This seems to be a result of the removal of the IFS handling in the code i think.

**Comment by romkatv** [comment]
Sorry about that. A silly bug on my part. I should know better. Fixed.

Thanks for the report!
