### ISSUE TITLE
diamond (rotated square) not showing 

### ISSUE THREAD

**Issue by jatin-cbs** [romkatv/powerlevel10k#455]
Other things like icons and everything is working I have installed Hack nerdfont.  Just the diamond does not show which limits my option selection in pk10 configure.
![Screenshot from 2020-02-03 07-52-45](https://user-images.githubusercontent.com/40650341/73621008-6a248280-465a-11ea-8d5f-25a2bb18d2f2.png)

**Comment by jatin-cbs** [comment]
I was able to see diamond before but i think an oh my zsh update caused something :( any dependency needed ? because I have tried many nerdfonts and I am sure its not a font problem.

**Comment by romkatv** [comment]
The problem is caused by your terminal using a font without powerline glyphs.

From Powerlevel10k troubleshooting: [Icons, glyphs or powerline symbols don't render](https://github.com/romkatv/powerlevel10k/blob/master/README.md#icons-glyphs-or-powerline-symbols-dont-render):

> Restart your terminal, [install the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#meslo-nerd-font-patched-for-powerlevel10k) and run `p10k configure`.

Please try this. Note that there is no point in trying other fonts. Powerline symbols are either present in a font or missing. They are present in the recommended font. If your terminal doesn't display powerline glyphs, it's not using the recommended font.

**Comment by jatin-cbs** [comment]
@romkatv but I am using patched fonts which are recommended all the icons are working except the diamond which causes less option, so you mean recommended fonts dont work correctly?

**Comment by romkatv** [comment]
> so you mean recommended fonts dont work correctly?

This is possible but very unlikely. Besides, you've already tried other fonts, and you still couldn't see the diamond, right?

You can reproduce this issue without powerlevel10k. Run the following command either in Zsh or Bash:

```zsh
echo -e '\uE0B2\uE0B0'
```

If it doesn't print diamond, your terminal cannot display powerline symbols. Please consult your terminal, OS or window manager documentation.

By the way, the font on your screenshot is clearly not the recommended font. Digits look different.

**Comment by crs1138** [comment]
I too have all the other icons working except for the diamond… How bizarre? 

* Ubuntu 20 on VM
* Terminal / Terminator
![image](https://user-images.githubusercontent.com/1313681/104452180-eb8ecf80-55a2-11eb-8f05-092bf1884faf.png)
![image](https://user-images.githubusercontent.com/1313681/104452247-02cdbd00-55a3-11eb-8bab-821d3984c399.png)

**Comment by romkatv** [comment]
@crs1138 The font on your screenshot is definitely not MesloLGS NF. Look at "i" for example and compare it with "i" here:

![p10k with meslo](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-styles-high-contrast.png)

You can solve your issue by following the FAQ entry [Icons, glyphs or powerline symbols don't render](https://github.com/romkatv/powerlevel10k/blob/master/README.md#icons-glyphs-or-powerline-symbols-dont-render):

> Restart your terminal, [install the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#meslo-nerd-font-patched-for-powerlevel10k) and run `p10k configure`.

**Comment by crs1138** [comment]
You're right it wasn't the right font. The confusing part was that the other icons were showing. 

*I managed to fix that by setting Meslo Nerd as the preferred font for the current profile in the Terminal preferences.*

Perhaps that could be made more prominent in the documentation.

**Comment by romkatv** [comment]
> Perhaps that could be made more prominent in the documentation.

How could it be made more prominent in the documentation? And would it have helped you? You've found the issue that describes your problem and links to the FAQ entry with the solution in the very first comment. You've left a "me too" comment on the issue instead of applying the solution.

**Comment by crs1138** [comment]
Nevermind, your code is perfect. Carry on, pat on the back.
