### ISSUE TITLE
prompt shifts to the left on tab completion

### ISSUE THREAD

**Issue by magnus-gross** [romkatv/powerlevel10k#458]
First of all thank you very much for this awesome project, this is by far the best zsh framework and I have tried a lot of them!

I think I might have found a bug, but it might also be just my configuration because I use many non-default settings.

If I type a command and press Tab to autocomplete it, the entire line shifts to the left, making the first character unreachable and thus creating the illusion that the first character was typed twice (although it wasn't).
See the following recording, where it visually shows `eecho`, but I typed `echo` and then Tab.

https://asciinema.org/a/7LgF1MP6r44Z6rZoXMX6Zq6Vb

Here is my configuration:
https://github.com/magnus-gross/dotfiles/blob/495d94aaac0b285bbe9320a3f2d723616ddc3b4b/zsh/.zshrc

I am using `zsh 5.7.1` and p10k at fab13389f17b1dc08f080bef4e0143f3d59d104c.

**Comment by romkatv** [comment]
Have you tried following this troubleshooting guide? https://github.com/romkatv/powerlevel10k/blob/master/README.md#cursor-is-in-the-wrong-place

**Comment by magnus-gross** [comment]
Well yes, if I use `unset ZLE_RPROMPT_INDENT`, the problem is fixed. But I don't want that extra character, so I intentionally set `ZLE_RPROMPT_INDENT`.
If this is a problem with zsh itself, I understand, but I would prefer to have the prompt like it is with `ZLE_RPROMPT_INDENT` set.

**Comment by romkatv** [comment]
Yes, this is a bug in zsh. You'll get the same behavior if you type `zsh -df` and then paste this:

```zsh
PS1='> '
RPS1='<'
ZLE_RPROMPT_INDENT=0
```

Now type `ls` followed by TAB. The cursor has jumped.

Powerlevel10k can work around this bug but not in all configurations. In some it's simply impossible.

It's not even one bug in zsh but several. I've fixed them some time ago and soon the fixes will make their way into the next release (5.8). If you don't want to wait, you can build zsh from source or grab a compiled beta binary for 5.8 release candidate.

**Comment by romkatv** [comment]
By the way, I'd move `typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet` together with other parameters. It just looks neater. It'll also avoid the misleading appearance as if this parameter had to be defined above. Technically, it will also make instant prompt appear faster but we are talking microseconds, so it's doesn't matter.

**Comment by magnus-gross** [comment]
Yeah, I moved it there for performance reasons, but you are probably right.
Thanks so much for fixing this bug in zsh itself, that's awesome!

I guess, i will just wait for zsh 5.8 then.

**Comment by romkatv** [comment]
I think it might be possible to extend the workaround to cover your config. I'm not sure yet. I'll reopen and double-check when I get to my dev machine.

> Yeah, I moved it there for performance reasons

The more code you have above the instant prompt preamble, the *longer* it takes for instant prompt to appear. If you put all parameters together, instant prompt will appear faster.

**Comment by romkatv** [comment]
Fixed. Your config should now work with `ZLE_RPROMPT_INDENT=0` even in the presence of zsh bugs.
