### ISSUE TITLE
Battery segment doesn't display on ChromeOS

### ISSUE THREAD

**Issue by extremepayne** [romkatv/powerlevel10k#461]
My config was newly generated and I have made no substantial changes. Here's the header:
```
# Generated by Powerlevel10k configuration wizard on 2020-02-03 at 11:38 MST.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh, checksum 60909. 
# Wizard options: nerdfont-complete + powerline, small icons, lean, time, 2 lines,
# dotted, left frame, lightest-ornaments, sparse, few icons, concise, transient_prompt.
```
I uncommented the battery segment but it's not showing. (Previous commands are mostly to assure myself I didn't do something stupid like forget to save the file).
![image](https://user-images.githubusercontent.com/46696318/73692312-51838f00-4691-11ea-90d8-ae67073ec0d5.png)
This is on ChromeOS using the default "Linux (Beta)" feature (I don't know what it's properly called--is it Crostini?).

Perhaps the fact that this is within some kind of VM precludes the possibility of displaying battery? If it's possible at all, I would appreciate it.

OS: ChromeOS 79.0.3945.123 (Official Build) (32-bit)
VM's OS: Debian 9 (Strech)
Terminal emulator: Default for "Linux (Beta)" feature
Zsh version: zsh 5.3.1 (aarch64-unknown-linux-gnu)

**Comment by romkatv** [comment]
I've an old chromebook lying around collecting dust. I thought I could use it to reproduce this locally and then perhaps I could find a way to make battery work. Unfortunately, my device doesn't seem to be supported by "Linux (Beta)". Grrrr.

We'll have to do a bit of remote debugging. What's the output of the following command?

```zsh
() {
  emulate -L zsh -o extended_glob
  if (( $+commands[acpi] )); then
    echo -E acpi is =acpi
    acpi
    echo status=$?
  else
    echo no acpi
  fi
  local -a bats=( /sys/class/power_supply/(BAT*|battery)/(FN) )
  typeset -p bats
  local dir file
  for dir in $bats; do
    for file in $dir/(energy_full|charge_full|charge_counter|power_now|current_now|energy_now|charge_now|capacity|status)(N); do
      echo -E - $file
      cat -- $file
      echo status=$?
    done
  done
}
```

**Comment by extremepayne** [comment]
Yeah, unfortunately, only new-ish Chromebooks get this feature. Thanks for your quick response!
```zsh
zsh: correct 'acpi' to '_acpi' [nyae]? n
no acpi
typeset -a bats=(  )
```
Same result with correction. Should I perhaps `sudo apt-get install acpi`?
`upower` also not installed currently.

**Comment by romkatv** [comment]
> Same result with correction. Should I perhaps `sudo apt-get install acpi`?

You can try but it's unlikely to work. There is a minor chance that `acpi` will work if `/sys/class/power_supply` has subdirectories but their names don't match `BAT*|battery`. This is technically possible but I've never encountered a system like this. Either way, please post the output of `strace acpi` so that we both know what we are dealing with. The output of `strace acpi -p` would also be useful.

**Comment by extremepayne** [comment]
![image](https://user-images.githubusercontent.com/46696318/73848169-d7641f00-47e4-11ea-8fd9-0c1f33c99639.png)
There isn't a lot of things pre-installed on these Chromebook's Linux things because space is limited. My Linux system totals at only 4.1 GB.

**Comment by romkatv** [comment]
No `strace`? No biggie. I'm pretty sure `acpi` wouldn't work anyway because it simply reads files from `/sys/class/power_supply` that you don't have.

You can also manually check whether `acpi -p` would work. Check for files in `/proc/acpi/battery`

P.S.

You never want to auto-correct `foo` to `_foo`. The latter is a completion function for `foo`.

**Comment by extremepayne** [comment]
`/proc/acpi` doesn't exist. So, I'm guessing that this means the Linux whatever doesn't have access to battery info? And then, therefore, I can't get it in my prompt? So, I'll close then. 

> You never want to auto-correct foo to _foo. The latter is a completion function for foo.

Ah, that makes sense. This happens a lot (again, not much comes pre-installed) and that simple pointer is very helpful.

**Comment by romkatv** [comment]
> `/proc/acpi` doesn't exist. So, I'm guessing that this means the Linux whatever doesn't have access to battery info?

Yep. I don't know how Linux Beta works on Chrome OS but it appears to be lacking some basic kernel stuff.

> And then, therefore, I can't get it in my prompt? So, I'll close then.

I don't see any way to get battery info. Closing sgtm.
