### ISSUE TITLE
Username not displaying, perhaps related to LDAP/NSS/SSSD

### ISSUE THREAD

**Issue by tymcauley** [romkatv/powerlevel10k#463]
# p10k version

I'm using p10k by way of prezto, and the HEAD of the powerlevel10k repo is `c21961b`, or the `v1.0` tag.

# Problem

Hello, I'm using p10k on several computers (macOS, Ubuntu, CentOS), and it's been wonderful. However, my username doesn't show up in the prompt on the CentOS machine (which I don't administer). The CentOS machine has a rather complex user authentication system, which I believe uses [SSSD](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system-level_authentication_guide/sssd) (perhaps that's relevant, not sure).

I'm using the same p10k configuration/version for all of these computers, and the username/hostname works as expected on the macOS and Ubuntu machines.

# My p10k config

`context` is in the `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` list. Here's my default context template in `~/.p10k.zsh`:

```
typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
...
# Don't show context unless running with privileges on in SSH.
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
```

# Results on different machines

On my macOS machine (my laptop), the context doesn't show up on the right side of the prompt, as expected (since it's accessed over ssh).

On the Ubunu machine (which is a server accessed by ssh), the context looks like this at the right side of the prompt:

```
my_username@my_hostname
```

That looks great. On the CentOS machine (also a server accessed by ssh), the context looks like this:

```
@my_hostname
```

The `username` field is an empty string. The `$USER` environment variable displays my username, but I'm not sure if that's how p10k is querying my username.

Any tests I can perform to figure this out?

**Comment by romkatv** [comment]
The format of `context` is controlled by `POWERLEVEL9K_CONTEXT_${state}_TEMPLATE` parameters. For example, if your config defines this parameter:

```zsh
# Context format when in SSH without privileges: user@hostname.
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
```

Then `context` will be shown as `'%n@%m'` when in SSH. You can print it manually to see how it looks:

```zsh
echo -E - ${(%):-"%n@%m"}
```

If on the CentOS machine `%n` expands to nothing, this explains why you are seeing only `@my_hostname` in prompt.

Since `$USER` works on the CentOS machine, you can work around this problem by changing the template:

```zsh
# Context format when in SSH without privileges: user@hostname.
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE=${USER//\%/%%}'@%m'
```

`${USER//\%/%%}` expands to `$USER` with all percents replaced with double percents. You are unlikely to have `%` in `$USER` but better safe than sorry.

Note that other things may break if `%n` expands to an empty string. You might want to get to the root cause of this issue and fix it. This is obviously unrelated to Powerlevel10k.

**Comment by tymcauley** [comment]
Ah, I see, according to [here](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html), `%n` should expand to `$USERNAME`, and that is blank on CentOS machine.

Thanks for the tip on the workaround! This definitely isn't an issue with p10k, so I'll close this issue for now.

Looks like others have run into the same issue with ZSH: https://github.com/denysdovhan/spaceship-prompt/issues/569

I'll post any other useful info I come up with.

**Comment by romkatv** [comment]
> Ah, I see, according to [here](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html), `%n` should expand to `$USERNAME`, and that is blank on CentOS machine.

This is backwards. Zsh doesn't *read* `$USERNAME`, it *sets* it. If `%n` is empty, then `$USERNAME` will be empty, too.

Zsh gets username similarly to `id -run` although there might be some differences. Does `id -run` work for you?

Note that `$USER` can go out of sync with `%n` on systems where `%n` is not broken. For example, type `sudo zsh -df` and then `UID=1000` (assuming you have a user with such id). Now `$USER` is `root` but `print -P %n` isn't.

**Comment by tymcauley** [comment]
`id -run` returns the correct username on CentOS (as well as on Ubuntu and macOS).

**Comment by romkatv** [comment]
Must be a bug in Zsh then. If `id -run` can get username, Zsh should be able to do the same.
