### ISSUE TITLE
gitstatusd issue with word splitting when hosting config on a cloud drive (google)

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/powerlevel10k#464]
So I have my config stored in Google Drive, which lives... you guessed it in Google Drive and gitstatusd fails to fire up due to word splitting (my guess)

```
┌─[11:31:21][boris][ares][~]
└─▪  GITSTATUS_LOG_LEVEL=DEBUG
typeset -i i=2
typeset -i num_lines=2
typeset -g _p9k_ret=''
typeset -i i=2
typeset -i num_lines=2
typeset -g _p9k_ret=0
[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  The content of /var/folders/fd/sjysxnvs16z_l64q8llf82x80000gn/T//gitstatus.1157.xtrace.1580833889.9638950825.20955 (gitstatus_start_impl xtrace):

    +gitstatus_start_impl:6> ((  daemon_pid == -1  ))
    +gitstatus_start_impl:7> local os
    +gitstatus_start_impl:8> local daemon='/Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64'
    +gitstatus_start_impl:9> [[ -n '/Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64' ]]
    +gitstatus_start_impl:16> [[ -x '/Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64' ]]
                               ^ this command failed

  Your system information:

    zsh:      5.7.1
    uname -a: Darwin ares 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

  If you need help, open an issue and attach this whole error message to it:

    https://github.com/romkatv/gitstatus/issues/new
```

**Comment by romkatv** [comment]
The error message says that `/Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64` either doesn't exist or isn't executable. Once you restore this file to it's original state, it should work.

**Comment by kurktchiev** [comment]
This is a problem with the Space in the directory structure:
```
┌─[11:45:20][boris][ares][~]
└─▪ sh /Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
sh: /Users/boris/Google: No such file or directory
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌─[11:45:33][0.01s][boris][ares][~]
└─▪ ls "/Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64"
/Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
```

**Comment by romkatv** [comment]
In pretty sure my first comment is correct.

**Comment by kurktchiev** [comment]
The file exists as you can see in the `ls` output. i think its because of the "Google Drive" in the name that space is tripping up the shell

**Comment by romkatv** [comment]
> The error message says that `/Users/boris/Google Drive/Mackup/.config/zsh/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64` either doesn't exist **or isn't executable**. Once you restore this file to it's original state, it should work.

(I'm on a phone. Excuse brevity.)

**Comment by romkatv** [comment]
Have you managed to fix it?

**Comment by kurktchiev** [comment]
yeah, changed the dir to no spaces and moved on with stuff. Thanks for the great work!

**Comment by romkatv** [comment]
I'm still pretty sure the error message said the file isn't executable. Spaces have nothing to do with it. You can see in the trace you've posted that the file name is quoted.

**Comment by romkatv** [comment]
> I'm still pretty sure the error message said the file isn't executable. Spaces have nothing to do with it. You can see in the trace you've posted that the file name is quoted.

I just learned that Google Drive sets all file permissions to 600 after a sync. If you want to keep powerlevel10k on Google Drive, you need to manually fix file permissions after every sync.
