### ISSUE TITLE
On Google Cloud Shell _GITSTATUS_CLIENT_PID_POWERLEVEL9K: parameter not set

### ISSUE THREAD

**Issue by AaronNBrock** [romkatv/powerlevel10k#465]
I'm using powerline10k as a zsh theme on [google cloud shell](https://cloud.google.com/shell/), but randomly after using it without issue for a bit it will start failing and spit out the following error on each command:

```
gitstatus_query:28: _GITSTATUS_CLIENT_PID_POWERLEVEL9K: parameter not set
```

If I restart `zsh` it starts working again for awhile.  I'm having trouble debugging what could cause this, so please ask for more information if needed.

**Comment by romkatv** [comment]
I'll need more specific reproduction instructions before I can do anything. I've tried using powerlevel10k on google cloud shell following the [manual installation instructions](https://github.com/romkatv/powerlevel10k/blob/master/README.md#manual). Seems to work fine.

When you see that error next time, try to figure out which actions led to it. In addition, post the output of the following command:

```zsh
() {
  emulate -L zsh
  typeset -pm '*GITSTATUS*'
  ps -lf
}
```

**Comment by romkatv** [comment]
I'm going to close this issue as there is nothing I can do at the moment. Please reopen if or when you get more information.
