### ISSUE TITLE
zsh dump on startup

### ISSUE THREAD

**Issue by errantepiphany** [romkatv/powerlevel10k#466]
It looks like commit 5e5ff583 on 2020-02-04 might have caused an intermittent problem. More often than not (but not always - which is weird), when I start up a terminal, I get this zsh code dumped out before the prompt displays:

![zsh-dump-in-internal-p10k-zsh](https://user-images.githubusercontent.com/392133/73768102-784fcd00-4746-11ea-9728-9b2a80b4b520.png)

The output looks related to that particular commit. I had used zplug to load p10k from master (which included that suspect commit):
`zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme, as:theme, at:master`

However, when I switch to the commit point _before_ that (fab13389 on 2020-02-03), then as many times as I start a new terminal, I never see the issue:
`zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme, as:theme, at:fab13389`

I am using zsh 5.7.1 on both my Fedora 31 laptop, and my iMac 10.15.3 desktop, and I see the issue in both. If you would like more environment or debug information, I would be happy to provide it. Thank you!

**Comment by errantepiphany** [comment]
Oh, and I am not using _instant prompt_ nor _transient prompt_.

**Comment by romkatv** [comment]
Oh crap... I've committed debug logging. Thanks for reporting this! Please update. These messages should be gone now.

**Comment by errantepiphany** [comment]
@romkatv That fixed it - thanks for the quick help!
