### ISSUE TITLE
Strange console output when .p10k.zsh changed

### ISSUE THREAD

**Issue by maxzinkus** [romkatv/powerlevel10k#467]
Whenever I change `.p10k.zsh` and restart zsh, the first time, I see the following:
```
typeset -i i=2
typeset -i num_lines=2
typeset -g _p9k_ret=''
typeset -i i=2
typeset -i num_lines=2
typeset -g _p9k_ret=0
```

With `typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose` this of course leads to an irksome error message about instant prompt (which I realize I can disable/silence).

**Comment by romkatv** [comment]
Year, I committed garbage there and fixed it fairly soon. You were unlucky to pull in the meantime. Please update powerlevel10k and it should fix it.

**Comment by maxzinkus** [comment]
Yep, you're 100% correct. Thanks for the fast response, and for maintaining this lovely software :clap:

**Comment by romkatv** [comment]
Sorry about that debug logging. I don't have an excuse for this embarrassment.
