### ISSUE TITLE
How can I write (fast) custom prompt segments?

### ISSUE THREAD

**Issue by nfischer** [romkatv/powerlevel10k#468]
Forgive me if this is not the best place for this, but I thought this would be a good starting point.

I'm trying to add custom segments to my powerlevel10k theme. I've read through [powerlevel9k's `custom_command` documentation](https://github.com/Powerlevel9k/powerlevel9k#custom_command) and have successfully created my own prompt segments, but they're **very slow**.

To summarize, I've implemented the following:

* If I'm in a chromium git repo, read and parse [`//chrome/VERSION`](https://source.chromium.org/chromium/chromium/src/+/master:chrome/VERSION;l=1;drc=82b75568feb18582a1734d4f8274a0d933dda55b?originalUrl=https:%2F%2Fcs.chromium.org%2F) to show the formatted result in my shell prompt (ex. "82.0.4049.0").
* If I have an Android device connected, communicate with the device over adb to retrieve some basic attributes (communicating over adb is slow, and adds 80ms to my "Time per prompt" as measured by zsh-prompt-benchmark).

I think either of these would be greatly improved by doing the work asynchronously or by caching the results. There are probably various ways I could optimize either segment, but async or caching seem much more general (and would hopefully be less error-prone). I thought caching might be simpler to implement first, so I tried the following minimal example, but it doesn't quite seem to work:

```sh
# Declare an associative array in my .zshrc file:
declare -gA FOO_CACHE
powerlevel9k_foo() {
  if [ "${FOO_CACHE[key]}" ]; then
    echo "cache hit!"
  else
    # I would expect a cache miss for the first prompt, but would want cache hits
    # for subsequent prompts in this simple example. But I get cache misses
    # consistently, because the writes to the array don't seem to stick.
    echo "cache miss!"
  fi
  # For this simple example, I'm always writing the same value into the cache.
  FOO_CACHE[key]=value
}
POWERLEVEL9K_CUSTOM_FOO="powerlevel9k_foo"
# And add "custom_foo" to the prompt somewhere.
```

Am I missing something simple, or is this something I can't easily achieve in a custom segment? It seems like my segment function is running in a subshell, so it has a new associative array which simply inherits from the parent shell's associative array, in which case I'm pretty sure my writes will never persist across prompts unless there are changes to powerlevel10k itself.

If async is technically feasible, do you have tips (or a documented minimal example) for how to get started? My understanding from reading other prompts is the strategy is to do the work async, save results in an associative array, and redraw the prompt (`zle .reset-prompt`) using the results from the cache. If that's right, would I run into the same issue with saving data in the associative array, or is there some reason that wouldn't happen in this case?

Do you have general tips/strategies for implementing high-performance custom segments?

**Comment by romkatv** [comment]
Writing fast prompt segments is difficult. I'll give some tips but I'm afraid they won't help much.

Avoid `_custom` API from powerlevel9k. In general, if something isn't found in `~/.p10k.zsh`, you should avoid it. Powerlevel10k has much better API for user-defined segments. Search for `prompt_example` in your `~/.p10k.zsh` on in [config templates](https://github.com/romkatv/powerlevel10k/tree/master/config).

You didn't specify what it means to "be in a chromium repo", so I'll take the easy approach and assume that it means `PWD` under `~/chromium`. You can adjust this. Here's fast `my_chrome_version` prompt segment:

```zsh
zmodload zsh/system

# Directory where chromium repo is checked out.
# This is one way to define what it means to be in a chromium repo.
typeset -g  _chrome_version_root=~/chromium
# Modification time of ~/chromium/VERSION.
typeset -gi _chrome_version_mtime
# Chromium version.
typeset -g  _chrome_version_content

# Note: It's a good idea to prefix your own custom
# segments with "my_" to avoid clashes with future
# versions of powerlevel10k.
function prompt_my_chrome_version() {
  emulate -L zsh -o extended_glob
  [[ ${(%):-%/}/ == $_chrome_version_root/* ]] || return
  local -a stat
  zstat -A stat +mtime -- $_chrome_version_root/VERSION 2>/dev/null || return
  if [[ $stat[1] != $_chrome_version_mtime ]]; then
    local parts
    { parts=(${(@)${${(f)"$(<$_chrome_version_root/VERSION)"}#*=}//[[:space:]]}) } 2>/dev/null
    _chrome_version_content=${(j:.:)parts}
    _chrome_version_mtime=$stat[1]
  fi
  [[ -n $_chrome_version_content ]] || return
  p10k segment -b 3 -f 1 -i $'\uF268' -t ${_chrome_version_content//\%/%%}
}
```

This is a very simple segment by p10k standards. It's also fairly fast. If I were implementing this as built-in segment, I could make it faster because there are a few nice things in powerlevel10k that aren't available through public API. But we are talking microseconds here. In practice the implementation I posted above is virtually instant.

Async segments are a couple of orders of magnitude more difficult to implement. Within powerlevel10k there is the fastest async Zsh machinery in existence but it's not exposed to the outside. You can either roll your own (quite difficult) or use a library such as zsh-async (moderately difficult but the library is not very fast and not very reliable). I'm not exposing the async API because it'll constrain p10k development and because there is no real demand for it. Almost no one can write correct prompt segments even on top of the very simple `p10k segment` API, and the async API is much more complex.

Even though it's easy to use async machinery within powerlevel10k, very few segments use it. In most cases it's feasible and better to write a fast and synchronous implementation. Instead of forking out to slow tools, it's often possible to reimplement them in zsh with 100x-1000x better performance. This sometimes can be challenging. I don't know what "communicate with the device over adb to retrieve some basic attributes" means, so cannot tell if a fast reimplementation is feasible. In many cases the output of the slow tool can change only under specific circumstances, so instead of reimplementing it you can simply call it less often.

Hope this helps at least a little.

> Do you have general tips/strategies for implementing high-performance custom segments?

The easiest way is to open an issue describing what you want. If anyone else wants it, I'll implement it.

**Comment by nfischer** [comment]
> Writing fast prompt segments is difficult. I'll give some tips but I'm afraid they won't help much.
> 
> Avoid `_custom` API from powerlevel9k. In general, if something isn't found in `~/.p10k.zsh`, you should avoid it. Powerlevel10k has much better API for user-defined segments. Search for `prompt_example` in your `~/.p10k.zsh` on in [config templates](https://github.com/romkatv/powerlevel10k/tree/master/config) [](/romkatv/powerlevel10k/tree/HEAD@{2020-02-04T21:56:58Z}/config).

Ah, after switching to the `p10k segment` my writes to the associative array now persist. The rewrite of my simple example is:

```sh
typeset -gA  _foo_cache
prompt_my_foo() {
  local msg
  if [ -z "${_foo_cache[key]}" ]; then
    # We only hit this for the first prompt...
    msg="cache miss!"
  else
    # ... and hit this case for subsequent prompts, as expected!
    msg="cache hit!"
  fi
  _foo_cache[key]=value
  p10k segment -f 208 -i '⭐' -t "${msg}"
}
# And add "my_foo" to the prompt somewhere.
```

> You didn't specify what it means to "be in a chromium repo", so I'll take the easy approach and assume that it means `PWD` under `~/chromium`. You can adjust this. Here's fast `my_chrome_version` prompt segment:

I made some minor edits to fix some incorrect assumptions about chromium's code layout, and I made it more general (it will accept any of my 4 chromium repos, rather than a single hardcoded path). Might not be quite as fast as your snippet, but this is much faster than what I had before. Thanks for your help!

```sh
zmodload zsh/system

# Modification time of ~/chromium/VERSION.
typeset -gi _chrome_version_mtime
# Chromium version.
typeset -g  _chrome_version_content

function prompt_my_chrome_version() {
  emulate -L zsh -o extended_glob
  [[ ${(%):-%/}/ == *"/src"* ]] || return
  local _chromium_repo_root="${PWD%%/src*}/src"
  local -a stat
  zstat -A stat +mtime -- $_chromium_repo_root/chrome/VERSION 2>/dev/null || return

  if [[ $stat[1] != $_chrome_version_mtime ]]; then
    local parts
    { parts=(${(@)${${(f)"$(<$_chromium_repo_root/chrome/VERSION)"}#*=}//[[:space:]]}) } 2>/dev/null
    _chrome_version_content=${(j:.:)parts}
    _chrome_version_mtime=$stat[1]
  fi
  [[ -n $_chrome_version_content ]] || return
  p10k segment -f 117 -i $'\uF268' -t ${_chrome_version_content//\%/%%}
}
# And add "my_chrome_version" to the prompt somewhere.
```

> I don't know what "communicate with the device over adb to retrieve some basic attributes" means, so cannot tell if a fast reimplementation is feasible.

Adb is the protocol for talking to a connected Android device (usually a physical device connected over USB cable). The specific command I'm running is `adb shell getprop ro.build.version.sdk`, which connects to the device, starts a POSIX shell, and executes a shell command to fetch the version of the Android OS (as an integer value). So this command will be unavoidably slow. I don't really want to write an adb-alternative, and I don't know if there's even a way to do so without Android OS modifications (some of the slowness is likely on the device side).

> In many cases the output of the slow tool can change only under specific circumstances, so instead of reimplementing it you can simply call it less often.

I think that's the better way to go in this case. Since this retrieves the OS version (which very rarely changes), caching adds a big performance boost. Unfortunately, it is possible for a user to reflash their device or stop an emulator and restart another using the same device identifier, so I'll have to come up with some strategy for cache invalidation (there's no obvious signal for either of these events). I can of course workaround this by manually invalidating the cache when I know it's invalid (the simplest way being to start a new shell), but I'll update this if I figure something out.

I think `p10k segment` was the thing I was missing to make forward progress, so I think it's fine to mark this ticket as resolved. Thanks again for your help!

**Comment by romkatv** [comment]
> I made some minor edits to fix some incorrect assumptions about chromium's code layout, and I made it more general (it will accept any of my 4 chromium repos, rather than a single hardcoded path).

You'll need to use several `_chrome_version_mtime` and `_chrome_version_content` variables to support several repos.

Here's a fixed version. Your code also gave me the answer to the question of what you mean by "being in chromium repo".

```zsh
zmodload zsh/system

# /path/to/chrome/VERSION => mtime:version
typeset -gA _chrome_versions

function prompt_my_chrome_version() {
  emulate -L zsh -o extended_glob
  local files=((../)##chrome/VERSION(.N))
  (( $#files )) || return
  local file=${files[-1]:A}
  local -a stat
  zstat -A stat +mtime -- $file 2>/dev/null || return
  local cached=$_chrome_versions[$file]
  if [[ $cached == $stat[1]:* ]]; then
    local version=${cached#*:}
  else
    local parts
    { parts=(${(@)${${(f)"$(<$file)"}#*=}//[[:space:]]}) } 2>/dev/null
    local version=${${(j:.:)parts}//\%/%%}
    _chrome_versions[$file]=$stat[1]:$version
  fi
  [[ -n $version ]] && p10k segment -f 117 -i $'\uF268' -t $version
}
```

As for `adb`, you can try the following implementation:

```zsh
# '' | 'running' | 'dirty'
typeset -g _android_sdk_version_state
# The last output of `adb shell getprop ro.build.version.sdk`.
typeset -g _android_sdk_version_content

# This hook, if defined, gets called by powerlevel10k before every prompt.
function p10k-on-pre-prompt() {
  [[ $P9K_PROMPT == regular ]] || return  # do nothing on instant prompt
  if [[ -n $_android_sdk_version_state ]]; then
    _android_sdk_version_state=dirty
  else
    _android_sdk_version_state=running
    zsh-defer -a _android_sdk_version_compute
  fi
}

function _android_sdk_version_compute() {
  local content
  content="${$(adb shell getprop ro.build.version.sdk 2>/dev/null)//\%/%%}" || content=
  if [[ $content != $_android_sdk_version_content ]]; then
    _android_sdk_version_content=$content
    zle .reset-prompt
    zle -R
  fi
  if [[ $_android_sdk_version_state == dirty ]]; then
    _android_sdk_version_state=running
    zsh-defer -a _android_sdk_version_compute
  else
    _android_sdk_version_state=
  fi
}

function prompt_my_android_sdk_version() {
  local content='$_android_sdk_version_content'
  p10k segment -f 117 -i $'\uF531' -c $content -e -t $content
}
```

This requires https://github.com/romkatv/zsh-defer. `my_android_sdk_version` is not an async prompt segment in proper sense but it should have fairly good UX.

Note that the implementation is generic. You can replace `adb shell getprop ro.build.version.sdk` with another command and it'll still work. However, you need to be mindful of latency. If the command takes >>100ms to complete, you'll notice it. In this case you'll need to go full async.

**Comment by romkatv** [comment]
Have you tried it? Did it work?

**Comment by nfischer** [comment]
`prompt_my_chrome_version` didn't quite work as written (not quite sure what the bug is, I'm not familiar with some of the more advanced zsh expressions in there). Instead, I got the following working:

```sh
zmodload zsh/system

# /path/to/chrome/VERSION => mtime:version
typeset -gA _chrome_versions

# I've got this factored out so it's zsh-theme agnostic, because I may share this
# with other coworkers in the near future.
helper::fast_chromium_version() {
  emulate -L zsh -o extended_glob
  [[ ${(%):-%/}/ == *"/src"* ]] || return
  local _chromium_repo_root="${PWD%%/src*}/src"
  local file=($_chromium_repo_root/chrome/VERSION(.N))
  local -a stat
  zstat -A stat +mtime -- $file 2>/dev/null || return
  local cached=$_chrome_versions[$file]
  if [[ $cached == $stat[1]:* ]]; then
    local version=${cached#*:}
  else
    local parts
    { parts=(${(@)${${(f)"$(<$file)"}#*=}//[[:space:]]}) } 2>/dev/null
    local version=${${(j:.:)parts}//\%/%%}
    _chrome_versions[$file]=$stat[1]:$version
  fi
  echo "$version"
}

prompt_my_chrome_version() {
  local version="$(helper::fast_chromium_version)"
  [ -z "${version}" ] && return
  p10k segment -f 117 -i $'\uF268' -t ${version}
}
# And add "my_chrome_version" to the prompt somewhere.
```

I confirmed this gives correct results even when multiple chrome checkouts have the same mtime for their `//chrome/VERSION` file (not a super common case, but certainly good to guard against). Thanks!

Your version of `prompt_my_android_sdk_version` works perfectly fine as advertised, although the Android OS version is actually only one piece of my actual prompt segment. My real prompt segment is tailored to my own workflow (I like to connect lots of devices and use the `ANDROID_SERIAL` env var to switch between them), so I like to display both `ANDROID_SERIAL` and the OS version of the selected device in my zsh prompt. Here's what I've been using for the past day or so:

```sh
# I've factored these out because I use them for other utilities. There's
# optimization potential for anyone who only cares about the zsh prompt, but
# these work fine for me as-is:
isemulator() {
  [[ "$1" == "emulator"* ]]
}
adb_shell() {
  # Some Android devices use '\r\n' line endings, this works around that in both
  # bash and zsh:
  adb shell "$@" | tr -d '\r'
  retval_bash="${PIPESTATUS[0]}" retval_zsh="${pipestatus[1]}"
  if [[ "$BASH_VERSION" ]]; then
    return "${PIPESTATUS[0]}"
  elif [[ "$ZSH_VERSION" ]]; then
    return "${pipestatus[1]}"
  else
    echo "Could not determine pipe exit code" >&2
    return 2
  fi
}
getsdk() {
  local serial="$1"
  local old_serial="$ANDROID_SERIAL"
  export ANDROID_SERIAL="${serial}"
  adb_shell getprop ro.build.version.sdk 2>/dev/null
  ANDROID_SERIAL="${old_serial}"
}

# This is the actual start of the prompt segment, including variables for customization:
CUSTOM_ADB_TRUNC=6
CUSTOM_ADB_ICON=$'\uF531' # The Android droid figure
# CUSTOM_ADB_ICON=$'\uF61C' # Android phone icon, also a pretty nice icon
CUSTOM_ADB_FOREGROUND="079" # Approximation of the 2019 Android logo's teal/green

# Fetches useful info for the currently selected Android device:
# * If a physical device, the Android serial number (truncated if too long)
# * If an emulator, "em-" followed by the port suffix of the emulator serialno
# * If the device is connected, also appends the SDK int of the OS level
#   (esp. helpful to differentiate emulators)
helper::formatted_adb_serial() {
  [ -z "${ANDROID_SERIAL}" ] && return 1

  local serial
  if isemulator "${ANDROID_SERIAL}"; then
    serial="${ANDROID_SERIAL/emulator/em}"
  else
    serial="${ANDROID_SERIAL[0,${CUSTOM_ADB_TRUNC}]}..."
  fi

  local sdk_int="$(getsdk "$ANDROID_SERIAL")"
  if [ -n "${sdk_int}" ]; then
    serial="${serial}|${sdk_int}"
  fi

  echo -n "${serial}"
}

# '1' if _android_sdk_version_compute is about to run.
typeset -gi _android_sdk_version_scheduled
# The last output of `helper::formatted_adb_serial`.
typeset -g _android_sdk_version_content

# This hook, if defined, gets called by powerlevel10k before every prompt.
p10k-on-pre-prompt() {
  if [[ $P9K_PROMPT == regular && $_android_sdk_version_scheduled == 0 ]]; then
    _android_sdk_version_scheduled=1
    zsh-defer -a _android_sdk_version_compute
  fi
}

_android_sdk_version_compute() {
  local content
  content="${$(helper::formatted_adb_serial 2>/dev/null)//\%/%%}" || content=
  if [[ $content != $_android_sdk_version_content ]]; then
    _android_sdk_version_content=$content
    zle .reset-prompt
    zle -R
  fi
  _android_sdk_version_scheduled=0
}

prompt_my_android_sdk_version() {
  local content='$_android_sdk_version_content'
  p10k segment -f "${CUSTOM_ADB_FOREGROUND}" -i "$CUSTOM_ADB_ICON" -c $content -e -t $content
}
# And add "my_android_sdk_version" to the prompt somewhere.
```

I don't expect others will find all of this useful, since most of my colleagues use a single device/emulator at a time. But I believe I've copied all the relevant pieces, so it should be copy-pasteable for anyone interested in trying it out.

I expect there's some optimization potential in my_android_sdk_version, but this is working fast enough for me at the moment (and with no observable impact to zsh-prompt-benchmark scores). [romkatv/zsh-defer](https://github.com/romkatv/zsh-defer) was a huge help!

**Comment by romkatv** [comment]
Thanks for posting your code. There aren't many examples of user-defined prompt segments, so it'll be helpful to others looking to implement some.

> ```zsh
>   [[ ${(%):-%/}/ == *"/src"* ]] || return
> ```

You might want to replace `/src` with `/src/` everywhere. (I'm assuming you don't want to match `src_it_is_not`.)

> ```zsh
> local version="$(helper::fast_chromium_version)"
> ```

Awwww :cry: Every time I see someone putting a fork into powerlevel10k prompt I die a little inside.

Forks are slow. Avoid them whenever possible. Here's idiomatic way to "return" strings from functions in Zsh:

```zsh
helper::fast_chromium_version() {
  ...
  REPLY=$version
}

prompt_my_chrome_version() {
  local REPLY
  helper::fast_chromium_version
  local version=$REPLY
  ...
}
```

Zsh has dynamic scope. Functions have access to local variables defined in their callers. Note that the name `REPLY` is not special. You could assign to `version` directly. This also allows you to "return" arrays or multiple values.

As for performance implications:

```zsh
❯ time ( repeat 10000 REPLY="hello" )
user=0.00s system=0.00s cpu=86% total=0.003
❯ time ( repeat 10000 REPLY="$(echo hello)" )
user=4.95s system=4.32s cpu=102% total=9.059
```

3000x difference. This is on Linux. On macOS and Windows forks are much slower still.

> ```zsh
> CUSTOM_ADB_ICON=$'\uF531' # The Android droid figure
> CUSTOM_ADB_FOREGROUND="079" # Approximation of the 2019 Android logo's teal/green
> ```

It's better to hard-code these values when calling `p10k segment`. Powerlevel10k already provides standard customization parameters that allow you to override these things.

```zsh
POWERLEVEL9K_MY_ANDROID_SDK_VERSION_FOREGROUND=42
POWERLEVEL9K_MY_ANDROID_SDK_VERSION_VISUAL_IDENTIFIER_EXPANSION=$'\u2B50'
```

If you define your own parameters, you end up with two parameters for the same thing. Also more code and bigger API for your custom segment.

> this is working fast enough for me at the moment (and with no observable impact to zsh-prompt-benchmark scores)

It shouldn't have any effect on prompt latency measured by zsh-prompt-benchmark because there is no computation happening. zsh-defer works fairly well as long as every deferred action is fast enough on its own. It's OK to defer 100 actions that run for 10ms each, but you'll start noticing typing lag if you defer one action that runs for 1000ms. zsh-prompt-benchmark won't show any different though.

**Comment by nfischer** [comment]
> You might want to replace `/src` with `/src/` everywhere. (I'm assuming you don't want to match `src_it_is_not`.)

Ah, good catch! Changed the relevant part to:

```sh
  local _pwd_with_slash="${(%):-%/}/"
  [[ "${_pwd_with_slash}" == *"/src/"* ]] || return
  local _chromium_repo_root="${_pwd_with_slash%%/src/*}/src"
```

> Zsh has dynamic scope. Functions have access to local variables defined in their callers. Note that the name `REPLY` is not special. You could assign to `version` directly. This also allows you to "return" arrays or multiple values.

I didn't know that, that's really cool! Seems like bash and sh work similarly (with similar perf wins), so I should be able to get something portable and performant to share with bash users.
