### ISSUE TITLE
[Request] Call function which contains all the user's "preferences"

### ISSUE THREAD

**Issue by eddyg** [romkatv/powerlevel10k#470]
Hi Roman.

First, thanks a ton for all your work on this prompt (and all your other zsh work)!

I like to `git pull` all your latest updates regularly, and re-run `p10k configure' so my generated `.p10k.zsh` file has all the "latest and greatest" examples, prompt segments, etc. I understand that I _don'_t need to do this, but my prompt is constantly evolving as I learn about new things, add new virtual environments / languages to my system, etc.

To make this as simple as possible, I defined this function:

```
function p10k_user_settings() {
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ssh context dir vcs newline prompt_char)
...
----8<---- snip! ----8<----  
...
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=same-dir
```

Then after I run `p10k configure` to generate `.p10k.zsh`, I add this above the `p10k reload` line:

```
  # If user has defined the function that can override any of these settings, call it now
  (( $+functions[p10k_user_settings] )) && p10k_user_settings
```

This way I don't have to go manually apply all my customized colors, prefixes, suffixes, etc. in the newly-generated `.p10k.zsh`.

**So here's the ask**: is this something you'd consider adding? (`p10k reload` should probably call `p10k_user_settings` as well?)

The only thing I _haven't_ found a clean/easy way to change using this approach are the colors in `my_git_formatter` which I still have to change manually since they are local variables:

```
      local       meta='%8F'
      local      clean='%14F'
      local   modified='%11F'
      local  untracked='%12F'
      local conflicted='%9F'
    else
      local       meta='%244F'
      local      clean='%244F'
      local   modified='%244F'
      local  untracked='%244F'
      local conflicted='%244F'
```

Figured it couldn't hurt to ask since I think there are others who might prefer to keep their customizations together like this.

**Comment by romkatv** [comment]
As long as you understand that your prompt may break when you update powerlevel10k, this approach is fine. You don't need to change `~/.p10k.zsh`. You can simply define your parameters after sourcing it and call `p10k reload` again (this call is cheap; the actual reloading happens on next prompt).

> **So here's the ask**: is this something you'd consider adding? (`p10k reload` should probably call `p10k_user_settings` as well?)

No, I wouldn't want to add this. It would give people a false idea what they can define their own settings in `p10k_user_settings`, update powerlevel10k, run `p10k configure` and have a non-broken prompt. In reality the results will be unpredictable.

**Comment by romkatv** [comment]
If you are OK patching parameters, you can patch `my_git_formatter`, too.

```zsh
functions[my_git_formatter]=${(pj:\n:)${(@)${(f)functions[my_git_formatter]}//local meta=*/local meta='%1F'}}
```

**Comment by eddyg** [comment]
> You can simply define your parameters after sourcing it and call `p10k reload` again (this call is cheap

OK, that makes things even simpler. I try to be cognizant of things that make startup slow, so I wasn't sure if that was valid approach. Good to know.

> As long as you understand that your prompt may break when you update powerlevel10k, this approach is fine

Totally understand. I don't mind looking in to why something "broke" after an update, but can recognize why this would be a problem for others.

> you can `patch my_git_formatter`

Very nice. Thanks for the hint. I will give that a try.

_(and thanks again for a great prompt framework!)_

**Comment by eddyg** [comment]
Yes, git merging usually works quite well. I was mostly playing around with the above approach as a possible way to have (easily-shared) "light" and "dark" color scheme "functions" that would be easy to switch between, but it seems like just having a function that redefines the settings and calls `p10k reload` is all I need. Thanks again for all your insight!
