### ISSUE TITLE
Getting the same prompt as doc's prompt under "Uncompromising performance" section

### ISSUE THREAD

**Issue by CChalland** [romkatv/powerlevel10k#474]
I was following the docs and used p10k configure but was hoping to have my command prompt as shown on powerlevel10k GitHub's main page(https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/performance.gif)

I'm a new developer, I have tried editing the .p10k.zsh and .zshrc but none of the changes are effective. I was wondering if you can post .p10k.zsh, or the zsh commands to make my prompt the same as the link above? Thanks for all the great work you're doing with P10K.

**Comment by romkatv** [comment]
Here's how you can configure the same prompt.

1. [Install the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#meslo-nerd-font-patched-for-powerlevel10k).
2. Type `p10k configure`.
3. Choose options that make prompt look the same as in this gif.
   1. Lean.
   2. 256 colors.
   3. Current time enabled.
   4. Two lines.
   5. Dotted connection.
   6. Right frame.
   7. Dark connection and frame color.
   8. Sparse.
   9. Many icons.
   10. Concise.
   11. Transient prompt enabled.
4. Enable a bunch of prompt segments that are disabled by default. Open `~/.p10k.zsh` and uncomment the following elements in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`: `load`, `disk_usage`, `ram`, `swap` and `vpn_ip`.
5. Change order of prompt elements.  Open `~/.p10k.zsh` and move elements of `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` to appropriate places to get the same order as in the gif. The last 4 elements of this array should be `timewarrior`, `time` and `vpn_ip`.

Note that there is no particular reason to use exactly these prompt options and these prompt elements in this order. It's just something I did for this recording without much thinking.

See also:

- [What is the best prompt style in the configuration wizard?](https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-the-best-prompt-style-in-the-configuration-wizard)
- [How were these screenshots and animated gifs created?](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-were-these-screenshots-and-animated-gifs-created)

**Comment by CChalland** [comment]
Thank you for your help, I really appreciate the help! I was wondering if you could help me with one more issue.

The issue is the Transient prompt. I answered yes to "Enable Transient Prompt?" while running the `p10k configure` command. I have tried multiple times running `p10k configure` to fix this bug but the transient prompt feature is still not working. 

I have posted an image below:
<img width="722" alt="Screen Shot 2020-02-06 at 3 48 54 PM" src="https://user-images.githubusercontent.com/33366636/73982943-de7d5100-48fa-11ea-9cb0-84809cd93192.png">

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k/blob/master/README.md#transient-prompt-stops-working-after-some-time
