### ISSUE TITLE
Terraform prompt makes directory look weird

### ISSUE THREAD

**Issue by sagikazarmark** [romkatv/powerlevel10k#475]
After running `p10k configure`, the terraform prompt (on the right) causes the left prompt to look like this:

<img width="1671" alt="Screenshot 2020-02-06 at 2 15 26" src="https://user-images.githubusercontent.com/1226384/73897555-bc49eb80-4886-11ea-9355-ab0642d46062.png">

Notice the extra space after the directory name, but no space after the prompt itself.

<img width="222" alt="Screenshot 2020-02-06 at 2 25 53" src="https://user-images.githubusercontent.com/1226384/73897946-041d4280-4888-11ea-919e-d60ed6a7c3a4.png">

**Comment by romkatv** [comment]
What terminal are you using?

**Comment by sagikazarmark** [comment]
iTerm 3 on MacOS

**Comment by romkatv** [comment]
Do you mean https://www.iterm2.com/? If not, could you link to the terminal you are using?

**Comment by sagikazarmark** [comment]
Yep, that's it

**Comment by sagikazarmark** [comment]
Note that this only happens if I'm in a terraform module and the terraform prompt is turned on.

**Comment by romkatv** [comment]
It works for me with the stock configuration produced by `p10k configure`.

Please try following the troubleshooting guide: [Cursor is in the wrong place](https://github.com/romkatv/powerlevel10k/blob/master/README.md#cursor-is-in-the-wrong-place).

If you cannot find a solution, you can also update powerlevel10k to the latest version and generate a new config with `p10k configure`. Powerlevel10k now uses a different glyph for terraform. It'll probably help. However, it would be better if you can fix your terminal by following the guide.

**Comment by sagikazarmark** [comment]
Updating powerlevel10k worked! Thanks a lot for the help and this great theme as well!

**Comment by romkatv** [comment]
Glad it worked for you. Note that your terminal is still a bit broken, which can bite you again in the future. The problem *is fixable*. I'm positive that iTerm2 is capable of displaying the original terraform glyph correctly provided that your locale, font and terminal settings are all good.

**Comment by sagikazarmark** [comment]
Thanks, I'll keep that in mind.

I have to admit that I use a custom patched Nerd Fonts version that worked just fine under p9k, so that's probably on me. I didn't have the guts to update the fonts yet, but I will give it a try. 😄 

Thanks again!
