### ISSUE TITLE
Wizard config every new tab or window

### ISSUE THREAD

**Issue by Glioburd** [romkatv/powerlevel10k#476]
Hello, every new tab or window I'm opening, the Configuration wizard is asking me for my preferences. At the end, it tells me I already have a .p10k.zsh config file, and ask me to overwrite it. If I abort, I'm on the default theme of powerlevel10k without any preferences.
I installed powerlevel10k using git :

`git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k`

OS : Kubuntu 18.04
Terminal : Konsole
Shell : zsh (using oh-my-zsh, with theme : `powerlevel10k/powerlevel10k`

Did I miss an obvious config step? Thanks for your help.

**Comment by romkatv** [comment]
Does this help?

https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by Glioburd** [comment]
Oh yes, it helped me. My bad, totally missed this part in the Readme. It seems that I simply had a syntax error in my .zshrc after adding my aliases (fresh install).  
Thanks a lot!
