### ISSUE TITLE
[ macOS ] Glyphs broken

### ISSUE THREAD

**Issue by cig0** [romkatv/powerlevel10k#48]
Hi @romkatv,

<img width="509" alt="Screen Shot 2019-04-01 at 23 32 14" src="https://user-images.githubusercontent.com/394089/55372153-19427b80-54d7-11e9-8f3e-72fa904d87e6.png">

I saw this other issue https://github.com/romkatv/powerlevel10k/issues/9, but not sure if it can be related with mine.

Relevant ~/.zshrc part:
```
   183	POWERLEVEL9K_MODE='awesome-fontconfig'
   184	#AWS_DEFAULT_PROFILE=adv
   185	DEFAULT_USER="$USER"
   186	POWERLEVEL9K_HOME_ICON=''
   187	POWERLEVEL9K_HOME_SUB_ICON=''
   188	POWERLEVEL9K_FOLDER_ICON=''
   189	POWERLEVEL9K_ETC_ICON=''
   190	POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
   191	POWERLEVEL9K_DIR_PATH_SEPARATOR=" $(print_icon "LEFT_SUBSEGMENT_SEPARATOR") "
   192	#POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
   193	#POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
   194	POWERLEVEL9K_DIR_HOME_BACKGROUND='white'
   195	POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="white"
   196	#POWERLEVEL9K_DISABLE_RPROMPT=true
   197	POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
   198	POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="blue"
   199	POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="black"
   200	#POWERLEVEL9K_MODE="awesome-fontconfig"
   201	#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_joined aws chruby virtualenv nvm vcs background_jobs)
   202	POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_joined virtualenv vcs)
   203	#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs history time)
   204	POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(history time)
   205	POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
   206	POWERLEVEL9K_SHORTEN_DELIMITER=""
   207	POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
```

Sys specs:
macOS 10.14.4
iTerm2 3.2.8
Fonts: Monaco and for the non-ASCII characters **SourceCodePro+Powerline+Awesome Regular**

Thanks!

**Comment by romkatv** [comment]
My guess is that you are defining `POWERLEVEL9K_MODE='awesome-fontconfig'` _after_ sourcing Powerlevel9k. Powerlevel9k picks up some of the options but not others if they are defined after the theme is sourced. It does not pick up `POWERLEVEL9K_MODE`, so your setting it has no effect on Powerlevel9k. Powerlevel10k, on the other hand, will pick up _all_ options that you set, regardless of where you set them in your config. You check whether my guess is correct by moving `POWERLEVEL9K_MODE='awesome-fontconfig'` to the very top of your `~/.zshrc`. If this breaks icons in your prompt when using Powerlevel9k, this is indeed the problem.

If you want to preserve the icons you currently have, simply remove `POWERLEVEL9K_MODE` form your config. Powerlevel9k will work like before, and Powerlevel10k will look the same.
