### ISSUE TITLE
Ability to update segments for transient prompt

### ISSUE THREAD

**Issue by HarHarLinks** [romkatv/powerlevel10k#480]
There is `POWERLEVEL9K_TIME_UPDATE_ON_COMMAND` which works great with [keeping the time segment in transient prompt](https://www.reddit.com/r/zsh/comments/dsh1g3/new_powerlevel10k_feature_transient_prompt/f6w9ept/?context=1).

I would like to use something like the following:
```
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off # acshually no

  function p10k-on-pre-prompt() { p10k display '1|2/right'=show '2/right/status|2/right/time|2/right/command_execution_time'=hide }

  function p10k-on-post-prompt() {
    [[ $last_prompt_dir == $PWD ]] && p10k display '1'=hide '2/right/status|2/right/time|2/right/command_execution_time'=show
    last_prompt_dir=$PWD
  }
```

The result is something like this:
![image](https://user-images.githubusercontent.com/2803622/74100573-e7effe80-4b30-11ea-9996-27ea88a1b70e.png)

I can see the color of the (next, bottom) prompt + segment making sense as to give immediate feedback on the last command. But for segments sticking around in transient mode, it would make more sense to me to have the indication on the associated failed line (i.e. "one earlier").

**Comment by romkatv** [comment]
I'm afraid this is impossible. See https://www.reddit.com/r/zsh/comments/eg49ff/powerlevel10k_prompt_history_exit_code_colors/fc5huku/ for details.

**Comment by romkatv** [comment]
Closing as there doesn't seem anything for me to do.

**Comment by HarHarLinks** [comment]
Thanks for the quick reply and explanation. I have edited my config to this:

```
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off # acshually no

  function p10k-on-pre-prompt() { p10k display '1/(left|gap|right/*)|2/right|empty_line'=show '2/right/time|2/right/command_execution_time'=hide }

  function p10k-on-post-prompt() {
    [[ $last_prompt_dir == $PWD ]] && p10k display '1/(left|gap|right/*)|empty_line'=hide '1/right/status|2/right/time|2/right/command_execution_time'=show
    last_prompt_dir=$PWD
  }
```

which seems to work okay given the constraints you explained:
![image](https://user-images.githubusercontent.com/2803622/74105353-5a76d380-4b5d-11ea-89fd-4debc7f4a7cb.png)


If the prompt functions have redundancy or can otherwise be optimized, please advice.

**Comment by romkatv** [comment]
> If the prompt functions have redundancy or can otherwise be optimized, please advice.

Your config looks fine to me.
