### ISSUE TITLE
How to configure `asdf` segments to show in project dirs?

### ISSUE THREAD

**Issue by levito** [romkatv/powerlevel10k#485]
I'd like to come back to my question originally posted in https://github.com/romkatv/powerlevel10k/issues/211#issuecomment-583272770:

What I want to do is showing certain segments not only when the version is different from `~/.tool-versions` but also when inside a project dir. I thought I could (mis)use `_p9k_upglob` which basically does what I need, so I added these lines to my `.zshrc`:

```zsh
function update-asdf-status() {
  typeset -f _p9k_upglob > /dev/null || return

  POWERLEVEL9K_ASDF_ELIXIR_PROMPT_ALWAYS_SHOW=$(_p9k_upglob 'mix.exs|*.ex' && echo false || echo true)
  POWERLEVEL9K_ASDF_ERLANG_PROMPT_ALWAYS_SHOW=$(_p9k_upglob 'mix.exs|*.ex|*.erl' && echo false || echo true)
  POWERLEVEL9K_ASDF_PYTHON_PROMPT_ALWAYS_SHOW=$(_p9k_upglob '*.py' && echo false || echo true)
  POWERLEVEL9K_ASDF_RUST_PROMPT_ALWAYS_SHOW=$(_p9k_upglob 'Cargo.toml|*.rs' && echo false || echo true)
}

autoload -U add-zsh-hook
add-zsh-hook chpwd update-asdf-status
update-asdf-status
```

When starting a new terminal session, I get an error:
```
_p9k_upglob:1: bad math expression: operand expected at `/mix.exs|*...'
_p9k_upglob:1: bad math expression: operand expected at `/mix.exs|*...'
_p9k_upglob:1: bad math expression: operand expected at `/*.py'
_p9k_upglob:1: bad math expression: operand expected at `/Cargo.tom...'
```

Afterwards it works partially but lags behind. `cd .` shows the correct segments.

Do you have an idea how to solve this?

[![asciicast](https://asciinema.org/a/JWWpWNGQHeNOrTQH3mv3AQYrM.png)](https://asciinema.org/a/JWWpWNGQHeNOrTQH3mv3AQYrM)

**Comment by romkatv** [comment]
Names that start with `_p9k`, `__p9k` or `_POWERLEVEL9K` are internal. If you use them in any way, bad things may happen. Prompt may display incorrect information, spew out errors, crash zsh, consume all CPU and memory, corrupt files, etc. If it appears to work now, it can break when you update powerlevel10k.

I can add a parameter like this:

```zsh
# If set to non-empty value, hide tool versions when neither the current directory nor any
# of its parent directories contain files matching the specified pattern.
#
# Note: If this parameter is set to an empty value, it won't hide tools.
# Tip:  Override this parameter for ${TOOL} with POWERLEVEL9K_ASDF_${TOOL}_SHOW_UPGLOB.
typeset -g POWERLEVEL9K_ASDF_SHOW_UPGLOB=
```

If you set `POWERLEVEL9K_ASDF_PYTHON_PROMPT_ALWAYS_SHOW=true` and `POWERLEVEL9K_ASDF_PYTHON_SHOW_UPGLOB='*.py'`, python version will be shown whenever you are in a directory of a python project. Outside of python projects it won't be shown.

Will this work for you? Note that it's different from what you are asking.

**Comment by levito** [comment]
Sounds awesome! This would be really easy to understand and flexible to use.

**Comment by romkatv** [comment]
Before I implement this, could you confirm that this will work for you? If the current python version in asdf is not equal to global, and you are not in a python project directory, prompt will not show python version. As far as I understand your attempt at implementing this, you wanted python version to be shown in this case. Are you OK with this difference?

The reason I want the behavior I proposed is that it makes all parameters that can hide tool versions independent. It's a much simpler model to understand as there are no interactions between parameters.

**Comment by levito** [comment]
Yeah, that's fine. Both approaches make sense somehow. The behavior which you suggest is pretty much like other segments work, e. g. `POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true`.

Would we still be able to have `asdf` versions shown when also setting the other options, like so:
```zsh
typeset -g POWERLEVEL9K_ASDF_SOURCES=(shell local global)
typeset -g POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false
typeset -g POWERLEVEL9K_ASDF_SHOW_SYSTEM=true
```

Or is `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=true` needed for your approach?

I think you can go for the version that's easier to implement.

**Comment by romkatv** [comment]
> Would we still be able to have `asdf` versions shown when also setting the other options

The easiest way to understand how different hiding parameters work is look at each parameter in isolation and understand under which conditions it will hide tool versions. Keep in mind that each parameter can only hide. None can unhide.

> `typeset -g POWERLEVEL9K_ASDF_SOURCES=(shell local global)`

This parameter never hides tool versions.

> `typeset -g POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false`

This parameter hides tool versions that are equal to global.

> `typeset -g POWERLEVEL9K_ASDF_SHOW_SYSTEM=true`

This parameter never hides tool versions.

Since parameters can only hide but not unhide, the order in which they are applied doesn't matter.

The new parameter that I'm going to add will work the same way. It will hide some tool versions in some circumstances but it will never unhide tool versions that get hidden by other parameters.

I think the biggest obstacle to understanding this is the poor naming of parameters. If they all had `HIDE_IF` in their names, it would be easier.

```
typeset -g POWERLEVEL9K_ASDF_HIDE_IF_SOURCE_NOT_ONE_OF_THESE=(shell local global)
typeset -g POWERLEVEL9K_ASDF_HIDE_IF_VERSION_THE_SAME_AS_GLOBAL=false
typeset -g POWERLEVEL9K_ASDF_HIDE_IF_VERSION_EQUALS_TO_SYSTEM=true
typeset -g POWERLEVEL9K_ASDF_HIDE_IF_NO_MATCH='*.py'
```

(These names are just for exposition. I'm not going to rename these parameters.)

Does it make sense?

**Comment by levito** [comment]
This makes sense, thanks a lot for explaining! And yes, that's fine for me.

**Comment by romkatv** [comment]
This is done. Once you update, this should work:

```zsh
typeset -g POWERLEVEL9K_ASDF_RUST_SHOW_ON_UPGLOB='Cargo.toml|*.rs'
```

You can either manually add these parameters or call `p10k configure` to generate a new config that already defines a skeleton.

`SHOW_ON_UPGLOB` parameters are generic. They work with all prompt segments.

**Comment by levito** [comment]
Awesome! It works like a charm once I set `POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=true`. Thank you so much!

**Comment by romkatv** [comment]
Thanks for the confirmation!
