### ISSUE TITLE
anaconda prompt appears without activated in libvterm

### ISSUE THREAD

**Issue by tshu-w** [romkatv/powerlevel10k#486]
The anaconda prompt appears without conda activated in libvterm but works fine in iTerm or terminal.

<img width="1380" alt="Screen Shot 2020-02-11 at 8 30 11 PM" src="https://user-images.githubusercontent.com/13161779/74237081-aa949800-4d0d-11ea-80ce-da61a0590a6f.png">

#### System Info :computer:
- OS: macOS 10.15.3
- Shell: zsh 5.7.1 (x86_64-apple-darwin19.0)
- Terminal: libvterm: stable 0.1.3

**Comment by romkatv** [comment]
This prompt segment is shown when `$CONDA_PREFIX` is not empty. This variable is set by conda. If you are seeing anaconda prompt segment in libvterm, it means `$CONDA_PREFIX` is not empty there. You can config this with `echo -E - $CONDA_PREFIX`. If you don't expect to see anaconda prompt segment in libvterm, find out what sets `$CONDA_PREFIX` and remove/change it.

**Comment by tshu-w** [comment]
@romkatv thank you for the quick reply, I figure it out that `$CONDA_PREFIX` is set by my emacs.
