### ISSUE TITLE
SHOW_ON_COMMAND do not work with custom element

### ISSUE THREAD

**Issue by Bysmyyr** [romkatv/powerlevel10k#488]
Hi, I like to use custom promt element:   POWERLEVEL9K_CUSTOM_KUBE_PS1='kube_ps1' but   typeset -g POWERLEVEL9K_POWERLEVEL9K_CUSTOM_KUBE_PS1_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc' do not work without it. It shows all the time. WIth normal kubecontext it works but I do not like the way it shows the context.

**Comment by romkatv** [comment]
If I may ask, what do you not like in the built-in kubecontext segment?

**Comment by Bysmyyr** [comment]
Hi, it do not show the context properly:

kubecontext: <3letter something>/<company>  
kube_ps1: (⎈ <context>:<company>)

That 3 letter something do not change if I change context which works in ps1

**Comment by romkatv** [comment]
Ouch. That sounds like a serious bug in powerlevel10k. I'd really like to fix it.

Could you add both kube_ps1 and kubecontext to prompt and post a screenshot when both of them are shown? In addition, please post the output of the following command:

```zsh
() {
  emulate -L zsh
  typeset -pm 'P9K_KUBECONTEXT_*|ZSH_VERSION|KUBECONFIG'
  kubectl config get-contexts
  kubectl version
}
```

**Comment by Bysmyyr** [comment]
`<cloudname>/<namespace> (⎈ <kubecontext_name>:<namespace>)

❯ () {

  emulate -L zsh

  typeset -pm 'P9K_KUBECONTEXT_*|ZSH_VERSION|KUBECONFIG'

  kubectl config get-contexts

  kubectl version

}
typeset -g P9K_KUBECONTEXT_CLOUD_ZONE=<cloud_zone>
typeset -g P9K_KUBECONTEXT_CLUSTER=arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>
typeset -g ZSH_VERSION=5.7.1
typeset -g P9K_KUBECONTEXT_NAMESPACE=<namespace>
typeset -g P9K_KUBECONTEXT_CLOUD_NAME=<cloudname>
typeset -g P9K_KUBECONTEXT_NAME=<kubecontext_name>
typeset -g P9K_KUBECONTEXT_CLOUD_CLUSTER=<cloudname>
typeset -g P9K_KUBECONTEXT_CLOUD_ACCOUNT=000000000000
typeset -g P9K_KUBECONTEXT_USER=arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>
typeset -g KUBECONFIG=/home/olli/.kube/config
CURRENT   NAME             CLUSTER                                             AUTHINFO                                            NAMESPACE
*         <kubecontext_name>     arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>   arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>   <namespace>
*  
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-<cloudname>-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by Bysmyyr** [comment]
Sorry about the formatting

`
<cloudname>/<namespace> (⎈ <kubecontext_name>:<namespace>)

❯ () {

  emulate -L zsh

  typeset -pm 'P9K_KUBECONTEXT_*|ZSH_VERSION|KUBECONFIG'

  kubectl config get-contexts

  kubectl version

}
typeset -g P9K_KUBECONTEXT_CLOUD_ZONE=<cloud_zone>
typeset -g P9K_KUBECONTEXT_CLUSTER=arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>
typeset -g ZSH_VERSION=5.7.1
typeset -g P9K_KUBECONTEXT_NAMESPACE=<namespace>
typeset -g P9K_KUBECONTEXT_CLOUD_NAME=<cloudname>
typeset -g P9K_KUBECONTEXT_NAME=<kubecontext_name>
typeset -g P9K_KUBECONTEXT_CLOUD_CLUSTER=<cloudname>
typeset -g P9K_KUBECONTEXT_CLOUD_ACCOUNT=000000000000
typeset -g P9K_KUBECONTEXT_USER=arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>
typeset -g KUBECONFIG=/home/olli/.kube/config
CURRENT   NAME             CLUSTER                                             AUTHINFO                                            NAMESPACE
*         <kubecontext_name>     arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>   arn:aws:<cloudname>:<cloud_zone>:000000000000:cluster/<cloudname>   <namespace>
*  
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-<cloudname>-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

`

**Comment by Bysmyyr** [comment]
Sorry about formatting:

first kubecontext, then ps_1: cloudname/namespace (⎈ kubecontext_name:namespace)

❯ () {

  emulate -L zsh

  typeset -pm 'P9K_KUBECONTEXT_*|ZSH_VERSION|KUBECONFIG'

  kubectl config get-contexts

  kubectl version

}
typeset -g P9K_KUBECONTEXT_CLOUD_ZONE=cloud_zone
typeset -g P9K_KUBECONTEXT_CLUSTER=arn:aws:cloudname:cloud_zone:000000000000:cluster/cloudname
typeset -g ZSH_VERSION=5.7.1
typeset -g P9K_KUBECONTEXT_NAMESPACE=namespace
typeset -g P9K_KUBECONTEXT_CLOUD_NAME=cloudname
typeset -g P9K_KUBECONTEXT_NAME=kubecontext_name
typeset -g P9K_KUBECONTEXT_CLOUD_CLUSTER=cloudname
typeset -g P9K_KUBECONTEXT_CLOUD_ACCOUNT=000000000000
typeset -g P9K_KUBECONTEXT_USER=arn:aws:cloudname:cloud_zone:000000000000:cluster/cloudname
typeset -g KUBECONFIG=/home/olli/.kube/config
CURRENT   NAME             CLUSTER                                             AUTHINFO                                            NAMESPACE
*         kubecontext_name     arn:aws:cloudname:cloud_zone:000000000000:cluster/cloudname   arn:aws:cloudname:cloud_zone:000000000000:cluster/cloudname   namespace
*  
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.11", GitCommit:"25074a190ef2a07d8b0ed38734f2cb373edfb868", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-cloudname-eb1860", GitCommit:"eb1860579253bb5bf83a5a03eb0330307ae26d18", GitTreeState:"clean", BuildDate:"2019-12-23T08:58:45Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Comment by romkatv** [comment]
Thanks!

The format of kubecontext is specified in `~/.p10k.zsh`. The relevant part is here: https://github.com/romkatv/powerlevel10k/blob/eb3ddadc6c6a99526925434c3ed4a48e3303c6cf/config/p10k-lean.zsh#L984-L1028

To display it as `(⎈ kubecontext_name:namespace)`, type the following commands:

```zsh
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='$P9K_KUBECONTEXT_NAME:$P9K_KUBECONTEXT_NAMESPACE'
typeset -g POWERLEVEL9K_KUBECONTEXT_PREFIX='('
typeset -g POWERLEVEL9K_KUBECONTEXT_SUFFIX=')'
typeset -g POWERLEVEL9K_KUBECONTEXT_VISUAL_IDENTIFIER_EXPANSION='⎈'
p10k reload
```

Does `kubecontext` now display what you want? If not, could you post the same data as before for the case where it doesn't display what you want?

**Comment by Bysmyyr** [comment]
Uuh, thanks a lot!

**Comment by Bysmyyr** [comment]
That issue is fixed for me but is there some reason that it do not work with custom commands?

**Comment by romkatv** [comment]
Glad it's working for you now :rocket:

Another popular feature among `kubecontext` users is context classes. It allows you to use different icons and colors with different kubernetes contexts. Great for distinguishing between prod and test/staging contexts. See here: https://github.com/romkatv/powerlevel10k/blob/eb3ddadc6c6a99526925434c3ed4a48e3303c6cf/config/p10k-lean.zsh#L951-L982

In general, `kubecontext` in powerlevel10k should be able to do anything that `kube_ps1` can do, plus more. It's also faster.

> That issue is fixed for me but is there some reason that it do not work with custom commands?

The API you've used to define a custom segment is considered legacy in Powerlevel10k. It still works and will continue to work forever because Powerlevel10k promises to handle all existing Powerlevel9k configs. However, new Powerlevel10k-only features may or may not work with custom segments that use legacy API.

Powerlevel10k has a better API for defining custom segments that is both more powerful and more performant. See [docs](https://github.com/romkatv/powerlevel10k/blob/master/README.md#extensible) or search for `prompt_example` in `~/.p10k.zsh`. All Powerlevel10k features work with segments defined this way.

Having said that, it turned out that making the old-style custom segments work with `SHOW_ON_COMMAND` is super easy, so I went ahead and committed https://github.com/romkatv/powerlevel10k/commit/3ca90731b0cc9f935c11f0f8fe3b2a72622712bf.

Thanks for opening this issue!
