### ISSUE TITLE
Ruby version behavior sporadic

### ISSUE THREAD

**Issue by Serneum** [romkatv/powerlevel10k#492]
OS: MacOS 10.14.6
Shell: iTerm2 + zsh
Ruby version manager: asdf
My global version is set to 2.4.3 in `~/.tool-versions`

It looks like p10k only occasionally knows what my Ruby version is, with some projects not showing anything from the right side prompt at all, sometimes showing the Ruby version, and sometimes showing the entirety of my Gemfile

No right prompt (and my directories are shortened when they definitely do not need to be):
![image](https://user-images.githubusercontent.com/1091716/74467907-f3f8fa80-4e67-11ea-8f4d-b05c96f75385.png)

Ruby version, working as intended:
![image](https://user-images.githubusercontent.com/1091716/74469706-33751600-4e6b-11ea-9f52-206727ff89e2.png)

Gemfile as ruby version (this goes on for many lines):
![image](https://user-images.githubusercontent.com/1091716/74467993-1a1e9a80-4e68-11ea-9cf5-969eabd375e6.png)

My POWERLEVEL9k_RIGHT_PROMPT_ELEMENTS is pretty sparse, containing just `status`, `command_execution_time`, `asdf`, and `newline`. Most of the time, nothing shows up on the right, so I expect that something is breaking and keeping anything from rendering but I haven't figured out what. My `.p10k.zsh` file is pretty standard since I just installed p10k a day or two ago. Most of the modifications have just been to remove elements from the Right Prompt and to adjust the white color for the directory.

Is there anything I should try to attempt to solve the ruby version and right prompt issues?

**Comment by romkatv** [comment]
Does this problem reproduce if you update powrlevel10k to the latest version and restart zsh?

Please attach `~/.p10k.zsh`.

What is the output of `asdf current`?

Do you get correct right prompt if you type `cd`? If you type `cd /`?

**Comment by Serneum** [comment]
ASDF Current:
![image](https://user-images.githubusercontent.com/1091716/74468759-5ef70100-4e69-11ea-8d32-014655922f0c.png)

[.p10k.zsh](https://pastebin.com/t1C7ZnTb)

`cd` / `cd /`:
Output appears correct. I can see a green check and `2.4.3` for the ruby version in the right prompt area

powerlevel10k update:
I just went to the theme's directory and did a `git pull`. Some updates did come down, but nothing changed in what I am seeing. I did notice, however, a red X when the terminal started up, which would imply some command failed, right?
![image](https://user-images.githubusercontent.com/1091716/74469200-2d326a00-4e6a-11ea-89f0-c443d946fa6a.png)

**Comment by romkatv** [comment]
Have you restarted Zsh after `git pull`?

Does it work in `~/w*` (I don't know the full name of this directory but it's the only subdirectory of `~` that starts with `w`).

**Comment by Serneum** [comment]
I did restart zsh. I tried running `zsh` and just completely quitting iTerm2 and restarting it to verify that nothing had changed.

~/w is the `workspace` directory that I thought I had posted above, though I accidentally posted the same screenshot twice. Here's a screenshot of the ruby version working:
![image](https://user-images.githubusercontent.com/1091716/74469680-2a844480-4e6b-11ea-9c97-074299769147.png)

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
() {
  emulate -L zsh -o xtrace -o dotglob -o extended_glob
  command ls -lA ~/workspace/epa-admin/*(^/)
  typeset -pm 'ASDF_*'
  command ls -lA ${ASDF_DATA_DIR:-~/.asdf}/plugins/ruby
  ${ASDF_DATA_DIR:-~/.asdf}/plugins/ruby/bin/list-legacy-filenames(N)
}
```

**Comment by Serneum** [comment]
```
+(anon):2> ls -lA ~/workspace/epa-admin/.babelrc ~/workspace/epa-admin/.ciconfig ~/workspace/epa-admin/.cmmdata.yml ~/workspace/epa-admin/.dockerignore ~/workspace/epa-admin/.enviro ~/workspace/epa-admin/.gitignore ~/workspace/epa-admin/.rspec ~/workspace/epa-admin/CONTRIBUTING.md ~/workspace/epa-admin/Capfile ~/workspace/epa-admin/Dockerfile ~/workspace/epa-admin/Gemfile ~/workspace/epa-admin/Gemfile.lock ~/workspace/epa-admin/Jenkinsfile ~/workspace/epa-admin/README.md ~/workspace/epa-admin/Rakefile ~/workspace/epa-admin/config.ru ~/workspace/epa-admin/docker-compose-onprem.yml ~/workspace/epa-admin/tags
-rw-r--r--  1 crees  INNOVA\Domain Users      25 Sep 26 13:47 ~/workspace/epa-admin/.babelrc
-rw-r--r--  1 crees  INNOVA\Domain Users      55 Jan 30 08:58 ~/workspace/epa-admin/.ciconfig
-rw-r--r--  1 crees  INNOVA\Domain Users     132 Feb  7 11:23 ~/workspace/epa-admin/.cmmdata.yml
-rw-r--r--  1 crees  INNOVA\Domain Users      42 Feb  7 11:23 ~/workspace/epa-admin/.dockerignore
-rw-r--r--  1 crees  INNOVA\Domain Users       9 Sep 26 13:47 ~/workspace/epa-admin/.enviro
-rw-r--r--  1 crees  INNOVA\Domain Users     453 Feb  7 11:23 ~/workspace/epa-admin/.gitignore
-rw-r--r--  1 crees  INNOVA\Domain Users      31 Feb  7 11:41 ~/workspace/epa-admin/.rspec
-rw-r--r--  1 crees  INNOVA\Domain Users    1719 Sep 26 13:47 ~/workspace/epa-admin/CONTRIBUTING.md
-rw-r--r--  1 crees  INNOVA\Domain Users     344 Sep 26 13:47 ~/workspace/epa-admin/Capfile
-rw-r--r--  1 crees  INNOVA\Domain Users     409 Feb  7 11:23 ~/workspace/epa-admin/Dockerfile
-rw-r--r--  1 crees  INNOVA\Domain Users    1845 Feb  7 11:32 ~/workspace/epa-admin/Gemfile
-rw-r--r--  1 crees  INNOVA\Domain Users   11076 Feb  7 11:33 ~/workspace/epa-admin/Gemfile.lock
-rw-r--r--  1 crees  INNOVA\Domain Users    1046 Feb 11 14:48 ~/workspace/epa-admin/Jenkinsfile
-rw-r--r--  1 crees  INNOVA\Domain Users    2803 Sep 26 13:47 ~/workspace/epa-admin/README.md
-rw-r--r--  1 crees  INNOVA\Domain Users     295 Sep 26 13:47 ~/workspace/epa-admin/Rakefile
-rw-r--r--  1 crees  INNOVA\Domain Users     153 Sep 26 13:47 ~/workspace/epa-admin/config.ru
-rw-r--r--  1 crees  INNOVA\Domain Users    1300 Feb  7 11:23 ~/workspace/epa-admin/docker-compose-onprem.yml
-rw-r--r--  1 crees  INNOVA\Domain Users  617106 Feb  7 11:55 ~/workspace/epa-admin/tags
+(anon):3> typeset -pm 'ASDF_*'
typeset -g ASDF_BIN=/usr/local/opt/asdf/bin
typeset -g ASDF_USER_SHIMS=~/.asdf/shims
export ASDF_DIR=/usr/local/opt/asdf
+(anon):4> ls -lA ~/.asdf/plugins/ruby
total 32
drwxr-xr-x  9 crees  INNOVA\Domain Users   288 Dec 18 13:01 .git
-rw-r--r--  1 crees  INNOVA\Domain Users    11 Dec 18 13:01 .gitignore
-rw-r--r--  1 crees  INNOVA\Domain Users   279 Dec 18 13:01 .travis.yml
-rw-r--r--  1 crees  INNOVA\Domain Users  1077 Dec 18 13:01 LICENSE
-rw-r--r--  1 crees  INNOVA\Domain Users  2594 Dec 18 13:01 README.md
drwxr-xr-x  7 crees  INNOVA\Domain Users   224 Dec 18 13:01 bin
drwxr-xr-x  3 crees  INNOVA\Domain Users    96 Dec 18 13:01 lib
drwxr-xr-x  4 crees  INNOVA\Domain Users   128 Jan 21 10:03 ruby-build
drwxr-xr-x  3 crees  INNOVA\Domain Users    96 Dec 18 13:01 rubygems-plugin
+(anon):5> ~/.asdf/plugins/ruby/bin/list-legacy-filenames
.ruby-version Gemfile
```

I substituted `~` in for my home directory just to be safe

**Comment by romkatv** [comment]
I think we are getting close to solving the mystery. Please run another command and post its output.

```zsh
() {
  emulate -L zsh -o xtrace
  command ls -lA ~/.asdf/plugins/ruby/bin
  ~/.asdf/plugins/ruby/bin/parse-legacy-file ~/workspace/epa-admin/Gemfile
  echo $?
  typeset -pm '_p9k_asdf_*|_p9k__asdf_*'
}
```

**Comment by Serneum** [comment]
```
+(anon):2> ls -lA ~/.asdf/plugins/ruby/bin
total 40
-rwxr-xr-x  1 user  group   310 Dec 18 13:01 exec-env
-rwxr-xr-x  1 user  group  2643 Dec 18 13:01 install
-rwxr-xr-x  1 user  group   390 Dec 18 13:01 list-all
-rwxr-xr-x  1 user  group    50 Dec 18 13:01 list-legacy-filenames
-rwxr-xr-x  1 user  group   930 Dec 18 13:01 parse-legacy-file
+(anon):3> ~/.asdf/plugins/ruby/bin/parse-legacy-file ~/workspace/epa-admin/Gemfile

+(anon):4> echo 0
0
+(anon):5> typeset -pm '_p9k_asdf_*|_p9k__asdf_*'
typeset -g -a _p9k_asdf_meta_files=( ~/.asdfrc ~/.asdf/plugins ~/.asdf/plugins/elixir/bin/list-legacy-filenames ~/.asdf/plugins/java/bin/list-legacy-filenames ~/.asdf/plugins/ruby/bin/list-legacy-filenames )
typeset -g _p9k_asdf_meta_sig=$'\C-@\C-@1579622034\C-@1576695247\C-@1576692040\C-@1576695239\C-@1576692063'
typeset -g -a _p9k_asdf_plugins=( elixir erlang groovy java ruby )
typeset -g -a _p9k_asdf_meta_non_files=( ~/.asdf/plugins/erlang/bin/list-legacy-filenames ~/.asdf/plugins/groovy/bin/list-legacy-filenames )
typeset -g -A _p9k__asdf_dir2files=( ~ 1581622511:~/.tool-versions ~/workspace 1581622511: )
typeset -g -A _p9k_asdf_file_info=( .exenv-version 'elixir 0 ' .java-version 'java 0 ' .ruby-version 'ruby 0 ' Gemfile 'ruby 0 ' )
typeset -g -A _p9k_asdf_file2versions=( :~/.tool-versions $'1579630778:ruby\C-@2.4.3' )
```

Same as before, I substituted in `~` for my home directory

**Comment by romkatv** [comment]
Thank you! Fix incoming.

> Same as before, I substituted in `~` for my home directory

FWIW, I didn't understand this comment both times you've posted it. The information you posted indicates that you've ran the commands I've asked. What did you replace?

**Comment by Serneum** [comment]
Oh, sorry. I shortened the directories in the output so as to not leak any user information (my home directory, username, etc)

**Comment by romkatv** [comment]
> Oh, sorry. I shortened the directories in the output so as to not leak any user information (my home directory, username, etc). Since `~` would be equivalent, I just swapped the absolute path in the output to use it so that the value would be the same, just in case it mattered.

Oh, right. Got it. Thanks for the explanation.

I've committed a fix for this bug. Please update powerlevel10k and restart zsh. Does it work now?

**Comment by Serneum** [comment]
Yep. Updated, restarted my terminal and now everything works as expected. The right prompt consistently shows up, and the Ruby version is accurate. Thanks!

**Comment by romkatv** [comment]
Thanks for your invaluable help with remote debugging!

Here's what was happening. When `~/.asdfrc` contains `legacy_version_file = yes`, `asdf` recognizes `.ruby-version` and `Gemfile` as additional files that can override Ruby version. If there is `~/.asdf/plugins/ruby/bin/parse-legacy-file`, it is used to parse these files. If there isn't, `cat` is used instead.

Powrelevel10k contains an embedded implementation of asdf that's about 1000 times faster than the official. It's supposed to work exactly like the stock asdf. That implementation had a bug where it would go haywire if `~/.asdfrc` doesn't contain `legacy_version_file = yes`. My bad, I've only tested Powerlevel10k with `legacy_version_file = yes`. The bug was causing the whole content of Gemfile to be treated as Ruby version. Since right prompt was becoming very long, directory was fully shortened to allow it to fit. It still didn't fit, so right prompt was dropped to avoid overlapping left prompt.
