### ISSUE TITLE
add custom variables to prompt

### ISSUE THREAD

**Issue by germio** [romkatv/powerlevel10k#495]
Hi how do I add a custom variable
for instance in my .zshrc
I have a custom variable called $USER_SERVER=the_server_user
How do I load it in context of .p10K.zsh

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#extensible.

For example, add this function to `~/.p10k.zsh`:

```zsh
function prompt_my_user_server() {
  if [[ -n $USER_SERVER ]]; then
    p10k segment -b yellow -f red -i '▼' -t "${USER_SERVER//\%/%%}"
  fi
}
```

Then add `my_user_server` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in the same file.

**Comment by germio** [comment]
Thank you omkatv
