### ISSUE TITLE
POWERLEVEL9K_DIR_FOREGROUND - Only works partially

### ISSUE THREAD

**Issue by Sherulez** [romkatv/powerlevel10k#497]
Hi,

I would like to change the color of the name of the current folder (regardless of his class).

If I understand correctly by reading the `.p10k.zsh` file, this line should be modified.

**# Default current directory color.**
`POWERLEVEL9K_DIR_FOREGROUND=red`

When I do so, this is the result : 
![Capture](https://user-images.githubusercontent.com/25638207/74568261-df0b8c80-4f77-11ea-8f7b-c87ebfe2dd1f.PNG)

The icon and the `/` turns red, but not the rest (`~` & `Desktop`)

Is it by design?

I also tried :
```
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=red
POWERLEVEL9K_FORBIDDEN_FOREGROUND=red
POWERLEVEL9K_DIR_HOME_FOREGROUND=red
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=red
```

- zsh v.5.7.1
- oh-my-zsh (stock config)
- powerlevel10k v.latest (stock config after p10k configure `classic / light` )

**Edit :**
2 levels down : 
![Capture](https://user-images.githubusercontent.com/25638207/74569970-ecc31100-4f7b-11ea-89e3-4b90af176750.PNG)

Now Desktop is red but the current directory is still not.

**Edit2 :**
After some digging into the` .p10k.zsh` file I finally found my answer : 

```
  # Color of the anchor directory segments. Anchor segments are never shortened. The first
  # segment is always an anchor.
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=red
```

**Comment by romkatv** [comment]
The color of `dir` prompt segment is controlled by the following parameters:

- `POWERLEVEL9K_DIR_FOREGROUND`
- `POWERLEVEL9K_DIR_SHORTENED_FOREGROUND`
- `POWERLEVEL9K_DIR_ANCHOR_FOREGROUND`
- `POWERLEVEL9K_DIR_ANCHOR_BOLD`

Look for them in `~/.p10k.zsh`. Surrounding comments explain what each parameter means.
