### ISSUE TITLE
How to add all kubectl aliases to SHOW_ON_COMMAND

### ISSUE THREAD

**Issue by Shini31** [romkatv/powerlevel10k#500]
Hello,

Oh-My-Zsh provides very useful aliases for kubectl command.
How to map all theses aliases to `POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND` without adding all of them (a ton of aliases)?

Regards.

**Comment by romkatv** [comment]
Do you have an example alias that doesn't get recognized by powerlevel10k out of the box?

**Comment by Shini31** [comment]
After a reload of zsh, it's working...

Sorry for the fast ticket opening.
Thanks for your reactivity !

Regards.

**Comment by romkatv** [comment]
It's not clear from the docs but Powerlevel10k understands the syntax of Zsh commands. It knows that `k` and `sudo kubectl` call `kubectl` while `echo kubectl` and `sudo k` don't.

**Comment by Shini31** [comment]
In my case, with aliases provided by Oh-My-Zsh `kubectl` plugins (kgp, kdelp, ...) it works.

**Comment by romkatv** [comment]
> In my case, with aliases provided by Oh-My-Zsh `kubectl` plugins (kgp, kdelp, ...) it works.

Thanks for the confirmation. Note that `kgp` triggers the display of kubernetes context in prompt, while `echo kgp` doesn't. This is expected behavior.

**Comment by diego898** [comment]
I did… that’s why I posted - I was asking if there was some other (more preferred/correct way)

**Comment by romkatv** [comment]
You've defined a new command and told powerlevel10k that `kubecontext` should be displayed when you are invoking this command. This is all fine. Powerlevel10k won't make this decision for you and will respect `POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND`.
