### ISSUE TITLE
How to do can make my custom element apply the function that display when my data ready？

### ISSUE THREAD

**Issue by weiyouwozuiku** [romkatv/powerlevel10k#503]
How to do can make my custom element apply the function that display when my data ready？just like the function of ip or publicIP.By the way , how to do can make me to use the function public_ip return the real ip for my function.

**Comment by romkatv** [comment]
> How to do can make my custom element apply the function that display when my data ready？just like the function of ip or publicIP.

1. Define a custom segment that displays a parameter whenever it's not empty:
```zsh
function prompt_my_stuff() {
  p10k segment -b yellow -f red -i '▼' -c '$my_stuff' -t '${my_stuff//\%/%%}'
}
```
2. Compute the value of the parameter any way you like. If you want to compute it asynchronously, https://github.com/mafredri/zsh-async is one way to do it.
3. Set the parameter and call `zsh reset-prompt` and `zle -R`.

> how to do can make me to use the function public_ip return the real ip for my function

I don't understand the question.

**Comment by weiyouwozuiku** [comment]
I mean ,in my custom element ,can I ask the value of the ip prompt into my function?

**Comment by romkatv** [comment]
> I mean ,in my custom element ,can I ask the value of the ip prompt into my function?

No.

**Comment by weiyouwozuiku** [comment]
thanks!
