### ISSUE TITLE
No file status for Mercurial repos

### ISSUE THREAD

**Issue by chrbirks** [romkatv/powerlevel10k#505]
Hi
I'm having a hard time figuring out why the vcs status line doesn't show the number of added/modified/untracked files for Mercurial as it does for a Git repository:
![Screenshot from 2020-02-16 16-20-28](https://user-images.githubusercontent.com/12070287/74607320-522c1480-50d8-11ea-9232-951a0c6e0928.png)

I have added hg as a backend to `.p10k.zsh`:
`typeset -g POWERLEVEL9K_VCS_BACKENDS=(git hg)`
And I assumed the function `my_git_formatter()` would also be used for Mercurial but maybe I'm missing something?

**Comment by romkatv** [comment]
`my_git_formatter` has the following lines at the top:

```zsh
if [[ -n $P9K_CONTENT ]]; then
  # If P9K_CONTENT is not empty, use it. It's either "loading" or from vcs_info (not from
  # gitstatus plugin). VCS_STATUS_* parameters are not available in this case.
  typeset -g my_git_format=$P9K_CONTENT
  return
fi
```

This is the code path that gets taken for every vcs backend that isn't `git`.

Support for non-git vcs backends in Powerlevel10k is quite terrible. It's about 100 times slower than everything else (you should notice how much slower your prompt gets when you simply add `hg` to the list of backends; it should be really slow when you are actually in a Mercurial repo) and doesn't support decent formatting. I'm maintaining it for backward compatibility with Powerlevel9k and making sure it's not worse than in Powerlevel9k. Virtually everyone is using Git, so the demand for good hg and svn support is almost inexistent.

**Comment by chrbirks** [comment]
Yes I noticed everything slowed down significantly when in the hg repo. I use hg at work so I'll just give it a try and see if it's usable as it is.
