### ISSUE TITLE
Broken glyphs on the right side of the prompt.

### ISSUE THREAD

**Issue by A-Lamia** [romkatv/powerlevel10k#506]
Not sure what is happening here, no matter how i change the style of the prompt or the font the right side check icon never has a background.

Is this fixable or is there a way i can remove it ?

Currently using Windows Terminal with the Iosevka font. 

![](https://ss.lamia.io/i/WindowsTerminal_e2oEShOau.png)

**Comment by romkatv** [comment]
This is a bug in windows terminal. You can do one of the following:

1. Use a different terminal.
2. Use Lean or Classic style.
3. Open `~/.p10.zsh`, search for `BACKGROUND=0`, uncomment all those parameters (if they are commented out) and replace value `0` with anything else.

**Comment by romkatv** [comment]
Forgot to mention what the bug is. Windows terminal cannot display black background (color 0). It shows it the same way as clear background. Black foreground, on the other hand, is perfectly visible.

**Comment by A-Lamia** [comment]
Tested it out on 3 other terminals and the same issue, though your fix worked well for all of them thanks.

**Comment by romkatv** [comment]
> Tested it out on 3 other terminals and the same issue

All on Windows I suppose? The bug is in ConPTY, so all terminals that use ConPTY are affected. Here's the issue (still open): https://github.com/microsoft/terminal/issues/293.

Here's a simple test for the terminal bug:

```zsh
for c in 1 0 2; do print -P ">%K{$c} %k%F{$c}\u2588%f<"; done
```

You'll notice that the middle line of the output is not like the others.

**Comment by A-Lamia** [comment]
The only one that fully worked was Mintty bottom right corner.

![](https://ss.lamia.io/i/NVIDIA_Share_ajmdiVRQZ.png)
