### ISSUE TITLE
Any way to use P10K as Tmux status line?

### ISSUE THREAD

**Issue by webnetwiz** [romkatv/powerlevel10k#507]
Hello @romkatv ,

Wanted to find out if I can use P10K inside of Tmux as its status line? Right now my P10K works perfectly, but once Tmux is started, it uses its own status line which is... very simple, to say the least, and is very archaic in its configuration in comparison to what you built with P10K. Thanks in advance!

**Comment by romkatv** [comment]
No, this is not currently possible. Powerlevel10k uses Zsh features extensively. It cannot be ported to other shells or environments.
