### ISSUE TITLE
conditional statements

### ISSUE THREAD

**Issue by iomari** [romkatv/powerlevel10k#508]
Greetings,
is it possible to use conditional statements such that I can use something like:
   if [ "$HOST" = hostname1]; then
       typeset -g POWERLEVEL9K_DIR_BACKGROUND=5
  elif [ "$HOST" = hostname2 ]; then
      typeset -g POWERLEVEL9K_DIR_BACKGROUND='darkred'
  else
      typeset -g POWERLEVEL9K_DIR_BACKGROUND=4

The reason I need this is so that I can have the same pk10 config in all of my systems and have colors based on hostname, ip address, etc.

Thansks in advance
iomari

**Comment by romkatv** [comment]
Yes.

**Comment by romkatv** [comment]
Is there anything else you wanted to ask? The code you wrote works, so I'm a bit confused about the issue.

**Comment by iomari** [comment]
when I run it I get:

   This is Powerlevel10k configuration wizard. You are seeing it because you
 haven't defined any Powerlevel10k configuration options. It will ask you a few
                      questions and configure your prompt.

                Does this look like a diamond (rotated square)?
                  reference: https://graphemica.com/%E2%97%86

                                 --->    <---

(y)  Yes.

(n)  No.

(q)  Quit and do nothing.

[1]  + 18277 suspended (tty output)  
apps%

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration-wizard-runs-automatically-every-time-zsh-is-started

**Comment by romkatv** [comment]
Have you resolved the problem? Is there anything I can help with?

**Comment by romkatv** [comment]
Closing as the reporting is MIA.

**Comment by alexdauenhauer** [comment]
Hello what is the condition I would use to set the LEFT_PROMPT_END_SEGMENT to empty if on a git repo?

![image](https://user-images.githubusercontent.com/11903445/85887123-d2603600-b7ac-11ea-8a93-bd61c379d34d.png)

In the above image, I want the angled end segment when I am in a normal directory, but I want a clear background with no end segment when in a git repo

**Comment by romkatv** [comment]
@alexdauenhauer Please don't post on unrelated issue. Open a new one and I'll be happy to help you out.
