### ISSUE TITLE
the os_icon prompt element loads as an empty character box in urxvt

### ISSUE THREAD

**Issue by borysn** [romkatv/powerlevel10k#509]
hi

the os_icon prompt element loads as an empty character box on voidlinux/gentoo in urxvt. can't figure out what's going on. all the other icons work fine

voidlinux doesn't have an icon (can we add one?), so it should load the default linux penguin, but it does not (in urxvtt). gentoo linux does have an icon, but it's still not loading, and not even dropping into a default penguin. 

the icon will load if i bring up a different terminal, like alacritty, termite, or tilix

it's weird because it worked at first on gentoo in urxvt, but i'm not sure what happened. had a similar issue when i was playing around with manjaro this week

any idea what could be going on? semms like i must've broke something somewhere, but it's not clear to me what could have gone wrong 

thanks

**Comment by psprint** [comment]
It works here on Gentoo / urxvt. Side question: how are the icons implemented?

**Comment by romkatv** [comment]
@borysn Please run the following command on Gentoo in urxvt and post a screenshot that includes the original command, its output, and the next (active) prompt.

```zsh
() {
  emulate -L zsh -o xtrace -o err_return
  uname
  [[ ! -r /etc/os-release ]] || command cat /etc/os-release
  typeset -pm 'ZSH_VERSION|_p9k_os|_p9k_os_icon|POWERLEVEL9K_(MODE|LINUX_*_ICON)'
  print -rl -- "$langinfo[CODESET]" "$_p9k_os_icon" $'\uF30D'
}
```

> voidlinux doesn't have an icon (can we add one?)

Sure, if you can help.

1. How to detect that a user is running voidlinux?
2. Which icon from https://www.nerdfonts.com/cheat-sheet to use?

@psprint I've opened https://github.com/romkatv/powerlevel10k/issues/510 to avoid side-tracking this issue. In the future feel free to open issues liberally when you want to ask a question about powerlevel10k. There is also gitter chat room (linked from the top of the powerlevel10k homepage).

**Comment by borysn** [comment]
@psprint, i am unsure of how the icons are implemented, i just pulled the recommended font patched meslo nerd font (MesloLGS NF). the thing is that it /was/ working for me. i just can't figure out what happened. or why it's behaving this way now

am i not seeing an obvious mistake or something in my urxvt? i believe i was playing around with font config when this started happening, i don't remember changing anything else before it started not working

```
! .resources 

! cursor theme
Xcursor.theme: deepin
Xcursor.size: 16

! settings for urxvt and xft

! xft settings
Xft.dpi: 96
Xft.lcdfilter: lcddefault
Xft.hinting: true
Xft.hintstyle: hintfull
Xft.antialias: true
Xft.rgba: rgb

!!!!!!!!!!!!!!!!!!!!
! general settings !
!!!!!!!!!!!!!!!!!!!!

URxvt.font: xft:Hack:style=Regular:size=10,\
    xft:Symbola:stye=Regular,\
    xft:Font Awesome 5 Free:style=Regular,\
    xft:MesloLGS NF:style=Regular

!    xft:MesloLGLDZ Nerd Font:style=RegularForPowerline
!    xft:DejaVu Sans Mono for Powerline:style=Book,\

URxvt.boldFont: xft:Hack:size=10:style=Bold
URxvt.italicFont: xft:Hack:size=10:stye=Italic
URxvt.boldItalicFont: xft:Hack:size=10:style=Bold Italic

!URxvt.letterSpace: 0
URxvt.saveLines: 10000
URxvt.scrollBar: false
URxvt.scrollTtyOutput: false
URxvt.scrollWithBuffer: true
URxvt.scrollTtyKeypress: true
URxvt.scrollstyle: rxvt
URxvt.urgentOnBell: true
URxvt.cursorBlink: true
URxvt.cursorUnderline: false
URxvt.iso14755: false
URxvt.internalBorder: 12
URxvt.depth: 32

!!!!!!!!!!!!!!!!!!!
! perl extensions !
!!!!!!!!!!!!!!!!!!!

! enable extensions
URxvt.perl-ext: default,url-select
URxvt.perl-ext-common: clipboard,matcher

! cut and paste
URxvt.clipboard.autocopy: true
URxvt.keysym.M-c: perl:clipboard:copy
URxvt.keysym.M-v: perl:clipboard:paste

! clickable urls
URxvt.url-launcher: /usr/bin/xdg-open
URxvt.matcher.button: 1
URxvt.keysym.C-Delete: perl:matcher:last
URxvt.keysym.M-Delete: perl:matcher:list
URxvt.matcher.rend.0: Uline Bold fg5

! yanktable urls (no mouse)
URxvt.keysym.M-u: perl:url-select:select_next
URxvt.url-select.launcher: /usr/bin/xdg-open
URxvt.url-select.underline: true

! tabbed
URxvt.tabbed.tabbar-fg: 2
URxvt.tabbed.tabbfar-bg: 0
URxvt.tabbed.tab-fg: 3
URxvt.tabeed.tab-bg: 0
```

**Comment by borysn** [comment]
here is the [screenshot](https://pasteboard.co/IVrfqZ1.png) 

as far as detecting void, the script you posted would work fine

```
() {
  emulate -L zsh -o xtrace -o err_return
  uname
  [[ ! -r /etc/os-release ]] || command cat /etc/os-release
  typeset -pm 'ZSH_VERSION|_p9k_os|_p9k_os_icon|POWERLEVEL9K_(MODE|LINUX_*_ICON)'
  print -rl -- "$langinfo[CODESET]" "$_p9k_os_icon" $'\uF30D'
}
```

NAME, ID, DISTRIB_ID, PRETTY_NAME all return "void" on voidlinux. but i do not see a void specific icon in nerd fonts. so i guess defaulting to the linux penguin is fine. if only i could figure out what i broke that it's not displaying >.< 

should i open an issue with nerd fonts and ask them to add voidlinux as an icon?

**Comment by romkatv** [comment]
Thanks for the info. Your terminal is fine. Something is broken in your powerlevel10k config.

What's is the output of `typeset -pm 'POWERLEVEL9K_OS_ICON_*'`?

**Comment by borysn** [comment]
@romkatv here is the output

```
typeset POWERLEVEL9K_OS_ICON_FOREGROUND=232
typeset POWERLEVEL9K_OS_ICON_BACKGROUND=7
typeset POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='%B${P9K_CONTENT// }'
```
i am not sure that p10k config is an issue here, because i can generate a fresh one and have the same issue. i believe this started with editing fonts in urxvt config, which i posted above. all the icons display fine during `p10k configure` until it builds out the status line again with the os_icon i should have and displays, which also shows a missing character box during the interactive config setup

**Comment by romkatv** [comment]
Try removing `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`. If this helps, try putting it back and removing just `%B` from it.

**Comment by borysn** [comment]
@romkatv that did it! 

went ahead and added the bold font to urxvt font config, and everything is loading fine now. didn't think that was going to be necessary because it worked fine at first. it probably broke at first then when i started specifying a bold font for ttf-hack. then i didn't think to add the bold style for the meslo font because removing those config options didn't help after that

thank you ^-^

**Comment by romkatv** [comment]
You are welcome.

> should i open an issue with nerd fonts and ask them to add voidlinux as an icon?

Up to you.

Can you post the output of `cat /etc/os-release` on voidlinux? I'll add it to the list of Linuxes in p10k.

**Comment by borysn** [comment]
@romkatv alright. i will ask nf to add a voidlinux icon

here is the output of the `/etc/os-release` on voidlinux

```
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

**Comment by romkatv** [comment]
> here is the output of the `/etc/os-release` on voidlinux

Thanks!
