### ISSUE TITLE
truncate options seem not to work

### ISSUE THREAD

**Issue by mattsawyer77** [romkatv/powerlevel10k#51]
Hello. First of all, thanks for forking P9K and fixing the speed issues!! 

I was wondering though why some of my POWERLEVEL9K settings didn't take effect, such as 
```
POWERLEVEL9K_DIR_SHORTEN_STRATEGY=truncate_from_right
```
My prompt is showing all dir segments all the time.

**Comment by romkatv** [comment]
> POWERLEVEL9K_DIR_SHORTEN_STRATEGY=truncate_from_right

To the best of my knowledge, there is no `POWERLEVEL9K_DIR_SHORTEN_STRATEGY` config option neither in p9k nor in p10k. The closest is `POWERLEVEL9K_SHORTEN_STRATEGY`.

Are you sure it works in p9k? If so, please post your config.

**Comment by Syphdias** [comment]
Currently `POWERLEVEL9K_SHORTEN_STRATEGY` on p9k/`master`, `P9K_DIR_SHORTEN_STRATEGY` on p9k/`next`.

**Comment by romkatv** [comment]
Closing as the reporter is MIA and it's unclear whether and what is broken without extra info.

If p9k and p10k generate different prompts with the same settings, please reopen the issue and post your config.

**Comment by mattsawyer77** [comment]
my bad: apparently I'd been using vars from the next branch of powerlevel9k and the official ones in master are different. The following for me works fine in powerlevel10k:
```
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
```

**Comment by romkatv** [comment]
Thanks for the update.
