### ISSUE TITLE
Question: how are the icons implemented?

### ISSUE THREAD

**Issue by romkatv** [romkatv/powerlevel10k#510]
Moved to a separate issue from https://github.com/romkatv/powerlevel10k/issues/509#issuecomment-588026838.

@psprint

**Comment by romkatv** [comment]
Here's how Gentoo icon is displayed:

```zsh
() {
  emulate -L zsh -o extended_glob -o xtrace
  if [[ "$(uname)" == Linux ]]; then
    if [[ "$(</etc/os-release)" == (|*$'\n')ID=[^$'\n']#gentoo* ]]; then
      print '\uF30D'
    fi
  fi
}
```

@psprint Does it answer your question?

**Comment by psprint** [comment]
I was curious how the graphical symbol gets into the font. Is there some unofficial allocation of the symbols for the Linux OSes? Chrome does display the icon too in address bar (only), and it doesn't even use the patched fonts.

**Comment by romkatv** [comment]
> I was curious how the graphical symbol gets into the font.

You can add a glyph to a font with FontForge. You can also use FontForge to edit glyphs.

The codepoint I used above (U+F30D) resolves to a gentoo icon in all fonts with Nerd Fonts glyphs. Search for "gentoo" in https://www.nerdfonts.com/cheat-sheet. The documentation at https://github.com/ryanoasis/nerd-fonts explains how to add Nerd Fonts glyphs to any font. The act of adding glyphs to a font, or modifying glyphs in a font, is called *patching*. So *patched fonts* are fonts that have been modified (usually with FontForge).

> Chrome does display the icon too in address bar (only)

Chrome displays favicon. Those are images. They don't come from fonts.

> and it doesn't even use the patched fonts

The word *patched* in *patched fonts* refers to the origin of the font. Applications that *use* fonts don't care about origin. A font is a font. You can use patched fonts in any application that allows you to specify which font to use. You can do that in Chrome. Search for "font" in settings.

**Comment by psprint** [comment]
So in general, those are the NerdFonts that have the icon. I'm still curious about Chrome, as it displays  a font letter there, not the favicon - I tried pasting the glyph into the address bar and it worked.

**Comment by romkatv** [comment]
> So in general, those are the NerdFonts that have the icon.

All patched fonts that you can download from https://github.com/ryanoasis/nerd-fonts have a Gentoo logo at U+F30D. Other fonts can have Gentoo logo at U+F30D, too. They can also have a different glyph U+F30D, or no glyph at all.

> I'm still curious about Chrome, as it displays a font letter there, not the favicon

Where is "there"?

> I tried pasting the glyph into the address bar and it worked.

It means the font in the address bar has Gentoo logo at U+F30D, either directly or through fallbacks. These are specified in `/etc/fonts/fonts.conf` and `/etc/fonts/conf.d/`. They allow you to specify how to render glyphs that a chosen font is missing.

**Comment by romkatv** [comment]
I suppose your question has been answered. Please reopen if it wasn't, or drop by on gitter.

**Comment by psprint** [comment]
`there` is: in the address bar – without any customizations done on Chrome – a curiosity I guess:

![2020-02-19-171535_525x79_scrot](https://user-images.githubusercontent.com/6049288/74851392-750a3300-533b-11ea-8198-9c724649f74a.png)

**Comment by romkatv** [comment]
It would indeed be curious if neither the font used by chrome had this widget, nor there was a fallback specified in `/etc/fonts/fonts.conf` and `/etc/fonts/conf.d/`.
