### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by cridemichel** [romkatv/powerlevel10k#511]
Hi, 
powerlevel10k already has a built-in segment for timewarrior but it lacks a segment for taskwarrior (which is typically used in conjuction with timewarrior). With powerlevel9k it was possible to add a segment for taskwarrior as discussed here: https://github.com/Powerlevel9k/powerlevel9k/wiki/User-Segments. Would it be possible to also add it to powerlevel10k?

best Cristiano

**Comment by romkatv** [comment]
Could you describe what you want to see in prompt without referring to that powerlevel9k code?

**Comment by cridemichel** [comment]
for example the taskwarrior status, i.e. the total number of pending tasks and the ones overdue...something like that

**Comment by romkatv** [comment]
Can I get this information by running a command?

You mentioned that taskwarrior is typically used in conjunction with timewarrior. Does it make sense to display information from both of them in prompt at the same time? Would it be the same or different?

**Comment by cridemichel** [comment]
> Can I get this information by running a command?
> 
> You mentioned that taskwarrior is typically used in conjunction with timewarrior. Does it make sense to display information from both of them in prompt at the same time? Would it be the same or different?

yes since timewarrior shows just current active task, while taskwarrior handles a list of task which can be started/stopped each

**Comment by romkatv** [comment]
> > Can I get this information by running a command?
> > You mentioned that taskwarrior is typically used in conjunction with timewarrior. Does it make sense to display information from both of them in prompt at the same time? Would it be the same or different?
> 
> yes since timewarrior shows the time elapsed since current task started, while taskwarrior handles a set of tasks where each task can be pending, done or overdue

Thanks for the explanation. I don't use either of these tools, so I need someone to teach me before I can implement anything.

Could you answer the first question too?

**Comment by cridemichel** [comment]
> > > Can I get this information by running a command?
> > > You mentioned that taskwarrior is typically used in conjunction with timewarrior. Does it make sense to display information from both of them in prompt at the same time? Would it be the same or different?
> > 
> > 
> > yes since timewarrior shows the time elapsed since current task started, while taskwarrior handles a set of tasks where each task can be pending, done or overdue
> 
> Thanks for the explanation. I don't use either of these tools, so I need someone to teach me before I can implement anything.
> 
> Could you answer the first question too?

just for curiosity do you use a different tool for handling tasks?
About your question yes you can use the command "task"

**Comment by romkatv** [comment]
> just for curiosity do you use a different tool for handling tasks?

I don't use any tool of this kind.

> About your question yes you can use the command "task", you can find
> details on its usage here https://taskwarrior.org/docs/syntax.html

Got it.

If you can give me a specific command, an example output and an example prompt that you would like to see in this case, I'll give it a shot at the implementation. If it's too much to ask, that's fine too. In this case I'll keep the issue open for a while in the hope that it attracts someone else who's interested in this prompt segment. If no one shows up, I'll close it.

**Comment by cridemichel** [comment]
in the following I give you some example commands useful to develop the segment function:

1. count number of pending tasks
```script
> task +PENDING count
 ```
```
2. count total number of tasks
```script
> task count
```
3. count tasks which are overdue:
```script
> task +OVERDUE count
```

**Comment by cridemichel** [comment]
a minimalist function for this segment could be (which is the one that I am actually using)

```zsh
function prompt_taskwarrior() {
  emulate -L zsh
  setopt pipefail
  (( $+commands[task] ))          || return
  local line IFS
  task +PENDING count 2>/dev/null | read -r lineP || return
  task +OVERDUE count 2>/dev/null | read -r lineO || return
  [[ "${lineP}" == "0" ]] && return
  lineP="⇡${lineP}"
  if [[ "${lineO}" == "0" ]] 
  then
    lineO="!${lineO}"
  else
    lineO=""
  fi      
  local tags="${lineP}${lineO}"
  [[ -n $tags ]] || return
  p10k segment -f 208 -i $'' -t $tags
}
```
which shows the pending and overdue task

**Comment by romkatv** [comment]
Thanks, that's super helpful!

How fast is it? Could you run the following command and post its output?

```zsh
time ( p10k() {}; repeat 100 prompt_taskwarrior )
```

**Comment by cridemichel** [comment]
```zsh
❯ time ( p10k() {}; repeat 100 prompt_taskwarrior )
( p10k () { ... }; repeat 100; do; prompt_taskwarrior; done; )  1,15s user 0,88s system 85% cpu 2,378 total
```

**Comment by romkatv** [comment]
Ouch. This would make the whole prompt over 100% slower.

The upper limit on prompt segment latency in powerlevel10k is 1ms. This prompt segment is currently at 24ms, so it'll need to be optimized before it can be included in powerlevel10k. When I get a free minute I'll use the pointer you provided to write an efficient implementation.

**Comment by cridemichel** [comment]
I see...but it seems _task_ command is inherently slow, indeed
I do:
```zsh
#!/usr/local/bin/zsh
for i in {0..100}
do
task +PENDING count rc.hooks=off >/dev/null 2>&1
task +OVERDUE count rc.hooks=off >/dev/null 2>&1
done
```
It takes 0.91 s, hence I do not know how much it can be optimized.
You could add a segment without enabling it by default...

**Comment by romkatv** [comment]
> but it seems _task_ command is inherently slow

Yes, this is the main reason why `prompt_taskwarrior` is slow.

> It takes 0.91 s, hence I do not know how much it can be optimized.

Probably by a lot. I haven't looked at it yet though.

> You could add a segment without enabling it by default...

I don't add slow segments to powerlevel10k. This makes powerlevel10k easier to use and understand. Users don't have to memorize which segments are fast and which are slow -- all segments fast. They don't have to profile or optimize configs. Powerlevel10k promises to always provide incredibly fast prompt with any configuration, even if you enable 50+ segments. If your aren't using custom prompt segments and your prompt isn't blazingly fast, that's a bug in powerlevel10k that I'll fix if it's reported.

**Comment by cridemichel** [comment]
I understand your vision of powerlevel10k but taskwarrior is a widely used and appreciated project, and having a dedicated segment would attract people to your powerlevel10k theme.
What about implementing a kind-of plugin mechanism by which users can add their own
segment functions? Or at least I think it would be nice to explain how to add custom segments in the docs and provide such "user segments" somewhere...

**Comment by romkatv** [comment]
> I understand your vision of powerlevel10k but taskwarrior is a widely used and appreciated project, and having a dedicated segment would attract people to your powerlevel10k theme.

The guarantee of always being fast doesn't mean that some segments cannot be added. They just need to be fast before they are added. Powerlevel10k has more segments than any other theme, and all segments that have ever been requested by anyone have been implemented.

My comments about the performance of your implementation of `prompt_taskwarrior` were meant to explain why I cannot just add this code to powerlevel10k right now. I need to optimize it first, which requires time. I'll do it, but later. I'm busy with other stuff right now.

> What about implementing a kind-of plugin mechanism by which users can add their own
> segment functions?

That's what your `prompt_taskwarrior` does. It's using the public and documented API of powerlevel10k for defining custom segments -- `p10k segment`. This API is fast and flexible.

By they was, it's a good idea to rename `prompt_taskwarrior` to `prompt_my_taskwarrior` to avoid clashes with future versions of powerlevel10k. I've added this to https://github.com/romkatv/powerlevel10k/blob/master/README.md#extensible but haven't yet updated all places where `p10k segment` API is mentioned.

**Comment by cridemichel** [comment]
ok looking forward to a possible optimized taskwarrior segment

**Comment by romkatv** [comment]
I added `taskwarrior` prompt segment. Please give it a try and let me know whether it works and whether it does what you need. The easiest way would be to update powerlevel10k, restart zsh and run `p10k configure`. You can also copy necessary parameters to your config manually. See the changes to `config/p10k-*.zsh` files in https://github.com/romkatv/powerlevel10k/commit/8cf22480c0817fe4de9503f9897e81197667b350.

Don't forget to remove your own `prompt_taskwarrior` function if you have it.

**Comment by cridemichel** [comment]
it seems to work nicely thank you very much!!
 
P.S. 
on https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render
the link of taskwarrior points to timewarrior

**Comment by romkatv** [comment]
> it seems to work nicely thank you very much!!

Thanks for verifying!

> on https://github.com/romkatv/powerlevel10k#icons-glyphs-or-powerline-symbols-dont-render
> the link of taskwarrior wrongly points to timewarrior homepage. Taskwarrior page is https://taskwarrior.org/

Thanks, fixed.

On my machine this implementation is 67 times faster than a simple one. It's much more complex though.

**Comment by cridemichel** [comment]
if I do 
```zsh
time ( p10k() {}; repeat 100 prompt_taskwarrior )
```
I get
```text
0,78s user 0,53s system 85% cpu 1,533 total
```
which apparently is not much faster though...
In addition, in the actual implementation (as mine) only the virtual tags PENDING and OVERDUE
are used but maybe it could be nice to implement the possibility to add other virtual tags (e.g. letting the user to set an array of possible virtual tags), such as ACTIVE, BLOCKED, WAITING, etc. The full list can be obtained by issuing the command:
```zsh
> task _tags
``

**Comment by romkatv** [comment]
> if I do
> 
> ```shell
> time ( p10k() {}; repeat 100 prompt_taskwarrior )
> ```

This implementation calls internal function `_p9k_prompt_segment` instead of `p10k` frontend, so you need to block that one. It also assumes that options are correct. Here's a command to time it:

```zsh
time ( _p9k_prompt_segment() {}; eval "$__p9k_intro"; repeat 1000 prompt_taskwarrior )
```

> In addition, in the actual implementation (as mine) only the virtual tags PENDING and OVERDUE
> are used but maybe it could be nice to implement the possibility to add other virtual tags (e.g. letting the user to set an array of possible virtual tags), such as ACTIVE, BLOCKED, WAITING, etc.

The implementation I put in powerlevel10k is easily extensible. It can compute the result of any query. The difficult part is figuring out what users want. I don't use taskwarrior myself, so it's hard to make choices here.

You can also notice that I haven't included any built-in formatting customization. This is also because I don't know what people want. E.g., I could support something like this:

```zsh
POWERLEVEL9K_TASK_WARRIOR_FORMAT=(
  OVERDUE '%F{red}!$1'
  PENDING '%F{yellow}$1')
POWERLEVEL9K_TASK_WARRIOR_SEPARATOR=' '
```

The risk is that this API might be not generic enough, so when someone comes and says they want something that cannot be done with this, I'll have to create another API, and it would increase API complexity.

**Comment by cridemichel** [comment]
yes issuing 
```zsh
time ( _p9k_prompt_segment() {}; eval "$__p9k_intro"; repeat 1000 prompt_taskwarrior )
```
I get 
```text
0,15s user 0,07s system 97% cpu 0,218 total
```
which is impressively much faster!
About the implementation probably it is wise to wait feedback from users in order to understand people's needs.

**Comment by romkatv** [comment]
> About the implementation probably it is wise to wait feedback from users in order to understand people's needs.

Yep, that's how I go about it. I can make decisions about segments I use myself but not about others. Taskwarrior is a large tool and I can imagine that people use it differently. If someone can explain to me what they want and it seems plausible that others could want this, I can implement stuff. Writing code is the easy part.

**Comment by cridemichel** [comment]
yes actual implementation is ok for me but probably not for others let's see...
and if I will feel the need for some change I will let you know so that you can improve
further taskwarrior plugin. Many many thanks again for the great work you are doing
with powerlevel10k!!

**Comment by romkatv** [comment]
Thanks for opening the issue, working with me on the implementation and testing the results!

**Comment by lambtho12** [comment]
First of all, thank you very much for the great support of taskwarrior.

I think it would be interesting to have a bit more modularity in the counter of tasks to do. I my case, I have an awful lot of tasks (as I collect literally everything in taskwarrior) and the current counter is not really helpful (+100 tasks).

I specifically would be interested in the possiblity to customize the `task` command that returns the counter if possible such as `task +in +PENDING count`  ([source](https://cs-syd.eu/posts/2015-06-21-gtd-with-taskwarrior-part-2-collection)), which would only display the number of pending tasks tagged with "+in". In my system (GTD) this is the number of tasks that I need to sort and act right now.

This modularity would also allow to display the number of tasks to do today (`task due:today count`), etc.

**Comment by romkatv** [comment]
@lambtho12 Please open a separate issue.
