### ISSUE TITLE
Git Icons Missing

### ISSUE THREAD

**Issue by BenediktEngel** [romkatv/powerlevel10k#513]
Hey, 
I have a problem with the icons for Git. The icons for untracked and unstaged files are missing. Has anyone a clue why this is happening?  
Everything else is working fine. 
I am using iTerm 3.3.9 with the latest version of oh-my-zsh.
<img width="589" alt="Bildschirmfoto 2020-02-19 um 15 16 46" src="https://user-images.githubusercontent.com/32795896/74842722-218fe900-532b-11ea-822b-547fb5788968.png">

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#question-mark-in-prompt.
