### ISSUE TITLE
getting error after running p10k configure

### ISSUE THREAD

**Issue by allzec** [romkatv/powerlevel10k#514]
after i run $ p10k configure and it saves to the config file this shows up:
_p9k_get_icon:13: character not in range
any idea how to fix as it just gets stuck on this and i cant use the terminal or anything

**Comment by romkatv** [comment]
That sounds bad.

When this error appears, please copy-paste the following command and attach `/tmp/p10k.txt` to this issue when the command finishes. You can drag-and-drop files to the edit box on github. You can still type commands when the error appears. Your prompt is empty but otherwise shell still works.

```zsh
() {
  emulate -L zsh -o xtrace
  typeset -pm 'ZSH_VERSION|_p9k__locale|POWERLEVEL9K_MODE|_p9k_uname*'
  type locale
  locale
  locale -a
  print -rl -- CODESET=$langinfo[CODESET] v=${_p9k__param_pat%%$'\1'*}
  print '\u276F'
} &>/tmp/p10k.txt
```

**Comment by allzec** [comment]
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4229021/p10k.txt)

**Comment by romkatv** [comment]
From the logs it appears that either your locale is misconfigured, or something in your zsh config files breaks it. The end result is that Zsh can print only ASCII characters and cannot print UNICODE. Your machine has a good locale installed -- `en_US.utf8` -- but it's not being used.

See https://github.com/romkatv/powerlevel10k#zsh-character-not-in-range.

**Comment by allzec** [comment]
Kde was overriding my locale and was set to "C". Just had to change it to en_US in kde locale settings and it fixed it. Thanks for your help.

**Comment by romkatv** [comment]
You are very welcome. I'll add an explicit check for locale in powerlevel10k and print a more helpful error message if locale is misconfigured.
