### ISSUE TITLE
Change OS_ICON

### ISSUE THREAD

**Issue by Tanish2002** [romkatv/powerlevel10k#515]
Might be a dumb question but I can't seem to figure out how can I change the os icon...in Prompt

**Comment by romkatv** [comment]
What icon do you see and what do you want to change it to?

**Comment by Tanish2002** [comment]
I see Manjaro's logo and I want to change it to Arch's logo or maybe Kali if possible..

**Comment by romkatv** [comment]
If you want to always see Archlinux logo regardless of your real OS, open `~/.p10k.zsh`, search for `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION` and sets its value to `$'\uF303'`. Put `%B` before it if you want a bold icon. Add a space after it if it looks too tight in your prompt.

If you want to see the icon of your real OS *except* when you are using Manjaro, define `POWERLEVEL9K_LINUX_MANJARO_ICON=$'\uF303'` in the same file.

If you want to add extra icons to your prompt, define a custom segment:

```zsh
function prompt_my_extra_icon() {
  p10k segment -b yellow -f red -i $'\uF303'
}
```

Then add `my_extra_icon` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. Type `p10k help segment` for help or search for `prompt_example` in `~/.p10k.zsh`.

**Comment by Tanish2002** [comment]
I tried this for the arch logo
`typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='$'\uF303''`
even tried this for a penguin logo
`typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION='$'\uF17C''`
Both don't seem to work


**With Custom Logo :** [Here](https://imgur.com/ysPuCS2)
**Without Custom Logo :** [Here](https://imgur.com/H8rWQyX)

Details:
**Terminal :** st
**Multiplier :** Tmux

**Comment by romkatv** [comment]
This is the right syntax:

```zsh
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uF303'
```

**Comment by Tanish2002** [comment]
Thanks A lot...even grateful for the quick support :100:

**Comment by romkatv** [comment]
Enjoy the archlinux logo on manjaro! :rocket: :wink:

**Comment by ankushom19** [comment]
well can u give the list of codes for the logos

**Comment by romkatv** [comment]
@ankushom19 Please be more specific.

**Comment by sachinoliver** [comment]
I do have the penguin logo now..which is default..
How to set kali linux  logo in prompt?

**Comment by romkatv** [comment]
@sachinoliver See https://github.com/romkatv/powerlevel10k/issues/515#issuecomment-589091421. Replace `$'\uF303'` with the icon of your choice. Kali Linux Logo is not included in any popular fonts, so you'll need to find a font that actually has this glyph and then figure out the UNICODE number of it.

**Comment by barun108** [comment]
as you have mentioned %B for bold , where do I put %B ?

 typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=%B$'\uF303'

is this correct ?

**Comment by romkatv** [comment]
> as you have mentioned %B for bold , where do I put %B ?
> 
> typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=%B$'\uF303'
> 
> is this correct ?

Looks fine to me. (BTW, you can just try things before asking.)

**Comment by peanutcelery** [comment]
You could go here to search your desired OS icon.
https://www.nerdfonts.com/cheat-sheet

**Comment by Leshu7w7** [comment]
Hi, how can i change os icon color?

**Comment by romkatv** [comment]
@Leshu7w7 Open `~/.p10k.zsh`, search for `POWERLEVEL9K_OS_ICON_FOREGROUND`, change its value and restart zsh with `exec zsh`. See the top of `~/.p10k.zsh` for how to choose colors.

**Comment by wasi-master** [comment]
Kali linux has their own custom nerd font with the kali linux icon now, [[changelog link]](https://www.kali.org/blog/kali-linux-2021-2-release/#:~:text=kali%E2%80%99s%20logo%20is%20now%20included%20in%20the%20nerd-fonts%20project%2C%20so%2C%20with%20their%20next%20release%20you%E2%80%99ll%20be%20able%20to%20customize%20your%20terminal%20with%20the%20dragon.%20if%20you%20want%20to%20try%20it%20now%2C%20we%E2%80%99ve%20created%20a%20patched%20fira-code%20font%20with%20these%20new%20changes%20(the%20code%20for%20the%20logo%20is%20%5Cuf32b))

> Kali’s logo is now included in the [nerd-fonts](https://www.nerdfonts.com/) project, so, with their next release you’ll be able to customize your terminal with the dragon. If you want to try it now, we’ve created a [patched Fira-Code](https://www.kali.org/blog/kali-linux-2021-2-release/fonts/Fira-Code-Regular-Nerd-Font-Complete.ttf) font with these new changes (the code for the logo is \uF32B)

**Comment by romkatv** [comment]
@wasi-master Your summary of the changelog doesn't look right. They aren't saying that Kali linux has their own font. They are saying that the next version of nerd-fonts will contain a logo for Kali linux.

**Comment by wasi-master** [comment]
@romkatv thanks, edited

**Comment by TechLionDev** [comment]
Where do i pu the typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=%B$'\uF303'

**Comment by romkatv** [comment]
The most common place to put it is within `~/.p10k.zsh`. If you don't have this file, put it at the bottom of `~/.zshrc`.

**Comment by TechLionDev** [comment]
can i make the ico bigger?

**Comment by romkatv** [comment]
The icon comes from your font. If you make it bigger in your font, it'll be bigger in the terminal.

**Comment by TechLionDev** [comment]
and where is the setting to change the GH Octopus?
tysm for ur help so far

**Comment by romkatv** [comment]
`POWERLEVEL9K_VCS_GIT_GITHUB_ICON='whatever'`

**Comment by SofiDevO** [comment]
Can I use a custom Logo, exmpl: if it come frome external source or even a svg or png logo/icon?

**Comment by romkatv** [comment]
The terminal can display glyphs from the font and nothing else. If you want to display something that does not have a glyph in your font, you'll need to create a new font. The most popular free tool for editing fonts is called FontForge. You can use it to create a new font that will have all glyphs from some other font plus an extra glyph. I do not recommend doing this unless you feel very strongly about seeing a particular glyph in your terminal.

**Comment by Alaponuke** [comment]
**just to clarify for future readers, after reading all the threat** 
1. enabled the line (_character set is for my KDE change \uF373 for any other number you desire_ )
`typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'%B\uF373'`
and I found my desired Icon character number in this search:
https://www.nerdfonts.com/cheat-sheet
![image](https://github.com/romkatv/powerlevel10k/assets/92026112/2ddbe3de-ff46-49c4-b887-d650c0e748f5)

Just to mention is you don not see all the symbols [**just download**](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.0/NerdFontsSymbolsOnly.zip) and install the symbols font only:
![image](https://github.com/romkatv/powerlevel10k/assets/92026112/62dfd51a-16f0-4e3e-86bc-6ec9d46aa2bb)
with these steps all is showed

**Comment by Koxepis** [comment]
I'm using the pure theme on my p10k. But I want to add apple logo displayed. How do I do that? I've tried to put down `typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=%B$'\uF302'` but it didn't show anything when sourcing it back with .zshrc

Instead I got this line after `source .zshrc`:
```
gitstatus_stop_p9k_:zle:41: No handler installed for fd 13
gitstatus_stop_p9k_:49: failed to close file descriptor 13: bad file descriptor
```

So I revert it back.

But when I tried to add `os_icon` like this on line 3:
```
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon
    # context                 # user@host
    dir                       # current directory
    vcs                       # git status
    # command_execution_time  # previous command duration
    # =========================[ Line #2 ]=========================
    newline                   # \n
    # virtualenv              # python virtual environment
    prompt_char               # prompt symbol
)
```

It will only display OSX. So can you show me how do I do that @romkatv 
Thanks.

**Comment by romkatv** [comment]
The easiest way is to run `p10k configure` and choose *Lean* style. *Pure* style is for those who want the exact prompt provided by https://github.com/sindresorhus/pure.
