### ISSUE TITLE
git status icon missing whitespace in pure theme

### ISSUE THREAD

**Issue by jtrees** [romkatv/powerlevel10k#517]
#### Description

When in a git repo with the pure themed prompt the status icon (e.g. `⇡`) should be prefixed by a space.

#### Expected Prompt

```
~/foo/bar master* ⇡
```

#### Actual Prompt

```
~/foo/bar master*⇡
```
Real world example:

![Screenshot from 2020-02-21 15-14-57](https://user-images.githubusercontent.com/5802758/75041546-0fde4b00-54bd-11ea-8b4a-427d2359cba6.png)

**Comment by romkatv** [comment]
Thanks! Fixed.

**Comment by jtrees** [comment]
Thanks! And wow, that was fast!
