### ISSUE TITLE
[feature] vpn_ip be able to show multiple VPN connexion

### ISSUE THREAD

**Issue by Shini31** [romkatv/powerlevel10k#518]
Hello,

I have a use case where I can be connected to multiple VPN servers. With the actual implementation of `vpn_ip` segment, only one is showed.

In p9k, I made a little change to add this functionality but in p10k, I'm completely lost with this new code.

My code for p9k:
```
  for vpn_iface in $(/sbin/ip -4 addr | egrep -e "${POWERLEVEL9K_VPN_IP_INTERFACE}" |grep -v "inet" | cut -d":" -f2)
  do
    ip=$(/sbin/ip -4 -o addr show dev ${vpn_iface} | awk '{split($4,a,"/");print a[1]}')
    "$1_prompt_segment" "$0" "$2" "cyan" "$DEFAULT_COLOR" "$ip" 'VPN_ICON'
  done
```

Regards

**Comment by romkatv** [comment]
Do you prefer to have one segment (and one icon) with all IPs listed in it, or a separate segment with an icon for every IP?

> I'm completely lost with this new code.

Powerlevel10k really has only one downside compared to all other themes. Its implementation is very complex. This sacrifice allows it to be faster and more flexible than any other theme.

**Comment by Shini31** [comment]
Actually i have separate segment with an icon for each IP and it's good for me.

> Powerlevel10k really has only one downside compared to all other themes. Its implementation is very complex. This sacrifice allows it to be faster and more flexible than any other theme.

I clearly understand that

**Comment by romkatv** [comment]
I've added a new parameter:

```zsh
# If set to true, show one segment per matching network interface. If set to false, show only
# one segment corresponding to the first matching network interface.
# Tip: If you set it to true, you'll probably want to unset POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION.
typeset -g POWERLEVEL9K_VPN_IP_SHOW_ALL=false
```

Please let me know whether it works for you.

**Comment by Shini31** [comment]
Hello,

It doesn't seem to be working on my side.

```
POWERLEVEL9K_VPN_IP_INTERFACE="tun.*|ppp.*"
POWERLEVEL9K_VPN_IP_BACKGROUND="red"
POWERLEVEL9K_VPN_IP_FOREGROUND="white"
POWERLEVEL9K_VPN_IP_SHOW_ALL= true
```

![Capture d’écran du 2020-02-25 15-42-35](https://user-images.githubusercontent.com/333820/75257923-00753f80-57e6-11ea-97ff-fae7d1015c8b.png)

**Comment by romkatv** [comment]
> ```
> POWERLEVEL9K_VPN_IP_SHOW_ALL= true
> ```

This line has no effect. You can confirm it with `echo $POWERLEVEL9K_VPN_IP_SHOW_ALL` right after it. You need to remove the space between `=` and `true`.

**Comment by Shini31** [comment]
my bad... Now it works like a charm

Thanks for your reactivity!!

**Comment by romkatv** [comment]
Thanks for the confirmation!
