### ISSUE TITLE
can we typeset local vars in the my_git_formatter function?

### ISSUE THREAD

**Issue by borysn** [romkatv/powerlevel10k#519]
i would like to have the local vars in the my_git_formatter function typeset. this would give be the ability to make more fine grained changes to those colors without needing to edit the `p10k.zsh` file. i've put all of my custom configuration options into a `.p10k-config.zsh` file which i source after 

my custom config file works fine, except i can't change the colors within the my_git_formatter function. i figure it'd look something like this, which doesn't break existing code

```bash
  function my_git_formatter() {
...
    # Styling for different parts of Git status.
    typeset -g POWERLEVEL9K_VCS_META_FOREGROUND='%7f'
    typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='%0f'
    typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='%0f'
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='%0f'
    typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='%1f'

    local       meta=${POWERLEVEL9K_VCS_META_FOREGROUND}
    local      clean=${POWERLEVEL9K_VCS_CLEAN_FOREGROUND}
    local   modified=${POWERLEVEL9K_VCS_MODIFIED_FOREGROUND}
    local  untracked=${POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND}
    local conflicted=${POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND}
...
```
it would probably be better to have a POWERLEVEL10K_... naming scheme here, but i just added those 9k vars because they're already being accounted for and it was easy to test. 

but then i can do something like this in my `.p10k-config.zsh` file

```bash
# p10k-config.zsh

# os_icon
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=0
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7

# cwd
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_first_and_last
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=".."

# git status
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=121
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=1
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=6
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=1
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=6
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=1
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=6
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=1
#
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=2
typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=7

typeset -g POWERLEVEL9K_VCS_META_FOREGROUND=${POWERLEVEL9K_VCS_CLEAN_FOREGROUND}
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=${POWERLEVEL9K_VCS_CLEAN_FOREGROUND}
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=${POWERLEVEL9K_VCS_MODIFIED_FOREGROUND}
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=${POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND}
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=${POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND}

# reload p10k
(( ! $+functions[p10k] )) || p10k reload
```

i feel that's it's just easier to track and save my changes if i put them into a different file. and with the local vars in `my_git_formatter` typeset, i can change the colors from my config file.

i'd like to make a pr for the change if this sounds good to you. i just have a couple questions which need to addressed

**Comment by romkatv** [comment]
Powerlevel10k guarantees backward compatibility with all configs in the following sense. If you update powerlevel10k and use it with the same set of `POWERLEVEL9K_*` parameters, it'll produce the same prompt as before.

Things that aren't guaranteed:

1. If you update powerlevel10k and run `p10k configure`, there may be different questions and options than before. For example, there may be no Rainbow style.
2. If you update powerlevel10k and run `p10k configure`, the config may look entirely different. For example, it may have no `POWERLEVEL9K` parameters at all.
3. If you update powerlevel10k and run `p10k configure`, prompt may look entirely different. There may be no option in the configuration wizard to produce prompt similar to what you had before.

> i've put all of my custom configuration options into a `.p10k-config.zsh` file which i source after

This approach may give you unexpected prompt in the following cases:

1. You run `p10k configure` and make different choices than before.
2. You update powerlevel10k and run `p10k configure`.

**Comment by borysn** [comment]
@romkatv the extra config thing is just for me. i'm not worried about dealing with breaking changes. it just makes things easier to separate config at a user level from generated application options because it's easier to see and track the changes. the proposed change wouldn't break existing styles if you put them into a different namespace and just got rid of the local vars altogether, then there's no backwards compatibility issues either because the color style theme for the git prompt is already different than the base p9k one

**Comment by romkatv** [comment]
> i'm not worried about dealing with breaking changes.

If you mean it literally, there is an easy way to resolve this issue. If I modify [p10k-classic.zsh](https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-classic.zsh) the way you suggest and revert the changes in the next commit, would this work for you?

> the proposed change wouldn't break existing styles if you put them into a different namespace and just got rid of the local vars altogether

When you update Powerlevel10k and run `p10k configure`, the new config and the new prompt can look completely different from what you used to have. This isn't considered "breaking existing styles". There is simply no guarantee of continuity whatsoever when it comes to configuration wizard.

> there's no backwards compatibility issues

Every version of powerlevel10k is backward compatible with every previous version. If I add a new `POWERLEVEL9K` parameter, all future versions of powerlevel10k will need to support it.

> the color style theme for the git prompt is already different than the base p9k one

Powerlevel10k is backward compatible with Powerlevel9k configs. If you use Powerlevel10k with the same parameters as Powerlevel9k, prompt will look the same including all colors.

**Comment by romkatv** [comment]
Defining `POWERLEVEL9K` parameters after sourcing `~/.p10k.zsh` is effectively patching `~/.p10k.zsh`. Once you generate a new `~/.p10k.zsh`, the patch may stop working. If you are OK with this, you can patch `my_git_formatter` the same way. For example:

```zsh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

function my_git_color() {
  eval "function my_git_formatter() {
    ${(S)functions[my_git_formatter]/ $1=\'*\'/ $1='%$2F'}
  }"
}

my_git_color meta       121
my_git_color clean      121
my_git_color modified   6
my_git_color untracked  6
my_git_color conflicted 6
```

Does this do what you need?

**Comment by borysn** [comment]
@romkatv wow, i just learned something new. didn't realize something like that would be possible with shell functions. i'm pretty amazed by this haha

this does what i need, yes. and now i can set all the text color of the vcs entries from my config ^-^

thanks

**Comment by romkatv** [comment]
I'm glad it's working for you. Closing.

**Comment by kulack** [comment]
3.5 years on. Still no way to customize git status colors in a safe way, but the work around above is beautiful! And likely isolates from most changes. Wonderful!

**Comment by romkatv** [comment]
@kulack I don't understand your comment. If something doesn't work the way you expect, or if some reasonable functionality is missing, please open a new issue.
