### ISSUE TITLE
gitstatus doesn't work in home directory

### ISSUE THREAD

**Issue by vanyasvl** [romkatv/powerlevel10k#520]
Hello. 
gitstatus doesn't work if my home dir is a root of git repo (MacOS 10.15)
but if clone the same repo in a different dir, it works ok

`❯ git status | head -3
On branch master
Your branch is up to date with 'origin/master'.

❯ ll -d .git
Permissions Size User Date Modified Name
drwxr-xr-x     - sid  23 Feb 19:24  .git/
❯ git clone git@gitlab.com:vanyas/dotfiles.git
Cloning into 'dotfiles'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 12 (delta 2), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (12/12), done.
Resolving deltas: 100% (2/2), done.
❯ cd dotfiles
❯
   ~/dotfiles    master                                                                                         19:25:30
❯`

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-is-git-status-from-homegit-not-displayed-in-prompt.
