### ISSUE TITLE
How remove truncate dirs?

### ISSUE THREAD

**Issue by Nisgrak** [romkatv/powerlevel10k#521]
Hi! 

I don't want to truncate my dirs, what config I need?

I search in many sites but didn't found it.

Thanks!

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and set the following parameters:

```zsh
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=0
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=0
```

All three parameters are already defined in the config. Search for them and change their values.

Does this do what you need?

**Comment by romkatv** [comment]
Closing as the reporter has disappeared.

**Comment by Nisgrak** [comment]
This work like a charm!

Thanks and sorry for the delay.

**Comment by romkatv** [comment]
Thanks for the confirmation!
