### ISSUE TITLE
[feature] when truncate_to_unique cannot truncate any further, allow replacing prefix with ../

### ISSUE THREAD

**Issue by cridemichel** [romkatv/powerlevel10k#522]
Hi,
if I have a prompt line as the following one:

![Schermata 2020-02-24 alle 08 39 12](https://user-images.githubusercontent.com/15322138/75135221-27961900-56e1-11ea-88c4-866f8e6a35a2.png)

and I reduce the size of the terminal I get:

![Schermata 2020-02-24 alle 08 39 50](https://user-images.githubusercontent.com/15322138/75135250-409eca00-56e1-11ea-9852-d19d5ddb0c6d.png)

i.e. the right prompt disappears. I think that in this case it should be better to truncate the current directory rather than making the right prompt disappear...

best  C.

**Comment by romkatv** [comment]
Indeed, it would be better. It's difficult to implement though. Hopefully I'll get to it at some point but it's unlikely to be soon.

**Comment by FreddieOliveira** [comment]
This is indeed an annoying behavior. In powerlevel9k, when the screen width is smaller than the right and left prompt together, the behavior is the right prompt to overlap the left prompt:

**Before zoom**
![Screenshot_2020-04-04-17-41-41-306_com termux](https://user-images.githubusercontent.com/9597536/78461189-510d7180-769d-11ea-81bc-8d7cd8b26fce.png)

**After zoom**
![Screenshot_2020-04-04-17-42-10-086_com termux](https://user-images.githubusercontent.com/9597536/78461195-579be900-769d-11ea-9e6c-55b44e92d276.png)

Powerlevel10k on the other hand simply discards the whole right prompt

**Before zoom**
![Screenshot_2020-04-04-17-42-45-537_com termux](https://user-images.githubusercontent.com/9597536/78461201-5cf93380-769d-11ea-864a-906130963e8a.png)

**After zoom**
![Screenshot_2020-04-04-17-42-51-452_com termux](https://user-images.githubusercontent.com/9597536/78461203-61255100-769d-11ea-97d2-73de211e5439.png)

As a personal preference, I'd rather prefer to lose some info from my left prompt while preserving the right one (like powerlevel9k does), than completely discarding it.

**Comment by romkatv** [comment]
Powerlevel10k does what zsh does.

**Comment by FreddieOliveira** [comment]
Is there any chance of introducing a config option to change it? I'd really appreciate it

**Comment by romkatv** [comment]
It's hard for me to see much value in it. You can solve your current problem simply by removing clatter from prompt. See a few tips in https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-the-best-prompt-style-in-the-configuration-wizard.

**Comment by cridemichel** [comment]
...but why powerlevel9k behavior can not be reproduced in powerlevel10k?

**Comment by romkatv** [comment]
> ...but why powerlevel9k behavior can not be reproduced in powerlevel10k?

It can be. I just don't find it useful useful enough to spend my time on it and to increase code and configuration complexity.

**Comment by cridemichel** [comment]
ok thank you very much  for the clarification

**Comment by romkatv** [comment]
Note that powerlevel9k has inconsistent behavior on different prompt lines. On the last prompt line it behaves like powerlevel10k. This is actually done by zsh itself -- it's the standard and documented behavior. Powerlevel10k does the same thing on all prompt lines but powerlevel9k has a bug that has many side effects including occlusion of left prompt by right prompt on all lines except the last.

**Comment by cridemichel** [comment]
ok, I can live with current behavior by just reducing the maximum length of
current directory before shortening with POWERLEVEL9K_DIR_MAX_LENGTH...

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by romkatv** [comment]
I acknowledge that the original feature request is valid and it would be useful to have it implemented. I already had it on my todo list when the issue has been filed (see [here](https://github.com/romkatv/powerlevel10k/commit/f06be72977932606e047fdff713959e59c7252e3)). I don't consider this feature high priority because the cases I've seen where it would've been most useful could be better served by removing clatter from prompt. In addition, implementing this feature is genuinely difficult.

Thus: 1) I'm not going to forget about this issue as it's in my notes; 2) I'm unlikely to work on this in the near future. I don't like having non-actionable issues (those that I don't intend to act on), so I'm going to close this one.
