### ISSUE TITLE
not a tty when loading terminal with powerlevel10k

### ISSUE THREAD

**Issue by alex-popov-tech** [romkatv/powerlevel10k#524]
Hello!

Here is my zshrc - https://github.com/alex-popov-tech/.dotfiles/blob/master/terminal/zshell/zshrc#L11
If i open terminal with that session i can see in terminal `not a tty`.

However, if i will comment prompt initialization, i can see something like `/dev/ttys009`.

Can someone please help on figuring out how that can be related and how to resolve that?

**Comment by romkatv** [comment]
From https://github.com/romkatv/powerlevel10k#how-do-i-enable-instant-prompt:

> When instant prompt is enabled, for the duration of Zsh initialization standard input is redirected to `/dev/null`...

I sent you https://github.com/alex-popov-tech/.dotfiles/pull/5 with a fix. The gist of it:

```diff
-export GPG_TTY=$(tty)
+export GPG_TTY=$TTY
```

**Comment by alex-popov-tech** [comment]
@romkatv thank you, that worked perfectly! super helpful as always!
