### ISSUE TITLE
p10k configure doesn't install Meslo

### ISSUE THREAD

**Issue by aserrallerios** [romkatv/powerlevel10k#525]
iTerm 3.3.9

In the configure process I choose to install the recommended font, then I restarted iTerm. 

After that, the font was not correctly selected (it selected instead Menlo, maybe because of the similar name), and the Meslo font seems not to be installed (brew cask list doesn't show it, it's not present on the fonts list on iTerm Profile > Text settings) at all.

**Comment by romkatv** [comment]
Do you see MesloLGS in the Font Book? Is there Regular style?

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
command ls -l /System/Library/Fonts/**/*Meslo*(N) ~/Library/Fonts/**/*Meslo*(N)
```

**Comment by aserrallerios** [comment]
```
-rw-r--r--  1 aserralle  staff  1248540 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Bold Italic.ttf
-rw-r--r--  1 aserralle  staff  1290352 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Bold.ttf
-rw-r--r--  1 aserralle  staff  1239812 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Italic.ttf
-rw-r--r--  1 aserralle  staff  1280812 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Regular.ttf
```

**Comment by romkatv** [comment]
If you click on `/Users/aserralle/Library/Fonts/MesloLGS NF Regular.ttf`, what does it say?

If you click on MesloLGS in Font Book, does it say there are problems with it?

**Comment by romkatv** [comment]
Also, have you ever manually installed any Nerd Fonts?

**Comment by aserrallerios** [comment]
> If you click on /Users/aserralle/Library/Fonts/MesloLGS NF Regular.ttf, what does it say?
It shows no problem with it, double click just opens Font Book, nothing selected.

>If you click on MesloLGS in Font Book, does it say there are problems with it?
No problems, but it just show Italic and Bold Italic.

> Also, have you ever manually installed any Nerd Fonts?
yes, using `brew cask`

**Comment by aserrallerios** [comment]
![](https://ibb.co/HFdC1wH)

**Comment by romkatv** [comment]
> yes, using `brew cask`

Still cannot reproduce :-/

Do you recall if you've installed any variant of Meslo? Do you recall the `brew cask` command you've used?

What is the output of the following command?

```zsh
() {
  command ls -l /System/Library/Fonts/**/*Meslo*(N) ~/Library/Fonts/**/*Meslo*(N)
  command find / -type f -name '*Meslo*' 2>/dev/null | xargs ls -l
}
```

(It might take a minute or two to complete.)

Is this a corporate machine managed by the organization? Does it have some unusual setup w.r.t. to fonts?

**Comment by aserrallerios** [comment]
Just did:

```
brew cask install font-firacode-nerd-font
brew cask install font-firacode-nerd-font-mono
brew cask install font-hack-nerd-font
brew cask install font-sourcecodepro-nerd-font-mono
brew cask install font-ubuntumono-nerd-font
```

No corporate machine.

The output of the command is:
```
-rw-r--r--  1 aserralle  staff  1248540 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Bold Italic.ttf
-rw-r--r--  1 aserralle  staff  1290352 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Bold.ttf
-rw-r--r--  1 aserralle  staff  1239812 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Italic.ttf
-rw-r--r--@ 1 aserralle  staff  1280812 Feb 26 11:47 /Users/aserralle/Library/Fonts/MesloLGS NF Regular.ttf
ls: /System/Volumes/Data/Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: /System/Volumes/Data/Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: /System/Volumes/Data/Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: /System/Volumes/Data/Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: /Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: /Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: /Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: /Users/aserralle/Library/Fonts/MesloLGS: No such file or directory
ls: Bold: No such file or directory
ls: Bold: No such file or directory
ls: Bold.ttf: No such file or directory
ls: Bold.ttf: No such file or directory
ls: Italic.ttf: No such file or directory
ls: Italic.ttf: No such file or directory
ls: Italic.ttf: No such file or directory
ls: Italic.ttf: No such file or directory
ls: NF: No such file or directory
ls: NF: No such file or directory
ls: NF: No such file or directory
ls: NF: No such file or directory
ls: NF: No such file or directory
ls: NF: No such file or directory
ls: NF: No such file or directory
ls: NF: No such file or directory
ls: Regular.ttf: No such file or directory
ls: Regular.ttf: No such file or directory
```

**Comment by eddyg** [comment]
@aserrallerios Out of curiosity, do you have any font files in your Trash?

**Comment by romkatv** [comment]
> @aserrallerios Out of curiosity, do you have any font files in your Trash?

Not Meslo at least, or the last command would've shown them. I screwed up with `find | xargs` there (missing `-print0` and `-0`) but you can still see from the output that only `~/Library/Fonts` has files with `Meslo* in their names, and those are the p10k files.

I think I've figured out what's going on. Trying to fix now...

**Comment by romkatv** [comment]
I've submitted a potential fix. Two even. I cannot verify that they work because I wasn't able to reproduce the original problem but there is a decent chance it'll work for you.

Please update powerlevel10k, restart iTerm2 and run `p10k configure`. When it asks whether to install the font, say Yes. Restart iTerm2 for the second time and run `p10k configure` again. This time the font should work.

**Comment by aserrallerios** [comment]
I did that, and it didn't work. iTerm has Menlo selected.

But guess what. Now, I can see Bold, Italic and Bold Italic :D

**Comment by romkatv** [comment]
Please try the following:

1. Manually change font in iTerm2 settings to `Monaco`.
2. Run this command:
```zsh
() {
  emulate -L zsh -o err_return
  {
    command rm ~/Library/Fonts/MesloLGS*.ttf
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /tmp/powerlevel10k
  } always {
    command rm -rf /tmp/powerlevel10k
  }
}
```
3. When prompt appears, run `p10k configure`.
4. Agree to install font.
5. When you get back to Zsh, run `exit 0`.
6. Restart iTerm2.

If on any step anything unexpected happens (where unexpected is defined by your best guess of what *I* am expecting and not what you *you* are expecting), please do let me know.

**Comment by aserrallerios** [comment]
It works now. That's some serious zsh-fu there, cheers. Hope it helps find and fix some problem.

**Comment by romkatv** [comment]
> It works now.

Great! Thanks for verifying.

> Hope it helps find and fix some problem.

Already fixed.

There is a bug in macOS. If you download (or slowly copy) a font directly into `~/Library/Fonts`, macOS will look at this file while it's still being written to, decide that this file is corrupted, and mark it as such. This font won't appear in the Font Book.

The workaround is to download/copy a font into a temporary file on the same partition and them atomically move it to `~/Library/Fonts`.

**Comment by shinelikastar** [comment]
Hi! I'm running into the same problem where iTerm2 uses Menlo instead of MesloLGS NF. I've tried running [this fix above](https://github.com/romkatv/powerlevel10k/issues/525#issuecomment-591459110) but the font still is set as Menlo upon reopening iTerm2. I've tried adding the font directly to the font book, but like you stated above, I think it's marked as corrupted and I'm unable to add it to the Font Book from `~/Library/Fonts` where it's downloaded.

**Comment by romkatv** [comment]
@shinelikastar

> I'm running into the same problem

What does this mean? Please describe the issue without any references to past issues. (Roman's law: whenever someone comments on a closed issue saying they are experiencing the same problem, they really aren't.)

> Hi! I'm running into the same problem where iTerm2 uses Menlo instead of MesloLGS NF.

Have you tried changing the font to MesloLGS NF in iTerm2 settings?
