### ISSUE TITLE
root user 'can't open powerlevel9k.zsh-theme'

### ISSUE THREAD

**Issue by duffydack** [romkatv/powerlevel10k#528]
Arch linux, release v1.2 from AUR
Switched from -git version to release 1.2, did a fresh p10k configure, removed existing .cache files, and tweaked it for my colourscheme.  Theme loads fine as user, but when logging in as root, or running 'sudo -i _or_ -s', there is a warning ...

`(anon):zcompile:18: can't open file: /usr/share/zsh-theme-powerlevel10k/powerlevel9k.zsh-theme`

File does not exist, but theme continues to operate without issue.

**Comment by romkatv** [comment]
Please file a bug against the owner of that AUR package. The package is missing files. It's impractical to write Powerlevel10k code defensively with the assumption that users will delete a portion of its source files.
