### ISSUE TITLE
Wrong asdf golang variable on freshly generated .p10k.zsh

### ISSUE THREAD

**Issue by nando740** [romkatv/powerlevel10k#529]
Hello

Just installed powerlevel10k via zinit, following the manual, with:
`zinit ice depth=1; zinit light romkatv/powerlevel10k`

After following the wizard, the new generated .p10k.zsh had these variables for asdf go:
```
typeset -g POWERLEVEL9K_ASDF_GO_FOREGROUND=0
typeset -g POWERLEVEL9K_ASDF_GO_BACKGROUND=4
# typeset -g POWERLEVEL9K_ASDF_GO_VISUAL_IDENTIFIER_EXPANSION='⭐'
# typeset -g POWERLEVEL9K_ASDF_GO_SHOW_ON_UPGLOB='*.foo|*.bar'
```
I wanted to change the default icon to the golang mascot:
`typeset -g POWERLEVEL9K_ASDF_GO_VISUAL_IDENTIFIER_EXPANSION='ﳑ'`

It seems the wizard is generating wrong variables, since changing GO to GOLANG fixed the problem:

```
# Go version from asdf.
typeset -g POWERLEVEL9K_ASDF_GOLANG_FOREGROUND=0
typeset -g POWERLEVEL9K_ASDF_GOLANG_BACKGROUND=6
typeset -g POWERLEVEL9K_ASDF_GOLANG_VISUAL_IDENTIFIER_EXPANSION='ﳑ'
# typeset -g POWERLEVEL9K_ASDF_GOLANG_SHOW_ON_UPGLOB='*.foo|*.bar'
```

**Comment by romkatv** [comment]
Thanks for the report. Fixed.

Once you update powerlevel10k, restart Zsh and generate a new config with `p10k configure`, it'll work as expected.
