### ISSUE TITLE
Minor visual inconsistencies with powerlevel9k

### ISSUE THREAD

**Issue by teddyhwang** [romkatv/powerlevel10k#53]
Thanks for the speed improvements! There are some visual inconsistencies between powerlevel9k (top) and powerlevel10k (bottom):

<img width="207" alt="Screen Shot 2019-04-06 at 3 43 55 PM" src="https://user-images.githubusercontent.com/22878/55674439-cf64e700-5882-11e9-9457-642c6806d7ea.png">

Are there any additional settings that I need to apply to make it look more like powerlevel9k?

**Comment by romkatv** [comment]
Please post your config.

**Comment by teddyhwang** [comment]
```POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  virtualenv
  root_indicator
  background_jobs
  time
  disk_usage
  ram
)

POWERLEVEL9K_CUSTOM_JAVASCRIPT="echo -n '\ue781' JavaScript"
POWERLEVEL9K_CUSTOM_JAVASCRIPT_BACKGROUND="yellow"
POWERLEVEL9K_CUSTOM_JAVASCRIPT_FOREGROUND="black"
POWERLEVEL9K_CUSTOM_PYTHON="echo -n '\uf81f' Python"
POWERLEVEL9K_CUSTOM_PYTHON_BACKGROUND="blue"
POWERLEVEL9K_CUSTOM_PYTHON_FOREGROUND="black"
POWERLEVEL9K_CUSTOM_RUBY="echo -n '\ue21e' Ruby"
POWERLEVEL9K_CUSTOM_RUBY_BACKGROUND="red"
POWERLEVEL9K_CUSTOM_RUBY_FOREGROUND="black"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
```

**Comment by romkatv** [comment]
Both p9k and p10k look the same with this config but it's different from either of the screenshots you've attached.

Both screenshots have an apple icon but your config doesn't use it. The screenshot for p9k has non-default background for the user segment but your config doesn't set it.

Please post the full config on which you can observe different behavior of p9k and p10k.

**Comment by teddyhwang** [comment]
🤦‍♂️ sorry, I missed some. Here's the full list of `POWERLEVEL_9k` configs:

```
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir_writable dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  virtualenv
  root_indicator
  background_jobs
  time
  disk_usage
  ram
)

# P9K
POWERLEVEL9K_CUSTOM_JAVASCRIPT="echo -n '\ue781' JavaScript"
POWERLEVEL9K_CUSTOM_JAVASCRIPT_BACKGROUND="yellow"
POWERLEVEL9K_CUSTOM_JAVASCRIPT_FOREGROUND="black"
POWERLEVEL9K_CUSTOM_PYTHON="echo -n '\uf81f' Python"
POWERLEVEL9K_CUSTOM_PYTHON_BACKGROUND="blue"
POWERLEVEL9K_CUSTOM_PYTHON_FOREGROUND="black"
POWERLEVEL9K_CUSTOM_RUBY="echo -n '\ue21e' Ruby"
POWERLEVEL9K_CUSTOM_RUBY_BACKGROUND="red"
POWERLEVEL9K_CUSTOM_RUBY_FOREGROUND="black"
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
POWERLEVEL9K_USER_DEFAULT_ICON='\uF415'
POWERLEVEL9K_USER_ROOT_ICON='\uF09C'
POWERLEVEL9K_USER_SUDO_ICON='\uF09C'
POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408'
POWERLEVEL9K_VCS_GIT_ICON='\uF408'

**Comment by romkatv** [comment]
This config also results in identical prompt in p9k and p10k. It's now also identical to the bottom screenshot you've posted. However, it is _not_ identical to the top screenshot even when using p9k.

Your screenshot has a custom user icon. This icon can be set with `POWERLEVEL9K_USER_ICON='\uF415'`. Your config has a fairly close stanza -- `POWERLEVEL9K_USER_DEFAULT_ICON='\uF415'` -- which has no effect on p9k.

Your screenshot also has non-default colors for `user` segment but the config doesn't set them. I cannot see from the screenshot the actual colors but a similar result can be achieved by setting the following options:

```zsh
POWERLEVEL9K_USER_DEFAULT_FOREGROUND=black
POWERLEVEL9K_USER_DEFAULT_BACKGROUND=yellow
```

If you observe different behavior of p9k and p10k on the same config, please isolate the config and then verify that these themes do indeed give different results. Here's how I'm testing your config with p9k.

```zsh
zsh -dfis <<END
  unset -m 'POWERLEVEL9K_*'
  POWERLEVEL9K_MODE='nerdfont-complete'
  POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes)
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir_writable dir vcs)
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    virtualenv
    root_indicator
    background_jobs
    time
    disk_usage
    ram
  )
  POWERLEVEL9K_CUSTOM_JAVASCRIPT="echo -n '\ue781' JavaScript"
  POWERLEVEL9K_CUSTOM_JAVASCRIPT_BACKGROUND="yellow"
  POWERLEVEL9K_CUSTOM_JAVASCRIPT_FOREGROUND="black"
  POWERLEVEL9K_CUSTOM_PYTHON="echo -n '\uf81f' Python"
  POWERLEVEL9K_CUSTOM_PYTHON_BACKGROUND="blue"
  POWERLEVEL9K_CUSTOM_PYTHON_FOREGROUND="black"
  POWERLEVEL9K_CUSTOM_RUBY="echo -n '\ue21e' Ruby"
  POWERLEVEL9K_CUSTOM_RUBY_BACKGROUND="red"
  POWERLEVEL9K_CUSTOM_RUBY_FOREGROUND="black"
  POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON=""
  POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
  POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  POWERLEVEL9K_PROMPT_ON_NEWLINE=true
  POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
  POWERLEVEL9K_USER_DEFAULT_ICON='\uF415'
  POWERLEVEL9K_USER_ROOT_ICON='\uF09C'
  POWERLEVEL9K_USER_SUDO_ICON='\uF09C'
  POWERLEVEL9K_VCS_GIT_GITHUB_ICON='\uF408'
  POWERLEVEL9K_VCS_GIT_ICON='\uF408'
  source ~/.oh-my-zsh/custom/themes/powerlevel9k/powerlevel9k.zsh-theme
END
```

If you run this command, you'll see some junk followed by one line showing the prompt. Please use the same method to verify that you've isolated all config options.

**Comment by teddyhwang** [comment]
Okay, thanks for looking into this! It turns out the problem was because I was on the `next` branch of POWERLEVEL_9K and not master. Switching it back to master shows the exact same look.

Do you plan on adopting the changes happening in `next` for 10k?

**Comment by romkatv** [comment]
Powerlevel10k is only providing compatibility with the stable/released code from Powerlevel9k. `next` is one of the development branches in Powerlevel9k; it has no compatibility or stability guarantees.
