### ISSUE TITLE
activate mercurial plugin

### ISSUE THREAD

**Issue by dio4ev** [romkatv/powerlevel10k#531]
Hi!

I switched to powerlevel10k today, as powerlevel9k is incredible slow...
How can I activate the mercurial plugin in this theme? [0]

Setting the PROMPT... did not change anything.

Thanks,
Jonas

[0]: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/mercurial

**Comment by romkatv** [comment]
From the docs:

> By default only `git` vcs backend is enabled in Powerlevel10k. If you need `svn` and `hg`, add them to `POWERLEVEL9K_VCS_BACKENDS`. These backends aren't yet optimized in Powerlevel10k, so enabling them will make prompt *very slow*.

If you want to display mercurial status in Powerlevel10k prompt, add the following line to `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_VCS_BACKENDS=(git hg)
```

(If you don't have `~/.p10k.zsh`, add this line to `~/.zshrc`.)

As the quoted passage says, it'll make prompt *very slow*. `POWERLEVEL9K_VCS_BACKENDS` is the only parameter that has this effect. Few users are relying on svn and hg these days, so I didn't optimize that part of the code.

**Comment by ZenenTreadwell** [comment]
Do you have any instructions or guidelines about how I would go about optimizing the code for Mercurial?

**Comment by romkatv** [comment]
Not really.
