### ISSUE TITLE
Why i cannot display username@host

### ISSUE THREAD

**Issue by Photonico** [romkatv/powerlevel10k#534]
I have added `context` item to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS`

```
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    context
    # os_icon               # os identifier
    dir                     # current directory
    vcs                     # git status
    # prompt_char           # prompt symbol
)
```

but it still cannot display username@host

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-add-username-andor-hostname-to-prompt.
