### ISSUE TITLE
[Feature Request] Haskell GHC version support

### ISSUE THREAD

**Issue by nasyxx** [romkatv/powerlevel10k#535]
Can p10k support the current version of Haskell GHC Compiler, defined in stack.yaml file?

**Comment by romkatv** [comment]
What command can you run to print that version?

Do you want to see the version only when there is stack.yaml in the current directory or above?

Is stack.yaml used only by Haskell?

**Comment by nasyxx** [comment]
Hi,

> What command can you run to print that version?

`stack ghc -- --numeric-version --no-install-ghc` will print a version number like `8.6.5`

> Do you want to see the version only when there is stack.yaml in the current directory or above?

Yes. On the other hand, the above command returns stack ghc version of global if there is no stack.yaml in the current directory.

> Is stack.yaml used only by Haskell?

I think so. There is no other irrelevant result in the search of `stack.yaml` in Google.

Thanks a lot!

**Comment by romkatv** [comment]
This is done.

Please update powerlevel10k, restart zsh and then either run `p10k configure` to generate a new config or manually add `haskell_stack` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` in `~/.p10k.zsh`.

**Comment by romkatv** [comment]
Please let me know whether it works for you and whether it behaves as you would expect.

**Comment by nasyxx** [comment]
It works! Thank you very much!

**Comment by romkatv** [comment]
Thanks for verifying!
