### ISSUE TITLE
vi-mode indicator error

### ISSUE THREAD

**Issue by yanzhang0219** [romkatv/powerlevel10k#536]
Hello, 

First I enter Visual mode (prompt symbol turns to "V"). Then I make a selection, say two characters. Next, I press `d` to delete these two selected characters and meanwhile, we go back to the Normal mode automatically. However, the prompt symbol is still "V' not "<". Also, no matter how many times I press `ESC`, the prompt symbol stays at "V". If I press `i` to go to the Insert mode, the prompt changes from "V" to ">" and then if I press `ESC` to go back to the Normal mode, the prompt changes from ">" to "V".

By following these steps above, I think this issue can be reproduced easily.

Thank you.

Best regards,

**Comment by romkatv** [comment]
Thanks for the report! Fixed.
