### ISSUE TITLE
p10k is continually reconfigures on new shell (zsh)

### ISSUE THREAD

**Issue by macintacos** [romkatv/powerlevel10k#538]
No matter what I do, whenever I start a new zsh shell I'm presented with the powerlevel10k configurator even though I've had it configured for several months. The `.p10k.zsh` file is symlinked to the actual file defined elsewhere in my filesystem (for backup purposes), but that's never been an issue in the past. Genuinely don't know how it's suddenly not understanding where things are. Updated to the latest version and still get the prompt.

Funnily enough, I can go through the whole wizard, set everything up, save the config, and then when I start a new shell it'll start up the configurator again. I'll even see in my repository that there are changes to the file that were saved to disk, but it seems like p10k can't find it.

[Here's a gif of the issue in action.](https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/Apurkw6e/Screen+Recording+2020-02-29+at+23.35.gif?v=7e0bcd70d5f03d99471bd0dd41d1d0ce)
You can see my .zshrc and .p10k files here:

- [`.zshrc`](https://github.com/macintacos/dotfiles/blob/master/.zshrc)
- [`.p10k.zsh`](https://github.com/macintacos/dotfiles/blob/master/.zsh/.p10k.zsh)

Please let me know if there's anything else that I can do to debug this issue; really don't know where to start.

**Comment by macintacos** [comment]
Nuked my whole configuration, cloned my dotfiles repo to my machine and then set everything up again and it's now working as I expect. Really not sure what was borked, but I'll close this out and reopen if I experience it again.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration-wizard-runs-automatically-every-time-zsh-is-started.
