### ISSUE TITLE
Gitstatus dying on Godot repo

### ISSUE THREAD

**Issue by evolarium** [romkatv/powerlevel10k#54]
Gitstatus seems to be dying on the 3.1 branch of the Godot repo, after building godot.x11.opt.tools.64.  I get the following message in dmesg when it happens:

[Sun Apr  7 18:33:09 2019] traps: gitstatusd-linu[17029] general protection fault ip:5616ea234f32 sp:7fff3f336890 error:0 in gitstatusd-linux-x86_64[5616ea200000+20a000]

I've put a copy of the repo here, to see if you can replicate it:

[https://drive.google.com/open?id=1utiZyxuxkK9PDu5Y3RWxEybxO7kAOp7W](https://drive.google.com/open?id=1utiZyxuxkK9PDu5Y3RWxEybxO7kAOp7W)

**Comment by romkatv** [comment]
Thanks for the bug report and a snapshot of the repo. I reproduced this bug, fixed it in https://github.com/romkatv/gitstatus/commit/b668f1ff25a4bea2271b7276b46bbeb059d6fab5, rebuilt binaries on all platforms and pushed a new release. Please `git pull` powerlevel10k.

**Comment by evolarium** [comment]
Thanks.  It is working with your fix.
