### ISSUE TITLE
My question

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#540]
How can I modify this blue part?
Where are the corresponding configuration options?

![2020年3月2日 GMT+0800 下午74039](https://user-images.githubusercontent.com/61009000/75676810-ff03b580-5cc4-11ea-8d89-a445983b52d6.jpg)

**Comment by romkatv** [comment]
This is `dir` prompt segment, so search for `dir:` in `~/.p10k.zsh`. In general, to modify settings for prompt segment `xyz`, search for `xyz:`.

**Comment by 26chk** [comment]
> 这是`dir`提示段，所以搜索`dir:`在`~/.p10k.zsh`。通常，要修改提示段的设置`xyz`，请搜索`xyz:`。

Yes, I found detailed configuration options for dir: but I cannot find configuration options for xyz:

![Screenshot_20200302_204549_com termux](https://user-images.githubusercontent.com/61009000/75677723-1348b200-5cc7-11ea-94e2-6d36a9dc42b4.jpg)
![Screenshot_20200302_204610_com termux](https://user-images.githubusercontent.com/61009000/75677736-16dc3900-5cc7-11ea-82c2-6dd5646b566f.jpg)

**Comment by romkatv** [comment]
> I cannot find configuration options for `xyz:`

There is no prompt segment that's literally called "xyz". I used this name as a placeholder.

- to modify settings for prompt segment `dir`, search for `dir:`
- to modify settings for prompt segment `os_icon`, search for `os_icon:`
- to modify settings for prompt segment `vcs`, search for `vcs:`
- to modify settings for prompt segment `status`, search for `status:`
- to modify settings for prompt segment `direnv`, search for `direnv:`
- to modify settings for prompt segment `nvm`, search for `nvm:`
- etc.

**Comment by 26chk** [comment]
> > 我找不到以下配置选项 `xyz:`
> 
> 没有字面上称为“ xyz”的提示段。我使用此名称作为占位符。
> 
> * 修改提示段的设置`dir`，搜索`dir:`
> * 修改提示段的设置`os_icon`，搜索`os_icon:`
> * 修改提示段的设置`vcs`，搜索`vcs:`
> * 修改提示段的设置`status`，搜索`status:`
> * 修改提示段的设置`direnv`，搜索`direnv:`
> * 修改提示段的设置`nvm`，搜索`nvm:`
> * 等等

Hmm ... how do I modify the blue part of dir? Which configuration option is it?

**Comment by romkatv** [comment]
> Hmm ... how do I modify the blue part of dir? Which configuration option is it?

:point_down: 

```zsh
# Current directory background color.
# typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
```

It's literally the first line after you find "dir:" and it has a comment.

There is also this at the top of the file:

```zsh
# Tip: Looking for a nice color? Here's a one-liner to print colormap.
#
#   for i in {0..255}; do print -Pn "%K{$i} %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'}; done
```

**Comment by 26chk** [comment]
I want to replace the blue part
But I can't find where to configure.
See the picture of the first question.

**Comment by 26chk** [comment]
> > Hmm ... how do I modify the blue part of dir? Which configuration option is it?
> 
> 
> 
> ```shell
> # Current directory background color.
> # typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
> ```
> 
> It's literally the first line after you find "dir:" and it has a comment.
> 
> There is also this at the top of the file:
> 
> ```shell
> # Tip: Looking for a nice color? Here's a one-liner to print colormap.
> #
> #   for i in {0..255}; do print -Pn "%K{$i} %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%8)):#7}:+$'\n'}; done
> ```

I want to replace the blue part
But I can't find where to configure.
See the picture of the first question.

**Comment by romkatv** [comment]
What do you mean by "replace the blue part"? Does it mean "change the color from blue to something else"?

**Comment by 26chk** [comment]
> “替换蓝色部分”是什么意思？这是否意味着“将颜色从蓝色更改为其他颜色”？

Yes

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/540#issuecomment-593394351. This comment points to the parameter that controls the background color of `dir` prompt segment. It also points to a code snippet that you can use to choose a suitable color.

If language barrier is the problem, perhaps ask someone with better mastery of Chinese and English to help?

**Comment by 26chk** [comment]
> 参见[＃540（评论）](https://github.com/romkatv/powerlevel10k/issues/540#issuecomment-593394351)。该注释指向控制`dir`提示段背景颜色的参数。它还指向一个代码段，您可以使用该代码段选择合适的颜色。
> 
> 如果语言障碍是问题，也许会要求精通中文和英文的人提供帮助？



> See [#540 (comment)](https://github.com/romkatv/powerlevel10k/issues/540#issuecomment-593394351). This comment points to the parameter that controls the background color of `dir` prompt segment. It also points to a code snippet that you can use to choose a suitable color.
> 
> If language barrier is the problem, perhaps ask someone with better mastery of Chinese and English to help?

Thank you very much, I have found the problem, I will add my English expression😅

**Comment by 26chk** [comment]
> See [#540 (comment)](https://github.com/romkatv/powerlevel10k/issues/540#issuecomment-593394351). This comment points to the parameter that controls the background color of `dir` prompt segment. It also points to a code snippet that you can use to choose a suitable color.
> 
> If language barrier is the problem, perhaps ask someone with better mastery of Chinese and English to help?

Thank you very much, I have found the problem, I will add my English expressionsweat_smile
