### ISSUE TITLE
pyenv/rbenv only reads global

### ISSUE THREAD

**Issue by yupswing** [romkatv/powerlevel10k#541]
I want to see the python/ruby version only when it is set locally (as of https://github.com/romkatv/powerlevel10k/issues/333)

So my configuration reads:
```
  typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local)
  typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true
```

But when in a folder with a local python it does not show ANYTHING
```
❯ pyenv local
2.7.17
❯ pyenv global
3.8.1
```
---
So I tried to set the configuration as follow
```
  typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)
  typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true
```

and the segment shows always `3.8.1`, even in a folder with a local 2.7.17
![2020-03-03T13:12:20_958x229](https://user-images.githubusercontent.com/10497150/75774637-a843bd80-5d50-11ea-9044-12727c430dd8.png)

am I doing something wrong or is there a wrong behaviour?
It does behave exactly the same with `rbenv`

**Comment by romkatv** [comment]
> ![2020-03-03T13:12:20_958x229](https://user-images.githubusercontent.com/10497150/75774637-a843bd80-5d50-11ea-9044-12727c430dd8.png)

What is the output of the following command when your current directory is `~/test`?

```zsh
() {
  emulate -L zsh -o extended_glob
  type pyenv
  pyenv version
  pyenv local
  pyenv global
  typeset -pm '*PYENV*'
  local f
  for f in ./(../)#.python-version; do
    print -r -- $f
    ls -ld -- $f
    cat -- $f
  done
}
```

**Comment by yupswing** [comment]
here we are. thanks for your time :)

```
pyenv is a shell function from /home/simo/.zshlib/modules/50-environments.zsh
2.7.17 (set by /home/simo/test/.python-version)
2.7.17
3.8.1
typeset -g -i _POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=1
typeset -g -a POWERLEVEL9K_PYENV_SOURCES=( shell local global )
export PYENV_SHELL=zsh
typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=true
export PYENV_DIR=/home/simo/.pyenv
typeset -g -a _POWERLEVEL9K_PYENV_SOURCES=( shell local global )
./.python-version
-rw-rw-r-- 1 simo simo 7 Mar  3 12:46 ./.python-version
2.7.17
```


```zsh
#50-environments.zsh
export PYENV_DIR="$HOME/.pyenv"
if [[ -d $PYENV_DIR ]]; then
  export PATH="$PYENV_DIR/bin:$PATH"
  eval "$(pyenv init -)"
fi
```

![2020-03-03T15:49:32_959x719](https://user-images.githubusercontent.com/10497150/75787177-9bca5f80-5d66-11ea-8771-eded369e8661.png)

**Comment by romkatv** [comment]
Cannot reproduce :-/

Are you using the latest version of powerlevel10k? Could you update and retry?

**Comment by yupswing** [comment]
I am using the latest version of powerlevel10k (commit 945643bcab868e95d0e0315f9fc961e6fb8730ca)

This is my config file (stripped of comments). [p10k.txt](https://github.com/romkatv/powerlevel10k/files/4281946/p10k.txt)

Also, to be sure, I've dumbed down my `.zshrc` to only this to eliminate every possible interference.

```zsh
#PYENV
export PYENV_DIR="$HOME/.pyenv"
if [[ -d $PYENV_DIR ]]; then
  export PATH="$PYENV_DIR/bin:$PATH"
  eval "$(pyenv init -)"
fi
#ZPLUG (with only powerlevel10k)
export ZPLUG_HOME=$HOME/.zshlib/zplug
source $ZPLUG_HOME/init.zsh
zplug romkatv/powerlevel10k, as:theme, depth:1
source "$HOME/.zshlib/p10k.zsh"
zplug load
```

Same exact behaviour.

---

Btw thanks again, if you can't help me don't worry too much and delete this issue, powerlevel10k is already a marvel as it is, to see the local `(py|rb)env version` was just a nice (not essential) addition for me.

**Comment by romkatv** [comment]
Figured it out. You have a typo in `~/.zshrc`. You need to rename `PYENV_DIR` to `PYENV_ROOT`. Please let me know if this fixes the problem. (It's the same with `rbenv`.)

I'll debug later why setting `PYENV_DIR` produces different results in p10k and pyenv. From my understanding of pyenv documentation what p10k shows is correct.

**Comment by yupswing** [comment]
Oh god, thank you very much. Obviously it was my fault. :)
It works now.

**Comment by romkatv** [comment]
> I'll debug later why setting `PYENV_DIR` produces different results in p10k and pyenv.

FYI: This is now fixed. Powerlevel10k is handling `PYENV_DIR` the same way as pyenv. (This doesn't mean that you should set `PYENV_DIR`.)
