### ISSUE TITLE
nodenv section behaviour

### ISSUE THREAD

**Issue by yupswing** [romkatv/powerlevel10k#542]
Is it possible to have the same behaviour implemented for `rbenv` (#333) and `pyenv` (#372)
in `nodenv`?

So, basically, supporting the new config

```
POWERLEVEL9K_NODENV_SOURCES
```

Thanks a lot for the hard work.

**Comment by romkatv** [comment]
Sure, I'll add this when I get a moment of free time.

By the way, if you are using several `*env` tools, you might want to switch to [asdf](https://asdf-vm.com/#/).

**Comment by romkatv** [comment]
This is done. Please update powerlevel10k and give it a try. Let me know whether it works for you.

**Comment by yupswing** [comment]
Confirmed. Thanks a lot, also for the suggestion about `asdf`, as soon as I'll get some time I'll give it a try.

**Comment by romkatv** [comment]
Thanks for the confirmation!
