### ISSUE TITLE
Feature request: hybrid one-or-two-line layout

### ISSUE THREAD

**Issue by gergelyhunyady** [romkatv/powerlevel10k#544]
Currently the user can specify one-line or two-line layout exclusively.

A third option would be really nice imo: The prompt changes automatically from one-line to two-line layout if the remaining space for typing your command is less than X characters (or similar rules).

I managed to quickly modify the agnoster theme myself to behave like that earlier but that's a small and simple script compared to powerlevel10k.

Any chance of adding this feature? Or maybe I just didn't found it but it already exists?

Thanks for your work!

**Comment by romkatv** [comment]
This feature doesn't currently exist in powerlevel10k and I'm reluctant to add it. Unlike agnoster, powerlevel10k prompt doesn't stay static after it's printed. It can change [depending on what you are typing](https://github.com/romkatv/powerlevel10k/blob/master/README.md#show-on-command) or expensive computation finishes in the background. Having command line jump back and forth could be jarring, but not having it jump back and forth would be confusing.

If you value horizontal space, take a look at [FAQ](https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-is-the-best-prompt-style-in-the-configuration-wizard). In particular, two-line prompt with [Transient Prompt](https://github.com/romkatv/powerlevel10k/blob/master/README.md#transient-prompt) is a popular configuration.
