### ISSUE TITLE
Questions about suggestions and completions folder color

### ISSUE THREAD

**Issue by AmrBinBashir** [romkatv/powerlevel10k#553]
How to change colors of specific segments. I mean how to know it's variables or whatever config related to it.

and can i change suggestions color. if you look at the pic below, i typed only "source ~/." the rest is suggested but it's the same color and its annoying.  
![2020-03-07_04-23](https://user-images.githubusercontent.com/48618675/76135014-c567dd00-602b-11ea-800b-8b8c95da2dea.png)

and can i change folders colors in tab completions, look at the page below. 
![2020-03-07_04-27](https://user-images.githubusercontent.com/48618675/76135032-ec261380-602b-11ea-868d-6e0c444e4d1e.png)

I cam from "agnoster" theme which didn't have these two problems but i like powerlvl10k more and hope i can fix it.

**Comment by romkatv** [comment]
> How to change colors of specific segments. I mean how to know it's variables or whatever config related to it.

See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-prompt-colors.

> and can i change suggestions color
> and can i change folders colors in tab completions

See https://github.com/romkatv/powerlevel10k/blob/master/README.md#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect.
