### ISSUE TITLE
Idea: decide according to $DISPLAY whether to use certain symbols

### ISSUE THREAD

**Issue by doronbehar** [romkatv/powerlevel10k#555]
Sometimes I use a bare TTY. Naturally, in a tty, my prompt doesn't look as good as it does inside an X session. I was considering editing my config to reflect this - according to `$DISPLAY`, but that would probably be tedious and I think this work could be useful for any other powerlevel10k users out there. 

Hence I wonder what would the author think about implementing such a behavior here.

**Comment by romkatv** [comment]
Here's the best way to do what you are after.

1. Run `p10k configure` and select *Lean* → *ASCII* → *8 colors*. The remaining options are up to your taste.
2. Run `mv ~/.p10k.zsh ~/.p10k-portable.zsh`.
3. Run `p10k configure` again and select any style you like.
4. Replace the existing line in `~/.zshrc` that sources `~/.p10k.zsh` with this code:
```zsh
if zmodload zsh/terminfo && (( terminfo[colors] >= 256 )); then
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
else
  [[ ! -f ~/.p10k-portable.zsh ]] || source ~/.p10k-portable.zsh
fi
```

**Comment by doronbehar** [comment]
I knew you wouldn't disappoint me @romkatv . Thanks!

**Comment by magnetophon** [comment]
The above code works for me when I change the first line to:
```shell
if zmodload zsh/terminfo && (( $terminfo[colors] >= 256 )); then
```

Maybe obvious to people that know their shell, but writing it here might save noobs like me some time.

**Comment by romkatv** [comment]
@magnetophon Does it work if you *don't* change the first line? That is, if you don't add `$` in front of `terminfo`? If it doesn't, what's the output of `$ZSH_VERSION`?

The original line should work as written. With your change it will work in some cases but not in others. More specifically, it won't work if there is no element with key `colors` in `terminfo`.

**Comment by magnetophon** [comment]
@romkatv I misspoke. It *does* work without the change. Sorry for the noise.

**Comment by romkatv** [comment]
> @romkatv I misspoke. It _does_ work without the change.

Thanks for the confirmation. I'll repeat that you should use the original line (without `$`) because the changed line (with `$`) will give  you an error if terminfo doesn't specify how many colors the terminal supports.

**Comment by magnetophon** [comment]
Thanks. I had already changed and committed my dotfiles to remove the $ again.
