### ISSUE TITLE
Node command not found in windows.

### ISSUE THREAD

**Issue by rakeshshubhu** [romkatv/powerlevel10k#556]
Every one have fixed this issue. But I'm so unable to fix it in windows.
`node -v` command not found. When I try in `gitbash` it works.
I uncommented the line in my .`zshrc` file. But it still gives me the error. How can I debug it?

```
# If you come from bash you might have to change your $PATH.
 export PATH=$HOME/bin:/usr/local/bin:$PATH
```
I have followed the steps mentioned here well.. but cannot make it work.
https://stackoverflow.com/questions/12743928/command-not-found-after-npm-install-in-zsh

**Comment by romkatv** [comment]
> Every one have fixed this issue.

Could you describe the issue?

- What do you do?
- What do you expect?
- What do you actually get?

**Comment by rakeshshubhu** [comment]
@romkatv when I try `node -v `in bash it works but it says command not found in my subsystem.

**Comment by romkatv** [comment]
It means `node` is not in your `PATH`. This has nothing to do with Powerlevel10k.

Does `bash -ic 'which node'` print path to `node`? If yes, you can fix your problem by running the following command:

```zsh
cat >>~/.zshrc <<END
typeset -gaU path
path+=($(dirname $(bash -ic 'which node')))
END
```

Restart Zsh and `node` should now work.

**Comment by rakeshshubhu** [comment]
okay. Thanks. `bash -ic 'which` no directory found.

**Comment by romkatv** [comment]
Run `bash` and then `type node`. What does it say?

**Comment by rakeshshubhu** [comment]
its asking me to install it with `sudo apt install nodejs`.. but `gitbash` seems to recognize `node -v`.
I did `sudo apt install nodejs` it prints out `E: Unable to locate package nodejs`
`

**Comment by romkatv** [comment]
> its asking me to install it with `sudo apt install nodejs`

There is no way `type node` will ask you to install anything. I suppose you ran `node` instead of `type node`. And apparently `node` doesn't work in bash despite what you said earlier.

Please ask for help on forums that are related to your issue.

**Comment by rakeshshubhu** [comment]
`type node` says  -bash: type: node: not found`

**Comment by romkatv** [comment]
> `type node` says `-bash: type: node: not found`

This is not surprising. `node` command doesn't work for you in bash. The problem is not related to powerlevel10k, zsh or bash. Please ask for help on forums that are related to your issue.
