### ISSUE TITLE
Cannot re run configure - pk10: command not found

### ISSUE THREAD

**Issue by shawnrmoss** [romkatv/powerlevel10k#557]
Ive installed this theme and have configured it initially.  

I ant to rerun the configuration.   The docs say to run pk10 configure when I do that I get an error.
pk10: command not found

How can I re run the configuration for this theme?

**Comment by romkatv** [comment]
This error means you aren't using powerlevel10k. You need to be using powerlevel10k for `p10k configure` to work. Please follow the [installation instructions](https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation) and then you'll be able to run `p10k configure`.

**Comment by GeekArthur** [comment]
@shawnrmoss I think you are running the wrong command, you should run `p10k` instead of `pk10`

**Comment by romkatv** [comment]
@GeekArthur Nice catch! I've totally missed it.

**Comment by Miguel-Bento-Github** [comment]
Same here. Opening .zshrc I can see 

```
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
"source /Users/miguelbento/.powerlevel10k/powerlevel10k.zsh-theme”
source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by romkatv** [comment]
@Miguel-Bento-Github Your `~/.zshrc` has syntax errors (unclosed double quote). You can fix it by removing all content from `~/.zshrc` and then following the installation instructions for Powerlevel10k to install it properly.

**Comment by Miguel-Bento-Github** [comment]
Thanks, all I had to do was change the double quotes on line 4.
Cheers

**Comment by romkatv** [comment]
> Thanks, all I had to do was change the double quotes on line 4.

👍 

Great! I didn't want to suggest it because I don't know where you have Powerlevel10k installed. In addition, I was worried that you'll end up with two `source` commands, or that you'll have something like this:

```zsh
"source /Users/miguelbento/.powerlevel10k/powerlevel10k.zsh-theme"
```

Some of these changes will appear to work even though they'll cause issues.

**Comment by Miguel-Bento-Github** [comment]
Exactly the problem.
There were two source paths, after removing that one it was actually better.
Thanks for the prompt replies. 
Enjoy your Sunday
