### ISSUE TITLE
Completions on new line disappear with prompt update

### ISSUE THREAD

**Issue by tuna-f1sh** [romkatv/powerlevel10k#56]
I'm using the purepower script but this also happens with vanilla powerlevel10k. When using completion, the options not selected disappear after 1 second. I presume this is the prompt update rate? Doesn't happen if the cursor doesn't move to a selection.

See: https://asciinema.org/a/w90JhM9DvXfhqUQG3fQBrUau5

**Comment by romkatv** [comment]
This looks awful.

Are you perchance setting `POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=true`?

**Comment by romkatv** [comment]
Do you have `vi-mode` plugin from oh-my-zsh enabled?

**Comment by romkatv** [comment]
Please update powerlevel10k and see if fixes the issue.

If it doesn't, please post your whole `~/.zshrc`, including the bits you might think irrelevant. Also, what's your OS and terminal?

**Comment by tuna-f1sh** [comment]
I am using `vi-mode` yes, it didn't seem to be the problem. 

However, disabling it, updating all the bundles and reloading seems to have fixed it. Not sure if it was actually an antigen caching issue or a fix in powerlevel10k upstream. I notice the clock on the RHS doesn't live update anymore (I don't mind this) but was before, perhaps it was something in that?

Thanks for your help and the plugin!

**Comment by romkatv** [comment]
Here's what's going on. I noticed in your screencast that time is updating in the right prompt. This can only happen if zle widget called `reset-prompt` is invoked periodically. There is a bug in zsh that makes completion menu disappear on `reset-prompt`. I've [reported this bug](https://www.zsh.org/mla/workers//2019/msg00161.html) some time back.

So I needed to figure out what's periodically calling `reset-prompt` in your setup. The first suspect was `POWERLEVEL9K_EXPERIMENTAL_TIME_REALTIME=true`, whose job is to do exactly this. The [documentation](https://github.com/romkatv/powerlevel10k/blob/master/EXTENDED_CONFIGURATION.md) for this option mentions that it triggers a bug in completion menu in zsh. However, you said you don't set this option, so I had to look for something else.

You mentioned you are using oh-my-zsh, so I searched its code for `reset-prompt`. There are just two plugins that call it. One is `dircycle` and it's benign -- it can only call `reset-prompt` when you press a key but not on its own. Another is `vi-mode`. This plugin traps `SIGWINCH` and calls `reset-prompt` from the trap. This lead looked very promising. First of all, I'm not using this plugin (neither should you, by the way; the only useful thing it does is set bindings, which you can simply copy to your `~/.zshrc` next to all other bindings you might have), so if _you_ are using it, it could be the reason why your setup behaves differently from mine.

There is [another bug](https://www.zsh.org/mla/workers//2019/msg00226.html) in zsh that causes the select/poll loop in zle to stall after zsh receives a signal. The fix has already been submitted but it'll take a while until it makes its way to all users. In the meantime I've implemented a workaround in gitstatusd. When zsh stops calling poll/select, sending it _any_ signal will fix the problem. Most signals will kill the process, and some signals will do something with user-visible effects. But there is one signal for which the default handler is to do nothing -- SIGWINCH. So gitstatusd sends SIGWINCH to its parent zsh process once a second. If zsh bugs out on poll/select, the next SIGWINCH will revive it. There are no other effects of SIGWINCH. That is, unless someone inappropriately traps SIGWINCH, which is exactly what `vi-mode` plugin does.

So the theory is that gitstatusd sends SIGWINCH once a second, which triggers `TRAPWINCH` in `vi-mode`, which calls `zle reset-prompt`, which triggers a bug in zsh, which wipes completion menu. I was almost certain this is it but to be sure I asked you whether you are using `vi-mode`. Even before receiving your reply I did two things. First, I submitted a [PR](https://github.com/robbyrussell/oh-my-zsh/pull/7753) to oh-my-zsh that removes `TRAPWINCH` from `vi-mode`. It has already been merged. I've also disabled the SIGWINCH workaround in gitstatusd by default; it can be enabled with `GITSTATUS_SEND_SIGWINCH=1`. I might flip the default back to "on" after some time, when most users will have updated their oh-my-zsh installation. So updating powerlevel10k and/or oh-my-zsh should fix the problem for you.

For completeness, there is [another bug](https://www.zsh.org/mla/workers/2019/msg00204.html) in zsh related to `reset-prompt` that affects history. My fix for it has just been merged in.

P.S.

I noticed that your shell flickers on `reset-prompt`. This isn't normal. I've seen terminals with unsavory rendering but nothing as bad as this. What terminal and OS are you using?

**Comment by tuna-f1sh** [comment]
Thanks for looking so deep into this. It looks like it was the `vi-mode` bug and your PR has fixed it. 

I'm using macOS with iTerm2. I also use my [dotfiles](https://github.com/tuna-f1sh/dotfiles) on Arch with termite/alacritty I don't experience the flickering in real-time, not sure why it appears in that asciinema.

**Comment by romkatv** [comment]
> It looks like it was the vi-mode bug and your PR has fixed it.

Thanks for the confirmation.

> I don't experience the flickering in real-time, not sure why it appears in that asciinema.

So flickering is an artifact of video capture. Makes sense.
