### ISSUE TITLE
Arch Linux prompt icon has some issue

### ISSUE THREAD

**Issue by atifchy** [romkatv/powerlevel10k#561]
powerlevel10k: 
![Screenshot from 2020-03-13 14-24-42](https://user-images.githubusercontent.com/42291930/76603240-d5555480-6536-11ea-80ad-7f44ecd66416.png)

Please replace it with the icon from this font: https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/font-logos.ttf

**Comment by romkatv** [comment]
Are you using Konsole?

**Comment by romkatv** [comment]
Added an FAQ: https://github.com/romkatv/powerlevel10k/blob/master/README.md#arch-linux-logo-has-a-dot-in-the-bottom-right-corner.

**Comment by atifchy** [comment]
> Added an FAQ: https://github.com/romkatv/powerlevel10k/blob/master/README.md#arch-linux-logo-has-a-dot-in-the-bottom-right-corner.

That Fixed the issue. Thanks.
