### ISSUE TITLE
ssh broken input

### ISSUE THREAD

**Issue by dottM3t** [romkatv/powerlevel10k#562]
hi,
when i connect to a remote server via ssh my "prompt" config doesn't work.
I followed the steps reported in the other closed issues but without luck. 
[https://github.com/romkatv/powerlevel10k/issues/267](url)

Here the output of "locale" command: 

```text
LANG="en_US.UTF-8" 
LC_COLLATE="en_US.UTF-8" 
LC_CTYPE="en_US.UTF-8" 
LC_MESSAGES="en_US.UTF-8" 
LC_MONETARY="en_US.UTF-8" 
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8" 
LC_ALL
```

**Comment by romkatv** [comment]
Could you provide more details about how exactly prompt doesn't work? A screenshot would be very useful.

**Comment by dottM3t** [comment]
Thanks for the reply Romka. 

Yes, i'm sorry. I will attach the screenshot here. Obliviously ssh server and user are fake, i made this to show the behavior of prompt.

![screenPl10k](https://user-images.githubusercontent.com/28950416/76647303-dd27ef80-655c-11ea-8137-ba6b7a73aacf.jpg)

**Comment by romkatv** [comment]
The first two prompts look like fine to me. Do you believe there is anything wrong with them?

The last prompt (after `ssh`) doesn't look like powerlevel10k prompt. It doesn't even look like Zsh prompt. If you want to have powerlevel10k prompt on `show.dev.edu`, you need to install Zsh and powerlevel10k there.
