### ISSUE TITLE
pasting characters into terminal slow

### ISSUE THREAD

**Issue by yee379** [romkatv/powerlevel10k#568]
so i have this nasty habit of pasting either long commands, or multiple line commands rather than writing a script for it. when i do this on a powerlevel10k terminal, it puts pasted really slowly (maybe a few characters a second). interestingly, pressing the right arrow whilst its pasting will increase the pasting speed by about a factor of 2.

am i the only person experiencing this?

i was thinking that some kinda monitor for 'inhumanly' character speeds could be used to deactivate all the relevant checks to help speed up pasting commands.

**Comment by romkatv** [comment]
> so i have this nasty habit of pasting either long commands

Nothing wrong with that. I do this all the time.

Are you using Oh My Zsh? If so, it's Oh My Zsh that makes pasting slow. To fix this, find the following lines in `~/.zshrc`:

```zsh
# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true
```

Uncomment the second line.

Zsh doesn't have this "magic" by default, so setting `DISABLE_MAGIC_FUNCTIONS=true` is simply opting out from this terrible feature. It not only slows down copy-pasting to a crawl, it will also silently rewrite what you are pasting. This is really quite horrible and should never be used unless you know what you are doing and have the practice of expecting copy-pasted text to be rewritten by Zsh (but not by anything else).

If you aren't using Oh My Zsh, or if setting `DISABLE_MAGIC_FUNCTIONS=true` doesn't help, please let me know which terminal and OS you are using and I'll look further into it.

**Comment by yee379** [comment]
@romkatv! yep, i'm using Oh My Zsh - `DISABLE_MAGIC_FUNCTIONS=true` that helped a lot! :) thanks! it's not as fast as say pasting into `vi` or whatever, but its certainly a lot more useable than before :)

**Comment by romkatv** [comment]
Awesome! Thanks for confirming that `DISABLE_MAGIC_FUNCTIONS=true` has helped.

**Comment by pcroland** [comment]
I also have this problem and `DISABLE_MAGIC_FUNCTIONS=true` didn't solve it. Any idea?

**Comment by romkatv** [comment]
@pcroland Please do the following:

1. Run the following command and paste into the terminal when prompt appears. Is it fast or slow?
```zsh
() (
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd $tmp
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
POWERLEVEL9K_MODE=ascii
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR='%# '
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=()
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```
2. Run the following command and paste into the terminal when prompt appears. Is it fast or slow?
```zsh
PS1='%# ' zsh -f
```
3. Which OS and terminal are you using?

**Comment by pcroland** [comment]
I'm using Ubuntu 18.04.4 LTS with WSL inside Cmder. After these two commands it's really fast using Windows's bash, but in Cmder it's still slow.

**Comment by romkatv** [comment]
> After I paste these two commands the terminal will be just a %.

Do I understand it correctly that the answer to my first question is "fast"? I'll repeat the question here:

> 1. Run the following command and paste into the terminal when prompt appears. Is it fast or slow?
> 
> ```shell
> () (
>   emulate -L zsh -o err_return
>   local tmp
>   tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
>   {
>     cd $tmp
>     git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
>     >.zshrc <<\END
> POWERLEVEL9K_MODE=ascii
> POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR='%# '
> POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=()
> POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
> source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
> END
>     ZDOTDIR=$tmp zsh
>   } always {
>     cd /
>     rm -rf -- $tmp
>   }
> )
> ```

If it's indeed fast, then the slowness of pasting into your terminal is not caused by powerlevel10k. I suggest that you try to identify which part of your regular `~/.zshrc` makes pasting slow.

**Comment by pcroland** [comment]
I uninstalled everything, removed oh-my-zsh, zsh and p10k and everything. After that I reinstalled everything, zsh with `apt install zsh` (version 5.4.2), oh-my-zsh with the one liner from their website and also p10k and it turned out that p10k pasting is slow out of the box for me. Still no idea how to fix it.

**Comment by romkatv** [comment]
@pcroland Please run the following command:

```zsh
() (
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd $tmp
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
source ~/.p10k.zsh
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```

When prompt appears, paste into the terminal. Is it fast or slow?

**Comment by pcroland** [comment]
It's slow this time.

**Comment by romkatv** [comment]
Which OS and terminal are you using?

**Comment by pcroland** [comment]
I'm using Ubuntu 18.04.4 LTS with WSL inside Cmder.

**Comment by romkatv** [comment]
Then it means Cmder doesn't support bracketed paste or you don't have this feature enabled. I don't know windows terminals well enough to know which ones support bracketed paste. Using a terminal without bracketed paste is an exercise in frustration.

**Comment by pcroland** [comment]
There are two pasting methods in Cmder, one works with Ctrl+V (pastes the whole thing as is), the other one works with right click (runs commands line by line). Both methods have the same speed with bash or other zsh themes and only the Ctrl+V method is slow with p10k:
https://x0.at/dpI.mp4

**Comment by romkatv** [comment]
Then it means one is using bracketed paste and another is writing one character at a time. The first is good, the second is bad.

> https://x0.at/dpI.mp4

This is crazy slow both in bash and zsh.

**Comment by pcroland** [comment]
But bash pasting is pretty fast I would say. Is there anything I can do so zsh will paste the same way?

**Comment by romkatv** [comment]
Use a terminal that implements bracketed paste.

**Comment by pcroland** [comment]
Okay, I'll use wsltty, but I'm still curious why bash is faster if I also paste there without bracketed paste support.

**Comment by russiann** [comment]
> am i the only person experiencing this?

Nope. Me too. 

Here a GIF:
https://pasteboard.co/JaykB9N.gif

I'm using powerlevel10k with oh-my-zsh on iTerm2 on a Macbook.

**Comment by romkatv** [comment]
@russiann Please run the following command:

```zsh
() (
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd $tmp
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
source ~/.p10k.zsh
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```

When prompt appears, paste into the terminal. Is it fast or slow?

**Comment by pcroland** [comment]
I just can't get used to other terminals than Cmder so I'll have to accept slow pasting :-/ I understand that it doesn't support bracketed paste but it's still ~20x slower with p10k than with other themes.

**Comment by romkatv** [comment]
@pcroland I've sped up pasting in terminals without bracketed paste. That said, pasting in terminals without bracketed paste is still about 500 times slower than. You also cannot undo those pastes.

**Comment by pcroland** [comment]
Nice, thank you very much.

**Comment by romkatv** [comment]
Please update and check whether it's faster now.

**Comment by pcroland** [comment]
It's much faster, almost the same speed as in bash, so it's pretty good now, thanks.

**Comment by romkatv** [comment]
Thanks for the confirmation.

@russiann This fix shouldn't have any effect on your setup. iTerm2 is a decent terminal, so it supports bracketed paste. Pasting text of any size should be instant. If it isn't, there is either something misconfigured in your zsh or in iTerm2 settings. See my previous comment, which should help narrow down where the problem lies.

**Comment by pcroland** [comment]
This is the current speed (bash vs p10k):
https://x0.at/PKn.mp4

**Comment by romkatv** [comment]
> This is the current speed (bash vs p10k):
> https://x0.at/PKn.mp4

Both are insanely slow.

**Comment by pcroland** [comment]
It's good enough for me so I don't have to switch to another terminal :D

**Comment by russiann** [comment]
> @russiann Please run the following command:
> 
> ```shell
> () (
>   emulate -L zsh -o err_return
>   local tmp
>   tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
>   {
>     cd $tmp
>     git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
>     >.zshrc <<\END
> source ~/.p10k.zsh
> source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
> END
>     ZDOTDIR=$tmp zsh
>   } always {
>     cd /
>     rm -rf -- $tmp
>   }
> )
> ```
> 
> When prompt appears, paste into the terminal. Is it fast or slow?

Thank you! Solved! 😁
Now it is fast.

**Comment by romkatv** [comment]
> Thank you! Solved! 
> Now it is fast.

If pasting is fast with this command (it should really be instant for text of any size) but slow with your own zshrc (you see text appearing one character at a time), there is something wrong with zshrc. Try disabling things one by one to find out what it is.
