### ISSUE TITLE
Your Git prompt may disappear or become slow.

### ISSUE THREAD

**Issue by ugrinwald** [romkatv/powerlevel10k#569]
Hi @romkatv.
Have the following issue and I saw something similar (two instances of powerlevel10k) I uninstalled both as recommended and now just have the one in the /.oh-my-zsh/custom/themes location.

Also pulled after cloning to make sure I have the latest.
Here are the diagnostics when running command provided.

[ERROR]: gitstatus failed to initialize.

  Your Git prompt may disappear or become slow.

  The content of /private/var/folders/7j/8488rx5j7_n26ym2973t74xr0000gn/T/gitstatus.POWERLEVEL9K.501.63156.1584574808.3.xtrace.log (gitstatus_start xtrace):

    +(anon):7> setopt monitor
    +(anon):9> ((  ! _GITSTATUS_STATE_POWERLEVEL9K  ))
    +(anon):10> [[ -r /proc/version ]]
    +(anon):13> print -rn
    +(anon):14> zsystem flock -f lock_fd /private/var/folders/7j/8488rx5j7_n26ym2973t74xr0000gn/T/gitstatus.POWERLEVEL9K.501.63156.1584574808.3.lock
    +(anon):15> [[ 14 == <1-> ]]
    +(anon):17> typeset -gi '_GITSTATUS_LOCK_FD_POWERLEVEL9K=lock_fd'
    +(anon):20> '(anon)' /dev/fd/16
    +(anon):1> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=-1'
    +(anon):2> sysopen -r -o cloexec -u resp_fd -- /dev/fd/16
    +(anon):3> [[ 18 == <1-> ]]
    +(anon):4> typeset -gi '_GITSTATUS_RESP_FD_POWERLEVEL9K=resp_fd'
    +(anon):120> typeset -gi '_GITSTATUS_STATE_POWERLEVEL9K=1'
    +(anon):123> ((  ! async  ))
    +(anon):124> ((  _GITSTATUS_CLIENT_PID_POWERLEVEL9K == sysparams[pid]  ))
    +(anon):126> local pgid
    +(anon):127> ((  0 < 20  ))
    +(anon):128> [[ -t 18 ]]
    +(anon):129> sysread -s 20 -t 5.0000000000 -i 18 'pgid[$#pgid+1]'
    +(anon):127> ((  20 < 20  ))
    +(anon):131> [[ '               63272' == \ #<1-> ]]
    +(anon):132> typeset -gi 'GITSTATUS_DAEMON_PID_POWERLEVEL9K=pgid'
    +(anon):134> sysopen -w -o cloexec -u req_fd -- /private/var/folders/7j/8488rx5j7_n26ym2973t74xr0000gn/T/gitstatus.POWERLEVEL9K.501.63156.1584574808.3.fifo
    +(anon):135> [[ 15 == <1-> ]]
    +(anon):136> typeset -gi '_GITSTATUS_REQ_FD_POWERLEVEL9K=req_fd'
    +(anon):147> zle -F 18 _gitstatus_process_response_POWERLEVEL9K
    +(anon):158> add-zsh-hook zshexit _gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:15> emulate -L zsh
    +add-zsh-hook:17> local -a hooktypes
    +add-zsh-hook:18> hooktypes=( chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name )
    +add-zsh-hook:22> local usage='Usage: add-zsh-hook hook function\nValid hooks are:\n  chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name'
    +add-zsh-hook:24> local opt
    +add-zsh-hook:25> local -a autoopts
    +add-zsh-hook:26> integer del list help
    +add-zsh-hook:28> getopts dDhLUzk opt
    +add-zsh-hook:55> shift 0
    +add-zsh-hook:57> ((  list  ))
    +add-zsh-hook:60> ((  help || 2 != 2 || 6 == 0  ))
    +add-zsh-hook:65> local hook=zshexit_functions
    +add-zsh-hook:66> local fn=_gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:68> ((  del  ))
    +add-zsh-hook:83> ((  0  ))
    +add-zsh-hook:89> typeset -ga zshexit_functions
    +add-zsh-hook:90> set -A zshexit_functions _gitstatus_cleanup_POWERLEVEL9K
    +add-zsh-hook:92> autoload -- _gitstatus_cleanup_POWERLEVEL9K
    +(anon):163> print -nru 15 -- $'hello\C-_\C-^'
    +(anon):164> local expected=$'hello\C-_0\C-^' actual
    +(anon):165> ((  0 < 8  ))
    +(anon):166> [[ -t 18 ]]
    +(anon):167> sysread -s 8 -t 5.0000000000 -i 18 'actual[$#actual+1]'
    +(anon):167> return
                         ^ this command failed (5)

  The content of /private/var/folders/7j/8488rx5j7_n26ym2973t74xr0000gn/T/gitstatus.POWERLEVEL9K.501.63156.1584574808.3.daemon.log (gitstatus daemon log):

    +(anon):22> local pgid=63272
    +(anon):23> [[ 63272 == <1-> ]]
    +(anon):104> ((  lock_fd == -1  ))
    +(anon):27> trap '' PIPE
    +(anon):29> [[ -z '' ]]
    +(anon):30> local kernel
    +(anon):107> zsystem flock -- /private/var/folders/7j/8488rx5j7_n26ym2973t74xr0000gn/T/gitstatus.POWERLEVEL9K.501.63156.1584574808.3.lock
    +(anon):31> kernel=+(anon):31> uname -s
    +(anon):31> kernel=darwin
    +(anon):32> [[ -n darwin ]]
    +(anon):35> [[ '' == /* ]]
    +(anon):37> ((  0  ))
    +(anon):39> [[ -n '' ]]
    +(anon):42> local -aU os
    +(anon):43> case darwin (linux)
    +(anon):43> case darwin (cygwin_nt-*)
    +(anon):43> case darwin (mingw* | msys*)
    +(anon):43> case darwin (*)
    +(anon):50> os=( darwin )
    +(anon):52> local arch
    +(anon):53> arch=+(anon):53> uname -m
    +(anon):53> arch=x86_64
    +(anon):54> [[ -n x86_64 ]]
    +(anon):55> local daemons=( /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64 /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/usrbin/gitstatusd-darwin-x86_64-static /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64-static )
    +(anon):59> local files=( /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 )
    +(anon):60> daemons=( /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 )
    +(anon):62> ((  stderr_fd && 1 != 1  ))
    +(anon):72> ((  1  ))
    +(anon):74> [[ '' == <1-> ]]
    +(anon):77> local cpus
    +(anon):78> ((  ! 1  ))
    +(anon):78> [[ darwin == linux ]]
    +(anon):79> cpus=+(anon):79> sysctl -n hw.ncpu
    +(anon):79> cpus=16
    +(anon):84> args+=( -t 32 )
    +(anon):87> mkfifo -- /private/var/folders/7j/8488rx5j7_n26ym2973t74xr0000gn/T/gitstatus.POWERLEVEL9K.501.63156.1584574808.3.fifo
    +(anon):88> print -rn -- '               63272'
    +(anon):90> zf_rm -- /private/var/folders/7j/8488rx5j7_n26ym2973t74xr0000gn/T/gitstatus.POWERLEVEL9K.501.63156.1584574808.3.fifo
    +(anon):92> local daemon
    +(anon):93> daemon=/Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +(anon):94> /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 -s -1 -u -1 -d -1 -c -1 -m -1 -v DEBUG -t 32
    dyld: Symbol not found: __ZdlPvm
      Referenced from: /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64 (which was built for Mac OS X 10.13)
      Expected in: /usr/lib/libc++.1.dylib
     in /Users/ugrinwald/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64
    +(anon):95> local -i ret=133
    +(anon):96> ((  ret == 0 || ret == 10 || ret > 128  ))
    +(anon):96> return ret
    +(anon):99> local -i ret=133
    +(anon):100> kill -- -63272

  Your system information:

    zsh:      5.3.1
    uname -a: Darwin UriGrinaldsPro4 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
See https://github.com/romkatv/gitstatus/issues/83.
