### ISSUE TITLE
Too many threads for gitstatus: is it possible to have one gitstatusd per host?

### ISSUE THREAD

**Issue by Aetf** [romkatv/powerlevel10k#57]
I've been facing strange `can't create OS threads` error from different unrelated programs. Then I realized that gitstatusd spawned near 4000 threads...

Some context: I'm working on a shared host, which has a large number of CPU cores. Thus gitstatusd defaults to 320 threads per instance. And I heavily use tmux, inside which I have about 10~20 shells. Each shell prompt spawns one gitstatusd, which then starts 320 threads...

Therefore my suggestion: is it possible to launch exactly one gitstatusd per host, and each shell can communicate with it using unix domain socket?

**Comment by romkatv** [comment]
> gitstatusd spawned near 4000 threads...

Holy moly!

> Is it possible to launch exactly one gitstatusd per host?

Not at the moment, no. One-per-host would likely not work in some cases and be a security hole in others but one-per-user could work in theory. It would be tricky to support the update model ZSH users are accustomed to (`git pull` and restart ZSH works with all plugins and themes) but with enough code it could be done.

I don't have immediate plans to implement this given that you are the first one to bump into the limitations of the current one-per-zsh model. To alleviate your pain I've change the default number of threads gitstatusd spawns from `2 * NumCPUs` to `min(32, 2 * NumCPUs)`. You can also define `GITSTATUS_NUM_THREADS` in your `~/.zshrc` to override this. If you don't work with humongous git repositories, you can lower the number of threads with no ill effect. You can try `GITSTATUS_NUM_THREADS=4` and see if you notice any difference. If things get slower, try 8, and so on.

> and each shell can communicate with it using unix domain socket?

Currently communication is done via pipes. If I were to switch gitstatus to one-per-user model I would probably keep it. Is it a requirement of your system that communication is done via unix domain sockets? If so, could you elaborate where it comes from?

**Comment by Aetf** [comment]
Thanks for the quick reply!

> One-per-host would likely not work in some cases and be a security hole in others but one-per-user could work in theory.

Yeah, one-per-user sounds good.

> It would be tricky to support the update model ZSH users are accustomed to (git pull and restart ZSH works with all plugins and themes) but with enough code it could be done.

Actually the idea is not mine, [powerline](https://github.com/powerline/powerline) already does this. Maybe some similar techniques can be applied here.

See its [daemon](https://github.com/powerline/powerline/blob/develop/scripts/powerline-daemon)  and [client](https://github.com/powerline/powerline/blob/develop/client/powerline.py) (both in python, though depends on the environment, there's also shell script and compiled version). Zsh [bindings](https://github.com/powerline/powerline/blob/develop/powerline/bindings/zsh/powerline.zsh).

> Currently communication is done via pipes. If I were to switch gitstatus to one-per-user model I would probably keep it. Is it a requirement of your system that communication is done via unix domain sockets? If so, could you elaborate where it comes from?

No there's no such requirement. But I think using pipes may have some problems with concurrent writes when you have multiple clients. I'm not an expert in this, but there seems to be some [caveats](https://unix.stackexchange.com/questions/68146/what-are-guarantees-for-concurrent-writes-into-a-named-pipe).

> To alleviate your pain I've change the default number of threads gitstatusd spawns from 2 * NumCPUs to min(32, 2 * NumCPUs).

Sounds good.

> You can also define GITSTATUS_NUM_THREADS in your ~/.zshrc to override this. If you don't work with humongous git repositories, you can lower the number of threads with no ill effect. You can try GITSTATUS_NUM_THREADS=4 and see if you notice any difference. If things get slower, try 8, and so on.

Sure, I'll try this.

**Comment by romkatv** [comment]
> Actually the idea is not mine, powerline already does this. Maybe some similar techniques can be applied here.

This idea of spawning a local daemon and communicating with it via sockets is older than powerline. dbus does the same thing, as do many other services.

As I mentioned above, the difficulty is in supporting the same workflow users are accustomed to for updating to a newer version. This is solvable with enough code but to the best of my knowledge Powerline doesn't even attempt to do it. If the client in a new version of Powerline is not compatible with the daemon from the older version, an update won't go smoothly. I would also like the daemon to shut down automatically when there are no client ZSH instances talking to it. This is also solvable with enough code but the implementation details can be thorny.

Anyhow, I believe the original issue with gitstatusd spawning too many threads on your system is now fixed, so I'm closing it. Please reopen if I'm mistaken. I'll look into switching to one-per-user model in the future if demand for it materializes.
