### ISSUE TITLE
java_version segment doesn't update after manually switching the java version

### ISSUE THREAD

**Issue by jordanjennings** [romkatv/powerlevel10k#572]
I just enabled the `java_version` prompt segment and it's printing the the java version as of the moment the shell starts, but when I change the version the prompt does not update.

At the start looking good:
![image](https://user-images.githubusercontent.com/1031913/77169248-915ed400-6a8f-11ea-9180-7ba164226d84.png)

But then:
![image](https://user-images.githubusercontent.com/1031913/77169295-a0de1d00-6a8f-11ea-9a6b-3ac5d182f8d2.png)

This is on macOS using AdoptOpenJDK installed via homebrew and  the `jdk` function is the helper they recommend [here](https://github.com/AdoptOpenJDK/homebrew-openjdk#switch-between-different-jdk-versions), which looks like:

```
jdk() {
  version=$1
  export JAVA_HOME=$(/usr/libexec/java_home -v"$version");
  java -version
}
```

Is there additional configuration I need to do to get it to update after I switch versions? Seems like maybe caching is at play, if that's the case is there a simple way to bust the cache only when I switch jdk versions?

**Comment by romkatv** [comment]
Thanks for the report! Fixed.

**Comment by jordanjennings** [comment]
Pulled latest, looks great. Thanks!!!

**Comment by romkatv** [comment]
Thanks for the confirmation!
