### ISSUE TITLE
Transient Prompt stops working after updating configs and sourcing zshrc

### ISSUE THREAD

**Issue by nickw8** [romkatv/powerlevel10k#575]
So i have been updating different zsh configs which requires me to source zshrc. After I do, the Transient prompt feature no longer works. I'm sure its a user error and I'm missing something but I don't know what

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#weird-things-happen-after-typing-source-zshrc.
