### ISSUE TITLE
[Feature Request] Parameterise a prompt branch name max length

### ISSUE THREAD

**Issue by ivanmilov** [romkatv/powerlevel10k#579]
Hi, current implementation of function **my_git_formatter()** uses hardcoded value for the max branch name length (32). Very often I use longer names for branches. Can you please make a parameter for this value e.g. **POWERLEVEL9K_VCS_BRANCH_MAX_LENGTH**? 

I tried to set
```
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=60
POWERLEVEL9K_VCS_SHORTEN_LENGTH=60
```
but it had no effect.

**Comment by romkatv** [comment]
You can replace 32 in `~/.p10k.zsh` with another value of your choice. You can also replace it with a parameter of your choice.
