### ISSUE TITLE
Going from insert mode to normal mode removes previous lines

### ISSUE THREAD

**Issue by Thimoteus** [romkatv/powerlevel10k#58]
It seems like when using anything that displays what the vi mode is, going from insert mode to normal mode will delete previous lines, like [in this example](https://asciinema.org/a/7Z61IH9uFH9Aj4UijmrXQH2Wl).

My relevant theming info:

```
zstyle ':prezto:module:prompt' theme 'powerlevel10k'

source ~/.purepower
```

where `~/.purepower` was not changed.

Happy to provide other config info.

**Comment by romkatv** [comment]
Can you reproduce this in a clean environment? E.g., like this:

```zsh
git clone https://github.com/romkatv/powerlevel10k.git /tmp/powerlevel10k
(cd /tmp/powerlevel10k && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower)
echo '
  source /tmp/powerlevel10k/.purepower
  source /tmp/powerlevel10k/powerlevel10k.zsh-theme
  bindkey -v' >/tmp/powerlevel10k/.zshrc
env -i TERM=$TERM LANG=$LANG ZDOTDIR=/tmp/powerlevel10k zsh
```

(Type `rm -rf /tmp/powerlevel10k` afterwards to clean up.)

If yes, please post the output of `uname -a`, `echo $ZSH_VERSION` and which terminal you are using.

If no, try to figure out what in your environment is necessary for the bug to trigger.

**Comment by romkatv** [comment]
Friendly ping. I'll be happy to debug this issue if you can provide a bit more info. Right now I have nothing to go with.

**Comment by Thimoteus** [comment]
Haven't been able to narrow it down much, but I've been able to reproduce it on a fresh ubuntu 18.04 VM using zsh as follows:

1. install prezto:
```
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"`

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
```
2. install powerlevel10k according to prezto instructions:
```
git clone https://github.com/romkatv/powerlevel10k.git  ~/.zprezto/modules/prompt/external/powerlevel10k
ln -s ~/.zprezto/modules/prompt/{external/powerlevel10k/powerlevel10k.zsh-theme,functions/prompt_powerlevel10k_setup}
```
3. Edit `~/.zpreztorc` to change the theme:
```
...
zstyle :prezto:module:prompt theme 'powerlevel10k'
...
```

4. Install the theme:
```
( cd && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower )
echo 'source ~/.purepower' >>! ~/.zshrc
```

5. Enable vi mode in `.zpreztorc`:
```
...
zstyle ':prezto:module:editor' key-bindings 'vi'
...
```

5. quit into bash then start zsh again, and switch from insert to normal modes several times.

**Comment by romkatv** [comment]
Thank you for the instructions. I managed to reproduce this and submitted a fix: https://github.com/romkatv/powerlevel10k/commit/5fc6fca402c44ae5292befa1c7633cd2db8b912c. It should work now.

For the record, here's how I reproduced the problem:

```zsh
docker run -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 -e TERM=$TERM -it --rm ubuntu bash -uexc '
  apt update && apt install -y zsh git curl

  git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto
  zsh -ec "
    setopt EXTENDED_GLOB
    for rcfile in ~/.zprezto/runcoms/^README.md(.N); do
      ln -s \$rcfile ~/.\${rcfile:t}
    done"

  git clone https://github.com/romkatv/powerlevel10k.git  ~/.zprezto/modules/prompt/external/powerlevel10k
  ln -s ~/.zprezto/modules/prompt/{external/powerlevel10k/powerlevel10k.zsh-theme,functions/prompt_powerlevel10k_setup}
  echo "zstyle :prezto:module:prompt theme powerlevel10k" >> ~/.zpreztorc

  cd && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower
  echo "source ~/.purepower" >> ~/.zshrc

  echo "zstyle :prezto:module:editor key-bindings vi" >> ~/.zpreztorc

  zsh -i'
```

The culprit was in the interaction between Powerlevel10k and `editor` module from zprezto.

Thanks for reporting the bug!

**Comment by romkatv** [comment]
I believe this issue is fixed. Please reopen if not.
