### ISSUE TITLE
aws profiles dont show with new aws-cli2 which is public

### ISSUE THREAD

**Issue by nickw8** [romkatv/powerlevel10k#580]
The aws profile shower isn't popping up anymore with aws or kubectl commands anymore since i upgraded to the now public and recommended aws-cli2.

**Comment by romkatv** [comment]
How can I reproduce this? Could you describe the series of steps I need to perform that would result in something being shown in prompt when using aws-cli1 but not when using aws-cli2?

**Comment by nickw8** [comment]
I forgot the step to export the profile I'm using. User error. Closing ticket

**Comment by ronniehicks** [comment]
@nickw8 I'm seeing the same thing on my end. I'm using the `asp` command to change my AWS account target and it still doesn't seem to be working. How are you setting your export for it to show?
