### ISSUE TITLE
When changing Vi mode, prompt go up and old console output get deleted

### ISSUE THREAD

**Issue by kureijir** [romkatv/powerlevel10k#582]
I just updated p10k (haven't done so for a couple of months) and now my prompt would go up a line or two everytime I change from Insert mode to Normal mode, or Normal mode to Overtype mode (and vice versa).

Strangely, switching back and forth between Normal mode and Visual mode doesn't affected.

![Peek 2020-03-25 12-56](https://user-images.githubusercontent.com/21220094/77506282-0ff4b080-6e98-11ea-98e9-ac94fbf66447.gif)

**Comment by romkatv** [comment]
Does this problem go away if you type `exit` and then start a new Zsh shell?

If not, please attach your `~/.zshrc` to the issue. In addition, please post the output of the following command:

```zsh
() {
  emulate -L zsh -o xtrace -o err_return
  typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION|ZSH_PATCHLEVEL|TERM*|LC_*|LANG'
  uname -a
  print -r -- $widgets[zle-keymap-select]
  functions -- "${widgets[zle-keymap-select]#user:}"
  print -r -- $widgets[._p9k_orig_zle-keymap-select]
  functions -- "${widgets[._p9k_orig_zle-keymap-select]#user:}"
}
```

**Comment by kureijir** [comment]
Thanks for your quick response! After re-examining my `~/.zshrc` and deleting these lines, the problem is gone:

```
vim_ins_mode="%{$fg[yellow]%}[INS]%{$reset_color%}"
vim_cmd_mode="%{$fg[cyan]%}[CMD]%{$reset_color%}"
vim_mode=$vim_ins_mode

function zle-keymap-select {
  vim_mode="${${KEYMAP/vicmd/${vim_cmd_mode}}/(main|viins)/${vim_ins_mode}}"
  zle reset-prompt
}
zle -N zle-keymap-select

function zle-line-finish {
  vim_mode=$vim_ins_mode
}
zle -N zle-line-finish
```

I think those lines are used to setup my custom prompt (prior to using p10k). Since I've been using my `.zshrc` for so long and the problem only appear after updating p10k, I didn't think it was my `.zshrc` that caused the problem.

Again thank you for your help!

**Comment by romkatv** [comment]
Thanks for the update. You are correct that these lines are no longer necessary.
