### ISSUE TITLE
ip/public_ip/vpn not working in FreeBSD

### ISSUE THREAD

**Issue by gregf** [romkatv/powerlevel10k#583]
All the BSD's still use ifconfig and none of the IP segments currently show up.

**Comment by romkatv** [comment]
This works for me:

```zsh
(
  emulate -L zsh
  setopt no_unset err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd -- $tmp
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    cat >.zshrc <<\END
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(ip vpn_ip public_ip)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_IP_INTERFACE='.*'
POWERLEVEL9K_VPN_IP_INTERFACE='.*'
POWERLEVEL9K_VPN_IP_INTERFACE='.*'
POWERLEVEL9K_MODE=ascii
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    ZDOTDIR=$tmp zsh
  } always {
    cd || true
    rm -rf $tmp
  }
)
```

I get this prompt:

```text
ip 157.230.108.63 | vpn 157.230.108.63  ip 157.230.108.63
```

Does this command work for you? If it doesn't, what is the output of the following command?

```zsh
(
  eval $__p9k_intro
  setopt xtrace
  _p9k_prompt_net_iface_async
)
```

If this command does work, please tell me how to reproduce the issue.

**Comment by gregf** [comment]
Yes that command is showing my IP. As you can see though it's not showing up in my prompt for whatever reason.

![2020-03-25_10-17](https://user-images.githubusercontent.com/980/77546193-e03aae00-6e81-11ea-9891-0d4bba4acd90.png)

As you can see here the lines are uncommented in my prompt file.

![2020-03-25_10-18](https://user-images.githubusercontent.com/980/77546308-111ae300-6e82-11ea-9652-da812b11486c.png)

**Comment by romkatv** [comment]
> Yes that command is showing my IP

All three? The same as in my prompt?

> As you can see though it's not showing up in my prompt for whatever reason.

Please type `typeset -p POWERLEVEL9K_IP_INTERFACE`. Do you have a network interface that matches this regex? If not, `ip` segment won't show anything. You'll need to search for `POWERLEVEL9K_IP_INTERFACE` in `~/.p10k.zsh` and change its value to the network interface you care about.

To figure out why `public_ip` isn't showing, please run the following command and post its output:

```zsh
(
  eval $__p9k_intro
  setopt xtrace
  _p9k_prompt_public_ip_async
)
```

**Comment by gregf** [comment]
I'm a idiot just had to adjust the interface variables. Sorry to waste your time.

**Comment by romkatv** [comment]
No worries. I'm here whenever you have questions/issues.
