### ISSUE TITLE
prompt_char and vi mode

### ISSUE THREAD

**Issue by cridemichel** [romkatv/powerlevel10k#584]
Hi,
I am using the prompt_char but after some recent update it the current vi mode is shown in the right prompt. For example, if I press Esc I get:

![Schermata 2020-03-25 alle 10 39 35](https://user-images.githubusercontent.com/15322138/77522698-eda56780-6e84-11ea-8013-1a77a90828bd.png)

i.e. I do not expect to have "normal" in the right prompt,
thank you very much
Cristiano

**Comment by romkatv** [comment]
If you don't want to see `NORMAL` in right prompt, open `~/.p10k.zsh`, search for `vi_mode` and comment it out.

```zsh
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  ...
  vi_mode                 # vi mode (you don't need this if you've enabled prompt_char)
  ...
)
```

The next time you decide you don't want to see something in your prompt, you can use the same approach.

**Comment by cridemichel** [comment]
ok even if I think that if one uses prompt_char, vi_mode segment
should be commented out by default,

best Cristiano

Cristiano De Michele
cristiano.demichele@gmail.com

**Comment by romkatv** [comment]
Good idea. Fixed in https://github.com/romkatv/powerlevel10k/commit/b80a4254b735bcfba3491d39e4dbd43ed18f8e99.

**Comment by cridemichel** [comment]
ok thank you
