### ISSUE TITLE
"zsh: exit 130" on Ctrl-C

### ISSUE THREAD

**Issue by transferkraM** [romkatv/powerlevel10k#585]
Hi there,

recently Arch added zsh-theme-powerlevel10k which replaced zsh-theme-powerlevel10k-git from AUR. 3 machines, one still has (a quite old) `-git` variant, the others have Arch package version 1.4.0.

Since 1.4.0 pressing `Ctrl-C` writes `zsh: exit 130` at the exact position of the cursor. This breaks the text on the command line. This makes it impossible to copy-paste earlier commands which have been ctrl-c'd. I use that quite often and this is really really annoying to me.

Is there a quick solution to disable that? Didn't find anything at a quick glance.

**Comment by romkatv** [comment]
Can you reproduce it from shell spawned by this command?

```zsh
(
  emulate -L zsh
  setopt no_unset err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd -- $tmp
    cat >.zshrc <<\END
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
POWERLEVEL9K_MODE=ascii
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
END
    ZDOTDIR=$tmp zsh
  } always {
    cd || true
    rm -rf $tmp
  }
)
```

If not, type `source ~/.p10k.zsh` while still in that shell. Can you reproduce the problem now?

**Comment by transferkraM** [comment]
Not reproducable with this command. Cannot really test with ~/.p10k.zsh. My configuration is too old and I've still ~/.purepower in use.

I guess, I really have to update the configuration, run the wizard, and find all the customizations I've done to icons and similar things before coming back to this one :/

Thanks so far!

**Comment by romkatv** [comment]
> Cannot really test with ~/.p10k.zsh. My configuration is too old and I've still ~/.purepower in use.

Try this then:

```zsh
(
  emulate -L zsh
  setopt no_unset err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd -- $tmp
    cat >.zshrc <<\END
source ~/.purepower
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
END
    ZDOTDIR=$tmp zsh
  } always {
    cd || true
    rm -rf $tmp
  }
)
```

If this reproduces the problem, please attach your `~/.purepower`. If it doesn't, there is something relevant in your `~/.zshrc`. Try commenting out parts of `~/.zshrc` one by one and see when the problem disappears.

**Comment by transferkraM** [comment]
Okay. Thank you! I'll try and get back to this one once I know what's wrong.

**Comment by transferkraM** [comment]
Thank you again, found my (stupidity based) issue. Somewhere deep in the config files was a tiny `setopt print_exit_value`, which my old prompt setup seemed to erase by drawing the prompt, or something like that.

**Comment by romkatv** [comment]
Thanks for the update. It might help someone in the future.
