### ISSUE TITLE
double left prompt

### ISSUE THREAD

**Issue by trancef0rmer** [romkatv/powerlevel10k#586]
I am using tilda as a terminal emulator and when i'm opening it i'm getting the left prompt elements doubled on the right side. This happens when there are more then 3 elements on the right. Thanks
![screen](https://i.imgur.com/wp5xHUC.png)

**Comment by romkatv** [comment]
I see that you've closed this issue an hour after opening it. Have you solved this problem? For the benefit of future users bumping into the same problem, could you mention how?

**Comment by trancef0rmer** [comment]
Yeah, sorry. So, the problem I think is in tilda. While starting it in fullscreen mode, it somehow does not calculate the correct width of the screen. I am using Manjaro and I had installed pl9k and pl10k-git. After the last update, I have replaced pl10k-git with pl10k and removed pl9k. That's when the problem started. I think pl10k I have upgraded to is not that tolerant to tilda as previous version I had.  The workaround was to disable "start in fullscreen" option, set the windows zise as 100% x 100% and then manually (f11) make it fullscreen. If you have any other thoughts, please, let me know

**Comment by romkatv** [comment]
Thanks for the details. I don't have any other thoughts.
