### ISSUE TITLE
WSL2 p10k configure certain paramaters restart dialog

### ISSUE THREAD

**Issue by wnklb** [romkatv/powerlevel10k#591]
Hey! Thanks for your work on powerlevel10k. Highly appreciated!

**Issue**: When trying to run `p10k configure`, under certain parameters, it won't save the settings but just run the setup dialog over and over again.

**OS**: Windows10
**Terminal**: Windows Terminal Preview

**Flow**:
1. `y`
2. `y`
3. `y`
4. `y` Classic/Rainbow
5. `1` Unicode
6. `any`
7. `2` 24-hour-format
8. `1` Angled
9. `1` Sharp
10. `1` Flat
11. `2` Two lines
12. `any` 
12. `1` No frame

After that point the dialog just starts over again at `1)`.

Step `8` - `10` produce different results depending on the selected option. I wasn't able to reproduce any consistent behavior across all combinations yet. I'll try to figure out more details.

![powerlevel10k_config_issue](https://user-images.githubusercontent.com/28780710/77811448-97117680-709a-11ea-86ad-62bc91bbda8e.gif)

**Comment by austinmw** [comment]
Same issue

**Comment by romkatv** [comment]
Thanks for the bug report! Should be fixed now. Please update powerlevel10k and retry.

**Comment by wnklb** [comment]
Works like a charm. Thanks a lot!

**Comment by romkatv** [comment]
Thanks for verifying!
