### ISSUE TITLE
Please help find right key in .p10k.zsh

### ISSUE THREAD

**Issue by prankousky** [romkatv/powerlevel10k#592]
Hi everybody,

this is my current prompt
![grafik](https://user-images.githubusercontent.com/11297070/77854611-7efd3c80-71eb-11ea-8335-57c701cc0ec6.png)

Which line do I need to modify in order to get the same color I got on the right (9s) on t he left side (<house icon>~)? This should be `color4`; I ran `for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done`, and `004` is the color that looks most like it.

So I searched for `4` and `004` in my `.p10k.zsh` file, changed those to `046`, which is a completely different color, so I should notice right away. When I source p10k, there is no change. What do I have to modify?

Thank you in advance for your help :)

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and take a look at the top.

```zsh
# The list of segments shown on the left.
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  # =========================[ Line #1 ]=========================
  os_icon                 # os identifier
  dir                     # current directory
  ...
)

# The list of segments shown on the right.
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  # =========================[ Line #1 ]=========================
  status                  # exit code of the last command
  command_execution_time  # duration of the last command
  ...
)
```

It'll pay off if you read this whole part. This way you'll know what you prompt can show. You might even want to uncomment some segments that are disabled by default.

Hopefully you can identify that `~` on the left hand side of your prompt corresponds to this segment:

```zsh
  dir                     # current directory
```

And `3s` on the right is this:

```zsh
command_execution_time  # duration of the last command
```

Now you can search for "current directory" and "duration of the last command" to find parameters that control these segments. Here's what you'll find for "current directory":

```zsh
##################################[ dir: current directory ]##################################
# Current directory background color.
# typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
# Default current directory foreground color.
typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
...
```

If you want to change the background of current directory, you need to change `POWERLEVEL9K_DIR_BACKGROUND` as the comment suggests. This parameter is commented out, so you'll need to uncomment it.

And here's what you'll see when you search for "duration of the last command":

```zsh
###################[ command_execution_time: duration of the last command ]###################
# Execution time color.
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3
...
```

Does this help?

**Comment by prankousky** [comment]
Thank you so much! This works perfectly :)

**Comment by romkatv** [comment]
You are very welcome.
