### ISSUE TITLE
Don't save configuration

### ISSUE THREAD

**Issue by tXambe** [romkatv/powerlevel10k#594]
Hello,

I have installed powerlevel10k in Kali but when I open the terminal always I have what configure everything don't save the change, ¿ someone can help me ?

Thanks and a greeting

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started.

**Comment by tXambe** [comment]
Thanks, I'll follow the link and let you know how it goes.

**Comment by romkatv** [comment]
Timed out waiting.
