### ISSUE TITLE
MesloLGS NF for URxvt

### ISSUE THREAD

**Issue by Syphdias** [romkatv/powerlevel10k#595]
Just starting to try out URxvt and had some trouble changing fonts (not exactly intuitive with Urxvt). I ended up with modifying/adding these lines in my `~/.Xresources` and running `xrdb ~/.Xresources` to "apply" the changes.
```
URxvt*font:                       xft:MesloLGS NF-11
URxvt*letterSpace:                -1
```

I'm not especially comfortable with the config yet which is why this is not a PR.

A few reasons why:
* there is also `URxvt*boldFont`, `URxvt*italicFont`, `URxvt*boldItalicFont` which apparently for me are not necessary. Probably falls back to normal font if it has bold and italic versions.
* Sometimes its a `.` and sometimes `*`. Probably to account for keys like `URxvt.tabbed.font`
* `letterSpace` had to be adjusted for me, not sure if that is always the case. I also read about cases where `letterSpace` had to be `0` in order for symbols to be rendered (properly); wasn't the case with me.

I'll leave it to you if you want to include it in your font install section since it is not as straight forward as clicking through menus and selecting it.

PS: Good way to find out if font string is correct:
```
❯ fc-match 'MesloLGS NF' # correct default font size (12 I think)
MesloLGS NF Regular.ttf: "MesloLGS NF" "Regular"
❯ fc-match 'MesloLGS NF-33' # correct font size 33
MesloLGS NF Regular.ttf: "MesloLGS NF" "Regular"
❯ fc-match 'MesloLGS NF Regular' # wrong
Vera.ttf: "Bitstream Vera Sans" "Roman"
```

**Comment by romkatv** [comment]
Thanks for sharing.

This isn't something I feel comfortable adding to the official docs but hopefully it'll help someone if they search for "URxvt" in issues. It also gives me something to link to in case of questions (and someone to poke for help :P).
