### ISSUE TITLE
VCS status does not use $icons hash

### ISSUE THREAD

**Issue by lordjavac** [romkatv/powerlevel10k#598]
The $icons hash is defined and has icons for VCS statuses such as VCS_UNTRACKED_ICON, but the theme code doesn't seem to use these, but instead has hard-coded values for those indicators. It would be nice if theVCS segments took advantage of those defined icons,which have ASCII fallbacks defined for those scenarios.

I'm not sure why those icons are even defined if they're not used anywhere. I'll try editing my cofig to use the icons and see if I can formulate a patch.

**Comment by romkatv** [comment]
> VCS status does not use $icons hash

It does. Your config probably overrides the whole content of `vcs` segment with `POWERLEVEL9K_VCS_CONTENT_EXPANSION`.

If you want to change the format of Git status, see https://github.com/romkatv/powerlevel10k/#how-do-i-change-the-format-of-git-status.

If you want to restrict prompt to ASCII, run `p10k configure` and select ASCII Character Set.

> I can formulate a patch.

Please don't. It's working as intended.

Please forgive brevity. I'm very busy.

**Comment by lordjavac** [comment]
I think I didn't make myself clear. I don't want the ASCII icons, but they're there anyway. My config is the one generated by `p10k configure`.

I am talking about the status icons for VCS. Untracked files, uncommitted changes, stashes, etc. These are hard-coded to certain characters in the theme configs. They do not use the icons defined in icons.zsh (`$icons[VCS_STASH_ICON]` et al). I only mentioned ASCII as the icons used currently are mostly ASCII (with a couple in unicode), and the $icons hash should gracefully downgrade the icons for users who want/need that.

I am well aware of the ability to change it myself, that is what I'm doing.I thought it might be of use to others. Also, I'd like to not lose my changes if I need to update p10k at some point. It makes sense to me that with the more icons setting, the VCS status indicators should use icons. That would respect people's choices when configuring the system and provide a nicer default for those that want it.

I appreciate that you're busy and I appreciate the quick reply. That is why I offered to make a patch myself.

**Comment by romkatv** [comment]
> That is why I offered to make a patch myself.

Please don't. It's working as intended.
