### ISSUE TITLE
Icons defined and provided by "get_icon_names" aren't usable

### ISSUE THREAD

**Issue by krenor** [romkatv/powerlevel10k#599]
I'm trying to display the branch icon and the branch as well as the commit icon and the commit itself.
Calling `get_icon_names` tells me there's an `POWERLEVEL9K_VCS_COMMIT_ICON` ready to be used. However, it cannot be used and isn't displaying at all. Not this is not a font issue, as you can see in the image bellow that the branch icon does get shown properly.  

<img width="373" alt="Screen Shot 2020-04-01 at 18 24 20" src="https://user-images.githubusercontent.com/13726968/78162779-acdebd00-7447-11ea-9e91-61b55fa42b11.png">

This is the statement inside the `my_git_formatter` function:
```
 res+="${meta}${clean} - ${(g::)POWERLEVEL9K_VCS_COMMIT_ICON} ${VCS_STATUS_COMMIT[1,6]}"
```
I assumed I had to use `${(g::)`, because a few lines above its used like this: `res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}"` 

I've got it working by replicating the icon by using  
`typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='\ue729'` inside the `my_git_formatter` function (haven't tried it outside of it, but I assume it's the same behaviour) but this feels wrong. 
How can I actually access these already defined icons?

**Comment by romkatv** [comment]
> I've got it working by replicating the icon by using
> `typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='\ue729'` inside the `my_git_formatter` function (haven't tried it outside of it, but I assume it's the same behaviour) but this feels wrong.

It's not a good idea to set global variables in `my_git_formatter`. This would be better:

```zsh
res+="${clean}"$'\uE729'
```

> How can I actually access these already defined icons?

You cannot.
