### ISSUE TITLE
No gitstatusd-freebsd-amd64 binary

### ISSUE THREAD

**Issue by alldigital** [romkatv/powerlevel10k#6]
I'm having an issue running powerlevel10k on my FreeBSD laptop:

```zsh
uname -a
FreeBSD ed 12.0-RELEASE-p3 FreeBSD 12.0-RELEASE-p3 GENERIC  amd64
source /tmp/powerlevel10k/powerlevel10k.zsh-theme                                                                                                 
file not found: /tmp/powerlevel10k/gitstatus/bin/gitstatusd-freebsd-amd64
```
Linking  gitstatusd-freebsd-amd64 to gitstatusd-linux-x86_64 gives the following:

```zsh
ELF binary type "3" not known.
gitstatus failed to initialize
```

Linux support is not installed and I'd rather not bother to install it to improve the zsh prompt speed.

**Comment by alldigital** [comment]
Never mind, I've found https://github.com/romkatv/gitstatus and compiled it on FreeBSD using

```zsh
CXX=clang++ LDLIBS=-lgit2 make
```

libgit2-0.27.8 was installed using pkg install.

**Comment by romkatv** [comment]
I'm glad it worked out for you. I'll keep this issue open to add a binary for amd64.

**Comment by romkatv** [comment]
I added a native binary for freebsd-amd64. I would appreciate if you could check whether it works for you. To verify, use powerlevel10k without any extra steps (like building gitstatusd yourself or overriding GITSTATUS_DAEMON).

**Comment by gregf** [comment]
Thank you @alldigital i learned from this being a FreeBSD user myself.

**Comment by romkatv** [comment]
So, does the new binary I built works? I built it in a VM (Virtual Box) and it seems to work fine there, but I don't have a real FreeBSD instance to try it. If you can confirm it works, I'll be able to release FreeBSD binaries on a regular basis.

**Comment by gregf** [comment]
@romkatv yes it is working fine now. Much easier to get installed with just using zplug. Thank you!

**Comment by romkatv** [comment]
That's great! Closing this issue.
