### ISSUE TITLE
Use powerlevel10k to replace powerlevel9k, but the prompt is invalid?

### ISSUE THREAD

**Issue by Leviathan1995** [romkatv/powerlevel10k#60]
I add this line in `.zshrc`:
```
zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme
```
then
```
source ~/.zshrc
```
but the prompt is invalid?

**Comment by romkatv** [comment]
> I add this line in `.zshrc`:

Did you call `zplug check || zplug instal` after it?

> then `source ~/.zshrc`

Please restart zsh instead. Many things break if you `source ~/.zshrc` manually.

> but the prompt is invalid?

Invalid how?

**Comment by Leviathan1995** [comment]
@romkatv Yes, I already install `romkatv/powerlevel10k` by zplug, but the promote configuration is not take effect.

**Comment by romkatv** [comment]
There is really nothing special about using powerlevel10k with zplug. If you know how to use _any_ external theme, you can also use powerlevel10k.

Could you post the content of your `~/.zshrc`?

What do you mean by "the prompt configuration is not take effect"? Could you post a screenshot of how your prompt looks like after you type `zsh`?

**Comment by Leviathan1995** [comment]
It fixed! Thank you!

**Comment by romkatv** [comment]
> It fixed! Thank you!

Great! Would you mind sharing the solution for the benefit of future readers?

**Comment by romkatv** [comment]
Thanks for the explanation. That makes sense.

Is powerlevel10k faster than powerlevel9k for you? Is it fast enough without overriding `POWERLEVEL9K_VCS_GIT_HOOKS`?

**Comment by Leviathan1995** [comment]
I think it is fast than powerlevel9k in my intuition :)

Roman Perepelitsa <notifications@github.com> 于2019年4月24日周三 下午4:30写道：
