### ISSUE TITLE
 How to change rainbow style git status prompt color？

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#600]
I did not find the corresponding configuration in the rainbow style

![Screenshot_20200402_113547_com termux](https://user-images.githubusercontent.com/61009000/78208527-2e316080-74d7-11ea-9135-0c262a104d56.jpg)
![Screenshot_20200402_113134_com termux](https://user-images.githubusercontent.com/61009000/78208533-312c5100-74d7-11ea-8d4e-0e8f6a671e04.jpg)

**Comment by romkatv** [comment]
I don't understand the question. Please read the docs and experiment.

**Comment by strider29** [comment]
@romkatv the github prompt always has green colour regardless of modified files being present

**Comment by romkatv** [comment]
This is controlled by `POWERLEVEL9K_VCS_CLEAN_BACKGROUND`. You need to uncomment this parameter in `~/.p10k.zsh` and change its value.

**Comment by strider29** [comment]
I had already tried playing with those parameters, they don't seem to have any effect on the colours of the prompt

**Comment by romkatv** [comment]
What's the output of `typeset -p POWERLEVEL9K_VCS_CLEAN_BACKGROUND`?
