### ISSUE TITLE
Heads and Tails misaligned with font "MesloLGS NF"

### ISSUE THREAD

**Issue by panchalkalpesh** [romkatv/powerlevel10k#602]
## Description: 
Found misalignment of heads and tails when switching to the font "MesloLGS NF".
After fresh installing the theme and required dependencies, I ran: 

```
p10k configure
```

### Font: MesloLGS NF
![Screenshot 2020-04-03 at 1 23 37 AM](https://user-images.githubusercontent.com/1808686/78327594-417e1380-754b-11ea-892a-8c00c90271ec.png)

### Font: Hack NF
![Screenshot 2020-04-03 at 1 23 16 AM](https://user-images.githubusercontent.com/1808686/78327831-bf421f00-754b-11ea-9ddf-4de98c56b45e.png)

_P.S: Checked other similar issues but I think this is different._

**Comment by romkatv** [comment]
You'll get those gaps if you provide incorrect answer to this question:

![image](https://user-images.githubusercontent.com/1282067/78328209-ebc35e80-757e-11ea-8f2b-e155b386d5b3.png)

When using MesloLGS NF, the icons do fit between the crosses, so the correct answer is **y**.

**Comment by panchalkalpesh** [comment]
Thanks @romkatv for quick revert! 
This seems to have fixed the alignment. 

![Screenshot 2020-04-03 at 2 01 52 AM](https://user-images.githubusercontent.com/1808686/78329310-55c40f80-754f-11ea-8f74-96335bfd382c.png)

**Comment by romkatv** [comment]
Yep. In addition, superfluous spaces after some icons are now gone. For example, on your first screenshot you can see that there is too much empty space after the ruby icon.
