### ISSUE TITLE
Prompt rerenders on i3 horizontal split

### ISSUE THREAD

**Issue by nstylo** [romkatv/powerlevel10k#605]
I installed p10k yesterday on my system and I am very pleased with the ease of setup and its  _blazingly_ fast speed.

Though I am experiencing weird prompt re-rendering my system using [i3 window manager](https://github.com/i3/i3). On a horizontal split the prompt re-renders, as well as on full screen mode. I am using [kitty](https://github.com/kovidgoyal/kitty) as terminal emulator, but I tested on urxvt and alacritty as well.

 A couple of horizontal splits:
![image](https://user-images.githubusercontent.com/45883614/78399319-f91b3000-75f4-11ea-9d63-33c934fa9ab9.png)

Horizontal split, full screen triggered multiple times creates this funny shape:
![image](https://user-images.githubusercontent.com/45883614/78399517-51523200-75f5-11ea-8486-4d79e866c778.png)

Before I installed p10k I used [starship](https://starship.rs/), and there was no bug.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#horrific-mess-when-resizing-terminal-window.
