### ISSUE TITLE
ZSH_CUSTOM variable

### ISSUE THREAD

**Issue by hungtran84** [romkatv/powerlevel10k#606]
Hi,
I just follow the instruction and cannot see where the $ZSH_CUSTOME set to so that i cannot setup Oh My Zsh as expected

Should i have to explicitly set it in ~/.zshrc?

**Comment by romkatv** [comment]
`ZSH_CUSTOM` is set by Oh My Zsh. See https://github.com/ohmyzsh/ohmyzsh/blob/master/oh-my-zsh.sh. If you don't have it in the interactive shell, it means that shell isn't using Oh My Zsh.

**Comment by romkatv** [comment]
Have you managed to solve this problem?

**Comment by hungtran84** [comment]
Thank you very much. It worked now
