### ISSUE TITLE
Making "bubbles"

### ISSUE THREAD

**Issue by MusicOnline** [romkatv/powerlevel10k#607]
I think the top-left portion of the following image would be a good example of the style I would like to achieve.
![image](https://raw.githubusercontent.com/paracorde/dots/master/screenshot.png)

I've been looking through the config and issues but could not find a way to do so.
I have tried using the left and right separators options but it will definitely not work with colors.
I believe as of now p10k does not support this through config (aka editing the functions may be needed).

Is there a way to accomplish this? If not, will p10k consider adding such an option?
(Also, I don't know a better title.)

**Comment by romkatv** [comment]
You can get pretty close.

1. Run `p10k configure` and select Classic style with the following options:
   1.1 Prompt Separators: Round.
   1.2 Prompt Heads: Round.
   1.3 Prompt Tails: Round.
   1.4 Prompt Height: One line.
   1.5 Prompt Spacing: Sparse.
   1.6 Icons: Few icons.
   1.7 Prompt Flow: Concise.
   1.8 Enable Transient Prompt: No.
2. Edit `~/.p10k.zsh` like this:
```diff
+  # No surrounding whitespace.
+  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
   # Separator between same-color segments on the left.
-  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%244F\uE0B5'
+  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%k%F{$POWERLEVEL9K_BACKGROUND}\uE0B4%k \uE0B6"
   # Separator between same-color segments on the right.
-  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%244F\uE0B7'
+  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%k%F{$POWERLEVEL9K_BACKGROUND}\uE0B4%k \uE0B6"
   # Separator between different-color segments on the left.
   typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4'
```

When running `p10k configure`, the only important options are Classic style and round heads and tail. I've listed other options simply to match your screenshot. You can try other variations.

**Comment by MusicOnline** [comment]
Thanks, that solution works for Classic. Is it possible for Rainbow?

**Comment by romkatv** [comment]
No, it's not currently possible to achieve this effect for Rainbow style.

**Comment by romkatv** [comment]
On second though, it might be possible. Give me a second.

**Comment by romkatv** [comment]
This works:

```zsh
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_LEFT_WHITESPACE='%S%F{#171A1B}\uE0B6%s'
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_RIGHT_WHITESPACE='%S%F{#171A1B}\uE0B4%s'

  # Separator between same-color segments on the left.
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='%k '
  # Separator between same-color segments on the right.
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='%k '
  # Separator between different-color segments on the left.
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='%k '
  # Separator between different-color segments on the right.
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='%k '
  # The right end of left prompt.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
  # The left end of right prompt.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  # The left end of left prompt.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  # The right end of right prompt.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=
```

However, you'll need to replace `#171A1B` on the first two lines with the background color used by your terminal. You can probably find it in the terminal's settings somwhere.

**Comment by MusicOnline** [comment]
Thanks, that works! It would be interesting to see if p10k could support these type of situations in Rainbow style without the terminal background color hack.

**Comment by ecosse3** [comment]
Is it possible to achieve the same in 2022? I don't have such options when running `p10k configure`:

> 1.1 Prompt Separators: Round.
> 1.2 Prompt Heads: Round.
> 1.3 Prompt Tails: Round.

**Comment by romkatv** [comment]
> Is it possible to achieve the same in 2022?

Yes.

> I don't have such options when running `p10k configure`:
> 
> > 1.1 Prompt Separators: Round.
> > 1.2 Prompt Heads: Round.
> > 1.3 Prompt Tails: Round.

See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by ecosse3** [comment]
@romkatv I have kitty term and 256 color support. I was able to make rounded background work as you suggested in previous comment. Thanks!

> However, you'll need to replace `#171A1B` on the first two lines with the background color used by your terminal.

Is it possible to make it semi-transparent/transparent? I'm using opacity in my terminal (kitty) and it shows a bit noticeable background anyway:

![image](https://user-images.githubusercontent.com/17691791/152350351-e8364779-5b03-4096-93f3-82d871e3f1bf.png)
