### ISSUE TITLE
Instant prompt slows down over time

### ISSUE THREAD

**Issue by cptpcrd** [romkatv/powerlevel10k#608]
I've noticed a strange phenomenon: Instant prompt slows down over time, up to the point of taking half a second or more to start. (There's really no other way to describe this; I think it's self-explanatory.)

I've noticed this on several Linux machines. This isn't a distro-specific issue, either -- I've reproduced it on Arch, Ubuntu (both 18.04 and 20.04 beta), and Raspbian on a Raspberry Pi. I can't believe this is specific to my setup, and I'm surprised that it seems nobody else has run into this. (Then again, I open a lot of terminals, which is probably exacerbating the issue.)

### Cause

The first thing I discovered was that a blind `rm -rf ~/.cache/p10k-*` speeds instant prompt up again (after loading Zsh once to let Powerlevel10k regenerate the cache files). I considered running this periodically, but it's obviously not a good solution.

Then I poked around a little more. It appears that that the `prompt-*` files in `~/.cache/p10k-<user>` are never overwritten, merely appended to. Over time, they slowly increase in size as you launch more and more shells. I'm guessing that the time it takes Powerlevel10k to read them is what slows things down so much.

### Reproducing

On Linux, if you have [`firejail`](https://github.com/netblue30/firejail) installed, you *should* be able reproduce this in a sandbox with these instructions:
1. Run `firejail --quiet --ignore=read-only --ignore=whitelist --overlay-tmpfs --private` to launch a shell inside a sandbox with a `tmpfs` mounted on the homedir.
2. Run `git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k && echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>! ~/.zshrc` (from the manual installation instructions in the README) to install Powerlevel 10k.
3. Run `exec zsh` to launch a new shell that will read the new `~/.zshrc`.
4. Configure Powerlevel10k through the UI. For the record, I inputted the following: `ynn311111111n3y` (picking the options that most closely match my slightly weird setup)
5. Run `ls -lah ~/.cache/p10k-$USER/prompt-*` to see the size of the `prompt-*` file(s).
6. Launch a new shell with `zsh`.
7. Re-run `ls -lah ~/.cache/p10k-$USER/prompt-*` to see how it has changed from step 5.

Expected behavior: The size of the `prompt-*` file(s) remains roughly the same.

Observed behavior: The size of the file for a given directory increases by ~13-14K for every new shell launched in that directory.

### Potential patch

This change *appears* to fix the issue.

```
--- a/internal/p10k.zsh
+++ b/internal/p10k.zsh
@@ -5868,7 +5868,7 @@ _p9k_dump_instant_prompt() {
   fi
 
   local -i fd
-  sysopen -a -m 600 -o creat -u fd -- $tmp || return
+  sysopen -a -m 600 -o creat,trunc -u fd -- $tmp || return
   {
     {
       print -rnu $fd -- $'\x1e'$_p9k__instant_prompt_sig$'\x1f'${(pj:\x1f:)_p9k_t}$'\x1f'$_p9k__instant_prompt || return
```

Confession: I'm decent at shell scripting, but nowhere near good enough to understand what's going on in Powerlevel10k's internals. I'm doing this rather blindly and have no idea whether this will mess things up. Hence, I'm not opening a PR (yet).

**Comment by romkatv** [comment]
Thanks a lot of the super high-quality bug report! Fixed.

**Comment by romkatv** [comment]
I am appropriately impressed with your debugging this problem. You've basically done all the work for me.

**Comment by cptpcrd** [comment]
> I am appropriately impressed with your debugging this problem. You've basically done all the work for me.

Thanks. :-) I usually like to figure out what's going on myself before I submit bug reports.
