### ISSUE TITLE
Issue with ZSH versions < 5.3

### ISSUE THREAD

**Issue by bauerj** [romkatv/powerlevel10k#61]
When sourcing `.zshrc` on some servers, I get 

    /root/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme:25: unknown condition: -v

Apparently, `-v` was only added in ZSH 5.3.

**Comment by romkatv** [comment]
What's the output of `echo $ZSH_VERSION` on this machine?

**Comment by bauerj** [comment]
shenzhou# echo $ZSH_VERSION 
    5.2

**Comment by romkatv** [comment]
> Since there are some other places where `-v` is used, I assume the minimum supported version should be raised to 5.3.

Indeed. I was under the impression that `-v` was added in 5.2 but I see in the zsh release notes that it only appeared in 5.3.

There are few users of ancient zsh, so this didn't come up (you are very brave to use complex software released 3.5 years ago). I'll see if it's feasible to port powerlevel10k and gitstatus to zsh 5.2. Will update this issue.

**Comment by bauerj** [comment]
> you are very brave to use complex software released 3.5 years ago

I'm sure some banks use software developed more than 30 years ago 😊

However, I will update my remaining servers to the latest version of ZSH.

Also: Thanks for powerlevel10k! The speedup is awesome.

**Comment by romkatv** [comment]
I've made a few changes and now Powerlevel10k works on ZSH 5.1. I cannot vouch for everything working but at least [Pure Power](https://github.com/romkatv/dotfiles-public/blob/master/.purepower) works.
