### ISSUE TITLE
_p9k_dump_state:zf_mv:22: {...tmp.$ID.zwc} permission denied

### ISSUE THREAD

**Issue by snoopotic** [romkatv/powerlevel10k#610]
Hi,

using wsl somehow now I get thiss error with the interactive shell:
```
_p9k_dump_state:zf_mv:22: $HOME/.cache/p10k-dump-$USER.zsh.tmp.1476.zwc: permission denied
```
Where `$HOME` and `$USER` are variables I replaced here manually.

The left part shows me there is possibly a "mv" transaction and thus... I went to:
`$HOME/.cache`
and found the file:
`p10k-dump-$USER.zsh.zwc`
with filemode: 0444
I manually changed the filemode to 0644 but after few commands I get the error back and find the file got mode 0444 back. 
I think this shouldn't be if the file gets overwritten several times.

Was on commit: dfc98ad

**Comment by romkatv** [comment]
Could you give me more details? What are the permissions on `$HOME/.cache`? Is this rootfs or ntfs?

Could you try creating a couple of files in that directory with permissions 444 and then moving them with `zf_mv`? Try to reproduce the error this way.

**Comment by romkatv** [comment]
I've added `>/dev/null` in there. If you figure out what's actually going on, please do let me know. (`zf_mv` is not supposed to fail if the source and/or destination files are non-writable. It only needs the directory to be writable.)

**Comment by snoopotic** [comment]
Hi thank you. Sorry for the delay. Did not expect you respond that quick:

Well, after further testing it seems an issue with "drvfs" - the fstype for WSL (windows subsystem for lnux) to mount windows (ntfs) partitions into the subsystem. I am using win 1903 maybe it's fixed in 1909!?

On drvfs mounted filesystems also GNU "mv" is not able to overwrite Files in readonly-mode (0444):
```
> pwd
/c/Users/snoopotic/test
> ll
total 0
-r--r--r-- 1 snoopotic snoopotic   0 Apr  5 07:58 from
-r--r--r-- 1 snoopotic snoopotic   5 Apr  5 08:22 to
> mv -v from to
mv: replace 'to', overriding mode 0444 (r--r--r--)? y
mv: cannot move 'from' to 'to': Permission denied
```

I went into a rootfs folder of wsl and there it works as expected. I switched the home-dir in wsl from other issues to the windows-partition. usualy this works good. Dunno why this moans now. Had no issues long time :/

Well, on one hand it's also to be expected that 444-mode-files cannot be overwritten, on the other hand it's still possible in usual linux filesystems if you're the owner and force it.... hmm.

I also found out that "zcompile" creates the $tmp.zwc file in mode 444. Regarding the author of zcompile it is supposed to be as this file is only for RO.
I will find out if the issue of drvfs is known and will be fixed. But until that maybe a workaround would be to add (time consuming) "chmod 644 $tmp.zwc" between zcompile and zf_mv?

You current Workaround really just suppresses the error and the zwc-file does not get recompiled. What happens if this get's older and older?

Thank you.

**Comment by romkatv** [comment]
> Well, on one hand it's also to be expected that 444-mode-files cannot be overwritten

If a file is not writable, it means you don't have permissions to change it. Deleting a file isn't a modification of the file, it's a modification of the directory. `mv` doesn't change files, it changes directories.

That's what POSIX says and zsh is a software that assumes POSIX-compliant OS.

> You current Workaround really just suppresses the error and the zwc-file does not get recompiled.

Correct. It'll be a little bit slower.

> What happens if this get's older and older?

Nothing. It'll work fine, just slower.

**Comment by snoopotic** [comment]
I see. 
I‘ll do more research and get back if there is a suitable solution.
Thank you very much for your effort! :)
