### ISSUE TITLE
Sourcing zshrc messes with zsh-autosuggestions colors

### ISSUE THREAD

**Issue by FreddieOliveira** [romkatv/powerlevel10k#611]
Didn't further investigate why this happens, but when I open a new prompt things works correctly as shown bellow, but if I source the `.zshrc` file then the zsh-autosuggestions plugin color changes from its default dark gray to my ordinary font color

![Screenshot_2020-04-04-18-08-00-768_com termux](https://user-images.githubusercontent.com/9597536/78461447-5f5c8d00-769f-11ea-93bc-6b77ca07a314.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#weird-things-happen-after-typing-source-zshrc

**Comment by Unequaled804** [comment]
Same issue here. So we have to use `soure ~/.zshrc` as little as possible, right?

**Comment by romkatv** [comment]
> Same issue here. So we have to use `soure ~/.zshrc` as little as possible, right?

You should never execute `source ~/.zshrc`. Use `exec zsh` instead. It's even less typing.

**Comment by Unequaled804** [comment]
Got it, thx!
