### ISSUE TITLE
[feature] command configuration

### ISSUE THREAD

**Issue by IainVM** [romkatv/powerlevel10k#613]
I use tools like Ansible to provision servers to my liking installing zsh, antibody and any other CLI tools I usually like to have. However, the only way to configure my Powerlevel10k configuration seems to be saving the generated `~/p10k.zsh` file and provisioning that to all the servers. It would be nice if there was an way to set the configuration options without using the interactive wizard. 

Options could be either exposing commands for the individual configuration options 
`p10k configure prompt-style lean`

Or 

Allowing a settings file to be accepted like
`p10k configure settings.yml`

settings.yml
```YAML
promt-style: lean
character-set: unicode
```

This would also remove the need to go through the entire wizard to change a single option.

**Comment by romkatv** [comment]
Powerlevel10k guarantees backward compatibility for all `POWERLEVEL9K_*` parameters. It does not, however, guarantee any kind of backward compatibility for the options you see in `p10k configure`. If there was `p10k configure prompt-style lean`, it could stop working or could do something completely different once you updated powerlevel10k.

> the only way to configure my Powerlevel10k configuration seems to be saving the generated `~/p10k.zsh`

Yes. This is the way. It works great. It ensures that you get the same prompt with any version of powerlevel10k. It also allows you to customize config by editing `~/p10k.zsh`. For example, there are several prompt segments that are disabled by default in configs generated by `p10k configure`. You might want to uncomment them.

I also highly recommend saving `~/.p10k.zsh` the same way you save `~/.zshrc` (perhaps in a git repository).
