### ISSUE TITLE
Configuration wizard doesn't trigger on the first run

### ISSUE THREAD

**Issue by dspp779** [romkatv/powerlevel10k#615]
Hi,

It seems that the configuration wizard doesn't trigger on the first run.
But it works days ago. 🤔

I then looked up the commits these days and found this one related.
https://github.com/romkatv/powerlevel10k/commit/fda14e93d2cbe67591156678983176340f05410b#diff-21234a8c0b8c7f9b8d29cf3d2c4e93acR6303

Revert the commit and it works!
Can you help me fix the problem?

**Comment by romkatv** [comment]
Thanks a lot for the report! Fixed.
