### ISSUE TITLE
POWERLEVEL9K_DIR_PATH_SEPARATOR not working

### ISSUE THREAD

**Issue by lestard** [romkatv/powerlevel10k#616]
I'm switching from powerlevel9k but can't get the POWERLEVEL9K_DIR_PATH_SEPARATOR to work. I'm using the configuration from the powerlevel9k page:

```
POWERLEVEL9K_DIR_PATH_SEPARATOR="%F{black} $(print_icon 'LEFT_SUBSEGMENT_SEPARATOR') %F{black}"
```

But there is still the slash as path separator.

**Comment by romkatv** [comment]
Try this:

```zsh
POWERLEVEL9K_DIR_PATH_SEPARATOR='%F{black} \uE0B0  '
```

You might also find `p10k configure` helpful. If you find it satisfying, try opening `~/.p10k.zsh` and adding these parameters:

```
typeset -g POWERLEVEL9K_DIR_PATH_SEPARATOR=' \uE0B1 '
typeset -g POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
```

**Comment by lestard** [comment]
Thanks for the fast reply.
The first command didn't work but adding the two `typeset...` lines to `.p10k.zsh` did work. 
I was already using `p10k configure` and now it looks as expected. Thank you very much!

**Comment by romkatv** [comment]
Great! Closing the issue.
