### ISSUE TITLE
Instant prompt causes ZSH to crash

### ISSUE THREAD

**Issue by malammar** [romkatv/powerlevel10k#617]
I'm on Ubuntu 18.04 and using ZSH/Tmux with Powerlevel10k  and instant prompt enabled.

Launching the gnome-terminal brings up the terminal for half a second and then crashes with no error in either the terminal or in /var/log.

I narrowed down the crash by commenting out these lines in my `.zshrc`:

```
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi
```

**Comment by romkatv** [comment]
Ouch! That sucks. Please open a bug against the program that crashes.

**Comment by rationalthinker1** [comment]
I have the same problem. When I removed the line where tmux to load, it's fine, but with tmux, it crashes.

**Comment by romkatv** [comment]
@rationalthinker1 Ouch! That sucks. Please open a bug against the program that crashes.

**Comment by romkatv** [comment]
@jaseemabid Please open a bug against the program that crashes.
