### ISSUE TITLE
powerlevel10k.zsh-theme installed in wrong palce?

### ISSUE THREAD

**Issue by BHamlen** [romkatv/powerlevel10k#622]
I'm using iterm2 and installed powerlevel10k using homebrew.

Went through the configuration wizard last night and was using powerlevel10k with iterm2 just fine. 

This morning, though, when I open iterm2 I get the "console output during configuration" dialog.
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/32946606/79001679-88a07180-7b14-11ea-8379-f47cfa7449da.png">

Here's that line 106 in oh-my-zsh.sh it's comlaining about
<img width="709" alt="image" src="https://user-images.githubusercontent.com/32946606/79000560-79202900-7b12-11ea-9436-ce04bff24387.png">

my zshrc shows at the powerlevel10k.zsh-theme is actually installed at
/usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
<img width="709" alt="image" src="https://user-images.githubusercontent.com/32946606/79000585-86d5ae80-7b12-11ea-8840-3a6ed973966f.png">

I copied powerlevel10k.zsh-theme to the ~/.oh-my-zsh/themes. This gives me
<img width="915" alt="image" src="https://user-images.githubusercontent.com/32946606/79001441-1c257280-7b14-11ea-9702-9c49d3ba2654.png">

removed powerlevel10k.zsh-theme from ~/.oh-my-zsh/themes. Closed and reopened iterm, gives me
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/32946606/79001620-66a6ef00-7b14-11ea-8cc0-282a52821445.png">

Then closing and reopening again bring me back to where we started
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/32946606/79002212-973b5880-7b15-11ea-8317-3a1bf1c7b2ab.png">

Any ideas of how to move the powerlevel10k files to the right place? Seems like homebrew just installed them in a different place than oh-my-zsh was expecting? I'm curious also about how the theme is loaded successfully if I'm getting these error messages that the powerlevel10k.zsh-theme file is not found.

Apologies if this is the wrong place to put this issue, newbiw to Git so still learning the norms.

**Comment by romkatv** [comment]
There are several [installation options](https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation) for powerlevel10k. You need to follow exactly one. If you want to install powerlevel10k using Homebrew, follow instructions for installing powerlevel10k with Homebrew. If you want to install powerlevel10k using oh my zsh, follow instructions for installing powerlevel10k with oh my zsh. Just pick one.

**Comment by BHamlen** [comment]
> There are several [installation options](https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation) for powerlevel10k. You need to follow exactly one. If you want to install powerlevel10k using Homebrew, follow instructions for installing powerlevel10k with Homebrew. If you want to install powerlevel10k using oh my zsh, follow instructions for installing powerlevel10k with oh my zsh. Just pick one.

Ah, my apologies. I misunderstood, thought that powerlevel10k was simply a theme for oh-my-zsh. Will uninstall stuff and install properly. Thanks for the fast reply!

**Comment by romkatv** [comment]
You can use it as a theme for oh my zsh.

You don't need to uninstall anything. Simply remove `ZSH_THEME` parameter from zshrc.

**Comment by agitrubard** [comment]
> You can use it as a theme for oh my zsh.
> 
> You don't need to uninstall anything. Simply remove `ZSH_THEME` parameter from zshrc.

That's Worked! 

This issue is second item in part of Oh My Zsh Installing File
https://github.com/romkatv/powerlevel10k#oh-my-zsh
