### ISSUE TITLE
Any way to anchor prompt to bottom of terminal?

### ISSUE THREAD

**Issue by lyiriyah** [romkatv/powerlevel10k#623]
I would like to anchor the prompt to the bottom of the terminal. Like [here](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/performance.gif), where the prompt is right at the bottom of the screen. Any way to do that?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/563.
