### ISSUE TITLE
ZLE_RPROMPT_INDENT=0 not working

### ISSUE THREAD

**Issue by alexypdu** [romkatv/powerlevel10k#624]
Environments

* OS: macOS 15.4
* Terminal: iTerm2 3.3.9
* Shell: zsh 5.8
* Zsh Framework: Oh My Zsh

I've seen the [troubleshooting](https://github.com/romkatv/powerlevel10k#extra-space-without-background-on-the-right-side-of-right-prompt) and added `ZLE_RPROMPT_INDENT=0` to `~/.zshrc` but it's not working.

**Comment by romkatv** [comment]
Please try copy-pasting that parameter to avoid typos.

**Comment by alexypdu** [comment]
<img width="894" alt="Screen Shot 2020-04-12 at 22 05 18" src="https://user-images.githubusercontent.com/28721952/79070628-b8fd3100-7d09-11ea-9fce-c140989381ee.png">

It's part of my `~/.zshrc` and I don't see any typos here.

**Comment by romkatv** [comment]
Thanks for removing the typo from the issue description.

Please post the output of the following command and a screenshot of your terminal.

```zsh
() {
  emulate -L zsh
  typeset -pm 'ZLE_RPROMPT_INDENT|POWERLEVEL9K_*|ZSH_VERSION'
  uname -ms
}
```

**Comment by alexypdu** [comment]
It seems like iterm would keep some space at the end of a line in the _full-screen_ mode. Toggle off the full-screen mode and then it works as intended. Thanks for your kind help!

**Comment by romkatv** [comment]
My pleasure.

Note that `ZLE_RPROMPT_INDENT` is a core zsh parameter. It's not specific to powerlevel10k. You can see it in action by starting Zsh without user configs:

```zsh
PS1='> ' RPS1='<' zsh -f
```

You can now type `ZLE_RPROMPT_INDENT=0`, `ZLE_RPROMPT_INDENT=1` and `ZLE_RPROMPT_INDENT=2` to see how it looks in your terminal.

**Comment by alexypdu** [comment]
Yes I just realized it's not related to specific powerlevel10k functions. Still appreciate your assistance!
