### ISSUE TITLE
displaying prompt always in the bottom

### ISSUE THREAD

**Issue by YusifKhalilov** [romkatv/powerlevel10k#627]
HI. Thanks for a nice customizable and powerful framework. In your documentation in some of the animations, it shows your prompt display always in the bottom of the terminal. I can't find a way to do this. Please help!

![](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/performance.gif)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/563.
