### ISSUE TITLE
Triangle not showing in Terminal or VSCode on Mac

### ISSUE THREAD

**Issue by corydorning** [romkatv/powerlevel10k#628]
As the subject says...the 'white' triangle does not show up. Contents of `.zshrc`:

```
source /Users/e022145/Web/www-local/.tools/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

**Comment by romkatv** [comment]
What white triangle?

**Comment by corydorning** [comment]
The one seen here:
https://github.com/romkatv/powerlevel10k#sub-pixel-imperfections-around-powerline-symbols

**Comment by romkatv** [comment]
Do you expect to see a white triangle? If so, why?

**Comment by corydorning** [comment]
I’m not sure what you mean. Isn’t there supposed to be a > at the end of the branch? Mine is just a rectangle

**Comment by romkatv** [comment]
> I’m not sure what you mean. Isn’t there supposed to be a > at the end of the branch?

Depends on your config. Mine looks like this:

![image](https://user-images.githubusercontent.com/1282067/79142306-94619180-7dbb-11ea-9daa-1c47fe2113ad.png)

There is no triangle.

**Comment by corydorning** [comment]
well...in p10k configure i don't see the following:
- diamond
- either lock
- i chose 'rainbow'
- flat

And every example shows the > at the end. Maybe the better question is how can i get the arrow when using rainbow? :)

**Comment by romkatv** [comment]
That's indeed a better question. See the answer: https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by corydorning** [comment]
- zsh version 5.7.1
- `print -P '%F{#ff0000}red%f'` is red
- `print $terminfo[colors]` says 256
- `locale -a` does have utf-8
- I've installed the fonts and setup my terminal to preferences to use them, however the icons do not display correctly
- `print ${COLUMNS}x${LINES}` is 215x30
- I've never use 9k

**Comment by corydorning** [comment]
Just looks like i'm missing the `U+E0B0` (a right-pointing triangle)

**Comment by romkatv** [comment]
> * I've installed the fonts and setup my terminal to preferences to use them, however the icons do not display correctly

Well, your terminal isn't using the font. If it were, you'd see the glyphs.

If you cannot figure out how to change font in the terminal, you might want to ask on the forum dedicated to your terminal.

**Comment by corydorning** [comment]
am i missing something?
https://ufile.io/4dgi1k52

**Comment by romkatv** [comment]
Dunno. I've never used vscode on macos. Most problems with the vscode terminal can be solved by replacing the integrated terminal with iterm2. I don't think there is a reason to ever used the integrated terminal. It's buggy and slow.

Either way, the problem you are facing is not specific to powerlevel10k. You need to figure out how to configure your terminal to use the font of your choice.

**Comment by corydorning** [comment]
There is the Mac terminal. Isn’t working there either.
