### ISSUE TITLE
Variables in segment are not changed when reset-prompting in ZLE

### ISSUE THREAD

**Issue by yuki-ycino** [romkatv/powerlevel10k#630]
I use the https://github.com/yukiycino-dotfiles/zsh-show-buffer-stack plugin to show the stack of commands in RPROMPT.

I am running reset-prompt in show-buffer-stack, but the COMMAND_BUFFER_STACK in the segment is not reflected.
If multiple stacks are created and the command is executed, the second and subsequent stacks will be displayed.

Is there a way to apply a variable to a segment immediately after executing show-buffer-stack?

```
  function prompt_show_buffer_stack() {
    p10k segment -f white -t $COMMAND_BUFFER_STACK
  }
```

**Comment by romkatv** [comment]
Try this:

```zsh
function prompt_show_buffer_stack() {
  p10k segment -f white -e -t '$COMMAND_BUFFER_STACK'
}
```

You might also want to rename `prompt_show_buffer_stack` to `prompt_my_show_buffer_stack`. This will protect your config from being broken by future versions of powerlevel10k (in the future, powerlevel10k might implement its own `show_buffer_stack` prompt segment but it won't implement `my_show_buffer_stack`).

**Comment by yuki-ycino** [comment]
It's working.
Thank you!
