### ISSUE TITLE
mafredri/zsh-async - widgets can only be called when ZLE is active

### ISSUE THREAD

**Issue by schmas** [romkatv/powerlevel10k#631]
Hi,

A few days ago I followed the explanation on the #609, and manage to get it working my similar element.

But I just updated everything today and this error started to appear:
```
_yadm_p10k_refresh:zle:2: widgets can only be called when ZLE is active
```

I have this script, that I call it at `.zshrc`:
```bash
#!/usr/bin/env zsh

async_init

# Initialize a new worker (with notify option)
async_start_worker yadm_class_name -n

# Create a callback function to process results
function _yadm_p10k_refresh() {
  yadm_class=$3
  zle reset-prompt
  zle -R
}

# Register callback function for the workers completed jobs
async_register_callback yadm_class_name _yadm_p10k_refresh
```
and this is my prompt_yadm_class_p10k function:
```bash
function _yadm_get_class() {
    local __yadm_class=$(yadm config --get local.class)
    echo "${__yadm_class}"
}

function prompt_yadm_class_p10k() {
    async_job yadm_class_name _yadm_get_class
    p10k segment -f 241 -e -c '$yadm_class' -t '(${yadm_class})'
}

source ~/.p10k.zsh;
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=yadm_class_p10k; 
_p9k_precmd
```

It was working before updating mafredri/zsh-async and powerlevel10k today.

Could you help me?

Thanks

**Comment by romkatv** [comment]
> ```
> _yadm_p10k_refresh:zle:2: widgets can only be called when ZLE is active
> ```

`_yadm_p10k_refresh` calls `zle reset-prompt`, which can only be called when ZLE is active. `_yadm_p10k_refresh` is called by mafredri/zsh-async. Thus, according to the error message, mafredri/zsh-async calls `_yadm_p10k_refresh` when ZLE is not active.

Note that this observation doesn't refer to powerlevel10k in any way.

- If you don't expect mafredri/zsh-async to call `_yadm_p10k_refresh` when ZLE is not active, open a bug against mafredri/zsh-async.
- If you do expect mafredri/zsh-async to call `_yadm_p10k_refresh` when ZLE is not active, modify `_yadm_p10k_refresh` to work correctly in such cases.

> ```
> _p9k_precmd
> ```

Functions and parameters from powerlevel10k whose names start with underscore (`_`) are internal. If you use them, things can break when you update powerlevel10k. Your prompt can start showing incorrect information, zsh may fail to start, commands you type may be altered before execution, files can be deleted, etc.
