### ISSUE TITLE
FreeBSD icons

### ISSUE THREAD

**Issue by atmichalak** [romkatv/powerlevel10k#632]
Upon installing zsh, ohmyzsh, and p10k, the icons used at the prompts do not show up. Is there a repository I can install that has these icons in them?

**Comment by gregf** [comment]
I'm on FreeBSD I would suggest installing this.

nerd-fonts-2.0.0_2             Developer-targeted fonts with a high number of glyphs

Has a bunch of good fonts with extra symbols.

**Comment by romkatv** [comment]
> Upon installing zsh, ohmyzsh, and p10k, the icons used at the prompts do not show up. Is there a repository I can install that has these icons in them?

https://github.com/romkatv/powerlevel10k#get-started
