### ISSUE TITLE
wifi segment does not work for Linux

### ISSUE THREAD

**Issue by LeoJhonSong** [romkatv/powerlevel10k#633]
Hi, this zsh theme tastes really great! So I installed on both my Ubuntu 18.04 Laptop and my Raspbian Buster RPi4b. However, I found nothing about wifi shows out after enabled the wifi segment, on both machines. Then I found this in my `~/.p10k.zsh`, at about line 1949:

```shell
  # All parameters except P9K_WIFI_BARS are extracted from the output of the following command:
  #
  #   /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I
```

That command does not exist in Linux, since there is even no `/System` directory.
![image](https://user-images.githubusercontent.com/37630203/79422583-bb080e00-7fef-11ea-979b-dd3cd383bab3.png)

So does that means this wifi segment is macOS only? Or is there a way to use this segment in a Linux system with few modifications? Thanks!

BTW, the battery segment does not show up in my Raspbian Buster, while it works fine with Ubuntu18.04, so I wonder if there is a way to check if my system support the battery segment?

**Comment by romkatv** [comment]
> Hi, this zsh theme tastes really great!

Thanks!

> So does that means this wifi segment is macOS only?

Yes.

> Or is there a way to use this segment in a Linux system with few modifications?

No.

> BTW, the battery segment does not show up in my Raspbian Buster

This is the expected behavior for devices without internal battery. RPi4b doesn't have an internal battery according to https://www.raspberrypi.org/products/raspberry-pi-4-model-b/.

**Comment by LeoJhonSong** [comment]
Thank you for your nice answer. Well I'll try if there is a way to indicate the wifi info in Linux :muscle:
