### ISSUE TITLE
Support alicloud

### ISSUE THREAD

**Issue by aschleifer** [romkatv/powerlevel10k#634]
Hey, similar to AWS and aws-vault there is now https://github.com/arafato/alicloud-vault which behaves the same as the AWS version and exposes `ALICLOUD_VAULT` with the profile name as env variable when in an exec shell.

Would it then be possible to implement some AWS like support in p10k in order to see the profile you are running under?

**Comment by romkatv** [comment]
Feature request acknowledged. I'm busy with other stuff right now, so no ETA at the moment.

**Comment by romkatv** [comment]
I just realized that https://github.com/arafato/alicloud-vault is very new. The project has 3 stars on GitHub. Google search for "ALICLOUD_VAULT" brings two results: the project's home page and this issue.

This is below the threshold of popularity for builtin support in powerlevel10k. However, you can add support for `ALICLOUD_VAULT` to your own prompt quite easily.

```zsh
function prompt_my_alicloud() {
  p10k segment -b white -f black -i '☁' -e -c '$ALICLOUD_VAULT' -t '${ALICLOUD_VAULT//\%/%%}'
}
function instant_prompt_my_alicloud() { prompt_my_alicloud; }
```

Type `p10k help segment` and see `prompt_example` in `~/.p10k.zsh` for documentation .

Now you can add `my_alicloud` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` and configure it the same way as any other prompt segment.

```zsh
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(my_alicloud)

# Show my_alicloud in red.
POWERLEVEL9K_MY_ALICLOUD_FOREGROUND=red

# Show my_alicloud only when the the command you are typing invokes one of these tools.
POWERLEVEL9K_MY_ALICLOUD_SHOW_ON_COMMAND='alicloud-vault|aliyun'
```

Note: it's a good practice to use `my_` prefix with user-defined prompt segments. This will avoid clashes with powerlevel10k in the future (powerlevel10k might get its own `alicloud` prompt segment some day but it won't have `my_alicloud`).
