### ISSUE TITLE
After Adding the themen

### ISSUE THREAD

**Issue by vivekdhiman** [romkatv/powerlevel10k#635]
HI, I ha
<img width="843" alt="Screen Shot 2020-04-16 at 4 00 29 PM" src="https://user-images.githubusercontent.com/7066652/79511231-1d670b80-7ffc-11ea-865f-cea0248d9bbc.png">

Whats that 77 5 etc.
ve added theme and branch information gets distorted. Can you let me know to fix that.

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean
