### ISSUE TITLE
Prompt heads not in sync with iTerm2 transparency setting

### ISSUE THREAD

**Issue by ikovacev** [romkatv/powerlevel10k#636]
I am seeing a weird issue wit p10k on macOS 10.15.4 with iTerm2 3.3.9 (latest). The prompt heads are not reacting to iTerm2 transparency setting. Here are some examples with different transparency settings with white surface in the background starting from 0 transparency:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/22508742/79516472-d143b780-804b-11ea-98e7-b802863ed10f.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/22508742/79516486-dacd1f80-804b-11ea-9f13-04a8eadf6fd5.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/22508742/79516497-e1f42d80-804b-11ea-8b7c-e76e2d58b765.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/22508742/79516511-eb7d9580-804b-11ea-847a-6049fb1b21a9.png">

Normally I keep it at 2nd setting, the rest are just for demonstrating the issue

**Comment by romkatv** [comment]
Transparency setting in iTerm2 (and all other terminals) makes background transparent. It does not affect foreground. If this is not what you expect, please file a feature request against iTerm2.

**Comment by onaforeignshore** [comment]
<img width="253" alt="Screen Shot 2020-05-01 at 12 06 37" src="https://user-images.githubusercontent.com/704406/80791951-3d71ff80-8ba4-11ea-8ade-d17fa33d5712.png">

Not a perfect solution, but checking `Keep background colors opaque` does mitigate the jarring effect
