### ISSUE TITLE
set background of input rows when using transient prompt

### ISSUE THREAD

**Issue by johnmathews** [romkatv/powerlevel10k#638]
Hi, this is really great, thanks!

I'm using 2 line transient promp. Rows which contain keyboard input have `>` to show that the text is a command I entered. (The rows not beginning with `>` are output).

I'd really like to change the background of the input rows to make my commands stand out more from their outputs. Then the screen would be split into horizontal sections of outputs, separated by the inputs that generated them.  

Is this possible?

**Comment by romkatv** [comment]
Make the background of `prompt_char` yellow:

```zsh
POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=yellow
```

Make the space between prompt and command line yellow:

```zsh
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR='%K{yellow} %k'
```

To set the background color of command line, see `zle_highlight` in `man zshzle`. Powerlevel10k [doesn't affect this in any way](https://github.com/romkatv/powerlevel10k/blob/master/README.md#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect).

**Comment by johnmathews** [comment]
thank you! this was really useful.
the best I've been able to do is 

`zle_highlight=(default:bold,bg=yellow,fg=black)`

which applied this highlight to characters that are not otherwise highlighted. 
do you a way to apply zle_highlight to e.g. all chars that are not spaces?

**Comment by romkatv** [comment]
> do you a way to apply zle_highlight to e.g. all chars that are not spaces?

This question is not related to Powerlevel10k. Please ask on forums related zsh.

**Comment by johnmathews** [comment]
:pray:

**Comment by RuRo** [comment]
Hi. Sorry to necro this issue, but `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` doesn't seem to do anything? No matter, what I set `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` to, the transient prompt always just has a transparent background color. Curiously, `_FOREGROUND` works but `_BACKGROUND` doesn't.

I am using the transient prompt and I want the previous commands to be highlighted until the end of the line.
`zle_highlight` *kinda* does what I want, but it also changes the highlighting of the actual interactive prompt.

How it looks currently:
![image](https://user-images.githubusercontent.com/3747318/107692080-5aa03680-6cbd-11eb-8039-bb8f4dd33455.png)

How I want it to look (kind of, pretend that the whole line has the same background color, not the inverse of foreground):
![image](https://user-images.githubusercontent.com/3747318/107692284-9e933b80-6cbd-11eb-8edf-214bc6511aae.png)

<details>
<summary>Output of <code>typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION'</code>:</summary>

```zsh
export POWERLEVEL9K_OS_ICON_FOREGROUND=8
export POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
export POWERLEVEL9K_IP_BACKGROUND=0
export POWERLEVEL9K_BATTERY_VERBOSE=true
export POWERLEVEL9K_BACKGROUND_JOBS_PREFIX='  '
export POWERLEVEL9K_OS_ICON_SUFFIX=' '
export POWERLEVEL9K_DIR_HYPERLINK=true
export POWERLEVEL9K_VIRTUALENV_FOREGROUND=0
typeset -ax POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status command_execution_time_joined background_jobs_joined date time_joined battery )
export POWERLEVEL9K_ROOT_ICON=
export POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
export POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='  '
export POWERLEVEL9K_USER_SUFFIX=' '
export POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=3
export POWERLEVEL9K_USER_ICON=
export POWERLEVEL9K_VIRTUALENV_BACKGROUND=3
export POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=true
typeset ZSH_VERSION=5.8
typeset -ax POWERLEVEL9K_VCS_BACKENDS=( git )
export POWERLEVEL9K_HOST_ICON=' '
export POWERLEVEL9K_DATE_FORMAT='%D{%d/%m/%Y}'
export POWERLEVEL9K_DIR_FOREGROUND=0
export POWERLEVEL9K_SHORTEN_FOLDER_MARKER='(.git)'
export POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
export POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=''
export POWERLEVEL9K_STATUS_BACKGROUND=0
export POWERLEVEL9K_SHORTEN_DELIMITER=''
export POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=90
typeset -ax POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon user_joined host_joined virtualenv vcs ip public_ip_joined vpn_ip_joined ram load disk_usage newline dir dir_writable )
export POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true
export POWERLEVEL9K_PUBLIC_IP_FOREGROUND=3
export POWERLEVEL9K_PUBLIC_IP_NONE='???.???.???.???'
export POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=3
export POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
export POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=8
export POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=4
export POWERLEVEL9K_IP_FOREGROUND=3
export POWERLEVEL9K_PROMPT_CHAR_CONTENT_EXPANSION='the transient prompt'
export POWERLEVEL9K_SSH_ICON=
export POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER=''
export POWERLEVEL9K_MODE=nerdfont-complete
export POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION=
export POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
export POWERLEVEL9K_DIR_BACKGROUND=8
export POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
export POWERLEVEL9K_ALWAYS_SHOW_USER=true
export POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=75
export POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
export POWERLEVEL9K_DIR_SHOW_WRITABLE=true
export POWERLEVEL9K_TRANSIENT_PROMPT=always
export POWERLEVEL9K_PUBLIC_IP_BACKGROUND=0
export POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
export POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=0
export POWERLEVEL9K_SUDO_ICON=
export POWERLEVEL9K_STATUS_EXTENDED_STATES=true
export POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=7
```

</details>

**Comment by romkatv** [comment]
> Hi. Sorry to necro this issue, but `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` doesn't seem to do anything? No matter, what I set `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` to, the transient prompt always just has a transparent background color. Curiously, `_FOREGROUND` works but `_BACKGROUND` doesn't.

Correct. This is the intended behaviour. (Just wanted to confirm that you aren't missing anything here.)

> I am using the transient prompt and I want the previous commands to be highlighted until the end of the line.
> `zle_highlight` _kinda_ does what I want, but it also changes the highlighting of the actual interactive prompt.

From the top my head I cannot say whether it's easy to achieve or not. Unfortunately, I'm really strained for time and attention right now, so I'll have to leave it at that. Hopefully you'll find a way.

**Comment by RuRo** [comment]
> Correct. This is the intended behaviour. (Just wanted to confirm that you aren't missing anything here.)

Sorry, the intended behavior is that the `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` setting doesn't affect anything?

**Comment by romkatv** [comment]
> > Correct. This is the intended behaviour. (Just wanted to confirm that you aren't missing anything here.)
> 
> Sorry, the intended behavior is that the `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` setting doesn't affect anything?

Sorry, I was too hasty in my reply. `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` sets the background color of the current prompt. It has no effect on transient prompt. This is the intended behavior.

**Comment by RuRo** [comment]
It seems really weird, that `POWERLEVEL9K_PROMPT_CHAR_FOREGROUND` sets the foreground color of "the transient prompt>" (you can see, it's orange(3) in the image), but `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` doesn't set the background color of the "the transient prompt>" part, but ok.

Oh, well. Again, sorry for necroing this.

**Comment by romkatv** [comment]
> It seems really weird, that `POWERLEVEL9K_PROMPT_CHAR_FOREGROUND` sets the foreground color of "the transient prompt>" (you can see, it's orange(3) in the image), but `POWERLEVEL9K_PROMPT_CHAR_BACKGROUND` doesn't set the background color of the "the transient prompt>" part, but ok.

As I said, this is intended and what virtually all users want.

It's flexible though. You can customize transient prompt to look pretty much any way you like (about as much flexibility as you have with the current prompt). Search for issues mentioning "p10k-on-pre-prompt".
