### ISSUE TITLE
VISUAL indicator for vi_mode

### ISSUE THREAD

**Issue by apgrc** [romkatv/powerlevel10k#64]
When using vi-mode and adding it to POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS I get a indication of NORMAL or INSERT mode, but vi-mode also has a VISUAL mode. Could it be possible to add that indication as well? Getting also that would be very nice.

I have been trying that on the case statement of powerlevel9k but does not work. I'm switching to 10k so I'm asking this here first.

**Comment by romkatv** [comment]
Done.

To enable `VISUAL` mode display, you need to set `POWERLEVEL9K_VI_VISUAL_MODE_STRING`. Styling for `VISUAL` can be defined similarly to `NORMAL` and `INSERT`. For example:

```zsh
POWERLEVEL9K_VI_VISUAL_MODE_STRING='[V]'
POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND=grey
POWERLEVEL9K_VI_MODE_VISUAL_FOREGROUND=red
```

I'm not a vi user myself, so please verify that it works the way you except.

**Comment by apgrc** [comment]
That work like a charm. Great work. Thank you very much.

**Comment by frescoraja** [comment]
@romkatv  @apgrc  visual mode works fine for me when pressing 'v' in vi-mode... however, when hitting Shift+v (V), the vi-mode prompt segment disappears.. is this a bug? thanks

**Comment by romkatv** [comment]
@frescoraja Thanks for the report! I've submitted a fix. Please update powerlevel10k and try again.

**Comment by frescoraja** [comment]
@romkatv thanks for the quick solution
i'm curious, in which commit was this fixed?

**Comment by romkatv** [comment]
> i'm curious, in which commit was this fixed?

This: https://github.com/romkatv/powerlevel10k/commit/b6ba19617c967b276f801c2163a1359303eceb3e

When you press `v`, zle sets `REGION_ACTIVE` to `1`. When you press `shift-v`, zle sets `REGION_ACTIVE` to `2`. The original code didn't expect `REGION_ACTIVE` to be anything other than empty, zero or one. My fix added handling for `REGION_ACTIVE=2` with the same code path as `REGION_ACTIVE=1`.

**Comment by romkatv** [comment]
@thetic What is replace mode and how do I enable it?

**Comment by thetic** [comment]
See descriptions of `overwrite` mode, bound to `R` in `vi-mode`:

> `ZLE_STATE` (scalar)
>
> Contains a set of space-separated words that describe the current zle state.
> _[...]_
> The string contains _[...]_ `overwrite` if characters to be inserted overwrite existing characters.

http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html

**Comment by romkatv** [comment]
@thetic Thanks for the info and the link. I opened https://github.com/romkatv/powerlevel10k/issues/219. It's probably not too much work to implement but I cannot make promises for any specific timeline.

**Comment by errantepiphany** [comment]
@thetic: I thought you might be interested in something like what I do here: https://github.com/romkatv/powerlevel10k/issues/219#issuecomment-532393984

**Comment by romkatv** [comment]
@thetic https://github.com/romkatv/powerlevel10k/issues/219 is done.
