### ISSUE TITLE
Context prompt is never shown if DEFAULT_USER is set

### ISSUE THREAD

**Issue by BrunoVernay** [romkatv/powerlevel10k#640]
Ok, it is similar to the ultra long #170 (and a bit to #195 ) but after spending a day searching for this, here is a short answer. If your context prompt is never displayed: 

- Edit your .zshrc and remove the line `export DEFAULT_USER=$USER`.
- For immediate effect, run `unset DEFAULT_USER`

Then you can tweak POWERLEVEL9K_CONTEXT_TEMPLATE and POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION and POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION in your `.p10k.zsh`

_No need to read further if that work for you._
I used to set DEFAULT_USER for the Agnoster theme years ago and forgot about it.  The link is really not obvious I found out grepping for "context" and reading `.config/oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh`  around line 1400 ...

I understand that if backward compatibility is paramount, this behavior is a feature. But, there could be:

- a warning typically when running `p10k configure`
- a comment in the `.p10k.zsh` in the `context` section

Thanks

**Comment by romkatv** [comment]
I'm sorry you had an issue caused by `DEFAULT_USER` parameter set in `~/.zshrc`. I'm glad you've solved it. I don't think this warning is useful enough to include it in all users' configs.

**Comment by BrunoVernay** [comment]
I think one comment in a 1000+ lines file is useful even to avoid 1 person hours of struggle. (Especially since it has been me :-).  But I will recover, you spend countless more hours than me.
Besides, any chance to have a toolbox/podman/OCI container segment integrated??

**Comment by romkatv** [comment]
> I think one comment in a 1000+ lines file is useful even to avoid 1 person hours of struggle.

I'm sorry for the hours of struggle you had to endure.

> Besides, any chance to have a toolbox/podman/OCI container segment integrated??

At this point zero chance. If you want to see it done, you'll need to at least open an issue and describe the feature in enough detail for me to understand what you want.
