### ISSUE TITLE
Recommended police doesn't differentiate Minus char and Dash chars

### ISSUE THREAD

**Issue by bplessis** [romkatv/powerlevel10k#643]
Hi,

I tested the recommended font and quickly identified one issue, the font doesn't differentiate (or at least not in a visible enough way) '-' / HYPHEN-MINUS and '–' / EN DASH.

Issues may arise since a lot of CMS/editors tend to automatically convert the hyphen/minus into the dash but i don't know many (if any) software that allow the dash as an argument toggle.

Regards,
benoit

**Comment by romkatv** [comment]
> the font doesn't differentiate (or at least not in a visible enough way) '-' / HYPHEN-MINUS and '–' / EN DASH.

They look different:

![image](https://user-images.githubusercontent.com/1282067/79770482-c16af280-832d-11ea-9f4a-2526a00535bf.png)

In any case, I'm not going to pretend I know better how to design monospace font than Apple (the recommended font is Menlo + extra glyphs).
