### ISSUE TITLE
Multiple new lines on Hyper startup

### ISSUE THREAD

**Issue by brianhafferkamp** [romkatv/powerlevel10k#645]
I'm using powerlevel10k with oh-my-zsh (zsh v5.7.1) in the Hyper terminal (3.0.2). I'm noticing an issue where, when I initialize my Hyper terminal, I'm seeing multiple new lines created as seen below:
<img width="875" alt="Screen Shot 2020-04-20 at 4 22 20 PM" src="https://user-images.githubusercontent.com/29557595/79805455-659b6c00-8323-11ea-9d6c-825f3b11e172.png">

Previously, I was seeing a `%` at the top, which is a fairly well known issue. I resolved this by adding `unsetopt PROMPT_SP` to my `.zshrc`. However, this did not fix the multiple new lines.

If I use a different theme for oh-my-zsh, I do not see this issue. It is possible that this could be an issue with Hyper, as I am not seeing the issue with powerlevel10k in the Mac Terminal. I have opened up a [similar ticket](https://github.com/zeit/hyper/issues/4504) in the Hyper repo.

Any ideas on how I might be able to fix this?

Thanks!

**Comment by romkatv** [comment]
This is a big in Hyper.
