### ISSUE TITLE
Configure doesn't ask whether icons work or not

### ISSUE THREAD

**Issue by MinerChAI** [romkatv/powerlevel10k#646]
Tried on Konsole and Yakuake.
I installed the default font but `p10k configure` didn't ask me about icons and about prompt shape - only colors.
Using Arch, tried installing powerline10k both with oh my zsh and through aur, didn't help.

**Comment by MinerChAI** [comment]
Oh, forgot to set locale

**Comment by romkatv** [comment]
> Oh, forgot to set locale

Or rather to install it.

Configuration wizard won't ask if you can see fancy glyphs if the answer is obviously No. The same goes for colors -- you'll see an option to use 256 and 16M colors only these colors can be displayed.

**Comment by bhumit070** [comment]
Please explain I ran sudo locale-gen
and then re run p10k configure but it did not ask me for icons again

**Comment by romkatv** [comment]
@bhumit070 See https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
