### ISSUE TITLE
Improvement suggestion : default $ZSH_CUSTOM in the docs

### ISSUE THREAD

**Issue by 779g** [romkatv/powerlevel10k#647]
Hello, and thanks for the hard work

I suggest in the readme.md you provide a default $ZSH_CUSTOM for installing the theme on oh my zsh, in case we execute the command in another shell or in a script

In readme.md i suggest the change of  
```
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
```

by 

```
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
```

This is the same sensible default provided for instance by zsh plugins, https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md

**Comment by romkatv** [comment]
Sounds good. Care to send a PR?
