### ISSUE TITLE
Many icons not available with 12h time format 

### ISSUE THREAD

**Issue by atifchy** [romkatv/powerlevel10k#649]
![Screenshot_20200422_153448](https://user-images.githubusercontent.com/42291930/79966259-ffdbeb00-84ae-11ea-8360-931325bf8e05.png)

**Comment by romkatv** [comment]
Please provide more details. The subject and the screenshot are not enough to understand what's wrong.

**Comment by atifchy** [comment]
Many icon option isn't available for 12-hour time format

**Comment by romkatv** [comment]
Could you post instructions how I can reproduce this issue?

**Comment by atifchy** [comment]
[p10k-2020-04-22_15.53.54.zip](https://github.com/romkatv/powerlevel10k/files/4515336/p10k-2020-04-22_15.53.54.zip)
watch this video

**Comment by romkatv** [comment]
Thanks! I was able to reproduce this by selecting the same options.

I'll fix it when I get free time. No ETA.

**Comment by romkatv** [comment]
This is fixed.
