### ISSUE TITLE
_gitstatus_cleanup_0_1337:3: _gitstatus_cleanup_0_1337: parameter not set

### ISSUE THREAD

**Issue by ehohn** [romkatv/powerlevel10k#65]
While investigating an issue with the "status" segment of powerlevel9k/10k, I stumbled upon this strange behaviour:

Steps to reproduce:

Run this within your ZSH with Powerlevel10k:

```
(exit 1)
```

This produces the following output:

```
_gitstatus_cleanup_0_1337:3: _gitstatus_cleanup_0_1337: parameter not set
```
(Where 1337 is the PID of the ZSH session).

I do not experience any problems with this setup, but the output is unexpected.
Powerlevel9k does not show this behaviour.

Expected behaviour would be no output at all.

**Comment by romkatv** [comment]
Thanks for the report! This is now fixed.
