### ISSUE TITLE
Custom prompt segment missing after last update?

### ISSUE THREAD

**Issue by Morg42** [romkatv/powerlevel10k#651]
Hi,

my .zshrc contains - as last lines - 

```zsh
function zsh_newmail(){
         if [[ $HOST == "narya" ]] ; then
                 local mail=$(find ~/Mail/in*/new -type f|grep -v copybox|wc -l)
                 local color='%F{blue}'
                 [[ $mail -ne 0 ]] && echo -n "%{$color%}\uf42f $mail"
         fi
 }

POWERLEVEL9K_CUSTOM_NEWMAIL="zsh_newmail"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs custom_newmail history)
```
The shell function counts new mails in all mailfolders as a combined new-mail count, but only on host narya (debian), and this has worked quite well for about a year now.

"Suddenly" - I guess since the last git pull of P10k - the whole prompt is displayed correctly, but the custom segment is missing. Calling the zsh_newmail from zsh results in 

```
%{%F{blue}%} 2%
```

I tried using p10k configuration wizard and inserting the three lines from above after sourcing .p10k.zsh from .zshrc, but - aside from the different colors - no changes.

Any hints? Am I doing something wrong? I don't remember changing anything, especially not in zsh config, aside from updating (git pull) p10k, o-m-z and plugins (autosuggest and syntax-highlight).

**Comment by romkatv** [comment]
Please post the output of the following command:

```zsh
() {
  emulate -L zsh -o xtrace
  typeset -pm 'POWERLEVEL9K_*|_p9k__rprompt|_p9k__lprompt|PS1|RPS1|HOST|ZSH_VERSION'
  functions zsh_newmail
  zsh_newmail
}
```

**Comment by Morg42** [comment]
Ran the command with ... ```&> zsh.log```
[zsh.log](https://github.com/romkatv/powerlevel10k/files/4523206/zsh.log)

**Comment by romkatv** [comment]
Thanks for the info. Should be fixed now.

I would recommend upgrading your zsh to a newer version. If you are using macOS, it's as easy as `brew install zsh`. You'll get faster shell with fewer issues. Even though powerlevel10k officially supports zsh versions as old as yours, I don't test it against them as much as against newer versions.
