### ISSUE TITLE
command_execution_time

### ISSUE THREAD

**Issue by 709908730** [romkatv/powerlevel10k#654]
Is it possible to set the duration of the last command？

![Screenshot_20200425_183001](https://user-images.githubusercontent.com/55641147/80278093-2192d780-8726-11ea-9efd-7e4e76af7668.jpg)

**Comment by romkatv** [comment]
Yes. See https://github.com/romkatv/powerlevel10k/blob/681f504d8ac98c5ac1b166999ceebc72cace2260/config/p10k-classic.zsh#L494-L495
