### ISSUE TITLE
Line Height

### ISSUE THREAD

**Issue by y1rah** [romkatv/powerlevel10k#656]
![Xnip2020-04-26_00-35-02](https://user-images.githubusercontent.com/30183249/80285295-6898c100-8756-11ea-8219-a6e638045b3e.jpeg)

How may I change the line height as showed in the image? Seems all defaults are not appropriate for that cursor and prompt are sticked together.

^_^

**Comment by romkatv** [comment]
> How may I change the line height as showed in the image?

You can do that in the preferences/settings of your terminal.

> Seems all defaults are not appropriate for that cursor and prompt are sticked together.

The line height looks as expected on your screenshot. If you don't like tall cursor, you can change its shape. Once again, this can be done through preferences/settings of your terminal.
