### ISSUE TITLE
Override POWERLEVEL9K_HOME_ICON location

### ISSUE THREAD

**Issue by smholvoet** [romkatv/powerlevel10k#658]
As mentioned in the [powerlevel9k README](https://github.com/Powerlevel9k/powerlevel9k#dir), there are a couple of icons which are mapped to specific directories.

I'd like to override the directory which gets linked to the `POWERLEVEL9K_HOME_ICON`.

E.g. show the :house: icon when I'm at `/mnt/C/Users/smholvoet` instead of when I'm in my Ubuntu homedir (as I'm using WSL).

Is this possible? If so, how could this be achieved?

**Comment by romkatv** [comment]
See: https://github.com/romkatv/powerlevel10k/blob/aca2f19fa385f01e7f9bef69316e8929707bac7b/config/p10k-rainbow.zsh#L279-L314
