### ISSUE TITLE
Strange behaviour with multi-line prompt and long completion menus

### ISSUE THREAD

**Issue by pwyde** [romkatv/powerlevel10k#66]
If multi-line prompt is enabled and completion generates a long menu that extends beyond the height of the terminal window, a strange "rendering" issue occurs.

To reproduce the issue: 

1. Start a terminal window and resize it to for example 80 x 30.
2. Use `Tab` to complete a command that is known to have many options/arguments.
3. Cycle through the completions menu with `Tab` and observe the line just above the completions menu.

See [this](https://asciinema.org/a/bsKwmNfwUiq8FnO6x3cocVWQw) asciinema recording for a better visual description of the issue.

Recording is created in **Konsole** running Zsh v**5.7.1** on Arch Linux. Configuration files are taken from your **[dotfiles-public](https://github.com/romkatv/dotfiles-public)** repository.

Issue occurs in both **Powerline10k** and **Pure Power** but __only__ if multi-line prompt is enabled.

**Comment by romkatv** [comment]
Indeed, Powerlevel9k/10k does illegal things when `POWERLEVEL9K_RPROMPT_ON_NEWLINE` is set to `false`. Specifically, it moves the cursor within a `%{%}` block, which can only be used for control codes that _don't_ move the cursor.

You can set `POWERLEVEL9K_RPROMPT_ON_NEWLINE=true` if this really bothers you. I rarely use menu completion, and certainly not when there are so many options that they don't fit on the screen, so I don't suffer from the defects of this hack. On the other hand, `POWERLEVEL9K_RPROMPT_ON_NEWLINE=false` gives you are full line for the command to type, which is really nice.

I'll see if I can come up with an alternative implementation of `POWERLEVEL9K_RPROMPT_ON_NEWLINE=false` that doesn't clash with completion menu.

**Comment by pwyde** [comment]
Thank you for looking into this.

At the end of the day it is all about what one find as aesthetically pleasing. For me personally it bothers a bit to have it set to `POWERLEVEL9K_RPROMPT_ON_NEWLINE=false`. It does however bother me more that the completion menu becomes jacked up. I am terrible at remembering command options/arguments. So having a menu that I can cycle through the options is a must.

I'll set `POWERLEVEL9K_RPROMPT_ON_NEWLINE=false` for now and if you do find a solution I thank you.

**Comment by romkatv** [comment]
This is fixed. Please verify.

**Comment by pwyde** [comment]
Works great. Thank you for fixing this!
