### ISSUE TITLE
git status icon issue

### ISSUE THREAD

**Issue by Arend-Jan** [romkatv/powerlevel10k#660]
just upgraded from p9k. Installed new fonts, but for some reason the git status icons aren't working (the "!3" and "?8" status items). I suspect it's because of the upgrade, but not sure. How can I change them to the p10k defaults?
![p10k](https://user-images.githubusercontent.com/868066/80302994-b8ef3d80-87ad-11ea-9623-b22e7190dcc7.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean.

If you like, you can use your old powerlevel9k config with powerlevel10k. Prompt will look exactly the same as before (see https://github.com/romkatv/powerlevel10k/blob/master/README.md#extra-or-missing-spaces-in-prompt-compared-to-powerlevel9k however).
