### ISSUE TITLE
green causes blinding

### ISSUE THREAD

**Issue by TyNguyen2001** [romkatv/powerlevel10k#661]
How do I turn it off or change it?
[https://drive.google.com/open?id=1LIaJGwH8uVc5pcGKppEqqiU9aYG9JyBq
![Annotation 2020-04-26 223458](https://user-images.githubusercontent.com/64082226/80312293-a3f6c680-880e-11ea-8184-0b49eab2f052.png)
](url)

**Comment by romkatv** [comment]
This has nothing to do with powerlevel10k. Please ask elsewhere.
