### ISSUE TITLE
Periodic refresh of prompt?

### ISSUE THREAD

**Issue by pkazmier** [romkatv/powerlevel10k#662]
Is it possible to periodically have the prompt refresh itself? I include several elements that change values regardless of activity inside a zsh session such as load average, free memory, and battery level. Can one specify an idle timer where the prompt refreshes itself asynchronously?

This would be great as it would be nice to see the values in the prompt reflecting the current state after returning to a zsh session—especially for battery charge. If my battery is level is at 40%, then I return an hour later after charging, it would be nice if it reflected the accurate charge without having to press enter to redraw the prompt.

Thanks for an amazing shell prompt! I just discovered it yesterday and spent about 4 hours customizing my p10k config. Most of that was on selecting colors to match my terminal color scheme exactly (basically went through and remapped everything to 16 color values). Here is my obligatory screenshot:

![image](https://user-images.githubusercontent.com/747855/80312369-7e37d600-87aa-11ea-82fe-de9684f85616.png)

**Comment by romkatv** [comment]
> Is it possible to periodically have the prompt refresh itself?

Yes, but it's not a good idea to do it.

```zsh
TRAPALRM() {
  emulate -L zsh
  local f
  for f in chpwd $chpwd_functions precmd $precmd_functions; do
    (( $+functions[$f] )) && $f &>/dev/null
  done
  zle .reset-prompt
  zle -R
}

TMOUT=10
```

Please don't treat this as endorsement. It's really a bad idea to do it. Unfortunately I'm too busy to explain everything that will go wrong and why you shouldn't use this even if it worked without issues.
