### ISSUE TITLE
Setting kitty theme from precmd_functions on startup breaks instant_prompt

### ISSUE THREAD

**Issue by BlueDrink9** [romkatv/powerlevel10k#665]
I'm looking for a solution/workaround to this issue.

In the code below, I set the kitty colourscheme (normally from a cached file, but for demo purposes it's explicit here) from a `precmd_function` (using code shared with bash via `$PROMPT_COMMAND`, but happens even without that setup).

When kitty's colourscheme is set in this way, the instant prompt still appears. However, **any text typed is discarded once profile initialisation finishes** (then the colours update).

This of course defeats the point of instant prompt.

kitty @ set-colors is defined [here](https://github.com/kovidgoyal/kitty/blob/master/kitty/rc/set_colors.py), if you want to read the python.

This might be a kitty problem, so I understand if you can't/don't want to address this.

.zshrc:

```zsh
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
if [[ -r "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PROMPT_COMMAND="kitty @ set-colors '/Users/user/.cache/kitty/kitty-themes/themes/Afterglow.conf'; $PROMPT_COMMAND"
export PROMPT_COMMAND="./.config/base16-shell/colortest 
# Enable using bash's PROMPT_COMMAND.
_prompt_command() { eval "$PROMPT_COMMAND" }
precmd_functions+=(_prompt_command)
sleep 1

ZINIT_DIR="/Users/user/.local/share/zinit/bin"
source "${ZINIT_DIR}/zinit.zsh"
# Theme with instant prompt support
zinit ice depth=1; zinit light romkatv/powerlevel10k
[ ! -f "$SCRIPT_DIR/plugins/p10k.zsh" ] || source "$SCRIPT_DIR/plugins/p10k.zsh"
```

**Comment by romkatv** [comment]
> This might be a kitty problem, so I understand if you can't/don't want to address this.

I'd say it's a configuration problem. You need to either call `kitty @ set-colors` before instant prompt or, better yet, use persistent terminal configuration. You aren't installing `kitty` from zshrc, so by the same token it makes sense to not configure `kitty` from zshrc.

By the way `~/.cache` is not a good place to store configs. This directory is meant for files that can be freely deleted. If you delete the whole `~/.cache`, it should only make things a bit slower but should have no other effects.

**Comment by BlueDrink9** [comment]
It's an downloaded repo of themes, so I don't care if it's deleted and I don't want it backed up in .config, where it used to be. It should probably go in share.

I use kitty's main config for the default theme, but if I change it I want the changes to apply to new instances, which is what this is for and why it's in zshrc.

Don't really want to put all the funcs and infrastructure needed for that before instant prompt, so I might have to give up.

Unless there's a way to set the precmd hooks and run a command after instant prompt does its thing. Maybe I'll try overwriting the function the first time precmd is called, so that my theme function is only called after my first interactive command.

Setting the colours didn't cause an issue if I ran it as a normal line in the rc, iirc, so I could rely on that for the first-time setup.

If you (as a zsh expert rather than maintainer) have any other suggestions, please provide. Either way, thanks for the response

**Comment by romkatv** [comment]
> If you (as a zsh expert rather than maintainer) have any other suggestions, please provide. Either way, thanks for the response

I don't know what `kitty @ set-colors` does and I haven't tried to reproduce this, so it's difficult to offer a workaround.

You could try a few things just to see what happens.

1. Try redirecting stdin and stdout to `$TTY`: `<$TTY >$TTY kitty @ set-colors`. I've no idea if this command actually controls kitty via escape sequences or if it uses some kind of IPC.
2. Remove your precmd hook and try this:
```zsh
function p10k-on-init() {
  emulate -L zsh
  if [[ $P9K_PROMPT == regular ]]; then
    eval $PROMPT_COMMAND
  fi
}
```

**Comment by romkatv** [comment]
If neither (1) nor (2) work from the previous comment, it means `kitty @ set-colors` wipes keyboard input buffer. To work around this you can try running `kitty @ set-colors` after zle finishes processing all buffered keys.

```zsh
zinit ice depth=1; zinit light romkatv/zsh-defer
zsh-defer -a -c "$PROMPT_COMMAND"
```

And remove `precmd_functions` hook of course.

**Comment by BlueDrink9** [comment]
That second suggestion was exactly what I was fumbling for! Thank you so much!

**Comment by BlueDrink9** [comment]
Updating for closure:
Finally got around to actually implementing this, and your final solution did work nicely. I also added a deferred line to re-add the precmd hook:

: `zsh-defer -a -c "precmd_functions+=(_prompt_command)"`

The first two suggestions changed nothing.
