### ISSUE TITLE
Prompt waits for gitstatus to finish instead of showing old info in grey

### ISSUE THREAD

**Issue by usernein** [romkatv/powerlevel10k#667]
I've been facing this issue for some weeks but i got used to it because i thought it was normal - until i read the docs.

Well, the prompt just don't show the grey info (to update later to orange), it simply waits for gitstatus to finish, then show the prompt. I read all documentation and i don't really know what to do, it takes several seconds on big repositories (e.g. 10 seconds for repositories of +100mb)

[Screen recording](https://usernein.souunick.com/p10k-gitstatus-slow.mp4)
[.p10k.zsh](https://hastebin.com/atiqunojuf.shell)
[.zshrc](https://hastebin.com/jamuxicide.shell)
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4540773/p10k.txt)

**Comment by romkatv** [comment]
Your prompt is not using gitstatus.

Do you see an error every time you start zsh?

Can you reproduce this after reinstalling powerlevel10k?

**Comment by usernein** [comment]
> Do you see an error every time you start zsh?
No, even with instant prompt set to verbose

> Can you reproduce this after reinstalling powerlevel10k?
Yes, i just tried it after i read your reply, it still occurring
I executed:
```
rm -rf ~/.oh-my-zsh/custom/themes/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/themes/powerlevel10k
```

**Comment by romkatv** [comment]
Please run the following command. When it completes, attach `~/p10k.txt` to this issue (you can drag-and-drop files to the edit box on github.com).

```zsh
(
  emulate -L zsh -o err_return -o xtrace -o no_unset
  typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION|*GITSTATUS*'
  uname -ms
  uname -o || true
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/gitstatus.XXXXXXXXXX)"
  {
    git clone --depth=1 https://github.com/romkatv/gitstatus.git $tmp
    cd $tmp
    zsh -dfeic "
      GITSTATUS_LOG_LEVEL=DEBUG
      source ./gitstatus.plugin.zsh
      gitstatus_start -s -1 -u -1 -c -1 -d -1 -m -1 MY
      gitstatus_query -p MY
      setopt xtrace
      typeset -m 'VCS_STATUS_*'
      cat \$GITSTATUS_XTRACE_MY
      cat \$GITSTATUS_DAEMON_LOG_MY"
  } always {
    cd /
    rm -rf -- $tmp
  }
) &>~/p10k.txt
```

**Comment by usernein** [comment]
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4540771/p10k.txt)

**Comment by romkatv** [comment]
The file you've posted has this error:

```text
fatal: unable to access 'https://github.com/romkatv/gitstatus.git/': Could not resolve host: github.com
```

It comes from this command:

```zsh
git clone --depth=1 https://github.com/romkatv/gitstatus.git
```

Please do what you need to do to fix it. Then retry the whole thing I posted above and post `p10k.txt`.

**Comment by usernein** [comment]
The zsh command was failing with no output
![20200427_234102](https://user-images.githubusercontent.com/29507335/80441515-91f25200-88fa-11ea-8a4a-40957d56c26e.jpg)

So i removed the option '-e' and here is the result:
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4543111/p10k.txt)

Meanwhile i tried to figure out what did i do to start getting this behavior and it was the binary gitstatusd-android-armv7l. I replaced it with the old one (that i compiled before gitstatus have it already available at the repo) and it's working now

By the way there still an issue with the available binary

**Comment by romkatv** [comment]
Thanks for the logs. I see that gitstatusd segfaults. Debugging revealed that it's a bug in gcc 8.2. I've rebuilt `gitstatusd-linux-armv7l` with gcc 9.2 and pushed it to powerlevel10k. Please remove your custom binary, update powerlevel10k to the latest version and try again.

**Comment by usernein** [comment]
It's working fine now, thank you!

**Comment by romkatv** [comment]
Thanks for the confirmation!
