### ISSUE TITLE
Truncation not truncating /mnt/ but other directories instead

### ISSUE THREAD

**Issue by turkeyphant** [romkatv/powerlevel10k#669]
```
  local anchor_files=(
    .shorten_folder_marker
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"

 # If set to true, remove everything before the last (deepest) subdirectory that contains files
  # matching $POWERLEVEL9K_SHORTEN_FOLDER_MARKER. For example, when the current directory is
  # /foo/bar/git_repo/baz, prompt will display git_repo/baz. This assumes that /foo/bar/git_repo
  # contains a marker (.git) and other directories don't.
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=true
```

I have a filesystem that goes:

/mnt/disk1/files/folder/sub/

However, even with a .shorten_folder_marker in /mnt/disk1/ it will truncate disk1

```
root@fs /mnt # ls -a                                      
.  ..  disk1  disk2  disk3  disk4  disk9  disks  user

 root@fs /mnt # cd disk1                                  

 root@fs disk1 # touch .shorten_folder_marker             

 root@fs disk1 # cd files                                 

 root@fs files # cd folder                                

 root@fs files/folder # cd sub                            

 root@fs files/folder/sub
```

Ideally I want it to always truncate level 1 (/mnt/) but never truncate or shorten level 2 (/mnt/disk1/, /mnt/disk2/, etc.)

**Comment by romkatv** [comment]
I'll paraphrase.

You are using these configuration options:

```zsh
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_FOLDER_MARKER=.shorten_folder_marker
POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=true
```

When your current directory is `/mnt/disk1/files`, prompt displays directory as `files` but you want to see `disk1/files`.

Is this correct?

Does `/mnt/disk1/files/.shorten_folder_marker` exist?

Can you reproduce this problem from the shell opened by the following command?

```zsh
() (
  emulate -L zsh -o err_return -o pushd_silent
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    pushd -- $tmp
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_SHORTEN_FOLDER_MARKER=.shorten_folder_marker
POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=true
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    popd
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```

**Comment by turkeyphant** [comment]
> When your current directory is `/mnt/disk1/files`, prompt displays directory as `files` but you want to see `disk1/files`.
> 
> Is this correct?

Yes.

> Does `/mnt/disk1/files/.shorten_folder_marker` exist?

Yes. I want level 2 and level 3 to show always.

> Can you reproduce this problem from the shell opened by the following command?

Yes:

Cloning into 'powerlevel10k'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 47 (delta 7), reused 22 (delta 3), pack-reused 0
Unpacking objects: 100% (47/47), done.
 video/del  pwd
/mnt/user/video/del
 video/del  cd /mnt
 /mnt  cd disk1
 disk1  ls -a
.   appdata  backup   download_old   ebooks       files    isos       .shorten_folder_marker  system 
..  audio    domains  Dropbox       folder1    filehistory  install  musictest  staging2                test
 disk1  cd files
 files  ls -a
.                        downloadconfigfile.conf          web
..                       camera uploads           more
photos  nfs_backup                           .shorten_folder_marker
 files  mkdir folder
 files  cd folder
 files/folder 

**Comment by romkatv** [comment]
> > Does `/mnt/disk1/files/.shorten_folder_marker` exist?
> 
> Yes.

This is why prompt shows only `files` when you are in `/mnt/disk1/files`. This is explained in the comment you've quoted.

> I want level 2 and level 3 to show always.

Do you get the behavior you want if you delete `/mnt/disk1/files/.shorten_folder_marker`?

**Comment by turkeyphant** [comment]
> > > Does `/mnt/disk1/files/.shorten_folder_marker` exist?
> > 
> > 
> > Yes.
> 
> This is why prompt shows only `files` when you are in `/mnt/disk1/files`. This is explained in the comment you've quoted.
> 
> > I want level 2 and level 3 to show always.
> 
> Do you get the behavior you want if you delete `/mnt/disk1/files/.shorten_folder_marker`?

Sometimes.

I have two folders. /mnt/disk1/files/ and /mnt/disk1/audio/.

```
root@fs  🖿  audio ▓▒░ rm .shorten_folder_marker                                                               ░▒▓ ✔  11.95  15% hdd  16:29 🕟  

 root@fs  🖿  disk1/audio ▓▒░  cd languages/                                                                    ░▒▓ ✔  11.91  15% hdd  16:29 🕟  

 root@fs  🖿  disk1/audio/languages ▓▒░ cd Spanish                                                              ░▒▓ ✔  11.89  15% hdd  16:29 🕟  

 root@fs  🖿  disk1/au…/languages/Spanish ▓▒░
```

Here it's truncating "audio" when I never want this to happen.

```
 root@fs  🖿  disk1/files ▓▒░ mkdir llllllllllllllllllllll                                                      ░▒▓ ✔  12.12  15% hdd  16:32 🕟  

 root@fs  🖿  disk1/files ▓▒░  cd llllllllllllllllllllll/                                                       ░▒▓ ✔  12.13  15% hdd  16:32 🕟  

 root@fs  🖿  disk1/files/llllllllllllllllllllll ▓▒░ mkdir mmmmmmmmmmmmmmmmmmmmm                                ░▒▓ ✔  12.13  15% hdd  16:32 🕟  

 root@fs  🖿  disk1/files/llllllllllllllllllllll ▓▒░  cd mmmmmmmmmmmmmmmmmmmmm/                                 ░▒▓ ✔  12.22  15% hdd  16:32 🕟  

 root@fs  🖿  disk1/files/llllllllllllllllllllll/mmmmmmmmmmmmmmmmmmmmm ▓▒░ 
```

Here it's not.

**Comment by turkeyphant** [comment]
> This is explained in the comment you've quoted.

I'm confused. The comment says:

> for example, when the current directory is
  # /foo/bar/git_repo/baz, prompt will display git_repo/baz. This assumes that /foo/bar/git_repo
  # contains a marker (.git) and other directories don't.

This explains why "files" is not being truncated but not why "disk1" is. Neither should be.

**Comment by romkatv** [comment]
> I'm confused.

It's explained in the comment you've quoted earlier.

```zsh
# If set to true, remove everything before the last (deepest) subdirectory that contains files
# matching $POWERLEVEL9K_SHORTEN_FOLDER_MARKER.
```

If your current directory is `/mnt/disk1/files` and both `/mnt/disk1` and `/mnt/disk1/files` have markers, then `files` is the last (deepest) subdirectory with a marker, so everything before it gets removed.

I think what you want is the ability to remove everything before the **first** subdirectory with a marker. I've added an option for this:

```zsh
typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=first
```

Please update powerlevel10k and give it a try. Does it do what you want?

**Comment by turkeyphant** [comment]
> Please update powerlevel10k and give it a try. Does it do what you want?

That sounds perfect but I'm afraid it didn't work:

```
 root@fs  🖿  disk1 ▓▒░ git -C $ZSH_CUSTOM/themes/powerlevel10k pull                                                ░▒▓ ✔  16.88  18%  00:33 🕧  
Already up to date.

 root@fs  🖿  disk1 ▓▒░ exec zsh                                                                              ░▒▓ ✔  0.6s  16.87  18%  00:33 🕧  

 root@fs  🖿  disk1 ▓▒░ ll                                                                                          ░▒▓ ✔  16.87  18%  00:33 🕧  
Permissions Size User   Date Modified    Name                      Permissions Size User   Date Modified    Name
.rw-rw-rw-   368 root   2017-08-18 02:37 ._.DS_Store               drwxrwxrwx     - nobody 2020-04-28 19:54 ebooks
.rw-rw-rw-   14k root   2019-04-26 14:33 .DS_Store                 drwxrwxrwx     - nobody 2020-04-23 08:35 filehistory
.rw-rw-rw-     0 root   2020-04-28 13:06 .shorten_folder_marker    drwxrwxrwx     - nobody 2020-04-28 16:37 files
drwxrwxrwx     - nobody 2020-04-26 17:07 .Trash-99                 drwxrwxrwx     - nobody 2020-04-28 19:54 install
drwxrwxrwx     - nobody 2020-04-26 14:21 appdata                   drwxrwxrwx     - nobody 2020-04-28 12:36 isos
drwxrwxrwx     - nobody 2020-04-29 00:32 audio                     drwxrwxrwx     - nobody 2020-04-28 12:36 musictest
drwxrwxrwx     - nobody 2020-04-28 19:54 backup                    drwxrwxrwx     - nobody 2020-04-28 13:53 staging2
drwxrwxrwx     - nobody 2020-04-17 12:38 domains                   drwxrwxrwx     - nobody 2020-04-26 14:20 system
drwxrwxrwx     - nobody 2020-04-23 02:24 download_old              drwxrwxrwx     - nobody 2020-04-29 00:08 test
drwxrwxrwx     - nobody 2020-04-18 02:06 Dropbox                   

 root@fs  🖿  disk1 ▓▒░ cd audio                                                                                    ░▒▓ ✔  16.81  18%  00:33 🕧  

 root@fs  🖿  audio ▓▒░  cd languages/                                                                              ░▒▓ ✔  16.79  18%  00:34 🕧  

 root@fs  🖿  audio/languages ▓▒░ cd Spanish                                                                        ░▒▓ ✔  16.82  18%  00:34 🕧  

 root@fs  🖿  audio/languages/Spanish ▓▒░                                                                           ░▒▓ ✔  16.84  18%  00:34 🕧  
```

**Comment by romkatv** [comment]
> I've added an option for this:
> 
> ```shell
> typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=first
> ```

Have you set this option?

**Comment by turkeyphant** [comment]
Yes.

**Comment by romkatv** [comment]
Please run the following command and post all output between and including the indicated lines:

```zsh
() (
  emulate -L zsh -o err_return -o pushd_silent -o extended_glob
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    pushd -- $tmp
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir newline)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=first
POWERLEVEL9K_SHORTEN_FOLDER_MARKER=.shorten_folder_marker
POWERLEVEL9K_MODE=ascii
POWERLEVEL9K_FOREGROUND=
POWERLEVEL9K_BACKGROUND=
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
    print -r -- '--- post all output starting from here ---'
    mkdir -p foo/bar/baz/qux
    touch {foo,foo/bar/baz}/.shorten_folder_marker
    cd foo/bar/baz/qux
    pwd
    print -lr -- ./(../)#.shorten_folder_marker(:a)
    ZDOTDIR=$tmp zsh -is </dev/null
    print -r -- '--- post all output up to here ---'
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```

**Comment by turkeyphant** [comment]
--- post all output starting from here ---
/tmp/p10k.iXJJTxccuM/foo/bar/baz/qux
/tmp/p10k.iXJJTxccuM/foo/bar/baz/.shorten_folder_marker
/tmp/p10k.iXJJTxccuM/foo/.shorten_folder_marker
foo/b*/baz/qux                                                                                                                                 
--- post all output up to here ---

**Comment by romkatv** [comment]
The output indicates that everything works as expected. If you can clearly explain what doesn't work for you and provide instructions to reproduce that I can follow, I'll take a look.

**Comment by turkeyphant** [comment]
I need to never see /mnt/ unless I'm in /mnt/. 

I need to always see foo and bar in any subdirectory of bar:

~/mnt/~**foo**/*bar**/_baz_/_qux_

So level 1 mnt is always omitted entirely. 
Level 2 foo is **never truncated**. 
Level 3 bar is **never truncated**.
Levels 4+ (baz, etc.) are _truncated normally_.

In the example bar was truncated when it should display in full.

**Comment by turkeyphant** [comment]
Examples:

/mnt/
I see /mnt/

/mnt/disk1/
I see disk1/

/mnt/disk1/audio/
I see disk1/audio/

/mnt/disk1/audio/foooooo/baaaaar/baz/qux/
I see disk1/audio/f.. /b... /baz/qux/

**Comment by romkatv** [comment]
> Examples:
> 
> `/mnt/`
> I see /mnt/
> 
> `/mnt/disk1/`
> I see disk1/
> 
> `/mnt/disk1/audio/`
> I see disk1/audio/
> 
> `/mnt/disk1/audio/foooooo/baaaaar/baz/qux/`
> I see disk1/audio/f.. /b... /baz/qux/

1. Use these settings:
```zsh
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=first
POWERLEVEL9K_SHORTEN_FOLDER_MARKER=.shorten_folder_marker
```
2. Create `.shorten_folder_marker` in `/mnt/disk1` and `/mnt/disk1/audio`.

Does it do what you want?

**Comment by turkeyphant** [comment]
Thank you for your patience. With both `.shorten_folder_marker` and `POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=first` it now seems to work.

**Comment by romkatv** [comment]
Thanks for the confirmation.

**Comment by romkatv** [comment]
FYI: `POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER` now supports optional offset, which could be useful for your setup.

```zsh
# Optionally, "first" and "last" can be followed by ":<offset>" where <offset> is an integer.
# This moves the truncation point to the right (positive offset) or to the left (negative offset)
# relative to the marker. Plain "first" and "last" are equivalent to "first:0" and "last:0"
# respectively.
```

To achieve the kind of truncation you describe https://github.com/romkatv/powerlevel10k/issues/669#issuecomment-621112428, create `/mnt/.shorten_folder_marker`, delete all other `.shorten_folder_marker` files you might have and set these parameters:

```zsh
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=first:1
POWERLEVEL9K_SHORTEN_FOLDER_MARKER=.shorten_folder_marker
```
