### ISSUE TITLE
Content is overlapping after resizing terminal

### ISSUE THREAD

**Issue by sarthakchaudhary13** [romkatv/powerlevel10k#670]
I am using **GNOME terminal** and when resizing the terminal from full screen the content is overlapping. I know I can fix this with Ctl+L but then whole content will be cleaned.
![Screenshot from 2020-04-29 07-31-39](https://user-images.githubusercontent.com/31184453/80554876-2be5f780-89ec-11ea-98cf-7743d49bcd28.png)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#horrific-mess-when-resizing-terminal-window
