### ISSUE TITLE
[Feature Request] restore last options in p10k configure 

### ISSUE THREAD

**Issue by Gerrit-K** [romkatv/powerlevel10k#672]
I already like p10k _very_ much and never regret switching from p9k ever since. One thing I still find a bit inconvenient though is the update process.

I'm checking for updates once a day and install the changes automatically. However, I still have to call `p10k configure` after updating and there I have to remember and type in all the configuration options I've provided to the last call of the configuration command.

As far as I know, p10k persists the selected options within the generated config file. Would it be possible to reload them on the next call to `p10k configure` and either (1) apply them silently, or (2) prompt the user to apply them or (3) provide them as defaults so that the user just has to hit enter?

**Comment by romkatv** [comment]
Call `p10k configure` only when you want to change your prompt. You don't need to call it after updating powerlevel10k.

**Comment by Gerrit-K** [comment]
Thanks for the quick response! I see, but calling `p10k configure` sometimes results in a significant difference in the `.p10k.zsh` file, depending on the number of changes done in the main repo between the updates. Those differences not only include comments but also code, so I'm wondering if not reconfiguring every now and then could lead to inconsistencies between the config and the plugin or to new features simply not being displayed.

**Comment by romkatv** [comment]
If you do not run `p10k configure`, you prompt will keep working just as it does forever. It may become faster after updating powerlevel10k but it will look the same as before.

The only purpose of running `p10k configure` is to change your prompt. If you want to change your prompt, then go ahead and run it. If you don't want to change your prompt, then don't run it. It's really that simple.
