### ISSUE TITLE
Have VCS icons been replaced by simple symbols?

### ISSUE THREAD

**Issue by ShaneTian** [romkatv/powerlevel10k#673]
In `~/.p10k.zsh`, I found:
```zsh
POWERLEVEL9K_VCS_UNTRACKED_ICON="?"

# ...

# *42 if have stashes.
(( VCS_STATUS_STASHES        )) && res+=" ${clean}*${VCS_STATUS_STASHES}"
# 'merge' if the repo is in an unusual state.
[[ -n $VCS_STATUS_ACTION     ]] && res+=" ${conflicted}${VCS_STATUS_ACTION}"
# ~42 if have merge conflicts.
(( VCS_STATUS_NUM_CONFLICTED )) && res+=" ${conflicted}~${VCS_STATUS_NUM_CONFLICTED}"
# +42 if have staged changes.
(( VCS_STATUS_NUM_STAGED     )) && res+=" ${modified}+${VCS_STATUS_NUM_STAGED}"
# !42 if have unstaged changes.
(( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
# ?42 if have untracked files. It's really a question mark, your font isn't broken.
# See POWERLEVEL9K_VCS_UNTRACKED_ICON above if you want to use a different icon.
# Remove the next line if you don't want to see untracked files at all.
(( VCS_STATUS_NUM_UNTRACKED  )) && res+=" ${untracked}${(g::)POWERLEVEL9K_VCS_UNTRACKED_ICON}${VCS_STATUS_NUM_UNTRACKED}"
```

It is a count after the corresponding symbol (such as `*`, `~`, `+`, `?`), so is it not suitable to use icon (such as `\uF06A`, `\uF059`, `\uF055`)? And author didn't leave corresponding settings.

Neither `MelsoLGS NF` nor `Hack Nerd Font` font can automatically change to icons.

Thank you!

**Comment by romkatv** [comment]
If you want to use `\uF06A` instead of `!`, change this line:

```zsh
(( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}!${VCS_STATUS_NUM_UNSTAGED}"
```

To this:

```zsh
(( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}"$'\uF06A'"${VCS_STATUS_NUM_UNSTAGED}"
```

**Comment by ShaneTian** [comment]
Thank you~
It is ok by:
```zsh
(( VCS_STATUS_NUM_UNSTAGED   )) && res+=" ${modified}"$'\uF06A '"${VCS_STATUS_NUM_UNSTAGED}"
```

Maybe it's convenient to set these as variables in original repo?

**Comment by romkatv** [comment]
Circled `!`, `?` and `+` have no advantages over plain `!`, `?` and `+`. They are much more difficult to distinguish. You are free to use any icons you like of course.

**Comment by onaforeignshore** [comment]
With the caveat that every time you have new updates, the user will have to go make the changes again

**Comment by romkatv** [comment]
> With the caveat that every time you have new updates, the user will have to go make the changes again

`~/.p10k.zsh` is your personal config. You can generate one with `p10k configure` and then edit it to your liking, or you can write one form scratch. If you keep that config, your prompt will look and function the same way forever even if you update powerlevel10k. You don't need to change anything after you update powerlevel10k (unless you want to change your prompt).

**Comment by onaforeignshore** [comment]
Sorry, blonde moment there :)
