### ISSUE TITLE
Terminal "arrow" is shifted 

### ISSUE THREAD

**Issue by moojek** [romkatv/powerlevel10k#675]
As in photo below (maybe you will have to zoom it) the left prompt ending is shited to the up.
![image](https://user-images.githubusercontent.com/42188458/80655938-33ef7700-8a80-11ea-8516-de9ac0bc9b35.png)
I want to believe it is not intended. How can I fix that?

[My config file](https://gist.github.com/moojek/df373a1e485a6a9e60619ef4a142454e)

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#sub-pixel-imperfections-around-powerline-symbols
