### ISSUE TITLE
Color config for *_SEGMENT_START_SYMBOL ?

### ISSUE THREAD

**Issue by Fubuchi** [romkatv/powerlevel10k#677]
I see there are config for which symbols are used for segment start and segment end (like POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL).

However, I didn't see any config to custom color for these elements.

**Comment by romkatv** [comment]
```zsh
POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%F{red}this is red%f'
```
