### ISSUE TITLE
extra trailing space on right prompt in 10k vs 9k

### ISSUE THREAD

**Issue by mr-salty** [romkatv/powerlevel10k#68]
Thanks for the quick fix to #67 - I just noticed something similar where there's an extra space at the end of my right prompt.  The screenshot shows 9k vs 10k (which is up to date - 154bc2e1ff9a435f8686962d5a8e88e6e63ff453)  It's a pretty minor issue and I'm happy to take a crack at fixing it myself.

![trailing space 9v10](https://user-images.githubusercontent.com/7683836/57653541-10e26380-75a0-11e9-919d-6a403b8172b8.png)

**Comment by mr-salty** [comment]
ah, I meant to say I have `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS="status time"`
and, as before `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS="dir dir_writable vcs newline background_jobs root_indicator"`

**Comment by romkatv** [comment]
It's one of those deviations from 9k that I just cannot force myself to fix. The behavior of 9k seems broken to me.

From [ZSH docs](http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-ZLE_005fRPROMPT_005fINDENT):

> `ZLE_RPROMPT_INDENT <S>`
> 
> If set, used to give the indentation between the right hand side of the right prompt in the line editor as given by RPS1 or RPROMPT and the right hand side of the screen. If not set, the value 1 is used.
> 
> Typically this will be used to set the value to 0 so that the prompt appears flush with the right hand side of the screen.

Powerlevel10k respects this parameter. If you set `ZLE_RPROMPT_INDENT=1` (or leave it unset, which is the same thing as setting it to 1), you'll get an empty space to the right of the right prompt. If you set `ZLE_RPROMPT_INDENT=0`, your prompt will go to the edge of the terminal. This is how it works with every theme that doesn't go out of its way to defy `ZLE_RPROMPT_INDENT`.

Powerlevel9k is special.

- With `ZLE_RPROMPT_INDENT=1` it looks the way it's supposed to look with `ZLE_RPROMPT_INDENT=0`. That is, the right prompt goes to the very edge of the terminal.
- With `ZLE_RPROMPT_INDENT=0` the right prompt is truncated. This can be clearly seen by comparing how the left and the right prompts look like on the edges of the terminal.
- With `ZLE_RPROMPT_INDENT=2` or any other value above `1` the background of the right prompt still goes to the edge of the screen. This is rather surprising.

If you want `RPROMPT` to reach the end of the screen, you can define `ZLE_RPROMPT_INDENT=0` and get the documented effect with every theme (except Powerlevel9k).

P.S.

I also highly recommend ditching background colors altogether. Something like [Pure Power](https://github.com/romkatv/dotfiles-public/blob/master/.purepower).

![Pure Power](https://raw.githubusercontent.com/romkatv/dotfiles-public/master/dotfiles/purepower.png)

Prompts without background are better at emphasizing things that are important and not drawing needless attention to fluff.

**Comment by mr-salty** [comment]
ok - I agree with your logic, and I'm happy to use the workaround... well, except that when I changed it, it also lost a space after the left prompt ;)  I'll see if I can figure it out.

![rprompt 0](https://user-images.githubusercontent.com/7683836/57659885-003ae900-75b2-11e9-9d04-b9220310be8a.png)

I'm new to zsh - I've been using csh/tcsh my whole life... so, I've been kind of enjoying the colors and whatnot, but I'm also open to playing around.

**Comment by romkatv** [comment]
> when I changed it, it also lost a space after the left prompt ;)

Yes, there is a bug in ZSH that does this. You can see it in action without any theme:

```zsh
ZLE_RPROMPT_INDENT=0 PROMPT='12' RPROMPT='3' zsh -df
```

If you remove `ZLE_RPROMPT_INDENT` or `RPROMPT` from this command, the bug won't trigger.

There are two workarounds. The first is to add an extra space to `PROMPT`.

```zsh
ZLE_RPROMPT_INDENT=0 PROMPT='12 ' RPROMPT='3' zsh -df
```

Translated to Powerlevel9k/10k it'll look like this:

```zsh
# Two spaces instead of the default single space to counter
# the bug in ZSH that causes the cursor position in the prompt
# to be one character to the left of the correct position when
# ZLE_RPROMPT_INDENT is set to 0.
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR='  '
```

This workaround doesn't work when you are modifying multi-line input (you'll get the first character duplicated).

Another workaround is to set `ZLE_RPROMPT_INDENT=-1`. This has the downside of adding an empty line below your prompt (it might have other undesired side-effects; I wouldn't know as I don't use it). Another problem with this workaround is that it doesn't work with multi-line prompts. Since you are using a multi-line prompt, this workaround is out.

Please also be aware that there are broken terminals out there (e.g., Command Prompt on Windows -- the fastest terminal you can use with WSL) that behave with `ZLE_RPROMPT_INDENT=1` as they should behave with `ZLE_RPROMPT_INDENT=0`. If you set `ZLE_RPROMPT_INDENT=0`, these terminals will eat the last character of `RPROMPT`.

My personal preference is to not tweak `ZLE_RPROMPT_INDENT` to avoid exposing myself to all these bugs. It looks fine IMO.

**Comment by mr-salty** [comment]
Heh, thanks again for the detailed explanation. It sounds like you're uncomfortably familiar with every little quirk of zsh ;).  it's somewhat concerning that these issues don't get fixed upstream, though...  I guess I don't really know what state it's in maintenance wise.

**Comment by romkatv** [comment]
> It sounds like you're uncomfortably familiar with every little quirk of zsh ;)

I'm really a beginner at ZSH. Wrote my first line of ZSH less than 3 months ago.

> it's somewhat concerning that these issues don't get fixed upstream, though...

To be fair, I had pretty good experience with upstreaming fixes to ZSH. The tools and processes they use are somewhat dated (no issue tracked; you send patches by posting a diff to a mailing list) but the core devs are responsive (basically, Peter Stephenson).

This particular bug is likely not too difficult to fix. ZLE code is well-structured and easy to read. Compiling ZSH is easy, too.

> I guess I don't really know what state it's in maintenance wise.

My impression is that ZSH is much buggier than Bash. This can at least partly be explained by its much faster pace of innovation and larger feature set.

**Comment by romkatv** [comment]
FYI: I sent a patch to ZSH devs to fix cursor position when `ZLE_RPROMPT_INDENT=0`: https://www.zsh.org/mla/workers//2019/msg00357.html.

**Comment by romkatv** [comment]
FYI: I changed the way the right prompt is rendered when `POWERLEVEL9K_PROMPT_ON_NEWLINE=true` and `POWERLEVEL9K_RPROMPT_ON_NEWLINE=false` (this is a great combination by the way). The new code can render the prompt correctly with `ZLE_RPROMPT_INDENT=0` even with broken versions of ZSH and broken terminals.

**Comment by romkatv** [comment]
FYI: My fix for the ZSH bug I mentioned earlier has been merged. In addition, I've implemented a workaround in Powerlevel10k for this bug.

If you update powerlevel10k, your cursor should behave correctly even if you set ZLE_RPROMPT_INDENT=0. Please let me know whether it works for you.

**Comment by mr-salty** [comment]
Hi, sorry for the delay - I tried this right after you sent the last update but didn't have time to investigate it.

When using ZLE_RPROMPT_INDENT=0 in 10k, the issue with the cursor being up against the left (https://github.com/romkatv/powerlevel10k/issues/68#issuecomment-492019276) is fixed, but there's still an extra space on the right compared to 9k:

![indent-July1](https://user-images.githubusercontent.com/7683836/60458409-8bc51380-9c0c-11e9-8583-91a2ea0f3343.png)

FYI at some point my TIME_BACKGROUND got changed to black so it wasn't obvious, I set it to 237 to make it grey-ish again. For 9k, `ZLE_RPROMPT_INDENT=0` is flush against the edge and for >0 it adds grey (237) spaces.  For 10k, setting it to 0 leaves one grey space, and >0 adds additional black spaces. 

Note I do *not* have an updated zsh, I'm still running 5.5.1, I can try to build a version with your fix, I'm not sure if it will change anything (at least for 10k, for 9k I assume it fixes the cursor position).  In any case, I've mostly gotten used to it.

```
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs newline background_jobs root_indicator)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_TIME_BACKGROUND='237'
```

**Comment by mr-salty** [comment]
FYI your [suggestion](https://github.com/romkatv/powerlevel10k/issues/68#issuecomment-496293872) really weird stuff for me in both 9k and 10k.  
```
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
```
![indent-1July2](https://user-images.githubusercontent.com/7683836/60459018-080c2680-9c0e-11e9-9840-6cd9b6ae7c47.png)

I ordinarily have them both `false`, and actually I get the same behavior shown above if I set `POWERLEVEL9K_PROMPT_ON_NEWLINE=true` regardless of the `POWERLEVEL9K_RPROMPT_ON_NEWLINE` setting.

**Comment by romkatv** [comment]
When you set `ZLE_RPROMPT_INDENT=0`, the left and the right sides of the screen must become symmetric. And they are symmetric when using Powerlevel10k. Powerlevel9k, on the other hand, truncates the last segment on the right (but not on the left). That grey space is a part of the time segment. The segment right before it also has has space. In fact, every segment on the right has a space after, and every segment on the left has a space before.

**Comment by mr-salty** [comment]
ok, that sounds plausible.  FWIW, here's an illustration of what happens with >1 that I tried to describe, although I think the 10k behavior is probably more correct.

![indent-1July3](https://user-images.githubusercontent.com/7683836/60459415-1eff4880-9c0f-11e9-9b2c-53eb59514778.png)

**Comment by romkatv** [comment]
> FYI your suggestion really weird stuff for me in both 9k and 10k.

To be honest, you have a very unusual configuration, so it looks weird to me no matter what. That extra line in the prompt that most of the time has no segments is something I've never seen anyone do. The powerline rendering isn't working with your font, so right prompt looks patched up.

I think if you try Pure Power config, you'd get decent mileage out of it. It's optimized with very high attention to detail (I use it myself). It gives you a much better starting point.

**Comment by romkatv** [comment]
> ok, that sounds plausible. FWIW, here's an illustration of what happens with >1 that I tried to describe, although I think the 10k behavior is probably more correct.

Yes, Powerlevel10k has the expected behavior. You can see it with your own simple prompt. Start up `RPROMPT='%K{blue} hello %k' zsh -df` and then see how it looks with different values of `ZLE_RPROMPT_INDENT`.

**Comment by mr-salty** [comment]
ok, sgtm...

I may play around with my prompt a little, I kinda got the idea from [this](https://github.com/bhilburn/powerlevel9k/wiki/Stylizing-Your-Prompt) but I guess having all the segments disappear is weird.
