### ISSUE TITLE
MacOS Mojave Terminal fail

### ISSUE THREAD

**Issue by gisborne** [romkatv/powerlevel10k#680]
$ source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
-bash: local: can only be used in a function
-bash: builtin: setopt: not a shell builtin
-bash: ((: $+__p9k_root_dir : syntax error: operand expected (error token is "$+__p9k_root_dir ")
-bash: ${${(%):-%x}:A:h}: bad substitution
-bash: ((: $+__p9k_intro : syntax error: operand expected (error token is "$+__p9k_intro ")
-bash: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
-bash: typeset: -g: invalid option
typeset: usage: typeset [-afFirtx] [-p] name[=value] ...
-bash: ${${__p9k_intro_base/ match / match reply }/ MATCH / MATCH REPLY }: bad substitution
-bash: zmodload: command not found
-bash: /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme: line 44: syntax error near unexpected token `)'
-bash: /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme: line 44: `() {'

**Comment by romkatv** [comment]
Powerlevel10k is a zsh theme. For bash you'll need to use something else.
