### ISSUE TITLE
command_execution_time: filter commands

### ISSUE THREAD

**Issue by scrouthtv** [romkatv/powerlevel10k#681]
Is there any possibility to blacklist some commands from being printed in `command_execution_time`?

My problem is that I use `vim` a lot from my console but I don't really care about the time I spent in it. Can I disable the `command_execution_time` module for certain commands, like `vim`?

**Comment by romkatv** [comment]
> My problem is that I use `vim` a lot

We've all been there. Hang on!

Can I disable the `command_execution_time` module for certain commands, like `vim`?

Sure.

```zsh
# This function is called by powerlevel10k before every prompt.
function p10k-on-pre-prompt() {
  emulate -L zsh
  local cmd=$history[$#history]
  if [[ $cmd == vim* ]]; then
    # If the last command starts with "vim", hide command_execution_time.
    p10k display '*/command_execution_time'=hide
  else
    # Otherwise show command_execution_time.
    p10k display '*/command_execution_time'=show
  fi
}
```

Customize the test as you like.

Type `p10k help display` for documentation.

**Comment by scrouthtv** [comment]
thank you very much!
