### ISSUE TITLE
Little triangle/arrow appearing at the left side of each line

### ISSUE THREAD

**Issue by guiemi** [romkatv/powerlevel10k#682]
I have this annoying light blue arrow at each line since I switched from 9k to 10k. Does someone know how to make it disappear?

macOS Catalina + iTerm2 here

![Screen Shot 2020-05-02 at 02 22 46](https://user-images.githubusercontent.com/24235344/80855933-d2640f80-8c1b-11ea-9121-b6056a1152fc.png)

**Comment by romkatv** [comment]
See https://www.google.com/amp/s/amp.reddit.com/r/zsh/comments/f9tzld/left_prompt_oddity/

**Comment by guiemi** [comment]
Oh thank you <3
