### ISSUE TITLE
Expansions in PROMPT_EOL_MARK are not performed when dumping instant prompt

### ISSUE THREAD

**Issue by cptpcrd** [romkatv/powerlevel10k#683]
*Background: I don't like Zsh's how `prompt_cr`/`prompt_sp` feature handles window resizing after an incomplete output line, so I have some custom hooks that mess around to make it a little saner. (I know, my setup is weird.) This system requires evaluating some things dynamically, so I put a brace expansion in `PROMPT_EOL_MARK` that calls a function to determine what should be output.*

Zsh expands parameter expansions in `PROMPT_EOL_MARK`. However, when Powerlevel10k saves `PROMPT_EOL_MARK` [while dumping the instant prompt](https://github.com/romkatv/powerlevel10k/blob/fdb0bb6af70c0ee70454fe456b4b40a9bba15118/internal/p10k.zsh#L5610), it does not perform expansions. As a result, if the `PROMPT_EOL_MARK` variable contains any expansions, the value as saved to the instant prompt dump file contains the raw, unexpanded version. When the instant prompt script prints out `PROMPT_EOL_MARK` [here](https://github.com/romkatv/powerlevel10k/blob/fdb0bb6af70c0ee70454fe456b4b40a9bba15118/internal/p10k.zsh#L5823) (and probably a few other places), it outputs the raw expansion, which can be rather ugly.

I think that changing the first line linked above (line 5610) to `local PROMPT_EOL_MARK=${(q)${(e)PROMPT_EOL_MARK-%B%S%#%s%b}}` (maybe this can be improved; I'm not good with Zsh expansions) would force expansion of variables in `PROMPT_EOL_MARK`  before saving the file. This *shouldn't* break backwards compatibility, since Zsh expands `PROMPT_EOL_MARK` in normal use. (However, if backwards compatibility is a concern, maybe this functionality could be optional?)

This may seem like an edge case (and perhaps it is), but I would argue it should be fixed because it is a scenario in which the behavior of Powerlevel10k's instant prompt diverges from Zsh's normal prompt behavior.

**Comment by romkatv** [comment]
Thanks for the report! Should be fixed now. Please verify.

P.S.

In the future please include instructions how to reproduce.

**Comment by cptpcrd** [comment]
Confirmed working. Sorry about not including reproducible instructions; will try do that in the future.

**Comment by romkatv** [comment]
Thanks for the confirmation.

And once again thanks for the superb analysis on this issue. Took me just a few minutes to implement a fix. Repro instructors are a good idea in general but in this case their lack hasn't hindered me.
