### ISSUE TITLE
Lighter head colours in Terminal

### ISSUE THREAD

**Issue by mxdvl** [romkatv/powerlevel10k#685]
Unlike most screenshots I’ve seen so far, the heads are showing a lighter colour that the rest of the segments. I have not seen this reported anywhere else.

![image](https://user-images.githubusercontent.com/76776/80916774-bdd66300-8d52-11ea-98b9-c5f3ba08d8be.png)

**Comment by romkatv** [comment]
Check your terminal settings. This has something to do with transparency or contrast.

**Comment by rickgorman** [comment]
Ran into this with iterm2. I was able to fix it by making sure that "Keep background colors opaque" is checked.
<img width="283" alt="image" src="https://user-images.githubusercontent.com/4432541/219976045-5760270b-847d-4573-bf64-79ea5e3ec769.png">
