### ISSUE TITLE
Match generic name pattern

### ISSUE THREAD

**Issue by cbows** [romkatv/powerlevel10k#686]
I have a tool that generates virtual environments that include the Python version name, like for example `python-3.7.7` or `python-3.8.2`.

Is there a way to match these with `POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES`?

Example:
```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=(virtualenv venv .venv env python-*)
```
should match the regular generic names plus all names starting with `python-`.

**Comment by romkatv** [comment]
Sounds useful. I'll implement it when I get free time. No ETA.

**Comment by romkatv** [comment]
This is done. To use this feature, make sure to quote patterns.

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_GENERIC_NAMES=(
  'virtualenv' 'venv' '.venv' 'env' 'python-*')
```

Note that `'python-*'` is quoted.

**Comment by cbows** [comment]
Awesome thank you!

By the way, can you recommend any modern zsh tutorial or other resources to learn the specifics of zsh?

**Comment by romkatv** [comment]
The official guides are pretty good.
