### ISSUE TITLE
gitstatus error since last update

### ISSUE THREAD

**Issue by MichaelAquilina** [romkatv/powerlevel10k#689]
I've just updated to the latest version of powerlevel10k (using `zplug update`) and I'm not receiving the following error on startup:
```
[ERROR]: gitstatus failed to initialize.                                                                                       

  Your Git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K

  If this command produces no output, add the following parameter to ~/.zshrc:

    GITSTATUS_LOG_LEVEL=DEBUG

  With this parameter gitstatus will print additional information on error.
```

Running `GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 POWERLEVEL9K` shows the following output:

https://gist.github.com/MichaelAquilina/354775e168ad6e0c87ea44827d16eb5d

**Comment by romkatv** [comment]
Wow. So on your system `cd` is a function whose behavior is not the same as of posix `cd`?

**Comment by MichaelAquilina** [comment]
`which cd` says its a shell built in so I dont think so :thinking: 

I'm running on opensuse Tumbleweed 
zsh 5.8

You could probably reproduce the same behaviour in a docker container (`docker run opensuse/tumbleweed`)

**Comment by romkatv** [comment]
> `which cd` says its a shell built in so I dont think so 

It may be now, but it 100% was a function when you captured the log.

I've pushed a workaround to survive this. Please update powerlevel10k and try again.

**Comment by romkatv** [comment]
Oh, perhaps it was a chpwd hook? Hold on.

**Comment by romkatv** [comment]
OK, added another workaround to survive chpwd hooks that interfere with scripts.

**Comment by MichaelAquilina** [comment]
>OK, added another workaround to survive chpwd hooks that interfere with scripts.

If you are referring to the `_venv` related stuff, its actually a plugin that is doing that.

https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv

Coincidentally the plugin is one that I maintain so I'm happy to help improve the situation if needed?

**Comment by MichaelAquilina** [comment]
PS: latest update works as you said

**Comment by romkatv** [comment]
> If you are referring to the `_venv` related stuff

Yes.

> its actually a plugin that is doing that.

Figured.

> I'm happy to help improve the situation if needed?

When `cd` prints to stdout, it can break scripts. For example:

```zsh
function compute-stuff() {
  mkdir /tmp/foo
  cd /tmp/foo
  ...
}

stuff=$(compute-stuff)  # `stuff` contains garbage
```

It's a good idea to not print to stdout from your hooks into primitive ops.

**Comment by romkatv** [comment]
> PS: latest update works as you said

Thanks for the confirmation!

**Comment by MichaelAquilina** [comment]
> It's a good idea to not print to stdout from your hooks into primitive ops.

Unfortunately that's a feature I dont think that can be worked round. In this case the plugin is just displaying a message when the python virtual environment is being swapped. In this case the hook is just the standard zsh `chpwd` hook because it determines if a virtual environment needs to be activated or deactivated based on the current directory:

 https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv/blob/master/autoswitch_virtualenv.plugin.zsh#L327

In a similar way, another plugin I maintain also prints messages using hooks (I guess including cd) but this time it uses preexec and postexec https://github.com/MichaelAquilina/zsh-you-should-use/blob/master/you-should-use.plugin.zsh#L256-L260

I guess my question to you would be, is there a way for these to play nicer without breaking their functionality?

**Comment by romkatv** [comment]
Do these messages have to go to stdout? Can they go to stderr or `$TTY` instead?

**Comment by MichaelAquilina** [comment]
> Do these messages have to go to stdout? Can they go to stderr or $TTY instead?

They can and *should*. If they dont its probably a mistake on my end. Will check this out in the evening and release a fix if thats the case.
