### ISSUE TITLE
"closing brace expected" spam

### ISSUE THREAD

**Issue by thriskel** [romkatv/powerlevel10k#691]
This is kind of clone of [this](https://github.com/romkatv/powerlevel10k/issues/443) issue,

I found myself having this error, my zsh is kinda broken now, it happened after I typed this command:
`python2 -m timeit -s "[x for x in range(100000000)]"`
and then used `^C` after 2 min while it was still running.

**Comment by romkatv** [comment]
How to reproduce?

**Comment by thriskel** [comment]
While in the powerlevel10k zsh, use the command `python2 -m timeit -s "[x for x in range(10000000000)]"` (add enough 0's so it prompts you memory error, and then delete a couple so it can be run) wait until your machine is slowing down and cancel it with ctrl+c.
It should break it.

**Comment by romkatv** [comment]
Are you using zplugin?

What are the errors?

What do the errors say?

Do they persist if you restart zsh?

Please do what https://github.com/romkatv/powerlevel10k/issues/443#issuecomment-578949347 suggests.

**Comment by thriskel** [comment]
I am not using zplugins,
the errors are spamming of these:

> "(anon):152: closing brace expected"
> "zsh: closing brace expected"
> "_zsh_highlight_main__type:53: closing brace expected"

Yes, they do persist after restarting zsh and computer.

I did try to update the repos, but it wouldn't fix the issue,

**Comment by romkatv** [comment]
Please run the following command:

```zsh
zsh -f --extendedglob
```

Then run this:

```zsh
tar -czf /tmp/configs.tar.gz ${ZDOTDIR:-~}/.{zshenv,zprofile,zshrc,zlogin,zlogout,p10k.zsh}(N) ~/.cache/p10k-*(N)
```

(If it prints a warning saying "tar: Removing leading '/' from member names", that fine. You can ignore it.)

When the command completes, attach `/tmp/configs.tar.gz` to this issue.

**After that** run `sudo rm -rf ~/.cache/p10k-*`. Let me know if this fixes zsh for you.

**Comment by thriskel** [comment]
here you have it.
[configs.tar.gz](https://github.com/romkatv/powerlevel10k/files/4585974/configs.tar.gz)

The last command did fix zsh.

**Comment by romkatv** [comment]
Thanks! I'll dig into it.

**Comment by romkatv** [comment]
I've analysed the data you've posted and as expected there are some corrupted cache files. I wasn't able to figure out how exactly this corruption came about but did nonetheless make several changes that should make code generally less prone to this sort of problem. If you ever see the same errors, please ping this issue or open another one. Run the same command as last time (see https://github.com/romkatv/powerlevel10k/issues/691#issuecomment-624532633) to create a state dump and attach it.

I also noticed that your powerlevel10k is quite old. It's a good idea to update to pick up bug fixes and various improvements. You can update with this command:

```zsh
git -C $ZSH_CUSTOM/themes/powerlevel10k pull && exec zsh
```

**Comment by Danisan** [comment]
[configs.tar.gz](https://github.com/romkatv/powerlevel10k/files/5258776/configs.tar.gz)

Here is mine

**Comment by romkatv** [comment]
@Danisan You are using a very old version of Powerlevel10k. It's a good idea to [update it](https://github.com/romkatv/powerlevel10k/#how-do-i-update-powerlevel10k).

**Comment by billoway** [comment]
[configs.tar.gz](https://github.com/romkatv/powerlevel10k/files/9893540/configs.tar.gz)
Here is mine

**Comment by romkatv** [comment]
@billoway If something doesn't work as you expect, file an issue.

**Comment by billoway** [comment]
> @billoway If something doesn't work as you expect, file an issue.

zsh: closing brace expected

**Comment by romkatv** [comment]
> @billoway If something doesn't work as you expect, file an issue.

☝️

**Comment by billoway** [comment]
> > @billoway If something doesn't work as you expect, file an issue.
> 
> ☝️

Sorry, it seems that "jonathan" cannot work.
