### ISSUE TITLE
Port 9k's chruby segment into 10k

### ISSUE THREAD

**Issue by aserrallerios** [romkatv/powerlevel10k#692]
Any hope on having it back?

**Comment by romkatv** [comment]
Powerlevel10k has all prompt segments that powerlevel9k has.

If you have a working powerlevel9k config, it'll work with powerlevel10k, too. You might need to add these extra parameters to have the same whitespace as before:

```zsh
ZLE_RPROMPT_INDENT=0
POWERLEVEL9K_LEGACY_ICON_SPACING=true
```

See FAQ: [Extra or missing spaces in prompt compared to Powerlevel9k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#extra-or-missing-spaces-in-prompt-compared-to-powerlevel9k).
