### ISSUE TITLE
Incompatible with zsh-syntax-highlighting?

### ISSUE THREAD

**Issue by proteo** [romkatv/powerlevel10k#693]
Hi there. First of all many thanks for your hard work on this, I'm loving pl10k! 

I've found an issue when trying to use it along with the zsh-syntax-highlighting plugin. I've installed zsh-syntax-highlighting directly in my `~/.zshrc` file [as described in their readme file](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#in-your-zshrc).  In the readme they say that you must source the file at the end of `.zshrc`.

But whenever it's enabled, the powerlevel10k prompt stops working, in the meaning that it won't be updated anymore. Changing directories, running commands, etc. will not change the prompt at all. It will remain exactly the same as when you first open the session. 

Let me know if you need me to provide additional info or perform some debugging for you.

- macOS 10.14.6
- iTerm2
- oh-my-zsh
- powerlevel10k installed according to [this](https://github.com/romkatv/powerlevel10k#oh-my-zsh).

**Comment by romkatv** [comment]
Please list all steps necessary to reproduce this.

**Comment by proteo** [comment]
Sure:

1. Install oh-my-zsh using the "Basic Installation" [described here](https://github.com/ohmyzsh/ohmyzsh#basic-installation).
2. Install zsh-syntax-highlighting in your `.zshrc` file as [described here](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#in-your-zshrc).
3. Test:
`cd /new/directory`
Will display `/new/directory` in the prompt.
`cd /directory/with/git_repo`
Will display vcs info in the prompt.
4. Install powerlevel10k following [this instructions](https://github.com/romkatv/powerlevel10k#oh-my-zsh).
5. Restart iTerm2.

Result:

`cd /new/directory`
Will display the same dir (~) in the prompt.
`cd /directory/with/git_repo`
Will not display any vcs info in the prompt.

6. Disable zsh-syntax-highlighting commenting the line `source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh `in your  `.zshrc` file.
7. Restart iTerm2.

Result:

`cd /new/directory`
Will display `/new/directory` in the prompt.
`cd /directory/with/git_repo`
Will display vcs info in the prompt.

**Comment by romkatv** [comment]
I cannot reproduce this following your instructions.

Please attach `~/.zshrc` and `~/.p10k.zsh` to this issue.

**Comment by proteo** [comment]
Thanks, here they are:

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4588750/p10k.txt)

[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/4588754/zshrc.txt)

**Comment by proteo** [comment]
Here's a quick example of the issue. As you can see, the prompt won't change at all:

![p10k](https://user-images.githubusercontent.com/376077/81215851-f28f2800-8fa7-11ea-9a7b-80cae569e009.gif)

**Comment by romkatv** [comment]
Your `.zshrc` doesn't match the instructions you've provided earlier. If I fix the instructions or `.zshrc` to make them match, I cannot reproduce the issue. Can *you* reproduce it by following your own instructions? Here's a command that you can run to test it. Once it opens shell, type `cd /`. Does the current directory change in prompt?

```zsh
() (
  emulate -L zsh -o err_return -o pushd_silent
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    pushd -q -- $tmp
    curl -fsSLo .p10k.zsh https://github.com/romkatv/powerlevel10k/files/4588750/p10k.txt
    curl -fsSLo .zshrc https://github.com/romkatv/powerlevel10k/files/4588754/zshrc.txt
    sed -i.bak -E 's/\$HOME|~/\$ZDOTDIR/g' .zshrc
    git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git .oh-my-zsh
    pushd -q -- .oh-my-zsh/custom
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
    git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting
    git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git plugins/zsh-autosuggestions
    popd -q
    popd -q
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```

**Comment by proteo** [comment]
I deleted all my current configuration files, restarted iTerm and ran your command. Unfortunately, the issue remains exactly the same:

![Screen Shot 2020-05-06 at 15 11 42](https://user-images.githubusercontent.com/376077/81218268-f0c76380-8fab-11ea-9aab-2182fb33f0af.png)

**Comment by romkatv** [comment]
> I deleted all my current configuration files, restarted iTerm

Wow. That wasn't necessary. Please follow the instructions exactly otherwise it'll take forever. In addition to executing extra steps you've changed some. I asked to type `cd /` but you've typed something else. Let's try again.

Please do the following:

1. Run this command (it's the same as last time):
```
() (
  emulate -L zsh -o err_return -o pushd_silent
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    pushd -q -- $tmp
    curl -fsSLo .p10k.zsh https://github.com/romkatv/powerlevel10k/files/4588750/p10k.txt
    curl -fsSLo .zshrc https://github.com/romkatv/powerlevel10k/files/4588754/zshrc.txt
    sed -i.bak -E 's/\$HOME|~/\$ZDOTDIR/g' .zshrc
    git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git .oh-my-zsh
    pushd -q -- .oh-my-zsh/custom
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
    git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting
    git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git plugins/zsh-autosuggestions
    popd -q
    popd -q
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```
2. Type `cd /`.
3. What's the current directory in prompt?

**Comment by proteo** [comment]
Oops, sorry. I didn't realize the last part was meaningful. Ran the command again, ran `cd` as asked and it says:

`cd: no such file or directory: .Users/proteo`

**Comment by romkatv** [comment]
So `cd /` doesn't work for you? Fascinating. Do you have any idea why?

**Comment by proteo** [comment]
Damn, sorry again. Ran `cd` with the dot. Running just `cd /` doesn't change the prompt, still at `~`.

![Screen Shot 2020-05-06 at 15 27 40](https://user-images.githubusercontent.com/376077/81219672-21a89800-8fae-11ea-966b-f0f8e0fbfbdd.png)

**Comment by romkatv** [comment]
Please run this command and attach `/tmp/p10k.txt` when it finishes.

```zsh
() (
  emulate -L zsh -o err_return -o pushd_silent
  cd -q
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    pushd -q -- $tmp
    curl -fsSLo .p10k.zsh https://github.com/romkatv/powerlevel10k/files/4588750/p10k.txt
    curl -fsSLo .zshrc https://github.com/romkatv/powerlevel10k/files/4588754/zshrc.txt
    sed -i.bak -E 's/\$HOME|~/\$ZDOTDIR/g' .zshrc
    git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh.git .oh-my-zsh
    pushd -q -- .oh-my-zsh/custom
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git themes/powerlevel10k
    git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git plugins/zsh-syntax-highlighting
    git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions.git plugins/zsh-autosuggestions
    popd -q
    popd -q
    ZDOTDIR=$tmp zsh -xis <<\END
cd /
typeset -pm 'ZSH_VERSION|precmd|precmd_functions'
exit
END
  } always {
    cd -q /
    rm -rf -- $tmp
  }
) &>/tmp/p10k.txt
```

**Comment by proteo** [comment]
Here you are:

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4589116/p10k.txt)

**Comment by romkatv** [comment]
Thanks for the logs. It's a bug in zsh-syntax-highlighting. I submitted an issue upstream: https://github.com/zsh-users/zsh-syntax-highlighting/issues/733.

This bug only affects older versions of zsh (this is why I wasn't able to reproduce this on my machine). As mitigation I suggest upgrading zsh to 5.8. You can do this with `brew install zsh`. If you don't have `brew`, see https://brew.sh/. Upgrading zsh to 5.8 is generally a very good idea. It's much faster than what you have and much more stable.

You also need to fix this line in `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION=' $'
```

This parameter has "expansion" in its name for a good reason. Its value undergoes single word expansion. If you want to display `$` instead of the default `❯`, you need to escape it with `\`. Like so:

```zsh
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION=' \$'
```

**Comment by proteo** [comment]
Thank you very much for your support @romkatv. I'll update zsh as suggested.

**Comment by romkatv** [comment]
You are very welcome.

**Comment by romkatv** [comment]
> I submitted an issue upstream: [zsh-users/zsh-syntax-highlighting#733](https://github.com/zsh-users/zsh-syntax-highlighting/issues/733).

FYI: this issue has been fix. I would still recommend that you upgrade zsh to 5.8 though.

**Comment by proteo** [comment]
Thanks @romkatv, I already did! It fixed the issue BTW :)

**Comment by zc62** [comment]
Hi @romkatv, I'm having an issue that transient prompt does not work with syntax-highlighting. It is very strange that:
- It works with my local Mac, even with syntax-highlighting
- My remote linux uses linuxbrew's latest zsh (version 5.9), and I exit and re-login to apply .zshrc changes (just to clarify that I did not source it).

Here I attach the log file according to your instructions. [p10k.txt](https://github.com/romkatv/powerlevel10k/files/9145172/p10k.txt)

**Comment by romkatv** [comment]
@zc62 Please open a new issue and describe it in your own words.
