### ISSUE TITLE
Weird behavior when resizing terminal 

### ISSUE THREAD

**Issue by ariassd** [romkatv/powerlevel10k#694]
Weird behavior when resizing terminal
Powerlevel10K writes a new line with the header 
<img width="1025" alt="Screen Shot 2020-05-06 at 14 42 18" src="https://user-images.githubusercontent.com/2159243/81226283-d7241d00-8fa7-11ea-95ce-89f5abef1381.png">

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window.

**Comment by ariassd** [comment]
I tried uninstalling and installing again OMZ and P10K. The error appears when you configure it for two lines.

<img width="922" alt="Screen Shot 2020-05-07 at 07 57 12" src="https://user-images.githubusercontent.com/2159243/81303354-d4253d00-9038-11ea-914d-6b7a0371bdbe.png">

**Comment by romkatv** [comment]
> I tried uninstalling and installing again OMZ and P10K.

It would be a better use of your time to click the link I posted earlier.

**Comment by Batresh** [comment]
I have the same rezising issue with Multiline. This issue is relevant because the powerlevel10k release for atleast 2 weeks ago had no issue with the exact same configuration

**Comment by Batresh** [comment]
Tested again, works with release 1.7.0.
but not with Git version

**Comment by romkatv** [comment]
@Batresh Which zsh version are you using?

**Comment by Batresh** [comment]
@romkatv zsh 5.8
arch package

**Comment by romkatv** [comment]
Cannot reproduce. zsh 5.8 is equally broken (as described in https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window) when using powerlevel10k v1.7.0 or HEAD. Please do click that link and read what it says. It describes the bug in precise detail.

**Comment by romkatv** [comment]
@Batresh I think with your config you might be hitting a zsh bug in signal handling that exacerbate the bug in resizing. I've pushed a speculative change that might make it better. Please update and give it a try.

**Comment by Batresh** [comment]
@romkatv Yep. The latest fix fixed the issue.
Now can keep my 'PROMPT_ON_NEWLINE=true' line. Very comfy

**Comment by romkatv** [comment]
@Batresh Thanks for the confirmation.

By the way, I don't recommend using `PROMPT_ON_NEWLINE` or `RPROMPT_ON_NEWLINE`. It's more convenient and more flexible to use `POWERLEVEL9K_PROMPT_ADD_NEWLINE` and to add `newline` in appropriate places within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. If you haven't yet run `p10k configure`, it's a good idea to try it.

**Comment by palonza** [comment]
> See https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window.

Hi @romkatv! Could you help me apply this patch? How should i do? I have little experience

**Comment by turingzhi** [comment]
@romkatv Hello, I have same issues, and I read the link(https://github.com/romkatv/powerlevel10k#horrific-mess-when-resizing-terminal-window). But I did not how to Apply [the patch](https://github.com/romkatv/powerlevel10k/issues/694#zsh-patch) and [rebuild Zsh from source](https://github.com/zsh-users/zsh/blob/master/INSTALL) although I read the links. I do not know how to find the directory where I have source code. I use zsh from iterm2.

**Comment by atahabilder1** [comment]
I am also facing this issue, I first thought it was due to not having a dedicated GPU on my PC.
