### ISSUE TITLE
Triangle at left posittion of prompt not showing

### ISSUE THREAD

**Issue by jiwidi** [romkatv/powerlevel10k#696]
Hi! I have installed powerlevel10k with antibody and my terminal looked like this:
![image](https://user-images.githubusercontent.com/10882086/81330638-a673de80-90a0-11ea-864b-eea0b923c90d.png)
I checked I had the correct fonts and I tried with both MesloLGS NF Regular and powerline fonts https://github.com/powerline/fonts but this still happens.

Im using the default terminal prompt from ubuntu with oh-my-zsh and antibody.

Any thoughts on what I missed to install/configure?

Thank you

**Comment by romkatv** [comment]
This is what you've chosen in the configuration wizard, right? So prompt looks as expected.

If you want to change the way your prompt looks like, run `p10k configure`. If you don't see the option that you except to see there, see https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard.

**Comment by jiwidi** [comment]
> This is what you've chosen in the configuration wizard, right? So prompt looks as expected.
> 
> If you want to change the way your prompt looks like, run `p10k configure`. If you don't see the option that you expect to see there, see https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard.

Hey! No I didnt set this option on the configuration wizard. Actually in the wizard it looked correctly. Let me share a screenshot:

![image](https://user-images.githubusercontent.com/10882086/81331471-f3a48000-90a1-11ea-8e95-acb7c5e741b1.png)

**Comment by romkatv** [comment]
Please run the following command and attach `/tmp/p10k.txt` to this issue when it finishes:

```zsh
() {
  emulate -L zsh -o xtrace
  typeset -pm '_p9k__param_pat|POWERLEVEL9K_*|ZSH_VERSION'
  uname -ms
  cat -- /dev/null ${ZDOTDIR:-~}/.zshrc(N) ${ZDOTDIR:-~}/.p10k.zsh(N)
  locale
  locale -a
} &>/tmp/p10k.txt
```

**Comment by FerJEP** [comment]
Hi, I'm having the same issue. I don't even get the triangles within the configuration process.

![Screenshot_2020-12-19_03-35-02](https://user-images.githubusercontent.com/58746156/102683994-3f2c1a00-41ab-11eb-924c-6597a8be84da.png)

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/5719023/p10k.txt)

**Comment by romkatv** [comment]
@FerJEP See https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by FerJEP** [comment]
I actually was reading that. I installed the last zsh version (5.8) and the recommended font. Also ran ```p10k configure```, and now it works, I even had extra configurations. Thanks.

**Comment by xoppyk** [comment]
In .p10k.zsh change 
this lines 
  # The right end of left prompt.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
  # The left end of right prompt.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'

**Comment by darianmorat** [comment]
> In .p10k.zsh change this lines
> 
> # The right end of left prompt.
> typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
> 
> # The left end of right prompt.
> typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'

This is what I was looking for, thanks

**Comment by hohsiangcheng-tomtom** [comment]
> In .p10k.zsh change this lines
> # The right end of left prompt.
> 
> typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
> # The left end of right prompt.
> 
> typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'

Thank you, you are truly a genius.

**Comment by xchehub** [comment]
> In .p10k.zsh change this lines
> 
> # The right end of left prompt.
> typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
> 
> # The left end of right prompt.
> typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'

Thank you, you are truly a genius.
