### ISSUE TITLE
Change font color into first segment (path)

### ISSUE THREAD

**Issue by DaRo0** [romkatv/powerlevel10k#697]
Hello everybody,

This is not an issue, but a question.

I want to change the colour of the first prompt section font. It appears in white, and I want it in black (I'm colour blind and I cannot see the path if it's in a white font).

I checked the config documentation, but after hours of trying (probably I'm a noob) I couldn't find the solution.

I attach a screenshot as I have done the p10k config, and I just want to change that white font colour where the path is displayed to black colour.

![Captura de pantalla 2020-05-08 a las 13 25 06](https://user-images.githubusercontent.com/12486544/81401729-36ad3480-9130-11ea-807c-3664e5d5aafa.png)

Thank you everybody for your help. And I'm sorry if this is a stupid question.

Regards,
Daniel

**Comment by romkatv** [comment]
Have you read this FAQ entry? [How do I change prompt colors?](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-prompt-colors)

What have you tried? Where did you get stuck?

**Comment by DaRo0** [comment]
Hello @romkatv 

Yes, i've read that FAQ entry. I just cannot find the variable name for the path section (the one with the blue background) which configures the font color. This is where I got stuck, I changed many variables but without any luck

**Comment by romkatv** [comment]
Which parameters have you tried changing and to which values?

**Comment by DaRo0** [comment]
Hello @romkatv ,

I've tried:
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND='000'

tried to add:
POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_COLOR='000'

also, with this one:
POWERLEVEL9K_DIR_FOREGROUND='000'

I've just noticed, whit this last one, I can partially change everything that I want, but still the symbol ~ and the current folder appear in white, as shown below:
<img width="460" alt="Captura de pantalla 2020-05-08 a las 14 08 56" src="https://user-images.githubusercontent.com/12486544/81404333-804c4e00-9135-11ea-9a08-f6d395c3ac14.png">


Thank you again for your help

**Comment by romkatv** [comment]
> also, with this one:
> POWERLEVEL9K_DIR_FOREGROUND='000'
> 
> I've just noticed, whit this last one, I can partially change everything that I want, but still the symbol ~ and the current folder appear in white, as shown below:
> <img alt="Captura de pantalla 2020-05-08 a las 14 08 56" width="460" src="https://user-images.githubusercontent.com/12486544/81404333-804c4e00-9135-11ea-9a08-f6d395c3ac14.png">

Nice! You are most of the way there. I'm glad that hours of reading documentation and trying different things weren't fruitless. I encourage you to keep trying.

**Comment by DaRo0** [comment]
Hello @romkatv ,

Oh I can see the irony in your words, you probably think that I just came here without trying anything.

Thank you for your help, I will keep trying

**Comment by romkatv** [comment]
No irony. You've tried to solve this problem on your own and have opened this issue when you've almost succeeded. I encourage you to continue. I'm sure you'll achieve what you are after. Next time it'll be easier.

**Comment by DaRo0** [comment]
Okay, I'm sorry for the misunderstanding.

This is my final result:
<img width="585" alt="Captura de pantalla 2020-05-08 a las 15 33 25" src="https://user-images.githubusercontent.com/12486544/81410601-4b45f880-9141-11ea-8255-3835a282f408.png">


I'll explain something in case that someone has the same questions.

For the first part of the prompt (~) the variable is:
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND

For the directory section:
POWERLEVEL9K_DIR_FOREGROUND

At this point, I'm giving up. As you can see, the anchor color still grey instead of black (And the code that I've placed is 000), also, the last part which is the current folder (auth) is also grey, I cannot manage to change it to black.

I hope that my solution can help somebody, let's see if anybody knows what I could do to still have all the foreground in black.

Thank you everybody and regards,
Daniel

**Comment by romkatv** [comment]
All parameters that control colors of current directory are in this block: https://github.com/romkatv/powerlevel10k/blob/459af1f2382ff53214bf9e4fc598b4e36fb8f8df/config/p10k-rainbow.zsh#L202-L218.

These are the parameters:

```zsh
# Current directory background color.
typeset -g POWERLEVEL9K_DIR_BACKGROUND=4

# Default current directory foreground color.
typeset -g POWERLEVEL9K_DIR_FOREGROUND=254

# Color of the shortened directory segments.
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250

# Color of the anchor directory segments. Anchor segments
# are never shortened. The first segment is always an anchor.
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255

# Display anchor directory segments in bold.
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
```

These parameters do what the comments say.

You've made the foreground color of anchor segments (the first and the last segments on your screenshot, although there can be more) but they are still bold, hence the difference in appearance.

Your screenshot doesn't contain any shortened segments. If you make your terminal window very narrow (or `cd` into a deep directory hierarchy), you'll see them. They'll be white unless you've changed the corresponding parameter.

In general, reading comments and seeing what happens when you change different parameters is the way to go. I'm glad you've managed to change prompt appearance in the direction you wanted.

By the way, **Lean** style is more legible for colorblind users (for everyone, really). Give it a try some day. Just type `p10k configure`.

**Comment by Lane** [comment]
Sorry to resurect a dead thread but I ended up in this thread looking for a solution.

As mentioned earlier, setting these variables will change the colors:

POWERLEVEL9K_DIR_ANCHOR_FOREGROUND
POWERLEVEL9K_DIR_FOREGROUND

> As you can see, the anchor color still grey instead of black (And the code that I've placed is 000), also, the last part which is the current folder (auth) is also grey, I cannot manage to change it to black.

I also had this issue and it may be isolated to iTerm, which will use bright colors for bold text. You can either:

- Uncheck "Brighten bold text"
- Darken the bright variant of "Black"

<img width="556" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/21034/368bba36-e483-4759-8de4-e2433b2dc74e">
