### ISSUE TITLE
What is the background color of the file path in the example?

### ISSUE THREAD

**Issue by liby** [romkatv/powerlevel10k#698]
As shown in the figure.
![Xnip2020-05-08_23-00-11](https://user-images.githubusercontent.com/38807139/81418906-fc6b8380-917f-11ea-9f64-80c4f492f172.jpg)

I want to set the value of the following configuration item to the same as in the diagram, but I didn't find the same color.
```sh
 # Current directory background color.
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=24
```

**Comment by romkatv** [comment]
This is color blue (4). Colors with codes up to 16 are defined by terminal color schemes (a.k.a. terminal themes). This screenshot uses Tango. It's quite popular. It shouldn't be difficult to find Tango theme for your terminal.

You can also manually set color to `#3465A4`. This is what Tango has as blue (4).

```zsh
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#3465A4'
```

**Comment by liby** [comment]
internal/p10k.zsh
I saw the code comment you wrote in this [file.](https://github.com/romkatv/powerlevel10k/blob/ca114f250863f0725e66049d7b74af2e9ea52655/internal/p10k.zsh).
```
# For compatibility with Powerlevel9k. It's not recommended to use mnemonic color
# names in the configuration except for colors 0-7 as these are standard.
typeset -grA __p9k_colors=(
            black 000               red 001             green 002            yellow 003
             blue 004           magenta 005              cyan 006             white 007
             grey 008            maroon 009              lime 010             olive 011
             navy 012           fuchsia 013              aqua 014              teal 014
           silver 015             grey0 016          navyblue 017          darkblue 018
            blue3 020             blue1 021         darkgreen 022      deepskyblue4 025
      dodgerblue3 026       dodgerblue2 027            green4 028      springgreen4 029
       turquoise4 030      deepskyblue3 032       dodgerblue1 033          darkcyan 036
    lightseagreen 037      deepskyblue2 038      deepskyblue1 039            green3 040
     springgreen3 041             cyan3 043     darkturquoise 044        turquoise2 045
           green1 046      springgreen2 047      springgreen1 048 mediumspringgreen 049
            cyan2 050             cyan1 051           purple4 055           purple3 056
       blueviolet 057            grey37 059     mediumpurple4 060        slateblue3 062
       royalblue1 063       chartreuse4 064    paleturquoise4 066         steelblue 067
       steelblue3 068    cornflowerblue 069     darkseagreen4 071         cadetblue 073
         skyblue3 074       chartreuse3 076         seagreen3 078       aquamarine3 079
  mediumturquoise 080        steelblue1 081         seagreen2 083         seagreen1 085
   darkslategray2 087           darkred 088       darkmagenta 091           orange4 094
       lightpink4 095             plum4 096     mediumpurple3 098        slateblue1 099
           wheat4 101            grey53 102    lightslategrey 103      mediumpurple 104
   lightslateblue 105           yellow4 106      darkseagreen 108     lightskyblue3 110
         skyblue2 111       chartreuse2 112        palegreen3 114    darkslategray3 116
         skyblue1 117       chartreuse1 118        lightgreen 120       aquamarine1 122
   darkslategray1 123         deeppink4 125   mediumvioletred 126        darkviolet 128
           purple 129     mediumorchid3 133      mediumorchid 134     darkgoldenrod 136
        rosybrown 138            grey63 139     mediumpurple2 140     mediumpurple1 141
        darkkhaki 143      navajowhite3 144            grey69 145   lightsteelblue3 146
   lightsteelblue 147   darkolivegreen3 149     darkseagreen3 150        lightcyan3 152
    lightskyblue1 153       greenyellow 154   darkolivegreen2 155        palegreen1 156
    darkseagreen2 157    paleturquoise1 159              red3 160         deeppink3 162
         magenta3 164       darkorange3 166         indianred 167          hotpink3 168
         hotpink2 169            orchid 170           orange3 172      lightsalmon3 173
       lightpink3 174             pink3 175             plum3 176            violet 177
            gold3 178   lightgoldenrod3 179               tan 180        mistyrose3 181
         thistle3 182             plum2 183           yellow3 184            khaki3 185
     lightyellow3 187            grey84 188   lightsteelblue1 189           yellow2 190
  darkolivegreen1 192     darkseagreen1 193         honeydew2 194        lightcyan1 195
             red1 196         deeppink2 197         deeppink1 199          magenta2 200
         magenta1 201        orangered1 202        indianred1 204           hotpink 206
    mediumorchid1 207        darkorange 208           salmon1 209        lightcoral 210
   palevioletred1 211           orchid2 212           orchid1 213           orange1 214
       sandybrown 215      lightsalmon1 216        lightpink1 217             pink1 218
            plum1 219             gold1 220   lightgoldenrod2 222      navajowhite1 223
       mistyrose1 224          thistle1 225           yellow1 226   lightgoldenrod1 227
           khaki1 228            wheat1 229         cornsilk1 230           grey100 231
            grey3 232             grey7 233            grey11 234            grey15 235
           grey19 236            grey23 237            grey27 238            grey30 239
           grey35 240            grey39 241            grey42 242            grey46 243
           grey50 244            grey54 245            grey58 246            grey62 247
           grey66 248            grey70 249            grey74 250            grey78 251
           grey82 252            grey85 253            grey89 254            grey93 255)
```
So I misinterpreted it to mean that the color values are selected from the values defined in the code above, between 0 and 255, and among them, I didn't find #3465A4.

Thanks for your reply, and by the way, have you tested who performs better with Powerlevel10K and [Starship](https://starship.rs/guide/)?

**Comment by romkatv** [comment]
If you terminal supports (at least) 256 colors, you can use colors 0-255. If you are using a new version of zsh and your terminal supports trucolor, you can also use colors such as '#3465A4'. Here's a nice interactive color picker built into Google: https://www.google.com/search?q=pick+color.

> have you tested who performs better with Powerlevel10K and Starship?

Of course. I follow all themes that are at least mildly popular. You can read https://github.com/starship/starship/discussions/580 if you are curious. The summary is that powerlevel10k is always very fast, to the point where you wouldn't be able to tell a difference if powerlevel10k became even faster. Starship, on the other hand, is fast in many cases, but not always. Sometimes it can be sluggish, and occasionally it can get unusably slow.

You can search for "slow" in the issue trackers of Powerlevel10k and Starship and compare results. There are no issues at all in Powerlevel10k where users complain about slowness or poor performance. There are quite a few in Starship:

- Very Slow on WSL 2
- Freezes and uses 100% of cpu in huge? git directories.
- Starship prompt takes ~20 seconds when inside rust repo
- Prompt is very slow to finish in large checkouts on HDD
- nvm sourcing slow startup

I should repeat that for many users Starship is fast enough. The difference is that Powerlevel10k is fast enough for all users and all uses.

As far as functionality goes, Powerlevel10k is significantly ahead. Stuff like instant prompt, transient prompt and show on command are out of reach for Starship. 

On the usability side, interactive configuration wizard is something Powerlevel10k users repeatedly single-out as one of the greatest benefits. There is nothing similar in Starship.

**Comment by liby** [comment]
It was a pleasure to get such a professional and detailed response.
I can now easily choose between them, without having to dwell on which is better!
You're so cool, friend, have a nice day.
