### ISSUE TITLE
Segment Wifi not working

### ISSUE THREAD

**Issue by Geeky-nutcracker** [romkatv/powerlevel10k#699]
With with the recent prompt Wifi segment is not working though it is mentioned in the config file.

``` POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status os_icon disk_usage ram load wifi root_indicator background_jobs history ip time) ```

So what am I doing wrong in here and what else should I do to make it display.

![image1](https://user-images.githubusercontent.com/62972573/81447581-86284a80-919a-11ea-9afd-5a8bec68057e.png)

**Comment by romkatv** [comment]
It works only on macOS.
