### ISSUE TITLE
[Feature Request] Ability to remove space after prompt_char in multi-line prompt

### ISSUE THREAD

**Issue by SubhamSatyajeet** [romkatv/powerlevel10k#700]
Frame-less multi-line mode enabled.

If I remove the character prompt (by removing `prompt_char` from the list of items inside `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` within the `.p10k.zsh` file), there's a space as the first character of the new line.

Allowing removal of that space will result in commands and their output being properly aligned to the left side of the terminal window. Please consider this.

I've attached my configuration and a screenshot of how it looks currently for reference.

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4602363/p10k.txt)

![Screenshot from 2020-05-09 06-04-11](https://user-images.githubusercontent.com/7932787/81458964-fe9f0380-91ba-11ea-8819-b8fdf696a5ff.png)

**Comment by romkatv** [comment]
```zsh
POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
```
