### ISSUE TITLE
Exit code status is lost when using multi-line layout

### ISSUE THREAD

**Issue by cesarizu** [romkatv/powerlevel10k#701]
With a fresh installation of p10k and running `p10k configure`, when selecting multi-line, most exit code statuses are not shown (some over 128 are shown). Selecting one line display shows all the exit codes.

**Comment by romkatv** [comment]
I guess the difference is not multi-line vs single line but the presence or absence of `prompt_char`. This character is green on success and red on error, so there is no need to waste time on status for the common cases where the error code is 0 or some non-signal value.

If you'd like to see status in all cases, open `~/.p10k.zsh` and sets these parameters to true:

```zsh
POWERLEVEL9K_STATUS_OK
POWERLEVEL9K_STATUS_OK_PIPE
POWERLEVEL9K_STATUS_ERROR
POWERLEVEL9K_STATUS_ERROR_SIGNAL
POWERLEVEL9K_STATUS_ERROR_PIPE
```

Your config already has these parameters, you just need to change their values. Comments above each parameter explain which state it corresponds to.

**Comment by cesarizu** [comment]
Thanks for your comment and I got it working setting those vars.

It was a bit confusing that only changing the multi-line to single line in `p10k configure` changed the visibility of the status codes, but I guess it makes sense because the `prompt_char` turns to red to indicate a failure.

**Comment by romkatv** [comment]
`prompt_char` is very useful. In addition to encoding error/success status of commands, it also shows current vi mode. So when you have `prompt_char`, `vi_mode` segment gets disabled by default.
