### ISSUE TITLE
Direnv and instant prompt: Minor question

### ISSUE THREAD

**Issue by mjlbach** [romkatv/powerlevel10k#702]
I have my zshrc set up as such:

```
# Enable direnv
eval "$(direnv hook zsh)"

# Enable Powerlevel10k instant prompt. Should stay at the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

```

This works for standard prompts, however, when using TMUX or opening a new terminal tab, it seems to trigger the following error in powerlevel10k's instant prompt initialization

```
[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

You can:

  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.

    * You will not see this error message again.
    * Zsh will start quickly and prompt will update smoothly.

  - Suppress this warning either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

    * You will not see this error message again.
    * Zsh will start quickly but prompt will jump down after initialization.

  - Disable instant prompt either by running p10k configure or by manually
    defining the following parameter:

      typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

    * You will not see this error message again.
    * Zsh will start slowly.

  - Do nothing.

    * You will see this error message every time you start zsh.
    * Zsh will start quickly but prompt will jump down after initialization.

For details, see:
https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt

-- console output produced during zsh initialization follows --

direnv: loading ~/Repositories/lab/interactive_physics/.envrc
direnv: export +POETRY_ACTIVE +VIRTUAL_ENV ~PATH
```

I'm not quite sure why instant prompt would only fail in tmux or a new tab, and not when opening a normal shell. Sorry if this is a configuration issue that has been noted! I tried a search but didn't find anything. Edit, this makes sense in retrospect, because direnv only outputs to stdout during prompt initialization when there is a .envrc in the current directory the shell is being initialized in.

**Comment by romkatv** [comment]
Please read the error message. What isn't clear?

**Comment by mjlbach** [comment]
Sorry, I should have phrased differently, I'm aware that direnv outputs to stdout when there is a detected envrc. Is there currently no way to use both direnv and instant prompt concurrently without running into this issue? Given this:
```
  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details
```
I assumed that sourcing the direnv hook before initializing instant prompt would fix the issue, but it did not.

**Comment by romkatv** [comment]
> I assumed that sourcing the direnv hook before initializing instant prompt would fix the issue, but it did not.

The output isn't produced by the line you put at the top. It's produced later, from `precmd`.

I suggest you do the following.

```zsh
emulate zsh -c "$(direnv export zsh)"

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

emulate zsh -c "$(direnv hook zsh)"
```

In addition, since you've read and understood the warning from instant prompt, I advise you to set `POWERLEVEL9K_INSTANT_PROMPT=quiet` in `~/.p10k.zsh`.

**Comment by mjlbach** [comment]
> ```shell
> emulate zsh -c "$(direnv hook zsh)"
> ```
That fixed it! I like keeping the warning in case I accidentally add something that slows down my shell (like this haha). Thank you :)

**Comment by jameskyle** [comment]
I know this is closed, but it's the first hit I found when searching for this issue. 

I ran into this issue when I start a tmux session within a Direnv. Rather than disabling the warning globally, you can disable only within the environment. 

e.g. in your .envrc, put:

`POWERLEVEL9K_INSTANT_PROMPT=quiet`

Now if you're in a Direnv and spawn another shell, it will disable the warning. But verbose is still enabled globally.

**Comment by romkatv** [comment]
> export POWERLEVEL9K_INSTANT_PROMPT=quiet

Since you know what the warning says, you can disable it globally. It doesn't suppress output, only removes the warning. Whenever you see output, you can imagine you are seeing the warning too.

**Comment by romkatv** [comment]
@jameskyle Have you noticed the solution in https://github.com/romkatv/powerlevel10k/issues/702#issuecomment-626222730?

**Comment by jameskyle** [comment]
Yeah, seemed a bit 'heavy'. I put the prompt disable export in my `.direnvrc` as a `layout_p10k` function. Seemed simple and would only effect Direnv's.

**Comment by romkatv** [comment]
> Yeah, seemed a bit 'heavy'.

???

**Comment by jameskyle** [comment]
> > Yeah, seemed a bit 'heavy'.
> 
> ???

So the `emulate` calls would throw an error if `direnv` isn't installed. So you'd want to wrap them in a check for the command. It would also run and source the cache in all new shells, but I was only seeing the warning when I'd create a tmux pane in a direnv. 

By creating a hook in the direnvrc, my zsh config remain the same, there's no cache sourcing, no need to test if direnv command exists, and the only time anything changes from default is in the narrow case where I saw the warning.

**Comment by muraii** [comment]
> I know this is closed, but it's the first hit I found when searching for this issue.
> 
> I run into this when I start a tmux session within a Direnv. Rather than disabling the warning globally, you can disable only within the environment.
> 
> e.g. in your .envrc, put:
> 
> `export POWERLEVEL9K_INSTANT_PROMPT=quiet`
> 
> Now if you're in a Direnv and spawn another shell, it will disable the warning. But verbose is still enabled globally.

Thank you. This worked a treat.

**Comment by dbalabka** [comment]
The solution that worked for me, is to silence `direnv`'s output logs by adding log settings into `~/.config/direnv/direnv.toml`:
```
[global]
log_format = "-"
log_filter = "^$"
```
`direnv` version `2.36.0`

**Comment by gracepetryk** [comment]
With the solution in https://github.com/romkatv/powerlevel10k/issues/702#issuecomment-626222730 I was running into issues with `PATH` being reset and losing nvm and other entries after `cd` when launching a shell into a directory with a `.envrc` file that changes `PATH`. I was able to silence the first direnv message while keeping any subsequent ones with the following at the *end* of my zshrc instead:

```zsh
tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

eval "$(direnv export zsh 2>!$tmpfile)"
grep 'direnv: error' $tmpfile # catch disallowed .envrc files on startup

eval "$(direnv hook zsh)"
```
