### ISSUE TITLE
POWERLEVEL9K_DIR_HYPERLINK=true does not add hyperlinks

### ISSUE THREAD

**Issue by sumanthratna** [romkatv/powerlevel10k#704]
Perhaps I'm misunderstanding something about this feature. In my p10k config, I set `POWERLEVEL9K_DIR_HYPERLINK=true`, but I don't see any change in my prompt. 

I would expect for directory I'm in to open in Finder when I click it (the equivalent of `open .`). However, this doesn't happen. 

![Screen Shot 2020-05-10 at 11 44 41](https://user-images.githubusercontent.com/31281983/81503802-ae579c80-92b3-11ea-8789-a7530ab0b284.png)

- macOS 10.15.5 Beta
- p10k 1.8.0
- zsh 5.7.1

**Comment by romkatv** [comment]
Not all terminals support hyperlinks. This is the spec if you are curious: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda.

**Comment by romkatv** [comment]
> I would expect for directory I'm in to open in Finder when I click it (the equivalent of `open .`). 

And yes, that's how it works in terminals that support hyperlinks. Often there is a key that you need to hold (for me it's Control) when clicking these links. They also get highlighted/underlined.

**Comment by sumanthratna** [comment]
Thanks for the quick reply. Do you think it would be useful to provide a fallback method for macOS? This likely won't seem as smooth, but if we can detect that the user clicked on the directory (I've configured `nano` to set the cursor to wherever I click), then we can simply run `open $directory`. 

I'm really not sure if this is possible.

https://github.com/romkatv/powerlevel10k/blob/75bbc4439fba7be0e72ab4c17e4aca62d03fc9c6/internal/p10k.zsh#L1990-L2000

**Comment by romkatv** [comment]
I'm afraid this isn't possible.
