### ISSUE TITLE
VCS branch custom shortening

### ISSUE THREAD

**Issue by mgh87** [romkatv/powerlevel10k#705]
Hey, I'd like to introduce an improved custom branch shortening.

### Adding configured shorting
At first, I tried as in #193 mentioned the add to .p10k.zsh config file, but it had no impact. (I tried it with truncate_right)

```
POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=32
POWERLEVEL9K_VCS_SHORTEN_LENGTH=12
POWERLEVEL9K_VCS_SHORTEN_STRATEGY=truncate_middle
```

After this, I found the configuration in the .p10k.zsh file for shortening:
```
    (( $#where > 32 )) && where[13,-13]="…"
    res+="${clean}${where//\%/%%}"  # escape %
```

Is this the correct place to add your custom shortening? (or is there a better location to don't break compatibility with p10k)

### Custom change of the "where" property

I use in most projects git flow with a folder component before the branch name:
```
$FOLDER/${JIRA_TICKET}-${BRANCH_NAME}
$FOLDER is one of (feature|bugfix|hotfix|release)
$JIRA_TICKET follows the pattern [A-Z]{2,6}-\d+
$BRANCH_NAME is any string that is allowed for a git branch.
```
I would like to reduce the folder to a single character, keep the jira ticket and then truncate from the right. I was looking up parameter substitution in the zsh documentation, but didn't find anything that would do this without a zsh function, or was able to get something working.

Example:
`feature/JIRA-000-this-is-my-branch-name-test-for-shortening`
Result:
`f/JIRA-000-this-is-my-bra…`

P.s.: Thanks for your great work with the theme and your responsiveness. I try to read most of the issues you answer and almost learn on every one something about zsh or shells in general.

**Comment by romkatv** [comment]
> Is this the correct place to add your custom shortening?

Yes. More generally, `~/.p10k.zsh` is the correct place for all prompt customization.

> I would like to reduce the folder to a single character, keep the jira ticket and then truncate from the right.

Try this:

```zsh
local where  # branch or tag
if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
  res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}"
  setopt extended_glob
  local -a match mbegin mend
  if [[ $VCS_STATUS_LOCAL_BRANCH == (#b)([^/]##)/([A-Z]##-[0-9]##)-(?*) ]]; then
    local folder=$match[1]
    local ticket=$match[2]
    local branch=$match[3]
    where=$folder[1]/$ticket-$branch
  else
    where=$VCS_STATUS_LOCAL_BRANCH
  fi
  where=${(V)where}
elif [[ -n $VCS_STATUS_TAG ]]; then
  res+="${meta}#"
  where=${(V)VCS_STATUS_TAG}
fi

(( $#where > 32 )) && where[26,-1]="…"
```

This should replace this block of code: https://github.com/romkatv/powerlevel10k/blob/459af1f2382ff53214bf9e4fc598b4e36fb8f8df/config/p10k-lean.zsh#L363-L375

**Comment by mgh87** [comment]
Works like a charm.
Still researching what you did there. 😄

**Comment by romkatv** [comment]
Thanks for the confirmation.

**Comment by LimeBlast** [comment]
Hi, I've got a similar request, but with a slightly different requirement. Our branches, which use GitFlow tend to look like this:

`feature/CU-52t2dq_BON1-claim-a-bonus-against-a-stage_Daniel-Hollands`

which breaks down like this:

- `feature/` The branch namespace/folder
- `CU-52t2dq` The ticket number from Clickup
- `BON1-claim-a-bonus-against-a-stage` our human-readable label
- `Daniel-Hollands` who owns the ticket

I'm after similar truncation as described above, where the namespace/folder gets shortened to a single character, but after this, I'm less concerned about what gets shown, so long as it truncates off the right of the branch, not the left.

I've applied the code above, hoping it would work for me too, but I think the regex is failing to match correctly (for example, when I reduce the size of iterm, I get `feature/CU-52t2dq_BON1-cl…`), and I'm not quite skilled enough at regex to figure out how to fix it.

**Comment by romkatv** [comment]
> I'm not quite skilled enough at regex to figure out how to fix it.

Zsh pattern matching syntax is documented in section "Glob Operators" of `man zshexpn`.

**Comment by LimeBlast** [comment]
I've ended up with this:

```
    local where  # branch or tag
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}"
      setopt extended_glob
      local -a match mbegin mend
      if [[ $VCS_STATUS_LOCAL_BRANCH == (#b)([^/]##)/(?*) ]]; then
        local folder=$match[1]
        local branch=$match[2]
        where=$folder[1]/$branch
      else
        where=$VCS_STATUS_LOCAL_BRANCH
      fi
      where=${(V)where}
    elif [[ -n $VCS_STATUS_TAG ]]; then
      res+="${meta}#"
      where=${(V)VCS_STATUS_TAG}
    fi

    (( $#where > 32 )) && where[26,-1]="…"
```

Which I don't really understand, and so I'm sure can be improved, but at least works correctly for shrinking the folder down, which results in something like `f/CU-82p8uk_Update-to-Rai…`
