### ISSUE TITLE
gitstatus failed to initialize

### ISSUE THREAD

**Issue by CNife** [romkatv/powerlevel10k#706]
When I updated powerlevel10k to 1.8.0, gitstatus starts to fail.

Error log:
https://paste.ofcode.org/5mXMwTmh6xM7RPjrwaznh8

**Comment by romkatv** [comment]
The log says that the following command hangs:

```zsh
curl -fsSLo /home/cnife/.cache/gitstatus/gitstatusd-linux-x86_64.tmp.5140.tar.gz -- https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-linux-x86_64.tar.gz
```

You need to have a working internet connection for powerlevel10k to download gitstatusd. If you want to, you can trigger this download manually after you update powerlevel10k:

```zsh
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f
```

**Comment by SebastianMuskalla** [comment]
I'm getting a similar problem.
When I try the manual install, I get the following error.

```
[gitstatus] error: failed to download gitstatusd: https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-cygwin_nt-10.0-x86_64.tar.gz
curl: (23) Failed writing body (0 != 16384)
```

The file itself exists; when I paste the URL into a browser, I can download it.

**Comment by romkatv** [comment]
@SebastianMuskalla Please post the command that fails. It should start with `curl`.

**Comment by romkatv** [comment]
Oh, I see that `curl` is broken on Cygwin. I'll write a workaround.

This is *not* the same problem that @CNife is experiencing.

**Comment by knaeble** [comment]
I may also have a related issue. Please check https://paste.ofcode.org/JvdwQEJEXq3ZjUWaiRh8Gy for reference. It fails at an earlier stage than @CNife .

**Comment by romkatv** [comment]
@SebastianMuskalla Please update powerlevel10k and try again.

@knaeble Has powerlevel10k every work for you on the same machine or has it started happening recently?

**Comment by romkatv** [comment]
To clarify, the issue @knaeble is having is unrelated. I'd be surprised if powerlevel10k ever worked on iSH.

**Comment by knaeble** [comment]
Never tried it on this machine, only have been using it on others. Damn :/

**Comment by romkatv** [comment]
> Never tried it on this machine, only have been using it on others.

Do any of those other machines run iSH? In other words, did powerlevel10k ever work for you on iSH?

**Comment by knaeble** [comment]
None of them run iSH. So no, never. It’s flawless in WSL & native installations of course. Great work!

**Comment by romkatv** [comment]
OK, then iSH is simply not there yet. Lots and lots of things don't work in it. Zsh is apparently one of them.

**Comment by SebastianMuskalla** [comment]
> @SebastianMuskalla Please update powerlevel10k and try again.

Fixed! Thanks a lot!

**Comment by romkatv** [comment]
Seems like everything is fixed. I assume the issue @CNife has posted was caused by not being connected to the internet. Please shout if not.

**Comment by Maryse47** [comment]
@romkatv why gitstatusd aren't bundled with powerlevel10k? I don't like my terminal downloading something over the web when I launch it.

**Comment by romkatv** [comment]
> @romkatv why gitstatusd aren't bundled with powerlevel10k?

The size of the repo has been growing too large too quickly.

> I don't like my terminal downloading something over the web when I launch it.

You can trigger this download manually after you update powerlevel10k:

```zsh
git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f
```

`git pull` requires internet connection and the ability to read data from github.com. The second line is no different.

**Comment by Maryse47** [comment]
> The size of the repo has been growing too large too quickly.

You could use submodule or just provide a way for downstream packagers to bundle it.

> You can trigger this download manually after you update powerlevel10k:
> 
> git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
> ~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f

I use from Arch Linux package and don't use oh-my-zsh.

> git pull requires internet connection and the ability to read data from github.com. The second line is no different.

I see `gitstatus failed to initialize` on every new shell I spawn and my working directory isn's a git repo so it shouldn't need to call `git pull` or anything.

**Comment by romkatv** [comment]
There are packaging instructions for distributions: https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-to-package-powerlevel10k-for-distribution. Arch isn't following them yet. I don't know if they intend to.

**Comment by Maryse47** [comment]
cc : @shibumi ^

**Comment by romkatv** [comment]
> cc : @shibumi ^

I've pinged @shibumi when I've made this change:  https://github.com/romkatv/powerlevel10k/issues/392#issuecomment-626341555. You are experiencing issues because a new Arch Linux package was released without changes to it's packaging procedure. It's not broken per se but it requires internet connection to download gitstatusd (just once, not on every shell startup).

**Comment by shibumi** [comment]
Uff, I hoped it would just work. Looks like I need to have another look on this.

@romkatv I am actually not a big fan of the change, because your new build method is not reproducible. It's bad practice to download dependencies during the actual build process.

I need the libgit2 version before I download any software. I can't download the powerlevel10k stuff first and then parse it, because there should be no outgoing connection during the build process. This is for isolation proccess. It ensures that no remote source is tampering with the build process.

I will have a look and see how I get this working again, but it will need major work on the PKGBUILD and take some time.

**Comment by romkatv** [comment]
> @romkatv I am actually not a big fan of the change, because your new build method is not reproducible. It's bad practice to download dependencies during the actual build process.

Is it possible you've misunderstood instructions?

**Comment by romkatv** [comment]
Specifically, this passage:

> Depending on your workflow, it might be easier to store the URL to the libgit2 tarball in the same place where you are going to put the main powerlevel10k tarball URL. You'll need to update both URLs at the same time when bumping package version.

So you need two tarballs and then you run `./build`. The latter doesn't download anything. The instructions show how to obtain the two tarballs.

**Comment by shibumi** [comment]
@romkatv yes, but the version info of your second tarball is hidden in the build info script that is in your first tarball. Do you see this dependency tree or am I misunderstanding something?

**Comment by romkatv** [comment]
You get the URL to the first tarball from a powerlevel10k release. That URL is fixed. Put that URL and the sha256 in your package definition.

Extract URL of the second tarball from the first. That URL is fixed because the first tarball is fixed. Put that URL and the sha256 in your package definition.

You start with a powerlevel10k release number and after that everything is reproducible. No hidden dependencies, nothing changing from underneath.

These steps can be done either manually or they can be automated. Up to you.

Does it make sense?

**Comment by romkatv** [comment]
I can attach libgit2 tarballs to powerlevel10k releases although it seems silly given that a powerlevel10k unambiguously defines libgit2 tarball by reference.

**Comment by shibumi** [comment]
@romkatv I really don't want to extract the tarball just for getting a second URL, doesn't matter if it's fixed. I still think you should provide the libgit2 URL somewhere else then only in the buildinfo file of the first release tarball. I maintain over 50 packages, I hope you understand the work load if every of these would start having such weird distribution methods.

No need to attach the libgit2 tarballs to the powerlevel10k release, it would be already enough if you could point via URL in the powerlevel10k release page on github to the corresponding libgit2 URL.

**Comment by romkatv** [comment]
Sure, I can add a link. Currently there is no link because no one has asked for it. I'm surprised that you prefer to manually extract technical data (such as URLs) from free-form release notes rather than from machine-readable metadata, but it's your time and your call.

Link added: https://github.com/romkatv/powerlevel10k/releases/tag/v1.8.2.

**Comment by shibumi** [comment]
@romkatv thanks.

**Comment by LimingFang** [comment]
> The log says that the following command hangs:
> 
> ```shell
> curl -fsSLo /home/cnife/.cache/gitstatus/gitstatusd-linux-x86_64.tmp.5140.tar.gz -- https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-linux-x86_64.tar.gz
> ```
> 
> You need to have a working internet connection for powerlevel10k to download gitstatusd. If you want to, you can trigger this download manually after you update powerlevel10k:
> 
> ```shell
> git -C ~/.oh-my-zsh/custom/themes/powerlevel10k pull
> ~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f
> ```

Thanks! It works.

**Comment by michaelmarziani** [comment]
Got this error after updating macOS to 11.5. The gitstatus install command fixed it.

**Comment by rudelm** [comment]
Ran into the same issue as @michaelmarziani had and using the manual checkout and installation of gitstatus helped. Thanks!

**Comment by CrazyVideoGamer** [comment]
When I run `~/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/install -f`, I get this error:
`/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
tar: Child returned status 2
tar: Error is not recoverable: exiting now`

**Comment by romkatv** [comment]
@CrazyVideoGamer It's a bug in your OS. See https://github.com/microsoft/WSL/issues/8219#issuecomment-1110508016.

P.S.

In the future open a new issue instead of commenting on an unrelated one.

**Comment by OurCodeBase** [comment]
I have created [starship](https://starship.rs/) config or preset exactly like powerlevel10k. you should definitly try `starship` as your shell prompt.

If someone needs to use powerlevel10k without headache use `starship`.

- 🚀 It is blazingly fast and reliable.
- ✍️ It is extremely customisable.
- 🦕 It is not built in dianosour technology, instead it is built in rust.

And also the preset will provide you exactly same experience like `powerlevel10k`.

Click here to get the preset [[Click Here]](https://gist.github.com/OurCodeBase/7d26fa98a8dd5d072c9bae4b8e083bdc)
