### ISSUE TITLE
kubecontext not showing up at alpine (WSL)

### ISSUE THREAD

**Issue by somatorio** [romkatv/powerlevel10k#707]
Hello, i tried to use powerlevel10k at an alpine wsl and noticed my kubecontext doesn't show up even if i unset `POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND` tried installing at a ubuntu wsl and it just worked

is there any requirements that i need to install at alpine?

**Comment by romkatv** [comment]
Please fire up alpine and run the following command:

```zsh
() {
  emulate -L zsh -o xtrace
  typeset -pm 'POWERLEVEL9K_*|P9K_KUBECONTEXT_*|ZSH_VERSION'
  uname -a
  whence kubectl
  (( ! $+commands[kubectl] )) || kubectl config view -o=yaml
} &>/tmp/p10k.txt
```

When it finishes, attach `/tmp/p10k.txt` to this issue.

**Comment by somatorio** [comment]
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4611753/p10k.txt)

**Comment by romkatv** [comment]
On your system `kubectl` is an alias for the following command:

```zsh
docker run -it --name kubectl --rm -v $KUBECONFIG:/.kube/config bitnami/kubectl:latest
```

Is this intended? Have you created this alias? If not, where does it come from? What is the output of the following command?

```zsh
time ( kubectl config view -o=yaml )
```

(Please answer all questions I've asked.)

**Comment by somatorio** [comment]
> Is this intended? 

Yes, my plan was to have only the minimal pkgs installed, and everything else to be used as containers

>Have you created this alias?`

yes, and it worked like a charm for all i needed until now

> What is the output of the following command?
>
>time ( kubectl config view -o=yaml )

```zsh
❯ time ( kubectl config view -o=yaml )
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.1.50.66:443
  name: cluster.local
contexts:
- context:
    cluster: cluster.local
    user: kubernetes-admin
  name: kubernetes-admin@cluster.local
current-context: kubernetes-admin@cluster.local
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
( docker run -it --name kubectl --rm -v $KUBECONFIG:/.kube/config  config vie)  0.06s user 0.04s system 7% cpu 1.252 total
```

**Comment by romkatv** [comment]
Fascinating.

`kubecontext` prompt segment (like many other prompt segments) doesn't do anything unless there is evidence that you are using the tools that are relevant to it. In this case the check is "do you have `kubectl` command in `PATH`". You don't, so it doesn't show you anything.

You could say that alias `kubectl` should qualify, but then where does it stop? Does `k` alias qualify, too? Maybe it expands to an ssh command that runs docker remotely.

If you want `kubecontext` to show up, create a script instead of the alias. This is generally a good idea. Aliases are meant for things that only make sense in interactive shell. Anything that you could conceivably want to call in a script must be a script itself.

**Comment by somatorio** [comment]
oh, making a script makes sense to me as well, forgot about that option :)

BUT, just made this and it does the same

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4611854/p10k.txt)

`❯ echo $PATH
/home/somatorio/.zinit/polaris/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/c/Windows/System32/OpenSSH/:/c/Program Files/PuTTY/:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/Git/cmd:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Docker/Docker/resources/bin:/c/ProgramData/DockerDesktop/version-bin:/c/Users/marco.martins/AppData/Local/Microsoft/WindowsApps:/c/Program Files/apache-maven-3.6.3/bin:/c/Program Files/Java/jdk1.8.0_212/bin:/home/somatorio/bin:/home/somatorio/.fzf/bin`

Please notice that `/usr/local/bin` is at PATH

**Comment by romkatv** [comment]
Repeat the large command please (https://github.com/romkatv/powerlevel10k/issues/707#issuecomment-626918279).

**Comment by somatorio** [comment]
i did that here: https://github.com/romkatv/powerlevel10k/issues/707#issuecomment-626936751

**Comment by romkatv** [comment]
Sorry, missed that. Try restarting zsh. It doesn't rehash commands very well.

**Comment by somatorio** [comment]
That did the trick, thanks!

**Comment by romkatv** [comment]
You are very welcome.
