### ISSUE TITLE
Opening a new prompt takes more than 20 sec 

### ISSUE THREAD

**Issue by a6avind** [romkatv/powerlevel10k#708]
I just installed powerlevel10k. Once the configuration is done, when trying to start a new terminal session, the shell is taking more than 20 sec to respond. Am I missing something here or is this the default behaviour.

**Comment by romkatv** [comment]
> I just installed powerlevel10k. Once the configuration is done, when trying to start a new terminal session, the shell is taking more than 20 sec to respond. [...] is this the default behaviour.

This is not the default behavior. Please run the following command and attach `/tmp/p10k.txt` to this issue when it finishes.

```zsh
(
  zmodload zsh/datetime zsh/mathfunc
  function with-ts() {
    emulate -L zsh
    local line
    while IFS= read -r line; do
      local -F ts=EPOCHREALTIME
      local -F3 ms=$((ts - int(ms)))
      print -r -- ${(%):-"%D{%H:%M:%S}"}.${ms##*.} $line
    done
  }
  (
    emulate -L zsh -o err_return
    local tmp
    tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
    {
      cd $tmp
      git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
      >.zshrc <<\END
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
GITSTATUS_LOG_LEVEL=DEBUG
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
END
      typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION'
      uname -a
      ZDOTDIR=$tmp zsh -dxis <<-\END
typeset -p GITSTATUS_DAEMON_LOG_POWERLEVEL9K; cat -- $GITSTATUS_DAEMON_LOG_POWERLEVEL9K
typeset -p GITSTATUS_XTRACE_POWERLEVEL9K; cat -- $GITSTATUS_XTRACE_POWERLEVEL9K
END
    } always {
      cd /
      rm -rf -- $tmp
    }
  ) 2>&1 | with-ts >/tmp/p10k.txt
)
```

**Comment by a6avind** [comment]
[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4615015/p10k.txt)

**Comment by romkatv** [comment]
Your machine is unable to download from github.com. Once you fix that, it'll work.

When you opened the issue, you said it was taking a long time to start Zsh but haven't said anything about a huge error message that gets printed after 30 seconds. Did you see it?

Are you perchance in China? I'm aware that github.com is (almost?) inaccessible from China. I'm working on a solution.

**Comment by a6avind** [comment]
I downloaded the code directly from GitHub. Am from India.

**Comment by romkatv** [comment]
Please run the following command and post its output:

```zsh
() {
  emulate -L zsh
  time curl -fsSLo /dev/null -- https://github.com/romkatv/gitstatus/releases/download/v1.0.0/gitstatusd-linux-x86_64.tar.gz
  echo $?
}
```

**Comment by a6avind** [comment]
`0.09s user 0.04s system 0% cpu 23.749 total`

**Comment by romkatv** [comment]
I see. It works but it's just very-very slow. I'll adjust the code to survive in environments like this.

**Comment by a6avind** [comment]
Ya thanks.

**Comment by romkatv** [comment]
Please update powerlevel10k and try again. Let me know if it works now.

**Comment by a6avind** [comment]
Ya, it works fine now.

**Comment by romkatv** [comment]
Thanks for the confirmation.
