### ISSUE TITLE
RFE: expand background jobs to include number

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/powerlevel10k#709]
Is it possible to expand the background job segment to add a count for when there is more than 1 backgrounded process?

Example: running multiple SSL VPNs from the CLI and backgrounding them. Right now I get an indication that I am connected but dont know any more information.

Just looking for simple number. I know i can probably add my own custom segment to get status and all of that if i wanted anything fancier, but the background segment does what i need mostly :)

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and behold these lines:

```zsh
# Don't show the number of background jobs.
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
```

You know what to do.

**Comment by kurktchiev** [comment]
well... now I feel silly. Thanks!
