### ISSUE TITLE
Stuck in fetching gitstatusd

### ISSUE THREAD

**Issue by ccboxes** [romkatv/powerlevel10k#710]
Having trouble when installing WSL2 Ubuntu completely new, powerlevel10 is stuck at this step.
![2020-05-13 132946](https://user-images.githubusercontent.com/22202732/81774891-393bcf80-951e-11ea-9a08-e20da423ddc6.png)

**Comment by romkatv** [comment]
Are you in China? I'm aware that fetching from github.com is very slow there. I've just added a mirror on gitee.com. Please [update powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k) and try again.

**Comment by ccboxes** [comment]
> Are you in China? I'm aware that fetching from github.com is very slow there. I've just added a mirror on gitee.com. Please [update powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k) and try again.

thanks for your work!

**Comment by romkatv** [comment]
Did it help? How long approximately the download took?

**Comment by ccboxes** [comment]
> Did it help? How long approximately the download took?

The download finshed immediately.There is another question, did your script use git to download gitstatusd？ I have set http proxy in global environment，strangely it did’t work。

**Comment by romkatv** [comment]
> did your script use git to download gitstatusd?

No.

**Comment by waitrosee** [comment]
> Are you in China? I'm aware that fetching from github.com is very slow there. I've just added a mirror on gitee.com. Please [update powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k) and try again.

curl: (28) SSL connection timeout
curl -q -fsSL --  > /dev/null  90.90s user 207.66s system 99% cpu 5:00.00 total
28
why still not work

**Comment by waitrosee** [comment]
> > did your script use git to download gitstatusd?
> 
> No.

I HAVE COPY THE BIN INTO .cache/gitstatus WHY EVERY TIME ZSH STILL NEEDS INITIAL?
