### ISSUE TITLE
Stable command to download gitstatusd

### ISSUE THREAD

**Issue by z0rc** [romkatv/powerlevel10k#711]
In https://github.com/romkatv/powerlevel10k/issues/706#issuecomment-626688478 was mentioned how to trigger download of gitstatusd manually using https://github.com/romkatv/powerlevel10k/blob/master/gitstatus/install. Is this expected to remain the same command to download gitstatusd for foreseeable future? I'm planning to add this step to my dotfiles post-pull install script, to be able to control download process and ensure that prompt doesn't do any background network connections.

**Comment by romkatv** [comment]
> Is this expected to remain the same command to download gitstatusd for foreseeable future?

No.

You can trigger all powerlevel10k and gitstatus post-update actions by starting zsh. Like this:

```zsh
zsh -is <<<exit &>/dev/null
```
