### ISSUE TITLE
How can I change background color for "ip my_ip" segment ? (and the < inside)

### ISSUE THREAD

**Issue by MilesTEG1** [romkatv/powerlevel10k#712]
Hello,
(at the end of my post, you'll see full .zshrc file in attachement as `zshrc.txt`)
I managed to change the foreground color of the "ip my_ip" segment  by adding `%F{blue}` :
```shell
function prompt_my_ip() {
    emulate -L zsh
    [[ -z $P9K_IP_IP ]] && return
    p10k segment -b 8 -f 38 -i "%F{blue}"$'\uFBF1' -t "%F{blue}$P9K_IP_IP"
    p10k segment -b 8 -t "%70F⇣$P9K_IP_RX_RATE %215F⇡$P9K_IP_TX_RATE"
  }
```
But, I can't see where I can change de background color...
![image](https://user-images.githubusercontent.com/29298312/81824732-1a493780-9536-11ea-9a7a-ea69b1768cde.png)
I succed to change foreground/backgroup color for public_IP and for wifi segment. But not for the `ip my_ip`

PS : I use the `.p10k.zsh` generated with the `p10k configure` to copy/paste some of it into my .zshrc file. Because the rendering with `.p10k.zsh` isn't what I have without...

PPS : I tried to change the username showed but whatever I tried, it doesn't change...
Is it even possible to force another thing for the username ?

Can someone help me ?
Thanks in advance.

Here the config file :
[zshrc.txt](https://github.com/romkatv/powerlevel10k/files/4622484/zshrc.txt)

**Comment by romkatv** [comment]
That's too many questions for one issue. I'll answer what I can and close it. If any of your questions remain unanswered, open a separate issue for one questions and clearly explain what you want to achieve.

I do not recommend customizing the appearance of `ip` by creating your own `prompt_my_ip`. Instead, customize it as documented here: https://github.com/romkatv/powerlevel10k/blob/459af1f2382ff53214bf9e4fc598b4e36fb8f8df/config/p10k-lean.zsh#L1347-L1357

You can embed colors and icons in there. If you are unable to configure this segment the way you like, open an issue where you clearly explain what you want to see.

Are you sure you want that `192.168.1.10` in your prompt? It takes a lot of spaces and gives you almost no information.

You can change your username with `su`. See `man su`.

**Comment by MilesTEG1** [comment]
Thanks for your answer.
You were right, I don't need the local IP. So I comment the `ip my_ip`. And I only use Public IP and the wifi speed and icon :
![image](https://user-images.githubusercontent.com/29298312/82048175-7043e980-96b4-11ea-8387-a793215e3cb5.png)
I think I'll leave it to this for now.
Thanks for your help.

PS : for the name, I don't want to change definitively it in macOS, but just to change what's seen in the terminal. Nevermind, it's not a big issue.
Thanks again.

**Comment by romkatv** [comment]
> PS : for the name, I don't want to change definitively it in macOS, but just to change what's seen in the terminal. Nevermind, it's not a big issue.

So you just want to display a fixed value? You can do it with a custom segment:

```zsh
function my_name() { p10k segment -b blue -f white -t 'batman' -i '👻' }
```

**Comment by MilesTEG1** [comment]
> function my_name() { p10k segment -b blue -f white -t 'batman' -i '👻' }

Oh great 🗡️ 
To get it working, I had to name the function `prompt my_name() `
![image](https://user-images.githubusercontent.com/29298312/82053252-56f36b00-96bd-11ea-918a-87fc86fed7b6.png)
Thank you very much 👍

**Comment by romkatv** [comment]
> To get it working, I had to name the function `prompt my_name() `

:+1: 

That's the right fix.
