### ISSUE TITLE
Issue with gitstatus after latest update.

### ISSUE THREAD

**Issue by srt0** [romkatv/powerlevel10k#715]
Having this issue after latest update. I'm using Arch Linux. Installed PowerLevel10K from pacman/community repo.

![powerlevel10k-issue](https://user-images.githubusercontent.com/10282404/81934039-1853a700-9610-11ea-94eb-8650dfbfb355.png)

**Comment by romkatv** [comment]
Have you tried doing what the message says?

**Comment by srt0** [comment]
Sorry for late reply. This issue seems to be gone after an update. Just rebooted. It seems to be okay right now.

BTW, I tried to diagnose the issue earlier. First command didn't produce any output. Second command did produce a log.

**Comment by romkatv** [comment]
> Second command did produce a log.

Have you tried reading it?

**Comment by romkatv** [comment]
> > Second command did produce a log.
> 
> Have you tried reading it?

These were the last two lines:

```
If you need help, open an issue and attach this whole error message to it:

  https://github.com/romkatv/gitstatus/issues/new
```
