### ISSUE TITLE
Transient prompt not working (from the beginning)

### ISSUE THREAD

**Issue by varagnac** [romkatv/powerlevel10k#716]
![1589479511](https://user-images.githubusercontent.com/63336227/81969475-55bf3100-961e-11ea-9c0b-d6538cd2eb52.png)

Configuration :
p10k configure
yynnn12232121y2y

Everything else (like directory name truncating) works.
.p10k.zsh is sourced in the very end of .zshrc. The plugin itself is added by zinit, and is loaded right after compinit. I have tried serveral times to change the loading order of plugins but it doesn't seem to be the issue.

**Comment by romkatv** [comment]
Can you reproduce this without zinit and without anything else you have? Run the following command and see if you can reproduce it from the shell that it spawns:

```zsh
() (
  emulate -L zsh -o err_return
  local tmp
  tmp="$(mktemp -d ${TMPDIR:-/tmp}/p10k.XXXXXXXXXX)"
  {
    cd $tmp
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git
    >.zshrc <<\END
source $ZDOTDIR/powerlevel10k/powerlevel10k.zsh-theme
[[ ! $ZDOTDIR/.p10k.zsh ]] || source$ZDOTDIR/.p10k.zsh 
END
    ZDOTDIR=$tmp zsh
  } always {
    cd /
    rm -rf -- $tmp
  }
)
```

**Comment by varagnac** [comment]
It is persistent with zinit disabled but I found the origin of the problem. It is very strange but some of my keybinding settings are in conflict with the theme, and I can't identify precisely which one for the time being (since I put all my keybindings into a .zkeybindings file and source it and found that by commenting it out transient prompt works).

**Comment by romkatv** [comment]
I would guess that your bindings override zle widgets, most likely `zle-line-finish`. Powerlevel10k can survive such abuse but you must override these widgets **before** you load Powerlevel10k. If you override them **after** Powerlevel10k is loaded, there is nothing it can do.

**Comment by lpouget** [comment]
I ran into the same issue and it was because of Oh My Zsh key-bindings (https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/key-bindings.zsh).

Removed it and it worked like a charm.

**Comment by romkatv** [comment]
@lpouget See https://github.com/romkatv/powerlevel10k/blob/master/README.md#weird-things-happen-after-typing-source-zshrc. Never use `source ~/.zshrc` regardless of which configuration framework or theme you are using. It's just a bad idea to ever execute this command. Use `exec zsh` instead.
