### ISSUE TITLE
The right prompt is overflowing to the left pane

### ISSUE THREAD

**Issue by hrai** [romkatv/powerlevel10k#719]
I've recently switched to powerlevel10k from 9k.

I noticed that the prompt flows from right pane to the left when using with tmux.

![image](https://user-images.githubusercontent.com/4055444/82024744-988f1080-96d3-11ea-9314-ab2f4bfb76d3.png)

Also, one thing I noticed was when I'm in the left pane, the top half of the divider gets highlighted and when I'm on the right the bottom half gets highlighted.

**Comment by romkatv** [comment]
Fascinating. I suggest that you ask on a forum dedicated to tmux. I'm not an expert in it.
