### ISSUE TITLE
Question: Issue with Background Color of custom segment

### ISSUE THREAD

**Issue by mstoetzer** [romkatv/powerlevel10k#720]
![terminal_kube-ps1_color_issue](https://user-images.githubusercontent.com/4034031/82033196-ad03e680-969c-11ea-8e91-71fb683d3771.png)

Please see the screenshot. I want to set the background color of the custom segment kube-ps1. I'm using the plugin 'kube-ps1' included in ohmyzsh. Is there some default BG Color for custom segments that I need to overwrite? Do you know, where this spacing arround the segment comes from?

This appears both in 9k and 10k.

**Comment by romkatv** [comment]
It's not a good idea to use `kube-ps1`. Please use `kubecontext` from Powerlevel10k instead. If you are building your config from scratch, you can copy these parameters: https://github.com/romkatv/powerlevel10k/blob/3ddb8025d5af9b31edf687098ecc41c5ed737c82/config/p10k-rainbow.zsh#L1174-L1261

However, it's much better to run `p10k configure` to create a config.

You might also find this useful: https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-some-prompt-segments-appear-and-disappear-as-im-typing
