### ISSUE TITLE
Seeing '(base)' before the prompt

### ISSUE THREAD

**Issue by classbproject** [romkatv/powerlevel10k#721]
Hi, I recently updated the python installation on my Mac and I've started seeing `(base)` before my prompt. How do I remove this? 

![Base text before prompt](https://i.imgur.com/7Pm3Jj2.png)

**Comment by romkatv** [comment]
Please post the output of the following command:

```zsh
typeset -pm 'POWERLEVEL9K_*|ZSH_VERSION'
```

**Comment by classbproject** [comment]
`typeset ZSH_VERSION=5.7.1` is what I see.

**Comment by romkatv** [comment]
How about this?

```zsh
typeset -pm '_POWERLEVEL9K_*'
```

**Comment by classbproject** [comment]
Nothing shows up!

**Comment by romkatv** [comment]
You aren't using powerlevel10k. You'll need to ask your question someplace else.
