### ISSUE TITLE
中国用户

### ISSUE THREAD

**Issue by paradiseduo** [romkatv/powerlevel10k#722]
I have been stuck here for a while, and restarting is invalid. Now I want to restore it to the original state, what should I do?
![image](https://user-images.githubusercontent.com/14846965/82036077-0555db00-96d3-11ea-9348-10c3907d1020.png)

**Comment by romkatv** [comment]
Are you using the newest version of powerlevel10k? Try updating just in case.

**Comment by paradiseduo** [comment]
For well-known reasons, the speed of Chinese users accessing github is very slow. I tried to let the terminal go to the agent, but there was no step to enter the agent command during the entire installation process, so it took a long time here.
Now it's working well.

**Comment by romkatv** [comment]
Yes, I know that github.com is slow to access from Chine. I've recently added a mirror on gitee.com. This is why I've asked if you are using the latest version of Powerlevel10k. The latest version downloads gitstatusd from gitee.com, so it should be faster for you.

**Comment by paradiseduo** [comment]
Maybe this should change to `gitee.com`
![image](https://user-images.githubusercontent.com/14846965/82048510-68516d00-96e7-11ea-96ed-b0fadc6ec5f2.png)

**Comment by romkatv** [comment]
It's a mirror. The content is identical to the official repository on GitHub.
