### ISSUE TITLE
Easier ways to set all backgrounds/set all foregrounds for prompt colours

### ISSUE THREAD

**Issue by BlueDrink9** [romkatv/powerlevel10k#723]
I made a custom prompt using the wizard, where most of the info elements (dir, git status, virtualenv, etc) use coloured backgrounds for their state and keep the foreground the same.

However, I must have made a mistake in setup so the foreground uses the default terminal foreground colour, which in a lot of colorschemes doesn't have enough contrast when on a coloured background.

It has been a huge hassle going through and manually setting every section's foreground colour to 'black' instead.

 Even for the prompt shown in the screenshot at the start of Powerlevel9k Compatilibility in the readme, I would prefer a higher contrast by using the white-like colour rather than the dark gray used as the dir foreground.

I imagine the case of only using foreground or only using background to indicate a state change, and keeping the other color static, would be fairly common. Would it be possible to add an option to set a 'default' foreground/background colour?

**Comment by romkatv** [comment]
> I made a custom prompt using the wizard, where most of the info elements (dir, git status, virtualenv, etc) use coloured backgrounds for their state and keep the foreground the same.

The only style in the wizard with colored backgrounds is Rainbow. It shows `dir` with white foreground and `vcs` (git status) with black background. Most segments in fact use black background.

> It has been a huge hassle going through and manually setting every section's foreground colour to 'black' instead.

Odd. As I mentioned, most segments in Rainbow have black background.

> Would it be possible to add an option to set a 'default' foreground/background colour?

It's possible but at this point I'm not sure what has actually happened. Can you describe how to reproduce this?

Also, have you seen this: https://github.com/romkatv/powerlevel10k/blob/master/README.md#change-the-color-palette-used-by-your-terminal? Usually when you find yourself wishing that some base color (such as "black") looked differently, you change it in your terminal.

**Comment by BlueDrink9** [comment]
Hmm, maybe it wasn't a wizard, or one of the themes that I changed the shape/order of instead... Although it does look very similar to the rainbow theme.

I'm struggling to think how I could reproduce it to be honest, because I made it ages ago, didn't notice it for a while (using solarized), then just put up with it for a while more (with onedark). The mostly-autogenerated config is [here](https://github.com/BlueDrink9/env/blob/fd6881b0255fa10f951193b2d4711339d2dac11a/shell/zsh/plugins/p10k.zsh) if that's helpful, but I'm not expecting you to comb through a whole file just to help me.


> most segments in Rainbow have black **background**

Was this a typo? Because yes, most of the prompt has a black or coloured background, but the text itself is white in all of the coloured sections. The main text is also this white (which is fine without a coloured background). 

> wishing that some base color

I'm happy with the palette. It's only the contrast in this case, and swapping easily to the opposite colour that is the issue.
I also change palettes fairly regularly. ATM I'm using onedark, which has low contrast between most of the colours and 'white', but good contrast with 'black'. But I'll often use other palettes, like gruvbox or solarized, which are both more balanced so that either colour is fine. Onedark is the mainly problematic palette, it's true, but it's a palette I *like*.

I've got some screenshots to show what I mean. I've already changed the directory and git to black. Time, last cmd duration, mode indicator are all default, and you can see in the onedark screenshot that mode and duration are hard to read. Time is white, but without a background it's fine to read (it's the same colour as typed text)

Onedark
![Screen Shot 2020-05-17 at 12 19 30 PM](https://user-images.githubusercontent.com/26474254/82132931-947d0300-9839-11ea-9e34-57e64f1ff9b9.png)
Gruvbox
![Screen Shot 2020-05-17 at 12 18 22 PM](https://user-images.githubusercontent.com/26474254/82132932-96df5d00-9839-11ea-9abc-0600afe25e49.png)
Solarized
![Screen Shot 2020-05-17 at 12 17 37 PM](https://user-images.githubusercontent.com/26474254/82132934-9777f380-9839-11ea-90e0-0e6c4d47399b.png)

**Comment by romkatv** [comment]
> Hmm, maybe it wasn't a wizard, or one of the themes that I changed the shape/order of instead...

This explains it. Wizard produces the config you seem to want but you are using some other config and manually changing it so that it becomes closer to what you get from `p10k configure`. I suggest running `p10k configure`. Note this though: https://github.com/romkatv/powerlevel10k/blob/master/README.md#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style.

**Comment by BlueDrink9** [comment]
Thanks. When I get more time I'll try recreating my config with just rainbow and the default. If it's just the dir that's white, that's easy to change.
