### ISSUE TITLE
Change current dir in prompt?

### ISSUE THREAD

**Issue by tmpm697** [romkatv/powerlevel10k#724]
I want to use custom dir setup in prompt, I don't find it's defined in ~/.p10k.zsh.

When I cd to a mutli-level directory like: cd ~/abc/de/mda/ddd, default p10k show extractly the same as it is, I want it list as ~/a/d/m/ddd

how to change with p10k?

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_DIR_MAX_LENGTH` and set its value to `0`.

**Comment by tmpm697** [comment]
@romkatv when under git repo, how to have branch (all repo related stuffs) always truncated? like: `feture/test/abc/namfdsa` to f/t/a/namfdsa`?

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for this line:

```zsh
where=${(V)VCS_STATUS_LOCAL_BRANCH}
```

Replace that line with this:

```zsh
setopt extended_glob
local MATCH MBEGIN MEND
where=${(V)${VCS_STATUS_LOCAL_BRANCH//(#m)[^\/]##\//$MATCH[1]/}}
```
