### ISSUE TITLE
Change symbol of vcs change/untracked ..etc?

### ISSUE THREAD

**Issue by tmpm697** [romkatv/powerlevel10k#725]
I want to change symbol of untracked file to `?`, modified file to `%`, after `git add .` command to `$`,
commit ahead remote to `+2` (ahead 2), behind to `-3` (behind 3)

How can I do that and also how to change color of them?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status

**Comment by tmpm697** [comment]
@romkatv How to change space between vcs statues like: `!1 ?2` to `!1?2`?

**Comment by romkatv** [comment]
Please expend more effort yourself.

**Comment by tmpm697** [comment]
@romkatv Please help, I read docs and tried to look into the code before ask, but I don't have much zsh programing experience.

**Comment by romkatv** [comment]
I'm sorry, you are asking for hand-holding and I don't provide that. You can either learn Zsh or ask other people to write the code for you.
