### ISSUE TITLE
Context format can't use with $HOST var?

### ISSUE THREAD

**Issue by tmpm697** [romkatv/powerlevel10k#727]
I'm trying to change context base on condition like `%B${HOST##*localhost*}%f%b` if `$HOST` is `localhost` then don't show.

`p10k` has some vars for it like `POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='<>'`, I tried to set them but context show raw `${localhost##*localhost*}` instead, how to have condition on context?

**Comment by romkatv** [comment]
You can use plain `if`:

```zsh
if [[ $HOST = localhost ]]; then
  POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE="..."
else
  POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE="..."
fi
```

By the way, it's very unlikely that `$HOST` is equal to `localhost`. Make sure you got that right. Verify with `print -r -- $HOST`.

**Comment by tmpm697** [comment]
It's critical to my workflow, as I work mostly with labs that have `localhost` as its default name, in real work, we can barely see this situation but in baremetal and labs.

**Comment by tmpm697** [comment]
@romkatv how to always show the context? I set `POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true` and create new shell but no shows the context.

**Comment by romkatv** [comment]
Note this in your config:

```zsh
# Don't show context unless running with privileges or in SSH.
# Tip: Remove the next line to always show context.
typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
```

Head the tip.

Please DO expend more effort on your part. The amount of hand-holding you are requesting is inappropriate.
