### ISSUE TITLE
Shorten that last directory with max length of N?

### ISSUE THREAD

**Issue by tmpm697** [romkatv/powerlevel10k#728]
I'm digging in `[ dir: current directory ]` of `~/.p10k.zsh` but I don't find a option to shorten the last directory if it's too long for e.g: `~/.ca/a/https-COLON--SLASH--SLASH-github.com-SLASH-romkatv-SLASH-powerlevel10k` to `~/.ca/a/https-COLON--SLASH--...romkatv-SLASH-powerlevel10k`

Baiscally if lenght of the last dir is more than 10 for e.g, then shorten it and place `...` in the middle of the name?

Sorry if this has in code before, I just don't find out. I tested with `POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=10` and `POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=5`  but both didn't give expected result.

**Comment by romkatv** [comment]
Look in `~/.p10k.zsh`:

```zsh
# Don't shorten this many last directory segments. They are anchors.
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
```

If you open another issue that can be resolved by saying "look at your config" or "look at FAQ", you'll get banned.
