### ISSUE TITLE
Python version shown in prompt twice with pyenv-virtualenv

### ISSUE THREAD

**Issue by nyuszika7h** [romkatv/powerlevel10k#730]
When using pyenv-virtualenv, and both `virtualenv` and `pyenv` are enabled in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`, it will result in the Python version being shown twice if I'm inside a project folder that's using a pyenv virtualenv. Disabling one of these solves the issue, but this should probably be fixed so it can work for either when they're not used together.

**Comment by romkatv** [comment]
Fixed. Update powerlevel10k and either run `p10k configure` to generate a new config or manually apply these changes to your `~/.p10k.zsh`:

- https://github.com/romkatv/powerlevel10k/commit/f96c1eb5e591bc10fd2e4e5f0bcd016ab0aba809
- https://github.com/romkatv/powerlevel10k/commit/6998d06a9168805a89b78ce403b70fac278d8454

**Comment by nyuszika7h** [comment]
Thanks! I like how it shows both the environment name and the Python version with pyenv-virtualenv now (rather than showing "Py envname" twice like the previous version did).

**Comment by reece-l** [comment]
Somewhat related, and I hope this is the right place to ask, but I use `venv` and `pyenv` and currently it seems to only show the `pyenv` local version on the right-hand-side.  I'd love if I could see both the `pyenv` local version and some additional indication that I have a `venv` virtual env activated too.  Is that easy to configure?

**Comment by romkatv** [comment]
@reece-l 

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=true
typeset -g POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION=
typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='venv'
```

This will show `venv` when you have an active virtual environment. You can replace `venv` with anything you like, including unicode icons.

```zsh
typeset -g POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION='●'
```

**Comment by reece-l** [comment]
@romkatv thanks!  I just changed `POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV` to `true` in the `p10k-rainbow.zsh` file (since I want to use the rainbow theme).  It seems `POWERLEVEL9K_VIRTUALENV_VISUAL_IDENTIFIER_EXPANSION` was already set to ⭐️, though I actually just get the name of the directory that my .venv file is in somehow.  Not a big issue for me though.

**Comment by romkatv** [comment]
> @romkatv thanks! I just changed `POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV` to `true` in the `p10k-rainbow.zsh` file (since I want to use the rainbow theme).

It's a bad idea to do this. These are not configs, they are templates. Please run `p10k configure` and then edit `~/.p10k.zsh`.

> I actually just get the name of the directory that my .venv file is in somehow. Not a big issue for me though.

Please read my comment once again and set all parameters just like I specified.

**Comment by reece-l** [comment]
Ah that makes sense, yep I should edit the `~/.p10k.zsh` instead of the template.

I don't find a `POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION` var in the template or the `~/.p10k.zsh` file though.

And again still the same issue with seeing a folder name rather than a start.

**Comment by romkatv** [comment]
> Ah that makes sense, yep I should edit the `~/.p10k.zsh` instead of the template.
> 
> I don't find a `POWERLEVEL9K_VIRTUALENV_CONTENT_EXPANSION` var in the template or the `~/.p10k.zsh` file though.

That's OK, just add it. This file doesn't list all parameters. I doesn't list even 10% of them.

> And again still the same issue with seeing a folder name rather than a star.

It'll disappear once you set all parameters I specified. You can simply copy-paste the whole block as I've written. (Do you feel I'm getting a bit frustrated with this exchange?)

**Comment by reece-l** [comment]
Ok I have it all working now, thanks for your patience :)

**Comment by romkatv** [comment]
> Ok I have it all working now, thanks for your patience :)

👍

**Comment by gschaffner** [comment]
Hi Roman, thanks for all your great work on p10k!

Currently, virtualenv is hidden if pyenv is already shown. Would you consider dynamically hiding virtualenv if virtualenv == pyenv? This would add support for displaying the active virtualenv even if this virtualenv is based on a shown pyenv-virtualenv.

**Comment by romkatv** [comment]
@gschaffner Done. Update powerlevel10k and set `POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=if-different`.

**Comment by gschaffner** [comment]
@romkatv Awesome, thank you!

**Comment by avatar-lavventura** [comment]
> ```shell
> venv
> ```

It shows `venv <username>` ; is it possible to show only `venv`?

**Comment by romkatv** [comment]
@avatar-lavventura Please open a separate issue.

**Comment by Cnly** [comment]
I've been thinking about displaying virtualenv and pyenv recently.

> Would you consider dynamically hiding virtualenv if virtualenv == pyenv? This would add support for displaying the active virtualenv even if this virtualenv is based on a shown pyenv environment.

Doesn't this mean that we should hide pyenv (not virtualenv), because we want to show the active virtualenv even if it's in a pyenv environment? Currently I'm using the following to prioritise showing virtualenv over pyenv instead:

```zsh
POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${VIRTUAL_ENV:+}$(test -z "$VIRTUAL_ENV" && echo $_p9k__pyenv_version)'
POWERLEVEL9K_PYENV_VISUAL_IDENTIFIER_EXPANSION='${VIRTUAL_ENV:+}$(test -z "$VIRTUAL_ENV" && print_icon PYTHON_ICON)'
```

**Comment by romkatv** [comment]
@Cnly Parameters with the names starting with `_p9k`, `__p9k` or `_P9K` are internal. If you rely on them, your shell may break in unpredictable ways without notice when you update powerlevel10k.

`CONTENT_EXPANSION` and `VISUAL_IDENTIFIER_EXPANSION` are evaluated on every command. Putting process substitutions in these parameters may introduce significant lag.

You probably want something like this instead:

```zsh
function p10k-on-pre-prompt() {
  # If virtualenv is active, hide pyenv.
  if [[ -n $VIRTUAL_ENV ]]; then
    p10k display '*/pyenv'=hide
  else
    p10k display '*/pyenv'=show
  fi
}
```

Put this function in `~/.p10k.zsh`, revert your custom changes to `POWERLEVEL9K_PYENV_CONTENT_EXPANSION` and `POWERLEVEL9K_PYENV_VISUAL_IDENTIFIER_EXPANSION`, and enable `virtualenv` segment.

**Comment by Cnly** [comment]
@romkatv Wow, that's immensely helpful, thank you!
