### ISSUE TITLE
gcloud segment always shows first configuration, not active one.

### ISSUE THREAD

**Issue by JSteeleIR** [romkatv/powerlevel10k#731]
I think [90d19e6](https://github.com/romkatv/powerlevel10k/commit/90d19e6f97dfde0709148a27ea0c2f0f248398d7#diff-21234a8c0b8c7f9b8d29cf3d2c4e93acR4343) in #318 introduced a bug into the gcloud segment, whereby it will always return the project_id and account for the first (alphabetical) configuration, instead of the currently active one.

`gcloud config configurations list --configuration=$P9K_GCLOUD_CONFIGURATION \
      --format=$'value[separator="\1"](properties.core.account,properties.core.project)` (as used in the new logic, seems to return those properties for all of the configs, regardless of the `--configuration` parameter. Therefore, p10k always shows the project_id/account of the first configuration and just ignores the rest.

(I can't provide direct examples, since I'd have to go through and redact the names & accounts out of my configs, sorry.) Should be reproducible by creating a second gcloud config, and switching between them to observe how p10k is parsing the values in the configs.

**Comment by romkatv** [comment]
Thanks for the report. Fixed.

**Comment by JSteeleIR** [comment]
Wow! Fantastic turnaround! Thanks!

Do you have a donation thing set up anywhere?
I loved what you've done with this whole project, and that kind of response deserves a beer!🍺

**Comment by romkatv** [comment]
> Wow! Fantastic turnaround! Thanks!

Have you tried the fix? Does it work for you?

> Do you have a donation thing set up anywhere?

No. More hassle than it's worth.

> I loved what you've done with this whole project, and that kind of response deserves a beer!

Thanks!

**Comment by JSteeleIR** [comment]
Alright! Keep on being awesome!

**Comment by JSteeleIR** [comment]
> Have you tried the fix? Does it work for you?

Hey, sorry. I missed this line when I was replying from mobile. 

I just tried the fix today, and it still doesn't seem to be working for me. 

Running the `gcloud config configurations describe $P9K_GCLOUD_CONFIGURATION --format=$'value[separator="\1"](properties.core.account,properties.core.project)'` manually is extracting the right project_id/account from my active config now (and not showing any other configs), but for some reason the instant prompt is still showing the project_id from the first configuration. 

The `$P9K_GCLOUD_CONFIGURATION` var is correct, but the `$P9K_GCLOUD_PROJECT` and `$P9K_GCLOUD_PROJECT_ID' vars still have the inactive configuration value? 

Perhaps the cache update isn't actually taking effect, or the instant prompt is somehow still stuck to the old values?

**Comment by romkatv** [comment]
What do you mean by instant prompt?

What is the output of the following command:

```zsh
print -r -- ${_p9k__param_pat%%$'\1'*}
```

If it's less than `v87`, you aren't using the latest version of powerlevel10k. Please update.

If it's `v87` or greater, please describe what you do, what you expect and what you observe. The output of the following command would be most helpful:

```zsh
() {
  emulate -L zsh -o xtrace
  typeset -pm 'P9K_GCLOUD_*'
  cat ~/.config/gcloud/active_config <(print)
  gcloud config configurations describe $P9K_GCLOUD_CONFIGURATION --format=$'value[separator="|"](properties.core.account,properties.core.project)'
}
```

Feel free to replace real values with dummy values, just make sure to keep equality relationships intact.

**Comment by JSteeleIR** [comment]
> What do you mean by instant prompt?
Err... Sorry, wrong term. I was calling the "only display segment when the current command will invoke that tool" 'instant prompt'. 

> What is the output of the following command:
> 
> ```shell
> print -r -- ${_p9k__param_pat%%$'\1'*}
> ```
> 
> If it's less than `v87`, you aren't using the latest version of powerlevel10k. Please update.

Apparently I'm only on v84? I'm not sure I understand how that's the case. I have p10k checked out as a submodule in my dotfiles, and it's checked out at c0091537.

Do I have to re-run `p10k configure` after an update?

**Comment by JSteeleIR** [comment]
Ah! I think I've figured it out. Somehow the symlink I had from `oh-my-zsh/custom/themes/powerlevel10k-> <submodule>` wasn't actually a symlink, it was another full copy of the repo. 

After fixing that, (and confirming that I'm on v87), everything is working properly.

Thanks for your help/patience!

**Comment by romkatv** [comment]
I'm glad you've got it sorted out. Thanks again for filing the bug report.
