### ISSUE TITLE
Pattern to match other users' homes

### ISSUE THREAD

**Issue by rejsmont** [romkatv/powerlevel10k#732]
Hi,

I am trying to define a DIR_CLASS for other user's home directories. Unfortunately, I cannot find a pattern to match against other users' homes:

```
typeset -g POWERLEVEL9K_DIR_CLASSES=(
    '~*'     HOME_O   ''
    '*'       DEFAULT  '')
``` 

The above does not work :( Do you have any ideas / tips?

Also - I am missing an option for HOME_FOLDER_ABBREVIATION for other users - would be great to be able to customize that.

Thanks in advance!

Radek

**Comment by romkatv** [comment]
These are regular zsh patterns, so you can test them at the command line:

```zsh
print -r -- ~
print -r -- ~*
```

The first works, the second doesn't.

You could try `/home/*`. If you put this pattern after the one that matches your own home directory, you'll get matches only for home directories of other users.
