### ISSUE TITLE
I can't change or remove folder icon

### ISSUE THREAD

**Issue by FlatZephyr** [romkatv/powerlevel10k#733]
Hello, I'm sorry if repeat question, or my question overly stupid, but I really have tried to find answer among issues or find answer in .p10k.zsh, but I steel can't change or remove folder icon. I have seen "...###[ dir: current directory ]###..." section, but I haven't found corresponding variable which responds particularly for home or folder icon. How can I change or remove this icon?
Also I have seen 'POWERLEVEL9K_DIR_CLASSES' variable, may be this is crucial variable, but I even don't know what **names** of icons exist.
![home_and_folder_arrows](https://user-images.githubusercontent.com/65401519/82234831-91b60700-993a-11ea-8844-676b0ef663c3.png)

**Comment by romkatv** [comment]
You can do it like this:

```zsh
POWERLEVEL9K_DIR_CLASSES=()
```

I see in your screenshot that your prompt is misconfigured -- there is too much empty space between icons and content. I highly recommend running `p10k configure` and then editing the resulting config rather than writing your config from scratch.

**Comment by sujeet-agrahari** [comment]
> You can do it like this:
> 
> ```shell
> POWERLEVEL9K_DIR_CLASSES=()
> ```
> 
> I see in your screenshot that your prompt is misconfigured -- there is too much empty space between icons and content. I highly recommend running `p10k configure` and then editing the resulting config rather than writing your config from scratch.

There is already a line in `~/.p10k.zsh`
```
typeset -g POWERLEVEL9K_DIR_CLASSES=()
```
Just uncomment this line.
