### ISSUE TITLE
SHOW_ON_COMMAND for subcommands

### ISSUE THREAD

**Issue by MichaelAquilina** [romkatv/powerlevel10k#734]
Is it possible to conditionally show prompts based on subcommands

e.g. I want to show a prompt when the user has typed `git commit` but not when they have typed `git status`?

Initial attempts at this seemed to indicate its not possible

If it's currently not possible, is this something I could look into adding?

**Comment by romkatv** [comment]
This is not possible with `SHOW_ON_COMMAND` but you can do something similar through `p10k-on-post-widget`:

```zsh
function p10k-on-post-widget() {
  # If $BUFFER invokes `git` and contains "commit", show prompt
  # segment "foo". Otherwise hide it.
  local z=$'\0'
  if [[ $P9K_COMMANDS[(I)(|*[/$z])git] != 0 && $BUFFER == *commit* ]]; then
    p10k display '*/foo'=show
  else
    p10k display '*/foo'=hide
  fi
}
```

`p10k-on-post-widget` is called after every zle widget when PS1 is active. Within it you have access to array parameter `P9K_COMMANDS`. It contains all commands from `$BUFFER`. Each element is a nul-separated list. The last component is the actual command (`git`, `kubectl`, `foo/bar`, `grep`, etc.). The previous components are precommands (`sudo`, `nice`,`nohup`, etc.) . For example:

```zsh
( exec sudo -u user =ls /etc ) && foo/bar
```

... results in the following `P9K_COMMANDS`:

```zsh
P9K_COMMANDS=(
  $'exec\0sudo\0/bin/ls'
  'foo/bar'
)
```

`SHOW_ON_COMMAND` is essentially a wrapper around `p10k-on-post-widget` API.

`p10k display` is documented in `p10k help display`.

**Comment by MichaelAquilina** [comment]
Works perfectly thanks @romkatv!

**Comment by MichaelAquilina** [comment]
Is there anything special I need to do to get this to also work with aliases? I noticed that `SHOW_ON_COMMAND` worked fine with those and you mentioned that was just essentially a wrapper around `p10k-on-post-widget`

**Comment by romkatv** [comment]
> Is there anything special I need to do to get this to also work with aliases? I noticed that `SHOW_ON_COMMAND` worked fine with those and you mentioned that was just essentially a wrapper around `p10k-on-post-widget`

No. Just edit the condition as you like. If you can tell me what aliases you use and how you want to look like for some example command lines, I can tell you how to achieve that.

**Comment by MichaelAquilina** [comment]
I have the following aliases

```
alias gc="git commit"
alias gca="git commit --amend"
```

There's probably a nice way to do this automatically, just thought there might be something by p10k considering `SHOW_ON_COMMAND` seemed to work out of the box for it.

**Comment by romkatv** [comment]
```zsh
function p10k-on-post-widget() {
  # If $BUFFER invokes `git` and contains word "gca", show prompt
  # segment "foo". Otherwise hide it.
  local z=$'\0'
  if (( $P9K_COMMANDS[(I)(|*[/$z])git] && ${${(z)BUFFER}[(I)gca]} )); then
    p10k display '*/foo'=show
  else
    p10k display '*/foo'=hide
  fi
}
```

**Comment by MichaelAquilina** [comment]
Not sure if I'm using it wrongly but that didnt seem to work for me.

I've tweaked your original function to automatically look through and compare aliases (albeit naively and probably not very effeciently)

```shell
function p10k-on-post-widget() {
  local key
  for key in "${(@k)aliases}"; do
    local value="${aliases[$key]}"
    if [[ "$value" == "git commit"* && "$BUFFER" == "$key"* ]]; then
      p10k display '*/git_user'=show
      return
    fi
  done

  # If $BUFFER invokes `git` and contains "commit", show prompt
  # segment "git_user". Otherwise hide it.
  local z=$'\0'
  if [[ $P9K_COMMANDS[(I)(|*[/$z])git] != 0 && $BUFFER == *commit* ]]; then
    p10k display '*/git_user'=show
    return
  fi

  p10k display '*/git_user'=hide
}
```

However it seems to work and it doesnt show any slowdown on my terminal :)
