### ISSUE TITLE
Branch background color taking a while to show up

### ISSUE THREAD

**Issue by amarbayar** [romkatv/powerlevel10k#736]
I have just upgraded from powerlevel9k -> powerlevel10k because I was seeing a really slow behavior in the former. After the upgrade, performance has flown out the roof and thank you for this! :) 

One thing I cannot quiet get it to work properly is that, when inside a git directory, the branch background color takes a while a to show up. 

Simply ran `clear` inside the git directory and the branch shows like below first:
<img width="1150" alt="Screen Shot 2020-05-18 at 12 07 44 PM" src="https://user-images.githubusercontent.com/8435370/82250524-775f3780-9900-11ea-94f1-8640772aae74.png">

After about 2-3 seconds, the background color shows up properly: 
<img width="1150" alt="Screen Shot 2020-05-18 at 12 07 50 PM" src="https://user-images.githubusercontent.com/8435370/82250533-7c23eb80-9900-11ea-920e-523ca2389e72.png">

I have enabled `set -x` in my `~/.zshrc` and looked at. It looked like it was the `typeset -g my_git_format` which was eventually executing after which enabled the background color. But I couldn't tell what was making it run after 2-3 seconds. 

Has anyone ran into this issue before?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-does-git-status-sometimes-appear-grey-and-then-gets-colored-after-a-short-period-of-time
