### ISSUE TITLE
miss p10k-spaceship

### ISSUE THREAD

**Issue by glepnir** [romkatv/powerlevel10k#742]
Hi found the p10k-spaceship on your gif .but i didn't fint it on config folder

**Comment by romkatv** [comment]
Right under the gif:

> [Pure](#pure-compatibility), [Powerlevel9k](#powerlevel9k-compatibility) and [robbyrussell](
  #how-to-make-powerlevel10k-look-like-robbyrussell-oh-my-zsh-theme) emulations are built-in. To emulate the appearance of other themes, you'll need to write a suitable configuration file. The best way to go about it is to run `p10k configure`, select the style that is the closest to your goal and then edit `~/.p10k.zsh`.
