### ISSUE TITLE
Support more bold options

### ISSUE THREAD

**Issue by glepnir** [romkatv/powerlevel10k#744]
Thanks for greate work.How can i set the vcs format font  to bold and the `on`  `took` etc to font? p10k.zsh only provide a few bold options.Normal font is easy to mix with output, bold can highlight prompt.
![image](https://user-images.githubusercontent.com/41671631/82435021-4c264500-9ac6-11ea-817d-dbb471adb647.png)

**Comment by romkatv** [comment]
You make things bold by enclosing them in `%B...%b`. To make git branch bold, find this line in `~/.p10k.zsh`:

```zsh
res+="${clean}${where//\%/%%}"  # escape %
```

And replace it with this:

```zsh
res+="%B${clean}${where//\%/%%}%b"  # escape %
```

To make "on" bold, find this line:

```zsh
typeset -g POWERLEVEL9K_VCS_PREFIX='%fon '
```

And replace it with this:

```zsh
typeset -g POWERLEVEL9K_VCS_PREFIX='%B%fon%b '
```
