### ISSUE TITLE
_p9k_worker_start: failed to close file descriptor: bad file descriptor

### ISSUE THREAD

**Issue by Stakker** [romkatv/powerlevel10k#745]
Hi

Sorry if this is not really an issue, but I couldn't figure out where else to ask for advice...

I just migrated from Bash to ZSH (feel like an idiot for not doing it earlier now :-) and installed Oh My ZSH & powerlevel10k on two Macs. Both have Catalina and I did the upgrade from Bash as suggested by Apple. (And WOW is Oh My ZSH and powerlevel10k an awesome combination!)

For some reason I get these three errors during instant prompt only on one Mac, even though the setups and install route should be pretty much identical:

-- console output produced during zsh initialization follows --

_p9k_worker_start:8: failed to close file descriptor 13: bad file descriptor
_p9k_worker_start:9: failed to close file descriptor 14: bad file descriptor
_p9k_worker_start:10: failed to close file descriptor 15: bad file descriptor

If you could point me to the right direction for finding a fix, I would really appreciate it! Cheers.

**Comment by romkatv** [comment]
Please update powerlevel10k.

**Comment by Stakker** [comment]
Yep, that did it. Much appreciated, thank you!
