### ISSUE TITLE
Support for random backgrounds on different hostnames

### ISSUE THREAD

**Issue by 3v1n0** [romkatv/powerlevel10k#746]
Would be nice to have the ability to set random colors (or defined ones) depending on the hostname you're connected to.

So that it would be possible to share the same configuration between multiple machines but with different colors so that when SSH-ing between them, they are still easy to discern

**Comment by romkatv** [comment]
Colors are set in your config (usually `~/.p10k.zsh`). You can set them conditionally based on hostname if you like.

**Comment by romkatv** [comment]
Here's an example:

```zsh
local -i host_color="${$(sum <<<${(%):-%m})[1]} % 15 + 1"
```

Now assign any `BACKGROUND` or `FOREGROUND` parameter in `~/.p10k.zsh` to `$host_color`.
