### ISSUE TITLE
Custom kubecontext commands?

### ISSUE THREAD

**Issue by ingshtrom** [romkatv/powerlevel10k#749]
Hey, I recently came across [kubeprompt](https://github.com/jlesquembre/kubeprompt), which I would like to use instead of whatever the default function is for the `kubecontext` prompt segment. Is there a way I can completely override the function that gets the information for the prompt, but keep all of my custom formatting like `*SHOW_ON_COMMAND`, `*CLASSES`, `*FOREGROUND`, etc?

Thank you for all of yours work on p10k--it's a real game changer and I cannot imagine using anything else!

**Comment by romkatv** [comment]
You can define a custom segment. See https://github.com/romkatv/powerlevel10k/blob/master/README.md#extensible and search for `prompt_example` in `~/.p10k.zsh`.

I've only skimmed https://github.com/jlesquembre/kubeprompt but it seems you won't gain anything by displaying it as a custom prompt segment. It appears to support a strict subset of the builtin `kubecontext` functionality.

**Comment by ingshtrom** [comment]
:+1: I tried this and you are right, unfortunately. Thank you for the quick feedback, though.

The functionality I needed was better done in a custom script at the end of my `~/.zshrc`--easier than messing with this other prompt tool. :smile:
