### ISSUE TITLE
Prompt glitches after segmentation fault

### ISSUE THREAD

**Issue by jasonkena** [romkatv/powerlevel10k#751]
After a segmentation fault or a core dump from the running program, the prompt breaks.

Normal Prompt:
![Screen Shot 2020-05-22 at 14 11 06](https://user-images.githubusercontent.com/35003073/82641163-1a33f080-9c36-11ea-8913-a0db2e65644a.png)

Broken Prompt:
![image](https://user-images.githubusercontent.com/35003073/82641478-975f6580-9c36-11ea-989d-919f9a7bee3d.png)

**Comment by romkatv** [comment]
Does it unbreak if you press <kbd>Enter</kbd>?

Does this also happen if you press <kbd>Ctrl-C</kbd>?

**Comment by jasonkena** [comment]
Nope, pressing enter just adds new lines.
![image](https://user-images.githubusercontent.com/35003073/82642131-a72b7980-9c37-11ea-947f-0a085dd00c5c.png)

Pressing `Ctrl-C` when the segfault hasn't occurred still behaves well.
![image](https://user-images.githubusercontent.com/35003073/82642206-c4604800-9c37-11ea-914a-c639c3945983.png)

But `Ctrl-C` after the segfault does not register
![image](https://user-images.githubusercontent.com/35003073/82642288-de018f80-9c37-11ea-98fd-672f9acdaa0d.png)

**Comment by romkatv** [comment]
I cannot reproduce this. Please provide all steps necessary to reproduce.

**Comment by romkatv** [comment]
Oh, I see that the program that crashed is `nvim`. It has probable hosed your terminal. Try typing `reset`. If that doesn't help, your'll have to close terminal and open another one. This has nothing to do with powerlevel10k.

**Comment by jasonkena** [comment]
Thanks, using `reset` worked like a charm!
