### ISSUE TITLE
show stash count in VCS output

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/powerlevel10k#752]
I am trying to get the stash count to show in the VCS output. Prior i used:
`typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED}_MAX_NUM=99`
to do this, but I am trying to upgrade to latest version of all the configs and to rely on p10k config :)

**Comment by romkatv** [comment]
Type `p10k configure`. Now you have stash.

**Comment by kurktchiev** [comment]
I did, thats how I got to the prompt I currently have, but when i am in a directory that has 2 things stashed, it doesn't really change the prompt

**Comment by romkatv** [comment]
Seems implausible. Try removing everything from your zshrc except for `source ~/.p10k.zsh` and `source powerlevel10k.zsh-theme`. Then restart terminal.
