### ISSUE TITLE
Symbol for "visual" in vi mode does not render

### ISSUE THREAD

**Issue by MithicSpirit** [romkatv/powerlevel10k#754]
The `Ⅴ` symbol for visual when in VI mode does not render properly and is just a (green) rectangle in conhost (windows), despite having the right font installed and everything (from what I can tell all other symbols are correct). In Windows Terminal it looks fine I think (not sure what it is _actually_ supposed to look like).

![image](https://user-images.githubusercontent.com/24192522/82719746-605f7300-9c7b-11ea-9c2a-5f28138a1da8.png)
Conhost

![image](https://user-images.githubusercontent.com/24192522/82719762-8258f580-9c7b-11ea-9415-86e50458c698.png)
Windows Terminal

**Comment by romkatv** [comment]
Thanks for the report. I've replaced This glyph (roman numeral 5) with plan V. You can either manually change it in your `~/.p10k.zsh` (search for `VIVIS_CONTENT_EXPANSION`) or update powerlevel10k and run `p10k configure` to create a new config.
