### ISSUE TITLE
On Start, _pk9_worker_start issue

### ISSUE THREAD

**Issue by AlikanakelaKarwowski** [romkatv/powerlevel10k#755]
Using WSL Ubuntu, oh-my-zsh, and the latest version of p10k theme. I run across the following issues when starting up my zsh shell
```
_p9k_worker_start:8: failed to close file descriptor 14: bad file descriptor
_p9k_worker_start:9: failed to close file descriptor 15: bad file descriptor
_p9k_worker_start:10: failed to close file descriptor 16: bad file descriptor
```
This has occurred since ive installed and used the theme.

Otherwise everything else works great

**Comment by romkatv** [comment]
Please update powerlevel10k.
