### ISSUE TITLE
p10k cause ssh-agent invalid on first time loading

### ISSUE THREAD

**Issue by stardiviner** [romkatv/powerlevel10k#756]
This is the first time I start oh-my-zsh.

```
Starting ssh-agent...
Enter passphrase for /home/stardiviner/.ssh/id_rsa: 
Identity added: /home/stardiviner/.ssh/id_rsa (/home/stardiviner/.ssh/id_rsa)
Starting ssh-agent...
ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
❯ source ~/.oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh
Enter passphrase for /home/stardiviner/.ssh/id_rsa: 
Identity added: /home/stardiviner/.ssh/id_rsa (/home/stardiviner/.ssh/id_rsa)
❯ tmux
no sessions
[detached (from session 0)
```
You can see, ssh-agent not correct when I first time start zsh. Then I have to load it manually by executing that `source` command.

I followed REAMDE instructions by added the p10k loading command line at bottom of `~/.zshrc` profile file.

**Comment by romkatv** [comment]
The best solution by far is to not use ssh-agent plugin (remove it from your zshrc) and instead add this to `~/.ssh/config`:

```zsh
Host *
  AddKeysToAgent yes
```

An alternative solution is to run `p10k configure` and disable *Instant Prompt* when asked about it. It's close to the end.

**Comment by stardiviner** [comment]
I see, Thanks @romkatv

**Comment by YAmikep** [comment]
Would there be a solution where the `ssh-agent` works with Instant Prompt? (based on load order?) 

For example, if I do `source .oh-my-zsh/plugins/ssh-agent/ssh-agent.plugin.zsh` after the prompt is ready, it executes the ssh-agent plugin and it works fine.

Would it be possible for `powerlevel10k` to do this automatically?

**Comment by romkatv** [comment]
The best solution by far is to not use ssh-agent plugin (remove it from your zshrc) and instead add this to `~/.ssh/config`:

```zsh
Host *
  AddKeysToAgent yes
```

**Comment by romkatv** [comment]
> I am confused, this is not doing the same thing as far as I can tell.
> It does not start the ssh-agent, add an identity and ask for my passphrase when doing so.

That's the entire point.

Why *would* you want to enter password for your ssh keys when starting your shell? Nobody does that with the exception of oh-my-zsh users. Everyone else enters password either on the first use of an ssh key or when logging in to the OS.

**Comment by electropolis** [comment]
In my case that solution worked

```bash
ssh-add -l > /dev/null
EXITCODE="$?"
test $EXITCODE -eq 0 || ssh-add --apple-load-keychain;
```
But it failed because 

```bash
Identity added: /Users/konrad/.ssh/id_rsa_sonic (konrad@macbook)
Identity added: /Users/konrad/.ssh/id_ed25519_pve1 (root@pve1)
Identity added: /Users/konrad/.ssh/id_ed_sonic (konrad@esetMac.local)
Identity added: /Users/konrad/.minikube/machines/minikube/id_rsa (/Users/konrad/.minikube/machines/minikube/id_rsa)

[WARNING]: Console output during zsh initialization detected.

When using Powerlevel10k with instant prompt, console output during zsh
initialization may indicate issues.

❯ ssh-add -l
The agent has no identities.
```

So basically Instant prompt puts output although the script has 
`ssh-add -l > /dev/null`

not to generate any output. 
Second, it doesn't even load those keys. So it looks like something is killing them when p10k loads all settings from `.zprofile`

Setting 
`AddKeysToAgent yes`
awesome, it basically does the same thing. Meaning running ssh-agent and loads keys into it but does it prevent user for typing passwords while doing it ? Because that's the whole point for MacOS to use
`--apple-load-keychain  -- add identities from keychain`

btw it's funny that running
`source .zprofile` .. works :/

```
❯ source .zprofile
Identity added: /Users/konrad/.ssh/id_rsa_sonic (konrad@macbook)
Identity added: /Users/konrad/.ssh/id_ed25519_pve1 (root@pve1)
Identity added: /Users/konrad/.ssh/id_ed_sonic (konrad@esetMac.local)
Identity added: /Users/konrad/.minikube/machines/minikube/id_rsa (/Users/konrad/.minikube/machines/minikube/id_rsa)
❯ ssh-add -l
4096 SHA256:QnMYoZ8+Vwv8ZuG+GRFPbICbeBEy+pRC5dZfH2sSp+Y konrad@macbook (RSA)
256 SHA256:AejMwHbQGtV9RNe1bh+K9sY10w66O5ZDN3yeSLIrmsU root@pve1 (ED25519)
256 SHA256:PcJ8kKpZKA6BoO1BDMp5IlBz+gXn6yNM1OBhAaZPzho konrad@esetMac.local (ED25519)
2048 SHA256:VgMp9SJytxeskh/ywC1KXE6hZP0/MST7IWOeo7DgQcc /Users/konrad/.minikube/machines/minikube/id_rsa (RSA)
```
