### ISSUE TITLE
Gitstatus not working with Mackup's simple link

### ISSUE THREAD

**Issue by ph00lt0** [romkatv/powerlevel10k#758]
I am using [Mackup](https://github.com/lra/mackup) to backup my configuration. This creates a simple link to config files in another location. Everything works as it should however I get the following error:

[ERROR]: gitstatus failed to initialize.

  Your git prompt may disappear or become slow.

  Run the following command to retry with extra diagnostics:

    GITSTATUS_LOG_LEVEL=DEBUG gitstatus_start -s -1 -u -1 -d -1 -c -1 -m -1 -a POWERLEVEL9K

The debug info tells me :
`    +gitstatus_start_impl:14> [[ -x ' ... /Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64' ]]`
                               ^ this command failed

**Comment by romkatv** [comment]
> The debug info tells me :
> ` +gitstatus_start_impl:14> [[ -x ' ... /Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64' ]]`
> ^ this command failed

Is this a real error message?

**Comment by romkatv** [comment]
I also noticed that your powerlevel10k is very old. Your issue can likely be resolved by updating powerlevel10k. See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k

**Comment by ph00lt0** [comment]
Yep that was a real error message. I updated the installation, but now it's not working at all. When opening a terminal I see:
`[powerlevel10k] fetching gitstatusd .. -                                                                           `
This keeps loading and nothing happens afterwards.

**Comment by romkatv** [comment]
> Yep that was a real error message.

The error message says that this file is not executable:

> ' ... /Mackup/.oh-my-zsh/custom/themes/powerlevel10k/gitstatus/bin/gitstatusd-darwin-x86_64'

It looks obviously broken. Note the leading spaces and dots.

There is practically zero chance that this error message could be produced by Powerlevel10k.

> This keeps loading and nothing happens afterwards.

It needs to download 1MB either from github.com or from gitee.com. If your Internet connection is very slow to both of these sites, it can take some time.

**Comment by ph00lt0** [comment]
I actually managed to fix it now by redoing the config of powerlevel10k. I guess it just got incompatible after not updating. Thanks for helping out. 

The dots are just a replacement to hide my folder location tho :D That wasn't the issue.

**Comment by romkatv** [comment]
> I actually managed to fix it now by redoing the config of powerlevel10k. I guess it just got incompatible after not updating. Thanks for helping out.

This is implausible.

> The dots are just a replacement to hide my folder location tho :D That wasn't the issue.

The error message said the file was not executable. I'm 100% certain. This was the issue.
