### ISSUE TITLE
Is it possible to change the nvm icon?

### ISSUE THREAD

**Issue by muuvmuuv** [romkatv/powerlevel10k#76]
I would like to remove the nvm nodejs icon, is there an option for that?

```shell
             ⇣              
~/Documen... ⬢ 10.15.3
❯
```

**Comment by romkatv** [comment]
You can define `POWERLEVEL9K_NODE_ICON='blah'` to change the icon. Set it to an empty string to have no icon at all.

**Comment by muuvmuuv** [comment]
AH, omg, I just tried `POWERLEVEL9K_NVM_ICON='blah'`. Thanks!

**Comment by mykhaliuk** [comment]
Setting 
```
  # NVM
  # typeset -g POWERLEVEL9K_NVM_BACKGROUND="black"
  typeset -g POWERLEVEL9K_NVM_FOREGROUND="002"
  typeset -g POWERLEVEL9K_NVM_VISUAL_IDENTIFIER_COLOR="002"
  typeset -g POWERLEVEL9K_NVM_ICON="\uf898"
  typeset -g COMPLETION_WAITING_DOTS="true"
```
didn't give an icon. Any thoughts please?

**Comment by romkatv** [comment]
@mykhaliuk  It's the same problem the OP had, so the same solution will work. Read the comments advice yours.

**Comment by mykhaliuk** [comment]
@romkatv, thanks a lot for a fast answer. Probably I've missed something, but neither `POWERLEVEL9K_NVM_ICON` nor `POWERLEVEL9K_NODE_ICON` doesn't give icon appeared in my case.

**Comment by romkatv** [comment]
@mykhaliuk Please run `p10k configure`. If this doesn't give you a prompt you like, post your full zshrc here.
