### ISSUE TITLE
Space on the right?

### ISSUE THREAD

**Issue by mamercad** [romkatv/powerlevel10k#760]
How can I remove this space on the right (the space above the "e")?

<img width="144" alt="image" src="https://user-images.githubusercontent.com/6192266/82757102-3a85bb80-9dac-11ea-95ad-0e1399a08cfa.png">

**Comment by romkatv** [comment]
```zsh
ZLE_RPROMPT_INDENT=0
```

See the bottom of this page: http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-ZLE_005fRPROMPT_005fINDENT
