### ISSUE TITLE
asdf shows ALL listed versions instead of selected version

### ISSUE THREAD

**Issue by bjeanes** [romkatv/powerlevel10k#764]
asdf lets you define a `.tool-versions` file that lists multiple versions with precedence, such as:

```
golang 1.14.2 1.14.1 1.14 1.13.9 1.13.8 1.13.7 1.13.6 1.13.5 1.13.4 1.13.3 1.13.2 1.13.1 1.13
```

I take advantage of this in my "global" configuration so that by default the highest installed is selected. I wish asdf allowed you to just specify major versions but alas, this is my only option. I have a script which generates my global `.tool-versions` regularly (filtering out beta, rc, etc).

Since this is a feature of asdf, it seems like the asdf component in p10k should be a bit more careful than its current behaviour, which is to dump the entire version string.

I think that taking the first space-delimited "word" would not suffice as that wouldn't necessarily be what is activated. Cross-referencing with installed versions in `~/.asdf` would be ideal (or interrogating `asdf` directly, but I suspect that is not fast enough).

![image](https://user-images.githubusercontent.com/2560/82793145-c9313000-9eb3-11ea-861e-ed3e0aa58a68.png)

**Comment by romkatv** [comment]
Thanks for the report. Fixed. Please update powerlevel10k and try again.

P.S.

You might want to add this to your `~/.zshrc`:

```zsh
# ~h is my windows home directory.
hash -d h=/mnt/c/Users/me
```

Then you can use `~h` the same way you use `~` (`cd ~h`, `ls ~h/Downloads`, etc.). Prompt will also reflect that.

**Comment by bjeanes** [comment]
> You might want to add this to your `~/.zshrc`:

Super awesome tip. Thanks!

**Comment by bjeanes** [comment]
Confirmed that this appears to work!

![image](https://user-images.githubusercontent.com/2560/82847221-439f9580-9f30-11ea-9b4d-bceac8ced6a6.png)

![image](https://user-images.githubusercontent.com/2560/82847878-f0c7dd00-9f33-11ea-9a8b-5b79e201a20b.png)

(I have also since configured the `_ON_UPGLOB` settings for the languages I use, which makes this just really such a beautiful feature 🙏)

**Comment by romkatv** [comment]
Thanks for the confirmation and double for reporting the bug in the first place.
