### ISSUE TITLE
Getting segmentation fault

### ISSUE THREAD

**Issue by siva-sundar** [romkatv/powerlevel10k#767]
I am getting segmentation fault on running the second command.

![image](https://user-images.githubusercontent.com/15258941/82870419-8ae84f00-9f4d-11ea-8d8a-f2c5a03068ce.png)

**Comment by romkatv** [comment]
Powerlevel10k is a theme for zsh. It doesn't provide zsh itself. If zsh crashes, you need to report this bug and/or ask for help someplace else.
