### ISSUE TITLE
custom segment

### ISSUE THREAD

**Issue by ImKifu** [romkatv/powerlevel10k#768]
Can i have this code? I don't know the icon HOT and WARM, and *C

https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/custom-segment.gif

**Comment by romkatv** [comment]
```zsh
function prompt_my_cpu_temp() {
  integer cpu_temp="$(</sys/class/thermal/thermal_zone0/temp) / 1000"
  if (( cpu_temp >= 80 )); then
    p10k segment -s HOT  -f red    -t "${cpu_temp}"$'\uE339' -i $'\uF737'
  elif (( cpu_temp >= 60 )); then
    p10k segment -s WARM -f yellow -t "${cpu_temp}"$'\uE339' -i $'\uE350'
  fi
}
```

You can search for icons here: https://www.nerdfonts.com/cheat-sheet

**Comment by ImKifu** [comment]
Thank you for your supporting <3

I copy it to p10k.zsh file, then i reboot the machine.

After login, i hit enter for few time. Then it disappear.

I don't know why, can you help me?
![Screenshot from 2020-05-27 08-45-52](https://user-images.githubusercontent.com/37338905/82968336-487b4c80-9ff7-11ea-9d3c-be500b8b8b6f.png)

**Comment by romkatv** [comment]
The function I posted displays temperature above 80 degrees as HOT, above 60 degrees as WARM and below 60 it doesn't display it at all. When you booted the machine it was at 62 degrees, then it got below 60 degrees.

**Comment by paulchabotca** [comment]
Funny enough, I just took a quick screen cap and copied the code, but I am trying to find information on the segment command.

-s state  segment's state for the purpose of applying styling options; if you want to
            to be able to use POWERLEVEL9K parameters to specify different colors or icons
            depending on some property, use different states for different values of that
            property

I can't seem to find what styles I can use? Is it just WARM and HOT? or do I make those in my zsh profile?

Loving the upgrade, so fast from 9k.

**Comment by romkatv** [comment]
> Funny enough, I just took a quick screen cap and copied the code, but I am trying to find information on the segment command.

Type `p10k help segment`.

> I can't seem to find what styles I can use? Is it just WARM and HOT? or do I make those in my zsh profile?

You can use anything.

> Loving the upgrade, so fast from 9k.

Thanks 😄
