### ISSUE TITLE
[req] Anny hope in getting this on powershell with oh-my--posh ?

### ISSUE THREAD

**Issue by NicTanghe** [romkatv/powerlevel10k#769]
So incase you want your powerlevel to climb over 10k maybe making a skin for oh-my-posh zhould be awsome.

**Comment by romkatv** [comment]
> Anny hope in getting this on powershell with oh-my--posh ?

None.

> So incase you want your powerlevel to climb over 10k maybe making a skin for oh-my-posh zhould be awsome.

Or I just wait.
