### ISSUE TITLE
Config help and instant prompt configuration

### ISSUE THREAD

**Issue by NICHOLAS85** [romkatv/powerlevel10k#772]
I am currently using the following config: https://gist.github.com/NICHOLAS85/0107c3fb87aaf91583dc318bbec9c856

Which is a slightly modified version of the config linked here: https://github.com/romkatv/powerlevel10k/issues/389#issuecomment-626137244

My actual issue is there is a space at the top left side of my prompt which I'd like to get rid of as seen here:
![image](https://user-images.githubusercontent.com/15698885/83192718-f116d280-a103-11ea-8816-7f031429a702.png)

This isn't present in any of the default configurations so I believe it was introduced somewhere in that config but I haven't been able to find it. If you happen to know where in that configuration I should be looking to edit I'd love to know!

---
The instant prompt is a great feature and has been working well so far. Recently, I've added a small snippet that outputs my current directory to a temporary file. When I open a new terminal this file is used to `cd` into leaving me at where I last left off.
Unfortunately, the instant prompt always displays the home directory before my terminal switches directories. Is there a way to either write to the instant prompt file with this directory or configure instant prompt to read from that file to provide the directory it uses?
Heres the relevant snippet code:

<details>
<summary>snippet</summary>

```zsh
autoload -Uz chpwd_recent_dirs
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-file "$TMPDIR/chpwd-recent-dirs"
(){
    local chpwdrdf
    zstyle -g chpwdrdf ':chpwd:*' recent-dirs-file
    dirstack=($(awk -F"'" '{print $2}' "$chpwdrdf" 2>/dev/null))
    [[ $PWD = ~ ]] && { cd ${dirstack[1]} 2>/dev/null || true }
    dirstack=("${dirstack[@]:1}")
}
```
</details>

Thanks!

**Comment by romkatv** [comment]
> there is a space at the top left side of my prompt

The config you are copying from is based on Classic style from `p10k configure`. You can see that space being present there.

![prompt](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-styles-high-contrast.png)

See that space on grey background to the left of `~` on the first Classic prompt? You've changed its background to transparent but the space is still there.

Lean style removes these spaces with this option: https://github.com/romkatv/powerlevel10k/blob/644488afcc2e12657c325539015402e914abf694/config/p10k-lean.zsh#L112

> Is there a way to either write to the instant prompt file with this directory or configure instant prompt to read from that file to provide the directory it uses?

The only way is to `cd` before sourcing the instant prompt file.

**Comment by NICHOLAS85** [comment]
> Lean style removes these spaces with this option:
> 
> https://github.com/romkatv/powerlevel10k/blob/644488afcc2e12657c325539015402e914abf694/config/p10k-lean.zsh#L112

Perfect, thanks!

> > Is there a way to either write to the instant prompt file with this directory or configure instant prompt to read from that file to provide the directory it uses?
> 
> The only way is to `cd` before sourcing the instant prompt file.

Understood, I'll rearrange my config to make it work.
