### ISSUE TITLE
[BUG] Window Title (_p9k__cwd)

### ISSUE THREAD

**Issue by Generator** [romkatv/powerlevel10k#773]
powerlevel10k keeps showing `_p9k__cwd`  on window title
![Captura de ecrã de 2020-05-28 22 03 39](https://user-images.githubusercontent.com/44146/83194902-4b7a5800-a131-11ea-9184-0c640a10f834.png)

With [caiogondim/bullet-train.zsh](https://github.com/caiogondim/bullet-train.zsh)  there's no issue
![Captura de ecrã de 2020-05-28 22 19 11](https://user-images.githubusercontent.com/44146/83195054-85e3f500-a131-11ea-901e-1b6e4a6b26da.png)

**Comment by romkatv** [comment]
Powerlevel10k doesn't set terminal title. See https://github.com/romkatv/powerlevel10k/#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect.

My guess is that whatever you are using to set terminal title performs prompt expansion on `%2~` and you also have option `auto_name_dirs` turned on. You can fix this by turning `auto_name_dirs` off.

```zsh
echo 'unsetopt auto_name_dirs' >>~/.zshrc
exec zsh
```

**Comment by romkatv** [comment]
> I believe this is also related to how `dirs` will show `~ _p9k__cwd` which is not an expected behavior.

It's the expected behavior of turning on `auto_name_dirs`. If you don't like it, don't turn it on.
