### ISSUE TITLE
Possible to hide line/skip newline if it is empty/whitespace?

### ISSUE THREAD

**Issue by jderose9** [romkatv/powerlevel10k#776]
I have a two-line setup with all of my "optional" outputs such as git repo, programming language environments, etc. on the first line, and my current directory and path prompt on the 2nd. I am using the lean output. So something like this:

```
master !3 node 11.0
~/mydir > 
```

If I am in a directory where the first line is empty, how can I omit the extra white space/newline?

**Comment by romkatv** [comment]
This is technically possible but difficult and it won't work very well. For example, if any of your optional segments respect [show on command](https://github.com/romkatv/powerlevel10k/blob/master/README.md#show-on-command), your prompt will jump up and down as you are typing.

One of the biggest advantages of two-line prompt is that you get more space for typing commands and all your commands start from the same offset. By putting directory on the second line you partially eliminating the first advantage and completely surrendering the second. I recommend putting directory on the first line. Incidentally this will also solve the problem with the empty first line.

I should also note the biggest disadvantage of two-line prompt: half as many commands fit in the terminal window. This disadvantage is eliminated by enabling [transient prompt](https://github.com/romkatv/powerlevel10k/blob/master/README.md#transient-prompt).

**Comment by jderose9** [comment]
Thanks @romkatv. I certainly understand this not being technically feasible or a feature that you want to include p10k.

The reason I prefer the path next to the prompt is that I have to make a conscious effort to look upward to see what my present working directory is, and with many terminal windows or tabs open this context can easily be mistaken. So generally, I don't personally get the advantages you describe but rather, after having the PWD on the first line in the way you describe for a month or so, I continue to make additional mistakes. So, I was hoping to use my terminal in a similar manner to a relatively default terminal prompt that I have used for years, but with the augmented information about my environment in an out of the way location, when it was available.
