### ISSUE TITLE
Collapse space between dir and prompt_char

### ISSUE THREAD

**Issue by jderose9** [romkatv/powerlevel10k#777]
I would like to collapse the space between `dir` and `prompt_char`. Setting `POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=''` did the trick but obviously not ideal since it gets rid of the whitespace between all of the other segments.

Thanks!

**Comment by romkatv** [comment]
If you are using Lean style, this should do it:

```zsh
POWERLEVEL9K_DIR_LEFT_SUBSEGMENT_SEPARATOR=
```

Here's the anatomy of this parameter. `POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR` defines the separator between left prompt segments that have the same background color. In Lean style all segments have the same background color, so this defines the separator between all left prompt segments. In Lean config this parameter is set to `' '` (space). You can override this value for a specific segment with `POWERLEVEL9K_${SEGMENT}_LEFT_SUBSEGMENT_SEPARATOR` where `${SEGMENT}` is the uppercase name of the segment *before* the separator. Thus, `POWERLEVEL9K_DIR_LEFT_SUBSEGMENT_SEPARATOR` defines the separator used after `dir` in left prompt.

**Comment by jderose9** [comment]
Thanks @romkatv! This did the trick. I really appreciate the detailed breakdown.
