### ISSUE TITLE
字符乱码

### ISSUE THREAD

**Issue by lswjkllc** [romkatv/powerlevel10k#779]
![image](https://user-images.githubusercontent.com/37967883/83322366-9d35f600-a289-11ea-8d87-8c2afd318359.png)

![image](https://user-images.githubusercontent.com/37967883/83322388-d2dadf00-a289-11ea-9094-99b73c1f1e92.png)

安装好了powerlevel10k，还有 nerd font 字体，还是会出现图1的乱码，想知道为什么？

**Comment by romkatv** [comment]
- https://github.com/romkatv/powerlevel10k/blob/master/README.md#question-mark-in-prompt
- https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean
