### ISSUE TITLE
Two line prompt loses first line when buffer cleared

### ISSUE THREAD

**Issue by rsalmei** [romkatv/powerlevel10k#782]
Hello!

Thanks for this project, it works pretty nice.

I'm using a transient prompt with two-lines, just like in the readme.
The problem is, when I hit COMMAND+K to clear the iTerm2 terminal, it redraws only the second, the actual prompt line, missing the first cool line with the directory and widgets. So after clearing I always have to push enter to see the full prompt.
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/6652853/83358525-886d6700-a34a-11ea-84d6-b37f11944b7e.png">

It's a small problem I know, but that annoys me. Is there any way to fix that?

**Comment by romkatv** [comment]
Are you sure it draws only the second line? Can you try scrolling up?

**Comment by rsalmei** [comment]
Yes I'm sure, there's no scrollback.

**Comment by romkatv** [comment]
I looked up what Command-K does. It simply clears everything except the last prompt line. It doesn't communicate with the shell at all. You are supposed to use it only when Ctrl-L doesn't work. In practice Ctrl-L always works, so there is no need to use the Command-K.

It's possible that Command-K will behave better if you install iTerm2 shell integration but I haven't tried to verify this. Either way, even if you do install it, please use Ctrl-L.

**Comment by rsalmei** [comment]
Humm I see, what a shame it doesn't communicate with the shell...

I don't like CTRL+L because the scrollback buffer does not get cleared, so if I scroll up after these tests and a CTRL+L, this is what I get:
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/6652853/83358751-0c741e80-a34c-11ea-90c5-7f47aeb00ccd.png">

I'm gonna test with shell integration.

**Comment by rsalmei** [comment]
Hey @romkatv, you're right, it does work with shell integration, thank you!
And congrats on the prompt response (pun intended!), no wonder there's almost none issues...

**Comment by romkatv** [comment]
Thanks for the confirmation that shell integration helps.

If those triangles on the left are annoying, you can turn them off in settings. Overall, shell integration in iTerm2 is super useful. I encourage you to learn the extra features it provides such as selecting the output of the last command, or adding timestamps to commands on the right hand side.

**Comment by rsalmei** [comment]
Yes, Profile -> Terminal -> Show mark indicators, just turned those off.

Nice, will read about these extra features!
Thank you very much, you were very thoughtful.
Be safe man.

**Comment by sparkbuzz** [comment]
> I looked up what Command-K does. It simply clears everything except the last prompt line. It doesn't communicate with the shell at all. You are supposed to use it only when Ctrl-L doesn't work. In practice Ctrl-L always works, so there is no need to use the Command-K.
> 
> It's possible that Command-K will behave better if you install iTerm2 shell integration but I haven't tried to verify this. Either way, even if you do install it, please use Ctrl-L.

This worked for me too, thanks! I'm using zsh with the _fino_ theme.

**Comment by romkatv** [comment]
> I'm using zsh with the _fino_ theme.

Sorry to hear that. You can change it though.
