### ISSUE TITLE
Ubuntu todo prompt element

### ISSUE THREAD

**Issue by benzino77** [romkatv/powerlevel10k#785]
First of all thanks for a fantastic project!

I'm using ubuntu 18.04 and I have installed todotxt-cli package which provides todo-txt. The problem is that this package does not provide `todo.sh`  script but `todo-txt`. On Ubuntu environment the todo directory is `$HOME/.todo-txt` not `$HOME/.todo`. Is this possible to address Ubuntu case in the p10k `todo` prompt element?

**Comment by romkatv** [comment]
Thanks for the report. Fixed. Please update powerlevel10k and try again.

**Comment by benzino77** [comment]
It was fast! Thanks!
![image](https://user-images.githubusercontent.com/15658235/83504294-a232b980-a4c4-11ea-8216-d21ac646b39c.png)

**Comment by romkatv** [comment]
Thanks for the (amusing) confirmation :+1:
