### ISSUE TITLE
Question: path aliases

### ISSUE THREAD

**Issue by DAmNRelentless** [romkatv/powerlevel10k#788]
Hey there!

I am using PowerLevel10k as theme for my ZShell on the Linux sub-system for Windows.
It's awesome and looks beautiful. One question I have is if you are able to define path aliases. The Linux sub-system uses the prefix `/mnt/` to access the Windows file system.

That looks kinda ugly and I would like to define something myself. So instead `/mnt/c/Users/Relentless`, it would be nice to have a custom alias and only `/Windows/Relentless` is displayed or whatever you'd like.

Is that possible?

**Comment by romkatv** [comment]
Add this to `~/.zshrc`:

```zsh
# My Windows home directory.
hash -d w=/mnt/c/Users/Relentless
```
Prompt will display `~w/foo/bar` when you are in `/mnt/c/Users/Relentles/foo/bar`. In addition, you'll be able to use `~w` with regular commands and completions.

```zsh
cd ~w
mkdir ~w/new_repository
ls ~w/<TAB>
```

You can define as many named directories as you want. They don't have to be limited to a single letter.

**Comment by DAmNRelentless** [comment]
Awesome! Thanks a lot. Love your work.
