### ISSUE TITLE
Prompt mess up after narrow gnome-terminal

### ISSUE THREAD

**Issue by lingsamuel** [romkatv/powerlevel10k#789]
Example:
![image](https://user-images.githubusercontent.com/14567045/83621591-6f222000-a5c1-11ea-9332-da461bfef5ef.png)

Narrow the terminal:
![image](https://user-images.githubusercontent.com/14567045/83621655-85c87700-a5c1-11ea-89cb-ea82a91a64f4.png)

Notice the scroll bar:
![image](https://user-images.githubusercontent.com/14567045/83621676-8f51df00-a5c1-11ea-8c94-45f764f0f630.png)

Those redundant parts appear at every time I narrow the terminal, such as from `80x24` to `60x24`, or `120x24` to `80x24`. I notice that all text in `gnome-terminal` is flashing when narrow it.

`Konsole` doesn't have this problem.

This problem also exists in theme `agnoster`, I don't know why it happens.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#horrific-mess-when-resizing-terminal-window
