### ISSUE TITLE
git tag not shown anymore

### ISSUE THREAD

**Issue by transferkraM** [romkatv/powerlevel10k#791]
```sh
git log -1 HEAD --oneline --decorate
cbb7dc7 (HEAD -> master, tag: v0.0.4, origin/master, origin/maint, maint) Merge branch '...'
```

`my_git_formatter` with `+x`:

```
+my_git_formatter:4> [[ -n '' ]]                                                                                                             
+my_git_formatter:11> ((  1  ))
+my_git_formatter:13> local meta=%f
+my_git_formatter:14> local clean=%76F
+my_git_formatter:15> local modified=%178F
+my_git_formatter:16> local untracked=%39F
+my_git_formatter:17> local conflicted=%196F
+my_git_formatter:27> local res
+my_git_formatter:28> local where
+my_git_formatter:29> [[ -n master ]]
+my_git_formatter:30> res+='%76F ' 
+my_git_formatter:31> where=master 
+my_git_formatter:39> ((  6 > 32  ))
+my_git_formatter:40> res+=%76Fmaster 
+my_git_formatter:44> [[ -z master ]]
+my_git_formatter:47> [[ -n '' ]]
+my_git_formatter:52> ((  VCS_STATUS_COMMITS_BEHIND  ))
+my_git_formatter:54> ((  VCS_STATUS_COMMITS_AHEAD && !VCS_STATUS_COMMITS_BEHIND  ))
+my_git_formatter:55> ((  VCS_STATUS_COMMITS_AHEAD   ))
+my_git_formatter:57> ((  VCS_STATUS_PUSH_COMMITS_BEHIND  ))
+my_git_formatter:58> ((  VCS_STATUS_PUSH_COMMITS_AHEAD && !VCS_STATUS_PUSH_COMMITS_BEHIND  ))
+my_git_formatter:60> ((  VCS_STATUS_PUSH_COMMITS_AHEAD   ))
+my_git_formatter:62> ((  VCS_STATUS_STASHES         ))
+my_git_formatter:64> [[ -n '' ]]
+my_git_formatter:66> ((  VCS_STATUS_NUM_CONFLICTED  ))
+my_git_formatter:68> ((  VCS_STATUS_NUM_STAGED      ))
+my_git_formatter:70> ((  VCS_STATUS_NUM_UNSTAGED    ))
+my_git_formatter:74> ((  VCS_STATUS_NUM_UNTRACKED   ))
+my_git_formatter:80> ((  VCS_STATUS_HAS_UNSTAGED == -1  ))
+my_git_formatter:82> typeset -g my_git_format='%76F %76Fmaster'
+my_git_formatter:83> set +x
```

For testing I ran `p10k configure` to review a diff between my `my_git_formatter` and the one created with p10k configure. No obviously related diff. No tags with a fresh ~/.p10k.zsh as well.

Any hint greatly appreciated!

**Comment by romkatv** [comment]
The default `my_git_formatter` doesn't show tag when you are on a branch. The logic is straightforward: https://github.com/romkatv/powerlevel10k/blob/189ecf8e1643e883b939f9880e71719f5e5f9480/config/p10k-lean.zsh#L363-L370

Change it if you want to always show tag.

**Comment by transferkraM** [comment]
Okay, got it. Dunno what to do exactly, but I'll figure that out. Thanks!

**Comment by romkatv** [comment]
> Dunno what to do exactly...

https://github.com/romkatv/powerlevel10k/issues/391#issuecomment-612702692

**Comment by jds-tag** [comment]
I found this post while googling. Here's what I did to get both the branch and tag to show up, around line 376.
```
    if [[ -n $VCS_STATUS_LOCAL_BRANCH ]]; then
      res+="${clean}${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}"
      where="${(V)VCS_STATUS_LOCAL_BRANCH} ${(V)VCS_STATUS_TAG}"
    fi
```

**Comment by romkatv** [comment]
> > Dunno what to do exactly...
> 
> [#391 (comment)](https://github.com/romkatv/powerlevel10k/issues/391#issuecomment-612702692)

For anyone looking at this, I highly recommend following this ^^ rather than anything else that people post here.

**Comment by romkatv** [comment]
I've updated the templates for `~/.p10k.zsh` so that it's easier to make this change: https://github.com/romkatv/powerlevel10k/commit/a5d0525c6a34b614a885ec6f1c3d8ff8ddfc9e45. If you update powerlevel10k and run `p10k configure`, you'll have the following piece of code in `~/.p10k.zsh`: https://github.com/romkatv/powerlevel10k/blob/a5d0525c6a34b614a885ec6f1c3d8ff8ddfc9e45/config/p10k-lean.zsh#L387-L389
