### ISSUE TITLE
SHOW_ON_COMMAND for custom prompt element?

### ISSUE THREAD

**Issue by transferkraM** [romkatv/powerlevel10k#792]
Currently I've a custom prompt function to show an icon in different colors in the prompt based on a variable I set up with a `chpwd` hook. The hook configures a hashistack (nomad, vault, consul, terraform) and provides one variable `HASHI_ENV`.

```
  function prompt_hashi() {
    typeset POWERLEVEL9K_HASHI_FOREGROUND=41
    if [ -n "${HASHI_ENV}" ]; then
      if [ "${HASHI_ENV}" = "csi" ] || [ "${HASHI_ENV}" = "ham" ]; then
        p10k segment -f 160 -i "" # -t "${HASHI_ENV}"
      else
        p10k segment -f 41 -i "" # -t "${HASHI_ENV}"
      fi
    fi
  }
```

Then I learned about SHOW_ON_COMMAND and wondered if I could use the same mechanics for such a custom prompt element function?

**Comment by romkatv** [comment]
This should work:

```zsh
POWERLEVEL9K_HASHI_SHOW_ON_COMMAND='foo|bar|baz'
```

---

> `typeset POWERLEVEL9K_HASHI_FOREGROUND=41`

This ☝️ doesn't do anything.

> `function prompt_hashi()`

It's a good idea to prefix all your custom prompt segments with `my_`: `prompt_my_hashi`. This way your code won't be broken by future powerlevel10k updates. Powerlevel10k may add `hashi` prompt segment but it will never add `my_hashi` or anything else starting with `my_`.

**Comment by transferkraM** [comment]
Okay, renamed the function to `prompt_my_hashi` and updated `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` to include `my_hashi` rather than `hashi`.
I've added `typeset -g POWERLEVEL9K_HASHI_SHOW_ON_COMMAND=consul|nomad|terraform|vault` before the prompt_my_hashi function.

Right now the function calls `p10k segment`. What should it really do?

**Comment by romkatv** [comment]
> I've added `typeset -g POWERLEVEL9K_HASHI_SHOW_ON_COMMAND=consul|nomad|terraform|vault` before the prompt_my_hashi function.

Since the prompt segment is called `my_hashi`, the parameter should be called `POWERLEVEL9K_MY_HASHI_SHOW_ON_COMMAND`.

> Right now the function calls `p10k segment`. What should it really do?

I thought this prompt segment already does what you want. If not, please clarify how it's different from what you want.

**Comment by romkatv** [comment]
> I've added typeset -g POWERLEVEL9K_HASHI_SHOW_ON_COMMAND=consul|nomad|terraform|vault before the prompt_my_hashi function.

I assume the lack of quotes is a typo. If not, please fix by adding quotes.

Also note that it doesn't matter where you define parameters. If you like to do it before `prompt_my_hashi` -- that's fine. The opposite order will work just as well.

**Comment by transferkraM** [comment]
Renaming the variable to POWERLEVEL9K_MY_HASHI_SHOW_ON_COMMAND does the trick. Thanks a lot, again, for all the help and great support. (I'd add this to the docs, btw.)

**Comment by romkatv** [comment]
> I'd add this to the docs, btw.

There is no reference for powerlevel10k. There is this FAQ entry though: https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-some-prompt-segments-appear-and-disappear-as-im-typing. It sort of suggests that `SHOW_ON_COMMAND` works with all segments.

There are many parameters that work automatically with all segments. Here are a few:

```zsh
# Red foreground.
POWERLEVEL9K_MY_HASHI_FOREGROUND=red
# Icon.
POWERLEVEL9K_MY_HASHI_VISUAL_IDENTIFIER_EXPANSION='H'
# Separator after the segment.
POWERLEVEL9K_MY_HASHI_RIGHT_SUBSEGMENT_SEPARATOR='>'
# Show segment only when there is *.blah in the current directory or up the hierarchy.
POWERLEVEL9K_MY_HASHI_SHOW_ON_UPGLOB='*.blah'
# Don't show segment when the current directory is under /foo.
POWERLEVEL9K_MY_HASHI_DISABLED_DIR_PATTERN='/foo(|/*)'
```
