### ISSUE TITLE
Put down prompt

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#793]
The question may seem silly, but how (if possible) to pin the input prompt at the bottom of the window? Like [here](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/transient-prompt.gif).

**Comment by romkatv** [comment]
On that gif prompt is at bottom but it's not pinned. You can move prompt to the bottom simply by pressing <kbd>Enter</kbd> a few times or by printing a bunch of empty lines. To the best of my knowledge it's not possible to automatically move prompt to the bottom every time time it gets moved up by widgets and commands.

**Comment by Mystic8b** [comment]
Oh, sorry, found the answer [here](#563 )
Before that googled for two hours, rekt
