### ISSUE TITLE
Swap lines

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#794]
Greetings! Please tell me, is it possible to swap lines so that the prompt is on top and the path is on the bottom?
![image](https://user-images.githubusercontent.com/35394377/83691882-a0b7dd00-a5fb-11ea-8499-4905ebf5c5a0.png)

**Comment by romkatv** [comment]
No, this isn't possible. Zsh doesn't allow prompt to extend below cursor.
