### ISSUE TITLE
Icons are all swaped or missing in ubuntu 20.04

### ISSUE THREAD

**Issue by jgabriel98** [romkatv/powerlevel10k#795]
i'm on ubuntu 20.04, fresh update from 19.04.

after installing zsh, then oh-my-zsh, the recomended powerlevel10k font then powerlevel10k

i noticed that the `p10k configure` would fail in a lot of icon availability checks, por example:
![Captura de tela de 2020-06-03 18-43-18](https://user-images.githubusercontent.com/37881981/83692431-58cc9200-a5ca-11ea-88bb-0db2287af3ad.png)
![Captura de tela de 2020-06-03 18-43-28](https://user-images.githubusercontent.com/37881981/83692434-5a965580-a5ca-11ea-9224-2f215c3816ee.png)
![Captura de tela de 2020-06-03 18-43-59](https://user-images.githubusercontent.com/37881981/83692437-5c601900-a5ca-11ea-8ceb-a66592f34e88.png)
![Captura de tela de 2020-06-03 18-45-34](https://user-images.githubusercontent.com/37881981/83692456-6bdf6200-a5ca-11ea-8adc-fb9c78ac3cd9.png)

for the distro icon, it was showing just a circle with a small hole ( like a CD disk). 
But after making a small program to print all unicode character/values, i've found the ubuntu logo, so then i had to manually set the distro icon in the config file.

### Printing distros icons
I've followed this [powerlevel9k issue](https://github.com/Powerlevel9k/powerlevel9k/issues/751#issuecomment-365825535) that tells all the distro icons code, so i printed some to get more debug info, my results where:

| code   | expected icon| displayed icon 	        |
|--------  |------------------- |--------------------------	|
| \uF300| Arch Linux     |![Captura de tela de 2020-06-03 18-55-25](https://user-images.githubusercontent.com/37881981/83693214-05f3da00-a5cc-11ea-8edb-9be4fb6794e9.png)|
|\uF301   	| CentOS          |![Captura de tela de 2020-06-03 19-06-54](https://user-images.githubusercontent.com/37881981/83694367-448a9400-a5ce-11ea-8145-980942de3190.png)|
|\uF30F  	| CoreOS |![Captura de tela de 2020-06-03 19-03-02](https://user-images.githubusercontent.com/37881981/83694452-726fd880-a5ce-11ea-8d6f-41490491033e.png)|
|\uF302   | Debian |![Captura de tela de 2020-06-03 19-03-48](https://user-images.githubusercontent.com/37881981/83693740-093b9580-a5cd-11ea-90d5-ea9432fbe4dc.png)|
|\uF30C| Ubuntu | ![Captura de tela de 2020-06-03 19-05-11](https://user-images.githubusercontent.com/37881981/83693814-2d977200-a5cd-11ea-8a9f-937867105028.png)|
|\uF30D| Ubuntu inverse| ![Captura de tela de 2020-06-03 19-05-44](https://user-images.githubusercontent.com/37881981/83693844-3f791500-a5cd-11ea-850c-18eb6c05c7b1.png)|

Update: according to [this thread](https://github.com/Powerlevel9k/powerlevel9k/issues/751#issuecomment-366397738), the fonts where updated, but it doesn't seem to be the case for the default nerd hack fonts(?).

does anyone know what is happening?

**Comment by jgabriel98** [comment]
after running `sudo apt install fonts-font-awesome` and switching from  MesloLGL for powerline to Hack Nerd Font, everything now works.

maybe i've messed up someting before

**Comment by njmsaikat** [comment]
In my case, I was using a custom font for terminal before the setup. But really thanks for the idea. From your issue I figured out the probable problem.
