### ISSUE TITLE
Show current directory

### ISSUE THREAD

**Issue by TornaxO7** [romkatv/powerlevel10k#796]
How can I show only my current directory instead of the absolute path?

**Comment by AitBits** [comment]
Try setting `typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
`

**Comment by romkatv** [comment]
Whta @AitBits said. (Open `~/.p10k.zsh`, search for `POWERLEVEL9K_SHORTEN_STRATEGY` and change the value of this parameter to `truncate_to_last`.)

Alternatively, you can try changing the value of `POWERLEVEL9K_DIR_MAX_LENGTH` to `1`.

If you frequently work outside of your home directory, you might want to utilize *named directories*. For example, WSL users often add this to their `~/.zshrc`:

```zsh
# My Windows home directory.
hash -d w=/mnt/c/Users/MyName
```

**Comment by TornaxO7** [comment]
Thanks guys! It works :)

**Comment by strugglebak** [comment]
Thx !

**Comment by terminal-root** [comment]
> Whta @AitBits said. (Open `~/.p10k.zsh`, search for `POWERLEVEL9K_SHORTEN_STRATEGY` and change the value of this parameter to `truncate_to_last`.)
> 
> Alternatively, you can try changing the value of `POWERLEVEL9K_DIR_MAX_LENGTH` to `1`.
> 
> If you frequently work outside of your home directory, you might want to utilize _named directories_. For example, WSL users often add this to their `~/.zshrc`:
> 
> ```shell
> # My Windows home directory.
> hash -d w=/mnt/c/Users/MyName
> ```

@AitBits, is there a way to put special/unicode characters in the names of the directories?

**Comment by romkatv** [comment]
@terminal-root What are you trying to achieve?

**Comment by terminal-root** [comment]
@romkatv , I was trying to put special characters in the name of the _named directory_
e.g.,
```bash
hash -d "~ name ~"="/path/to/dir";
```
but I get an error saying I can't have the spaces or tilde characters.

**Comment by romkatv** [comment]
Named directories are a feature of zsh. They aren't a part of Powerlevel10k. The names of named directories aren't allowed to contain spaces or tilde. More specifically, zsh enforces the same rules for the names of named directories as for usernames.

**Comment by terminal-root** [comment]
@romkatv Thank you for the information.

**Comment by grace-joh** [comment]
I am trying to open `~/.p10k.zsh` to change the value of `POWERLEVEL9K_SHORTEN_STRATEGY`, but I am receiving an error - `zsh: permission denied: /Users/username/.p10k.zsh`

**Comment by romkatv** [comment]
@grace-joh You must have created this file with a different user. To fix the issue, run this:

```zsh
sudo chown -R $USER ~
```

In the future be more careful with using `sudo`.

**Comment by grace-joh** [comment]
@romkatv thank you!

**Comment by m-mourouh** [comment]
Thanks guys, this was helpufull

**Comment by nicc-b** [comment]
> @grace-joh You must have created this file with a different user. To fix the issue, run this:
> 
> ```shell
> sudo chown -R $USER ~
> ```
> 
> In the future be more careful with using `sudo`.

Hi, even with this command, I'm still not able to. I put the right password and still says 'Operation not permitted' :/
