### ISSUE TITLE
zsh: command not found: p10k

### ISSUE THREAD

**Issue by Gahamelas** [romkatv/powerlevel10k#797]
Great package!
I followed instructions for `oh-my-zsh`.
I can see that it is installed in
`~/.oh-my-zsh/custom/themes/powerlevel10k`

However:
`zsh: command not found: p10k`

Any thoughts?

**Comment by romkatv** [comment]
There can be three reasons for this. Either you haven’t changed ZSH_THEME as per the instructions (in which case you should change it), you haven’t restarted zsh (please do restart it) or you aren’t using Oh My Zsh (then you should follow manual installation instructions).

**Comment by Gahamelas** [comment]
Thanks, it was the latter. Now fixed!
