### ISSUE TITLE
Path shows "wd" points instead of paths

### ISSUE THREAD

**Issue by pro-sumer** [romkatv/powerlevel10k#798]
After a recent update my prompt shows the `wd` "point" instead of the "path" on macOS Catalina (10.15.4).

Example: 

```
wd add dl ~/Downloads
wd dl
```

* Expected path (as a few days ago) in prompt: `~/Downloads`
* Actual path (now) in prompt: `~dl`

What changed? How can I get the old behaviour back?

**Comment by romkatv** [comment]
I don’t know what wd does but your prompt indicates that you have created a named directory called `dl` that points to `~/Downloads`. If you don’t want to see `~dl` in prompt, don’t define a named directory with this name.

Nothing has changed in powerlevel10k in this regard. It has always respected named directories.

**Comment by romkatv** [comment]
Note that you can use `cd ~dl`, `ls ~dl/foo` and the like.

**Comment by pro-sumer** [comment]
It sure looks like that! (I could not do that before...)

The behaviour is still as I expected on my old Mac (also running macOS Catalina 10.15.4, but with older versions of both Oh My Zsh and powerlevel10k)

Maybe the `wd` implementation in Oh My Zsh changed recently?

**Comment by romkatv** [comment]
> Maybe the `wd` implementation in Oh My Zsh changed recently?

Maybe. I’ve no idea what wd is.

**Comment by pro-sumer** [comment]
[wd](https://github.com/mfaerevaag/wd) _(warp directory) lets you jump to custom directories in zsh_

It comes bundled with Oh My Zsh, so I'll ask over [there](https://github.com/ohmyzsh/ohmyzsh/issues/8996).
