### ISSUE TITLE
How to implement "Recommended: Change ~/.zshrc so that it does not perform console I/O"

### ISSUE THREAD

**Issue by Gahamelas** [romkatv/powerlevel10k#799]
I am getting the [WARNING] when I run Terminal.

I get the message: 

```
  - Recommended: Change ~/.zshrc so that it does not perform console I/O
    after the instant prompt preamble. See the link below for details.
```

However, I don't find any guidelines about how to "Change ~/.zshrc so that it does not perform console I/O".

Thanks, 
GM

**Comment by romkatv** [comment]
You can always disable instant prompt.
