### ISSUE TITLE
(eval):1 command not found: custom_rprompt

### ISSUE THREAD

**Issue by sebaLinares** [romkatv/powerlevel10k#80]
Every time I press enter, it appears that message. All commands work fine, but it's annoying. 

![rprompt](https://user-images.githubusercontent.com/29524678/59072215-c34fd280-888f-11e9-8721-272045dd5e66.jpg)

**Comment by romkatv** [comment]
This could happen if you've updated `.purepower` to the latest version but haven't updated Powerlevel10k. Could you update and retry?

I also see there is a missing space between ❯ and the cursor. This is not normal and likely will cause other issues. For example, if you press `Ctrl+R` or type `ls<tab>` you may get some extra brokenness. If these issues persist after you update Powerlevel10k, please attach your config (I'm assuming you have a modified `.purepower` config) and I'll try to figure out what went wrong.

**Comment by sebaLinares** [comment]
I deleted powerlevel9k/10k and purepower directories and configuration from my .zshrc file. Then did a clean installation and voilá. Thanks.

**Comment by romkatv** [comment]
Thanks for verifying!
