### ISSUE TITLE
Problems with a light theme

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#800]
If you enable a bright scheme in the terminal, then there are some problems.
These two parts of the invitation should be the same color, but in reality for some reason they will use different colors.
Tell me where these parameters are in the config, please.
![image](https://user-images.githubusercontent.com/35394377/83747435-49e8ec80-a669-11ea-99f0-c6241b76e944.png)

**Comment by romkatv** [comment]
This is either incorrect terminal configuration or a terminal bug. You terminal displays background 7 as white (expected) and foreground 7 as black (unexpected). Either try to figure out how to configure terminal properly or report a bug against the terminal.

**Comment by Mystic8b** [comment]
Foreground is black, it should be so. If I replace it with white, the input color will also change.
![image](https://user-images.githubusercontent.com/35394377/83752408-2c1f8580-a671-11ea-9402-76ef8fb37a7d.png)

**Comment by romkatv** [comment]
> Foreground is black, it should be so.

Foreground and background with any color code must look the same or powerline prompt style won't work.

The fact that Microsoft Terminal confuses foreground color 7 with default foreground is a problem of Microsoft Terminal.

**Comment by Mystic8b** [comment]
Ok, sorry. Thanks, have a nice day.
