### ISSUE TITLE
Meaning of status bar symbols

### ISSUE THREAD

**Issue by Gahamelas** [romkatv/powerlevel10k#801]
Is there a legend for the meaning of status bar symbols?

For instance, in my status bar I have:

`>~/Doc> master !4 ?23`

What is the meaning f `!4` and `?23`?

Also on the right side:

`127 ✘  base   13:32:28  `

What is the meaning of `127x`?
Thanks!

**Comment by romkatv** [comment]
127 is error code. For git see https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean

**Comment by Gahamelas** [comment]
I actually don't see git symbols in my Terminal, but !4 ?23. With exclamation and interrogation. I have installed the fonts. This it not supposed to be ! and ? I suppose?

**Comment by romkatv** [comment]
See the link I posted above to understand the meaning of Git status in your prompt.

**Comment by Gahamelas** [comment]
Thanks. However, I can't find in the config file the file to change the color for the master (it's golden by default).

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status

**Comment by Gahamelas** [comment]
I still can't find how to change the "master" color part of the prompt...

**Comment by romkatv** [comment]
Custom configuration requires some proficiency in Zsh.

**Comment by Gahamelas** [comment]
Yes, but I can see all git statuses formatting colors, but not "master" prompt.

**Comment by romkatv** [comment]
> Custom configuration requires some proficiency in Zsh.

:point_up:

**Comment by Gahamelas** [comment]
It would be nice to have some config file examples for the non professional.
