### ISSUE TITLE
How to show 🔋 below

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#803]
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='%7F─┤'

![prompt-highlight](https://user-images.githubusercontent.com/61009000/83936342-69148500-a7f5-11ea-8205-2ffaf3b9430c.png)
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%7F─╯'

**Comment by romkatv** [comment]
You can display battery charge level by uncommenting "battery" in `~/.p10k.zsh`. It only works on Linux and macOS. It does not work in Termux.

**Comment by Freed-Wu** [comment]
hey, can it support termux? i know `termux-battery-status` can get a json about battery status. like this:
```{.json}
{
  "health": "GOOD",
  "percentage": 52,
  "plugged": "UNPLUGGED",
  "status": "NOT_CHARGING",
  "temperature": 31.0,
  "current": 232
}
```

**Comment by romkatv** [comment]
I don’t intend to add termux battery support. If you send a high quality implementation via a PR, I’ll merge it.

**Comment by Freed-Wu** [comment]
with pleasure.
