### ISSUE TITLE
How to change colors?

### ISSUE THREAD

**Issue by Mystic8b** [romkatv/powerlevel10k#805]
Please tell me in what parameters can I change the colors of the text?
And if someone at the same time tells me how to change or remove the selection (background) of modified dirs (and files) in the branch - I will be just happy.
![image](https://user-images.githubusercontent.com/35394377/83955712-c7298280-a85e-11ea-8e87-97b5ce11e97c.png)
I tried to find in the config, but I almost went crazy, there are so many things.

**Comment by skarchmit** [comment]
According to the readme, have you tried

```The parameters you are looking for are called POWERLEVEL9K_DIR_BACKGROUND, POWERLEVEL9K_DIR_FOREGROUND, POWERLEVEL9K_DIR_SHORTENED_FOREGROUND, POWERLEVEL9K_DIR_ANCHOR_FOREGROUND and POWERLEVEL9K_DIR_ANCHOR_BOLD. You can find them in in ~/.p10k.zsh
```

**Comment by romkatv** [comment]
This should help:

- Current directory color: https://github.com/romkatv/powerlevel10k/blob/master/README.md#directory-is-difficult-to-see-in-prompt-when-using-rainbow-style
- Prompt colors in general: https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-prompt-colors
- Colors in the output of `ls`: https://github.com/romkatv/powerlevel10k/blob/master/README.md#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect

The last link will tell you that Powerlevel10k doesn't affect the colors of `ls` in any way. You can google how to change them. I personally use this:

```zsh
export LS_COLORS='rs=0:no=00:mi=00:mh=00:ln=01;36:or=01;31:di=01;34:ow=04;01;34:st=34:tw=04;34:pi=01;33:so=01;33:do=01;33:bd=01;33:cd=01;33:su=01;35:sg=01;35:ca=01;35:ex=01;32:'
```

This works very well on WSL and doesn't overwhelm with colors, nor does it slow down zsh startup.

**Comment by Mystic8b** [comment]
My regards!!
Thank you for your time. Have a nice day!

**Comment by ricardolopes86** [comment]
Thanks a lot @romkatv !!!!

**Comment by chetan-1924** [comment]
Thanks a lot @romkatv !!!!

**Comment by yangliuly1** [comment]
Great !!!
