### ISSUE TITLE
dir prompt component duplicated and out of position

### ISSUE THREAD

**Issue by egonbraun** [romkatv/powerlevel10k#806]
Here is the issue with the prompt. Note that the current directory is listed twice.

![2020-06-07-210947_1600x900_scrot](https://user-images.githubusercontent.com/5523795/83977762-55574480-a903-11ea-9677-32831e70d506.png)

Here are the software that I believe relevant for this issue, let me know if I missed any.

- ArchLabs
- zsh 5.8
- alacritty 0.4.3-1

I followed the steps provided in the `README` file and also installed the `MesloLGS NF` font family.

I ran the `p10k configure` command and here is the file.

[p10k.txt](https://github.com/romkatv/powerlevel10k/files/4742730/p10k.txt)

Let me know if I need to provide any further information.

**Comment by romkatv** [comment]
Looks like incorrect `TERM`. What is it set to?

**Comment by egonbraun** [comment]
It is set to `xterm-256color`

**Comment by romkatv** [comment]
Thanks for the the confirmation.

**Comment by romkatv** [comment]
Sorry, posted on the wrong issue. Can you reproduce the problem with empty zshrc that only sources powerlevel10k?

**Comment by egonbraun** [comment]
Ok, that's a good catch. I still could not pin down the root cause but I am guessing it might be some other `zinit` plugin I am using.

The issue disappears if my `.zshrc` is  only loading `zinit` and `powerlevel10k`.

**Comment by egonbraun** [comment]
Found it, my mistake indeed. I left `sindresorhus/pure` in the list of zinit plugins and obviously that was generating issues.

Thanks for the help!
