### ISSUE TITLE
Incorrect VCS_GIT icons

### ISSUE THREAD

**Issue by HackAttack** [romkatv/powerlevel10k#808]
Related: #560, #399 

Here are a couple screenshots demonstrating incorrect Git remote icons when switching from 9k to 10k. In the first one I have a tag checked out, in the second, a branch. Initial condition for both is running under 9k (Mac, iTerm, oh-my-zsh).

<img width="1158" alt="Screen Shot 2020-06-09 at 9 53 33 AM" src="https://user-images.githubusercontent.com/1222646/84177877-6190ee00-aa38-11ea-99b6-0f2401fc741f.png">

<img width="1293" alt="Screen Shot 2020-06-09 at 9 55 12 AM" src="https://user-images.githubusercontent.com/1222646/84177907-6fdf0a00-aa38-11ea-9c68-c487a32d0d35.png">

In scenario 1, 10k replaces the GitLab icon and the branch icon.
In scenario 2, 10k replaces the Bitbucket icon with GitHub (??) and _doesn’t_ replace the branch icon.
(In both scenarios, 10k adds the Python version when it wasn’t there before, but this is a separate inconsistency and not the subject of this issue.)

`get_icon_names` looks correct.

Running in the second directory:
```
$ typeset -m 'POWERLEVEL9K_*|ZSH_VERSION|GITSTATUS_*|VCS_STATUS_*'
VCS_STATUS_PUSH_COMMITS_BEHIND=0
VCS_STATUS_NUM_ASSUME_UNCHANGED=0
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon dir vcs virtualenv anaconda )
GITSTATUS_DAEMON_PID_POWERLEVEL9K=23679
VCS_STATUS_COMMITS_AHEAD=0
VCS_STATUS_COMMITS_BEHIND=0
ZSH_VERSION=5.3
VCS_STATUS_PUSH_REMOTE_NAME=''
VCS_STATUS_TAG=''
VCS_STATUS_REMOTE_NAME=origin
VCS_STATUS_NUM_STAGED=0
VCS_STATUS_HAS_UNTRACKED=0
VCS_STATUS_NUM_UNTRACKED=0
VCS_STATUS_RESULT=ok-async
VCS_STATUS_STASHES=2
VCS_STATUS_INDEX_SIZE=31
VCS_STATUS_HAS_UNSTAGED=0
VCS_STATUS_PUSH_COMMITS_AHEAD=0
VCS_STATUS_NUM_UNSTAGED_DELETED=0
VCS_STATUS_WORKDIR=/Users/mhackner/src/automerge-service
VCS_STATUS_NUM_CONFLICTED=0
VCS_STATUS_NUM_UNSTAGED=0
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(  )
VCS_STATUS_ACTION=''
VCS_STATUS_LOCAL_BRANCH=clone-on-demand
VCS_STATUS_REMOTE_BRANCH=clone-on-demand
VCS_STATUS_NUM_STAGED_DELETED=0
VCS_STATUS_NUM_SKIP_WORKTREE=0
POWERLEVEL9K_MODE=nerdfont-complete
GITSTATUS_XTRACE_POWERLEVEL9K=/dev/null
VCS_STATUS_COMMIT=36275e34d2dc917d0a8c17851701eac8a8252f1d
VCS_STATUS_REMOTE_URL=ssh://git@stash.<redacted>
VCS_STATUS_NUM_STAGED_NEW=0
VCS_STATUS_HAS_CONFLICTED=0
GITSTATUS_DAEMON_LOG_POWERLEVEL9K=/dev/null
VCS_STATUS_PUSH_REMOTE_URL=''
VCS_STATUS_HAS_STAGED=0
```

Relevant portion of ~/.zshrc
```
ZSH_THEME="powerlevel10k/powerlevel10k"  # or 9k as I swap back and forth
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs virtualenv anaconda)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
VIRTUAL_ENV_DISABLE_PROMPT=1
<snip>
source $ZSH/oh-my-zsh.sh
```

**Comment by romkatv** [comment]
> In scenario 1, 10k replaces the GitLab icon and the branch icon.

p10k is correct on both counts. You are not on a branch, so the branch icon is wrong. Both p9k and p10k correctly display commit hash but only p10k displays the commit hash icon.

And since you are not on a branch, there is no tracking remote, so GitLab icon is wrong, too.

> In scenario 2, 10k replaces the Bitbucket icon with GitHub

Thanks for the report! Fixed.

**Comment by romkatv** [comment]
By the way, you might want to run `p10k configure`.

**Comment by romkatv** [comment]
> Related: #560, #399

Thanks for these links. Here's a comment from one of them that's applicable here: https://github.com/romkatv/powerlevel10k/issues/399#issuecomment-569328029
