### ISSUE TITLE
How to enable showing conda env name?

### ISSUE THREAD

**Issue by hologerry** [romkatv/powerlevel10k#809]
Hi, I am new to powerline10k theme, and I work a lot with python and conda.
Could someone please help me how to set the config to show the active conda environment name?
Thanks a lot!

**Comment by romkatv** [comment]
Type `p10k configure`. Choose any style except Pure. Done.

**Comment by hologerry** [comment]
I have chose the `Lean` style, but it didn't show up.
<img width="650" alt="Screen Shot 2020-06-10 at 03 14 43" src="https://user-images.githubusercontent.com/11660168/84189867-8b91f100-aac8-11ea-9a7a-198373fd66f4.png">

**Comment by romkatv** [comment]
Please run the following command and post its output here:

```zsh
typeset -pm 'ZSH_VERSION|*CONDA*'
```

**Comment by hologerry** [comment]
```
typeset _POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=')'
typeset ZSH_VERSION=5.7.1
typeset _POWERLEVEL9K_ANACONDA_FOREGROUND=37
typeset POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}'
export CONDA_PYTHON_EXE=/Users/Gerry/miniconda/bin/python
export _CE_CONDA=''
typeset _POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}'
typeset POWERLEVEL9K_ANACONDA_FOREGROUND=37
export CONDA_SHLVL=0
export CONDA_EXE=/Users/Gerry/miniconda/bin/conda
typeset -i _POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=1
typeset _POWERLEVEL9K_ANACONDA_LEFT_DELIMITER='('
```

**Comment by romkatv** [comment]
Please do the same thing after typing `act torch`. I need to see the output when there is python logo on the right hand side of your screen.

**Comment by hologerry** [comment]
```
❯ typeset -pm 'ZSH_VERSION|*CONDA*'
export CONDA_PYTHON_EXE=/Users/Gerry/miniconda/bin/python
export CONDA_EXE=/Users/Gerry/miniconda/bin/conda
export CONDA_DEFAULT_ENV=torch
export CONDA_PREFIX=/Users/Gerry/miniconda/envs/torch
typeset ZSH_VERSION=5.7.1
typeset POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}'
typeset _POWERLEVEL9K_ANACONDA_LEFT_DELIMITER='('
typeset _POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=')'
typeset _POWERLEVEL9K_ANACONDA_FOREGROUND=37
typeset _POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}'
typeset POWERLEVEL9K_ANACONDA_FOREGROUND=37
typeset P9K_ANACONDA_PYTHON_VERSION=3.7.7
export CONDA_PROMPT_MODIFIER=''
typeset CONDA_INTERNAL_OLDPATH=/usr/local/sbin:/Users/Gerry/miniconda/condabin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin
export _CE_CONDA=''
export CONDA_SHLVL=1
typeset -i _POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=1
```

**Comment by romkatv** [comment]
Please [update powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k) and try again.

**Comment by romkatv** [comment]
> Please [update powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-update-powerlevel10k) and try again.

Sorry, meant to say update, restart zsh, run `p10k configure` and then try `act torch`.

**Comment by hologerry** [comment]
<img width="650" alt="Screen Shot 2020-06-10 at 03 36 16" src="https://user-images.githubusercontent.com/11660168/84191758-90a46f80-aacb-11ea-9d39-8c607bf47ebb.png">
Seems this issue is still there.

**Comment by romkatv** [comment]
From the screenshot you've posted I see that either you haven't update powerlevel10k, haven't restarted zsh, or haven't run `p10k configure`. Please do all of these in this order.

**Comment by hologerry** [comment]
It worked now! Thanks for your patience.
(In last screenshot, I forgot to reconfigure..., sorry)
<img width="650" alt="Screen Shot 2020-06-10 at 03 42 28" src="https://user-images.githubusercontent.com/11660168/84192345-6bfcc780-aacc-11ea-91aa-bc6bb05ca560.png">

**Comment by romkatv** [comment]
Thanks for the confirmation. What was happening is that you’ve explicitly disabled conda prompt through conda’s own configuration. Powerlevel10k by default shows conda prompt because it assumes you’ve configured it for a reason. I’ve not changed the code so that powerlevel10k doesn’t trust your configuration if you set conda prompt to empty.

**Comment by hologerry** [comment]
I see. I did this (explicitly disabled conda prompt through conda’s own configuration) because I use [`spaceship`](https://github.com/denysdovhan/spaceship-prompt) theme, it provides conda env name itself.

**Comment by romkatv** [comment]
> [`spaceship`](https://github.com/denysdovhan/spaceship-prompt) theme provides conda env name itself.

I'd phrase it differently. Spaceship doesn't respect your configuration of conda prompt. Powerlevel10k does. Or rather did before I've submitted the latest change. Now it respects your configuration unless you set prompt to empty.

You might find this part of your config useful: https://github.com/romkatv/powerlevel10k/blob/e3f582f246840279abf6a75b78cb9b2316e96a71/config/p10k-lean.zsh#L837-L861

**Comment by hologerry** [comment]
Powerlevel10k indeed did better.
I am planning switch all my machines' zsh theme to Powerline10k.

**Comment by pranavpsv** [comment]
@romkatv Is there any way to get Conda environment names with Pure style?

**Comment by romkatv** [comment]
@pranavpsv Search for "conda" in https://github.com/romkatv/powerlevel10k/blob/master/config/p10k-lean.zsh and copy over bits and pieces to your own `~/.p10k.zsh`.

Keep in mind that Pure style is generally worse than Lean. It's an exact replication of Pure Zsh Theme, so it deliberately disables features that no one would disable even in Pure Zsh Theme if they existed there.

**Comment by pranavpsv** [comment]
@romkatv Sure, understood, thanks for the information regarding Pure vs Lean style!

**Comment by CurssedCoffin** [comment]
<img width="804" alt="image" src="https://user-images.githubusercontent.com/49067137/176632594-85807aa8-90b9-4881-b2c3-0e862aef1c17.png">
How can I change the string "py" to empty or custom string?

**Comment by romkatv** [comment]
@CurssedCoffin See https://github.com/romkatv/powerlevel10k/issues/1914. In the future please open a separate issue instead of commenting on unrelated closed issues.

**Comment by CurssedCoffin** [comment]
> @CurssedCoffin See #1914. In the future please open a separate issue instead of commenting on unrelated closed issues.

ok thanks a lot

**Comment by xiao333ma** [comment]
> Type `p10k configure`. Choose any style except Pure. Done.

follow this instruction, it's work. but when i restart iTerm2, it's gone. what should i do? plz help me
here is my

```
 typeset -pm 'ZSH_VERSION|*CONDA*'

export CONDA_PYTHON_EXE=/usr/local/anaconda3/bin/python
export CONDA_EXE=/usr/local/anaconda3/bin/conda
export CONDA_DEFAULT_ENV=base
export CONDA_PREFIX=/usr/local/anaconda3
typeset ZSH_VERSION=5.9
typeset POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-${CONDA_PREFIX:t}}'
typeset _POWERLEVEL9K_ANACONDA_LEFT_DELIMITER='('
typeset _POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=')'
typeset _POWERLEVEL9K_ANACONDA_FOREGROUND=0
typeset _POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-${CONDA_PREFIX:t}}'
typeset POWERLEVEL9K_ANACONDA_FOREGROUND=0
typeset POWERLEVEL9K_ANACONDA_BACKGROUND=4
export CONDA_PROMPT_MODIFIER='(base) '
export _CE_CONDA=''
export CONDA_SHLVL=1
typeset -i _POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=1
typeset _POWERLEVEL9K_ANACONDA_BACKGROUND=4
```

**Comment by jek-bao-choo** [comment]
Thank you @romkatv This thread solves my problem. Thanks so much.
