### ISSUE TITLE
Problem starting

### ISSUE THREAD

**Issue by x93008** [romkatv/powerlevel10k#813]
When I execute the 'zsh' command ：
stty: 标准输入: 对设备不适当的 ioctl 操作

**Comment by romkatv** [comment]
I guess your zshrc calls `stty` and you have enabled Instant Prompt in Powerlevel10k. When you call `stty`, redirect stdin and stdout to `$TTY`. If you can’t figure out how to do is, disable instant prompt. See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-enable-instant-prompt
