### ISSUE TITLE
VCS for git doesn't appear in worktree checkouts

### ISSUE THREAD

**Issue by cujomalainey** [romkatv/powerlevel10k#816]
The git status does not show up if you are in a work tree checkout.

See documentation here https://git-scm.com/docs/git-worktree

My guess is the system is confused by the fact that .git is a file not a folder and just ignoring it.

**Comment by romkatv** [comment]
Could you list the exact commands necessary to reproduce this?

**Comment by cujomalainey** [comment]
I am only able to reproduce this so far with a chromiumos checkout using worktrees.

https://chromium.googlesource.com/chromiumos/docs/+/master/developer_guide.md#Get-the-source-code

if you add --worktree to the `repo init` command then none of the repos will have their git status after a sync

**Comment by romkatv** [comment]
Here's what I've tried:

```zsh
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git ~/depot_tools
path=(~/depot_tools $path)
mkdir ~/chromiumos
cd ~/chromiumos
repo init -u https://chromium.googlesource.com/chromiumos/manifest.git --repo-url https://chromium.googlesource.com/external/repo.git --worktree
repo sync -j4
cd ~/chromiumos/src/chromium/src/tools/md_browser
```

This gave me `@be8cf5a1` in prompt -- the same as `git rev-parse HEAD`.

Which commands do I need to run to reproduce this problem?

**Comment by cujomalainey** [comment]
Hmm, that should have reproduced it. Is there any sort of debug I can dump to help identify the issue?

**Comment by romkatv** [comment]
I've reproduced it. I think on my previous attempt I've either forgot to pass `--worktree` or it didn't work somehow.

Powerlevel10k uses gitstatus, and gitstatus for historical reasons relies on libgit2 for non-performance-critical operations, and that includes opening repositories. libgit2 cannot open repositories with `extensions.worktreeconfig` extension.

Powerlevel10k will start supporting your use case when gitstatus start supporting it. The latter will happen either when libgit2 starts supporting `extensions.worktreeconfig` or when more users ask for this feature (in this case I'll implement it myself).

**Comment by cujomalainey** [comment]
Thanks for the detailed explanation.

**Comment by ericu65** [comment]
+1 for this

Compiling and using the latest gitstatusd still shows:
```
[2021-01-13 12:23:42 0000000109791e00 INFO src/gitstatus.cc:192] Processing request: "1610533422.0786039829 _p9k_vcs_resume 0" for "/Users/eric/Code/cc_source" [no-diff]
[2021-01-13 12:23:42 0000000109791e00 ERROR src/repo_cache.cc:66] git_repository_open_ext: "/Users/eric/Code/cc_source/.git/": unsupported extension name extensions.worktreeconfig
[2021-01-13 12:23:42 0000000109791e00 INFO src/response.cc:69] Replying without git status
[2021-01-13 12:23:42 0000000109791e00 INFO src/timer.cc:64] Timing for: request: 0.624ms cpu
[2021-01-13 12:23:42 0000000109791e00 ERROR src/gitstatus.cc:197] Error processing request: "1610533422.0786039829 _p9k_vcs_resume 0" for "/Users/eric/Code/cc_source" [no-diff]
```

Strange thing is that I am not using worktrees but I am using sparse-checkout. I will open a case on gitstatusd for this.

**Comment by romkatv** [comment]
> Strange thing is that I am not using worktrees but I am using sparse-checkout. I will open a case on gitstatusd for this.

No need. https://github.com/romkatv/powerlevel10k/issues/816#issuecomment-643475021 still applies except that I won't be adding support for `extensions.worktreeconfig` in libgit2 myself.

**Comment by seanabraham** [comment]
Thanks for the detail on this. Is this the appropriate issue on the libgit2 side to track: https://github.com/libgit2/libgit2/issues/6044

**Comment by romkatv** [comment]
@seanabraham I don’t know.

**Comment by urwrstkn8mare** [comment]
Would it be very hard to add a fallback? i.e. If the `extensions.worktreeconfig` extension is found, use something else that does support it?

**Comment by romkatv** [comment]
Very hard? Probably not. For someone with the level of zsh experience similar to my own it would probably take no more than 40 hours.

**Comment by romkatv** [comment]
> Is that something that you would accept in your project?

If someone submits a clean PR (no bugs, good performance, matches the style and architecture of the existing code, etc.), I'll merge it.

**Comment by urwrstkn8mare** [comment]
Yeah same here

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/816#issuecomment-1519590221 above. No need to post "me too" comments.

**Comment by joepvl** [comment]
FWIW: I had this problem up to Git 2.39, but I recently started using [microsoft/git](https://github.com/microsoft/git) (aka Scalar) with a large monorepo I'm working on, and now both the branch name and the status indicator shorthand (e.g. `!1`) _are_ showing in all my worktrees. I'm not sure if it's because of the later Git version (2.40) or because of Microsoft's additions, but I'm not complaining.

**Comment by art3xias23** [comment]
@joepvl 

I'm on Windows with WSL2 with Debian and just updated git for windows to version 2.42.0

Unfortunately, still not seeing branch name and status indicator for worktrees.

**Comment by Freed-Wu** [comment]
A reproduce steps:

```sh
❯ git clone --bare https://github.com/petronny/pinyin-completion pinyin-completion
❯ cd pinyin-completion
❯ git worktree add ../src
❯ cd ../src
❯ cat .git
gitdir: /home/wzy/.cache/paru/clone/pinyin-completion-git/pinyin-completion/worktrees/src
```

![screen-2023-10-20-18-29-32](https://github.com/romkatv/powerlevel10k/assets/32936898/98a65edd-fd52-468f-b999-7c905b900c10)

No any git status.

OS: 6.5.6-arch2-1
zsh: 5.9 (x86_64-pc-linux-gnu)

**Comment by romkatv** [comment]
Please don't post "me too" comments here. They aren't helpful.

**Comment by joaotavora** [comment]
> Please don't post "me too" comments here. They aren't helpful. 

The clean reproducer that someone just added and someone just deleted was certainly helpful

**Comment by fei6409** [comment]
It looks like the `extensions.worktreeconfig` support was added recently: libgit2/libgit2#6044

**Comment by joepvl** [comment]
> ~FWIW: I had this problem up to Git 2.39, but I recently started using [microsoft/git](https://github.com/microsoft/git) with a large monorepo I'm working on, and now both the branch name and the status indicator shorthand (e.g. `!1`) _are_ showing in all my worktrees. I'm not sure if it's because of the later Git version (2.40) or because of Microsoft's additions, but I'm not complaining.~ **EDIT** it has since stopped working again unfortunately. My setup hasn't structurally changed but the repo has grown.

Update on this: it still doesn't work... __in iTerm2__. Even on a new machine with fresh installs of both iTerm2 and p10k, the repo I work on has this problem. It works fine in other terminal emulators I've tried on macOS — Terminal.app, WezTerm, Alacritty, even Warp. I've personally switched to WezTerm full time and am no longer experiencing issues. I don't know if the problem is with iTerm2 itself or the way p10k (internals and/or dependencies) acts when it detects it's being run in iTerm2. :shrug:

**Comment by Nxt3** [comment]
> Update on this: it still doesn't work... **in iTerm2**. Even on a new machine with fresh installs of both iTerm2 and p10k, the repo I work on has this problem. It works fine in other terminal emulators I've tried on macOS — Terminal.app, WezTerm, Alacritty, even Warp. I've personally switched to WezTerm full time and am no longer experiencing issues. I don't know if the problem is with iTerm2 itself or the way p10k (internals and/or dependencies) acts when it detects it's being run in iTerm2. 🤷

Yeah I'm noticing the same. Has anyone discovered a workaround?

**Comment by kwillis01** [comment]
I am having this issue as well, except for I can see the status for a while, then it disappears. If I delete the local repo and reinstall and add back all the worktrees it usually works again for a while, then disappears at some point.

**Comment by jousby** [comment]
It looks like libgit2 v1.8.0 added the fix but the libgit2 bundled in the gitstatus project is using an older version? 
@romkatv any chance the community might be able to convince you to schedule a deps refresh. Please.

git worktrees "are like so hot right now" with everyone trying to get ai agents working on multiple feature requests in parallel. it would be great to keep the existing powerline10k users ticking along happily in the agentic development / multiple spinning plates world.
