### ISSUE TITLE
Custom newline prompt no longer works after switching to pl10k

### ISSUE THREAD

**Issue by martmists** [romkatv/powerlevel10k#818]
Code (PL9K):
```bash
# newline
custom_newline(){
    print -P "\e[49m%F{236}"
}
POWERLEVEL9K_CUSTOM_NEWLINE='custom_newline'
POWERLEVEL9K_CUSTOM_NEWLINE_BACKGROUND="black"
POWERLEVEL9K_NEWLINE_BACKGROUND="234"
POWERLEVEL9K_NEWLINE_FOREGROUND="234"
```
The effect:
![image](https://user-images.githubusercontent.com/16361449/84575078-0568f980-adab-11ea-9ce0-629f2a3e549a.png)

This allowed me to use prompts on multiple lines, which no longer works in pl10k:
![Screenshot_20200613_192229](https://user-images.githubusercontent.com/16361449/84575100-3c3f0f80-adab-11ea-8944-87cb2eb674fa.png)

**Comment by romkatv** [comment]
Wow. I don't know if I'm more impressed or repulsed by this hack.

To define a multi-line prompt, put `newline` in `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and/or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. I would also recommend running `p10k configure` to get a decent config.

If you cannot figure out how to define a prompt you want, open another issue and describe how you want prompt to look like.
