### ISSUE TITLE
Cannot change prompt char content expansion 

### ISSUE THREAD

**Issue by philong6297** [romkatv/powerlevel10k#820]
### enviroment
- OS: PopOS 20.04
- zsh: 5.8
- config with zinit

### context
This is my related config (i think so)
```zsh
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=green
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=red
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_CONTENT_EXPANSION='✓'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_CONTENT_EXPANSION='✗'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false
```
As you can see in the picture below, the error prompt symbol is still the '✓' symbol. Im i missing something ?
![image](https://user-images.githubusercontent.com/29605147/84584803-14938a00-ae33-11ea-9a71-0e80796e6734.png)

For more information, i attached my config files in a zip if it can help you guys.
[longlp.zip](https://github.com/romkatv/powerlevel10k/files/4775878/longlp.zip)

### More question
From reading p10k-pure.zsh, i know that ```POWERLEVEL9K_PROMPT_CHAR_{OK, ERROR}_ ...``` is for customize the style of last command status, is the a way i can achieve in transient mode that my status prompt is coressponding to that content of promp like this:
![image](https://user-images.githubusercontent.com/29605147/84585078-04c97500-ae36-11ea-9437-a6f8fc8f6901.png)

**Comment by romkatv** [comment]
> As you can see in the picture below, the error prompt symbol is still the '✓' symbol.

Thanks for reporting this bug. Fixed. Please update powerlevel10k and try again.

As for you second question, I'm afraid the answer is that it's impossible. See [FAQ](https://github.com/romkatv/powerlevel10k/blob/master/README.md#can-prompts-for-completed-commands-display-error-status-for-those-commands-instead-of-the-commands-preceding-them).

**Comment by philong6297** [comment]
thanks for quick response, it works now. But im going to stick with default prompt symbol, because my question is impossible to achieve, so it not make any senses to use tick and cross symbol.

**Comment by romkatv** [comment]
It's unnecessary to use different symbols because different colors (green and red) are already enough to differentiate between successful and failed commands.
