### ISSUE TITLE
Enable POWERLEVEL9K_DIR_HYPERLINK made directory have dot line under content

### ISSUE THREAD

**Issue by philong6297** [romkatv/powerlevel10k#821]
i enabled ``POWERLEVEL9K_DIR_HYPERLINK=true`` and it made a dot line like this, is there any option i can remove it?
![image](https://user-images.githubusercontent.com/29605147/84600047-c026f380-aea0-11ea-8ac2-b57cbc97e4f1.png)
My terminal is gnome terminal. I print some other links in this terminal and it didnt have it, the dash line is showed up when i hover on the link:
![image](https://user-images.githubusercontent.com/29605147/84600086-1431d800-aea1-11ea-9e7c-dc44ad3c14d6.png)

**Comment by romkatv** [comment]
> i enabled `POWERLEVEL9K_DIR_HYPERLINK=true` and it made a dot line like this, is there any option i can remove it?

Your terminal determines how hyperlinks are styled. If it doesn't have an option to control styling of links, then you cannot change it.

> My terminal is gnome terminal. I print some other links in this terminal and it didnt have it

These aren't hyperlinks, they are just text. If you set `POWERLEVEL9K_DIR_HYPERLINK=false`, your directory will also be just text. But with `POWERLEVEL9K_DIR_HYPERLINK=true` is becomes a hyperlink.

Here's the spec for hyperlinks in terminals: https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda.

**Comment by philong6297** [comment]
yeah you are right, i readed the link you gave me, thanks you.
