### ISSUE TITLE
VCS segment does not work with $GIT_DIR

### ISSUE THREAD

**Issue by StopMotionCuber** [romkatv/powerlevel10k#822]
When having $GIT_DIR set, powerlevel10k does not detect this.
I'm using this in combination with `vcsh` (basically have multiple git configs with your homedir as root, and with the `zsh` theme agnoster this worked.

Would be nice if you could take a look at this

**Comment by romkatv** [comment]
Have you seen this? https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-is-git-status-from-homegit-not-displayed-in-prompt

If yes, please post instructions how to reproduce the problem.

**Comment by StopMotionCuber** [comment]
No, haven't seen this, feeling kinda dumb now.
I thought this was related to the fact that $GIT_DIR is used, and not that we are talking about the home directory.

Thank you, this fixed the issue for me
