### ISSUE TITLE
Too many zsh processes

### ISSUE THREAD

**Issue by misuzu** [romkatv/powerlevel10k#823]
Every zsh session spawns two additional zsh processes. 
Here i've started 4 zsh sessions under tmux and they started additional 8 zsh processes:
https://i.imgur.com/BUzSkzW.png
It's not spawning additional processes when using older `.p10k.zsh` (no idea what version, it says `Generated by Powerlevel10k configuration wizard on 2020-01-13 at 01:40 EET` at the top of the file).
How to disable this behavior?

**Comment by romkatv** [comment]
> Every zsh session spawns two additional zsh processes.

Indeed. https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-does-powerlevel10k-spawn-extra-processes

> How to disable this behavior?

https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-uninstall-powerlevel10k

**Comment by ddzdll** [comment]
Now.. this one is a stupid question but.. is it possible to merge everything in a single file?

**Comment by romkatv** [comment]
What?

**Comment by rodhash** [comment]
In my case it seems to spawn even more zsh processes, for every zsh opened I see 4 in total

**Comment by romkatv** [comment]
> In my case it seems to spawn even more zsh processes, for every zsh opened I see 4 in total

That's normal.
