### ISSUE TITLE
history error when navigating using up or down

### ISSUE THREAD

**Issue by francogp** [romkatv/powerlevel10k#824]
[https://recordit.co/xndxC0sLyw](url)

This gif reproduce the problem. I'm only pressing up and down keys.

At the beginning you can see whats inside the history file, on the top. It seems that the char 'e' is causing problems for some reason.

this are my configs, but can be reproduced using default 'p10k configure'
[https://github.com/francogp/myzsh/blob/master/.p10k.zsh](url)

It seems that I can reproduce it ONLY inside windows WSL using windows terminal (on ubuntu distro), but if remote access to my Native Ubuntu server using the same window terminal and configs, all work just fine.

**Comment by romkatv** [comment]
Can you reproduce this if you disable Powerlevel10k but keep everything else unchanged?

**Comment by francogp** [comment]
Yes, it can be reproduced with vanilla default configs zsh. I will post the problem there. I cannot reproduce this on bash.

**Comment by francogp** [comment]
Did you know where is the correct bug tracker to report? zsh is not no github

**Comment by romkatv** [comment]
> Yes, it can be reproduced with vanilla default configs zsh.

Closing then.

> Did you know where is the correct bug tracker to report? zsh is not on github

If indeed you can reproduce this problem with the default zsh configs (meaning no user-defined zsh configs), then it's likely a bug in Windows Terminal. I've replied on your post at https://www.zsh.org/mla/workers//2020/msg00869.html.
