### ISSUE TITLE
Help: The command of "antigen theme" error.

### ISSUE THREAD

**Issue by yangxyo** [romkatv/powerlevel10k#825]
Use:
```
antigen theme romkatv/powerlevel10k
```
when I exec `source ~/.zsh` the shell will hang.

I found a solution, use:
```
THEME=romkatv/powerlevel10k
antigen list | grep $THEME; if [ $? -ne 0 ]; then antigen theme $THEME; fi
```

But, a new problem comes, when I open a new session it will occasionally show "You don't have any bundles."

There is an opening issue for a long time. 
https://github.com/zsh-users/antigen/issues/675#issuecomment-452764451

My powerlever10k is latest:
![image](https://user-images.githubusercontent.com/32320149/84735769-dcc54780-afd6-11ea-8d08-11f05c44c124.png)

From the pure: 
Update your .zshrc file with the following two lines (order matters). Do not use the antigen theme function.
> ```
> antigen bundle mafredri/zsh-async
> antigen bundle sindresorhus/pure
> ```

But the command of `antigen bundle` doesn't suit for powerlevel10k.
Is there a good way to solve it?

**Comment by romkatv** [comment]
> when I exec `source ~/.zsh` the shell will hang.

Don't use this command. See https://github.com/romkatv/powerlevel10k/blob/master/README.md#weird-things-happen-after-typing-source-zshrc.

> But, a new problem comes, when I open a new session it will occasionally show "You don't have any bundles."

You might want to report this to Antigen. Note that the last update to Antigen has happened 2.5 years ago, so a bug report is unlikely to have any effect.

> There is an opening issue for a long time.
> [zsh-users/antigen#675 (comment)](https://github.com/zsh-users/antigen/issues/675#issuecomment-452764451)

Indeed.

**Comment by yangxyo** [comment]
> You might want to report this to Antigen. Note that the last update to Antigen has happened 2.5 years ago, so a bug report is unlikely to have any effect.
> 
> 
> 
> > There is an opening issue for a long time.
> 
> > [zsh-users/antigen#675 (comment)](https://github.com/zsh-users/antigen/issues/675#issuecomment-452764451)
> 
> 
> 
> Indeed.

Oh, thanks. emm, it seems that you do not use antigen. Can you recommend another zsh manager for me？Very thanks.

**Comment by romkatv** [comment]
> it seems that you do not use antigen

No, I don't. I think it has generally fallen out of fashion.

> Can you recommend another zsh manager for me？

I don't use a plugin manager myself. I think zplug is fine, or zinit as long as you stick with the plain `zinit light foo/bar` and don't use anything else.

**Comment by yangxyo** [comment]
zinit is better, as you said, just use zinit light.
Only need 0.23 s to open zsh.
But the same plug with zplug, it needs 1 s.
```
# source ~/.zplug/init.zsh

# _Z_CMD=j

# zplug "zplug/zplug", hook-build:"zplug --self-manage"
# zplug "zsh-users/zsh-autosuggestions"
# zplug "zsh-users/zsh-syntax-highlighting"
# zplug "lib/theme-and-appearance", from:oh-my-zsh
# zplug "lib/clipboard", from:oh-my-zsh
# zplug "joel-porquet/zsh-dircolors-solarized"
# zplug "rupa/z", use:z.sh
# zplug "zsh-users/zsh-completions"
# zplug "b4b4r07/enhancd", use:init.sh
# zplug "lib/directories", from:oh-my-zsh
# zplug "zsh-users/zsh-history-substring-search"
# zplug "mollifier/cd-gitroot"
# zplug "paulirish/git-open"
# zplug "plugins/git", from:oh-my-zsh
# zplug "plugins/tmux", from:oh-my-zsh
# zplug "plugins/vi-mode", from:oh-my-zsh
# zplug "plugins/sudo", from:oh-my-zsh

# # # Load theme file
# zplug "romkatv/powerlevel10k", as:theme, depth:1

# if ! zplug check --verbose; then
    # printf "Install? [y/N]: "
    # if read -q; then
        # echo; zplug install
    # fi
# fi

# zplug load

```
