### ISSUE TITLE
Option to show multiline prompt only on change in working directory

### ISSUE THREAD

**Issue by jahan01** [romkatv/powerlevel10k#826]
I have a suggestion to add an option for multi line prompts where first line of the prompt only shows when there is change in working directory. 

I plan to keep more constant prompts like user/host, cwd, etc., in first line and frequently changing prompts like git status, exit codes, execution time etc., on second line. So this option can help to reduce visual clutter to an extent.

I wanted to get rid-off right prompts to have more space on the line and also it gets mad when resizing depending on the console application. I switch between vscode, jetbrains and iterm2 on Mac and each of these terminal behave differently during resize.

**Comment by romkatv** [comment]
This should do it:

```zsh
function p10k-on-pre-prompt() {
  if [[ $PWD == $my_last_pwd ]]; then
    p10k display '1'=hide
  else
    p10k display '1'=show
  fi
  my_last_pwd=$PWD
}
```

If you have left and right frame, you'll need to hide/show them too:

```zsh
function p10k-on-pre-prompt() {
  if [[ $PWD == $my_last_pwd ]]; then
    p10k display '1|2/left_frame|2/right_frame'=hide
  else
    p10k display '1|2/left_frame|2/right_frame'=hide
  fi
  my_last_pwd=$PWD
}
```

Instead of this, you might like `POWERLEVEL9K_TRANSIENT_PROMPT=always` or `POWERLEVEL9K_TRANSIENT_PROMPT=same-dir`. See demo: https://github.com/romkatv/powerlevel10k/blob/master/README.md#transient-prompt

**Comment by jahan01** [comment]
Thanks, it pretty close to what I am looking for. How can I move the RPROMT segments to the new line?

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/814. Basically, you need put the same prompt segments on both lines and then hide/show whichever are appropriate.

**Comment by jahan01** [comment]
I don't really follow the discussion, as I am a novice zsh/powerlevel user. I am looking to accomplish something like `POWERLEVEL9K_NEWLINE_LEFT_PROMPT_ELEMENTS`, if that exists. 
i.e., same as `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` but for newlines.

And what are left_frames and right_frames? Is it same as left_prompt and right_prompt ?

**Comment by romkatv** [comment]
I'm giving you as much info as I possibly can given how little information you've provided.

If you want more specific instructions, post your `~/.p10k.zsh` and explain how you want prompt to look like when you `cd` into a new directory and when you stay in the same directory.

**Comment by jahan01** [comment]
ok for now I ll live what I have, thanks for your support and quick response
