### ISSUE TITLE
Bug when using Ruby

### ISSUE THREAD

**Issue by surfcode** [romkatv/powerlevel10k#827]
When changing to a directory containing ruby files the UI messes up:

![image](https://user-images.githubusercontent.com/16279095/84801752-da2b1800-afff-11ea-9ffb-fd0172eddc25.png)
Also, the cursor is aligned at the start of the row resulting in the UI being erased when typing:

![image](https://user-images.githubusercontent.com/16279095/84801979-2e35fc80-b000-11ea-88a6-a98047d8d1b0.png)

**.zshrc** as follows:

```zsh

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="/home/surf/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git)

source $ZSH/oh-my-zsh.sh

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
```

The relevant piece in **.p10k.zsh** is **rbenv** being listed under POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS.

For the record: I am using the Windows Terminal with MesloLGS NF as font.

**Comment by romkatv** [comment]
Is `rbenv version` also broken?

**Comment by surfcode** [comment]
Thank you for your ultra fast response!

`rbenv version` renders the following:

![image](https://user-images.githubusercontent.com/16279095/84804920-bc5fb200-b003-11ea-86ff-b107f9314857.png)

(Thanks because I the version specified in the .ruby-version file was not installed yet :-)

**Comment by surfcode** [comment]
Thank you for your ultra fast response!

`rbenv version` renders the following:

![image](https://user-images.githubusercontent.com/16279095/84805243-40b23500-b004-11ea-84f2-a13e905c1a77.png)

(Also thanks because the version specified in the .ruby-version file was not installed yet :-).

**Comment by romkatv** [comment]
Thanks for the report and debug info. Should be fixed now. Please update and try again.

```zsh
git -C /home/surf/.oh-my-zsh/custom/themes/powerlevel10k pull
exec zsh
```

**Comment by surfcode** [comment]
Thank you. 

If anyone is using WSL and cloning repositories via GitHub's Desktop app (on windows) into a Linux vm add **.gitattributes** to the root of your repository and paste the following:
```zsh
* text=auto eol=lf
*.{cmd,[cC][mM][dD]} text eol=crlf
*.{bat,[bB][aA][tT]} text eol=crlf
```
This will make sure that LF line endings are kept as is except for possible Windows batch files.

**Comment by romkatv** [comment]
Could you confirm that my fix works for you? Did the original problem go away once you've updated powerlevel10k.

**Comment by surfcode** [comment]
I can confirm that your fix works! (After that I fixed the line endings to be LF instead of CRLF... great catch.)

**Comment by romkatv** [comment]
Thanks for the confirmation and for filing the bug in the first place.
