### ISSUE TITLE
Terminal not showing anything

### ISSUE THREAD

**Issue by LHY-iS-Learning** [romkatv/powerlevel10k#83]
Hi
I've been using powerlevel10k for a while now and just remembered to update the theme.
After update the theme, when I open a new tab, the terminal won't show anything
![image](https://user-images.githubusercontent.com/21372855/59151872-59e6d580-89ef-11e9-8e9b-88b65b6abb94.png)
Then I switch the theme to powerlevel9k and everything is normal.
Any idea what might be the problem?
Please tell me if I need to provide anything.
Thanks in advance!

**Comment by romkatv** [comment]
- What's your OS?
- Are you using a plugin manager?
- What's the output of `zsh -x`?

**Comment by LHY-iS-Learning** [comment]
macos
No, i add the repository as a submodule in my dotfiles
It outputs tons of codes, is it normal?

**Comment by romkatv** [comment]
> It outputs tons of codes, is it normal?

Yes. It prints every line of ZSH code that is executed. This lets you see on which command it hangs.

I'm assuming it actually hangs. Does it? Or is it an empty prompt that you can type commands into and execute them?

**Comment by LHY-iS-Learning** [comment]
Thank you!
Yes, it acutally hangs.
And when I execute `zsh -x`, the last line shows 
`+prompt_todo:14> bash -c $'\n      function dirname() {\n        local f=$1\n        [[ "$f" == bash ]] && f=/usr/local/bin/todo.sh\n        command dirname "$f"\n      }\n      source todo.sh shorthelp &>/dev/null\n      echo "$TODO_FILE"'`
Seems something wrong with todo-txt? 
I will try to disable the prompt element.
Yep, when i disable the prompt, the terminal's working as normal.
Can you inspect what's wrong with the code.

**Comment by romkatv** [comment]
Thanks, that's very useful information. Should be easy to fix with a bit more info.

What's the output of the following command?

```zsh
bash -c $'\n function dirname() {\n local f=$1\n [[ "$f" == bash ]] && f=/usr/local/bin/todo.sh\n command dirname "$f"\n }\n source todo.sh shorthelp\n echo "$TODO_FILE"'
```

And this:

```zsh
whence todo.sh
```

**Comment by LHY-iS-Learning** [comment]
It seems something wrong with the first command, the output is 
~~~~
 Usage: bash [-fhpantvV] [-d todo_config] action [task_number] [task_description]

  Actions:
    add|a "THING I NEED TO DO +project @context"
    addm "THINGS I NEED TO DO
          MORE THINGS I NEED TO DO"
    addto DEST "TEXT TO ADD"
    append|app ITEM# "TEXT TO APPEND"
    archive
    command [ACTIONS]
    deduplicate
    del|rm ITEM# [TERM]
    depri|dp ITEM#[, ITEM#, ITEM#, ...]
    do ITEM#[, ITEM#, ITEM#, ...]
    help [ACTION...]
    list|ls [TERM...]
    listall|lsa [TERM...]
    listaddons
    listcon|lsc [TERM...]
    listfile|lf [SRC [TERM...]]
    listpri|lsp [PRIORITIES] [TERM...]
    listproj|lsprj [TERM...]
    move|mv ITEM# DEST [SRC]
    prepend|prep ITEM# "TEXT TO PREPEND"
    pri|p ITEM# PRIORITY
    replace ITEM# "UPDATED TODO"
    report
    shorthelp

  Actions can be added and overridden using scripts in the actions
  directory.
~~~~

And the second command outputs `/usr/local/bin/todo.sh`

**Comment by romkatv** [comment]
Could you attach the whole `/usr/local/bin/todo.sh`?

**Comment by LHY-iS-Learning** [comment]
[todo.txt](https://github.com/romkatv/powerlevel10k/files/3268927/todo.txt)
I modified the extension to txt

**Comment by romkatv** [comment]
I couldn't reproduce it on macOS with your version of `todo.sh`. I've pushed a minor fix hoping for blind luck. Could you update powerlevel10k and try again? It's unlikely to help though.

If it still hangs, please manually execute the following command and send the output. Also say whether it hangs or not.

```zsh
() {
  local todo=$commands[todo.sh]
  [[ -n $todo ]] || return
  local script="
    function dirname() {
      local f=\$1
      [[ \"\$f\" == bash ]] && f=${(qqq)todo}
      command dirname \"\$f\"
    }
    source ${(qqq)todo} shorthelp &>/dev/null
    echo \"\$TODO_FILE\""
  echo $(bash -c $script)
}
```

**Comment by LHY-iS-Learning** [comment]
Thank you but It still hangs....

**Comment by romkatv** [comment]
If it still hangs, please manually execute the following command and send the output. Also say whether it hangs or not.

```zsh
() {
  local todo=$commands[todo.sh]
  [[ -n $todo ]] || return
  local script="
    function dirname() {
      local f=\$1
      [[ \"\$f\" == bash ]] && f=${(qqq)todo}
      command dirname \"\$f\"
    }
    source ${(qqq)todo} shorthelp &>/dev/null
    echo \"\$TODO_FILE\""
  echo $(bash -c $script)
}
```

**Comment by romkatv** [comment]
I rewrote that piece of code hoping that it'll avoid triggering whatever issues it's triggering on your machine. Could you update powerlevel10k and check whether `todo` prompt works now?

**Comment by LHY-iS-Learning** [comment]
It's working!!!
Thank you!

**Comment by romkatv** [comment]
Thank you for reporting the issue and for aiding in debugging it.
