### ISSUE TITLE
Evaluation of `_p9k__cwd_a` is slow

### ISSUE THREAD

**Issue by ben-z** [romkatv/powerlevel10k#831]
Hi Roman,

Thank you for spending so much time developing p10k! I recently discovered this and have been loving the speed!

However when I use p10k on my school servers (they put student home directories on a network attached storage) the prompts show up very slowly (the slowness isn't consistent, but the average is around 3 seconds with a large spread (~2s), based on my rough estimate). I pinpointed down the issue to this line: https://github.com/romkatv/powerlevel10k/blob/8854cb6000d7eccd9b95ca4eec9fb16ea8d283eb/internal/p10k.zsh#L204

If I change it to `_p9k__cwd_a=${_p9k__cwd}` it becomes a lot faster (however, a "Loading" message starts showing after this change: `username@host ~ loading ❯`—it disappears after a few seconds.)

I'm not too familiar with how these scripts work and wasn't able to get any information on what the `A` means from Google (my guess is that it expands the path to an absolute path?). Could you look into this? I'm surprised to not find any existing issues regarding this.

EDIT: oh I should also mention that instant prompt doesn't help with this.

**Comment by romkatv** [comment]
`:A` resolves symbolic links, so `_p9k__cwd_a` is roughly equivalent to `readlink -m $PWD` with `readlink` from GNU. If you remove `:A`, all prompt segments that reference `_p9k__cwd_a` will work incorrectly in the presence of symbolic links.

> I'm surprised to not find any existing issues regarding this.

The environment you are forced to work with is unusual bad. I'm closing this issue as I don't intend to support this use case. I realize that it sucks that you cannot use powerlevel10k at school. I'm sorry about that.
