### ISSUE TITLE
How to add git work in progress status

### ISSUE THREAD

**Issue by bsushmith** [romkatv/powerlevel10k#833]
I tried to go thru the instructions but was unable to understand how to add the git work in progress status in the prompt. Need assistance in adding this to prompt whenever I have a wip commit in a given git branch. 
`git log -n 1 | grep -c "\-\-wip\-\-"`

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status
