### ISSUE TITLE
Icons showing up weird after config

### ISSUE THREAD

**Issue by Razorfin8** [romkatv/powerlevel10k#834]
https://imgur.com/a/rjTqH8Y  <- not sure why icons are showing up like that.  Worked fine after the configuration then Terminator restarted and it looks like that

**Comment by romkatv** [comment]
Your terminal is using a font that's missing powerline glyphs. Either configure your terminal to use a better font (for example, [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#meslo-nerd-font-patched-for-powerlevel10k)), or run `p10k configure`.

**Comment by Razorfin8** [comment]
Ah,  I am new to using Terminator and I had switched to the recommended one but appaerntly my profile switched back.  Switched it back and it works fine. Thanks!
