### ISSUE TITLE
How to add -e option to gitstatus?

### ISSUE THREAD

**Issue by mundry** [romkatv/powerlevel10k#837]
Hey,

I've installed Powerlevel10k through the instructions for oh-my-zsh and ran the configuration wizard.

I was wondering how I'd go about adding the `--recurse-untracked-dirs` option for gitstatus.
Is this configurable yet? I could only find variables for the max number of stashes, changes, conflicts, etc.

Cheers!

**Comment by romkatv** [comment]
It's called `POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS`.

```zsh
typeset -g POWERLEVEL9K_VCS_RECURSE_UNTRACKED_DIRS=true
```
