### ISSUE TITLE
A little custom segment / path rewriting help needed

### ISSUE THREAD

**Issue by kachunkachunk** [romkatv/powerlevel10k#840]
Hello There,

I hate to bother you over what I believe is just going to be my lack of knowledge on how to use functions properly, but maybe if I'm getting stuck here, someone else may as well.

Basically I have this bash prompt that conditionally rewrites the present path if it matches a certain pattern.

It looks/works like this when done:
```
[ 1001 20:33:20 /foo1/bar1/myhomedir ]$ cd /dir1/dir2/dir3/dir4/4/012/345/678/901
[ 1002 20:33:23 Num 12345678901 / ]$ cd test
[ 1003 20:33:25 Num 12345678901 /test ]$
```

Elements:

- [,] are just style/separator characters
- 1001-1003 indicate the position in command history
- 20:33:xx is the timestamp of the command run, in local server time.
- Num is a plain text string, conditionally added.
- 12345678901 is the string derived from a conditionally reformatted present working directory/path.

And below is the sorry excuse of prompt scripting that I wrote 10+ years ago. It is still working without issue, as above... but I hope you don't get an aneurism reading it:

```
PROMPT_COMMAND='DIR=`pwd|sed -e "s!$HOME!~!"`; \
if [[ $DIR == /dir1/dir2*/dir3*/dir4/?/???/???/???/???* ]]; then \
    CurNum="Num `pwd | cut -d / -f7-10 | cut -b2- | sed 's%/%%g'` "; \
    CurDir="/`pwd | cut -d / -f11-`"; else \
        CurNum=""; \
        CurDir=`pwd`; \
fi'

PS1="$bldwht[ $txtwht\! \t $bldred\$CurNum$txtrst$bldblu\$CurDir$txtrst $bldwht]\\$ $txtrst"
PS2="$bldwht> $txtrst"
```

- The else statement prevents the number from being printed when you've navigated out of a matching path.
- This could certainly be done more elegantly.
- I'm breaking all kinds of laws and best practices when it comes to formatting, I'm sure, too.

What I am trying to incorporate via a new segment function:
```
  function my_dir_number() {
        var_pwd=`pwd|sed -e "s!$HOME!~!"`
        if [[ $var_pwd == /dir1/dir2*/dir3*/dir4/?/???/???/???/???* ]]; then
            var_current_num="`pwd | cut -d / -f7-10 | cut -b2- | sed 's%/%%g'`"
            p10k segment -b 'gray' -f 'red' -t "${var_current_num}"
        fi
        }
```

Unfortunately I don't see the segment in my left/newline/right prompt when testing in what I would expect is a matching path. But I figure it's just my function being terrible, and my general lack of understanding.

The end result I'd like to see would be something like:
[powerlevel10k segments, usual-smart-path-stuff] .... [right segment stuff]
[newline] [my_dir_number] ❯

The path depth can be an additional 8 or so levels after what you see above, so it can get a bit silly looking, hence doing something similar to what hash does (plus rewrite), here.

Really appreciative of some help on this one. I'm also not necessarily married to the idea of having to parse/format it the way I am, if you have a more elegant way of doing this kind of thing.

**Comment by romkatv** [comment]
This should do it:

```zsh
function prompt_my_dir_number() {
  emulate -L zsh
  if [[ $PWD == /dir1/dir2*/dir3*/dir4/?/???/???/???/???* ]]; then
    p10k segment -b gray -f red -t "${(j::)${(@s:/:)PWD}[7,10]}"
  fi
}
```

The important difference is the name of the function. I've also rewritten it to make it simpler and much faster. If you have multiple directory patterns, you can do it like this:

```zsh
function prompt_my_dir_number() {
  emulate -L zsh
  case $PWD in
    /dir1/dir2*/dir3*/dir4/?/???/???/???/???*)
      p10k segment -b gray -f red -t "${(j::)${(@s:/:)PWD}[7,10]}"
    ;;
    ~/foo/bar/*)
      p10k segment ...
    ;;
  fi
}
```

Here's how `"${(j::)${(@s:/:)PWD}[7,10]}"` works:

1. `"${(@s:/:)PWD}"` splits `$PWD` on `/`, resulting in an array.
2. `"${${(@s:/:)PWD}[7,10]}"` selects elements 7-10 from the array.
3. Finally, `(s::)` joins the elements with an empty string as separator.

**Comment by kachunkachunk** [comment]
Super helpful - thank you!

So indeed my mistake was a misunderstanding of two things:
1. Function naming is indeed important - `prompt_my_prompt_name` would be needed in this case, and to include it in my left side config (newline or not), I have to also call the function as `my_prompt_name`, dropping the `prompt_` prefix.
This is easily noticed when trying to display the helpful `prompt_example` as a test - in the left/right line config, it's called by just `example`.

2. Also, seems I needed the `emulate -L zsh` line - I surmise that  is so subshells/scripting can be performed within the function.

I greatly appreciate the streamlining via array that you did! Much cleaner... though I wasn't sure how to add additional logic to that in the segment's expansion (-t) - a leading number/character needs to be dropped, so: .../~~0~~12/345/678/901. I presume I'd instead have to parse it all 'n' characters into an array, and just grab the last 10 digits, perhaps.

Still, for now, I managed to just reincorporate the less efficient cut + sed commands like my old bash scripting, and it works well. If that seems generally distasteful or offensive in some way (heh), I'm open to more suggestions, but you've pretty much solved this one for me now and I am on the path to writing more plugins as needed for what I'm doing - thank you very much! All of this is helpful.

```
  function prompt_my_current_sr() {
    emulate -L zsh
    if [[ $PWD == /dir1/dir2*/dir3*/dir4/?/???/???/???/???* ]]; then
      local var_curNum
      local var_curDir
      var_curNum="`pwd | cut -d / -f7-10 | cut -b2- | sed 's%/%%g'`"
      var_curDir="/`pwd | cut -d / -f11-`"
      p10k segment -b gray -f red -t "Num ${var_curNum} ${var_curDir}"
    fi
  }
```

**Comment by romkatv** [comment]
> seems I needed the `emulate -L zsh` line - I surmise that  is so subshells/scripting can be performed within the function.

This line ensures that your function is executed with predictable shell options. For example, it assumes that arrays are one-based but this is only true if `ksh_arrays` is unset. `emulate -L zsh` ensures that it's indeed unset, so your function will always work the same way regardless of which options powerlevel10k chooses to use for its own internal code.

> I wasn't sure how to add additional logic to that in the segment's expansion (-t) - a leading number/character needs to be dropped

```zsh
function prompt_my_dir_number() {
  emulate -L zsh
  if [[ $PWD != /dir1/dir2*/dir3*/dir4/?/???/???/???/???* ]]; then
    return
  fi
  # Split $PWD on '/' and store the result in an array.
  # The first two elements are "" and "dir1". They can
  # be referred to as $parts[1] and $parts[2].
  local parts=("${(@s:/:)PWD}")
  # Select elements 7 through 10 (inclusive).
  parts=($parts[7,10])
  # Join elements with an empty string as separator.
  local tail=${(j::)parts}
  # Remove the first element.
  tail[1]=""
  p10k segment -b gray -f red -t $tail
}
```

See docs: http://zsh.sourceforge.net/Doc/Release/Expansion.html

> If that seems generally distasteful or offensive in some way (heh)

It does hurt a bit, yes. Your custom segment is over 1000 times slower than it needs to be. It can make your prompt noticeably slower despite having very little computation in it.

**Comment by kachunkachunk** [comment]
Yikes, okay - that's compelling enough for me to commit to refine this then, appreciate the kicks in the right direction.

**Comment by romkatv** [comment]
> appreciate the kicks in the right direction.

The code I’ve posted should work the same way as your version (except faster). Does it work for you?

**Comment by kachunkachunk** [comment]
Yes it does, thank you - and your comments/explanations help with my understanding/learning quite a bit.
Admittedly I haven't really noticed issues with the old prompt necessarily _feeling_ slow with all that piping, but I'm still committing to trying the better/faster approach you wrote and will keep at it for my ongoing efforts. But yes, so far so good. Real good, actually.

If you're curious what this is all for - my main intention for now is to build upon a function (or few) that organically and automatically parses and hashes useful attributes/properties that can be gleaned from extracted log bundles taken from a bunch of servers.
So, just from navigating in certain locations is enough for it to get/save/print useful values, without having to manually read/grep output/diagnostic files. It can just be stored in variables and/or hashes automatically, provided in a convenient prompt, or both.

Anyway I learned a good deal from many of your suggestions around the Issues tracker and here, so you've been quite empowering - thank you again.

**Comment by fernandoroa** [comment]
I wanted to bring attention to this question, maybe the authors in this thread can help me? https://superuser.com/questions/1808323/how-to-change-folder-separator-in-p10k-command-line
