### ISSUE TITLE
Flutter fvm prompt broken after fvm update to 1.0.x

### ISSUE THREAD

**Issue by orestesgaolin** [romkatv/powerlevel10k#842]
After latest update of [fvm](https://github.com/leoafarias/fvm) the POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS doesn't show correct version.

Now in order to check currently used version following command need to be used:

```sh
fvm flutter --version
```

**Comment by romkatv** [comment]
Thanks for the report. Fixed.
