### ISSUE TITLE
laravel version and icon not showing on regular user

### ISSUE THREAD

**Issue by adamkenway007** [romkatv/powerlevel10k#843]
hello i've encountered problem with powerlevel10k icon and version of laravel not showing,i'm already done enable laravel_version line and also read documentation other icon is all working.strangely this problem only occur in regular user when i'm log out then switch user (i'm using debian btw) with root user laravel version and icon are working.tried copy root oh-my-zsh & powerlevel10k into regular user oh-my-zsh & powerlevel10k then fix access mode still doesn't work either

**Comment by romkatv** [comment]
There is nothing in `laravel_version` prompt segment that is user-specific. If it works for some user on your machine but not for another user, there must be an issue in your configuration and/or file permissions. I don't have access to your machine, so I don't know what specifically you need to fix.
