### ISSUE TITLE
Suggestion: Add Codeigniter 4 check version

### ISSUE THREAD

**Issue by adamkenway007** [romkatv/powerlevel10k#844]
hello could you add support codeigniter 4 check version please?.. codeigniter 4 is current version nowdays

**Comment by adamkenway007** [comment]
> 
> 
> I don't understand your suggestions. Could you elaborate? What changed do you wan to see in powerlevel10k?

i would like see codeigniter_version promot segment in powerlevel10k similiar as laravel_version but this for codeigniter

**Comment by romkatv** [comment]
Got it. I acknowledge the feature request. I'm unlikely to work on it any time soon. If you could post the list of commands I need to execute in order to obtain the content you want shown in prompt, it'll make it plausible that I'll work on this feature request in 2020. Otherwise I likely won't.

**Comment by romkatv** [comment]
This issue has died of old age.
