### ISSUE TITLE
[BUG] Flutter fvm prompt does not respect POWERLEVEL9K_FVM_FOREGROUND color

### ISSUE THREAD

**Issue by orestesgaolin** [romkatv/powerlevel10k#845]
I've recreated `.p10k.zsh` file with p10k configure and it has some configuration parameters for `fvm` prompt:

- POWERLEVEL9K_FVM_FOREGROUND
- POWERLEVEL9K_FVM_VISUAL_IDENTIFIER_EXPANSION

They are not respected when displaying prompt. Instead a letter 'F' from `icons.zsh` and color `p9k_color1` are used.

**Comment by romkatv** [comment]
That's embarrassing. Thanks for reporting this so quickly after my breaking it. Fixed.
