### ISSUE TITLE
Suggestion: GitHub Sponsor or Buy Me a Coffee

### ISSUE THREAD

**Issue by orestesgaolin** [romkatv/powerlevel10k#846]
I wonder if it would be possible to setup the GitHub Sponsor for the powerlevel10k. I'd happily contribute some money.

**Comment by romkatv** [comment]
> I wonder if it would be possible to setup the GitHub Sponsor for the powerlevel10k.

It's possible but it's more hassle than it's worth.

> I'd happily contribute some money.

Your willingness to pay is appreciated :wink:
