### ISSUE TITLE
Conditional statement to remove LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL

### ISSUE THREAD

**Issue by alexdauenhauer** [romkatv/powerlevel10k#848]
Is there a way I could add a conditional statement to include a LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL when in a normal directory, but set it to blank when I am in a git repo?

![image](https://user-images.githubusercontent.com/11903445/85903694-95a43700-b7cc-11ea-8d0b-0510c247858b.png)

I want to have a solid fill on my DIR segment, but I want my VCS segment to have clear background. When I set it this way, the LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL shows up black instead of clear so I want to just remove it with a condition if possible

**Comment by romkatv** [comment]
This should do it:

```zsh
POWERLEVEL9K_VCS_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
```

This sets left prompt terminator to empty when `vcs` is the last (rightmost) visible segment.

P.S.

Have you tried Lean style? Your prompt is already almost devoid of background, so Lean style would be a natural choice.

**Comment by alexdauenhauer** [comment]
@romkatv thank you very much! Yes I started with lean style in the configuration wizard. I am still playing around with it. Lean looks really nice, I just kind of liked having one segment with background, but might go back to it.

**Comment by romkatv** [comment]
Thanks for confirming that it works for you.
