### ISSUE TITLE
icon for root directory is not correct

### ISSUE THREAD

**Issue by Puspendert** [romkatv/powerlevel10k#849]
When I type `cd /` the icon I get is not recognized to me. Is it a valid icon or I need some more configuration?

![Screenshot 2020-06-27 at 9 14 38 PM](https://user-images.githubusercontent.com/16055344/85926272-037b5c00-b8bc-11ea-94cf-96342a765d8f.png)

Also, I executed `p10k configure` multiple times but still, I can't see the lock icon when configuration asks for it. Why font awesome icon not visible here?
![Screenshot 2020-06-27 at 9 15 56 PM](https://user-images.githubusercontent.com/16055344/85926301-2f96dd00-b8bc-11ea-802d-fc6ca2a18472.png)

**Comment by romkatv** [comment]
This icons means the current directory is not writable. To customize it, open `~/.p10k.zsh` and search for this line:

```zsh
typeset -g POWERLEVEL9K_LOCK_ICON='∅'
```

Set value to `''` to not show any icon. Or set it to anything you like.

**Comment by romkatv** [comment]
> Also, I executed `p10k configure` multiple times but still, I can't see the lock icon when configuration asks for it.

Try [the recommended font](https://github.com/romkatv/powerlevel10k/blob/master/README.md#meslo-nerd-font-patched-for-powerlevel10k).
