### ISSUE TITLE
Two-line prompt leaves residual lines after terminal resizing

### ISSUE THREAD

**Issue by subnut** [romkatv/powerlevel10k#850]
![2020-06-27-232349_1920x1080_scrot](https://user-images.githubusercontent.com/56714626/85928804-77723000-b8cd-11ea-877a-69a1926e949d.png)

[See this screencast for reference](https://1drv.ms/u/s!AofEJose2lFFjku5-12hG030ml7L?e=qyNf7U)

The terminal is [kitty](https://github.com/kovidgoyal/kitty)
The p10k config can be found [here](https://github.com/subnut/dotfiles/blob/master/linux/home/.p10k.zsh)

**Comment by romkatv** [comment]
> Two-line prompt leaves residual lines after terminal resizing

See https://github.com/romkatv/powerlevel10k/blob/master/README.md#horrific-mess-when-resizing-terminal-window

> [See this screencast for reference](https://1drv.ms/u/s!AofEJose2lFFjku5-12hG030ml7L?e=qyNf7U)

FYI: That link doesn't work for me.

![image](https://user-images.githubusercontent.com/1282067/85928807-256ee180-b8b0-11ea-848c-5fe00144f6e5.png)
