### ISSUE TITLE
Show battery segment only below a threshold 

### ISSUE THREAD

**Issue by ashish-kothari** [romkatv/powerlevel10k#853]
Hi,

I tried looking through the issues and the documentation but I couldn't find an example to conditionally show the `battery` segment (say only if the battery is below 30%). I see that some of the segments can be controlled using their respective `SHOW_ON_COMMAND` parameter, is there something similar for `battery`? 

I considered writing a custom prompt segment but I like the bundled implementation and would prefer to extend that functionality. Let me know if there's already something available to achieve this.

Thanks

**Comment by romkatv** [comment]
This should do it:

```zsh
# Don't show battery if it's at or above this charge level.
typeset -g POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD=30
```

All segments respect `SHOW_ON_COMMAND`. You can try it with this:

```zsh
# Show battery only when the current command being typed invokes `echo`.
typeset -g POWERLEVEL9K_BATTERY_SHOW_ON_COMMAND=echo
```

This isn't very useful. But then again, `battery` segment isn't very useful.

**Comment by ashish-kothari** [comment]
Thanks, it works! I agree it's not very useful and I want it to pop up only if it requires me to plug in the power.

**Comment by romkatv** [comment]
> Thanks, it works!

Thanks for the confirmation. Closing the issue.
