### ISSUE TITLE
Fading squares doesn't look as expected

### ISSUE THREAD

**Issue by jcrengifoa** [romkatv/powerlevel10k#854]
Hello!,

Is there any way to fix the way the fading looks? It is supposed to look like a solid fading square but I see it as a group of dots. I am using the recommended font (auto-downloaded from wizard).

Current:
![Screen Shot 2020-06-29 at 12 33 47](https://user-images.githubusercontent.com/8794284/86032543-e48cdf00-ba0d-11ea-9308-7c1774aac4e4.png)

Expected:
![extravagant-style](https://user-images.githubusercontent.com/8794284/86036656-93ccb480-ba14-11ea-8e00-0050b1fd5cdb.png)

iTerm2 Build 3.3.11

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k/issues/537.
