### ISSUE TITLE
'inline' visual mode for vi-mode

### ISSUE THREAD

**Issue by LHY-iS-Learning** [romkatv/powerlevel10k#855]
First, p10k is a great project and thanks for your effort for making the project excellent!
I use p10k for both working terminal and personal terminal.

Today I just notice there's a feature in working terminal that allows 'inline' visual mode.
The usual visual mode would open a tmp file in vi, and edit inside the file, which I'm not a fan of it.
However, this visual mode allows me to modify the content in command line via visual mode.

I cannot configure this feature to be enabled on personal terminal.
So, is this the p10k feature? 
If so, how should I enable this via `p10k.zsh`?
Thanks in advance!

**Comment by romkatv** [comment]
What is 'inline' visual mode?

Zsh does have visual mode. Here's how you can use it.

1. Type `zsh -d`. This will launch zsh without user configs.
2. Type `bindkey -v`. This will make vi keymap the default.
3. Type something but don't hit <kbd>Enter</kbd>.
4. Press <kbd>Esc</kbd> to enter command mode.
5. Press <kbd>v</kbd> to enter visual mode.
6. Press <kbd>V</kbd> (<kbd>Shift+v</kbd>) to enter line visual mode.

As you can see this is builtin in Zsh. No plugins required. Now, there are plugins that break this functionality by rebinding <kbd>v</kbd> and/or <kbd>V</kbd>. I think `vi-mode` plugin in Oh My Zsh does this. It binds <kbd>v</kbd> to `edit-command-line`. I would recommend disabling that plugin. If you want to have a binding for `edit-command-line`, you can add it like this:

```zsh
autoload -Uz edit-command-line
zle -N edit-command-line
# Ctrl+E: edit command line in external editor.
bindkey -M vicmd '^E' edit-command-line
```

**Comment by LHY-iS-Learning** [comment]
Thanks!
Thats exactly what I want, i always use `vi-mode` plugin and don't know `bindkey -v` would achieve the same without `edit-command-line` feature.
Thanks again for pointing that out!
