### ISSUE TITLE
Weird Glyph on startup (even when not in a git folder)

### ISSUE THREAD

**Issue by justahuman1** [romkatv/powerlevel10k#857]
Hello, 

A few days ago, this symbol appeared on the right side prompt and I'm unsure of what is means (!1/1). 
![p10k prompt glyph](https://user-images.githubusercontent.com/40372802/86267798-1ae86c80-bb7c-11ea-894c-0d80fde778a9.png)

I tried searching for this on issues and search engine to no avail. I also did not see it referred to in the troubleshooting section. This prompt occurs on terminal startup and renders in all folders, even if it is not a git folder. Thank you.

Terminal: Kitty

**Comment by romkatv** [comment]
That's taskwarrior. You have a task overdue. Type `tw` to see it.

**Comment by romkatv** [comment]
Sorry, I think the command is called `task` (not `tw` as I wrote earlier).

**Comment by justahuman1** [comment]
Wow, features that I didn't even know existing. Thank you for such an awesome theme!

**Comment by romkatv** [comment]
You are very welcome.

If you want to customize how taskwarrrior task counts are displayed in prompt, open `~/.p10k.zsh` and search for "taskwarrrior". You'll find a section there with plenty of comments.

If you don't want to see taskwarrior in prompt, comment out the first occurrence of "taskwarrior" in `~/.p10k.zsh`.

> Where can I find a complete list of the supported glyphs?

If you mean the list of prompt segments, then see https://github.com/romkatv/powerlevel10k/blob/master/README.md#batteries-included. You can also see them close to the top of `~/.p10k.zsh`. You might want to try uncommenting something that's commented just to see what happens.
