### ISSUE TITLE
Incompatibility with new zsh version

### ISSUE THREAD

**Issue by ahmadrezash** [romkatv/powerlevel10k#859]
hi
pk10 is Incompatibility with new zsh version 5.2
I think its cause of where pk10 is located in oh-my-zsh dir
It's in "/home/ahmad/.oh-my-zsh/custom/themes" but loaded from "/home/ahmad/.oh-my-zsh/themes" and zsh said it's not found

please fix this issue about this greate theme pk10 :)

**Comment by romkatv** [comment]
Closing as nonsense.
