### ISSUE TITLE
Nerd-Fonts not showing for 'ls' command

### ISSUE THREAD

**Issue by ueberBrot** [romkatv/powerlevel10k#86]
It seems that I cant make Nerd-Fonts completely work for me. In my prompt the Nerd-fonts are displayed but when I use the 'ls' command the folder or file icons in front of the names are not showing.

This is a Tilix screenshot:
![image](https://user-images.githubusercontent.com/32489486/59335845-ab4bd900-8cfd-11e9-9c1d-257ba361c927.png)

I tried it also in Terminator:
![image](https://user-images.githubusercontent.com/32489486/59335950-e948fd00-8cfd-11e9-923e-e2375c598bc8.png)

In the standard Gnome-Terminal i cant choose the Hack Font Mono Regular. Thats why i cant provide a screenshot of that because it doesn't work.

OS: Manjaro Linux 18.0.4 Illyria Gnome Desktop (up-to-date)
zsh: zsh 5.7.1 (x86_64-pc-linux-gnu) + [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)

Fonts: Hack Fonts Mono Regular in Tilix:
![image](https://user-images.githubusercontent.com/32489486/59337355-b81dfc00-8d00-11e9-98d0-9bbda8b5e942.png)
In Terminator I also changed it that way.

I downloaded this directly from the [nerd-fonts](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack/Regular/complete) repo. Here i picked `Hack Regular Nerd Font Complete Mono.ttf` I installed it after opening the font and clicking on `Install`.

My `.zshrc` file looks like this:
```zsh
# Font mode for powerlevel10k
POWERLEVEL9K_MODE='nerdfont-complete'

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/user/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true

# Separators
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR_ICON=$'\ue0b0'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR_ICON=$'\ue0b1'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR_ICON=$'\ue0b2'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR_ICON=$'\ue0b7'

# VCS colours
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='orange1'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='lightgreen'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='lightgreen'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'

# Command auto-correction.
ENABLE_CORRECTION="true"

# Command execution time stamp shown in the history command output.
HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
	git
	copyfile
	dirhistory
	extract
	pipenv
	sudo
	zsh-autosuggestions
	zsh-syntax-highlighting
	zsh-completions
)

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

#Removes username@hostname
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
  fi
}
```
With `get_icon_names`  i get this: https://imgur.com/a/qjNGXQV 

Hope you can help me

Cheers ueberBrot

**Comment by ueberBrot** [comment]
I close this issue because I figured out that it is not powerlevel10k related...

For anybody wondering: The desired behavior is achieved with the ruby gem `colorls`.

**Comment by romkatv** [comment]
> For anybody wondering: The desired behavior is achieved with the ruby gem colorls.

Or https://github.com/Peltoche/lsd. It's about 40 times faster.

**Comment by ueberBrot** [comment]
@romkatv why don't you recommend it? An why no aliasing if you mind me asking?

**Comment by romkatv** [comment]
Aliasing `ls` to `lscolor` is a bad idea because its output is verbose and incompatible. Most of the time when you need to list a directory you want terse output.

Using `lsd` in addition to `ls` is OK. After some time you'll likely realize you never actually use `lscolor`. There will be many reasons for it:
1. It's not available on some of the machines where you need to do stuff.
2. When `lsd` is available, half of the time patched fonts don't work.
3. The output is too verbose. Icons are impractical and useless.

The one good use case for `lsd` is to make pretty screenshots to elicit "wow" from Bash users.

This is just my personal opinion of course.

P.S.

Judging by the two issues I've seen you open I'll hazard a guess that you are new to ZSH. I strongly recommend sticking with more standard tools at least at first rather than installing flashy alternatives that only a tiny fraction of ZSH users employs. Once you get comfortable with the basics, you can try `lsd`, `rg` and a million ZSH plugins that exist out there.

**Comment by ueberBrot** [comment]
Thank you for your input.
And yes I'm fairly new to zsh. I thought about what you said and I think you're right.
I installed `lsd` and it is as stated in the repo noticeably faster so i'll switch to that and don't use aliases. I mean it' one letter more to type and that's ok.

**Comment by romkatv** [comment]
:+1:
