### ISSUE TITLE
Spaceship config

### ISSUE THREAD

**Issue by oktay** [romkatv/powerlevel10k#861]
Can you guys share spaceship config at the preview, I love p10k it is really fast and flexible but also I love spaceship theme. I'm not very good at zsh theme editing.

![fkadsjflkds](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/other-theme-emulation.gif)

**Comment by romkatv** [comment]
I don't have a spaceship config. I created a limited version with just 4 prompt segments to record this gif.

You might try running `p10k configure` and choosing *Lean* style. Then edit `~/.p10k.zsh` to customize it.
