### ISSUE TITLE
The prompt splits into two-line in CLion terminal

### ISSUE THREAD

**Issue by wishayne** [romkatv/powerlevel10k#862]
I'm using the default generated `.p10k.zsh ` settings and only `git` plugin installed.

It performs well in my windows terminal like this:
![well](https://user-images.githubusercontent.com/15211912/86509999-c0bb0600-be1e-11ea-9af5-3460414403df.png)

But when I use wsl as the CLion terminal and open it, it allways split ioto two-line just like this:
![bad1](https://user-images.githubusercontent.com/15211912/86510089-653d4800-be1f-11ea-9167-7dda19ac021a.png)
![bad2](https://user-images.githubusercontent.com/15211912/86510091-67070b80-be1f-11ea-8727-5ac591edf18a.png)

The issue does't happen in the VSCode integrated terminal.
![vscode-well](https://user-images.githubusercontent.com/15211912/86510141-c1a06780-be1f-11ea-9fa6-a50e8311a063.png)

**Comment by romkatv** [comment]
Please report this bug to CLion.
