### ISSUE TITLE
How to get "classic" frame but with "pure"/"rainbow" text colors

### ISSUE THREAD

**Issue by hermesjpappas** [romkatv/powerlevel10k#865]
Hello there! This is my first time ever submitting an "issue" so if this doesn't belong here please feel free to delete it.
I was wondering if there is a way to have the style of the "classic" p10k prompt (including the choice of darkness) but for the colors of the letters in it to follow the terminal colors just like "rainbow" and "pure" do. "Rainbow" is too bright for me and I feel that the default colors of "classic" clash with any theme chosen for the terminal overall.

If this is functionality that could be implemented, I'd love to see that, otherwise if it is a simple setting I'd love to know how to change it!

Thank you very much. :)

**Comment by romkatv** [comment]
You can generate a config with Classic style, open `~/.p10k.zsh`, search for `_FOREGROUND` and change values to 0-7.

Or select Lean style with 8 colors. (I'll let you on on a secret: Lean style is the best.)

**Comment by hermesjpappas** [comment]
Thank you for your quick response! I will try what you suggested. I hope it's OK to write again if I can't figure it out :)

**Comment by romkatv** [comment]
> I hope it's OK to write again if I can't figure it out :)

Sure thing.

**Comment by hermesjpappas** [comment]
<img src="https://images2.imgbox.com/ea/a9/70WoU3Nq_o.png" alt="image host"/>

I managed to get most of the colors working as I want (had to find 256 color alternatives for the git conditionals and the github icon was tough to locate and change) but your instructions helped, thank you for that!

I would love to see this as a version in the future if it's not too tough to implement: taking colors from the theme and putting them on top of the classic look for another theme variation that is selectable from the interactive configuration.

PS: Not related to the above but I hope I can ask here: is there a right arrow character that fits with the ╰─ characters in the terminal? I tried to find characters from the patched nerd fonts (including powerline symbols) and couldn't find something that fits. Thanks again!

**Comment by romkatv** [comment]
> I would love to see this as a version in the future if it's not too tough to implement: taking colors from the theme and putting them on top of the classic look for another theme variation that is selectable from the interactive configuration.

It's not difficult to implement but ongoing maintenance costs are non-trivial. Virtually no one uses Lean with 8 colors, so I expect that Classic with 8 colors wouldn't be popular either. The few users who want it can tweak colors manually.

> PS: Not related to the above but I hope I can ask here: is there a right arrow character that fits with the ╰─ characters in the terminal? I tried to find characters from the patched nerd fonts (including powerline symbols) and couldn't find something that fits. Thanks again!

When you ran `p10k configure` there was a screen to select *frame*. You've selected *left*, so you have it only on the left. There was also *full*, which would give you symmetric decoration on the right.

While right frame is pure decoration without functional drawbacks (apart from wasted space), left frame does have drawbacks. By default, when you choose prompt with left frame, `prompt_char` gets hidden. Without `prompt_char` it becomes necessary to enable `status` even in state `OK` (it's that green check mark that you can see on the right). If you use vi keymap, it also becomes necessary to enable `vi_mode`. All this wastes a lot of space. I highly recommend `prompt_char` over left prompt.

**Comment by romkatv** [comment]
Forgot to mention. These frames are made of box-drawing characters. See https://en.wikipedia.org/wiki/Box-drawing_character.

**Comment by hermesjpappas** [comment]
Sorry, I probably didn't clarify exactly what I meant. I only wanted the frames on the left so I chose the option I wanted in the configurator, but I wanted the little character to end in an arrow like this -> instead of an abrupt line cut/stop. 

Thank you for pointing me to the characters you used, I don't think something like what I want exists that is compatible with them but I'll have a look. 

Really enjoying your theme overall, thank you once more for it and for your guidance regarding its customization!

I will also have a look at what you said regarding picking prompt_char over the left frame and see how it goes. I like some snazzy visuals but if function trumps them I'll definitely consider changing. :)

**Comment by romkatv** [comment]
> Sorry, I probably didn't clarify exactly what I meant. I only wanted the frames on the left so I chose the option I wanted in the configurator, but I wanted the little character to end in an arrow like this -> instead of an abrupt line cut/stop.

Got it. Open `~/.p10.zsh`, search for `prompt_char` and uncomment the first occurrence. Additionally, you can now unclutter your prompt a little bit by setting `POWERLEVEL9K_STATUS_OK` and `POWERLEVEL9K_STATUS_ERROR` to `false`. This will hide `status` segment when it doesn't add anything useful on top of the information already provided by `prompt_char`.

What I'm saying here is that you can use `prompt_char` together with left frame.

**Comment by hermesjpappas** [comment]
Thank you so much! The default prompt character actually works quite nicely with the left frame. I'll experiment to see if I can find something that blends in even better but for now this is very cool, and what you suggested is indeed less cluttered.
