### ISSUE TITLE
The configuration wizard run on terminal start every time

### ISSUE THREAD

**Issue by gambithunt** [romkatv/powerlevel10k#866]
Hi there

I've been through the wizard over 10 times now and it keeps starting again and again after I quite and start iTerm2 again, that or the terminal or if I ssh in.

I have no idea how to sort it out, please help.

It does this even if I add POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true to my zshrc file

Thanks

**Comment by romkatv** [comment]
See https://github.com/romkatv/powerlevel10k#configuration-wizard-runs-automatically-every-time-zsh-is-started
