### ISSUE TITLE
context: distinguish local and remote root

### ISSUE THREAD

**Issue by maximbaz** [romkatv/powerlevel10k#868]
Hey!

Now that I tried p10k for remote shell, I would like to suggest to allow `context` segment distinguish local and remote root. Not sudo, I did see a few existing threads about SUDO and REMOTE_SUDO and how this is a legacy from P9K, I'm talking about a regular root.

Here's what I want to achieve with the built-in `context` segment:

| Context | Desired output of the segment |
|---------|-------------------------------|
| Local, regular user | (blank) |
| Local, root user | `root` (in red) |
| Remote, regular user | `username@hostname` (in green) |
| Remote, root user | `root@hostname` (in red) |

As far as I can see, with the current `context` module I can achieve the first three cases, but not the last one; there is only one `ROOT` configuration, so remote root is always rendered exactly as local root.

This custom segment demonstrates the behavior I want:

```
prompt_my_context() {
    local content
    local foreground='green'
    local user="${(%):-%n}"
    local host="${(%):-%m}"
    if (( P9K_SSH )); then
        content="$user@$host"
    elif ! (( EUID || UID )); then
        content="$user"
    fi
    ! (( EUID || UID )) && foreground='red'

    p10k segment -t "$content" -f "$foreground"
}
```

Let me know if this makes sense, hope I didnt miss something obvious.

**Comment by romkatv** [comment]
`context` segment is really stupid. I'm not changing it because of backward compatibility.

I can add new parameters or a new segment but you can actually achieve what you want with a simple `if`.

```zsh
if (( P9K_SSH )); then
  # remote non-root
  POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  # remote root
  POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
else
  # local non-root
  POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  # local root
  POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'fi
fi
```

You can also use `if (( EUID ))` instead of `ROOT` state if you don't care about setuid.

**Comment by maximbaz** [comment]
Of course 🤦‍♂️ I love this trick! No need for a new segment, I like your suggestion. Thanks!
