### ISSUE TITLE
Idea: color picker 

### ISSUE THREAD

**Issue by maximbaz** [romkatv/powerlevel10k#870]
This is just an idea, so feel free to close if it doesn't click with you 🙂 

Configuration wizard is very helpful to setup prompt layout, it provides visual feedback and saves a ton of time. 

Once the layout is set, a second task that consumes a lot of time is choosing colors for every single segment, and this is where I think we have an opportunity to improve.

The [one-liner to generate colormap](https://github.com/romkatv/powerlevel10k/blob/0c341b67024642b8f1741920d1ae5d760bc488b0/config/p10k-lean.zsh#L6) that you put in the comment block is a good start, but at least personally I found it still less than ideal to use: when you pick a color, it still looks differently on an actual segment, so you jump back and forth between configuration and prompt while trying neighboring colors to see which one looks best. `POWERLEVEL9K_DISABLE_HOT_RELOAD=false` helps, but I feel it still requires too much keypresses to compare between neighboring colors. 

So here's an idea inspired by a wizard:

- You type `p10k color <segment-name>`, e.g. `p10k color kubecontext`
- A prompt gets rendered, and `kubecontext` becomes always visible
- `kubecontext` segment is rendered with some color, e.g. `POWERLEVEL9K_KUBECONTEXT_FOREGROUND=123`, and somewhere I can see a current color value (`123` in this case)
- Now I can press `<Left>` or `<Right>` and it will increment or decrement the color in a range between `0` and `255` and re-render the prompt in place
- Once I'm satisfied with the color, I take a note of the current color value, press `q` to exit color picker and go update my `.p10k.zsh`

This obviously works only for 256 palette. 

What do you think?

**Comment by romkatv** [comment]
> when you pick a color, it still looks differently on an actual segment, so you jump back and forth between configuration and prompt while trying neighboring colors to see which one looks best.

How about this?

```zsh
() {
  local color
  for color in {1..7}; do
    sleep 1
    print -r -- "color $color" >$TTY
    print -r -- "POWERLEVEL9K_TIME_FOREGROUND=$color; p10k reload"
  done
} | zsh -is
```

Advantages:

- Not limited to 256 colors.
- Can try combinations of background and foreground color.
- Can try combinations of multiple colors, such as default, anchor and shortened colors for `dir`.
- Can try combinations of icons and colors or pretty much anything.

You can also turn it into an interactive script you've described earlier.

```zsh
() {
  local -i color=7
  local key
  while true; do
    print -r -- "color $color"
    print -r -- "POWERLEVEL9K_TIME_FOREGROUND=$color; p10k reload" |
      zsh -is 2>&1 | tail -2
    print
    while true; do
      read -k key'?Choice [jkq]: ' || return
      print
      case $key in
        j) color='(color + 255) % 256'; break;;
        k) color='(color +   1) % 256'; break;;
        q) return;;
      esac
    done
  done
}
```

Press <kbd>j</kbd>/<kbd>k</kbd> to decrease/increase color number. Press <kbd>q</kbd> to quit. Once again, you have freedom to decide which combinations you want to explore. For example, you can easily extend this script to allow you to change background and foreground color independently.

**Comment by maximbaz** [comment]
Thank you very much, I like these scripts, and I agree with you that the power lies in extending these scripts to combinations that a given person wants to try, it's not something generic that can or needs to be part of `p10k` subcommand. 

I would suggest to put such a script in a more discoverable place (in README perhaps?), something that will give users a boilerplate script to try several combinations, a starting point that they can build upon.

**Comment by romkatv** [comment]
I've added license info to my previous comment. Feel free to use the code and/or distribute it.

I won't be adding it to Powerlevel10k at this point. I'm not sure it'll be helpful to more than a handful of users. At the same time, I'd like to avoid documentation bloat (it's already so large that no one reads it) and spare me the burden of fielding user support requests.
