### ISSUE TITLE
problem with suckless terminal st _prompt_segment issue

### ISSUE THREAD

**Issue by jasonstone20** [romkatv/powerlevel10k#872]
I get this message after running the p10k configure command and completing set up:
prompt_status:29: command not found: _prompt_segment
prompt_background_jobs:11: command not found: _prompt_segment
prompt_context:33: command not found: _prompt_segment
prompt_time:3: command not found: _prompt_segment
prompt_dir:245: command not found: _prompt_segment

**Comment by romkatv** [comment]
It looks like you are trying to load several themes at once. You can only use one Zsh theme at a time.

**Comment by jasonstone20** [comment]
Yes, awesome, thank you for responding so quick.  That was the issue, I had some extra prompt commands in my .zshrc.  I have it working now.  Thank you for the awesome theme!

**Comment by romkatv** [comment]
Great!
