### ISSUE TITLE
Improper configuration of powerlevel10k.

### ISSUE THREAD

**Issue by priyanshu219** [romkatv/powerlevel10k#873]
Recently I install powerlevel10k, but it behaves differently on my system
Please have a look
![Screenshot from 2020-07-09 14-35-42](https://user-images.githubusercontent.com/44081226/87020585-abb0ef00-c1f1-11ea-8e64-5848197c9f9e.png)

**Comment by romkatv** [comment]
What is unexpected to you in the provided screenshot?

**Comment by priyanshu219** [comment]
@romkatv I want a triangular figure instead of square ones

**Comment by priyanshu219** [comment]
Currently, I am using ubuntu 20.04

**Comment by romkatv** [comment]
Then you need to configure your terminal to use a font that has these symbols. Powerlevel10k can only display symbols that your terminal can display. See https://github.com/romkatv/powerlevel10k/#meslo-nerd-font-patched-for-powerlevel10k.

**Comment by priyanshu219** [comment]
@romkatv I installed meslo-nf- regular but still it doesn't recognise **diamond**, and figures overlap with cross
also same square is coming, instead of the triangle

**Comment by romkatv** [comment]
Please click the link I posted above and do exactly what it says.

**Comment by priyanshu219** [comment]
I **followed** all steps as mentioned for both **Terminator** and **Gnome Terminal**
But the same result i.e. **Diamond** not recognised, crosses overlap with images etc.

**Comment by priyanshu219** [comment]
If you need more information please **Let me know**

**Comment by romkatv** [comment]
You need to find a way to change your terminal's font. If following the instructions on the Powerlevel10k site doesn't help, search for other instructions. E.g., try the official GNOME Terminal documentation: https://help.gnome.org/users/gnome-terminal/stable/app-fonts.html.en. Or google it: https://www.google.com/search?q=how+to+change+font+in+gnome+terminal.
