### ISSUE TITLE
`p10k configure` doesnt ask about instant prompt, manually adding the code does not work either

### ISSUE THREAD

**Issue by ReagentX** [romkatv/powerlevel10k#874]
This is at the top of my `.zshrc`:

    # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
    # Initialization code that may require console input (password prompts, [y/n]
    # confirmations, etc.) must go above this block; everything else may go below.
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
      source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi

And this is in my `.p10k.zsh`:

    typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose

Are there any other config steps I need to take? There aren't any listed in the docs. As far as I can tell, the `source` line inside of the `if` block does not get executed.

The prompt loads like I don't have p10k installed, setting up pyenv and nvm before allowing me to type.

**Comment by romkatv** [comment]
Instant prompt requires zsh >= 5.4. You can see yours with `echo $ZSH_VERSION`.

**Comment by ReagentX** [comment]
❯ echo $ZSH_VERSION
    5.8

**Comment by romkatv** [comment]
What does this print?

```zsh
( set -x; is-at-least 5.4; ret=$?; )
```

**Comment by ReagentX** [comment]
❯ ( set -x; is-at-least 5.4; ret=$?; ) 
    +-zsh:1> is-at-least 5.4
    +is-at-least:23> emulate -L zsh
    +is-at-least:25> local IFS=.- min_cnt=0 ver_cnt=0 part min_ver version order
    +is-at-least:27> min_ver=( 5 4 )
    +is-at-least:28> version=( 5 3 0 )
    +is-at-least:30> ((  0 <= 2  ))
    +is-at-least:31> [[ '' != <-> ]]
    +is-at-least:32> ((  ++ver_cnt > 3  ))
    +is-at-least:33> [[ 5 = *[0-9][^0-9]* ]]
    +is-at-least:45> part=5
    +is-at-least:31> [[ 5 != <-> ]]
    +is-at-least:48> true
    +is-at-least:49> ((  ++min_cnt > 2  ))
    +is-at-least:50> [[ 5 = <-> ]]
    +is-at-least:50> break
    +is-at-least:53> ((  part > min_ver[min_cnt]  ))
    +is-at-least:54> ((  part < min_ver[min_cnt]  ))
    +is-at-least:55> part=''
    +is-at-least:30> ((  1 <= 2  ))
    +is-at-least:31> [[ '' != <-> ]]
    +is-at-least:32> ((  ++ver_cnt > 3  ))
    +is-at-least:33> [[ 3 = *[0-9][^0-9]* ]]
    +is-at-least:45> part=3
    +is-at-least:31> [[ 3 != <-> ]]
    +is-at-least:48> true
    +is-at-least:49> ((  ++min_cnt > 2  ))
    +is-at-least:50> [[ 4 = <-> ]]
    +is-at-least:50> break
    +is-at-least:53> ((  part > min_ver[min_cnt]  ))
    +is-at-least:54> ((  part < min_ver[min_cnt]  ))
    +is-at-least:54> return 1
    +-zsh:1> ret=1
    ❯ zsh --version
    zsh 5.8 (x86_64-apple-darwin18.7.0)

**Comment by romkatv** [comment]
You have versions of zsh installed and you are using the old one.

Have you lied on the previous comment?

**Comment by ReagentX** [comment]
❯ echo $ZSH_VERSION
    5.8
    ❯ zsh --version
    zsh 5.8 (x86_64-apple-darwin18.7.0)

**Comment by romkatv** [comment]
You might want to run this: `chsh -s /usr/local/bin/zsh`

If it says it’s not a valid shell, add it to `/etc/shells`

**Comment by romkatv** [comment]
> ❯ ( set -x; is-at-least 5.4; ret=$?; ) 
> +-zsh:1> is-at-least 5.4
> +is-at-least:23> emulate -L zsh
> +is-at-least:25> local IFS=.- min_cnt=0 ver_cnt=0 part min_ver version order
> +is-at-least:27> min_ver=( 5 4 )
> +is-at-least:28> version=( 5 3 0 )

It’s 5.3. That’s the version of your shell.

**Comment by ReagentX** [comment]
See my edited comment, I only have one zsh installed and it's version 5.8 (from `brew`).

**Comment by romkatv** [comment]
> ❯ echo $ZSH_VERSION
> 5.8

Type the same is-at-least command in **this** shell.

**Comment by romkatv** [comment]
> See my edited comment, I only have one zsh installed and it's version 5.8 (from `brew`).

The output of is-at-least says you have two.

**Comment by ReagentX** [comment]
![image](https://user-images.githubusercontent.com/1920666/87053133-97f49100-c1cf-11ea-9a78-99ad393c7379.png)

**Comment by romkatv** [comment]
Sounds like you have found a bug in zsh from brew. I suggest you report it.

**Comment by romkatv** [comment]
Just to clarify, according to you, `is-at-least 5.4` fails in zsh from homebrew. That, if true, would definitely be a bug.

**Comment by ReagentX** [comment]
❯ brew info zsh
    zsh: stable 5.8 (bottled), HEAD
    ...

Fair enough, thanks for the help!

**Comment by romkatv** [comment]
By the way, I’m virtually certain you have two versions of zsh installed. This theory is consistent with all screenshots and command outputs you have posted. You’ve posted some from zsh 5.3 and others from zsh 5.8. The most interesting thing would be to run both commands I’ve asked you to run from the same shell. All commands that you’ve run are not relevant here (e.g. `zsh --version`).
