### ISSUE TITLE
Inconsistent transient prompt

### ISSUE THREAD

**Issue by BLucky-gh** [romkatv/powerlevel10k#875]
Oftentimes the transient prompt doesn't kick in and I still see the usual prompt after running something. If the transient prompt disappears it doesn't reappear until I restart the shell or re-source `.zshrc`, though restarting the shell doesn't always fix the issue.

**Comment by romkatv** [comment]
> Oftentimes the transient prompt doesn't kick in and I still see the usual prompt after running something.

Please provide instructions to reproduce.

> If the transient prompt disappears it doesn't reappear until I restart the shell or re-source `.zshrc`, though restarting the shell doesn't always fix the issue.

You must never, ever run `source ~/.zshrc`. This command means "I would like something random to happen, I don't care what exactly". If you want to reinitialize zsh after making changes to configuration files, use `exec zsh`. It's even easier to type.

**Comment by BLucky-gh** [comment]
> Please provide instructions to reproduce
It happens randomly so I couldn't find a correlation with anything, but now that you said that source .zshrc can and will lead to issues I will check if that happens to be the entire issue and reply here again.

**Comment by BLucky-gh** [comment]
Yeah turns out the issue was due to ``source .zshrc`. thanks for helping me out
