### ISSUE TITLE
Battery section do not work correctly

### ISSUE THREAD

**Issue by PoMkaNik** [romkatv/powerlevel10k#88]
With 9k:
![image](https://user-images.githubusercontent.com/11088944/59551341-4fee4500-8fa2-11e9-898a-6e5a3981b204.png)

With 10k:
![image](https://user-images.githubusercontent.com/11088944/59551356-701e0400-8fa2-11e9-9341-6d06d5bbbbb9.png)
Config:
`## Powerlevel9k settings
#POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(battery date time newline dir dir_writable vcs newline context root_indicator status)
POWERLEVEL9K_DISABLE_RPROMPT=true
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_TIME_BACKGROUND='118'
POWERLEVEL9K_DATE_BACKGROUND='028'
POWERLEVEL9K_DIR_HOME_BACKGROUND='012'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='012'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='012'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='028'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='162'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='165'
POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(darkred orange4 yellow4 yellow4 chartreuse3 grse3 green3 green4 darkgreen)
POWERLEVEL9K_STATUS_OK_BACKGROUND='046'
POWERLEVEL9K_STATUS_OK_FOREGROUND='007'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='028'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='013'
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='007'

#POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD=50
POWERLEVEL9K_STATUS_OK=true
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_BATTERY_VERBOSE=true`

**Comment by romkatv** [comment]
Thanks for the report. Should be fixed now. Please update and let me know if it works as expected.

**Comment by PoMkaNik** [comment]
I guess, that the real problem not in colors.
I have updated but really nothing changed.
In screenshot below I've switched off the following setting:
`#POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(darkred orange4 yellow4 yellow4 chartreuse3 green3 green4 darkgreen)`
to show that no any battery % presented.
![image](https://user-images.githubusercontent.com/11088944/59561181-5edb0300-9047-11e9-8681-c16860960429.png)

**Comment by romkatv** [comment]
What is your OS?

If it's OSX, please post the complete output of `pmset -g batt`.

**Comment by PoMkaNik** [comment]
Windows 10 with bash installed

**Comment by romkatv** [comment]
Do you mean WSL?

Please post the output of the following command:

```zsh
() {
  emulate -L zsh && setopt xtrace null_glob
  echo $OS
  uname
  uname -o
  uname -a
  ls /sys/class/power_supply/(BAT*|battery)/
  cat /dev/null /sys/class/power_supply/(BAT*|battery)/(energy|charge)_now
  cat /dev/null /sys/class/power_supply/(BAT*|battery)/(energy|charge)_full
  cat /dev/null /sys/class/power_supply/(BAT*|battery)/(power|current)_now
  cat /dev/null /sys/class/power_supply/(BAT*|battery)/status
  cat /dev/null /sys/class/power_supply/(BAT*|battery)/capacity
}
```

**Comment by PoMkaNik** [comment]
WSL - yes.

`+(anon):2> echo Linux
Linux
+(anon):3> uname
Linux
+(anon):4> uname -o
GNU/Linux
+(anon):5> uname -a
Linux X1-Extreme 4.4.0-17134-Microsoft #706-Microsoft Mon Apr 01 18:13:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
+(anon):6> ls '--color=tty' /sys/class/power_supply/battery/
capacity  charge_counter  current_now  health  present  status  technology  temp  type  voltage_now
+(anon):7> cat /dev/null
+(anon):8> cat /dev/null
+(anon):9> cat /dev/null /sys/class/power_supply/battery/current_now
3185
+(anon):10> cat /dev/null /sys/class/power_supply/battery/status
Charging
+(anon):11> cat /dev/null /sys/class/power_supply/battery/capacity
73`

**Comment by romkatv** [comment]
Thank you. I didn't know WSL provided battery status. Apparently it does but in a different format than on Linux. I added WSL support. Please update and give it a try.

**Comment by PoMkaNik** [comment]
Great!
Thank you for support and quick fix.
A little bit different remaining time...will see who is more precise :)
![image](https://user-images.githubusercontent.com/11088944/59562420-b46adc00-9056-11e9-85a6-0684d3c3061f.png)
