### ISSUE TITLE
Incorrect IP address shown

### ISSUE THREAD

**Issue by wb9688** [romkatv/powerlevel10k#883]
Powerlevel10k shows `127.0.0.1` as my IP address, which is obviously incorrect. Powerlevel9k correctly shows `192.168.1.16` as my IP address.

**Comment by romkatv** [comment]
Add this to your config:

```zsh
# Regular expression for the network interface name from which LAN IP is extracted.
# Type `ifconfig || ip -4 a show` to see all available network interfaces.
typeset -g POWERLEVEL9K_IP_INTERFACE='e.*'
```

The default value of `POWERLEVEL9K_IP_INTERFACE` is `.*`, which matches all network interfaces, so you see the IP from a random network interface. It could be loopback (in your case it is), LAN, VPN or WAN. Definitely not what you want.

Note that in powerlevel10k you can also configure the format of `ip` segment. Try adding this parameter:

```zsh
# The following parameters are accessible within the expansion:
#
#   Parameter             | Meaning
#   ----------------------+---------------
#   P9K_IP_IP         | IP address
#   P9K_IP_INTERFACE  | network interface
#   P9K_IP_RX_BYTES   | total number of bytes received
#   P9K_IP_TX_BYTES   | total number of bytes sent
#   P9K_IP_RX_RATE    | receive rate (since last prompt)
#   P9K_IP_TX_RATE    | send rate (since last prompt)
typeset -g POWERLEVEL9K_IP_CONTENT_EXPANSION='${P9K_IP_RX_RATE:+⇣$P9K_IP_RX_RATE }${P9K_IP_TX_RATE:+⇡$P9K_IP_TX_RATE }$P9K_IP_IP'
```

P.S.

You might also want to run `p10k configure`.

**Comment by wb9688** [comment]
Why is that difference not mentioned at https://github.com/romkatv/powerlevel10k#does-powerlevel10k-always-render-exactly-the-same-prompt-as-powerlevel9k-given-the-same-config then?

**Comment by romkatv** [comment]
You get a random network interface in p9k, and you get a random network interface in p10k. There is no difference in high-level behavior. The RNG ends up giving you different network interfaces.

**Comment by wb9688** [comment]
No, it has nothing to do with a RNG. P9k executes `/sbin/ip -brief -4 a show`, and gets the first line that contains `UP`. P10k executes `ip -4 a show` and gets the first line that contains `UP`, however the output of that command is of course different:

```
$ /sbin/ip -brief -4 a show
lo               UNKNOWN        127.0.0.1/8 
enp7s0           UP             192.168.1.16/24 
br-2265b2cef022  DOWN           172.20.0.1/16 
br-40581c168bd7  UP             172.18.0.1/16 
br-8bc39bef6dd3  UP             172.19.0.1/16 
docker0          DOWN           172.17.0.1/16 
br-a643026a6e8f  UP             172.22.0.1/16 
virbr0           DOWN           192.168.122.1/24
$ ip -4 a show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.1.16/24 brd 192.168.1.255 scope global dynamic enp7s0
       valid_lft 80292sec preferred_lft 80292sec
3: br-2265b2cef022: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    inet 172.20.0.1/16 brd 172.20.255.255 scope global br-2265b2cef022
       valid_lft forever preferred_lft forever
4: br-40581c168bd7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-40581c168bd7
       valid_lft forever preferred_lft forever
5: br-8bc39bef6dd3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.19.0.1/16 brd 172.19.255.255 scope global br-8bc39bef6dd3
       valid_lft forever preferred_lft forever
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
7: br-a643026a6e8f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    inet 172.22.0.1/16 brd 172.22.255.255 scope global br-a643026a6e8f
       valid_lft forever preferred_lft forever
18: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
```

**Comment by romkatv** [comment]
Ok.

**Comment by romkatv** [comment]
There is some extra details in https://github.com/romkatv/powerlevel10k/issues/305#issuecomment-552113108.

To summarize:

1.  p9k has a bug in the detection of network interface state. On your machine it mistakenly things that `lo` is down when it's actually up, so it effectively removes `lo` from the set of interfaces it can display.
2. If several network interfaces match `POWERLEVEL9K_IP_INTERFACE` regular expression, you'll see the IP from an unspecified interface in both p9k and p10k. (I've used the word "random" in the same sense as "unspecified" in my previous comments.)

In p10k there is an extra parameter called `POWERLEVEL9K_VPN_IP_SHOW_ALL`. If you set it to true, you'll see IPs of all network interfaces matching the regex.
