### ISSUE TITLE
history line no longer in prompt as 9k?

### ISSUE THREAD

**Issue by rogermanich** [romkatv/powerlevel10k#884]
Hi,
I recently update from powerlevel9k to 10k. What I miss is the history line in the right hand as powerlevel9k. Can I add it? is it a bug? I cannot find it the documentation. Sorry if it is not a bug.

![image](https://user-images.githubusercontent.com/3322032/87273291-fe7ff480-c4d8-11ea-9b8a-1ffa6bf24934.png)

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and add `history` to `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`:

```zsh
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  ...
  history
  ...
)
```

Optionally, customize history colors by adding these parameters and changing their values as you like:

```zsh
typeset -g POWERLEVEL9K_DIR_FOREGROUND=grey
typeset -g POWERLEVEL9K_DIR_BACKGROUND=black
```

**Comment by rogermanich** [comment]
ok, not it works. thank you
