### ISSUE TITLE
Allow external configure variables

### ISSUE THREAD

**Issue by SleepyBag** [romkatv/powerlevel10k#885]
I often jump between several machines which share zshrc file by git.
I use different themes for each machine, so p10k.zsh is not managed by git.
But at the same time, I want to make some common configuration for p10k, such as icons.
So I define some variables in my zshrc before `source ~/.p10k.zsh`. But they only work after I delete this line in .p10k.zsh:

```
unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'
```

But I don't exactly know what's the point of this line of code. Why don't allow configure variables from files outside of p10k.zsh? Or why isn't there a tweak for that in p10k wizard? I think that would be more convenient.

**Comment by romkatv** [comment]
> I often jump between several machines which share zshrc file by git.
> I use different themes for each machine, so p10k.zsh is not managed by git.

It's a very good idea to store p10k config together with .zshrc. You can load them conditionally depending on the machine. E.g., depending on the OS:

```zsh
if [[ $OSTYPE == linux* ]]; then
  source ~/.p10k-linux.zsh
else
  ...
fi
```

Or depending on hostname:

```zsh
if [[ ${(%):-%m} == myhostname ]]; then
  source ~/.p10k-myhostname.zsh
else
  ...
fi
```

> So I define some variables in my zshrc before `source ~/.p10k.zsh`.

Why not after?

> But I don't exactly know what's the point of this line of code.

There is a comment above it that explains it.

> why isn't there a tweak for that in p10k wizard?

It's infeasible to provide include every considerable option in the configuration wizard. The wizard is meant to generate a sensible config as a starting point, which you can then edit to your desire.

**Comment by SleepyBag** [comment]
Blonde moment there. I didn't realize that I can put configuration after source .p10k.zsh. Thank you very much!
