### ISSUE TITLE
Github icon not showing in branch other than master

### ISSUE THREAD

**Issue by diazgilberto** [romkatv/powerlevel10k#886]
After `git checkout <branch>` other than master, the github icon doesn't show, instead the `git` word that shows when initially `giti init` a directory.

![Screen Shot 2020-07-13 at 4 15 05 PM](https://user-images.githubusercontent.com/9165819/87354386-1b8de500-c524-11ea-90d3-8728db61306f.png)

![Screen Shot 2020-07-13 at 4 15 16 PM](https://user-images.githubusercontent.com/9165819/87354406-20eb2f80-c524-11ea-8127-007e38168ede.png)

**Comment by romkatv** [comment]
The GitHub logo indicates that `git pull` and `git push` would interact with github.com. If you run these commands in `dev` branch, they'll simply fail.

**Comment by diazgilberto** [comment]
Shouldn't always be there to indicate that local repo is linked with a GitHub repo regardless of the commands you run. I think that should be the expected behavior of the icon. If not, What is the expected behavior?

**Comment by romkatv** [comment]
> Shouldn't always be there to indicate that local repo is linked with a GitHub repo regardless of the commands you run.

But there is no such thing in git.

**Comment by romkatv** [comment]
What I mean is that your local repo is *not* linked with a GitHub repo because git doesn't have a concept of linked repos.

**Comment by diazgilberto** [comment]
```
$ mkdir test
$ cd test/
$ touch README.md
$ git init
$ git add .
$ git commit -m 'initial commit'
$ git info

commit de3ebc57155fd4f975f7a2fb136827bc59dbc66d
Author: Gilberto Diaz <diaz.gilberto@gmail.com>

    initial commit

Type 'git log' for more commits, or 'git show <commit id>' for full commit details.

## Configuration (.git/config):

credential.helper=osxkeychain
user.name=My Name
user.email=my-email@gmail.com
filesystem.Oracle Corporation|13.0.1|/dev/disk1s1.timestampresolution=8000 nanoseconds
filesystem.Oracle Corporation|13.0.1|/dev/disk1s1.minracythreshold=0 nanoseconds
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
```
☝️ notice that there is no `remote.origin.url=git@github.com:<org>/<repo-name>.git`. Now go to a project that is on GitHub.
```
$ cd repo/that/is/on/github
$ git info
## Configuration (.git/config):

credential.helper=osxkeychain
user.name=My Name
user.email=my-email@gmail.com
filesystem.Oracle Corporation|13.0.1|/dev/disk1s1.timestampresolution=8000 nanoseconds
filesystem.Oracle Corporation|13.0.1|/dev/disk1s1.minracythreshold=0 nanoseconds
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=git@github.com:<org-name>/<repo-name>.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```
☝️ notice the `remote.origin.url=git@github.com:<org-name>/<repo-name>.git`

**Comment by romkatv** [comment]
I'm not sure what you are getting at. I know that repositories and branches can have any number of remotes.

**Comment by diazgilberto** [comment]
I think that the expected behavior for the Github icon is to show if the local repo is linked with a Github repo regardless if one change branch. 

Given a local repo is linked with a GitHub repo:
* If I'm on master show GitHub icon
* If I'm on a different branch other than master show GitHub icon

**Comment by romkatv** [comment]
> I think that the expected behavior for the Github icon is to show if the local repo is linked with a Github repo regardless if one change branch.

This is incorrect. What you describe doesn't make sense because there is no such thing as the local repo being linked with a GitHub repo.

Repos can have remotes (any number, not necessarily one) and branches can have tracking information. If your current branch is tracking a remote on github.com, you get GitHub logo. If it doesn't, you don't get the GitHub logo. Whether you see or don't see the GitHub logo gives you useful information. If there is GitHub logo, you know you can `git push` and `git pull` and it'll result in communication with github.com.

**Comment by diazgilberto** [comment]
🤔 what you are saying makes me think that something is wrong with my repo. The 1st post that started this thread is showing an actual repo that is on development for quick sometime now.  The `dev` branch has been there since the beginning of the project and we `push` and `pull` from that `dev` branch. What it is about that `dev` branch that supposedly is not tracking a remote on GitHub when actually it does track a GitHub remote?

**Comment by z0rc** [comment]
In all fairness it's better to consult with `git config push.default`, as majority of user configurations are done in way where push goes to remote `origin`.

**Comment by diazgilberto** [comment]
> In all fairness it's better to consult with `git config push.default`, as majority of user configurations are done in way where push goes to remote `origin` without need to specify repository and refspec.

95% of the time is done this way.

**Comment by romkatv** [comment]
> 🤔 what you are saying makes me think that something is wrong with my repo. The 1st post that started this thread is showing an actual repo that is on development for quick sometime now. The `dev` branch has been there since the beginning of the project and we `push` and `pull` from that `dev` branch.

What is the output of `git pull` when prompt shows `dev` branch without GitHub logo?

**Comment by diazgilberto** [comment]
😮 
```
$ git pull
warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> dev
```

**Comment by romkatv** [comment]
Powerlevel10k is working as expected. You might want to set tracking info:

```zsh
git branch --set-upstream-to=origin/dev
```

**Comment by romkatv** [comment]
That command only affects your local repo, so don’t worry about breaking anything.
