### ISSUE TITLE
When transient prompt enabled, % (percent) symbol appears in upper left corner of small terminals

### ISSUE THREAD

**Issue by kylebarbour** [romkatv/powerlevel10k#887]
When I open small windows, a black-on-white percent symbol (see below) appears in the upper left corner. This occurs with a minimal `.zshrc` that only sources `p10k` and a `.p10k.zsh` generated by the `p10k configure` wizard. Transient prompt must be enabled; commenting it out in `.zshrc` or disabling `p10k` solves the problem. This occurs regardless of the verbosity set by `p10k configure`.

![Percent in corner](https://user-images.githubusercontent.com/4647176/87363005-353c2600-c53e-11ea-928f-8d8eca97226c.png)

I have been unable to replicate this in `urxvt` but it does occur in `termite`.

System:
```
$ uname -srv
Linux 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000
```

Window manager:
```
$ bspwm -v
0.9.7-10-g2ffd9c1
```

Terminal:
```
$ termite -v
termite v15
```

zsh:
```
$ zsh --version
zsh 5.8 (x86_64-pc-linux-gnu)
$ cat .zshrc
 Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```

Powerlevel10k:
```
$ yay -Qi zsh-theme-powerlevel10k | grep Version
Version         : 1.12.0-3
$ head -n 4 .p10k.zsh
# Generated by Powerlevel10k configuration wizard on 2020-07-13 at 17:41 EDT.
# Based on romkatv/powerlevel10k/config/p10k-lean.zsh, checksum 29130.
# Wizard options: nerdfont-complete + powerline, small icons, unicode, lean, 1 line,
# compact, few icons, concise, instant_prompt=off.
```

**Comment by romkatv** [comment]
Can you reproduce this issue with the following `~/.zshrc`?

```zsh
# This is the whole of ~/.zshrc.
RPS1='x'
# Nothing below this line.
```

**Comment by kylebarbour** [comment]
Yes, I can. I'm sorry, does that mean that this isn't a powerlevel10k issue?

**Comment by romkatv** [comment]
It's a terminal bug. It reports incorrect terminal dimensions for a short while after starting. You can see this with the following `~/.zshrc`:

```zsh
# This is the first line in ~/.zshrc.
typeset -p LINES COLUMNS
# You can put anything you want below this line.
```

You'll likely notice that it says the terminal is 80 columns wide even though it's not.

You can replace the `typeset` line with `stty size` and you'll get the same results. This shows that the issue is not in Zsh but in the terminal.

The bug might be coming from an old version of VTE that Termite is using. Skimming through the Termite documentation I see that it's using a very old fork of VTE. It's possible that updating that fork and rebuilding Termite will get rid of the bug.

**Comment by romkatv** [comment]
Just to clarify. You see that inverted `%` sign whenever zsh prompt appears very quickly after terminal starts (while termite is still lying about the dimensions). This will happen with any theme that gives you fast prompt on startup. Instant prompt in powerlevel10k does just that -- fast prompt on startup -- so you see the inverted `%`.

**Comment by kylebarbour** [comment]
Understood, thank you! Very much appreciate the help.
