### ISSUE TITLE
Help understanding the implementation of transient prompt

### ISSUE THREAD

**Issue by whodevil** [romkatv/powerlevel10k#888]
This is a really cool feature, and I'm trying to understand how it works under the hood so I can try to implement it in my shell. It seems like there is some combination of zle-line-finish, zle-line-init and precmd. Would you mind giving me the 10k foot view of how this is working?

It appears as though this commit is what implements this feature https://github.com/romkatv/powerlevel10k/commit/00c69d6bda183825376864b5ba40588bc84a85a8

I'm not familiar enough with this codebase to discern exactly how that is all fitting together. Thanks!

**Comment by romkatv** [comment]
You can get 90% of the transient prompt functionality with this simple code:

```zsh
set-long-prompt() { PROMPT='%~%# ' }
precmd_functions=(set-long-prompt)

set-short-prompt() {
  if [[ $PROMPT != '%# ' ]]; then
    PROMPT='%# '
    zle .reset-prompt
  fi
}

zle-line-finish() { set-short-prompt }
zle -N zle-line-finish

trap 'set-short-prompt; return 130' INT
```

Try opening `zsh -f` and simply pasting the code. This will fail in a few weird corner cases. Getting rid of those is really hard.

Here's an alternative and also quite simple implementation:

```zsh
zle-line-init() {
  emulate -L zsh

  [[ $CONTEXT == start ]] || return 0

  while true; do
    zle .recursive-edit
    local -i ret=$?
    [[ $ret == 0 && $KEYS == $'\4' ]] || break
    [[ -o ignore_eof ]] || exit 0
  done

  local saved_prompt=$PROMPT
  local saved_rprompt=$RPROMPT
  PROMPT='%# '
  RPROMPT=''
  zle .reset-prompt
  PROMPT=$saved_prompt
  RPROMPT=$saved_rprompt

  if (( ret )); then
    zle .send-break
  else
    zle .accept-line
  fi
  return ret
}

zle -N zle-line-init
```

This implementation has different corner cases.

You can find extra details here:

- https://www.zsh.org/mla/workers/2019/msg00944.html
- https://www.zsh.org/mla/users/2019/msg00633.html
- https://github.com/romkatv/powerlevel10k/issues/321

**Comment by whodevil** [comment]
Thank you so much for this!

**Comment by faaizajaz** [comment]
@romkatv Thanks for this. Your first implementation works for me, but it seems to break zsh autocompletions. Any ideas?

**Comment by romkatv** [comment]
@faaizajaz The working implementation can be found in powerlevel10k. It's very complex. All short implementations posted here are broken in some way or another.

**Comment by faaizajaz** [comment]
> @faaizajaz The working implementation can be found in powerlevel10k. It's very complex. All short implementations posted here are broken in one way or another.

That's what I thought, powerlevel10k is so much more complex than I realized--a really impressive piece of work. I guess I will need to commit some time to building my own p10k theme to use that implementation. Thanks for your help.
