### ISSUE TITLE
Prompt does not change color anymore after changes in git

### ISSUE THREAD

**Issue by BenedictTest** [romkatv/powerlevel10k#889]
For some reason my prompt does not change color anymore when I change code or add new files to my git directory. Reinstalling or a fresh configuration did not change that behavior. 

Oh My Zsh with Agnoster Theme:
![image](https://user-images.githubusercontent.com/60546588/87393443-7c61ff80-c5ae-11ea-9e47-d5757a0957a7.png)

Powerlevel10k:
![image](https://user-images.githubusercontent.com/60546588/87393757-ebd7ef00-c5ae-11ea-96e4-3d878de41e7d.png)

**Comment by romkatv** [comment]
Powerlevel10k is not Agnoster, so it normal that it doesn't look exactly like Agnoster.

In the default config the presence of untracked files won't change the color from green to yellow, but the presence of staged or unstaged changes will. For example, if you modify an existing file tracked by your Git repository, prompt will turn yellow.

You can [customize this](https://github.com/romkatv/powerlevel10k/blob/master/README.md#how-do-i-change-the-format-of-git-status).

**Comment by BenedictTest** [comment]
Thanks for the fast answer! Could you explain to me how I would configure it to also make the color change from green to yellow while adding new files?

I had it figured out before but after setting it up on my new work machine it does not work anymore and I cant remember what I have done to make it work.

**Comment by romkatv** [comment]
> Could you explain to me how I would configure it to also make the color change from green to yellow while adding new files?

Have you clicked the link I've posted?

**Comment by romkatv** [comment]
Sorry, I think I've confused myself and you as well. To change the background you need to uncommend `POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND` in `~/.p10k.zsh` and set its value to `3` or `yellow`.

**Comment by BenedictTest** [comment]
Thank you very much. That was exactly what I was looking for. Couldn't figure it out my self.

Again, thanks for the fast help and this great tool. Really makes life easier while working.
