### ISSUE TITLE
Battery segment does not display

### ISSUE THREAD

**Issue by Who23** [romkatv/powerlevel10k#89]
The battery segment doesn't display in my prompt, even though it displays in powerlevel9k.

powerlevel9k
<img width="604" alt="powerlevel9k" src="https://user-images.githubusercontent.com/40632266/59646447-fe31f000-9144-11e9-9239-f9fc211c8f02.png">

powerlevel10k
<img width="598" alt="powerlevel10k" src="https://user-images.githubusercontent.com/40632266/59646449-02f6a400-9145-11e9-9da2-d0fcc7559a2d.png">

I'm on MacOS Mojave (10.12), using the iTerm 2 beta. However, the segment seems to be missing on Terminal.app and Hyper.js as well.

My [.zshrc](https://gist.github.com/Who23/e90222838a32395f30abd3d945b6face)

**Comment by romkatv** [comment]
Thanks for the bug report. This issue should be fixed now. Please update powerlevel10k and let me know whether it works for you.

**Comment by Who23** [comment]
Yup it's working! Thanks for the quick fix and thanks for making such a fast prompt :)

**Comment by romkatv** [comment]
Thanks for the confirmation!

**Comment by extremepayne** [comment]
I'm having the exact same problem, same OS, terminal, everything. How exactly does one update powerlevel10k?

**Comment by romkatv** [comment]
@extremepayne If you've installed powerlevel10k by cloning its git repository, you can `cd` into `powerlevel10k` and run `git pull` there. If you've powerlevel10k via some other distribution channel, you'll need to figure out how to pick up updates from that channel.

**Comment by extremepayne** [comment]
Yeah, prezto comes with it pre-installed

**Comment by romkatv** [comment]
I've sent https://github.com/sorin-ionescu/prezto/pull/1717 to update the powerlevel10k submodule commit hash in prezto.

If you know how to update git submodules, you can update to the last version yourself. If not, wait for the PR to get merged and then run `zprezto-update`.

**Comment by romkatv** [comment]
@extremepayne 

> I've sent sorin-ionescu/prezto#1717 to update the powerlevel10k submodule commit hash in prezto.

It's been merged. Run `zprezto-update` to pick it up.
