### ISSUE TITLE
Proxy Configuration or Running in Isolation

### ISSUE THREAD

**Issue by oldguardmd** [romkatv/powerlevel10k#891]
Is there a way to tell Powerlevel10K to use a proxy when fetching gitstatusd? I have tried setting a git proxy, but it doesn't seem to see or use it. 

Is there a way to tell Powerlevel10K to use the proxy, or a way to cancel the gitstatusd process in a way that isn't detrimental to the theme?

Ubuntu Version 1804 on Windows Subsystem for Linux
zsh version 5.4.2
git version 2.17.1

**Comment by romkatv** [comment]
gitstatusd is downloaded with curl from https://github.com/romkatv/gitstatus/releases. `curl` respects `HTTPS_PROXY` environment variable, so you can set that. You can also specify proxy in `~/.curlrc`.
