### ISSUE TITLE
Instant prompt is not working

### ISSUE THREAD

**Issue by vaibhavsingh97** [romkatv/powerlevel10k#893]
As stated in the Readme
I added following code in the top of `~/.zshrc`, but still it's not working for me
```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
```

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
typeset -pm 'POWERLEVEL9K_INSTANT_PROMPT|ZSH_VERSION'
```

What do you mean by the following statement?

> not working for me

**Comment by vaibhavsingh97** [comment]
> typeset -pm 'POWERLEVEL9K_INSTANT_PROMPT|ZSH_VERSION'

The output was 5.3, and I got the issue, sorry for opening the issue without debugging it. I am closing this issue, as I upgraded to 5.8 and it's working fine.

For people who had faced same issue, below what I did
```sh
# check the zsh info
brew info zsh

# install zsh
brew install --without-etcdir zsh

# add shell path
sudo vim /etc/shells

# add the following line into the very end of the file(/etc/shells)
/usr/local/bin/zsh

# change default shell
chsh -s /usr/local/bin/zsh
```

**Comment by romkatv** [comment]
Thanks for the update. I’m glad it’s working for you now.

(For anyone looking at this in the future: Instant Prompt requires zsh >= 5.4. You can find of the version of your zsh with `echo $ZSH_VERSION`.)
