### ISSUE TITLE
 AWS_PROFILE don't display on my terminal

### ISSUE THREAD

**Issue by toxypapi** [romkatv/powerlevel10k#894]
When i move on powerlevel10k my AWS_PROFILE display
<img width="403" alt="Screenshot 2020-07-16 at 08 28 57" src="https://user-images.githubusercontent.com/9954759/87640309-6e42e900-c73e-11ea-99a7-fa48a955ca26.png">
 don't work (AWS: AWS_PROFILE)
Do you have any config for that?

**Comment by romkatv** [comment]
Please do the following:

1. Enable powerlevel10k and activate `reamsAdmin` AWS profile.
2. Run the following command and post its output (as text) to this issue.
```zsh
typeset -pm 'ZSH_VERSION|POWERLEVEL9K_*|_p9k_uname*|AWSUME_PROFILE|AWS_(VAULT|PROFILE|DEFAULT_PROFILE)'
```
3. Post a screenshot of your terminal. Make sure that prompt is visible on it.

**Comment by toxypapi** [comment]
typeset POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
typeset POWERLEVEL9K_ASDF_HASKELL_BACKGROUND=3
typeset POWERLEVEL9K_OS_ICON_FOREGROUND=232
typeset POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=3
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset POWERLEVEL9K_TIMEWARRIOR_CONTENT_EXPANSION='${P9K_CONTENT:0:24}${${P9K_CONTENT:24}:+…}'
typeset POWERLEVEL9K_IP_BACKGROUND=4
typeset POWERLEVEL9K_ASDF_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_BATTERY_VERBOSE=false
typeset POWERLEVEL9K_ASDF_RUBY_BACKGROUND=1
typeset POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL=true
typeset POWERLEVEL9K_PHP_VERSION_BACKGROUND=5
typeset POWERLEVEL9K_ASDF_NODEJS_BACKGROUND=2
typeset POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION=✘
typeset POWERLEVEL9K_NORDVPN_DISCONNECTING_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_CONTEXT_SUDO_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_DIR_MAX_LENGTH=80
typeset POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset -a POWERLEVEL9K_LUAENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_STATUS_ERROR=true
typeset POWERLEVEL9K_CONTEXT_BACKGROUND=0
typeset POWERLEVEL9K_NORDVPN_DISCONNECTED_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_ASDF_GOLANG_FOREGROUND=0
typeset POWERLEVEL9K_CONTEXT_SUDO_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset POWERLEVEL9K_CONTEXT_REMOTE_SUDO_TEMPLATE=%n@%m
typeset POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=%242F├─
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_CONTENT_EXPANSION=▶
typeset POWERLEVEL9K_CONTEXT_PREFIX='with '
typeset POWERLEVEL9K_OS_ICON_BACKGROUND=7
typeset POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_ASDF_LUA_BACKGROUND=4
typeset POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_DISABLE_HOT_RELOAD=true
typeset POWERLEVEL9K_DIR_HYPERLINK=false
typeset POWERLEVEL9K_VCS_STAGED_MAX_NUM=-1
typeset POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED=false
typeset POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1
typeset -a POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status command_execution_time background_jobs direnv node_version context nnn vim_shell midnight_commander nix_shell vi_mode load disk_usage ram time battery wifi )
typeset POWERLEVEL9K_GOENV_SHOW_SYSTEM=true
typeset -a POWERLEVEL9K_PLENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE=%n@%m
typeset POWERLEVEL9K_ASDF_PHP_FOREGROUND=0
typeset POWERLEVEL9K_ASDF_JAVA_FOREGROUND=1
typeset POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='took '
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=''
typeset POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND=1
typeset POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
typeset POWERLEVEL9K_ASDF_DOTNET_CORE_FOREGROUND=0
typeset POWERLEVEL9K_PYENV_CONTENT_EXPANSION='${P9K_CONTENT}${${P9K_PYENV_PYTHON_VERSION:#$P9K_CONTENT}:+ $P9K_PYENV_PYTHON_VERSION}'
typeset POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=3
typeset POWERLEVEL9K_NORDVPN_DISCONNECTING_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform|pulumi'
typeset POWERLEVEL9K_CONFIG_FILE=/Users/juniorkabore/.p10k.zsh
typeset POWERLEVEL9K_JAVA_VERSION_FULL=false
typeset -a POWERLEVEL9K_PHPENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_ASDF_GOLANG_BACKGROUND=4
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset POWERLEVEL9K_CONTEXT_TEMPLATE=%n@%m
typeset POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
typeset POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_IP_CONTENT_EXPANSION='${P9K_IP_RX_RATE:+⇣$P9K_IP_RX_RATE }${P9K_IP_TX_RATE:+⇡$P9K_IP_TX_RATE }$P9K_IP_IP'
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION=❯
typeset -a POWERLEVEL9K_GOENV_SOURCES=( shell local global )
typeset -a POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES=( '*' DEFAULT )
typeset POWERLEVEL9K_ASDF_PYTHON_FOREGROUND=0
typeset POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
typeset POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'
typeset ZSH_VERSION=5.7.1
typeset POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi'
typeset POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'
typeset POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
typeset POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
typeset POWERLEVEL9K_ASDF_PHP_BACKGROUND=5
typeset POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=''
typeset POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset POWERLEVEL9K_GCLOUD_COMPLETE_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_NAME//\%/%%}'
typeset -a POWERLEVEL9K_VCS_BACKENDS=( git )
typeset POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION='${${${${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-${CONDA_PREFIX:t}}'
typeset _p9k_uname=Darwin
typeset POWERLEVEL9K_CONTEXT_REMOTE_TEMPLATE=%n@%m
typeset POWERLEVEL9K_DIR_FOREGROUND=254
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
typeset POWERLEVEL9K_PHPENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito'
typeset POWERLEVEL9K_ASDF_FLUTTER_FOREGROUND=0
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=%242F─╮
typeset POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_ASDF_RUST_FOREGROUND=0
typeset POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION=''
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION=❮
typeset POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
typeset POWERLEVEL9K_SHORTEN_FOLDER_MARKER='(.bzr|.citc|.git|.hg|.node-version|.python-version|.go-version|.ruby-version|.lua-version|.java-version|.perl-version|.php-version|.tool-version|.shorten_folder_marker|.svn|.terraform|CVS|Cargo.toml|composer.json|go.mod|package.json|stack.yaml)'
typeset -a POWERLEVEL9K_NODENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_NORDVPN_CONNECTING_CONTENT_EXPANSION=''
typeset -a POWERLEVEL9K_RBENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=%242F─╯
typeset POWERLEVEL9K_BATTERY_LOW_FOREGROUND=1
typeset POWERLEVEL9K_ASDF_PYTHON_BACKGROUND=4
typeset POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
typeset POWERLEVEL9K_VCS_CONFLICTED_MAX_NUM=-1
typeset POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_STATUS_ERROR_PIPE=true
typeset POWERLEVEL9K_VIRTUALENV_RIGHT_DELIMITER=''
typeset POWERLEVEL9K_NODENV_SHOW_SYSTEM=true
typeset POWERLEVEL9K_VI_MODE_FOREGROUND=0
typeset POWERLEVEL9K_VCS_COMMITS_AHEAD_MAX_NUM=-1
typeset POWERLEVEL9K_ASDF_POSTGRES_FOREGROUND=0
typeset POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
typeset POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION=✘
typeset POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_ASDF_PERL_FOREGROUND=0
typeset POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=4
typeset POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
typeset POWERLEVEL9K_NODEENV_SHOW_NODE_VERSION=false
typeset POWERLEVEL9K_JENV_SHOW_SYSTEM=true
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_CONTENT_EXPANSION=▶
typeset POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=8
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=76
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT_EXPANSION=V
typeset POWERLEVEL9K_GCLOUD_PARTIAL_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_ID//\%/%%}'
typeset POWERLEVEL9K_ASDF_RUST_BACKGROUND=208
typeset POWERLEVEL9K_SHORTEN_DELIMITER=''
typeset POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_ASDF_JULIA_FOREGROUND=0
typeset POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
typeset POWERLEVEL9K_PLENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_DISK_USAGE_CRITICAL_LEVEL=95
typeset POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs'
typeset -a POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon dir vcs terraform aws aws_eb_env azure )
typeset POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
typeset POWERLEVEL9K_DISK_USAGE_ONLY_WARNING=false
typeset POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=0
typeset POWERLEVEL9K_RVM_SHOW_GEMSET=false
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset POWERLEVEL9K_NODEENV_LEFT_DELIMITER=''
typeset POWERLEVEL9K_NORDVPN_CONNECTING_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIOWR_FOREGROUND=76
typeset POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=7
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
typeset POWERLEVEL9K_VI_INSERT_MODE_STRING=''
typeset POWERLEVEL9K_STATUS_OK=true
typeset POWERLEVEL9K_ASDF_JAVA_BACKGROUND=7
typeset POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS=60
typeset POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=76
typeset POWERLEVEL9K_NORDVPN_DISCONNECTED_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset POWERLEVEL9K_LARAVEL_VERSION_BACKGROUND=7
typeset POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=''
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset POWERLEVEL9K_ASDF_PERL_BACKGROUND=4
typeset POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND=0
typeset POWERLEVEL9K_ASDF_DOTNET_CORE_BACKGROUND=5
typeset -a POWERLEVEL9K_ASDF_SOURCES=( shell local global )
typeset POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=0
typeset POWERLEVEL9K_IP_FOREGROUND=0
typeset POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=%242F╭─
typeset POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
typeset POWERLEVEL9K_PYENV_SHOW_SYSTEM=true
typeset POWERLEVEL9K_VIRTUALENV_LEFT_DELIMITER=''
typeset POWERLEVEL9K_HASKELL_STACK_ALWAYS_SHOW=true
typeset POWERLEVEL9K_ASDF_RUBY_FOREGROUND=0
typeset POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=OVERTYPE
typeset POWERLEVEL9K_GOOGLE_APP_CRED_SHOW_ON_COMMAND='terraform|pulumi'
typeset POWERLEVEL9K_VPN_IP_INTERFACE='(wg|(.*tun))[0-9]*'
typeset POWERLEVEL9K_NODEENV_RIGHT_DELIMITER=''
typeset POWERLEVEL9K_ASDF_ERLANG_FOREGROUND=0
typeset POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
typeset POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=%242F╰─
typeset POWERLEVEL9K_BATTERY_STAGES='\uf58d\uf579\uf57a\uf57b\uf57c\uf57d\uf57e\uf57f\uf580\uf581\uf578'
typeset POWERLEVEL9K_VCS_UNTRACKED_MAX_NUM=-1
typeset POWERLEVEL9K_PHPENV_SHOW_SYSTEM=true
typeset POWERLEVEL9K_STATUS_OK_PIPE=true
typeset POWERLEVEL9K_MODE=nerdfont-complete
typeset POWERLEVEL9K_KUBECONTEXT_PREFIX='at '
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
typeset POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND=3
typeset POWERLEVEL9K_LOAD_WHICH=5
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION=❮
typeset POWERLEVEL9K_TIME_PREFIX='at '
typeset POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
typeset POWERLEVEL9K_DIR_BACKGROUND=4
typeset POWERLEVEL9K_ICON_BEFORE_CONTENT=''
typeset POWERLEVEL9K_ASDF_FOREGROUND=0
typeset POWERLEVEL9K_ASDF_FLUTTER_BACKGROUND=4
typeset -a POWERLEVEL9K_JENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_CONTENT_EXPANSION='${P9K_GOOGLE_APP_CRED_PROJECT_ID//\%/%%}'
typeset POWERLEVEL9K_RVM_SHOW_PREFIX=false
typeset POWERLEVEL9K_ASDF_LUA_FOREGROUND=0
typeset POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND=2
typeset -a POWERLEVEL9K_PYENV_SOURCES=( shell local global )
typeset POWERLEVEL9K_LUAENV_SHOW_SYSTEM=true
typeset POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND=4
typeset POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
typeset POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
typeset POWERLEVEL9K_ASDF_ELIXIR_FOREGROUND=0
typeset -a POWERLEVEL9K_KUBECONTEXT_CLASSES=( '*' DEFAULT )
typeset POWERLEVEL9K_DISK_USAGE_WARNING_LEVEL=90
typeset POWERLEVEL9K_CONTEXT_DEFAULT_VISUAL_IDENTIFIER_EXPANSION=''
typeset POWERLEVEL9K_ASDF_ERLANG_BACKGROUND=1
typeset POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND=2
typeset POWERLEVEL9K_VCS_PREFIX='on '
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_LEFT_WHITESPACE=''
typeset POWERLEVEL9K_JAVA_VERSION_FOREGROUND=1
typeset POWERLEVEL9K_VI_VISUAL_MODE_STRING=VISUAL
typeset POWERLEVEL9K_ASDF_SHOW_ON_UPGLOB=''
typeset POWERLEVEL9K_VPN_IP_SHOW_ALL=false
typeset POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND=3
typeset POWERLEVEL9K_ASDF_SHOW_SYSTEM=true
export AWS_PROFILE=reamsAdmin
typeset POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false
typeset POWERLEVEL9K_RBENV_SHOW_SYSTEM=true
typeset POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
typeset POWERLEVEL9K_ASDF_POSTGRES_BACKGROUND=6
typeset POWERLEVEL9K_DIR_SHOW_WRITABLE=v2
typeset POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=0
typeset POWERLEVEL9K_INSTANT_PROMPT=off
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_CONTENT_EXPANSION=V
typeset POWERLEVEL9K_TRANSIENT_PROMPT=off
typeset POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=%242F─┤
typeset POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION=✔
typeset POWERLEVEL9K_ASDF_HASKELL_FOREGROUND=0
typeset POWERLEVEL9K_ASDF_BACKGROUND=7
typeset POWERLEVEL9K_ICON_PADDING=none
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND=196
typeset POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
typeset POWERLEVEL9K_ASDF_JULIA_BACKGROUND=2
typeset POWERLEVEL9K_VCS_UNSTAGED_MAX_NUM=-1
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
typeset -a POWERLEVEL9K_TERRAFORM_CLASSES=( '*' OTHER )
typeset POWERLEVEL9K_PROMPT_CHAR_LEFT_RIGHT_WHITESPACE=''
typeset POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION=✘
typeset POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
typeset POWERLEVEL9K_PHP_VERSION_FOREGROUND=0
typeset POWERLEVEL9K_ASDF_ELIXIR_BACKGROUND=5
typeset POWERLEVEL9K_ASDF_NODEJS_FOREGROUND=0
typeset POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION=❯
typeset POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
typeset POWERLEVEL9K_VCS_COMMITS_BEHIND_MAX_NUM=-1
typeset POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION=✔
typeset POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
typeset POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=5
typeset POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3
typeset POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VIOWR_FOREGROUND=196
typeset POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=2
typeset POWERLEVEL9K_JAVA_VERSION_BACKGROUND=7
typeset POWERLEVEL9K_IP_INTERFACE='e.*'
typeset POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
typeset POWERLEVEL9K_PLENV_SHOW_SYSTEM=true
typeset _p9k_uname_m=x86_64
typeset _p9k_uname_o=''
typeset -a POWERLEVEL9K_HASKELL_STACK_SOURCES=( shell local )
typeset POWERLEVEL9K_CONTEXT_FOREGROUND=3
typeset POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=196
typeset -a POWERLEVEL9K_AWS_CLASSES=( '*prod*' PROD '*test*' TEST '*' REAMS )
typeset POWERLEVEL9K_VI_COMMAND_MODE_STRING=NORMAL
typeset POWERLEVEL9K_STATUS_EXTENDED_STATES=true
typeset POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=false
typeset POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250

**Comment by romkatv** [comment]
Thanks for posting the output of the command.

> 3. Post a screenshot of your terminal. Make sure that prompt is visible on it.

Do this :point_up:, too, please. You can drag-and-drop files (such as screenshots) to the comment's edit box on this issue.

**Comment by toxypapi** [comment]
<img width="1641" alt="Screenshot 2020-07-16 at 09 09 41" src="https://user-images.githubusercontent.com/9954759/87644472-17401280-c744-11ea-9a28-9d1d6230c5e9.png">

**Comment by romkatv** [comment]
I think I know what the issue might be. Try typing `aws` without hitting <kbd>Enter</kbd>. Does the AWS profile appear in prompt then? If yes, see [Show on Command](https://github.com/romkatv/powerlevel10k/blob/master/README.md#show-on-command) and [FAQ](https://github.com/romkatv/powerlevel10k/blob/master/README.md#why-some-prompt-segments-appear-and-disappear-as-im-typing). If you are using command that respect `AWS_PROFILE` but are missing from `POWERLEVEL9K_AWS_SHOW_ON_COMMAND` (it's currently set to `aws|awless|terraform|pulumi`), you can add them in. If you want to always see AWS profile regardless of your current command line, remove `POWERLEVEL9K_AWS_SHOW_ON_COMMAND` from `~/.p10k.zsh`.

**Comment by toxypapi** [comment]
Yes when I write just AWS I see the profile

**Comment by romkatv** [comment]
You are very welcome.
