### ISSUE TITLE
How to enable "many icons" editing p10k ?

### ISSUE THREAD

**Issue by distante** [romkatv/powerlevel10k#897]
I am trying to test the icons option and I want to change it on the p10k file. I know I can trigger the wizard again but I would prefer to just change that setting instead of do all the wizard again.

That said, I can not figure out which config is the one related to the "many icons" settings.

Can you please point me to the correct direction?

Thanks !

**Comment by romkatv** [comment]
There is no individual option in `~/.p10k.zsh` that reflects few vs many icons choice from the wizard. To manually change your config to retroactively enable "many icons" option, apply the following edits to `~/.p10k.zsh`:

- Remove these parameters:
  - `POWERLEVEL9K_DIR_CLASSES`
  - `POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION`
  - `POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION`
  - `POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION`
- Uncomment `POWERLEVEL9K_VCS_BRANCH_ICON` and sets its value to what you see when you type `echo -E - ${(qq)icons[VCS_BRANCH_ICON]}`. For example, for me that would be:
```zsh
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
```
