### ISSUE TITLE
Artix Linux symbol is missing

### ISSUE THREAD

**Issue by GoDzM4TT3O** [romkatv/powerlevel10k#898]
Hello there!

I use Powerlevel10k on Arch Linux, as well as Artix Linux.

I noticed that I only have the Arch symbol (on Arch) but I only have the Tux symbol on Artix.

How can I add the custom symbol? If I can't, can you add it? Here's the Artix artwork (svg):

https://gitea.artixlinux.org/artix/artwork/src/branch/master/logo
https://gitea.artixlinux.org/artix/artwork/src/branch/master/logo/Signet_ColorFull.svg
https://gitea.artixlinux.org/artix/artwork/src/branch/master/logo/Signet_ColorSingle.svg
https://gitea.artixlinux.org/artix/artwork/src/branch/master/logo/Signet_Grayscale.svg

Here's an image for reference

![artixarch](https://user-images.githubusercontent.com/28765699/87853603-c0853500-c90b-11ea-8758-a5da297f5b16.png)

**Comment by romkatv** [comment]
> How can I add the custom symbol?

1. Update powerlevel10k to the latest version.
2. Add the following parameter to `~/.p10k.zsh`:
```zsh
typeset -g POWERLEVEL9K_LINUX_ARTIX_ICON='\uF17C'
```

`'\uF17C'` is the tux. Replace it with anything you want. Unless your font has a glyph for Artix Linux logo (none of the fonts I know of have it), you'll have to settle for something more mundane.
