### ISSUE TITLE
WSL terminal In VSCode "cursor comes down" error issue

### ISSUE THREAD

**Issue by wowgod9504** [romkatv/powerlevel10k#899]
I use wsl terminal In VSCode. but I have one error issue.
I don't want to two lines but it works. like below.
I'm not settings in configure two lines.
I think it's been pushed down a little.
So the cursor comes down.
it works normally in external terminal. but in vscode not works.
![3](https://user-images.githubusercontent.com/60169820/87856252-e4229c80-c958-11ea-8848-200a84c38985.PNG)

**Comment by romkatv** [comment]
Please file a bug against VSCode.

**Comment by wowgod9504** [comment]
> Please file a bug against VSCode.

okay, Thank you for your comment.
