### ISSUE TITLE
when using a Go prompt lib it breaks using this theme

### ISSUE THREAD

**Issue by deepu105** [romkatv/powerlevel10k#90]
I have GoLang CLI app which uses [this](https://github.com/AlecAivazis/survey) lib to show console prompts. When using the select type from this the command is interrupted and breaks with error
`Unexpected Escape Sequence: ['\x1b' 'O']`. This does not happen when using powerline9k theme. 

Also once I load powerline10k theme on a shell the broken behavior remains even if I switch back to powerline9k theme by sourcing it. Only if I launch a new shell with powerline9k by default it works again

**Comment by deepu105** [comment]
Let me know if I can provide any additional info to help. Unfortunately, I can't share the CLI app itself as its proprietary from my company

**Comment by romkatv** [comment]
Can you reproduce this problem when using any of the examples provided by https://github.com/AlecAivazis/survey/tree/master/examples?

**Comment by deepu105** [comment]
@romkatv yes I'm able to reproduce. Below is both powerline9k & powerline10k in action. The one below is powerline10 and gives an error when hitting down arrow to cycle through options

![image](https://user-images.githubusercontent.com/1107223/59756436-fcbe1000-9289-11e9-86b8-abcb6d32e63b.png)

**Comment by deepu105** [comment]
This is my `.zshrc` file https://gist.github.com/deepu105/9723cb70032eca98ff09d110369af67a

**Comment by romkatv** [comment]
I suspect this is the result of interaction between oh-my-zsh, zsh-syntax-highlighting and powerlevel10k. oh-my-zsh hooks `zle-line-finish` is a bad way, zsh-syntax-highlighting wraps the hook, and then powerlevel10k adds its own hook in a nice way (via `add-zle-hook-widget`), which inadvertently removes the existing hook from oh-my-zsh.

I've submitted a small change that should fix the problem if my theory is correct. Could you update powerlevel10k and try again?

**Comment by deepu105** [comment]
Awesome works fine. Thank you. That was super quick.
Great implementation btw

**Comment by romkatv** [comment]
Thanks for verifying!

Would you be open to suggestions on how you could get more out of your prompt?

I see that you are using `$` as your prompt symbol -- a popular choice among past Bash users. In Bash this symbol turns into `#` when you are root. Try typing `sudo bash` -- you'll see `#` where `$` normally goes. You can get the same behavior in ZSH. In addition, many users find it convenient to display their prompt symbol in green if the last command has succeeded and in red if it has failed. This way a single character encodes two bits of information. You can try this by setting the following parameter in your `~/.zshrc`. (I preserved the leading space the same way your current config has it.)

```zsh
# green on success, red on failure; '#' if root, '$' otherwise
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' %F{%(?.76.196)}%(#.#.$)%f '
```

If you are using nvm, you might find `nvm` prompt segment useful. Most users put it into `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`. It doesn't require any configuration. Unlike with p9k, enabling `nvm` won't make your p10k prompt slower (p10k is fast with any configuration).

If copy-pasting commands into your prompt is slow, add `DISABLE_MAGIC_FUNCTIONS=true` at the top of your `~/.zshrc`. This really should be the default in Oh-My-Zsh.

Add `ZSH_AUTOSUGGEST_MANUAL_REBIND=1` to your `~/.zshrc` to reduce your prompt latency by 10-15ms. No other side effects. This isn't the default only for historical reasons.

**Comment by deepu105** [comment]
Hey, @romkatv awesome tips man. Thank you. I'm gonna try it and also I'm gonna update my blog post to mention `powerlevel10k` https://dev.to/deepu105/my-beautiful-linux-development-environment-2afc

**Comment by romkatv** [comment]
That's a beautiful setup.

Oh, you are using k8s? `kubecontext` is another prompt segment that could be useful in right prompt. For best results you'll need to define extra options. Something like this, adjust to satisfy your needs:

```zsh
# Don't show trailing "/default" in kubecontext.
POWERLEVEL9K_KUBECONTEXT_SHOW_DEFAULT_NAMESPACE=false

# Use red background for k8s contexts containing "prod",
# green background for "testing" and yellow for everything else.
POWERLEVEL9K_KUBECONTEXT_CLASSES=(
    '*prod*'    PROD
    '*testing*' TESTING
    '*'         OTHER)

POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND=red
POWERLEVEL9K_KUBECONTEXT_TESTING_BACKGROUND=green
POWERLEVEL9K_KUBECONTEXT_OTHER_BACKGROUND=yellow
```

`kubecontext` exists in p9k, too, but almost no one is using it because it's excruciatingly slow and doesn't support styling options that depend on the context.

**Comment by deepu105** [comment]
I have tried the nvm, kubecontext elements before but I found them to be too cluttered for my taste. But thanks for the `DISABLE_MAGIC_FUNCTIONS` tip. copy pasting was kind of slow and was annoying me.
Btw, I tried `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' %F{%(?.76.196)}%(#.#.$)%f '` but didnt work for some reason

**Comment by romkatv** [comment]
> I have tried the nvm, kubecontext elements before but I found them to be too cluttered for my taste.

Indeed, there is only so much space in the prompt.

> Btw, I tried `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' %F{%(?.76.196)}%(#.#.$)%f '` but didnt work for some reason

Didn't work how? If I copy your config and replace the existing `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX` line with this one, it works for me. Prompt symbol becomes green `$`. If I type `false`, it turns red.

**Comment by deepu105** [comment]
For me there is no change in color, it stays white

**Comment by romkatv** [comment]
Perhaps you are modifying `POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX` within an interactive shell? You need to modify your `~/.zshrc` and then restart ZSH.

**Comment by deepu105** [comment]
Oh sorry my bad. I was sourcing the .zshrc, reloading shell works

**Comment by deepu105** [comment]
Thanks man.

**Comment by romkatv** [comment]
Sourcing `~/.zshrc` is unreliable. You can use `exec zsh` instead. This will reinitialize everything without forking a new process and without changing your directory.

**Comment by deepu105** [comment]
I have updated my blog. Thanks for the theme man. it's cool. Just out of curiosity, any particular reason you decided to reimplement instead of collaborating with powerlevel9k?

**Comment by romkatv** [comment]
> I have updated my blog. 

Thanks :-)

> Just out of curiosity, any particular reason you decided to reimplement instead of collaborating with powerlevel9k?

Tried it at first, didn't work out. Large performance improvements and fixes for longstanding difficult bugs require ambitious changes that are beyond what p9k dev team can absorb. The [last commit](https://github.com/bhilburn/powerlevel9k/commit/469ff8dedac026b4ee349e4eccb660abe2023c6b) into p9k has happened over 2 months ago, and it was a simple backport of a fix I implemented in p10k. So it was either reimplementing the theme or not having progress.

**Comment by deepu105** [comment]
Ok, I can understand. All the best man.

**Comment by deepu105** [comment]
Hey @romkatv so I saw [this](https://www.reddit.com/r/zsh/comments/c3osfa/performance_comparison_spaceship_vs_powerlevel10k/) post from you and was interested in configuring powerlevel10k to look like the spaceship theme. But since you said the config there is not recommended, do you have a config that gives a theme that is closest to the spaceship(doesn't have to be exact) but with currently available settings?

**Comment by romkatv** [comment]
@deepu105 I don't have a config that would emulate Spaceship. Depending on what appeals to you in Spaceship you might find Pure Power config to your liking, perhaps with some modifications.

If you want to give it a try, run this command:

```zsh
( cd && curl -fsSLO https://raw.githubusercontent.com/romkatv/dotfiles-public/master/.purepower )
echo 'source ~/.purepower' >>! ~/.zshrc
```

Remove all `POWERLEVEL9K` config options form your `~/.zshrc`. Edit `.purepower` to customize your prompt. Some things that you might want to change:

1. By default this config shows a ruler between prompts. It takes the same amount of space and serve the same function as an empty line -- to better separate different commands from each other. To disable it,  flip `POWERLEVEL9K_SHOW_RULER` to `false`. If you want to have an empty line where ruler used to be, add `POWERLEVEL9K_PROMPT_ADD_NEWLINE=true`.

2. Enable the same directory shortening strategy that you used to have:

```zsh
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_middle
```

3. Uncomment `time` in `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

4. By default Pure Power doesn't use icons where they don't add any information. For example, in your config you have an icon of a clock next to the current time. Since this icon is uninformative (you _know_ that your prompt shows time on the right), Pure Power doesn't have it. If you want to see this icon, set `POWERLEVEL9K_TIME_ICON=$'\uF017'. Similarly for other `POWERLEVEL9K_*_ICON` parameters.

**Comment by deepu105** [comment]
@romkatv thanks, so that is what I end up doing. So I ended up with this 
```
############ POWERLEVEL THEME SETTINGS ##############
POWERLEVEL9K_MODE='awesome-fontconfig'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)

POWERLEVEL9K_DISABLE_RPROMPT=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
POWERLEVEL9K_WHITESPACE_BETWEEN_LEFT_SEGMENTS=

POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(disk_usage time status)

POWERLEVEL9K_DIR_SHOW_WRITABLE=true

POWERLEVEL9K_DIR_HOME_BACKGROUND=none
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=none
POWERLEVEL9K_DIR_ETC_BACKGROUND=none
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=none
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND=none

POWERLEVEL9K_DIR_HOME_FOREGROUND=blue
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=blue
POWERLEVEL9K_DIR_ETC_FOREGROUND=blue
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=blue
POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=red

POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="blue"

POWERLEVEL9K_VCS_GIT_ICON='\uf09b '

POWERLEVEL9K_VCS_CLEAN_BACKGROUND=none
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=none
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=none
POWERLEVEL9K_VCS_LOADING_BACKGROUND=none
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="040"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="red"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
POWERLEVEL9K_VCS_LOADING_FOREGROUND="yellow"

POWERLEVEL9K_VCS_UNTRACKED_ICON=$'%{\b?%}'
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'%{\b!%}'
POWERLEVEL9K_VCS_STAGED_ICON=$'%{\b+%}'

POWERLEVEL9K_DIR_NOT_WRITABLE_VISUAL_IDENTIFIER_COLOR=red
POWERLEVEL9K_LOCK_ICON=$'\uE0A2'

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
# Prompt symbol: '❮' when vicmd keymap is active, '❯` otherwise; red on error, magenta on success.
local p='%F{%(?.green.red)}${${${KEYMAP:-0}:#vicmd}:+❯}${${$((!${#${KEYMAP:-0}:#vicmd})):#0}:+❮}%f '
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%1(l. .)$p"


############ END- POWERLEVEL THEME SETTINGS ##############
```

**Comment by romkatv** [comment]
>  thanks, so that is what I end up doing. So I ended up with this

LGTM :+1: 

Small suggestions below.

> `POWERLEVEL9K_OS_ICON_BACKGROUND="white"`
> `POWERLEVEL9K_OS_ICON_FOREGROUND="blue"`

These two lines have no effect because you aren't using `os` prompt segment. You can remove them.

> `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(disk_usage time status)`

This has no effect due to `POWERLEVEL9K_DISABLE_RPROMPT=true`. You can remove it.

> `POWERLEVEL9K_VCS_LOADING_FOREGROUND="yellow"`

It's much better to use `grey` here. You'll almost never see Git prompt in `LOADING` state but when it happens it's really nice to know that the info isn't up-to-date.

> `# Prompt symbol: '❮' when vicmd keymap is active, '❯` otherwise; red on error, magenta on success.`

Typo: It's green on success.

> POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%1(l. .)$p"

`%1(l. .)` has no effect. You can remove it. Its purpose in `pure10k.zsh` is to insert a whitespace separator when `virtualenv` is active.

**Comment by deepu105** [comment]
Hey thanks, Ya most of those are leftover from my previous setup. Thanks for the tips.
