### ISSUE TITLE
p10k configure doesn't work as shown in README

### ISSUE THREAD

**Issue by shrihanDev** [romkatv/powerlevel10k#901]
I ran `p10k configure` in Cygwin+ZSH+OHMYZSH.
But it doesn't ask for the Prompt Style (Lean, classic or rainbow). It doesn't ask anything about the prompt, except Transient and Instant

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#some-prompt-styles-are-missing-from-the-configuration-wizard
