### ISSUE TITLE
Make the transient prompt customizable

### ISSUE THREAD

**Issue by NickAnderegg** [romkatv/powerlevel10k#902]
Using the [suggestions in this issue](https://github.com/romkatv/powerlevel10k/issues/316#issuecomment-551867287) for adding timestamps before the old prompt char, I was trying to figure out a way to get `POWERLEVEL9K_TRANSIENT_PROMPT=same-dir` to display timestamps before old prompts, but I couldn't figure out how to get it to work. The first saved prompt after a directory change will correctly have the timestamp beside the prompt, but after that, only the prompt character appears.

The closest I could get was this: 
![image](https://user-images.githubusercontent.com/542937/87885508-9fdcde00-c9e4-11ea-94fc-a4ee6ce50eb7.png)

So, now I have a feature request: Make it easy to customize what appears in the transient prompt in the same was `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` can be customized.

**Comment by romkatv** [comment]
> Using the [suggestions in this issue](https://github.com/romkatv/powerlevel10k/issues/316#issuecomment-551867287) for adding timestamps before the old prompt char, I was trying to figure out a way to get `POWERLEVEL9K_TRANSIENT_PROMPT=same-dir` to display timestamps before old prompts, but I couldn't figure out how to get it to work.

I couldn't figure out from this description what you want to achieve. Perhaps this?

```zsh
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon dir vcs newline
  time prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  load time newline
)

typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

function p10k-on-pre-prompt() {
  p10k display '1'=show '2/left/time'=hide
}

function p10k-on-post-prompt() {
  if [[ $PWD == $my_last_dir ]]; then
    p10k display '1'=hide '2/left/time'=show
  else
    my_last_dir=$PWD
  fi
}
```

> So, now I have a feature request: Make it easy to customize what appears in the transient prompt in the same was `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` and `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` can be customized.

It's a legitimate feature request but I'm afraid it would fall too low on my priority list to ever be done. So I'm closing this issue.

**Comment by NickAnderegg** [comment]
> It's a legitimate feature request but I'm afraid it would fall too low on my priority list to ever be done.

I'd be happy to add the feature myself and open a pull request if you could be so kind as to point me to the relevant parts of the code that generate the current transient prompt! I think I have a good idea of how it works, but I might be missing a few functions.

**Comment by romkatv** [comment]
> > It's a legitimate feature request but I'm afraid it would fall too low on my priority list to ever be done.
> 
> @romkatv I'd be happy to add the feature myself

Sure, go ahead. Note that it's incomparably more difficult than configuring transient prompt based on the existing API.

> and open a pull request

Just to be clear: there is no guarantee your PR will be accepted. What I'm writing here is not an encouragement to work on this feature.

> if you could be so kind as to point me to the relevant parts of the code that generate the current transient prompt!

It's in p10k.zsh. Search for "transient" and for "post-prompt".

> I think I have a good idea of how it works, but I might be missing a few functions.

I'm curious. Where have you learned this? I'm fairly sure there is no other project that has this feature (expect maybe in limited form) and likely not a single person apart form myself who knows how it works or how to implement it.

**Comment by NickAnderegg** [comment]
> I'm curious. Where have you learned this? I'm fairly sure there is no other project that has this feature (expect maybe in limited form) and likely not a single person apart form myself who knows how it works or how to implement it.

I was referring to how the prompt is generated in p10k.zsh, specifically. I found the functions that mention "transient" and worked backward to find where those functions were called, etc. but I was still having trouble getting the transient prompt to cooperate. Now that you pointed it out, I realized I should follow the same process for understanding the "post-prompt" function.

In any case, using your suggestion above, I managed to get the transient prompt to behave almost how I want it: 
![image](https://user-images.githubusercontent.com/542937/87984654-4938d800-caa8-11ea-8c65-7158f0e72076.png)

The timestamp is missing on the first prompt in a directory, but that's fine, because the header prompt is also timestamped. It's better than the inverse I was generating before where the first prompt had two timestamps and the rest had none :)

**Comment by romkatv** [comment]
> In any case, using your suggestion above, I managed to get the transient prompt to behave almost how I want it

Why almost? If you can tell me what you want, I’ll tell you how to get it. And post your current config so that I don’t have to reverse engineer it from screenshots.

**Comment by Luxcium** [comment]
@romkatv I am so impressed with how much dedication you put in solving every one problem I feel sad that you are not awarded some sort of medal even if you do not need a medal I need you to have it for my personal satisfaction (I am such a selfish person haha [insert soft irony])...

**Comment by Luxcium** [comment]
@NickAnderegg  I do not see your code I was happy to find the solution and just realized it is only a screen capture
