### ISSUE TITLE
Unable to use custom glyph as OS icon

### ISSUE THREAD

**Issue by k-caps** [romkatv/powerlevel10k#903]
I'm using the nerdfonts, I can use the builtin icons just fine, but my distro's icon is not included. 
I created a glyph and got it added into https://github.com/lukas-w/font-logos, which is what the nerdfonts project uses, and then I tried running the nerdfont patcher to get the new icons merged into my Hack font ttf. It hasn't worked and the nerdfont project haven't replied to my queries, so I'm posting here in the hopes that someone can point me in the right direction - do I even need to be doing all this work on the fonts themselves?   
What steps SHOULD be taken, assuming I have an svg glyph that I would like to use as my left segment os icon?

**Comment by romkatv** [comment]
This question is off topic here.

Nonetheless, what you need to do is install FontForge (it’s free), open hack font ttf in it (you can use a patched font from nerd fonts) and follow https://fontforge.org/docs/tutorial/importexample.html to add a new glyph based on svg.
