### ISSUE TITLE
no context 

### ISSUE THREAD

**Issue by raxou** [romkatv/powerlevel10k#907]
i dont have the option for activate the username in my shell 
![image](https://user-images.githubusercontent.com/40395422/88184365-e293f580-cc32-11ea-865d-010bfe07e546.png)

how to fix the problem?
![image](https://user-images.githubusercontent.com/40395422/88184439-fe979700-cc32-11ea-88b3-2a8d21a33e2c.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#how-do-i-add-username-andor-hostname-to-prompt
