### ISSUE TITLE
Diamond not showing correctly in Cmder with WSL Bridge

### ISSUE THREAD

**Issue by davidgourde** [romkatv/powerlevel10k#908]
In order, I:
1. Installed WSL, made zsh my default shell, installed the Meslo Nerd Font patched for Powerlevel10k as well as p10k (manual), which I configured using the Ubuntu terminal. Everything works fine on the WSL Ubuntu terminal.
2. Downloaded the latest version of Cmder and started it.
3. Configured Cmder to use the recommended fonts, and modified the start task to be `{WSL::bash}`. I changed nothing else. 

The fonts were incorrect, so I launched `p10k configure` again. I only see half of the Diamond.
Is there something I can do? I do not understand why this does not show correctly on Cmdr.

The fonts I installed are: [Meslo Nerd Font patched for Powerlevel10k](https://user-images.githubusercontent.com/8690438/88187976-3851a900-cc05-11ea-9e4d-47f8648a51de.png)

Here is how the Diamond is shown:
![image](https://user-images.githubusercontent.com/8690438/88190279-16a5f100-cc08-11ea-870a-f51948796c99.png)

Here are my Cmdr settings for the fonts (which are the default, with the fonts modified for the Meslo one):
![image](https://user-images.githubusercontent.com/8690438/88187502-9a5dde80-cc04-11ea-98c1-5027f783b31a.png)

If you have any idea, I'd be interested to know.

What I tried:
- Changing every single option in the fonts page of Cmdr (size, anti-aliasing, charset, etc). Nothing worked.
- Reinstalling the fonts and restarting Cmdr. Nothing worked.
- Reinstalling Cmdr to get the default settings. Did not work.

**Comment by romkatv** [comment]
I neither use nor maintain Cmder. I suggest you ask this question someplace where users and/or maintainers of Cmder can be found. Here's your question rephrased:

> When using Cmder with [this font](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf), powerline glyphs get displayed incorrectly. Here's how I'm printing them:
>
> ```bash
> bash -c "echo -e '\\uE0B2\\uE0B0'"
> ```
>
> Here's what I expect the output to look like (this is a screenshot of Windows Terminal using the same font): <screenshot>
>
> Here's what it actually looks like in Cmder: <screenshot>
>
> I've also tried the following fonts, all of which have powerline glyphs, and the behavior with all of them is the same (powerline glyphs get rendered incorrectly in Cmder but correctly in Windows Terminal): <list of fonts>.
>
> Here's are the font settings I'm using: <screenshot>
>
> I've tried all combinations of checkboxes and radioboxes in Cmder > General > Fonts settings page (1536 combinations total). None work.

Naturally, adjust this for accuracy.
