### ISSUE TITLE
Powerline icons/triangles not displaying properly

### ISSUE THREAD

**Issue by pd93** [romkatv/powerlevel10k#91]
I'm trying to use powerlevel10k on a remote Ubuntu 16.04 server via SSH. When using powerlevel9k, everything renders as expected. However, if I change my config to powerlevel10k, the glyphs/triangles stop working.

I have powerline fonts installed on my local machine and have tried replacing `ZSH_THEME` with the manual method described in your README, but to no avail.

Not sure what else to try now.

**Powerlevel9k:**
~/.zshrc: `ZSH_THEME="powerlevel9k/powerlevel9k"`
![image](https://user-images.githubusercontent.com/9294862/59767295-e8820f00-9299-11e9-9fd5-07f87957f573.png)

**Powerlevel10k:**
~/.zshrc: `ZSH_THEME="powerlevel10k/powerlevel10k"`
![image](https://user-images.githubusercontent.com/9294862/59767141-8f19e000-9299-11e9-8ae0-e79d78e5e2c2.png)

**Comment by romkatv** [comment]
Please post your `~/.zshrc`, preferably the whole thing.

**Comment by pd93** [comment]
I hope you understand, but I've had to sanitise this a bit as it's for a work machine, but I have included everything that is ZSH-related. I have also verified that running a `.zshrc` with just the following config results in the same issue.

```
    export ZSH="$HOME/.oh-my-zsh"
    export ZSH_THEME="powerlevel10k/powerlevel10k"
    export plugins=( \
        git \
        docker \
        node \
        npm \
        sudo \
        zsh-autosuggestions \
        zsh-syntax-highlighting \
        z \
    )
    source "$ZSH/oh-my-zsh.sh"
    export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
```

**Comment by romkatv** [comment]
Should be fixed now. Please update and try again.

**Comment by pd93** [comment]
@romkatv Amazing. All working now. Thank you for such a quick fix!

**Comment by romkatv** [comment]
Thanks for verifying and for opening the issue in the first place!
