### ISSUE TITLE
vpn indicator

### ISSUE THREAD

**Issue by raxou** [romkatv/powerlevel10k#911]
i dont have vpn indicator but my vpn connection is active 
how activate this symbole

**Comment by raxou** [comment]
i have uncomment the option

**Comment by romkatv** [comment]
To show a VPN indicator in Powerlevel10k prompt you need to do the following.

1. Open `~/.p10k.zsh` in a text editor.
2. Search for `vpn_ip` and uncomment the first hit.
3. Search for `POWERLEVEL9K_VPN_IP_INTERFACE` and do what the comment above it says.
