### ISSUE TITLE
Configuration wizard doesn't launch

### ISSUE THREAD

**Issue by snakedye** [romkatv/powerlevel10k#916]
I've installed it following the instructions for Arch (I'm o n Manjaro), starting with the font but the wizard doesn't lauch even after I rebooted my laptop.

_Sent from my OnePlus 7 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#configuration-wizard
