### ISSUE TITLE
Recommended way of conditionally enabling prompt elements

### ISSUE THREAD

**Issue by sumanthratna** [romkatv/powerlevel10k#919]
I don't want to set the time prompt element if I'm in a vim terminal. Right now this is what I'm doing to get that functionality:
```zsh
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    ...
    # time                  # current time  # added conditionally
    ...
  )
  if [ -z "$VIMRUNTIME" ]; then
      POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=('time')
  fi
```

This doesn't make me feel too good because if I ever want to add segments after `time`, I'll need to add yet another command after the if-statement to add those segments to the array. Does p10k have any functionality built into its element-checking?

Thanks, by the way. p10k is great.

**Comment by romkatv** [comment]
What you are doing is the way to do. Zsh is a flexible programming language. You should be able to express any logic you want by using native zsh constructs such as `if`.
