### ISSUE TITLE
Weird character !5?5 on my screen.

### ISSUE THREAD

**Issue by lucsm00** [romkatv/powerlevel10k#920]
I already tried different powerline patched fonts. I also tried messing around some with the config files and nothing.

![image (1)](https://user-images.githubusercontent.com/53633131/88940648-6155e780-d25e-11ea-82b3-c2c22f41700b.png)

Someone know what is this and how to fix it?

![Screenshot_4](https://user-images.githubusercontent.com/53633131/88940722-7894d500-d25e-11ea-8c79-57a0d6f0cd89.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean
