### ISSUE TITLE
Branch names show "?1" at the end

### ISSUE THREAD

**Issue by samicodesit** [romkatv/powerlevel10k#922]
![image](https://user-images.githubusercontent.com/55199091/89028838-6170e880-d32d-11ea-9d8d-a662b0f114de.png)

Every branch has its name followed by a string of 2 characters "?1"
so it always looks like this: `/home/app   develop ?1`

It didn't happen until I installed other plugins like fuzzy search and auto suggest though

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/blob/master/README.md#what-do-different-symbols-in-git-status-mean
