### ISSUE TITLE
Why isn't 'same-dir' an option for the transient prompt during set up?

### ISSUE THREAD

**Issue by holmescharles** [romkatv/powerlevel10k#925]
I always have to edit the .p10k.zsh file manually to change transient prompt to `same-dir`. Can't this be an option during the set up wizard?

**Comment by romkatv** [comment]
Feature request acknowledged and rejected.

**Comment by romkatv** [comment]
> Can't this be an option during the set up wizard?

It can be but the attention and time of users going through the wizard is limited. This option is not useful enough to be shown in the wizard.
