### ISSUE TITLE
p10k prompt broken over ssh

### ISSUE THREAD

**Issue by IvanBliminse0101** [romkatv/powerlevel10k#927]
Hello, I have a home server that I need to connect to with ssh, but when I connect the prompt appears to not work? I found a similar problem [here.](https://github.com/romkatv/powerlevel10k/issues/153) But that did not solve my problem, please help.
**Image:**

> ![obfuscated](https://user-images.githubusercontent.com/69111720/89123903-cb72c480-d4ca-11ea-8dab-18f748245717.png)
_Some areas of the image were redacted._

### What it says on the other bug report:

> _The problem is that the locale in your SSH session isn't using utf-8 encoding. If you try to print a non-ascii character with `print '\u2B50'` or `echo $'\u2B50'`, you'll get "`character not in range`" error. It's not affecting just p10k but everything you run in the SSH session. To fix this problem you need to run `locale -a`, pick a locale that has utf8, utf-8 or UTF8 or UTF-8 in its name, and export LANG from your **`~/.zshrc`** or **`~/.zshenv`** with the value set to the chosen locale._
**For example:**
`echo 'export LANG=C.UTF-8' >>! ~/.zshenv`
**Or:**
`echo 'export LANG=en_US.UTF-8' >>! ~/.zshenv`

I tried the above and the locale was set correctly to `en_GB.UTF-8` and the server's locale was set correctly too, yet this issue still occurs?

**Comment by romkatv** [comment]
If you want to use zsh with powerlevel10k on mineos-tkldev, you need to install zsh with powerlevel10k on mineos-tkldev.

The issue you've linked to is unrelated.

**Comment by IvanBliminse0101** [comment]
Oh thanks, I thought it would just work with any ssh server, i'm sorry for my ignorance.
