### ISSUE TITLE
How do i change the os_icon 

### ISSUE THREAD

**Issue by dehayev** [romkatv/powerlevel10k#928]
How do i change the os_icon in p10k  
my shell look like this now

![image](https://user-images.githubusercontent.com/54002119/89321673-12b4ad00-d6a5-11ea-9e0f-6a41be3a5174.png)

but i want to change the penguine logo to something else

**Comment by romkatv** [comment]
Open `~/.p10k.zsh`, search for `POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION`, uncomment it and set its value to anything you like.
