### ISSUE TITLE
Blank first line in tmux

### ISSUE THREAD

**Issue by backdround** [romkatv/powerlevel10k#930]
Hi,

I have blank first line, when set `POWERLEVEL9K_PROMPT_ADD_NEWLINE=true` and start tmux:
![image](https://user-images.githubusercontent.com/17349169/89457284-d26d3180-d76d-11ea-9361-71dde4e40c0b.png)

thanks

**Comment by romkatv** [comment]
Thanks, noted.

**Comment by zzzeyez** [comment]
just a reminder.  i'd also really love if this issue was fixed.  running `clear` places it back at the top

**Comment by romkatv** [comment]
Fixed.
