### ISSUE TITLE
Customizable Color for subsegment separators

### ISSUE THREAD

**Issue by sfosdal** [romkatv/powerlevel10k#931]
I use `·` to separate subsegments.  As it is, these take on the color of the subsegment to the left or right, depending on where they are.

I would like to find a way to always make them the same color

**Comment by sfosdal** [comment]
<img width="892" alt="Screen Shot 2020-08-05 at 2 23 10 PM" src="https://user-images.githubusercontent.com/684453/89465758-7c759b00-d727-11ea-8ef5-da6c61fd96de.png">

**Comment by romkatv** [comment]
Use `%7F ·%f` as separator. Replace 7 with any commit you like.

**Comment by sfosdal** [comment]
nice. thank you so much. obviously I have more to learn about unix colors...

thanks again.
