### ISSUE TITLE
Right prompt elements are not showing

### ISSUE THREAD

**Issue by back-2-95** [romkatv/powerlevel10k#932]
I have macOS Catalina + iTerm2 + oh my zsh and p10k. I made clean configuration with wizard.
Nothing is shown on right from POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS.

Here is the wizard selections:

```
# Wizard options: nerdfont-complete + powerline, small icons, rainbow, unicode,
# round separators, round heads, round tails, 2 lines, solid, no frame, dark-ornaments,
# sparse, few icons, concise, instant_prompt=verbose.
```

**Comment by back-2-95** [comment]
I guess it shows if command takes more than "some" time? As now I saw time took, in my case 11m 44s

**Comment by romkatv** [comment]
This is working as expected. If there is nothing to show, nothing is shown.

You can customize what right prompt shows by editing `.p10k.zsh`.
