### ISSUE TITLE
`p10k configure` not asking for theme

### ISSUE THREAD

**Issue by C-Duv** [romkatv/powerlevel10k#933]
When I run `p10k configure` (on a fresh Debian 10 with ZSH 5.7.1 and Oh My Zsh) the wizard does not prompt me for theme (as it should do per [the documentation](https://github.com/romkatv/powerlevel10k#configuration-wizard))

I get asked the following things:
* Does this look like a diamond (rotated square)?
* Does this look like a lock?
* Does this look like a lock? (second try)
* Character Set (Unicode or ASCII)
* Show current time?
* Prompt Height
* Prompt Spacing
* Prompt Flow
* Enable Transient Prompt?
* Instant Prompt Mode

The generated `.p10k.zsh` file says it's based on `romkatv/powerlevel10k/config/p10k-lean-8colors.zsh` so I guess it's using "lean-8colors" by default

I want to try other themes but can't and don't see the cause of this

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/#some-prompt-styles-are-missing-from-the-configuration-wizard

**Comment by C-Duv** [comment]
Thanks, using other terminal (where `print $terminfo[colors]' prints 256) fixes the issue.

At least, I hope my useless (because answer is in the manual) issue will help others finding it via search engine...
