### ISSUE TITLE
I am having trouble setting up the prompt style.

### ISSUE THREAD

**Issue by PraiseJacob** [romkatv/powerlevel10k#935]
I am using termux on android and when I use ```p10k configure``` It doesn't show the options to select the  prompt style. By default I am getting pure style  but I want the rainbow one. Plz help 

Any kind of help will be appreciated

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k/#some-prompt-styles-are-missing-from-the-configuration-wizard
