### ISSUE TITLE
zsh: command not found: p10k

### ISSUE THREAD

**Issue by CharlesARoy** [romkatv/powerlevel10k#936]
Hello,

I've been trying to install powerlevel10k both manually and with oh-my-zsh and in both cases, I can't seem to run the configuration wizard to get started. After exiting zsh and starting it again, the wizard doesn't start automatically and when I try to run "p10k configure" I get an error which says: 
`zsh: command not found: p10k`

My path looks like:
`/home/croy/lib/cmake_install/bin:/home/croy/lib/bamtools_install/usr/bin:/home/croy/tools/gatk-4.1.8.1:/home/croy/java/jre1.8.0_231/bin:/home/croy/lib/guppy_install/bin:/home/croy/lib/sra_toolkit_install/bin:/home/croy/bin:/usr/local/bin:/opt/mvapich2/intel/ib/bin:/opt/intel/2018.1.163/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/bin:/home/croy/bin:/usr/local/sbin:/usr/sbin:/opt/sdsc/bin:/opt/sdsc/sbin:/opt/ibutils/bin:/opt/pdsh/bin:/opt/rocks/bin:/opt/rocks/sbin`

Most of my zsh themes appear to be found at $ZSH rather than $ZSH_CUSTOM so I tried an install with both:
`git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k`
and 
`git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k`

As far as I can tell, I've successfully updated the font. I also changed the ZSH_THEME accordingly (to: ZSH_THEME="powerlevel10k/powerlevel10k"). I tested the oh-my-zsh installs first and then I tested the manual install. (I did make sure to disable the ZSH_THEME line when I tried to test it manually). 

The OS I'm using is: CentOS Linux release 7.6.1810 (Core). **Note, after some further testing it seems like I can't load any of the oh-my-zsh themes on either the Linux cluster I'm working on or my Mac. I'm coming over from bash so I'm not sure if that could mess with things but given that, it's probably not an issue with powerlevel10k. 

Feel free to close this but if you have any suggestions, they would be appreciated!

**Comment by romkatv** [comment]
Start `zsh` and run this command:

```zsh
() {
  emulate -L zsh -o xtrace -o err_return
  ZDOTDIR=/no/such/dir command zsh -ic '[[ $ZDOTDIR == /no/such/dir ]]'
  command mkdir -p -- ~/zsh-backup
  local rc
  for rc in ~/.zshenv ~/.zprofile ~/.zshrc ~/.zlogin ~/.zlogout ~/.oh-my-zsh; do
    [[ -e $rc ]] || continue
    [[ ! -e ~/zsh-backup/${rc:t} ]] || {
      command rm -rf -- $rc
      continue
    }
    command rm -rf -- ~/zsh-backup/${rc:t}.tmp.$$
    command cp -r -- $rc ~/zsh-backup/${rc:t}.tmp.$$
    command mv -- ~/zsh-backup/${rc:t}.tmp.$$ ~/zsh-backup/${rc:t}
    command rm -rf -- $rc
  done
  command git clone -- https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
  command git clone --depth=1 -- https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  command sed -- 's|robbyrussell|powerlevel10k/powerlevel10k|' ~/.oh-my-zsh/templates/zshrc.zsh-template >~/.zshrc
  ZDOTDIR=~ exec zsh -i
}
```

**Comment by CharlesARoy** [comment]
Beautiful! That fixed everything. Thanks so much for the help!

**Comment by CharlesARoy** [comment]
This may be more of an issue with oh-my-zsh than with powerlevel10k, but it potentially relates to what you posted above and any help is appreciated. 

While running the above code did result in a functioning oh-my-zsh prompt on my mac, when I started trying to further customize the prompt by uncommenting stuff in the `.p10k.zsh` file, another issue became apparent. Despite running `source ~/.p10k.zsh`, my prompt was never updating. Then, after either running `exec zsh` or restarting my shell, oh-my-zsh completely stops working and I can't seem to load it up again unless I run the code you sent me above. 

From reading a number of threads, I've tried the following, none of which have worked:

- Ensuring that zsh is my default shell (i.e. yes I've run chsh -s /bin/zsh and yes echo $SHELL returns "/bin/zsh")
- Checking that my Terminal Preferences are set run the default shell (i.e. Terminal-->Preferences-->Shells open with-->Default login shell)
- Restarting my laptop
- Restarting my shell
- Running exec zsh
- Running source ~/.zshrc
- Running source $ZSH/oh-my-zsh.sh

Any suggestions?

**Comment by romkatv** [comment]
Do you experience the same issue if you use the default theme in ohmyzsh (robbyrussell)?

**Comment by CharlesARoy** [comment]
Ok, so I've finally determined what is killing oh-my-zsh (for all themes). It has something to do with the fact that I put a few .zsh files that contained aliases, variables, and functions in $ZSH_CUSTOM. After running source on them, oh-my-zsh and powerlevel10k would keep running in that session, but as soon as I run `exec zsh` or restart my shell, oh-my-zsh would completely stop working. Not sure why, but that's one thing semi-figured out. 

I also figured out why changes to .p10k.zsh weren't showing up. There was a two-fold issue. First, I didn't realize that you needed to uncomment the settings both in the `# =========================[ Line #1]=========================` section and in the specific section that you want to activate (e.g. `################################[ battery: internal battery ]#################################`).

The second reason is more embarrassing to admit but I'll post it here in case anyone else makes the same mistake. A long time ago I had made an alias for source (e.g. `alias source='source ~/.zshrc'`) such that whenever I thought that I was running source on .p10k.zsh, it wasn't doing what I thought it was.

**Comment by romkatv** [comment]
> First, I didn't realize that you needed to uncomment the settings both in the `# =========================[ Line #1]=========================` section and in the specific section that you want to activate (e.g. `################################[ battery: internal battery ]#################################`).

This is false.

**Comment by CharlesARoy** [comment]
Oh, yep, my bad. You only need to uncomment the section under `# =========================[ Line #1 ]=========================` or `# =========================[ Line #2 ]=========================` at the top of the .p10k.zsh script.

**Comment by efkan** [comment]
On Manjaro, I run only `zsh` command on terminal and it opened `p10k configure` screen. If you encountered this issue, recommend giving it a try.

**Comment by romkatv** [comment]
> On Manjaro, I run only `zsh` command on terminal and it opened `p10k configure` screen. If you encountered this issue, recommend giving it a try.

The issue the OP was having was unrelated. In a nutshell, they redefined `source` builtin command (more precisely, they defined an alias with the same name), which broke parts of Oh My Zsh that use `source`.

**Comment by thearjunmdas** [comment]
Thanks a lot @romkatv. I faced a similar issue in macOS Sequoia 15.3 - https://github.com/romkatv/powerlevel10k/issues/936#issuecomment-670839712 helped solved the issue.
