### ISSUE TITLE
Configuration to show only last dir name does not works

### ISSUE THREAD

**Issue by ExposedCat** [romkatv/powerlevel10k#937]
~/.zshrc:
```
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_SHORTEN_DELIMITER=""
```
~/.p10k.zsh:
```
local anchor_files=()
typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="%1~"
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=1
```
![image](https://user-images.githubusercontent.com/44642024/89730927-cd4d0280-da4b-11ea-8006-2a6e66253950.png)
I want only last folder name

**Comment by ExposedCat** [comment]
Fixed it by changing `~/.oh-my-zsh/custom/themes/powerlevel10k/internal/p10k.zsh`:
```
# local p=${(%):-%~}
local p=${(%):-%1~}
```

**Comment by romkatv** [comment]
For anyone looking at this in the future: open `~/.p10k.zsh`, search for `POWERLEVEL9K_SHORTEN_STRATEGY` and set its value to `truncate_to_last`. Don’t do what the OP has done.

**Comment by ExposedCat** [comment]
> For anyone looking at this in the future: open `~/.p10k.zsh`, search for `POWERLEVEL9K_SHORTEN_STRATEGY` and set its value to `truncate_to_last`. Don’t do what the OP has done.

Thx. I put it into `~/.zshrc`🤦‍♂️
