### ISSUE TITLE
How to ~/.motd without getting instant prompt output warning

### ISSUE THREAD

**Issue by marmalodak** [romkatv/powerlevel10k#938]
I have a `[[ ! -f ~/.motd ]] || source ~/.motd` stanza near the end of my `.zshrc` which has a few `echo` statements in it. After I added this, I started getting an instant prompt warning.

Is there a correct way to execute my script without causing the warning?

**Comment by romkatv** [comment]
Move it to the top of zshrc. See https://github.com/romkatv/powerlevel10k/#how-do-i-enable-instant-prompt.
