### ISSUE TITLE
Feature Request: Number of Files in Current Directory

### ISSUE THREAD

**Issue by CharlesARoy** [romkatv/powerlevel10k#939]
I'm sorry if this is super trivial, but I was wondering how to add a tab to show the number of files in the current directory? I don't mind if this results in a slight lag when entering directories with a lot of files.

**Comment by romkatv** [comment]
Add this to `~/.p10k.zsh`:

```zsh
function prompt_my_file_count() {
  emulate -L zsh -o extended_glob
  local -a mtime
  zstat -A mtime +mtime -- . || return
  typeset -gA my_file_count_cache
  local kv=$my_file_count_cache[$PWD]
  if [[ $kv != $mtime[1]:* ]]; then
    local files=(./*(DN))
    kv=$mtime[1]:$#files
    my_file_count_cache[$PWD]=$kv
  fi
  p10k segment -b black -f white -t ${kv#*:}
}
```

Then put `my_file_count` somewhere within `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` or `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`.

See `p10k help segment` for how to customize the appearance (colors, icon, etc.) of this segment.

**Comment by CharlesARoy** [comment]
Very nice! Worked like a charm. Thank you!
