### ISSUE TITLE
VCS_STATUS_WORKDIR in zsh prompt

### ISSUE THREAD

**Issue by fikovnik** [romkatv/powerlevel10k#94]
First, thanks for a super fast theme! I have switched to powerlevel10k in my zprezto config and it is great, only I'm experiencing a weird issue in git dirs:

```
 ~ > cd ~/.zprezto/modules/prompt/external/powerlevel10k                                                                               
 ~/.zprezto/modules/prompt/external/powerlevel10k > 31fdb679 >
 ~VCS_STATUS_WORKDIR > 31fdb679 >                                                               
 ~VCS_STATUS_WORKDIR > 31fdb679 >  
 ~VCS_STATUS_WORKDIR > 31fdb679 >  exec zsh
 ~/.zprezto/modules/prompt/external/powerlevel10k > 31fdb679 >
 ~VCS_STATUS_WORKDIR > 31fdb679 >  
 ~VCS_STATUS_WORKDIR > 31fdb679 >  
```
Basically, the current directory gets replaced by `VCS_STATUS_WORKDIR` when I press enter (or run any command).

Do you have any ideas what might be wrong?

**Comment by romkatv** [comment]
If you have `AUTO_NAME_DIRS` option set, this is intended behavior. You can add `unsetopt AUTO_NAME_DIRS` to your `.zshrc` to turn it off.

**Comment by fikovnik** [comment]
Thanks a lot!
