### ISSUE TITLE
Emacs Tramp - how?

### ISSUE THREAD

**Issue by voobscout** [romkatv/powerlevel10k#940]
That's the usual way of accomplishing the required deed for emacs tramp-mode:
```zsh
if [ "$TERM" = dumb ]; then
  unsetopt zle prompt_cr prompt_subst
  unset RPS1 RPROMPT  
  PS1='$ '
  PROMPT='$ '
fi
```
However, this has no effect on p10k, neither directly setting those vars, ie:
```zsh
export PS1='$ '
```
Any help/advise is greatly appreciated!

**Comment by romkatv** [comment]
Which installation method have you followed to enable powerlevel10k?

**Comment by voobscout** [comment]
to answer my own question:
```zsh
if [ "$TERM" = dumb ]; then
    unsetopt zle prompt_cr prompt_subst
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='$'
fi
```
Apparently tramp is smart enough to discard escape codes, so supplying the usual ```'$ '``` works just fine and p10k tacks on an element separator for my config, I believe it's the ```POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '```.

May I suggest a feature - do something similar by default, most emacs installs are defaulting to ```'$ '``` anyways and there really aren't many other notable ```DUMB``` terminals out there. This will make it super smooth for emacs users.

Feel free to close the issue at any time, it is solved.

**Comment by romkatv** [comment]
Could you answer my question?

**Comment by voobscout** [comment]
Ofcourse, I used [antibody](https://github.com/getantibody/antibody)
zshrc:
```zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -Uz compinit && autoload -Uz bashcompinit
compinit && bashcompinit

source <(antibody init)
antibody bundle < .config/zsh/bundles.txt
[[ ! -f .config/zsh/.p10k.zsh ]] || source .config/zsh/.p10k.zsh
```
and the corresponding ```romkatv/powerlevel10k``` in my bundles.txt
The initial p10k.zsh was generated with p10k configure, upon the first run.

**Comment by treed** [comment]
What I do for this is put a block very early on that does just what I need for TRAMP to work, and then returns before plugins are loaded:

```
if [[ $TERM == "dumb" ]]; then
  unsetopt zle
  PS1='$ '
  return
fi
```

**Comment by romkatv** [comment]
Generally you load things conditionally like this:

```zsh
if [[ $TERM = dumb ]]; then
  # load dumb stuff
else
  # load smart stuff
fi
# load common stuff
```

Antibody makes this more difficult. If using static loading with antibody, you generate multiple bundles (one for dumb, one for smart) and load the right bundle conditionally on `$TERM`.

**Comment by eike-fokken** [comment]
For future readers having the same problem:
I had the same problem but magically it didn't work for me in the way described here.
I still had to return in the if statement to make sure nothing after it is executed on a dumb terminal.
I'm not sure, the && are neccessary, probably not.

```
if [ "$TERM" = dumb ]; then
    unsetopt zle prompt_cr prompt_subst &&
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='$' &&
    export PS1='$ ' &&
    return
fi
```
