### ISSUE TITLE
Feature Request: Hide previous prompt after command returns

### ISSUE THREAD

**Issue by vinay0410** [romkatv/powerlevel10k#941]
Hi, I recently started using Transient Prompt and it is very helpful. I just had a small feature request about transient prompt.
Let's say I execute `git fetch origin`, now this command may take let say 4-5 minutes sometimes depending on internet speed and size of repo.

Now, for these 4-5 minutes my normal prompt disappears which contains useful information such as time, public ip, ram, etc. So, would it be possible to hide the main prompt after the command returns, instead of after it is executed.

**Comment by romkatv** [comment]
This isn’t possible.
