### ISSUE TITLE
Transient prompt right prompt configuration

### ISSUE THREAD

**Issue by roman-geraskin** [romkatv/powerlevel10k#942]
Hello

Is it possible to implement configuration for a right prompt in transient mode?

It's good to know when and how long command been executing, for example:
```
❯                                                                 at 18:03:15 
❯ sleep 10                                               took 10s at 18:03:16
❯                                                                 at 18:03:26 

/                                                                 at 18:03:28 
❯
```

or at least a timestamp only. I see [this comment](https://github.com/romkatv/powerlevel10k/issues/316#issuecomment-551867287) but it is for left prompt and it makes left screen side slightly overloaded. That's why we use transient prompt btw. On the other side, the right screen side is totally free in transient prompt mode.

Moreover, when we launch a long-running command we totally lose the right prompt for the time of command running. This is slightly confusing.

Thanks!

**Comment by romkatv** [comment]
Yes, it’s possible. Check the link you’ve posted and search through the issues for more examples.

**Comment by roman-geraskin** [comment]
I've achieved timestamps to the right side with this
```
POWERLEVEL9K_TRANSIENT_PROMPT=off
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS+=time
function p10k-on-pre-prompt() {
  # Show empty line if it's the first prompt in the TTY.
  [[ $P9K_TTY == old ]] && p10k display 'empty_line'=show
  # Show the first prompt line.
  p10k display '1|*/left_frame'=show '2/right/time'=hide
}

function p10k-on-post-prompt() {
  # Hide the empty line and the first prompt line.
  p10k display 'empty_line|1|*/left_frame'=hide '2/right/time'=show
}
```

Thanks to [this comment](https://github.com/romkatv/powerlevel10k/issues/316#issuecomment-587925470)
