### ISSUE TITLE
macOS Big Sur Beta Upgrade Error

### ISSUE THREAD

**Issue by ogirginc** [romkatv/powerlevel10k#943]
I can't upgrade to powerlevel10k on macOS Big Sur Beta. Do you need any info/help from me?

```
❯ brew upgrade powerlevel10k

Updating Homebrew...
Warning: You are using macOS 11.0.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this pre-release version.

==> Upgrading 1 outdated package:
romkatv/powerlevel10k/powerlevel10k 1.7.0 -> 1.12.0
==> Upgrading romkatv/powerlevel10k/powerlevel10k 1.7.0 -> 1.12.0
==> Downloading https://github.com/romkatv/powerlevel10k/archive/v1.12.0.tar.gz
Already downloaded: /Users/ogirginc/Library/Caches/Homebrew/downloads/cf06db494382b0bf002143b286b8d885ef74c2b9c91fb02ff34b543a286fefe2--powerlevel10k-1.12.0.tar.gz
Error: Your CLT does not support macOS 11.0.
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.

❯ zsh --version
zsh 5.8 (x86_64-apple-darwin19.3.0)
```

**Comment by romkatv** [comment]
I’ve no idea what this error message means. If brew is broken, try manual installation. See docs.

**Comment by qudarr** [comment]
I'm having a similar issue and cannot install on Mac OS Big Sur Beta.

Oh-my-zsh and other brew installs run fine.

Xcode command line tools are also already installed and run fine.

```
Error: The following formula
  powerlevel10k
cannot be installed as binary package and must be built from source.
Install the Command Line Tools:
  xcode-select --install
```

**Comment by romkatv** [comment]
@qudarr What's the output of `uname -a` ?

**Comment by qudarr** [comment]
uname -a
Darwin Martins-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Fri Aug 28 20:45:30 PDT 2020; root:xnu-7195.40.65.0.2~61/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
@qudarr Thanks. Do you get a warning when running `brew` similar to the one in https://github.com/romkatv/powerlevel10k/issues/943#issue-676992975 ?

**Comment by qudarr** [comment]
@romkatv yes I do, but most issues with other brew apps have been alleviated with the current beta of the Xcode command line tools.

**Comment by romkatv** [comment]
> @romkatv yes I do

Feel free to send a PR. I've no idea what that error message means and I don't have access to Big Sur Beta.

**Comment by qudarr** [comment]
I would love to, but I am not familiar with coding and pull requests. But I would gladly assist you in any way I can.

**Comment by romkatv** [comment]
> I would love to, but I am not familiar with coding and pull requests.

Then you can wait until Big Sur is out of beta. I'm sorry, I don't have the time to provide support for beta products that come with no support of their own.

**Comment by qudarr** [comment]
sure

**Comment by qudarr** [comment]
BTW, install via git-clone works. The brew way doesn't.

**Comment by romkatv** [comment]
> BTW, install via git-clone works. The brew way doesn't.

Thanks for the info.
