### ISSUE TITLE
Strange chars

### ISSUE THREAD

**Issue by Robert969696** [romkatv/powerlevel10k#946]
Hello i am trying to configure powerlevel10k with zhs and finally i got something nevertheless i see strange chars at the end of line, see:

`+4 !5 ?2`

![2](https://user-images.githubusercontent.com/22511932/90033052-51f38700-dcbf-11ea-98b6-16b66156e8bc.png)

Normally i should see as on this picture:

![1](https://user-images.githubusercontent.com/22511932/90033084-5ae45880-dcbf-11ea-8996-cf6ef3ec1a29.png)

How to fix that?

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean
