### ISSUE TITLE
No unstaged changes but prompt shows there are

### ISSUE THREAD

**Issue by passaca** [romkatv/powerlevel10k#95]
Hi,

First of all thank you very much for your effort, the increase in speed is really remarkable and I didn't even notice there was a "problem" until I tried to key-repeat "Enter" to see how laggy powerlevel9k is.

I'm rather new to this so I hope I have not made a stupid mistake or am unaware of something important, but in a directory controlled by Git the prompt shows "three unstaged changes", but `git status` shows me that there are no changes and nothing to commit. Also `git add .` does not change anything about this.

Here is a screenshot, I put a black rectangle over my actual path:

![prompt](https://user-images.githubusercontent.com/50840652/60365988-9ab78600-99c0-11e9-9ced-a0dda40c53d4.png)

Am I missing something or is this a bug?

PS: I reverted to powerlevel9k and checked, and there everything is consistent with the actual status of the Git repo.
Btw: I'm on Mac OS 10.14.5

**Comment by romkatv** [comment]
Thanks for the report. This is likely a bug in `gitstatusd`. I'll need your help debugging it.

Please run the following command in the root directory of the git repo:

```zsh
zsh -dfxic 'GITSTATUS_ENABLE_LOGGING=1 && source ~/powerlevel10k/gitstatus.plugin.zsh && gitstatus_start MY && gitstatus_query MY && cat $GITSTATUS_DAEMON_LOG_MY'
```

You'll probably need to change `~/powerlevel10k` for this command to work. If you are using Oh-My-Zsh, the path is `$ZSH_CUSTOM/themes/powerlevel10k`.

Post the output of the command here. It won't contain anything personal but if you have to censor something, please tell me what you've changed.

Among other things, the output will contain a line that looks like this:

```
[2019-06-28 22:40:23 INFO src/repo.cc:196] Found unstaged file: foo/bar.baz
```

`foo/bar.baz` is a placeholder for a real file path. Is there anything unusual about this file?

Run these commands and post their output here:

```zsh
git ls-files --debug -- foo/bar.baz
stat foo/bar.baz
```

**Comment by passaca** [comment]
Hi, many thanks for your prompt (pun intended) reply.

I will only have access again on Monday to run your commands, but if it is of any good, I have a hunch that it is caused by this kind of files which I know are in the folders of the repository:

[https://superuser.com/questions/298785/icon-file-on-os-x-desktop](url)

So they have the carriage return sequence `0x0D` in their name, which is probably an uncommon thing. Maybe this is causing the problem. But I will run your requested commands on Monday.

**Comment by romkatv** [comment]
A quick experiment with a file named `Icon$'\r'` doesn't result in spurious unstaged changes report.

I'll wait for extra data from you on Monday. It should help with narrowing down the problem.

P.S.

When you get to your workstation, please also check whether defining `GITSTATUS_NUM_THREADS=1` at the top of your `~/.zshrc` makes a difference.

**Comment by passaca** [comment]
I will, thank you very much :)

**Comment by romkatv** [comment]
I've added extra logging to gitstatus to make our remote debugging session more efficient. It's available only in the dev branch for now. When you get a chance, please run the following command and send me its output. You can ignore all the commands I mentioned in earlier comments.

```zsh
() {
  emulate -L zsh && setopt err_return
  local tmp && tmp=$(mktemp -d "${TMPDIR:-/tmp}"/gitstatus.XXXXXXXXXX)
  {
    git clone -b dev https://github.com/romkatv/gitstatus.git $tmp
    local cmd="
      GITSTATUS_LOG_LEVEL=DEBUG
      source ${(q)tmp}/gitstatus.plugin.zsh
      gitstatus_start -u -1 MY
      gitstatus_query MY
      cat \$GITSTATUS_DAEMON_LOG_MY"
    echo '===[ run #1 ]==='
    zsh -dfice "GITSTATUS_NUM_THREADS=1 $cmd"
    echo '===[ run #2 ]==='
    local f && f=("${(@Q)${(@f)$(zsh -dfice $cmd | tee /dev/stderr | grep -o 'Found unstaged file: .*')}#*: }")
    echo '===[ git index ]==='
    git ls-files --debug -- $f
    echo '===[ workdir ]==='
    stat -- $f
  } always {
    rm -rf $tmp
  }
}
```

**Comment by passaca** [comment]
Many thanks, unfortunately I will only be able to do it tomorrow. Sorry for the delay.

**Comment by passaca** [comment]
Hi :)

I did as you requested and sent you an e-mail with the debug output.

**Comment by passaca** [comment]
So the files mentioned as "unstaged" all contain the letter "Ä" or "ä". In the debug output, this letter is written as "A\514952\504948" or "\514851\505252", respectively.

But this is then not found by the "stat" command. So I guess it has something to do with that.

**Comment by romkatv** [comment]
The logs you sent me were very helpful and I was able to reproduce this issue. Running the following code on macOS triggers the bug in gitstatusd:

```zsh
cd /tmp/repo
git init
touch $'a\314\210'
git add $'a\314\210'
```

At this point git index will contain an entry with the name $'\303\244' while the filesystem will still have $'a\314\210'. This confuses gitstatusd. I'm working on a fix.

**Comment by romkatv** [comment]
The bug should now be fixed. Please update powerlevel10k and try again. Let me know whether it works for you.

P.S.

There is one corner case in which strange things happen.

```zsh
function test-rename() {
  emulate -L zsh && setopt err_return no_unset
  mkdir /tmp/repo
  {
    cd /tmp/repo
    git init
    touch $1
    git add $1
    mv $1 $2
    mv $2 $3
    git status
    lg2 status
  } always {
    rm -rf /tmp/repo
  }
}
```

(`lg2` is from [libgit2](https://github.com/libgit2/libgit2/).)

`test-rename a - A` produces expected results. `git status`, `lg2 status` and `gistatusd` are all in agreement:

- staged: `a`
- unstaged: none
- untracked: none

Now, if we replace `a` and `A` with `ä` and `Ä` respectively, things get weird. `test-rename $'\303\244' - $'\303\204'` produces:

- `git status`:
  - staged: `ä`
  - unstaged: none
  - untracked: `Ä`
- `lg2 status`:
  - staged: `ä`
  - unstaged: `ä` (deleted)
  - untracked: `Ä`

`gitstatusd` agrees either with `git status` or with `lg2 status` depending on which codepath it takes.

Since both `git status` and `lg2 status` seem broken in this case, I'm inclined to not do anything about it in `gitstatusd`.

**Comment by passaca** [comment]
Thank you very much for your effort in tracking and fixing this error.

I updated and now everything seems to be fine.

**Comment by romkatv** [comment]
Thanks for the verification and double thanks for reporting this corner case and assisting in debugging it.

FYI, to trigger this bug all of the following were required:

- Must be macOS.
- Must be a file system that decomposes unicode.
- The Git repo must have files with non-ascii symbols in their names.
- The file names must use non-canonical UTF-8 encoding.
