### ISSUE TITLE
Segmentation fault while entering command with specific syntax

### ISSUE THREAD

**Issue by 16NoCo** [romkatv/powerlevel10k#950]
When entering a command that contains `grep` after piping, within a mathematical operation `$((...))`, the shell crashes.

For example, with:
```echo $(($(echo foo | grep bar)))```
I am able to type without issue up to the second-to-last ')', but when typing the last one, the shell crashes _BEFORE_ I even run the command.

This seems to be _related to powerlevel10k specifically_, because when I change the `ZSH_THEME` to something else (I tried pygmalion), I do not have the issue.

The default behaviour is: terminal closes immediately.
So I tried to run `zsh` from a terminal (so that when it exits, I am still in a terminal that can show me an error). Then I can see the error message which is simply 
> segmentation fault (core dumped)  zsh

My only example is with `grep` in this specific 'nesting', but I of course do not know if it could happen in other cases.
Here is what I've tried:
- basically, `$(($([some_valid_command] | grep [something])))` gives segfault;
- without a valid command (could be anything: `sl` gives segfault), without piping, or without some argument to `grep`, the error does not occur;
- when it is not in a mathematical evaluation, it does not occur;
- no need of the `echo` or anything before the mathematical evaluation.

Note that it does not happen all the time, and when it does not happen, it seems to be for the whole shell 'session'. (The only time I got that, was after running another command: `echo connect [bluetooth_MAC_address] | bluetoothctl`, but I tried that again on purpose and I got the segfault…)

Edit: might be useful to tell that I use ohmyzsh (latest version from git master),
that I installed zsh from `apt` on Ubuntu 18.04 (zsh version 5.4.2),
and that I installed powerlevel10k from this repository, last week.

**Comment by romkatv** [comment]
Zsh isn’t supposed to segfault. If it does, file a bug against zsh.

**Comment by 16NoCo** [comment]
Before posting, I've seen an issue where it was not related to powerlevel10k specifically, so I made sure it was specific to this tool.

Why would it happen with powerlevel10k and not with other 'themes'? My guess is that it could be related to the completion (or something like that), for which powerlevel10k has _some_ role to play. Or so I think, since you explain that the way the 'theme' is coded has an influence on the performances (you give the example of 9k vs 10k)… So it does not seem unthinkable to me that powerlevel10k _at least triggers_ the segfault for zsh.

I'm sorry I cannot dive into the code to verify my thinking, because I've never looked at the structure of shells and how to deal with them, and you seem to say that your code is hard to understand for beginners :sweat_smile:

**Comment by romkatv** [comment]
> Why would it happen with powerlevel10k and not with other 'themes'?

I've no idea. As I mentioned above, Zsh is not supposed to segfault with any theme. If it does, it's a bug in Zsh.
