### ISSUE TITLE
why is appear  !2(unstaged changes)

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [romkatv/powerlevel10k#951]
![image](https://user-images.githubusercontent.com/22312092/90357312-2557ba80-e085-11ea-9709-cce3dbe12c06.png)

**Comment by romkatv** [comment]
Please post instructions how to reproduce. Which command do I need to run to see this issue in action on my machine?

**Comment by Mr-jiangzhiguo** [comment]
step:

- 1. `git add .`
- 2. `git commit -am "some desc"`
- 3. `git fetch upstream master`
- 4. `git rebase upstream/master master`

then it appear !2, and after run `git status`, the !2 disappear

**Comment by romkatv** [comment]
I'm getting an error from the first command:

```text
% git add .
fatal: Not a git repository (or any of the parent directories): .git
```

**Comment by Mr-jiangzhiguo** [comment]
Are you install git, and `git init` ?

**Comment by romkatv** [comment]
I have `git` installed. I didn't run `git init` because it's not in your instructions.

**Comment by Mr-jiangzhiguo** [comment]
Maybe it appear in case:

in one project which use git, do some change, and commit, rebase, then it maybe appear !number, 

if I git push above modifies, then rebase, it cannot appear

-

**Comment by romkatv** [comment]
Please post specific instructions. Which commands do I need to execute?

**Comment by Mr-jiangzhiguo** [comment]
I cannot repetition this case, so I close this issues.

**Comment by iwarriorgit** [comment]
It's a [feature](https://github.com/romkatv/powerlevel10k#what-do-different-symbols-in-git-status-mean)...
it shows !2 for two unstaged changes.
