### ISSUE TITLE
Issue when hiding dir

### ISSUE THREAD

**Issue by o0-o** [romkatv/powerlevel10k#952]
I am running into an issue where a long directory path that is shortened causes the line to run over when it is hidden. See screenshot. I used empty printf statements for visual clarity, but it occurs with any command.

<img width="716" alt="Screen Shot 2020-08-17 at 03 24 29" src="https://user-images.githubusercontent.com/17324878/90369133-31b62600-e039-11ea-8216-b934f93d5edc.png">

Relevant portions of my config (happy to post more if needed):

```
 typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    dir                     # current directory
    # =========================[ Line #2 ]=========================
    newline
    prompt_char            # prompt symbol
  )

 typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    time                    # current time
  )

...

typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  function p10k-on-pre-prompt()  {
    p10k display '*/left_frame|1/left/dir'=show
  }

  function p10k-on-post-prompt() {
    p10k display '*/left_frame|1/left/dir'=hide
  }

```

**Comment by romkatv** [comment]
Please attach your complete config.

**Comment by o0-o** [comment]
[p10k.zsh.txt](https://github.com/romkatv/powerlevel10k/files/5085187/p10k.zsh.txt)

**Comment by romkatv** [comment]
Fixed.
