### ISSUE TITLE
How can I rotate glyph/icons?

### ISSUE THREAD

**Issue by rediffusion** [romkatv/powerlevel10k#954]
Aloha! 🙂

 I set icons:

![image](https://user-images.githubusercontent.com/30071027/90452578-2f1a0600-e0f7-11ea-84af-7f05d8c46dab.png)

typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%{%F{050}%}\u250f"
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%F{050}%}\u2517%F{cyan}\uF460%F{073}\uF460%F{109}\uF460%f "

I want to set the same icons for **RIGHT** side too! How can I rotate these icons?

...source [Modified Abyss for VSCode](https://github.com/Powerlevel9k/powerlevel9k/wiki/Show-Off-Your-Config#modified-abyss-for-vscode).

**Comment by romkatv** [comment]
Replace your two lines with this:

```zsh
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%F{50}\u250F%f'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='%F{50}\u2513%f'
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{50}\u2517%F{6}\uF460%F{73}\uF460%F{109}\uF460%f'
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%F{109}\uF47D%F{73}\uF47D%F{6}\uF47D%F{50}\u251B%f'
```
