### ISSUE TITLE
Windows WSL colors settings have no effect on windows system directories

### ISSUE THREAD

**Issue by meirkl** [romkatv/powerlevel10k#955]
When i run `ls -a` in WSL file system the colors work fine. But when i run the command in a directory of Windows file system i get unreadable colors.

![image](https://user-images.githubusercontent.com/19801904/90482108-6f9b7300-e13b-11ea-9571-d75b1889ef23.png)

![image](https://user-images.githubusercontent.com/19801904/90482016-5266a480-e13b-11ea-9a24-91cf260df594.png)

**Comment by romkatv** [comment]
Powerlevel10k doesn't affect the output of `ls` in any way. See https://github.com/romkatv/powerlevel10k/#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect.

The default `ls` colors do indeed look horribly in a filesystem where every file has `777` permissions (such as NTFS). You can make it look nicer by adding the following lines at the bottom of `~/.zshrc`:

```zsh
export LS_COLORS='fi=00:mi=00:mh=00:ln=01;36:or=01;31:di=01;34:ow=04;01;34:st=34:tw=04;34:'
LS_COLORS+='pi=01;33:so=01;33:do=01;33:bd=01;33:cd=01;33:su=01;35:sg=01;35:ca=01;35:ex=01;32'

# This is optional. Try `ls -l` with and without it and see which one you like better.
LS_COLORS+=':no=38;5;248'

zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
```

I also highly recommend adding this:

```zsh
# Replace YourName with your Windows username.
hash -d w=/mnt/c/Users/YourName
```

This will establish a bidirectional mapping between `~w` and `/mnt/c/Users/YourName` which works just like the mapping between `~` and `$HOME`. (`w` is short for Windows Home Directory but you can use any other name.) You can type `cd ~w/Desktop` and it'll just work. Tab completion will work, too (`cd ~w/De<TAB>`). Prompt will look nicer.

**Comment by meirkl** [comment]
Thanks! 
I had the LS_COLORS set but for some unknown reason it didn't work.

I added the lines that you recommended and everything looks great.
