### ISSUE TITLE
Appending "in" before current directory

### ISSUE THREAD

**Issue by Sensanaty** [romkatv/powerlevel10k#957]
I was looking through the `p10k.zsh` file for this option but I couldn't find what I'm looking for specifically.

Is there a way for me to add `in` before my current directory?

![image](https://user-images.githubusercontent.com/24919018/90538999-924f7b00-e17f-11ea-801d-4885c93fef2c.png)

So the end result of the above would look something like

`as sensanaty@sensanaty in [ICON] ~/Code/Projects/vanessa on [ICON] [ICON] master `

**Comment by romkatv** [comment]
Open `~/.p10k.zsh` and find this:

```zsh
# Custom prefix.
# typeset -g POWERLEVEL9K_DIR_PREFIX='%fin '
```

Uncomment the second line.
