### ISSUE TITLE
Wifi segment for Linux disappears

### ISSUE THREAD

**Issue by sys-lectern** [romkatv/powerlevel10k#958]
Willing first time contributor here.

I'm working on a function to create a wifi segment for the prompt on any Linux distro, with zero dependencies using only pre-packaged tools, and not using long-deprecated packages.

It appears to work just fine, with the exception that it disappears from the prompt immediately after I start the terminal, and after looking through docs and issues both here and powerlevel9k's archive, I'm not sure what the problem is.

```
custom_wifi_signal(){
  local strength=$(iw dev wlp3s0 link | grep signal | grep -o "[0-9]+")
  local percent=$(( 100 - $strength ))
  
  p10k segment -b 5 -f 0 -t " $percent"
}

function instant_prompt_custom_wifi_signal(){
  custom_wifi_signal
}
```

**One important note:** "wlps3s0" refers to the wifi radio device, but varies across machines, so writing a script to get this device automatically will be the next step as soon as I can figure this part out. You can get it by using `nmcli c` and looking under the "DEVICE" header.

SPECS: Tested on Alacritty and Konsole in Manjaro Linux. Same issue on both.

**Comment by romkatv** [comment]
See `p10k help segment` for the documentation on writing custom segments. You can also search for `prompt_example` in `~/.p10k.zsh` to see an example.
