### ISSUE TITLE
Change frame characters (╭╰╮╯) to square ones (┌└┐┘)

### ISSUE THREAD

**Issue by pcroland** [romkatv/powerlevel10k#959]
Hi! I think these characters would look much nicer for the frame. Or maybe an option in `p10k configure` would be great.

**Comment by romkatv** [comment]
Go ahead and change them in your `~/.p10k.zsh`. Search for these lines:

```zsh
# Connect left prompt lines with these symbols.
...
# Connect right prompt lines with these symbols.
...
```

**Comment by pcroland** [comment]
Thanks a lot.
