### ISSUE TITLE
[Question] Color darker?

### ISSUE THREAD

**Issue by meav** [romkatv/powerlevel10k#962]
When first run config wizard I remember have option to choose color between light or dark, I choosed Lightest. Now I want to change color to Darkest but when I rerun config wizard by command `p10k configure` or when I uninstall and reinstall, I do not see this option again.

I want to ask:

1. In config wizard have options to choose color ligh or dark?
2. Now, how do I change color to darkest?

Sorry for my bad english and thank you for your great project!

**Comment by romkatv** [comment]
Yes, `p10k configure` has an option for lighter/darker colors. It may or may not be displayed depending on which prompt style you choose. For example, Classic style always presents this option, Lean style shows it only if you choose two-line prompt with a frame or connection, and Pure style never shows lighter/darker option screen. Note that some options can be missing if your system lacks necessary capabilities. See https://github.com/romkatv/powerlevel10k/#some-prompt-styles-are-missing-from-the-configuration-wizard.

**Comment by meav** [comment]
> Yes, `p10k configure` has an option for lighter/darker colors. It may or may not be displayed depending on which prompt style you choose. For example, Classic style always presents this option, Lean style shows it only if you choose two-line prompt with a frame or connection, and Pure style never shows lighter/darker option screen. Note that some options can be missing if your system lacks necessary capabilities. See https://github.com/romkatv/powerlevel10k/#some-prompt-styles-are-missing-from-the-configuration-wizard.

Thank you @romkatv , I see this option if I choose Classic style, but if I choose Rainbow Style, it not appear. Can I use darkest option with Rainbow style?

**Comment by romkatv** [comment]
> Thank you @romkatv , I see this option if I choose Classic style, but if I choose Rainbow Style, it not appear. Can I use darkest option with Rainbow style?

No, there is no such option for Rainbow style, and never was.

**Comment by meav** [comment]
> No, there is no such option for Rainbow style, and never was.

Thank you for your answer!
