### ISSUE TITLE
User name and host name not shown on MSYS and Cygwin

### ISSUE THREAD

**Issue by DDoSolitary** [romkatv/powerlevel10k#963]
Hello, I'm trying this theme on MSYS using the Pure style and it seems that my prompt is missing the \<user\>@\<host\> part.

![image](https://user-images.githubusercontent.com/25856103/90794809-d4bfb600-e33f-11ea-848c-7a7c365b6c89.png)

I also tried on Cygwin and got the same result.

In contrast, it is working as expected WSL

![image](https://user-images.githubusercontent.com/25856103/90795037-26684080-e340-11ea-8dc2-3aa05d6ad8e7.png)

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#how-do-i-add-username-andor-hostname-to-prompt

**Comment by DDoSolitary** [comment]
That doesn't help. As I've already mentioned I'm using the Pure style, which has the context segment by default.

Part of my `.p10k.zsh`:

```zsh
  # Left prompt segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    context                   # user@host
    dir                       # current directory
    vcs                       # git status
    command_execution_time    # previous command duration
    # =========================[ Line #2 ]=========================
    newline                   # \n
    virtualenv                # python virtual environment
    prompt_char               # prompt symbol
  )

  # Right prompt segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    # command_execution_time  # previous command duration
    # virtualenv              # python virtual environment
    # context                 # user@host
    # time                    # current time
    # =========================[ Line #2 ]=========================
    newline                   # \n
  )
```

**Comment by DDoSolitary** [comment]
Oops I didn't notice that it only shows context in special scenarios. Thanks for your patience!
