### ISSUE TITLE
Powerline10k shows unstaged changes but disappear after pressing "enter" a few times.

### ISSUE THREAD

**Issue by normangoh** [romkatv/powerlevel10k#965]
Recently I updated files to change letter casing using git config `core.ignorecase true` command. After that push I starts to notice powerline10k showing unstaged changes while there are none (only for that repo).

The unstaged changes counter disappear after pressing `enter` a few times but it is quite annoying see it appear at the start when I `cd` to the folder.

May I know how to fix this?

**Comment by normangoh** [comment]
I just found out that there is a post on this before. And I fixed it using the solution [here](https://github.com/romkatv/powerlevel10k/issues/127#issuecomment-590782683).

**Comment by romkatv** [comment]
Are you using sparse checkouts? If not, it’s a different issue from the one you linked. If you can provide instructions how to reproduce this problem, I might be able to fix it.
