### ISSUE TITLE
Unable to run a command immediately when using instant prompt 

### ISSUE THREAD

**Issue by xd003** [romkatv/powerlevel10k#966]
I have been using instant prompt since the very start and facing this issue since . I didn't reported because i wasn't sure if this is normal behaviour regarding how instant prompt works. Just wanted to confirm it here

 The thing is when i open the terminal  and immediately run any command ( lets say ```ls``` ) , it kind of gets stuck for 1,2 seconds and then only executes it . This behaviour doesn't happpen if i wait for 2,3 seconds after opening the terminal prior to running any command . i have noticed the prompt kind of blinks/refreshes once on its own , it is only after then any command gets executed  , if we have ran anything before that , it gets stuck until that prompt refresh thing happens . i can send a screen recording too if needed

OS - Arch Linux ARM aarch64
Zsh - v 5.8 
Pk10 is also updated because i cloned the repo just now before testing

If any other info is required , do let me know

**Comment by romkatv** [comment]
This is the expected behavior. Commands can be executed only after full Zsh initialization. _Instant prompt_ gives you prompt instantly and allows you to start typing commands instantly but it cannot magically make Zsh fully initialize instantly.
