### ISSUE TITLE
Arrow on the left hand side of my screen

### ISSUE THREAD

**Issue by rpathak38** [romkatv/powerlevel10k#970]
I'm not too sure what happened, but I just noticed that there's an arrow on the left hand side of my iterm. Is this an issue with the font? If so, how can I fix it?
<img width="1094" alt="Screen Shot 2020-08-21 at 12 39 34 PM" src="https://user-images.githubusercontent.com/68093241/90919084-687a9c00-e3ab-11ea-94c2-fc7c2aae9849.png">

**Comment by shyam-habarakada** [comment]
I just installed iTerm 3.5.2 and am noticing the triangle is back, and it wont go away with the setting turned off. Does anyone else see this and has there been a regression? 🤔

**Comment by rwmitchell** [comment]
It's an iTerm2 feature to indicate shell integration is working.

iTerm2 -> Settings... -> Profiles -> Terminal

near the bottom:
![image](https://github.com/romkatv/powerlevel10k/assets/15944841/8619886c-fde2-48bc-b5e3-ea61f7e7f433)

I'll let you figure out which one it is.

**Comment by rosszurowski** [comment]
I ran into this too. I found this thread via Google, so wanted to share [an answer from Reddit](https://www.reddit.com/r/commandline/comments/10t7yaj/why_do_iterm2_show_this_blue_arrow/):

> Those [arrows] are called "marks." You can hide them via Settings > Profiles > Terminal > Show mark indicators. 

Untoggling this setting removes the marks.
