### ISSUE TITLE
(question) is it possible to remove the secondary enter stroke when using reverse search

### ISSUE THREAD

**Issue by hjobrien** [romkatv/powerlevel10k#974]
Hi, so on bash, when I `ctrl-R` to reverse search, the best match is autofilled as I type, and if it looks right, I just press enter and run that command. on zsh with p10k, the behavior I'm currently experiencing is that when I search, I see a list of matches, which I can select from with `enter` but then to run the command, I have to hit `enter` again. This is pretty minor, but is it possible to simply run the command that I select from the reverse-search list when I select it? Thanks!

**Comment by romkatv** [comment]
This is question is not related to powerlevel10k. See https://github.com/romkatv/powerlevel10k#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect.

**Comment by hjobrien** [comment]
Oh I thanks for that link, I missed that section earlier
