### ISSUE TITLE
(question) Can i load color values from external file?

### ISSUE THREAD

**Issue by shaneyost** [romkatv/powerlevel10k#975]
In the ".p10k.zsh" file there are colors defined (e.g. grey, red, yellow, blue, magenta, etc...). I have a scheme generator that kicks out color values to a file. 

What options are available for me to effectively read in values from a file and set them in the ".p10k.zsh"? It would even be better if I could point ".p10k.zsh" to an external file that had my colors defined.

**Comment by romkatv** [comment]
You can edit `~/.p10k.zsh`. If you want to `source` some other file from it, go ahead.
