### ISSUE TITLE
How to manually install gitstatus for powerlevel10k without internet connection?

### ISSUE THREAD

**Issue by Blindingend** [romkatv/powerlevel10k#976]
My workenviroment is isolated from internet. Every time I start my shell, it starts installing gitstatus automatically, which is pretty annoying. But due to my limited ability, I can't find a way to manually install it(I've tried git clone it to my root directory). It'll be great if you can tell me how to manually install it.

**Comment by romkatv** [comment]
I'm not sure I understand your question but perhaps this script will do what you want?

```zsh
#!/usr/bin/env zsh

git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
zsh -fis <<<'source ~/powerlevel10k/powerlevel10k.zsh-theme'
```

**Comment by Blindingend** [comment]
> I'm not sure I understand your question but perhaps this script will do what you want?
> 
> ```shell
> #!/usr/bin/env zsh
> 
> git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
> zsh -fis <<<'source ~/powerlevel10k/powerlevel10k.zsh-theme'
> ```

Sorry that I don't explain myself clearly. I've already installed powerlevel10k as you described, but everytime I launch my shell, it'll try to fetch gitstatus like picture below. Since my environment is isolated from internet, this action can't complete automatically. I want to know how to avoid it or complete manually.
![image](https://user-images.githubusercontent.com/23724924/91113048-32912c80-e6b7-11ea-8447-abc251cbc49d.png)

**Comment by romkatv** [comment]
Please copy paste the complete command I posted above when you are installing powerlevel10k. As far as I can tell, you’ve skipped the last line.

**Comment by romkatv** [comment]
Just to clarify, the command I posted has two lines. The first lines clones powerlevel10k Git repo to `~/powerlevel10k`. The second line downloads gitstatusd to `~/.cache/gitstatus`. Naturally, both of them require internet access. More specifically, they require access to github.com. Since you've somehow managed to run the first command, I suppose you can also run the second.
