### ISSUE TITLE
Why can't the specified color be modified correctly

### ISSUE THREAD

**Issue by 26chk** [romkatv/powerlevel10k#977]
What should I do
Can't change the color in 
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=#1abc9c
![Screenshot_20200824_142538](https://user-images.githubusercontent.com/61009000/91011079-3caf1e80-e616-11ea-9cb7-10b81c554626.jpg)
![Screenshot_20200824_142513](https://user-images.githubusercontent.com/61009000/91011092-420c6900-e616-11ea-8c27-639b2ef190c1.jpg)

**Comment by romkatv** [comment]
You need to quote.

```zsh
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#1abc9c'
```
