### ISSUE TITLE
Conditionally showing prompt segments based on directory contents

### ISSUE THREAD

**Issue by Jacrys** [romkatv/powerlevel10k#978]
I want only to show the dotnet core version info in folders that contain a .NET project (based on the current directory having specific files or folders).  How would I go about implementing this?

**Comment by romkatv** [comment]
This:

```zsh
POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=true
```

If it doesn't work for you, then this:

```zsh
POWERLEVEL9K_DOTNET_VERSION_SHOW_ON_UPGLOB='*.foo|*.bar'
```

**Comment by Jacrys** [comment]
It turns out, the segment was working the whole time.  I had an .sln file in my root repos directory from an old project. Moved it into a sub-directory and voila! The segment disappeared. Yep, another PEBKAC error 🤦  😄
