### ISSUE TITLE
vpn_ip segment not showing up (Cisco Anyconnect)

### ISSUE THREAD

**Issue by JeffTadashi** [romkatv/powerlevel10k#979]
Hello! I can't get the vpn_ip segment to display on my setup (MacOS Catalina, 10.15.6). To reproduce:

- Installed theme with Oh-My-Zsh
- Ran `p10k configure` for fresh configuration
- Enabled `vpn_ip` segment
- My Mac has some unused tunnels (utun0, utun1), so manually set `typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='utun2'`
- Lock icon or IP does not show up as a segment
- When testing using my non-vpn interface: `typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='en0'`, the lock icon and/or IP does show up correctly 

Also here is my ifconfig for utun2:
```
utun2: flags=80d1<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST> mtu 1390
	inet 172.23.118.242 --> 172.23.118.242 netmask 0xfffffc00 
```

After further testing, it looks like it's working with OpenVPN, but not Cisco Anyconnect. Above is showing utun2 for Cisco Anyconnect. (Both used utun2)

**Comment by romkatv** [comment]
Thanks for the report. Fixed. Please update powerlevel10k and let me know whether it works for you now.

**Comment by JeffTadashi** [comment]
Thanks, much appreciated! This does work now as intended.

Also FYI, when testing with GlobalProtect (Palo Alto VPN), I made the following config change as their interfaces are generally `gpd0`
```
 typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='(gpd|wg|(.*tun))[0-9]*'
```

**Comment by romkatv** [comment]
> Thanks, much appreciated! This does work now as intended.

Thanks for the confirmation and for submitting a superb bug report in the first place.

> Also FYI, when testing with GlobalProtect (Palo Alto VPN), I made the following config change as their interfaces are generally `gpd0`
> 
> ```
>  typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='(gpd|wg|(.*tun))[0-9]*'
> ```

Thanks for the info. I've updated the default value of `POWERLEVEL9K_VPN_IP_INTERFACE`.
