### ISSUE TITLE
prompt_context:2: command not found: prompt_segment

### ISSUE THREAD

**Issue by cosimogonnelli** [romkatv/powerlevel10k#980]
I just installed the theme and I am getting this error:

                                            "prompt_context:2: command not found: prompt_segment"

I tried enabling and disabling instant prompt without success.
I get this error every time I open iTerm

Any suggestions?
Thanks

**Comment by romkatv** [comment]
My guess is that you are trying to load several themes simultaneously. You must load only one theme. If you want to use powerlevel10k, you should not load another theme at the same time.

**Comment by cosimogonnelli** [comment]
thanks for the quick answer! 
I checked my ~/.zshrc file and it seems I am loading one theme.

I was also reading something about it in here: 
https://stackoverflow.com/questions/31848957/zsh-hide-computer-name-in-terminal/31874173#31874173

I commented out the prompt_context in ~/.zshrc file. 
Now everything seems ok, but I am not sure if this will have negative impacts.

**Comment by romkatv** [comment]
If you attach your zshrc, I’ll be able to tell you how to fix it.

**Comment by romkatv** [comment]
> I commented out the prompt_context in ~/.zshrc file.

That function is a part of a theme. You must delete it and all the other parts of that theme.

**Comment by cosimogonnelli** [comment]
This is the file.

[copy of zshrc.txt](https://github.com/romkatv/powerlevel10k/files/5125554/copy.of.zshrc.txt)

**Comment by romkatv** [comment]
The encoding of the uploaded zshrc seems broken but other than that the only offending second theme was prompt_context that you’ve already commented out.

**Comment by cosimogonnelli** [comment]
I see, should I do something about the broken encoding? and how? Otherwise am I good to go?

**Comment by romkatv** [comment]
> I see, should I do something about the broken encoding?

Click the link to the file you’ve uploaded. See the brokenness? I’ve never seen anything like this, with all those backslashes and weird symbols at the beginning. I would suggest trying a different method to upload a file the next time you need to do it.

> Otherwise am I good to go?

Yep.
