### ISSUE TITLE
theme does not display icons and configure command has no option to use icons

### ISSUE THREAD

**Issue by PPHyperion** [romkatv/powerlevel10k#981]
I just installed this theme and the initial setup did not ask me if the icons overlap or if I want to use many icons like it did when I installed it on another computer. I have installed the optional font and also set it in my terminal (alacritty).

I'm currently running zsh 5.8, xfce 4.14 on Arch Linux.

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
