### ISSUE TITLE
Right end of the prompt showing up as black on black

### ISSUE THREAD

**Issue by shikhanshu** [romkatv/powerlevel10k#982]
First time using zsh, oh-my-zsh and powerlevel10k. I noticed that the right side of the prompt looks like its not displaying, but upon selecting the text with mouse, it indeed prints but black on black.

![image](https://user-images.githubusercontent.com/31578/91357855-bf66e380-e7a6-11ea-9639-b82b18278851.png)

![image](https://user-images.githubusercontent.com/31578/91357898-cd1c6900-e7a6-11ea-81d3-88d8b3bb9a58.png)

I did the first time configuration and it was quite intuitive and I don't think I missed anything. I even re-did the configuration using `p10k configure` and changed the theme a bit (replaced rounded corner with sharp) and that made no difference.

What am I doing wrong?

**Comment by romkatv** [comment]
Your terminal defines the actual hues of colors. Your terminal is configured to display color 0 with the same hue as the background. If you set background to the same hue as the color 2 (green), Git status will appear to have no background.

There are several things you can do:

1. Do nothing. Prompt is unambiguous as it is.
2. Open terminal preferences and change the background color or color 0 (black).
3. Open `~/p10k.zsh`, find `POWERLEVEL9K_STATUS_OK_BACKGROUND=0
` and `POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0`, uncomment them and replace 0 with anything else. See the top of the file for a one-liner that should help you pick a color. Note that `status` isn't the only segment that uses background color 0.
4. Run `p10k configure` and choose *Lean* style. This has numerous advantages apart from making you immune to subtle issue like this.
