### ISSUE TITLE
Not all prompt theme's available on Arch linux

### ISSUE THREAD

**Issue by arushgupta2007** [romkatv/powerlevel10k#983]
Hi,
I was trying out zsh, and came across p10k. I liked this and wanted to use it.
I am on arch linux and terminator, and I tried installing manually, using oh-my-zsh, and also from arch linux. but could not get access to all the prompt themes. So I tried installing it on docker (arch linux) and saw that it worked. By that I conclude that I have installed the font's correctly.
![fonts](https://user-images.githubusercontent.com/39236387/91399155-18904f00-e85b-11ea-8596-51c4ec91c8e8.png)
![fonts2](https://user-images.githubusercontent.com/39236387/91399160-19c17c00-e85b-11ea-9f5b-46493db72230.png)
![p10kproblem](https://user-images.githubusercontent.com/39236387/91399162-1a5a1280-e85b-11ea-9e12-cf5538431629.png)

^^^ First (page) of config
But then what am I doing wrong?
Thanks

**Comment by romkatv** [comment]
https://github.com/romkatv/powerlevel10k#some-prompt-styles-are-missing-from-the-configuration-wizard
