### ISSUE TITLE
Unbind vi command mode?

### ISSUE THREAD

**Issue by PopeRigby** [romkatv/powerlevel10k#985]
I don't have vi command mode bound to anything in my .zshrc, and I don't have anything else that could be binding this. When I press `Alt+F`, it brings me into command mode with the `❮` symbol. I would like it if I could disable this.

OS: Arch Linux
p10k version: 1.12.0-3 from AUR

**Comment by romkatv** [comment]
You can enable emacs mode with `bindkey -e` and vi mode with `bindkey -v`. If you don't put either of these in your `~/.zshrc`, zsh will try to guess based on `EDITOR`. If you have `EDITOR` set to `vi` or similar, you'll get vi mode by default.

So the solution is to put `bindkey -e` in `~/.zshrc`.

P.S.

This has nothing to do with powerlevel10k. See [FAQ](https://github.com/romkatv/powerlevel10k/#which-aspects-of-shell-and-terminal-does-powerlevel10k-affect).

**Comment by PopeRigby** [comment]
Thanks for the help. I'll remember to consult the FAQ next time.
