### ISSUE TITLE
Broken fonts in p10k configure (and in shell)

### ISSUE THREAD

**Issue by Ohio2** [romkatv/powerlevel10k#986]
So. I've got Meslo installed and set but the symbols are quite broken. 
![image](https://user-images.githubusercontent.com/61843348/91636600-26cc9f80-ea02-11ea-8c7a-7bf30da3035c.png)

**Comment by romkatv** [comment]
Please run `p10k configure` and post screenshots of the first screens with “Does this look like ...” questions and indicate your answers to them.

**Comment by Ohio2** [comment]
![image](https://user-images.githubusercontent.com/61843348/91636718-24b71080-ea03-11ea-9587-c35b98ffdcd8.png)
![image](https://user-images.githubusercontent.com/61843348/91636727-2c76b500-ea03-11ea-8f16-1c25e6233258.png)
![image](https://user-images.githubusercontent.com/61843348/91636736-34365980-ea03-11ea-820e-2f229bdb6781.png)
![image](https://user-images.githubusercontent.com/61843348/91636743-40221b80-ea03-11ea-8575-fe084535be99.png)

**Comment by romkatv** [comment]
Thanks!

I can see from the screenshots that you are not using the recommended font (MesloLGS NF), so you can fix this problem by installing the recommended font and configuring your terminal to use it **for all characters**.

However, I’m curious, what font is that?

**Comment by Ohio2** [comment]
i actually think that may be meslo. Terminator wich has a set font to Meslo still fails

**Comment by Ohio2** [comment]
oh wait i set it to correct font, it works. but i dunno about alacritty.

**Comment by romkatv** [comment]
> i actually think that may be meslo

100% sure it is not Meslo. Look at “r” for example.

**Comment by Ohio2** [comment]
It may not be, but gosh i need to use alacritty and i need to change fonts in the config file.

**Comment by Ohio2** [comment]
HO boy i configed it.

**Comment by romkatv** [comment]
> HO boy i configed it.

👍
