### ISSUE TITLE
Cannot run p10k configure when .zshrc is not writable?

### ISSUE THREAD

**Issue by Ptival** [romkatv/powerlevel10k#987]
I'm using home-manager to try and set up all of zsh, oh-my-zsh, and powerlevel10k.

However, I find the `p10k` program practical for updating my configuration, but it fails in such a setup:
```
❯ p10k configure
[ERROR] p10k configure: ~/.zshrc is not writable
```

Given I don't intend to overwrite `.zshrc` in the first place, it seems like this check is happening too early.

**Comment by romkatv** [comment]
Fixed.

You were getting this error because your home directory is not writable. Unless you explicitly override the location of `~/.p10k.zsh` with `POWERLEVEL9K_CONFIG_FILE`, `p10k configure` will still fail for you.

**Comment by Ptival** [comment]
Ah, specifically it was probably because I am using home-manager, which symlinks ~/.zshrc into a location in the (not writable) nix store. Thanks for the fix!

Indeed in my use case, I just want to use `p10k configure` to generate the configuration file, and I take care of putting that file in place.
