### ISSUE TITLE
feature: POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD should honor state modifiers

### ISSUE THREAD

**Issue by 1nVitr0** [romkatv/powerlevel10k#988]
At the moment `POWERLEVEL9K_BATTERY_HIDE_ABOVE_THRESHOLD` only applies globally. It would be very nice, if it would honor the battery state. For example a config like this would be tremendously useful:

```
POWERLEVEL9K_BATTERY_DISCONNECTED_HIDE_ABOVE_THRESHOLD=50
POWERLEVEL9K_BATTERY_CHARGING_HIDE_ABOVE_THRESHOLD=0
POWERLEVEL9K_BATTERY_CHARGED_HIDE_ABOVE_THRESHOLD=999
```
I don't care so much about my battery level while charging, but I want to be notified when I need to unplug.

**Comment by 1nVitr0** [comment]
I'm happy to submit a pull request if this is a feature that would be approved

**Comment by romkatv** [comment]
Done.

**Comment by 1nVitr0** [comment]
@romkatv You are awesome!
