### ISSUE TITLE
Can't change anaconda background color

### ISSUE THREAD

**Issue by JPUnD** [romkatv/powerlevel10k#989]
On the Powerlevel9k wiki page, on the [anaconda](https://github.com/Powerlevel9k/powerlevel9k#anaconda) entry, we can see several options for configuration, including `POWERLEVEL9K_ANACONDA_BACKGROUND` however this one doesn't seem to work.

Here's the relevant config:
```
POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=false
POWERLEVEL9K_PYTHON_ICON=''
POWERLEVEL9K_ANACONDA_LEFT_DELIMITER=''
POWERLEVEL9K_ANACONDA_RIGHT_DELIMITER=''
POWERLEVEL9K_ANACONDA_BACKGROUND='196'
POWERLEVEL9K_ANACONDA_FOREGROUND='black'
```

And here's a screenshot of the whole prompt being the relevant part the one in the middle with the python symbol:
![image](https://user-images.githubusercontent.com/41581666/91894595-da958f80-ec8d-11ea-93aa-0cf075a4ed71.png)

If you look at the Powerlevel9k color codes in their wiki - [here](https://github.com/Powerlevel9k/powerlevel9k/wiki/Stylizing-Your-Prompt#segment-color-customization) - you can see that color `196` should be `red1`, which clearly it isn't. Changing the value to something else like `blue` or `black` doesn't make any change.

Everything else works as expected from foreground to symbols and delimiters.

**Comment by romkatv** [comment]
Is there a reason why you aren't using `p10k configure`? Have you tried it?

**Comment by JPUnD** [comment]
Interesting using `p10k configure` and then editing `~/.p10k.zsh` and adding `POWERLEVEL9K_ANACONDA_BACKGROUND` there works as expected, I guess I'll switch over to having my customization over at `~/.p10k.zsh`, it makes more sense anyways.

In order to move this file to say `.config/powerlevel10k` I would just have to replace the line
```
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
```
With
```
[[ ! -f ~/.config/powerlevel10k/p10k.zsh ]] || source ~/.config/powerlevel10k/p10k.zsh
```
In my `.zshrc` right?

Thanks for the help, I'm not sure how that fixed it but it did, I've never bothered to use it because I got my configs from somebody else who had them in the .zshrc aswell.

**Comment by romkatv** [comment]
> In order to move this file to say `.config/powerlevel10k` I would just have to replace the line
> 
> ```
> [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
> ```
> 
> With
> 
> ```
> [[ ! -f ~/.config/powerlevel10k/p10k.zsh ]] || source ~/.config/powerlevel10k/p10k.zsh
> ```
> 
> In my `.zshrc` right?

Correct. You can also `source` unconditionally.

```zsh
source ~/.config/powerlevel10k/p10k.zsh
```

When you need to change something in your prompt, it’s better to read the code and comments in the config rather than p9k docs. While p9k options still work, there are often better ways to achieve the same thing in p10k.

**Comment by JPUnD** [comment]
Alright I'll keep that in mind, thanks for the help.
