### ISSUE TITLE
How to change icons in p10k

### ISSUE THREAD

**Issue by v1nay90** [romkatv/powerlevel10k#990]
Hey I wanna change the folder icon cause i think it looks kinda odd so i want to change it i tried changing it in `icons.zsh` but it did not work. So can you help me change the icon. I changed `FOLDER_ICON                    '\uE818'$s             # `  to `FOLDER_ICON                    '\u0024'$s             # $`

**Comment by romkatv** [comment]
Add this to `~/.p10k.zsh`:

```zsh
typeset -g POWERLEVEL9K_HOME_ICON='$'
typeset -g POWERLEVEL9K_HOME_SUB_ICON='$'
typeset -g POWERLEVEL9K_FOLDER_ICON='$'
```

**Comment by v1nay90** [comment]
Thank you so much man

**Comment by v1nay90** [comment]
but i still have a doubt how to change it to an icon i have it's hex code copied for nerd font "uf74b" so i did 

`  typeset -g POWERLEVEL9K_HOME_ICON \uf74b `
`  typeset -g POWERLEVEL9K_HOME_SUB_ICON= \uf74b `
`  typeset -g POWERLEVEL9K_FOLDER_ICON= \uf74b `

but it did not work any help

**Comment by romkatv** [comment]
```zsh
typeset -g POWERLEVEL9K_HOME_ICON=$'\uf74b'
```

**Comment by glepnir** [comment]
does this works on current version . I want to change the home tilde symbol . but failed.

**Comment by romkatv** [comment]
> does this works on current version.

Yes.

> I want to change the home tilde symbol . but failed.

Open an issue. Describe what you do, what you observe and what you expect.
