### ISSUE TITLE
Icons not showing on p10k configure

### ISSUE THREAD

**Issue by aaaguirrep** [romkatv/powerlevel10k#996]
Hi, I am using MacOs with iterm + zsh + oh-my-zsh and when I want to configure p10k it does not show the icons.

![image](https://user-images.githubusercontent.com/38407321/92345310-45383800-f09f-11ea-8232-db91c16e53af.png)

I have installed the fonts but it doesnt work.
![image](https://user-images.githubusercontent.com/38407321/92345389-84ff1f80-f09f-11ea-80b6-b9bae8ae67c3.png)

**Comment by romkatv** [comment]
Uncheck “Use a different font...” at ether bottom of iTerm preference window.

**Comment by gnzlplcs** [comment]
I have the same issue. I work from Terminal, on WSL for Windows 10.

**Comment by romkatv** [comment]
Install the recommended font: https://github.com/romkatv/powerlevel10k/blob/master/font.md. That should help.

**Comment by gnzlplcs** [comment]
> Install the recommended font: https://github.com/romkatv/powerlevel10k/blob/master/font.md. That should help.

Thanks, @romkatv!

**Comment by bekrozikoff** [comment]
Set font choice to "Fira Code" if icons still not appearing.

**Comment by androchentw** [comment]
Using Nerd font may also help with the issue on macOS

```sh
# install
brew tap homebrew/cask-fonts
brew install --cask font-hack-nerd-font

# setup iTerm2
# iTerm2 > Preferences > Profile > Text > Font > Hack Nerd Font Mono
```

**Comment by alegorosito** [comment]
Excelent! 

I've used Nerd font so I can configure the icons and style with _p10k configure_, then I switch to MesloLGS NF.

Thanks @androchentw

**Comment by sachinsenal0x64** [comment]
> Using Nerd font may also help with the issue on macOS
> 
> ```shell
> # install
> brew tap homebrew/cask-fonts
> brew install --cask font-hack-nerd-font
> 
> # setup iTerm2
> # iTerm2 > Preferences > Profile > Text > Font > Hack Nerd Font Mono
> ```

this work for me in arch linux
