### ISSUE TITLE
What is the recommended MesloLGS custom font?

### ISSUE THREAD

**Issue by psprint** [romkatv/powerlevel10k#997]
I wonder: is the font:
- created/patched by you and distributed separately, or:
- … by you and pushed to the upstream, or:
-  is it a regular Nerd Font patched font?

PS. I'd suggest adding some Xdefaults–based setup-instructions for Xterm and URxvt.

**Comment by romkatv** [comment]
Does this help? https://github.com/romkatv/powerlevel10k#how-was-the-recommended-font-created

**Comment by psprint** [comment]
The following sentence introduces the doubt, IMO: "Finally, extra glyphs have been added to Meslo with scripts forked from Nerd Fonts.". Added by you to make a custom powerline10k font, or added by the Nerd Font project? The part "foked from…" suggests that it's you that forked Nerd Fonts (scripts, at least) and (further) extended the font.

**Comment by romkatv** [comment]
There is a command that you can use to create the font. It’s open source.

**Comment by psprint** [comment]
But did you introduce some new glyphs by yourself? Extra to the default Nerd Font dist?

**Comment by romkatv** [comment]
> The part "foked from…" suggests that it's you that forked Nerd Fonts (scripts, at least) and (further) extended the font.

That’s the intended reading.

**Comment by romkatv** [comment]
> But did you introduce some new glyphs by yourself? Extra to the default Nerd Font dist?

No.

Again, you can see the code. It’s on GitHub. You can easily see my changes there.

**Comment by romkatv** [comment]
Closing as I believe I've answered all questions.
